### ISSUE TITLE
Add analytics tracking to the Court's production environment

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#137]
As a Court, so that we may more easily track user activity, we need to add analytics tracing to the production site. 

## Acceptance Criteria
* Data analytics tracking added to production and staging site

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by vickimcfadden** [comment]
https://digital.gov/guides/dap/add-your-site-dap/, Tim Lowden in TTS can help if we need it.

**Comment by vickimcfadden** [comment]
@kfoley-18F and I also talked about, in addition to Google Analytics through GSA's Digital Analytics Program, to start tracking AWS monitoring.

**Comment by adunkman** [comment]
Be sure we have guidance around what is considered a page view/how it would be reported to DAP.

**Comment by vickimcfadden** [comment]
Digital Analytics Program (DAP)

There is an executive order requiring executive branch agencies to have DAP on their sites, which doesn't apply to the Court, but is probably a best practice the EF-CMS should follow (pg 4) - https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf

Process starts with the Court sending the program an email at dap@support.digitalgov.gov to fill out a registration form.

Guide for getting started with DAP - https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf

Next step: Have Tim Lowden, DAP Program Manager, attend a standup to go over what information would be available from a single page web app.

**Comment by adunkman** [comment]
As shared by Tim, the [Code Capabilities Summary and Reference](https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20DAP%20Code%20Capabilities%20Summary%20and%20Reference.pdf) document covers Virtual Pageview Tracking, which is designed for sending single-page app page view data.

**Comment by JessicaMarine** [comment]
Once the Court determines what metrics are important to capture (https://github.com/ustaxcourt/ef-cms/issues/229), we will need to define those in the story that goes over to Flexion for implementation.
