### ISSUE TITLE
OCR Orders and Opinions

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1431]
We need to re-perform optical character recognition on all of the legacy Order and Opinion documents. We have the go-ahead to perform this endeavor, which will likely incur ~$2k AWS bill. We need to save the association between the documents and the text. When we do this, we should also keep the Docket Number in addition to the Docket Entry ID for ease of reference.

**Tasks**

- [x] Verify that we have all of the proper `eventCodes`: MOP, O, OAD, OAJ, OAL, OAP, OAPF, OAR, OAS, OASL, OAW, OAX, OCA, OD, ODD, ODJ, ODP, ODR, ODS, ODSL, ODW, ODX, OF, OFAB, OFFX, OFWD, OFX, OIP, OJR, OODS, OPFX, OPX, ORAP, OROP, OSC, OSCP, OST, OSUB, SOP, SPOS, SPTO, TCOP
- [x] Find all of the documents belonging to these eventCodes 
  - *NOTE*: we are not currently 100% confident that Elasticsearch has all of these fully indexed in any environment. 
  - *NOTE*: we only need to perform OCR on documents with a `filedAt` before December, 2020. 
- [x] Write a Lambda that
  - takes a `docketNumber` and `docketEntryId`
  - points Textract at the PDF in a bucket (`mig` should have the most up-to-date PDFs)
  - saves outputted information into an easy to lookup place (S3 seems a likely candidate; perhaps a JSON file in the root dir that could be queried with Athena)
- [x] Populate an SQS queue with all of the `docketNumber` and `docketEntryId` combinations
- [x] Test
- [x] Perform OCR
