### ISSUE TITLE
All application content created, edited and approved

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#146]
All content needed in the EF-CMS is created, edited and approved by the court

- [x] How to Create a Case
- [x] How to Merge Files into One PDF
- [x] Browser Compatibility Statement (in FAQ)
- [x] What Documents Can be eFiled?
- [x] Public User Guide #535 
- [x] Petitioner User Guide #533 
- [x] Practitioner User Guide #534 
- [x] Internal User Guide #536

**Comment by adunkman** [comment]
Marked as completed in the [Launch Plan spreadsheet](https://docs.google.com/spreadsheets/d/1cNu1VfP4rIo4PxouMw4G6qTvIZZ5OXIDW6iun30zbk8/edit#gid=582310075) — is there anything more that needs to be done here?

**Comment by JessicaMarine** [comment]
@adunkman This has been done, but I’d like to do one final review of all content before we go live.

**Comment by vickimcfadden** [comment]
Jen Siegel is working on content that will replace Blackstone information.

**Comment by adunkman** [comment]
Remaining work is tracked in #536, and is good enough to 🚢 ! 🎉 🌮 🎉 🌮
