### ISSUE TITLE
Ready plan for Tech Lead OOO

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1477]
## Acceptance Criteria

- [x] Pull Request acceptance (documentation)
- [x] Handling escalated Support Requests (specifying that process, what happens?)
- [x] Application Log Access
  - [x]  Flexion
  - [x] 18F (Mark, Andrew)
- [x] Monitoring of Application Health Alerts / Uptime Alerts
- [ ] Data reports required by the Court (OST, etc.) 👍 
- [x] Identify any requirements for interfacing with the IRS
- [ ] Homework for Candidates

## Tasks

- [x] Get 18F access to Production AWS account - @adunkman has access
- [x] Walkthrough deployment to `test` and then to `staging`
- [ ] Find out what reports are needed by Jessica in the coming weeks
- [x] Get 18F subscribed to Health Alerts
- [ ] Get Tenille access to Statuspage to communicate about system status
- [x] Create Draft PR with documented scripts
- [ ] Update Blue/Green documentation

## Escalated Support Requests

These will be forwarded to Tenille, Jessica, and Chris. They will be gauged for their urgency. Only urgent items will be forwarded to 18F to assist with troubleshooting. They should be limited to investigation only via Application Logs and Datastore checks. Any changes will have to be recommended to Tech Lead upon my return unless deemed absolutely necessary.

### I did not receive electronic service

Try to identify a document on a case they should have received service.

1. Need to ascertain a Docket Number (Tenille/Chris/Jessica can help)
2. Go into DAWSON and find the most recently served document on that case (Tenille/Chris/Jessica can help); need the `docketEntryId`
3. Go into DynamoDB and find the `servedAt` timestamp for that document via:

```
{
  pk: 'case|${docketNumber}',
  sk: 'docket-entry|${docketEntryId}
}
```

4. Go into Kibana and find the request by zooming into that Timestamp
  * Usually one of the following request.urls
    * `/case-documents/:docketNumber/:docketEntryId/serve-court-issued`
    * `/case-documents/:docketNumber/file-and-serve-court-issued-docket-entry`
    * `/case-documents/:docketNumber/paper-filing`
    * `/case-documents/:docketNumber/external-document`
  * Filter for Value by the `requestId.lambda`
  * Observe the "Bulk Email Params" and the "Bulk Email Response" to ensure the Email Address was included in the Params and a confirmation was returned with Status: "Success" and "MessageId"
5. If it was successfully sent, check with the `bounced-service-emails@ustaxcourt.gov` account to see if the Email bounced back as Undeliverable (Rare, but has happened)
  * Getting Tenille access, but Jessica can also reach out to Docket who has access.

## Health alert

In the event of a health alarm that impacts the system, perform the following procedure:

1. Notify the team via #18f-collab
2. Try to assess the severity, is the application impaired?
3. If the system is impaired, post an update to Statuspage.io with any relevant information drafted by Chris and/or Jessica. (NOTE: hopefully we can get Tenille to do this.)

## Glue Jobs

From time to time the team feels that it makes sense to perform a glue job to refresh the information in `mig` or `test`. It is recommended to do this in advance of any final testing of a batch of stories, a significant bugfix, or a bugfix/story that has a Blue/Green Migration.

In order to do this, you need to have an empty DDB table in the environment to which you are sending the Glue Job. You may need to delete a table (east & west) and then re-deploy in order to get an empty DDB table to send information. I usually delete the table that is not the current source or destination table in the `efcms-deploy-{ENV}` table so that the environment can continue to function on the current  table.

Once the table is ready to perform the Glue Job, perform the following steps:

1. Start an aws sync of information from the production bucket to the target environment bucket:

```
aws s3 sync s3://dawson.ustaxcourt.gov-documents-prod-us-east-1 s3://test.ef-cms.ustaxcourt.gov-documents-test-us-east-1
```

2. Log into the Production AWS Console, go into DynamoDB
3. Look in the `efcms-deploy-prod` table to identify the currently live table, whatever matches the `source-table-version` and `destination-table-version` (they should be the same!)
3. Via the AWS Console, go to AWS Glue
3. Click on Jobs
4. Select `mock_emails`
5. Click on Actions
6. Click on Run Job
7. Under "Security configuration, script libraries, and job parameters", ensure you have the correct `--source-table` (the production table) and `--destination-table` (the staging account table)
8. Click Run job, and you can monitor its status. They usually take about 6.5 hours to complete.

Then finally you will need to do a blue/green migration or run your deploy that may have a blue/green migration to index this information and get it working with the application.

**Comment by adunkman** [comment]
What kinds of drills or ride-alongs should we be doing in the coming weeks? It would likely reduce the risk of failure and give us a chance to practice/update guides and checklists.

**Comment by mmarcotte** [comment]
https://github.com/ustaxcourt/ef-cms/issues/1532

**Comment by mmarcotte** [comment]
Items from Flexion:

- PR review for bugs
- PR review for stories
- Batch PR review
- Production merges/deploys
- Reindexing ES data on the court env
- Glue jobs; especially things we don’t know about
- Getting access to certain things for development
- Reproduce, document and troubleshoot bugs
