### ISSUE TITLE
Incorporate Mark's Jupyter Notebook work into project

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#1751]
Mark has a lot of Jupyter notebook work written to explore the data in DAWSON that could be handy to anyone working on the project. Let's figure out a way to share that with the team. 

### TODO

- [ ] @mmarcotte create a private github repo for these
- [ ] @mark-meyer to commit the notebooks into this newly created repo
- [ ] @mark-meyer to demo to @mmarcotte and @ttlenard  🤓

**Comment by mmarcotte** [comment]
Mark has two notebooks he'd like to share. Would be easiest if @mmarcotte made a private github repo for them. Do not want to inadvertently commit results from one of the queries.
