### ISSUE TITLE
Ensure `index` is present on v2 API

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#2535]
As a consumer of the Reconciliation Report, in order to have all of the information I need to process the documents that have been served, I need the API to return the include the index number for docket entries.

Even though it is documented in v2.yml, the `index` attribute is missing from docket entries on the v2 api. We need each docket entry to relay the index number of the document on the case's docket record.

## Tasks

- [ ] Check Reconcilation Report on Test
- [ ] Check Reconcilation Report on IRS Environment 
- [ ] Check Reconcilation Report on IRS Environment with IRS
- [ ] Deploy to production
- [ ] Communicate to IRS
