### ISSUE TITLE
Determine a path forward for ustcadmin@example.com.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#277]
The `ustcadmin@example.com` is created by [`setup-cognito-users.sh`](https://github.com/ustaxcourt/ef-cms/blob/2880b0f3c99299d60dbb1eeb0c71f570bb719510/web-api/setup-cognito-users.sh#L61-L85), which is [only run in some environments](https://github.com/ustaxcourt/ef-cms/blob/2880b0f3c99299d60dbb1eeb0c71f570bb719510/.circleci/config.yml#L539-L546).

This user account is used for machine authentication (related to #227) when: 

- Logging in to [create court users](https://github.com/ustaxcourt/ef-cms/blob/2880b0f3c99299d60dbb1eeb0c71f570bb719510/web-api/setup-court-users.sh#L78) during post-deploy.
- Logging in to [create the IRS user](https://github.com/ustaxcourt/ef-cms/blob/2880b0f3c99299d60dbb1eeb0c71f570bb719510/web-api/setup-irs-user.sh#L38) during post-deploy.
- [Importing practitioners](https://github.com/ustaxcourt/ef-cms/blob/2880b0f3c99299d60dbb1eeb0c71f570bb719510/web-api/bulkImportPractitionerUsers.js#L125-L126).
- (Non-exhaustive list)

Also, permissions seem similar between this account and the migrator account, which may also be in the same boat.

**Comment by adunkman** [comment]
Next steps here — Andrew is scheduling a meeting with Mike to knock this issue into actionable tasks and determine if they sit pre- or post- MVP.

**Comment by adunkman** [comment]
## Usages of the admin account

Migration scripts:

- `bulk-import-practitioner-users.sh` — there’s a new version that Mike needs to add to the repo. It’s currently using the ustcadmin account, but it should be using the migrator account via environment variable as it is part of the migration from Blackstone. We can disable this user after the migration is complete.
- `importHelpers.js` — should use the migrator account via environment variable.

Ongoing user management scripts: 

- `create-cognito-user.sh` — should be deleted. Appears to be unused — setup cognito users bash script is used instead.
- `setup-court-users.sh` — Mike has a python script to accomplish this; this script and the underlaying node script `validateUser.js` can be removed. 
- `setup-irs-user.sh` — Should be treated similarly to the other user management scripts. 

Test environment setup:

- `setup-congito-users.sh` — long-term, this feels like a part of a environment seed step, which should be run once when a non-production environment is stood up. There is likely wider work needed to get a seed step implemented, as it doesn’t currently exist.

---------------------------

## Action plan

To accomplish this now: 

- Make the changes to use the migrator account for the migration scripts above.

Backlog grooming: 

- Backlog work around creating an environment seed step, which can be manually executed against a running EF-CMS environment, to create test users (including an IRS user), and test data. This would enable us to remove it from the deployment steps. 

Acknowledging: 

- Likely no changes to the stop-gap solution for user management scripts, knowing that we’re moving towards adding user management for users with admin roles to the EF-CMS UI which would handle administration for users of all roles, including the IRS Superuser.

**Comment by adunkman** [comment]
Tasks: 

- [x] Backlog work around creating an environment seed step. https://github.com/ustaxcourt/ef-cms/issues/540
- [ ] Delete unused `create-cognito-user.sh`. Delete `setup-court-users.sh` and dependency `validateUser.js` as @mmarcotte has other self-written scripts to accomplish these tasks. 
- [ ] Update `bulk-import-practitioner-users.sh` with updates on @mmarcotte’s machine locally.
- [ ] Update `bulk-import-practitioner-users.sh` and `importHelpers.js` to operate using the `migrator` user, accepting credentials via environment or input variable. 

Given the remaining work, I think this falls into your camp @mmarcotte — a good task to knock out when you have 15 minutes and want to feel accomplished. 😄 

Going to drop this from my TODOs. Give me a shout if I can be helpful again!

**Comment by mmarcotte** [comment]
Created a ticket with AWS support to increase our S3 quota from 100 to 200.

**Comment by mmarcotte** [comment]
Mike to get a meeting on the books with @JessicaMarine to determine the path forward once and for all.

**Comment by adunkman** [comment]
Congrats on closing the issue!! We got you a Cartoon Mike (with personal time and personal funds in accordance with federal gift guidelines) to celebrate!  

![1](https://user-images.githubusercontent.com/14930/117043923-cfdb4080-acdb-11eb-8e93-0762a33fc83c.png)
