### ISSUE TITLE
Application monitoring

### ISSUE THREAD

**Issue by vickimcfadden** [ustaxcourt/ef-cms#317]
As the Court product owner and lead software engineer, I need to understand site performance, so that I know when it is not operating within an acceptable range and can make necessary changes. 

Acceptance criteria:

- [x] Investigate what is available out-of-the-box from AWS CloudWatch(i.e. uptime, ping times, logs being generated, database calls per day, calls across gateways, CPU/Memory load levels, HTTP response codes/error logging, number of failed/successful log-ins)
- [X] Investigate what is available with HoneyBadger. *Decision made not to use in production environments but keep enabled in other environments*
- [X] Determine if there is any necessary work to be done prior to installing AWS monitoring **yes, see below**
- [x] 18F provide a cost estimate to the Court for additional elasticsearch instance **$30.55 / month, see below**
- [x] Terraform configuration @julialeague 
- [x] Ongoing work: Configure Kibana dashboard(s) to track errors, exceptions, and metrics. Approved to proceed. @julialeague 
- [ ] ~18F + Court performs a logging audit (number of log-ins, number of documents QC'd, number of documents signed, number of documents completed, did X Court user view this document, email bounces).~ Mike/Laura/Andrew to kick off Nov 6, tracking progress in https://github.com/ustaxcourt/ef-cms/issues/474.
- [ ] ~Court consider what metrics it wants tracked in Kibana dashboard (i.e. number of log-ins, number of documents QC'd, number of signatures, did X user view this document, etc). @JessicaMarine to talk to Fig & Loretta~ (Moved to https://github.com/ustaxcourt/ef-cms/issues/371)
- [x] Talk with Flexion about elasticsearch at upcoming design meeting, who creates, if 18F creates, does Flexion want a mirror image with terraform? **18F creates and Flexion can ingest data if they want to.**  @mmarcotte to follow up with Flexion
- [x] Add a user story to the Flexion backlog that describes the work to be done, as appropriate. @adunkman @mmarcotte to develop a story for log redaction of security tokens.
- [ ] ~Figure out how to archive information. Elasticsearch will only hold data for 1-2 weeks.~ (Moved to https://github.com/ustaxcourt/ef-cms/issues/413)
- [ ] ~Do not index log items that start with: `REPORT` or `END`~ (Moved to https://github.com/ustaxcourt/ef-cms/issues/474).

Related to #137 and #339.

**Comment by adunkman** [comment]
Pulling in from #233: 

> Notifications are sent when:
>- The application is partially or completely down
>- There are usage patterns which indicate a security breach
>- There is a spike in traffic which may cause unusually high AWS billing
>- Routine processes are not occurring
> - Elasticsearch is overloaded

**Comment by adunkman** [comment]
Pulling in from #236, these metrics should be visible in some kind of dashboard view.

**Comment by adunkman** [comment]
Pulling in from #141, error messages should be monitored.

**Comment by julialeague** [comment]
Currently, I'm working on setting up the Elasticsearch log ingestion instance in the USTC court environment.

Pricing update: I'm starting us out with a t2.small Elasticsearch instance to see how it will perform. I don't have great confidence that we will want to stick with this size ultimately, but it's fine for starting out.

The price for that is laid out below:
![Screen Shot 2020-09-01 at 4 04 36 PM](https://user-images.githubusercontent.com/51330839/91905967-fe94a900-ec6c-11ea-8406-aa262e7f1718.png)
![Screen Shot 2020-09-01 at 4 04 14 PM](https://user-images.githubusercontent.com/51330839/91905965-fe94a900-ec6c-11ea-928e-ef7782267fa1.png)
![Screen Shot 2020-09-01 at 4 02 15 PM](https://user-images.githubusercontent.com/51330839/91905964-fdfc1280-ec6c-11ea-886e-7935c3f5d77e.png)

**Comment by vickimcfadden** [comment]
Configuration of kibana dashboard still in progress. This tool is being used to see what is logged and shouldn't, and vice versa. 

A more informative dashboard for site metrics may come later (#387).

**Comment by julialeague** [comment]
Running list of log subscriptions we would like to be forwarded to Kibana: https://docs.google.com/document/d/11tuQbeYOpywHWCvlGGt-7H-EpyEPEGvvP6eHDSHKeIM/edit?usp=sharing

**Comment by julialeague** [comment]
The configuration for the Elasticsearch Kibana dashboard domain and some initial log subscriptions per the running document above has been merged! https://github.com/ustaxcourt/ef-cms/commit/c3b3c759d73f1444adb86e35be6f8cf3dbde2234

**Comment by vickimcfadden** [comment]
Related to #250.

**Comment by adunkman** [comment]
Andrew to split this up and close.

**Comment by adunkman** [comment]
Updated above checklist with issues tracking all remaining work. Closing!
