### ISSUE TITLE
Court: Ability to see "bounced" service emails

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#393]
As a court user, so that I can tell if a party did not receive their service email, I need the ability to see if any service emails were bounced back to the server as undeliverable.

## Acceptance Criteria
* Court user can see any service emails that were returned/bounced back to the server as undeliverable. 

## Tasks

- [x] Test in exp1
- [x] Merge in #678 
- [x] Verify bounced email `bounced-service-emails@ustaxcourt.gov` in SES
- [x] Specify Environment Variable
- [x] Deploy to Prod

**Comment by vickimcfadden** [comment]
Docket section needs to have access to this bounce service so they can re-serve or make changes to contact info.

**Comment by adunkman** [comment]
Docket needs the ability to monitor bounce-back emails.

**Comment by adunkman** [comment]
Mike has a crude way to see failed email addresses, by parsing S3 email records — but it’s hard to see which email messages themselves bounced.

**Comment by vickimcfadden** [comment]
Can see them in S3 bucket now. How do we want to see emails bounce? What would docket do with this? What data do they need?Kicking the tires: 1) Might be able to set up an email address that a list of individuals can monitor. 2) product design to show email bounce-back within Dawson. etc etc

**Comment by vickimcfadden** [comment]
Have emails bounce to an email address (possibly in MS365).

**Comment by mmarcotte** [comment]
dawson.bounced.email@ustaxcourt.gov

**Comment by mmarcotte** [comment]
Looks like we already have an email account to use: `bounced-service-emails@ustaxcourt.gov` Will be sending email there.

**Comment by mark-meyer** [comment]
SES allows bounced email notifications [to be sent to an SNS topic](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/configure-sns-notifications.html). You can subscribe to SNS topics in many ways, including via email, which will result in bounce notification sending an email like this to whomever is subscribed to the SNS stream:

`
{"notificationType":"Bounce","bounce":{"feedbackId":"0100017667ed692f-b4234b84-f2a9-4e3d-abf3-09635145ddda-000000","bounceType":"Permanent","bounceSubType":"General","bouncedRecipients":[{"emailAddress":"bounce@simulator.amazonses.com","action":"failed","status":"5.1.1","diagnosticCode":"smtp; 550 5.1.1 user unknown"}],"timestamp":"2020-12-15T19:43:00.000Z","remoteMtaIp":"3.218.174.122","reportingMTA":"dsn; a8-200.smtp-out.amazonses.com"},"mail":{"timestamp":"2020-12-15T19:43:00.327Z","source":"noreply@exp1.ef-cms.ustaxcourt.gov","sourceArn":"arn:aws:ses:us-east-1:350455059537:identity/noreply@exp1.ef-cms.ustaxcourt.gov","sourceIp":"72.21.217.107","sendingAccountId":"350455059537","messageId":"0100017667ed66e7-bf83ed15-5de9-40ef-a62f-94702f03bebc-000000","destination":["bounce@simulator.amazonses.com"]}}
`

While not the most user-friendly email, this could provide a quick solution via simple configuration/terraform update. It will require that the person receiving the email understand what it is and what actions need to follow the email.

**Comment by mark-meyer** [comment]
Another option that is primarily a configuration change is to set the `return-path` header on the outgoing notification emails to the address of the court employee who should handle bounces. This is distinct from the `reply-to` header and intended to be used for bounces and other errors. https://docs.aws.amazon.com/ses/latest/DeveloperGuide/send-email-concepts-email-format.html. Unlike the SNS messages, this should allow the original body of the email to be viewed by the recipient of the bounced email.

**Comment by mark-meyer** [comment]
The API call Dawson uses to send email, [`SendBulkTemplatedEmail()`](https://docs.aws.amazon.com/ses/latest/APIReference/API_SendBulkTemplatedEmail.html), accepts a `return-path` arguments. The docs indicate this is likely what we want to use:

> ReturnPath
The email address that bounces and complaints will be forwarded to when feedback forwarding is enabled. If the message cannot be delivered to the recipient, then an error message will be returned from the recipient's ISP; this message will then be forwarded to the email address specified by the ReturnPath parameter. The ReturnPath parameter is never overwritten. This email address must be either individually verified with Amazon SES, or from a domain that has been verified with Amazon SES.
Type: String

**Comment by mmarcotte** [comment]
Thanks to @mark-meyer 🙏  doing all of the hard work in researching a solution, I have tried to put some code behind it. Will test this out tomorrow.

**Comment by adunkman** [comment]
The subscription confirmation email will look something like this: 

![image](https://user-images.githubusercontent.com/14930/102649113-9fcd3f80-4136-11eb-836f-d591698231c8.png)
