### ISSUE TITLE
Elasticsearch Kibana: filter what is indexed

### ISSUE THREAD

**Issue by julialeague** [ustaxcourt/ef-cms#474]
## Acceptance Criteria
- [x] The court defines the logs they want to be indexed to Kibana
- [x] The LogsToElasticsearch_info lambda is adjusted to pass only the desired logs to Elasticsearch Kibana (all logs in JSON)
- [x] The Elasticsearch Kibana dashboard only indexes certain logs that are pertinent for regular monitoring

## Tasks

- [x] Implement Winston logger to allow logging in JSON. https://github.com/ustaxcourt/ef-cms/pull/514
- [x] Remove references to console.log and console.error from code, using applicationContext.logger instead. https://github.com/ustaxcourt/ef-cms/pull/514
- [ ] ~Log in JSON from cognito authorizer.~ Moved to #541.
- [x] Adjust logging pattern in app to use log levels (currently using error and info, we’ll want to switch some info to debug). https://github.com/ustaxcourt/ef-cms/pull/514
- [x] Set log level in production. https://github.com/ustaxcourt/ef-cms/pull/514
- [x] Adjust logger lambda to only send JSON logs to kibana. https://github.com/ustaxcourt/ef-cms/pull/526
- [x] Send the requestId when constructing the logger, so all log messages include the request ID. https://github.com/ustaxcourt/ef-cms/pull/514
- [x] Consider kibana rotation. (Moved to https://github.com/ustaxcourt/ef-cms/issues/413)
- [x] Logs contain environment name (https://github.com/ustaxcourt/ef-cms/pull/523)
- [ ] ~Task out any log changes required for auditing purposes.~ (Moved to https://github.com/ustaxcourt/ef-cms/issues/524)

**Comment by julialeague** [comment]
We're going to try using winstonjs to help define what types of logs will make it to the Kibana instance.

**Comment by adunkman** [comment]
Moved the one remaining task to #541, as it was one of the issues we observed with monitoring and logging yesterday during the load test. No remaining work lives here!
