### ISSUE TITLE
Improve monitoring and logging with lessons learned from load test.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#541]
Creating this issue to track improvements to monitoring and logging from our run of #138: 

- [x] No errors were logged — we suspect an error in the implementation of #502. — #556
- [x] It would have been nice to search and view request headers. — #556
- [x] It was hard to judge how widespread `400` issues may be without a breakdown of HTTP response codes for all API responses. — #556
- [x] Tweak Index Template for logging format changes. #611
- [x] We could not see failed authorization attempts. #572

**Comment by adunkman** [comment]
Pinging @mark-meyer @julialeague @mmarcotte for your contributions to the task list above from things you noticed/noted — feel free to edit! 

I’m dropping this in the "In Progress" column with my name on it as I’m rolling the remaining task from #474 into here as well (since it was something we observed yesterday).

**Comment by mark-meyer** [comment]
@mmarcotte and I were debugging some of the dynamoDB migrations last night. One issue with the current log setup is that we need to be thorough in avoiding uncaught exceptions. The `migration-segments` lambda has places where the lambdas are allowed to fail (by design so the SQS items return to the queue), but since the errors are not caught, there is no explicitly logged json, preventing them from showing up in Kibana. I wonder if there is any way to detect uncaught errors in the logging lambda, or if we just need to be a bit more disciplined in catching and logging errors.

**Comment by adunkman** [comment]
> No errors were logged — we suspect an error in the implementation of #502.

Confirmed that anything passed to `applicationContext.logger.error()` was logged, but the resulting JSON was not very helpful. If there were errors that occurred during our load test that were logged this way, we would have seen log entries with `level: 'error'` but `message: null` — which we didn’t see. However, there are (of course) improvements to be made — #556 implements uncaught exception, uncaught promise rejection logging, and better error formatting (message and call stack now included).

>  - It would have been nice to search and view request headers.
>  - It was hard to judge how widespread 400 issues may be without a breakdown of HTTP response codes for all API responses.

#556 changes how requests are logged, moving them up in the execution stack to the request level. This allows us to ensure that for every request, the outgoing response code, overall response time, and incoming request data are logged. We’ll now be able to see every request which hits the API, even those which do not match routes, and their response codes in the logs.

**Comment by adunkman** [comment]
In meeting with @lauraGgit just now, we determined that we’ll need to index the user email and role for auditing purposes (and, of course, usefulness purposes!). 

Will include in the index tweaks.
