### ISSUE TITLE
Petitioner: Online Petition Start Page: Hello World

### ISSUE THREAD

**Issue by sadlerw** [ustaxcourt/ef-cms#6493]
As a petitioner, so that I can have a url to go to to start my petition, I need a frontend javascript applications framework in place.

## Acceptance criteria:

- [x] framework for the frontend code is in place and committed to github 
- [x] accessing the url as a developer starts the js app (hello world)

## Tasks

- [x] fix jenkins webhook - cody/will
- [x] configure jenkins terraform in management subdir - cody/will
- [x] initial commit of the skeleton frontend application - eric/kris
- [x] get cypress running from jenkins
- [x] connect up sonarqube - cody
- [x] get accounts setup for everyone in jenkins - cody
- [x] get swagger working
- [x] fix urls to match deployed environment - cody
- [x] add in lambda backend test endpoints - will
- [x] configure api gateway logs in cloudwatch - will
- [x] use terraform to setup apigateway to publish CloudWatch log role ARN
- [x] have jenkins run the serverless-api jenkinsfile and the webclient jenkinsfile
- [x] Style Guide
    - [x] Add client router - Eric
    - [x] Create Style Guide Component - Eric
    - [x] Add typography section
    - [x] Add form section - Eric
    - [x] Add colors section
    - [x] Add buttons section
- [x] index.html (eric)
- [x] set correct backend url in jenkins (eric/will/cody)
- [x] get different browsers going in unit tests (chrome and firefox for now)
- [x] find manual workaround for edge and running unit tests (for now)
- [x] investigate browserstack, saucelabs for running tests in different browsers (Eric)
- [x] fix sonar coverage (exclude files etc.) (will)
- [x] create guide for testing pages with voiceover on osx (Kris)
- [x] configure artillery to run a perf test (will)
- [x] jenkins stage for pa11y and cypress (will/cody)
- [x] investigate setting up a cloudwatch alarm for number of hits on a lambda > 1000 in an hour
- [x] add npm audit to build (maybe already in?) decide on how to mark issues as ignored (cody)

## Definition of Done

- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
