### ISSUE TITLE
Petitioner: Identify myself to the eFiling system. (1.1.2)

### ISSUE THREAD

**Issue by sadlerw** [ustaxcourt/ef-cms#6500]
As a Petitioner, in order to file a PDF Petition (and later manage my case), I want to identify myself to the Tax Court system.

## Pre-conditions:
- Petitioner is a user defined in the system.
- Petitioner is at the location (link from USTC Homepage) where they can ID them self to the System to start the process of uploading the required PDFs (Petition form, Request for Place of Trial, and Statement of Taxpayer Identification Number) to initiate a case.

## Acceptance Criteria (Post-conditions):
- The system thinks (versus knows) that Petitioner is the current user.
- Petitioner sees that they are logged in. (USWD)

## Notes

- System does not need to "know" Petitioner is the user in the sense of being authenticated - just be able to identify the user somehow.

## Tasks
- [x] Create a front-end component to display user name - UX Design
- [x] Create route to reach screen (front-end) (eric/will)
- [x] Design Name entry screen - UX Design
- [x] Code Name entry screen (eric/will/kris)
- [x] Create mock auth API (eric/will/kris)
- [x] Review design (Eric/Kris/Natalie/Kristen)

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
