### ISSUE TITLE
Petitioner:  Indicate that I want to file a petition (1.1.3)

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6501]
As a Petitioner, in order to file a Petition online, I want to indicate that I want to file a petition with the court.

## Pre-conditions:
 * Petitioner is logged in.
 * Petitioner is at the location where they can select an option to file a petition.

## Acceptance Criteria (Post-conditions):
* Petitioner is able to start filing a petition.

## Tasks
- [x] Design user interaction for case initiation - UX Design
- [x] Code case initiation user interface

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
