### ISSUE TITLE
Petitioner:  Upload my existing PDF documents (1.1.5)

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6503]
As a Petitioner, in order to file a Petition online, I want to upload my existing PDFs (Petition form, Request for Place of Trial, Statement of Taxpayer Identification Number).

## Pre-conditions:
* Petitioner can see how to begin entering Petition information.
* The Petitioner has the Petition form, Request for Place of Trial, and Statement of Taxpayer Identification Number in PDF format.

## Acceptance Criteria (Post-conditions):
* Petitioner’s PDFs are in the system and the Court can distinguish between the three forms.
* Petitioner gets confirmation of successful upload(s).

## Tasks
- [x] Design interface for upload
- [x] Design success interface
- [x] Create route (Eric/Kris)
- [x] Create document policy action (Eric/Kris)
- [x] Create document id action (Eric/Kris)
- [x] Create S3 bucket upload action (Eric/Kris)
- [x] Upload all 3 files with one click (Eric/Kris)
- [x] Upload all 3 files with one click (Eric/Kris)
- [x] Add success message to home screen (Eric)
- [x] add routing sequence (Eric/Will)
- [x] Show progress indicator (Eric)
- [x] Add checks when files have been chosen (Kris/Cody)
- [x] Create document database (cody/will)
- [x] Create S3 database for documents (cody/will)
- [x] Create migration/serverless configuration for the API (will/cody)
- [x] Create endpoint/Lambda for uploading document and metadata (cody/will)
- [x] Create endpoint for secure upload URL (cody/will)
- [x] Fix custom access logging (will/cody)
- [x] Update "File a Petition" labels (kris)
- [x] keep the green checkmark on the same line with the file name when screen is resized (will/eric)

# Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
