### ISSUE TITLE
Petitioner: view the docket # associated with the Case (1.1.6)

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6504]
As a Petitioner, in order to reference the Petition I filed (and later manage my case), I want to view the docket # associated with the case.

## Pre-conditions:
* Petitioner's personal information (name, address, phone, TIN, etc.) is in the system.
* Petitioner submitted a petition package (transmitted the PDFs) to the Court.

## Acceptance Criteria (Post-conditions):
* The system generates the docket number
* Petitioner can see the docket # associated with the Petition.
* The docket # is formatted as 00101-18.
* The docket number includes the next sequential number from the previous.

## Notes
101 to 99999, last 2 digits are year case created.

## Tasks
- [ ] TBD

 ## Definition of Done
- [ ] acceptance criteria have been met
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [ ] 0 errors reported in manual a11y testing
- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version
