### ISSUE TITLE
Petitioner: Pay Petition Filing Fee (1.2)

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6506]
As a Petitioner, in order to have my petition processed, I want to pay the petition filing fee.

After the PDF upload of my petition is complete and the system responds with a docket #, Petitioner can access Pay.gov, so that they can pay the filing fee and reference the docket # in the Pay.gov system.  A report is sent to the Petition section of the Court that includes the Pay.gov payment filing fee ID and the docket #.  The Petitions clerk will search for the case by Docket # and manually enter the Pay.gov payment filing fee ID into that case. The petitioner will then be able to access the system and see that their payment has been received by the court.
 
## Notes
Does the simplest happy path require a section where the petitions clerk can see all pending payment and completed payments? Design decision. Depends on volume. Most likely, not a lot. 
	
## Pre-conditions:
* Petitioner can view the docket # associated with her petition.
* Petitioner is a defined user in the System
* Petition Clerk is a defined user in the System

## Acceptance Criteria (Post-conditions):
* Petitioner can access Pay.gov through the system
* Petition clerk can search for case by docket #
* Petition clerk can manually enter Pay.gov filing fee ID in the case (filing fee ID is associated to the docket # in the system)
* Petitioner and Petition Clerk can verify payment ID on the case

## Definition of Done
- [ ] acceptance criteria have been met
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version
