### ISSUE TITLE
Petitioner: View caption associated with case.

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6519]
As a Petitioner, to ensure that my information was accurately captured, I want to view the caption associated with the case.

## Pre-Conditions:
 * Petitioner's personal information (name, address, phone, TIN, etc.) is in the system.

## Post-Conditions (Acceptance Criteria):
 * Caption should populate as "[First Name] [Last name], Petitioner v. Commissioner of Internal Revenue Service, Respondent"

## Notes
 * Petitioner's personal information will likely be populated during the account creation phase, so this assumes that this information is already captured by the system.

## Tasks
- [ ] TBD

## Definition of Done
- [ ] acceptance criteria have been met
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present

- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ] 0 errors reported in manual testing
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version
