### ISSUE TITLE
Member of the Public: Public-facing Case Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6522]
As a Member of the Public, to protect the privacy of the parties, only Court-issued documents will be viewable by Members of the Public through the public-facing docket record.

## Pre-Requisite:
* A member of the public (unauthenticated user) has accessed a case

## Acceptance Criteria:
* Only the Docket Record is displayed on the Case Detail page for a Member of the Public and no other case information
* Only Court-issued documents are able to be opened by a Member of the Public from the Docket Record
* Remove all search for logged in petitioner

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes:

* Whole separate elastic search instance for public
* Docket entry should display even though document can't be linked to
* Consider how to handle sealed docs/docket entries -- perhaps change text to "SEALED DOCKET ENTRY"
* Document titles on public docket record should be semi-bold, with the additional docket entry info regular weight
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9fab28c6-5ddc-4ab3-a456-06bbf1280a82)

## Tasks
- [x] 1 Public case detail header (Cody ustaxcourt/ef-cms-flexion#3737)
- [x] 2 Public docket record view (Matt ustaxcourt/ef-cms-flexion#3742, ustaxcourt/ef-cms-flexion#3746)
- [x] 3 Endpoint / entity for public docket record (Cody ustaxcourt/ef-cms-flexion#3743)
- [x] 4 Integrate docket record data with view (Rachael ustaxcourt/ef-cms-flexion#3749)
- [x] 5 change link in header to just plain text (Rachael, Kris ustaxcourt/ef-cms-flexion#3750)
- [x] 6 double check the order is in chronological order (Rachael, Kris ustaxcourt/ef-cms-flexion#3750)
- [x] 7 double check security; verify that a public user can’t figure out the document ID and directly access the petition document (Team mob ustaxcourt/ef-cms-flexion#3752)
- [x] 8 spacing between case caption and docket number needs to be expanded (Rachael, Kris ustaxcourt/ef-cms-flexion#3750)
- [x] 9 bring in the full text of the docket entry (Rachael, Kris ustaxcourt/ef-cms-flexion#3750)
- [x] 10 filter draft documents out of response from api (Team mob ustaxcourt/ef-cms-flexion#3757)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
