### ISSUE TITLE
Petitioner: PII warning

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6526]
As the Clerk of the Court, to ensure that a Petitioner does not inadvertently disclose any PII when they upload a document, I want inform the Petitioner about what PII is and warn them to check their documents and redact before uploading.

Parties, especially unrepresented taxpayers, often submit filings to the Court that include PII (Personal Identification Information).  PII includes SSNs, birth dates, names of minor children, financial account info.  The most common mistake is that Petitioners do not redact this information from the IRS notice they received.  In order to remind Petitioners that this information should be redacted from all filings with the Court, the filer should be reminded each time they try to file a new document. [Note: some language currently included in our Guide to eFiling is below in a comment.  It is intended as a starting point for discussion]

## Pre-Conditions
* Petitioner is trying to upload/file a new document with the Court

## Acceptance Criteria (Post-Conditions)
* Petitioner is informed about what PII they should redact every time they upload a document to the system

## Notes
 * Tax Court Rule 27 provides what PII should be redacted from all documents submitted to the Court
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d245ef86-1ddf-4f48-99fe-2bf132c12d19)

## Tasks
- [x] Design PII messaging
- [x] Develop business use test cases
- [x] Implement view changes

## Definition of Done
- [ ] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
