### ISSUE TITLE
Petitioner: Evidence warning

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6527]
As the Clerk of the Court, in order to prevent Petitioners from filing evidence prematurely, I need the system to inform petitioners when they are uploading documents that evidence is not accepted until the time of trial.

Parties, especially unrepresented taxpayers, often try to send evidence in support of their case to the Court.  Evidence is generally NOT accepted by the Court until the time of trial.  In order to remind Petitioners that evidence should be submitted during their trial and that any evidence submitted before then will be disregarded, the filer should be reminded of this each time they try to file a new document. [Note: The Court currently issues a notice to a party AFTER they improperly submit evidence.  I've included the language of that notice in a comment below.  This language may be helpful in drafting the language for this warning.]

## Pre-Conditions
* Petitioner is trying to upload/file a new document with the Court

## Acceptance Criteria (Post-Conditions)
* Petitioner is informed that they should not submit any evidence to the Court until their trial every time they upload a document to the system.

## Tasks
- [x] Design of the premature evidence messaging and warning
- [x] Develop business use test cases
- [x] Implement view changes

## Definition of Done
- [ ] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
