### ISSUE TITLE
CMS User: View and print case record.

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6528]
As a Party or Court User, in order to see what has transpired in a case, I want to be able to view and print a copy of the docket record.

The docket record is a official record of everything that has happened in a case. A Party or Court User may need to print a copy of the docket record for a variety of reasons.  If someone wishes to print the docket record, a print optimized view should be created that includes the docket number, case caption, party information, as well as the docket record.

## Pre-Conditions:
* A case exists in the system.

## Acceptance Criteria (Post-Conditions):
* Any party or Court user can view and produce a print optimized view of the docket record that includes the docket number, case caption, party information, docket record, and date. [Sample provided below]
* Docket record should print in chronological order (oldest to newest); not on sort
* Print optimized view should be for 8.5x11 paper

## Notes:
* Users may print to paper or to a PDF (via print to PDF)
* The preview of the print-optimized version will be seen via print preview
* The print button should reset the sort order to default
* The public will also need a version of this, but without Petitioner's contact information.  That will be handled in a different story ustaxcourt/ef-cms#6840 .

## Tasks:
- [x] create print stylesheet (#2503 -> ustaxcourt/ef-cms-flexion#2538)
- [x] print styled header (#2503 -> ustaxcourt/ef-cms-flexion#2538)
- [x] print styled party information (#2503 -> ustaxcourt/ef-cms-flexion#2538)
- [x] print styled docket record table (#2503 -> ustaxcourt/ef-cms-flexion#2538)
- [x] add print button to docket record (#2503 -> ustaxcourt/ef-cms-flexion#2538)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
