### ISSUE TITLE
Petitioner: Link to Pay.gov to pay filing fee (1.2)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6531]
As a petitioner, in order to  pay my filing fee, I want to link to pay.gov through the system.

After the case is created and Petitioner has a Docket #, the Petitioner should be directed to Pay.gov to pay their filing fee.

## Pre-conditions:
*Petitioner has a docket #

## Acceptance Criteria (Post-conditions):
*Petitioner can link to pay.gov 
*Include instructions on how to pay (link on current USTC website)

## Notes
USTC Pay.gov webpage: https://pay.gov/public/search/agencyforms?agencyFilters=United+States+Tax+Court&searchCategory=PAYMENT&searchType=AGENCYPAYMENT&agencyId=1392

## Tasks
- [x] Create instruction content (Kristen)
- [x] Design where instructions and link will be placed (Kristen)
- [x] Implement on the front-end (will)

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
