### ISSUE TITLE
Petitions Clerk: Send petition package to IRS. (1.4)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6539]
As a Petitions Clerk, in order notify the IRS of the case filing, I need to send the Petition package to the IRS.

In order for the IRS to know that a case has been filed in the Court, the Petitions clerk transmits/sends the petition package (copy of Petition, Request for place of trial, STIN) to the IRS, who then internally routes the package to the appropriate IRS office and IRS attorney who will be working the case.
	
## Pre-conditions:
* Petition package has been saved in system.
* Petition package is associated with Docket #.
* Petition package is sent to the IRS immediately
* The Petition package is error-free (all 3 documents have been uploaded by Petitioner)

## Acceptance Criteria (Post-conditions):
* Petitions Clerk can transmit the petition package to the IRS successfully once reviewed
* Petitions Clerk can verify the case has been forwarded to the IRS
* Petitions Clerk name, Date and time of service/transmission is captured as metadata in the "Audit Log"
* Date and time of service/transmission is viewable in the "Docket Record"
* Is removed from the Petitions Clerk Work Queue
* Case status is changed to General Docket

## Notes:
* The actual transmission function will be a later story and we may need to be coordinated with IRS IT to figure out how this needs to be accomplished.

## Tasks
- [x] Design how clerk indicates send and success message (Sarah)
- [x] Create mock IRS API (will/cody)
- [x] Persistence layer method to talk to mock IRS API (will/cody)
- [x] Create use case to call the Persistence layer (will/cody)
- [x] Create use case proxy for the front-end to hit (will/cody)
- [x] Create Lambda to call the use case (will/cody)
- [x] Create a sequence that will be called by the UI (will/cody)
- [x] Code the screen and success message (will/cody)
- [x] implement changes in design views  - see below (eric)
- [x] review application view (everyone)
- [x] change case status general to general docket and set font to 14px bold (will)
- [x] change format of served status in success alert to match the docket record (12/11/18 9:50 AM) (will)
- [x] add time to docket status after send (will)
- [x] hide sendtoirs button after sent the first time
- [x] Change font of general docket button so the padding issue goes away. Talk to Natalie if you have questions.
- [x] Ensure anchor back up to top with success message works. 
- [ ] move payment expando above the tabs

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
