### ISSUE TITLE
IRS Attorney: File Answer (1.5)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6540]
As an IRS Attorney, in order to comply with Court rules and have the case proceed, I need to file an Answer. 

By Court rule, the IRS must file an Answer within 60 days of receiving a Petition.  When the IRS Attorney is ready to file an Answer, they access the system, search for case by Docket #, and then upload the Answer. 

## Pre-conditions:
* IRS Attorney is defined user in the system.
* IRS Attorney can access the system.
* IRS Answer is saved as PDF.
* IRS Attorney knows the docket # of the case.
* IRS Attorney can search for the case by docket #.
	
## Acceptance Criteria (Post-conditions):
* The system knows that the user is an IRS Attorney.
* The IRS Attorney information (all information) assigned to the case can viewed by all parties and internal court users
* Answer is saved in the system.
* Answer is associated with the correct case (Docket #).
* The date of filing the Answer is captured as metadata
* IRS Attorney and Petitioner can view a record (the PDF) of the filing in the system in the correct case.
* Case (docket #) is now associated with that IRS Attorney and appears on the IRS Attorney Dashboard

## Tasks
- [x] Design the Upload Screen, and IRS Attorney Dashboard (design team)
- [x] Create IRS Attorney Dashboard View (Kris, Eric)
- [x] Create IRS Attorney Case Detail / Document Upload View (Eric)
- [x] Create IRS Attorney user (Name and Tax Court Bar Number)
- [x] Add drop-down for answer document
- [x] Create sequence for upload
- [x] create use case and use case proxy (cody/will)
- [x] Create Lambda (will/cody)
- [x] refactor case to use document entities (will)
- [x] add irs attorney (respondent) info to design of views (kristin)
- [x] add irs attorney (respondent) info to database/backend (cody)
- [x] modify view to show petitioner and respondent info per design and integrate with backend (will)
- [x] add new specs (eric)
- [x] design tweaks (eric)
- [x] add bar number on respondent info (will)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
