### ISSUE TITLE
IRS Attorney: Submit Stipulated Decision (1.6)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6541]
As an IRS Attorney, in order to settle a case, I want to submit a Stipulated Decision.

After the Answer is filed and the case is “at issue”, the IRS Attorney and Petitioner have settlement discussions without the Court’s involvement.  Before Petitioner’s trial is scheduled, Petitioner convinces the IRS that the deductions she claimed are correct. Petitioner and the IRS Attorney agree to a written settlement (Stipulated Decision) and both sign it.  The IRS Attorney then submits a PDF of the Stipulated Decision to the Court capturing the relevant details of the settlement.

## Pre-conditions:
* IRS Attorney is logged into the system.
* Stipulated Decision signed by both parties is saved as PDF.
* IRS Attorney knows the docket # of the case.
* IRS Attorney has filed an Answer (not always required).
* IRS Attorney can search for the case by docket # (or is on attorney’s case list).

## Acceptance Criteria (Post-conditions):
* The system knows that the user is an IRS Attorney.
* Stipulated Decision is saved in the system.
* Stipulated Decision is associated with the correct case (Docket #).
* IRS Attorney and Petitioner can view a record of the filing (PDF) in the system in the correct case.

## Tasks
- [x] Create Upload view(Same as ustaxcourt/ef-cms#6540 ) (cody)
- [x] create a work queue record after submit (cody)
- [x] discuss current code with team and try to "clean" up if possible (cody / will)
- [x] fix filedBy to show Respondent for irs and Petitioner <name> for petitioner (will)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
