### ISSUE TITLE
Docket Clerk: Forward Stipulated Decision (1.7)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6542]
As a Docket Clerk, in order to close a case, I want to review the Stipulated Decision.

Once the IRS Attorney submits the Stipulated Decision, it is received by a Docket Clerk.  The Docket Clerk reviews the Stipulated Decision for obvious errors (checks to make sure the Stipulated Decision was submitted in the right case, signed by both sides, etc.).  The Docket Clerk then forwards the Stipulated Decision to Senior Attorney for further action.
 	
## Pre-conditions:
* Work queue item has been created and has been assigned to specific docket clerk
* A Stipulated Decision is saved in the system.
* Docket Clerk is logged into the system.
* The Sr. Attorney that will receive the forward must already exist in the system

## Acceptance Criteria:
* Docket clerk can see within the system that Stipulated Decision is ready to view. (Work queue - keep it simple until we have more user research for design)
* Docket clerk can view the Stipulated Decision.
* Docket clerk can forward the Stipulated Decision to a Sr. Attorney (or any other court user) for further action with a message to the Sr. Attorney
* Docket clerk gets success message that document was forwarded
* Sr. Attorney can see within the system (work queue) that Stipulated Decision is ready to view, along with the name of the person who sent it to them.
* Work queue item has been created and has been assigned to specific docket clerk (temporary by-pass; docket section will get added in future)

## Notes
* Received date in work queue is the date the clerk receives the work item in their queue.
* Breadcrumb will mimic the back button.
Notes from 12/20 design meeting:
* Blue bar indicates that box is scrollable
* Regarding the flow. Jessica felt Natalie's summary was spot on. It's closer to "B," the messaging board approach
* "Topic" - There isn't one. Threads don't have subject lines.
* User can only reply to the most recent message that's open
*How do you know when a thread is complete? User clicks "complete"

## Test Scenarios
- [x] as a respondent, after I upload a stipulated decision to a case, a work item shall be made for the docketclerk user which is associated with that uploaded document, AND the work item shall appear on the docketclerks work queue
- [x] as a docketclerk, I shall be able to click on the document that work item is associated with from my work queue and be redirected to the view document page
- [x] as a docketclerk, on the view document page, I shall be able to see the latest message of the work item attached to the document.
- [x] as a docketclerk, on the view documents page, I shall be able to forward a work item to another user (seniorattorney) and attach a new message to the work item, AND my work item should be removed from dockerclerk's work queue, AND the work item shall show up in the seniorattorney work queue

## Tasks
- [x] Design Docket Clerk Work Queue (Kristen/Sarah)
- [x] Design Document Detail view (Kristen/Sarah)
- [x] Design messaging/forwarding Work Queue-to-Work Queue (Kristen/Sarah)
- [x] Create senior Attorney user (Kris)
- [x] create docketclerk user (Kris)
- [x] implement docketclerk work queue dashboard (same for sr attorney) (Kris)
- [x] getWorkItem(s)/update sequence and action in cerebral (will)
- [x] update work queue item sequence
- [x] submit work queue item sequence
- [x] test get all / get one / update work item sequences (Cody)
- [x] move work queue sequence to dashboard sequence (Cody)
- [x] add dynamic data to new dashboard work queues (Kris)
- [x] getWorkItems GET PUT GET with id lambda (will - pr)
- [x] getWorkItems interactor (returns workitems assigned to user either docketclerk or srattny) (will - pr)
- [x] getWorkItems(userId) persistence method (Cody & Will)
- [x] saveWorkItems in persistence method (Cody & Will)
- [x] Design the Sr. Attorney dashboard/Work Queue (Kristen/Sarah)
- [x] implement work item view (with forward button) (Eric)
- [x] revisit tests for work item flow (confirm necessary tests) (Eric & Cody, UX Designers)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] usability has been validated
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
