### ISSUE TITLE
Senior Attorney: Sign Stipulated Decision (1.8)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6543]
As a Senior Attorney, in order to close a case, I want to sign the proposed Stipulated Decision submitted by the parties.

When a proposed Stipulated Decision is submitted to the Court by the parties, the document is routed to the Docket Section.  After reviewing the [Stipulated Decision](https://www.ustaxcourt.gov/taxpayer_info_glossary.htm#STIPULATED_DECISION), the Docket Clerk notifies a Senior Attorney that the Stipulated Decision is ready for final review and signature.  The Senior Attorney reviews the Stipulated Decision and, if everything is okay, needs to apply the signature of the Chief Judge.  After the Stipulated Decision is signed, it is sent back to the Docket Clerk for final processing.  The Docket Clerk creates a new docket entry for the *signed* Stipulated Decision.  The signed Stipulated Decision is viewable by all CMS users (members of the public, parties, internal court users).

## Test Scenarios:
https://docs.google.com/document/d/159FznIwhcWJlk2LYjI9yCDfASwCDgDZT6XFE5ZeV0U4/edit?usp=sharing 

## Pre-conditions:
* A proposed Stipulated Decision has been filed by the parties and has been manually routed to a Senior Attorney for review/signature -- shows up in Senior Attorney's individual and section work queue.
	
## Acceptance Criteria (Post-conditions):
* Senior Attorney can apply an electronic signature of the Chief Judge anywhere on the proposed Stipulated Decision.
* Senior Attorney can reapply the signature if they placed it incorrectly
* Senior Attorney can cancel signature process
* Senior Attorney can confirm signature
* The signed version of the Stipulated Decision is saved as a separate draft document. It does not overwrite the original.
* Senior Attorney MUST generate a message to the docket clerk during the signature process that appears on the Signed Stipulated Decision doc detail page, and this message appears in Senior Attorney's Sent Message box - 
* Once signed, the draft Stipulated Decision is viewable by all internal users, but not public or parties int he case. 
* Once signed, the message thread TO the Senior Attorney on the Proposed Stipulated Decision is closed and removed from their Message Inbox. 

## Notes
* Proposed Stipulated Decisions are of various sizes, so need the ability to apply the signature anywhere on the page.
* The digital signature will be a conformed signature of the judges signature
* Stipulated decisions are always 8.5x11; we don't need to scale the signature because of this. 
* Need the ability to drag and drop ("stamp")
* Need the ability to sign on any page
* Jessica said she envisions a "box" with transparent background
* PDF will be searchable. We'll have an original and then the signed copy.
* The UI is only a representation of the PDF, which gives us the coordinates of the signature
* On the back end it adds the signature to the doc
* Jessica - we would not want users typing it out every time. We'd want to control the content and who has access to the signature. 
* Managing the signature is easier with text than an image. 
* Jessica, for now, just used conformed signature (text). If it changes, we'll address it then. 

Which page the signature is likely to be on:
* 95% on the first page
* 4% on second
* 1% past that

## Tasks
- [x] POC - Drag / drop signature UI (Matt)
- [x] POC - Document generation with signature (Matt)
- [x] Document generation interactor (Matt)
- [x] Cycle for page selection, ability to drag signature after placed and ability to confirm and cancel (UX) (Sarah)
- [x] Implement cycle view (Matt ~*Done, but waiting on additional UX input~ ustaxcourt/ef-cms-flexion#2199)
- [x] Service worker implementation (Cody)
- [x] Refactor drag and drop UI (Joe/Matt ~* Done, but waiting on lambda work for PR~ ustaxcourt/ef-cms-flexion#2199)
- [x] Generate a document persistence; needs a lambda (Joe)
- [x] Testing scenarios (Mariah)
- [x] Apply updated design to signature view (Matt ustaxcourt/ef-cms-flexion#2210)
- [x] Dispatch message to docket clerk (Joe ustaxcourt/ef-cms-flexion#2219)
- [x] Complete Proposed Stip Decision message (Joe ustaxcourt/ef-cms-flexion#2211)
- [x] Add opaque white box to signature background on PDF (Joe ustaxcourt/ef-cms-flexion#2233)
- [x] Add opaque white box to signature background on view
- [x] Update design based on 7/1 feedback (Sarah, Matt ustaxcourt/ef-cms-flexion#2227)
- [x] Refactoring and clean up (Cody/Matt/Joe ustaxcourt/ef-cms-flexion#2258)
- [x] Add user role/title to signature on view and PDF (Joe ustaxcourt/ef-cms-flexion#2241)
- [x] Work queue flow issues (Cody/Matt)

 ## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] ~Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only)~ N/A 
  - [x] No errors reported in manual a11y testing (Eric)
  - [x] ~All new functionality verified to work with keyboard and osx voiceover~ N/A
  - [x] Code refactored for clarity and to remove any known technical debt (Joe)
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Cody)
  - [x] ~UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)~ N/A
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (Eric)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (Joe)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised (Matt)
