### ISSUE TITLE
Docket Clerks: Adds details (stats) about case after it's closed

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6544]
As a Docket Clerk, in order to easily reference a case's final outcome, I need the ability to enter additional resolution amount to the case.  

## Pre-conditions:
* A case in the system has been closed

## Acceptance Criteria:
* Docket Clerk can add resolution amount 
* Resolution amount is viewable to internal users 
* Resolution amount can be edited and saved

## Tasks
- [ ] TBD

 ## Definition of Done
- [ ] acceptance criteria have been met
- [ ] all code changes have been reviewed, approved, and merged and deployed to develop 
- [ ] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [ ] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [ ] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [ ] 0 errors reported in manual a11y testing
- [ ] all new functionality verified to work with keyboard and osx voiceover
- [ ] all code quality checks are passing - sonar, eslint, html validation, etc.
- [ ] code refactored for clarity and to remove any known technical debt 
- [ ] application can be deployed to multiple regions
- [ ]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [ ] performance tests successfully completed and no new significant performance issues found
- [ ] alerting and monitoring for new functionality in place and successfully exercised
- [ ] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [ ] npm audit for CVE’s in production library/module dependencies identified and resolved
- [ ] library/module dependencies are up-to-date and are at the latest resolvable version
