### ISSUE TITLE
Petitioner: Submit new case to Court

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6545]
As a Petitioner, in order to officially start my case at the Court, I need to submit my case to the Court.

After Petitioner has uploaded all of the PDFs and entered all required personal information (name, address, phone, TIN, etc.), Petitioner submits/transmits the new case to the Court.  At the time of submission, the system should generate a docket number and case caption for the case.  The system should also generate a case record where all of the case information and filings are accessible.  

## Pre-conditions:
* Petitioner’s personal information (name, address, phone, TIN, etc.) is complete
* Petitioner has uploaded the three PDFs (Petition, Request for Place of Trial, Statement of Taxpayer Identification Number)

## Acceptance Criteria:
* The system generates a docket number.
* The system generates a case caption.
* The system generates a case record.
* Case status is set to "New Case"
* Petitioner can see the docket # associated with the case.
* Petitioner can see the caption created with the case. 
* Petitioner can see a record of the Petition in the system in the correct case. 
* Petitioner can see a record of the Request for Place of Trial in the system in the correct case. 
* Petitioner can see a record of the STIN in the system in the correct case.

## Notes:
* Petitioner's personal information will likely be populated during the account creation phase, so this assumes that this information is already captured by the system.
* The docket # is formatted as 00101-18.  First part goes from 101 to 99999, last 2 digits are year case created.  The docket number includes the next sequential number from the previous. (There may also be a suffix applied after the year due to case type, but that will be in another story)
* Caption should populate as "[First Name] [Last name], Petitioner v. Commissioner of Internal Revenue, Respondent" 

## Tasks
- [x] Design UI for Case Summary view (Kristen)
- [x] Design UI for Case Detail view (Kristen)
- [x] Responsive table (Eric & Kris)
- [x] Code Case Summary view (Eric & Kris)
- [x] Code Case Detail view (Eric & Kris)
- [x] Create endpoint to create a case in dynamo (will/cody)
- [x] define REST API (will)
- [x] Create Lambda to create docket number (cody/will)
- [x] Create front-end service layer to talk to the back end for case detail and case listing by user (kris/eric)
- [x] Create end-to-end tests covering petitioner workflow (kris)
- [x] Add changes for accessibility where appropriate for keyboard/voiceover (kris)
- [x] Create pre-signed URL endpoint for GET document (will/cody)
- [x] Create endpoint to GET cases by user (will/cody)
- [x] Create endpoint to GET case by case ID
- [x] Create endpoint to GET document meta data by case ID (will/cody)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
