### ISSUE TITLE
Intake Clerk: Search for case by Docket # to associate pay.gov filing fee ID with case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6546]
As an Intake Clerk, in order to make sure that the pay.gov filing fee ID is associated with the correct, I need to search for case by Docket #.

The Court receives a report from pay.gov each day that lists all of the cases in which a filing fee has been paid through pay.gov (sample of report attached).  The cases are referenced by Docket #.  An Intake Clerk needs to be able to search for the case by Docket # and enter the pay.gov filing fee ID to indicate that the filing fee has been paid.

## Pre-conditions:
* Intake Clerk is logged into the system 
* Petitioner has paid fee through pay.gov 
* Payment has been associated with docket # in pay.gov 
* Intake Clerk has received filing fee report from pay.gov and has filing fee ID with associated docket # 

## Acceptance criteria:
* System knows that the user is an Intake clerk
* Intake Clerk can access case through docket # search 
* Internal Court users can access case through docket # search (non-permission based)
* Intake Clerk can enter pay.gov filing fee ID within the case
* Petitioner can access the system and see that the Court has confirmed the filing fee payment through pay.gov but not change the status (view only not edit)

## Notes: 
* USDS does not have type ahead (Natalie to research)

## Tasks:
- [x] add intake clerk to available users (Eric)
- [x] backend docketnumber find endpoint /cases/XXXXX-XX (will)
- [x] design where docket number search goes in views (Kristen)
- [x] implement design (add docket number search to header on dashboard until design complete) (Eric)
- [x] add search value to cerebral state (Eric & Kris)
- [x] implement updateSearch sequence (Eric & Kris)
- [x] implement submitSearch sequence [getCase, setCase, showCaseDetail] (Eric & Kris)
- [x] implement padding and shortening of docket numbers in HTML (Eric & Kris)
- [x] design view for adding pay.gov filing id to case for internal users (Kristen)
- [x] Design view for viewing pay.gov status for any public users (kristen)
- [x] implement input on case detail for adding pay.gov filing id to case

 ## Definition of Done:
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
