### ISSUE TITLE
Petitions Clerk: Validate Petition (1.3)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6547]
As a Petitions Clerk, in order for the case to proceed, I need to validate the Petition.

Pre-conditions:
* A complete petition (3 PDFs) is saved in the system.
* Petitions Clerk is logged into the system.

Acceptance Criteria
*  The system knows that the user is a Petitions Clerk.
* Petitions Clerk can see within the system that the petition is ready to be validated (work queue - keep it simple until we have more user research)	
* Petitions Clerk can view each of the three PDFs in their browser		
* Petitions Clerk validates each individual petition document
* Case status automatically changes to "General Docket" status

## Tasks
- [x] Design the Petitions Section "Work Queue" (kristen)
- [x] Design the validation per document on the "Case Detail" view (kristen)
- [x] Design how to change the case status to "General Docket" (kristen)
- [x] Implement the Petitions Section "Work Queue" view on the front end (eric/cody/will)
- [x] Implement the "Case Detail" view (cody/eric)
  - [x] put pdf into iframe
  - [x] link up the checkboxes as per design (float: right)
- [x] Create end-to-end tests covering petitioner workflow (kris)
- [x] Add changes for accessibility where appropriate for keyboard/voiceover (kris)
- [x] Implement the individual document validation in the view (cody / eric)
- [x] Create endpoint to GET all cases in "New" status (will/cody)
- [x] Create endpoint to PUT the case to "General Docket" status (will/cody)
- [x] Create endpoint to PUT each document as validated (will/cody)

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
