### ISSUE TITLE
Petitioner: Edit and display personal contact data

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6549]
As a Petitioner, in order to ensure the court has my up-to-date contact information for document service, I need the ability to edit and display my personal contact data within my case.

## Pre-Conditions:
* Petitioner has successfully created an account and has personal data in the system (CMS)
* Petitioner has a username and password saved in the system (Cognito)

## Acceptance Criteria:
* Petitioner has the ability to modify their address and phone number
* Petitioner’s address, phone number are saved in the system (CMS)
* Petitioner’s address, phone number display in the system 
* Record of data change is captured through creation of a new docket entry that should read: "Notice of Change of Address by [name of person]" 
* Petitioner may not change the contact information for another party. THey should be instructed to contact the Court by filing a Form 10, Notice of Change of Address, available at https://ustaxcourt.gov/forms/NOCOA_Form_10.pdf

## Notes
* Changes to personal data do not change/affect cover sheet
* Practitoner and Sr. Attorney contact info changes in ustaxcourt/ef-cms#6864
* For email change, going to explore if integration is possible and what just linking to Cognito looks like. (6/20)
* Do not display petitioner's personal data in the docket entry. Keep language simple, e.g. "It has changed." (6/20)
* When this happens, start a work item in the docket record's work queue. Other parties need to be informed via service. Generate a Change of Address and serve on parties. Paper and Electronic. Docket will link to a notice. Add this to the Notice epic.  NOT PART OF THIS STORY. WILL CREATE NEW STORY(6/20) ustaxcourt/ef-cms#6886
* Petitioner could have multiple cases, each with a different address. (6/20)
* Moved changing email address to another story ustaxcourt/ef-cms#6890 

## Tasks
- [x] Edit Button and Modals (Matt ustaxcourt/ef-cms-flexion#2263)
- [x] Update user data on db (Matt ustaxcourt/ef-cms-flexion#2269)
- [x] Validate contact info before saving (Joe ustaxcourt/ef-cms-flexion#2289)
- [x] Show confirmation when saved (Joe ustaxcourt/ef-cms-flexion#2285)
- [x] Authorize for write (isAuthorized->owner) (Eric)
- [x] Generate docket entry (Eric)
- [x] Write test scenarios (Mariah/Eric ustaxcourt/ef-cms-flexion#2280)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated (Sarah)
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning (Cody)
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) (Matt)
  - [x] No errors reported in manual a11y testing (Eric)
  - [x] All new functionality verified to work with keyboard and osx voiceover (Eric)
  - [x] Code refactored for clarity and to remove any known technical debt (Eric)
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Cody)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required) (Eric)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (Eric)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (Joe)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised (Eric)

__________
Outdated based on clarification (6/18):
Before Petitioner can file an electronic petition with the Court, they need to create an account.  Petitioner navigates to the webpage where they can create an account.  As part of the registration process, Petitioner will use an email address as a user name and select a secure password.  Petitioner will receive email confirmation of account creation. Petitioner validates email address.

When a Petitioner creates a new case within the CMS, they will enter additional contact information name, address, phone.  That information should be saved to the Petitioner's profile.  A Petitioner should be able to manage their profile at any time.
