### ISSUE TITLE
[UX] Preliminary user research and documentation

### ISSUE THREAD

**Issue by uxforgood** [ustaxcourt/ef-cms#6553]
Activities performed as a result of the on-site DC research trip

- [x] 1. Review and analyze user research  (Valencia) 
- [x] 2. Identify common themes and areas for change (Valencia) 
- [X] 3. Identify and document personas - Valencia
 - [X] 4. Work on persona templates (Valencia/Sarah)
- [x] 4. Create presentation on research findings (Valencia)
- [x] 5. Reformat journey map template (Valencia/Sarah) 
- [x] 6. Create "case" journey map/docket clerk and petitions clerk (continue work from focus group)
- [x] 7. Provide epic narrative feedback (Valencia, Natalie, Kristen)
- [x] 8. Talk to devs about moving their documents to a shared folder (Mariah)
- [x] 9. Update UX flow chart of what we're building as a whole. Consolidate Intake Workflow and Petitions Intake into the same doc. Update by the end of Sprint 6 (Sarah)
- [x] 10. Move all loose ends from the flow doc into Zenhub; facilitate a meeting to backlog together - Mariah
- [x] 11. Case Statuses - update diagram with what drives status changes - Sarah
- [x] 12.  Ensure USTC folder (shared with court) is updated with final copies or working documents. Nothing outdated - All
- [x] 13. Main UX folder - organize by  testing or research session. If not a specific session, organize by topic (e.g. "deep dive") Formalize document naming conventions - Sarah
- [x] 14. User Roles; pull out epics doc and put in it's own doc (Mariah) 
- [x] 15. Sprinkles list - currently a tab in notes analysis doc. Make it's own document. Put into spreadsheet  -  Kristen 
 - [x] 16. Complete USTC roles document - Kristen
              - Document created; visibility by role reviewed/approved by Jessica 
             - waiting for Jessica review for role definitions and functional permissions 
- [x] 17. Create glossary of page names/views (Valencia)

Notes:
* (1/8) New persona format will be used. More focused on system usage. 
* (1/8) Personas will be focused on roles.
