### ISSUE TITLE
Parties: Assign Doc Type for External Filing

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6556]
As a Petitioner, Practitioner and IRS Attorney, in order to correctly identify my document, I need to select my document type from a list of court-approved document types. 

For consistency in naming of documents filed with the Court, only Court-approved document types can be filed.  When a Petitioner wants to file a document in their case, they must select from the options provided by the Court.

## Pre-Conditions:
* Petitioner has indicated they want to file a document

## Acceptance Criteria:
* Parties are able to select a document type from a list of Court-approved documents. https://docs.google.com/document/d/1BIDQcmkZIql3w0alX8Skku5J-EgaS7SlVYTBTNtb2sc/edit?usp=sharing

## Notes:
* When we load the doc types into the system, we need to correspond them to the doc codes. Even though external parties won't use them, internal court users will. 
* We'll use this story to build out the tiered doctype design. 
* Pages 55-61 of Guide to eFiling (publicly available) shows how the Court currently does this: https://ustaxcourt.gov/eaccess/Petitioners_Guide_to_eAccess_and_eFiling.pdf
* There are some special circumstances (pages 61-74) that require special handling. However, they will handled in another story (#980). 
     *  Motion for leave to file per Rule 41(a) require motion and other document. Two separate upload spaces.
     *  Amended _____
     *  First/Second/Third Stipulation of Facts; etc.

## Tasks
- [x] Add File Document Button for petitioners, practitioners, and respondent (cody, ustaxcourt/ef-cms-flexion#1254)
- [x] Create document type map with categories and titles (kris ustaxcourt/ef-cms-flexion#1250  )
- [x] Update File Document screen with doc categories, helper text accordion, and button to open modal (Rachael ustaxcourt/ef-cms-flexion#1255)
- [x] Import document type data into the app somehow (cody ustaxcourt/ef-cms-flexion#1253)
- [x] Create modal for doc type selection with special modal styling (kris ustaxcourt/ef-cms-flexion#1264 )
- [x] Make File Document its own page instead of a hidden section of the case detail page (Rachael ustaxcourt/ef-cms-flexion#1258)
- [x] Refactor/combine case detail views (Rachael)

## Definition of Done

**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
