### ISSUE TITLE
Parties: Review, Submit, and Confirm File Upload

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6557]
As a Petitioner, Practitioner and IRS attorney, in order to make sure I complete the eFiling process and successfully file my document, I need to review, submit, and confirm file upload.

To avoid a Party uploading the wrong document, or not providing accurate information about the document to be filed, the Party should be able to review the document and all data before submitting to the Court.  Upon submission to the Court, the Party should be able to confirm the document was properly uploaded by viewing it on the docket record.

## Pre-Conditions:
* Party has selected a document type and uploaded a file
* Party has entered all required information
* Party indicates they want to file the document

## Acceptance Criteria:
* Party can review the uploaded .pdf document and all other data provided before filing it
* Party can submit/file the document in the selected case
* Party sees success message
* Party can view and access it on the docket record upon submission
* If a supporting document is provided in support of the primary document, that supporting document should appear on the docket record as a separate docket entry.
* If a secondary document is provided (in the case of a Motion for Leave or Motion for Leave to File Out of Time), the secondary document must display on the docket record as a separate docket entry.
* If a supporting document is provided in support of a secondary document, that supporting document should appear on the docket record as a separate docket entry.
* When external filing(s) are submitted/filed in a case, a new work item should be created on the Docket Section work queue and be viewable as a pending message in the case detail and document detail pages.

Notes:
* There is the possibility that a single transaction could result in up to 4 docket entries: main document; supporting doc for main doc; secondary doc; supporting doc for secondary doc.

## Tasks
Design:
- [x] Design review screen [Sarah]
- [x] Create docket record view with success state [Sarah]

Code:
- [x] 1. Create review view (Rachael ustaxcourt/ef-cms-flexion#1388)
- [x] 2. Create fileExternalDocument interactor to upload documents to S3 (Rachael ustaxcourt/ef-cms-flexion#1390)
  - [x] 4. Create submit sequence to call fileExternalDocument (William ustaxcourt/ef-cms-flexion#1403)
- [x] 3. Create service endpoint/ interactor that updates Case and Docket Record with uploaded documents (William/Cody ustaxcourt/ef-cms-flexion#1403)
- [x] 5. Create modal for cancel button (kris/Rachael ustaxcourt/ef-cms-flexion#1386)
- [x] 6. Fix service date bug on FileDocument form - after all data is entered and you click the review button, there is an error that service date is not entered; click in one of the date fields and unfocus it and the error goes away (William ustaxcourt/ef-cms-flexion#1393)
- [x] 7. Fix date format on service date on review screen to match design (MM/DD/YYYY) (Rachael/Kris ustaxcourt/ef-cms-flexion#1399)
- [x] 8. Update review screen with updated document type labels and file icon (in tech channel on Slack) (Rachael/Kris ustaxcourt/ef-cms-flexion#1394)
- [x] 9. Load data from state on FileDocument form (for Edit functionality from FileDocumentReview page) (Cody/Rachael ustaxcourt/ef-cms-flexion#1404)
- [x] 10. Show Success Message on completed upload. (William / Cody ustaxcourt/ef-cms-flexion#1403)
- [x] 11. Add Work Item for each uploaded document (William / Cody ustaxcourt/ef-cms-flexion#1403)
~~12. Verify saved metadata for primary document~~ Handled by ustaxcourt/ef-cms#6765
- [x] 13. Verify supporting document title generation (Rachael ustaxcourt/ef-cms-flexion#1406)
- [x] 14. Address that gotoCaseDetailSequence runs clearAlertsAction which doesn't allow alert message to show up. (Kris ustaxcourt/ef-cms-flexion#1414)
- [x] 15. Clean up old code/tests for respondents filing documents (the "old way") (Rachael ustaxcourt/ef-cms-flexion#1411)
  - [x] Update respondent case journey tests with new sequences (Rachael ustaxcourt/ef-cms-flexion#1411)
- [x] 16. Case journey test for filing a document from start to finish (this was started on a previous story - petitionerFilesADocument.test.js) (William ustaxcourt/ef-cms-flexion#1417)
- [x] 17. [Updated Exhibits/Attachments/Certificate/ Objections Section](https://github.com/flexion/ef-cms/issues/302#issuecomment-484152030) (Rachael ustaxcourt/ef-cms-flexion#1418)
- [x] 18. Ensure supporting-document metadata is cleared when "no" is selected (Kris, William ustaxcourt/ef-cms-flexion#1420 )
- [x] 19. [UX Review Items](https://github.com/flexion/ef-cms/issues/302#issuecomment-484593903)
  - [x] 19a. Loading overlay to show progress and stop multiple submissions. (William ustaxcourt/ef-cms-flexion#1435)
  - [x] 19b. Supporting Documents - We need to show the selection if they say no to supporting documents - display under “Filing Does Not Include” (Rachael ustaxcourt/ef-cms-flexion#1438)
    - [x] 19ba. This should occur for Secondary documents as well. (Rachael ustaxcourt/ef-cms-flexion#1438)
~~19c. Docket entries not ordering correctly - -Docket Number: 802-19W (Rachael)~~ can't recreate
  - [x] 19d. secondary document for Motion for Leave to File is optional, yet when i submitted the form without uploading a secondary document - app broke (white screen) (William/Kris ustaxcourt/ef-cms-flexion#1436)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required) (Rachael ustaxcourt/ef-cms-flexion#1423, Kris ustaxcourt/ef-cms-flexion#1422)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
