### ISSUE TITLE
Petitioner: Select party type and enter appropriate contact information

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6559]
As a Petitioner, in order to inform the court about what type of party I'm filing as, I need to indicate my party type and provide the contact information that's required for that party type

The person filing a petition may be filing for themselves, them and a spouse, on behalf of someone (child, elderly parent (incompetent person), business, estate, trust, etc.). The Court needs the ability for the person who is filing the Petition to indicate who they are filing for and then provide contact information fields based on that response.

## Pre-Conditions
* Petitioner has confirmed that they want to Start a New Case

## Acceptance Criteria
* Petitioner must select a Party Type
* Party types must be official, court-designated party types [Provided in Notes]
* Petitioners are required to enter the contact information that's required for the specific party type they've selected
* Party Type and contact information is saved in the System
* Petitioner and internal court users can easily see within the case all party information

## Notes
* The Party Types are:
    * Petitioner
    * Petitioner & Spouse
    * Corporation
    * Partnership (as the Tax Matters Partner)
    * Partnership (as a Partner Other Than Tax Matters Partner)
    * Partnership (BBA Regime)
    * Estate with an Executor/Personal Representative/Fiduciary/etc.
    * Estate without an Executor/Personal Representative/Fiduciary/etc.
    * Trust
    * Conservator
    * Guardian
    * Custodian
    * Minor (Without a Guardian, Conservator, or other like Fiduciary)
    * Incompetent Person (Without a Guardian, Conservator, or other like Fiduciary)
    * Surviving Spouse
    * Petitioner and Surviving Spouse
    * Transferee
    * Donor

* Required contact information fields for each Party Type (https://docs.google.com/document/d/1_pv9J_RnUGVdEM8HOdX4iikx3rKbgQXyXd_OG8BVC_I/edit?usp=sharing)
* This story does not cover international addresses.  That will be covered in another story (#655). If the design team feels it should be included in the design then combine ustaxcourt/ef-cms-flexion#655 .
* Jessica needs to learn more about how the Court treats aliases and how we need to capture that information in the system (if at all for MVP).

## Tasks
- [x] Design Party Type selection section of Start a Case Form (Kristen) 
- [x] Update design of Party Information on Case Information tab (Kristen) 
- [x] Develop business tests
- [x] Update design and case information tab
- [x] Design views based upon system flows
- [x] Modify party type entity and additional entity combinations
- [x] Modify Start a Case view
- [x] Field-level validation for existing fields (eric)
- [x] Field-level validation for petitioner contact (eric)
- [x] petitioner & spouse & deceased spouse validation (William)
- [x] estate with & without executor, validation (kris)
- [x] place input forms for each party type into StartCase (rachael)
- [x] corporation, partnership tax matters, partnership NOT tax matters entity validation (William)
- [x] partnership BBA regime, trust & trustee entity validation (kris)
- [x] conservator, guardian, custodian entity validation (kris)
- [x] minor without guardian, incompetent person without guardian entity validation (William)
- [x] surviving spouse, petitioner & deceased spouse entity validation (William)
- [x] donor, transferee entity validation (kris)
- [x] remove "email" field from all secondary users (Rachael)
- [x] verify/clean up mobile view (Rachael)
- [x] change case title based on party type (Rachael)
- [x] field-level validation on address (Eric)
- [x] Jessica's comments from review: (1) When you select “Myself & Spouse” and “Deceased=NO”, fill everything out and try to submit the case, there is an error that comes up requiring an email.  There is no blank email field, so this is a false-positive error. (2) Another false-positive error when you select “Other”…”with Estate/Trust”…”Estate with Executor/PR”.  This error message says Name is required (x2) and Phone is required. (3) Another false-positive error when you select “Other”…”Estate/Trust”…”NO Executor/PR”.   This error message says Name is required. (Rachael) - PR ready

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
