### ISSUE TITLE
Court: Ability to correct a case caption

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6562]
As a Court User, so that I can correct any typos the Petitioner makes, I need the ability to correct case captions that were generated by the system. 

Case captions are automatically being generated by system, based on Petitioner-entered data. If a Petitioner accidentally enters incorrect information, the system will generate a caption from that incorrect data. During the QC process or at any other time, court users need the ability to correct the case caption, just as they would with any other case metadata. 

## Pre-Conditions
* Case caption has been automatically generated
* Court user can see the auto-generated case caption

## Acceptance Criteria
* Court user can edit and save the auto-generated case caption
* Only the part of the caption before "v. Commissioner of Internal Revenue" needs to be editable
* Change is captured on the docket record as an entry that reads "Caption of case is amended from [old caption] to [new caption]"
* Anywhere the case caption currently displays, it displays the corrected case caption after it is edited

## Research/Analysis Notes
* This can happen during the Petitions Clerk QC process and any other time.

## Tasks
- [x] Design mechanism for editing the case caption (Kristen) 
- [x] Update Case Detail page - add edit button 
- [x] Update Document Detail page - add edit button
- [x] Create Edit Case Caption modal 
- [x] Add checkbox icon and text beside Case Caption (kris)
- [x] Create Modal for editing Case Caption (kris)
- [x] Create Sequences for opening, closing modal (William)
- [x] Create sequence & actions for saving case caption (William)
- [x] Add Docket Record Item when the case caption is updated (William)
- [x] write tests for sequence which updates case caption (William)

 ## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
  -  [x] CI/CD - Code is deployed to DEV
- Other
  - [ ] alerting and monitoring for new functionality in place and successfully exercised
