### ISSUE TITLE
Court User: Creating a case on behalf of paper-filing petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6563]
As a Court User, in order to start a new case for a paper-filed Petition, I need the ability to create a new case in the System.   

When a Petitioner submits a Petition in paper form, an internal Petitions Clerk must upload that Petition into the CMS.  This includes entering all contact information and case metadata, as well as uploading any documents provided by the Petitioner.  Once the internal Court User is done entering everything, the case should be treated just as if an external filer uploaded the Petition electronically.

## Pre-Conditions
* Court User is logged into the System

## Acceptance Criteria
* Court User must be able to indicate that they are starting a case for a Petitioner
* Court User must enter all contact information for Petitioner
* Court User must enter all case metadata for the Petitioner
* Court User must upload any required documents for the Petitioner
* Court User must be able to overwrite date that petition was received by Court for case creation/document upload
* System must store that this case was started as a paper petition (metadata stored for later reporting needs, but not displayed in UI)
* Court User must be able to confirm that a new case has been successfully started for a Petitioner
* When the case is created in the system issues the next sequential docket number
* When an internal user (Petitions Clerk or Docket Clerk) starts a new case from a paper petition, the new case is added to the user's work queue and to the user's section work queue as a work item.  The work item should be assigned to the internal user who started it.
* The work item in the individual queue and section queue should contain the following message: "Petition filed by [Petitioner's name -- everything before the v. in the caption] is ready for review."

## Notes
* Same interface as petitioner except doesn't need notifications and warnings

## Tasks
- [x] Design: Update petition's clerk dashboard
- [x] Design: Modify form design
- [x] Design: Update case info tab on case detail page
- [x] Code: Add "Create a Case" button to petition clerk dashboard/work queue (William ustaxcourt/ef-cms-flexion#1219)
- [x] Code: Create "Create a Case" page for internal users (William ustaxcourt/ef-cms-flexion#1236)
- [x] Code: Sequence and Tests for Petition from Paper (William ustaxcourt/ef-cms-flexion#1232)
- [x] Code: Reduce validation requirements for a Petition Clerk on the Start a Case page (Kris & Eric ustaxcourt/ef-cms-flexion#1221)
- [x] Code: Interactors, Lambda, Swagger (Eric ustaxcourt/ef-cms-flexion#1231)
- [x] Code: Interactor tests (Cody)
- [x] Code: Update Petition QC Document Info tab for paper petitions (add Date Received, etc.) (Rachael ustaxcourt/ef-cms-flexion#1228)
- [x] Code: Add ability for Docket Clerk to Start a Case in the same manner. (Rachael ustaxcourt/ef-cms-flexion#1233)
- [x] Code: Interactor for Uploading files when submitting a Petition without Paper (Eric ustaxcourt/ef-cms-flexion#1236)
- [x] Code: UI Integration
- [x] Code: make file selection icons consistent (Rachael)
- [x] Code: fix createdAt time
- [x] Code: take the user directly to document detail after case is created (William ustaxcourt/ef-cms-flexion#1240)
- [x] Code: add isPaper and dateReceived to Case entity and store that info when case is created (Rachael, Cody ustaxcourt/ef-cms-flexion#1243)
- [x] Code: add work item for user who created the case (Rachael, Cody)
- [x] Email of Internal User showing for Primary Contact on case detail page (Rachael)
- [x] Size of Caption Field changing in error state (Rachael)
- [x] Fee Payment Date Not Displaying when "Batched for IRS" (Rachael)
- [x] Notice /Case Type not showing in read-only view or case info tab (Rachael)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
