### ISSUE TITLE
Generation of cover sheet for all uploaded documents

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6568]
As a user, so that I may easily see document metadata when I view, print or download a document, I need the system to generate a cover page which contains the metadata for every document uploaded to the system. 

Whenever a party is filing a document (or an internal user is uploading a paper-filed document), the System needs to generate a cover page that becomes the first page of the document.  That cover page has a standard format across all Court filings and contains standard content:  
Document type, case caption, docket #, date and time document received, filed date, etc.

If any of the data entered on the cover sheet changes due to a QC by a Petitions/Docket Clerk, a new cover sheet should be generated and added to the document. [This function is *NOT* part of this story]

## Pre-Conditions:
* Party/internal user is filing a document

## Acceptance Criteria:
* System generates a cover page that becomes the first page of every document uploaded to the system.
* The cover page contains the following data; which is originally sourced via the application in multiple ways (see sample link in comments below):
  * Document title
  * Case caption
  * Docket number
  * Date and time  document received by the court (whether paper or electronic)
  * Date document was e-filed with the court (if paper, could be different from date it was filed with the court)
  * Date and time document lodged (if applicable) - See sample in comments
  * Whether or not the document was originally filed electronically
  * Whether or not the document included a certificate of service
* ~~Filer(s) of document should follow document title -- copy format from docket entry (#937)~~
* The data that displays on the cover page is the same for every document. 
* Cover page downloads when a user downloads the document
* Cover page prints when a user prints the document

## Notes:
* The Court currently puts the initials of the clerk who reviewed the document on the cover sheet.  Per Rhonda, this is not required as long as that information is captured elsewhere. (#1293) 
* Date document was served will happen in another story. 
* All times should be Eastern time zone

## Tasks
- [x] Create a function (use case) that received a binary PDF file and raw JSON coversheet data and returns a new binary PDF file that contains the original PDF with a coversheet matching the format in the example below. (includes tests) (Matt)
- [x] Talk to Doug about where to add the PDF fetch and where to trigger the next lambda Eric, Matt, Cody)
- [x] Design for distinguishing processing vs ready to view documents in the docket record (Sarah)
- [x] Update the docket record views to show the document status
- [x] Wrap the cover sheet use case in a lambda that replaces the old PDF with the updated PDF and updates the document status in DynamoDB (Eric)
- [x] Create cover sheet use case proxy (Cody)
- [x] Call coversheet use case proxy from client (Cody)
- [x] update document status after coversheet has been added
- [x] Letters at the end of the docket number
- [x] Lowercase V on case caption
- [x] Font sizes and font face
- [x] Remove horizontal line
- [x] page sizes need to be consistent
- [x] integrations & bug fixes

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
