### ISSUE TITLE
Court User: Ability to make procedural notes on a case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6569]
As a court user, in order to share procedural case information across the court, I need the ability to make procedural notes at the case level. 

## Acceptance Criteria
* Court users can make procedural notes about a case and have it be easily seen by all users (no permissions)
* Any user can edit any other person's notes or make their own and save (no permission)
* One big text box will be sufficient

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add proceduralNote to case entity (Rachael ustaxcourt/ef-cms-flexion#3891)
- [x] 2 Endpoints for adding, editing, deleting procedural notes (Kris, Cody ustaxcourt/ef-cms-flexion#3894)
- [x] 3 Add Case Notes card to Notes tab of case detail (Rachael ustaxcourt/ef-cms-flexion#3891)
- [x] 4 Create Add/Edit Case Notes and delete note confirm modals (sequences and actions for showing/hiding and submitting) (Rachael, Kris ustaxcourt/ef-cms-flexion#3901)
- [x] 5 Add case note button to case detail header action menu (Rachael, Kris ustaxcourt/ef-cms-flexion#3901)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Rachael)
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
