### ISSUE TITLE
Document-level message thread in document detail

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6608]
As a court user, so that I can be aware of all current and past communication pertaining to a particular document within a case, I need a way to easily see all messages threads associated with that document. 

A court user may need to look at the history of all messages on a document.  As a result, the user should be able to easily see all threads on a document (open and closed), and be able to navigate through them.

## Pre-Conditions
* User has access to a document in the system

## Acceptance Criteria
* User can view all message threads (pending and closed/completed) associated with a document
* User can view who closed the final message

## Research/Analysis Notes
* When a message thread is closed, it should add an automatic message that says "Closed by [user name] on [date/time]"

## Tasks
- [x] Design display of completed message threads (Kristen) 
- [x] Create tabs for Complete messages (William)
- [x] implement view for completed messages (Cody)
- [x] Implement automated message when message thread is completed, rename properties on messages (Cody)
- [x] add the check fa-icon on the completed message and also verify the styles match the UX designs (cody)
- [x] verify design matches UX proof
- [x] Panel should be fixed height and scrollable (Rachael)
- [x] If user entered optional message text when completing the message thread, display message. If no message text was entered, do not display any message.

 ## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [ x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
-  [x] CI/CD - Code is deployed to DEV
- Other
  - [x] alerting and monitoring for new functionality in place and successfully exercised
