### ISSUE TITLE
 Epic 2 Clean-Up

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6616]
As a development team ...

## Clean-up items:
1) Show section in work queue; possibly as a separate column
2) Error Handling - Make sure all error handling has been implemented
3) On the dashboard views (Petitioner, Practioner, IRS Attorney), the "Petitioner Name" column should be changed to "Case Name" and the field should display the part of the case caption before "v. Commissioner of Internal Revenue" [Note: if it's easy to drop ", Petitioner" or ", Petitioners" from that, please do that as well.  If not, it's okay to have that under Case Name] [Moved from ustaxcourt/ef-cms#6567]
4) The message generated in the work queue/message thread for an incoming Petition should read "A Petition filed by [name of Petitioner in the caption (i.e., everything before the "v. Commissioner of Internal Revenue")] is ready for review." [Moved from ustaxcourt/ef-cms#6567]
5) UX consider adding caption correction option in QC form (in additional to global caption edit function)
6) Update global and doc detail headers to save some space
7) Review modal behavior for interactive form modals and make necessary changes 
8) Two-step "Send To" in existing message.
9) Remove "Deficiency" from "No IRS Notice" list on Start a Case form

## Tasks 
- [x] Update design of My Queue and Section Queue to add Section Name of sender (Kristen)
- [x] Update design of Petition Document Detail to add Case Caption field (Kristen)
- [x] Update header design (Kristen)
- [x] 1 - Add Section to the Work Queue Table (Cody ustaxcourt/ef-cms-flexion#1175)
- [x] clean up bullet number 2 (Eric)
- [x] clean up bullet number 3 (William ustaxcourt/ef-cms-flexion#1182)
- [x] clean up bullet number 4 (Rachael)
- [x] 5 - Caption correction option in QC form (William ustaxcourt/ef-cms-flexion#1177)
- [x] 6 
  - [x] Document Detail Page Updates (William ustaxcourt/ef-cms-flexion#1170)
  - [x] Case Detail Page; Componentize case detail header (William ustaxcourt/ef-cms-flexion#1168)
- [x] 7 
  - [x] reposition modal to be centered vertically with bottom buttons always visible (kris)
  - [x] prevent modal from being dismissed (kris)
- [x] 8 - Add section dropdown in "Send To" for existing messages (Rachael)
- [x] 9 - Remove "Deficiency" from "No IRS Notice" list on Start a Case form (William ustaxcourt/ef-cms-flexion#1167)
- [x] Run through the app and make sure spinners are on any long running action (Eric, Kris ustaxcourt/ef-cms-flexion#1184 )
- [x] Refactor Case Caption work to limit duplication (William, Rachael, Cody ustaxcourt/ef-cms-flexion#1186)
- [x] a little more space under textarea case caption (Eric PR)
- [x] a little more space under the h2 case header (Eric PR)
- [x] Select Section dropdown should be in alpha sorted (William ustaxcourt/ef-cms-flexion#1244)
- [x] Select Recipient should be alpha sorted (William ustaxcourt/ef-cms-flexion#1244)
- [x] ~~additional Section values(in spreadsheet) (William ustaxcourt/ef-cms-flexion#1246)~~
- [x] Chambers dropdown values(in spreadsheet) (William ustaxcourt/ef-cms-flexion#1256)
- [x] revisit utc timezone views (Eric)
- [x] remove focus states on headers, elements that aren't interactive (Kris)
- [x] Add Sent Section to Outboxes (William ustaxcourt/ef-cms-flexion#1277)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
