### ISSUE TITLE
Petitioner: Upload IRS Notice (2.4)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6624]
As a Petitioner, in order for the Court to confirm it has jurisdiction, I need to upload my IRS Notice as part of my Petition package.

In addition to uploading a Petition form, Petitioner should be prompted to also upload their IRS notice(s) (if any) as part of the Petition package (only 1 upload function), so that when it is transmitted to the Court, the Petition and IRS notice should be part of the same PDF.

## Pre-Conditions:
* Petitioner is logged into the System
* Petitioner has elected to “Start a New Case”

## Acceptance Criteria:
* Petitioner is prompted to upload IRS notice as part of Petition.
* The Petition with IRS notice is viewable to internal users and both parties (Taxpayer and IRS) as one document on the docket record.

## Tasks
- [x] Redesign Start a case form to accommodate single petition file upload (Natalie, Kristen)
- [x] remove irs notice from the view(s) (update ui to match design - remove progress indicators) (Kris)
- [x] remove irs notice from entities and interactors and computeds etc.(both presenter and backend) (Eric)
- [x] modify test scenarios to accommodate no irs notice (Eric)
- [x] Make UI updates and changes to copy presentation (Eric & Natalie)

### Business Test Cases
nothing new

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
