### ISSUE TITLE
Petitioner: Enter Case Metadata (2.5)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6625]
As a Petitioner, in order to give the Court necessary case related information, I need to provide certain metadata.

Before submitting the case to the Court, Petitioner will enter/select additional case metadata, such as:
Type of Case 
Small v. Regular Case 
Place of Trial 

Some of the metadata will be REQUIRED fields and the Petitioner will be stopped from submitting their Petition unless those fields are completed. 

## Pre-Conditions:
* Petitioner is logged into the System
* Petitioner has elected to “Start a New Case”

## Acceptance Criteria: 
* Petitioner can enter Date of IRS notice (if any) [Note: actual notice upload function is story ustaxcourt/ef-cms#6624]
* Petitioner can select the type of Case (Deficiency, Collection Due Process, Innocent Spouse, Whistleblower, etc.)--REQUIRED*
* Petitioner can select whether they want case conducted as Small v. Regular (Procedure Type) and can view information about the differences --REQUIRED* 
* Petitioner can select Place of Trial (options should be intuitively driven based on selection of small v. regular)--REQUIRED*  
* All metadata should be saved in the System upon case submission
* All metadata is viewable to internal Court users on the case information tab 
* The Place of Trial selected should be displayed on the Docket Record as “Request for Place of Trial at City, State"
* If Petitioner does not enter required metadata, they should be stopped from submitting their Petition.
* The Court is confident the data submitted by the Petitioner is accurate

## Notes: 
* The PDF upload functions for Place of Trial and STIN can be removed
* Need a list of all Places of Trial and whether they conduct small or regular procedure types (Jessica provided in comments)
* Need a complete list of case types (Jessica provided in comments)
* (1/8) Can leave a dead upload link. It will go live when we do ustaxcourt/ef-cms#6624. Include design elements. Just won't do anything. 
* (1/8) Design will incorporate a validation modal for the cancel button. "Are you sure?"
* (1/8) Use full list of fields now. Can break up when we add yes/no logic.
* (1/8) If a state doesn't have a city available, write some helper text instead of implementing some logic. "Please note, if you select small tax cases, there are no available trial sessions in the following states. Please select the next closest city."
* (1/10) Override USDS design standards and don't wrap text next to textbox.
* (1/10) Don't allow text to run all the way across the page. Instead, make about 75% across the page. Approx. 75 to 85 characters
* (1/10) PDF icons need to be black, not blue.
* (1/10) Sentences should be closer to the thing above it. 
* (1/0) Types of notice are ordered by most commonly used. ~80% of users will select the first two. 
* Sorting of the the Petitioner's Docket Record is not required for acceptance of this story. This will be addressed in Issue ustaxcourt/ef-cms#6712 

## Tasks
- [x] 1. Design the "Start a New Case" form (Kristen)
- [x] 2. Add instructional text for Petition upload (Form 2 or custom petition)(Kristen)
- [x] 3. Update text to suggested plain language (Natalie)
- [x] 4. Design the "Case Information" tab (Kristen)
- [x] 5. Modify "Submit" action on the form to include additional metadata and required fields (Eric)
- [x] 6.1 Design the "Case Information" tab (Kris)
- [x] 6.2 Modify the "Case Information" tab  to reflect live data(cody)
- [x] 7. Add fields to Case Detail record (will)
- [x] 8. Design how case type entities are connected to the case entity (will)
- [x] 9. Design how place of trial entity is connected to the case entity (will)
- [x] 10. Implement changes to the database based upon additional relationships (will)
- [x] 11. create interactors, actions, sequences for case types, procedure types, trial cities (will)
- [x] 12. add simple form to the filepetition view which can be changed later based on the design (will)
- [x] 13. remove stin and placeoftrial from fileapetition (will)
- [x] 14. Add validation and error messaging (Cody)
- [x] 15. Plug-in the cerebral tests to display the error messages
- [x] 16. Need to create the integration test for cerebral
  - see names listed below for assignment (Cody)
- [x] 17. Develop BDD test scenarios
- [x] 18. Add new styles to make App look like Figma (Eric)
- [x] 19. Create cancel modal (Kris)
- [x] 20. Research how to implement text not spanning the entire page; esp in light of responsive design (Natalie)
- [x] 21. Determine what we're doing with PDF icons (Natalie)
- [x] 22. Upload Petition Helptext (see design in comment jan 11 2019)
- [x] 23. Research file size limitation solutions as it applies to court documents.  (Waldo)
- [x] 24. Add "Other" to case types (Will) pr out
- [x] 25. Coordinate with User Design on Error Handling (Will, Eric, and Natalie)
- [x] 26. Tie preferredCity, trialcities, proceduretype  and irsNoticeDate to the form in the view (will/cody)
- [x] 27. If user clicks Yes on the modal, they return to the dashboard. (kris)
- [x] 28. clear the form data on page load (kris)
- [x] 29. the select dropdown for state should use optgroup for grouping by state (cody)
- [x] 30. trial cities hint should change depending on the selected procedureType 
-add to start a case helper computed (will/eric)
- [x] 31. update the success alert to match design (cody)
- [x] 32. format the irsNoticeDate on the case information tab to be MM/DD/YYYY (kris)
- [x] 33. implement the checkbox for "I have reviewed" to not allow the form to submit (cody)
- [x] 34. hide the current validation messages and display a generic message instead (cody)
- [x] 35. bring back the functionality to marking a case as paid (kris)
- [x] 36. revisit the date inputs validation (Eric/Will)
  - [x] a. Date field should accept only numeric values
  - [x] c. Date cannot be in the future
- [x] 37. implement the "how is a small case different than a regular case" accordion (kris)
- [x] 38. PDF Help Text - https://github.com/flexion/ef-cms/issues/402#issuecomment-453609301 - (cody)
- [x] 39. address bugs posted in slack by jessica 1/13 (will) (prs out)
- [x] 40. add trial city as described in AC to the petitioner view similar to paygov date (note - the underlying data structure and code behind this view will be refactored in a later story) (will)
- [x] 41. adjust body copy width (Eric, Natalie, Kristen)

## Test Scenarios 
When initiating a petition (start a case):
- [x] petitioner sees all available options for case types and can only select one option (will)
- [x] petitioner sees options available for procedure type (Small or Regular) and can only select one option (will)
- [x] after choosing a procedure type, petitioner sees all available options for preferred trial locations based on the selected procedure type and petitioner can select only one preferred trial location (will)
- [x] changing the selected procedure type causes the selected trial location to reset (will)
- [x] petitioner can select a single petition pdf (will)
- [x] petitioner should be prompted to indicate that they have reviewed all information before submitting case to the Court
- [x] when petitioner submits form a case is not initiated unless caseType, procedureType, preferredTrialLocation, and petitionPdf are present and valid. (cody)
- [x] all fields are saved to the case and the petitioner can view the newly created case (cody/will)
- [x] case metadata is viewable to internal court users on "Case Information" tab in case

## Definition of Done
- [ ] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
