### ISSUE TITLE
Court: Suffix on Docket Number (2.6)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6626]
As the Court, in order for the Docket Number to be accurately identify the case, I need a suffix added to the end of a docket number where appropriate.

If a Petitioner elects to have their case conducted as a “small” case, or selects certain types of cases (i.e., CDP, Whistleblower), a suffix needs to be added to the end of the docket number.  See Notes for specific rules.

## Pre-Conditions:
* Petitioner has selected the type of Case (Deficiency, Collection Due Process, Innocent Spouse, Whistleblower, etc.)
* Petitioner has selected whether they want case conducted as Small v. Regular
* Petitioner has submitted case to Court

## Acceptance Criteria:
* The auto-generated docket number has a suffix if certain conditions are met [see Notes for rules]

## Tasks:
- [x] 1. Implement the docket number logic into the docket number creation function (will/cody pr)
- [x] 2. Modify search to remove the suffix when a user searches a docket number (will/cody pr)
- [x] 3. Create cerebral computed for display of docket number with the suffix (cody pr)

## Business Tests
- [x] when a case is created the docket number suffix is created according to the rules
- [x] when any user views a docket number anywhere in the system the suffix displays with the docket number

## Notes:
* If Petitioner elects “small” tax case procedures, a “S” is added to the end of the Docket Number
* If Petitioner elects “Lien/Levy” as case type, a “L” is added to the end of the Docket Number
* If Petitioner elects “Whistleblower” as case type, a “W” is added to the end of the Docket Number
* If Petitioner elects “Passport” as case type, a “P” is added to the end of the Docket Number
* If Petitioner elects “Declaratory judgments for Exempt Orgs” as case type, a “X” is added to the end of the Docket Number
* If Petitioner elects “Declaratory Judgment for retirement plan revocation” as case type, a “R” is added to the end of the Docket Number
* Special Case: If a Petitioner elects “small” tax case, as well as “lien/levy” as case type, the “S” for small tax case should proceed the “L” for the case type.  For example, a docket number would be 12345-18SL.  (The “SL” suffix is unique; the “S” is not combined with any other suffix.  In any other case, if “S” and another suffix are both relevant, only the other suffix displays.)
* Suffix is always uppercase

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
