### ISSUE TITLE
Internal User: View Work Items Within Case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6627]
As a Petitions Clerk, Docket Clerk, and Senior Attorney (all internal users created to date), I need to view all work items within a case, in order to know what work has been done and what outstanding work items remain.

In addition to work items being displayed on work queues (already built), those work items also need to appear in the case detail page, and document detail page, so that ALL internal users can see what is going on within any given case.

## Pre-Conditions:
* Internal user is logged into the system
* A work item is associated with a case
* A message thread exists with multiple messages

## Acceptance Criteria:
* Only most recent message in work item thread appears in Section work queue
* Only most recent message in work item thread appears in individual work queue
* Only most recent message in work item thread appears in case detail
* Only most recent message in work item thread appears in document detail
* History/thread of work item is viewable
* User must be able to complete and/or forward any work item from the document detail 

## Notes
Moved to comments section below. 
(1/8) When user hits send they are returned back to the thing they were looking at previously. Leave as is for now. Most of the time users will likely be looking at their individual queue anyway. No need to spend time trying to force it.

## Tasks
- [x] Design the message appearance in the Case Detail (Kristen, Natalie)
- [x] Design the message thread in the document view (Kristen, Natalie)
- [x] Ensure consistency in fonts, table styles, etc by updating CSS (Eric)
- [x] Design how message text display in Work Queues 
- [x] Discuss the data entity model regarding Activity item vs Work item entities
- [x] Review the data points based upon the design and revise the entity relationship (if applicable)
- [x] Document test scenarios
- [x] Develop behavior-driven test scenarios
- [x] Modify the Case Detail screen and the Document detail screen (Cody)
- [x] make "complete" button work by updating the completedAt timestamp 
  -  [x] update views per design to add message input, complete button and cancel button (will)
  -  [x] create new sequence to call from view (will)
  -  [x] create new action to call from sequence (will)
  -  [x] add completedAt to workitem entity (will)
  -  [x] update views to filter out completedAt workitems (cody)
- [x] implement hover style over workitem rows (kris)
- [x] implement click event on workitem rows to expand row and include hover style (kris)
- [x] implement "no more messages" when completed with no more messages (will)
- [x] remove success message on complete and send (will)
- [x] review styles in relation to Figma updates (Eric)
- [x] Hide latest of history messages (Cody)
- [x] Create a new message on the work item when work item is assigned to the user (Cody)
- [x] button actions on the workItem need to reset on load of document detail
- [x] add date to the time on the workitem card (same format as date on case detail) (will)
- [x] when uploading files the selected file is not cleared when loading the form (Cody)
- [x] receivied not spelled right on case detail messages section, dateformat in case detail messages should be month/day/year, am/pm should be lowercase (check documentdetail view date might be wrong there) (will)
- [x] forward button on send to for workitem should be labelled Send (will)
- [x] work queue hover styles (revealing button) must work in Internet Explorer 11 (kris)
- [x] add all internalUsers to sendTo dropdown on workitem (will)
- [x] remove items assigned to anyone other than docketclerks or Unassigned from docketclerk queue (cody)
- [x] sort queues by most recently updated workitem (kris)
- [x] return to work queue after send and add a success alert (low priority) (will)

## Test Scenarios
- [x] As an internal user, after any party has uploaded a document, I shall be able to view the system generated message on the case details page
- [x] As an internal user, after a message was forwarded to the senior attorney, the message displayed shall be the latest on all of the case detail page, document detail page AND it will appear in the correct individual work queue and section work queue.
- [x] As an internal user, I shall be able to navigate to the document detail page via selecting the document link on the case detail work item
- [x] As an internal user, I shall be able to view a history of a pending message thread on the documents detail page
- [x] As an internal user, I shall be able to complete and add a message to a pending message thread
- [x] As an internal user, after a message thread has been marked as completed, it should no longer appear on the case detail page, document detail page, and correct individual work queue or section work queue. (Cody)

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
