### ISSUE TITLE
Docket Clerk: Forward/Assign work from Docket Section work queue to Individual work queue

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6628]
As a Docket Clerk, in order for a filing to be properly processed by the Court, I need all new documents to be routed to the appropriate Section Work Queue and then be assigned from Section work queue to an Individual work queue.

When an external user (Petitioner or IRS attorney) files/uploads any new document to a case (except for any documents filed to initiate a case), those documents need to be automatically routed to the Docket Section Work Queue. In order to get work from the Section work queue to individuals, Court users need the ability to forward/assign work items from the Section queue to an individual's queue.

## Pre-Conditions:
* Internal user is logged into the system.
* External user (Petitioner or IRS attorney) has filed a new document in a case.

## Acceptance Criteria:
* Incoming document is automatically routed to Section work queue 
* Internal users can see work items in the Section work queue.
* Internal users can forward/assign one or more work items (bulk assign) from the Section work queue to an individual Court user.
* Any work items that are forwarded/assigned to an individual user can be seen in the individual's work queue.
* The individual assignee's name should be easily viewable in the Section Work queue
* All assigned and unassigned work items should be easily identifiable in the Section Work queue
* When item is initially assigned a message thread is started on the document

## Notes:
* ALL new docs (except for Petitions) need to be routed to the Docket Section work queue.  
* ALL Petitions should be routed to the Petitions Section work queue.
* Assigned work queue items will remain in the Section work queue and have the individual's name associated with it.
* The Work item contains a messages collection each message has message text, created at date, assignee id, assigner/forwarder id
* Docket clerks should NOT need to send anything in bulk to users outside the docket section
* Neither sorting or filtering is part of this story. These things would come after MVP.
* Re: whitespace. Combo of max width, padding and margins can be used to maximize white space without compromising usability.
* (12/27) bold items that are unread
* (12/27) drop shadow not worth spending a day to figure out. Don't worry about for now.
* (12/28) don't need a success message, it will be distracting to the user. there are other success indicators in the screen. 

## Tasks
- [x] Design the Section Work Queue (UX Team)
- [x] Normalize Queue Design (Individual/Section) (UX Team)
- [x] Minor design tweaks (Natalie)
- [x] Document test cases/ scenarios based upon design
- [x] Update Individual Work Queue based upon Queue normalization
- [x] Develop Section Work Queue (leverage the Individual Work Queue) (Kris)
- [x] When the stipulated decision is uploaded need to assign the work item to the section
- [x] Determine the section model and how it fits into the other entities
- [x] Modify the persistence layer to store the data
- [x] Recreate work queue design in JSX and CSS and review with designers (Eric)
- [x] Display the number of work items next to the section / my queue tabs (Cody)
- [x] Verify that all values in the table are correct (Eric)
- [x] Show / hide blue bar based on selections (Eric)
- [x] My Queue not updating more than one when assigned from section queue - need to fix. (Eric)
- [x] Ensure header styles are a medium weight; field labels appear bolder than semi-bold; is there something else applied; tighten up blue underline (Eric)
- [x] Refactoring (Cody)

## Test Scenarios
- [x] as a docketclerk, I shall be able to switch between viewing my individual work queue and a "docket" section work queue
- [x] as either the taxpayer or respondent, after I upload any document except for a petition, a work item should be placed in the docket section work queue
  - AND an initial "a {documentType} filed by {party role} is ready for review" message shall be attached to the work item's thread (cody)
- [x] as any user in the docket section (dockerclerk1 and docketclerk2), I shall be able to select one or more work items on the section work queue and assign it to a docket clerk users's individual work queue (cody)
  - AND the docket clerks assignee's name shall be associated with the work item
  - AND the docket clerk assignee shall be able to login and view that work item on their individual work queue
  - AND a new message shall be added to the work item's messages containing some message of "a {documentType} filed by {party role} is ready for review" with an updated to and from.

## Definition of Done
- [x] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90%  
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer 
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
