### ISSUE TITLE
(1) File a Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6641]
As a petitioner, practitioner or court user, in order to file a case with the USTC, I need the ability upload a PDF petition package and add party and case data to the system.

As a petitioner, practitioner or court user, I navigate to the USTC public website so that I may file a petition with the court. I see the area in the site where I can begin my petition process, so I log in and upload my petition package and supply case information to the Court. After uploading my petition, I am able to confirm that my petition was uploaded and a case has been initiated.

## Roles: 
* Petitioner
* Practitioner
* Internal Court User (Filing on behalf of a paper-filing petitioner)

## Pre-Conditions:
* Petitioner, Practitioner and/or Internal User is logged into the system.
* Petitioner, Practitioner and/or Internal User can see where to begin a new case

## Acceptance Criteria
* Petitioner:
    * Receive warning about POAs, CPAs, etc. not being able to file for a third party ustaxcourt/ef-cms-flexion#645
* Petitioner and Practitioner:
    * Receive warning about timeliness of filing petition and are informed of options for mailing ustaxcourt/ef-cms-flexion#644
* Petitioner, Practitioner and Court User can:
    * indicate party type (Individual, Married, Business, etc.) and enter contact data for one (or more) petitioner(s)
    * upload a Petition and IRS notice (if any) as one document ustaxcourt/ef-cms#6498, ustaxcourt/ef-cms-flexion#786, ustaxcourt/ef-cms-flexion#654, ustaxcourt/ef-cms-flexion#588, ustaxcourt/ef-cms-flexion#488
    * supply case information (metadata) to the Court, including case type, notice date (if any), etc ustaxcourt/ef-cms-flexion#727, ustaxcourt/ef-cms-flexion#655
    * enter data for "innocent spouse," when applicable
    * easily tell whether or not their case is small or regular and note within the system which the case is.  
    * request a place of trial and can clearly tell which locations makes the most sense for them to request. 
    * review all case details prior to submitting
    * submit all case details, including the uploaded documents to the court. 
    * confirm that the petition was uploaded and a new case has been initiated
    * confirm that a docket number and case caption has been automatically generated and assigned to the case
* Court User:
     * Change filing date
     * Provide proof of case creation  that they can snail mail to paper-filing petitioner
     * Indicate whether parties would like paper service, electronic service or none
     * Create a case on behalf of a paper-filing petitioner
     * Scan a paper petition directly into the system without having to upload
     * Generate a summary of orders as part of the QC process

Stories not mapped:
ustaxcourt/ef-cms-flexion#966, ustaxcourt/ef-cms-flexion#780, ustaxcourt/ef-cms-flexion#676, ustaxcourt/ef-cms-flexion#591

## Notes
- **Can petition information be saved but not submitted?**  No
- **Will we allow a user to submit an incomplete petition (missing documents)?** A user will need to submit a Petition form and enter certain required metadata to start a case. If anything is missing from the content of the Petition, the Petitions Clerk will issue an Order asking for that information. 
- **What messaging (if any) is needed if a document is missing?** General error messaging telling them what required items are missing.
 - **When do we ask for SSN? After they start case?** As the petitioner is starting the case.  The SSN needs to be transmitted to the IRS with the Petition.
 - **User should be able to see and edit these personal details (email, phone) at an account level with a user management function, which would change what auto-populates in the start a case form.** Need to determine whether auto-populating contact information from registration is easy, or if we just ask them to re-enter it on the start a case form.  
- **Should we add in a scenario about a court user needing to change permissions/role (from a promotion or something)...?** Okay, but I think that is just controlled in Active Directory.
- **KL- When internal court users are initiating a case, will they be associating the case with a petitioner account - if the petitioner has registered for the system?** No, for MVP, if a petitioner sends in a paper petition, they will not be given or linked to an electronic account. 
- **Does court enter decimals?** Dollar amounts are already rounded on IRS notices.
- **Should we ask petitioner to indicate if/how they intend to initiate payment? Who is responsible for tracking these payments? Should we have a quick meeting with them to learn more about their business needs?** yes, if we cannot fully integrate with Pay.gov for MVP, I think we should ask petitioner how they are going to pay.
- **We talked about not including the petitioner's ability to see the case once it's been submitted; because changes are if they're having the practitioner do it, they'd never access the system anyway. But what about in the future? If they ever decide to come to the system, shouldn't they be able to see it? What data point or "key" would be use?** This is not MVP -- but, at some point in the future, we will need to be able to give someone electronic access to case that is already in progress.

## Tasks
- [ ] Discuss what is missing from the epic. Esp. in light of only looking at happy path.
- [ ] Plan user research needed to complete the epic
- [ ] Conduct any additional user research needed to complete the epic
- [ ] Create or update system and UX flows and diagrams (USTC e-file process, domain model, etc)
- [ ] Determine approach for form error handling
- [ ] ustaxcourt/ef-cms#6625 - Usability study test plan and screener for case form - petitioner, friends and fam (Valencia)

## Definition of Done 
- [ ] Usability testing, if applicable, is done
- [ ] Add UX flow docs to code repository
- [ ] Ensure Figma is archived as pages for each sprint; if we move away from sprints, maybe at the end of each epic?

## Research/Analysis
Petitions clerks work with paper and electronic documents throughout the day. They receive a batch of 30 items each morning. Items received each day must be completed on that day. Sometimes work does carry over to the next day, but those items are not high priority items

In addition to processing petitions, clerks also spend quite a bit of time on the phone answering questions from petitioners, and transferring calls to other USTC personnel when a petitioner needs additional information or guidance.

When processing a petition, clerks must check to see if filing fees have been paid. Clerks have to be mindful of important alerts/memos regarding rule changes that apply to the processing of petitions. They may receive 2-3 rule change memos per week that may affect their work.

## What hasn't been built yet?

- **Petitioner: Warning of timeliness and option to mail** ustaxcourt/ef-cms-flexion#644

- **Petitioner: Warning that POAs, CPAs, etc. cannot file petitions**#645

- **Petitioner: PII and Evidence warning needed at each upload space and before submitting case to Court (universal)** ustaxcourt/ef-cms#6526 and ustaxcourt/ef-cms#6527 (should we combine into one?)

- **Petitioner: Enter data for multiple parties, select party type** ustaxcourt/ef-cms#6559 {need to break into 3 stories}
    * Pick a Party Type (Myself; Myself & Spouse; Estate; Corporation; Partnership; Trust; Other)
    * If “Corporation” is selected as the Party Type, need to provide additional (MANDATORY) upload space for Ownership Disclosure Statement [Note: ODS will upload as a separate docket entry when case submitted]
    * Enter/confirm contact information (Name, address, phone, email, TIN) -- Contact information fields should be intuitively driven from selection of Party Type [Note: Need to develop required fields/format for each Party Type]
   * Domestic and international addresses

- **Petitioner: Automatic creation of Case Caption based on Court rules by Party Type** ustaxcourt/ef-cms#6565

- **Petitioner: Clean up petition form** ustaxcourt/ef-cms#6567
    * "streamline dashboard design" (per Kristen 1/15)
    * Opportunity to cancel/delete transaction - "Are you sure?"
    * Doc upload success message - include doc type name, remove second line and add an "x" to clear the message
    * Doc upload error message
    * File size and type limitations with help text
     
- **Petitioner: SSN/EIN/TIN Encryption** ustaxcourt/ef-cms-flexion#649

- **Petitioner: yes/no logic of form** ustaxcourt/ef-cms-flexion#588
    * IRS notice; Case Type for no notice

- **Petitioner: Innocent Spouse Case Type** ustaxcourt/ef-cms-flexion#650
    * If “Innocent Spouse” is selected for Case Type, user needs to be prompted to enter additional information re: other spouse 

- **Petitioner: field-level validation (wait until usability testing done to determine)**  ustaxcourt/ef-cms-flexion#651

- **Practitioner: Ability to create case on behalf of a petitioner** ustaxcourt/ef-cms-flexion#488

- **Practitioner: Dashboard** ustaxcourt/ef-cms-flexion#652
- **Court User: Creating a case on behalf of paper-filing petitioner** ustaxcourt/ef-cms#6563
   * Same interface as petitioner except doesn't need notifications and warnings
   * Ability to change date -- date uploading may NOT be date that needs to be associated with document

- **Court User: Generate paper confirmation that they can print and mail** ustaxcourt/ef-cms-flexion#653

- **Petitioner/Practitioner: New case indicator on dashboard** ustaxcourt/ef-cms-flexion#590
