### ISSUE TITLE
Upload PDF documents to the system

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6648]
As a Judge or other Court User, in order to issue an order or other document that I've generated outside of the system, I need the ability to upload a PDF document to the system.

## Pre-Conditions
* Court person has created a document in PDF format outside of the system

## Acceptance Criteria
* Court User can upload a PDF document to the system
* Uploaded PDF document should be uploaded to the "Draft Documents" tab of the system
* Once uploaded, a PDF document should be treated the same as a document created in the system (be signed, send messages, create docket entry, served, etc.)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Allow all functionality that we have for draft documents to remain
* For MVP, don't worry about direct scanning

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical  (all functionality internal)
 - [x] New screens have been added to pa11y scripts (William/Rachel ustaxcourt/ef-cms-flexion#4373)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (William/Rachel/Kris ustaxcourt/ef-cms-flexion#4373)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (William/Rachel ustaxcourt/ef-cms-flexion#4373)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (all screens internal)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
