### ISSUE TITLE
Petitions: Create Order in the system and save to docket record 

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6649]
As a Petitions Clerk, in order to notify a Petitioner that they need to provide additional information, I need the ability to issue an order in the system.

When a Petitioner files a Petition, it is often missing some of the information that the Court needs.  To direct the Petitioner to file/submit the missing information, the Petitions Clerks will issue an Order to Petitioner.

## Pre-Conditions
* Petitions Clerk has received a petition that does not have all the information needed

## Acceptance Criteria
* Petitions Clerk can create an order in the system from a system-generated template
* Order template contains standard content derived dynamically from system data
* Petitions Clerk clerk type order content into a free form text field
* Petitions Clerk can perform basic content editing, such as bolding, underline and italics. {Need to define exactly what "basic" is so we're all on the same page}
* Petitions Clerk can preview the document while editing
* Petitions clerk can save completed order
* A docket entry (is created, can be created) for the newly created order (Can be simple language "Order"; Will be handled in another story).
* The docket entry should link to the PDF
* Need ability to copy and paste with out stripping formatting (formatting to be defined)

## Notes
* This story does not include save and continue function (Draft State). Save and continue/Draft state is needed, but will be handled in another story. 
* Court users cannot edit header content or order template
* Jessica will put together a list of the different types of Orders and decisions
https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing
* The order is generated as a PDF. This does not require a cover sheet
* With pasting from WP, it didn't retain the formatting. Court will be required to use Word. 

## Tasks
- [x] List of requirements from a tech text editors (Kristen)
- [x] List of rich text editors: feature compatibility 
- [x] Set of example order PDFs (Jessica)
- [x] POC of in-browser PDF generated from rich text editor content
- [x] Add Create Order button, route, and basic screen so we have somewhere to test possible text editors (Rachael ustaxcourt/ef-cms-flexion#2150)
- [x] Customize toolbar for Quill editor (Rachael ustaxcourt/ef-cms-flexion#2162)
- [x] Fix underline (Rachael, William)
- [x] Set default font on PDF to Times New Roman (Rachael ustaxcourt/ef-cms-flexion#2167)
- [x] Test orders with and actual Word document (Mariah)
- [x] Isolate styles from rest of application (Kris)
- [x] Fix multiple new lines
- [x] Generate PDF server side (William ustaxcourt/ef-cms-flexion#2176)
  - [x] Refactor Utility into Use Case (William ustaxcourt/ef-cms-flexion#2176)
- [x] Get lambda layer configured correctly (William and Rachael)
- [x] Print - set up print media rules to produce headers on correct pages (Kris, Rachael ustaxcourt/ef-cms-flexion#2178)
- [x] Integrate, so working on dev (William ustaxcourt/ef-cms-flexion#2217)
- [x] Handle pdf binary type (William ustaxcourt/ef-cms-flexion#2218)
- [x] Clean up PDF formatting (Rachael, Kris)
  - [x] insert spaces for tabs (#2187)
  - [x] increasing/decreasing font size is not working (#2187)
  - [x] footer margin on every page after the first (#2187)
  - [x] docket number dynamically generated from case detail (#2188)
  - [x] docket number on right side of first page header, clean up formatting on first page header
- [x] Clean up Create Order view (Rachael ustaxcourt/ef-cms-flexion#2193)
- [x] Create entity for orders (Rachael ustaxcourt/ef-cms-flexion#2197)
- [x] Create Order-Type Modal Dialog (Kris, Rachael ustaxcourt/ef-cms-flexion#2222 ustaxcourt/ef-cms-flexion#2224 ustaxcourt/ef-cms-flexion#2226)
  - [x] validate modal using OrderWithoutBody entity (Rachael ustaxcourt/ef-cms-flexion#2228)
- [x] Show form cancel modal when Cancel button is clicked from the Create Order page (Rachael ustaxcourt/ef-cms-flexion#2206)
- [x] Create actions and sequence to submit order(William ustaxcourt/ef-cms-flexion#2232)
- [x] Move order template into a separate html file that can be imported; fix associated jest issues (Rachael ustaxcourt/ef-cms-flexion#2231)
- [x] On Refresh direct to case detail with modal (William ustaxcourt/ef-cms-flexion#2236)
- [x] ~Update success alert if needed~
- [x] If form is not pristine regenerate on submission (William ustaxcourt/ef-cms-flexion#2236)
- [x] Case journey test (Rachael ustaxcourt/ef-cms-flexion#2244)
- [x] Fix font issues on generated PDF on dev (Rachael ustaxcourt/ef-cms-flexion#2244 ustaxcourt/ef-cms-flexion#2248 / William ustaxcourt/ef-cms-flexion#2260)
- [x] Force order title to all caps in the PDF (Rachael ustaxcourt/ef-cms-flexion#2234)
- [x] pa11y test (Rachael ustaxcourt/ef-cms-flexion#2252)
- [x] "Filed By" column should be blank (William ustaxcourt/ef-cms-flexion#2261)
- [x] Link from docket record to Order Document Detail page - the success message “Your filing has been successfully submitted” is showing on Document Detail (William ustaxcourt/ef-cms-flexion#2261)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
