### ISSUE TITLE
Petitions Clerk & Docket Clerk: Manually add a deadline to a case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6650]
As a Petitions Clerk or Docket Clerk, in order to keep track of items that require follow up, I need the ability to add a deadline at the case level. 

Whenever the Court issues an order to the parties, that Order will contain some sort of due date.  The Petitions Clerk or Docket Clerk (whoever is serving the Order) needs the ability to enter a deadline in the system at the case level.  That deadline should be viewable when viewing the case, as well as somewhere in the aggregate with all other due dates on all cases.

## Pre-Conditions
* Something in a case has a deadline

## Acceptance Criteria
* Petitions Clerk or Docket Clerk can manually add a deadline at the case level
* Any CMS user can see within a case that a deadline exists
* Petitions Clerk or Docket Clerk can edit a previously entered deadline
* Petitions Clerk or Docket Clerk can remove a deadline from a case

## Notes
* Due dates should be viewable within a case, as well as somewhere in the aggregate with all other due dates on all cases. ustaxcourt/ef-cms#6651 

## Tasks
- [x] 1 dynamno persistence methods (William ustaxcourt/ef-cms-flexion#2267)
- [x] 2 entity (William ustaxcourt/ef-cms-flexion#2267)
- [x] 3 validation sequence (William ustaxcourt/ef-cms-flexion#2267)
- [x] 4 create sequences (William ustaxcourt/ef-cms-flexion#2267)
- [x] 5 update sequence (William ustaxcourt/ef-cms-flexion#2267)
- [x] 6 delete sequence (William ustaxcourt/ef-cms-flexion#2267)
- [x] 7 journey test for case deadlines (William ustaxcourt/ef-cms-flexion#2267)
- [x] 8 case detail view of case deadlines (Rachael ustaxcourt/ef-cms-flexion#2270)
- [x] 9 create case deadlline modal (Rachael ustaxcourt/ef-cms-flexion#2270)
- [x] 10 update case deadline modal (Rachael ustaxcourt/ef-cms-flexion#2270)
- [x] 11 delete case deadline modal (Rachael ustaxcourt/ef-cms-flexion#2270)
- [x] 12 Case Deadline sort (William ustaxcourt/ef-cms-flexion#2274)
- [x] 13 Store Case Deadlines away from case entity to prevent flash (Kris ustaxcourt/ef-cms-flexion#2275)
- [x] 14 Success messages (William ustaxcourt/ef-cms-flexion#2274)
- [x] 15 Case Deadlines view on external case detail view (Rachael ustaxcourt/ef-cms-flexion#2277)
- [x] Updates to table column order and font (Kristen ustaxcourt/ef-cms-flexion#2286)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (William ustaxcourt/ef-cms-flexion#2283)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (#2271 ustaxcourt/ef-cms-flexion#2279)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
