### ISSUE TITLE
Court User: Aggregate of deadlines

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6651]
As a court user, so that I can have a broad overview of all deadlines in the system, I need a place where I can see all deadlines aggregated. 

## Pre-Conditions:
* A deadline exists in at least 1 case

## Acceptance Criteria:
* A Court User can see in one place all of the due dates in all of the cases system-wide
* The information displayed in this aggregated area should include: docket number, due date, text of what's due [Note: Text should match what's displayed on case detail page]
* Events with the same due dates should be grouped together by date, and then displayed in docket number order (oldest to newest)
* User should be able to hyperlink from due date to the case detail page (maybe through hyper-linked docket number?)

## Tasks
- [x] 1 Add Reports tab to global navigation header and update computed to show it for correct users (Rachael, Kris ustaxcourt/ef-cms-flexion#2850)
  - [x] 1a Add hover state and Deadlines link to header Reports tab (Rachael, Kris ustaxcourt/ef-cms-flexion#2850)
- [x] 2 Create new route and empty view for all case deadlines (William ustaxcourt/ef-cms-flexion#2849)
- [x] 3 Find React calendar component with option to choose a date range and add to the view (Rachael ustaxcourt/ef-cms-flexion#2859)
- [x] 4 Create all case deadlines table view (William ustaxcourt/ef-cms-flexion#2852)
- [x] 5 Create persistence method, endpoint, and interactor for getting all case deadlines (William ustaxcourt/ef-cms-flexion#2849)
- [x] 6 Create sequences and actions to get the case deadlines from the backend into the view (William ustaxcourt/ef-cms-flexion#2849)
- [x] 7 Create computed to filter all case deadlines by date and format deadlines and date header  (William ustaxcourt/ef-cms-flexion#2852)
- [x] 8 Add multiple case deadlines on different dates to seed data (Rachael ustaxcourt/ef-cms-flexion#2861)
- [x] 9 Refactor nav header to use USWDS components/styles (Kris, William, Rachael ustaxcourt/ef-cms-flexion#2869)

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable)

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael ustaxcourt/ef-cms-flexion#2884)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael ustaxcourt/ef-cms-flexion#2884)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
