### ISSUE TITLE
(8) Calendaring of a trial session

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6673]
As a Calendar Clerk, so that cases can get scheduled for trial in a timely manner, I need the ability to see which cases are ready for a trial session and schedule them. 

As a Calendar Clerk, I am responsible for managing trial sessions and ensuring cases are scheduled for trial in a timely manner. Each year, the Court secures locations throughout the United States for which trial sessions will be scheduled. Because trials do not always take place in the same location, I need to look at all cases that are ready for trial at all of the Court's available trial locations (75 nationwide) and determine what the best locations will be. In addition to our main courthouse in Washington DC, the Court rents space in 37 trial locations, and borrows space in the other 37.

Once I have determined when and where the trial sessions will take place, I enter them into the system so that I may assign cases to the trial session. 

Now that all of the trial sessions have been set up in the system, I check to see which cases are ready for trial and assign them to the session. I usually assign 100-125 cases to each trial session five (5) months before the trial session is scheduled to take place.  Parties in the case are then notified that action has been taken in the case and they can log into the system to see details regarding their trial, as well as easily access the case for which the trial has been scheduled.

After a trial session is scheduled, cases may be manually added or removed from the trial session.

Roles: 
* Calendar Clerk
* Docket Clerk

## Pre-Conditions
* There are cases in the system ready for trial.

## Acceptance Criteria
* System auto-updates a case status to "Ready for Trial" when two criteria have been met: An answer has been uploaded and a certain number of days has passed since the petition was filed (Done)
* Court users can print a report that will help them determine when and where to schedule trial sessions. Report includes data regarding how many cases are ready per trial location, what types of cases they are, the last time a session was held in a trial location, who the judge was and more. (Done)
* Court users can see a list of how many cases (regular and small) are ready for trial in each of the Court's 75 trial locations. (Done)
* Court user can enter trial session details into the system (Done)
* Court user can set a max limit on how many cases can be scheduled for each trial session (Done)
* Court user can see a list of all trial sessions entered into the system (Done)
* Court users can view which cases are ready for a specific trial session (Done)
* User can perform a batch auto-scheduling of each trial session of cases that are in a "Ready for Trial" status (Done)
* System auto-schedules cases to a trial session based on priority logic, including FIFO, white cards,  and case type 
* Court users can put a "hold" on a case, indicating that it should not be auto-scheduled for a trial session. 
* System excludes "holds" during the auto-scheduling process
* Court users can view a list of all cases that have a "hold" and sort or view them by date range and/or docket range
* Court can indicate cases that are "white card." 
* System includes "white cards" during the auto-scheduling process, even if they do not meet the criteria for auto-scheduling
* Court can manually schedule any case for trial, even if it does not meet the criteria for the auto-scheduling
* Court can manually schedule a case for a trial session after that session has been scheduled. Max rules should apply to a manually scheduled trial session.
* Court can remove a case from a trial session
* Once a case has been scheduled for a trial session, parties in the case are notified, can log in and see trial session details

New AC (Added 9/26/19):
* User has the ability to easy filter or sort data so that it's most usable to them
* Calendar clerk has the ability to perform a QC process on cases that are ready for trial
* Trial session is automatically set to closed based on criteria present in the system
* Calendar Clerk has a dashboard that's personalized to their role

## Notes
 - **What is the title of someone who works in the calendar section? A calendar clerk?** Yes
- **How will users query the system to see all cases ready for trial at a certain location? Search function? Filtering of status and location?** Status and location.
- **Supporting bulk assigned of cases to a trial session or only individual assignment?** for MVP, whichever is easiest
- **Would notice of trial ever need to be served to parties by mail/on paper if that is their preferred method of communication**? yes
- **We also heard a big need from users that they want to filter out/not see cases that are scheduled for trial that have been settled. (mk - is this for calendar folks, judges or both?)** yes, as cases settle/close, they should fall off of the calendar list

## Tasks
- [ ] Discuss what is missing from the epic. Esp. in light of only looking at happy path.
- [ ] Conduct any additional user research needed to complete the epic
- [ ] Create or update system and UX flows and diagrams (USTC e-file process, domain model, etc)
- [ ] Determine approach for form error handling
- [ ] Plan and conduct usability testing

## Definition of Done 
- [ ] Add UX flow docs to code repository
- [ ] Ensure Figma is archived as pages for each sprint; if we move away from sprints, maybe at the end of each epic?
