### ISSUE TITLE
Practitioner & IRS Attorney login (Test run)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6683]
As a court user, so that I can give a pracitioner and IRS attorney access to the system, I need the ability to create those users in Cognito with a temporary password. 

The Practitioner and IRS attorney should then be able to log in by resetting their temporary password.

## Acceptance Criteria
* Court can create a practitioner user in Cognito (back door)
* Cognito sends an email to the practitioner
* Practitioner can login by resetting their PW, which was created by the court when set up in Cognito

Next steps:
* Create list of users, import into the CMS (bulk load, include name address and status field)
* Mock UI to add an individual user (name, address, status field)
* Generate user in cognito
* Generate email to users with some content and link back to login
* Users get temporary password , can change password and get logged in
* Prevent users from accessing the system if their status changes

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* We want to use this group as test subjects
* If customized email content is needed, we'll create another story
* 30K active attorneys practicing with the court

## Tasks
- [x] 1 Create practitioner user in cognito and make sure they get an email, can reset their password, and can login to the system (Rachael)
- [x] 2 Create respondent user in cognito and make sure they get an email, can reset their password, and can login to the system (Rachael)
- [x] 1 Create endpoint to add user to cognito and dynamo (Rachael ustaxcourt/ef-cms-flexion#4626)
- [x] 2 Create script to load in users from CSV and call the endpoint to add each one (Rachael ustaxcourt/ef-cms-flexion#4633)
- [x] 3 Create view to add a single user (view, submit sequence to hit endpoint) (Matt)
- [x] 4 Figure out email stuff - customized cognito email; make sure the flow works correctly with user confirming email and changing password (Rachael ustaxcourt/ef-cms-flexion#4633)
- [x] 5 Create a role for users who are disallowed from using the site and a dashboard with a message saying their account is inactive (Rachael ustaxcourt/ef-cms-flexion#4637)
- [x] 6 Create endpoint to update user in cognito and dynamo (for changing their role to be inactive) (Rachael ustaxcourt/ef-cms-flexion#4639)
- [x] 7 UI to load attorney user list and go to an edit form (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment
