### ISSUE TITLE
Practitioner: Ability to create case on behalf of a petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6689]
As a Practitioner, in order to file a Tax Court Petition on behalf of my client, I need the ability to create a case on behalf of a Petitioner.

Practitioners who are admitted to practice before the Court need to be able to initiate a case on behalf of a client.  As a result, the system should allow a Practitioner to create a case on behalf of a Petitioner.

## Pre-Conditions
* Practitioner is logged into the system

## Acceptance Criteria
* Practitioner can see how to start a case on their dashboard [Note: need Practitioner dashboard]
* Practitioner can create a case on behalf of taxpayer(s)
* After submitting a case, the practitioner information (name, address, email, phone, bar number) associated with the case is able to be viewed by the parties and internal court user
* After submitting a case, a practitioner can access the case and all of the case details

## Tasks
 - [x] Create practitioner users in Cognito (with hardcoded bar numbers, contact info) (Cody ustaxcourt/ef-cms-flexion#1203)
 - [x] Create practitioner dashboard view (same as petitioner but no sidebar) (Cody ustaxcourt/ef-cms-flexion#1206)
 - [x] Modify start case form view to change labels based on user (Rachael ustaxcourt/ef-cms-flexion#1212)
 - [x] Create/Modify the createCaseInteractor to save the practitioner info (Cody ustaxcourt/ef-cms-flexion#1210)
 - [x] Add petitioner counsel to the contacts views (William ustaxcourt/ef-cms-flexion#1209)
 - [x] Trial Information and Petition Details is supposed to show up for the Practitioner and Petitioner (Cody ustaxcourt/ef-cms-flexion#1207)
- [x] The email address field for the primary contact needs to be hidden throughout - It would be the practitioner's email since they are the logged in user - and not necessarily the petitioner (Rachael ustaxcourt/ef-cms-flexion#1223)
- [x] Estate without an Executor / PR and Corporation - In Care Of - need to remove the helper text - (Your Name) (Rachael ustaxcourt/ef-cms-flexion#1223)
- [x] Can we hide the Secondary Contact header on Case Info tab if it is blank? (Rachael ustaxcourt/ef-cms-flexion#1223)
- [x] Practitioner info not populating on Case Detail page; I logged in as Practitioner 2- the address and phone number didn't populate on Case info tab, only the name and email address (Rachael, Cody)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
