### ISSUE TITLE
Petitions Clerk/Supervisor:  Assign Petition to Petitions Clerk (2.7)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6690]
As the Petitions Clerk/Supervisor, in order to keep work moving, I need to assign work items from the Section queue to an individual Petitions Clerk.

All new Petitions should be automatically routed to the Petitions Section work queue as a new work item.  In order to assign each work item to a specific Petitions Clerk, the Petitions Clerk/Supervisor needs to be able to forward or assign the work queue item to a specific Petitions Clerk.  Once assigned to a particular Petitions Clerk, the work item shows up in that individual’s work queue (as well as remains in the section queue).

## Pre-Conditions:
* Petitioner has submitted a new case to the Court.
* Petitions Clerk/Supervisor is logged into the system.

## Acceptance Criteria:
* Incoming Petition is automatically routed to the Petitions Section work queue
* Petitions Clerk/Supervisor can see work items in the Section work queue.
* Petitions Clerk/Supervisor can forward/assign one or more work items (bulk assign) from the Section work queue to an individual user who is a member of the Petitions Section.
* Any work items that are forwarded/assigned to an individual user can be seen in the individual's work queue.
* The individual assignee's name should be easily viewable in the Section Work queue
* All assigned and unassigned work items should be easily identifiable in the Section Work queue
* When work item is created (by being routed to Section queue) a message thread is started on the document

## Notes:
* Use same view for this story as we did for Docket. 
* The section and individual work queues have been updated and are consistent with style guide

## Tasks
- [x] 1. Update Individual and Section work queues views to be consistent with updated work queue design (needs to look like the Docket Work Queue)(Eric)
- [x] 2. Add more Petitions Clerk users (will)
- [x] 3. modify createCase interactor to create a workitem for the petition section (Cody/Will)
- [x] 4. Modify the cerebral actions, sequences, states for Petitions Clerk from Docket Clerk (Kris)
- [x] 5. create business cases (Will/Eric/Cody/Kris)
- [x] 6. fix createCase return object - remove all trialCities from submit (except the one they selected) (will)
- [x] 7. refactor caseTitle to be a function on the Case entity not code in the createCase interactor (will)
- [x] 8. write caseJourney/business tests (cody)
- [x] 9. stop event bubbling on row clicks in work queue tables (will)

## Business Tests
- [x] petition clerk logs and is routed to dashboard with "My Queue" that displays all workitems assigned to the user
- [x] petition clerk can select the section view and see all workitems in a "new" status
- [x] petition clerk can select multiple work items and assign to a given petitions section user
- [x] as a petitionsclerk, I shall be able to switch between viewing my individual work queue and a "petition" section work queue
- [x] When a case is created, a work item should be placed in the petition section work queue
  - AND an initial "a {documentType} filed by {party role} is ready for review" message shall be attached to the work item's thread
- [x] as any user in the petitions section (petitionsclerk1 and petitionsclerk2), I shall be able to select one or more work items on the section work queue and assign it to a petitions clerk users' individual work queue
  - AND the petitions clerks assignee's name shall be associated with the work item
  - AND the petitions clerk assignee shall be able to login and view that work item on their individual work queue
  - AND a new message shall be added to the work item's messages containing some message of "a {documentType} filed by {party role} is ready for review" with an updated to and from.

 ## Definition of Done
- [ ] acceptance criteria have been met
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
