### ISSUE TITLE
Petitions Clerk: Send Petition to Holding Queue for Service on IRS (2.9)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6692]
As a Petitions Clerk, in order to indicate that I have reviewed a Petition and it is ready to be served on the IRS, I need to send the Petition to a holding queue for batch service on the IRS.

Once the Petitions Clerk fully reviews the Petition and saves all case metadata, the Petitions Clerk should indicate that the case is ready to be served on the IRS.  Upon making that indication, the case status should be changed from “New” to “Batched for IRS” and automatically send the Petition to a holding queue to await service on the IRS (batch service at 3pm). Upon sending the Petition to the holding queue, the work item is no longer visible in the inbox.  

## Pre-Conditions:
* Petitions Clerk is logged into the System
* Petitions Clerk has reviewed and saved any changes to the case/metadata

## Acceptance Criteria:
* Petitions Clerk can see how to send the case to the IRS holding queue
* The Petitions Clerk should not be able to prematurely or accidentally send to IRS holding queue
* Upon sending the case to the IRS holding queue, it should be clear to the user that the petition is in the IRS holding queue 
* Upon sending the case to the IRS holding queue, the petitions clerk should know no futher action is needed on the work item

## Research/Analysis Notes
Petitions clerk task summary
* Petitions clerks receive 30 items at one time each day. If they complete their 30 items they may go to the mail bin and get more items to work on.
* Sometimes a clerk will want to reference a submitted petition before IRS service is made, or in some cases make a minor edit

Petitions Clerk Needs:
•	The ability to review work prior to IRS service

Petitions Clerk Challenges
•	Recalling documents with incorrect information prior to service
•	Correcting information after IRS service

Petitions Clerk Goals
•	The ability to recall a submitted petition prior to IRS service to make changes without submitting an order, or reference information on the petition for a similar petition they need to process

## Tasks:
- [x] 1. Design out the business workflow (Sarah)
- [x] 2. Design out the user interface (Sarah)
- [x] 3. Create business test scenarios (Kristin)
- [x] 4. add setBatchedForIRS to Case entity prototype to set the case status to "Batched for IRS" and make case statuses a constant (will/cody)
- [x] 5. add sendToIRSBatch interactor that invokes setBatchedForIRS, validates, then saves case (will/cody)
- [x] 6. Add new interactor to web-client appctx then disconnect existing sendToIRS action from the sendToIRS interactor and rename to something more apropos like sendToIRSBatchAction then connect it to the new interactor. Same with proxy. Same with sequence. (cody/will)
- [x] 7. modify the CaseDetailEdit jsx to have new button and modal per design. Add sequences/actions for modal if necessary.  Connect Yes on modal to the renamed sendToIRSBatch sequence. note: updateCase is called before you open the modal, then sendToIRSBatch on "Yes" in modal. (eric/kris)
- [x] 8. remove old sendToIRS button from case detail view. (will)
- [x] 9. update workitem on petition document in the interactor
- [x] 10. create DocketRecord as new collection on Case and figure out how to add entries (will)
- [x] 11. update computed for hide/show button (Recalled or Batched for IRS and Petition) (kris)
- [x] 12. remove the message from the success alert after serve to irs (kris)
- [x] 13. add in validation before send to irs (eric/will/cody/kris)

## Business Tests
- [x] Petitions clerk sees the option to send petition to IRS Holding queue when a case is in the "New" status

When petitions clerk selects "Serve to IRS" 
- [x] Petitions clerk can see and correct any errors with the case metadata AND petitions containing errors are not added to IRS holding queue
- [x] Valid changes to case metadata are saved in the system 

When petitions clerk selects "Serve to IRS" AND all case metadata is valid, the petitions clerk can
- [x] Select "Yes, serve" to add petition to the IRS Holding Queue, and 
- [x] petition's case's status is changed to "Batched for IRS" 
- [x] AND the work item is removed from the petitions clerk's individual and petitions section work queue 
- [x] AND the petitions clerk returns to their individual work queue
       
- [x] Select "No, take me back" to not add the petition to IRS Holding queue and
- [x] petition case status is unchanged 
- [x] AND the petition work item remains in the petitions clerk's individual work queue and the petitions section work queue 
- [x] AND petitions clerk remains on the Petition Document Detail page 

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
