### ISSUE TITLE
Petitions Clerk/Supervisor:  View/Edit cases in IRS Holding Queue (2.10)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6693]
As a Petitions Clerk or Supervisor, I need to see how to view/edit cases in the IRS holding queue, so that I can make any necessary corrections before the case is served on the IRS.

Once a case is sent to the IRS holding queue, and before it is batch served on the IRS at 3pm that afternoon, there might be a reason a Petitions Clerk or the Petitions Clerk Supervisor needs to revisit that case.  The Court user should be able to easily see which cases have been sent to the IRS holding queue and review them.  If necessary, the Petitions Clerk or Supervisor should be able to pull the case out of the holding queue and back into the their work queue. Any case pulled out of the IRS holding queue should not be served on the IRS until placed back in the IRS holding queue.

## Pre-Conditions:
* Case is in IRS holding queue

## Acceptance Criteria:
* Petitions Clerk or Supervisor should be able to see which cases are in the IRS holding queue 
* Petitions Clerk or Supervisor can view the case and case metadata while the case is in the IRS holding queue
* No changes to a case or metadata can be made while it is in the IRS holding queue
* Petitions Clerk or Supervisor can pull the case out of the holding queue and back into the Petitions Clerk Individual Work queue and the Petitions Section work queue.
* Sent items in the petitions clerk sent box should only be visible for seven days
* Petitions clerk or supervisor can easily see what petitions have been recalled and be able to send them back to the IRS holding queue.
* No other internal user (no one outside of Petitions can change the status) can pull the case from the IRS holding queue and back into the Individuals and Petitions Section work queue. 

## Design Notes:
* (2/1/19) Recalling the document will not create another work item. Instead, the recalls will be noted in the document history.
* (2/1/19)Send button will not mark item as complete, because it can be recalled. 

## Research/Analysis Notes
Petitions clerk/supervisor task summary
* Sometimes a clerk will want to reference a submitted petition before IRS service is made, or in some cases make a minor edit

Petitions clerk/supervisor needs:
•	The ability to review work prior to IRS service

Petitions clerk/supervisor challenges
•	Recalling documents with incorrect information prior to service

Petitions clerk/supervisor goals
•	The ability to recall a submitted petition prior to IRS service to make changes without submitting an order, or reference information on the petition for a similar petition they need to process

## Tasks:
- [x] 1. Design out the business workflow (Kristen)
- [x] 2. Design out the user interface (Kristen)
- [x] 3. Create business test scenarios (Eric)
- [x] 4. create new interactor to retrieve workItems for the "sent" box on the individual petitions clerk work queue -> completedAt in last 7 days or case status is Batched for IRS (cody)
- [x] 5. create new interactor to retrieve workItems for the "sent" box on the petitions section work queue -> completedAt in last 7 days or case status is Batched for IRS (cody)
- [x] 6. make necessary changes to persistence to allow querying by the business criteria (completedAt in last 7 days or case status is  Batched for IRS) (cody)
- [x] 7. new interactor to recall a work item setting status on the case to Recalled and creating a new workitem on the petition document (will)
- [x] 8. change the getWorkItems and getWorkItemsBySection interactors to include status of "Recalled"
- [x] 9. new sequence and action to populate the "sent" queue for an individual (getCompletedWorkItemsForUser) (kris)
- [x] 10. new sequence and action to populate the "sent" queue for the section queue (getCompletedPetitionWorkItemsBySection)
- [x] 11. new sequence and action to recall a workItem (recallWorkItem) (will)
- [x] 12. computed (?) to make view readonly for the petition document detail (or just a different view) (Eric)
- [x] 13. add recall button to the view only petition document detail and hook up to modal and then the recallWorkItem sequence on OK (kris/eric)
- [x] 14. view for new "sent" workitems for an individual (kris)
- [x] 15. view for new "sent" workitems for the section (kris)
- [x] 16. new modal for the recall button (kris)
- [x] 17. add new actions - getSentWorkItemsForSection, getSentWorkItemsForUser, getWorkItemsForSection, getWorkItemsForUser (will)
- [x] 18. read only version for "batched for irs" (will)
- [x] 19. remove complete and sendTo buttons from the isInitializeCreate workitem on the petition (will/kris/eric)
- [x] 20. add test data for "last seven days"(will/kris/eric)
- [ ] 21. Fix cerebral test framework
- [x] 22. fix position of send to holding queue button (kris)
- [x] 23. default to document tab in recalled status (will)
- [x] 24. red clock icon in recalled (kris/will)
- [x] 25. add a class to go with tab-link to change size of document info and messages tabs to same size as h3 (Eric)

## Business Tests
As a petitions clerk when I click Serve to IRS  
- [x] Assign petition creation work item to IRS Batch 
- [x] Add new message to petition creation work item ("Petition batched for IRS")
- [x] Case status is change to Batched to IRS 
- [x] Remove petition creation work item from individual work queue inbox 
- [x] Remove petition creation work item from section work queue inbox 
- [x] add petition creation work item to individual sent box
- [x] add petition creation work item to section sent box

- [x] As a petitions clerk, I can view all petition work items I have completed within the last 7 days in my individual work queue Sent box except work items with the case status Recalled 
- [x] As a petitions clerk, I am able to identify the work items that are in the IRS Holding Queue 
- [x] As a user in the petition section, I  can view all petition work items completed by any petitions clerk within the last 7 days except work items with the case status Recalled in the Petition Section work queue Sent box AND I am able to identify the work items that are in the IRS Holding Queue 

- [x] No user can complete the petition creation work item (it will only be completed when the petition is served to IRS as part of the automated batch process) 
- [x] Petitions Clerk cannot send/forward the petition creation work item to any user outside of the Petitions Section 

As a user not in the petitions section, when I navigate to the Petition Document Detail Page AND the case is in the status "Batched for IRS" 
- [x] I can view the case metadata 
- [x] I cannot edit the case metadata 
- [x] I cannot see the option to "Recall" the petition   

As a user in the petitions section, when I navigate to the Petition Document Detail page AND the case is in the "Batched for IRS" status,
- [x] I can see the case metadata 
- [x] I cannot edit any case metadata
- [x] I can see the option to Recall the petition from the IRS holding queue

As a user in the petitions section, when I select "Recall" 
- [x] I can confirm to recall the petition by selecting "Yes, recall" 
- [x] AND petition's case status is changed to "Recalled" 
- [x] AND the petition work item is assigned to me with a new message ("Assigned to [username}") AND is visible in my individual Work Queue Inbox and the Petitions Section Work Queue Inbox
- [x] AND I am returned to my individual Work Queue Inbox screen 

As a user in the petitions section, when I select "Recall" 
- [x] I can cancel this action  by selecting "No, keep in batch" 
- [x] AND the petition remains in the holding queue with the case status "Batched for IRS"
- [x] AND I remain on the Petition Document Detail page
- [x] AND the option to "Recall" is replaced with option to "Serve to IRS" 

- [x] As a petitions clerk, I can view and identify petition work items with the case status "Recalled" that are assigned to me in my individual Work Queue Inbox
- [x] As any user in the Petitions section, I can view AND identify petition work items with the case status "Recalled" assigned to any user in the petitions section in the Petitions Section Work Queue Inbox 

 ## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
