### ISSUE TITLE
Internal user: See unread messages in work queue

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6694]
As an internal user, in order to properly prioritize work, I need to see easily see my unread messages in my work queue.

An internal user will be working from their work queue throughout the day.  Since this is a dynamic work queue (items coming in and going out), the internal user will need to easily see when they get a new work item.

## Pre-Conditions
* Internal user is logged into the System.
* Internal user is viewing their work queue.

## Acceptance Criteria
* User can easily see which items in their work queue have not been read in their Individual Queue.
* User can easily see how many unread items are in their individual work queue.
* Apply this change to all internal users.

## Notes
* Section Queue has no concept of Read/Unread and only in the individual queue
* Users cannot mark a message as Unread

## Tasks
- [x] update work queue view (Matt)
- [x] update computed with unread flags (Eric)
- [x] update computed with unread count (Eric)
- [x] add read status work item entity (Eric)
- [x] add set read status when assigning work item
- [x] add set read when clicking link on the work queue
- [x] add use case for marking item as read (Cody)
- [x] integration and testing

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
