### ISSUE TITLE
Docket Clerk: Service on Parties of Signed Stipulated Decision

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6702]
As a Docket Clerk, in order to close a case, I want to serve the signed Stipulated Decision on the parties and close the case.

After signing the [Stipulated Decision,](https://www.ustaxcourt.gov/taxpayer_info_glossary.htm#STIPULATED_DECISION) the Senior Attorney then notifies the Docket Clerk that the Stipulated Decision is signed and ready to be served on the parties. The Docket Clerk updates the case metadata (as necessary), marks the served date on the document, and serves the signed Stipulated Decision on both parties.  The case status should automatically change to “Closed”. 

## Pre-conditions:
* Petition has been served on the IRS
* A signed Stipulated Decision is saved in the system in a particular case/docket #. ustaxcourt/ef-cms#6543
* ~The case has multiple parties associated with the case~
* Docket Clerk has received a message that a Signed Stipulated Decision is ready to be served

## Acceptance Criteria (Post-conditions):
* Only Docket clerks can see the "Serve" button
* Docket clerk can initiate electronic service for the signed stipulated decision to all parties in the case from within the system
* When the Docket clerk initiates service of the Signed Stipulated Decision, a docket record entry is created for the document.
* The docket record is updated with the date and time upon the service to the parties.
* Parties associated with the case receive an email notifying them to log into the system because there's been activity in the case.
* Parties can log into the system and see the signed stipulated decision.
* When parties are served, the case status is automatically changed to “Closed”.

## Notes
* This story does NOT include designing the email template that will be sent (it will remain a plain text email for now)
* Story DOES include writing content for that email, which will be the same content regardless of what document is being served - include dynamic docket number, case caption, and link to log in to system (login page)
* Serving a document does not generate any new Message / Document QC item
* Will need to create some real emails to test sending/receiving service emails
* Served stamp will not be applied to cover sheet in this story
* Served time will be captured when the docket clerk confirms the "serve" action
* 07/24/19 decision to allow authenticated users to pass through to dashboard / home page when using the log in link in the notification email. Unauthenticated users will be asked to login with valid credentials.

## Tasks
- [x] 1 Set up generic e-mail address (Matt)
- [x] 2 Set up account in Cognito (Joe)
- [x] 3 Distribute new account information (Sarah)
- [x] 4 Figure out how to set up SES in terraform (Joe ustaxcourt/ef-cms-flexion#2441)
- [x] 5 Show "Serve" Button on Signed Stipulated Decision page only for docketclerk (Cody ustaxcourt/ef-cms-flexion#2430)
- [x] 6 Hide "Serve" button after case is served (Cody ustaxcourt/ef-cms-flexion#2430)
- [x] 7 Confirmation modal (Cody ustaxcourt/ef-cms-flexion#2434)
- [x] 8 Success message displayed on document detail page upon case being served (Cody)
- [x] 9 Add served [date and time] stamp to doc detail page (Cody ustaxcourt/ef-cms-flexion#2440)
- [x] 10 Change default doc name from "Signed stipulated decision" to "Stipulated Decision" (Cody ustaxcourt/ef-cms-flexion#2447)
- [x] 11 Close case upon case being served (Matt ustaxcourt/ef-cms-flexion#2436)
- [x] 12 Create docket entry upon case being served (Matt ustaxcourt/ef-cms-flexion#2436)
- [x] 13 Add [time] to served column on the Stipulated Decision docket entry (Matt ustaxcourt/ef-cms-flexion#2445)
- [x] 14 Stipulated Decision event code is SDEC - display in code column on docket entry (Cody ustaxcourt/ef-cms-flexion#2463)
- [x] 15 Lambda & use cases (call to SES) (Joe ustaxcourt/ef-cms-flexion#2458)
- [x] 16 Generate e-mail (with dynamic data) & send it via SES (Joe ustaxcourt/ef-cms-flexion#2458)
- [x] 17 Create e-mail text (Sarah)
- [x] 18 UI Design (Sarah)
- [x] 19 Add backend support for capturing served parties for stip decisions (Matt ustaxcourt/ef-cms-flexion#2452)
- [x] 20 Populate Parties column on docket record after stip decision has been served (Matt ustaxcourt/ef-cms-flexion#2455)
- [x] 21 Add users for each party type in cognito under test emails (Joe)
- [x] 22 Fixed the served column of the docket record for the served stipulated decision (Matt)
- [x] 23 Email template name should probably be scoped via environment: `case_served_dev` (Cody ustaxcourt/ef-cms-flexion#2468)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Matt ustaxcourt/ef-cms-flexion#2474)
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt ustaxcourt/ef-cms-flexion#2466)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
