### ISSUE TITLE
Practitioner: Filing an Entry of Appearance or Substitution of Counsel

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6703]
As a Practitioner, in order to have access to case records, I need to be associated to the case when I file an Entry of Appearance or Substitution of Counsel.

There are two main scenarios when a practitioner will file an Entry of Appearance:
1) Pro-Se to Represented. A Pro-Se Petitioner has filed, but then hires an attorney. Since the case is already started, the newly hired practitioner will file an Entry of Appearance.
2) Adding Counsel. A case may already have representation, but an additional attorney is being added. In this scenario, the newly hired counsel would file an Entry of Appearance.

Substituting Counsel (Substitution of Counsel)
When a Petitioner wants to substitute counsel (replace previous counsel with a new one), the new counsel should will file a "Substitution of Counsel." (Note: Post-MVP, counsel should be able to select who they are subbing in for. MVP is that we'll allow the Docket Section to do it manually)

## Pre-Conditions
* Practitioner files an Entry of Appearance or Substitution of Counsel

## Acceptance Criteria
* The filing appears on the Docket Section Queue
* When a practitioner files an Entry of Appearance or Substitution of Counsel, they are immediately associated to the case.
* Once associated with a case, the practitioner can see everything in the case 
* Once associated with the case, the practitioner’s data is viewable to other parties and internal Court Users on the Case Info tab
* Once associated with a case, the case should show up on the Practitioner's dashboard.
* Before association, practitioner should be able to see documents in a case, but not open/access them.

## Notes
* Processing of Substitution of Counsel by Docket and removing exiting attorney is addressed in separate story (#1325)

## Tasks
- [x] 1.  Search A Case
  - [x] 1a. Create Search Box View (Kris ustaxcourt/ef-cms-flexion#1520)
  - [x] 1b. Create Search sequences and actions, connect to view (Kris ustaxcourt/ef-cms-flexion#1520)
  - [x] 1c. Create/update computed to determine whether header-search shows (hidden from Practitioners) (Kris ustaxcourt/ef-cms-flexion#1520)
 - [x] 1d. Ensure consistency of responsive design (kris ustaxcourt/ef-cms-flexion#1529)
- [x] 2. Request a Case
  - [x] 2a.  Create Request a Case button (determine when to hide/show within computed) (Rachael/William ustaxcourt/ef-cms-flexion#1516)
  - [x] 2b.  Create Request a Case form view and new route (Rachael ustaxcourt/ef-cms-flexion#1518)
  - [x] 2c.  Create Request a Case Review screen (Rachael ustaxcourt/ef-cms-flexion#1518)
  - [x] 2d.  Create Request a Case validation sequences/actions (William ustaxcourt/ef-cms-flexion#1519)
  - [x] 2e.  Create association (new or updated interactor?) between practitioner and case (supports 2a) (William ustaxcourt/ef-cms-flexion#1527 ustaxcourt/ef-cms-flexion#1528)
  - [x] 2f.  Refactor determining whether a practitioner is associated with a case (currently calling getCasesByUserAction in gotoCaseDetailSequence) (Rachael)
  - [x] 2g.  Integrate validation sequences into views (Rachael ustaxcourt/ef-cms-flexion#1521)
- [x] 3. Reveal Practitioner information on Case Info tab (kris)
- [x] 4. pa11y test (kris ustaxcourt/ef-cms-flexion#1545 )
- [x] 5. Case journey test (Rachael ustaxcourt/ef-cms-flexion#1531)
- [x] 6. Add petitioner names to docket record entry for Entry of Appearance (Rachael/William/Kris ustaxcourt/ef-cms-flexion#1537)
- [x] 7. Change Filed By to counsel name for docket record entries (Rachael/William/Kris ustaxcourt/ef-cms-flexion#1537)
- [x] 8. Change order of columns in dashboard for practitioners (William ustaxcourt/ef-cms-flexion#1536)
- [x] 9. Disable document links before practitioner is associated with a case (Rachael ustaxcourt/ef-cms-flexion#1547)
- [x] 10. Clear Certificate of Service date when unselected. (William ustaxcourt/ef-cms-flexion#1549)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning (William ustaxcourt/ef-cms-flexion#1554)
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt (William ustaxcourt/ef-cms-flexion#1556)
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (PR ustaxcourt/ef-cms-flexion#1551)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
