### ISSUE TITLE
Filing Fee: Notate how and when paid or waived (by 1/8)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6712]
As a court user, so that I may capture within the system that the filing fee has been paid, I need the ability to notate how and when the fee was paid. 

## Acceptance Criteria
* Court user needs ability at any time to indicate that the filing fee has been paid or if it was waived
* Court user needs ability to indicate at any time how the filing fee was paid
* Information regarding payment of filing fee (including null state) should display on Case Info tab for internal users, practitioners and petitioners (not respondent or any public view)
* When filing fee is paid, a Docket entry should be created as of the date of payment and display as "Filing Fee Paid"
* When filing fee is waived, a Docket entry should be created as of the date of waiver and display as "Filing Fee Waived"
* For fee paid: Implement date, code (FEE), filing and proceeding
* For fee waived: Implement date, code (FEEW), filing and proceeding

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] modify the entity (Cody / Kris) ustaxcourt/ef-cms-flexion#3978
- [x] create the needed docket entries after the IRS Batch process runs (Cody ustaxcourt/ef-cms-flexion#3980)
- [x] create the edit case information page, action, sequences (Cody ustaxcourt/ef-cms-flexion#3991)
  ~create the edit button on case information (don't show the edit button until petition is served & processed)~ don't think this is needed. discussed on slack
- [x] create new endpoint for saving the new case information (lambda, serverless config, interactor, persistence) (Kris) ustaxcourt/ef-cms-flexion#3982
- [x] modify the existing edit petition details view to match the new radio button design in figma (make PetitionPaymentForm component reusable in both places) (Rachael ustaxcourt/ef-cms-flexion#4011)
- [x] add a new route / pseudo route for the edit petition details page so that users can press the browser back button (Kris) ustaxcourt/ef-cms-flexion#4012 
- [x] only show Edit button on case detail -> case information -> petition details card for docket users (Rachael ustaxcourt/ef-cms-flexion#3994)
- [x] clean up payGovDate and payGovId (replaced with new fields) (Rachael ustaxcourt/ef-cms-flexion#4014)
- [x] add the title for the case info tab that says Petition Fee (Rachael ustaxcourt/ef-cms-flexion#4016)
- [x] docket entry title needs to be fixed (Cody)
- [x] create the docket entry when changing from unpaid to either paid or waived (Cody)
- [x] fix validation issues (validating too early?) (Kris)
- [x] hide Order for Filing Fee checkbox on QC form when fee is paid or waived (Rachael ustaxcourt/ef-cms-flexion#4016)
- [x] add filing fee section to case detail case information for petitioners and practitioners (Rachael ustaxcourt/ef-cms-flexion#4018)
- [x] make petitionPaymentStatus required ~and create migration~ (Rachael ustaxcourt/ef-cms-flexion#4018)
- [x] update validation error messages to match what was provided by Kristen (Rachael ustaxcourt/ef-cms-flexion#4016)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
