### ISSUE TITLE
Petitioner: Yes/No logic with respect to IRS notice

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6713]
As a Petitioner, in order to provide accurate information to the Court, I need to indicate whether I've received an IRS notice when starting a case.

In most cases, a taxpayer must receive a notice from the IRS before filing a case with the Tax Court.  However, there are some instances where the taxpayer can file a Petition without having a notice.  It is important for the Court to know whether the taxpayer has a notice or not. 

## Pre-Conditions
* Petitioner has decided to Start a New Case

## Acceptance Criteria
* Petitioner must indicate whether they have received an IRS notice or not
* Petitioner should be presented with two different sets of Case Type options based on Yes-Notice vs. No-Notice
* The Petitions Clerk  needs to understand whether a notice has been provided or not during the QC process
* Any Court user needs to understand whether a notice has been provided or not

## Notes:
* Two separate case type lists based on Yes-Notice vs. No-Notice are below in comments.

## Tasks
- [x] Modify design of "Start a Case" page [Sarah]
- [x] Modify design of "Petition QC" page [Sarah]
- [x] Modify design of "Case Detail" page [Sarah]
- [x] Add mapping list [Sarah]
- [x] Modify entity validation rules (Kris)
- [x] Develop business tests (Rachael)
- [x] Modify views of start a new case screen (Rachael)
- [x] Change case type dropdown values based on yes/no notice (in view) (Rachael) 
- [X] Modify views of QC screen (Cody)
- [x] Modify view of case info tab to include "No notice" (Cody)
- [x] Fix bug where there is no way to remove an IRS notice date once it has been added 
- [x] Fix bug in which values persist in state (and are validated against) yet are not reflected in form; (clear some state values when validation requirements change?) (Rachael)
- [x] fix FontAwesome icon color on "before you start a case" (Kris)
- [x] fix notice date required on start case validation when hasIrsNotice is false (Kris)
- [x] look into date validation on petitions clerk side (can submit form, no errors with only month filled in, but it does not save) (Cody)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [ ] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
