### ISSUE TITLE
SPIKE: File Size and Type Limitations

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6716]
What file size limitations (if any) should the Court impose on external filers? 500MB (#1166)
Are there any common work-arounds (i.e., upload as multiple docs)? Post-MVP (#1165)
Should the court impose file type limitations? Yes, only PDFs (#1164) 

### Upload Scenarios:
* External initial filings (petition package)
* External subsequent filings
* Court uploads

### Issues:
* System dealing with large file sizes, timeout, etc
* Usability of large documents
* Limiting file types
* Workarounds
     
### Solution:
* Pick a max file size and apply across the board
* Limit to PDFs; esp. for PDF. We're only building for PDFs right now.
* Workaround for files that are too big: Users can upload multiple docs. 
* Also add helper text to guide users. 

### Notes/Considerations:
* Don't make so small that frustrating for users
* Any time we ask an external user to upload something, include file size limitations in helptext (make global)
* Don't need to use page count; it doesn't impact file size

### Tasks
- [x] Court to test out creating and handling of large docs to see how large of doc they can handle. [Jessica to complete when shutdown has ended]
- [x] Jessica to ask Tony to inquire with AO office
- [x] Stephanie to look into what's been recommended in the past.
- [x] Establish file size limitations
