### ISSUE TITLE
Petitioner: Warning of timeliness of electronic Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6720]
As the Clerk of the Court, in order to assure that the Petitioner is informed about filing their petition in a timely manner, I need the system to inform the petitioner about rules regarding timeliness of filing when they use the system and their options for filing offline, if necessary.

When a Petitioner indicates that they want to Start a New Case, one of the first things that they need to see is a warning explaining to them when an electronic Petition will be considered to be timely, and their other options if they cannot submit it electronically. This is important because, if a Petitioner submits a Petition to the Court even 1 day late, the Court lacks jurisdiction to hear the case. [Note: the eProjects committee developed some language previously for this purpose; I've put it in the comments as a starting point/something to discuss]

## Pre-Conditions
* Petitioner has indicated that they want to Start a New Case

## Acceptance Criteria
* Petitioner knows what it means to submit an electronic Petition timely
* Petitioner is provided with other options (mailing or hand-delivery) if they cannot submit case electronically
* Petitioner should not be allowed to move forward with filing a petition without acknowledging they have seen the timeliness messaging (do not need to store acknowledgement)

## Notes
* (1/28) Date will be on notice and we can add tell user to refer to notice. Tina's recommended language is, "...on the last date for your filing as described in your notification from the IRS"
* (1/28) Purpose of checkbox = an extra step to make user pause and read

## Tasks
- [x] 1. Design of the timeliness messaging and warning (Sarah)
- [x] 2. Design updates to Start a Case form including messaging (Kristen) 
- [x] 3. Develop business use test cases
- [x] 4. Build and implement view changes
- [x] 5. Modify existing "Start a case" view (will)
- [x] 6. Implement interstitial view (kris)
- [x] 7. Create new route to view/page (kris)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
