### ISSUE TITLE
Petitioner: Verify that I am Filing Petition for Myself

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6721]
As the Clerk of the Court, in order to limit the amount of unqualified third parties filing on behalf of a petitioner, I need petitioners to be informed of  the Court rules regarding 3rd party filing

Only practitioners admitted to practice before the Court are allowed to file a Petition on behalf of a third party.  The Court routinely gets Petitions from Powers-of-Attorney (POAs), Certified Public Accountants (CPAs), Enrolled Agents (EAs), etc. that are filing the case on behalf of a client.  These Petitions are improper and the Court often has to dismiss the case.  In order to prevent this as much a possible, the Petitioner needs to confirm that they are filing the Petition for themself (and not a third party). [Note: The Court's eProjects Committee had previously developed language to address this; I'm putting that language in a Comment as a starting point for discussion]

## Pre-Conditions
* Petitioner has indicated they want to Start a New Case

## Acceptance Criteria
* Petitioner is informed that POAs, CPAs, EAs, etc. cannot file a Petition on behalf of a third party
* Petitioner should not be allowed to move forward with filing a petition without acknowledging they are filing the petition for themselves (the system does not need to store the acknowledgement)

## Notes
(1/31/19) Accountants think that because they're the enrolled agent to interact with the IRS. They think they're allowed to file on behalf of, when they're not. CPAs are not permitted  to file on behalf. 
(1/31/19)  Warning is static for THIS story and should be presented no matter who is filing
(1/31/19) Radio button  is only an acknowledgement that they've read the message. No logic. 

## Tasks
- [x] Design of the third party filing warning message (Kristen)- See design in comments for 644 
- [x] Develop business use test cases
- [x] Build out party selection design  
- [x] Implement view changes
- [x] apply updated style for the warning box (will)

## Business Test Cases 
- [x] As a Petitioner, I am able to acknowledge that I am filing this petition on behalf of myself  
- [x] As a Petitioner, when I select that I am filing this petition on behalf of another party, I am able to view the third party filing warning message 

## Definition of Done
- [ ] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
