### ISSUE TITLE
Petitioner: Ownership Disclosure Statement (ODS)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6727]
As a Judge, in order to make sure the Judge does not have a conflict of interest due to having an ownership interest in the company, it's parent or subsidiary, I need the Petitioner to provide an Ownership Disclosure Statement if they are a party type of "Corporation" or "Partnership."

Rule 20(c) requires a corporation, partnership, or limited liability company, filing a Petition with the Court to also file an Ownership Disclosure Statement(ODS). That ODS is used by the Judge to make sure they have no  conflict of interest due to having an ownership interest in the company, its parent or subsidiary. 

## Pre-Conditions:
* Petitioner has selected "Corporation" or "Partnership" as the Party Type

## Acceptance Criteria:
* Petitioner is required to provide an ODS
* Petitioner can see where to upload a completed ODS (Mandatory)
* ODS is saved in the system
* ODS displays as a separate docket entry when case created
* ODS does not show up as a separate message thread
* ODS does not show up as a separate work items

## Notes
* Petitioner is provided link to ODS on the Court's website (https://ustaxcourt.gov/forms/Ownership_Disclosure_Statement_Form_6.pdf)
* We need to make sure that, if a Petitioner selects a business type that makes the ODS upload function appear, and they ultimately change their selection to something other than one of those business types, the ODS fields should re-hide.  Right now, once it shows up, it stays, even if the Petitioner actually selects "Myself"

## Tasks
- [x] Add an upload field to design of "Start a Case"
- [x] Develop Business Tests
- [x] Add logic to show upload field if Corporation or Partnership party type is selected (will)
- [x] Add the upload field to the form (will)
- [x] modify createCase action and Petition and Case entities (will)
- [x] Modify the validation
- [x] Modify the "Start a Case" interactor to create the docket record entry for this document (will)
- [x] Fix bugs from Sprint Review: (1) ODS still showing as required even if Petitioner picked another party type that wasn't a business; 
- [x] ODS does NOT need to show up as a separate work item in the work queue

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
