### ISSUE TITLE
Petitioner: International and Other Domestic Addresses and Phone Numbers

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6728]
As a Petitioner, In order to provide international addresses and phone numbers for any address I enter into the system, I need to the system to accommodate international address.

The Court occassionally has Petitioners who do not live in the United States.  The System needs to be accomodate to international addresses.

## Pre-Conditions:
* Petitioner has decided to Start a New Case

## Acceptance Criteria:
* Petitioner must be able to enter an international/unusual address for any address they can enter into the system
* The System can save and display international addresses

## Tasks
- [x] 1. Modify the Start a Case Form (Rachael)
- [x] 2. Update pa11y tests for Start a Case Form (Rachael)
- [x] 3. Update seed data with new required fields and international addresses (Rachael - PR)
- [x] 4. Update taxpayerCreatesNewCase business test with required fields, intl addresses (Kris)
- [x] 5. Modify the Case Information page (William)
- [x] 6. Find a better way to use object composition for creating some of these contact entities (Cody / Kris)
- [x] 7. Dry up the strings we are using throughout the code base and components (Cody)
- [x] 8. Come up with validation requirements for international addresses (UX)
- [x] 9. Create validation routines for international addresses (Eric & William)
- [x] 10. Change zip to postal code throughout code (Rachael)
- [x] 11. Reminder to revisit string constants from a CA perspective as part of refactoring at the end of this story (also clean up incomponentPerson -> incompetentPerson) (Cody)
- [x] 12. Reminder to revisit default countryType in updatePartyTypeAction (William)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
