### ISSUE TITLE
Server Error Handling - Global Solution and Implementation

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6732]
As a development team, we need to define and document our approach for server error handling, so we can implement global error handling as needed.

## Acceptance Criteria
* Define and document approach for server error handling
* Error statements and handling implemented for 
  * 401: User isn't logged in
  * 403: User is logged in, but doesn't have permission OR 404: Not Found
  * 4XX: Unexpected request from the client
  * 5XX: Something went wrong, we made a mistake in our code or configuration

## Tasks
- [x] 1. Design error statements for each error type- see comments and FIgma https://www.figma.com/file/MOgSt8RJaYnz3oyRPpTuTBrV/Sprint-7?node-id=2%3A1035 (Kristen)
- [x] 2. Design user flow - see comments (Kristen)
- [x] 3. Develop each error flow
- [x] 4. create cerebral error classes that represent each http status code grouping (see 514-errors-update for example) (kris) (done pr coming)
- [x] 5. add error factory and decorator to application context throws new cerebral error based on generic error (kris/cody) 
- [x] 6. implement Error jsx for new /error route (see 676-error-handling) (will/eric)
- [x] 7. add special handling for bad user on login page (red alert on login) (kris)
- [x] 8. figure out how to define route so all unknown routes go to unauthorizedErrorSequence (will pr out)
- [x] 9. how to mock provider with mockRejectedPromise per https://cerebraljs.com/docs/api/test.html and write tests? (eric)
- [x] 10. redirect to login page on 401 (will/eric)
- [x] 11. fix styling of error messages and make sure errornotification is placed properly on all views  below h1 (kris)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
