### ISSUE TITLE
Petitions Clerk: Orders to be Issued following QC process

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6734]
As a Petitions Clerk, in order to keep track of what orders I need to issue, I need a way to note in the system what orders are required after a QC is performed. 

## Pre-Conditions:
* Petitioner has submitted a new case to the Court
* Petitions Clerk can access the new Petition for QC

## Acceptance Criteria
* User has a way to indicate which orders need to be issued during the QC process
* Update Petitions Clerk's QC view implemented during ustaxcourt/ef-cms#6735 to be read-only when status is "Batched for IRS" (see design below)

## Note:
* All of the metadata fields need to be editable on the QC screen
* List of orders issued by petitions section - https://drive.google.com/file/d/13VqXTvxwB0Cb8VbU3H_WPhy6n4Zzl9gZ/view?usp=sharing
* Need to use the QC metadata to determine the list of orders that could be issued at this point

### Feedback from Petitions Clerks 2/26  
- Clerks preferred tabs to be reordered; party information was the area most of them would focus first 
- Clerks preferred the order checkboxes in context to the information they related to; had no issues with the display of the other orders 
- Clerks all had questions related to the Fee Payment Date and Payment ID fields - we will address these fields in a later story 
- Clerks all had concerns about the timing of IRS batch service - their current process has IRS service happening in the morning for the previous days petitions
- Clerks did not find the summary screen beneficial- they all prefer to complete the orders immediately and would not likely print or return to the summary screen 
- Clerks and supervisor all had major concerns about petitions being served before completing the required orders 
- Want order generation to occur before the petition is batched for IRS service or prevent petitions with orders still required to be blocked from service somehow 

### Recommendations 
- Update tab order on Document Info to : Parties , Case Info, IRS Notice 
- Keep the order checkboxes in context with their related fields 
- Work with the Court to revisit the QC and order generation flow

## Tasks
- [x] 1. Design updates to petition QC screen (Kristen)
- [x] 2. Add checkboxes to views (Rachael) 
- [x] 3. Add validation for new fields to Case entity (Rachael)
- [x] 4. Add party information to read-only view of Document Info tab (Rachael) 

## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
-  [x] CI/CD - Code is deployed to DEV
- Other
  - [x] alerting and monitoring for new functionality in place and successfully exercised
