### ISSUE TITLE
Petitions Clerk: Review Party Type, Contact Information, and other Metadata

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6735]
As a Petitions Clerk, in order to ensure that case metadata is accurate, I need the ability to review, edit and save Party Type and Contact Info. 

As part of the QC process, a Petitions Clerk needs to be able to review, edit, and save the party type and contact information entered by Petitioner.
___________

## Pre-Conditions
* Petitioner has entered party type data and contact information when starting a new case ustaxcourt/ef-cms#6559

## Acceptance Criteria
* Petitions Clerk can view all of the data that a petitioner has entered when starting a new case 
* Petitions Clerk can edit and save all fields (except for email address)
* If Petitions Clerk makes a change that affects the docket number (i.e., case type or small/regular), that change is captured on the docket record as an entry that reads: "Docket Number is amended from [old docket number] to [new docket number]"
* When the court changes the data originally entered by the petitioner, internal Court users can see the updated information on the Case Information tab.

## Tasks
- [x] 1. Redesign the QC page to accommodate the metadata (Kristen)
- [x] 2. Create new tabs (william)
- [x] 3. Party View (rachael, kris)
- [x] 4. Case Info View (cody)
- [x] 5. IRS Notice View (cody)
- [x] 6. Validation on entities and use case (no required fields) (kris)
- [x] 7. Create the entry into the docket record (William, Cody)
- [x] 8. Party View tab scrollable (Rachael)
- [x] 9. ODS link (Rachael)
- [x] 10. update docket number suffix on the case and work items (Cody)
- [x] 11. add autosave to all fields (Rachael)
- [x] 12. revisit autosave on caseProcedure and hasNotice after validation is removed (Rachael, Kris) - PR ready
- [x] 13. update the docketNumber in the page title after a suffix is updated (basically just set the caseDetail to match the case returned after an autosave update)
- [x] 14. Update docket record view to display updated docket record (William)
- [x] 15. Save when sending to IRS (Eric)
- [x] 16. Fix bug in which case caption is updated upon petitions clerk updating party type (kris)

## Definition of Done
- Jessica
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
  - [x] 0 errors reported in manual a11y testing
  - [x] all new functionality verified to work with keyboard and osx voiceover
  - [x] code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
- CI/CD
  - [x] npm audit for CVE’s in production library/module dependencies identified and resolved
  - [x] application can be deployed to multiple regions 
  - [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
  - [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
  - [x] all code changes have been reviewed, approved, and merged and deployed to develop 
  - [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- Other
  - [x] alerting and monitoring for new functionality in place and successfully exercised
  - [x] performance tests successfully completed and no new significant performance issues found
