### ISSUE TITLE
Petitioner: Login (Bare Bones)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6749]
As a petitioner, so that I may start a case with the court, I need the ability to log in to the CMS.

## Pre-Conditions
* Spike is complete
* Team is clear upon Cognito technical approach (cognito pgs vs APIs)
* Parameter of this story are clear

## Acceptance Criteria
* Petitioner can log into the CMS using their email and the password they generated during registration

## Tasks
- [x] 1. Create the integration points between Cognito and current app (will/cody)
- [x] 2. Pass security tokens to subsequent pages (will/cody)
- [x] 3. create docketclerk, petitionsclerk, intakeclerk, respondent, seniorattorney, taxpayer and add extra 1-5 users for each with password Testing1234$ (will/cody)
- [x] 4. rename navigateToLogIn to navigateToMockLogin (note the capitalization) (will/cody)
- [x] 5. use ENV=test instead of ENV=local? (will/cody)
- [x] 6. configure api gateway to use cognito pool for restricting access (cody/will)
- [x] 7. is a logout button needed for local work? (will/cody)
- [x] 9. add required attributes to User entity schema for validation
- [x] 8. add logout button (will)
- [x] 10. router.js - helper function to check if user is logged in on all routes (will)
- [x] 11. remove the "Dev only" restriction on reloading pages once logged in
- [x] 12. remove "new User({ userId}) from all places where it isn't needed and get user from application context instead (will/cody)
- [x] 13. refactor how to get the users in a section and how users are added to sections (for dropdowns) (cody)
- [x] 14. 404 on search case redirects to cognito (Will)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  (eric)
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
