### ISSUE TITLE
Petitioner: Statement of Taxpayer Identification Number

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6754]
As a Petitioner, in order to comply with Court rules, I need to submit a Statement of Taxpayer Identification Number.

Because taxpayers must redact all PII, including TINs, from their petition, the IRS cannot easily identify the taxpayer when the Court serves the Petition on the IRS.  To facilitate proper taxpayer identification, the Court collects the taxpayer's TIN for the IRS through a Statement of Taxpayer Identification Number ("STIN").  This document is submitted with the Petition (Rule 20(b)).  That STIN is not part of the official docket record of the case, but is transmitted to the IRS along with the Petition.

## Pre-Conditions:
* Petitioner has decided to start a new case

## Acceptance Criteria:
* Petitioner should see where to upload a Statement of Taxpayer Identification Number
* The STIN should be saved in the System but NOT displayed on the docket record
* No data from the STIN should ever display to system end-users
* The STIN should be able to be transmitted to the IRS with a copy of the Petition
* After successful transmission of STIN to IRS the document is deleted from the system

## Notes:
https://ustaxcourt.gov/forms/Form_4_Statement_of_Taxpayer_Identification_Number.pdf

## Tasks:
- [x] Design: Update the "Before You Get Started Page" with instructional text
- [x] Design: Update the "How to Prepare Your Documents" PDF with instructional text
- [x] Design: Update Submit a Case form
- [x] Code: Update the "Before You Get Started Page" with instructional text (Eric)
- [x] Code: Update Submit a Case form (Rachael)
- [x] Code: Update link to "How to Prepare Your Documents" PDF from Petitioner Dashboard (https://drive.google.com/open?id=1az4-G1vmgpz33hWJEzAmyDOP_p4HqYoJ) (cody)
- [x] Code: Update filePetition and createCase Use Cases to include STIN (Rachael)
- [x] Code: Update petition entity to include STIN (William)

 ## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [ ] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
-  [x] CI/CD - Code is deployed to DEV
- Other
  - [ ] alerting and monitoring for new functionality in place and successfully exercised
