### ISSUE TITLE
Petitioner: Registration (Bare Bones)

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6755]
As a Pro Se Petitioner, I would like to create an account and login into the system so that I may start my case

## Pre-Conditions
* Spike is complete
* Team is clear upon Cognito technical approach (cognito pgs vs APIs)
* Parameter of this story are clear

## Acceptance Criteria
* Pro Se Petitioner is able to create an account using their email address

## Notes
* Doesn't include password reset or other PW functions

## Tasks
 - [x] 1. Add the configurations into Terraform (cody)
 - [x] 2. Develop text for verification email and add to configuration (will/cody)
 - [x] 3. Add a link from the appropriate page (this is the new starting page)
 - [x] 4. If not in Terraform develop scripts via command line (cody)

## Definition of Done
- [x] acceptance criteria have been met
- [x] Field level and page level validation errors (front-end and server side) integrated and functioning
- [x] all code changes have been reviewed, approved, and merged and deployed to develop 
- [x] all automated unit tests are passing on all supported browsers with coverage > 90% 
- [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer  
- [x] all automated a11y checks are passing - no new WCAG2.1 or AA contrast issues present
- [x] 0 errors reported in manual a11y testing
- [x] all new functionality verified to work with keyboard and osx voiceover
- [x] all code quality checks are passing - sonar, eslint, html validation, etc.
- [x] code refactored for clarity and to remove any known technical debt 
- [x] application can be deployed to multiple regions
- [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
- [x] performance tests successfully completed and no new significant performance issues found
- [x] alerting and monitoring for new functionality in place and successfully exercised
- [x] ui should be touch optimized and responsive (functions on supported mobile devices and optimized for screen sizes as required)
- [x] usability has been validated
- [x] npm audit for CVE’s in production library/module dependencies identified and resolved
- [x] library/module dependencies are up-to-date and are at the latest resolvable version
