### ISSUE TITLE
Petitioner: Content Changes from Usability Testing 

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6759]
As a Petitioner, in order to be ready to pay the filing fee, I need to be notified early in the process that there is a filing fee.

## Acceptance Criteria
* Complete this bug as part of the story. Needs to not only be updated here, but everywhere in the system. https://trello.com/c/ZnKivdYB/259-step-2-required-field-text-weight-and-spacing
    * "all fields" required text should be semibold 600
    * change bottom margin to margin-bottom-3
* Petitioner is notified early in the process that they need to pay the filing fee *after* the case is created
* Move pay.gov and filing content to dashboard
* Items from usability testing ustaxcourt/ef-cms-flexion#3286:
   * Break the form instructions down into bite-sized chunks to make it clear which forms need to be completed, what they are for, and when they will be used (Priority)
   * Spell out all acronyms in their first use (Priority) 
   * Use plain language to rewrite all headers and descriptions for file a petition (Priority) 
   ~ * Add alternative instructions for merging PDFs for users without Adobe Pro (Priority)~ NO -- can delete instructions in their entirety if necessary
   * Clearly define the file upload fields by user-friendly form names (Priority) 
   * Inform the user upfront of how many PDF documents they will need to upload (Priority) 
   * Include reference links to the corresponding forms co-located with upload field (Priority)
   * Clarify the redaction warning message to ensure that users understand that it does not apply to the STIN (Priority) 
   * Create null state for Case Detail > Case Information tab for external parties 

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
**Dashboard (before a case(s) has been filed (amy)
- [x] Body copy updates including
        * New sections
        * Updated icons
        * Rename Start a petition button to Start a Case
- [x] Taxpayer tools
        * Update "Petition Filing Guide" to "How to Create a Case"
- [x] Other Filing Options
        * New copy
**Dashboard (after a case(s) has been filed  (amy)
- [x] Filing Fee Options
        * new content added to tile
        * Button for pay now that links to Pay.gov
        * Other Options- accordion script added to tile
** Instructions For Creating a Case (amy)
- [x] Create PDF of page
- [x] add accordion script to page
- [x] Update page content including text, icons, downloads and links
- [x] update text on button from " Got it, Let's File My Petition" to Got it, Let's Start a Case" 
- [x] cancel link needs cancel modal added in
** Form Page 1: STIN (Kristen)
- [x] Update content in Warning banner
- [x]  Text Changes to body copy
- [x]  green check icon moved to in front of the file name once file is uploaded
** Form Page 2: Petition (Kristen)
- [x] Update content in Warning banner
- [x]  Text Changes to body copy
- [x]  green check icon moved to in front of the file name once file is uploaded
- [x] Error message banner- order of errors needs to be Upload a Petition then Indicate whether you received an IRS notice
** Form Page 3: Who Are You Filing this Case For?
- [x] Petitioner and spouse option checkbox to copy address and phone to spouse
- [x] Corporation- updated copy
- [x] Corporation -  green check icon moved to in front of the file name once file is uploaded
- [x] Updates to Error messaging (for later?)
** Form Page 4. What Case Procedure Should You Choose for Trial?
- [x] Updated body copy
- [x] Update small case table content
** Form Page 5 Review Your Case Page
- [x] Update content in Warning banner
- [x] Update content in A Few Reminders Before You Submit
- [x] Clicking submit button submits case to Court and directs back to Dashboard and displays Success Modal
** Success Modal
- [x] Clicking submit button submits case to Court and directs back to Dashboard and brings up Success Modal
- [x] New Copy including static and dynamic included in new modal
- [x] Close button closes modal and returns user to dashboard

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
