### ISSUE TITLE
Court: Time-Out due to Inactivity

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6760]
As the Clerk of the Court, in order to protect the CMS, I need the system to log people out after some period of inactivity.

Due to security concerns, if a CMS user is inactive for more than 1 hour, they should automatically be logged out of the CMS.

## Pre-Conditions
* User is logged into the System

## Acceptance Criteria
* If User is inactive for more than 1 hour, they will be automatically logged out of the CMS.
* Upon automatic log-out, the CMS user should be notified that they have been logged out.
* Upon acknowledgment of log-out, the CMS user should be routed back to the log-in screen.
* Users should get a warning 5 minutes before being logged out.
* Activity is defined as movement of mouse or keystrokes. 

## Notes
* Token expiration -- auto-renewal as being used.
* Inactivity definition proposed to Product Owner
* Users include both internal and external
* Don't forget mobile
* Uploads not subject to timeout. 

## Tasks
- [x] 1.) create the modal (Matt)  - ustaxcourt/ef-cms-flexion#1540
- [x] 3.) create an action which refreshes the token and sets the new token into the store (Cody) - ustaxcourt/ef-cms-flexion#1540
- [x] 4.) create a interval which refreshes the token after 20 minutes if the user has interacted with the page -#1540
- [x] 5.) setup a listener which keeps track of if the user has used the mouse (move or click), or keyboard, and refresh the modal interval -#1540
- [x] 6.) create an interval which displays the modal after 55 minutes of inactivity - ustaxcourt/ef-cms-flexion#1540
- [x] 7) Refactor code base to work with cognito `code` option instead of `token` (Cody) - ustaxcourt/ef-cms-flexion#1540
- [x] 8) UI testing (Matt)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
