### ISSUE TITLE
Parties: Upload doc and provide information about document at time of upload

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6764]
As a Petitioner, Practitioner or IRS Attorney, in order to provide the Court with additional information about the document I am filing, I need to provide specific information.

When a Party is filing a document in a case, they need to provide certain information to the Court about each filing.  That information includes: the party or parties filing the document, whether a certificate of service is included and the service date, whether attachments or exhibits are included, and whether there are objections by other parties or counsel.

## Pre-Conditions:
* Party has indicated they want to file a document

## Acceptance Criteria:
* Parties can see where to upload the document
* Parties can upload the document
* Parties are reminded to redact all PII from the document and that evidence should not be submitted until trial
* Parties must select the party or parties filing the document. 
* Parties must indicate whether a certificate of service is included and the service date.
* Parties must Indicate whether attachments or exhibits are included. [Note: Exhibits and attachments must be included in the same electronic file as the document being filed]
* For all motions, Application to Take Deposition, and Substitution of Counsel, Parties must Indicate whether there are objections by other parties or counsel. This question is **NOT** needed for any other documents.
* Parties must indicate where there are any supporting documents for the document(s) they are filing.  If so, the parties should be able to upload those supporting documents and they should upload as separate docket entries.

## Notes:
* Pages 55-61 of Guide to eFiling (publicly available) shows how the Court currently does this: https://ustaxcourt.gov/eaccess/Petitioners_Guide_to_eAccess_and_eFiling.pdf

## Tasks:
- [x] Validation
  - [x] 1 Code: Revisit entities for validations (William ustaxcourt/ef-cms-flexion#1364, ustaxcourt/ef-cms-flexion#1370)
  - [x] 2. Code: Validation Interactor (William ustaxcourt/ef-cms-flexion#1365)
  - [x] 3. Code: Sequences for validation (William ustaxcourt/ef-cms-flexion#1365)
  - [x] 8. Code: Validation for party selection requirement (William ustaxcourt/ef-cms-flexion#1378)
  - [x] 9. Update error messages (William ustaxcourt/ef-cms-flexion#1397, ustaxcourt/ef-cms-flexion#1398)
- [x] 4. Code: Create Views (Rachael/Kris ustaxcourt/ef-cms-flexion#1357)
- [x] 5. Code: Integrate Views with Sequences (Rachael/Kris ustaxcourt/ef-cms-flexion#1368)
  - [x] 6. Code: Submission Sequence Integration (William ustaxcourt/ef-cms-flexion#1375)
  - [x] 8. Code: Add Validation Sequence to the inputs (William ustaxcourt/ef-cms-flexion#1372)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Add relevant fields to File a Document page [Kristen / Sarah]
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt (#1379)
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
