### ISSUE TITLE
Court: Docket entry format

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6765]
As the Court, in order to maintain consistency across all filings in the docket record, I need the docket entry for a new document to include specific information in a specific format.

The Court currently uses a format of Concatenated Document Title (C/S 04/17/2019) (Exhibit(s)) (Attachment(s)) (Objection) (Lodged) on all external filings. Keeping the format consistent across all filings in the docket record makes it easy to read.

## Pre-Conditions
* A Party has successfully filed a document.

## Acceptance Criteria
* The docket entry is populated based on Court-provided rules [See below for sample docket entry format]
* Document title is a hyperlink to the actual document.
* Each docket entry should include a sequential docket entry number 
* Each docket entry has the associated event code (derived from document type)

## Notes
* Court is not bound to All caps for document title
* Court currently uses "Exhibit" or "Exhibits" to differentiate between one or more exhibits.  The Court is not bound to this current practice and "Exhibit(s)" is fine for all instances where one or more Exhibits are attached to a document.  Same thing for "Attachment(s)".

## Tasks

Engineering
- [x] 1. modify formattedCaseDetail for filings & proceedings strings, date formatting, filed by strings (Rachael ustaxcourt/ef-cms-flexion#1450)
  - [x] 1a. add isPaper boolean to document (Rachael ustaxcourt/ef-cms-flexion#1450)
- [x] 2. update view for desktop (Rachael ustaxcourt/ef-cms-flexion#1442)
  - [x] 2a. update responsive view (Rachael ustaxcourt/ef-cms-flexion#1422)
- [x] 3. Document Metadata (William, Kris ustaxcourt/ef-cms-flexion#1440)
  - [x] 3a. Add event code to document metadata upon creation
  - [x] 3b. ~~Ensure petitions have event code~~ (save for ustaxcourt/ef-cms#6778)
  - [x] 3c. Add 'lodged' property 
  - [x] 3d. Normalize parties across documents
- [x] 4. verify functionality when docket record number change updates order of the docket record (William)
  - [x] 4a. assign numbers to docket record entries upon creation? (William ustaxcourt/ef-cms-flexion#1454 ustaxcourt/ef-cms-flexion#1456)
- [x] 5. make docket record table fixed height and scrollable - possibly with fixed header (Rachael ustaxcourt/ef-cms-flexion#1452)
- [x] 6. Fix order in which Petition document and Request for Place of Trial are added to the docket record (Rachael ustaxcourt/ef-cms-flexion#1455)
- [x] 7. Show 2 docket record table view options on mobile temporarily for practitioner usability testing (Rachael ustaxcourt/ef-cms-flexion#1459)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
  - [x] Local Seed data up to date with latest changes (William ustaxcourt/ef-cms-flexion#1463)
