### ISSUE TITLE
Court User: Start a message thread

### ISSUE THREAD

**Issue by tjcurington** [ustaxcourt/ef-cms#6766]
As a Court User I need to be able to create a new message that will start a thread, so that I am able to communicate to other internal court users regarding a document within a case

## PreCondition:
* A document exists in the case docket record

## Acceptance Criteria
* The Court User is able to start a new message
* The Court User is able to choose a message recipient (any internal court user)
* The Court User is able to free-form a message in the thread
* The new message is viewable in the docket detail page, the case detail page, in the senders sent box, and in the queue of the recipient
* The sent message is viewable in the sender's individual and section Sent box [Note: make sure Sent box is built out for all users]

## Tasks 
- Design
  - [x] Design mechanism to start a new message thread (Kristen)
  - [x] Update document detail page design (Kristen)
- Code
  - [x] Update document detail page view (kris ustaxcourt/ef-cms-flexion#1115 )
  - [x] Create the buttton for opening the modal on document details page (cody ustaxcourt/ef-cms-flexion#1098)
  - [x] Start initial work on the new message modal (cody, ustaxcourt/ef-cms-flexion#1098)
  - [x] Fix styles for the create message button to match UX images (eric)
  - [x] Attach validation to the modal fields (William ustaxcourt/ef-cms-flexion#1114)
  - [x] Add validation messages to Entity (William ustaxcourt/ef-cms-flexion#1114)
  - [x] Update language (Messages In Progress) on Case Detail page view  (Rachael)
  - [x] Make sure Sent box is built out for all users (Rachael, Cody)
  - [x] Case journey tests (cody)
  - [x] Swagger updates (cody)
  - [x] Close the modal on errors (Rachael & William & Cody)
  - [x] Sort by date (newest first) the Pending Messages on Case Detail and Document Detail (kris ustaxcourt/ef-cms-flexion#1125 )
  - [x] Test coverage updates (cody)
  - [x] The assigneeId select is not being disabled afte the message is created (William ustaxcourt/ef-cms-flexion#1117 ustaxcourt/ef-cms-flexion#1119)
  - [x] Update the success alert text
  - [x] The sent work items are not showing up in the either the section sent box or individual sent box (Rachael, Cody)
  - [x] Create new message thread use case, action, sequence (cody, ustaxcourt/ef-cms-flexion#1098)
  - [x] Create get users by section using list of sections in https://github.com/flexion/ef-cms/blob/develop/shared/src/business/entities/WorkQueue.js (cody)
  - [x] Add Sent box tests to case journey (Rachael)
  - [x] Reset modal form values when form is cancelled (William ustaxcourt/ef-cms-flexion#1119)

 ## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
  -  [x] CI/CD - Code is deployed to DEV
- Other
  - [x] alerting and monitoring for new functionality in place and successfully exercised
