### ISSUE TITLE
Parties: Unique Doctype data requirements and doc name concatenation

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6771]
As a Petitioner, Practitioner and IRS Attorney, in order to provide unique supporting data for specific doc types, I need the ability to add specific data based upon which document I am uploading. 

In certain circumstances, more document metadata is required for an external filing than in a typical filing. When specific data is required for an external filing, the user needs to be prompted to enter that data. For all of these special circumstances, the additional 

https://docs.google.com/document/d/1vg6F3-mZzhfMfjyYgYz69JzVZZR6kTn4y3CdHxeF36k/edit?usp=sharing

## Pre-Conditions
* Party has the need to upload a document for which the court requires specific doc-related data to be collected. 

## Acceptance Criteria
* Every document selection should have a title and related code.
* If a Nonstandard A document is selected (e.g. Opposition to", "Redacted," "Response to," "Reply to" and "Unredacted), the user is required to select which previously filed document they are filing the document for, AND the document name must concatenate the document type and the name of the previously filed document (e.g. Reply to Motion to Dismiss).
* If a Nonstandard B document is selected (e.g. Application to Take Deposition of [Name]), then the user is required to enter additional text AND the document name must concatenate the document type and the additional text (e.g. Application to Take Deposition of John Smith).
* If a Nonstandard C document is selected (e.g. Affidavit Of [Name ] in Support Of [Document Name]), then the user is required to enter additional text and to select which previously filed document they are filing for, AND the document name must concatenate the document type and additional text and previously filed document (e.g. Affidavit of John Smith in Support of Motion to Dismiss).
* If a Nonstandard D document is selected (e.g. "Certificate of Service") is selected, user must indicate which previously-filed document they are providing a certificate for and indicate a service date, AND the document name must concatenate the document type, previously filed document and date of service (e.g. Amended Certificate of Service of Motion for Continuance 03/30/2017)
* If a Nonstandard E document is selected (e.g., Motion to Change Place of Trial [place]), then the user is required to select a trial location applicable to their case procedure type, AND the document name must concatenate the document type and the trial location (e.g. Motion to Change Place of Trial Birmingham, AL)
* If a Nonstandard F document is selected (e.g.[First, Second, etc.] Amendment to [Document Name]) , then the user is required to select which ordinal number of the filing and to select which previously filed document this is for, AND the document name must concatenate the ordinal number and the document type and the previously filed document (e.g. Second Amendment to Motion to Dismiss).
* If a Nonstandard G document is selected (e.g. {First, Second, etc.] Stipulation of Facts), then the user is required to select the ordinal number of the filing AND the document name must concatenate the ordinal number and the document type (e.g. First Stipulation of Facts).
* If a Nonstandard H document (“Motion for Leave to File” or "Motion for Leave to File Out of Time") is selected, the user is required to select a secondary document for which they are requesting leave to file AND the document name must concatenate the document type and the secondary document name (e.g. Motion for Leave to File Motion to Dismiss)
* The secondary document name must concatenate using the same pattern as described above depending on the document scenario (e.g. Nonstandard A).

## Notes
* **Do we need to do anything with unique document codes? Referenced on pg. 55 and 84.**  _Yes, for internal users only. Parties don’t need to know the codes. However, we need to tie the codes to the doctypes when we load them into the database._
* **Do we need to do anything with e-Lodging? Referenced in "Motion for leave to file" section of the e-guide.** _Yes, Docket felt this was important to maintain.  Jessica met with Designers in DC to go over this in detail_
* **Are there any other situations where we should be adding text to a document name that’s not part of the original doc type data or data fields?** _Possibly, but maybe the example in efiling doc was incorrect_
* **When users selects the name of a previously filed document, is there any limit to what the user can select?** _Yes, Only documents that have already been filed in the case_
* **When users selects the name of a previously filed document, are they referring to a list of doc types or are they referring to a list of documents that were actually filed?** _Same answer as above_
* **Are there any situations when we concatenate a document name that we’re not using the actual name from the dropdown or from a field?**
* **Are the doc types listed in the e-filing guide the actual doc types in the list? For example Supplemental and Supplements To, are those actual doc types?** _Not necessarily. Still need to identify the actual doctype that will trigger the logic_
* **Other than the unique naming conventions above, are there any other doctypes that require special naming conventions?** 
* **For documents that reference a previously filed document, is there any hierarchical relationships between the two documents (other than the name)?** _No, it appears as just another docket entry_

## Tasks
- [x] Design scenario for selecting a secondary document and secondary supporting documents for appropriate documents 
- [x] Design scenario for selecting document ordinal (first, second, third) for appropriate documents 
- [x] Code: Tweak the script that generates `externalFilingEvents.json` (kris, ustaxcourt/ef-cms-flexion#1317 )
- [x] Code: `GenerateDocumentTitle` use case, using `externalFilingEvents.json` (kris ustaxcourt/ef-cms-flexion#1320)
- [x] Code: Comprehensive tests for document scenario options
- [x] Code: Create React views for each of the document scenarios and load them when their respective document types are selected (Rachael ustaxcourt/ef-cms-flexion#1321, ustaxcourt/ef-cms-flexion#1327)
- [x] Code: Create Entities / UseCases / Actions / Sequences for validation (William ustaxcourt/ef-cms-flexion#1319)
- [x] Code: Create Actions / Sequences for title generation (William ustaxcourt/ef-cms-flexion#1332)
- [x] Code: Show Nonstandard view again if secondary doc type is a nonstandard scenario (Rachael ustaxcourt/ef-cms-flexion#1329)
- [x] Code: Create React view for File a Document form with read-only document title (also probably should rename old FileDocument view to something else) (kris ustaxcourt/ef-cms-flexion#1339)
- [x] Code: E2E Journey Test (William, Rachael ustaxcourt/ef-cms-flexion#1332)
- [x] Code: Remove Nonstandard H documents from secondary document dropdown (Rachael ustaxcourt/ef-cms-flexion#1338)
- [x] Code: Integrate view code with Sequences (William ustaxcourt/ef-cms-flexion#1343)
- [x] Code: Clear properties when editing or category/type is selected.

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
