### ISSUE TITLE
Petitions Clerk: Summary of Orders to Be Generated During QC Process

### ISSUE THREAD

**Issue by uxforgood** [ustaxcourt/ef-cms#6772]
As a Petitions Clerk, in order to keep track of what orders I need to issue after the QC process is completed, I need to see a summary of orders.

## Pre-Conditions:
* Petitions Clerk has QC'd a new Petition

## Acceptance Criteria

* The Petitions Clerk can easily see and print a summary of all of the orders that need to be issued
* Court users can return to the system at a later date and see the summary of orders
* If petition is recalled and QC form edited the summary displays the new list of orders

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* List of orders issued by petitions section - https://drive.google.com/file/d/13VqXTvxwB0Cb8VbU3H_WPhy6n4Zzl9gZ/view?usp=sharing
* Need to use the QC metadata to determine the list of orders that could be issued at this point
* Reminder - review Read-only view of the Document Detail tab - may want to include list of orders there.
* Printing is vanilla browser based printing

## Tasks
 - [x] 1) create summary view (with create order link) (Jojo ustaxcourt/ef-cms-flexion#3123)
 - [x] 2) create interactor and proxy for fetching the orders (Cody)
 - [x] 3) actions and sequence for fetching orders and adding them to the state
 - [x] 4) add the link to the petition view to summary screen (Jojo ustaxcourt/ef-cms-flexion#3127)
 - [x] 5) print orders needed summary view (Jojo ustaxcourt/ef-cms-flexion#3131)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Jojo ustaxcourt/ef-cms-flexion#3151)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo ustaxcourt/ef-cms-flexion#3151)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment (Jojo ustaxcourt/ef-cms-flexion#3153)
