### ISSUE TITLE
Docket Clerk: QC of Incoming Documents/Edit Docket Entries

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6777]
As a Docket Clerk, in order to correct any errors in the docket record, I need the ability to edit an existing docket entry.

When a Docket Clerk is reviewing an incoming document, one of the things that the Docket Clerk will do is make sure that the information provided by the filer, and the docket entry that populated from the information is accurate.  If the Docket Clerk notices an error, they need the ability to manually correct (edit and save) a Docket Entry.  If the Docket Clerk edits a docket entry, that change needs to be captured in two ways: (1) the corrected entry now displays in place of the original entry; and (2) a Notice is generated summarizing the change. 

## Pre-Conditions
* Incoming filing (other than a Petition) has been routed to Docket Section.

## Acceptance Criteria
* Docket Clerk can manually correct (edit and save) any part of a docket entry.  The corrected entry displays (overwrites the original) in the docket record after save.
* Ability to Complete and also complete and send message.
* Add detail on page on who did the QC with date/time stamp (document detail page once QC is complete)
* Docket Clerk can indicate within the CMS that the QC is complete
* Docket Clerk can indicate within the CMS that the QC is complete AND send a message to another user in one step
* Message generated would start a new message thread
* Once the QC process is complete the work items is removed from the individual and section QC inbox
~ Add column for who did QC on processed tab ~ added to ustaxcourt/ef-cms#6947
* Once the QC is complete, the document displays in the "processed" tab
* After 7 days, the document no longer displays in the "processed" tab
* Add the non-standard selections fields to the form (Filing/Proceedings, document title should update when document type changes to reflect change)

## Research/Analysis Notes
* Per Tina & Stephanie: OK to abandon practice of putting 2nd cover sheet on top of document to correct information.  Strike-through approach is fine.  However, this is more technically difficult, so going to proceed with 2nd cover sheet as short-term solution.
* Design idea for how to tell whether a document has been QC'ed or not -- document shows up in red on the docket record until QC is complete

#### Scenario 1 - Docket Clerk can manually correct (edit and complete) any part of a docket entry. The corrected entry displays (overwrites the original) in the docket record after save.
1. Log in as a docket clerk
2. Navigate to My Document QC section.
3. Select one of the documents
4. Make Edits to the document (Title, Date)
5. Click Complete

Expected result
- [x] Document opens in edit mode
- [x] Document moves to the processed section of document QC
- [x] Success messages displays stating document was saved. 

#### Scenario 2 - Docket Clerk can manually correct (edit complete and send a message) any part of a docket entry. The corrected entry displays (overwrites the original) in the docket record after save.
1. Log in as a docket clerk
2. Navigate to My Document QC section.
3. Select one of the documents
4. Make Edits to the document (Title, Date)
5. Click Complete and Send Message button
6. Create a Message and Send

Expected result
- [x] Document opens in edit mode
- [x] Document moves to the processed section of document QC
- [x] Create Message modal appears
- [x] Success messages displays stating document was saved and Message was sent

#### Scenario 3 - Docket Clerk can manually correct (edit and save) any part of a docket entry. Once the document has been completed (docket entry)
1. Log in as a docket clerk
2. Navigate to Docket Record Tab of Docket page
3. Select one of the documents
4. Click Edit link
5. Edit the document
6. Click complete

Expected result
- [x] Document opens in edit mode
- [x] Success messages displays stating document was completed

#### Scenario 4 - Docket Clerk can manually correct (edit and save) any part of a docket entry. Once the document has been completed (processes tab of Session Doc QC)
1. Log in as a docket clerk
2. Navigate to Session Document QC section processed tab.
3. Select one of the documents
4. Click Edit link
5. Edit the document
6. Click complete

Expected result
- [x] Document opens in  non-edit mode
- [x] Document changes to edit mode after edit link has been clicked
- [x] Edits can be made and saved

#### Scenario 5 - Completed time stamp and owner will on Document Detail page displays
1. Follow steps 1-3 from Scenario 3
2. Verify that the Court Personnel that completed the QC's Name appears along with time/date stamp under the Filed by line under heading

Expected result
- [x] Name of user who completed QC and time/date line appears on page

#### Scenario 6 - non-standard selections fields are added to the form (Filing/Proceedings, document title should update when document type changes to reflect change)
1. Log in as a docket clerk
2. Navigate to Session Document QC section processed tab.
3. Select one of the documents
4. Click Edit link
5. change document type to affidavit in support
6. Select who signed this.
7. Click complete

Expected result
- [x] Document opens in  non-edit mode
- [x] Document changes to edit mode after edit link has been clicked
- [x] After document type change secondary dropdown appears
- [x] Document changes have been saved

## Tasks
- [x] 1.  Edit Docket Entry view(William/Kris ustaxcourt/ef-cms-flexion#3256)
  - [x] Tabs with Document Info and Messages
- [x] 2. Edit Docket Entry links (Kris/William ustaxcourt/ef-cms-flexion#3266 ustaxcourt/ef-cms-flexion#3315)
  - [x] 2a. Docket Record
  - [x] 2b. Docket QC links
  - [x] 2c. Validate document detail view shows up for 'processed' documents
- [x] 3. Add auto save functionality for edit docket record screen. (William ustaxcourt/ef-cms-flexion#3265)
  - [x] save but doesn't apply until the docket entry is completed
- [x] 4. Complete docket entry sequence (William ustaxcourt/ef-cms-flexion#3282)
  - [x] Validate correct success message generated
- [x] 5. Complete docket entry and send message sequence (William ustaxcourt/ef-cms-flexion#3313)
	- [x] Rewrite CreateMessageModalDialog so that you can run a sequence after a message send
	- [x] ~Use Case Helper for sending messages~
	- [x] Validate correct success message generated
- [x] ~6. Processed document list~
	- [x] ~Remove item from 'processed' list after 7 days (can we use ttl? truncate to midnight?)~
- [x] 7. Edit button link display on document detail page for internal users. (Kris ustaxcourt/ef-cms-flexion#3299)
- [x] 8. Rewrite CreateMessageModalDialog so that it doesn't use form (William ustaxcourt/ef-cms-flexion#3280)
- [x] 9. auto save functionality puts item 'In Progress' (William ustaxcourt/ef-cms-flexion#3295 ustaxcourt/ef-cms-flexion#3298)
- [x] 10. Validation (Jojo ustaxcourt/ef-cms-flexion#3311)
- [x] 11. Display processed by on Document Detail page (Kris ustaxcourt/ef-cms-flexion#3308)
- [x] 12. Verify that clicking link into edit screen marks work item as read. (William ustaxcourt/ef-cms-flexion#3325)
- [x] 13. Bug: Redirects to blank page after "Complete & Send Message" on develop (unsure about just "Complete") (Jojo -- no PR needed, used invalid seed data on `develop` env)
- [x] 14. Bug: Document name not being transpiled (i.e. `[Name]` translated to `Guy Fieri`) (William ustaxcourt/ef-cms-flexion#3335)
- [x] 15. Bug: Free text fields not persisting (`freeText` / `freeText2`) after completing the docket entry (William ustaxcourt/ef-cms-flexion#3343)
- [x] 16. Bug: QC'd by date not showing in Document Detail Header after completed (Kris ustaxcourt/ef-cms-flexion#3352)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
