### ISSUE TITLE
Docket Clerk: Ability to upload/file paper-filed external filing

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6778]
As a Docket Clerk, in order to get a paper document into a case, I need the ability to upload and file a paper-filed document.

The Court will continue to receive paper documents/filings from the parties, especially from pro-se Petitioners.  In order to get those paper-filed documents into the proper case, a Docket Clerk will need the ability to scan and upload the paper document into the electronic case.

## Pre-Conditions
* Docket Clerk has a paper document that needs to be filed in a case

## Acceptance Criteria
* Docket Clerk has the ability to search for doc type by name or code (see note below)
* Docket Clerk has the ability to upload a document into a case record
* Docket Clerk must provide all of the other information required for filing a document (#936), including whether a document should be filed or lodged
* Docket Clerk must be able to manually provide the "filed" or "lodged" date for each document
* Docket Clerk is able to add additional text that will be added to the document title on the cover sheet
* Docket Clerk is able to add additional text that will be added to the end of the docket entry
*  A docket entry is populated in accordance with Court-provided rules (#937)
* ~~The Docket Clerk can upload the associated document at time of docket entry creation or anytime thereafter~~ [holding for another story]
* After the Docket Clerk uploads the document, it is viewable to all parties and internal Court users on the docket record

## Notes
* Per Tina - a Docket Clerk should not need the drill down approach we are building for the parties.  A Docket Clerk should either know the doc code or be able to search for a known doc title/type. BUT, per Rhonda - a Docket Clerk needs the drill-down approach.  Let's show them both and decide!
* Per Rhonda: the Docket Clerks will not need any of the "Turbo-tax" like questions we utilized for Petitioners.  As long as they have all the fields they need to upload/file the paper document, we can dispense with the extra messaging.
* Consider revamping or tweaking the public upload functionality (search, etc). (needs to be in another story)
* Archived design documentation for previous iterations here: https://drive.google.com/open?id=1M0llL3azVw5H5wRLSxn5A2ZFLTgoFGsXYoqoSSdasyI

## Tasks
- [x] 1. Create "Add Docket Entry" button, sequence, route (kris ustaxcourt/ef-cms-flexion#1564 )
- [x] 2. Create "Add Docket Entry" views 
  - [x] 2a. First iteration: primary w/o secondary doc and hardcoded doc type (use StateDrivenInput) (Rachael)
  - [x] 2b. Supporting docs screen (Rachael ustaxcourt/ef-cms-flexion#1578)
  - [x] 2c. Integrate dynamic event code / doc type (William ustaxcourt/ef-cms-flexion#1583 ustaxcourt/ef-cms-flexion#1590)
  - [x] 2d. Show nonstandard forms if needed based on document type selected (Rachael/Kris ustaxcourt/ef-cms-flexion#1597)
  - [x] 2e. Show secondary doc form if needed (Rachael/Kris ustaxcourt/ef-cms-flexion#1598)
- [x] 3. Create Event Code / Document Type lookup component interaction (develop independent of first screen) (kris ustaxcourt/ef-cms-flexion#1576 )
  - [x] 3a. update styling for select-react component (Rachael ustaxcourt/ef-cms-flexion#1580)
  - [x] 3b. alter select menu to prioritize eventCode matches first when sorting (kris ustaxcourt/ef-cms-flexion#1585)
- [x] 4. Docket Entry Entity validation rules
  - [x] 4a. Create Docket Entry Entity validation rules (primary) (William ustaxcourt/ef-cms-flexion#1570)
  - [x] 4b. entity validation rules for secondary, primary supporting, secondary supporting
- [x] 5. Cleanup
  - [x] 5a. unselecting primary doc type (with X) does not remove secondary document dropdown (William ustaxcourt/ef-cms-flexion#1603 ustaxcourt/ef-cms-flexion#1610)
  - [x] 5b. secondary nonstandard form isn’t showing up (William ustaxcourt/ef-cms-flexion#1604 ustaxcourt/ef-cms-flexion#1610)
  - [x] 5c. additional info 1 should be appended to document name in docket record (Rachael ustaxcourt/ef-cms-flexion#1617)
  - [x] 5d. additional info 2 should be appended to entire docket record entry (Rachael ustaxcourt/ef-cms-flexion#1617)
  - [x] 5e. verify that practitioners are showing under parties filing (Rachael/Kris ustaxcourt/ef-cms-flexion#1611)
  - [x] 5f. switch text on secondary button on supporting documents page (Rachael ustaxcourt/ef-cms-flexion#1615)
  - [x] 5g. on supporting documents page, Affidavit and Declaration should have a field for “Supporting Document Signed By” (William ustaxcourt/ef-cms-flexion#1612)
  - [x] 5h. hide Inclusions section on supporting documents if “Which Document is This Supporting?” is the secondary document (William)
  - [x] 5i. supporting documents should inherit filing status, date received, filing parties from the primary document (William ustaxcourt/ef-cms-flexion#1609﻿﻿)
  - [x] 5j. secondary document should inherit date received, filing status, and filing parties from primary document (William ustaxcourt/ef-cms-flexion#1609)
  - [x] 5k. add isPaper to documents so the paper filed icon shows up on the docket record (William ustaxcourt/ef-cms-flexion#1607)
  - [x] 5l. Kristen reported a bug from a previous story that needs to be verified/fixed when cleanup is complete - "I'm seeing what could be a bug on the docket entries filed by Practitioner. We saw this during usability testing and I just confirmed. When a practitioner files a primary doc and supporting doc and selects "Myself..." and "Petitioner Name" as filing parties- they both show for the primary document, but only Petitioner is showing in Filed By for the supporting document. Whatever filed by is selected for primary should apply to both. See docket 1119-19L- under practitioner1"
- [x] 6. UX Review Items to Address
  - [x] 6a. Create updated internalFilingEvents.json from spreadsheet (kris ustaxcourt/ef-cms-flexion#1637)
  - [x] 6b. Create NonStandard I entity, tests, getDocumentTitle func (kris)
  - [x] 6c. Create NonStandard J entity, tests, UI updates, computed updates, getDocumentTitle func
- [ ] 7. PO Review Items to Address
  - [x] 1. The upload of a paper document by a Docket Clerk should not create a new message thread.  There are a lot of unnecessary messages on 231-19 because each new document/docket entry is creating a new message. (Rachael ustaxcourt/ef-cms-flexion#1672)
  - [x] 2. If you start typing text in the Additional Info. boxes and then erase it because it was a mistake, it throws an error when you try to submit the filing.  It does this on both the main document and supporting doc page. And, the error is not clear; it doesn't tell you what the problem is.  It took me several attempts to realize that's what was causing it. (William ustaxcourt/ef-cms-flexion#1671)
  - [x] 3. If the Court has a paper Request for Place of Trial, that docket entry should be hyperlinked to the PDF that was uploaded.  This is treated differently than an electronic petition submission where we just listed the entry without hyperlink.
  - [x] 6. Design question -- and if this is a lot of effort, please ignore -- when you are adding a supporting document, it asks you which doc you are filing it in support of.  If there is only 1 doc (as in most cases), is this question even necessary?  Maybe the drop-down is only necessary where there is a primary & secondary doc in the case of Motion to Leave & Motion for Leave to File Out of Time. - Discussed with Kristen having the dropdown with the previous doc already selected if there is only one option (a simpler solution that will still reduce unnecessary clicks). (Rachael ustaxcourt/ef-cms-flexion#1676)
   - [x] 4. Remove timestamp on coversheets generated from paper documents (William ustaxcourt/ef-cms-flexion#1675)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning (William ustaxcourt/ef-cms-flexion#1623)
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
