### ISSUE TITLE
CMS: Auto-serve externally filed documents (electronic)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6779]
As a party in the case, so that other parties in the case may be served with my documents electronically, I need the system to auto-serve my document to the other parties. 

## Acceptance Criteria
* When externally filed documents are filed electronically, the system auto-serves the document to all parties in the case that have a "electronic" indicator for service
* The system should *NOT* automatically serve any document with "Simultaneous" in the document title [Note: These are manually served by Docket once all documents are filed]
* A service date is captured on the cover sheet at the time of service and is placed in the bottom center of the first page of the document when served
* The service date and parties served is captured on docket record (already done)
* Parties in the case who receive electronic service receive a service email (already done)
* Parties in the case can access the served document via the docket record (already done)
* If a new cover sheet is generated after the QC, the SAME served date is reapplied to the new cover sheet and document is *not* re-served

## Notes:
* Email integration for service on parties is in Epic ustaxcourt/ef-cms#6653. 
* No need to consider paper service because the party will do that on their own.

## Tasks
- [x] 1 Add service emails and set documents served in interactors for filing external documents (Rachael ustaxcourt/ef-cms-flexion#3790) 
- [x] 2 Verify If a new cover sheet is generated after the QC, the SAME served date is reapplied to the new cover sheet (Rachael)
- [x] 3 add “Served” to bottom of coversheet, check font size (too big?) (Rachael ustaxcourt/ef-cms-flexion#3794)
- [x] 4 filter out “Simultaneous” docs from being auto-served (Rachael ustaxcourt/ef-cms-flexion#3794)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
