### ISSUE TITLE
Epic 3 Clean-up

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6782]
Epic 3 Clean-up

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Acceptance Criteria

**Log out Behavior**
* ~~After auto logout / session timeout, user sees a page-level error for a few seconds before the cognito login screen loads (SLR)~~ (Cannot reproduce- removed)
* ~~Modals can be invoked from pages even after auto logout / session timeout (SLR)~~ (Cannot reproduce)

**Documents**
* ~~Consider adding design cues to indicate that the docket table is scrollable~~ (Removed per Jessica)
* ~~Consider indicating file size on document detail page~~ (Removed per Jessica) 
* Change text on "uploading" docket record tag to "processing" 
* Add a remove option for supporting docs once selected on File a Document form 
* Concatenated doc name is not displaying correctly on Doc Detail page (see example for First Amended Petition) 
![Screen Shot 2019-09-30 at 9.27.14 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/98903602-0f82-431a-8769-1190e5cfc558)

**Filed By Date/Time** 
- [ ] All times should be displayed as hh:mm am ET (need to add ET to all displayed times) and drop the leading 0 when the time is a single digit (EXCEPT the time on the Add Trial Session form and Trial Session Detail screen)
- [ ] Update "Received" label on message thread to "Sent on" 
![Screen Shot 2019-08-15 at 12.15.14 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bfb5a2e1-3ee3-424c-9f81-4897ec45437a)
- [ ] For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread. 

**Navigation / Docket Header**
- [ ] The header on the printable docket record PDF viewer page - the docket number should be hyperlinked back to the case detail page - THIS IS A GLOBAL BEHAVIOR AND SHOULD BE CREATED AS A GLOBAL COMPONENT SO WE DON'T HAVE TO REMEMBER TO DO IT EACH TIME
- [ ] Caption edit link falling to third line on long case names￼￼

## Tasks
- [x] 1 Change text on "uploading" docket record tag to "processing" (Kristen ustaxcourt/ef-cms-flexion#2808)
- [x] 2 Add a remove option for supporting docs once selected on File a Document form (William ustaxcourt/ef-cms-flexion#3179)
- [x] 3 Concatenated doc name is not displaying correctly on Doc Detail page (see example for First Amended Petition) (William ustaxcourt/ef-cms-flexion#3172)
- [x] 4 All times should be displayed as hh:mm am ET (need to add ET to all displayed times) and drop the leading 0 when the time is a single digit (EXCEPT the time on the Add Trial Session form and Trial Session Detail screen) (Kris ustaxcourt/ef-cms-flexion#3185 )
- [x] 5 Update "Received" label on message thread to "Sent on" (William ustaxcourt/ef-cms-flexion#3173)
- [x] 6 For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread.  (William ustaxcourt/ef-cms-flexion#3184)
- [x] 7 The header on the printable docket record PDF viewer page - the docket number should be hyperlinked back to the case detail page - THIS IS A GLOBAL BEHAVIOR AND SHOULD BE CREATED AS A GLOBAL COMPONENT SO WE DON'T HAVE TO REMEMBER TO DO IT EACH TIME (Cody ustaxcourt/ef-cms-flexion#3077)
- [x] 8 Caption edit link falling to third line on long case names (Rachael ustaxcourt/ef-cms-flexion#3189)
- [x] 9 For docket clerks when they add a docket record, they enter a "received date." This date is what should appear in the "Filed by" under the doc name on doc detail page and what appears for both "received" and "filed" on the cover sheet. The date the document was entered into the system should be displayed as the "Sent On" date on the message thread.  (Verify that petition works the same way) (William ustaxcourt/ef-cms-flexion#3192)
- [x] 10 Refactor storage of supportingDocumentCount in state - mentioned in ustaxcourt/ef-cms-flexion#3179 (Rachael ustaxcourt/ef-cms-flexion#3193)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
