### ISSUE TITLE
SPIKE::  Petitions & Docket: Ability for court users to scan paper documents directly into the system 

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6785]
As a Petitions Clerk or Docket Clerk, in order to make sure the right document gets uploaded, I need the ability to scan paper documents directly infor the system.

The Court will continue to receive paper Petitions and other paper filings.  As a result, Petitions Clerk and Docket Clerks will need the ability to get those paper documents into the system.  The idea that a clerk would scan, save, and upload the document leaves a lot of room for error that the wrong document will be uploaded.  Plus, it involves multiple steps.  To avoid this, the Petitions Clerks and Docket Clerks will need the ability to directly scan a document into the system.

## Pre-Conditions:
* Petitions Clerk or Docket Clerk has paper filing

## Acceptance Criteria:
* Petitions Clerk or Docket Clerk has the ability to scan paper documents directly into the system without having to perform a separate scan, save and upload function. [See note re: multiple scans for large documents]
* The Petitions Clerk or Docket Clerk can see that the document has been scanned successfully into the system

## Notes:
* Implementation/design will be handled in other stories: ustaxcourt/ef-cms-flexion#1895 for Petitions Clerk and ustaxcourt/ef-cms-flexion#1896 for Docket Clerk
* Cody recommended a web-based solution during our 3/12/19 design meeting.
https://www.dynamsoft.com/Products/WebTWAIN_Overview.aspx
* If Flexion recommends that the Court use a COTS product for this functionality, that will need to get Court approval.  The Court would need Flexion to provide a recommendation that includes: (1) that Flexion is recommending a certain COTS product and why (i.e., it performs the exact functionality we need; the time it would take to build it is cost-prohibitive, etc.); (2) a statement that there is no equivilant product available from open source software; and (3) the expected expense to the Court for the COTS product.

## Tasks ##
- [x] Research licensing for third-party software (Matt)
- [x] Proposal to Court for purchasing of software (Matt - GoogleDocs)
- [x] Replacing/hosting files (standing up server to serve third-party files) (Cody ustaxcourt/ef-cms-flexion#1909)
- [x] Deploy method for third party files  (Cody ustaxcourt/ef-cms-flexion#1909)
- [x] Scanner library implementation in the web app (Matt ustaxcourt/ef-cms-flexion#1919)
- [x] Generation of PDF from scanner data (Matt ustaxcourt/ef-cms-flexion#1919)
- [x] Store scanner device preference (Matt ustaxcourt/ef-cms-flexion#1919)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**Engineering**
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
