### ISSUE TITLE
Practitioner: File Documents before associated w/ case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6786]
As a Practitioner, in order to get access to case records, there are certain documents that I need to be able to file *before* I am associated with a case. 

In addition to filing an Entry of Appearance or Substitution of Counsel, a Practitioner needs to be able to file specific documents *before* they are associated with the case.  Those documents are:
* Motion to Substitute Parties and Change Caption
* Notice of Intervention
* Notice of Election to Participate
* Notice of Election to Intervene

Unlike an Entry of Appearance or Substitution of Counsel, which automatically associate a Practitioner with a case upon filing, these document do not.  Rather, a Docket Clerk has to manually associate the Practitioner with the case upon QC'ing the document.

## Pre-Conditions
* Practitioner is logged in and wants to file a document in a case that they are not associated with

## Acceptance Criteria
* In addition to an Entry of Appearance and Substitution of Counsel, Practitioner is able to file the following documents before being associated with a case: 
 (1) Motion to Substitute Parties and Change Caption (M107)
 (2) Notice of Intervention (NOI)
 (3) Notice of Election to Participate (NOEP)
 (4) Notice of Election to Intervene (NOEI)
* Filing is routed to Docket Section for QC
* Filing does NOT automatically associate Practitioner with case [Note: Only Entry of Appearance and Substitution of Counsel automatically associate Practitioner with case ustaxcourt/ef-cms#6703]
* External user can perform this task on mobile device

## Notes
* Builds upon work done on ustaxcourt/ef-cms#6703

## Tasks

- [x] 0 Request Access Form Updates (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 1 Update radio set to drop-down (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 2 Update form fields to display Exhibits/Attachments/Objections based off of document selection (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 3 Add supporting document form for Motion document (William ustaxcourt/ef-cms-flexion#1911)
- [x] 4. Update Review screen to show added fields (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 8 should "Certificate of Service" show up in "Filing Includes"?  (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 9 Generate Supporting Document title (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 10 remove petitioners from title from new documents  (William ustaxcourt/ef-cms-flexion#1911)
- [x] 5. Update Validation for new fields (William ustaxcourt/ef-cms-flexion#1911)
- [x] 6. Submission that creates pending request for practitioner association (William ustaxcourt/ef-cms-flexion#1911 ustaxcourt/ef-cms-flexion#1923)
- [x] 7. Case Detail view updates for a practitioner with a pending access request  (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 7a Request Access button is hidden (William ustaxcourt/ef-cms-flexion#1911)
  - [x] 7b Label is displayed “Request for Access Pending” (William ustaxcourt/ef-cms-flexion#1911)
- [x] 11 Case journey test (William ustaxcourt/ef-cms-flexion#1911)
- [x] 12 Do not allow access to 'request access' page is request is already pending (William ustaxcourt/ef-cms-flexion#1920)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (William ustaxcourt/ef-cms-flexion#1922)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library] (Rachael ustaxcourt/ef-cms-flexion#1926)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
