### ISSUE TITLE
Court: Each party needs to have a service indicator

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6787]
As the Court, in order to make sure each party is getting served in the appropriate manner, each party needs to have a service indicator.

Each party to a case should have a service indicator (Electronic, Paper, None).  When a party initiates a case electronically, their default service should be electronic service.  When a party initiates a case in paper, their default service should be paper service.  

## Pre-Conditions
* A case has been created with a party associated to it

## Acceptance Criteria
* Each party to a case needs to have a service indicator at all times 
* The service indicator options are Electronic, Paper, or None.
* When a Petitioner starts a case in paper, their service indicator should default to Paper.
* When a Petitioner starts a case electronically, their service indicator should default to Electronic.
* When a Practitioner starts a case electronically, their service indicator should default to Electronic and the Taxpayer's service indicator should default to None.
* When a Practitioner starts a case in paper, their service indicator should default to Electronic (if they have an account) and Paper (if not)  and the Taxpayer's service indicator should default to None. 
* The service indicator for IRS attorneys should always default to Electronic. 
* The service indicator needs to be easily viewable to all other parties.

## Notes
* This story doesn't not include editing the indicator, which is handled in ustaxcourt/ef-cms-flexion#1130.

## Tasks
 - [x]  Encapsulate SI logic into function with tests (Matt ustaxcourt/ef-cms-flexion#2837)
 - [x]  Implement SI Logic in Case Detail (Joe ustaxcourt/ef-cms-flexion#2838)
 - [x]  Update UI (Joe ustaxcourt/ef-cms-flexion#2838) 

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo ustaxcourt/ef-cms-flexion#2842)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
