### ISSUE TITLE
Court: Dummy IRS Repository

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6788]
As the Court, in order to practice serving Petitions and other documents on the IRS, we need a dummy IRS repository.

## Pre-Conditions:
* A document in a case is ready to be served on the IRS

## Acceptance Criteria:
* For a newly created case, all documents existing in the case at the time it is set to be served to the IRS (either by forced service or default time), must be Zipped together into 1 file
* The Zip file should be titled with the Docket No and Petitioner's last name
* Service can happen either by "forcing" the batch process to run, or at a pre-set time.
* The STIN has been successfully transmitted in the Zip file and removed from the documents S3 bucket
* The status of the case is changed to "General Docket"
* The served date and time is entered into the docket record
* When a Petition is "Batched for IRS", the message thread that is created when a Petition is filed should be hidden on the case detail page and document detail page.  
* If a Petition is "Recalled", a new message should be added to the message thread created when the petition is filed, and the new message should show up on the recaller's inbox (as well as section inbox) and that pending message should display on the case detail page and document detail page.  
* Once a Petition is served on the IRS, the message thread should be Completed (show up under Complete tab on the doc detail page)--the final message in the thread should be "Served on IRS at [date, time]"

## Tasks
Note: use existing S3 bucket for zip files
- [x] create an endpoint for starting the force batch process (Rachael / Cody ustaxcourt/ef-cms-flexion#1133)
- [x] add a button for starting this batch process (action, sequence, proxy) (Rachael / Cody ustaxcourt/ef-cms-flexion#1133)
- [x] create the interactor for doing the batch process (Rachael / Cody ustaxcourt/ef-cms-flexion#1133)
  - [x] repeat the steps for all cases in the IRS holding queue  (cody)
  - [x] fetch all documents in the case and put them into a zip (Rachael / Cody ustaxcourt/ef-cms-flexion#1133)
  - [x] upload the zip to s3 (Rachael / Cody ustaxcourt/ef-cms-flexion#1133)
  - [x] put the s3 related logic into persistence gateway methods (cody)
  - [x] double check the s3Endpoint is using valid s3 endpoints when deployed
  - [x] delete the STIN file associated with the case
  - [x] include https://www.npmjs.com/package/sanitize-filename for file names
  - [x] update case status to General Docket (#1137)
  - [x] add an entry to the docket record saying when the case was processed by the batch date and 
time
  - [x] set the work item associated with the "sent to irs holding queue" to completed after the batch process runs (Rachael)
- [x] display a link in the docket record for someone to download the zip (William ustaxcourt/ef-cms-flexion#1138)
- [x] hide the IRS Holding Queue message from the case detail page (cody)

## Definition of Done
- Product Owner
  - [ ] acceptance criteria have been met
- UX
  - [x] usability has been validated
- Engineering
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] alerting and monitoring for new functionality in place and successfully exercised
