### ISSUE TITLE
Docket Clerk: Edit Case Information

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6789]
As a Docket Clerk, in order to change case metadata, I need the ability to edit the information in the Case Information tab.

When a Docket Clerk is reviewing an incoming document, there might be the need to update case metadata based on the filing.  The Docket Clerk needs the ability to edit all case metadata on the Case Information tab.

## Pre-Conditions:
* Incoming filing (other than a Petition) has been routed to Docket Section.

## Acceptance Criteria
* Docket Clerk [permissions based] must have the ability to modify any case metadata on the Case Information tab: Notice/Case Type, Case Procedure, IRS Notice Date, Requested Place of Trial, Party Type, Petitioner's Contact Information.  Note: Changing Service Preference is addressed in ustaxcourt/ef-cms#6790
* If the Docket Clerk changes the Notice/Case Type or Case Procedure type, the Docket number should automatically update, if necessary [NOTE: this should *not* create a Minute Entry on the docket record; that logic should be broken after Petition QC process; this will be preceded by an Order after the Petitions QC process ustaxcourt/ef-cms#7012]
* If the Docket Clerk changes the contact information for any petitioner in the case, that updated contact information should be viewable to all parties and internal users.
* If the Docket Clerk changes the contact information for any petitioner in the case, that should automatically generate a Notice of Change of Address/Phone Number/Both. [Note: consider how to handle attorneys who may be in more than 1 case] 

## Notes
* If court changes address, also needs to generate a change of address
* For MVP, we don't need the ability to change practitioner's, attorney's or respondent's information at the case level

## Tasks
- [x] 1 Remove "Party Type" field from Case Detail > Case Information > Overview and add to Case Information -> Petitioner tab (Rachael ustaxcourt/ef-cms-flexion#4052)
- [x] 2 Update Edit Petition Details screen with new fields (Rachael ustaxcourt/ef-cms-flexion#4052)
- [x] 3 Modify existing interactor/sequence (updatePetitionFeePaymentSequence/Interactor) to modify new fields (Rachael ustaxcourt/ef-cms-flexion#4053)
  - [x] 3a If case type or case procedure are updated, the docket number should automatically update if needed (Rachael ustaxcourt/ef-cms-flexion#4053)
- [x] 4 Check form validation (see error messages in story comment) (Rachael)
- [x] 5 Add Edit button to Petitioner Information card for internal users (Cody ustaxcourt/ef-cms-flexion#4056)
- [x] 6 Create Edit Petitioner Information route and view (Cody ustaxcourt/ef-cms-flexion#4056)
- [x] 7 Endpoint to submit petitioner information (Kris)
  - [x] 7a If address and/or phone was updated, generate Notice of Change of Address
- [x] 8 Sequences and actions to submit petitioner information (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
