### ISSUE TITLE
Docket Clerk: Edit Service Indicator

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6790]
As a Docket Clerk, in order to make sure that each party gets served in an appropriate manner, I need to be able to update a party’s service indicator.

When a party initiates a case electronically, their default service is electronic service.  When a party initiates a case in paper, their default service will be paper service.  However, over the life-cycle of a case, a party may want to change how they get service.  In order to make sure that each party is getting served in an appropriate manner, a Docket Clerk needs the ability to update a party’s service indicator.

## Pre-Condition:
•	Each party has a service indicator (#1072)

## Acceptance Criteria:
* The Docket Clerk must be able to change the service indicator on each party (from electronic to paper or electronic/paper to non only; paper to electronic will be post MVP.)
* Changing the service indicator for one party does not affect service indicator for other parties
* The options for service indicator for each party should be Electronic, Paper, None

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Changing service indicator from paper to electronic out of scope? concerns with party registration and jurisdiction. 

## Tasks
- [x] 1 Add Service Information to Edit Petitioner Information screen (Rachael ustaxcourt/ef-cms-flexion#4223)
- [x] 2 Update interactor to edit petitioner’s service information (Rachael ustaxcourt/ef-cms-flexion#4223)
- [x] 3 Create action to validate that they are not going from paper/none to electronic (All ustaxcourt/ef-cms-flexion#4230)
- [x] 4 Allow service indicators to be stored on the user objects (petitioner, practitioner, and respondents) (Cody, Rachael)
- [x] 5 Update setServiceIndicatorsForCase to check for a service indicator for each user (Cody, Rachael)
- [x] 6 Add Service preference to Add/Edit Petitioner/Respondent counsel modals  (Cody ustaxcourt/ef-cms-flexion#4222)
- [x] 7 Update interactor for adding/editing counsel to set service indicator (Cody ustaxcourt/ef-cms-flexion#4222)
- [x] 8 Create Service preference component (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
