### ISSUE TITLE
Bugs: Found during Sprint 10 Review Prep

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6791]
High priority (fix before sprint review):
- [x] Fee paid displaying multiple times in docket record during petitions QC process. (William ustaxcourt/ef-cms-flexion#1142)
- [x] Remove ZIP file from docket record and display outside of docket record on the case detail page (petitions QC) (cody)
- [x] Remove from docket record "Case sent to IRS" message that displays when batch is sent to IRS (petitions QC) (cody)
- [x] Modal for message thread - can't click "Send" or save. UX issue. Would be nice to have fixed before sprint review, but could work around.  (kris ustaxcourt/ef-cms-flexion#1144)

Medium priority
- [x] Jessica getting automatically logged out when clicking "Send to IRS" (cody)
- [x] On the case detail page, when clicking into the document view, "Case Info Tab" should not display and "Messages" tab should default to left of document when status is anything other than New, Batched for IRS or Recalled (William ustaxcourt/ef-cms-flexion#1146)
- [x] Horizontal and vertical scrolling - remove horizontal scroll everywhere and vertical anywhere no scroll is required.  E.g.) on the message thread complete boxes; document info box (Rachael ustaxcourt/ef-cms-flexion#1141)
