### ISSUE TITLE
Court: Viral scans for document uploads (Clam AV)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6792]
As the Court, in order to protect the CMS system from potential viral threats, we need to implement virus-scanning for document uploads. 

## Pre-Conditions
* External party is uploading/filing a document. 

## Future Dependency
* Error handling for viral scans (#1894)

## Acceptance Criteria
* All document uploads are scanned for viral threats
* Documents that have been identified to have viral threats are stopped from entering the CMS
* If a threat is detected as a part of the Petition, the case is prevented from being created

## Notes
- the user needs to be told which file(s) have a virus
- clamscan node package https://www.npmjs.com/package/clamscan
- the maximum temp space for AWS Lambda is 512 MB, which is too small to hold a 500 MB PDF and 112 MB of virus definition
- we may be able to split a large PDF into 2 and scan each piece separately
- per Jessica 5.24.19: If we need to lower the PDF upload limit to 350MB (approx. 3000 pages) to allow for the ClamAV functionality, that will be fine.  However, the Court would need Flexion to implement something to track how many PDF uploads in excess of 350MB are attempted to be uploaded once the system goes live so that we can reassess this 350MB max size if it's preventing too many docs from being filed.  
 
## Tasks
- [x] upgrade node version (Eric) ustaxcourt/ef-cms-flexion#1910
- [x] lambda layers for clamav (Joe) ustaxcourt/ef-cms-flexion#1904
- [x] virus scan interactor, lambda, proxy (Eric) ustaxcourt/ef-cms-flexion#1910
- [x] virus scan interactor test ustaxcourt/ef-cms-flexion#1910
- [x] virus scan cerebral action (Joe) ustaxcourt/ef-cms-flexion#1928

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
