### ISSUE TITLE
Court: Maximum Upload Size for External Users

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6794]
As the Court, in order to avoid very large documents from being uploaded, we need to set the maximum upload size for external users at 500MB.

The Court may, from time to time, receive *VERY* large documents in a case.  In order to avoid any degradation in service (i.e., opening PDF) and to allow an external filer to upload a document within the 1 hour time-out period, the Court needs to set some reasonable upper-limit for file size limitations.  The Court has decided that limit should be 500MB.

## Pre-Conditions
* External party is filing/uploading a document.

## Acceptance Criteria
* All file uploads by external filers should be limited to 500MB
* The system should prevent the user of uploading a file that is over 500MB
* The system should warn the user if they try to upload something larger than 500MB
* The file upload is not bound by the user activity timeout function (#837)
* User can track the progress of upload
* User can see the estimated time remaining for file upload
* User can cancel upload at any time before the upload is complete
* If a user cancels a document upload or the document upload is unsuccessful, no part of the document or data associated with the document should be saved in the system
* If a user cancels an "Start a Case" upload or the upload is unsuccessful, no case should be generated.

## Notes
* Progress indicator applies to external uploads (petitioner and practitioner) ONLY at this time.

## Tasks
- [x] Add final decision UX wiki regarding global file size, file type and help text requirements
- [x] Make text changes, coming from @sarahridgway
- [x] Add 500 MB limit in the petition entity validation (Joe ustaxcourt/ef-cms-flexion#1577)
- [x] Add 500 MB limit in the stin entity validation (Joe ustaxcourt/ef-cms-flexion#1593)
- [x] Add 500 MB limit in the external documents entity validation (Eric)
- [x] Add 500 MB limit in the petition from paper entity validation (Joe ustaxcourt/ef-cms-flexion#1599)
- [x] add validation error message to all file input views (Eric ustaxcourt/ef-cms-flexion#1601)
- [x] Limit external file size uploads with S3 policy (Joe ustaxcourt/ef-cms-flexion#1577)
- [x] trigger sequence to update state with number of bytes uploaded (Cody ustaxcourt/ef-cms-flexion#1587)
- [x] trigger sequence to update state with time of upload start
- [x] calculate % upload complete (Cody ustaxcourt/ef-cms-flexion#1587)
- [x] calculate time remaining based on % complete vs time spent uploading (Cody ustaxcourt/ef-cms-flexion#1587)
- [x] sequence for cancelling an upload (Matt ustaxcourt/ef-cms-flexion#1606)
- [x] preparing upload modal (Matt ustaxcourt/ef-cms-flexion#1586)
- [x] % complete upload modal (Matt ustaxcourt/ef-cms-flexion#1586)
- [x] all done modal (Matt ustaxcourt/ef-cms-flexion#1586)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
