### ISSUE TITLE
Petitions: QC  - changes to QC section based upon Petitions Section feedback

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6795]
During grooming, discuss with team whether to split story.

## Acceptance Criteria
Work Queues:
* Hyperlink docket numbers in queues
* Provide a success message after petitions have been assigned from Section to Individual indicating completion as expected.

QC Form
~~Alter the QC tab designs to draw attention to navigation and workflow.~~
~~* Co-locate the ratification order checkbox with the second party on the Parties tab for better context and clarity when considering and requesting ratification orders. Consider having space to free-text the party that needs to ratify~~
* Recall: show editable fields immediately to act faster
* ~Provide zoom in/out tool in the viewer's top toolbar for PDF views (confirm)~ (this is browser-specific)
* Only record a change to docket number or case caption upon hitting "Serve on IRS" [Note: this is intended to only capture one change to these items during the QC process; if another user makes multiple, successive changes, it will result in multiple docket entries]
* Update the required/optional fields on the QC screen to be consistent with new Paper-filed Petition form
* Verify that new contact fields have been implemented
* Remove the statistics stuff -- will be added in another story (likely post-MVP)
* Remove Trial Location field on QC form
* Add order to "Designate Place of Trial"

**Start a Case Form (internal)*
* Add Trial Location field, required only when a Request for Place of Trial is uploaded 

## Tasks
- [x] 1) hyperlink docket numbers in all work queues (Kris ustaxcourt/ef-cms-flexion#2893)
- [x] 2) remove all IRS Notice Year Amounts from schema, UI, persistence, seed data, tests (Kris ustaxcourt/ef-cms-flexion#2901)
- [x] 3) Prevent changes to "case caption" from recording change event to case if not 'Served to IRS' (see above) (Kris, William ustaxcourt/ef-cms-flexion#2920)
- [x] 4) Add trial location field to internal start a case form (paper filed petition) with proper validation (Rachael ustaxcourt/ef-cms-flexion#2902)
- [x] 5) Work queues - Provide a success message after petitions have been assigned from Section to Individual indicating completion as expected (Rachael ustaxcourt/ef-cms-flexion#2906)
- [x] 6) Navigate to petition QC form on success when recalling a petition (Kris ustaxcourt/ef-cms-flexion#2909)
- [x] 7) Update the required/optional fields on the QC screen to be consistent with new Paper-filed Petition form (William ustaxcourt/ef-cms-flexion#2918)
- [x] 8) Verify that new contact fields have been implemented on the QC form (William ustaxcourt/ef-cms-flexion#2903)
- [x] 9) Remove Trial Location field on QC form (Rachael ustaxcourt/ef-cms-flexion#2906)
- [x] 10) Add order to "Designate Place of Trial" on QC form (Rachael ustaxcourt/ef-cms-flexion#2906)
- [x] 11) UX review bugs
  - [x] 11a - bug 1 - assigned column too narrow (Rachael ustaxcourt/ef-cms-flexion#2934)
  - [x] ~11b - bug 2 - when case type is changed, petition is no longer appearing in batched box~ works for new cases - Natalie is retesting
  - [x] ~11c - bug 3 - when case caption is changed, petition is no longer appearing in batched box~ works for new cases - Natalie is retesting
  - [x] ~11d - bug 4 - judge user doc qc box not loading data~ holding for later
  - [x] 11e - bug 2 - update error messages on start case internal form (Rachael ustaxcourt/ef-cms-flexion#2940)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (William ustaxcourt/ef-cms-flexion#2921)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William ustaxcourt/ef-cms-flexion#2921)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
