### ISSUE TITLE
Clerk of the Court: Case gets set as "General Docket -  At Issue (Ready for Trial)"

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6796]
As the Clerk of the Court, in order for the system to know which cases are ready for trial, I need the system to automatically change the case status on a case 45 days after an answer-type document is filed to "General Docket - At Issue (Ready for Trial)"

A case is "at issue" and eligible to be scheduled for trial 45 days after any type of answer is filed by the IRS.  In order for the system to easily identify those cases that are eligible to be scheduled for trial, the system should change the case status to "General Docket - At Issue (Ready for Trial)" in each case 45 days after an answer-type document (i.e., any doc in the Answer category) is filed. See ustaxcourt/ef-cms-flexion#1594 for a list of all Case Statuses.

## Pre-Conditions
* Case exists in the system

## Acceptance Criteria
* Case status is automatically set to "General Docket -  At Issue (Ready for Trial)"  at the time that all of these conditions become present:
1) An answer-type document has been filed in the case [see note]
2) 45 days have passed after the filing of an answer-type document
3) Case is of status 'General Docket - Not At Issue'
* The subsequent filing of another answer-type document in a case does *not* start the 45-day clock over

## Notes
* For purposes of this story, an answer-type document includes any document in the "Answer" category:
Answer (A)
Answer to Amended Petition (AAPN)
Answer to Amended Petition, as Amended (ATAP)
Answer to Amendment to Amended Petition (AAAP)
Answer to Amendment to Petition (AATP)
Answer to Petition, as Amended  (APA)
Answer to Second Amended Petition  (ATSP)
Answer to Second Amendment to Petition  (AATS)
Answer to Supplement to Petition (ASUP)
Answer to Third Amended Petition (ASAP)
Answer to Third Amendment to Petition (AATT)
* Day 0 is today
* Status gets changed on day 46
* 45 calendar days, not business days

## Tasks
- [x] 1 Create lambda which runs on a schedule (William ustaxcourt/ef-cms-flexion#1870)
~- [ ] 2 Case Status is displayed in Application~
- [x] 3 Within Lambda, update cases which qualify for 'Ready for Trial' (William/Rachael  ustaxcourt/ef-cms-flexion#1883 ustaxcourt/ef-cms-flexion#1885)
- [x] 4 Update 'General Docket' to 'General Docket - Not at Issue' (see  ustaxcourt/ef-cms-flexion#1153) (William ustaxcourt/ef-cms-flexion#1887 ustaxcourt/ef-cms-flexion#1888)

## Post Demo Tasks
- [ ] 5 Update time of cron to run once per day (William ustaxcourt/ef-cms-flexion#2008)
- [ ] 6 Update offset amount and unit to '45' 'days' (William ustaxcourt/ef-cms-flexion#2008)
- [ ] 7 Remove http endpoint for lambda (William ustaxcourt/ef-cms-flexion#2008)

## Demo Steps
1. Create a new case
2. Add an answer document to case
3. Mark petition as 'Batched for IRS'
4. Run batch process as petitions clerk
5. Check case is 'General Docket - Not at Issue'
6. Wait 6 minutes (5 minutes is the current offset)
7. Wait until the next hour starts or go to temp url that runs the process 'https://efcms-dev.ustc-case-mgmt.flexion.us/v1/checkForReadyForTrialCases'
8. Check case is 'General Docket - At Issue (Ready for Trial)' 

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
