### ISSUE TITLE
Court User: "White Card" a case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6798]
As a Court User, in order to make sure that a case definitely gets scheduled for trial, I need the ability to "white card" the case.

The Court usually schedules cases for trial on a first-in, first-out (FIFO) basis.  However, there may be an instance where a particular case needs to jump to the top of the priority for some reason.  In those events, a Court User needs the ability to indicate somewhere in the case that it needs to be scheduled for trial at the next available trial date at the selected place of trial.  This will effectively force a case to be picked up during the scheduling of a trial session even though it does not fall sequentially in the order to be scheduled. The Court currently calls this practice "white-carding" a case.

## Pre-Conditions
* A case exists in the system.

## Acceptance Criteria
* A Court User can notate in a case that this case should be forced (white card) to be picked up during the scheduling of a trial session even though it does not fall sequentially in the order to be scheduled. 
* When the automatic scheduling is run, the system will pick up a "white card" case make it first to get prioritized among all of the other cases being scheduled. 
* Note: Making a case a "white card" does not force it to get picked up for a session that's already been scheduled. It would get picked up and prioritized during the next automated scheduling process. 
* Case cannot be white carded and on hold at the same time. When on hold, the case can't be white carded. 
* Once scheduled, doesn't need to be designated as a white card any longer

## Tasks
- [x] 1 entity updates, endpoint to set a case as high priority (Rachael ustaxcourt/ef-cms-flexion#3355)
- [x] 2 Add Mark High Priority button to case detail trial session card (Cody ustaxcourt/ef-cms-flexion#3357)
- [x] 3 Mark as High Priority modal (Cody ustaxcourt/ef-cms-flexion#3357)
- [x] 4 High Priority state for case detail trial card (Cody ustaxcourt/ef-cms-flexion#3358)
- [x] 5 entity updates, endpoint to remove high priority from a case (Rachael ustaxcourt/ef-cms-flexion#3355)
- [x] 6 Remove High Priority modal (Cody ustaxcourt/ef-cms-flexion#3358)
- [x] 7 Move some of the serverless-cases endpoints to serverless-case-documents so we have enough space for the new endpoints (Rachael ustaxcourt/ef-cms-flexion#3354)
- [x] 8 Update eligible trial sessions list to show/pick high priority cases first (Rachael ustaxcourt/ef-cms-flexion#3359)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
