### ISSUE TITLE
Court User: Print a report  to help Court determine trial locations

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6799]
As a Court User, in order to determine which cities the Court needs to schedule trial sessions in, I need the system to provide me with a report I can print that shows me the number of cases ready for trial in each city, what type of cases they are (small vs. regular), and information about prior sessions in that city. 

The Court schedules trial sessions in cities as needed.  This means, as there are enough cases ready for trial (100-125) for a city, the Court wants to schedule a trial session.  For cities that have a lot of cases, the Court may go to that city several times throughout the course of a year.  For cities that do not have alot of cases, the Court may only go once a year.  The Court goes to EVERY city at least once a year, even if there are less than 100-125 cases for trial.  In order to determine which cities the Court needs to go to and when, Court Users (espcially the Calendar Section) need to be able to run a report at any time that tells them the number of cases ready for trial in each of the 75 trial cities.  That number should further be broken down into regular cases versus small cases.  The report should also provide some information about prior trial sessions in each of the cities: date(s) of last three sessions and name of Judge who presided at each session.

## Pre-Conditions
* Cases are in the system with designated Places of Trial

## Acceptance Criteria
* Ability for Court Users to generate and print a report at any time which will help them determine which cities to schedule trial sessions in; and how many sessions to schedule and what type of sessions they need.
* User must indicate which future session they are trying to plan for
* Report must include the number of cases ready for trial for each trial location; what type of cases they are (small vs. regular); the dates of previous three (3) trial sessions in each trial location; whether it was a regular, small or hybrid session; and who the presiding judge was for each session. 

## Tasks
- [x] 1 Run Trial Session Planning Report modal, sequences, validation, button in header for Trial Session Planning (Cody ustaxcourt/ef-cms-flexion#3460)
- [x] 2 Endpoint (lambda, interactor, proxy, persistence methods) for generating PDF (Team mob ustaxcourt/ef-cms-flexion#3471 ustaxcourt/ef-cms-flexion#3475)
- [x] 3 Route, view for Trial Session Planning Report, submit sequence from the modal to call the endpoint and change the route (Team mob ustaxcourt/ef-cms-flexion#3471)
- [x] 4 Create template for PDF (Matt ustaxcourt/ef-cms-flexion#3467)
- [x] 5 Fix footer issue on generated PDF - cutting off last row in the table (Rachael ustaxcourt/ef-cms-flexion#3477)
- [x] 6 Show multiple judge names on the past trial sessions if there was more than one session (Rachael, Cody ustaxcourt/ef-cms-flexion#3482)
- [x] 7 Filter out special and motion/hearing sessions from trial session list (Rachael, Cody ustaxcourt/ef-cms-flexion#3482)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Cody)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Rachael)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
