### ISSUE TITLE
Court User: Enter trial session details into the system

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6800]
As a Court User, in order to start scheduling cases for trial, I need to enter trial session details into the system.

Once the Court prints the report (#1190), it uses an off-line process to decide which cities in should hold trial sessions in and when.  Once the Court has decided on a tentative schedule of trial sessions to be added to the system, a Court User needs to be able to "create" the trial session by entering trial session details into the system.  That information includes: the date range of the trial session (usually 1 week), trial city, session type (Small, Regular, Hybrid, Special), Name of Judge, Max number of cases for the session. 

## Acceptance Criteria
* Court User needs to the ability to enter trial session details: 
         - date range of the trial session (usually 1 week), REQUIRED
         - trial city, REQUIRED
         - session type (Small, Regular, Hybrid, Special), REQUIRED
         - Name of Judge, 
         - Max number of cases for the session REQUIRED
         - Term (Spring. Fall, Winter). REQUIRED
         - Courthouse Location
         - Time
         - Trial Clerk
         - Court Reporter
         - IRS Calendar Administrator
         - Free text for any other Trial Session Notes
* Session types should include:
         - Regular -- trial session includes only Regular cases
         - Small -- trial session includes only Small cases
         - Hybrid -- trial session includes a combination and Regular and Small cases
        - Special -- a trial session that is set by a Judge to hear 1 or more cases that cannot be heard during a regular trial session; can happen anytime, anywhere
         - Motion/Hearing -- a session where a Judge will hold a hearing on a motion or small issue (something other than an entire case)
* User can visually see when two swing sessions are scheduled together.
      - Note: A Swing session = a trial session that is shorter than a week and often times combined with another shorter session.
* ~~Trial session details can be edited after it's been put into the system~~ (making another story)
* View a list of sessions that have been scheduled, including dates and locations [See Note below]

## Notes
* From a design perspective, I see this as a three-level drill down:
(1) ustaxcourt/ef-cms#6800 creates the list of all trial sessions 
* Should be able to filter between Upcoming, Closed, All
* Judges should also have the ability to view/filter only their trial sessions (POST-MVP?)
* List should include the following for each trial session -- Session Location | Type | Date | Time | Judge
* Ability to sort on any column (Session Location | Type | Date | Time | Judge)
* City name is hyperlink into the specifc trial session -- When you click into a specific trial session, you get a list of all the cases on that trial session
(2) ustaxcourt/ef-cms#6803 creates the list of all cases on a trial session
* Should be able to filter between Open, Closed, All
* List should include the following information for each case -- Docket No. | Case Caption | Petitioner's Counsel Respondent's Counsel | Disposition
* Ability to sort on any column (Docket No. | Case Caption | Petitioner's Counsel | Respondent's Counsel | Disposition)
* List also provides information about trial session -- Courthouse Location, Judge, Time, Trial Clerk (and anything else we want to add)
* List should be printable
* Docket number for each case is hyperlink -- When you click into a case on a trial session list (by clicking on hyperlink on Docket number), it should take you into the case detail page of that case
(3) Case Detail Page (already exists)

## Tasks
- [x] 1 create trial session entity with validation rules (Rachael ustaxcourt/ef-cms-flexion#1933)
- [x] 2 create endpoint, interactor, and persistence method to submit a trial session (William ustaxcourt/ef-cms-flexion#1951)
- [x] 3 create view and route for trial session data entry form (Rachael, Kris ustaxcourt/ef-cms-flexion#1955)
  ~3a create users in chambers and trial clerk sections to fill Judge/Trial Clerk dropdowns on form~ - these are going to be hardcoded for this story
  - [x] note: trial location dropdown should populate with all possible trial locations regardless of the session type selected
- [x] 4 create sequences and actions to submit a trial session (William ustaxcourt/ef-cms-flexion#1951)
- [x] 5 integrate validation into UI for trial session form (Rachael, Kris ustaxcourt/ef-cms-flexion#1960)
- [x] 6 create endpoint, interactor, and persistence method to retrieve list of trial sessions (Rachael ustaxcourt/ef-cms-flexion#1935)
- [x] 7 create view and route for trial session list/table (Kris, Rachael ustaxcourt/ef-cms-flexion#1950)
  - [x] note: create tab container for Upcoming/Closed/All, but Upcoming will be the only tab for this story - others will be added in later stories
  - [x] also note: filtering will be done as part of a separate story
- [x] 8 create sequences and actions to retrieve list of trial sessions (Rachael ustaxcourt/ef-cms-flexion#1940)
- [x] 9 add global navigation header for Trial Sessions (all internal users will have access to this) (Rachael ustaxcourt/ef-cms-flexion#1934)
- [x] 10 add trial session seed data (#1935, ustaxcourt/ef-cms-flexion#1950)
- [x] 11 create sequences and actions to validate a trial session (William ustaxcourt/ef-cms-flexion#1951)
- [x] 12 Look into trial session data modeling. pk should be uuid (William ustaxcourt/ef-cms-flexion#1965)
- [x] 13 remove defaults from form (#1970)
- [x] 14 remove Term field from form; calculate from entered startDate (#1970)
- [x] 15 store term year either separately or with term field (#1974)
- [x] 16 fill swing session dropdown with other sessions in selected term (#1970)
- [x] 17 set both sessions to swingSession=true when linking a swing session to another session (Rachael ustaxcourt/ef-cms-flexion#1981)
- [x] 18 validation on Time field (XX:XX am/pm) - and store this as a string (needs to be added to entity) (#1974)
- [x] 19 secondary sort on trial sessions table alphabetically by trialLocation (#1974)
- [x] 20 update form cancel modal sequence to redirect to the trial session table (William ustaxcourt/ef-cms-flexion#1992)
- [x] 21 fix trial session table sorting (date storage issues) (Kris, Rachael ustaxcourt/ef-cms-flexion#1991)
- [x] 22 add helper text to time field "Enter time as hour : minutes (e.g. 10:30 am)." (Kris, Rachael ustaxcourt/ef-cms-flexion#1991)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
  - [ ] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael ustaxcourt/ef-cms-flexion#1984)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version (Rachael ustaxcourt/ef-cms-flexion#1984)
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (William ustaxcourt/ef-cms-flexion#1985)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised (Rachael ustaxcourt/ef-cms-flexion#1984)
