### ISSUE TITLE
Calendar Clerk: Run automated scheduling of trial sessions

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6801]
As a Calendar Clerk, in order to schedule specific cases for trial on a trial session, I need to run an automated scheduling of the trial sessions.

Once all of the trial sessions (dates and cities) have been agreed upon, the Court needs to actually populate each trial session with cases ready for trial.  The Calendar Section is in charge of doing this function.  The trial session is actually populated with cases 5 months before the trial session is scheduled to commence by the Calendar Clerk.  When a trial session is ready to be populated with cases, the Calendar Section should be able to run an automated scheduling program that will link specific cases with a trial session.  This automated scheduling program should take several things into account: (1) Only cases with the status of "General Docket - At Issue (Ready for Trial)" and that designated place of trial are eligible to be scheduled on a particular trial session; (2) Only regular cases get scheduled to regular session; (3) only small cases get scheduled to small sessions; (4) both regular and small cases can get scheduled to hybrid sessions; (5) "L" cases, and "P" cases get prioritized for scheduling over any other type of case regardless of when they were filed vis-a-vis other cases; (6) cases are otherwised scheduling on a FIFO basis, up to the maximum number of cases allowed for a specific trial session (this was defined when the trial session was created in the system).

## Pre-Conditions
* Cases are in the system with various case statuses, including "General Docket - At Issue (Ready for Trial)"
* Cases have a designated place of trial
* A trial session has been created

## Acceptance Criteria
* Calendar section can initiate the generation of a trial session calendar at any time
* For each trial session, only cases with the status of "General Docket - At Issue (Ready for Trial)" and a requested trial location for that designated place of trial are eligible to be scheduled on that particular trial session, up to the max number that has been set for the trial session when it was entered.
* Only small cases get scheduled to the trial session that's has a small type
* Only regular cases get scheduled to the trial session that's has a regular type
* Both small and regular cases get scheduled to the trial session that's has a hybrid type
* Cases are scheduled sequentially based up on the date and time the petition was filed (FIFO)
* L and P case types get prioritized before any other type of case; and then sequentially based upon the date petition was filed (FIFO)
* Case status is automatically set to "Calendared for Trial" once a case is scheduled to a specific trial session
* Trial details display on the case detail page (case info tab)

## Tasks
- [x] 0 Mechanism for setting cases 'ready for trial' manually (Rachael ustaxcourt/ef-cms-flexion#2035)
- [x] 1 Trial Session Details Page
  - [x] 1a route, sequence, actions for trial session detail page (Kris ustaxcourt/ef-cms-flexion#2033)
  - [x] 1b Set Calendar Button (Kris ustaxcourt/ef-cms-flexion#2047)
  - [x] 1c Confirm Modal for Set Calendar (Kris ustaxcourt/ef-cms-flexion#2047)
  - [x] 1d Eligible Cases View (Dependent on 2) (Rachael ustaxcourt/ef-cms-flexion#2046)
  - [x] 1e Link to the detail page from the trial session list (Rachael ustaxcourt/ef-cms-flexion#2045)
  - [x] 1f Trial session detail cards, finish building out getTrialSessionDetails endpoint (Rachael ustaxcourt/ef-cms-flexion#2051)
  - [x] 1g Update header on trial session detail page with trial location, term tag, and start date (Rachael ustaxcourt/ef-cms-flexion#2053)
  - [x] 1h Computed for formatting trial session details (Rachael ustaxcourt/ef-cms-flexion#2055)
  - [x] 1i Call the setCalendar sequence as the confirm on the modal and hide the eligible case list when session is calendared (Rachael ustaxcourt/ef-cms-flexion#2056)
  - [x] 1j Show associated swing session on the trial session details view (Rachael ustaxcourt/ef-cms-flexion#2063)
  - [x] 1k Hide eligible cases table and set calendar button on Motion/Hearing and Special sessions (Rachael ustaxcourt/ef-cms-flexion#2063)
- [x] 2 Update ustaxcourt/ef-cms#6796 Lambda process to create mapping records for case to be used for sorting (William ustaxcourt/ef-cms-flexion#2018)
  - [x] 2a Get Eligible Cases http Endpoint / Use Case (William ustaxcourt/ef-cms-flexion#2018)
  - [x] ~2b For 'Special' or 'Motion/Hearing' Trial Sessions what should happen?~
  - [x] 2c update sort key when case is updated (Rachael ustaxcourt/ef-cms-flexion#2036)
  - [x] 2d Eligible Cases Endpoint should have limit + 50 extra returned (William ustaxcourt/ef-cms-flexion#2066)
- [x] 3 Set Calendar Sequence (William ustaxcourt/ef-cms-flexion#2034)
  - [x] 3a remove mapping records for cases (William ustaxcourt/ef-cms-flexion#2034)
  - [x] 3b update calendared cases with trial details and set status to "Calendared" (See: [USTC Case Statuses](https://docs.google.com/document/d/1qhxASEKuzcPp99rTfCVkYbi6hVKS1pPPIgn5MvEWFPM/edit)) (William ustaxcourt/ef-cms-flexion#2034)
  - [x] 3c update trail session status and case list (William ustaxcourt/ef-cms-flexion#2034)
  - [x] 3d verify trail details display on case details page for calendared cases (William ustaxcourt/ef-cms-flexion#2034)
  - [x] ~3e "Not selected" defaults for trial information on case detail page~
  - [x] 3f make sure that concatenated date is provided as trial date to case details (William ustaxcourt/ef-cms-flexion#2050)
  - [x] 3g Case Journey Test (William ustaxcourt/ef-cms-flexion#2058)
- [x] 4 Test Scenarios
    - [x] 4a Scenario 1 - https://github.com/flexion/ef-cms/issues/1192#issuecomment-502137868 (William ustaxcourt/ef-cms-flexion#2068)
    - [x] 4b Scenario 2 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (William, Rachael ustaxcourt/ef-cms-flexion#2070)
    - [x] 4c Scenario 3 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (William, Rachael ustaxcourt/ef-cms-flexion#2071)
    - [x] 4d Scenario 4 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528  (Rachael ustaxcourt/ef-cms-flexion#2073)
    - [x] 4e Scenario 5 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael ustaxcourt/ef-cms-flexion#2075)
    - [x] 4f Scenario 6 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael ustaxcourt/ef-cms-flexion#2077)
    - [x] 4g Scenario 7 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael ustaxcourt/ef-cms-flexion#2078)
    - [x] 4h Scenario 8 https://github.com/flexion/ef-cms/issues/1192#issuecomment-502203528 (Rachael ustaxcourt/ef-cms-flexion#2080)
- [x] 5 fixes
  - [x] 5a prioritize L cases over P cases, regardless of date (scenario 6) (Rachael, William ustaxcourt/ef-cms-flexion#2082)
  - [x] 5b set isCalendared to true for Motion/Hearing and Special sessions (Rachael, William ustaxcourt/ef-cms-flexion#2082)

## Post Demo Tasks
- [ ] Eligible Cases Use Case should return limit + 50 (Currently 2) (William ustaxcourt/ef-cms-flexion#2239)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael ustaxcourt/ef-cms-flexion#2090 ustaxcourt/ef-cms-flexion#2086)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
