### ISSUE TITLE
Notice of Trial Issued

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6802]
As the Court, in order to notify the parties that their case has been set for trial, a Notice of Trial is issued about 5 months in advance of the start date of the trial session.  

## Acceptance Criteria
* When a calendar is set/automatically scheduled, all cases on that session should be issued a "Notice of Trial" (format in comments)
* If a case is manually added to a trial session *before* it is set/automatically scheduled, the case should not be issued a issued a "Notice of Trial" until that automatic scheduling
* If a case is manually added to a trial session *after* it is set/automatically scheduled, that case should be issued a "Notice of Trial" at the time the case is added to the trial session
* User should be able to easily see the sessions for which notices have already been issued (UX feedback; 9/2019 visit)
* When the Notice of Trial is issued, it is added to the Docket Record as a separate entry and served on the parties:
   * served date added to document; 
   * docket record displays served date and parties; 
   * parties receiving electronic service get email; 
   * parties receiving paper service get paper.
* Code for Docket Record = NDT
* Full address and Judge are required fields before a case is auto-scheduled (calendared)

## Notes
* This story does not include the issuance of a "Standing Pre-Trial Order" (for regular cases) or a "Standing Pre-Trial Notice" (for small cases) -- that is handled in ustaxcourt/ef-cms#7003
*required fields to set trial Address 1 city state and zip
- 150 cases in a trial

## Tasks
_Tasked in trello_

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (William)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (All Screens Internal)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Joseph)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Joseph)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
