### ISSUE TITLE
Court User: View list of cases on a trial session

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6803]
As a Court User, in order to easily keep track of the cases on a specific trial session, I need the ability to view a list of cases on the trial session.

Once a trial session is populated with cases, a Judge or other Court User who needs to easily keep track of what is happening with those cases, needs a list of all the cases on the trial session.  That list should include the following information for each case -- Docket No. | Case Caption | Petitioner's Counsel | Respondent's Counsel | Disposition.  The list should also display any trial session details entered -- Courthouse Location, Judge, Time, Trial Clerk, etc.  Court Users should be able to sort/filter between Open Cases, Closed Cases, and All, and the list must be printable.

## Pre-Conditions
* Calendar Section has scheduled cases to a trial session.

## Acceptance Criteria
* Ability to view a list of all cases on a specific trial session and then link to each of the cases
* The list should include the following information for each case -- Docket No. | Case Caption | Petitioner's Counsel | Respondent's Counsel | Disposition
* Court User should be able to sort/filter between Open Cases, Closed Cases, and All
* Header above list should display any trial session details entered
* Header & List must be printable (not an optimized print, just able to print; optimized view is in ustaxcourt/ef-cms-flexion#1976)
* Display list sequentially by docket number

## Notes
* No other sorting of filtering needed at this time (other than what's above)
* Blank state for case lists for session types Motions/Hearing or Special will not be handled in this case 
* We won't actually have any closed cases, so the testing for that will have to be focused on just not showing any of the "open" cases in that tab.

## Tasks
- [x] 1 endpoint, lambda, proxy, interactor, and persistence method to get cases associated with a trial session (Rachael ustaxcourt/ef-cms-flexion#2099)
- [x] 2 sequences/actions to get cases associated with the session (William ustaxcourt/ef-cms-flexion#2100)
- [x] 3 associated cases tabs and table view (Kris ustaxcourt/ef-cms-flexion#2106)
- [x] 4 add print link at the top of session detail view (Rachael ustaxcourt/ef-cms-flexion#2103)
- [x] 5 Verify that endpoint returns cases in caseOrder (William ustaxcourt/ef-cms-flexion#2108)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
