### ISSUE TITLE
Court User: Manually add a case after a trial session has been scheduled

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6804]
As a Court User, in order to add a case to a trial session after the trial session has already been populated with cases, I need the ability to manually add a case to a trial session.

After a trial session has been created and cases have been scheduled to that trial session, there may be a need to add one or two cases to the session.  If a case needs to be added to a trial session after the session is scheduled, it will have to be manually added to the session.  This manual addition of more cases does *not* affect any of the cases that were already scheduled to the trial session. A case manually scheduled for a trial session that is already at its max limit will not bump out another case. (e.g. If 100 cases was the limit that was set when the session was created and that session had 100 cases scheduled, the manually added case would allow for 101 cases)

## Pre-Conditions
* Trial session has already been created and cases are scheduled to the trial session

## Acceptance Criteria
* At any time after a trial session has been scheduled (up until the date of the trial session), a court user can manually add a case to a trial session
* Once a case is manually scheduled to a trial session, that case is associated with the trial session and should show up on the list of cases Active and All on the trial session
* Manual scheduling of a case does not affect any of the cases that were automatically scheduled for the session.
* Case can be scheduled for a session that is already at its max limit and other cases don't get bumped out. (e.g. If 100 cases was the limit that was set when the session was created and that session had 100 cases scheduled, the manually added case would allow for 101 cases)
* Once a case is automatically added to a trial session, the case status should change to "Calendared" 
* When a case is manually added, the judge and court need an indicator so that they can see what items were manually added to the trial session
* When a case is manually added to a trial session, it should show up in the trial session list sequentially based on docket number
* Replace wording on "Closed" tab with "Inactive"

## Notes
* Jessica's design thoughts on this: Docket Clerk would change the trial information on the Case Info tab to match a trial session and that would associate the case to that trial session and the case would now show up on the trial session list.
* No need to bubble manually added item to the top of the list

## Tasks
- [x] 1 Create endpoint for adding case to a trial session (interactor, lambda, proxy, serverless) (Cody ustaxcourt/ef-cms-flexion#3336)
- [x] 2 Add to Trial Session modal, add to trial button on trial info card (Rachael ustaxcourt/ef-cms-flexion#3338)
  - [x] 2a confirm sequence to call addCaseToTrialSession endpoint (Rachael ustaxcourt/ef-cms-flexion#3341)
  - [x] 2b modal validation (Rachael ustaxcourt/ef-cms-flexion#3341)
- [x] 3 Add icon to trial session tables to indicate the case was manually added (Cody ustaxcourt/ef-cms-flexion#3337)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
