### ISSUE TITLE
Court User: Manually remove a case from a trial session

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6805]
As a Court User, in order to appropriately account for cases that are closed or continued, I need the ability to remove a case from a trial session.

Once a case is scheduled for trial on a trial session, there may be a few reasons that case needs to be removed from the trial session.  The first reason is that the case settled.  In this instance, the case status would be changed to "Closed" and the case would automatically fall off/be removed from the trial session.  The second reason is if a case is continued.  If the parties are not ready to go to trial on the date the Court scheduled, they may ask the Court to "continue" the case.  If granted, this involves removing the case from the trial session and putting the case back into the general pool of cases ready to be scheduled for trial the next time the Court goes to that trial city, or moving the case to another trail session that has already been scheduled.

## Pre-Conditions
* A case is scheduled for trial on a trial session.

## Acceptance Criteria
* Court User should have the ability to manually remove a case from a trial session
*Once removed the status of the case needs to be set back to "General Docket - Ready for Trial" [Note: The case would get scheduled during the next automated scheduling or if it were manually scheduled]
* Even though a case gets removed, nothing is automatically scheduled to replace it [Note: Once a session is automatically scheduled, everything is manually added or removed after that]
* Court user needs the ability to type in the reason the case was removed from the trial session
* The reason the case was removed displays under disposition with the date. 
* Court user needs the ability to see all cases (both active and removed), see all active cases and see all cases that were removed

CREATE A NEW STORY: (#3351)
* Case is automatically removed from a trial session when it is closed. 
* Once a case is removed from a trial session, it shows up under "closed cases" for that trial session
* The reason the case was removed displays under disposition with the date. 
* Court user needs the ability to see all cases that were originally on trial calendar, see all active cases and see all cases that were removed

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* A case will automatically get removed from a trial session when it is closed. However, that functionality is being handled in the stip decision story (#114)

## Tasks
- [x] 1 Case detail layout updates (Rachael ustaxcourt/ef-cms-flexion#3327)
  - [x] move Requested Place of Trial to petition details card (Rachael ustaxcourt/ef-cms-flexion#3327)
  - [x] update trial card (Rachael ustaxcourt/ef-cms-flexion#3327)
- [x] 2 Create Remove from Trial modal, sequence for opening (Cody ustaxcourt/ef-cms-flexion#3326)
  - [x] sequence for opening
  - [x] validation
  - [x] submit sequence
- [x] 3 Endpoint for removing case from trial (interactor, lambda, proxy, serverless) (Rachael ustaxcourt/ef-cms-flexion#3324)
- [x] 4 Add removeFromTrial method to case entity and disposition, removedFromTrial, removedFromTrialDate to trial session case order (Rachael ustaxcourt/ef-cms-flexion#3324)
- [x] 5 Trial session tables layout updates (Rachael, Cody ustaxcourt/ef-cms-flexion#3329)
- [x] 6 show spinners on modal submit for slow networks

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
