### ISSUE TITLE
Practitioner: Filing a document for a client

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6806]
As a Practitioner, in order to file documents on behalf of my client, I need the ability to electronically file all of the same documents that a Petitioner can file, as well as some related to my representation.

A Practitioner stands in the place of a Petitioner.  As a result, a Practitioner needs the ability to file any document that a Petitioner can file.  In addition, a Practitioner needs the ability to file additional documents related to representation: Entry of Appearance, Substitution of Counsel, Motion to Withdrawal as Counsel.

## Pre-Conditions
* A case exists in the system.

## Acceptance Criteria
* A Practitioner can file all of the same documents (#269) and provide the same requested information for each document as a Petitioner.
* When filing by a Practitioner, the Practitioner has the ability to select who is filing, including themselves

## Tasks
- [x] 1. Change view of Parties Filing section based on user's role (Rachael ustaxcourt/ef-cms-flexion#1471)
  - [x] 1a. Don't select a default party for practitioners (Rachael ustaxcourt/ef-cms-flexion#1473)
- [x] 2. Update validation to allow partyPractitioner (William ustaxcourt/ef-cms-flexion#1470)
- [x] 3. Add "Counsel" to docket record entry Filed By string (Rachael ustaxcourt/ef-cms-flexion#1474)
- [x] 4. UX review notes
  - [x] 4a. Nonstandard document types are showing up in previous document dropdown and docket record document title without fully concatenated document title (Rachael ustaxcourt/ef-cms-flexion#1487)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
