### ISSUE TITLE
Judge: Manage work from Dashboard

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6811]
As a Judge, in order to manage my workload, I need to easily access everything from a central location.

A Judge will need to access and manage the trial sessions he/she has assigned to them.  They will also need to see any pending messages that they have that need attention.  It would be preferable for the Judge to be able to easily access all of this information from a central point.

## Pre-Conditions:
•	A Judge is a registered user in the system

## Acceptance Criteria:
•	Each Judge needs to easily see and access all of the work requiring his/her attention from a centralized point.

## Tasks
- [x] 1 create 'judge' role, seed data with role, cognito users with 'judge' role (Kris, Rachael ustaxcourt/ef-cms-flexion#2641)
  - [x] 1a add actual judges to seed data (Kris, Rachael ustaxcourt/ef-cms-flexion#2657)
  - [x] 1b pull in real judge users in messaging functionality (Kris, Rachael ustaxcourt/ef-cms-flexion#2657)
  - [x] 1c pull in real judge users in trial session creation form (Rachael, ustaxcourt/ef-cms-flexion#2658 )
  - [x] 1d Fix judge names on dev (they are currently all `Test judge`) (Rachael ustaxcourt/ef-cms-flexion#2662)
  - [x] 1e Refactor `setup-cognito-users.sh` (Rachael ustaxcourt/ef-cms-flexion#2678)
- [x] 2 Create Judge's Dashboard (Kris, Rachael ustaxcourt/ef-cms-flexion#2641)
  - [x] 2a Create judge dashboard sequence & actions (Kris, Rachael, ustaxcourt/ef-cms-flexion#2661)
  - [x] 2b Create "Recent Messages" table (Kris, Rachael ustaxcourt/ef-cms-flexion#2661)
  - [x] 2c Create Upcoming/Recent Trial Sessions list (dashboard view) (Kris, Rachael, ustaxcourt/ef-cms-flexion#2661)
  - [x] 2d Create messages in seed data for user `judgeArmen` (Rachael ustaxcourt/ef-cms-flexion#2663)
- [x] 3 Create Upcoming Sessions Table (William ustaxcourt/ef-cms-flexion#2649 ustaxcourt/ef-cms-flexion#2653 ustaxcourt/ef-cms-flexion#2655)
   - [x] 3a add filtering features to sessions table
   - [x] 3b trial sessions helpers to apply filters
- [x] 4 write computed to filter upcoming OR recent sessions (five each) (William ustaxcourt/ef-cms-flexion#2671)
- [x] 5 create seed data to ensure we have some sessions both in the past and in the future to be displayed in the session summary lists (Kris ustaxcourt/ef-cms-flexion#2667)
- [x] 6 Send judges messages in a few integration tests to further build out data for testing (Rachael ustaxcourt/ef-cms-flexion#2677)
- [x] 7 Link to the full message inbox from the `View All Messages` link on the dashboard (Kris ustaxcourt/ef-cms-flexion#2667)
- [x] 8 Filter recent messages to show only the most recent 5 messages (William ustaxcourt/ef-cms-flexion#2675)
- [x] 9 App header/routing updates (Kris, William ustaxcourt/ef-cms-flexion#2679)
  - [x] 9a Refactor messages route to separate dashboards from messages (Kris, William ustaxcourt/ef-cms-flexion#2679)
  - [x] 9b Add home button to main app header for judges only (Kris, William ustaxcourt/ef-cms-flexion#2679)
  - [x] 9c Update `headerHelper.js` to work with new routing updates and verify that the correct tab is selected on the judge's dashboard (Kris, William ustaxcourt/ef-cms-flexion#2679)
- [x] 10 remove the underline from the home icon (William ustaxcourt/ef-cms-flexion#2682)
- [x] 11 home messages don't show up when going from document qc to messages (William ustaxcourt/ef-cms-flexion#2683)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
