### ISSUE TITLE
Judge/Trial Clerk: Case list-level notes

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6813]
As a Judge, in order to keep record of specific things related to a case, I need the ability to take notes at a case-level.

Before a Judge leaves DC to travel to a trial session, they may hold conference calls with the parties or have other notes that they want to make related to a specific case. The Judge needs these notes to be viewable to him/her and to whomever else he/she gives permission to.  These notes should display on the Judge's trial session list and be associated with the case to which they relate.

## Pre-Conditions
* A case has been calendared for trial on a trial session.
* A judge has been assigned to a trial session

## Acceptance Criteria
* Judge assigned to a trial session can take notes on the their working copy of the trial session (#1272) at the case level and the notes would also appear on the case detail page
* Judge can take notes at the case detail page and if they are the judge assigned to the trial session, the notes would also appear on the working copy 
* Any judge can take notes on any case detail page at any time but only ever see their own notes on the case detail page

## Notes
* Permissions are not part of this story. Just judge can see it on their working copy. They will be addressed in ustaxcourt/ef-cms#6851
* Consider WYSIWYG editor from order generation? 

## Tasks
- [x] 1 add Notes to caseMetadata on TrialSessionWorkingCopy entity (Rachael ustaxcourt/ef-cms-flexion#2774)
  - [x] 1a entity validation and tests (Rachael ustaxcourt/ef-cms-flexion#2774)
- [x] 2 Create modal for adding/editing notes (William ustaxcourt/ef-cms-flexion#2795)
  - [x] 2a sequences and actions for opening modal, handling change events (William ustaxcourt/ef-cms-flexion#2795)
  - [x] 2b add validation for empty note (William ustaxcourt/ef-cms-flexion#2795)
- [x] 3 Create modal for deleting notes (William ustaxcourt/ef-cms-flexion#2795)
  - [x] 3a actions, sequences to delete note (William ustaxcourt/ef-cms-flexion#2795)
- [x] 4 Table updates: "has note" and "does not have note" status (Kris, Rachael ustaxcourt/ef-cms-flexion#2796)
  - [x] 4a actions and sequences connected to buttons for add note, delete note, edit note (William ustaxcourt/ef-cms-flexion#2795)
- [x] 5 update Case Detail component with Judges Notes and add, edit, delete (Kris, ustaxcourt/ef-cms-flexion#2800 )
  - [x] 5a actions, sequences connected to modal as in 2, 3 (William ustaxcourt/ef-cms-flexion#2795)
- [x] 6 Action to retrieve notes from current case (Rachael ustaxcourt/ef-cms-flexion#2793)
  - [x] 6a add to sequence leading to Case Details component (Rachael ustaxcourt/ef-cms-flexion#2793)
 - [x] 7 Create seed data for Trial Session Working Copy for `judgeArmen` with at least one case in order to show things in the working copy table (Rachael ustaxcourt/ef-cms-flexion#2801)
- [x] 8 Update to allow judges that are not associated with a trial session to create notes for cases on that trial session 
  - [x] 8a persistence methods for create, get, update, delete case notes (Rachael ustaxcourt/ef-cms-flexion#2832)
  - [x] 8b endpoints, lambdas, interactors, proxies for case notes (Rachael ustaxcourt/ef-cms-flexion#2834)
  - [x] 8c actions/sequences and frontend changes for case notes (William ustaxcourt/ef-cms-flexion#2834)
  - [x] 8d update TrialSessionWorkingCopy and CaseNote entities (Rachael ustaxcourt/ef-cms-flexion#2834)
  - [x] 8e create SessionNote entity with action, sequences, and interactor for validating session notes (Rachael ustaxcourt/ef-cms-flexion#2834)

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William ustaxcourt/ef-cms-flexion#2807)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
