### ISSUE TITLE
Judge: Session-related logistical notes

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6814]
As a Judge, in order to capture information related to the trial session (and not a specific case), I need the ability to add session-related logistical notes to the trial session list (the working copy of the trail session will be worked out in ustaxcourt/ef-cms#6811).

In addition to taking notes on specific cases, a Judge may also need to include logistical notes at the session level (i.e. travel plans, hotel, note about the trial location - anything you don't want to forget).  These notes should only be viewable to the Judge.

## Pre-Conditions
* Trial session has been created and assigned to a Judge.

## Acceptance Criteria
* Judge has ability to take logistical notes at the session level (i.e. travel plans, hotel, note about the trial location - anything you don't want to forget)

## Notes
* Permissions is not part of this story.  It will be handled in ustaxcourt/ef-cms#6851

## Tasks
- [x] 1 Session Notes Card (Rachael ustaxcourt/ef-cms-flexion#2822)
  - [x] 1a Connect Sequences to Buttons (William ustaxcourt/ef-cms-flexion#2826)
- [x] 2 Session Notes Modal (William ustaxcourt/ef-cms-flexion#2826)
  - [x] 2a Sequences for opening modal / updating sessions working copy. (William ustaxcourt/ef-cms-flexion#2826)
- [x] 3 add session notes to working copy entity (Rachael ustaxcourt/ef-cms-flexion#2815)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
