### ISSUE TITLE
Judge: Batch download cases/document

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6815]
As a Judge, in order to have access to electronic files in a case when I lack internet access, I need the ability to batch download cases/documents within a case to my laptop.

As a Judge for the Tax Court, I often travel to trial locations throughout the United States to officiate cases that have been scheduled to a trial session. When I travel, it can be very cumbersome for my trial clerk and I to transport paper case documents. Communications and organization can also be a challenge for me while I'm traveling due to a lack access to court systems and sometimes the Internet.

Due to concerns about internet connectivity while I am in transit OR while I am at a trial session, on the Thursday or Friday before my session, I need to batch download the documents for all cases remaining on the trial session on to my laptop. They are saved/grouped by case and display in the order they are listed in system (docket record). This allows me to review the cases while in flight or in an area of the airport where I do not get cellular coverage.

## Pre-Conditions
* Case is scheduled for trial on a trial session

## Acceptance Criteria
* Judge should be able to access all documents on all cases on a trial session without internet connectivity
* For the cases remaining on the trial session, the Judge should be able to perform a bulk/batch download
* Files display in docket number order; naming convention is the docket number, case name (everything before , Petitioners)
  * Within individual case folders, we should have a printable docket record and then the individual case records
* Individual case records should be saved in a convention that makes them appear in the same order as they are on the docket record.
* Users should be able to tell which document is related to which docket entry number
* Document naming convention (e.g. 2019-01-22_0001_Petition) (0001 is the docket record index number, use the fully concatenated document title)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Users don't need ability to do on mobile phone.
* Possible folder structure: September 9, 2019 - Los Angeles.zip
  * 101-19, John Smith
    * printable docket record
    * 2019-01-22_0001_Petition
    * 2019-01-23_0002_Another Document
    * 2019-01-23_0003_Some Other Document
  * 102-19, Jane Something & James Something
    * printable docket record
    * 2019-01-22_0001_Petition
    * 2019-01-23_0002_Another Document
    * 2019-01-23_0003_Some Other Document

## Tasks
- [x] 1 Download an Empty zip of Trial Session `September_9_2019-Los_Angeles_California.zip`(William ustaxcourt/ef-cms-flexion#2887)
- [x] 2 Create Zip that includes docket record pdf (William ustaxcourt/ef-cms-flexion#2890)
- [x] 3 Create Zip that includes trial session documents (William ustaxcourt/ef-cms-flexion#2890)
- [x] 4 Refactor Printable docket record to generate the pdfs completely on the server side (Matt ustaxcourt/ef-cms-flexion#2912)
- [x] 5 Refactor to return zip directly without uploading to S3 (William, Kris ustaxcourt/ef-cms-flexion#2972)
- [x] 6 Stress test lambda limits 
  * https://dashbird.io/blog/exploring-lambda-limitations/
  * https://docs.aws.amazon.com/lambda/latest/dg/limits.html
  * https://www.reddit.com/r/aws/comments/8kqy0t/how_to_handle_zipping_files_in_s3/
- [x] 7 Update Naming of items in batch download (William, Kris ustaxcourt/ef-cms-flexion#2937 ustaxcourt/ef-cms-flexion#2964)
- [x] 8 Add Loading Overlay to stop multiple submissions (Themis ustaxcourt/ef-cms-flexion#3064)
- [x] 9 Update process to GET request (William ustaxcourt/ef-cms-flexion#2984)
- [x] 10 Convert endpoint from lambda proxy to lambda (Team mob ustaxcourt/ef-cms-flexion#3055)
- [x] 11 Handle API gateway timeout on large downloads (moving to websockets)
  - https://joarleymoraes.com/serverless-long-running-http-requests/
  - https://aws.amazon.com/blogs/compute/from-poll-to-push-transform-apis-using-amazon-api-gateway-rest-apis-and-websockets/
- [x] 12 Implement websockets for message capability (Cody/Themis [poc_web_sockets](https://github.com/flexion/ef-cms/compare/develop...poc_web_sockets))
  - [x] 12a Convert lambda to run async
  - [x] 12b add ttl on dynamo record (William)
  - [x] 12c figure out proxy to work with websockets
- [x] 13 deploy into dev env
- [x] 14 Stress test lambda limits part 2
  * https://dashbird.io/blog/exploring-lambda-limitations/
  * https://docs.aws.amazon.com/lambda/latest/dg/limits.html
  * https://www.reddit.com/r/aws/comments/8kqy0t/how_to_handle_zipping_files_in_s3/
- [x] 15 update exp env
- [x] 16 add socket gateway to applicationContext to isolate socket communication (William ustaxcourt/ef-cms-flexion#3118)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
~~- [ ] Story has been tested on a mobile device (for external users only)~~

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
