### ISSUE TITLE
Petitions Clerk: New Flow for Paper Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6817]
As a Petitions Clerk, so that I may have record of the Petitioner's original petition data, I need the ability to enter data for a paper-filing petitioner as it appears on the paper petitions and then correct it in the system.
 Possibly combine with ustaxcourt/ef-cms#6856

## Pre-Conditions
* Petitioner submitted a paper Petition 

## Acceptance Criteria
* Petitions Clerk can enter and save original paper petition data into the system before the QC process.
* Original paper petition data is retained for record (in audit logs, which is already being done)
* New Petition appears in the Petitions Section Document QC after all metadata is entered AND petition has been scanned (#1895)
* Any petitions Clerk can change the entered data as part of the QC process

## Tasks
- [x] 1 Move Create Case button (Kris ustaxcourt/ef-cms-flexion#2451)
- [x] 2 Update form on create case page (Rachael ustaxcourt/ef-cms-flexion#2453)
- [x] 3 Update validation for creating case from paper (William ustaxcourt/ef-cms-flexion#2459)
- [x] 4 Verify that cancel modal appears when cancelling the form (Kris)
- [x] 5 Verify that work items appear where they should after submit (Rachael)
- [x] 6 Update submit sequence for creating case from paper (William ustaxcourt/ef-cms-flexion#2459)
- [x] 7 Update Filed By to use the contact primary name or business name instead of case caption (Rachael ustaxcourt/ef-cms-flexion#2465)
- [x] 8 Update integration test (William ustaxcourt/ef-cms-flexion#2467)
- [x] 9 Switch Filed By back to use the case caption entered (Rachael ustaxcourt/ef-cms-flexion#2469)
- [x] 10 Filed date and received date should be Date Received from form (Rachael ustaxcourt/ef-cms-flexion#2469)
- [x] 11 Optional phone number (William ustaxcourt/ef-cms-flexion#2481)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#2484)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
