### ISSUE TITLE
Internal User: Manually add attorney to case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6819]
As an Internal User, in order to make sure all of the counsel of record are properly associated with the case, I need the ability to add Practitioners to a case.

If a Practitioner files a Petition for a Petitioner, only the Practitioner logged into the system will be recognized as the attorney of record and be associated with the case.  However, there are many times when *multiple* attorneys have signed a petition (usually multiple attorneys from the same law firm).  In those cases, the Petitions Clerk needs a way to manually add the other attorneys to the case.

Additionally, other Court users may need to manually add a Practitioner to a case at other times.

## Pre-Conditions
* The Practitioner has been admitted to the Tax Court Bar and has a CMS account

## Acceptance Criteria
* Internal User can search for and select an attorney from a list of practitioners
* Once identified, Internal user can add that attorney to a case
* The CMS needs the ability for more than 1 attorney to be associated with a single party
* If there is more than one Petitioner, the Internal User should be able to notate which petitioner(s) each Practitioner is representing.
* When a practitioner is added to a case:
   * the practitioner can see/access the documents in the case
   * the practitioner's data is viewable to other parties and internal Court Users on the Case Info tab 
   * the case should show up on the Practitioner's dashboard.
   * Practitioner receives any future electronic service

## Notes:
* Need to create some more practitioners in Cognito and Dynamo to test this

## Tasks:
- [x] 1 Build out some users locally and in cognito with different bar numbers and names for practitioners and respondents (Rachael ustaxcourt/ef-cms-flexion#2560)
- [x] 2 Persistence methods, interactors, and endpoints for searching for practitioners/respondents by bar number or name (Rachael ustaxcourt/ef-cms-flexion#2591 ustaxcourt/ef-cms-flexion#2593)
- [x] 3 Actions and sequences for searching for practitioners/respondents (Rachael ustaxcourt/ef-cms-flexion#2597)
- [x] 4 Persistence methods, interactors, and endpoints for associating practitioners/respondents to case (William ustaxcourt/ef-cms-flexion#2570 ustaxcourt/ef-cms-flexion#2583 ustaxcourt/ef-cms-flexion#2578)
- [x] 5 Actions and sequences for associating practitioners/respondents to case (William ustaxcourt/ef-cms-flexion#2583 ustaxcourt/ef-cms-flexion#2578)
- [x] 6 Update case detail case information tab upper portion with new card setup (Rachael ustaxcourt/ef-cms-flexion#2569)
- [x] 7 Add views for Petitioner Counsel and Respondent Counsel sections (Rachael ustaxcourt/ef-cms-flexion#2569)
- [x] 8 Create modal for adding counsel (Rachael ustaxcourt/ef-cms-flexion#2573)
- [x] 9 Create association between practitioners and individual parties on the case (they are currently just associated with an entire case) (Rachael ustaxcourt/ef-cms-flexion#2602)
- [x] 10 Update printable case detail view (Rachael ustaxcourt/ef-cms-flexion#2581)
- [x] 11 Validation for add counsel modals (William ustaxcourt/ef-cms-flexion#2615)
- [x] 12 Show error state on search box when no matches are found (Rachael ustaxcourt/ef-cms-flexion#2599)
- [x] 13 Journey/integration tests (Rachael ustaxcourt/ef-cms-flexion#2604 ustaxcourt/ef-cms-flexion#2611)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
