### ISSUE TITLE
Internal User: Manually remove practitioner from case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6820]
As a Court user, in order to make sure the appropriate Practitioners are associated with a case, I need the ability to manually remove Practitioners from a case. 

An internal user needs the ability to manually remove an attorney/practitioner from a case at any time.  This most often happens when a Substitution of Counsel is filed or there are disciplinary actions.

## Pre-Conditions
*  A Practitioner is associated with a case and a court user needs to disassociate them

## Acceptance Criteria
* Internal court user can manually remove a practitioner from a case.
* User can edit the parties they are representing (see note)
* When a practitioner is removed, the practitioner can no longer access the documents in the case and the practitioner's data is no longer viewable to other parties or internal Court Users on the Case Info tab.
* After a Practitioner is disassociated with a case, that case should no longer show up on the Practitioner's dashboard.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes 
* Bug to fix: If you add a practitioner to a case representing 1 of 2 petitioners, then try to add the same practitioner for the 2nd petitioner, the success message displays but the representing info does not update to include petitioner 2. I would expect that if I search for the same practitioner, any currently represented parties would be pre-checked and that checking unrepresented parties would add them to the practitioners representation info
* Make sure service info still functions when practitioner is removed, so that no data is sent to a removed practitioner.

## Tasks
- [x] 1 Add Edit link to petitioner counsel and respondent counsel cards on case detail page (Rachael ustaxcourt/ef-cms-flexion#3263)
- [x] 2 Edit Petitioner/Respondent Counsel modal views (Rachael ustaxcourt/ef-cms-flexion#3270)
  - [x] 2a Sequences, actions to handle opening and closing the modals (Rachael ustaxcourt/ef-cms-flexion#3270)
- [x] 3 Add methods to Case entity for removing and updating respondents and practitioners (see `attachRespondent`) (Matt ustaxcourt/ef-cms-flexion#3261)
- [x] 4 Create persistence method to remove the user/case mapping record (see `associateUserWithCase`) (Matt ustaxcourt/ef-cms-flexion#3264)
- [x] 5 Create endpoint to handle submitting the edit counsel modals, calling the correct methods on the entity, updating the case, and calling disassociateUserWithCase method when appropriate (Matt ustaxcourt/ef-cms-flexion#3269)
- [x] 6 Sequences and actions to handle validating and submitting the modals (Rachael, Cody ustaxcourt/ef-cms-flexion#3272)
~- [ ] 7 Refactor updateCounselOnCaseInteractor to only update practitioners (respondents can't be updated, only deleted)~
- [x] 8 Validation for edit practitioner modal (Rachael ustaxcourt/ef-cms-flexion#3273)
- [x] 9 Update Add Counsel modals to disable selecting a counsel that has already been added to the case (Cody)
- [x] 10 Edit counsel in journey tests (Rachael ustaxcourt/ef-cms-flexion#3275)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
