### ISSUE TITLE
Petition & Docket Sections: Different inbox for external messages

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6821]
As a Docket or Petition Clerk, in order to manage the volume of external messages generated by external filings, I need a place to manage these external filings that is separate from internal messages. 

The Docket Section is the main traffic controller for all documents coming into and out of the Court.  Every externally-filed document (except a Petition) is routed through docket, and all internally-created documents (Orders, Notices, Opinions, Decisions) are routed through docket.  In order to manage the internal versus external message, especially in light of the high volume of each, it is important that the internal and external messages are kept separate.  As a result, the Docket Section needs to manage external messages separately from the rest of their work. Petition Section also needs a way to see petitions that need QC separately from internal messages they receive. 

MARIAH'S TEST SCENARIOS DOC: https://docs.google.com/document/d/1GH3SRt5-vD2rXAzCzlvQLT97BjfvXYa7WVRMwXds22M/edit?usp=sharing

## Pre-Conditions:
* A party has filed a Petition to start a new case or document in an existing case

### QC Box
* The external document is routed to: Petition Section if it's a petition, the Docket Section if it's any other type of external document
* The external document displays in the Document QC queue that is separate from the queue for internal messages
* Once the QC is complete, the document should move out of QC "inbox" and to: For Petitions goes to "Batched for IRS" tab; for Docket goes to "Processed" tab (Docket QC and "processed" requirements to be completed in ustaxcourt/ef-cms#6777)
* Documents pending in the Docket Section QC Inbox need to be viewable to other Court users (Judges, Senior Attys, etc.)
* Petitions and Docket clerks can see if QC items in their personal QC inbox are read/unread
* Petitions and Docket clerks can see if a QC item is unassigned in the section QC inbox 
* Petitions and Docket clerks can bulk assign QC items in the Section QC box to another clerk in their section 
* Petitions and Docket clerks can toggle between their personal QC box and Section QC box
* Petitions and Docket clerks can see how many "unread" QC items are in their personal inbox and how many TOTAL items are in the QC section inbox
* Other court users only see the count for the TOTAL items in the QC section inbox

### Messages
* Message box should only show internal messages from other court users
* Messages always display the message text in the table (no show/hide function) 
* User can click anywhere on the row and be taken to the message in the document detail page
* User can see count of TOTAL number of items in their section message box 
* User can see an indication of when they have a new unread message no matter where in the system they are. 

## Notes:
* Implement this with high-priority indicator story (#1432)

## Tasks ##
~NOTE: All tasks are currently completed and merged to develop, but are awaiting resolution on a deploy issue.~

- [x] Add isInternal flag to document work items on creation (Cody ustaxcourt/ef-cms-flexion#1956)
- [x] Add QC Route and assoc. view (Matt ustaxcourt/ef-cms-flexion#1939, ustaxcourt/ef-cms-flexion#1956)
- [x] Document QC: Batched for IRS tab (Cody ustaxcourt/ef-cms-flexion#1956)
- [x] Document QC: Dynamically Change the Sent tab name "Served / Processed / Sent" (Cody ustaxcourt/ef-cms-flexion#1956)
- [x] Filter messages between "My" and "Section" Document QC (Cody ustaxcourt/ef-cms-flexion#1956)
- [x] Verify all table column names match design (Joe ustaxcourt/ef-cms-flexion#1956)
- [x] Refactor My Messages to only display internal messages (Cody ustaxcourt/ef-cms-flexion#1956)
- [x] Served should not displayed the "Batched for IRS" messages (Joe ustaxcourt/ef-cms-flexion#1956)
- [x] Work on the "Other Court Users" design (Cody ustaxcourt/ef-cms-flexion#1956)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
