### ISSUE TITLE
Petitioner/Practitioner: Review Petition before starting a case

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6823]
As a Petitioner or Practitioner, in order to make sure that I've entered in accurate information as I'm filing my Petition, I need the ability to review all of my entries and documentation before starting a case.

## Pre-Conditions:
* Petitioner or Practitioner has entered all required information in the "Start a Case" form and is ready to submit it to the Court and start a new case

## Acceptance Criteria:
* Petitioner or Practitioner has the ability to review and change any information submitted on the "Start a Case" form
* Petitioner or Practitioner can view the actual PDF of each document to be transmitted to the Court as part of the review process (#1566 functionality)
* User should be able to perform this function on mobile

## Notes:
* Confirm design is done (posted below)

## Tasks
 - [x]  Create review view (Matt)
 - [x]  Routing (for back button use) (Matt)
 - [x]  Generate document previews (Matt)

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable)

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
