### ISSUE TITLE
Feedback from Practitioner Interviews

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6827]
Usability Study | Practitioner Case Form: https://docs.google.com/presentation/d/1HcjhQ3_nKtgIR-9hh8uqKMS4yB02XGwznEKfFrx6SyA/edit?usp=sharing

("Recommendations" section moved to the bottom of this comment)

## Acceptance Criteria:

**Petitioner and Practitioner Dashboard:**
* Change "Petitioner Name" to "Case Name" 

**Petitioner and Practitioner "Start a Case" Forms:**
* Change `Start a Case`  to `File a Petition` (make sure that this change is applied throughout the application)
* Add reminder to redact information on the IRS notice to the helper text 
* Consider adding guidance to party options to make it clear there are additional choices in each category 
* Revise party contact fields & use new fields to populate "Filed by" options on File a Petition form (https://docs.google.com/document/d/1_pv9J_RnUGVdEM8HOdX4iikx3rKbgQXyXd_OG8BVC_I/edit?usp=sharing)
* Add Judge Buch's comment about "next closest place of trial may not be in your state"
* Remove IRS notice date from "Start a Case" form; info should be entered by Petitions Clerk during QC
* Add clarification that redaction does not apply to the STIN document  
* Soften language for these instructions; update to “Reminders

**Docket Record for All Users:**
* Make sure any document uploaded during the petition filing process (Petition, Request for Place of Trial, ODS) has a corresponding code for the docket table
* When practitioner files a petition, update the petition "Filed By" to display with petitioner's name (not practitioner)

## Tasks 
- [x] 1 Change "Petitioner Name" to "Case Name" (Kristen ustaxcourt/ef-cms-flexion#2335) 
- [x] 2 Update Before You Begin screen (Kristen ustaxcourt/ef-cms-flexion#2335)
- [x]  3 Add Judge Buch's comment about "next closest place of trial may not be in your state" (Kristen ustaxcourt/ef-cms-flexion#2335/#2354)
- [x]  4 Add clarification that redaction does not apply to the STIN document (Kristen ustaxcourt/ef-cms-flexion#2335/#2354)
- [x] 5 Create wizard for starting a case and split views into separate steps (Rachael ustaxcourt/ef-cms-flexion#2494)
- [x] 6 Multi-step validation for wizard (Rachael ustaxcourt/ef-cms-flexion#2502 ustaxcourt/ef-cms-flexion#2504)
  - [x] 6a Remove irsNoticeDate from validation (it's no longer on the form) (Rachael ustaxcourt/ef-cms-flexion#2509)
- [x] 7 Step 1 view updates (STIN) (Rachael ustaxcourt/ef-cms-flexion#2494)
- [x] 8 Step 2 view updates (Tell Us About Your Petition) (Rachael ustaxcourt/ef-cms-flexion#2497)
   - [x] 8a Remove Date of Notice from UI (Rachael ustaxcourt/ef-cms-flexion#2497)
- [x] 9 Step 3 view updates (Who are you filing this petition for?) (William ustaxcourt/ef-cms-flexion#2511)
   - [x] 9a Update party contact fields (William ustaxcourt/ef-cms-flexion#2511)
   - [x] 9b Update case info space (William ustaxcourt/ef-cms-flexion#2511)
   - [x] 9c Remove email field and hint (William ustaxcourt/ef-cms-flexion#2511)
   - [x] 9d Update labels on QC page for new combined contacts (William ustaxcourt/ef-cms-flexion#2511)
   - [x] 9e Update case caption generation for combined contacts (William ustaxcourt/ef-cms-flexion#2511)
- [x] 10 Step 4 view updates (How do you want this case handled?) (Rachael ustaxcourt/ef-cms-flexion#2497)
   - [x] 10a Add U.S. Tax Court Locations subsection (Rachael ustaxcourt/ef-cms-flexion#2497)
   - [x] 10b Update small case vs regular case accordion (Rachael ustaxcourt/ef-cms-flexion#2497)
- [x] 11 Call submit sequence from step 4 continue button and verify that it submits correctly (Rachael ustaxcourt/ef-cms-flexion#2509)
- [x] 12 Verify that all form values are retained when clicking the back buttons (Rachael ustaxcourt/ef-cms-flexion#2509)
- [x] 13 Clean up old code that is no longer used (Rachael ustaxcourt/ef-cms-flexion#2516)
- [x] 14 Add event codes for initially filed docs (Rachael ustaxcourt/ef-cms-flexion#2515)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (William)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Rachael)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (William ustaxcourt/ef-cms-flexion#2521)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (William ustaxcourt/ef-cms-flexion#2521)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
## Recommendations:
* Dashboard 
   * Emphasize “Start a Case” button and consider updating language to “File Petition” - DONE
* Petition Upload 
    * Add reminder to redact information on the IRS notice to the helper text - ustaxcourt/ef-cms#6827 
* Party Information  
   * Consider adding guidance to party options to make it clear there are additional choices in each category - ustaxcourt/ef-cms#6827 
   * Consider redefining the required contact fields (telephone, email), especially when the petitioner is represented by counsel - ustaxcourt/ef-cms#6827 
* Case Type 
   * Update language to account for cases that are not initiated by a “notice” (specifically Declaratory Judgment) - DONE
   * Update Notice Date field to optional - ustaxcourt/ef-cms#6827 
* Submission Instructions 
    * Add clarification that redaction does not apply to the STIN document - ustaxcourt/ef-cms#6827   
    * Soften language for these instructions; update to “Reminders” - ustaxcourt/ef-cms#6827 
* Review Case Form 
   * Add PDF preview option before submission - ustaxcourt/ef-cms#6823 
   * Add a review screen to view all entered information before submission - ustaxcourt/ef-cms#6823 
* Document Type Selections 
   * Make the type-ahead search for document type available to practitioners - ustaxcourt/ef-cms-flexion#1508 
   * Revise the “browse” document type presentation and flow - ustaxcourt/ef-cms-flexion#1508
   * Revisit the flow of the document selection - ustaxcourt/ef-cms-flexion#1508
* Inclusions 
   * Add helper text language for the different types of inclusions, with examples (specifically Attachments) - ustaxcourt/ef-cms-flexion#1508
* Filing Parties  
   * Revise options to clarify that counsel is filing on behalf of the petitioner and not themselves - ustaxcourt/ef-cms-flexion#1508 
   ~* Consider removing the “Counsel” option unless the document type is Motion to Withdraw~ 
* Review and Submission 
   * Add PDF preview feature before document submission - ustaxcourt/ef-cms-flexion#1566 
* Case Management 
   ~* Maintain visibility into closed cases; consider capping access to closed cases after 5 years~  
   ~* Define and display an external-facing case status (may be a subset of internal statuses, or mapped to specific internal statuses)~ 
   * Display pending due dates for active cases (for example, due date for pre-trial memorandum 14 days before trial date) - ustaxcourt/ef-cms-flexion#2041
* Service Emails 
   * Consider including case caption and document title in the service notifications (if privacy laws allow) - ustaxcourt/ef-cms-flexion#1921 
* Dashboard 
   * Display recent/new filings for active cases on the dashboard - ustaxcourt/ef-cms-flexion#2040
   * Display pending due dates for cases on dashboard - ustaxcourt/ef-cms-flexion#2041
* Search  
   * Add ability to search by petitioner name (MVP) ustaxcourt/ef-cms-flexion#2038
   * Add ability to search by attorney name (Post-MVP) - ustaxcourt/ef-cms-flexion#2039
* Messaging 
   ~* Consider communication options between practitioners and judges (i.e. could practitioners be able to send a system message to a judge’s inbox to request a conference call)~
* Account Management 
   ~* Consider a student access role to allow law students visibility into their cases without full rights~ 
   * Allow practitioners to add multiple service addresses for different client types - ustaxcourt/ef-cms-flexion#1944
