### ISSUE TITLE
CMS User: Sortable Docket Record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6828]
As a CMS User, in order to view the docket record in a way that's most useful to me, I need each column to be sortable.

## Pre-Conditions:
* CMS User is viewing docket record

## Acceptance Criteria:
* The docket record should be sortable by the index entry number (column 1) and the date filed (column 2)
* Default sort on the date column

## Tasks
- [x] 1. create select menus
  - [x] 1a. with four options for use on large screens (Rachael ustaxcourt/ef-cms-flexion#1645)
  - [x] 1b. as toggle-button (with two options for date asc, date desc) on mobile (Rachael ustaxcourt/ef-cms-flexion#1645)
  - [x] 1c. create sequences & actions to store sorting preferences in state (William ustaxcourt/ef-cms-flexion#1643)
- [x] 2. alter `formattedCaseDetail` (around line 155) to identify the desired sorting method and apply it (kris ustaxcourt/ef-cms-flexion#1644)
  - [x] 2a. create sort functions for 'date asc', 'date desc', 'index asc', 'index desc' (kris ustaxcourt/ef-cms-flexion#1644)
- [x] 3. clear sessionMetadata sort option when navigating to a different case or when logging out/in (Rachael)
- [x] 4. Persist sort option per case over the session (William ustaxcourt/ef-cms-flexion#1650)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x] README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
