### ISSUE TITLE
Mobile Docket View

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6829]
As a mobile user, so that I can easily access the docket on my mobile device, I need a docket table that is mobile friendly. 

## Pre-Conditions:
* CMS user is trying to view docket table on mobile device

## Acceptance Criteria:
* Implement mobile-friendly view of docket record
* Apply new mobile style to all mobile views.

## Tasks
- [x] 1. Dashboard - update table mobile design (William ustaxcourt/ef-cms-flexion#1496)
- [x] 2. Case Detail - update table mobile design (Rachael ustaxcourt/ef-cms-flexion#1483)
  - [x] 2a. Call sequences created in 3a to open/close overlay (Kris ustaxcourt/ef-cms-flexion#1492 )
- [x] 3. Document detail mobile view overlay (Kris ustaxcourt/ef-cms-flexion#1492 )
  - [x] 3a. Create sequences to open/close overlay (Kris ustaxcourt/ef-cms-flexion#1492)
- [x] 4. Responsive tab design (style guide reminder) (William ustaxcourt/ef-cms-flexion#1494)
~~5. Refactor document detail links on DocketRecord.jsx to refine logic~~ (devex task)
- [x] 6. Make sure styles extend for tablet width (William ustaxcourt/ef-cms-flexion#1505)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects) (#1507)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
