### ISSUE TITLE
System validates that PDF is valid PDF during upload

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6830]
As the court, in order to ensure that we're only uploading PDFs into the system, I need the system to validate during all document upload that documents are valid PDFs.

## Pre-Conditions
* User has attempted to upload a document

## Acceptance Criteria
* System validates that PDF is a valid PDF during document upload

## Notes
* Hard to know what failure rate would be until we start getting uploads from the public.
* Lots of different software that creates PDFs and they may not follow PDF specifications. If some piece of metadata is missing, it may cause a failure during cover sheet application. 
* Jessica would prefer for documents to be rejected instead of not having cover sheet applied.
* See ustaxcourt/ef-cms#6792 

## Tasks
- [x] Create use case ustaxcourt/ef-cms-flexion#1973 
- [x] Create use case test ustaxcourt/ef-cms-flexion#1973 
- [x] Create lambda ustaxcourt/ef-cms-flexion#1973 
- [x] Create validatePdf proxy and execute it on file uploads ustaxcourt/ef-cms-flexion#1973
- [x] Address failed "pending document" bug (Joe ustaxcourt/ef-cms-flexion#2032)
- [x] Address test coverage flags from SonarCube (Joe)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
