### ISSUE TITLE
Usability Testing: File a Document Form Clean-Up

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6831]
As a Petitioner, Practitioner and IRS Attorney, so that I may have a clear and organized user experience, I need the File a Document form updated. 

## Acceptance Criteria 

For all external users (petitioners, practitioners and IRS attorneys) in the File a Document Form:
 * Allow type-ahead document selection (same as currently built for internal users)
 * Update the "browse" document type presentation and flow to allow users to more easily navigate ("drill down") and select the correct document
* On the File Your Documents Screen:
     * Display full concatenated document title
     * Allow user to add multiple supporting documents
     * _For multiple supporting documents test/ensure:_ that each creates a separate docket entry w/court-formatting rules; If the supporting document is filed in support of a "Filed" document, the supporting document will also be "Filed"; if the supporting document is filed in support of a "Lodged" document, the supporting document will also be "Lodged"
* Provide users with more details about what can be included with their document (exhibits, attachments and certificate of service)
* In Supporting Documents section, add questions re: C/S, Attachments, Exhibits, Objections (if relevant) to each document on File a Doc form (Primary, Supporting Doc to Primary, Secondary, Supporting Doc to Secondary) 
* In the Tell Us about Parties Filing section, dynamically display petitioner's and counsel's names instead of static field labels; always include respondent (static) as an option
* In the Review Your Filing section:
     * Show what inclusions were selected; show objections as well
     * Content Edit: Does this document have Exhibits? should be Exhibit(s).  Same with Attachment(s) 
* Ensure all above changes are mobile friendly (responsive); with slight variations between desktop and mobile as needed.

## Tasks
- [x] 1 Add `Before you file` screen to file doc wizard (desktop and mobile) (Kris ustaxcourt/ef-cms-flexion#2298)
- [x] 2 Update Desktop document type select screen (William ustaxcourt/ef-cms-flexion#2322)
  - [x] 2a Desktop doc type select view using type-ahead menu  (William ustaxcourt/ef-cms-flexion#2322)
  ~2c Use typeahead doc type select menu created for internal users~
  - [x] 2d Add accordion section on right side of screen on desktop (William ustaxcourt/ef-cms-flexion#2299 ustaxcourt/ef-cms-flexion#2301 ustaxcourt/ef-cms-flexion#2315)
- [x] 3 Create Desktop `All Document Categories` view (William ustaxcourt/ef-cms-flexion#2315 ustaxcourt/ef-cms-flexion#2322)
  - [x] 3a Create modal for nonstandard form  (William ustaxcourt/ef-cms-flexion#2322)
  - [x] 3b Accordion Component (William ustaxcourt/ef-cms-flexion#2299)
- [x] 4 Update mobile type select screen (William ustaxcourt/ef-cms-flexion#2344 ustaxcourt/ef-cms-flexion#2351)
  - [x] 4a Mobile doc type select view  (William ustaxcourt/ef-cms-flexion#2344)
  - [x] 4b Create mobile wizard for selecting a document type when `I Need Help Selecting a Document` (William ustaxcourt/ef-cms-flexion#2344)
- [x] 5 Create Mobile `All Document Categories` view (William ustaxcourt/ef-cms-flexion#2344)
- [x] 6 Update file document form view (desktop and mobile) (Rachael ustaxcourt/ef-cms-flexion#2328 ustaxcourt/ef-cms-flexion#2346)
  - [x] 6a Create `What can I include with my document?` view (William ustaxcourt/ef-cms-flexion#2387)
  - [x] 6b Modify file document actions and interactors to add multiple supporting documents (Rachael ustaxcourt/ef-cms-flexion#2370)
  - [x] 6c Create view for multiple supporting documents (Rachael ustaxcourt/ef-cms-flexion#2370)
  - [x] 6d Generalize inclusions form to be used on primary, secondary, and supporting docs (Rachael ustaxcourt/ef-cms-flexion#2349)
  - [x] 6e Validation for multiple supporting docs (Rachael ustaxcourt/ef-cms-flexion#2395)
  - [x] 6f Add inclusions form to supporting docs (Rachael ustaxcourt/ef-cms-flexion#2385)
  - [x] 6g Review validation messages that are shown in UI for multiple supporting docs (Rachael ustaxcourt/ef-cms-flexion#2425)
    - [x] supportingDocuments ustaxcourt/ef-cms#6491 - supportingDocument field - Enter selection for Supporting Document. (Rachael ustaxcourt/ef-cms-flexion#2425)
    - [x] cert of service date on supporting docs not validating (Rachael ustaxcourt/ef-cms-flexion#2425)
- [x] 7 Update review screen (desktop and mobile) (William ustaxcourt/ef-cms-flexion#2363)
  - [x] 7a Incorporate Document Preview links (Clarion ustaxcourt/ef-cms-flexion#2391)
  - [x] 7b Handle Optional forms (William ustaxcourt/ef-cms-flexion#2392)
  - [x] 7c Update review page for multiple supporting docs (Rachael ustaxcourt/ef-cms-flexion#2396)
  - [x] 7d Update review page to show inclusions for all docs (Rachael)
- [x] 8 Add `File a Document` button to mobile case detail page (Rachael ustaxcourt/ef-cms-flexion#2306)
- [x] 9 Update pa11y test (Rachael ustaxcourt/ef-cms-flexion#2431)
- [x] 10 Remove exhibits from entities, form, and review page (Rachael ustaxcourt/ef-cms-flexion#2398)
- [x] 11 UX fixes
  - [x] cancel button on mobile on step 1 (William ustaxcourt/ef-cms-flexion#2410)
  - [x] change document button next to uploaded files on doc form (mobile) (Rachael ustaxcourt/ef-cms-flexion#2427)
  - [x] add text to replace button if they add 5 supporting docs - "You can only add 5 supporting documents at a time. You may file another supporting document in a separate filing." (Rachael ustaxcourt/ef-cms-flexion#2427)
  - [x] hook up supporting doc what can I include modal (Rachael ustaxcourt/ef-cms-flexion#2414)
  - [x] ~space below review filing button on mobile file doc page~ looks like this is already fixed
  - [x] add margin-bottom-2 div around file area on review page for supporting docs ONLY on mobile (margin-bottom-0 on desktop) (Rachael ustaxcourt/ef-cms-flexion#2414)
  - [x] add ,Petitioner to parties on review page (display the same as on File a Doc form page for all parties) (Rachael ustaxcourt/ef-cms-flexion#2427)
  - [x] hide inclusions and Add Secondary Supporting button on secondary doc unless they upload a doc for optional (only for Motion for Leave to File) (Rachael ustaxcourt/ef-cms-flexion#2414)
- [x] 12 add "Back" button on File a Document form on mobile and desktop  (William ustaxcourt/ef-cms-flexion#2424)
- [x] 13 anchor back to top when navigating to modal on mobile (William ustaxcourt/ef-cms-flexion#2437)
- [x] 14 resolve issues with multiple practitioner parties on form and review page (Rachael ustaxcourt/ef-cms-flexion#2429)
- [x] 15 Per feedback from Jessica, whenever a document is lodged, the code should always be MISL. Currently it's getting the code for the document for which is was filed (incorrect) - When a party files a Motion for Leave to File -- the secondary document and any supporting docs for that secondary doc are "lodged" not filed. Those secondary and supporting docs should have MISL as code. (William ustaxcourt/ef-cms-flexion#2432)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael ustaxcourt/ef-cms-flexion#2433)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) 
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael ustaxcourt/ef-cms-flexion#2444)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#2433)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Rachael ustaxcourt/ef-cms-flexion#2433)
 - [x] Deployed to the dev environment
