### ISSUE TITLE
Global navigation

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6832]
As a user, so that I can easily navigate within the system, I need global navigation.

## Pre-Conditions
* User is logged in

## Acceptance Criteria
* Users can easily navigate around the system
* Users have a way to sign out of the system

## Tasks
- [x] add logo (Matt ustaxcourt/ef-cms-flexion#1641)
- [x] primary links with styling (Matt ustaxcourt/ef-cms-flexion#1641)
- [x] computed to show / hide primary links based on roles (Matt ustaxcourt/ef-cms-flexion#1641)
- [x] user dropdown (Matt ustaxcourt/ef-cms-flexion#1641)
- [x] mobile? (Matt? ustaxcourt/ef-cms-flexion#1641)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version [Note:  5/6/19 - Court granted permission for a 30-day exception for the `tar` library]
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
