### ISSUE TITLE
External User: View documents uploads before they are associated with case/docket entry (Orphan Documents)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6833]
As an external user (Petitioner, Practitioner, IRS attorney), in order to make sure the correct document is being uploaded, I need to the ability to view documents before they are associated with a case/docket entry.

There are several instances where an external user needs the ability to view documents before they are associated with a case/docket entry:
* As an external filer, I need the ability to review the documents I am trying to submit as my petition package before the case is created.
* As an external filer, I need the ability to review the documents I am trying to file before they are filed in an existing case.

## Pre-Conditions:
* External user (Petitioner, Practitioner, IRS attorney) is in the process of uploading a document

## Acceptance Criteria:
* External user (Petitioner, Practitioner, IRS attorney) has the ability to view documents before they are associated with a case/docket entry
* External user (Petitioner, Practitioner, IRS attorney) can perform this task on mobile device

## Notes
* This story does not address Start a Case review page. This will be handled in ustaxcourt/ef-cms#6823 when we work on the review story. 
* Concurrent work on these pages. Themis working on File a Doc page in same sprint. 
* No housing of documents in temporary state for this story

## Tasks
 - [x]  Finalize test scenarios and inform team they're ready (Mariah to pair w/Sarah)
 - [x] POC modal vs. tab for document display (Eric and Matt ustaxcourt/ef-cms-flexion#2374)
 - [x] Testing modal vs. tab on tablets/phone (Cody)
 - [x] Add spinner (Joe ustaxcourt/ef-cms-flexion#2388)
 - [x] Update UX design (Sarah)
 - [x] Adding links to all review pages (Matt)
- [x] Error message on failure to load document

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ] Acceptance criteria have been met

**UX**
 - [ ] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Eric)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt ustaxcourt/ef-cms-flexion#2408)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Cody)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Joe)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
