### ISSUE TITLE
Docket Clerk: Ability to scan/upload document after docket entry is created

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6834]
As a Docket Clerk, in order to manage my work flow, I need the ability to scan/upload a document after the docket entry is created.

When a Docket Clerk is processing a paper document, they may choose to scan/upload the document at the same time that they are creating the docket entry.  However, a Docket Clerk may also choose to create several docket entries and then come back and scan/upload the documents for each docket entry.  The Docket Clerk needs the flexibility to do both.

## Pre-Conditions:
* Docket clerk has a paper-filed document
* Docket Clerk can create a docket entry without a document (#1896)

## Acceptance Criteria:
* Docket Clerk must have the ability to scan/upload document to a previously created docket entry
* Court users and parties must be able to see which docket entries are incomplete on the docket record (missing scanned doc)
* Docket Clerks must be able to see which docket entries are incomplete in a way other than on the docket record (so they don't forget)
* Docket Clerks must be able to select a docket entry for which to scan/upload a document
* Incomplete docket entries on the docket record are viewable

## Notes:
* Docket clerk may have a section on dashboard that lists incomplete docket entries
* Comprehensive tests required - when things are valid vs not valid
* Story ustaxcourt/ef-cms#6857 will change the add docket entry page so user can add an entry without a document
* Docket entry without a document will appear on the docket entry but will not have a hyperlink (or could have a hyperlink that links to doc detail to complete)
* Start with all potential states of a document / docket entry
* Docket Clerks normally complete these on the same day (working box on their desk)
* Possibilities for displaying incomplete docket entries include on the QC for the user who made the entry (as well as in the section), probably shown separately from other QC items
* Court currently tells parties that an entry is "pending" when there is no doc attached yet
* No links are provided to public / parties on docket record as standard

## Tasks
 - [x]  Test scenarios around docket entry states
 - [x]  Validation for docket entry that does not include adding a document as required
 - [x]  Show incomplete entries on the docket record
 - [x]  Assign work item to creator (Docket Clerk)
 - [x]  In Progress Tab on Docket Clerk - My Document QC
 - [x]  In Progress Tab on Docket Clerk - Section QC
 - [x]  Edit docket entry route
 - [x]  Editable docket entry view (reuse create view) for incomplete docket entries
 - [x]  Update docket record interactor

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (#2749 Cody Jojo)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (#2749 Cody Jojo)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (#2749 Cody Jojo)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
