### ISSUE TITLE
High Priority Indicator for External Filings (automated)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6836]
As a Court user, in order to easily identify items that are high priority and need immediate attention, I need a high priority indicator on certain messages in my work queues. 

There are 10,000s of documents that get filed each year with the Court.  In general, the Court processes things on a first-in-first-out basis.  However, when documents get filed in cases that are set for trial, those documents must be processed ASAP.  For external filings, there needs to be the ability to automatically set something as high priority based on Court-provided parameters.  This will apply whenever a document is filed in a case that is calendared for a trial on trial session.   

## Pre-Conditions:
* External document is filed in a case that is scheduled for trial.
* External document is routed to Docket QC box.

## Acceptance Criteria:
* External filings should automatically be marked as high priority based on Court-provided logic
* High priority items should appear at the top of the QC box and should be displayed in descending order based on trial date. 
      * Any document filed in a case that is calendared for trial should automatically be tagged as high-priority.  The high-priority items should be further prioritized by trial/hearing date.  Closest trial/hearing date first then second closest etc.

## Notes:

* We may have design for this already in Figma

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add high priority to work item entity (Rachael ustaxcourt/ef-cms-flexion#4199)
- [x] 2 Set high priority to true when creating a work item for an external document filing if the case is calendared for trial (Rachael ustaxcourt/ef-cms-flexion#4199)
- [x] 3 Add high priority indicator to work items in document QC inboxes (individual and section inboxes only) (Rachael ustaxcourt/ef-cms-flexion#4199)
- [x] 4 Sort work items in document QC inboxes with high priority items at the top (individual and section inboxes only) (Cody ustaxcourt/ef-cms-flexion#4204)
- [x] 5 Sort high priority work items in trial date order (oldest to newest), then by date received (oldest to newest)  (Cody ustaxcourt/ef-cms-flexion#4204)
- [x] 6 Add trial date to work items and update it when the trial date is updated (same way we update the docket number suffix) (Rachael/Kris ustaxcourt/ef-cms-flexion#4205)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
