### ISSUE TITLE
Removing executables from documents

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6839]
As the Court, in order to protect the CMS from unnecessary risk, I need all executables to be removed from incoming documents.

## Acceptance Criteria:
* All executables must be removed from all incoming documents.

## Notes 
How to add binaries to Lambdas: https://instil.co/2017/08/07/using-native-dependencies-with-aws-lambda/

## Tasks
- [x] 1 create use-case interactor for sanitizing PDFs (Kris, William, Rachael) ustaxcourt/ef-cms-flexion#1890
- [x] 2 integrate sanitizing use-case into workflow that adds cover sheet (Kris)
- [x] 3 add docker updates for ghostscript4js ustaxcourt/ef-cms-flexion#1890
- [x] 4 write tests producing image diff artifacts with pixel differences under a given threshold (Rachael, Kris, William - in branch `pdf-comparison-demo`)
- [x] 5 figure out the `no-cache` docker issue (Rachael ustaxcourt/ef-cms-flexion#1902)
- [x] 6 add interactor to Lambda with native ghostscript library (Rachael)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs (Rachael ustaxcourt/ef-cms-flexion#1929)
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
