### ISSUE TITLE
Member of the Public: Printable Docket Record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6840]
As a member of the public, in order to see what has transpired in a case, I want to be able to view and print a copy of the docket record.

The docket record is a official record of everything that has happened in a case. A member of the public may need to print a copy of the docket record for a variety of reasons.  If someone wishes to print the docket record, a print optimized view should be created that includes the docket number, case caption, as well as the docket record. The parties' contact information should *not* be displayed on this public view.

## Pre-Conditions:
* A case exists in the system.

## Acceptance Criteria (Post-Conditions):
* Any member of the public can view and produce a print optimized (PDF) view that includes the docket number, case caption, as well as the docket record.
* Parties' contact information should *not* be displayed on this public view.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes:
* This is very similar to the print optimized view that was created for parties and Court users in ustaxcourt/ef-cms#6528.  The only difference is that the parties' contact information needs to be hidden to members of the public.

## Tasks
- [x] 1 Create new endpoint for generating public docket record pdf (Cody ustaxcourt/ef-cms-flexion#3776)
  ~- [ ] 1a Update generateDocketRecordPdfInteractor to use pug (and possibly reuse for public docket record pdf) (Kris)~ move to refactoring backlog
- [x] 2 Create route and view for public printable docket record (Cody ustaxcourt/ef-cms-flexion#3776)
- [x] 3 Update generateDocketRecordPdfInteractor to hide contact info with flag passed in (Kris ustaxcourt/ef-cms-flexion#3783)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
