### ISSUE TITLE
Upgrade to USWDS 2.0

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6841]
As a development in order to make sure that all styles are consistent across the app, we need to updates styles wherever they're not consistent. 

## Acceptance Criteria
* All styles are consistent throughout the site. 

## Notes
* These changes are for pre-USWDS changes and to ensure style classes are consistent throught the site before the update takes place; with the exception of the header, which will be updated to 2.0 classes. 

## Tasks
- [x] 1) Update inconsistencies in Start a Case Flow (Joe) 
- [x] 2) Update inconsistencies in File a Document Flow (Rachael)
- [x] 3) Update header w/2.0 classes (Matt)
- [x] 4) Update inconsistencies on Case Detail Page (William)
- [x] 5) Update inconsistencies on Document Detail and in Modals (Kris)
- [x] 6) Update inconsistencies in Dashboards (Eric)
- [x] 7) Review changes with engineering (Kristen)
- [x] 8) Update labels (Eric)
- [x] 9) Request Access to Case (Rachael)
- [x] 10) Add Docket Entry (Joe)
