### ISSUE TITLE
New Design: All Messages/QC Review

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6843]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update all messages/QC review pages. 

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* Messages/QC Review design for all sections and users are updated with newest changes to our style guide

## Tasks
- [x] Convert messages header to blue bar design, with message context toggle (Matt ustaxcourt/ef-cms-flexion#1698)
- [x] Show message icon in global nav when message count is greater than zero (Cody ustaxcourt/ef-cms-flexion#1689)
- [x] Pull table controls out of the table (selected, actions, etc.) (Cody ustaxcourt/ef-cms-flexion#1693)
- [x] Main table design (Joseph ustaxcourt/ef-cms-flexion#1706)
- [x] Case status label text should be bold (Kris)
- [x] "Switch to X" toggle link should be underlined by default (stays underlined and changes color on hover) (Rachael ustaxcourt/ef-cms-flexion#1735)
- [x] Hyperlinked document title should show uniform blue outline (Kris ustaxcourt/ef-cms-flexion#1750)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
