### ISSUE TITLE
New Design: Case Detail Page

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6844]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the Case Detail Page

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* Case Detail Page is updated with newest changes to our style guide

## Tasks
- [x] 1. Update Messages in Progress view (Cody ustaxcourt/ef-cms-flexion#1713)
- [x] 2. Update Docket Record view (desktop) (Cody ustaxcourt/ef-cms-flexion#1716)
- [x] 2a. Docket Number Header - Eric
- [x] 2b. update button design and actions - (Rachael ustaxcourt/ef-cms-flexion#1715 ustaxcourt/ef-cms-flexion#1726)
- [x] 3. Update Docket Record view (mobile) - (Matt ustaxcourt/ef-cms-flexion#1718)
- [x] 4. Update Document Details mobile overlay (Rachael ustaxcourt/ef-cms-flexion#1732)
- [x] 5. Update Case Information view - (William ustaxcourt/ef-cms-flexion#1717 ustaxcourt/ef-cms-flexion#1728)
- [x] 6. Update Action Required view - (Cody ustaxcourt/ef-cms-flexion#1707 ustaxcourt/ef-cms-flexion#1710)
- [x] 7. Revisit header (Cody ustaxcourt/ef-cms-flexion#1737)
- [x] 8. Remove icon from pending messages (Joe ustaxcourt/ef-cms-flexion#1724)
- [x] 9. Add hoverstate to white links on dark backgrounds (Eric)
- [x] 10. Check hoverstates on all primary links
- [x] 11. TAB TASKS - a. Unselected tabs color should be blue and bold, b. Left align first tab with left margin of table underneath, c. Onstate bar underneath tab should be same width as text (Cody ustaxcourt/ef-cms-flexion#1734)
- [x] 12. Sizing on the case information docket record tabs (Cody ustaxcourt/ef-cms-flexion#1734)
- [x] 13. Select dropdown box should have a hoverstate, check global style guide (Joe ustaxcourt/ef-cms-flexion#1729)
- [x] 14. Add semi-bold 600 font weight back to global styles (Eric)
- [x] 15. Change mobile view tabs to select menu (Joe ustaxcourt/ef-cms-flexion#1731 ustaxcourt/ef-cms-flexion#1764)
- [x] 16. Update Case Information view (mobile) - (William  ustaxcourt/ef-cms-flexion#1739 ustaxcourt/ef-cms-flexion#1741)
- [x] 17. Align responsive breakpoints - (William ustaxcourt/ef-cms-flexion#1748)
- [x] 18. Format dates with 2-digit year (Rachael ustaxcourt/ef-cms-flexion#1751)
- [x] 19 Both tables are missing row hover (Eric)
- [x] 20 The underline under Messages should be closer to the word (10px bottom padding) (Matt #https://github.com/flexion/ef-cms/pull/1767)
- [x] 22 Top/bottom padding on all table rows should be 15px, not 20px  (Eric)
- [x] 23 When body copy falls under a field label (like in Case info tab), the body copy/paragraph style should have margin-top: 5px (default is 16px it appears) (Rachael ustaxcourt/ef-cms-flexion#1755)
- [x] 24 On case info tab, the padding around content area should be 20px (currently 15px) (William ustaxcourt/ef-cms-flexion#1754)
- [x] 25 Increase spacing under the horizontal line under the docket record/case info table (above the cards) to 40px (margin-bottom of tab container) (Rachael ustaxcourt/ef-cms-flexion#1752)
- [x] 26 Stroke outline on cards for should be #dcdee0 bg-base-lighter (Rachael ustaxcourt/ef-cms-flexion#1752)
- [x] 27 wrap td content with span and add no wrap to columns (Cody ustaxcourt/ef-cms-flexion#1753)
- [x] 28 align add docket entry button and sort field (Rachael ustaxcourt/ef-cms-flexion#1755)
## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
