### ISSUE TITLE
New Design: Document Detail Page

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6845]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update Document Detail Page

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* Document Detail Page design is updated with newest changes to our style guide

## Notes
* (From 1652 review)-  Required fields on Send Message form not showing field level errors 

## Tasks
- [x] 1) update card styles in messages (Cody ustaxcourt/ef-cms-flexion#1720)
- [x] 2) realign the filed by (Matt ustaxcourt/ef-cms-flexion#1736)
- [x] 3) buttons on messages / header (Cody)
- [x] 4) align pdf view with tabs on left (Kris ustaxcourt/ef-cms-flexion#1742)
- [x] 5) fix tab styles (blue background on selected) (Cody)
- [x] 6) subtab styles (Cody)
- [x] 7) fix field level errors for send message (Cody ustaxcourt/ef-cms-flexion#1749)
- [x] 8 H3 tabs should be split evenly and centered across the horizontal space (Cody ustaxcourt/ef-cms-flexion#1756) 
- [x] 9 H3 tabs onstate/hover state underline should be closer to text (update padding-bottom to 5px for .ustc-ui-tabs.container-tabs nav ul li button span) (Cody ustaxcourt/ef-cms-flexion#1756) 
- [x] 10 Space between document name and filed by should be 15px (William ustaxcourt/ef-cms-flexion#1758)
- [x] 11 Field borders should be #71767a bg-base (Rachael ustaxcourt/ef-cms-flexion#1761)
- [x] 12 Doc Info Parties tab (for Petition doc type) - Remove "Mailing Address" (this might be global, if so, remove in all cases) and change "Address Line 1" to "Mailing Address Line 1"  (Rachael ustaxcourt/ef-cms-flexion#1761)
- [x] 13 Notice Attached to Petition + Type of Case - should be 15px between label and field (Rachael ustaxcourt/ef-cms-flexion#1761)
- [x] 14 toggle group buttons missing hover state (Kris ustaxcourt/ef-cms-flexion#1777  )
- [x] 15 Side by side boxes should top align and tabs sit above that in horizontal plane. Currently tabs are aligning with the doc (Cody ustaxcourt/ef-cms-flexion#1765)
- [x] 16 Add Message (under Complete) needs correct styling for "optional" (Kris ustaxcourt/ef-cms-flexion#1769)
- [x] 17 Blue background for H3 tabs isn't extending all the way to the right - there's a weird gray box sitting behind it (Kris ustaxcourt/ef-cms-flexion#1760)
- [x] 18 Serve to IRS button should right align with PDF box (Kris ustaxcourt/ef-cms-flexion#1760)
- [x] 19 Update disabled style of "Select Recipient" dropdown on Sent to toggle group button in Messages tab (Kris ustaxcourt/ef-cms-flexion#1788)
- [x] 20 SG - divider line between messages under View History needs to be bg-base-lighter (Rachael ustaxcourt/ef-cms-flexion#1784)
- [x] 21 SG - completed messages- text needs to be updated to base color
- [x] 22 SG - completed message card - border should be bg-base-lighter 
- [x] 23 in case header, space between docket number and case status label should be 15px  (Matt ustaxcourt/ef-cms-flexion#1763)
- [x] 24 in case header, space between caption and edit link should be 15px  (Matt ustaxcourt/ef-cms-flexion#1763)
- [x] 25 Document Info and Messages tab set should be 24px (Matt)
- [x] 26 Petition- Batched for IRS- doc detail view - space between label and read only field should be same as on case info tab (15px?) (William ustaxcourt/ef-cms-flexion#1779)
- [x] 27 The Batched for IRS + recall button needs to be styled completely on Petition Doc Detail - Batched for IRS screen (William ustaxcourt/ef-cms-flexion#1762)
- [x] ~~28  serve to irs button needs to right align to the pdf viewer chrome~~ (duplicate of 18)
- [x] 29 Parties Tab- increase padding above  v. commissioner line (Matt)
- [x] 30 Case Info tab - space between fields should be 20px (Rachael ustaxcourt/ef-cms-flexion#1807)
- [x] 31  Parties tab- when no party is selected - too much space between bottom of party type drop list  and bounding box bottom border - should be 20px (Rachael)
- [x] 32 Checkboxes and radios should have 1px border (see style guide) 
- [x] 33 Trial Location and Fee Payment ID labels too close to their respective fields
- [x] 34 Tab bounding box (general) should have 20px spacing between the last field and the border (Matt ustaxcourt/ef-cms-flexion#1775) 
- [x] 35 Radio buttons/check boxes should have hover state of 1px primary-darker
- [x] 36 Parties tab- styling of "optional" on field label should be bg-base, 15px, regular weight 
- [x] 37 Save success message next to save button should be #2e8540 success-green (Rachael)
- [x] 38 Align check box with text on Order for ownership disclosure statement under corporation and partnerships categories, Party Info tab (William ustaxcourt/ef-cms-flexion#1785)
- [x] 39 No period on "No file uploaded" for ODS in corp and partnerships categories, Party Info tab (Joe)
- [x] 40 Help text colors throughout the taxpayer categories on Party Info tab (Joe)
- [ ] ~41 (your name) vs (optional) applied inconsistently on C/O fields in several categories in Parry Info tab - @uxforgood do they make sense as-is or should we make them uniform? (Joe)~
- [x] 42 Update Fee Payment Date style to Internal Date Field on Petition QC page - Case Info (Rachael ustaxcourt/ef-cms-flexion#1783)
- [x] 43 Messages - the check icon next to Complete should be fas.fa-check-circle (Rachael ustaxcourt/ef-cms-flexion#1818)
(https://fontawesome.com/icons/check-circle?style=solid)
- [x] 44 Complete message - Need 40px spacing between Add Message field and Complete button (Rachael ustaxcourt/ef-cms-flexion#1814)
- [x] 45 Send Message- Decrease spacing between fields to 30px total - looks like there is 30px space (15 margin, 15 padding) on the field itself and another 30px bottom padding on the group (Rachael ustaxcourt/ef-cms-flexion#1818)
- [x] 46 F/u ustaxcourt/ef-cms#6503 - Completed message text should be #1b1b1b theme-color-ink (Rachael ustaxcourt/ef-cms-flexion#1814)
- [x] 47 F/U ustaxcourt/ef-cms#6509 - Batched for IRS label section (with Recall button) should bottom align with the H3 tabs. On this screen, the PDF and form sections are misaligned- need to top align (William ustaxcourt/ef-cms-flexion#1816)
- [x] 48 F/U ustaxcourt/ef-cms#6512 - Date Received looks like has 30px bottom on margin and on field set- need to decrease (should look like the Fee Payment Date field spacing) (Rachael ustaxcourt/ef-cms-flexion#1814)
- ~[ ] 49 F/U ustaxcourt/ef-cms#6517 - checkbox/radio hover state - looks like dev has 2px, should be 1px (Rachael)~ should be 2px
- [x] 50 - Parties tab - need to add 30px spacing between address fields (City, State, Zip, Phone number) -throughout (Rachael ustaxcourt/ef-cms-flexion#1814)
- [x] 51 F/U ustaxcourt/ef-cms#6521 - Still seeing period after “No file uploaded” (Natalie ustaxcourt/ef-cms-flexion#1815)
- [x] 52 Parties Tab- Estate with Executor- need 10px spacing above helper text on “Title” field (Rachael ustaxcourt/ef-cms-flexion#1814)
- [x] 53 Parties Tab- Estate without Executor - In Care of Field needs spacing under label (Rachael ustaxcourt/ef-cms-flexion#1814)
- [x] 54 Remove dropshadow from global search box in header (#1815 Natalie)
- [x] 55 On document detail other than the Petition, the PDF iframe needs to align with the H3 tabs (Rachel)
- [x] 56 The space under Date Received need to be decreased - should be 30px (Rachel)
- [x] 57 Update spacing between label and helper text (Kristen ustaxcourt/ef-cms-flexion#1837)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
