### ISSUE TITLE
New Design: File an External Document Flow

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6846]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the External Document Flow.

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
* External Document Flow is  updated with newest changes to our style guide

## Tasks
- [x] 1: Margin between sections with H3 - file document form (Matt ustaxcourt/ef-cms-flexion#1786)
- [x] 2: Margin between sections with H3 - review (Matt ustaxcourt/ef-cms-flexion#1786)
- [x] 3: Wrap Frequently Used Docs in blue-container and hide after doc type is selected (Rachael ustaxcourt/ef-cms-flexion#1789)
- [x] 4: Add Card layout to Frequently Used Docs (Rachael ustaxcourt/ef-cms-flexion#1789)
- [x] 5: Document Icon should be black not blue (William ustaxcourt/ef-cms-flexion#1792)
- [x] 6: Remove "back" link above the docket number header (Matt ustaxcourt/ef-cms-flexion#1796)
- [x] 7: Docket number header blue background should span full width (Matt ustaxcourt/ef-cms-flexion#1796)
- [x] 8: Add space between the question mark icon and the text (in accordion) (William ustaxcourt/ef-cms-flexion#1792)
- [x] 9: File Document should be H1 (William ustaxcourt/ef-cms-flexion#1792)
- [x] 10: Accordion link needs hover state - text change to #1a4480 on hover added to style guide (Matt)
- [x] 11: Buttons should have 20px top margin (Rachael ustaxcourt/ef-cms-flexion#1791)
- [x] 12: Upload fields have odd border around them- on Chrome (Kris ustaxcourt/ef-cms-flexion#1799)
- [x] 13: Fields with helper text (upload document, who is filing) should have 10px between label and helper text (Rachael ustaxcourt/ef-cms-flexion#1804)
- [x]  14: Change green on file upload icon to #2e8540 (Rachael ustaxcourt/ef-cms-flexion#1794)
- [x] 15: Update field level error spacing - should be 15px below field (William ustaxcourt/ef-cms-flexion#1803)
- [x] 16: Update spacing in Cancel modal -see Figma (Kris ustaxcourt/ef-cms-flexion#1811)
- [x] 17: Update alert message on Review Page - icon color should be #ffbe2e; message header text should use H3 style (Rachael ustaxcourt/ef-cms-flexion#1802)
- [x] 18: on Review page, need 40px spacing above buttons (Rachael ustaxcourt/ef-cms-flexion#1797)
- [x] 19. Continue button needs 40px spacing above (Rachael ustaxcourt/ef-cms-flexion#1797)
- [x] 20: Review page, Edit link should be bottom aligned with section header (Rachael ustaxcourt/ef-cms-flexion#1800)
- [x] 21: Update spacing between "What Type of Document Are You Filing?", helper text below, and accordion button (Rachael ustaxcourt/ef-cms-flexion#1808)
- [x] 22: Accordion content styling updates (see Figma) (Rachael ustaxcourt/ef-cms-flexion#1810)

## Definition of Done
**Product Owner**
 - [ ] Acceptance criteria have been met
**UX**
  - [ ] Usability has been validated
