### ISSUE TITLE
New Design: File a Petition - "Before You Begin" Page

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6847]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the File a Petition - Before You Begin Page

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*File a Petition - Before You Begin Page is updated with newest changes to our style guide

## Tasks
- [x] 1. Update grid view (William ustaxcourt/ef-cms-flexion#1809)
- [x] 2. Update Icons (William ustaxcourt/ef-cms-flexion#1809)
- [x] 3. Top Bar Header (William ustaxcourt/ef-cms-flexion#1809)
- [x] 4. Mobile Layout (William ustaxcourt/ef-cms-flexion#1825)
- [x] 5 Replace PDF "Petition Filing Guide" version (Kristen ustaxcourt/ef-cms-flexion#1845)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
