### ISSUE TITLE
New Design: External User Dashboard and Error Pages

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6848]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update External User Dashboard and Error Pages

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*External User Dashboard and Error Pages is updated with newest changes to our style guide

## Tasks
- [x] 1 Update sidebar on petitioner dashboard - gray instead of blue box, separate Other Filing Options (Rachael ustaxcourt/ef-cms-flexion#1819)
- [x] 2 Change Start a New Case button to File a Petition with icon and align with table (Rachael ustaxcourt/ef-cms-flexion#1820)
- [x] 3 Update header of dashboard table (Rachael ustaxcourt/ef-cms-flexion#1823)
- [x] 4 Update Search for a Case box styling on practitioner dashboard (Rachael ustaxcourt/ef-cms-flexion#1823)
- [x] 5 Practitioner/petitioner dashboard view with no cases (Rachael ustaxcourt/ef-cms-flexion#1826)
- [x] 6 Change header to full width big blue header (Rachael ustaxcourt/ef-cms-flexion#1828)
- [x] 7 Error page updates (Rachael ustaxcourt/ef-cms-flexion#1836)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
