### ISSUE TITLE
New Design: Start a Case Form

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6849]
As a development team, in order to ensure our design is updated with the latest internal style guide, we need to update the Start a Case form

Figma File: https://www.figma.com/file/Z2MXE2BHNyNKK8rILSWkLCAX/USTC-For-devs?node-id=1927%3A0

## Acceptance Criteria
*Start a Case Form is updated with newest changes to our style guide

## Tasks

- [x] 1 Add blue header “File a Petition” (William ustaxcourt/ef-cms-flexion#1842)
- [x] 2 Set width of blue boxes to width of application (William ustaxcourt/ef-cms-flexion#1851)
- [x] 3 Address padding at bottom of blue boxes (William ustaxcourt/ef-cms-flexion#1854)
- [x] 4 “How do you want this case handled” intro paragraph width set to body-copy (Jojo ustaxcourt/ef-cms-flexion#1849)
- [x] 5 Small/regular accordion should also be full-width (Jojo)
- [x] 6 Body-copy should be used for “review your information” paragraph, “Select trial location” paragraph, and “review and sign” checkbox label (Jojo ustaxcourt/ef-cms-flexion#1849)
- [x] 7 Ensure correct font size and weights compared to figma (Cody)
- [x] 8 Green checkmark-dots for file uploads are correct size and shade of green (Jojo ustaxcourt/ef-cms-flexion#1850)
- [x] 9 Text area on "Your Case is Ready to Submit If..." should expand to 700px max width (currently at 68ex) (Natalie ustaxcourt/ef-cms-flexion#1852)
- [x] 10 Text for Review and Sign - add line height to that checkbox label for 24px and max width of 700px (this is true for any checkbox label that extends to 2 lines so can be a global change) (Natalie ustaxcourt/ef-cms-flexion#1852)
- [x] 11 Update title to "Tell us about your case" (William ustaxcourt/ef-cms-flexion#1854)
- [x] 12 Remove Question icon on accordion (William ustaxcourt/ef-cms-flexion#1854)
- [x] 13 Contacts header margin update (William ustaxcourt/ef-cms-flexion#1854)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met
**UX**
  - [x] Usability has been validated
