### ISSUE TITLE
Fix respondent association

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6854]
As an IRS attorney, when I file the first IRS document in a case, I need to be automatically associated with the case.

The IRS is the respondent in every Tax Court case.  After a case is started by a Petitioner, an IRS attorney will file an Answer or a motion in that case.  Upon the filing of the first IRS document in a particular case, the IRS attorney needs to be associated with the case.

## Pre-Conditions:
* A case has been started.
* IRS attorney can find the case by searching for the docket number.

## Acceptance Criteria:
* When an IRS attorney files the first IRS document (see note below), they are immediately associated to the case.
* Once associated with a case, the IRS attorney can see everything in the case
* Before association, the IRS attorney should be able to see documents in a case, but not open/access them.
* Once associated with the case, the IRS attorney's data is viewable to other parties and internal Court Users on the Case Info tab
* Once associated with a case, the case should show up on the IRS attorney's dashboard.
* Once the document is filed it is routed to docket for processing

## Notes:
* First IRS Document: Any IRS practitioner could eFile any document in a case that does not have an IRS practitioner already assigned to it. When the first responsive document is eFiled, if it is being eFiled by multiple counsel for respondent (multiple counsel have signed the document), the eFiler could indicate the other IRS practitioners by entering the Tax Court Bar# for each. Only valid, active, IRS practitioners could be added to the case.
* Kristen & Jessica should talk before any design work is done -- need to make sure we're accounting for association by filing 1st document as well as association by regular means (Entry of Appearance, Substitution of Counsel, etc.)

## Tasks:
- [x] 1 Update respondent dashboard view with side search box (Rachael ustaxcourt/ef-cms-flexion#2118)
- [x] 2 Add button to file first IRS doc/request access to case to case detail page header; disable linked documents in docket record before respondent is associated with case (Rachael ustaxcourt/ef-cms-flexion#2119)
- [x] 3 Update fileExternalDoc interactor to associate respondent when they file a document (William ustaxcourt/ef-cms-flexion#2128)
- [x] 4 Add hardcoded Respondent option to parties filing on file a doc form (Rachael ustaxcourt/ef-cms-flexion#2124)
- [x] 5 Show different doc type options on request access form based on user role (Rachael ustaxcourt/ef-cms-flexion#2127)
- [x] 6 Allow multiple respondents to be stored on the case, similar to the way practitioners are stored (William  ustaxcourt/ef-cms-flexion#2132)
- [x] 7 Refactor caseDetailHelper (Rachael, Kris ustaxcourt/ef-cms-flexion#2126)
- [x] 8 Fix bottom margin styling on sections on request access form (Rachael ustaxcourt/ef-cms-flexion#2129)
- [x] 9 Set partyRespondent to true by default for user role respondent on request access form (Rachael ustaxcourt/ef-cms-flexion#2130)
- [x] 10 Verify that association is checked for respondent to a case (William  ustaxcourt/ef-cms-flexion#2132)
- [x] 11 Once associated with a case, the case should show up on the IRS attorney's dashboard. (William ustaxcourt/ef-cms-flexion#2141) 
- [x] 12 Journey tests for respondent filing first doc/requesting access to case (Rachael ustaxcourt/ef-cms-flexion#2144)

## Definition of Done
**Product Owner**
 - [x] Acceptance criteria have been met

**UX**
  - [x] Usability has been validated

**Engineering**
  - [x] Field level and page level validation errors (front-end and server side) integrated and functioning
  - [x] Run the browser stack scripts to verify that application is usable in Chrome, Firefox, Safari, Edge and Internet Explorer (external only) 
  - [x] No errors reported in manual a11y testing
  - [x] All new functionality verified to work with keyboard and osx voiceover
  - [x] Code refactored for clarity and to remove any known technical debt 
  - [x]  README, other appropriate docs, and swagger/APIs fully updated - all code functions documented with jsdocs
  - [x] UI should be touch optimized and responsive for external only(functions on supported mobile devices and optimized for screen sizes as required)
  - [x] Library/module dependencies are up-to-date and are at the latest resolvable version
  - [x] Code is deployed to DEV
  - [x] Errors in sonarcloud are fixed (https://sonarcloud.io/organizations/flexion-github/projects)
  - [x] Alerting and monitoring for new functionality in place and successfully exercised
