### ISSUE TITLE
Petitions Clerk: Direct Scan of Paper filings, preview and associate with case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6856]
As a Petitions Clerk, in order to make sure the right document gets uploaded, I need the ability to scan paper documents directly into the system and review the document before it is associated with a case/docket entry.

The Court will continue to receive paper Petitions.  As a result, Petitions Clerks will need the ability to get those paper documents into the system.  The idea that a clerk would scan, save, and upload the document leaves a lot of room for error that the wrong document will be uploaded.  Plus, it involves multiple steps.  To avoid this, the Petitions Clerks will need the ability to directly scan a document into the system (#1066) and be provided a review feature (#1566) before doc is associated with case/docket entry

## Pre-Conditions:
* Petitions Clerk has paper filing

## Acceptance Criteria:
* we would need to apply a cover sheet
* Petitions Clerk has the ability to scan paper documents directly into the system without having to perform a separate scan, save and upload function.
* The Petitions Clerk can see that the document has been scanned successfully into the system
* Petitions Clerk can preview the content of the document that was uploaded to confirm it's correct
* Petitions Clerk can delete the document if it's incorrect or scanned poorly
* upon submission, scans become associated with the case
* Once associated with the case, the scanned petition is available for the Petitions Clerk to start the QC process. 
* ~ Remove scan button once the scan is complete. we're going to keep this button for now~
* Reduce chances of user accidentally clearing a scan

## Notes:
* ~should we include CLAM AV virus scans for internal users as well? no~
* Some documents require multiple scans (more than 50 pages) to create one document
* Design note 6/10/19 - consider removing scan button once the document has been uploaded

## Tasks:
In Trello: https://trello.com/b/hCZ0JD3v/efcms-one-team

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written (Jojo ustaxcourt/ef-cms-flexion#2558)

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning (Cody ustaxcourt/ef-cms-flexion#2596)
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt ustaxcourt/ef-cms-flexion#2582, ustaxcourt/ef-cms-flexion#2592)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt ustaxcourt/ef-cms-flexion#2631)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Matt)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (JoJo ustaxcourt/ef-cms-flexion#2630)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt ustaxcourt/ef-cms-flexion#2600)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt ustaxcourt/ef-cms-flexion#2594)
 - [x] Code refactored for clarity and to remove any known technical debt (Cody ustaxcourt/ef-cms-flexion#2596)
 - [x] Deployed to the dev environment
