### ISSUE TITLE
Docket Clerk: Direct scan paper filing, preview, then associate with case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6857]
As a Docket Clerk, in order to make sure the right document gets uploaded, I need the ability to scan paper documents directly into the system and review the document before it is associated with a case/docket entry.

The Court will continue to receive paper filings.  As a result, Docket Clerks will need the ability to get those paper documents into the system.  The idea that a Docket clerk would scan, save, and upload the document leaves a lot of room for error that the wrong document will be uploaded.  Plus, it involves multiple steps.  To avoid this, the Docket Clerks will need the ability to directly scan a document into the system (#1066) and be provided a review feature (#1566) before doc is associated with case/docket entry

## Pre-Conditions:
* Docket Clerk has received a paper filing from a party in a case
* A case exists in the system for the party submitting the external filing

## Acceptance Criteria:
* Docket Clerk has the ability to scan paper documents directly into the system without having to perform a separate scan, save and upload function. 
* Docket Clerk can see that the document has been scanned successfully into the system (before it's added to the docket record)
* Docket Clerk can  preview the content of the document that was uploaded to confirm it's correct (before it's added to the docket record)
* Docket clerk can delete the document if it's incorrect or scanned poorly (before it's added to the docket record)
* A cover sheet should be added to the document before it's added to the Docket Record
* Docket clerk can add the scan to the docket entry when creating the docket entry
* Once added to the docket record, the scanned document is available for the Docket Clerk to view
* New docket entries (with a document) appear in the My and Section Document QC Processed tabs
* Reduce chances of user accidentally clearing a scan

## Notes:
* Functionality for this story is tied to https://github.com/flexion/ef-cms/issues/1895, and may be under development.
* ~Should we include CLAM AV scans for internal users as well?~ No
* Some documents require multiple scans (more than 50 pages) to create one document
* Design note 6/10/19 - consider removing scan button once the document has been uploaded
* This story is intended to capture scanning a document and creating a docket entry all at the same time. 
 The ability to scan/upload a document after the docket entry is created is handled in another story ustaxcourt/ef-cms#6834

## Tasks
- [x] Update/refactor view for Create Docket Entry (currently Add Document) (Cody, Matt, Jojo ustaxcourt/ef-cms-flexion#2656)
~- [ ] Validation for docket entry that does not include adding a document as required~ (This is handled in ustaxcourt/ef-cms#6834)
- [x] Add scanning/preview module to page (MOB together) (Cody, Matt, Jojo ustaxcourt/ef-cms-flexion#2656)
- [x] Update/refactor adding supporting/secondary documents 
- [x] Implement incomplete scan error handling if user has scanned 1 or more batches and tries to click "Finish" (Cody, Matt, Jojo ustaxcourt/ef-cms-flexion#2656)
- [x] Create Document QC entry for newly created docket entry

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning  (Joe)
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html - (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated - (Cody)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
