### ISSUE TITLE
Court User: Editing Trial Session details

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6859]
As a Court User, in order to make sure the trial session details are accurate, I need the ability to edit trial session details at any time before the date of the trial session.

## Pre-Conditions:
* A trial session has been created

## Acceptance Criteria:
* Court user can edit and save trial session details at any time before the date of the trial session
* after trial session date has passed, edit and delete functions are unavailable
* Court user can delete trial session at any time before it is automatically scheduled
* Changes should overwrite original details
*  If the Judge assigned to the trial session changes, the Judge associated (#3407) with each case on that trial session should automatically update to the new Judge assigned to the session 

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] create "edit trial session" endpoint (lambda, interactor, proxy) (Rachael ustaxcourt/ef-cms-flexion#3943)
 - [x] create 'delete trial session' endpoint (lambda, interactor, proxy) (Cody ustaxcourt/ef-cms-flexion#3944)
 - [x] create sequences to open "trial session edit" view, actual view to edit session, "trial session update" sequence (Rachael ustaxcourt/ef-cms-flexion#3949)
 - [x] "delete trial session" confirmation modal, delete trial session sequence (Kris ustaxcourt/ef-cms-flexion#3941)
 - [x] Add edit/delete buttons to view (Kris ustaxcourt/ef-cms-flexion#3941)
- [x] fix issues on trial session working copy (can't save trial statuses) (Rachael ustaxcourt/ef-cms-flexion#3949)

### Question:
 - [ ] should edit/delete buttons be concealed in some way AFTER trial session date has passed?

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
