### ISSUE TITLE
Closing a Trial Session

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6860]
As a court, so that we don't have to manually close every trial session, we need the trial session status to change to closed when certain criteria are present. 

## Acceptance Criteria
* A trial session should move from "Open" to "Closed" when the following criteria are present:
        * All cases on the trial session have been moved to inactive

Other AC:
* Add "Ability to filter sessions by All, Closed, Open or New" 
* All and Closed tab also need Session Type, Location and Judge filter
* Reconsider the judge's quick links on their dashboard (Jessica to touch base w/Judges on what's needed) - need to consider trial session calendar screen and how it relates to judges' dashboard.
* Trial sessions that have not been set need to be displayed in a separate tab (New)
* Once the calendar has been set, the trial session moves from New to Open
* Need ability in the New tab to filter by session type and location

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Not related to date
* Minimal logic in router

## Tasks
- [x] 1 Create full set of tabs for open, closed, all, new (Kris, Matt) - ustaxcourt/ef-cms-flexion#4334
- [x] 2 Create corresponding routes & sequences for each (Kris, Matt) - ustaxcourt/ef-cms-flexion#4338
~~- [ ] 3 update TrialSession entity STATUS_TYPES (?)~~
- [x] 4 Expose tab-sorting business logic with a simple test / method - ustaxcourt/ef-cms-flexion#4334
~~- [ ] 5 Update Trial Session status type once calendared~~
- [x] 6 sort Closed and All tabs by newest to oldest (Kris ustaxcourt/ef-cms-flexion#4346)
- [x] 7 update labels on trial session detail page for new/open/closed (Rachael ustaxcourt/ef-cms-flexion#4341)
- [x] 8 updated design for judge’s dashboard (Matt ustaxcourt/ef-cms-flexion#4349)
- [x] 9 update closed session detail page to only show Cases table (Rachael ustaxcourt/ef-cms-flexion#4341)
- [x] Add status column to ALL sessions table (Matt ustaxcourt/ef-cms-flexion#4349)
- [x] Fix sorting (set to opposite for each table view) (Matt ustaxcourt/ef-cms-flexion#4349)

Refactoring: 
- [x] Remove status from trial session entity (verify that this isn't used anywhere else) (Rachael ustaxcourt/ef-cms-flexion#4348)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt ustaxcourt/ef-cms-flexion#4359)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Matt ustaxcourt/ef-cms-flexion#4359)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
