### ISSUE TITLE
Court User: QC of Eligible Cases

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6862]
As a Court User, so that I can keep track of cases that require action before being scheduled for trial, I need the ability to mark which cases do not require further action.

## Pre-Conditions
* Multiple cases are ready for trial at a particular trial location (#1187)
* Calendar Clerk can see a list of cases that are ready for trial (#1192)

## Acceptance Criteria
* Among a list of cases that are ready/eligible for trial, the Calendar Clerk can denote which cases have been reviewed and do not require further action
* Before being scheduled for trial, the Calendar Clerk can come back to this list of eligible cases at any time and see which cases they've noted as not requiring further action
* Only cases that have been QC'd and checked off are eligible to be scheduled for trial when the automatic scheduling is run

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add field to case entity to store whether or not the case is QC’d for trial (Rachael ustaxcourt/ef-cms-flexion#4027)
- [x] 2 When setting the calendar for a trial session, filter out cases that have not been QC’d (Cody ustaxcourt/ef-cms-flexion#4036)
- [x] 3 Add QC Complete column with checkboxes to trial session eligible cases list (Rachael ustaxcourt/ef-cms-flexion#4028)
- [x] 4 Endpoint to mark a case as QC complete for trial (Rachael ustaxcourt/ef-cms-flexion#4031)
- [x] 5 Sequences and actions to mark a case as QC complete for trial (Rachael ustaxcourt/ef-cms-flexion#4033)
- [x] 6 Add Completed count to top of eligible cases table (Rachael ustaxcourt/ef-cms-flexion#4028)
- [x] 7 Only show the QC complete column for calendar clerks, and only give calendar clerks the permission for the endpoint to update it (Rachael ustaxcourt/ef-cms-flexion#4034)
- [x] 8 qcCompleteForTrial should be tied to a specific trial session - make it an object with key as the trialSessionId and value as the qcCompleteForTrial for that session (Rachael ustaxcourt/ef-cms-flexion#4032)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
