### ISSUE TITLE
Practitioner/IRS Attorney: Edit and display personal contact data

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6864]
As a Practitioner or IRS Attorney, in order to easily populate my contact information across my many cases when I have an address change, I need the ability to change it in one place and have it populate across all of my cases. 

## Pre-Conditions
* Practitioner or IRS Attorney have one or more cases in the system

## Acceptance Criteria
* Practitioner or IRS Attorney can edit and save their address and phone number in the system in one location
* Practitioner's or IRS Attorney's updated contact information displays in the system everywhere the data currently displays, including across all cases they're tied to
* A Notice is generated in every case the Practitioner or IRS Attorney is associated with and is tied to a new docket entry (#150)
* Notice of Change of Address (#2146) is generated when address is changed
* Notice of Change of Phone Number (#2146) is generated when phone number is changed
* Notice of Change of Address and Phone Number (#2146) is generated when both address and phone number have changed. 
* Associated event code should appear with each document in the docket record
* All notices need a cover sheet
* Notices need to generate a QC item in the Docket Section inbox
* Notices must contain the case caption, docket number, old contact information and new contact information
* Completed notice is saved as a PDF
* Practitioner/IRS attorney should be instructed that if they need to change their name or Bar information, they need to contact the Court.
* User should be able to perform function on mobile device
* Only populate notices to open cases
* Complete party name should be included in the concatenated document title on the docket record and the cover page

## Notes
* On the Notices: "Please change the contact information for [Name] on the records of the court." needs to display the Attorney / Practitioner name
* Add name to contact form (read only)

## Tasks
- [x] update seed data (Eric ustaxcourt/ef-cms-flexion#2913) 
- [x] create address view for the practitioner / atty home screens  (Eric ustaxcourt/ef-cms-flexion#2904)
- [x] create edit address screen or reuse another for address edits (Eric ustaxcourt/ef-cms-flexion#2913)
- [x] create user validator use case (Eric / Cody ustaxcourt/ef-cms-flexion#2916)
- [x] create update contact use case proxy (Cody)
- [x] create sequences and actions to connect use cases to views  (Cody ustaxcourt/ef-cms-flexion#2916)
- [x] create update practitioner / atty address use case: update user objects, update all active case 
metadata (Cody ustaxcourt/ef-cms-flexion#2907)
- [x] add update address pdf to docket records of active cases (Matt)
- [x] display success message (Cody ustaxcourt/ef-cms-flexion#2916)
- [x] reset user objects in dynamo in dev/staging (Eric/Cody)
- [x] apply presentation updates (Eric, Sarah)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
