### ISSUE TITLE
Draft state for orders

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6866]
As a Court User, so that I may have someone review my order before it is served on a party, I need the ability to save an in-progress order. 

## Pre-conditions
* Court users have the ability to create an order

## Acceptance Criteria
* Court user can save an in-progress order
* Court user can edit and save changes to an in-progress order
* Any court user can review an in-progress order that was created by another court user (preview PDF)
* Court user can save an in-progress order, return at a later date, continue drafting the order and save again
* Court user can change data that they previously entered in their draft order

* Note - that in the system's current state only a Petitions clerk has the "Create Order" button but this story should not be limited by permissions at all in terms of how it's implemented. All Court users should have the ability to interact with draft states

## Notes
* Need to discuss what to do if user applies a signature to a doc, sees an error, then wants to go back, correct and reapply signature. When does the document become a PDF?
* No version control needed. Only latest version of document should be retained (MVP)
* This story includes creation of draft documents tab, which is the space where signed stip decisions and orders will be held until they are linked to a docket entry and served. 
* Can user see an aggregated list of "in progress" orders or do they have to go back into that case first?
* Can user delete an in progress order?
* Can other users see the drafted order?
* Draft state for orders/decisions don't have work item

## Tasks
 - [x]  Add Draft Documents tab to case detail (Matt ustaxcourt/ef-cms-flexion#2969)
 - [x] "draft" state on document object (Matt ustaxcourt/ef-cms-flexion#3004)
 - [x]  Add draftDocuments array on formattedCaseDetail (Cody ustaxcourt/ef-cms-flexion#2992)
 - [x] Edit Proposed Stip Decision view (Cody ustaxcourt/ef-cms-flexion#2992)
 - [x] Edit Order / Decision view (Matt ustaxcourt/ef-cms-flexion#3004)
 - [x] Logic to generate an "edit" link (Cody ustaxcourt/ef-cms-flexion#2992)
 - [x] Add endpoint for deleting draft documents (Cody ustaxcourt/ef-cms-flexion#2980)
 - [x] Modal for deleting document (JoJo ustaxcourt/ef-cms-flexion#2986)
 - [x] ~Filings and Proceedings display in Draft Tab~ (removing per discussion with Kristen)
 - [x] Draft order Document Detail UI (Matt ustaxcourt/ef-cms-flexion#3011)
- [x] Update success message when order is created 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
