### ISSUE TITLE
Add Court Sections and Users to Dropdowns

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6871]
As a court user, so that I can assign a specific court user to something in the system, I need the ability to select a court user from a certain section.

## Acceptance Criteria
* Court sections and users are present in the system
* Court user can send message to another court user 
* Court users are present in all drop downs where they're required (messaging, calendaring, elsewhere?)
* "Senior Attorney" is replaced with "ADC" in the dropdowns
* User permissions are configured for each user group as defined by PO (Jessica to meet with UXers to define)

## Notes
* List of all Court Users by section: https://docs.google.com/spreadsheets/d/1o7IBYXQgFzMrInr6gn9yj1JqGJyPYJJSqi7Sw40CkeY/edit?usp=sharing
* Keep generic test users for testing

##Security Considerations
None at this time. Not adding actual users to system.

## Tasks
- [x] 1 Refactor to use constants for user roles throughout the app (https://trello.com/c/JSQjNR5P/190-use-constants-for-user-roles-throughout-the-app) (Rachael ustaxcourt/ef-cms-flexion#3370 ustaxcourt/ef-cms-flexion#3373)
- [x] 2 Replace “Senior Attorney” with “ADC” throughout the app (Rachael ustaxcourt/ef-cms-flexion#3376)
- [x] 3 Create CSV file of users to add (Cody)
- [x] 4 Create script to add users from CSV (Cody)
- [x] 5 Update permissions for users (TBD) (Rachael, Matt ustaxcourt/ef-cms-flexion#3385)
- [x] 6 Add local test users for the newly added sections (Rachael ustaxcourt/ef-cms-flexion#3378)
- [x] 7 Create homepages for all new users (Rachael, Matt ustaxcourt/ef-cms-flexion#3385)
- [x] 8 Pull in trial clerk section users on `SectionAssignmentsForm.jsx` - see comment (Matt ustaxcourt/ef-cms-flexion#3390)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael ustaxcourt/ef-cms-flexion#3427)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael ustaxcourt/ef-cms-flexion#3427)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael ustaxcourt/ef-cms-flexion#3427)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#3427)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment
