### ISSUE TITLE
Printable PDF of calendar/trial session list

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6873]
As a court user, so that I may work offline, I need the ability to print a PDF view of the calendar/trial session list. 

## Pre-Conditions
Calendar/trial session list exists in the system.

## Acceptance Criteria
* Court user can generate a printable / downloadable PDF of the calendar/trial session list with related session details
* Printed version of the calendar/trial session list is designed to print on 8.5.x11 paper
* Related session details include: 
   * City/State of Trial Session
   * Term
   * Session Type (Regular, Small, Hybrid, Special, Motion/Hearing)
   * Assignments -- Judge, Trial Clerk, Court Reporter, IRS Calendar Administrator
   * Courthouse Location
   * Notes
* List of cases should only include open cases by default sort order (oldest to newest by case filing date)
* Any internal user can print from within the trial session detail page (not the Judge's working copy)
* Subsequent pages should include page numbers, trial session info (city/session start date)

## Notes
* Date of print should be captured somewhere on the document ustaxcourt/ef-cms#6913 
* No mobile capability needed
* Possible design - only show print button after trial session has been "Set" -- no need to print eligible case list
* Page header for all but first page shall include document title / detail in the top left and page number / count [format: Page 2 of 3] in the top right. Other PDFs, such as the Docket Record, shall match this header. Orders shall match format but not in typeface / size.

## Tasks

- [x] a) UX Design complete and documented (Sarah - done)
- [x] 1) front end
  - [x] 2) add button to session list for print called "print trail calendar" (cody ustaxcourt/ef-cms-flexion#2757)
  - [x] 3) create a new page for viewing the printable trial session (similar to PrintableDocketRecord)  (cody ustaxcourt/ef-cms-flexion#2757)
  - [x] 4) create sequence for print trail calendar  (cody ustaxcourt/ef-cms-flexion#2757)
  - [x] 5) add a route for this print view which runs the sequence  (cody ustaxcourt/ef-cms-flexion#2757)
  - [x] 6) create action used for creating the PDF html (follow printDocketRecordAction example) (Cody & Joe ustaxcourt/ef-cms-flexion#2775)

- [x] 7) backend work (used already-existing endpoint from printable docket record)
  - [ ] ~8) create UI proxy for interactor~
  - [ ] ~9) add serverless endpoint in api (copy generateDocketRecordPdfLambda & other stuff related)~
  - [ ] ~10) create lambda~
  - [ ] ~11) create interactor for generating the pdf from html~

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo ustaxcourt/ef-cms-flexion#2817)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo ustaxcourt/ef-cms-flexion#2817)
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
