### ISSUE TITLE
UX - Random Design Updates

### ISSUE THREAD

**Issue by uxforgood** [ustaxcourt/ef-cms#6885]
Random Design Updates

## Acceptance Criteria

**Form Field Updates**
- [ ] Decrease width of Zip Code field 
- [ ] On Doc detail Doc Info tab, the state field should right align with the rest of the boxes

**Browser**
* ~~Consider adding helper text on browser-level message re: file size too big~~ (Removed, edge case) 
* Page title does not include docket number or document name. Unhelpful browsing history. See image in comments (SLR).
 ![image.png](https://images.zenhubusercontent.com/5be0bad045b0290c78fb7458/840a4e89-8648-49ac-94ad-819fd64360cb)

**Navigation**
- [ ]  Mobile view on global navigation -- menu should auto-close upon selection; ~~search icon should be next to search bar~~
- [ ] Tab state - should always reset to default tab on page load 

**External Parties Case Detail View**
- [ ] Remove / replace? the Petition Details card on Case Info tab for external users (petitioner, specifically) 

**Tables**
- [ ] Need empty state for all tables (see comment for text)
- [ ] Table row heights should be min 50 (currently 65)
- [ ] Update Filed By entries in Docket record (Petition shows as [Petitioner name]; subsequent entries show as [Petr. Petitioner's name]

**Hover States**
- [ ] Add hover state for page navigation on preview scanned pages and preview selected document during review modals

**Keyboard Navigation**
- [ ] bring back the focus styles for the tabs component throughout the application

Feedback to User
- [ ] add some kind of messaging/behavior after practitioner updates contact info to inform them it may take a while

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
~- [ ] 1 Decrease width of zip code field; this has been corrected on some forms and not others; size on File a Petition for external users is correct~ looks like this has already been taken care of
- [x] 2 On Doc detail Doc Info tab, the state field should right align with the rest of the boxes (Rachael ustaxcourt/ef-cms-flexion#3215)
- [x] 3 Add docket number and/or document name to page title where appropriate (Rachael ustaxcourt/ef-cms-flexion#3219)
- [x] 4 Mobile view on global navigation -- menu should auto-close upon selection (Rachael ustaxcourt/ef-cms-flexion#3222)
- [x] 5 Tab state - should always reset to default tab on page load (throughout the app) (Kris / William ustaxcourt/ef-cms-flexion#3224)
- [x] 6 Remove the Petition Details card on Case Info tab for all external users (see design in comments below) (Rachael ustaxcourt/ef-cms-flexion#3215)
- [x] 7 Table updates
  - [x] 7a Need empty state for all tables (see comment for text); some of these have been done, but double check them; they should all be body copy instead of h2/h3 (William ustaxcourt/ef-cms-flexion#3227 ustaxcourt/ef-cms-flexion#3229)
  - [x] 7b Table row heights should be min 50 (currently 65) (Kristen ustaxcourt/ef-cms-flexion#2808)
  - [x] 7c Update Filed By entries in Docket record (Petition shows as [Petitioner name]; subsequent entries show as [Petr. Petitioner's name]) - always use "Petr." before name (Rachael ustaxcourt/ef-cms-flexion#3225)
- [x] 8 Add hover state for prev/next buttons on scan preview pane (create case from paper) - same color as hover state on primary button (Rachael ustaxcourt/ef-cms-flexion#3215)
- [x] 9 Bring back the focus styles for the tabs component throughout the application (William ustaxcourt/ef-cms-flexion#3223)
- [x] 10 Add some kind of messaging/behavior after practitioner updates contact info to inform them it may take a while - see design in comments below (Rachael ustaxcourt/ef-cms-flexion#3215)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
