### ISSUE TITLE
Petitioner: Generation of Notice of Change of Address

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6886]
As the Court, in order to make sure that all contact information is properly memorialized on the docket record, whenever a Petitioner changes their address or phone number, notices needs to be automatically generated and filed in the relevant case.  

## Pre-Conditions:
* Petitioner changes their address or phone number within the system

## Acceptance Criteria:
* Notice of Change of Address is generated when address is changed
* Notice of Change of Telephone Number is generated when phone number is changed
* Notice of Change of Address and Telephone Number is generated when both address and phone number have changed. 
* Associated event code should appear with each document in the docket record
* Docket entries read <link>"Notice of [Change of Address / Change of Address and Telephone Number / Change of Telephone Number]"</link> "for [Contact Name]"
* Docket entry Filed By column shows the name of the user who made the change (for example, if a Practitioner made the change on behalf of their client, show the Practitioner's name in the Filed By column)
* All notices need a cover sheet
* Notices are tied to the docket entry created upon making the change (#150)
* Notices need to generate an unassigned QC item in the Docket Section inbox
* Notices must contain the case caption, docket number, document title, old contact information and new contact information
* Completed notice is saved as a PDF
* Restore success message on the case detail page after user changes their contact information in the UI

## Notes:
* The docket entry is already being created as part of ustaxcourt/ef-cms#6549. This story creates the document that is hyperlinked to that docket entry. The Document Name shall be linked and the "for [Contact Name]" portion shall be unlinked (use Additional Info 2 field)
* Wherever [Contact Name] is used, follow the same logic as the Contact Name display on the case info tab 
* New PDF does not have to match the existing form exactly (per Natalie 8/20)
* Do not include paragraph at the bottom, rule number, document version info (per Natalie 8/20)
* The scope of this story was extended to separate Address/Phone/Address and Phone versions of the PDF and standardize form content on 8/22/19
* All forms will now read "Please change the contact information for [caseName/Practitioner Name/Attorney Name] on the records of the Court."
* All forms will now use the section headers "Old Contact Information" and "New Contact Information"
* The Court's Notice of Change of Address form:
 [https://app.zenhub.com/files/152320868/87668902-f849-44c8-b79d-d628b02f5a39/download](https://app.zenhub.com/files/152320868/87668902-f849-44c8-b79d-d628b02f5a39/download) 

## Tasks:
 - [x]  HTML template for pdf generator (Matt)
 - [x]  Refactor pdf generation endpoint to be more generic (Cody)
 - [x]  Actions / interactors (Matt)
 - [x]  Case name in docket entry (Matt)
 - [x]  Generate cover sheet (Cody)
 - [x]  Generate QC item in the Docket Section inbox
 - [x]  Update filedBy (Matt)
 - [x]  Success message on save contact info

## Definition of Done (Updated 8-15-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable)

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
