### ISSUE TITLE
Epic 8 Calendaring: Clean-Up

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6887]
As a development team, so that we can ensure a good user experience, we need to perform some clean up items. 

## Acceptance Criteria
1. Fix "create a trial session" form to allow trial sessions to be created in summer (we need to create a Summer term -- this will likely only have Special sessions assigned to it, but since the Court has trial sessions in the summer (July & Aug) we definitely need a way to allow that) (Valid - need to do)
2. Judge Thornton's name is misspelled on the drop-down (Valid - need to do)
3. Update time field in Add Trial Session form to default to 10:00 am - with ability to edit Valid - need to do)
4. Confirm that if the time is set to something other than 10:00am, that it doesn't default back to 10:00am when another field is changed

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x]  1) Create Summer term (Matt ustaxcourt/ef-cms-flexion#4413)
 - [x]  2) Fix Judge Thornton's name spelling (Matt ustaxcourt/ef-cms-flexion#4413)
 - [x]  3) Update time field in Add Trial Session form to default to 10:00 am - with ability to edit Valid
 - [x]  4) Confirm that if the time is set to something other than 10:00am, that it doesn't default back to 10:00am when another field is changed

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
