### ISSUE TITLE
Petitioner: Edit email address

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6890]
As a Petitioner, in order to keep my contact information current with the Court and continue to receive service emails, I need the ability to update my email address.

Related to ustaxcourt/ef-cms-flexion#7406: Edit Practitioner's email

## Pre-Conditions: ##
* Petitioner exists in DAWSON with an email address

## Acceptance Criteria:
* Petitioner has the ability to edit his/her email address
* Petitioner is provided new credentials to access DAWSON with the new email address [See note below]
* When the email has changed, the petitioner is required to verify their new email address. 
* Petitioner is able to log-in and access their cases
   * Ensure that the petitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
   * Petitioner can eFile documents in cases
* Petitioner's service preference remains as electronic
* Petitioner receives service emails at the new service email address
* ~~Change generates a Notice of Change of Email Address (create as own user story)~~
* When user updates their email address, it updates in all the cases they're in. [Note: need to change the edit info from case level to account level]

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider whether we have to create and link a new Cognito account or whether Cognito may allow an admin to just change email address
* Consider having ability to edit info at a more global level
* We can customize the email user receives to verify their address.
https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/signing-up-users-in-your-app.html#verifying-when-users-change-their-email-or-phone-number

## Tasks
- [x] 1 Add My Account to menu dropdown for petitioners - Team mob ustaxcourt/ef-cms-flexion#7710
- [x] 2 Create My Account view for petitioners (probably reuse the one for practitioners) - Team mob ustaxcourt/ef-cms-flexion#7710
- [x] 3 Create Change Login & Service Email Address for petitioners (probably reuse the one for practitioners)  Team mob ustaxcourt/ef-cms-flexion#7712
- [x] 4 Add permissions in all interactors related to updating email for petitioners - Team mob  Team mob ustaxcourt/ef-cms-flexion#7712
- [x] 5 Display success message after submitting email change 
- [x] 6 Display pending email warning in header for petitioner
- [x] 7 Updates to Change Login & Service Email page - add Pending email address section if the user has already attempted to update their email - Team mob ustaxcourt/ef-cms-flexion#7713
- [x] 8 After email verification, use same behavior as practitioner flow - go to success page or instruction page depending on if user is logged in - Team mob ustaxcourt/ef-cms-flexion#7713
- [x] 9 Update email address in all cases for a petitioner when updating their email address - Team mob ustaxcourt/ef-cms-flexion#7713

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## User Menu
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a85c493d-4a8b-462f-8337-8dd36a6a52e2)
* Add My Account item 
* on select of My Account, route to My Account screen 


## My Account screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ee68743e-770f-4ac0-a185-aac5d8c235c0)

#### Login & Service Email Address 
* display current email 
* On click of Change Email, route to Change Email screen 


## Change Login & Contact Email Address 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6ba39d13-32de-4800-bdc1-b95d3132eab8)

**Current email address**
* display current email in read-only format 

#### Change Login & Contact Email 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display verify email modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* Old email is still valid
* New email is not yet valid 


## Verify Email Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2583b7aa-1fb8-4f07-80be-370616679531)

* On click of OK, route to dashboard with success message 


## My Account - Email verification required 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3436820d-b0e4-405f-bbab-3a0c98cb8974)

* app routes back to My Account with success message displayed

* display warning message under page header globally 

* old email still displays under Login & Service Email

## Change Login & Service Email Address  with pending email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a695b0fb-fc0e-45ec-a329-1eac959eeedc)

* Display warning message 

**Current email**
* display current (old) email in read-only format 

**Pending email**
* display new email in read-only format 

#### Change Login & Contact Email
* same functionality as before 


## User clicks Verify Email link while logged in 

* Route to Email Verified Success screen
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1d55a31b-a9af-4dce-8e0f-b3e4d1abcb36)

* old email is now invalid; user cannot log in with old email; service emails do not go to old email 
* new email is valid and user can log in with new email; service emails now go to new email 
* New email displays in UI on My Account > Login & Service Email and in all cases

## User clicks Verify Email link when not logged in 

* Route to "You Must be Logged in" screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6395cc5b-68b1-476a-a800-a44b8e0e53d8)

* old email is still valid and user can log in with old email
* user cannot log in with new email

**Comment by klohman** [comment]
## 2223 Test Scenarios 

#### A) Petitioner accesses My Account information 
* Login as petitioner 
* Click user menu and select My Account 
Expected results 
- [x] My Account is option in user menu
- [x] My Account screen displays Login & Service email card 

#### B) Petitioner accesses Change email screen  
* Login as petitioner 
* Click user menu and select My Account 
* Click Change Email link
Expected results 
- [x] App routes to Change Email screen 
- [x] current email displays 

#### 1) Petitioner updates email and saves form with valid email address 
* Login as practitioner - flexionustc+petitioner@gmail.com
* Update email address - flexionustc+petitionerupdated@gmail.com
* Click Save 
* Click OK
Expected results 
On click of Save 
- [x] Verify email modal displays 
- [x] On click of OK on modal, App routes to My Account with success message displayed 
- [x] Verification email is sent to new email 
- [x] Old email is still valid 
- [x] old email still displays under My Contact Information 
- [x] old email still displays under all cases
- [x] Global warning message displays 

#### 2) Petitioner updates email and saves form with invalid email address 
* Login as petitioner
* Update email address = notvalid@
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 3) Petitioner updates email and saves form with duplicate email address 
* Login as petitioner
* Update email address = petitioner1@example.com
* Re-enter matching email = petitioner1@example.com
* Click Save
Expected results 
- [x] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Petitioner updates email files a document before verifying new email 
* Login as petitioner - flexionustc+petitioner2@gmail.com
* Update email address - flexionustc+petitionerupdated2@gmail.com
* Go to case 
* File a Motion for New Trial 
Expected results 
- [x] Motion for New Trial is added to Docket Record 
- [x] New email address does not receives service email 
- [x] Old email does receives service email 

#### 5) Petitioner updates email and cannot login with new email address before verifying email
* Scenario 4 
* Login as petitioner with new email 
    * flexionustc+petitionerupdated2@gmail.com
Expected results 
- [x] User sees error on login for invalid credentials 

#### 6) Petitioner updates email and can login with old email address before verifying new email
* Scenario 4 
* Login as petitioner with old email 
    * flexionustc+petitioner2@gmail.com
Expected results 
- [x] User is able to login 
- [x] Global warning to verify email is displayed 
- [x] Old email displays under My Account > Login & Service email and in all cases

#### 7) Petitioner updates email and receives service for court-issued document at old email before verifying new email 
* Scenario 4 
* Login as docket clerk 
* Go to case 
    * Case has petitioner - flexionustc+petitioner2@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [x] order to show cause is added to Docket Record 
- [x] New email address does not receive service email 
    - flexionustc+petitionerupdated2@gmail.com
- [x] Old email receives service email 
    * flexionustc+petitioner2@gmail.com

#### 8) Petitioner updates email and enters non-matching email on confirmation 
* Login as petitioner
* Click Change Email
* Update email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save 
Expected results 
- [x] Error displays on email field -  “Email addresses do not match.”

#### 9) Petitioner verifies new email and logs in with new email 
* Scenario 4 
* Go to gmail 
* Click Verify Email link 
* Click login on success page
* Login as petitioner
    * flexionustc+petitionerupdated2@gmail.com
Expected results 
On click of verification link:
- [x] User is routed to Email Verified success page 
On login: 
- [x] Login is successful 
- [x] App displays new email on My Account> Login & Service email and in all associated cases 
- [x] Global warning message is not displayed

#### 10) Petitioner verifies new email and files a document 
* Scenario 9 
* Go to case
* File a Document 
    * Administrative Record 
* Submit document
Expected results 
- [x] Administrative Record is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 11) Practitioner verifies new email and receives service email for court-issued document 
* Scenario 9 
* Login as docket clerk 
* Go to case 
    * Case has petitioner - flexionustc+petitionerupdated2@gmail.com
* Create, sign and serve Decision 
Expected results 
- [x] Decision is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 12) Petitioner verifies new email and cannot log in with old email 
* Scenario 9 
* Login to system with old email - flexionustcpetitioner2@gmail.com
Expected results 
- [x] Login is unsuccessful and error message is displayed

#### 13) Petitioner tries to verify new email when not logged in 
* Login as petitioner - petitioner3@emample.com
* Change email - flexionustc+petitionerupdated3@gmail.com
* Log out of Dawson
* Go to gmail
* Click Verify link from email
Expected results 
- [x] User is routed to "You Must be Logged in" screen 
- [x] user can log in with old email 
- [x] user cannot log in with new email

**Comment by JessicaMarine** [comment]
.
