### ISSUE TITLE
Clean-Up: Signed Stipulated Decision

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6893]
## Pre-Conditions
* SDEC is available in the system

## Acceptance Criteria
* Remove cover page (permanently) when Proposed SDEC is put on canvas for signature

## Notes
* ideally complete before the demo on 9/27/2019
* once signed this document has no coversheet

## Tasks
 - [x] Load up PDF in preview without cover page for proposed stip decisions (Matt ustaxcourt/ef-cms-flexion#2962)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
