### ISSUE TITLE
Docket Clerk: Ability to Manually change case status 

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6899]
As a Docket Clerk, so that I may have the flexibility to change a case status, I need the ability to manually change a case status that has already been set. 

## Pre-Conditions
* A case exists in the system and has a case status.
* Complete ustaxcourt/ef-cms-flexion#3407 -- add Judge association to each case

## Acceptance Criteria
* Docket Clerk can manually change the status of the case [Note: this should be role based; Docket Clerks only]
* When status of case is changed, all logic tied to a system-generated status is applied to the manually generated status.
* Case must always have a case status

## Notes
* Since we don't have time to program automated case statuses for every document, we're allowing user to change manually. 
* A case always has a case status based on Court-defined rules. (#1594) See https://docs.google.com/document/d/1qhxASEKuzcPp99rTfCVkYbi6hVKS1pPPIgn5MvEWFPM/edit?usp=sharing
* Once a status is manually changed, all other actions follow the same logic
* In addition to case status, each case should also have a Judge associated with it at all times -- to be handled in a different story (#3407)

## Tasks
- [x] 1 Update case detail page - move Create Order button, add Edit Case button, remove Edit link next to case caption (Rachael ustaxcourt/ef-cms-flexion#3515)
- [x] 2 Modify Edit Case Caption modal to be the new Edit Case modal (Team mob ustaxcourt/ef-cms-flexion#3521)
  - [x] 2a Update validation, submit sequences for modal (Team mob ustaxcourt/ef-cms-flexion#3521)
- [x] 3 Create endpoint for submitting the modal - edit case? manually edit case? change case status? (serverless, lambda, interactor, proxy, persistence if needed) (Team mob ustaxcourt/ef-cms-flexion#3521)
- [x] 4 Add new case statuses to Case entity (Cody ustaxcourt/ef-cms-flexion#3514)
- [x] 5 Validation for Edit Case modal (Rachael, Matt ustaxcourt/ef-cms-flexion#3529)
- [x] 6 Show associated judge dropdown in Edit Case modal for certain statuses, and update associated judge on the case when needed (Team mob ustaxcourt/ef-cms-flexion#3524)
- [x] 7 Show alert on the modal when the case status is currently Calendared (Matt ustaxcourt/ef-cms-flexion#3526)
- [x] 8 Filter case status options in the modal - some should not be shown (see comments below) (Rachael, Matt ustaxcourt/ef-cms-flexion#3529)
- [x] 9 The current status of the case should be selected in the dropdown when the modal opens (Team mob ustaxcourt/ef-cms-flexion#3524)
- [x] 10 Show success message after modal is submitted and closed (Rachael, Matt ustaxcourt/ef-cms-flexion#3529)
- [x] 11 Restrict interactors to only docket clerks/clerk of court and hide Edit button for all other users (Rachael ustaxcourt/ef-cms-flexion#3533)
- [x] 12 Integration test (Rachael ustaxcourt/ef-cms-flexion#3535)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment
