### ISSUE TITLE
Docket Clerks: Service of Internal Documents (electronic)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6900]
As a Docket Clerk, in order to serve internal documents parties, I need the ability to electronically serve the documents to parties with an electronic service indicator.

## Pre-Conditions
* An internal document is ready to be served to parties in a case (docket entry is created, image linked to docket entry)

## Acceptance Criteria
* Docket clerk can electronically serve any court-issued document to parties that require electronic service
* Docket will need the ability to select between “Served” or “Entered and Served” for specific documents
   * The following documents will always be "Entered and Served"
      * Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
      * Order of Dismissal (Code = OD)
      * Order of Dismissal and Decision (Code = ODD)
      * Order and Decision (Code = OAD)
      * Decision (Code = DEC)
      * Stipulated Decision (Code = SDEC)
   * Generic Orders (Code = O) need the option to be "Served" or "Entered and Served"
   * Any other Order (see https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing) would always be "Served"
* Document is served electronically only to those parties who have an electronic service indicator (Per Rhonda - court-issued document are always served on all parties)
* When a document is served, either the “Served” or “Entered and Served” dates, is applied to the document 
* Whenever the following documents are "Entered and Served", the case status is automatically changed to `Closed`
      * Order of Dismissal for Lack of Jurisdiction (Code = ODJ)
      * Order of Dismissal (Code = OD)
      * Order of Dismissal and Decision (Code = ODD)
      * Order and Decision (Code = OAD)
      * Decision (Code = DEC)
      * Stipulated Decision (Code = SDEC)
* Service date and time, and who was served, are captured on docket record (Displays a "B" for "both")
* Parties receives an email notifying them to log into the system because there's been activity in the case.
* Parties can log in and see the court-issued document in the system
* The docket entry should link to the PDF
* Party can see served date on first page at the bottom center of the document

## Notes
* Cover pages are not added to court-issued documents

## Tasks
- [x] 1 Add Service Stamp field to court-issued docket entry form, entities, validation updates (Rachael ustaxcourt/ef-cms-flexion#3635)
  - [x] 1a Add served/entered and served doc type options to entity (Rachael ustaxcourt/ef-cms-flexion#3635)
- [x] 2 Create Serve to Parties modal, open/close sequences (Matt ustaxcourt/ef-cms-flexion#3631)
- [x] 3 Endpoint (interactor, serverless, lambda, proxy) for serving court-issued document (Matt, Cody ustaxcourt/ef-cms-flexion#3644)
  - [x] 3a Add Served/Entered and Served (based on doc type) stamp to bottom center of first page of PDF (Rachael ustaxcourt/ef-cms-flexion#3648)
  - [x] 3b Send email to parties when document is served (Matt ustaxcourt/ef-cms-flexion#3644, ustaxcourt/ef-cms-flexion#3658)
  - [x] 3c Case status automatically changes to “Closed” for some doc types - see list below (Matt ustaxcourt/ef-cms-flexion#3647)
- [x] 4 Sequences, actions to submit the modal and call endpoint (Cody)
  - [x] 4a Navigate to Case Detail page with success message
- [x] 5 Move in-progress work item to processed after document is served (Rachael ustaxcourt/ef-cms-flexion#3653)
- [x] 6 After a document is served, the docket clerk link to the document on the docket record/work queue should go to the document detail instead of edit docket entry (Cody ustaxcourt/ef-cms-flexion#3649)
- [x] 7 If a case is closed but was previously ready for trial, it should no longer show up on trial session eligible cases (Cody ustaxcourt/ef-cms-flexion#3652)
~- [ ] 8 If a case is closed but was previously calendared, it should be moved to the inactive cases for the trial session~ this is already working
- [x] 9 Update docket record view for unserved court-issued doc (see https://github.com/flexion/ef-cms/issues/2378#issuecomment-556058359) (Rachael ustaxcourt/ef-cms-flexion#3656)
- [x] 10 Can't create a user account with email - error during email verification step (Cody) 
~- [ ] 11 Allow signing of Proposed Stipulated Decisions for only docket clerks, ADC, judges, and chambers - new permission needed?~ holding this for a future story
- [x] 12 Remove high priority and block when a case is closed (Rachael ustaxcourt/ef-cms-flexion#3667)
- [x] 13 Signed Stipulated Decision in draft documents tab should go to the doc detail page with Add Docket Entry button and no Serve Document button - they should go through the same flow as any court-issued document (Rachael ustaxcourt/ef-cms-flexion#3670)
- [x] 14 Sign document is erroring/going to a blank screen (Rachael ustaxcourt/ef-cms-flexion#3670)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs (Matt)
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
