### ISSUE TITLE
Docket Clerk: Ability to add court-issued documents to the docket record

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6902]
## Pre-Conditions
* Court-issued documents exist in a draft state

## Acceptance Criteria
* Docket Clerk needs the ability to add Court-issued documents to the Docket Record [Note: This functionality should only exist for Docket]
* Docket Clerk will use unique codes for various types of Orders/Notices/Opinions/Decisions -- code will drive language generated for docket entry  (https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit?usp=sharing)
* Once Order is associated with docket entry, it is viewable by parties

## Notes
* After order is created, sent to docket, docket takes from draft tab, creates a docket entry and links the document to the docket entry; then service comes after this. 
* Similar to docket entry creation for external documents, with the exception of some fields
* Instead of "magic" document selector, more free form. Court can issue orders for anything, so there's no way to pre-populate it

## Tasks
- [x] 1 Update Draft Order screen (Matt ustaxcourt/ef-cms-flexion#3565)
- [x] 2 Create Add Docket Entry view for court-issued docs (Cody ustaxcourt/ef-cms-flexion#3562)
  - [x] 2a Dynamically generate concatenated docket entry on user input (Rachael ustaxcourt/ef-cms-flexion#3576)
  - [x] 2b Use typeahead document type selector (Cody ustaxcourt/ef-cms-flexion#3562)
  - [x] 2c Add document types (see document) to mapping generator (Cody ustaxcourt/ef-cms-flexion#3562)
  - [x] 2d Ensure additional fields are displayed per document type (Rachael ustaxcourt/ef-cms-flexion#3568)
  - [x] 2e Truncate concatenated docket entry after 2 lines and add attachments text if selected (Rachael ustaxcourt/ef-cms-flexion#3586)
- [x] 3 Create entity for non-standard document types (Rachael ustaxcourt/ef-cms-flexion#3552)
- [x] 4 Cancel modal / sequence / actions (Cody ustaxcourt/ef-cms-flexion#3562)
- [x] 5 Link Add Docket Entry sequence (Matt ustaxcourt/ef-cms-flexion#3567)
- [x] 6 Cancel Add Docket Entry sequence (Matt ustaxcourt/ef-cms-flexion#3567)
- [x] 7 Save docket entry sequence / actions (Matt ustaxcourt/ef-cms-flexion#3589)
- [x] 8 Save court issued docket entry interactor (Matt ustaxcourt/ef-cms-flexion#3585)
- [x] 9 Form validation (Rachael ustaxcourt/ef-cms-flexion#3578)
  - [x] 9a Select original order type when page is loaded (Rachael ustaxcourt/ef-cms-flexion#3578)
- [x] 10 Refactor isDraftDocument computed to exclude SAVED court-issued doc after docket entry is created (Team mob ustaxcourt/ef-cms-flexion#3594)
- [x] 11 Create `inProgress` state for newly created docket entry (Matt ustaxcourt/ef-cms-flexion#3592)
- [x] 12 Link to Edit Docket Entry page from docket record for in-progress court-issued doc (Team mob ustaxcourt/ef-cms-flexion#3594)
- [x] 13 Create endpoint for editing court-issued document docket entry (Team mob ustaxcourt/ef-cms-flexion#3600)
  - [x] 13a Call correct interactor for updating docket entry when submitting from the edit docket screen (Team mob ustaxcourt/ef-cms-flexion#3600)
- [x] 14 In-progress work item after docket entry is created (Team mob ustaxcourt/ef-cms-flexion#3600)
- [x] 15 (Attachment(s)) text is showing up twice on the created docket entry (Cody ustaxcourt/ef-cms-flexion#3599)
- [x] 16 Update document detail view for internal users other than docket clerks for saved court-issued docs (Rachael ustaxcourt/ef-cms-flexion#3601)
- [x] 17 Fix for Scenario 4a - "What is this order for" field is repopulated with "Order to do something" (Rachael ustaxcourt/ef-cms-flexion#3603)
- [x] 18 Fix for Scenario 12 - "Filed" date is blank (Rachael ustaxcourt/ef-cms-flexion#3603)
- [x] 19 Fix for Scenario 15 - Saved order link is not clickable (and the title looks wrong — templated) (Rachael ustaxcourt/ef-cms-flexion#3605)
- [x] 20 Cancel add docket entry modal not clearing (Rachael ustaxcourt/ef-cms-flexion#3605)
  - Create order
  - Go to draft documents and click on order
  - Add docket entry
  - Cancel - confirm cancel
  - Go back to order, create draft document
  - *Modal still displays* (but should not)
- [x] 21 When you change the document type - the text entered in “What is this order for” field persists- this should clear when a different document type is selected (Rachael ustaxcourt/ef-cms-flexion#3605)
- [x] 22 Link to Edit Docket from work item for docketclerk users; link to document detail for non-docketclerk users (Rachael ustaxcourt/ef-cms-flexion#3606)
- [x] 23 Currently logged-in user should be assigned to the work item created when the docket entry is created (and it should also be updated if the docket entry is updated) (Rachael ustaxcourt/ef-cms-flexion#3606)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt ustaxcourt/ef-cms-flexion#3629)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Rachael)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment
