### ISSUE TITLE
Revamp content of service emails for documents other than a Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6905]
As the Court, in order to make sure that the parties are getting sufficient information, the content of the service emails needs to be updated.

## Acceptance Criteria
* Service email for all other documents (other than a Petition) must include the following information:
   * Case name 
   * Docket Number
   * Document Name
   * Docket Index Entry No.
   * Document Type (Code)
   * Filing party
   * Served Date/Time
   * Hyperlink to log into the system
* Service email must also include the following machine readable data: [Note: needs to be added to design]

------------------------ COMPUTER-READABLE DATA -------------------
docketNumber: [docketNumber]
docketEntryNo: [XX]
documentId: [documentId]
eventCode: [eventCode]

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update service email content (Rachael ustaxcourt/ef-cms-flexion#5182)
- [x] 2 Send IRS superuser emails for non-petition initial case documents when served (Rachael ustaxcourt/ef-cms-flexion#5183)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [ ] Deployed to the stage environment
