### ISSUE TITLE
(16) Court-Issued Notices

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6906]
As a court user, so that parties in a case can be notified of pertinent information, I need the system to generate court-issued notices. 

## Acceptance Criteria
* System auto-generates a Notice of Change of Address
* System auto-generates a Notice of Receipt of Petition
* System auto-generates Notice of Docket Change
* System auto-generates Notice of Trial

All notices: 
* don't need a cover sheet
* are tied to the docket entry created upon making the change (#150)
* need to generate an unassigned QC item in the Docket Section inbox
* must contain the case caption, docket number, document title, old contact information and new contact information
* are saved as a PDF when completed

On the fence about adding this to MVP:
* Notice of Documents in the Nature of Evidence

## Notes
* NOFC, NOF and everything else under Calendar (but Notice of Trial) are not needed. 

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
