### ISSUE TITLE
Judge: Working copy of trial session

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6910]
As a Judge, in order to manage the cases scheduled on a trial session, I need the ability to access and manage the cases from a centralized report.

Once a Judge is assigned to a trial session, they will start reviewing the cases on that session.  They need a working copy of the trial session list (#1194) that they can work from.  That working copy is only viewable by the Judge and needs to be quickly and easily accessible.

## Pre-Conditions:
•	A trial session exists in the system
•	A Judge has been assigned to that trial session

## Acceptance Criteria:
•	 A Judge has a working copy of the trial session list (#1194) for each trial session the Judge is assigned to
•	The working copy of the trial session list should be quickly and easily accessible from the Judge’s dashboard (#1272)
•	The Judge should be able to access both upcoming and old working copies
*  Only the judge assigned has access to the working copy
* Judge should still be able to see the full "court copy" of the trial session

## Tasks:
- [x] 1 Verify that a judge is associated to a Trial Session (Rachael ustaxcourt/ef-cms-flexion#2709) 
- [x] 2 Link session summary links to Judge Session Working Copy of trial session — if assigned — else to standard trial session detail screen (also link to working copy from the main trial session list if the user is assigned to the session) (Rachael ustaxcourt/ef-cms-flexion#2709)
- [x] 3 Add “switch to working copy / session detail” link in header of Trial Session Detail / Trial Session Working Copy pages; separate routing! Only visible if session assigned to judge (Kris ustaxcourt/ef-cms-flexion#2711)
- [x] 4 Trial Session Working copy routing / page / init sequence / helper (William ustaxcourt/ef-cms-flexion#2702)
- [x] 5 Trial Session Working Copy Table (William ustaxcourt/ef-cms-flexion#2707)
	- [x] 5a Sort session working copy by newest docket number first
	- [x] 5b List petitioner counsels oldest to newest
	- [x] 5c List respondent counsel, oldest to newest

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Usability has been validated

**Team**
 - [x] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael ustaxcourt/ef-cms-flexion#2713)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#2713)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
