### ISSUE TITLE
Judge: Manage calendar call

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6911]
As a Judge, in order to manage the cases on a trial session during the Calendar Call, I need the ability to quickly add information and manipulate my working copy of the trial session list.

When a Judge arrives on site for a trial session, one of the first things he/she does is to have a "Calendar Call." During a calendar call, the parties for each case that is scheduled for the trial session is present in the court room. To perform the calendar call, the trial clerk calls before the Court every case that scheduled for the session. As each case is called, the parties tell the Judge the trial status (not to be confused with the case status) of the case and whether a trial is necessary. As each case is called, in addition to making notes about the case, the Judge also needs the ability to quickly mark the "trial status" of the case.  Some standard trial statuses are: Set for Trial, Dismissed, Continued, Rule 122, A Basis Reached, Settled, Recall, Taken Under Advisement.  The Judge needs the ability to sort and/or filter the list of cases on the trial session list based on "trial status".  The Judge also needs the ability to hide cases that they don't want to see any longer - this may be on an individual case-by-case basis or auto-hide based on "trial status".  If the Judge takes action on an item(case) in the list, they need the ability to easily move on to take action on the next item in the list, without losing one's place.

## Pre-Conditions
* A Judge has a working copy of a trial session list (#2565)

## Acceptance Criteria
* Judge needs the ability to assign a trial status (not to be confused with case status) to a case scheduled for a trial session
   * Ability to select a "trial status" from pre-defined statuses 
   * Trial Statuses: Set for Trial, Dismissed, Continued, Rule 122, A Basis Reached, Settled, Recall, Taken Under Advisement
* Judge needs the ability to sort and/or filter the cases on the working copy based on "trial status"
* Judge needs the ability to hide cases on the working copy that they don't want to see any longer based on "trial status"
* Judge needs to take action on an item on the working copy and easily move on to take action on the next case, without losing one's place
* Judge needs the ability to access/hyperlink into each case detail page from the working copy

## Tasks
- [x] 1 Add trial statuses to trial session or case entity? (Rachael, Kris ustaxcourt/ef-cms-flexion#2728)
- [x] 2 Add trial status dropdown to each case row on the working copy (William ustaxcourt/ef-cms-flexion#2727)
- [x] 3 Add filtering view to the working copy page (Rachael ustaxcourt/ef-cms-flexion#2736)
- [x] 4 Add filtering functionality to the computed (along with count of cases shown) (Rachael ustaxcourt/ef-cms-flexion#2752)
- [x] 5 Add sorting options to the UI on the working copy case table (William ustaxcourt/ef-cms-flexion#2727)
  - [x] 5a Add sorting functionality to the computed 
- [x] 6 Functionality for storing/updating trial session working copy (including sort/filter options selected and case trial statuses) (Rachael ustaxcourt/ef-cms-flexion#2731 ustaxcourt/ef-cms-flexion#2735)
- [x] 7 Create TrialSessionWorkingCopy entity (Rachael, Kris ustaxcourt/ef-cms-flexion#2728)
- [x] 8 Verify that a judge is associated with the session before allowing them to see the working copy (Rachael ustaxcourt/ef-cms-flexion#2721)

## Definition of Done (Updated 7-10-19)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Usability has been validated

**Team**
 - [ ] Test scenarios to meet all acceptance criteria have been written

**Engineering**
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (William ustaxcourt/ef-cms-flexion#2760)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachael ustaxcourt/ef-cms-flexion#2758)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (William ustaxcourt/ef-cms-flexion#2756)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
