### ISSUE TITLE
Court User: Search for Case by Docket Number or Keyword

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6937]
As a court user of the site, so that I can find cases within the system, I need a place where I can search for and view cases that meet my search criteria.

A Court user have various reasons that they may need to find a case within the system.  The person performing the search may have limited information.  They will need the ability to search for a case by docket number or by a key word search (name).  The system should return all cases matching the search.  If there are no cases that match the search criteria, the system should tell the user that "no results found".

## Acceptance Criteria
* Court users can perform search by a docket number (already done)
* Court users can perform search by keyword (Petitioner's name) search
* Court user should be able to add additional search term or filter by Petitioner's state
* System should display all cases that match the search criteria entered
* Results should display: Docket Number, Case Filing Date, and Case Name
* Search results should display in descending order (newest to oldest) by docket number
* Court user should be able to hyperlink into case through search results
* If no case(s) meet the search criteria, the system should notify the user that "no results found"
* Search results should display both open and closed cases

## Security Considerations
* Does this work make you nervous about privacy or security?
Flagging this story for security review for by CISO due to elastic search. Team has no current concerns. 
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] 1. Global Nav Search UI Updates (Kris ustaxcourt/ef-cms-flexion#2981)
   - [x] 1a. Sequence & actions connecting "Advanced" link to search page
 - [x] 2. Create Advanced Search Page (Rachael ustaxcourt/ef-cms-flexion#2981)
   - [x] 2a. Create route at `/search` (Rachael ustaxcourt/ef-cms-flexion#2981)
     - [x] note: for sake of testing and more, can we allow search terms in query strings in addition to state, such as `/search?name=Smith&yearStart=2017` (etc)? (Rachael ustaxcourt/ef-cms-flexion#2996)
   - [x] 2b. Create advanced search form for Domestic and International (Rachael ustaxcourt/ef-cms-flexion#2981)
   - [x] 2c. Create Search Results table & 'no matches' message (Rachael/Kris ustaxcourt/ef-cms-flexion#2990)
   - [x] 2d. Create computed for formatting search results (Rachael ustaxcourt/ef-cms-flexion#2993)
 - [x] 3. Update "Search for a Case" (CaseSearchBox) per figma (Rachael ustaxcourt/ef-cms-flexion#2973)
   - [x] 3a. If no match found, send to "Search Results" page with "no matches found" message and link to advanced (Rachael ustaxcourt/ef-cms-flexion#2973)
  - [x] 4 Search backend research (Rachael)
  - [x] 5 validate advanced search form (Kris ustaxcourt/ef-cms-flexion#2998)
  - [x] 6 default to United States in advanced search form (Rachael ustaxcourt/ef-cms-flexion#3007)
  - [x] 7 hide state field on advanced search form when international country type is selected (Rachael ustaxcourt/ef-cms-flexion#3007)
  - [x] 8 in the search results table, display only the petitioner name(s) and state which match the user's search - discussion with Kristen 9/9: we're going to show both petitioners and both states in the table (if they are different) (Rachael ustaxcourt/ef-cms-flexion#3018) 
  - [x] 9 "load more" functionality when there are more than 25 results (set this to 5 for testing) (Rachael ustaxcourt/ef-cms-flexion#3021)
  - [x] 10 research other search solutions
  - [x] 11 Use DynamoDB streams to populate ElasticSearch index for searching (Team mob ustaxcourt/ef-cms-flexion#3112)
  - [x] 12 Fix year filed search (Rachael ustaxcourt/ef-cms-flexion#3139)
  - [x] 13 Fix credentials issue with search endpoint on us-west-1 (Team mob ustaxcourt/ef-cms-flexion#3164)
  - [x] 14 Change processStreamRecordsInteractor for loop await to a promise.all (possibly) (Rachael ustaxcourt/ef-cms-flexion#3157)

## Notes:
* The Court's current search functionality can be found at: https://www.ustaxcourt.gov/docket.htm
* For docket number search:
   * Make sure inclusion of leading zeros does not prevent results
   * Make sure inclusion of suffix does not prevent results
* This story does not include the "public" search -- that will be handled in ustaxcourt/ef-cms#6938

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
