### ISSUE TITLE
Member of the Public: Perform Case Search

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6938]
As a member of the public, in order to locate the information I am looking for, I need the ability to search for cases by keyword & docket number.

## Pre-requiste:
* Member of the public (unauthenticated user or authenticated) comes to the site

## Acceptance criteria:
* Member of the public is able to perform a keyword & docket number search (same as ustaxcourt/ef-cms-flexion#2828)
* Consider including some additional instructional text re: docket number format and clearing docket # when clearing search.  Add whatever design changes are made to internal search as well.
* Only return data that's in the table, nothing else

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Decide if we should use a separate elasticsearch instance (if so, set up) - or maybe a decorator for the response? use current ES instance for now, and we can decide this later (Discussed 11/26/19 - decided on using same elasticsearch instance and index for now unless we can find a compelling reason not to)
- [x] 2 Endpoint for public search (interactor, serverless - separate stack for public, proxy, lambda) (Matt ustaxcourt/ef-cms-flexion#3706)
- [x] 3 Update search form view and include on public search page (Rachael ustaxcourt/ef-cms-flexion#3707)
  - [x] 3a Mobile view for search form and results (Cody)
  - [x] 3b Separate sequences and actions for public search
- [x] 4 Remove search capabilities completely for petitioner role (Cody ustaxcourt/ef-cms-flexion#3703)
- [x] 5 When user hits search on name or docket number in advanced search, the global search in the header should be cleared of any inputs (authed app) (Cody)
- [x] 6 Add router to public build and stub case detail page (Cody)

## Notes: 
* This story is intended to include development of the public-facing part of the system. 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael ustaxcourt/ef-cms-flexion#3730)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael ustaxcourt/ef-cms-flexion#3730)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
