### ISSUE TITLE
Court users: Ability to Generate Order/Decision in any case at any time

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6939]
As a Court User, in order to easily generate an Order/Decision whenever I need to, I need the ability to generate an Order/Decision in any case at any time.

## Pre-Conditions
Internal User is in a case.

## Acceptance Criteria
* All Court Users (Petitions, Docket, Judges, Sr. Attorney) need the ability to generate an Order/Decision in any case at any time.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider a toolbar for users.

## Tasks
 - [x]  Add create order button for all court user types (Matt ustaxcourt/ef-cms-flexion#3048)
 - [x]  Ensure `CREATE_COURT_ISSUED_ORDER` exists on court user types (Matt ustaxcourt/ef-cms-flexion#3048)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
