### ISSUE TITLE
Court Users: Ability to sign a court-issued document

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6940]
As a Court User, in order to easily sign a document whenever I need to, I need the ability to apply a signature to a document in any case at any time.

## Pre-Conditions
Internal User is in a case.

## Acceptance Criteria
* All Court Users need the ability to apply a signature to court-issued document and stipulated decisions while it's being created or in draft state
* Court User can reapply the signature if they placed it incorrectly
* Court User can cancel signature process
* Court User can preview the document with the signature
* Case services (docket, petitions, calendar, sr attorneys) have access to only the Chief Judge's signature
* Chambers has access to only their Judge's signature
* All signed documents should end up in the Draft folder
* Sending a message with the signed document is optional (change signed stip message to optional as well)
* User has the ability to edit the original document and reapply the signature

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the existing system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* We need to retain the original draft of the document so the user has the ability to edit the doc without a signature.

## Tasks
 - [x]  Refactor PDFSigner Component (Matt ustaxcourt/ef-cms-flexion#3183)
 - [x]  Load order into signer (Matt ustaxcourt/ef-cms-flexion#3194)
 - [x]  Save signed order (Matt)
 - [x]  Add signature added column to draft docs table (Cody ustaxcourt/ef-cms-flexion#3178)
 - [x] Editing this document - remove signature modal (Cody ustaxcourt/ef-cms-flexion#3186)
 - [x] Remove signature on document details page, button and modal (Cody)
 - [x] Apply signature button on doc detail page (Cody)
 - [x] Signature added alert message

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Jojo ustaxcourt/ef-cms-flexion#3226)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Cody ustaxcourt/ef-cms-flexion#3211)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Jojo ustaxcourt/ef-cms-flexion#3210)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo ustaxcourt/ef-cms-flexion#3210)
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
