### ISSUE TITLE
Clean-Up: Random Design Items (Must be Done by 9/27)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6941]
As a Judge, in order to know which case something is in reference to, I need to have the case name displayed on my message boxes.

## Acceptance Criteria
* Display Case Name in all user's Message Inbox and Message Outbox
* Display Case Name on Judge's Message Quick-link on Dashboard
* Display Case Name on Aggregate Deadline result table
* Update "Received" column label in all QC boxes to "Filed" 
* Update sort order on document and message queues (for Docket and Petition)
    - Document QC / Inbox - Filed date - oldest to newest (NEED to FIX)
    - Document QC / Batched - Filed date - oldest to newest (NEED to FIX)
    - Message Inbox - oldest to newest - Filed date (NEED TO FIX)
* Add empty states to Judge's trial session and messages on dashboard (see screenshot below)
* Update case caption to case name - on session info page for each trial session

## Tasks
- [x] add empty states to trial session summary (Jojo ustaxcourt/ef-cms-flexion#3096)
- [x] fix sorting on document qc / message queues (Jojo ustaxcourt/ef-cms-flexion#3098)
- [x] update "received" column to "filed" (Jojo ustaxcourt/ef-cms-flexion#3098)
- [x] Display Case Name in all user's Message Inbox and Message Outbox (Jojo ustaxcourt/ef-cms-flexion#3107)
- [x] Display Case Name on Judge's Message Quick-link on Dashboard (Cody ustaxcourt/ef-cms-flexion#3107)
- [x] Display Case Name on Aggregate Deadline result table (Jojo ustaxcourt/ef-cms-flexion#3107)
- [x] Update case caption to case name - on session info page for each trial session (Cody ustaxcourt/ef-cms-flexion#3107)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Jojo ustaxcourt/ef-cms-flexion#3110)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
