### ISSUE TITLE
UX Usability Tests

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6943]
On September 17-19, 2019, the UX team conducted on-site usability tests with various user groups: Petitions, Docket, Calendar, Judges, IRS and Petitioners. https://docs.google.com/presentation/d/1dRmjUKiWYvdZAgxsXNvnXT_JGm8_H_PQey_u7oEIsVM/edit?usp=sharing

The output of those tests are captured here.

#### ACCEPTANCE CRITERIA: New MVP Recommendations: 
* [x] 1) Add case status, sender to Judge’s messages inbox (MVP - New)- (Amy) (Matt ustaxcourt/ef-cms-flexion#3228)
* [x] 2) Add Application for Waiver of Filing Fee as document included during case creation (MVP -New)- (Amy) (Matt ustaxcourt/ef-cms-flexion#3232)
* [x] 3) Add “Batched By” information to the Petition QC Section Served tab (MVP - New) - (Amy) (Cody ustaxcourt/ef-cms-flexion#3234)
* [x] 4) Update language and priority of the “Add Batch” action; options include updating language to “Start Scan” or “Add Document”, changing the style to a primary button, co-locating the action with the scan selector (MVP - New) - (Amy) (Cody ustaxcourt/ef-cms-flexion#3234)
* [x] 6) Update language and consider changing visual treatment of the session detail toggle to clarify that this will open the official (complete) trial session case list (MVP - New) - (Kristen) (Cody ustaxcourt/ef-cms-flexion#3235)
* [x] 7) Include printable receipt for all document filings, with unique identifier (MVP - New) - (Kristen) (Matt)
* [x] 8) Add helper text regarding typeahead to Document Type field (MVP - New) - (Kristen) (Cody ustaxcourt/ef-cms-flexion#3243)
* [x] 10) Change the “Additional Info” fields on the Add Docket Form to text area fields to allow more visible characters (MVP- New) - No design (Rachael ustaxcourt/ef-cms-flexion#3246)

BELOW NOT IN THIS STORY________

#### MVP - New Stories Needed
* Additional testing for filing a petition with pro-se petitioners (#3286)
* Update the list of trial statuses to include statuses that are meaningful and beneficial to judges prior to calendar call (#3287)
* Consider a redesign of the Case Detail page after core functionality is implemented (#3288)
* Add functionality for flatbed and two-sided scanning (MVP- New) - No design (#3290)
* Redesign message view on Document Detail screen to prioritize the selected message; allow access to other user messages as a secondary action (#3306)

#### MVP - Add to Existing Stories 
* Consider wayfinding queues for workflows with deeper structures; considering breadcrumbs, in-app “Back” functionality, etc. (#1925)
* Add indicator for docket entries that are awaiting QC; these could be treated the same or similar to   incomplete docket entries ( ustaxcourt/ef-cms#6777)
* Allow users to mark if a case has been reviewed and is ready to set for trial; show indicator cases that have been reviewed versus cases that are awaiting review (#1925)
* Allow users to remove cases that should not be set for trial from the eligible cases list; this could be automated based on case status (#1188, ustaxcourt/ef-cms#6805)
* Allow visibility into when trial notices should/will be sent, and indicators for sessions that have been issued notices  (#1193)

#### Post-MVP - New Stories  (#3291)
* Add tooltip for icons (Post-MVP - New Story)
* Consider draft-state/in-progress state for petitions where QC has been updated (Post-MVP - New Story)
* Add ability to sort messages by read/unread (Post-MVP)
* Add direct “Reply” ability to messages (Post-MVP)
* Retain data in contact information fields when party type is changed (Post-MVP)
* Add a general summary screen with all petition information (and orders needed) prior to adding to batch (Post-MVP) 
* Add details on what is included in the petition batch: other documents included with petition, number of pages within each document (Post-MVP)
* Update the scan review panel to show a scrollable list of thumbnails for scanned pages (Post-MVP)
* Add ability for user to enter the expected number of pages a scan should contain (to verify the scan is complete) (Post-MVP)
* Investigate need for multiple document scans and individual page deletion/replacement. While this was expressed as a concern by all users,  their stated QC process does not indicate an actual need for these features. (Ongoing- Post-MVP) 
* Consider adding the timeliness date (date the petition was due) along with the IRS Notice date (Post-MVP)
* Add additional sort and filter options for the docket record (Post-MVP)
* Add tooltip for icons (Post-MVP)
* Allow users to more easily navigate between documents on the docket record, without having to go back to the Case Detail and select another document (Post-MVP)
* Add known court addresses to database to support prepopulation of trial locations (Post-MVP)
* Provide easy access to court contact information for external users (Post-MVP) 
* Add service information where relevant in the File a Document form; consider including it with the filing parties or COS (Post-MVP)
* Include additional instructions around supporting documents on File a Document form  for external users (Post-MVP) 

#### Post- MVP - Add to Existing Stories 
* Include pending motions on Judge’s Dashboard (#2764)
* Allow users to customize the Working Copy by additional sort and filter options (#2767)
*Allow judge users to select their note privacy preferences and opt in/opt out of sharing notes with other users (#338)
* Indicate on external dashboard  if a case has deadlines and if case has been set for trial (#534)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
