### ISSUE TITLE
Court User: Adding a case to an "upcoming" not-yet Calendared trial session

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6948]
As a Court User, in order to comply with a Judge's instructions, I need the ability to manually add a case to an "upcoming" not-yet calendared trial session.

There are occasions where a Judge will issue an Order directing a case to be calendared on a future calendar that has been identified, but not yet "cut".  The Court needs the ability to add a case to an "upcoming" not-yet calendared session.

## Pre-Conditions: ##
* Trial session exists in the system but has not yet been cut/automatically scheduled -- still in "upcoming" status

## Acceptance Criteria: ##
* Court User has the ability to manually add a case to an "upcoming" not-yet calendared trial session
* Case remains added to the trial session after the session is automatically scheduled regardless if the case would otherwise have been included
* Case can be added (and changed to Calendared) when the session is set, but we need to make sure that it doesn't get picked up on any intervening trial session as eligible

## Tasks: ##
- [x] 1 Add hint to modal (Matt ustaxcourt/ef-cms-flexion#3430)
- [x] 2 Refactor interactor to allow an uncalendared trial session to be set for case (Matt ustaxcourt/ef-cms-flexion#3430)
- [x] 3 Ensure case is in eligible cases for uncalendared session, and no others (Matt ustaxcourt/ef-cms-flexion#3430)
- [x] 4 Create `Trial - Scheduled` card layout for the trial session card on case detail case info tab (Rachael ustaxcourt/ef-cms-flexion#3436) 
- [x] 5 Do not set cases to calendared status when they're manually added if the trial session is not calendared (Rachael ustaxcourt/ef-cms-flexion#3436)
- [x] 6 If a case becomes eligible after it has already been manually added, it should not be shown twice in the eligible case list (don't create the trial sort records) (Rachael ustaxcourt/ef-cms-flexion#3436)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
