### ISSUE TITLE
Clean-Up: Redesign Case Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6951]
Consider a redesign of the Case Detail page (internal and for parties) after core functionality is implemented

## Acceptance Criteria ##
* Revisit design for case detail page
* Combine Due Dates and Actions Needed

## Tasks
- [x] 1 Tab component addition for top-level tabs (Rachael ustaxcourt/ef-cms-flexion#3849)
- [x] 2 Case detail header view/button placement updates (Rachael, Kris ustaxcourt/ef-cms-flexion#3858)
- [x] 3 Case detail internal view updates (Rachael ustaxcourt/ef-cms-flexion#3849)
- [x] 4 Case detail external view updates (Rachael ustaxcourt/ef-cms-flexion#3850)
- [x] 5 Case detail public view updates (Rachael, Kris ustaxcourt/ef-cms-flexion#3858)
- [x] 6 Misc cleanup (add header to deadlines table, move docket record sort, move File Document button, etc) (Rachael ustaxcourt/ef-cms-flexion#3865 ustaxcourt/ef-cms-flexion#3867)
- [x] 7 Mobile design updates (Rachael, Kris ustaxcourt/ef-cms-flexion#3873)
- [x] 8 UX review comments (Rachael ustaxcourt/ef-cms-flexion#3875)
  - [x] Update all table header labels to sentence case 
  - [x] Deadlines - change “Remove” to “Delete” and change icon and placement of Edit and Delete buttons (match Draft Documents) 
  - [x] Pending Report - get rid of “remove” header in table 
  - [x] On hover state on Tabs - thicken line  
  - [x] Petition Details - change Print receipt to Print Confirmation 
  - [x] Add Counsel - should be sentence case 
  - [x] Enter bar no or name - change to sentence case 
  - [x] Docket record - right align icon in column
  - [x] Docket record - Sort - change to sentence case 
  - [x] Add hover state to Actions button (see style guide) 
  - [x] In Progress - change “Add signature” to “Apply Signature” and add icon (see Order Draft screen) 
- [x]  UX review comment question
  - [x] On tab- always scroll to top 

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
