### ISSUE TITLE
Docket Clerk: Serve Orders and Decisions (paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6957]
As a Petitions or Docket Clerk, so that I may serve internally created court documents to parties with a paper service indicator, I need the ability to print the documents for any party that receives paper service.

## Acceptance Criteria
* Petitions and Docket Clerk can serve court-issued documents in paper form to parties that have a paper service indicator
* Service is noted within the system/docket record (already done)
* Served document is available within the system with the served date on it (already done)
* System prints the served date on the paper document being served (already done)
* System prints the name and address of the party on a blank first sheet so that a window envelope can be used (see comment below for placement of address -- same at ustaxcourt/ef-cms#6726) 

Notes:
* Follow up with Rhonda to confirm that the court NEVER serves externally filed documents to parties with paper indicator
* Regular mail versus certified/registered [Jessica needs to find out which docs get sent certified/registered]

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update `aggregateElectronicallyServedParties` to also return paper service parties (Rachael ustaxcourt/ef-cms-flexion#3801)
- [x] 2 Add alert to service modal and update confirm button text if any parties have paper service (Cody ustaxcourt/ef-cms-flexion#3807)
- [x] 3 Trigger print dialog when submitting the service modal if any parties have paper service (Kris ustaxcourt/ef-cms-flexion#3834)
- [x] 4 Add address page to document that is printed only and return the pdf data from the interactor (Team mob ustaxcourt/ef-cms-flexion#3810)
- [x] 5 Fix PDF spacing/styling issues with address and header (Cody ustaxcourt/ef-cms-flexion#3835)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
