### ISSUE TITLE
Add Judge association for each case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6960]
As the Court, in order to make sure all work is appropriately assigned, each case should have a Judge associated with it at all times.

## Acceptance Criteria: ##
* A case must have a Judge associated with it at all times
* Court user can easily see which judge is associated with a case
* Rules for Judge association: https://docs.google.com/document/d/1qhxASEKuzcPp99rTfCVkYbi6hVKS1pPPIgn5MvEWFPM/edit?usp=sharing

## Notes: ##
* When a Trial Session is set/automatically scheduled, the Judge associated with each case on that trial session should automatically change to the Judge assigned to the trial session.
* If the Judge assigned to a trial session changes, the Judge associated with each active case remaining on that trial session should automatically be updated to that new Judge.

## Tasks: ##
~- [ ] 1 Write some tests around the rules provided in the google document for judge association (Matt)~
- [x] 2 Add judge tag to case detail header (Rachael, Matt ustaxcourt/ef-cms-flexion#3498)
- [x] 3 Add judge association to case entity (maybe remove trialJudge and replace with associatedJudge?) as a required field (Rachael, Matt ustaxcourt/ef-cms-flexion#3498)
- [x] 4 Add chief judge association when a case is created electronically or from paper (Rachael, Matt ustaxcourt/ef-cms-flexion#3498)
- [x] 5 When a case is removed from a trial session, set the judge back to the chief judge (Rachael, Matt ustaxcourt/ef-cms-flexion#3498)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
