### ISSUE TITLE
Search: Allow unauthenticated users to access a public version of the site

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6966]
## Pre-requiste:
* Member of the public (unauthenticated user) comes to the site https://ui-public-dev.ustc-case-mgmt.flexion.us/

## Acceptance criteria:
* Unauthenticated user can access the case management system to perform a search

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

##Tasks
- [x] 1 Public site terraform config (#3675)
- [x] 2 Create new build target for public version of the site (#3677)
- [x] 3 Create public search view with instructional text for desktop and mobile (Rachael ustaxcourt/ef-cms-flexion#3687)
  - [x] 3a Public template header/footer (Matt ustaxcourt/ef-cms-flexion#3693)
- [x] 4 Deploy public version of the site (Rachael ustaxcourt/ef-cms-flexion#3688)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts (Rachael)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Rachel)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (Rachael)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Matt)
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
