### ISSUE TITLE
Docket Clerk: Add Docket Entries to Consolidated Group Members (Court-Issued Docs)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6969]
As a docket clerk, in order to prevent having to add multiple docket entries in a group of consolidated cases, I need the system to automatically add a docket entry to any other cases in the group that I choose when adding a docket entry for a Draft in the Lead case.

When a document is filed in a case that is part of a consolidated group (CG), it is often necessary to have that document reflected on the docket record for some or all of the other cases part of that group. Currently, this requires the court user to manually scan/upload the document(s), send a message, and then add the docket entry individually for each case in the group as needed, which can take a lot of time and introduces opportunity for error.

We would like the Court to have the ability when adding a docket entry in the Lead case of the CG (designated currently as the lowest-numbered case in the CG) to select which, if any, other cases in the CG to automatically create a docket entry. This initial story will focus on court-issued documents only.

## Acceptance Criteria
* In the Lead case for a consolidated group, when a docket clerk chooses Add Docket Entry for a Draft document, the clerk has the ability to choose one or more _other_ cases in that group in which to also add a docket entry
* The docket entry for each additional case in the CG:
  - is entered with the same data values as the Lead Case entry
  - should be docketed just as if the document for the entry had been added to the case manually
  - should share a single source of truth as the entry in the Lead Case if possible
  - are viewable on the docket record as per normal visibility rules 
  - is created and served when the Lead case docket entry is served.
* When the docket entry is created and served for the Lead case in a consolidated group of cases, the user is presented with a visual reminder of all parties in the consolidated group who will receive service
* Parties receive service as normal for each docket entry (including the Lead docket entry)
  - Paper service documents are presented for printing as normal for each party receiving paper service
* Court issued documents that require cover sheets to be generated are not in scope for this story.
     - Hearing Exhibits (HE)
     - Trial Exhibits (TE)
     - U.S.C.A (USCA)
     - Bounced Electronic Service (ES)
     - Returned Mail (RM)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
**Questions from UX**
1. Cover sheet AC - is this covered in ustaxcourt/ef-cms#6996?
2. Do we need to serve each docket entry for the non-lead cases if it's being served in the lead case? Yes

### Engineering

How do we want to handle duplicate docket entries?

- Making a Docket Entry Alias "type" that points to the parent docket entry.
  - This might not work because each case has unique properties for its docket entries (e.g. served parties).  If this was to work, you'd have to also specify some kind of overrides.
- Duplicating the docket entry, but it references the same PDF file.
  - Isn't the docket entry's UUID and S3 PDF linked directly?  There may be complications with making duplicate docket entries depending on how we have architected our DynamoDB schema.
  - This could work since docket entries don't have "entity" entries in DynamoDB.  They only ever exist as being attached to a case PK.

## Tasks
- [x] Feature flag
- [x] Modify model to display all the checkmarks for CG cases
- [x] Modify model to display the paper service parties
- [x] Backend modifies docket record on selected CG cases
- [x] Modify paper service to make copies of the PDF.
- [x] Rename nearly all variables

## Test Cases
* Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in; clerk selects one other case from the consolidated group; Parties receiving paper service are displayed in modal; Print paper service is available for clerk, Upon service, document is reflected appropriately on the docket record for both the lead case and the selected case.
* Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in; selects some of the other cases (not all) from the consolidated group to also add the docket entry in that case; Parties receiving paper service are displayed in modal; Print paper service is available for clerk, Upon service, document is reflected appropriately on the docket record for the lead case and each case selected.
* Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in; selects all other cases from the consolidated group to also add the docket entry in those cases; Parties receiving paper service are displayed in modal; Print paper service is available for clerk, Upon service, document is reflected appropriately on the docket record for the lead case each case selected.

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by swongCO** [comment]
![Add Docket entry modal 1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/6d064db7-9a24-4220-ad1f-03d08c326cdb)
![Add Docket entry modal 2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/0e845f22-b7de-46ee-baad-95abe7fdc673)
On the Add Docket Entry page of a **lead case in a group**, when a user clicks "Save and Serve", display a modal with modified content: 

1. Below existing content , add the checkbox list that contains the All option first, then the lead case (lowest docket number) followed by the other cases in ascending order.
2. All boxes are checked by default and disabled (text is not in disabled state) **except for the first one.**
3. Selected cases will be served the document that is being created as a docket entry.
4. For selected cases, parties that receive paper service will be listed in the message box above the list.
5. If the list of paper service parties pushes content below the boundary of the modal, enable vertical scrolling for the whole modal.
6. Amend the paper service message from "This case has parties..." to "This group has parties..."
7. If a case isn't the lead, then display the existing modal as is without the checkbox list.

![Add docket entry modal 3.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/46cb6662-be8d-4696-b257-d082f3f9f1c1)
1. If the All box is unchecked, then all checkboxes become unchecked and enabled, except for the lead case.
2. There is a hover tip over the lead case checkbox/line that reads "Lead case cannot be unselected"

**Comment by swongCO** [comment]
![Docket record confirmation.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/60ee3356-8d51-497c-bcfd-4805029c9c95)
After the user clicks "Yes, Serve", keep the existing flow and navigate to the Docket Record page:
1. Display the existing confirmation banner with the amended text "Document served to selected cases in group."

**Comment by ttlenard** [comment]
## Test Cases 

#### 1.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve

Expected Results
- [x] Updated modal has the checkbox checked for "All of the consolidated Group"
- [x] The list of parties receiving paper service shows parties from all the cases that receive paper service in the CG


#### 1.2) Docket Clerk selects one other case from the consolidated group; Parties receiving paper service are displayed in modal. 
- Continuing from test case 1.1
- Uncheck the first checkbox for "All in the consolidated group"
- Select one other case besides the lead case (check and uncheck a few of the cases)

Expected Results
- [x] The lead case checkbox will be unselectable and will remain checked.
- [x] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"
- [x] The message in the modal displays "This group has parties receiving paper service:" with the paper service parties listed below
- [x] The parties receiving paper service list adjusts to display only the parties receiving paper service on the selected cases within the list.


#### 1.3) Upon service, the print paper service is available for clerk.
- Continuing from test case 1.2
- Take note of the petitioners names in the list of parties receiving paper service
- Click Yes, Serve

Expected Results:
- [x] The Print for paper service screen opens
- [x] Each party that receives paper service in the CG of cases that were selected in the previous test and that were listed on the modal have the document and address cover sheet to be printed for service.


#### 1.4) Updated confirmation message appears after service.
- Continuing from test case 1.3
- Click Done

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] Green banner is present on the top of the page that states, "Document served to selected cases in group"


#### 1.5) Document is reflected appropriately on the docket record for both the lead case and the selected case.
- Continuing from test case 1.4
- Review the document details on the docket record

Expected Results
- [x] On the lead case, the document is attributed with index #, date, title, pages, action, served date, served parties, and has the edit/seal links
- [x] On the one other case in the CG that was selected, the document is attributed the exact same way on the docket record as in the lead case.


#### 1.6) Document in the non-lead case is the same as the document in the lead case.
- Continuing from test case 1.5
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other case that you filed the document in
- Click on the URL of the document
- Click on the URL to View Full PDF
- This will open the document in a new tab

Expected Results
- [x] Both documents should be exactly the same
- [x] Both documents should share the same document ID


#### 2.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (Can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve

Expected Results
- [x] Updated modal has the checkbox checked for "All of the consolidated Group"
- [x] The list of parties receiving paper service shows parties from all the cases that receive paper service in the CG


#### 2.2) Docket Clerk selects some of the other cases (not all) from the consolidated group to also add the docket entry in that case; Parties receiving paper service are displayed in modal. 
- Continuing from test case 2.1
- Uncheck the first checkbox for "All in the consolidated group"
- Select a few other cases (not all) besides the lead case 

Expected Results
- [x] The lead case checkbox will be unselectable and will remain checked.
- [x] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"
- [x] The message in the modal displays "This group has parties receiving paper service:" with the paper service parties listed below
- [x] The parties receiving paper service list adjusts to display only the parties receiving paper service on the selected cases within the list.


#### 2.3) Upon service, print paper service is available for clerk  
- Continuing from test case 2.2
- Take note of the petitioners names in the list of parties receiving paper service
- Click Yes, Serve

Expected Results:
- [x] The Print for paper service screen opens
- [x] Each party that receives paper service in the CG of cases that were selected in the previous test and that were listed on the modal have the document and address cover sheet to be printed for service.


#### 2.4) Updated confirmation message appears after service.
- Continuing from test case 2.3
- Click Done

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] Green banner is present on the top of the page that states, "Document served to selected cases in group"


#### 2.5) Document is reflected appropriately on the docket record for the lead case and each case selected.
- Continuing from test case 2.4
- Review the document details on the docket records of each case that the document was served to

Expected Results
- [x] On the lead case, the document is attributed with index #, date, title, pages, action, served date, served parties, and has the edit/seal links
- [x] On the other cases in the CG that were selected, the documents are attributed the exact same way on the docket record as in the lead case.


#### 2.6) Document in the non-lead cases are the same as the document in the lead case.
- Continuing from test case 2.5
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the documents
- Click on the URL to View Full PDF
- This will open the documents in a new tab

Expected Results
- [x] All of the documents should be exactly the same
- [x] All of the documents should share the same document ID


#### 3.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in; 
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (Can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve

Expected Results
- [x] Updated modal has the checkbox checked for "All of the consolidated Group"
- [x] The list of parties receiving paper service shows parties from all the cases that receive paper service in the CG


#### 3.2) Docket Clerk selects all other cases from the consolidated group to also add the docket entry in those cases; Parties receiving paper service are displayed in modal; 
- Continuing from test case 3.1
- Leave the checkbox checked for "All in the consolidated group"

Expected Results
- [x] The message in the modal displays "This group has parties receiving paper service:" with the paper service parties for all of the cases in the CG listed below


#### 3.3) Upon service, print paper service is available for clerk, 
- Continuing from test case 3.2
- Take note of the petitioners names in the list of parties receiving paper service
- Click Yes, Serve

Expected Results:
- [x] The Print for paper service screen opens
- [x] Each party that receives paper service in the CG of cases that were listed on the modal have the document and address cover sheet to be printed for service.


#### 3.4) Updated confirmation message appears after service.
- Continuing from test case 3.3
- Click Done

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] Green banner is present on the top of the page that states, "Document served to selected cases in group"


#### 3.5) Document is reflected appropriately on the docket record for the lead case each case selected.
- Continuing from test case 3.4
- Review the document details on the docket records of each case that the document was served to

Expected Results
- [ ] On the lead case, the document is attributed with index #, date, title, pages, action, served date, served parties, and has the edit/seal links
- [ ] On all of the other cases in the CG, the documents are attributed the exact same way on the docket record as in the lead case.

#### 3.6) Document in the non-lead cases are the same as the document in the lead case.
- Continuing from test case 3.5
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the documents
- Click on the URL to View Full PDF
- This will open the documents in a new tab

Expected Results
- [x] All of the documents should be exactly the same
- [x] All of the documents should share the same ID


#### 4) Docket Clerk is in the lead case of a consolidated group and adds a docket entry.  Clicks Cancel, document is saved to drafts folder of lead case, is not added to any other case in consolidated group. 
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (Can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Cancel
- Click Yes, Cancel

Expected Results:
- [x] You will be navigated back to the drafts tab and the document preview, where you can edit, delete, apply signature, add docket entry, or view full PDF.

#### 5)  Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in, but then docket clerk clicks No, take me back instead of Yes, Serve
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (Can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve
- On the Pop-up, click "No, take me back"

Expected Results
- [x] DAWSON navigates back to the Add Docket Entry screen


#### 6.1) Docket Clerk adds a docket entry in a case that is in a consolidated group, but it is not the lead case.  Add docket entry workflow does not include the new modal, and docket clerk does not have the ability to file the document in other cases in the group.
- Log in as a Docket Clerk
- Navigate to a case that is in a consolidated group, and be sure that the case is NOT the lead case. (I used case 17495-17)
- Click Create and select PDF Upload (Can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve

Expected Results:
- [x] The pop up modal that states "Are you ready to Initiate Service?" appears (This is NOT the new modal, this should be the original modal that appears for non-consolidated cases).

#### 6.2) Docket clerk serves the document in the non-lead case in a consolidated group; document is only filed in the individual case.
- Continuing from test case 6.1.
- Click Yes, Serve

Expected Results:
- [x] Print for paper service appears (if parties are receiving paper service)
- [x] Document is filed on the docket record of only this case, not filed in any other cases in the consolidated group.

#### 7.1) Docket Clerk is in the lead case of a consolidated group and adds a docket entry; modal appears for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select any document type (excluding the documents listed in the AC that have cover sheets). If you created an Order, just keep the document type as selected previously.
- Click Save and Serve

Expected Results
- [x] Updated modal has the checkbox checked for "All of the consolidated Group"
- [x] The list of parties receiving paper service shows parties from all the cases that receive paper service in the CG


#### 7.2) Docket Clerk selects ONLY the lead case from the consolidated group; Parties receiving paper service are displayed in modal. 
- Continuing from test case 7.1
- Uncheck the first checkbox for "All in the consolidated group"

Expected Results
- [x] The lead case checkbox will be unselectable and will remain checked.
- [x] When hovering over the lead case in the CG, the hover over help text will display "The lead case cannot be unselected"
- [x] The message in the modal displays "This group has parties receiving paper service:" with the paper service parties listed below


#### 7.3) Upon service, the print paper service is available for clerk.
- Continuing from test case 7.2
- Take note of the petitioners names in the list of parties receiving paper service
- Click Yes, Serve

Expected Results:
- [ ] The Print for paper service screen opens
- [ ] Each party that receives paper service in the lead case that was selected in the previous test and that were listed on the modal have the document and address cover sheet to be printed for service.


#### 7.4) Updated confirmation message appears after service.
- Continuing from test case 7.3
- Click Done

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] Green banner is present on the top of the page that states, "Document served to selected cases in group"


#### 7.5) Document is reflected appropriately on the docket record for the lead case only
- Continuing from test case 7.4
- Review the document details on the docket record

Expected Results
- [x] On the lead case, the document is attributed with index #, date, title, pages, action, served date, served parties, and has the edit/seal links
- [x] Document is NOT present on any of the other cases in the CG


#### 8) Docket Clerk is in the lead case of a consolidated group and adds a docket entry that is a decision type of document; modal does not appear for clerk to select additional cases to file the document in.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select PDF Upload (can also select Order or Notice)
- Upload a PDF and click Save (or generate a draft Order/Notice)
- Click Add Docket Entry from the drafts page
- If it was an uploaded PDF, Select a document type that is a decision type of document. If you created an Order, be sure that you select a decision type of order.
- Click Save and Serve

Expected Results
- [ ] Updated modal does not appear
- [ ] "Normal" workflow for serving documents (outside of consolidated cases) occurs

**Comment by halprin** [comment]
Created the `consolidated-case-with-duplicating-docket-entries` feature flag.

**Comment by halprin** [comment]
The model is located at `web-client/src/views/ConfirmInitiateServiceModal.jsx`.

**Comment by halprin** [comment]
`web-client/src/presenter/sequences/serveCourtIssuedDocumentFromDocketEntrySequence.js` is the sequence that most likely runs when someone clicks "Yes, Serve".  That sequence could be overridden though.

**Comment by ttlenard** [comment]
It was discussed that if a Decision type of document is added as a docket entry in the lead case, then the updated modal that displays for the user to select additional cases to file in will NOT appear.  Decision documents are only to be filed in individual cases.  I added test case 9 for this scenario.

**Comment by halprin** [comment]
Need to add `setupConsolidatedCasesAction` to `web-client/src/presenter/sequences/openConfirmServeCourtIssuedDocumentSequence.js` for when we tackle serving (without filing) of court issued documents.

Need to update `web-client/src/presenter/actions/serveCourtIssuedDocumentAction.js` and `shared/src/business/useCases/courtIssuedDocument/serveCourtIssuedDocumentInteractor.js` too.

**Comment by ttlenard** [comment]
I deleted the original test case 4 that involved saving the docket entry rather than save and serve since we split that workflow out of this story.  The test cases that were in here are now in story 9513.

**Comment by halprin** [comment]
TODO

- set-up feature flag script
- feature flag the other "served only" UI
- "Document served to selected cases in group" after service.
- Cypress and integration tests

**Comment by liadmccabe** [comment]
![Screen Shot 2022-06-20 at 11.27.34 AM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/39e7ec7c-5bbd-4e2d-9705-74e01381ecba)Issue found during UX Review: Our mockups incorrectly indicated modal text should say "The following document will be served on all parties:".  This text should be corrected to say "The following document will be served on all parties in selected cases"

**Comment by ttlenard** [comment]
Found an issue while testing.  When serving a document, if the petitioner has paper service, the print for paper service screen overtakes all DAWSON tabs that you have open.  This is very confusing if a user needs to issue an Order in a Consolidated group of cases.  If this user is doing multiple things in DAWSON, they may accidentally print the same paper service multiple times. They  may not realize that it is the same document. Based on the conversation we had during standup, it seems to be related to the current websocket configurations?  Here are the steps to take to recreate the issue:

1 - Have multiple tabs open with various cases (can have cases that are in a Consolidated group, or just random cases)
2 - Go to the lead case (22447-16) and create an order (or you can also create an order in docket 22449-16- a member case)
3 - On the pop-up modal for selecting which cases to serve the document on, be sure to select a case that has petitioners that receive paper service (in my testing, docket 22449-16 has Paper service)
4 - The Print for paper service screen appears.  
5 - This screen will appear on ALL DAWSON tabs that you have open.

**Comment by ttlenard** [comment]
Found an issue while testing today.  I am unable to serve a document to a Consolidated group. I receive a spinner of doom.  Here are the steps to recreate it.

1.  Log in as a docket clerk
2. Navigate to a lead case in a consolidated group (I used 22447-16)
3. Click Create, select Order or Notice
4. Draft an Order, and then click Save and Serve.
5. You will get the "which cases do you want to serve this to" message.  I selected only the lead case, and I also selected all cases when attempting to test this, so it doesn't matter what you select.
6. Serve the document on the selected cases.
7. You will get the spinner of doom. When I had the console open, I received a lot of websocket errors.  Not sure if this means anything?  

Note: Chris Holly also experienced this same behavior.

Here is a screen capture:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ae71a72f-b467-4a3e-a90b-389dd29f7207)

**Comment by ttlenard** [comment]
On TEST, when you are serving a court issued document via pdf upload in a member case, or just a regular ol' case that isn't part of a CG, you get the pop-up modal that has the updated wording for Consolidated cases...Granted, it doesn't have the checkboxes, but the wording has changed from what it was originally, which could cause some confusion.

Here is what it is currently displaying when serving a document on a non lead case on TEST:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/8bc9a0f3-b9b7-4a9e-a5ea-3bd97abb97c2)

Here is the language that currently exists when serving (without the Consolidated functionality deployed) on Staging:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/25a960c2-b76f-4d67-974a-d22da0b9ac35)

**Comment by cholly75** [comment]
Approved to remove feature flag
