### ISSUE TITLE
Court User: Unlink Consolidated Cases

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6972]
As a court user, so that I may remove a case from a consolidated group, I need the ability to unlink one or more cases.

## Pre-Conditions ##
* Two or more cases are consolidated

## Acceptance Criteria
* Court user can unlink one or more cases from a consolidated group
* After being unconsolidated, the unconsolidated case looks and behaves just as it did before it was consolidated 
   * There should be no consolidated icon on case
   * The case should not be listed on the consolidated card in any case
   * The case should be removed from the consolidated group on party dashboard(s); if the user is a party to the case, the case would now show up as a stand-alone case on the dashboard; if the user is not a party to the case, the case would not show on the dashboard
* All activity/filings/etc. that took place in the case when it was consolidated remains and is not "undone"
* If the lowest number case in a consolidated group is unconsolidated, the next lowest docket number becomes the lead case for the group

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- [x] 1 Add Remove cases button to Consolidated Cases card under Case Information (Cody ustaxcourt/ef-cms-flexion#4136)
- [x] 2 Create Unconsolidate Cases modal (sequence for opening) (Cody ustaxcourt/ef-cms-flexion#4136)
- [x] 3 Submit sequence, actions for modal (Kris, Rachael, Cody ustaxcourt/ef-cms-flexion#4146)
  - [x] 3a Success confirmation message appears at the top to the screen stating that cases were unconsolidated from the group (Kris)
- [x] 4 Endpoint for unconsolidating (interactor, serverless, lambda) (Rachael ustaxcourt/ef-cms-flexion#4137)
- [x] 5 Hide Remove button if the case isn't already consolidated (Cody)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
