### ISSUE TITLE
Clean-Up: Redesign Document Detail Page

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#6974]
As a court user, in order to easily access multiple documents on the docket record, I need the ability to toggle documents from the document detail page. 

This story also includes various clean-up items. 

 ## Pre-Conditions

## Acceptance Criteria
* All documents on the docket record display on the left of the document
* User should be able to view a full-page PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update Docket Record on case detail to H1 tab, and add Document View as second H1 tab (Document View link only displayed for internal users) (Cody ustaxcourt/ef-cms-flexion#5711)
- [x] 2 Create Document View view
  - [x] 2a Left panel with documents listed,  sorted oldest to newest by date (same sort as docket record) (Matt ustaxcourt/ef-cms-flexion#5716)
  - [x] 2b Right panel with document viewer (Matt ustaxcourt/ef-cms-flexion#5716)
  - [x] 2c only display documents that are on the docket record - not draft docs or minute entries (Matt ustaxcourt/ef-cms-flexion#5716)
  - [x] 2d Display Sealed in Blackstone for legacy data (Matt)
  - [x] 2e Document actions bar, View Full PDF link (Matt ustaxcourt/ef-cms-flexion#5716)
- [x] 3 On click of the document link from the Docket Record, display the "Document View" tab with the clicked document selected and visible in the PDF viewer (Matt ustaxcourt/ef-cms-flexion#5716)
- [x] 4 Update document links to redirect to correct page (see story comment) (Rachael ustaxcourt/ef-cms-flexion#5712)
- [x] 5 Display document that was clicked on when navigating to case detail view from qc boxes or pending report (Rachael)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
