### ISSUE TITLE
Clean up Items

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#6976]
As a development team, so that we can ensure a good user experience, we need to perform some clean up items.

## Acceptance Criteria
* If a user selects "Myself & Spouse" as the party type, have user confirm (maybe through a modal) that he/she has authority to file the Petition on behalf of the spouse [Note: have user helper text that requires both TPs to have signed the Petition form uploaded]
* Remove "Create Case" ability for docket clerks. Petitions clerks are the only role that needs the ability to create a case from paper. (Kristen added 11/20/19)   (Valid)
* Wording for motion objection should be "Is there any objection to the granting of this motion?" (Valid) [Note: this needs to be fixed on external and internal views of file a doc page]

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] 1) on select of "Myself and Spouse" and "No" (my spouse is not deceased), display acknowledgement modal (Kris ustaxcourt/ef-cms-flexion#4420)
 - [x] 2) remove create case privilege from docketclerk role. creation of paper case should only be permitted by petitionclerk role.
 - [x] 3) update wording of motion objection as seen above in AC (Kris ustaxcourt/ef-cms-flexion#4418)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
