### ISSUE TITLE
Court User: Serve Automated Notices

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6977]
As a court user, in order to notify parties that an automated notice has been issued, I need the system to serve all automated noticed on parties when the notice is generated.

## Pre-Conditions
* The system has generated an automated notice that gets added to the Docket Record (Notice of Change of Address, Notice of Change of Phone Number, Notice of Change of Address and Phone Number, Notice of Docket Change) -- ANY OTHERS?

## Acceptance Criteria
* System/user serves an automated notice on parties after it's generated [Note: need to account for both paper and electronic service]
* Parties in the case receive the service

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* When notices are served, they are still not visible to public users ( should not be hyperlinked on docket record) 
* Make sure the notice of docket change "docket entry text" is correct for parties/external public view
* This story does not include editing practitioner information/service related to editing practitioner information

## Tasks
- [x] 1 Create paper service modal (Team mob ustaxcourt/ef-cms-flexion#4092)
- [x] 2 Create helper method for serving a notice (Team mob ustaxcourt/ef-cms-flexion#4092)
- [x] 3 Notice of Docket Change flow (Team mob ustaxcourt/ef-cms-flexion#4092)
- [x] 4 Notice of Change of Address/Phone/Address&Phone (internal) flow (Rachael ustaxcourt/ef-cms-flexion#4101)
- [x] 5 Notice of Change of Address/Phone/Address&Phone (external) flow (#4096)
  - [x] 5a Create a work item
  - [x] 5b Update docket QC screen with alert and redirect to print preview page when completing if there are any paper service parties (Rachael ustaxcourt/ef-cms-flexion#4107)
- [x] 6 Fix issue with routing on the print preview page - should we be navigating to a separate route? When on the print preview page, you can't click on the docket number in the case detail header to go back to the case detail page (because you're already on the case detail route) (Rachael ustaxcourt/ef-cms-flexion#4112)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
