### ISSUE TITLE
Court User: Add Judge filter to deadline report

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6984]
As a court user, so that I may easily see navigate my deadlines, I want the ability to filter the deadline report by judge. 

## Acceptance Criteria
* Judge is added to deadline report
* Court user can filter the deadline report by judge

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] add associatedJudge to the CaseDeadline entity
- [x] add the judge to the objects returned by the getAllCaseDeadlines persistence function
- [x] add CaseDeadline validation to the getAllCaseDeadlinesInteractor (Eric)
- [x] add judges to the Case Deadline table View
- [x] add judge filter to view
- [x] write tests for deadline report (Rae)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
