### ISSUE TITLE
Court User: Ability to record postmark date and display on petition coversheet

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6986]
As a court user, in order to know if a paper petition was timely mailed, I need the ability to note the postmark dated in the system so it's legible.  

## Acceptance Criteria
* Court user can record "Mailing Date" information for paper-filed documents (1 free text field)
* One line of free text is sufficient
* Text entered in the field displays on the coversheet above the docket record [Note: in the same place as "Filed Electronically" appears for an electronic Petition]
* Mailing Date field should be *required* as part of "Start a Case" for a paper petition
* Text entered during the "Start a Case" flow for a paper petition should show on the Petitions QC screen
* If electronic Petition, no Mailing Date field is displayed on the Petitions QC screen
* Mailing Date field should be *optional* as part of the "File a Document" flow for a paper document processed by Docket

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Court doesn't currently have on cover sheet, so we can discuss placement

## Tasks
- [x] update create paper case flow to allow the optional mailing date field, includes UI / Interactors changes (Cody ustaxcourt/ef-cms-flexion#3871)
- [x] update add docket entry flow to allow the optional mailing date field, includes UI / Interactors changes (Cody ustaxcourt/ef-cms-flexion#3880)
- [x] update the coversheet code to display the mailing date if provided (Cody ustaxcourt/ef-cms-flexion#3871)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
