### ISSUE TITLE
Prod: Create Court's Testing and Production Environments

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6997]
As the court, in order to facilitate user testing in a real-world environment, we need to set up our testing and production sites

## Acceptance Criteria
* Court's testing and production sites are set up
* Users can access the application through Court's test and production sites
* Ensure environments are updated with latest functionality
* Ensure users are set up in test environment

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Court will perform daily testing of test environment (T-F), starting on 1/13
* Court does not need test data in the test environment
* TEST environment URL is https://ui-test.ef-cms.ustaxcourt.gov/
* PRODUCTION environment URL is https://ui-prod.ef-cms.ustaxcourt.gov/

## Tasks
- [x] Set up testing environment and load test users (Eric) 
    - [x] Add variables to the config files; Waldo to create branch on court side that matches it
- [x] Set up production environment
- [x] Provide PR to tax court, w/changes necessary to set up test environment w/users (Kris and Eric)
- [x] Update AWS roles (Waldo)
- [x] Determine update schedule for testing and production environments (Waldo, for now)
- [ ] Testing of both environments - general UX review (Court will test details during daily session)
