### ISSUE TITLE
Petitions Clerk: Issuing Orders (by 1/8)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#6999]
As a petitions clerk, in order to issue orders, I need the ability to create and serve orders.

## Acceptance Criteria
* Petitions Clerk can generate an Order (done)
* Petitions Clerk can sign an Order with the Chief Judge's signature (done)
* Petitions Clerk can create a docket entry for the Order
* Petitions Clerk can serve the Order on the parties
   * Parties (petitioner only, not respondent) with electronic service get an email
   * Parties with paper service get paper

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Not transmitting files to IRS at this time
* Not adding the doc to the ZIP file at this point, since we don't know actual solution for transmitting docs to IRS
* Decision made to serve generic IRS email if no attorney attached. That work is not part of this story. 

## Tasks
- [x] create a new permission and attach it to the petitions clerk to allow them to create & serve a court issued order (Cody ustaxcourt/ef-cms-flexion#3925)
- [x] Filter out draft documents whee creating the zip (Rachael ustaxcourt/ef-cms-flexion#3930)
- [x] petitionsclerk should only be able to create the generic order (Cody ustaxcourt/ef-cms-flexion#3925)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
