### ISSUE TITLE
Calendaring: Any due date or pending item should put case on "blocked list"

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7001]
As a court user, in order to ensure that cases needing to be blocked don't slip through the cracks, I need the case to become blocked from being calendared if it has a pending item or an assigned due date.

## Acceptance Criteria: ##
* Any case with a pending item or due date should automatically be blocked from trial and show up on the blocked cases report
* Reason for blocking case should be noted on the blocked report as "Pending Item", "Due Date", or "Pending Item and Due Date"
* Once all pending items and due dates have been removed, the block on the case should be automatically removed

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add automatic block fields to the Case entity (automaticBlocked, automaticBlockedReason, automaticBlockedDate), functions to setAutomaticBlock, unsetAutomaticBlock (Kris, Rachael ustaxcourt/ef-cms-flexion#4271)
- [x] 2 In the interactors where pending items are generated, set an automatic block (Kris, Rachael ustaxcourt/ef-cms-flexion#4271)
- [x] 3 In the interactor where a due date is added, set an automatic block (Kris, Rachael ustaxcourt/ef-cms-flexion#4271)
- [x] 4 In the interactor where pending items are removed, reset/unset the automatic block (Kris, Rachael ustaxcourt/ef-cms-flexion#4276)
- [x] 5 In the interactor where due dates are removed, reset/unset the automatic block (Kris, Rachael ustaxcourt/ef-cms-flexion#4276)
- [x] 6 Show Blocked in header when case has a manual OR an automatic block (Kris ustaxcourt/ef-cms-flexion#4284)
- [x] 7 Add automatic block cases to the blocked report (Kris ustaxcourt/ef-cms-flexion#4284)
- [x] 8 Delete case trial sort mapping records when a case is blocked and re-create them when a case is unblocked (will need to also check if a case has been manually blocked before re-creating them) (Rachael ustaxcourt/ef-cms-flexion#4282)
- [x] 9 Update trial card on case detail case information (Kris, Rachael ustaxcourt/ef-cms-flexion#4288)
- [x] 10 Update UnblockFromTrialModal with new alert (Rachael ustaxcourt/ef-cms-flexion#4285)
- [x] 11 Case should not be set to blocked if it is calendared (Rachael ustaxcourt/ef-cms-flexion#4290)
- [x] 12 Show high priority indicator on trial card if case is system blocked and high priority (Rachael ustaxcourt/ef-cms-flexion#4290)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment
