### ISSUE TITLE
Make transcripts unavailable to parties for 90 days

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7002]
As a court user, in order to comply with contractual obligations with our Court reporting vendor, we need to make transcripts unavailable to parties within a case for 90 days.

The Court has a contract with a reporting company to transcribe our Court proceedings.  One term of our contract is that the Court will not make any transcripts publicly available (even to parties) for 90 days.

## Pre-Conditions: ##
* Court has uploaded a transcript in a case

## Acceptance Criteria: ##
* All transcripts should only be viewable to internal Court users for the first 90-days [Note: 90-day period runs from the date of trial/hearing.  This information should be gathered when Docket Clerk enters information while creating docket entry.]
* After 90 days, transcripts should then be viewable to parties in the case
* Transcripts are never viewable to the public
* Provide a way to test without waiting 90 days

## Notes
* the document type required fields for TRAN needs to be updated to add the date- the spreadsheet is now updated
*** for testing purposes we need to set the timer to 1 day at first then can update after testing to 90 days**

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Figure out what restrictions are on the date the transcript is filed - should it be in the past? If so, fix validation to allow date in the past. (Rachael ustaxcourt/ef-cms-flexion#4335)
~~- [ ] 2 Add permission for viewing all transcripts at any time~~
- [x] 3 Update getDownloadPolicyUrlInteractor to retrieve the document, check the event code for TRAN, and check if 90 days have passed (if the user doesn’t have transcript permission) (Kris, Rachael ustaxcourt/ef-cms-flexion#4350)
- [x] 4 Update getFormattedCaseDetail with a new computed value to hide the document link (Kris, Rachael ustaxcourt/ef-cms-flexion#4350)
- [x] 5 Hide transcript links for public users (Rachael ustaxcourt/ef-cms-flexion#4351)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
