### ISSUE TITLE
Allow Primary Petitioner to change the contact info for secondary Petitioner

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7009]
## Acceptance Criteria
* Allow primary Petitioner to change contact info for the secondary Petitioner
* If primary Petitioner changes the contact information for the secondary Petitioner, a Notice of Change of Address, Notice of Change of Phone Number, and/or Notice of Change of Address and Phone Number should be automatically generated and served on the parties

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Can we add some additional ACs?
* Allow Petitioner Counsel to change contact info for the secondary Petitioner
* Serve automated notices on paper and electronic parties when Petitioner Counsel updates Primary or Secondary Petitioner address and/or telephone number 

## Tasks

- [x] 1) on case info petitioner and practitioner views (NOT respondent): (Kris ustaxcourt/ef-cms-flexion#4393)
  - remove "why can’t I edit this” link
  - add “edit” link to secondary contact info card, available to petitioner and petitioner counsel
- [x] 2) create/update sequence to edit secondary contact info (Matt ustaxcourt/ef-cms-flexion#4397, ustaxcourt/ef-cms-flexion#4401)
- [x] 3) display secondary contact name, non-editable on form. (Rachael ustaxcourt/ef-cms-flexion#4395)
- [x] 4) in the interactor: If address and/or phone number is updated, a "Notice of Change of Address/ Notice of Change of Telephone Number/ Notice of Change of Address and Telephone Number" should be generated (same functionality as #2146 and #3676) (Matt ustaxcourt/ef-cms-flexion#4397)
 - [x] 5) update 'cancel' links to show the cancel modal when editing primary *or* secondary contact info (Rachael ustaxcourt/ef-cms-flexion#4395)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
