### ISSUE TITLE
Fix document codes

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7010]
Clean up needed to document codes:

## Acceptance Criteria: 
* Remove M025 (Motion for Preliminary Injunction) from all lists/drop-downs
* Update the code for Proposed Stipulated Decision to PSDE.  Confirm name in drop-down and cover sheet is "Proposed Stipulated Decision"
* Fix typo in M084 Motion to Permit Expert Witness to Testify Without a Written Report Regarding Industry Practice Pursuant to Rule 143(f)(2) – The rule should be Rule 143(g)(3)
* Add Notice of Appeal to external filing drop-down -- it is now allowed to be electronically filed
* Incorporate Rhonda's changes to internal list [Jessica to provide to Kristen]
* Add "Notice" to create order drop down for all internal users
* Add "Notice" to dropdown for adding court issued docket entry
* Notice code is NOT
* User should be able to create their own generic notice name, like they do when they create a generic order
* Update Create Order button to Create Order or Notice
* Add Clerk of Court's signature automatically to the bottom of a notice when it's created (See Notice of Receipt of Petition for format)
* When notice is created, it follows same flow as order, but doesn't need signature portion.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Adding "notice" to create order dropdown as a Workaround for Notice of Documents in the Nature of Evidence (and other notices)

## Tasks
- [x] 1 Remove M025 (Motion for Preliminary Injunction) from all lists/drop-downs (Rachael ustaxcourt/ef-cms-flexion#4071)
- [x] 2 Update the code for Proposed Stipulated Decision to PSDE. Confirm name in drop-down and cover sheet is "Proposed Stipulated Decision" (Rachael ustaxcourt/ef-cms-flexion#4071)
- [x] 3 Fix typo in M084 Motion to Permit Expert Witness to Testify Without a Written Report Regarding Industry Practice Pursuant to Rule 143(f)(2) – The rule should be Rule 143(g)(3) (Rachael ustaxcourt/ef-cms-flexion#4071)
- [x] 4 Add Notice of Appeal to external filing drop-down -- it is now allowed to be electronically filed (Rachael ustaxcourt/ef-cms-flexion#4066)
- [x] 5 Add "Notice" to create order drop down for all internal users (Rachael ustaxcourt/ef-cms-flexion#4076)
  - [x] 5a Notice code is NOT
  - [x] 5b User should be able to create their own generic notice name, like they do when they create a generic order
- [x] 6 Add "Notice" to dropdown for adding court issued docket entry (Rachael ustaxcourt/ef-cms-flexion#4066)
- [x] 7 Update Create Order button to Create Order or Notice (Kris) ustaxcourt/ef-cms-flexion#4069
- [x] 8 Add Clerk of Court's signature automatically to the bottom of a notice when it's created (See Notice of Receipt of Petition for format) (Kris) ustaxcourt/ef-cms-flexion#4072
- [x] 9 Update document maps per spreadsheets in comment https://github.com/flexion/ef-cms/issues/3917#issuecomment-570631825 (Rachael ustaxcourt/ef-cms-flexion#4066)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
