### ISSUE TITLE
Seal a case - Make entire case hidden from public view

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7014]
As the Court, in order to protect a party or filing in a case from disclosure, we need the ability to "SEAL" a case.

The Court needs the ability to SEAL a case.  That means make the entire case (except for Docket Number) hidden from public view.

## Acceptance Criteria: ##
* A Docket Clerk [permissions based] has the ability to mark a case as SEALED
* Once a case is SEALED, it needs to be:
   * Prominently marked as SEALED for all internal Court users.
   * Prominently marked as SEALED for all parties to the case.
   * Completely hidden from public view (as well as practitioners and respondents that aren't part of the case) except for the docket number.  [Design suggestion from Jessica -- if a non-party searches for a SEALED case, it should only return the docket number and "This case is sealed."  Name search should not return anything.] 
* Unsealing a case is not part of this story -- that can be post-MVP.
* Ensure data is not in network response
 * Add messaging for how to enter a case if your a counsel

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 create endpoint, lambda, interactor to seal a case (Rachael ustaxcourt/ef-cms-flexion#4163)
  - [x] 1a add a property to the case entity for sealing a case (Kris  ustaxcourt/ef-cms-flexion#4159)
  - [x] 1b add utility function that scrubs cases of all but a whitelist of attributes if it is sealed AND to be hidden from the user performing the query (Kris ustaxcourt/ef-cms-flexion#4190)
- [x] 2 create action, sequence, proxy to seal a case (Rachael ustaxcourt/ef-cms-flexion#4165)
- [x] 3 Add 'Seal Case' button to Case Detail Overview card (Rachael ustaxcourt/ef-cms-flexion#4160) 
  - [x] 3a visible to docketclerk, clerkofcourt roles (Rachael ustaxcourt/ef-cms-flexion#4160)
- [x] 4 create 'Seal This Case' modal component, sequence to open (Rachael ustaxcourt/ef-cms-flexion#4161)
- [x] 5 create 'This case is sealed' banner component for docket header (Kris ustaxcourt/ef-cms-flexion#4159)
- [x] 6 ensure when a case is sealed, the public case detail: (Kris ustaxcourt/ef-cms-flexion#4159)
  - [x] 6a hides caption from docket header (Kris  ustaxcourt/ef-cms-flexion#4159)
  - [x] 6b hides docket record (Kris ustaxcourt/ef-cms-flexion#4190)
- [x] 7 update case search so that cannot be found with search on name (Kris ustaxcourt/ef-cms-flexion#4190)

## Definition of Done (Updated 8-28-19)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
