### ISSUE TITLE
Service of Petitions to IRS

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7015]
As the court, in order to ensure that the IRS is served petitions, we need a way to ensure they receive service.

## Pre-Conditions
ustaxcourt/ef-cms#7015 -  Service of Petitions to IRS

## Acceptance Criteria
* When a case served, the IRS superuser is assigned to the case (done)
* When the petitions clerk serves the document, the IRS receives a separate email for each individual document that is served [Note: service of other documents usually filed with Petition (Request for Place of Trial, Ownership Disclosure Statement, Application for Waiver, etc.) will be handled in ustaxcourt/ef-cms#6905)
* Petitions are only served on the IRS (respondent)
* Upon service of a Petition, an email is generated and sent to the generic IRS (test w/Flexion emails only)
* Service email for Petitions must include the following information:
   * Case name 
   * Docket Number
   * Document Name
   * Docket Index Entry No.
   * Document Type (Code)
   * Petitioner Name(s)
   * Petitioner Address
   * Petition File Date
   * Petition Postmark Date
   * Requested Place of Trial
   * Service indicator for Petitioner(s)
   * Practitioner Information (if applicable):
      * Name
      * Address
      * Phone
      * Email
      * Bar Number
   * Served Date/Time
   * Hyperlink to log into the system
* Service email must also include the following machine readable data: [Note: needs to be added to design]

------------------------ COMPUTER-READABLE DATA -------------------
docketNumber: [docketNumber]
docketEntryNo: [XX]
documentId: [documentId]
eventCode: [eventCode]

* Upon service, the Docket Record is updated to reflect the time and date of service of the Petition and the R is the party served
* Upon service, the date of service is applied to bottom of the first page (cover sheet) of the Petition

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Create the generic user as a separate role, so that they are not treated as a respondent
* (New Story) IRS Superuser - doesn't have a dashboard. They can search for and find a case. 

## Tasks
- [x] 1 Look through serveCaseToIrsInteractor and update as needed (Team mob ustaxcourt/ef-cms-flexion#5160)
  - [x] 1a Don’t need to zip docs anymore
  - [x] 1b Add sending email for only the petition document to IRS test account
  - [x] 1c Mark only the petition document as served only on the respondent (R in the docket record)
- [x] 2 Add new email template for petition document served on IRS (Matt ustaxcourt/ef-cms-flexion#5170)
- [x] 3 Update IRS superuser email address on flexion envs to a flexion-accessible email account (still needs to be the original email on court’s envs)
- [x] 4 Show R in docket record parties served column (Team mob ustaxcourt/ef-cms-flexion#5161)

Refactoring?
- [x] document.status === ‘served’ (Rachael)
- [x] irsSendDate (Rachael)
- [x] markAsSentToIRS (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
