### ISSUE TITLE
Basic Search for Orders (system-created)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7016]
As a CMS user, in order to locate a relevant Order, I need the ability to perform a basic search of Court orders.

## Pre-Conditions: ##
* System generated order is created and served

## Acceptance Criteria ##
* All CMS users have the ability to search all system-created Court Orders by keyword (basic search) [Note: uploaded orders will be handled in different story]
* Only court orders that have been served are indexed and searchable
* The search only returns documents with the codes for orders 
* Keyword search will match the contents of the document 
* Mobile design needs to be reconsidered for order (and opinion) search. Design is not optimal for public and parties in the case. Story backlogged to reconsider overall design for mobile search. ustaxcourt/ef-cms-flexion#5025

Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)

## Notes ##
* Court's current public Order search is below in comments
* Consider splitting into three stories - past judges (legacy data); basic search filter (keyword); advanced search filters
* Dealing w/sealed cases will happen in a different story. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? Yes.
 - [ ] Does this work make major changes to the system? No.
 - [ ] Does this work implement new authentication or security controls? Kind of.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features? Yes. 

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (#4947)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) (#4947)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (#4947)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
