### ISSUE TITLE
IRS Superuser

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7017]
As the Court, in order to properly serve the IRS, we need an IRS Superuser to be associated with each case once the Petition is served.

## Acceptance Criteria ##
* IRS Superuser is created as a separate role
* IRS Superuser is associated with each case as soon as the Petition is served
* IRS Superuser has log-in credentials to the CMS
   * Email address to be used: service.agent.test@irs.gov
* IRS Superuser's information is not displayed as "Respondent" on any case 
* IRS super user can log into the system and access all cases

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* View of dashboard does not need to be the same as other practitioners; search/return case
* IRS's actual email address - service.agent@irs.gov

## Tasks
- [x] 1 Create IRS superuser role, set permissions in authorizationClientService (can access all cases, but cannot edit anything), create local and cognito logins (Rachael ustaxcourt/ef-cms-flexion#4821)
- [x] 2 IRS superuser can only see full case information after a petition has been served in a case - create separate endpoint for IRS superuser getCase (for data for case detail page) (Rachael ustaxcourt/ef-cms-flexion#4823)
- [x] 3 Create IRS superuser dashboard view (Advanced search VIEW should be the same as for a privatePractitioner), sequence and action to submit search (Rachael ustaxcourt/ef-cms-flexion#4826)
- [x] 4 Update caseSearchFilter for caseAdvancedSearchInteractor to allow IRS superuser access to all cases in advanced search (look into refactoring this, code is a little messy) (Rachael ustaxcourt/ef-cms-flexion#4823)
- [x] 5 Setup IRS user script (Matt ustaxcourt/ef-cms-flexion#4832)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
