### ISSUE TITLE
Direct court user to signature page after saving a draft order

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7021]
Currently, after a petitions clerk or docket clerk saves a draft order from the actions dropdown, the user is directed to the docket record.  Instead, the user should be directed to the page where they can add a signature and send the draft Order to another Court user. It better supports the workflow.

## Acceptance Criteria
* When a Court user generates and saves an anything other than a Notice from the actions dropdown, he/she should be directed immediately to the sign order page [Note: The flow works this way if the user generates an Order from the "Summary of Orders" page after a Petitions QC]
* When a court user generates and saves a notice from the actions dropdown he/she should be directed immediately to the document detail for the draft notice.

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update submit sequence from Create Order page to redirect to the sign document page (only when submitting anything other than a notice) (Matt ustaxcourt/ef-cms-flexion#4364)
- [x] 2 Update submit sequence from Create Order page to redirect to the document detail page (only when submitting a notice) (Matt ustaxcourt/ef-cms-flexion#4364)
- [x] 3 Add page title to Apply Signature page; update link to “Back to Draft Document” (Matt ustaxcourt/ef-cms-flexion#4364)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
