### ISSUE TITLE
Docket Clerk: Unseal a case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7041]
As the Court, in order to properly manage our cases while remaining a court of public-record, we need the ability to unseal a case that has been previously sealed.

The Tax Court is a court of public record, so, in general, we seal as little as possible.  Because we might temporarily seal a case while we figure out which document(s) within a case really need to be sealed, we need the ability to seal a case (already done) and then unseal it.

Note that this story is intended to address unsealing entire cases/legacy cases only, **not** specific docket entries.

## Pre-Conditions
* ustaxcourt/ef-cms#8090

## Acceptance Criteria
(Note: AC should include non-standard testing, deployment, documentation or security requirements)
* Only Docket Clerk/CotC has the ability to unseal a previously sealed case.
* Once a case is unsealed, it is treated the same as all other non-sealed cases:
   * Red banner goes away
   * Case is returned during "Case Search" with normal public view
   * Orders in the case can return in during "Order search"
* Unsealing a Case does not unseal individual docket entries

## Notes
- [User research report on sealing. ](https://drive.google.com/file/d/1MhGcaIpT7TDfEO1t9HoZrQl1iv6F8lvX/view?usp=sharing)
- Sealing/unsealing individual docket entries and addressing migration sealing issues will be done in future separate stories.
- Add message to confirm they want to unseal the case that says "Are you sure you want to unseal this case?"

## Tasks
- [x] Add backend (proxy, lambda, etc.) for unsealing a case
- [x] Update UI to show modal, new unlock icon to unseal a case
- [x] Update authorization so only Docket Clerk/CotC can unseal a sealed case
- [x] Verify unsealed case is returned during order search
- [x] DOD: Write integration test 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
# Design
## Case Detail update
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6a5c3413-07fe-4974-b4a8-484029097613)


**Unseal case button**
* Display this button if: 
* Docket clerk is logged in
* Case is sealed 

On click of Unseal case button, display confirmation modal  


## Confirmation modal - Unseal a case 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/09130299-422a-4362-9636-483fbe716468)
Display docket number and case title 

**On Cancel**
modal closes, no update 

**On Yes, Unseal Case**
Case is no longer sealed 
Sealed banner no longer displays in header 
Unseal case button is hidden (docket clerk only)
Seal case button displays (docket clerk only)

**Comment by cholly75** [comment]
@klohman Design approved!

**Comment by klohman** [comment]
### Test Cases 4251 

#### 1) Docket clerk views sealed case 
* Login as docket clerk 
* Go to case 1
    * Case is sealed 
    * Case has a served Order 
        * Keyword - glacier
* Go to Case Information tab 
Expected results 
- [x] Unseal case button displays in Case Details card 

#### 2) Docket clerk unseals a case 
* Scenario 1 
* Click Unseal case button 
* Click Yes, Unseal Case button
Expected results 
On click of Unseal case button 
- [x] Confirmation modal displays 

On click of Yes, Unseal case:
- [x] Case is no longer sealed 
- [x] Sealed banner no longer displays in header 
- [x] Unseal case button is hidden
- [x] Seal case button displays 

#### 3) Docket clerk unseals a case and court users view case 
* Scenario 2
* Login as court user (other than docket or clerk of court) 
* Go to case 1
* Go to Case Information 
Expected results 
 - [x]  Sealed banner does not display in header 

#### 4) Docket clerk unseals a case and public users search for case 
* Scenario 2 
* Go to public search 
* Search for case 1 by docket number 
* Search for case 1 by case title 
Expected results 
Search by docket 
- [x] App navigates to Case 1 Public View of Docket Record 
Search by case title 
- [x] Case 1 displays in search results 

#### 5) Docket clerk unseals a case and public users searches for Order in case 
* Scenario 2 
* Go to public search 
* Search for Order by keyword - glacier 
Expected results 
- [x] Order from case 1 displays in search results

**Comment by cholly75** [comment]
Discussed with @mrinsin - this functionality will only apply to cases created post-go live or legacy cases that have no sealed individual entries for now, until the logic that deems cases sealed if any individual documents are sealed is reversed. We will add that AC to the upcoming stories for unsealing document entries.

**Comment by cholly75** [comment]
A bit more detail: right now the behavior that governs sealing means that if there are any individually sealed docket entries the whole case is considered sealed. Therefore, unsealing a case that still has sealed docket entries will not in fact unseal the case. As we have not been able to seal individual docket entries since go-live, the presumption is that any case created since then will not contain these sealed entries, and therefore will be able to be unsealed. This will need to be communicated to the Court prior to going live with this.
