### ISSUE TITLE
Docket Clerk: Seal an individual document from the public

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7042]
As the Court, in order to protect the contents of a filing, we need the ability for a Docket Clerk to seal a individual document within a case from the public.

ustaxcourt/ef-cms#7164 -- back-end work to allow the sealed flag at the document level

ustaxcourt/ef-cms#8120 -- companion story to develop to seal a document from all users who are not Court employees

## Pre-Conditions:
ustaxcourt/ef-cms#7041
ustaxcourt/ef-cms#8090

## Acceptance Criteria:
* Docket Clerk has the ability to seal an individual document within a case.
* When sealing the document, the Docket clerk must explicitly indicate they are sealing the document from the public
* When a document is "Sealed from the public," it is only sealed (non-viewable) from the public.  Parties/practitioners/IRS counsel on the case can still view it.
* Court users can view "Sealed from the public" documents.
* Sealing an individual document does *not* seal the whole case.
* Docket record indicates whether or not a particular document is sealed, and to whom
* Sealing an Order from the public removes it from being returned as a result in an Order Search for the public
* Opinions cannot be sealed.

## Notes
* [User research study on sealing.](https://drive.google.com/file/d/1MhGcaIpT7TDfEO1t9HoZrQl1iv6F8lvX/view?usp=sharing)
* What is the desired visibility on the Docket Record for a sealed document w/r/t a public view? Do we display the entry with a sealed indicator, or omit the entry entirely? --- *The former*
* Are there other exceptions to what can be sealed other than Opinions? - *no*
* Deploy alongside ustaxcourt/ef-cms#8120
* Need to test w/ IRS

## Tasks
- [x] Add Seal button - mob ustaxcourt/ef-cms-flexion#9374
- [x] Add Seal Document Modal - mob ustaxcourt/ef-cms-flexion#9374
- [x] Add tooltip on hover of the status column (sealed to the public) - mob ustaxcourt/ef-cms-flexion#9382
- [x] Seal document permission - mob ustaxcourt/ef-cms-flexion#9374
- [x] Seal Document endpoint - mob ustaxcourt/ef-cms-flexion#9375
- [x] Migration?
  - [x] delete `hasSealedDocuments` off all Case entities - mob ustaxcourt/ef-cms-flexion#9393 
  - [x] set `sealedTo` for `isLegacySealed` docket entries - mob ustaxcourt/ef-cms-flexion#9393 
- [x] Fix externalUserOrderAdvancedSearch integration test  - mob ustaxcourt/ef-cms-flexion#9393 
- [x] Remove hasSealedDocuments  - mob ustaxcourt/ef-cms-flexion#9393 
- [x] Replace `isSealed` with `isDocketEntrySealed` and `isCaseSealed` in InternalDocumentSearchResult to make searchClient results clearer  - mob ustaxcourt/ef-cms-flexion#9393 
- [x] Require `sealedTo` when `isSealed` is true - mob ustaxcourt/ef-cms-flexion#9393 

## Test Cases
* Docket clerk seals document from public for a Case which is sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is sealed
* Docket clerk seals document from public for a Case which is not sealed; docket record indicates document is sealed to public; parties/practitioners/court employees can access sealed document and view in DAWSON; public cannot view document; case itself is not sealed
* Docket clerk seals Order from public for a Case which is sealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is sealed
* Docket clerk seals Order from public for a Case which is unsealed; docket record indicates Order is sealed to public; parties/practitioners/court employees can access sealed Order and view in DAWSON; public cannot view Order; Order is not returned in Order Search results in public Order Search; Order is returned in Order Search results for all others; case itself is not sealed

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
Reverse logic that if any document is "Sealed in Blackstone", the whole case is sealed. [Should this be it's own story? Maybe with the unseal a case story] - edited from original story

**Comment by cholly75** [comment]
Split story between public and all sealing - @cholly75

**Comment by swongCO** [comment]
Figma mockup: https://www.figma.com/file/yQwciZR2mvGT024eYarnGu/USTC-Docket-Record-Seal-Unseal-Docket-Items-4252-9147

![USTC Docket Record Seal Doc.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4f10d5f6-773c-4438-b7df-875906109c4e)

- Add "Seal" icon text links under Edit link
- When a document is sealed, show "Unseal" icon link in red
- Keep the current functionality of adding the lock icon in the status column when a document is sealed
- Specs for developers:
![USTC Docket Record SPECS.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e055b439-1e5c-4909-bdbd-8a5dc5064302)

**Comment by swongCO** [comment]
![USTC Docket Record Seal modal.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e60d4920-c099-48b7-a1f8-ef39205c56f1)

- When Seal link is clicked, display modal
- The modal will have two options to choose from
- The first option (Seal to the public) will be selected by default

**Comment by swongCO** [comment]
![USTC Docket Record hover tips.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/2852ed38-2698-49be-8f22-1cd957404f81)

- When the user hovers over the Unseal link, display text to indicate the action and type of seal applied:
Unseal to the public and parties of this case
Unseal to the public
- **If this doesn't conflict with the current functionality,** in the status column, add hover text on the lock icon to indicate the type of seal applied:
Sealed to the public and parties of this case
Sealed to the public
- NOTE: only one hover tip will display at a time

**Comment by ttlenard** [comment]
**### Test Cases**

1. Docket Clerk seals a document on a Sealed Case
- Log in as docket clerk
- Navigate to a Sealed Case (ex: 11288-21)
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6491.
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- The first option "Seal to the Public" will be auto-selected by default - keep the default selection
- Select "Seal"

Expected results

- [x] The modal will close, and a red lock icon will appear next to the document name on docket index ustaxcourt/ef-cms#6491
- [x] The far right column will now have the text "Unseal" displayed as a Red link
- [x] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public"
- [x]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public"
- [x] The red banner at the top of the screen will still be present - indicating that the entire case is sealed.

**2. Parties associated with a case can view sealed documents in Sealed cases.** 
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the Sealed case that you used in test case ustaxcourt/ef-cms#6491.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the sealed case from Test ustaxcourt/ef-cms#6491
- Navigate to the sealed case

Expected Results
- [x] As Petitioner, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [x] As Participant, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [x] As Intervenor, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [x] As Private Practitioner, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [x] As IRS Respondent, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [x] The red banner at the top of the screen will be present for all of these users, indicating that the Case is sealed

**3. Public users can NOT view sealed documents in a sealed case**
- As a public non-logged in user, type in the Docket # of the Sealed case you used in Test Case ustaxcourt/ef-cms#6491

Expected Results:
- [x] You should see the "This case is sealed and not accessible to the public" message


**4. Court users can access and view documents that have been "sealed to public" in a sealed case.**

- Log in as a court user (ex: ADC)
- Navigate to the sealed case that you used in Test case ustaxcourt/ef-cms#6491
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results

- [x] Docket index ustaxcourt/ef-cms#6491 (or whatever document you sealed) is available as a hyperlinked document on the docket record.
- [x] The red lock icon will appear next to the document name on the docket record.
- [x] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public"
- [x] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [x] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [x] Click on the document, and you should be able to view it.

**5. Docket Clerk seals a document on an unsealed Case**
- Log in as docket clerk
- Navigate to an unsealed case in any status other than "New"
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6491.
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- The first option "Seal to the Public" will be auto-selected by default - keep the default selection
- Select "Seal"

Expected results

- [x] The modal will close, and a red lock icon will appear next to the document name on docket index ustaxcourt/ef-cms#6491
- [x] The far right column will now have the text "Unseal" displayed as a Red link
- [x] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public"
- [x]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public"
- [x] The red banner that indicates that a case is sealed will NOT be present at the top of the screen.

**6. Parties associated with a case can view sealed documents in an unsealed case.** 
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the unsealed case that you used in test case ustaxcourt/ef-cms#6494.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above from test case 5
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the unsealed case from Test ustaxcourt/ef-cms#6494
- Navigate to the unsealed case

Expected Results
- [x] As Petitioner, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [x] As Participant, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [x] As Intervenor, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [x] As Private Practitioner, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [x] As IRS Respondent, you should be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [x] The red banner at the top of the screen will NOT be present on this case for any of these users

**7. Public users can NOT view sealed documents in a unsealed case**
- As a public non-logged in user, type in the Docket # of the unsealed case you used in Test Case ustaxcourt/ef-cms#6494

Expected Results:
- [x] You should see the "normal" docket record view with no links to documents (unless it is an unsealed Order, or an Unsealed Opinion - these documents will be active links)
- [x] Lock symbol is present next to the document name for the sealed document 


**8. Court users can access and view documents that have been "sealed to public" in an unsealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the unsealed case that you used in Test case ustaxcourt/ef-cms#6494
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results

- [x] Docket index ustaxcourt/ef-cms#6491 (or whatever document you sealed) is available as a hyperlinked document on the docket record.
- [x] The red lock icon will appear next to the document name on the docket record.
- [x] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public"
- [x] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [x] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [x] Click on the document, and you should be able to view it.

**9. Docket Clerk seals an Order on a Sealed Case**
- Log in as docket clerk
- Navigate to a Sealed Case (ex: 20988-21)
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms-flexion#4.  (Or, of you used a different Sealed case, be sure that the document you are sealing is an Order)
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- The first option "Seal to the Public" will be auto-selected by default - keep the default selection
- Select "Seal"

Expected results

- [x] The modal will close, and a red lock icon will appear next to the Order name on docket index ustaxcourt/ef-cms-flexion#4
- [x] The far right column will now have the text "Unseal" displayed as a Red link
- [x] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public"
- [x]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public"
- [x] The red banner at the top of the screen will still be present - indicating that the entire case is sealed.

**10. Parties associated with a case can view sealed Orders in Sealed cases.**
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the Sealed case that you used in test case ustaxcourt/ef-cms-flexion#9.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the sealed case from Test ustaxcourt/ef-cms-flexion#9
- Navigate to the sealed case

Expected Results
- [x] As Petitioner, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#9
- [x] As Participant, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#9
- [x] As Intervenor, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#9
- [x] As Private Practitioner, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#9
- [x] As IRS Respondent, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#9
- [x] The red banner at the top of the screen will be present for all of these users, indicating that the Case is sealed

**11. Public users can NOT view sealed Orders in a sealed case**
- As a public non-logged in user, type in the Docket # of the Sealed case you used in Test Case ustaxcourt/ef-cms-flexion#9

Expected Results:
- [x] You should see the "This case is sealed and not accessible to the public" message

**12. Court users can access and view Orders that have been "sealed to public" in a sealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the sealed case that you used in Test case ustaxcourt/ef-cms-flexion#9
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results

- [x] Docket index ustaxcourt/ef-cms-flexion#4 (or whatever Order you sealed) is available as a hyperlinked document on the docket record.
- [x] The red lock icon will appear next to the Order name on the docket record.
- [x] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public"
- [x] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [x] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [x] Click on the Order, and you should be able to view it.


**13. Public user should not have search results returned for sealed Orders in sealed cases when using the Order search**
- Navigate to the Search screen as a non-logged in public user.
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#9 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
- Click Search

Expected Results:

- [x] You should see either see the "No Matches found" message or the sealed Order should never appear in the search results.

**14. (associated) Private Practitioner, (associated) IRS Respondent, and Court users should have search results returned for sealed orders in sealed cases when using the Order Search.**
- Log in as each of these roles to perform this test: Private Practitioner, IRS Respondent, and various Court users
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#9 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
- Click Search

Expected Results:
- [x] (privatePractitioner) Sealed Order from Test case ustaxcourt/ef-cms-flexion#9 should be available in the search results.
- [x] The red lock symbol should be next to the Order name in the search results. 
- [x] (IRS Respondent) Sealed Order from Test case ustaxcourt/ef-cms-flexion#9 should be available in the search results.
- [x] (court user) Sealed Order from Test case ustaxcourt/ef-cms-flexion#9 should be available in the search results.

**15. Docket Clerk seals an Order on a unsealed Case**
- Log in as docket clerk
- Navigate to an unsealed Case (ex: 4856-21)
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6497.  (Or, of you used a different unsealed case, be sure that the document you are sealing is an Order)
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- The first option "Seal to the Public" will be auto-selected by default - keep the default selection
- Select "Seal"

Expected results

- [x] The modal will close, and a red lock icon will appear next to the Order name on docket index ustaxcourt/ef-cms#6497
- [x] The far right column will now have the text "Unseal" displayed as a Red link
- [x] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public"
- [x]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public"
- [x] There will be no red banner at the top of the screen on this case - indicating that the entire case is unsealed.

**16. Parties associated with a case can view sealed Orders in unsealed cases.**
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the unsealed case that you used in test case ustaxcourt/ef-cms-flexion#15.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the unsealed case from Test ustaxcourt/ef-cms-flexion#15
- Navigate to the unsealed case

Expected Results
- [x] As Petitioner, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#15.  Red lock icon should be next to the Order name.
- [x] As Participant, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#15. Red lock icon should be next to the Order name.
- [x] As Intervenor, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#15. Red lock icon should be next to the Order name.
- [x] As Private Practitioner, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#15. Red lock icon should be next to the Order name.
- [x] As IRS Respondent, you should be able to view the sealed Order from test case ustaxcourt/ef-cms-flexion#15. Red lock icon should be next to the Order name.
- [x] There will be NO red banner at the top of the screen for all of these users, indicating that the case is unsealed.

**17. Public users can NOT view sealed Orders in an unsealed case**
- As a public non-logged in user, type in the Docket # of the unsealed case you used in Test Case ustaxcourt/ef-cms-flexion#15

Expected Results:
- [x] You should see the docket record, but the link to the order should not be hyperlinked or clickable


**18. Court users can access and view Orders that have been "sealed to public" in an unsealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the unsealed case that you used in Test case ustaxcourt/ef-cms-flexion#15
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results

- [x] Docket index ustaxcourt/ef-cms#6497 (or whatever Order you sealed) is available as a hyperlinked document on the docket record.
- [x] The red lock icon will appear next to the Order name on the docket record.
- [x] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public"
- [x] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [x] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [x] Click on the Order URL, and you should be able to view it.

**19. Public user should not have search results returned for sealed Orders in unsealed cases when using the Order search**
- Navigate to the Search screen as a non-logged in public user.
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#15 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
- Click Search

Expected Results:

- [x] You should see either see the "No Matches found" message or the sealed Order should never appear in the search results.

**20. Private Practitioner or IRS Respondent associated with the case, and Court users should have search results returned for sealed orders in unsealed cases when using the Order Search.**
- Log in as each of these roles to perform this test: Private Practitioner, IRS Respondent, and various Court users
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#15 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that served the Order
- Click Search

Expected Results:
- [x] Sealed Order from Test case ustaxcourt/ef-cms-flexion#15 should be available in the search results.
- [x] The red lock symbol should be next to the Order name in the search results.

**Comment by rachelschneiderman** [comment]
After discussing with Chris and Tenille, legacy sealed docket entries will be migrated to be marked as sealed from the public.
