### ISSUE TITLE
Court: Send case message without document

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7044]
As a Court Employee, so that I can send a message that's case-related, I need the ability to send a message that's not tied to a document.

## Pre-Conditions

- ustaxcourt/ef-cms-flexion#4294 completed - prototype and testing

## Acceptance Criteria
* Court user can create a message that's not tied to a document
* Court user can create a message that's tied to a case
* Court user can send the message to another court user
* Receiver of message can see the message sent to them
* Section the receiver is in can see the message that was sent

## Notes
* Launch create message modal, w/ free text subject line
* Don't need document section of modal
* Launch create message from the case level actions
* Add case detail tabs
* We discussed something related to the completed section, but would that come later (in the "complete" story?)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create new entity for new messages (Rachael ustaxcourt/ef-cms-flexion#5389)
- [x] 2 Create persistence method to create a new message associated with a case (Rachael ustaxcourt/ef-cms-flexion#5397)
- [x] 3 Create endpoint to create a new message (Rachael ustaxcourt/ef-cms-flexion#5393)
- [x] 4 Add “Create New Message” to the actions dropdown on case detail header (Cody ustaxcourt/ef-cms-flexion#5391)
- [x] 5 Create “Create New Message” modal (Cody ustaxcourt/ef-cms-flexion#5391)
  - [x] 5a Dropdown functionality (select a section and recipient fills in) (Cody ustaxcourt/ef-cms-flexion#5391)
  - [x] 5b Validation (Cody ustaxcourt/ef-cms-flexion#5391)
- [x] 6 Sequences and actions to submit modal (Rachael ustaxcourt/ef-cms-flexion#5397)
- [x] 7 Create Message Detail view and route (Rachael ustaxcourt/ef-cms-flexion#5405)
- [x] 8 Create new tab at the top level navigation for new messaging (Rachael ustaxcourt/ef-cms-flexion#5401)
- [x] 9 Create endpoint to retrieve a single message for message detail screen (Rachael ustaxcourt/ef-cms-flexion#5398)
- [x] 10 Sequences, actions, computed for message detail screen (Rachael ustaxcourt/ef-cms-flexion#5405)
- [x] 11 Create new messaging inbox, sent box, completed box views (Rachael ustaxcourt/ef-cms-flexion#5401)
  - [x] 11a Tables, computeds (Matt ustaxcourt/ef-cms-flexion#5412, ustaxcourt/ef-cms-flexion#5416)
- [x] 12 Create endpoints to retrieve messages for new messaging boxes (Rachael ustaxcourt/ef-cms-flexion#5409)
  - [x] 12a get user inbox
  - [x] 12b get section inbox (Rachael)
  - [x] 12c get user outbox (Rachael)
  - [x] 12d get section outbox (Rachael)
- [x] 13 Create new stack for messages (Rachael ustaxcourt/ef-cms-flexion#5393)
- [x] 14 Create new elasticsearch index for messages (Rachael ustaxcourt/ef-cms-flexion#5409)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
