### ISSUE TITLE
Docket Clerk: Service for paper-scanned documents

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7046]
As a docket clerk, so that I can provide paper service for a paper-scanned document, I need the ability to print and mail the document. 

## Acceptance Criteria
* Docket Clerk can provide service (electronic and paper) for documents that are submitted in paper by parties in a case
* When serving a paper document, cover sheet should not be added until it's served
* If a docket entry has not been served, the docket record should say "Not Served"
* Docket Clerk has ability to save and serve a paper document immediately, or save for later
  * Implies that a Docket Clerk can come back to the document to serve it later

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- **Engineering**: see `followRedirectAction`
- The UI pieces are already present and computed in `shared/src/business/utilities/getFormattedCaseDetail.js` via `!result.isCourtIssuedDocument && result.isFileAttached === false;`-- double-check tests

## Tasks
- [x] Replace `Finish` with `Save and Serve` (Jojo ustaxcourt/ef-cms-flexion#5805)
- [x] Replace `Save and Add Another` with `Save for Later` (Jojo ustaxcourt/ef-cms-flexion#5805)
  - If no document present and click `Save and Serve`, show error message
- [x] Navigate to print paper receipt view on paper Docket Entry `Save and Serve` (Jojo/Kris ustaxcourt/ef-cms-flexion#5805)
  - PDF note: address page first, coversheet, then document
- [x] Serve document on `Save and Serve`, add coversheet when the document is served (Jojo/Kris ustaxcourt/ef-cms-flexion#5805)
  - Note: we have similar functionality somewhere
- [x] Remove `Add Another Entry` button (and its functionality)
- [x] Add `Save for Later` functionality
- [x] Add doc type to paper service preview view
- [x] UX feedback: save & serve bug on paper case (fails to complete QC on serve) (Jojo ustaxcourt/ef-cms-flexion#5835)
- [x] UX feedback: show confirm modal for save & serve (Jojo ustaxcourt/ef-cms-flexion#5870)
- [x] UX feedback: clear validation errors on submission on `save for later` (Jojo ustaxcourt/ef-cms-flexion#5870)
- [x] UX feedback: no hyperlink on docket record for docket entry without document uploaded (Cody)
- [x] UX feedback: hyperlink for Internal Users on docket record for docket entry with document uploaded but not served; NO hyperlink for External parties for docket entry with document uploaded but not served (Cody)
- [x] UX feedback: Docket entry without document uploaded should NOT show in "Add Documents" dropdown for sending messages (Jojo ustaxcourt/ef-cms-flexion#5882)
- [x] UX feedback: show served date and served parties on docket record for served documents (Jojo ustaxcourt/ef-cms-flexion#5840)
- [x] UX feedback: show served stamp on pdf (Jojo ustaxcourt/ef-cms-flexion#5840)
- [x] UX feedback: don't add coversheet on `save for later` (Jojo ustaxcourt/ef-cms-flexion#5840)
- [x] UX feedback: Saved for Later - with document added- docket entry should show the yellow background and icon (same as incomplete entry without document uploaded (Jojo ustaxcourt/ef-cms-flexion#5840)
- [x] UX feedback: Document should appear in the My Document /Section QC > In Progress box until it is served (it’s currently showing in the Processed box) (Jojo ustaxcourt/ef-cms-flexion#5865)
- [x] UX feedback: Hyperlink from My Document/Section QC > Processed box should navigate to Case Detail > Document View (Cody)
- [x] UX feedback: If Saved for Later w/o Document then went back to add document and serve - Docket entry still shows the incomplete icon / color - should show as complete entry (Cody. ustaxcourt/ef-cms-flexion#5858)
- [x] UX feedback - For pending docket entries, If a docket entry has not been served, the docket record should say "Not Served" - see design in comments (Cody ustaxcourt/ef-cms-flexion#5847)
- [x] On save and serve - if paper parties are on the case, app should route to Print Paper Service Documents screen (Cody ustaxcourt/ef-cms-flexion#5856)
- [x] UX feedback: preview document when editing/completing docket record (Jojo ustaxcourt/ef-cms-flexion#5865)
- [x] UX feedback: remove warning when document is already attached (Jojo ustaxcourt/ef-cms-flexion#5865)
- [x] UX feedback: verify functionality for documents that are not served is working correctly- see [url](https://github.com/flexion/ef-cms/issues/5525) (Jojo)
- [x] UX feedback: Date validation on save and serve for Received inconsistent (and annoying) (Jojo ustaxcourt/ef-cms-flexion#5899)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Jojo ustaxcourt/ef-cms-flexion#5924)
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by alsmith1** [comment]
![Screen Shot 2020-07-08 at 11.21.08 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/ba7fc52d-4152-444f-8d53-1defc8de521d)
Clicking “Save and Serve” will 
document should appear in My Document QC > Processed and Section Document QC > Processed
Clicking “Save and Serve” will
serve the document
allow docket clerks to print the paper receipt and mail to to the party
add document to the docket record
add served date and parties to docket record
add coversheet to the document once save and serve is clicked

**Clicking “Save for later” without a document**
- saves entry to the docket record without a link
- entry can be accessed through the document qc in progress tab and completed by entering a document and served
- docket record will say not served
- coversheet will not be added
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7173d2e2-7589-4fc1-aa63-f15160e414b7)

**Clicking “Save for later” with a document**
- saves entry to the docket record with a link
- entry can be accessed through the document qc in progress tab and completed by entering a document and served
- docket record will say not served
- coversheet will not be added
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f094cfdf-132b-4379-8355-4144da333099)

![Screen Shot 2020-07-08 at 11.21.16 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/8dd00607-79ca-44b6-9204-fa621f41d9e9)
If a document is not scanned or uploaded and user clicks on save and serve error messages will display
- Page level error: Please Correct the following errors:   Scan or upload a document to serve, or click Save for later to serve at a later time

- In line error:     Scan or upload a document to serve, or click Save for later to serve ar a latr time


![Screen Shot 2020-07-09 at 10.24.11 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/4c970780-af08-4bf2-a0ae-85226bc0e7bd)
- After clicking “Save and Serve” page will redirect to the print receipt page (for paper filers)
- Clerk will print page and mail document to the paper filing parties
- Clicking the done button will open up a modal to confirm print service is complete

*Order and contents of PDF
- Address page
- Cover sheet
- PDF

Warning banner displays to give notification clerk must print/mail document to complete paper service

Done button directs user to the docket record


![Screen Shot 2020-07-08 at 11.21.36 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/901b0876-22e2-4773-b83f-fbf0655a4862)
Upon completing the print paper service docket record displays with success message

Save and served
document should appear in My Document QC > Processed and Section Document QC > Processed
Clicking “Save and Serve” will
serve the document
allow docket clerks to print the paper receipt and mail to to the party
add document to the docket record
add served date and parties to docket record
add coversheet to the document once save and serve is clicked

Save for later with or without document
- document link is not visible
- yellow background for row, pin icon displays next to entry name
- displays not served in served column in red semi bold
- clerk will need to go to document qc in progress tab to add document and serve entry

![Screen Shot 2020-07-08 at 11.21.45 AM.png](https://images.zenhubusercontent.com/5d766a771251c6000116623d/34aae606-5539-4a63-b179-77c1cb691e52)
Docket clerks get tot he edit docket entry page from the Document QC > in progress folder
Once they have uploaded a document,  edit the data, reviewed the data:

Clicking “Save and Serve” will 
document should appear in My Document QC > Processed and Section Document QC > Processed
Clicking “Save and Serve” will
serve the document
allow docket clerks to print the paper receipt and mail to to the party
add document to the docket record
add served date and parties to docket record
add coversheet to the document once save and serve is clicked

Clicking “Save for later” with and without a document
- saves entry to the docket record without a link
- entry can be accessed through the document qc in progress tab and completed by entering a document and served
- docket record will say “not served”
- coversheet will not be added

**Comment by klohman** [comment]
UX feedback
- Incomplete docket entry - when “Saved for Later” without document uploaded
    - the docket entry should not be hyperlinked 


- Saved for Later - with document added
    - docket entry should show the yellow background and icon (same as incomplete entry without document uploaded
    - docket entry should not be hyperlinked until served.
    - Document should appear in the My Document /Section QC > In Progress box until it is served (it’s currently showing in the Processed box) 
    - Cover sheet should not be applied until the document is served 

- On Save and Serve 
    - getting an error message when serving (but the document is still showing on the docket record) 
    - On click of Save and Serve, we should display the service confirmation modal and make the user confirm before actually serving  (use the “Are You Ready to Initiate Service?” Modal)
    - Served date and served Parties should populate on docket entry when served 
    - Served stamp should be applied to cover sheet 
    - Unable to test service emails and the navigation to “Print” screen because of errors 

Saved for Later w/o Document
    - Should not trigger error “Upload a Document” (if you click Save and Serve and get error and then click Save for Later, displaying error still)


- Saved for Later w/o Document then went back to add document and serve 
    - Docket entry still shows the incomplete icon / color
    - Document link from Processed box should navigate to Case Detail > Document View (it’s currently still navigates to Edit)

**Comment by klohman** [comment]
## Updated Test Scenarios 
Test data 
* Case xx1-20
    * Petitioner = paper service 
* Case xx2-20
    * Petitioner = electronic service 


#### 1) Docket clerk adds docket entry for paper document without PDF uploaded and saves
* Login as docket clerk 
* Navigate to case xx1-20
* Click Add Docket Entry from Actions menu
* Select “Administrative Record” as doc type 
* Complete form but do not upload PDF 
* Click Save for Later 
Expected results 
- [ ] App navigates to Case Detail > Docket Record with success message displayed 
- [ ] Administrative Record displays on Docket Record as pending entry (yellow icon, etc.)
- [ ] Administrative Record entry displays “Not Served” under Served column 
- [ ] Administrative Record is not hyperlinked 
- [ ] Administrative Record displays in My Document / Section Document QC > In Progress

#### 2) Docket clerk adds docket entry for paper document with PDF uploaded and saves 
* Login as docket clerk 
* Navigate to case xx1-20
* Click Add Docket Entry from Actions menu
* Select “Motion for New Trial” as doc type 
* Complete form and upload PDF 
* Click Save for Later 
Expected results 
- [ ] App navigates to Case Detail > Docket Record with success message displayed 
- [ ] Motion for New Trial displays on Docket Record as pending entry 
- [ ] Motion for New Trial entry displays “Not Served” under Served column 
- [ ] Motion for New Trial is hyperlinked for internal users and navigates to Document View 
- [ ] Motion for New Trial entry is visible for external parties but not hyperlinked
- [ ] Motion for New Trial displays in My Document / Section Document QC > In Progress
- [ ] Motion for New Trial PDF does not display cover sheet 

#### 3a) Docket clerk adds docket entry for paper document (PDF uploaded) in case with paper service parties and saves and serves 
* Login as docket clerk 
* Navigate to case xx1-20 
* Click Add Docket Entry from Actions menu
* Select “Motion for Continuance” as doc type 
* Complete form and upload PDF 
* Click Save and Serve 
* Confirm service on modal 
Expected results 
On click of Save and Serve, 
- [ ] display “Are you sure you want to initiate service” modal 
On click of “Yes,  Serve”
- [ ] App navigates to Print Paper Service Document screen with PDF in viewer 
- [ ] PDF on Print Paper Service screen displays Address Page, Cover Sheet, and original document 
- [ ] Cover sheet includes Served stamp with date 
- [ ] Motion for Continuance entry displays served date and parties (“B”) on docket entry
- [ ] Motion for Continuance entry displays blue “paper document” icon
- [ ] Motion for Continuance is hyperlinked on docket entry and navigates to Document View
- [ ] Motion for Continuance displays in My Document / Section Document QC > Processed 

#### 3b) Docket clerk adds docket entry for paper document (PDF uploaded) in case with paper service parties and saves and serves (after print)
* Scenario 3a
* Click “Done” on Print Paper Service Documents screen 
Expected results: 
- [ ] App navigates to Case Detail> Docket Record with success message displayed 

#### 4) Docket clerk adds docket entry for paper document (PDF uploaded) in case without paper service parties and saves and serves 
* Login as docket clerk 
* Navigate to case xx2-20 
* Click Add Docket Entry from Actions menu
* Select “Answer” as doc type 
* Complete form and upload PDF 
* Click Save and Serve 
* Confirm service on modal 
Expected results 
On click of Save and Serve, 
- [ ] display “Are you sure you want to initiate service” modal 
On click of “Yes,  Serve”
- [ ] App navigates to Case Detail> Docket Record with success message displayed  
- [ ] Cover sheet is added to PDF and includes Served stamp with date 
- [ ] Answer entry displays served date and parties (“B”) on docket entry
- [ ] Answer entry displays blue “paper document” icon
- [ ] Answer is hyperlinked on docket entry and navigates to Document View 
- [ ] Answer displays in My Document / Section Document QC > Processed 

#### 5) External parties can view docket entries for un-served documents but cannot access PDF
* Login as privatePractitioner 
* Search for case xx1-20 
* Click Request Access 
* Complete Form
* View Docket Record 
Expected results 
- [ ] Administrative Record entry displays on docket record with “Not Served” 
- [ ] Administrative Record is not hyperlinked 
- [ ] Motion for New Trial entry displays on docket record with “Not Served”
- [ ] Motion for New Trial is not hyperlinked 

#### 6) Docket clerk serves a document that was saved for later (without document uploaded) 
* Scenario 1 
*  Navigate to My Document QC > In Progress 
* Click on Administrative Record 
* Upload PDF 
* Click Save and Serve 
* Click Yes, Serve from modal
* Click “Done” on Print Document screen
Expected results 
On click of Administrative Record from My Document QC > In Progress:
- [ ] App navigates to Edit Docket Entry screen with warning message displayed 
On click of Yes, Serve on modal:
- [ ] App navigates to Print Paper Documents screen 
On click of Done: 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Administrative Record docket entry no longer displays as pending (with yellow icon, etc.) or Not Served message
- [ ] Administrative Record entry displays served date and parties (B) 
- [ ] Administrative Record entry is hyperlinked and navigates to Document View 
- [ ] Administrative Record PDF includes cover sheet with served stamp applied 
- [ ] Administrative Record no longer displays in My. Document QC/ Section Document QC > In Progress
- [ ] Administrative Record displays in My. Document QC/ Section Document QC > Processed 

#### 7) Docket clerk serves a document that was saved for later (with document uploaded) 
* Scenario 2 
*  Navigate to My Document QC > In Progress 
* Click on Motion for New Trial  
* Click Save and Serve 
* Click Yes, Serve from modal
* Click “Done” on Print Document screen
Expected results 
On click of Motion for New Trial  from My Document QC > In Progress:
- [ ] App navigates to Edit Docket Entry screen without warning message displayed 
- [ ] PDF preview displayed the uploaded document 
On click of Yes, Serve on modal:
- [ ] App navigates to Print Paper Documents screen 
On click of Done: 
- [ ] App navigates to Docket Record with success message displayed 
- [ ] Motion for New Trial docket entry no longer displays as pending (with yellow icon, etc.) or Not Served message
- [ ] Motion for New Trial entry displays served date and parties (B) 
- [ ] Motion for New Trial entry is hyperlinked and navigates to Document View 
- [ ] Motion for New Trial PDF includes cover sheet with served stamp applied 
- [ ] Motion for New Trial no longer displays in My. Document QC/ Section Document QC > In Progress
- [ ] Motion for New Trial displays in My. Document QC/ Section Document QC > Processed 

#### 8) External parties can view docket entries for served documents but cannot access PDF
* Scenario 7
* Login as privatePractitioner 
* Search for case xx1-20 
* View Docket Record 
Expected results 
- [ ] Motion for New Trial entry displays on docket record with served date and parties (B)
- [ ] Motion for New Trial is hyperlinked and opens PDF in new tab
