### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *ENTERING* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7047]
As a Petitions Clerk, so that I may enter a paper petition and QC it all at the same time, I need the petition workflow revamped to accommodate my needs. 

## Acceptance Criteria
* Petitions Clerk is able to QC and enter a paper Petition all at one time
* Petitions Clerk can immediately serve a paper Petition after the QC process has been completed (Note: moving away from batching and implementing real-time service)
* Petitions Clerk has the option to save a Petition after the QC process and come back later and serve
* If a Petition is saved to "In Progress" that Petition should stay there until served to IRS [Note: In Progress Petitions should never auto-delete]
* Ability to copy the primary contact address and phone to the secondary contact address and phone

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* ODS is required for Corporation and all the Partnership party types - need to update tests

## Tasks
- [x] 1 Parties tab is default tab selected on load (Rachael)
- [x] 2 Party type (Rachael)
	•	Required field
	•	On select, display contact fields depending on party type selected
	•	Party contact information is used to repopulate Case caption on Case Info tab
	•	If party contact information is edited on Parties tab, the autogenerated case caption updates as well
- [x] 3 Party type = Petitioner & Spouse (Rachael)
	•	If Petitioner & Spouse is selected, display primary and secondary contact fields
	•	Display checkbox “Use same address & phone number as above for spouse information
- [x] 4 Use same address as above checkbox (Rachael)
	•	On check, copy primary contact information to secondary contact form, including
	◦	Country
	◦	Mailing address line 1
	◦	Address line 2
	◦	Address line 3
	◦	City
	◦	State
	◦	Zip
	◦	Phone number
	•	Copied contact fields are editable
	•	If edit is made to primary contact field when checked, edit should copy to secondary contact form
	•	If edit is made to secondary (spouse) contact field when checked, edit should not copy to primary contact form
- [x] 5 Order for Ownership Disclosure Statement (Rachael ustaxcourt/ef-cms-flexion#4956)
	•	If party type = Corporation, Partnership (as the Tax Matters Partner), Partnership (as a partnership representative under BBA regime), or Partnership (as a partner other than Tax Matters Partner) - check box is displayed and auto-checked
	•	If user uploads ODS PDF, checkbox is auto-unchecked
- [x] 6 Date received (Rachael)
	•	Required field
- [x] 7 Mailing date (Rachael)
	•	Required field
- [x] 8 Case Caption (Rachael)
	•	Is required
	•	if primary / secondary contact information has been entered on Parties tab, case caption field Is autogenerated and is editable
	•	if primary / secondary contact information has NOT been entered on Parties tab, case caption field is blank and editable
	•	If party contact information is edited on Parties tab, the case caption updates as well
	•	If case caption field is manually edited on the Case Info tab, the party contact information is not updated
- [x] 9 Case procedure (Rachael ustaxcourt/ef-cms-flexion#4958)
	•	Is required
	•	Default selection is Regular
- [x] 10 Order to Show Cause checkbox (Rachael)
	•	Is optional
	•	Is always displayed
- [x] 11 Trial Location (Rachael)
	•	Field is required IF an RQT PDF is uploaded; otherwise it’s optional
	•	If Regular case procedure is selected, the trial location dropdown displays the list of regular case locations
	•	If Small case procedure is selected, the trial location dropdown displays the list of small case locations
- [x] 12 Order for Place of Trial (Rachael ustaxcourt/ef-cms-flexion#4962)
	•	If Trial Location field is blank and RQT PDF is not uploaded = checkbox auto-checked
	•	If Trial Location is selected = checkbox is unchecked
- [x] 13 Fee paid? (Rachael ustaxcourt/ef-cms-flexion#4967)
	•	If Paid is selected, display Payment date (required) and Payment method (required)
	•	If Not Paid is selected, display “Order for Filing fee checkbox” = auto-checked
	•	If Waived is selected, display Date waived (required)
- [x] 14 Orders needed (Rachael)
	•	Optional
- [x] 15 Notice attached to Petition (Matt ustaxcourt/ef-cms-flexion#4970)
	•	Is required
	•	If Yes is selected, display Type of Case (required) and Date of Notice (optional)
	•	If No is selected, display Type of Case (required)
- [x] 16 Type of Case (Matt - per discussion with Kristen, setting default value for notice attached to No, so this won't be an issue any further)
	•	Field hidden until Notice attached to Petition selection is made
- [x] 17 Petition PDF Upload
	•	Is required
- [x] 18 STIN PDF Upload
 	•	Is required
- [x] 19 RQT PDF Upload (Matt ustaxcourt/ef-cms-flexion#4973)
	•	Is required IF Trial location field is selected
	•	Is optional IF Trial location field is blank
- [x] 20 ODS PDF Upload (Rachael ustaxcourt/ef-cms-flexion#4974)
	•	Is required if party type = Corporation, Partnership (as the Tax Matters Partner), Partnership (as a partnership representative under BBA regime), or Partnership (as a partner other than Tax Matters Partner) AND Order for Ownership Disclosure Statement is unchecked
	•	If uploaded, Order for Ownership Disclosure Statement is auto-unchecked ![image.png]
- [x] 21 APW PDF Upload (Rachael ustaxcourt/ef-cms-flexion#4971)
	•	is required if Fee paid = Waived
	•	error message if blank and Fee paid = Waived: "Upload or scan an APW"

Refactoring:
- [x] 1 Update PROCEDURE_TYPES constant on Case entity to be a map instead of array, so we can access it like "PROCEDURE_TYPES.regular" (Rachael ustaxcourt/ef-cms-flexion#4974)
- [x] 2 navigateToReviewPetitionFromPaperSequence and gotoReviewPetitionFromPaperSequence (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
