### ISSUE TITLE
Court User: Ability to search and return results for attorneys

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7049]
As a court user, so that I may determine if attorneys are registered with the court, I need the ability to search for attorneys and see their data.

## Acceptance Criteria
* Court user can search for an attorney by name and by bar number- discuss combined name field + elastic search
* Court user can see attorney data in the system (one of the fields admitted/not admitted)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create search results table view, paging (Rachael ustaxcourt/ef-cms-flexion#4855)
- [x] 2 Create endpoint to get search results by name (using elasticsearch) (Rachael ustaxcourt/ef-cms-flexion#4854)
- [x] 3 Sequences, actions to submit a search (Rachael ustaxcourt/ef-cms-flexion#4855)
- [x] 4 Create practitioner detail view, route, sequence, computed for formatting (Matt, Cody ustaxcourt/ef-cms-flexion#4865)
- [x] 5 Create endpoint to get practitioner details (Matt ustaxcourt/ef-cms-flexion#4865)
- [x] 6 Sequences, actions to get practitioner details and route to page (Matt ustaxcourt/ef-cms-flexion#4865)
- [x] 7 Add valid admissions statuses to Attorney entity and validation (Rachael ustaxcourt/ef-cms-flexion#4857)
- [x] 8 Fix Clear Search buttons on practitioner search (Rachael ustaxcourt/ef-cms-flexion#4859)
- [x] 9 Refactoring: rename Attorney -> Practitioner throughout (createAttorneyUser, updateAttorneyUser, etc) (Rachael ustaxcourt/ef-cms-flexion#4863)
- [x] 10 Case-sensitivity in bar number search (Rachael ustaxcourt/ef-cms-flexion#4874)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html  (Matt)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required) (Matt)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Matt)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
