### ISSUE TITLE
Admissions Clerk: Update Attorney data in Attorney Database

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7050]
As an Admissions Clerk, so that I may ensure the data in the practitioner/respondent database is accurate, I need the ability to edit and save practitioner data.

## Acceptance Criteria
* New Admissions Clerk role is created
* Admissions Clerk can edit and save Attorney data within the database
* Where attorney data currently displays, updated data displays in all open cases and any case that has been closed for 6 months or less
* When an attorney makes a change to their contact information on their dashboard, it updates the database [this is already done]
* When either the Admissions Clerk or Attorney updates their data, a notice of change of address is generated, added to docket record and served to parties in the case (only on open cases or those closed for 6 mo or less)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Don't allow editing of email address
* Only data that displays is address and phone number
* Just updating what displays in the UI for this story. Any ties to Cognito or login are not part of this story. 

## Tasks
- [x] 1 Add Edit link to practitioner detail view for admissions clerks only (Rachael ustaxcourt/ef-cms-flexion#4926)
- [x] 2 Move form elements from Add Practitioner form into separate component to be reused for editing (Rachael ustaxcourt/ef-cms-flexion#4927)
- [x] 3 Create Edit Practitioner Details view and route (Rachael ustaxcourt/ef-cms-flexion#4927)
- [x] 4 Create endpoint for editing practitioner details (Cody)
- [x] 5 Sequences, actions for validating and submitting the form (Rachael ustaxcourt/ef-cms-flexion#4927)
- [x] 6 If address and/or phone number are changed, create a Notice of Change of Address/Phone on associated cases; also update practitioner data on all associated cases (#4928 Cody)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
