### ISSUE TITLE
Admissions Clerk: Ability to add Attorneys to the Attorney Database

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7051]
As an Admissions Clerk,  so I can ensure the accuracy of the Attorney Database, I need the ability to add new Attorneys to the database. 

## Acceptance Criteria
* Admissions Clerk can add a new Attorneys to the database
* New Attorneys are assigned an auto-generated Bar No. 
* Auto-generated Bar No. needs to be unique for each attorney 
* Adding an Attorney to this stand-alone database will create an active user in Cognito

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Admission date - date they were admitted to the tax court bar, not the date they were added to the system
* Bar Number Format -----  {Last_Initial}{First_Initial}{YY}{count}; where count is a 3-digit number that resets and starts at 001 each year and is the cumulative number of new practictioners for a given for that year.
   * Example: Matt Hopson is the 10th new practitioner created in 2021, his bar number would be `HM21010`

## Tasks
- [x] 1 Add Practitioner button (Admissions Clerk only) and Add Practitioner form view (modify / reuse current create practitioner flow?) (Cody ustaxcourt/ef-cms-flexion#4884)
- [x] 2 Submit add practitioner (use existing if possible? Cody ustaxcourt/ef-cms-flexion#4897)
- [x] 3 Generate bar number and make required on practitioner? (Matt ustaxcourt/ef-cms-flexion#4880)
- [x] 4 Create practitioner validation (Team mob ustaxcourt/ef-cms-flexion#4892 ustaxcourt/ef-cms-flexion#4894)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
