### ISSUE TITLE
Court: Attorney Database and Search UI

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7053]
As a court, so that we can search for attorneys, we need a database that houses all attorney data and search UI. 

## Acceptance Criteria
* Attorney database contains the following data fields:
   * BAR_NUMBER
   * LAST_NAME
   * FIRST_NAME
   * MIDDLE_NAME
   * SUFFIX
   * FIRM_NAME
   * ADDRESS_LINE_1
   * ADDRESS_LINE_2
   * CITY
   * STATE
   * ZIP_CODE
   * ADMISSIONS_DATE
   * ORIGINAL_BAR_STATE
   * BIRTH_YEAR
   * PRACTITIONER_TYPE
   * ADMISSIONS_STATUS
   * EMAIL_ADDRESS
   * ALTERNATE_EMAIL
   * PHONE_NO
   * ADDITIONAL_PHONE
   * IRS_EMPLOYEE (Y/N)
   * DOJ_EMPLOYEE (Y/N)
* Search UI created for internal court users
* Fields for search
   * Name
   * Bar Number
* Use sample practitioner/respondents: https://docs.google.com/spreadsheets/d/1CSMzj2DbogDV6qF_DLxisQaT00179K-I6ZgNiP_NZ5g/edit?usp=sharing
* Include bulk load with dummy data
* On bulk load, keep existing bar number
* Bulk load will generate Cognito accounts. (Use Flexion email account to verify login)

Note:
* Is there a cost for the number of Court users using Cognito - "MAU - monthly active users" -- the Court currently has about 150,000 practitioners and respondents
* https://aws.amazon.com/cognito/pricing/

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create Attorney entity that extends User entity (Rachael ustaxcourt/ef-cms-flexion#4671)
- [x] 2 Add Practitioner tab to Advanced Search, create form UI (Rachael ustaxcourt/ef-cms-flexion#4679)
- [x] 3 Create script to import attorneys from spreadsheet with all fields, update create attorney interactor to use the new Attorney entity (Rachael ustaxcourt/ef-cms-flexion#4678)
- [x] 4 Clean up code that was added in ustaxcourt/ef-cms#6683 and is no longer needed (Rachael ustaxcourt/ef-cms-flexion#4680)
- [x] 5 Change practitioner in our code to “privatePractitioner” and respondent to "irsPractitioner" (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [ ] Deployed to the stage environment
