### ISSUE TITLE
Practitioner: Generate and serve Notice when Practitioner changes address

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7055]
As a practitioner, so that parties may be notified that my address has changed, I need a change of address notice generated and served. 

## Acceptance Criteria
* When practitioner changes their address in the system, a notice is generated in each case in which they are attorney of record (already done) and served to all parties in each case
* When a Practitioner and IRS attorney updates their contact information, a notice only needs to be generated in open cases and cases that have been closed for less than 6 months

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- [ ] Stress testing - from Jessica: "For an IRS attorney, this could kick off several hundred notices at one time"

## Tasks
- [x] 1 Fix bug with practitioners changing their address, and add integration tests (Rachael et al ustaxcourt/ef-cms-flexion#4476)
- [x] 2 Verify that respondent can change their address
- [x] 3 After fixes, go through test scenarios and verify that everything is working as expected
- [x] 4 Stress testing (Rachael)
  * Create x quantity of cases, associate a practitioner/respondent to each, then change their address
- [x] 5 Automatically serve generated notices (Kris ustaxcourt/ef-cms-flexion#4476)
- [x] 6 Only update address for counsel on cases that are not closed more than 6 months (Rachael, Kris ustaxcourt/ef-cms-flexion#4487)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
