### ISSUE TITLE
Court-issued documents that need a cover sheet, but not a filing party

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7056]
As the court, in order to 

## Acceptance Criteria
* These documents require a cover sheet, but not a filing party:
1. Hearing Exhibits for [Anything]
2. Trial Exhibits for [Anything]
3. Bounced Electronic Service of [Anything]
4. Returned Mail of [Anything]
5. U.S.C.A [Anything]

* Populate case caption, docket number, document title and filed date
* Don't need received date; doesn't need "electronically filed" or paper icon on docket record
* Doesn't need served stamp

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes:
* Make filing parties optional field?)
* Probably will not need to ever regenerate or replace cover sheet. If so, wouldn't be part of this story. 

## Tasks
- [x]  Generate coversheet for the following documents: (Matt, Mrinalini, Rae, ustaxcourt/ef-cms-flexion#5808 & ustaxcourt/ef-cms-flexion#5821)
1. Hearing Exhibits for [Anything]
2. Trial Exhibits for [Anything]
3. Bounced Electronic Service of [Anything]
4. Returned Mail of [Anything]
5. U.S.C.A [Anything]

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
