### ISSUE TITLE
Case Inventory Report

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7059]
As a court user, in order to manage my workload, I need the ability to generate a print-out of my case inventory.

## Acceptance Criteria ##
* List of all cases that can be filtered by status and judge (can filter by either and both) 
* Can filter by more than once status at a time
* Default order should be by docket number, lowest to highest
* Closed cases can be excluded from report
* Status filtered list should include:
   * Docket number
   * Case title
   * Judge
  ~* Date on which the case was associated with Judge~
* Judge filtered list should include:
   * Docket number
   * Case title
   * Case status
  ~* Date on which the case was associated with Judge~
* User can print a view of their results (Print Optimized)
* No data displayed on page/report load

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Date associated with judge - Removed from AC (2/20 design meeting)
* Load More function will be used to manage number of load on page
* Stress testing - max cases 1000

## Tasks
- [x] 1 Create endpoint to get case inventory by status and/or judge (use elasticsearch) (interactor, proxy, serverless, lambda) (Rachael, Kris, Rae ustaxcourt/ef-cms-flexion#4551)
- [x] 2 Add Case Inventory option to Reports dropdown (alpha order) (Matt ustaxcourt/ef-cms-flexion#4552)
- [x] 3 Create Run Case Inventory Report modal (without multi-select for case status), sequences, validation, submit sequence and action (Rachael, Rae ustaxcourt/ef-cms-flexion#4556)
- [x] 4 Case Inventory route and view, with filtering dropdowns (without table) (Matt ustaxcourt/ef-cms-flexion#4552)
- [x] 5 Case Inventory data table and computed (Rachael ustaxcourt/ef-cms-flexion#4575)
- [x] 6 Create endpoint to get case inventory printable report (template generator, interactor, proxy, serverless, lambda, sequence, action) - use websockets and block the UI until fully loaded (Rachael ustaxcourt/ef-cms-flexion#4583)
- [x] 7 Case Inventory Report printable route/view, sequences, actions (Rachael ustaxcourt/ef-cms-flexion#4588)
- [x] 8 Paging (25) (Matt ustaxcourt/ef-cms-flexion#4598)
- [x] 9 Stress testing (Rachael - 200 cases added so far as of Friday afternoon)
~~- [ ] 10 Look into multi-select for case status~~
- [x] 11 Create reports cloudformation stack (Rachael ustaxcourt/ef-cms-flexion#4577)
- [x] 12 Add entity name to Case entity to persist the entity type, so it can be filtered on for elasticsearch query (we are currently checking for existence of caseType field - fix this in other places too) (Rachael ustaxcourt/ef-cms-flexion#4592)
- [x] 13 UI validation when both filters are cleared from the table (backend throws an error that needs to be handled on the frontend) (Rachael ustaxcourt/ef-cms-flexion#4602)
~~- [ ] 14 Printable report - use websockets and block the UI until fully loaded (Rachael)~~ not needed

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
