### ISSUE TITLE
Chambers User Dashboard

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7060]
As a Chambers User, so that I can assist the Judge with his/her work, I need a dashboard that is similar to the Judges.

## Acceptance Criteria 
* Chamber Users have the same dashboard layout as their Judge
   * Messages should be the individual users (not the judge's)
   * Trial Sessions (Upcoming and Recent) should be Judge's

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
*~~Currently the Chambers Admin role is under "chambers" - needs to be renamed/defined (Kristen 2/11/20)~~

## Tasks
- [x] 2) Create CA view - clone of Judge's (Matt ustaxcourt/ef-cms-flexion#4426)
- [x] 3) Add global "Dashboard" item to nav for chambers view (Matt ustaxcourt/ef-cms-flexion#4431)
- [x] 5) Filter by judge when clicking "View All" link from CA Dashboard (Matt ustaxcourt/ef-cms-flexion#4431)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
