### ISSUE TITLE
QC Boxes for ADC/Judges

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7061]
As an ADC or Judge, in order to know what documents have come in on my cases and remain to be QC'd, I need to have my QC box only display items in cases I'm associated with.

## Acceptance Criteria ##
* An ADC's QC box should display all Docket QC items that have "Chief Judge" associated with case
* A Judge's (and everyone in the Judge's Chambers) QC box should display all Docket QC items that have that specific Judge associated with case

## Security Considerations
 - [x] Does this work make you nervous about privacy or security? No.
 - [x] Does this work make major changes to the system? No. 
 - [x] Does this work implement new authentication or security controls? No.
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features? No.

## Tasks
- [x] 1 Add associated judge to work items (make it required, default to chief judge) (Rachael ustaxcourt/ef-cms-flexion#4496)
- [x] 2 Update judge on work items when the case is updated if the judge changes (see updateCase.js lines 50-86) (Rachael ustaxcourt/ef-cms-flexion#4496)
- [x] 3 Filter work items in judge/ADC qc boxes by the appropriate judge (Matt ustaxcourt/ef-cms-flexion#4498)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
