### ISSUE TITLE
Trial Clerks: Working copy of trial session

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7062]
As a Trial Clerk, in order to prepare for a trial session, I need a working copy of any trial session to which I am assigned, separate from the working copy of the Judge.

## Acceptance Criteria 
*  Trial Clerk who is assigned to a trial session needs a working copy of the trial session

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security? No.
 - [ ] Does this work make major changes to the system? No.
 - [ ] Does this work implement new authentication or security controls? No.
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?  No. 

## Notes
* Separate from judges working copy
* Judges notes don't display; it's the trial clerks copy to do what they want

## Tasks
- [x] 1 Modify createTrialSessionInteractor and updateTrialSessionInteractor to create a working copy for the trial clerk if one is assigned (Matt ustaxcourt/ef-cms-flexion#4450)
- [x] 2 Update isUserAssociatedWithTrialSessionAction to allow for an associated trial clerk (update jsdoc description) (Matt ustaxcourt/ef-cms-flexion#4452)
- [x] 3 Rename judgesNotes to userNotes and allow trial clerks to add their own notes (not viewable on case detail as the judge's notes are) (Rachael ustaxcourt/ef-cms-flexion#4455)
  - [x] 3a Create migration script to change judgesNotes -> userNotes (Rachael ustaxcourt/ef-cms-flexion#4455)
- [x] 4 Update trial session list to link to working copy for sessions a trial clerk is assigned to (see formattedTrialSessions line 128) (Matt ustaxcourt/ef-cms-flexion#4452)
- [x] 5 Update trial session detail page to allow trial clerks to switch between the detail page and their working copy - also the working copy is displaying the judge's name instead of the trial clerk's in the header (Errybody ustaxcourt/ef-cms-flexion#4465)
- [x] 6 Look into why past trial sessions are throwing an error locally (Rachael ustaxcourt/ef-cms-flexion#4467)
- [x] 7 Change "Judge's notes" label in notes modal to "Notes" for trial clerk only (Rachael ustaxcourt/ef-cms-flexion#4467)
- [x] 8 Remove "Judge" from "View Judge Session Copy" link (Rachael ustaxcourt/ef-cms-flexion#4467)

Refactoring:
- [x] 1 Update user case note endpoints to be named better and/or pass in the userId (currently `case-notes/user/{caseId}`) (Rachael ustaxcourt/ef-cms-flexion#4468)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
