### ISSUE TITLE
Provide STINs to IRS

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7070]
As a court, so that we may provide STINs to the IRS, we need a method of transmitting STINs securely to the IRS

## Acceptance Criteria
* IRS superuser is able to access the STIN in a secure way
* STIN should not be viewable to parties or court users (except petitions clerk before the petition is served)

## Notes
* Coordinate with Andrew on API
* We need to also consider how this document shows in the UI (if it does) and how that impacts the paper-petition flow (if at all)
* System is currently serving STIN to IRS with Petition (IRS Super user is receiving service email) 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Remove STIN deletion code after we serve the case - Eric
- [x] Add STIN filter to Case constructor (filter it out for all roles except the IRS super user and petitions clerk if the case is not served)
- [x] Filter access to the STIN to the IRS super user and petitions clerk if the case is not served in the getDownloadPolicyURLInteractor - ustaxcourt/ef-cms-flexion#6625

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
Human still needs to be able to log in to the UI, in case the API solution isn't working.
In Flexion's environment, we can test the IRS superuser, because it's our email.
Story was built with expectation that Court is only going to access through API endpoint. 

What we need to validate:
* That a service email is kicked off to user for STIN
* If the UI/logging solution for the superuser is still working. 
* The superuser can access the STIN from the API endpoint. 
     - If we can log in w/the UI, we can get an access token to try the API endpoint.

**Comment by JessicaMarine** [comment]
Flexion reviewed with Mike Marcotte.  OK to move to done.
