### ISSUE TITLE
Docket Number: Year suffix has to match year paper petition received/filed

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7080]
As a court, in order to  know what year a paper petition was received/filed, I need the suffix number to match the  received/filed date on the petition.

Currently, system is displaying date entered into system. However, a paper petition will likely be received prior to that date; and if it occurs during the cusp of the new year, could likely reflect an incorrect date. 

For example, a paper petition could come in on Dec. 22, 2020, but not be entered into the system until Jan. 3, 2021.  Because the filed date is December 22, 2020, this case would need a -20 suffix, not -21.

## Acceptance Criteria: ##
* Year suffix on case is determined by the filing date, not processing `createdAt` date
* Incrementer needs to be on a per-year basis.
* For cut-over to new system, need to make sure CMS can pick up from last docket number from legacy data [Note: Mike Marcotte can manually set incrementer]

## Tasks ## 
- [x] Year suffix on case is determined by the filing date, not processing `createdAt` date (Rachael & Rae ustaxcourt/ef-cms-flexion#6653)
- [x] Incrementer needs to be on a per-year basis. (Rachael & Rae ustaxcourt/ef-cms-flexion#6653)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
