### ISSUE TITLE
Ability to easily reference case details while generating an order and QCin

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7084]
As a court user, in order to easily reference case details while drafting an order or QC'ing a document, I need the ability to view the work i'm doing on an order or QC a doc while viewing other case details at the same time. 

## Acceptance Criteria
* User needs to be able to easily reference the docket record (or other parts of the Case Info) when drafting an Order or QC'ing a document. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider easier method to create split-screen views, especially for docket record navigation, order creation, and document QC
[Note: The idea of being able to open in new tab/window?]

## Tasks
- [x] 1 New Tab Button - Mrinalini ustaxcourt/ef-cms-flexion#6004  
  - [x] 1a Add New Tab button to header visible only to internal users
  - [x] 2a Open Case Detail in new tab with Docket Record tab displayed 
- [x] 2 On click of "Continue" from Create Order modal, open Case Detail in new tab with Docket Record tab displayed on the previous tab and navigate to Create Order screen - Mrinalini ustaxcourt/ef-cms-flexion#6009

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Case header update
* Add "New Tab" button to Actions menu for all internal users

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cbaa91f9-9266-4b7f-8242-3eac8cd03307)
**On click of "New Tab"**
* Open Case Detail in new tab with Docket Record tab displayed 

**Create Order Flow**
* On click of "Continue" from Create Order modal, open Case Detail in new tab with Docket Record tab displayed and navigate to Create Order screen

**Comment by klohman** [comment]
### 4533 Tests Scenarios

#### 1)  Internal user sees “New Tab” option on Case Detail header 
* Login as internal user
* Navigate to Case Detail 
* Click Actions menu
* View header 
Expected results 
- [x] “New Tab” option is displayed in Actions menu 

#### 2) Internal user launches case detail in new tab from Document QC screen 
* Login as Docket Clerk
* Navigate to Document QC > Inbox 
* Click document link for case xx1-20
* On Document QC screen, click “New Tab” button 
Expected results 
- [x] New tab opens displaying Case Detail > Docket Record for case xx1-20
- [x] Current tab remains on QC screen for document

#### 3) Internal user views case detail in new tab automatically from Create Order flow 
* Login as internal user
* Navigate to case xx1-20
* Click Create Order or Notice from Actions menu
* Select order type
* Click continue  
Expected results 
- [x] Current tab remains on current screen
- [x] New tab opens with Create Order screen displayed
