### ISSUE TITLE
Calendar: Create Remote Trial Session (MUST BE DONE BY early January 2021)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7087]
As a Petitions Clerk, in order to issue the correct notices when cutting a calendar, I need to create a remote trial session.

Due to COVID-19, the Court was forced to move to remote proceedings using Zoomgov.  As a result, the Notice of Trial and SPTOs issued during the calendaring process have changed.  We need the ability to enter information and generate notice that have been approved for remote proceedings.

## Acceptance Criteria
* Allow the user to choose between in-person trial or remote trial when creating a session
* If the user chooses a Remote Trial Session the fields for data entry should accommodate the Notice of Trial and SPTOs that are unique for remote proceedings (samples below in comments)
* When remote trial session is created with session type Regular, Small, or Hybrid it should display on the "New" trial sessions tab and have cases eligible for trial listed [Note: same logic for an in-person session]
* When remote trial session is created with session type Special or Motion/Hearing it should display on the "Open" trial sessions tab [Note: same logic for an in-person session]
 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Update create trial session form - Themis mob
    - [x] Add UI for Proceeding Type - ustaxcourt/ef-cms-flexion#7479
    - [x] Add proceeding type to `TrialSession.js` - ustaxcourt/ef-cms-flexion#7481
    - [x] Add validation for Proceeding Type - ustaxcourt/ef-cms-flexion#7481
    - [x] Add default proceeding type selected on form (Remote) -#7479
    - [x] Add seed data - ustaxcourt/ef-cms-flexion#7481
- [x]  On select of proceeding type - Themis mob
    - [x] If In-Person is chosen, display in-person trial session form fields
    - [x] If Remote is selected, display remote trial session form fields ustaxcourt/ef-cms-flexion#7482
    - [x] Add validation for Remote trial session form fields ustaxcourt/ef-cms-flexion#7483, ustaxcourt/ef-cms-flexion#7489
- [x] On form submit
    - [x] When remote trial session is created with session type Regular, Small, or Hybrid it should display on the "New" trial sessions tab and have cases eligible for trial listed [Note: same logic for an in-person session]
    - [x] When remote trial session is created with session type Special or Motion/Hearing it should display on the "Open" trial sessions tab [Note: same logic for an in-person session]
- [x] Trial Session Detail - Remote Proceeding Type ustaxcourt/ef-cms-flexion#7484
    - [x] Display Courthouse Location Card with appropriate fields, and relevant default values when none provided ustaxcourt/ef-cms-flexion#7484
- [x] Migration for old trial sessions that do not have proceeding type - Jojo, Kris, Matt ustaxcourt/ef-cms-flexion#7490 
- [x] Allow saving of new remote fields when editing a trial session - mob ustaxcourt/ef-cms#7608

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
The Notice of Trial is issued in all cases: [Notice of Trial (Zoomgov).docx](https://github.com/flexion/ef-cms/files/5716060/Notice.of.Trial.Zoomgov.docx)
The SPTO (Remote-Regular) is issued in all regular cases: [SPTO (Remote-Regular).docx](https://github.com/flexion/ef-cms/files/5716063/SPTO.Remote-Regular.docx)
The SPTO (Remote-Small) is issued in all small cases: [SPTO (Remote-Small).docx](https://github.com/flexion/ef-cms/files/5716065/SPTO.Remote-Small.docx)

**Comment by klohman** [comment]
## Updated Create Trial Session form 

#### In Person proceeding type 
**Proceeding type**
* Add radio set for proceeding type 
* Options include In Person and Remote 
* Field is required 

**In Person**
if “In Person” is selected, display the following fields: 
* Trial location 
* Courthouse name 
* Address line 1
* Address line 2
* City 
* State
* ZIP code 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fab90458-38df-4683-a5e4-5ba6b75c539d)


#### Remote proceeding type 
## Add Trial Session form 

**Proceeding type**
* Add radio set for proceeding type 
* Options include In Person and Remote 
* Field is required 

**Remote**
* is selected as default 

if “Remote” is selected, display the following fields: 
* Trial location 
* Meeting ID
* Password 
* Join by Telephone 
* Chambers phone number (new field)

**Trial location**
* Is required
* List of all trial locations 

**Meeting ID**
* Is optional to create session 
* Is required to set the calendar 

**Password**
* Is optional to create session 
* Is required to set the calendar 

**Join by Telephone**
* Is optional to create session 
* Is required to set the calendar 

**Chambers phone number**
* Is optional to create session 
* Is required to set the calendar 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b565c411-ef93-41f8-bc9a-13551510d866)

## Session Detail - Remote Proceeding Type 

##  Trial Session Detail  

**Courthouse Location card**
if “Remote” is selected, display the following fields: 
* Display “Remote Proceeding” as card title 
* Display Meeting ID 
* Display Password 
* Display Join by Telephone 
* Display Chambers Phone number 
* Null state for any empty field = "Not provided" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8b19a6d9-fb0c-469c-8ac1-c48b60eab3d7)

**Comment by klohman** [comment]
## 4561 Test Scenarios 

#### 1) Internal user selects “In person”  proceeding type
* Login as internal user
* Go to Trial Sessions 
* Click Add Trial Session 
* Select “In Person” proceeding type  
Expected results 
- [x] Fields for In Person proceeding type display 
    - [x] Trial location 
    - [x] Courthouse name 
    - [x] Address line 1
    - [x] Address line 2
    - [x] City 
    - [x] State
    - [x] ZIP code 


#### 2) Internal user adds trial session with “In person”  proceeding 
* Login as internal user
* Go to Trial Sessions 
* Click Add Trial Session 
* Select “In Person” proceeding type 
* Complete form 
* Click Add Session 
Expected results
- [x] App routes to Trial Session screen with success message displayed 
- [x] New in-person session displays under the New Tab  
- [x] Eligible cases for trial session display in Eligible List 


#### 3) Internal user selects “remote”  proceeding type
* Login as internal user
* Go to Trial Sessions 
* Click Add Trial Session 
* Select “Remote” proceeding type  
Expected results 
- [x] Fields for In Person proceeding type display 
    - [x] Trial location 
    - [x] Meeting ID 
    - [x] Password 
    - [x] Join by telephone number
    - [x] Chambers telephone number 

#### 4) Petitions clerk user adds trial session with “remote”  proceeding for (Regular, Small, Hybrid) session type 
* Login as internal user
* Go to Trial Sessions 
* Click Add Trial Session 
* Select session type = Regular
* Select “Remote” proceeding type 
* Complete form 
* Click Add Session 
Expected results
- [x] App routes to Trial Session screen with success message displayed 
- [x] New session displays under the New Tab  

#### 5) internal users views “New” remote trial session 
* Scenario 4
* Click remote session link from New tab 
Expected results 
- [x] App routes to Trial Session Detail 
- [x] Remote proceedings card displays with the following read-only fields 
    - [x] Meeting ID 
    - [x] Password 
    - [x] Join by telephone number 
    - [x] Chambers telephone number 
- Eligible cases for trial location display in eligible list 


#### 6) Petitions clerk user adds trial session with “remote”  proceeding for (Special, Motion/Hearing) session type 
* Login as internal user
* Go to Trial Sessions 
* Click Add Trial Session 
* Select “Special” session type  
* Select “Remote” proceeding type
* Complete form 
* Click Add Session 
Expected results
- [ ] App routes to Trial Session screen with success message displayed 
- [ ] New session displays under the Open Tab
