### ISSUE TITLE
Court: Send case message with a document "attached"

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7089]
## Pre-Conditions
* ustaxcourt/ef-cms#7044

## Acceptance Criteria
* Court user can create a message that's tied to one or more documents from the docket record and/or draft documents
* Subject line of the message pre-populates with the name of the first attached document but can be edited by the user 
* Court user can send the message to another court user
* Receiver of message can see the message sent to them
* Section the receiver is in can see the message that was sent
* From the message, the receiver and section can view the documents the message is tied to

## Notes
* Design / tech question - Should we allow attached documents to be changed/removed from a message? What is the technical complexity of this? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add “Add documents” section to Create New Message modal
  - [x] 1a Fetch documents from the case to fill dropdown (Matt ustaxcourt/ef-cms-flexion#5476)
  - [x] 1b Add dropdown / button UI (Matt ustaxcourt/ef-cms-flexion#5464)
  - [x] 1c Sequences / actions for updating form attachments (Matt ustaxcourt/ef-cms-flexion#5473)
  - [x] 1d Display current attachments (Matt ustaxcourt/ef-cms-flexion#5473)

- [x] 2 Update interactor for creating a message to accept array of document ids (Matt ustaxcourt/ef-cms-flexion#5488)
- [x] 3 Add Attachments section to My Messages -> Inbox, My Messages -> Sent boxes (Matt ustaxcourt/ef-cms-flexion#5490)
  - [x] 3a Links should open PDF in a new tab (not document detail page - straight up PDF) (Matt ustaxcourt/ef-cms-flexion#5490)
- [x] 4 Update Message Detail screen with attachments section (Matt ustaxcourt/ef-cms-flexion#5495)
- [x] 5 Verify that all tables have a blank state “There are no messages.” (Matt)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt ustaxcourt/ef-cms-flexion#5505)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#5503)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
