### ISSUE TITLE
Court: Message complete, forward and reply

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7090]
## Pre-Conditions
ustaxcourt/ef-cms#7089 

## Acceptance Criteria
* Court user can reply to a message sent to them
* Message can be forwarded to another court user
* Message is removed from inbox once it's been replied to, forwarded or completed
* Message can be completed
* Once message is completed, the court user knows no further action is needed, but the message is still accessible to the user (from completed tab and at case level)
* A message that's forwarded or replied to creates a thread that's available for all court users to see
* A message that's been replied to forwarded displays in the sent box
* Any court user can access any message and take action on the message

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Complete redesign of Case Detail  and  Case Messages tables in this story 

## Tasks
- 1 Message Detail
  - [x] 1a Add message action buttons to message detail (Rachael ustaxcourt/ef-cms-flexion#5521)
  - [x] 1b Sequences for displaying modals (Rachael ustaxcourt/ef-cms-flexion#5521)
  - [x] 1c Updates for threaded message display (Rachael)
- 2 Reply to message
  - [x] 2a Reply modal (Rachael ustaxcourt/ef-cms-flexion#5528)
  - [x] 2b Sequences / Actions for submitting reply (Rachael, Matt)
  - [x] 2c Persistence methods for updating inbox/outbox records (Rachael, Matt)
- 3 Forward message
  - [x] 3a Forward modal (Rachael ustaxcourt/ef-cms-flexion#5542)
  - [x] 3b Sequences / Actions for forwarding message (Rachael, Cody ustaxcourt/ef-cms-flexion#5553)
  - [x] 3c Persistence methods for updating inbox/outbox records (Rachael, Cody ustaxcourt/ef-cms-flexion#5553)
- 4 Complete message
  - [x] 4a Complete message modal (Rachael, Cody)
  - [x] 4b Sequences / Actions for completing message (Rachael, Cody)
  - [x] 4c Persistence methods for updating inbox/outbox records (Rachael, Cody ustaxcourt/ef-cms-flexion#5555)
- [x] 5 Dynamo records / entity updates for threaded messages (Rachael, Matt)
- 6 Case Detail (Matt ustaxcourt/ef-cms-flexion#5543)
  - [x] 6a Add Tracked Items tab with pending report and deadlines (default)
  - [x] 6b Add Drafts with Draft Documents table
  - [x] 6c Add Case Messages tab with In Progress and Completed tab
- [x] 7 Add Case Title to case message tables (Matt ustaxcourt/ef-cms-flexion#5523, ustaxcourt/ef-cms-flexion#5535)
- [x] 8 Change Docket to Docket Number on message tables (Matt ustaxcourt/ef-cms-flexion#5523)
- [x] 9 Completed box (Rachael, Cody ustaxcourt/ef-cms-flexion#5558)
  - [x] 9a Route, table view, computed (Rachael, Cody ustaxcourt/ef-cms-flexion#5558)
  - [x] 9b Endpoint to retrieve data (Rachael, Cody ustaxcourt/ef-cms-flexion#5558)
- [x] 10 Message detail alert for completed message thread (Rachael)
- [x] 11 Case Detail -> Case Messages -> In Progress and Completed boxes
- [x] 12 completed and sent boxes - filter out anything older than 7 days (Rachael ustaxcourt/ef-cms-flexion#5571)
- [x] 13 stay on message detail screen when replying/forwarding/completing, but update the messages displayed with the new one (Matt ustaxcourt/ef-cms-flexion#5572)
- [x] 14 case detail case messages is not displaying the latest message sent from the case detail actions menu (Rachael ustaxcourt/ef-cms-flexion#5571)

- [x] Need to align Message Subject line link with table header and left align wrapping text (Cody)
- [x] Add padding to blank state messages on Message Detail > Attachments (Cody)
- [x] Sent box > Section is not displaying the correct section for the “To” user (Cody)
- [x] Example, message was sent to petitions clerk 1 - “To” displays as Petitions clerk 1; “Section” displays as docket 
- [x] Success message on Message Detail should clear when user navigates away from screen (currently it’s still displaying when I click back to Case Messages > Inbox (Matt ustaxcourt/ef-cms-flexion#5585)
- [x] When completing message, do not show the "Message has been sent" success message. Only display the "message completed ...." (Matt ustaxcourt/ef-cms-flexion#5585)
- [x] Correct sorting on Messages > Completed box - should be newest to oldest by completed date (Matt ustaxcourt/ef-cms-flexion#5585)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Matt)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Matt)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
