### ISSUE TITLE
Court: Create an order tied to a message thread

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7091]
As a court employee, so I can create an order in response to an open message thread, I need the ability to create an order that's associated to the thread.

## Acceptance Criteria
* Court user can create an order from a messaging thread
* The new order is "attached" to the message
* When the order is saved, user is routed back to the message page
* Order should appear in draft documents

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Update Apply Signature screen for the Create Order flow to include "Skip Signature" 

## Tasks
- [x] 1 Add “Create Order” link to message actions - should open modal (Rachael ustaxcourt/ef-cms-flexion#5597)
- [x] 2 Add Skip Signature button and functionality to Apply Signature screen (Cody ustaxcourt/ef-cms-flexion#5605)
- [x] 3 Navigate back to Message Detail with success message displayed after skipping or saving signature (Rachael ustaxcourt/ef-cms-flexion#5608)
- [x] 4 Update create order endpoint - send messageId in props; submitted Order is attached to the latest message in the thread (Rachael ustaxcourt/ef-cms-flexion#5599)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
