### ISSUE TITLE
Court: Take action on a document from the message thread

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7092]
## Acceptance Criteria
* Court user can take action on a draft document from the message view (edit, apply/edit signature, add docket entry for petitions and docket, view Full PDF)
* For externally filed documents and served court-issued documents, court users should be able to view full PDF
* If an action is initiated from the message view, the user will return back to that message after the action is complete. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add Actions bar to document display on message detail (Matt ustaxcourt/ef-cms-flexion#5635)
  - [x] 1a Computed for which buttons to show/hide on the bar based on document type and user role (Matt ustaxcourt/ef-cms-flexion#5641)
- [x] 2 Edit Order navigation updates (Rachael ustaxcourt/ef-cms-flexion#5649)
- [x] 3 Apply Signature navigation updates (Cody ustaxcourt/ef-cms-flexion#5650)
- [x] 4 Add Docket Entry navigation updates (Matt ustaxcourt/ef-cms-flexion#5653)
- [x] 5 View Full PDF link (Rachael ustaxcourt/ef-cms-flexion#5652)
- [x] 6 Edit Signature updates (Rachael ustaxcourt/ef-cms-flexion#5657)
- [x] 7 Refactoring - always get parentMessageId from the same place in state (sometimes it's in state.modal.parentMessageId, state.form.parentMessageId, or state.parentMessageId) (Cody ustaxcourt/ef-cms-flexion#5655 5655)
- [x] 8 Update navigation to use `followRedirectAction` (Rachael)

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Rachael)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
