### ISSUE TITLE
Court: Draft view of document detail

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7093]
## Acceptance Criteria
* All documents on the docket record display on the left of the document
* User should be able to view a full-page PDF
* User can edit, apply signature, edit signature, add docket entry for docket clerks and petitions clerks

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add Draft Document view to Drafts tab on case detail (only for internal users) - Mrinalini ustaxcourt/ef-cms-flexion#5731
- [x] 2 Draft Document view left panel (display all drafts sorted by created date) - Mrinalini ustaxcourt/ef-cms-flexion#5731 
- [x] 3 Draft Document view right panel (PDF viewer, sequences to update which document is displayed) - Mrinalini ustaxcourt/ef-cms-flexion#5735
- [x] 4 Draft Document view action bar, computed to determine which actions to display (Rachael ustaxcourt/ef-cms-flexion#5736)
~- [ ] 5 Delete old Drafts Document view (Rae, Mrinalini)~ Will instead be completed in a devex task (https://trello.com/c/4a1r9ZF2/668-remove-references-to-documentdetail-view)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
