### ISSUE TITLE
Court: Redesign Order Creation Page (by 3/27)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7094]
As a court employee, so that I may more easily see the text of the order that I'm generating, I need to see a full page view of the PDF as I'm creating and editing it. 

## Acceptance Criteria
* Court employee can easily read the text of draft order while they're creating and editing it

## Notes
* Consider tabbed approach (Jessica)
* Won't be instant - need spinner or something to indicate loading - progress-cursor? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks

- [x] 1 Update Create Order view with tabs (Rachael ustaxcourt/ef-cms-flexion#4733)
- [x] 2 Edit order title functionality (Rachael ustaxcourt/ef-cms-flexion#4733)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
