### ISSUE TITLE
SDEC: Pro-Se P's information non-viewable

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7095]
As the Court, so that a pro-se petitioner's information is not disclosed to the public, we need to ensure that contact information on a SDEC is not viewable. 

** FOR MVP -- okay to make SDECs (or SDECs in cases where pro-se Ps) non-viewable to public **

## Pre-Conditions ##
* SDEC is signed and served.

## Acceptance Criteria ##
* SDEC are only viewable to court users and parties to the case
* SDEC are non-viewable to public or anyone not associated to the case

## Notes: 
* Per Judge Buch 8.3.2020 -- the information needs to be **removed** from the document
* May want to consider a solution that would allow Court to "redact" (hide) any part of any document.
* Current system puts a black box over sensitive data.
* Per Joeliette -- Docket has to redact case caption on all documents when the Motion to Proceed Anonymously is granted.

## Questions (for grooming)
* is it ok for external user to view a "copy" of the PDF? 
* simply masking the content will not hide the PDF content stored in the data 
* is this a destructive action? we will no longer save the original pdf
* one solution for both PDF security issue and redacting content? 
* flattening pdfs- how does this relate to PDF security? 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add checks for stipulated decision event code in PublicCase isPrivateDocument, getDownloadPolicyUrlInteractor, and in helpers that show links to documents - Rachael ustaxcourt/ef-cms-flexion#6681 

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
