### ISSUE TITLE
Court: Tweaks to Document Codes

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7096]
As a court, so that we can go-live with accurate filing codes, we need to clean-up the document codes.

## Acceptance Criteria: ##
* `MISL` when an external parties lodges a document should be `MISCL`- Done 
* The code for Notice of Trial should be `NTD` not `NDT
* Confirm event code for: Oral *anything* [internal only] -- see comment below
* Confirm event code for: Redacted *anything* [internal and external] -- see comment below
* Confirm event code for: Unredacted *anything* [internal and external] -- see comment below
* Options for Petitions/Calendar in Order/Notice generator needs to include: - (done in ustaxcourt/ef-cms-flexion#5715)
   * Order (already have)
   * Notice (already have)
   * Order of Dismissal for Lack of Jurisdiction
   * Order to Show Cause
* Fix Transcript codes 
TRAN      Transcript of [date] *anything*
RTRA       Revised Transcript of [date] *anything*
CTRA       Corrected Transcript of [date] *anything*

Separate story:
* Docket drop-down -- shouldn't have code and title -- same as magic selector for eFiled docs

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] The code for Notice of Trial should be `NTD` not `NDT` (Rae, Mrinalini ustaxcourt/ef-cms-flexion#5797)
- [x] Fix Transcript codes (Kristen [#5789](https://github.com/flexion/ef-cms/pull/5789))

## Definition of Done (Updated 6-19-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written (
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
