### ISSUE TITLE
Petitions and Docket Clerks: Ability to remove/modify PDFs

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7099]
As a Petitions clerk and Docket clerk, so that I can correct my mistakes, I need the ability to remove and replace a PDF that was previously added from a paper petition or paper filing. 

When a Petitions clerk is adding a paper petition (and related filings) to the system, he/she may need to go back and change the PDF out before serving everything.  For example, if the Request for Place of Trial was accidentally scanned in as part of the Petition, the Petitions Clerk will need to delete the previously scanned petition PDF and then add the new petition PDF (remove and re-add) and add the Request for Place of Trial PDF (being added for first time).  Likewise, a Docket Clerk may have mis-scanned a document added to a docket entry but not served.  Until that document is served, the Docket Clerk should have the ability to remove and re-add an entire PDF to the entry.

## Acceptance Criteria
* Petitions Clerk can remove and re-add a previously scanned PDF (entire PDFs only) from a paper-filed petition package (Petition, Request for Place of Trial, Ownership Disclosure Statement, Application for Waiver of Filing Fee) at any time before the Petition is served
* Petitions Clerk can add a new PDF (entire PDFs only) from a paper-filed petition package (Petition, Request for Place of Trial, Ownership Disclosure Statement, Application for Waiver of Filing Fee) at any time before the Petition is served 
* Docket Clerk can remove and re-add an entire PDF attached to a docket record at any time before the document is served.

## Mobile Design/Considerations
 - no, all internal

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Does the original PDF need to be retained somehow? No. Completely replace. 
* Court-issued document not in scope

## Tasks
- [x] Remove initially-filed document (non-petition) PDF from paper filed case (Rae ustaxcourt/ef-cms-flexion#6090)
  - [x] Re-add PDF UI (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6113)
  - [x] Re-add PDF backend (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6145)
- [x] Remove PDF from unserved docket record item (Rachael ustaxcourt/ef-cms-flexion#6141)
  - [x] Re-add PDF (Rachael ustaxcourt/ef-cms-flexion#6141)
- [x] Remove Petition
  - [x] Confirm remove petition modal, sequence (Matt ustaxcourt/ef-cms-flexion#6096)
  - [x] Correct validation for petition qc form on removal of a pdf (Matt, Rachael, Mrin ustaxcourt/ef-cms-flexion#6147)
- [x] Do not display initially-filed documents (non-petition) on Docket Record until they have been served (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6126)
- [x] Do not display initially-filed documents (non-petition) on Document View until they have been served (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6126)
- [x] Create Case (paper filed) - Update UI (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6128)
- [x] e-filed petition (Matt ustaxcourt/ef-cms-flexion#6153)
  - [x] Hide "Remove PDF" button
  - [x] Hide APW, RQT tabs
  - [x] Hide ODS if none was originally filed

Bugs:
- [x] 1 Enter mailing validation bug on paper filing - Rachael ustaxcourt/ef-cms-flexion#6155

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written (Mrinalini & Rae)
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning - Rachael
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts - Rachael
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated - Rachael
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update) - Rachael
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt - Mrinalini
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Create Case (paper filed) - Update UI
* remove current “Delete PDF” button  
* Add “Remove PDF” button and functionality  (same as Petition QC- Paper Filed documents)  
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/63bbf8d9-a231-4202-802c-06278ed69bd1)

## Petition QC - for Paper-Filed Petitions 
* add “Remove PDF” button for documents with PDF uploaded 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0c4be06b-45f6-4bf7-8f3b-86bd1c013fb2)

## Remove PDF modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3f08985d-7919-4363-ba94-c10bc5f2b7d5)
* on click of Remove PDF button, display modal 
* On click of Cancel, modal closes, no changes

**On click of Yes, Remove**
* Modal closes and success message displays "PDF removed."
* PDF is deleted 
* PDF viewer is hidden 
* Scan or Upload options are displayed 
* Validation should remain the same as current 
    - Petition PDF is required 
    - STIN is optional 
    - RQT is conditionally required 
    - ODS is conditionally required 
    - APW is conditionally required 

## Adding Petition package documents  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5beaa142-87b8-4463-8317-98421c9627df)

**STIN, RQT, ODS, APW** 
if no  PDF was uploaded for these document when the paper-case was created 
* Remove current messaging “No document added” 
* Display  Scan or Upload options 

**On PDF Scan or Upload**
* Display “Change PDF” button 

* Validation should remain the same as current 
    - Petition PDF is required 
    - STIN is optional 
    - RQT is conditionally required 
    - ODS is conditionally required 
    - APW is conditionally required 


## Petition QC - for e-Filed Petitions 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3d30b550-a3e6-47e6-a140-dd0f04c5a96c)

* Remove PDF button is hidden 

* Hide Document tabs for APW, RQT
* Hide Document tabs for ODS if no ODS is uploaded 


## New Flow for Initial Documents for Paper Filings
**On click of Create Case** 
* Case is created 
* Petition entry is added to the Docket Record with no cover sheet 
* other initial documents are not added to Docket Record 

**On Serve to IRS**
* Petition and all initial documents are served to IRS 
* Petition entry displays as served on docket record 
* other initial documents are added to Docket Record and display as served 
* All documents receive a cover sheet

**Comment by klohman** [comment]
### Test Scenario 4654 

#### 1a) Petitions clerk removes paper-filed Petition package PDF before case creation (Petition document) 
* Login as petitions clerk 
* Navigate to Document QC 
* Click Start a Petition 
* Upload a Petition PDF 
* Click “Remove PDF” 
* Click “Yes, Continue” 
Expected results
On upload of Petition PDF 
- [x] “Remove PDF” button displays 
On click of Remove PDF button
- [x] Confirmation modal displays 
On click of Yes, Continue
- [x] Original PDF is removed 
- [x] PDF preview is hidden 
- [x] Scan and Upload radio buttons display

#### 1b) Petitions clerk removes paper-filed Petition package PDF before case creation (associated document) 
* Login as petitions clerk 
* Navigate to Document QC 
* Click Start a Petition 
* Select RQT tab
* Upload a Request for Place of Trial PDF 
* Click “Remove PDF” 
* Click “Yes, Continue” 
Expected results
On upload of RQT PDF 
- [x] “Remove PDF” button displays 
On click of Remove PDF button
- [x] Confirmation modal displays 
On click of Yes, Continue
- [x] Original PDF is removed 
- [x] PDF preview is hidden 
- [x] Scan and Upload radio buttons display

#### 2a) Petitions clerk removes paper-filed Petition package PDF during QC (Petition document) 
* Login as petitions clerk 
* Navigate to Document QC 
* Click Start a Petition 
* Upload Petition PDF
* Upload ODS
* Complete form 
* Click Create Case (case xx1-20)
* Click Save for Later 
* Navigate to Document QC > In Progress 
* Select Petition for case xx1-20
* Click “Remove PDF” 
* Click “Yes, Continue” 
Expected results
On view of the Petition QC screen
- [x] “Remove PDF” button displays on Petition tab 
On click of Remove PDF button
- [x] Confirmation modal displays 
On click of Yes, Continue
- [x] Original PDF is removed 
- [x] PDF preview is hidden 
- [x] Scan and Upload radio buttons display

#### 2b) Petitions clerk removes paper-filed Petition package PDF during QC (associated document) 
* Scenario 2a 
* Select ODS tab 
* Click “Remove PDF” 
* Click “Yes, Continue” 
Expected results
On view of the Petition QC screen > ODS tab
- [x] “Remove PDF” button displays on ODS tab 
On click of Remove PDF button
- [x] Confirmation modal displays 
On click of Yes, Continue
- [x] Original PDF is removed 
- [x] PDF preview is hidden 
- [x] Scan and Upload radio buttons display

#### 3a) Petitions clerk cannot remove e-filed Petition package PDFs during QC (no ODS)
* Login as petitions clerk 
* Navigate to Document QC > Inbox 
* Click on eFiled Petition 
Expected results 
- [x] “Remove PDF” button is hidden on all Document tabs 
- [x]  APW, RQT, ODS tabs are hidden

#### 3b) Petitions clerk cannot remove e-filed Petition package PDFs during QC (with ODS)
* Login as petitions clerk 
* Navigate to Document QC > Inbox 
* Click on eFiled Petition 
Expected results 
- [x] “Remove PDF” button is hidden on all Document tabs 
- [x]  APW, RQT tabs are hidden

#### 4) Petitions clerk adds paper-filed Petition package PDF during QC 
* Scenario 1a 
* Complete form 
* Click Create Case (case xx2-20)
* Save for Later 
* Navigate to Document QC > In Progress 
* Select Petition for case xx2-20
* Click APW tab 
* Upload PDF for APW 
Expected results 
On click of APW tab 
- [x] Scan and upload radio buttons display 
On upload of PDF 
- [x] Remove PDF button displays 


#### 5) Docket clerk removes paper-filed document from docket entry before service
* Login as docket clerk 
* Navigate to case xx3-20 
* Click “Paper Filing” from case menu 
* Select “Motion” as document type 
* Upload PDF 
* Complete Form
* Click Save Entry 
* Navigate to Document QC> In Progress 
* Click on Motion for case xx3-20
* Click Remove PDF 
Expected results
On view of the Add Paper Filing screen from In Progress:
- [x] “Remove PDF” button displays 
On click of Remove PDF button
- [x] Confirmation modal displays 
On click of Yes, Continue
- [x] Original PDF is removed 
- [x] PDF preview is hidden 
- [x] Scan and Upload radio buttons display
- [x] “Incomplete” docket entry warning message displays 

#### 6) Docket clerk adds new paper-filed document to docket entry before service 
* Scenario 5 
* Scan or Upload new PDF 
Expected results 
- [x] New PDF displays in PDF preview 
- [x] “Incomplete” docket entry warning message is hidden 
- [x] Remove PDF button displays  

#### 8) Docket clerk cannot remove paper-filed PDF from docket entry after service 
* Scenario 5
* Click Save and Serve 
* Navigate to Document QC> Processed 
* Select Motion for. Case xx3-20
Expected results 
- [x] Navigates to Document View with Motion selected 
- [ ] Remove PDF option is not displayed 

#### 9) Docket clerk cannot remove court-issued PDF from docket entry before or after service 
* Login as docket clerk 
* Navigate to case xx4-20
* Create, sign, and save docket entry for Order 
* Navigate to Document QC > In Progress
* Select Order for case xx4-20 
Expected results 
- [x] Navigates to Edit Court Issued Docket Entry screen. 
- [x] Remove PDF button is not displayed

#### 10) Initial documents added with paper-filed Petition do not appear on docket record before service 
* Login as petitionsclerk 
* Go to Document QC 
* Click Start a Petition 
* Upload Petition, RQT, ODS, APW 
* Complete form 
* Click Review Petition
* Navigate to Docket Record 
expected results 
- [x] Petition displays on docket record as "not served" 
- [x] RQT does not display on docket record 
- [x] ODS does not display on docket record 
- [x] APW does not display on docket record 


#### 11) Initial documents added with paper-filed Petition appear on docket record after service 
* Scenario 10 
* Navigate to Petition QC 
* Serve to IRS 
* Navigate to Docket Record
expected results 
- [x] Petition displays on docket record as served
- [x] RQT displays on docket record as served 
- [x] ODS displays on docket record as served 
- [x] APW displays on docket record as served



12) User removes ODS PDF with Corporation, Partnership (TMP), Partnership (partnership representative from BBA regime), or Partnership (other than TMP)as party type 
* Login as petitions clerk 
* Start a Petition
* Upload Petition, ODS
* Select party type = Corporation
* Leave trial location = blank
* Click Create Case 
* Navigate to parties tab
* Remove ODS PDF  
Expected results
- [x] Error message displays on ODS Upload = “Upload or scan Ownership Disclosure Statement”

13) User removes ODS PDF with Corporation, Partnership (TMP), Partnership (partnership representative from BBA regime), or Partnership (other than TMP)as party type, checks Order for ODS, and does not upload new ODS PDF
* Scenario 12
* Navigate to parties tab
* Select a party type from dropdown menu
* Check Order for ODS checkbox
* Click Review Petition
 Expected results
- [x] App navigates to Review and Serve Petition screen 

14) User adds ODS PDF with Corporation, Partnership (TMP), Partnership (partnership representative from BBA regime), or Partnership (other than TMP)as party type 

* Scenario 12 
* Navigate to parties tab
* Upload ODS PDF 
Expected results
- [x] Order for Ownership Disclosure Statement checkbox displays and is auto unchecked
- [x] Uploaded PDF displays In ODS tab


15) User adds new RQT PDF after case creation and does not enter a trial location
* Scenario 12
* Upload RQT PDF
* Navigate to Case Info
* Click Review Petition 
 Expected results
- [x] On submit of form, Trial location field displays error message “Select a preferred trial location”
- [x] Order Designating Place of Trial checkbox is automatically unchecked

16) User removes RQT PDF with a trial location selected
* Scenario 15
* Select trial location 
* Remove RQT 
* Click Review Petition  Expected results
- [x] Order Designating Place of Trial checkbox is automatically unchecked
- [x] On submit of form, RQT PDF field displays error message “Upload or scan a requested place of trial”

17) User does not select trial location or upload a RQT PDF
* Scenario 16
* Leave Trial location field empty
* Click Review Petition  Expected results
- [x] Order Designating Place of Trial checkbox is automatically checked

18) User does not select trial location or upload a RQT PDF and unchecks Order Designating Place of Trial
* Scenario 17 
* Navigate to Case Info tab
* Leave Trial location field empty
* Do not upload RQT PDF 
*Uncheck Order Designating Place of Trial checkbox 
Expected results
- [x] Error displays Select Preferred Trial Location and Upload RQT or Select Order Designating Place of Trial at top of page
- [x] Error displays Select Preferred Trial Location and Upload RQT or Select Order Designating Place of Trial on RQT tab
- [x] Error displays Select Preferred Trial Location and Upload RQT or Select Order Designating Place of Trial under both Select trial location and Order Designating Place of Trial


19) User removes APW with  “Waived” selected for filing fee 
* Login as petition clerk 
* Start a Petition 
* Select Filing Fee = Waived 
* Upload APW 
* Click Create Case 
* Remove APW PDF 
* Click Review Petition Expected results
- [x] Error message is displayed on APW field “Upload or scan an APW”

**Comment by JessicaMarine** [comment]
PO Review:
(1) As part of the paper-petition flow, when you go back to edit documents, the green check mark is no longer on the tabs that have PDFs.  As a result, you have to click into each one to see what has/hasn't been uploaded. 
(2) On staging, in Dkt. No. 376-20L, I uploaded an Ownership Disclosure Statement and served the Petition.  The ODS is not hyperlinked on the docket record and is not displaying on the Document view.

**Comment by JessicaMarine** [comment]
PO Review 8.14.2020:
 (1) The green check marks are showing up after the case is created and I go back to edit, but they don't seem to be showing up on the initial case entry now; and
 (2) if you added a RQT initially and then remove it during edit and de-select the place of trial, the "Designate Place of Trial" gets auto-checked, but is not showing up on the Review Screen as an order needed. Even when I manually check that box, it's not showing up on the Review Screen.
