### ISSUE TITLE
Petitions/Calendar Clerk: Add statistics during petition entry and QC

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7102]
As a Petitions/Calendar Clerk, so that I can capture statistics on a case, I need the ability to add data during the Petition QC process.

## Acceptance Criteria
* For **deficiency** cases, where there IS an IRS notice, a Petitions/Calendar Clerk- must have the ability to capture the following information for each tax year while entering a paper case or performing an electronic petition QC.  
   (1) Deficiency amount proposed by IRS 
   (2) Individual penalties
   (2) Aggregate penalty amount (not broken out by type), which are calculated from the individual entries

[Note: For all other case types (CDP, Whistleblower, Passport, Partnership, etc.), we will not capture any amounts at issue or amounts determined by the Court.]

* These case statistics should be viewable to all Court employees
* Case statistics are not viewable by external users

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add array of statistics to Case entity (include in block of data that is filtered out for external users) (Rachael, Matt ustaxcourt/ef-cms-flexion#5189)
  - [x] 1a Add Statistic entity (Rachael, Matt ustaxcourt/ef-cms-flexion#5189)
- [x] 2 Create StatisticsForm UI component and include in StartCaseInternal and PetitionQC screens (Rachael ustaxcourt/ef-cms-flexion#5214 ustaxcourt/ef-cms-flexion#5216)
  - [x] 2a Only display if case type is Deficiency and hasVerifiedIrsNotice is true
  - [x] 2b Create a computed just for this component
- [x] 3 Create Calculate Penalties modal (Matt ustaxcourt/ef-cms-flexion#5215)
- [x] 4 Sequences, actions to calculate penalties (Matt ustaxcourt/ef-cms-flexion#5223)
- [x] 5 Add Statistics to ReviewSavedPetition view (Rachael ustaxcourt/ef-cms-flexion#5221)
- [x] 6 Validation (make first statistic required) (Cody ustaxcourt/ef-cms-flexion#5227 ustaxcourt/ef-cms-flexion#5233)
- [x] 7 Find a component to use for formatting currency during data input (Rachael ustaxcourt/ef-cms-flexion#5229)
- [x] 8 Use currency component for penalty modal (Rachael)
- [x] 9 Validation bug fix - period date (Rachael)
- [x] 10 Update validation error messages in the error notification for statistics (Rachael)

Refactoring
- [x] 1 Look at how we compute dates for submitting a paper petition vs qc'ing a petition (Rachael)
- [x] 2 Convert statistics on Review Petition screen into a table for accessibility (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written (Matt)
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Cody)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment (Due to staging freeze, Jessica tested in dev)
