### ISSUE TITLE
Docket Clerk: Notice of Change of Address/Phone #/Both ?

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7106]
As a Docket Clerk, so that I don't have to QC hundreds of the same Notice of Change of Address/Phone#/Both, I only need notices of unrepresented petitioners and cases where there is paper service to be routed to Docket's QC box.

## Acceptance Criteria
* Only Notices of Change of Address/Phone/Both by unrepresented Petitioners need to route to Docket's QC box.
* Any Notice of Change of Address/Phone/Both automatically generated by the system by a Practitioner changing his/her information does not need to be QC'd by Docket, unless there is paper service in the case
* If there's an unrepresented petitioner or paper service, when address/phone is changed by Docket Clerk, the automated Notice display in the Docket QC Inbox 
* Filed by for system generated Notices of Change of Address/Phone/Both should be blank ; when docket is completing QC for a system-generated Notice, they should not select a Filing Party

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Need to determine how the index number should apply to these documents based on rules applied in [#4881](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4881)
* Need to determine how the hyperlinking of document should work for system-generated Notice that is unserved (https://flexion.slack.com/archives/CD58Y6799/p1600172148100800) - Unserved Notice of Change of Address/Phone should be hyperlinked for internal users but not for parties or public

## Tasks
- [x] 1 When generating a notice of change of address/phone/both for a petitioner updating their address, only create a work item if they do not have a practitioner representing them - Rachael, Rae ustaxcourt/ef-cms-flexion#6949 
- [x] 2 When generating a notice of change of address/phone/both for a practitioner, only create a work item for their cases with paper service - Mrinalini ustaxcourt/ef-cms-flexion#6951
- [x] 3 Filed by for system-generated notices of change of address/phone/both should be blank - Rachael ustaxcourt/ef-cms-flexion#6950
- [x] 4 When docket is completing QC for a system-generated notice, they should not have to select a filing party - The `Filing Party` form field should not be visible to the user. - Rae ustaxcourt/ef-cms-flexion#6953

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by klohman** [comment]
### 4661 Test Cases 

#### 1) Pro se petitioner updates address / phone number and Notice of Change routes to Docket Document QC Inbox 
* Login as petitioner 
* Go to case 
    * Case does not have petitioner counsel 
* Edit petitioner address and phone number 
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record 
- [x] Notice of Change of Address and Phone Number is hyperlinked for external parties and internal users 
- [x] Notice of Change of Address and Phone Number is routed to Docket Document QC Inbox 
- [x] Notice of Change of Address and Phone Number displays on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 2) Represented petitioner updates address / phone number and Notice of Change does not route to Docket Document QC Inbox 
* Login as petitioner 
* Go to case 
    * Case has petitioner counsel representing logged in petitioner 
* Edit petitioner address and phone number 
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record 
- [x] Notice of Change of Address and Phone Number is hyperlinked for external parties and internal users 
- [x] Notice of Change of Address and Phone Number is not routed to Docket Document QC Inbox 
- [x] Notice of Change of Address and Phone Number does not display on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 3) Practitioner updates address / phone number and Notice of Change does not route to Docket Document QC Inbox for cases with electronic service 
* Login as private practitioner 
    * Practitioner only has cases with electronic service
* Edit address and phone number 
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record for each case practitioner is associated with
- [x] Notice of Change of Address and Phone Number is hyperlinked for external parties and internal users 
- [x] Notice of Change of Address and Phone Number is not routed to Docket Document QC Inbox for cases with electronic service
- [x] Notice of Change of Address and Phone Number does not display on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 4) Practitioner updates address / phone number and Notice of Change routes to Docket Document QC Inbox for cases with paper service 
* Login as private practitioner 
    * Practitioner only has cases with paper service
* Edit address and phone number 
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record for each case practitioner is associated with
- [x] Notice of Change of Address and Phone Number is hyperlinked for external parties and internal users 
- [x] Notice of Change of Address and Phone Number is routed to Docket Document QC Inbox for cases with paper service
- [x] Notice of Change of Address and Phone Number displays on internal Docket Record view with bold text and star icon (QC incomplete) for cases with paper service

#### 5) Docket clerk updates petitioner address/phone number for unrepresented petitioner with electronic service and Notice of Change routes to Docket Document QC Inbox 
* Login as docket clerk 
* Go to case 
    * Case has unrepresented petitioner with electronic service 
* Update petitioner address and phone number
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record 
- [x] Notice of Change of Address and Phone Number is hyperlinked for external parties and internal users 
- [x] Notice of Change of Address and Phone Number is routed to Docket Document QC Inbox for cases with paper service
- [x] Notice of Change of Address and Phone Number displays on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 6) Docket clerk updates petitioner address/phone number for unrepresented petitioner with paper service and Notice of Change routes to Docket Document QC Inbox 
* Login as docket clerk 
* Go to case 
    * Case has unrepresented petitioner with paper service 
* Update petitioner address and phone number
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record as not served
- [x] Notice of Change of Address and Phone Number is hyperlinked 
- [x] Notice of Change of Address and Phone Number is routed to Docket Document QC Inbox 
- [x] Notice of Change of Address and Phone Number displays on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 7) Docket clerk updates petitioner address/phone number for represented petitioner with a paper service party and Notice of Change routes to Docket Document QC Inbox 
* Login as docket clerk 
* Go to case 
    * Case has represented petitioner 
    * Party on the case has paper service 
* Update petitioner address and phone number
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record as not served
- [x] Notice of Change of Address and Phone Number is hyperlinked 
- [x] Notice of Change of Address and Phone Number is routed to Docket Document QC Inbox 
- [x] Notice of Change of Address and Phone Number displays on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 8) Docket clerk updates petitioner address/phone number for represented petitioner with all electronic service and Notice of Change does not route to Docket Document QC Inbox 
* Login as docket clerk 
* Go to case 
    * Case has represented petitioner 
    * All parties on case have electronic service 
* Update petitioner address and phone number
* Save 
Expected results 
- [x] Notice of Change of Address and Phone Number is added to the Docket Record 
- [x] Notice of Change of Address and Phone Number is hyperlinked for internal users and external parties 
- [x] Notice of Change of Address and Phone Number is not routed to Docket Document QC Inbox 
- [x] Notice of Change of Address and Phone Number does not display on internal Docket Record view with bold text and star icon (QC incomplete) 

#### 9) Docket clerk QCs Notice of Change of Address / Phone / Both 
* Pro se petitioner updates address
* Login as docket clerk
* go to Document QC > Inbox 
* Click on Notice of Change of Address
* Click Complete button
Expected results 
- [x] Filed by field is hidden on Document QC screen
on click of Complete
- [x] no errors received for Filed by field 
- [x] App routes to My Document QC Inbox 
- [x] Docket entry no longer displays as pending (no longer bold with star icon) 
- [x] Docket entry does not display a Filed by

**Comment by klohman** [comment]
#### 4661 UX Review 

- Test 5) Docket clerk updates petitioner address/phone number for unrepresented petitioner with electronic service and Notice of Change routes to Docket Document QC Inbox
    - Notice is not being routed to the Document QC Inbox 
    - Notice is not showing as QC incomplete on the docket record 
- Test 6) Docket clerk updates petitioner address/phone number for unrepresented petitioner with paper service and Notice of Change routes to Docket Document QC Inbox
    - Notice is not being routed to the Document QC Inbox 
    - Notice is not showing as QC incomplete on the docket record
- Test 7) Docket clerk updates petitioner address/phone number for represented petitioner with a paper service party and Notice of Change routes to Docket Document QC Inbox
    - Notice is not being routed to the Document QC Inbox 
    - Notice is not showing as QC incomplete on the docket record
- Paper service modal is popping up at odd times ( could be related to this bug: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/6940 )
    - Expect paper service modal to display after clerk Completes QC for the document

**Comment by rachelschneiderman** [comment]
PR for UX feedback: ustaxcourt/ef-cms-flexion#6968

**Comment by klohman** [comment]
@mrinsin @rachelschneiderman Updates look good. One thing- "Print Paper Service" modal is still displaying after docket clerk saves updates to petitioner contact info. Since this modal displays when they complete the QC on the Notice, we don't need to display it after save.

**Comment by rachelschneiderman** [comment]
PR for UX feedback part 2: ustaxcourt/ef-cms-flexion#6980
