### ISSUE TITLE
Court: Index legacy document PDF content

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7107]
As a court, in order to search the body of legacy PDF documents in Dawson, we need to index the content. 

## Pre-Conditions
* Legacy documents are available and able to be indexed. 

## Acceptance Criteria
* All legacy document content must be indexed for search
* Document content of legacy PDFs is searchable in Dawson
* Documents should behave just like any other document in the system. 

## Notes:
* Should this be done as they are being imported into DAWSON or at some other time?
* Total size of legacy PDFs: 2.4TB
* Legacy documents already OCR'd; get w/ Mark to see if that's accessible
* Text available and able to be sent? Text is embedded in the PDFs. Only way to get at text is to parse PDFs. 
* Start by reviewing a few PDFs. Mike to provide and post on Slack. 
* We have a process for parsing documents already. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create SQS queue ustaxcourt/ef-cms-flexion#7041
- [x] 2 Update migrateCaseInteractor to add messages to the queue ustaxcourt/ef-cms-flexion#7044
- [x] 3 Lambda that is triggered by messages from the queue - parse the pdfs, store the contents in S3, update the docket entry ustaxcourt/ef-cms-flexion#7055
- [x] Bug fixes - ustaxcourt/ef-cms-flexion#7065

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the **prod** environment

**Comment by rachelschneiderman** [comment]
Waiting to hear from Mark if it's possible to provide the PDF text as part of a case migration.

**Comment by JessicaMarine** [comment]
If providing Flexion real PDFs would assist in the "Searchable PDF content" story, we are safe to provide them PDFs in the following cases -- they do not contain PII:
110-15
240-15S
420-15S
570-15S
600-15
680-15S
1050-15
1090-15SL
1290-15
1310-15
1320-15
1330-15
1400-15S
1860-15
1880-15L
1890-15S
1910-15S
1690-15S
2040-15
2140-15
2350-15
2390-15
2420-15S
2500-15S
2720-15SL
2730-15
2760-15
2850-15
2900-15
3140-15S

**Comment by mrinsin** [comment]
Demo'd & QA'd with @mmarcotte
