### ISSUE TITLE
Petitions Clerk: Revamp - QC E-Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7110]
As a Petitions Clerk, so that I may review and edit an electronically filed petition, I need the petition workflow revamped to accommodate my needs. 

## Acceptance Criteria
* Make sure all Petition links direct to the right places 
* E-filed petition and associated documents receive coversheet when filed
* Petition clerk can copy address and phone for petitioner and spouse 
* Petition clerk views documents uploaded with Petition in tabbed view 
* Any court user should be able to view paper-filed and e-filed Petitions (and associated documents) when case status = NEW 
* Petition clerk can review petition details during QC (Review Your Petition screen) 
* Once they click “Review Petition” - QC’d petition should go into In Progress tab 
* Petitions clerk can edit after Reviewing 
* Need to update Petition QC "Orders Needed" to "Orders/Notices Needed" - change on form and review screen
* See other notes below - do we need?
* Make sure that the Petitions Clerk can enter case statistics during the QC process (same logic as paper petition should apply -- required if Deficiency and "yes" to notice)

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Per Jessica (5/18/20) - e-filed petitions receive coversheet when filed; on serve, they receive served date applied to original coversheet (not a duplicate coversheet) 
* if there are changes to the docket number suffix or case caption for e-filed petitions during QC, a minute entry noting the change is added to the docket record when served (in second story)

## Tasks
- [x] 1 Update petition links (see story comment) (Rachael ustaxcourt/ef-cms-flexion#5340)
- [x] 2 Update Orders Needed titles to Orders/Notices Needed (Cody ustaxcourt/ef-cms-flexion#5339)
- [x] 3 Case Info tab of petition QC screen updates (see story comment) (Cody ustaxcourt/ef-cms-flexion#5339)
- [x] 4 Make sure document tabs work on petition qc for e-filed petitions (Cody)
- [x] 5 Verify that petition is removed from document qc inbox and moved to In Progress when Review Petition is clicked (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
