### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *CREATE CASE & REVIEW* (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7116]
As a Petitions Clerk, so that I can ensure the data I'm entering into the system is correct, I need the ability to review all of that data I entered to create a paper petition in the system. 

## Acceptance Criteria
* Petitions clerk can create a case from a paper petition
* Petitions clerk can review "at a glance" all of the data entered into the create a petition form
* Petitions clerk can access the documents they uploaded to the form

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* need to update STIN PDF upload to an optional field 

## Tasks
- [x] 1 Update create paper case form (Rachael ustaxcourt/ef-cms-flexion#5085) 
  - [x] 1a Make STIN upload optional (Rachael ustaxcourt/ef-cms-flexion#5085) 
  - [x] 1b Update submit button text to “Create Case” (Rachael ustaxcourt/ef-cms-flexion#5085) 
- [x] 2 Update Create Case button to submit the actual case instead of just going to the review page (Rachael ustaxcourt/ef-cms-flexion#5087)
- [x] 3 Update review page to pull data from caseDetail instead of the form (Cody)
- [x] 4 Update review page header to use case detail header
- [x] 5 Case should appear in Petitions Section Document QC > In Progress tab after case is created
- [x] 6 Verify that all data displayed on the review petition screen is correct (see story comments)
- [x] 7 Update Attachments section of review screen; STIN should not be viewable (Cody)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
