### ISSUE TITLE
Petitions Clerk: Revamp Petition Flow *EDIT In-Progress Petition (Paper)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7117]
As a Petitions Clerk, so that I may fix any mistakes I see while reviewing the petition I''m uploading, I need the ability to edit the data from the review page. 

## Acceptance Criteria
From the review page, the Petitions Clerk can:
* Edit the party information
* Edit case information
* Edit IRS notices

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Remove and re-add PDFs (to be implemented in [#4654](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/4654) )

## Tasks
- [x] 1 Fix Edit links on petition review screen to navigate to petition qc with specified tab open (Rachael ustaxcourt/ef-cms-flexion#5101)
- [x] 2 Check petition qc screen for updates (see story comment) (Rachael ustaxcourt/ef-cms-flexion#5111)
- [x] 3 Update petition QC PDF preview to tabbed view (if no document exists, display “no document added” (Rachael, Matt ustaxcourt/ef-cms-flexion#5127)
- [x] 4 On click of Petition link from In Progress work queue, navigate to Review Petition screen (Rachael)
- [x] 5 On click of non-petition document links from Review page or docket record, navigate to document detail page with Review & Serve Petition button (Rachael)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
