### ISSUE TITLE
Judge Drop-Downs: System-wide

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7124]
As a CMS user, in order to locate a correct order or opinion, I need the Judge drop-down to include current and past (legacy) judges.. 

## Acceptance Criteria ##
* Before we start work, confer w/ Mark to align on strategy re: legacy judges (e.g., UUID; loading order; etc.) 
* When a CMS user performs an opinion search with a judge's name, the system returns all opinions associated with that judge (current or past)
* When a CMS user performs an order search with a judge's name, the system returns legacy data that are associated with that judge (current or past)
* Judge's names can display in UI as last name only *except* for Messages (see note below) and signatures (need full name and title)
* Ensure that all judge drop-downs (system-wide) contain the correct judges:
  * **Legacy AND Current Judges should display**
    * Associated Judge (in Case Header) 
    * Trial Sessions (Closed, All) - Judge filter 
    * Advanced Search - Order - Judge filter  
    * Advanced Search - Opinion - Judge filter  
  * **Current judges ONLY should display**
    * Messages - Select Recipient [Note: Display last name only for first selection "Buch's Chambers" -- Judge [Last Name] for second selection "actual recipient]
    * Add Trial Session form - Judge select
    * Add Court Issued Docket Entry - “Judge’s Name” select 
    * Trial Sessions (New, Open) - Judge filter 
    * Pending Report - Judge filter 
    * Case Inventory - Judge filter 
    * Trial Session Planning Report (past sessions) 
    * Deadlines Report - Judge filter 
    * Judge’s Note - Once a judge is no longer active, his/her notes should not be retained.

Security requirement - API only returns data as specified in design. (Write test scenarios around only returning specific data)

## Notes ##
* If we need to keep Judge Foley separate from Chief Judge Foley to make things easier for MVP, we can. 
* Consider format of legacy judges being passed into CMS (associated judge is allowed as a string; should it be exact values).
* What happens if Judge's "name" changes -- Judge Foley is current "Chief Judge Foley", but that will change in 2 years -- may also apply to tag on case.
* possible solution, add a unique judge ID that will never change and allow display name to be editable 
- What data should be/should not be included in the API call?
* Will be about 80 judges total
* When judge retires and is no longer a user, you don't need to have a chambers section for the judge. Many of the users in their chambers would likely be assigned to a different role in the court. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] add legacyJudge role (Mrin, Jojo ustaxcourt/ef-cms-flexion#6580)
- [x] add local legacyJudge user and auth-gate (Mrin, Jojo ustaxcourt/ef-cms-flexion#6580) 
- [x] add `judgeUserId` (optional uuid) to Case and DocketEntry since judge names will change (Mrinalini ustaxcourt/ef-cms-flexion#6583)
  - Note: `pk = case|abcdef123, sk = user|${case.judgeUserId}` in Dynamo for aggregatedCaseItems?
  - Double check ES indexes (judge name searches) -- not required as search dropdown is populated from back end
- [x] separate bash script for creating legacy judge users imported via CSV (Matt, Jojo, Mrinalini ustaxcourt/ef-cms-flexion#6619)
  - [x] script to bulk import judges (Matt, Jojo ustaxcourt/ef-cms-flexion#6619)
  - [x] endpoint for adding judges from script (Mrinalini ustaxcourt/ef-cms-flexion#6612)
- [x] (internal) sequence/actions for getting current _and_ legacy judges (Mrinalini and Matt ustaxcourt/ef-cms-flexion#6593)
- [x] (internal) sequence/actions for getting _only_ current judges (Mrinalini and Matt ustaxcourt/ef-cms-flexion#6593)
- [x] (public) sequence/actions for getting current _and_ legacy judges (Mrinalini and Matt ustaxcourt/ef-cms-flexion#6593)
- [x] (public) sequence/actions for getting _only_ current judges (Mrinalini and Matt ustaxcourt/ef-cms-flexion#6593)
- [x] hook up correct sequences to associated drop-downs (defined above) (Mrinalini and Matt ustaxcourt/ef-cms-flexion#6593)
- [x] add seed data for order/opinion associated to test legacy judge (Mrinalini, Matt, Jojo ustaxcourt/ef-cms-flexion#6609)
- [x] create cognito users for each judge, disable/archive legacy judges (Matt, Jojo ustaxcourt/ef-cms-flexion#6671)
- [x] local env: generate userId upon import (Matt, Jojo ustaxcourt/ef-cms-flexion#6671)
  - **maybe**: append new json file (`judge_users.json`) with user entries (`users.json`) after import and .gitignore
- [x] output lastname and judgeUserId map after import (Matt, Jojo ustaxcourt/ef-cms-flexion#6671)
  - e.g. `{ buch: '1f1aa3f7-e2e3-43e6-885d-4ce341588c76', ... }`
- [x] ~modify case migration code~ (field already in `Case` entity)
  - include `judgeUserId` 
- [x] update migration documentation to reflect `judgeUserId` in updated schema (Matt, Jojo ustaxcourt/ef-cms-flexion#6671)
- [x] double check: places where we use linked judges to include `judgeUserId` (e.g. orders)
- [x] add signedJudgeUserId to DocketEntry (for future) (Matt ustaxcourt/ef-cms-flexion#6707)
- [x] format judge name with title on Create Message modal (Matt ustaxcourt/ef-cms-flexion#6707)
- [x] import legacy judge users to dev env (Matt / JoJo)
- [x] Replace legacy judge Armen in unit tests w/ current Judge (Matt ustaxcourt/ef-cms-flexion#6753)
- [x] Replace endpoint with users endpoint for password consistency (Matt / Jojo ustaxcourt/ef-cms-flexion#6768)

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by alsmith1** [comment]
List of Current and Past judges from USTC site (updated 9.25.2020):

**Current/Active Judges:**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/1f725dea-fe8e-4611-8be1-59964fc54fa1)

**Legacy/Inactive Judges:**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/643dbfa3-77ba-44ad-a50c-75cebffe636c)

**All Judges:**
Aarons
Armen
Ashford
Beghe
Buch
Buckley
Cantrel
Carluzzo
Chabot
Chiechi
Clapp
Cohen
Colvin
Copeland
Couvillion
Dawson
Dean
Dinan
Drennen
Fay
Featherston
Foley
Gale
Galloway
Gerber
Goeke
Goffe
Goldberg
Greaves
Gussis
Gustafson
Guy
Haines
Halpern
Hamblen
Holmes
Jacobs
Jones
Kerrigan
Korner
Kroupa
Laro
Lauber
Leyden
Marshall
Marvel
Morrison
Nameroff
Nega
Nims
Pajak
Panuthos
Paris
Parker
Parr
Pate
Peterson
Powell
Pugh
Raum
Ruwe
Scott
Shields
Simpson
Sterrett
Swift
Tannenwald
Thornton
Toro
Urda
Vandervort
Vasquez
Weiler
Wells
Whalen
Wherry
Whitaker
Wilbur
Wiles
Williams
Wolfe
Wright

**Comment by sutt0n** [comment]
OCR'd list of active judges:
```
Ashford	
Buch	
Carluzzo	
Cohen	
Colvin	
Copeland	
Foley	
Gale	
Goeke	
Greaves	
Gustafson	
Guy	
Halpern	
Holmes	
Jones	
Kerrigan	
Lauber	
Leyden	
Marshall	
Marvel	
Morrison	
N ega	
Panuthos	
Paris	
Pugh	
Ruwe	
Thornton	
Toro	
Urda	
Vasquez	
Weiler	
Wells
```

OCR'd list of legacy judges:
```
Aarons	
Armen	
Beghe	
Buckley	
Cantrel	
Chabot	
Chiechi	
Clapp	
Couvillion	
Dawson	
Dean	
Dinan	
Drennen	
Fay	
Featherston	
Galloway	
Gerber	
Goffe	
Goldberg	
Gussis	
Haines	
Hamblen	
Jacobs	
Korner	
Kroupa	
La ro	
Nameroff	
Nims	
Pajak	
Parker	
Parr	
Pate	
Peterson	
Powell	
Raum	
Scott	
Shields	
Simpson	
Sterrett	
Swift	
Tannenwald	
Vandervort	
Whalen	
Wherry	
Whitaker	
Wilbur	
Wiles	
Williams	
Wolfe	
Wright	

```

**Comment by mariahkannenberg** [comment]
Chief Judge title is not important for search; but is important for some of the filters. 
For search, if it makes sense to treat the Judge Foley separate from Chief Judge Foley for search purposes, that's fine for MVP. 

F/Jojo - we’ll prolly have to start persisting the chambers/sections in dynamo since these will change regarding current/legacy judges

Chief Judge's signature is always the same.
How do we import all of the legacy data that has a judge associated with them, make sure we're able to search and get results. We don't know what the legacy data looks like. (e.g.From 2015-2017 what does Judge Marvel look like?) We could search for both, if the pattern is consistent w/judge naming. 

Find out f/Mark

**Comment by klohman** [comment]
## Test Scenarios

#### 1a) Users can select from legacy and current judges in Order filter 
* Login as docket clerk 
* Go to Advance Search > Orders 
* Enter search term
* Open judge filter options
Expected results 
- [x] Dropdown contains all legacy and current judges 

#### 1b) Users filters by legacy judges in Order search 
* Scenario 1 
* Select legacy judge from dropdown 
* Search 
Expected results 
- [x] App displays Order matches for keyword and legacy judge 

#### 1c) Users filters by current judges in Order search 
* Scenario 1 
* Select current judge from dropdown 
* Search 
Expected results 
- [x] App displays Order matches for keyword and current judge 

#### 2a) Users can select from legacy and current judges in Opinions filter 
* Login as docket clerk 
* Go to Advance Search > Opinions 
* Enter search term
* Open judge filter options
Expected results 
- [x] Dropdown contains all legacy and current judges 

#### 2b) Users filters by legacy judges in Opinion search 
* Scenario 1 
* Select legacy judge from dropdown 
* Search 
Expected results 
- [x] App displays Opinion matches for keyword and legacy judge 

#### 2c) Users filters by current judges in Opinion search 
* Scenario 1 
* Select current judge from dropdown 
* Search 
Expected results 
- [x] App displays Opinion matches for keyword and current judge 

#### 3a) Users sees legacy judge associated with case in Case Header
* Go to case with legacy judge associated (need migrated/test data)
Expected results 
- [x] Legacy judge name displays in Case Header 

#### 3b) Users sees current judge associated with case in Case Header
* Go to case with current judge associated
Expected results 
- [x] current judge name displays in Case Header

#### 4a) Users can filter by legacy judge associated with session in Trial Session list (Closed, All)
* Go to Trial Sessions 
* Click Closed tab 
* Filter by legacy judge (need migrated/test data for legacy trial session)
Expected results 
- [x] Judge filter contains legacy and current judges
- [x] Trial sessions display that match selected legacy judge

#### 4b) Users can filter current judge associated with session in Trial Session list (Closed, All)
* Go to Trial Sessions 
* Click Closed tab 
* Filter by current judge 
Expected results 
- [x] Judge filter contains legacy and current judges
- [x] Trial sessions display that match selected current judge

#### 5) Users can only select from current judges for messages 
* Go to a case 
* Click Create and “Message” 
* Select section “Chambers” 
* View Select chambers options
Expected results 
- [ ] Chambers dropdown only contains current judges

#### 6) Users can only select from current judges when adding a new trial session
* Go to Trial Session 
* Click Add Trial Session 
* View “Select judge” options 
Expected results 
- [x]  dropdown only contains current judges

#### 7) Users can only select from current judges  when adding a court-issued docket entry
* Go to case 
* Create Order / Sign/ Save 
* Add Docket Entry 
* View Judge’s Name options
Expected results 
- [x] dropdown only contains current judges

#### 8a) Users can only filter from current judges for Trial Session list (New, Open)
* Go to Trial Sessions 
* Click New tab 
* Filter by current judge 
Expected results 
- [x] Judge filter contains current judges
- [x] Trial sessions display that match selected current judge

#### 8b) Users can only filter from current judges for Trial Session list (New, Open)
* Go to Trial Sessions 
* Click Open tab 
* Filter by current judge 
Expected results 
- [x] Judge filter contains current judges
- [x] Trial sessions display that match selected current judge

#### 9a) Users can only filter from current judges and “Chief Judge” for Pending Report 
* Click Reports > Pending Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [ ] Judge filter contains current judges and Chief judge option
- [ ] Documents display that match selected current judge

#### 9b) Users can only filter from current judges and “Chief Judge” for Pending Report 
* Click Reports > Pending Report 
* Select Chief Judge
* View Report
Expected results 
- [x] Judge filter contains current judges and Chief judge option
- [x] Documents display that match selected current judge

#### 10a) Users can only filter from current judges for Case Inventory Report 
* Click Reports > Case Inventory Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [x] Judge filter contains current judges and Chief judge option
- [x] Cases display that match selected current judge

#### 10b) Users can only filter from current judges and “Chief Judge” for Case Inventory Report 
* Click Reports > Case Inventory Report 
* Select Chief Judge
* View Report
Expected results 
- [x] Judge filter contains current judges and Chief judge option
- [x] Documents display that match selected current judge

#### 11a Users can only filter from current judges for Deadlines Report 
* lick Reports > Deadlines Report 
* Select current judge [Judge Buch]
* View Report
Expected results 
- [x] Judge filter contains current judges and Chief judge option
- [x] Cases display that match selected current judge

#### 11b) Users can only filter from current judges and “Chief Judge” for Deadlines Report 
* Click Reports > Deadlines Report 
* Select Chief Judge
* View Report
Expected results 
- [x] Judge filter contains current judges and Chief judge option
- [x] Cases display that match selected current judge

#### 12) User searches for Order signed by Chief Judge [Foley] using judge filter [Foley]
* Login as docket clerk 
* Go to Advanced Search > Orders 
* Enter search term
* Select Foley as judge filter 
Expected results 
- [ ] Orders with keyword and signed by Judge Foley and Chief Judge Foley display in results 

#### 13) User searches for Opinion signed by Chief Judge [Foley] using judge filter [Foley]
* Login as docket clerk 
* Go to Advanced Search > Opinion 
* Enter search term
* Select Foley as judge filter 
Expected results 
- [ ] Opinion with keyword and signed by Judge Foley and Chief Judge Foley display in results

**Comment by sutt0n** [comment]
Questions:
- can't import `userId` into Cognito since we get the `userId` after a cognito account is created
  - create Cognito account and disable, or don't create one at all for legacyJudges (via @mmarcotte)
- dropdown: `Judge <Name>` or just `<Name>`? e.g. `Judge Cohen` vs. `Cohen`
- ~dev: checking for existing judges prior to creation (use ES and create an ES index?)~

**Comment by matthopson** [comment]
These are some notes from discussions in Slack, that I wanted to put here so they stay with the story - this is mostly related to fields for data migration and searches.

#### Document Search Associations
```
Opinion - judge: judgeFullName
Order - signedJudgeName: judgeFullName
Today's Opinions - judge: judgeFullName
Opinion Public Search - judge: judgeFullName
Order Public Search - signedJudgeName: judgeFullName
```

#### Entity Judge Associations
```
Case:
  associatedJudge - name of assigned judge based on trial session: defaults to Chief Judge
DocketEntry:
  judge - judge associated with the document filing (NOT signatory)
  signedJudgeName: - the full name of the judge who signed the document
WorkItem:
  associatedJudge: - name of assigned judge: defaults to Chief Judge
TrialSession:
  judge - obj containing {name, userId} for associated judge
```

##### Future-proof fields that are not currently not being used, but likely will with a refactor, so important for legacy migrations.
```
Case.judgeUserId (associated judge id)
DocketEntry.judgeUserId (associated judge id)
DocketEntry. signedJudgeUserId (id of judge whose signature is on the document)
```
