### ISSUE TITLE
Prod: Configure and Test Email Domain for electronic service

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7125]
As the Court, in order to serve the IRS, we need to configure AWS service to come from the ustaxcourt.gov 
domain. 

NOTE: See emails in comments below about Court's use of DMARC

## Acceptance Criteria
* Parties (petitioners, practitioners, IRS attorney, and IRS superuser) are assured that service email is from the Tax Court

## Notes
* Determine who needs to do the work - collab w/Mike
* Consider using `ustaxcourt.gov` subdomain.
* Ensure Court has enabled DMARC, and DKIM and/or SPF, on the domain name and on the email servers.
* Ensure AWS SES emails are compatible and working.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] run dig commands to find out validity
  - spf `dig txt mail.ustaxcourt.gov`
  - dkim `dig txt noreply._domainkey.mail.ustaxcourt.gov`
  - dmarc `dig txt _dmarc.mail.ustaxcourt.gov`
- [x] analyze responses
- [x] address problems
  - ~no DMARC policy set (quarantine / reject)~ setting DMARC policy to new env var (see below)
- [x] set DMARC policy to one env variable (Jojo / Rachael / Matt ustaxcourt/ef-cms-flexion#6328)
  - `EMAIL_DMARC_POLICY = "v=DMARC1; p=none; rua=mailto:blah@ustaxcourt.gov;"`

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
