### ISSUE TITLE
Index number - Do not give an item an index number until it's been served

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7133]
In order to provide proper ordering on the docket record, we need to  not give a document an index number until the document has been served. 

An item that's added to the docket record will not receive an index number until it is served. This item should fall to the bottom of the docket record until it's served

## Acceptance Criteria 
* Documents (both court issued and paper filed) should not have an index number until served.
* When the document is served, it gets the next available index number
* Sort order on docket record is by date. If items have the same date, sorted by index number (time is irrelevant)
* Ensure unservable documents still have an index number

## Notes
Add/clarify AC??
* Does this apply to Petitions / associated documents as well? No, doesn't apply. 
* Confirm it applies to both paper filings not served and court-issued documents not served . Correct.
* need to make sure the is Unservable documents still work correctly 
* For an unserved docket entry should always display as the last entry? Or display as entered? 
* Don't need to change anything related to filing date for either court issued or paper-filed
* Utilize scenarios Kristen created one fine Friday afternoon. 
* Doesn't affect minute entries. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update DocketRecord entity and methods (Matt ustaxcourt/ef-cms-flexion#6068)
  - [x] 1a Make index optional
  - [x] 1b Replace index with docketRecordId as identifier in methods
- [x] 2 Remove implicit index creation until served (Matt ustaxcourt/ef-cms-flexion#6068)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Saving and Serving Petition package (unchanged-just for reference) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2d0cfe2e-93a1-487a-b50b-2171358f1d0f)

* Petition and any other initial documents (uploaded with petition) show an index number associated

## Saving and Serving Paper Filed Document 

**Docket clerk saves paper-filed document to docket record without document uploaded**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ec014829-cadc-46cb-94c7-e3ad70b93510)

* Docket entry does not have index number associated

**Docket clerk saves paper-filed document to docket record with document uploaded**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bba00567-1681-4f22-8ac1-4ee894700a99)

* Docket entry does not have index number associated

## Saving and Serving Court-Issued Document 
**Docket clerk saves court-issued document to docket record ("servable" documents)**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3872ed4b-adb6-4ecd-b304-4605d308859a)

* Docket entry does not have index number associated

**Docket clerk saves court-issued document that "isUnservable" to docket record**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3c252116-5db9-434d-92b7-71ffc4ff23cf)

* Docket entry has index number associated

**Comment by klohman** [comment]
### Test Scenarios 4881

Test data 
- Create case by paper 
    - Case xx1-20
        - Petition 
            - Date received 07/28/20
            - Party type = Corporation 
            - Upload ODS 
            - Upload RQT
            - Upload APW 
        - File paper “Answer” (paper) 
            - Date received 07/29/20
            - Save and Serve
    - Case xx3-20
        - Petition 
            - Date received 07/28/20 
        - File paper “Answer” (paper) 
            - Date received 07/29/20
            - Save and Serve
- E-file case as petitioner 1
    - Case xx4-20
        - Serve Petition

#### 1a) User sees index number for paper-filed Petition documents that have not been served 
* Login as petitionsclerk
* Start a New Petition
    * Party type = Corporation 
*. Upload Petition, RQT, ODS
* View docket record 
Expected results
- [x] Docket record is sorted as: 
    - Index 1: [today’s date] Petition
    - Index 2: [today’s date] Request for Place of Trial
    - Index 3: [today’s date] Ownership Disclosure Statement

#### 1b) User sees index number for e-filed Petition documents that have not been served 
* Login as petitioner1 
* File Petition (case xx2-20)
    * Party type = Corporation 
* View docket record 
Expected results
- [x] Docket record is sorted as: 
    - Index 1: [today’s date] Petition
    - Index 2: [today’s date] Request for Place of Trial
    - Index 3: [today’s date] Ownership Disclosure Statement

#### 2) User does not see index number for paper-filed document saved to docket record without PDF 
* Login as docket clerk 
* Navigate to case xx1-20 
* Add Paper Filing 
* Date received = [07/28/20]
* Document type = Motion for New Trial 
* Do not upload PDF 
* Click Save Entry 
* View docket record 

Expected results 
- [x] Docket entry displays entry for Motion for New Trial with in progress icon and yellow background 
- [x] Motion for New Trial entry does not display index number 


#### 3) User does not see index number for paper-filed document saved to docket record with PDF 
* Scenario 1 
* Navigate to case xx2-20 
* Add Paper Filing 
* Date received = [today’s date]
* Document type = Motion for New Trial 
* upload PDF 
* Click Save Entry 
* View docket record 

Expected results 
- [x] Docket entry displays entry for Motion for New Trial with in progress icon and yellow background 
- [x] Motion for New Trial entry does not display index number 


#### 4) User does not see index number for court-issued document saved to docket record (excluding docs that cannot be served) 
* Navigate to case xx1-20 
* Create, sign, save entry for Order 
* View docket record 
Expected results 
- [x] Docket entry displays entry for Order with in progress icon and yellow background 
- [x] Order entry does not display index number
- [x] Order entry does not display Filed date

#### 5) User does see index number for “unservable” court-issued document saved to docket record  
* Navigate to case xx2-20
* Upload PDF to drafts
* Add Docket Entry for PDF draft
* Select doc type = “Trial before” 
* Complete form
* Save Entry 
* View docket record 
Expected results 
- [x] Docket entry displays entry for “Trial Before…” without in progress icon or background
- [x] “Trial before” entry displays index number
- [x] “Trial before” entry displays Filed by = [today’s date]
- [x] “Trial before” entry displays Served  =  blank

#### 6) User sees docket record sorted by filed date, then index number 
* Scenario 2 
* Navigate to case xx1-20 
* Add Paper Filing 
* Date received = 07/28/20
* Document. Type - Motion for Continuance 
* Save and Serve 
* View sorted docket record 
Expected results 
- [x] Docket record sort order: 
    - Index 1: 07/28/20 - Petition
    - Index 2: 07/28/20 - Application for Waiver of Filing F
    - Index 3: 07/28/20 - Request for Place of Trial
    - Index 4: 07/28/20 - Ownership Disclosure Statement
    - Index 6: 07/28/20 - Motion for Continuance
    - No index: 07/28/20 - Motion for New Trial 
    - Index 5: 07/29/20 Answer 

#### 7) User sees unserved court-issued docket entries sorted to end of docket record 
* Navigate to case xx3-20 
* Create Notice 
* Add Docket Entry for Notice 
* Save entry 
* Create, sign, and serve Order for Dismissal 
* View docket record 
Expected results 
- [x] Docket record sort order: 
    - Index 1: 07/28/20 - Petition 
    - Index 2: 07/29/20 - Answer 
    - Index 3: [today’s date] - Order for Dismissal 
    - No index [no Filed Date] - Notice 

#### 8) User sees index number applied to court-issued document after service 
* Scenario 7 
* Go to Document QC > In Progress 
* Click on Notice for case xx3-20
* Save and Serve document
Expected result 
- [x] Notice docket entry displays index number 
- [x] Notice docket entry displays Filed date, Served, and served parties 

#### 9) User sees index number applied to paper-filed document after service 
* Scenario 7 
* Go to Document QC > In Progress 
* Click on Motion for New Trial for case xx2-20
* Save and Serve document
Expected result 
- [x] Motion for New Trial docket entry displays index number 
- [x] Motion for New Trial docket entry displays Filed date, Served, and served parties 


#### 10) Order is created, docket clerk adds Order to docket record but does not serve; party e-files a document same date; docket clerk serves the Order same date 
* Login as docketclerk1
* Navigate to case xx4-20 
* Create “Order to Dismiss”, add to docket record and save (do not serve)
* Login as irsPractitioner1 
* Navigate to case xx4-20
* File Answer 
* Login as docketclerk1
* Navigate to case xx3-20 
* Serve Order to Dismiss
Expected results:
- [x] Docket record order:
- Index 1, Date Filed [today’s]: Petition
- Index 2, Date Filed [today’s]: Requested Place of Trial Baltimore, MD
- Index 3 Date filed [today’s date]: Ownership Disclosure Statement
- Index 4: Date filed [today’s date]: Answer
- Index 5: Date filed [today’s date]: Order to Dismiss

#### 11) Users do not see index number for paper-filed RQT, ODS, or APW added after Petition (not as an initial. document ) and not served
* Login as petitions clerk 
* Start a new case 
* Complete form and save case (Case xx5-20)
* Serve Petition  
* login. as docket clerk 
* Navigate to case xx5-20
* Add Paper Filing = RQT
*.Save entry 
* add paper filing = ODS 
* Save entry 
* Add paper filing = APW 
* Save entry 
*. View docket record 
expected results. 
- [x] Docket record displays as 
    * Index 1 - [filed date] - Petition
    * No index - [filed date] - RQT
    * No index - [filed date] - ODS
    * No index - [filed date] - APW

#### 12) Users sees index number for paper-filed RQT, ODS, or APW added after Petition (not as an initial. document ) and served 
* Scenario 11 
* Serve RQT 
* Serve ODS 
* Serve APW 
* View docket record 
expected results 
- [] Docket record displays as 
    * Index 1 - [filed date] - Petition
    * Index 2 - [filed date] - RQT
    * Index 3 - [filed date] - ODS
    * Index 4 - [filed date] - APW
