### ISSUE TITLE
POC: Multi-Factor Authentication for IRS Superuser login

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7141]
As a development team, in order to fully vet out security requirements for the IRS superuser login, we need to create a proof of concept for our proposed MFA solution. 

## Acceptance Criteria
- Do more research into MFA
- Determine final approach
- Review proposed solution w/Flexion security experts
- Finalize approach
- Create a proof of concept to vet out security requirements for the IRS superuser login. 
- Create a proof of concept to successfully log in w/IRS superuser w/MFA
 - POC has been reviewed and approved by Court Security stakeholders

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [ ] 1 Create separate user pool in Cognito (Rachael ustaxcourt/ef-cms-flexion#4979)
* MFA enabled (required), TOTP only (no SMS)
* app client with no secret key, enabled ADMIN_NO_SRP_AUTH and USER_PASSWORD_AUTH
* a cognito UI setup (similar to our currently pool if not identical to it)
* same attributes as our current pool
* probably turn off the ability for people to register
- [ ] 2 Look into only allowing a single device to log in https://aws.amazon.com/blogs/mobile/tracking-and-remembering-devices-using-amazon-cognito-your-user-pools/

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
- [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [ ] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt 
 - [ ] Deployed to the dev environment
- [ ] Deployed to the stage environment
