### ISSUE TITLE
Legacy Data: Linking users with existing cases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7151]
As a petitioner who has open cases in the current CMS and e-Access, I need the ability to log in to the new CMS and see my open cases.

## Acceptance Criteria
* Legacy petitioners needing access to CMS are notified about how to access
* Only legacy petitioners w/ current e-Access account **and** at least one open case should be able to log into the new system and see their open case(s)
* Legacy petitioners w/o current e-Access accounts or only closed cases should not be able to log in to the new system 
* Court users can easily identify which petitioners have e-Access to the new system

## Notes
* Legacy petitioners only need access to open cases.
* If it's hard to link multiple open cases to 1 petitioner (edge case), it is OK to treat each as a separate petitioner (i.e., multiple accounts) DECISION 8/19/2020 (per Jessica) -- one-to-one relationship; if a legacy petitioner has more than 1 open case, he/she may end up with multiple accounts 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
Questions: 
- [ ] How will the users be created? Will it be with a script that includes a UUID for each user? We don't have a process for this currently. - this story is for creating the users
- [ ] Is this only for pro-se petitioners? yes
- [ ] Can we associate the user as part of a migration step? Or does this need to be a separate endpoint? - ask Mark if this should be a 2-step process or if the users should be created as part of the case migration
- [ ] Is there only one user account per case? there might be more than 1 - need to see if the system can handle that

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by rachaelparris** [comment]
Mark has reviewed, this just needs to go to staging.
