### ISSUE TITLE
Petitions/Calendar Clerk & Docket Clerk: Add and display statistics after petition served

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7152]
As a Petitions/Calendar Clerk and/or Docket Clerk, so that I can record the outcome of the case, I need the ability to add statistics to the case metadata.

## Acceptance Criteria
* For **deficiency** cases, a Petitions/Calendar Clerk and/or Docket Clerk must have the ability to capture the following information for each tax year after the petition is served:  

   (1) Deficiency amount determined by Court; and
   (2) Aggregate penalty amount determined by Court.

[Note: For all other case types (CDP, Whistleblower, Passport, Partnership, etc.), we will not capture any amounts at issue or amounts determined by the Court.]
 
* For all cases, a Petitions/Calendar Clerk or Docket Clerk must have the ability to capture after the petition is served:
   (1)  Litigation costs; and
   (2)  Damages under IRC §6673

* These case statistics should be viewable to all Court employees
* Case statistics are not viewable by external users

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Updates to entities (Rachael ustaxcourt/ef-cms-flexion#5276)
  - [x] 1a Add determination amount for deficiency and penalties to Statistics entity (Rachael ustaxcourt/ef-cms-flexion#5276)
  - [x] 1b Add other statistics to Case entity (not an array, just the 2 additional fields) (Rachael ustaxcourt/ef-cms-flexion#5276)
- [x] 2 Add Statistics tab to case detail page - Case Information tab (only displays for internal users) (Rachael ustaxcourt/ef-cms-flexion#5278 ustaxcourt/ef-cms-flexion#5279)
  - [x] 2a If no statistics, display message
  - [x] 2b Add table display of statistics (Rachael)
  - [x] 2c Edit buttons for tables (check user role) (Rachael)
- [x] 3 Display Add Deficiency Statistics and Add Other Statistics buttons if correct user role and case type (Rachael ustaxcourt/ef-cms-flexion#5284)
- [x] 4 Add route and view for Add Deficiency Statistics form (Cody ustaxcourt/ef-cms-flexion#5282)
  - [x] 4a Sequences and actions for submitting the form (Matt ustaxcourt/ef-cms-flexion#5298)
  - [x] 4b Endpoint for submitting the form (Rachael ustaxcourt/ef-cms-flexion#5293)
  - [x] 4c Calculate penalties as determined by court modal (Cody ustaxcourt/ef-cms-flexion#5282)
  - [x] 4d Validation (Cody ustaxcourt/ef-cms-flexion#5294)
  - [x] 4e Fix Styles (Cody ustaxcourt/ef-cms-flexion#5294) 
- [x] 5 Add route and view for Add Other Statistics form (Rachael)
  - [x] 5a Sequences and actions for submitting the form (Matt ustaxcourt/ef-cms-flexion#5292)
  - [x] 5b Endpoint for submitting the form (Rachael ustaxcourt/ef-cms-flexion#5288)
  - [x] 5c Validation

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
