### ISSUE TITLE
Petitions Clerk: Revamp - Serve or Save for Later an E-Filed Petition

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7154]
As a petitions clerk, so that I may serve a petition or save it in while in progress, I need the e-filed petition revamped. 

## Acceptance Criteria
* Petition clerk can save an e-filed petition to serve later 
* Save for Later - leaves petition in In Progress tab 
* Petition clerk can serve an e-filed petition and associated documents in real-time 

On serve:
* Coversheets for all Petition documents receive Served date ( not duplicate cover sheets and do not replace, just served stamp)
* IRS super user receives service email for Petition and other documents (separate email for each)
* IRS super user has party access to the case but does not display under respondent counsel
* Petition Notice of Receipt is generated and link is available on Case Info screen
* Docket entries display served date and “R” for parties 
* If changes were made to case caption, a minute entry is added to the docket record (delta between initial entry and when served)
* If changes were made to docket number suffix (by editing case procedure or case type), a minute entry is added to the docket record (delta between initial entry and when served)
* Petition and other documents are visible under Served tab 
* Case status changes to General Docket - Not at Issue 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 After serving petition, navigate to My Document QC => Inbox with success message (Rachael ustaxcourt/ef-cms-flexion#5353)
- [x] 2 Check processed by column in Served box - why is it a uuid? (Rachael ustaxcourt/ef-cms-flexion#5353)
- [x] 3 Coversheet fixes - should not have 2 coversheets (Rachael ustaxcourt/ef-cms-flexion#5356)
- [x] 4 Verify create docket entry if changes were made to case caption
- [x] 5 Verify create docket entry if changes were made to docket number

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
