### ISSUE TITLE
Petitions/Calendar Clerk & Docket Clerk: Edit statistics after petition is served

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7157]
As a Petitions/Calendar Clerk and/or Docket Clerk, so that I can record the outcome of the case, I need the ability to add statistics to the case metadata.

## Acceptance Criteria
* For **deficiency** cases, a Petitions/Calendar Clerk and/or Docket Clerk must have the ability to edit the following information for each tax year after the petition is served:  

   (1) Deficiency amount determined by Court; and
   (2) Aggregate penalty amount determined by Court.

[Note: For all other case types (CDP, Whistleblower, Passport, Partnership, etc.), we will not capture any amounts at issue or amounts determined by the Court.]
 
* For all cases, a Petitions/Calendar Clerk or Docket Clerk must have the ability to edit after the petition is served:
   (1)  Litigation costs; and
   (2)  Damages under IRC §6673

* These case statistics should be viewable to all Court employees
* Case statistics are not viewable by external users

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create Edit Deficiency Statistics base view and route (Rachael ustaxcourt/ef-cms-flexion#5315)
  - [x] 1a Delete Year/Period UI functionality (display modal) (Rachael)
  - [x] 1b Calculate penalties functionality
  - [x] 1c Form validation
  - [x] 1d Sequences, actions to submit (Rachael ustaxcourt/ef-cms-flexion#5318)
  - [x] 1e Endpoint to update statistic (Rachael ustaxcourt/ef-cms-flexion#5312)
  - [x] 1f Endpoint to delete statistic (Rachael)
- [x] 2 Create Edit Other Statistics view and route (Cody ustaxcourt/ef-cms-flexion#5306)
  - [x] 2a Sequences, actions to submit (Cody ustaxcourt/ef-cms-flexion#5306)
  - [x] 2b Endpoint (might be able to use endpoint from last story?)
  - [x] 2c Delete Other Statistics functionality (Cody ustaxcourt/ef-cms-flexion#5306)

## Definition of Done (Updated 1-30-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
- [x] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt 
 - [x] Deployed to the dev environment
- [x] Deployed to the stage environment
