### ISSUE TITLE
Docket Clerk: Provide "other" filing party during QC and paper filing

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7163]
Sometimes someone other than a party to the case submits a document to the Court.  The Docket Clerk needs the ability to add that person as the "filing party" when processing that paper document.  The Docket Clerk also needs the ability to enter/change the name of the filing party to anything when QC'ing an electronic document.

## Acceptance Criteria
* Provide "Other" and free text box as an option for filing party when Docket is QC'ing an eFiled document
* Provide "Other" and free text box as an option for filing party for a paper filing
* Text entered in "Other" box displays as filing party on the docket record
* Doesn't create another party in the case

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 'Other' checkbox and input field UI and validation when QC'ing e-filed docket entry - Mrin & Rae ustaxcourt/ef-cms-flexion#5871
- [x] Save 'Other' value when QC'ing an e-filed Docket Entry - Rachael ustaxcourt/ef-cms-flexion#5874
- [x] 'Other' checkbox and input field UI and validation when adding a paper docket entry - Mrin & Rae ustaxcourt/ef-cms-flexion#5871
- [x] Save 'Other' value when adding a paper petition Docket Entry - Rachael ustaxcourt/ef-cms-flexion#5874
- [x] Display 'Other' value as 'Filing Party' on Docket Record - Rachael ustaxcourt/ef-cms-flexion#5874
- [x] Generate Notice of Docket Change when 'Other' party is added - Rachael ustaxcourt/ef-cms-flexion#5874

Refactoring:
~- [ ] updateDocketEntryFormValueSequence has 2 actions that do similar things - clean this up~[ Moved to devex trello board](https://trello.com/c/aQ0Nm6L7/687-refactor-updatedocketentryformvaluesequence)
- [x] look at Document.generateFiledBy - why is this called in the constructor (without case detail) and also in some interactors? - Rachael
- [x] DRY up filing party UI checkboxes into reusable component - Rachael ustaxcourt/ef-cms-flexion#5875 
 
## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Docket Document QC screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8ef46467-b37e-4e97-b3ee-5b971e34982b)

**Who is filing this document field**
* add new checkbox for “Who is filing this document?” labeled “Other” 
* On click of “Other” checkbox, the “Other Filing Party Name” field displays  

**Other Filing Party Name**
* Is conditionally required if “Other” checkbox is selected 

**On Complete of QC**
* Other Filing Party name is included in the Filed By column in the Docket Entry 
* a Notice of Docket Change is generated 

#### Add Docket Entry screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a64ef611-1020-40d2-ae5d-4339fe0124a5)

**Who is filing this document field**
* add new checkbox for “Who is filing this document?” labeled “Other” 
* On click of “Other” checkbox, the “Other Filing Party Name” field displays  

**Other Filing Party Name**
* Is conditionally required if “Other” checkbox is selected 

**On Save and Serve or Save for Later**
* Other Filing Party name is included in the Filed By column in the Docket Entry 


#### Docket Record 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6c3d1aac-3f18-4371-a209-1e05bbd18ca6)

#### Docket Entry with Other Filing Party

**Other Filing Party as the only filing party**
* Filed By should displays [Other Filing Party Name[

**Other Filing Party with multiple filing parties**
* Other filing party name should be appended to the other Filed By information : Resp. & Petr. [Primary Contact], [Other Filing Party Name]


### Edit Docket Entry (/edit-meta)
On click of Edit link from an existing docket entry
* Other is displayed as an option under Who is filing this document
* If "Other" is checked, "Other filing party name" field displays 
* any existing data from QC or Add DOcket Entry should be displayed in fields 

**On save**
* updates to Filed By should display on docket entry 
* a Notice of Docket Change is not generated when updated from this flow

**Comment by klohman** [comment]
### 5381 Tests 

Test data 
- Case xx1-20 - (Party type=Petitioner)
    - Petitioner name - Bobby Sue
    - File “Motion for Summary Judgement” as petitioner 
- Case xx2-20 (Party type= Petitioner and Spouse)
    - File “Motion for New Trial” as petitioner and spouse
    - 

#### 1) Docket clerk adds Other Filing Party during QC 
* Login as docket clerk 
* Navigate to Section Document QC > Inbox 
* Click on Motion for Summary Judgement 
* Select “Other” under Who is filing this document 
* Enter John Smith 
* Leave Petitioner selected as Filing party 
* Complete QC 
Expected results 
- [x] on check of “Other”, “Other Filing Party Name” field displays 
- [x] on complete of QC, a Notice of Docket Change is generated and added to the Docket Record 

#### 2) Docket clerk adds Other Filing Party to paper filing 
* Login as docket clerk 
* Navigate to case xx2-20 
* Click “Add Docket Entry” from Actions menu 
* Enter doc type = Administrative Record 
* Select “Other” under Who is filing this document 
* Enter John Smith 
* Complete entry  
Expected results 
- [x] on check of “Other”, “Other Filing Party Name” field displays 

#### 3) Docket clerk sees Other Filing Party as solo filer on docket entry 
* Scenario 2 
* Navigate to case xx2-20
* View docket entry for Administrative Record  
Expected results 
- [x] Filed By on Administrative Record entry displays as John Smith 


#### 4) Docket clerk sees Other Filing Party as additional filer on docket entry 
* Scenario 1 
* Navigate to case xx1-20
* View docket entry for Motion for Summary Judgement 
Expected results 
- [x] Filed By on Motion for Summary Judgement entry displays as Petr. Bobby Sue, John Smith 

#### 5) Docket clerk adds/edits Other Filing Party on existing docket entry 
* Scenario 1 
* Navigate to case xx1-20 
* Click Edit link next to Motion for Summary Judgement 
* Update Other Filing party name to John Jones 
* Save 
Expected results 
On click of Edit link:
- [x] App navigates to Edit Docket Entry (/edit-meta) screen
- [x] Other is listed as option under Who is filing this document? and is checked 
- [x] Other filing party name field displayed "John Smith"
On click of Save: 
- [x] App navigates to Docket Record with success message displayed 
- [x] Filed By on Motion for Summary Judgement entry now. displays as Petr. Bobby Sue, John Jones
- [x] No Notice of Docket Change is generated
