### ISSUE TITLE
Docket Clerk: Remove Petitioner(s) from Case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7165]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to remove petitioner(s) from an existing case.

Over the course of a case, petitioners may enter or leave the case for various reasons.  Docket Clerks need the ability to remove one or more petitioners from a case. [Note: Adding Petitioners is covered in ustaxcourt/ef-cms#7166]

## Pre-Conditions
* Petitioner is associated with a case
* Refactor the way we story petitiones from primary, secondary an dother into one list of petitioners

## Acceptance Criteria
* Docket Clerk needs the ability to remove one petitioner from a case at a time.
* At least one petitioner must remain in the case at all times.
* Once removed from a case, the removed petitioner should no longer have any access to the case, except for the public view.
* Consider all the areas that the Petitioner needs to be removed from.
* Once petitioner is removed from the case, they are not "searchable" in the case, order and opinion searches
* User should no longer get service
* If the petitioner being removed from the case is represented by counsel, the counsel should also be removed from the case unless he/she is still representing a remaining party.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Once we get into the story,there will be more questions. 
* Possible dragons coming from validating cases after a petitioner has been removed.
- There could be consequences to changing things that aren't immediately obvious. 
- Any additional info needed when a petitioner is removed? Preceding the removal, there's an order for removal. 
- Do we need to keep record on the case that the petitioner was part of it? The petitioners' names are in the documents, including the order. 
- This story is for only the primary and secondary contacts. There will be separate stories for other petitioner types. 
- What happens when we remove a primary? 
- Consider how to handle petitioner's counsel if petitioner is removed and counsel is the same for both petitioners.
 - If we abandon party type, we have to make fields other than name and address optional. 
 - Need party type in place for creating a case - it's how the caption is created. 
 - During case creation, if petitioner and spouse or petitioner and deceased spouse, save both as petitioners. 

## Tasks
- [x] Add Remove This Petitioner button to Edit Petitioner Form - mob ustaxcourt/ef-cms-flexion#8189
  - [x] If <1 Petitioner on case, don’t show remove button
- [x] On click of remove petitioner button - Clarion
    - [x] Display Remove Petitioner Modal with case caption field editable ustaxcourt/ef-cms-flexion#8192
- [x] On submit of modal, remove petitioner sequence and actions - mob ustaxcourt/ef-cms-flexion#8197
- [x] Remove petitioner back end - mob ustaxcourt/ef-cms-flexion#8197
    - [x] If petitioner has eAccess, case is removed from dashboard and petitioner has public view of case
    - [x] If counsel ONLY represents the removed petitioner, petitioner counsel is removed from the case

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
- [x] Automated test scripts have been written
- [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
- [x] Verify that language for docket record for internal users and external users is identical
- [x] New screens have been added to pa11y scripts
- [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html
- [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
- [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
- [x] Interactors should validate entities before calling persistence methods
- [x] Code refactored for clarity and to remove any known technical debt
- [x] Acceptance criteria for the story has been met
- [x] Deployed to any Flexion environment for UX Review
- [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
UX Research Questions 
- What initiates removing a petitioner? 
- Do you need to document the reason why a petitioner was removed? 
- Do you need any record that the petitioner was once a part of the case? 
- how would you expect to perform this action?

**Comment by ericsorenson** [comment]
Possible dragons coming from validating cases after a petitioner has been removed.

**Comment by klohman** [comment]
## Edit Petitioner screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/808083e2-a785-415e-bad1-677a7ef2e6d4)

* Add Remove this Petitioner button 

## Remove Petitioner modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bb915c09-08e9-4a56-bccc-e818ba2389e1)

* on click of Remove this Petitioner button, display modal 

* Display selected petitioner name in warning message: "Are you sure you want to remove [petitioner name] from this case?"
* Display current case caption in editable field - Case Caption 

**On Yes, Remove**
* Modal closes, and app routes to Case Info > Petitioner tab with success message displayed: "Petitioner removed."
* Updated case caption displays in case header and in all places case title displays 
* Removed petitioner no longer displays in Petitioner tab 
* Removed petitioner no longer displays in Filing Parties for eFile a Document, Add Paper Filing forms
* Removed petitioner no longer displays in service parties in Add Docket Entry form 
* Removed petitioner no longer receives service 
* If petitioner has eAccess, case is removed from dashboard and petitioner has public view of case 

#### Removed petitioner represented by counsel
* If counsel ONLY represents the removed petitioner, petitioner counsel is removed from the case 
* If counsel represents the removed petitioner and a remaining petitioner, petitioner counsel remains on the case and displays as representing the remaining petitioner only 

#### One petitioner on case 
**If only one petitioner remains on case**
* hide "Remove this Petitioner" button on Edit Petitioner form

**Comment by klohman** [comment]
## 5385 Test Scenarios

#### 1) Docket clerk removes petitioner on a case with multiple petitioners 
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Click Yes, Remove 
Expected results 
On Edit Petitioner form 
- [x] Remove this Petitioner button display on form 
On click of Remove this Petitioner button 
- [x] modal displays 
- [x] petitioner name displays is warning message 
- [x] Current case caption is displayed in Case Caption field and is editable 
On Click of Yes, Remove 
- [x] modal closes and app routes to Petitioner tab with success message displayed 
- [x] Petitioner 1 no longer displays in Petitioner card 

#### 2) Docket clerk cannot remove petitioner on a case with a single petitioner 
* Login as docket clerk 
* Go to case 
    * Case has one petitioners 
* Click Edit on petitioner 1 
Expected results 
On Edit Petitioner form 
- [x] Remove this Petitioner button does not display on form 

#### 3) Docket clerk removes petitioner with counsel representing only one petitioner - MOVED TO 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
    * Private practitioner represents petitioner 1 
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Click Yes, Remove 
Expected results 
On Edit Petitioner form 
- [ ] Remove this Petitioner button display on form 
On click of Remove this Petitioner button 
- [ ] modal displays 
- [ ] petitioner name displays is warning message 
- [ ] Current case caption is displayed in Case Caption field and is editable 
On Click of Yes, Remove 
- [ ] modal closes and app routes to Petitioner tab with success message displayed 
- [ ] Petitioner 1 no longer displays in Petitioner card 
- [ ] Private practitioner no longer displays in Petitioner Counsel card 
- [ ] Private practitioner no longer has eAccess to case and case does not display on dashboard

#### 4) Docket clerk removes petitioner with counsel representing multiple petitioners - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
    * Private practitioner represents petitioner 1 and petitioner 2
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Click Yes, Remove 
Expected results 
On Edit Petitioner form 
- [ ] Remove this Petitioner button display on form 
On click of Remove this Petitioner button 
- [ ] modal displays 
- [ ] petitioner name displays is warning message 
- [ ] Current case caption is displayed in Case Caption field and is editable 
On Click of Yes, Remove 
- [ ] modal closes and app routes to Petitioner tab with success message displayed 
- [ ] Petitioner 1 no longer displays in Petitioner card 
- [ ] Private practitioner displays in Petitioner Counsel card as representing petitioner 2 only 

#### 5) Docket clerk removes petitioner and updates case caption 
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Update case caption
* Click Yes, Remove 
* Go to Overview tab 
* Click Edit Case Status/Caption
Expected results 
- [ ] modal closes and app routes to Petitioner tab with success message displayed 
- [ ] Petitioner 1 no longer displays in Petitioner card 
- [ ] updated case caption displays in case header 
- [ ] updated case caption displays in Case Caption field in Edit Case Status/Caption modal 

#### 6) Docket clerk removes petitioner and adds paper filing - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Remove petitioner 2
* Add Paper Filing 
* Save and Serve 
Expected results 
- [ ] petitioner 2 does not display under “Who is filing this document” in Add Paper Filing form
- [ ] petitioner 2 does not receive service 

#### 7) Docket clerk removes petitioner and serves court issued document - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Remove petitioner 2
* Upload PDF + Add Docket Entry 
* Save and Serve 
Expected results 
- [ ] petitioner 2 does not display under Service Parties on Add Docket Entry form
- [ ] petitioner 2 does not receive service 

#### 8) Docket clerk removes petitioner and party e-files a document - MOVED TO 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
        * Petitioner 1 has eAccess 
* Remove petitioner 2
* Login as petitioner 1 
* Go to case 
* efIle a Document
Expected results 
Expected results 
- [ ] petitioner 2 does not display under “Who is filing this document” in Add Paper Filing form
- [ ] petitioner 2 does not receive service 

#### 9) Docket clerk removes petitioner with eAccess and case no longer displays on petitioner dashboard 
* Login as docket clerk 
* Go to case 
    * Case has two petitioners with eAccess
* Remove petitioner 2
* Login as petitioner 2 
Expected results 
- [ ] case does not display on dashboard

**Comment by JessicaMarine** [comment]
PO Review:
- When I tried to remove any of the petitioners from 208-20SL on `mig` I got the following error: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/867d3d67-989c-42ac-a3de-ae33a6674f5e)

- Also, not sure if it's related to this work, or a separate bug, but in mig if you try to generate an order, I get a blank white screen with the deploy time: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/62214b14-4b5d-4c92-ac17-815c5e7d9e19)
