### ISSUE TITLE
Docket Clerk: Add petitioner(s) to existing case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7166]
As a Docket Clerk, in order to proper manage the parties to a case, I need the ability to add one or more petitioners to an existing case.

Over the course of a case, petitioners may enter or leave the case for various reasons.  Docket Clerks need the ability to add one or more petitioners to an existing case. [Note: Removing Petitioners is covered in ustaxcourt/ef-cms#7165]

## Pre-Condition: ##
* Case already exists with only 1 petitioner.
* Refactor primary, secondary and other petitioners into a simple list of petitioners on the case

## Acceptance Criteria: ##
* Docket Clerk needs the ability to add a second petitioners to an existing case.
* Once added to a case, the additional petitioner should be treated the same as a "contact secondary" petitioner.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Now may be the time to move away from primary/secondary/other petitioners and adopt a single array of petitioners.

## Tasks
- [x] Add petitioner button - mob ustaxcourt/ef-cms-flexion#8123
- [x] new route on click of add petitioner button - mob ustaxcourt/ef-cms-flexion#8124
- [x] Hide Add Petitioner button for non docket clerk users, or when the case has not been served - mob ustaxcourt/ef-cms-flexion#8128
- [x] Add Petitioner form
    - [x] UI - mob ustaxcourt/ef-cms-flexion#8127
    - [x] validation - mob ustaxcourt/ef-cms-flexion#8130
    - [x] Add existing address logic when checked - mob ustaxcourt/ef-cms-flexion#8143
    - [x] Add address logic when not checked - Mrinalini ustaxcourt/ef-cms-flexion#8144
- [x] Submit sequence for add petitioner form - Mrinalini ustaxcourt/ef-cms-flexion#8145
- [x] submit back end for add petitioner form - Rachael ustaxcourt/ef-cms-flexion#8146 
    - [x] interactor, lambda etc - Rachael ustaxcourt/ef-cms-flexion#8146 
    - [x] contactType - secondary - do the distinctions between contact types go away - Rachael ustaxcourt/ef-cms-flexion#8153 
- [x] Display other petitioners in case information petitioners tab - Tom ustaxcourt/ef-cms-flexion#8148
- [x] Edit link should display for newly added petitioner(s) - mob ustaxcourt/ef-cms-flexion#8177
- [x] Display addres 1, 2 and 3 in dropdown, and only display unique addresses - mob ustaxcourt/ef-cms-flexion#8182

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Cody & Mrin)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html (Cody & Mrin)
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated (Cody & Mrin)
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
UX research questions 
- What initiates this action? Why? 
- Does it matter that a petitioner wasn’t on the case initially? 
- Do we care when / why this person was added to the case? 
- Is this petitioner any different than the original petitioner? 
- How would you expect to perform this action?

**Comment by ericsorenson** [comment]
Notes: Now may be the time to move away from primary/secondary/other petitioners and adopt a single array of petitioners.

**Comment by klohman** [comment]
## Petitioner tab  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b2ae6e17-c41f-43ed-b2f5-f946d699aac8)

* display “Add Petitioner” button EXCEPT when case is in status = New


**Add Petitioner button**
* On click, navigate to Add Petitioner form 

## Add Petitioner form 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6345053a-3684-4109-816c-efd1ad56c5ff)

**Name** 
* is required 
* Error message if blank - “Enter name”

**Additional name** 
* is optional 

#### Use existing address checkbox 
**If checked**
* display dropdown 
* dropdown should include Mailing address line 1 for all existing petitioners on the case 
* when user selects address from dropdown, address (line 1-3), city, state, zip is populated with selected address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/812d27d2-52fc-424f-94d0-c1648f974155)


**if unchecked**
* dropdown is hidden 
* address fields (address (line 1-3), city, state, zip) are not pre-populated 

#### Login & Service 
* Options are Paper and None 

#### Case caption 
* Field is required 
* Field is pre-populated with current case title 
* on save, case caption is updated and displays updated in case header, and anywhere else case title appears

## On Save
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a68614e6-5c90-45f7-a673-4c362e3fd472)

- app routes back to Petitioner tab with success message displayed: “Petitioner [Name field] added to case.”  
- added petitioner information displays under Petitioner Contact Info 
- updated case caption displays in header and everywhere case title displays 
- added petitioner displays everywhere that lists the parties on the case 
   examples: 
        - Add Docket Entry - Service Parties 
        - File a Document - Who is filing this document? 
        - Add Paper Filing - Who is filing this document?

**Comment by klohman** [comment]
## 5386 Test Scenarios 

#### 1) Docket clerk sees options to add petitioner to case (for case in status = anything except “new”)
* Login as docket clerk 
* Go to case 
    * Case status = General Docket Not At Issue 
* Click Case Information > Petitioner 
Expected results 
- [x] “Add Petitioner” button displays 

#### 2) Docket clerk does not see options to add petitioner to case (for case in status = “new”)
* Login as docket clerk 
* Go to case 
    * Case status = General Docket Not At Issue 
* Click Case Information > Petitioner 
Expected results 
- [x] “Add Petitioner” button does not display


#### 3) Docket clerk adds petitioner with new address 
* Login as docket clerk 
* Go to case 
    * Case status = General Docket Not At Issue 
* Click Case Information > Petitioner 
* Complete Add Petitioner form 
    * Do not edit case caption field
* Click Save 
Expected results 
- [x] App routes to Petitioner tab with success message displayed: “Petitioner [name field] added to case.”
- [x] New petitioner contact information is displayed in Petitioner card 
- [x] New petitioner displays option to “Edit” 
- [x] New petitioner displays option to “Seal address” 
- [x] Case caption is not updated 

#### 4) Docket clerk adds petitioner using existing address 
* Login as docket clerk 
* Go to case 
    * Case status = General Docket Not At Issue 
* Click Case Information > Petitioner 
* Check “use existing address” checkbox 
* Select petitioner 1’s address 
Expected results 
On click of “Use Existing Address” checkbox:
- [x] Dropdown displays 
- [x] Dropdown options include all current petitioner address (mailing address line 1) 
On select of petitioner 1 address: 
- [x] Mailing address line 1, address line 2, address line 3, city, state, zip are populated with petitioner 1 information 
- [x] Mailing address line 1, address line 2, address line 3, city, state, zip are editable 

#### 5) Docket clerk adds petitioner and updates case caption 
* Login as docket clerk 
* Go to case
    * Case status = General Docket Not At Issue 
    * Case has externally filed document in Document QC Inbox 
* Click Case Information > Petitioner 
* Complete Add Petitioner form 
    * Update case caption field
* Click Save 
* Go to Document QC inbox 
Expected results 
- [x] App routes to Petitioner tab with success message displayed: “Petitioner [name field] added to case.”
- [x] New petitioner contact information is displayed in Petitioner card 
- [x] New petitioner displays option to “Edit” 
- [x] New petitioner displays option to “Seal address” 
- [x] Case caption is updated with new petitioner information in case header 
- [x] Case title is updated with new petitioner information in Document QC Inbox table (spot check other tables with case title) 

#### 6) Docket clerk adds petitioner and sees new petitioner when serving court-issued document - MOVED TO 8131
* Login as docket clerk 
* Go to case
* Add new petitioner 
* Save 
* Upload PDF 
* Add Docket Entry for draft PDF 
Expected results 
- [ ] New petitioner displays in the Service Parties list on the Add Docket Entry form

#### 7) Docket clerk adds petitioner and sees new petitioner when serving paper-filed document - MOVED TO 8131
* Login as docket clerk 
* Go to case
* Add new petitioner 
* Save 
* Add Paper Filing 
Expected results 
- [ ] New petitioner displays in the “Who is filing this document” field 

#### 8) Docket clerk adds petitioner, and new petitioner displays in filing party options when e-filing a document - MOVED TO 8131
* Login as docket clerk 
* Go to case
    * Case has petitioner 1 with eAccess
* Add new petitioner 
* Save 
* Login as petitioner 1 
* Go to case 
* File a document 
Expected results 
- [ ] New petitioner displays in the “Who is filing this document” field 


## Additional tests to verify new petitioner is treated the same as current petitioner 

#### 9) Docket clerk edits new petitioner address/phone number 
* Go to case - not “New” status
* Add new petitioner 
* Save 
* Click Edit link for added petitioner 
* Update address / phone number 
* Save 
Expected results 
- [x] Notice of Change of Address and Telephone number for [petitioner name] is added to Docket Record as complete served entry
- [x] Notice of Change of Address and Telephone number entry is hyperlinked 
- [x] updated address/telephone number displays
- [x] Notice of Change of Address and Telephone Number for case (step 1) appears in Document QC Inbox 

#### 10) Docket clerk seals address for new petitioner
* Go to case - not “New” status
* Add new petitioner 
* Save 
* Click Seal Address link for new petitioner 
* Click Yes, Seal Address 
* Click Printable Docket Record 
Expected results 
- [x] new petitioner contact displays lock icon
- [x] new petitioner contact address displays in red
- [x] no change to other petitioner’s address
- [x] Printable PDF displays "Address Sealed" for new petitioner contact and address is hidden

#### 11) Docket clerk adds petitioner counsel for new petitioner - MOVED TO 8131
* Go to case - not “New” status
* Add new petitioner 
    * Service = paper 
* Save 
* Search for private practitioner in Petitioner Counsel card 
    * Private practitioner is active in database
* Select new petitioner 
* Save 
Expected results 
- [ ] new petitioner displays in list for “Representing” in Add Counsel modal 
- [ ] On save, counsel displays in Petitioner Counsel card as representing new petitioner 
- [ ] New petitioner service changes to None

**Comment by JessicaMarine** [comment]
PO Feedback:
- c/o in Additional Name line shouldn't auto-populate
- Service preference needs to be required (not validating)
