### ISSUE TITLE
Flexion: Allow eAccess flag for Contacts

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7173]
As a project team, in order to know which petitioners need access to the new system, Flexion needs the ability to identify which petitioners have eAccess to the Court's current system.

Legacy petitioners who have eAccess in the Court's current system **and** have open cases will need to have an account in the new system before we go live.  Flexion needs to determine how they would like these legacy petitioners to be identified to them from the legacy database so that, when the time comes to create the new accounts, Flexion can easily identify those legacy Petitioners needing new accounts.

## Acceptance Criteria: ##
* For migrated Contacts, the CMS needs to allow an `eAccess` flag to be migrated as part of the Case Contacts
* **Iff** the e-mail address is provided, then the `eAccess` flag should be allowed
* The `eAccess` flag should be displayed on the UI on a per-Contact basis for Internal users only
* Ensure the migration documentation is updated

## Notes: ##
* Per Jessica: Only legacy petitioners with **open** cases and eAccess to the current system will need accounts in the new system
* Per Jessica: All case contacts could potentially have eAccess (both primary and secondary, other petitioners, other participants/intervenor, etc.)
* Validation: eAccess flag on _any_ Contact **iff** e-mail is provided
* **Engineering**: At a later date for when accounts are created, we'll be able to do a scan on cases for the `eAccess` flag

## Tasks ##
- [x] Add validation for eAccess flag for Contacts when an email is provided (Jojo ustaxcourt/ef-cms-flexion#5722)
- [x] Add flag icon to UI beside contact's email (other petitioner, participants/intervenors, contacts, etc.) (KRIS ustaxcourt/ef-cms-flexion#5724 )
- [x] Seed data (KRIS ustaxcourt/ef-cms-flexion#5729 )

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
