### ISSUE TITLE
Messaging Re-design clean up - Remove old messaging flow

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7174]
As a development team, in order to maintain a clean code base and ensure the changes we made to the messaging flow work, we need to remove all of the old messaging flow items that are not used for the new flow and run E2E tests on the new flow. 

## Pre-Conditions
* ustaxcourt/ef-cms-flexion#5841/Revamping the stip decision flow

## Acceptance Criteria
* Disable old messaging flow
* Test new messaging flow - E2E
* Remove "Messages" tab from Document QC pages, as well as any other UI remnants from the old flow
* Old document detail page is removed 
* Once we remove "Messages" from the global header, we need to rename "Case Messages" to "Messages" and make sure everything is renamed correctly on the back end. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1) Remove old Messages link in the page header and replace with Case Message (Mrin & Rae & Rachael ustaxcourt/ef-cms-flexion#6048)
- [x] 2) Remove old Messages views (Mrin & Rae & Rachael ustaxcourt/ef-cms-flexion#6048)
  - [x] Remove route
- [x] 3) Remove old Document Detail view (Rachael ustaxcourt/ef-cms-flexion#6040)
  - [x] Remove route (Rachael ustaxcourt/ef-cms-flexion#6040)
- [x] 4) Remove old Message entity (Rachael ustaxcourt/ef-cms-flexion#6042)
- [x] 5) Remove Messages from Work Items (Rachael ustaxcourt/ef-cms-flexion#6042)
- [x] 6) Remove Messages tab from Document QC pages (Rachael ustaxcourt/ef-cms-flexion#6043)
- [x] 7) Update all references of `Case Message` to `Message`(Mrinalini) ustaxcourt/ef-cms-flexion#6060
- [x] 8) Remove WorkItem `isQC` (Rachael ustaxcourt/ef-cms-flexion#6052)
- [x] 9) Remove `workQueueIsInternal` (Rachael ustaxcourt/ef-cms-flexion#6050)
- [x] 10) Convert Document.workItems to a single object instead of an array (Rachael ustaxcourt/ef-cms-flexion#6062)
- [x] 11) Remove createWorkItemInteractor (Rachael ustaxcourt/ef-cms-flexion#6044)
- [x] 12) Remove SignStipDecision.jsx and route, sequences (Rachael ustaxcourt/ef-cms-flexion#6045)
- [x] 13) Remove/clean up documentDetailHelper (Rachael ustaxcourt/ef-cms-flexion#6047)
- [x] 14) Remove/clean up DocumentDetailHeader (Rachael ustaxcourt/ef-cms-flexion#6047)
- [x] 15) Remove endpoints/persistence methods for old messaging (Rachael ustaxcourt/ef-cms-flexion#6056)
- [x] 16) Rename CaseMessage* views to Message* (Rachael ustaxcourt/ef-cms-flexion#6072)
- [x] 17) Rename `/case-message/*` routes to `/message/*` (Rachael ustaxcourt/ef-cms-flexion#6073)
- [x] 18) Remove code related to old messaging view - CreateMessageModalDialog, ForwardMessage entity (Rachael ustaxcourt/ef-cms-flexion#6074)
- [x] 19) Update actions, sequences, proxies, interactors, computeds, etc with *CaseMessage* in the name to *Message* (Rachael)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
Tests

- [x] Send message without a document attached (https://github.com/flexion/ef-cms/issues/4293) - Rachael
- [x] Send message with a document attached (https://github.com/flexion/ef-cms/issues/4607) - Rachael
- [x] Forward message (https://github.com/flexion/ef-cms/issues/4609) - Mrinalini
- [x] Reply to message (https://github.com/flexion/ef-cms/issues/4609) - Kristen
- [x] Complete message (https://github.com/flexion/ef-cms/issues/4609) - Kristen
- [x] Create Order from message (https://github.com/flexion/ef-cms/issues/4611)  - Kristen
- [x] Apply and Edit Signature to document attached to message (https://github.com/flexion/ef-cms/issues/4612) -  Kristen
- [x] Edit document attached to message (https://github.com/flexion/ef-cms/issues/4612)- Kristen
- [x] Add Docket Entry for document attached to message (https://github.com/flexion/ef-cms/issues/4612) - Kristen 
- [x] Serve document attached to message (https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/5811) - Kristen 
- [x] View message thread (https://github.com/flexion/ef-cms/issues/4609) - Kristen 
- [x] View completed message thread (https://github.com/flexion/ef-cms/issues/4609) - Kristen
- [x] Judge's view recent messages on their dashboard (https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/5810) - Kristen

**Comment by klohman** [comment]
Notes from Jessica (for testing). 

 (1) I don't think the Recent Messages on the Judge's dashboard is working as expected.  I thought it was supposed to show the 5 most recent messages. Check out Judge Buch's -- it's not showing the 5 most recent and they aren't in newest-to-oldest order.  (2) Also, in general, there is a lag in messages being added and removed from the Recent Messages on the Judge's dashboard.  In staging, a DocketClerk1 sent a Proposed Stipulated Decision to jasford.  That message wasn't displaying on the dashboard when I signed in as Judge Ashford.  I had to click around a bit before it showed up.  Then, when Judge Ashford replied to the message, it stayed on the Recent messages until I clicked around a bit again.  (3) Also, when a Docket Clerk completes a message, it's not clearing it from the Inbox until you click around a bit.  All of this messaging behavior has to work as expected.

**Comment by mrinsin** [comment]
(Kristen's findings)
- [x] On message screen, clicked Create Order, clicked Continue on modal - new tab opens but displays 404 error - Rachael
- [ ] When adding docket entry for uploaded PDF draft, the message attachment still displays the original description and not what the docket entry states (is this related to https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/5893) - Addressed in 5893
- [x] Message without any documents attached: if I attach a document when replying or forwarding -  the attachment should be selected by default and display in PDF preview - Mrinalini ustaxcourt/ef-cms-flexion#6102
- [x] On Judge’s Dashboard “Recent Messages” - not showing the five most recent. Messages - Rachael ustaxcourt/ef-cms-flexion#6098
    - See Judge Ashford’s Recent Messages 
- [x] Judge’s Dashboard Recent Message should sort from newest oldest - Rachael ustaxcourt/ef-cms-flexion#6098
- [x] Completed messages are still showing in Message Inbox - see Docket Clerk messages - Rachael ustaxcourt/ef-cms-flexion#6098
- [x] Completed messages still showing in Recent Messages (see Judge Ashford) - Rachael ustaxcourt/ef-cms-flexion#6098
- [x] unable to complete a message (case 103-20) test correspondence until i forwarded to another user (?) - should be fixed after migration runs

(Mrinalini's Findings)
- [x]  Bug - Clicking on the message link to a message with no attachments throws an error  - should be fixed after migration runs
- [x] Clicking on document from QC inbox, then clicking cancel should navigate back to document QC (currently navigating to Docket Record) - Rachael ustaxcourt/ef-cms-flexion#6100

- [x] ![image](https://user-images.githubusercontent.com/20514925/89314039-0a6d5b00-d62e-11ea-9800-cf23e0e603a6.png) - Rachael ustaxcourt/ef-cms-flexion#6100
