### ISSUE TITLE
Final Document Code Changes

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7178]
* Anything implemented from Remote Proceedings
   * PTE – Proposed Trial Exhibits
   * LEA – Limited Entry of Appearance -- needed on Request Case Access page for private practitioner and paper filings
   * NOC – Notice of Completion
   * SPOS – Standing Pretrial Order
   * M137 - Motion for Document Subpoena Hearing

From Rhonda McGraw:
* M072-Motion to Dismiss on Grounds of Mootness--Need to take the “s” off the end of "Ground".
* CS-Certificate of Service—Needs “of” in entry.  Needs to read “Certificate of Service *of* Motion for Continuance 04-07-2020.
* AMDC-Amended Certificate of Service—Date entered is not showing in docket entry.  Entry should read as “Amended Certificate of Service of Motion for Continuance 04-07-2020.
* PTFR-Redacted Petition Filed—Take “Filed” off.
* SORI-Statement of Redacted Information—CANNOT be eFiled; should be on paper-filing dropdown only

* NOTW - Notice of Withdrawal as Counsel

 

### Tasks
- [x]  Add to internal/external - PTE – Proposed Trial Exhibits
- [x]  LEA – Limited Entry of Appearance -- needed on Request Case Access page for private practitioner and paper filings - Rachael ustaxcourt/ef-cms-flexion#6716 
- [x] Automatically associate practitioner with case when LEA is filed - Rachael ustaxcourt/ef-cms-flexion#6716 
- [x]  Add to internal/external -NOC – Notice of Completion
- [x]  Add to internal~~/external~~ -SPOS – Standing Pretrial Order 
- [x]  Remove SPOS from external ^^^
- [x]  Add to internal/external -M137 - Motion for Document Subpoena Hearing
- [x] M072-Motion to Dismiss on Grounds of Mootness--Need to take the “s” off the end of "Ground".
- [x]  CS-Certificate of Service—Needs “of” in entry. Needs to read “Certificate of Service of Motion for Continuance 04-07-2020. - Rachael
- [x]  PTFR-Redacted Petition Filed—Take “Filed” off.
- [x] SORI-Statement of Redacted Information—CANNOT be eFiled; should be on paper-filing dropdown only **Remove from external** 
- [x]  Add internal/external -- NOTW -- Notice of Withdrawal as Counsel - Rachael

 ## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
@JessicaMarine 

We have M075 as Motion to Dismiss on Ground of Mootness; and M072 as Motion to Dismiss for Failure to State a Claim upon Which Relief Can Be Granted

Can you confirm?

**Comment by JessicaMarine** [comment]
@klohman That correct

**Comment by JessicaMarine** [comment]
PO Review 10/14/2020:
* When trying to eFile "Proposed Trial Exhibits" as petitioner1 in 101-20 in staging, it won't move beyond the document selector screen
* Same thing with "Notice of Completion"
* In 101-20 in staging, all of the docket entries are being created as duplicate text and no page numbers:![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/8d627f1b-d845-4ec8-acd7-7d02a77c436e)
