### ISSUE TITLE
Court: Documents that are not served - remove NOT SERVED indicator

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7179]
As a court, so that we have an accurate Docket Record, a Docket Clerks needs to be able to add specific documents to the Docket Record that are not served.

The Court has 13 documents that are not served.  Currently, when those items are added to the Docket Record, the "Not Served" indicator automatically displays and there is no way to remove it without a serving a document.  In order to have an accurate Docket Record, a Docket Clerks needs to be able to add these specific documents to the Docket Record **without** the "Not Served" note showing up.

## Acceptance Criteria: ##
* Documents (13) that are not served: 
CODE	DOCKET ENTRY LANGUAGE
HE	Hearing Exhibits for [Anything]
TE	Trial Exhibits for [Anything]
TRAN	Transcript of [Anything]
FTRL 	Further Trial before [Judge] at [Place]
CTRA	Corrected Transcript of [Date]
HEAR	Hearing before [Judge] at [Place]
PTRL	Partial Trial before [Judge] at [Place]
TRL	Trial before [Judge] at [Place]
RTRA 	Revised Transcript of [anything]

USCA	U.S.C.A. * Anything*
ES	Bounced Electronic Service of *Anything*
RM	Returned Mail of *Anything*
https://docs.google.com/spreadsheets/d/1wsG_6fKAerdTBaD3NW5jkFB0KY8KuOeyH7eTPJspvB4/edit?usp=sharing 

* When any of these documents are added to the Docket Record, the "Not Served" note should not display on the Docket Record or the document detail page
* Consider whether to remove the "Serve" option when any of these documents are involved

## Tasks ##
- [x] Add `isUnservable` boolean for corresponding event codes (above) to courtIssuedEventCodes JSON (Jojo ustaxcourt/ef-cms-flexion#5769)
  - Add constant `UNSERVABLE_EVENT_CODES` to entity constants
- [x] Hide `Save and Serve` button on Add Court Issued Docket Entry view (Jojo ustaxcourt/ef-cms-flexion#5769)
- [x] Hide `Not served` verbiage on docket record view (Jojo ustaxcourt/ef-cms-flexion#5769)
- [x] UX Feedback: Unserved documents should be automagically processed (show up in Processed QC tab) (Jojo ustaxcourt/ef-cms-flexion#5775)
- [x] CTRA Corrected Transcript of [Date] should be past or present date not future (Jojo ustaxcourt/ef-cms-flexion#5775)

## Notes
* Once this story is done, look into filed date not displaying on the docket record (re: legacy data)
   * Note from Mark: @esorenson  we have a question about a case (the json we’re sending is attached). There are two docket items in this case, 9 and 12 that according to Jessica are not the kind of documents that are are served (they both say “Not Served” in the right column). The question we have is: Why aren’t the filing dates showing up on these in the UI? We are passing filingDate fields for all the docket records. Do you know if there’s another field we need to pass with these? This isn’t blocking anything — just wanted to put in on your radar in case it’s an issue. (https://ustaxcourt.slack.com/files/U013V8SPSTD/F015JDDGGHG/case.json)

ROA	Record on Appeal *Anything*.   TO ADDRESS LATER
## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
