### ISSUE TITLE
Docket Clerk/Petitions Clerk: Drop down options for adding docket record entry for Court-issued docs

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7181]
As a Docket Clerk or Petitions/Calendar Clerk, in order to quickly identify the correct document when I'm creating a docket entry for a Court-issued doc, I need to be able to search by keyword or code.

## Acceptance Criteria
* Docket drop-downs should function similarly to magic selector for eFiled docs 
   * Code is not displayed in UI but will pull up document (DONE)
   * Confirm that this is working for both external (paper) and Court-created documents (DONE)
   * "Order to show cause" should be in the dropdown (DONE)
   * When creating the full docket entry display "Order to show cause <free text>" 
* Petitions clerk - should have same add docket entry dropdown as docket clerk for court issued documents - (done in ustaxcourt/ef-cms-flexion#5715)

## Tasks
- [x] 1 When creating the full docket entry display "Order to show cause <free text>"  (Rachael ustaxcourt/ef-cms-flexion#5786)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
