### ISSUE TITLE
Court: Disclosure Cases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7183]
As the Court, in order to capture all current case types, we need to add "Disclosure" to the available case types.

## Acceptance Criteria: ##
* Add the following notices to the IRS Notice=YES dropdown for eFiled petitions
   * Notice of Intention to Disclose
   * Notice - We Are Going To Make Your Determination Letter Available for Public Inspection
* Add `Disclosure` to the IRS Notice=NO dropdown for eFiled petitions
* Add `Disclosure` to the Case Type dropdown for paper petitions
* Add `Disclosure` to the available case types when modifying Case Info.
* Disclosure cases carry a "D" suffix on the docket number
* Update data migration documentation

## Tasks 
- Add the following notices to the IRS Notice=YES dropdown for eFiled petitions [6245](https://github.com/flexion/ef-cms/pull/6245)
   - [x] Notice of Intention to Disclose [6245](https://github.com/flexion/ef-cms/pull/6245)
   - [x] Notice - We Are Going To Make Your Determination Letter Available for Public Inspection [6245](https://github.com/flexion/ef-cms/pull/6245)
- [x] Add `Disclosure` to the IRS Notice=NO dropdown for eFiled petitions [6245](https://github.com/flexion/ef-cms/pull/6245)
- [x] Add `Disclosure` to the Case Type dropdown for paper petitions [6245](https://github.com/flexion/ef-cms/pull/6245)
- [x] Add `Disclosure` to the available case types when modifying Case Info. [6245](https://github.com/flexion/ef-cms/pull/6245)
- [x] Apply docketnumbersuffix "D" for Disclosure cases [6245](https://github.com/flexion/ef-cms/pull/6245)
- [x] Update docket number search matcher to include new suffix - Mrinalini & Kris ustaxcourt/ef-cms-flexion#6248
- [x] Update data migration documentation

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### 1)  Petitioner sees Notice of Intention to Disclose and Notice - We Are Going To Make Your Determination Letter Available for Public Inspection in the case type dropdown when they select "Yes" to IRS Notice 
* Login as petitioner 
* Upload STIN and continue 
* Select "Yes' to IRS Notice 
expected results 
- [x] Notice of Intention to Disclose displays as option for case type 
- [x] Notice - We Are Going To Make Your Determination Letter Available for Public Inspection displays as option for case type 

#### 2) Petitioner sees "Disclosure" in case type dropdown when they select "No" to IRS Notice 
* Login as petitioner 
* Upload STIN and continue 
* Select "Yes' to IRS Notice 
expected results 
- [x] Disclosure displays as option for case type 

#### 3) Petitions clerk sees Disclosure in case type dropdown on Create Case form
* Login as petitions clerk 
* Click Start a Petition 
* Go to IRS Notice tab 
* Select case type 
expected results 
- [x] Disclosure displays as option for case type 

#### 4) Petitions clerk sees Disclosure in case type dropdown on Petition QC form
* Login as petitions clerk 
* Click on a Petition from Inbox 
* Go to IRS Notice tab 
* Select case type 
expected results 
- [x] Disclosure displays as option for case type 

#### 5) Docket clerk sees Disclosure in case type dropdown on Edit Petition Details form
* Login as docket clerk 
* Navigate to Case Detail > Case Information> Overview 
* Click Edit on Petition Details 
* Select case type 
expected results 
- [x] Disclosure displays as option for case type 

#### 6) User sees docket number suffix "D" for disclosure cases 
* Login as petitioner 
* Create case with "Disclosure" case type 
* Submit Petition 
Expected results 
- [x] Docket number displays suffix "D"
