### ISSUE TITLE
Data Migration: Legacy Practitioners

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7186]
As the Court, in order to make sure our legacy practitioners get associated with the right cases, we need the data migration team to be able to transmit the bar nos. of the practitioners on each case as part of that case.

## Acceptance Criteria: ##
* Allow migration team to pass related Bar Nos. with cases (one or more -- array) as an optional field on case entity
* Update migration documentation, as appropriate
* Find a way to verify that the data has been migrated and saved successfully (pair with Mark)

## Notes: ##
* 7/7/2020: per Jessica -- because Mark (18F) doesn't have access to the legacy private practitioner data yet, we are not able to determine how to solve the Practitioner-to-other petitioner or Practitioner-to-Intervenor/Participant issue.  (Going to backlog that as an additional story). 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- **Engineering**: Users are not being created in Dynamo for this, but the practitioner entries will have a `userId` and other properties (see ustaxcourt/ef-cms#7173). User creation will be in the future.

## Tasks
- [x] On Case migration, associate Practitioners with existing users by searching via barNumbers (Jojo ustaxcourt/ef-cms-flexion#5756)
  - [x] For users not found via barNumber, generate a userId (Jojo ustaxcourt/ef-cms-flexion#5756)
  * Note: in the future, we can tell via dynamo table scan if a user account should need to be created
- [x] Add integration test (Jojo ustaxcourt/ef-cms-flexion#5756)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met
**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment
