### ISSUE TITLE
Development Team: Allow production domain configuration (Groom w/ 18F)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7190]
As the Court, so we have consistency across environment URLs and prevent possible issues associated with special cases (e.g. hard-coded URLs), we need to configure our environment URLs.

Why:
* Consistency across environment URLs
* Deploy are currently same because of URL structure. If we change only one environment, it introduce issues with hard-coded URLs not working

## Acceptance criteria
* The user interface in production is available at dawson.ustaxcourt.gov
* The production environment naming convention is not treated as a special case

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
As it currently stands, the production URL is UI-prod.dawson.ustaxcourt.gov. Desired URL is dawson.ustaxcourt.gov

```
UI:             ui-${ENV}.${EFCMS_DOMAIN}
API:            efcms-api-${ENV}.${EFCMS_DOMAIN}
PUBLIC API:     efcms-public-api-${ENV}.${EFCMS_DOMAIN}
WS:             efcms-websockets-${ENV}.${EFCMS_DOMAIN}

PROD UI:        dawson.ustaxcourt.gov

($ENV = prod)
EFCMS_DOMAIN:   dawson.ustaxcourt.gov
PUBLIC UI:      dawson.ustaxcourt.gov
UI:             app.dawson.ustaxcourt.gov
API:            api.dawson.ustaxcourt.gov
PUBLIC API:     public-api.dawson.ustaxcourt.gov
WS:             ws.dawson.ustaxcourt.gov

=== Lower Environments ===

($ENV = stg)
EFCMS_DOMAIN:   stg.efcms.ustaxcourt.gov 
UI:             app.stg.efcms.ustaxcourt.gov
PUBLIC UI:      stg.efcms.ustaxcourt.gov
API:            api.stg.efcms.ustaxcourt.gov
PUBLIC API:     public-api.stg.efcms.ustaxcourt.gov
WS:             ws.stg.efcms.ustaxcourt.gov
```

 The current solution we’re moving away from uses the ENV and EFCMS_DOMAIN as follows:

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/459c26f6-c1c6-422a-8bdf-c5cb45c4d7d0)

* The EFCMS application’s environments will be run in multiple AWS accounts, so the EFCMS_DOMAIN should be used as the unique key needed for things like S3 bucket names rather than the current combination of ENV + EFCMS_DOMAIN.
* We could use CircleCI Contexts (https://circleci.com/docs/2.0/contexts/) to switch environment variables as appropriate.
* The production URL (dawson.ustaxcourt.gov) will be available at the EFCMS_DOMAIN environment variable 

## Tasks
- [x] Rename URLs for specific environments (prod, stg, dev) for EFCMS_DOMAIN (Cody/Jojo ustaxcourt/ef-cms-flexion#6036)
  - $EFCMS_DOMAIN is computed based on the $ENV
  - e.g. `$EFCMS_DOMAIN = dev.efcms.ustaxcourt.gov` for lower environments & `$EFCMS_DOMAIN = dawson.ustaxcourt.gov`
- [x] Update terraform scripts with an updated domain variable (Cody/Jojo ustaxcourt/ef-cms-flexion#6036)
- [x] Deploy `dawson.flexion.us` (Cody/Jojo)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met (Andrew and Mike Marcotte gave Jessica thumbs us 8.6.2020)
**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by sutt0n** [comment]
Here are the steps @codyseibert and I procured for the deployment process:

- If the terraform state bucket changes (i.e ZONE_NAME !== previous EFCMS_DOMAIN)
  - create an s3 bucket called "${ZONE_NAME}.terraform.deploys"
  - copy the documents-$ENV.tfstate, permissions-$ENV.tfstate, and ui-$ENV.tfstate files from the previous deploys bucket into new bucket
- Setup circle ci environment variables
  - EFCMS_DOMAIN_DEV = dev.ef-cms.ustaxcourt.gov
  - EFCMS_DOMAIN_STG = stg.ef-cms.ustaxcourt.gov
  - EFCMS_DOMAIN_TEST = test.ef-cms.ustaxcourt.gov
  - EFCMS_DOMAIN_IRS = irs.ef-cms.ustaxcourt.gov
  - EFCMS_DOMAIN_MIG = mig.ef-cms.ustaxcourt.gov
  - EFCMS_DOMAIN_PROD = dawson.ustaxcourt.gov
  - ZONE_NAME_DEV = ef-cms.ustaxcourt.gov
  - ZONE_NAME_STG = ef-cms.ustaxcourt.gov
  - ZONE_NAME_TEST = ef-cms.ustaxcourt.gov
  - ZONE_NAME_IRS = ef-cms.ustaxcourt.gov
  - ZONE_NAME_MIG = ef-cms.ustaxcourt.gov
  - ZONE_NAME_PROD = dawson.ustaxcourt.gov
- Run the documents backup script `domain-s3-backup.sh` (this will back up all the documents from our s3 buckets)
- Empty the following buckets, where $ENV is the environment you are updating (dev, stg, exp1, irs...)
  - failover-ui-$ENV.ustc-case-mgmt.flexion.us
  - failover-ui-public-$ENV.ustc-case-mgmt.flexion.us
  - ui-public-$ENV.ustc-case-mgmt.flexion.us
  - ui-$ENV.ustc-case-mgmt.flexion.us
  - ustc-case-mgmt.flexion.us-documents-$ENV-us-east-1
  - ustc-case-mgmt.flexion.us-temp-documents-$ENV-us-east-1
  - ustc-case-mgmt.flexion.us-documents-$ENV-us-west-1
  - ustc-case-mgmt.flexion.us-temp-documents-$ENV-us-west-1
- Empty & delete the following s3 buckets
  - ustc-case-mgmt.flexion.us.efcms.$ENV.us-west-1.deploys
  - ustc-case-mgmt.flexion.us.efcms.$ENV.us-east-1.deploys
  - $ENV.ustc-case-mgmt.flexion.us.efcms.$ENV.us-east-1.lambdas
- Delete the following cloudfront distributions manually
  - ui-public-$ENV.ustc-case-mgmt.flexion.us
  - ui-$ENV.ustc-case-mgmt.flexion.us
- Delete efcms-$ENV-ws.ustc-case-mgmt.flexion.us custom domain in API Gateway
- Go into the gateway_api_$ENV and delete the /clamav resource
- **Note**: If the following error(s) occur during Web UI deployment, redeploy (we are working on an upcoming fix):
  - `error creating CloudFront Distribution: InvalidViewerCertificate: The specified SSL certificate doesn't exist, isn't in us-east-1 region, isn't valid, or doesn't include a valid certificate chain.`

**Comment by mmarcotte** [comment]
Just for posterity, final steps would be to:
* run `domain-s3-backup.sh` and then 
* empty and remove the two `bck-` S3 buckets.
