### ISSUE TITLE
Docket Clerk: Strike a Document

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7194]
As a Docket Clerk, in order to manage the docket record, I need the ability to strike an item from the record. 

## Acceptance Criteria
* Docket Clerk can "strike" [this is a term of art at the Court] an item from the docket record
* When the item has been stricken, it remains on the docket record with the date and notice of proceedings crossed out and (STRICKEN)" in parens is at the end
* Once an item is stricken, the document is still viewable to all Court personnel (hyperlink still active), but is not visable to parties or public (no hyperlink)
* User cannot unstrike a document

## Notes
* Similar to ustaxcourt/ef-cms#7171 from data migration

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Strike entry link and modal (Jojo ustaxcourt/ef-cms-flexion#6197)
- [x] Strike proxy, lambda, interactor, and persistence (Jojo ustaxcourt/ef-cms-flexion#6199)
- [x] Display success message after document is stricken (Jojo ustaxcourt/ef-cms-flexion#6199)
- [x] Show stricken info (user, date) on edit docket record meta view (Jojo ustaxcourt/ef-cms-flexion#6203)
- [x] Public-facing docket record should show stricken docket entries (Jojo ustaxcourt/ef-cms-flexion#6203)
- [x] Add `(STRICKEN)` to Document View (list and in document title) if a document is stricken (Jojo)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written (Jojo ustaxcourt/ef-cms-flexion#6210)
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Docket Record (no change)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/75e77f91-00c5-491e-9161-87f631101bdf)

**Edit** 
* Link displays only for  Docket Clerk  / Clerk of the Court 


 ## Edit Docket Entry 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8fa109fe-3799-4dc2-b444-d7ff8bd6e5f8)

* Add “Strike Entry” link to Actions tab 

**On click of “Strike Entry”**
* Display “Strike  Entry modal”

## Strike Entry modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5aeb0a5e-fefa-450f-8ec4-08215c83c51b)

**On click of Yes, Strike Entry**
* Modal closes 
* “Strike Entry” link is hidden on Edit Docket Entry screen 
* Edit Docket Entry screen displays message “ Striken by [username] on [date]”
* Docket entry is updated to display as Stricken
* Success message displays 


## Edit Docket Entry screen - Stricken
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4ca3a004-7d65-4006-89d3-a31f9d2e9ded)

* If document is stricken, displays message “ Striken by [username] on [date]”
* “Strike Entry” link is hidden on Edit Docket Entry screen 


## Stricken entries on Docket Record 

#### Internal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fa97f957-16f4-4bc8-9fa6-3561ae55faa6)

* Filed date and Filing and Proceedings are crossed out and hyperlink remains 

#### External and Public 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b392d14b-9375-425a-8d1f-d11281390610)

* Filed date and Filing and Proceedings are crossed out and no hyperlink

**Comment by klohman** [comment]
## 5676 Test Scenarios 
Test data 
- Create case(xx1-20) as petitioner1
    - e-File “Motion for New Trial” 

#### 1) Docket clerk sees “Strike Entry” link on Edit Docket Entry screen for entry that is not stricken
* Login as docket clerk
* Go to case xx1-20
* Click “Edit” on Motion for New Trial 
* Click the Actions tab 
Expected results 
- [x] “Strike Entry” link displays


#### 2) Docket clerk clicks Strike Entry link 
* Scenario 1 
* Click “Strike Entry” link
Expected results 
- [x] Strike entry modal displays 

#### 3) Docket clerk strikes entry 
* Login as docket clerk
* Go to case xx1-20
* Click “Edit” on Motion for New Trial 
* Click the Actions tab 
* Click Strike Entry 
* Click Yes, Strike 
Expected results 
- [x] Modal closes and page refreshes with success message displayed
- [x] “Strike Entry” link is hidden on Edit Docket Entry screen 
- [x] Message displays “Stricken by [username] on [date]
- [x] Docket entry is updated as Stricken 

#### 4) Internal users sees stricken entry on Docket Record with hyperlink
* Scenario 3 
* Go to Docket Record 
Expected results 
- [x] Motion for New Trial displays with strikethrough
- [x] Motion for New Trial is hyperlinked 

#### 5) External party sees stricken entry on Docket Record without hyperlink
* Scenario 3 
* Login as petitioner 1 
* Go to Docket Record 
Expected results 
- [x] Motion for New Trial displays with strikethrough
- [x] Motion for New Trial is not hyperlinked 

#### 5) Public user sees stricken entry on Docket Record without hyperlink
* Scenario 3 
* Go to public search
* Search for case xx1-20
* Go to Docket Record 
Expected results 
- [x] Motion for New Trial displays with strikethrough
- [x] Motion for New Trial is not hyperlinked
