### ISSUE TITLE
Update Message Boxes

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7197]
## Acceptance Criteria

- Remove docket number link from messages in My Messages/Section Messages Inbox, Sent, Completed
- Remove attachments column from messages in My Messages/Section Messages Inbox, Sent
- Remove docket number link from messages in Recent Messages on Judge's/CA dashboard
- Remove attachments column in Recent Messages on Judge's/CA dashboard
- Add case title to Recent Messages on Judge's/CA's dashboard
- Add "Section" column for the "from" to Recent Messages on Judge's/CA's dashboard
- Redesign Judge's/CA's dashboard
- fix navigating from QC boxes - Petitions QC > Served links are still going to old document detail screen (Kristen will define)
* The Document View seems to be listing the "Served" date, not the "Filed" date.  (1) Use the 
  Filed Date from the Docket record, not the Serveddate; and (2) add headers to the table on document view and draft view

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Remove docket number link from messages in My Messages/Section Messages Inbox, Sent, Completed - Mrin ustaxcourt/ef-cms-flexion#5951 
- [x] 2 Remove attachments column from messages in My Messages/Section Messages Inbox, Sent - Mrin ustaxcourt/ef-cms-flexion#5957
- [x] 3 Remove docket number link from messages in Recent Messages on Judge's/CA dashboard - Rachael ustaxcourt/ef-cms-flexion#5959
- [x] 4 Remove attachments column in Recent Messages on Judge's/CA dashboard - Rachael ustaxcourt/ef-cms-flexion#5959
- [x] 5 Add case title to Recent Messages on Judge's/CA's dashboard - Rachael ustaxcourt/ef-cms-flexion#5959
- [x] 6 Add "Section" column for the "from" to Recent Messages on Judge's/CA's dashboard - Rachael ustaxcourt/ef-cms-flexion#5959
- [x] 7 Redesign Judge's/CA's dashboard - Rachael ustaxcourt/ef-cms-flexion#5952 
  - [x] 7a Use case messages for Recent Messages on Judge's/CA's dashboard - Rachael ustaxcourt/ef-cms-flexion#5959
- [x] 8 fix navigating from QC boxes - Petitions QC > Served links are still going to old document detail screen (Kristen will define) - Mrin ustaxcourt/ef-cms-flexion#5964
- [x] 9 The Document View seems to be listing the "Served" date, not the "Filed" date. (1) Use the Filed Date from the Docket record, not the Serveddate; and (2) add headers to the table on document view and draft view (Matt ustaxcourt/ef-cms-flexion#5961)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the stage environment

**Comment by klohman** [comment]
### My Messages > Inbox 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/692e88d8-4aa3-46a8-9347-e78748a23dd1)

* Remove docket number link 
* Remove Attachments column 

### My Messages > Sent 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3e95e155-7863-4c7e-9f7f-cfc8cb306d13)

* Remove docket number link 
* Remove Attachments column 

### My Messages > Completed 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d6623007-1bff-4f49-b7cd-d11ef898e048)

* Remove docket number link 
* Remove Attachments column 

### Section Messages > Inbox 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/141e171e-9326-41d5-acdc-8ba4dd5e813a)
* Remove docket number link 
* Remove Attachments column 

### Section Messages > Sent 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/efb370d5-e5f8-4cb0-bfe3-1f0fa4ea08e9)

* Remove docket number link 
* Remove Attachments column 

### Section Messages > Completed
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/38623e6f-2988-419c-8deb-2e752bd5ada3)
* Remove docket number link 
* Remove Attachments column 

## Judges/ Chambers Dashboard 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5c1c38e3-b33f-4501-8118-13f48fb03d07)
* update Trial Sessions (upcoming and recent) to two-panel design 
* no change to functionality 

**Recent Messages**
* displays last five case messages in Judge's inbox 
* Add Case Title to table 
* Add sender's Section to table 

## Case Detail Case Messages 
* Remove attachments column 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b94369e1-5995-460a-9731-af491be3112f)

**Comment by klohman** [comment]
## Link Navigation from QC boxes 

#### Docket Document QC (Individual and Section) 

**Inbox**
* On click of Document link , navigate to Document QC screen 

**In Progress**
* For court-issued document, on click of Document link , navigates to Edit Docket Entry screen (edit-court-issued)
* For paper filed documents,  on click of Document link, navigates to Add Docket Entry screen 

**Completed**
* On click of Document link, navigate to Document View with selected document displayed 

#### Document QC Inbox (for all other internal users besides Docket and Petitions) 
* on click of Document link, navigate to Document View with selected document displayed 

#### Petition Document QC (Individual and Section) 

**Inbox**
* On click of Document link, navigate to Petition QC screen 

**In Progress**
* On click of Document link, navigate to Review and Serve Petition screen 

**Completed**
* On click of Document link, navigate to Document View with selected document displayed 


### Document View 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5a54982d-702c-4262-95dc-f10bc89fb8eb)

* add header to document list 

**No**
* Index number from docket entry 

**Filed**
* filedBy date 
*. is blank for unserved court-issued documents

**Filings and proceedings**
* displays document title  

### Drafts 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bacdb678-cbe0-46b9-98b0-0d9de48458d8)

* Add header to draft. document list 

**Created**
* displays createdAt 

**Document**
* displays document title / description

**Comment by klohman** [comment]
### 5810 Test Scenarios 

#### 1) Internal user views My Message Inbox / Sent / Completed 
* Login as internal user 
* Navigate to My Message Inbox 
* Click Sent tab 
* Click Completed tab 
Expected results 
- [x] Inbox / Sent / Completed display updated design 
- [x] Docket number is. not hyperlinked 
- [x] Attachments column is removed 

#### 2) Internal user views Section Messages inbox / Sent / Completed 
* Login as internal user 
* Navigate to Section Message Inbox 
* Click Sent tab 
* Click Completed tab 
Expected results 
- [x] Inbox / Sent / Completed display updated design 
- [x] Docket number is. not hyperlinked 
- [x] Attachments column is removed 

#### 3) Judge / chambers views updated dashboard design 
* Login as Judge Ashford 
* View dashboard 
Expected results 
- [ ]. Dashboard displays updated design 
- [x] 5 most recent messages display in table 
- [x] 5 upcoming trial sessions display in Upcoming Trial Sessions 
- [x] 5 past trial sessions display in Recent Trial Sessions 

#### 4) Petitions clerk clicks on Petition from Inbox 
* Login as petitioner 
* E-file Petition 
* Login as petitions clerk 
* Navigate to Inbox 
* Click on Petition link
Expected results 
- [x] App navigates to Petition QC screen 

#### 5) Petitions clerk clicks on Petition from In Progress box  
* Scenario 4 
* Click Review Petition 
* Click Save for Later 
* Navigate to Document QC > In Progress 
* Click Petition link 
Expected results 
 - [x] App navigates to Review and Serve Petition screen 

#### 6) Petitions clerk clicks on Petition from Served box 
* Scenario 5
* Click Serve to IRS 
* Click Yes, Serve
* Navigate to Document QC > Served 
* Click Petition link
Expected results 
- [x] App navigates to Document View with Petition selected

#### 7) Docket clerk clicks document link from Inbox 
* Login as petitioner 
* Navigate to case xx1-20
* File a Administrative Record 
* Login as docket clerk 
* Navigate to Document QC > Inbox 
* Click on Administrative Record 
Expected results 
 - [ ] App navigates to Document QC screen 

#### 8) Docket clerk clicks court-issued document link from In Progress box 
* Login as docket clerk 
* Navigate to case xx1-20
* Create Order, sign and save 
* Add Docket Entry 
* Save Entry 
* Navigate to Document QC > In Progress 
* Click on Order 
Expected results 
- [x] App navigates to Edit Docket entry screen for Order 

#### 9) Docket clerk clicks paper-filed document link from In Progress box 
* Login as docket clerk 
* Navigate to case xx1-20
* Add Docket Entry 
* Select “Motion for New Trial” 
* Complete Form 
* Save Entry 
* Navigate to Document QC > In Progress 
* Click on Motion for New Trial 
Expected results 
- [x] App navigates to Add Docket entry screen for Motion for New Trial 

#### 10) Docket clerk clicks document link from Completed box 
* Scenario 9
* Click Save and Serve 
* Clock Yes, Serve
* Navigate to Document QC > Completed 
* Click Motion for New Trial
Expected results 
 - [x] App navigates to Document View with Motion for New Trial selected 

#### 11) Internal user views updated Document View design 
* Login as docket clerk 
* Navigate to case xx1-20 
* Click Document View 
Expected results 
- [x] Document list displays header 
- [x] Filed date displays 
- [x] Document tile display in Filings and Proceedings 

#### 12) Internal user views updated Draft view design  
* Login as docket clerk 
* Navigate to case xx1-20 
* Click Drafts 
Expected results 
- [x] Draft list displays header 
- [x] Created date displays 
- [x] Document tile displays in Document column

**Comment by klohman** [comment]
**5810 feedback** 
* Docket Document QC - some document links are going to the “Add Docket Entry” screen instead of the QC screen 
    * Happened (at least) on Motion for Leave to File and Proposed Stipulated Decision 
    * On dev 
        *  Inbox - 731-20 - Motion for Leave to File Administrative Record- goes to Add Docket Entry screen 
        *  Inbox - 731-20 - Administrative Record  - goes to correct screen
        *  Inbox - 731-20 - Proposed Stipulated Decision - goes to Add Docket Entry screen 

![Screen Shot 2020-07-23 at 9.21.43 AM.png]
(https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b8e9dfb0-2d54-4a34-b6b8-e090cf065322)

![Screen Shot 2020-07-23 at 9.31.23 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/abdb2fd8-2c74-4df8-8488-aa0985184e55)


![Screen Shot 2020-07-23 at 9.22.06 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/838dfce3-873e-4698-aa6e-213ff013f810)
