### ISSUE TITLE
Serve a court-issued and paper-filed document that was added to the Docket Record

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7198]
## Acceptance Criteria

- Docket clerk / petitions clerk / Clerk of Court can serve a court-issued and paper-filed document that was saved to the Docket Record (and not served) - from Message and Document View 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Should we also provide the ability to serve a paper document that was saved on docket record in the Document view? 
* Once a paper document is uploaded to the system and saved, it should be treated exactly as a court-issued document from that point on. 

## Tasks
- [x] 1 Message Detail/Document View - add “Not served” in attachment section - Rachael, Mrinalini, Rae ustaxcourt/ef-cms-flexion#5894
- [x] 2 Hide createdAtFormatted on the docket record and also on document detail view for court issued documents that have not been served. (Paper filed documents that have not been served **should** display their createdAt date) - Rachael ustaxcourt/ef-cms-flexion#5902 
- [x] 3 Message Detail - serve court-issued documents - Rachael, Mrin ustaxcourt/ef-cms-flexion#5904 
- [x] 4 Document View - serve court-issued documents - Rachael & Mrin ustaxcourt/ef-cms-flexion#5908
- [x] 5 Message Detail - serve paper filed documents (not court-issued) - Mrin & Rachael ustaxcourt/ef-cms-flexion#5910
- [x] 6 Document View - serve paper filed documents (not court-issued) - Mrin & Rachael ustaxcourt/ef-cms-flexion#5894 
- [x] 7 Message Detail - serve Petition - Matt (#5909)
- [x] 8 Document View - serve Petition - Matt ustaxcourt/ef-cms-flexion#5894

## Refactoring
- [x] Fix attachment titles that are too long (Kris)
![image](https://user-images.githubusercontent.com/20514925/87700287-f5965980-c74a-11ea-9d70-1acbd8b2287c.png)
~- [ ]  Refactor `DocumentViewer.jsx` and `DraftDocumentViewer.jsx` to reuse code.~ - Rachael and Matt investigated, and these views are different enough that we'd be adding more logic than the lines of code we'd save
- [x] Add `courtIssuedDocumentTypes` to `getConstants` and replace 4 occurrences of `courtIssuedDocumentTypes.map` being called - Rachael ustaxcourt/ef-cms-flexion#5918
~- [ ] DRY up service code (servePaperFiledDocumentInteractor) - Rachael~ - moved to Trello
- [x] Refactor use of "alternateBackLocation" in favor of "redirectUrl" (noticeGenerationCompleteSequence) - Matt

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Message Detail Update

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e43e6ec-6eea-480d-b4ba-315421f43b2d)

#### Attachment List- Documents saved but not served
* Display Document title (current functionality) 
* Display "Not served" message next to document title 
* Applies to both court-issued documents (courtIssuedEventCodes) and paper filed documents (internalFilingEvents)
* Not applicable to  documents with isUnservable 

#### PDF Viewer Actions- Documents saved but not served
** View Full PDF**
* no change to functionality 

**Serve**
* link is only visible to Docket Clerk, Petitions Clerk, and Clerk of Court 
* on click, display "Are you sure you want to initiate service?” modal 
   - On service, modal closes, and success message displays on Message Detail screen
   - Document no longer displays "Not Served" message in attachment list 
   - "Serve" link no longer displays in PDF Viewer Actions 
   - Docket entry on Docket Record displays served date and parties  (current functionality)
   - Cover sheet is applied to document with Served stamp  (current functionality)
   - Parties with electronic service receive service email  (current functionality)
   - If there is a paper service party on the case, app navigates to “Print Service document” screen before returning to Message Detail 


#### Petition (specific) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/477ba9a0-34f2-4d70-957e-22645b7b4c78)
**Review and Serve Petition**
* display for Petitions Clerks only 
* On click, navigate to Petition QC
      - On Serve > navigate back to Message Detail screen with success message displayed “Petition served to IRS.”
   - Document no longer displays "Not Served" message in attachment list 
   - "Serve" link no longer displays in PDF Viewer Actions 


### Document View Update

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1263cf9-3184-45bc-b2ef-35e7fd4c04db)
#### Document View List- Documents saved but not served
* Add 4th column to document view list  
* Display Filed Date and Document title (current functionality) 
* Display "Not served" message next to document title for documents saved but not served 
* Applies to both court-issued documents (courtIssuedEventCodes) and paper filed documents (internalFilingEvents)
* Not applicable to  documents with isUnservable 

#### PDF Viewer Actions- Documents saved but not served
** View Full PDF**
* no change to functionality 

**Serve**
* link is only visible to Docket Clerk, Petitions Clerk, and Clerk of Court 
* on click, display "Are you sure you want to initiate service?” modal 
   - On service, modal closes, and success message displays on Document View screen 
   - Document no longer displays "Not Served" message in document view list 
   - "Serve" link no longer displays in PDF Viewer Actions 
   - Docket entry on Docket Record displays served date and parties  (current functionality)
   - Cover sheet is applied to document with Served stamp  (current functionality)
   - Parties with electronic service recieve service email  (current functionality)
   - If there is a paper service party on the case, app navigates to “Print Service document” screen before returning to Document View 


#### Petition (specific) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5b2d4413-b0b5-4b09-a30a-74792a12f8ab)
**Review and Serve Petition**
* display for Petitions Clerks only 
* On click, navigate to Pettiion QC 
* On serve to irs, navigate to Document View with success message displayed “Petition served to IRS.”
   - Document no longer displays "Not Served" message in attachment list 
   - "Serve" link no longer displays in PDF Viewer Actions

**Comment by klohman** [comment]
## 5811 Test Scenarios 

**Test Data**
* Case xx1-20 
    * Create “Order to Show Cause”, sign, add docket entry, and save entry (do not serve) 
    * Add Docket Entry for paper filed document “Administrative Record” but do not serve 
* Case xx2-20 
    * E-file petition but do not serve 
* Case xx3-20 
    * Create “Notice”, sign, add docket entry, and save entry (do not serve) 
    * Add Docket Entry for paper filed document “Answer” but do not serve 


#### 1) Internal user views unserved document on Message Detail 
* Login as docket clerk 
* Navigate to case xx1-20
* Create Message 
* Attach “Order to Show Cause” to message
* Attach “Administrative Record” to message 
* Send to ADC1 
* Login as ADC 
* View message detail 
Expected results 
- [ ] Order to Show Cause displays in Attachments with “Not Served” message 
- [ ] Administrative Record displays in Attachments with “Not Served” message 
- [ ] “Serve” link is hidden on PDF Viewer for Order to Show Cause
- [ ] “Serve” link is hidden on PDF Viewer for Administrative Record

#### 2) Docket clerk serves court-issued document from Message Detail 
* Scenario 1 
* Login as docket clerk 
* Navigate to Sent Messages 
* Click on message to ADC 
* Select Order to Show Cause from attachments 
* Click Serve 
* Click Yes, Serve on modal
Expected results 
On Click of Serve from Message Detail 
- [ ] “Are you sure you want to initiate service” modal displays 
On click of Yes, Serve on modal 
- [ ] Modal closes and success message displays 
- [ ] “Not served” message is removed from Order to Show Cause in Attachments list
- [ ] Serve link is hidden on Order to Show Cause PDF Viewer Actions

#### 3) Docket clerk serves paper-filed document from Message Detail 
* Scenario 1 
* Login as docket clerk 
* Navigate to Sent Messages 
* Click on message to ADC 
* Select Administrative Record from attachments 
* Click Serve 
* Click Yes, Serve on modal
Expected results 
On Click of Serve from Message Detail 
- [ ] “Are you sure you want to initiate service” modal displays 
On click of Yes, Serve on modal 
- [ ] Modal closes and success message displays 
- [ ] “Not served” message is removed from Administrative Record in Attachments list
- [ ] Serve link is hidden on Administrative Record PDF Viewer Actions

#### 4) Petitions clerk serves petition (and associated documents) from Message Detail 
* Login as petitions clerk 2 
* Navigate to case xx2-20 
* Create message to Petitions Clerk 1 
* Attach Petition
* Send message
* Login as Petitions clerk 1
* Click message for case xx2-20 
* Click Review and Serve Petition 
* Click “Serve to IRS” on Review and Serve Petition screen
* Click “Yes, serve” from modal 
Expected results 
On click of “Review and Serve Petition” from Message Detail 
- [ ] App navigates to Petition QC screen 

On click of “Yes, serve”
- [ ] App navigates to Message Detail with success message displayed 
- [ ] “Review and Serve Petition” link is removed from PDF viewer Actions 
- [ ] Petition no longer displays “Not Served” message In Attachments list 

#### 5) Internal user views unserved document on Document View 
* Login as ADC 
* Navigate to case xx3-20 
* Click Document View tab 
Expected results 
- [ ] “Notice” displays “Not Served” in document view list 
- [ ] “Notice” does not display “Serve” link in PDF. Viewer Actions 
- [ ] “Answer” displays “Not Served” in document view list 
- [ ] “Answer” does not display “Serve” link in PDF. Viewer Actions 

#### 6) Docket clerk serves court-issued document from Document View
* Login as docket clerk 
* Navigate to case xx3-20 
* Click Document View tab 
* Select “Notice” from document view list 
* Click “Serve” on PDF View Action
* Click Yes, Serve
On click of Yes, Serve on modal 
- [ ] Modal closes and success message displays 
- [ ] “Not served” message is removed from Notice in Document View list
- [ ] Serve link is hidden on Notice PDF Viewer Actions

#### 7) Docket clerk serves paper-filed document from Document View 
* Login as docket clerk 
* Navigate to case xx3-20 
* Click Document View tab 
* Select “Answer” from document view list 
* Click “Serve” on PDF View Action
* Click Yes, Serve
On click of Yes, Serve on modal 
- [ ] Modal closes and success message displays 
- [ ] “Not served” message is removed from Answer in Document View list
- [ ] Serve link is hidden on Answer PDF Viewer Actions

#### 8) Petitions clerk serves petition (and associated documents) from Document View
* Login as petitions clerk 
* Navigate to Document QC 
* Click “Start a Petition” 
* Complete form 
* Click Create Case 
* Navigate to Case Detail > Docket Record 
* Click on Document View 
* Select Petition 
* Click Review and Serve Petition 
* Click Serve to IRS
* Click Yes, Serve 
Expected results 
On click of Review and Serve Petition on Document View
- [ ] App navigates to Petition QC screen

On click of “Yes, serve”
- [ ] App navigates to Case Detail > Document View  with success message displayed 
- [ ] “Review and Serve Petition” link is removed from PDF viewer Actions 
- [ ] Petition no longer displays “Not Served” message In Attachments list

**Comment by JessicaMarine** [comment]
PO Review 7/21/2020:
Feedback on ustaxcourt/ef-cms#7198/4295 (since they seem to overlap):

(1) the "Order Order" has returned when adding a system-generated Order to the docket record:![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a24e9a34-3750-4869-b388-713adc7ef488)

(2) on the document view, should there be some padding between the document title and "Not Served":![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/5d118d97-0156-4550-b603-dccaf42f922a)
