### ISSUE TITLE
Applying and editing signatures on uploaded PDF drafts

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7199]
## Acceptance Criteria

- Internal user can apply a signature to an uploaded pdf draft (current functionality)
- Internal user can edit a signature on an uploaded pdf draft and apply a new signature to the original uploaded PDF
- Internal user can edit the uploaded pdf draft, which will remove any existing signatures to the original uploaded PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 New endpoint for removing signature - Rachael & Mrin & rae ustaxcourt/ef-cms-flexion#5937
  - [x] Unset `signedAt`
  - [x] Set `documentId` back to `documentIdBeforeSigning`  
- [x] 2 Change "Edit Signature" buttons to say "Remove Signature" - (Matt ustaxcourt/ef-cms-flexion#5942)
- [x] 3 Edit uploaded PDF after signature is applied (Matt ustaxcourt/ef-cms-flexion#5944)
  - [x] From Drafts view
  - [x] From Case Messages view

Refactoring
- [x] 1 draftState - look at cleaning up - Rae ustaxcourt/ef-cms-flexion#5943
- [x] 2 Clean up - use isDraft in helpers instead of looking through the docket record - Mrin & Rachael & rae & Matt ustaxcourt/ef-cms-flexion#5945

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
# There are no UI changes in this story, only an update/correction to the flow 

### Apply Signature to uploaded PDF draft
* no changes to current functionality 

### Edit Signature for uploaded PDFs (Updated flow) 

#### Edit Signature from Drafts 
On click of Edit Signature, "Are You Sure You Want to Edit this Signature?" modal displays; on click of Continue:
* Signature is removed 
* App navigates to Apply Signature screen 
* Uploaded PDF displays in PDF viewer (currently the PDF is being regenerated and overriding the original uploaded PDF) 
* User can skip or save signature 

**On Skip Signature**
* app routes back to Drafts screen with success message displayed 
* PDF preview displays uploaded PDF with NO signature 
* Apply Signature link is displayed 
* Edit Signature link is hidden 

**On Save Signature**
* navigate to Drafts screen with success message displayed 
* Uploaded PDF displays in PDF Preview with applied signature displayed 
* Apply Signature link is hidden
* Edit Signature link is displayed 

#### Edit Signature from Message Detail 
On click of Edit Signature, "Are You Sure You Want to Edit this Signature?" modal displays; on click of Continue:
* Signature is removed 
* App navigates to Apply Signature screen 
* Uploaded PDF displays in PDF viewer (currently the PDF is being regenerated and overriding the original uploaded PDF) 
* User can skip or save signature 

**On Skip Signature**
* app routes back to Message Detail screen with success message displayed 
* PDF preview displays uploaded PDF with NO signature 
* Apply Signature link is displayed 
* Edit Signature link is hidden 

**On Save Signature**
* navigate to Message Detail screen with success message displayed 
* Uploaded PDF displays in PDF Preview with applied signature displayed 
* Apply Signature link is hidden
* Edit Signature link is displayed 

### Edit Uploaded PDF after Signature is applied 

#### Edit Uploaded PDF with Signature from Draft 
on click of Edit 
* display warning modal (currently functionality) 

on click of Continue on warning modal 
* navigate to Edit Upload PDF -( /edit-upload-court-issued)
* Original PDF displays in PDF viewer without signature applied 

On Save
* app navigates back. to Drafts screen with success message displayed 
* Updated uploaded PDF displays in PDF viewer 

#### Edit Uploaded PDF with Signature from Message 
on click of Edit 
* display warning modal (currently functionality) 

on click of Continue on warning modal 
* navigate to Edit Upload PDF -( /edit-upload-court-issued)
* Original PDF displays in PDF viewer without signature applied 

On Save
* app navigates back. to Message Detail screen with success message displayed 
* Updated uploaded PDF displays in PDF viewer

**Comment by klohman** [comment]
## 5812 

Test data 
* case xx1-20
    * Click “Upload PDF” from Actions menu 
    * Enter description = Minutes Sheet 
    * Upload pdf 
    * Save 

#### 1) Internal user applies signature to draft uploaded PDF 
* Login as add 
* Navigate to case xx1-20
* Select Drafts tab 
* Select Minutes Sheet 
* Click “Apply Signature”
* Add signature 
* Click Save Signature 
Expected results 
On click of Apply Signature 
- [x] app navigates to Apply Signature screen 
On click of Save Signature 
- [x] app navigates to Drafts screen with success message displayed 
- [x] Minutes Sheet PDF displays with signature 
- [x] Apply Signature link is hidden 
- [x] Remove Signature link is displayed 

#### 2) Internal user removes signature on draft uploaded PDF from Drafts screen 
* Scenario 1 
* Login as Judge Buch
* Click Remove Signature 
* Click “Yes, Remove Signature” on confirmation modal 
Expected results 
On click of Remove Signature 
- [x] Warning modal displays 
On click of Yes, Remove
- [x] Minutes sheet does not display original signature (Chief Judge)
- [x] Apply Signature link is displayed 
- [x] Remove Signature link is hidden 

#### 3) Internal user applies signature and edits uploaded PDF from Draft screen
* Scenario 1 
* Select Minutes Sheet 
* Click “Edit” 
* Click “Yes, Continue” on confirmation modal 
* Click “Change” 
* Upload a different pdf 
* Click Save 
Expected results 
On click of Yes, Continue
- [x] App navigates to Edit Upload PDF screen (/edit-upload-court-issued)
- [x] PDF preview displays original uploaded PDF document 
On click of Save 
- [x] app navigates to Drafts screen with success message displayed 
- [x] Minutes Sheet PDF displays new uploaded PDF 
- [x] Minutes Sheet does not display signature 
- [x] Apply Signature link is displayed 

#### 4) Internal user applies signature and edits PDF description from Draft screen
* Scenario 1 
* Select Minutes Sheet 
* Click “Edit” 
* Click “Yes, Continue” on confirmation modal 
* Edit description to “Minutes Sheet from Trial”
* Click Save 
Expected results 
On click of Yes, Continue
- [x] App navigates to Edit Upload PDF screen (/edit-upload-court-issued)
- [x] Description displays “Minute Sheet” 
On click of Save 
- [x] app navigates to Drafts screen with success message displayed 
- [x] Minutes Sheet is renamed “Minutes Sheet from Trial” in draft list 
- [x] Minutes Sheet from Trial does not display signature 
- [x] Apply Signature link is displayed 

#### 5) Internal user edits signature on draft uploaded PDF from Message Detail 
* Scenario 1 
* Login as Judge Buch
* Send message with Minutes Sheet attached 
* Navigate to Message Detail 
* Click Remove Signature 
* Click “Yes, Remove” on confirmation modal 
* Click Apply Signature
* Apply new signature 
* Click Save Signature 
Expected results 
- [x] app navigates to Message Detail screen with success message displayed 
- [x] Minutes sheet does not display original signature (Chief Judge)
- [x] Minutes Sheet PDF displays with new signature (Judge Buch)
- [x] Apply Signature link is hidden 
- [x] Remove Signature link is displayed

#### 6) Internal user applies signature and edits uploaded PDF from Message Detail screen
* Scenario 1 
* Send message with Minutes Sheet attached
* Navigate to Message Detail 
* Select Minutes Sheet 
* Click “Edit” 
* Click “Yes, Continue” on confirmation modal 
* Click “Change” 
* Upload a different pdf 
* Click Save 
Expected results 
On click of Yes, Continue
- [x] App navigates to Edit Upload PDF screen (/edit-upload-court-issued)
- [x] PDF preview displays original uploaded PDF document 
On click of Save 
- [x] app navigates to Message Detail screen with success message displayed 
- [x] Minutes Sheet PDF displays new uploaded PDF 
- [x] Minutes Sheet does not display signature 
- [x] Apply Signature link is displayed

**Comment by klohman** [comment]
### Updated Design / Functionality (per conversation 7/20) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c0d4fe00-c441-4853-9dc1-ee8be5509247)

#### Drafts screen / Messages screen 
**Draft document with signature**
* applies to both court-issued documents created within the system and draft documents added using the Upload PDF feature
* Change link from Edit Signature to "Remove Signature" 
* On click of Remove Signature, display Remove Signature warning modal?

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f2ba7382-9fd7-4e76-957d-bd0cfe7dd02c)

**On click of Yes, Remove**
* Modal closes and page displays Success Message "Signature removed" 
* Signature is removed from PDF 
* "Apply Signature" link is displayed in PDF actions toolbar
* "Remove Signature link is hidden in PDF actions toolbar
