### ISSUE TITLE
Require a signature for Orders and Decisions being added to the docket record + no manual signature for notices

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7201]
As the Court, to ensure that an unsigned document requiring a signature doesn't get added to the docket record, we need add some logic to Orders and Decisions.

## Acceptance Criteria
- Court users are not able to add a signature to a Notice or Notice of Trial
- Docket clerk/petitions clerk/Clerk of Court cannot add docket entry for Orders and Decisions created in the system without a signature
- Docket clerk/petitions clerk/Clerk of Court cannot add docket entry for Orders and Decisions uploaded as PDF drafts without a signature

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Notice will never be uploaded as a PDF; they're all system-generated
 [Note: Notices should be automatically signed by the Clerk of the Court]

## Tasks
 - [x] 1 Remove signature validation for NOT and NTD event codes (Matt ustaxcourt/ef-cms-flexion#5929)
 - [x] 2 Drafts View (NOT and NTD)
   - [x] 2a Hide “Apply Signature” link on PDF Viewer Actions (Matt ustaxcourt/ef-cms-flexion#5929)
   - [x] 2b Display "Add Docket Entry" for Docket Clerk/Petitions Clerk/ Clerk of Court only (Matt ustaxcourt/ef-cms-flexion#5929)
   - [x] 2c Hide “Add Docket Entry” for other internal users (Matt ustaxcourt/ef-cms-flexion#5929)
 - [x] 3 Message Detail view (Matt ustaxcourt/ef-cms-flexion#5929)
   - [x] 3a Hide “Apply Signature” link on PDF Viewer Actions 
   - ~~[ ] 3b Display "Add Docket Entry" for Docket Clerk/Petitions Clerk/ Clerk of Court~~ This functionality is already implemented
   - ~~[ ] 3c Hide “Add Docket Entry” for other internal users~~ This functionality is already implemented
## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
#### Notices can be added to docket record without manual signature applied 
* remove signature validation on Add Court-issued Docket entry screen for:
    - Notice (NOT) 
    - Notice of Trial (NTD) 

#### Drafts screen Updates 
**draft Notices (Docket/Petitions/CoC)**
* Hide "Apply Signature" link on PDF Viewer Actions 
* Display "Add Docket Entry" for Docket Clerk/Petitions Clerk/ Clerk of Court only 
* Display Edit link (currently functionality)
* Display Delete link (currently functionality)
* Display View Full PDF link (currently functionality) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3014fb76-571b-4989-9bba-ec08846b9763)

**draft Notices (other internal users)**
* Hide "Apply Signature" link on PDF Viewer Actions 
* Hide "Add Docket Entry" 
* Display Edit link (currently functionality)
* Display Delete link (currently functionality)
* Display View Full PDF link (currently functionality) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d47c3afd-f900-44c8-b982-3f9572f9cb39)

#### Message Detail Updates 

**draft Notices (Docket/Petitions/CoC)**
* Hide "Apply Signature" link on PDF Viewer Actions 
* Display "Add Docket Entry" for Docket Clerk/Petitions Clerk/ Clerk of Court only 
* Display Edit link (currently functionality)
* Display View Full PDF link (currently functionality) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7cb210f7-7cf8-476c-a0e6-a76732763d9a)

*draft Notices (other internal users)**
* Hide "Apply Signature" link on PDF Viewer Actions 
* Hide "Add Docket Entry" 
* Display Edit link (currently functionality)
* Display View Full PDF link (currently functionality) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/182bd09d-8810-4597-b76e-ca8bb13bbfa9)

**Comment by klohman** [comment]
## 5814 Test Scenarios 

#### 1) Docket clerk cannot add docket entry for unsigned Order /Decision from Drafts screen
* Login as docket clerk 
* Navigate to case xx1-20 
* Create Order to Show Cause 
* Skip Signature 
* Navigate to Case Detail > Drafts 
* Click on Order to Show Cause 
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] “Signature is required for this document” message displays 
- [x] Apply Signature link displays 
- [x] Edit link displays 
- [x] Delete link displays 

#### 2) Docket clerk cannot add docket entry for unsigned Order/Decision from Message Detail 
* Login as docket clerk 
* Navigate to case xx1-20 
* Create Decision 
* Skip Signature 
* Create Message  
* Attach Decision 
* Send message to ADC
* Navigate to Message Detail
* Select Decision in attachment list 
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] “Signature is required for this document” message displays 
- [x] Apply Signature link displays 
- [x] Edit link displays 

#### 3) Internal user views unsigned Order / Decision in Draft view 
* Scenario 1 
* Login as ADC 
* Navigate to case xx1-20
* Click. Drafts tab 
* Select Order to Show Cause 
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] “Signature is required for this document” message displays 
- [x] Apply Signature link displays 
- [x] Edit link displays 
- [x] Delete link displays 

#### 4) Internal user views unsigned Order/Decision in Message Detail 
* Login as ADC
* Click on message from docket clerk for case xx1-20 (scenario 2)
* Select Decision in attachment list 
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] “Signature is required for this document” message displays 
- [x] Apply Signature link displays 
- [x] Edit link displays 

#### 5) Docket clerk views draft Notice from Drafts screen 
* Login as docket clerk 
* Navigate to case xx1-20
* Create Notice and Save 
* Navigate to Drafts 
* Select Notice 
Expected results 
- [x] Add Docket Entry link is visible on PDF Actions 
- [x] Apply Signature link is hidden  
- [x] Edit link displays 
- [x] Delete link displays 
- [x] Notice is displays in PDF viewer with Clerk of the Court signature automatically applied

#### 6) Docket clerk views draft Notice from message detail
* Scenario 5 
* Create message 
* Attach Notice 
* Send message to ADC 
* View sent message detail 
Expected results 
- [x] Add Docket Entry link is visible on PDF Actions 
- [x] Apply Signature link is hidden  
- [x] Edit link displays
- [x] Notice is displays in PDF viewer with Clerk of the Court signature automatically applied 

#### 7) Internal user views draft Notice to docket record from Drafts screen 
* Login as ADC
* Navigate to case xx1-20
* Navigate to Drafts 
* Select Notice 
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] Apply Signature link is hidden  
- [x] Edit link displays 
- [x] Delete link displays 
- [x] Notice is displays in PDF viewer with Clerk of the Court signature automatically applied

#### 6) Internal user views draft Notice to docket record from message detail
* Scenario 5 
* Login as ADC
* View sent message detail from docket on case xx1-20 (scenario5)
Expected results 
- [x] Add Docket Entry link is hidden on PDF Actions 
- [x] Apply Signature link is hidden  
- [x] Edit link displays 
- [x] Notice is displays in PDF viewer with Clerk of the Court signature automatically applied

#### 7) Docket clerk adds Notice to docket record from system-generated document 
* Scenario 5 
* Click Add Docket Entry 
* Complete form 
* Click Save and Serve 
Expected results 
- [x] App navigates to Docket Record with success message displays 
- [x] Served date and parties is populated on docket entry for Notice 
- [x] Served stamp is applied to Notice 
**If any parties have paper service, app navigates to Print Service Document screen and back to Docket Record on “Done”**
