### ISSUE TITLE
Update Correspondence File design

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7202]
As the Court, to have consistent UI across the application, we need to change the correspondence file design to match the document view design.

## Acceptance Criteria
- Internal user can add a Correspondence file to message as attachment
- Internal user views Correspondence Files in two panel display with PDF preview
- Internal user can toggle between Correspondence File PDFs on the same screen and View Full PDF for Correspondence File
- Docket Clerk and Petitions/Calendar Clerk can Add, Edit, and Delete Correspondence File

**NOTE: editing correspondence file description/title from message screen will be handled in ustaxcourt/ef-cms-flexion#5893 https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/5893

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update Correspondence view
  - [x] 1a Replace correspondence table with document viewer (Matt ustaxcourt/ef-cms-flexion#5876)
  - [x] 1b Action to set default correspondence document for viewer (Matt ustaxcourt/ef-cms-flexion#5876)
  - [x] 1c Action / sequence for selecting correspondence document for viewer (Matt ustaxcourt/ef-cms-flexion#5876)
  - [x] 1d Correspondence action bar (Matt ustaxcourt/ef-cms-flexion#5876)
- [x] 2 Create Messages Modal
  - [x] 2a Add Correspondence section to Add Document(s) dropdown (Matt ustaxcourt/ef-cms-flexion#5878)
  - [x] 2b Action / Sequence for fetch correspondence files for dropdown (Matt ustaxcourt/ef-cms-flexion#5878)
- [x] 3 Update Message Detail view
  - [x] 3a Update actions toolbar for Correspondence file types (Matt ustaxcourt/ef-cms-flexion#5880)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Updated Correspondence File screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bcf9e261-4bc3-49c6-88d5-e38e1cbdf9de)

* Update Correspondence tab with two panel design

**Correspondence File List**
* Left panel displays list of all Correspondence files (same design and functionality from Drafts view and Document View) 
* List is sorted oldest to newest by date 

**PDF Preview**
* Displays selected Correspondence file PDF 

**PDF Actions toolbar**
* View Full PDF - on click, open PDF in new tab 
* Edit - on click, navigate to Edit Correspondence File screen 
* Delete - on click, displays modal "Are You Sure You Want to Delete this document?"
![Screen Shot 2020-07-14 at 11.06.09 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3ced9de8-5775-4aac-b6e4-07da1078cd16)
* On delete, modal closes, success message is displayed and document is removed from Correspondence File list 

### Updates Message modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/68d6fcf3-c2ab-4d5d-8353-5f57de5f0915)

**Add Documents Dropdown**
* Add Correspondence files to add documents dropdown everywhere it appears 

### Message Detail - with Correspondence File attached 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/49114f1f-ea84-447d-8073-283c1d47d436)
If a Correspondence file is attached to a message 

**PDF Actions toolbar on Message screen**
* View Full PDF - on click, open PDF in new tab 
* Edit - on click, navigate to Edit Correspondence File screen

**Comment by klohman** [comment]
# 5815 Test Scenarios 

Test data
- Case xx1-20
    - Add Correspondence file = “Letter”
    - Add Correspondence file - “Receipt from Petitioner”


#### 1) Internal user views Correspondence file 
* Login as internal user 
* Navigate to case xx1-20
* Click Correspondence tab 
Expected results 
- [x] App displays two panel view of Correspondence tab 
- [x] List displays all documents added to Correspondence file 
    - Letter
    - Receipt from Petitioner 
- [x] PDF viewer displays preview of first file in list 
- [x] PDF Viewer Actions displays View Full PDF, Edit, and Delete links 

#### 2) Internal user views full PDF of correspondence file from Correspondence tab
* Scenario 1 
* Click “View Full PDF” link on “Letter” 
Expected results 
- [x] PDF of “Letter” opens in new tab 

#### 3) Internal user views full PDF of correspondence file from Message Detail 
* Login as internal user 
* Navigate to case xx1-20
* Click “Create New Message” from Actions menu 
* Send message with “Letter” attached 
* Navigate to message detail 
* Select “letter” from attachments list 
* Click “View Full PDF” link 
Expected results 
- [x] PDF of “Letter” opens in new tab 

#### 4) Internal user edits Correspondence file from Correspondence tab 
* Scenario 1
* Select “Receipt from Petitioner” 
* Click “Edit” 
* Change PDF
* Save 
Expected results 
On click of Edit:
- [x] App navigates to Edit Correspondence File screen 
On Click of Save from Edit screen:
- [x] App navigates to Correspondence tab with success message displayed 
- [x] Updated PDF displays in PDF viewer

#### 5) Internal user edits Correspondence file from Message Detail 
* Login as internal user 
* Navigate to case xx1-20
* Click “Create New Message” from Actions menu 
* Send message with “Letter” attached 
* Navigate to message detail 
* Click Edit 
* Change PDF 
* Save 
Expected results 
On click of Edit:
- [x] App navigates to Edit Correspondence File screen 
On Click of Save from Edit screen:
- [x] App navigates to Message detail with success message displayed 
- [x] Updated PDF displays in PDF viewer

#### 6) Internal user deletes Correspondence file from Correspondence tab 
* Login as internal user 
* Navigate to case xx1-20 
* Click on Correspondence tab 
* Select “Letter from Petitioner” 
* Click Delete
* Click “Yes, Delete” 
Expected results
On click of Delete: 
- [x] Delete confirmation modal displays 
On click of “Yes, Delete” from modal:
- [x] Modal closes, page refreshes and success message displays 
- [x] “Letter from Petitioner” is removed from the Correspondence list

#### 7) Internal user adds Correspondence file from Correspondence tab 
* Login as internal user 
* Navigate to case xx1-20 
* Click on Correspondence tab 
* Click “Add Correspondence File” link 
* Enter description:  “Notes from Trial”
* Upload PDF 
* Save 
Expected results 
On click of Add Correspondence File: 
- [x] App navigates to Add Correspondence File screen 
On Save: 
- [x] App navigates back to Correspondence tab with success message displayed 
- [x] “Notes from Trial” displays in Correspondence list 

#### 8) Internal user sends message with Correspondence file attached 
* Login as internal user 
* Navigate to case xx1-20 
* Click “Create New Message” from Actions menu 
* Select “Letter from Petitioner” as attachment 
* Complete form 
* Send 
* Navigate to Message Detail 
Expected results 
On Create New Message modal:
- [x] Correspondence documents display in “Add Document” dropdown 
On Message Detail 
- [x] “Letter from Petitioner” displays as attached to message 
- [x] PDF Actions toolbar displays for “Letter from Petitioner”
    - View Full PDF 
    - Edit

**Comment by JessicaMarine** [comment]
PO Feedback:
I just sent a message w/ correspondence file attached from Docket Clerk 2 to Judge Buch in 101-20 in Staging. it's showing up under "case messages" in 101-20, but not in the Sent box for DocketClerk2 or in Judge Buch's Inbox?

Will be backlogged as a bug.
