### ISSUE TITLE
Revisit flow: Proposed/Signed Stipulated Decision

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7205]
As the docket clerk, so that I may send the proposed stipulated decision to a sr attorney (or other court user), I need the the ability to forward the document from my QC inbox. 

Currently, system is prompting the docket clerk to add to the docket record when it was already added during upload. 

## Pre-Conditions
* IRS attorney can upload a proposed stipulated decision

## Acceptance Criteria
* Code for this already exists - reuse
* Docket clerk receives the proposed stipulated decision in the QC inbox, for both paper and electronically received (already done)
* Docket clerk QC the proposed stipulated decision
* Docket clerk can forward the proposed stipulated decision to a court user from the QC screen.
* Court user can sign the document
* When the document is signed, it creates a copy of the stip decision that is then treated as a second, separate document that does not have the cover page and is treated as a separate document
* The signed stipulated decision appears in the draft documents
* Court user can edit the signature while the signed stipulated decision is in draft form
* Court user can attach the document to an existing message or new message
* Docket clerk can add the signed stipulated decision to the docket record and serve (save and serve, save and serve later, etc...)
* When it's served, the "entered" stamp gets applied to the bottom of the first page and the case status automatically changes to closed. 
* Signed stipulated decision is viewable to internal users, parties and the public.

##Notes
* When judge signs, creates a copy of the document without the coversheet - this is what the signature gets applied to. It creates a draft document of the signed stipulated decision. New document is treated
* Can utilize event codes for functionality

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
~~Docket clerk can forward Stipulated Decision to a court user from QC inbox~~ (already implemented)
- [x] Display Sign Stipulated Decision link for internal users, when doc code is PSDE and SDEC event code does not exist on docket record or drafts (Rachael ustaxcourt/ef-cms-flexion#6030)
  - [x] Message Detail View (Rachael ustaxcourt/ef-cms-flexion#6030)
  - [x] Document View (Rachael ustaxcourt/ef-cms-flexion#6030)
- [x] Apply Signature Page for Proposed Stipulated Decision (Mrinalini & Rachael)
    ~~No coversheet~~
  - [x] No Skip Signature button (Mrin & Rae & Rachael ustaxcourt/ef-cms-flexion#6032)
- [x] Save Signature From Document View (Rachael, Mrin & Rae ustaxcourt/ef-cms-flexion#6033)
  - [x] On Save, create draft with event code SDEC
  - [x] Navigate to Drafts with success message displayed “Stipulated Decision signed and saved.”
  - [x] Stipulated Decision PDF is created with signature applied
  - [x] Stipulated Decision is displayed in Drafts list
  - [x] 'Remove Signature' option is hidden in toolbar
  - [x] 'Edit' option is hidden in toolbar
- [x] Save Signature From Message Detail View (Rachael)
  - [x] On Save, create draft with event code SDEC
  - [x] Navigate to Message Detail  with success message displayed “Stipulated Decision signed and saved.”
  - [x] document is attached to the message
  - [x] Stipulated Decision PDF is created with signature applied
  - [x] Stipulated Decision is displayed in Drafts list
  - [x] 'Remove Signature' option is hidden in toolbar
  - [x] 'Edit' option is hidden in toolbar
- [x] Add Docket Entry and Serve Stipulated Decision - from Drafts Screen (Mrinalini & Rae & Rachael) 
  - [x] Delete - display confirmation modal (text is specific to Stipulated Decision, different form current modal) (Mrinalini & Rae & Rachael) ustaxcourt/ef-cms-flexion#6038
   ~~On Served - Case Status updates to Closed~~
~~Do not prompt user to add docket entry for Stipulated Decision (docket entry already added on upload)~~

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Message Detail View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/97af4257-b1b7-4b94-8533-e90d5c522620)

**Sign Stipulated Decision link**
display if
* role = internal user 
* document code = PSDE
* SDEC event code does not exist on docket record or drafts  

### Document View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3f18e439-69e1-43d2-924b-4f07ea52dec1)

**Sign Stipulated Decision link**
display if :
* role = internal user 
* document code = PSDE
* SDEC event code does not exist on docket record or drafts 


### Apply Signature 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e65363f8-5365-4cba-b2d3-fdc93380fbdc)

****![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f60f1caf-94bb-402a-a74e-fa85e4d854f2)

#### Sign and Save Stipulated Decision (from Document View) 
On click of Sign Stipulated Decision from Document View
* navigate to Apply Signature screen 

**Back to Draft Documents**
* on click, navigate back to Drafts View 

**PDF Viewer**
* Displays PDF of Proposed Stipulated Decision without cover sheet

**Delete Signature**
* Is hidden unless signature is applied to PDF 

**Save Signature**
* Is hidden unless signature is applied to PDF 
* on click:
   * Navigate to Drafts with success message displayed “Stipulated Decision signed and saved.”
   * Stipulated Decision PDF is created with signature applied 
   * Stipulated Decision is displayed in Drafts list 



#### Sign and Save Stipulated Decision (from Message Detail) 
On click of Sign Stipulated Decision from Message Detail 
* navigate to Apply Signature screen 

**Back to Drafts Document**
* on click, navigate back to Drafts

**PDF Viewer**
* Displays PDF of Proposed Stipulated Decision without cover sheet

**Delete Signature**
* Is hidden unless signature is applied to PDF 

**Save Stipulated Decision**
* Is hidden unless signature is applied to PDF 
* on click:
   * Navigate to Message Detail with success message displayed “Stipulated Decision signed and saved.”
   * Stipulated Decision is attached to message and displays in Attachments list 
   * Stipulated Decision PDF is created with signature applied 
   * Stipulated Decision is displayed in Drafts list 

### Add Docket Entry and Serve Stipulated Decision-  from Drafts screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/904867c3-4486-45c0-8434-dd0d3662bbac)
**Delete**
* On click, display Delete confirmation modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5dd362fe-245a-49ab-90b3-a4068cc776e0)
* On Yes, Delete, document is removed from drafts list 

**Add Docket Entry**
* visible to docket clerk/petitions clerk/Clerk of Court 
* On Click, navigate to Add Court-Issued Docket Entry screen


#### Add Docket Entry and Save for Later 
* app navigates to Docket Record with success message displayed 
* Stipulated Decision no longer displays in Drafts 
* Stipulated Decision entry is displayed on Docket Record as “Not Served” 
* Stipulated Decision displays in Document QC > In Progress box 

#### Add Docket Entry and Serve 
* app navigates to Docket Record with success message displayed 
* Stipulated Decision no longer displays in Drafts 
* Stipulated Decision entry is displayed on Docket Record with Served date and Parties populated 
* “Entered” stamp is displayed on Stipulated Decision PDF 
* Stipulated Decision displays in Document QC > Processed box 

### Stipulated Decision-  from Message  Detail screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/70b648cc-fd64-452b-aedd-20616abee44a)
**Add Docket Entry**
* visible to docket clerk/petitions clerk/Clerk of Court 
* On Click, navigate to Add Court-Issued Docket Entry screen

#### Add Docket Entry and Save for Later 
* app navigates to Message Detail with success message displayed 
* Stipulated Decision no longer displays in Drafts 
* Stipulated Decision entry is displayed on Docket Record as “Not Served” 
* Stipulated Decision displays in Document QC > In Progress box 

#### Add Docket Entry and Serve 
* app navigates to Message Detail with success message displayed 
* Stipulated Decision no longer displays in Drafts 
* Stipulated Decision entry is displayed on Docket Record with Served date and Parties populated 
* “Entered” stamp is displayed on Stipulated Decision PDF 
* Stipulated Decision displays in Document QC > Processed box 
* Case status is automatically updated to Closed

**Comment by klohman** [comment]
### 5841 Proposed/Signed Stipulated Decision 

#### 1) External party files Proposed Stipulated Decision 
* Login as irsPractitioner
* Navigate to case xx1-20
* File “Proposed Stipulated Decision” 
Expected results 
- [x] Proposed Stipulated Decision displays on Docket Record 
- [x] Proposed Stipulated Decision includes system-generated cover sheet 
- [ ] Proposed Stipulated Decision is served on electronic parties 
- [x] Proposed Stipulated Decision entry is hyperlinked only for internal user and external parties to the case 
- [x] Proposed Stipulated Decision displays in Docket Document QC > Inbox 

#### 2) Docket clerk completes QC on e-filed Proposed Stipulated Decision 
* Login as docket clerk 
* Navigate to Document QC > Inbox 
* Click document link for Proposed Stipulated Decision 
* Click Complete 
Expected results 
- [x] App navigates to. Document QC > inbox
- [x] Proposed Stipulated Decision no longer displays in Document QC> Inbox 
- [x] Proposed Stipulated Decision displays in Document QC > Processed 

#### 3) Docket clerk completes QC and sends message with Proposed Stipulated Decision attached 
* Login as irsPractitioner 
* Navigate to case xx3-20
* File Proposed Stipulated Decision
* Login as docket clerk 
* Navigate to Document QC > Inbox 
* Click on Proposed Stipulated Decision for case xx3-30
* Click Complete and Send Message 
* Select recipient = adc1
* Enter message 
* Send 
Expected results 
- [x] App navigates to. Document QC > inbox
- [x] Proposed Stipulated Decision no longer displays in Document QC> Inbox 
- [x] Proposed Stipulated Decision displays in Document QC > Processed 
- [x] Proposed Stipulated Decision is attached to message
- [x] Message displays in Section/Individual Messages > Inbox for adc1
- [x] Message displays in Section/Individual Messages > Sent box for docket clerk 
- [x] Message displays in Case Detail > Case Messages 

#### 4) Docket clerk adds paper filed Proposed Stipulated Decision to Docket Record 
* Login as docket clerk. 
* Navigate to case xx2-20
* Click “Add Docket Entry” from Actions menu 
* Select Proposed Stipulated Decision as document type 
* Complete form
* Click Save and Serve 
Expected results
- [x] Proposed Stipulated Decision displays on Docket Record 
- [x] Proposed Stipulated Decision includes system-generated cover sheet 
- [ ] Proposed Stipulated Decision is served on electronic parties 
- [x] Proposed Stipulated Decision entry is hyperlinked only for internal user and external parties to the case 
- [x] Proposed Stipulated Decision displays in Docket Document QC > Processed 

#### 5) Internal user sends message with Proposed Stipulated Decision attached 
* Scenario 4. 
* Navigate to case xx2-20 
* Click “Create New Message” from actions dropdown 
* Attach document = Proposed Stipulated Decision
* Select recipient = adc1 
* Enter message 
* Send 
Expected results 
- [x] Create Message modal closes and success message displays
- [x] Proposed Stipulated Decision is attached to message
- [x] Message displays in Section/Individual Messages > Inbox for adc1
- [x] Message displays in Section/Individual Messages > Sent box for docket clerk 
- [x] Message displays in Case Detail > Case Messages

#### 6a) Internal user applies signature to copy of Proposed Stipulated decision from Document View 
* Scenario 3 
* Login as adc1
* Navigate to case xx3-20 
* Click on Document View
* Select Proposed Stipulated Decision
* Click “Sign Stipulated Decision” 
Expected results 
- [x] App navigates to Apply Signature screen 
- [x] PDF viewer displays original Proposed Stipulated Decision without cover sheet 
- [x] “Back to Draft Documents” link displays 
- [x] Signature block is attached to mouse 
- [x] Delete signature link is hidden until signature is added 
- [x] Save Signature button is hidden until signature is added 

#### 6b) Internal user applies signature to copy of Proposed Stipulated decision from Document View 
* Scenario 6a 
* Add signature 
Expected results 
- [x] PDF viewer displays signature block on original Proposed Stipulated Decision without cover sheet 
- [x] “Back to  Draft Documents” link displays 
- [x] Delete signature link is displayed 
- [x] Save Signature button is displayed 

#### 7) Internal user saves Stipulated Decision with signature applied from Document View 
* Scenario 6b 
* Click “Save Stipulated Decision” 
Expected results 
- [x] App navigates to Drafts screen with success message displayed “Stipulated Decision signed and saved. 
- [x] Stipulated Decision is saved as Draft on case and visible in Drafts screen
- [x] “View Full PDF” displays in PDF viewer toolbar 
- [x] “Delete” displays in PDF viewer toolbar 
- [x] “Add Docket Entry” is hidden in PDF viewer toolbar 

#### 8a) Internal user creates applies signature from Message Detail View 
* Scenario 4 
* Login as adc1
* Navigate to case xx2-20 
* Click on Case Messages 
* Select message for Proposed Stipulated Decision
* Click “Sign Stipulated Decision” 
Expected results 
- [x] App navigates to Apply Signature screen 
- [x] PDF viewer displays original Proposed Stipulated Decision without cover sheet 
- [x] “Back to Draft Documents” link displays 
- [x] Signature block is attached to mouse 
- [x] Delete signature link is hidden until signature is added 
- [x] Save Signature button is hidden until signature is added 

#### 8b) Internal user applies signature to copy of Proposed Stipulated decision from Message Detail View 
* Scenario 8a 
* Add signature 
Expected results 
- [x] PDF viewer displays signature block on original Proposed Stipulated Decision without cover sheet 
- [x] “Back to Draft Documents” link displays 
- [x] Delete signature link is displayed 
- [x] Save Signature button is displayed 

#### 9) Internal user saves Stipulated Decision with signature applied from Message Detail View 
* Scenario 8b 
* Click “Save Stipulated Decision” 
Expected results 
- [x] App navigates to Message Detail with success message displayed “Stipulated Decision signed and saved. 
- [x] Stipulated Decision is attached to message and displays in Attachments list
- [x] Stipulated Decision is saved as Draft on case and visible in Drafts screen
- [x] “View Full PDF” displays in PDF viewer toolbar 
- [x] “Add Docket Entry” is hidden in PDF viewer toolbar 

#### 10) Internal user attaches stipulated decision to message 
* Scenario 6b
* Navigate to case xx3-20
* Click “Create  New Message” from Actions menu 
* Select recipient = docket clerk 1
* Attach Stipulated Decision to message 
* Complete form 
* Send 
Expected results 
- [x] Create Message modal closes and success message displays
- [x] Stipulated Decision is attached to message
- [x] Message displays in Section/Individual Messages > Inbox for docket clerk 1
- [x] Message displays in Section/Individual Messages > Sent box for adc1
- [x] Message displays in Case Detail > Case Messages > In Progress

#### 11) Docket clerk adds docket entry for stipulated decision and saves for later
* Scenario 7 
* Login as docket clerk 1
* Navigate to case xx2-20
* Click on Drafts tab 
* Select Stipulated Decision 
* Click “Add Docket Entry” button 
* Complete form 
* Click Save for Later 
Expected results
- [x] App navigates to Docket Record screen with success message displayed 
- [x] Stipulated Decision is no longer displayed in Drafts table 
- [x] Stipulated Decision entry is displayed as pending (Not Served) on docket record 
- [x] Stipulated Decision is displayed in Document QC > In Progress (Individual and Section) 

#### 12) Docket clerk adds docket entry for stipulated decision and serves (electronic parties only)
* Scenario 9
* Login as docket clerk 
* Navigate to case xx3-20
* Click on Case Messages tab
* Click on message for Stipulated Decision 
* Click “Add Docket Entry” for Stipulated Decision 
* Complete form 
* Click Save and Serve 
Expected results 
- [x] App navigates to Message Detail with success message displayed 
- [x] Stipulated Decision is no longer displayed in Drafts table 
- [x] Stipulated Decision entry is displayed on docket record with served date and parties 
- [x] “Entered” stamp is applied to Stipulated Decision PDF 
- [ ] Service email is sent (for electronic parties) 
- [x] Stipulated Decision is displayed in Document QC > Processed (Individual and Section) 
- [x] Case status is automatically updated to Closed 

#### 13) Docket clerk adds docket entry for stipulated decision and serves (paper parties)
* Scenario 11
* Navigate to Document QC > In Progress
* Click on Stipulated Decision for case xx2-20
* Click “Add Docket Entry” for Stipulated Decision 
* Complete form 
* Click Save and Serve 
Expected results 
- [x] App navigates to Print Paper Service screen 
- [x] On click of “Done” from Paper Service screen, navigate to Docket Record with success message displayed
- [x] Stipulated Decision is no longer displayed in Drafts table 
- [x] Stipulated Decision entry is displayed on docket record with served date and parties 
- [x] “Entered” stamp is applied to Stipulated Decision PDF 
- [x] Stipulated Decision no longer displays in Document QC > In Progress (Individual and Section) 
- [x] Stipulated Decision is displayed in Document QC > Processed (Individual and Section) 
- [x] Case status is automatically updated to Closed 

#### 14a) Internal users/external users/public users view signed stipulated decision PDF from Docket Record 
* Login as party to case 
* Navigate to case xx2-20 
Expected results 
- [x] Proposed Stipulated Decision is on docket record and hyperlinked. 
- [x] Stipulated Decision is on docket record and hyperlinked 

#### 14b) Internal users/external users/public users view signed stipulated decision PDF from Docket Record 
* Login as external user (not associated with case)
* Navigate to case xx3-20 
Expected results 
- [x] Proposed Stipulated Decision is on docket record and not hyperlinked
- [x] Stipulated Decision is on docket record and hyperlinked 

#### 14c) Internal users/external users/public users view signed stipulated decision PDF from Docket Record 
* Go to public site 
* Navigate to case xx3-20 
Expected results 
- [x] Proposed Stipulated Decision is on docket record and not hyperlinked
- [x] Stipulated Decision is on docket record and hyperlinked 

#### 15) Internal user deletes Stipulated Decision draft 
* Scenario 1 
* Login as internal user 
* Navigate to case xx1-20 
* Click on Document View 
* Select Proposed Stipulated Decision
* Click Apply Signature
* Add signature 
* Click Save Signature 
* Select Stipulated Decision from Document View 
* Click Delete 
* Click Yes, Delete on modal 
Expected results 
On click of “Delete”: 
- [x] Delete confirmation modal for Stipulated Decision displays
On click of Yes, Delete, 
- [x] modal closes and success message displays 
- [x] Stipulated Decision is removed from Drafts 
- [ ] “Sign Stipulated Decision” link is displayed on Document View > Proposed Stipulated Decision 
- [ ] “Sign Stipulated Decision” link is displayed on Message Detail > Proposed Stipulated Decision

**Comment by klohman** [comment]
UX feedback 
* on sign and save of Stipulated Decision, when you return to the Drafts screen, the Stipulated Decision should be selected (currently nothing is selected or displayed in PDF Viewer)
 ![Screen Shot 2020-07-30 at 12.48.42 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d88252d7-bbd8-46c9-aea3-1e7e92231d18)


* When i signed and saved SDEC, then deleted the SDEC. draft, the "Sign Stipulated Decision" button is no longer there (On Doc View and Message Detail). If i delete the SDEC. draft,  I need the option to sign displayed again 
![Screen Shot 2020-07-30 at 1.13.17 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1d79b2ca-6b73-44be-a9e7-f019ba6b2aad)

**Comment by JessicaMarine** [comment]
PO Review:
(1) I thought we discussed the back button being something different on the Sign and Save Stipulated Decision page.  It doesn't make any sense to go back to Draft docs from there. 
(2) After signing and saving the Stipulated Decision, when the user is routed back to the message, I would expect the Stipulated Decision doc to be selected and showing in the PDF viewer, and not the Proposed Stipulated Decision.
