### ISSUE TITLE
Clean-Up: Document drop-down

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7206]
As the Court, in order to allow users to easily locate the proper document in the document drop-down, we need the filter to be refined to give priority to exact `eventCode` or `documentType` in all of our document drop-downs. 

## Acceptance Criteria: 
* If user enters a `eventCode` or `documentType` that has an **exact** match in any document drop-down list, that exact match should be the first in the list

## Notes
* possibly related to this https://trello.com/c/QWTNlMr7/676-sort-event-in-react-select

## Mobile Design/Considerations
* Needs to be addressed on mobile for external filings

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Move [Trello bug](https://trello.com/c/QWTNlMr7/676-sort-event-in-react-select) to Done (last)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
## 5842 Test Scenarios 

### Test Scenarios 

#### 1) User enters event code and sees exact match first in dropdown list for paper-filings 
* Login as docket clerk
* Go to a case 
* Click "Paper Filing" 
* Enter Document Type = “A”
Expected results 
- [x] “Answer” is sorted to top of list 
- [x] Partial matches display in alphabetical order 


#### 2) User enters document type and sees exact match first in dropdown list for paper-filings
* Login as docket clerk
* Go to a case 
* Click "Paper Filing" 
* Enter Document Type = “Motion for Leave to File”
Expected results 
- [x] “Motion for Leave to File” is sorted to top of list 
- [x] Partial matches display in alphabetical order 


#### 3) User enters event code and sees exact match first in dropdown list for court-issued docket entries
* Login as docket clerk
* Go to a case 
* Upload PDF 
* Click “Add Docket Entry”
* Enter Document Type = “HE”
Expected results 
- [x] “Hearing Exhibits” is sorted to top of list 
- [x] Partial matches display in alphabetical order 


#### 4) User enters document type and sees exact match first in dropdown list for court-issued docket entries
* Login as docket clerk
* Go to a case 
* Upload PDF 
* Click “Add Docket Entry”
* Enter Document Type = “Transcript”
Expected results 
- [ ] “Transcript” is sorted to top of list 
- [ ] Partial matches display in alphabetical order 


#### 5) Party enters event code and sees exact match first in dropdown list for e-filings 
* Login as irsPractitioner
* Go to a case 
* Click “File a Document” 
* Enter Document Type = “A”
Expected results 
- [x] “Answer” is sorted to top of list 
- [x] Partial matches display in alphabetical order 

#### 6) Party enters document type and sees exact match first in dropdown list for e-filings 
* Login as irsPractitioner
* Go to a case 
* Click “File a Document 
* Enter Document Type = “Motion for Leave to File”
Expected results 
- [x] “Motion for Leave to File” is sorted to top of list 
- [x] Partial matches display in alphabetical order
