### ISSUE TITLE
Court User: Deleting and modifying documents attached to messages

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7207]
As a court user, so that I may delete or modify orders and correspondence attached to messages, I need the ability to edit or delete these documents and have messaging still work correctly. 

## Acceptance Criteria
* Court user can edit the title of a attached document and the updated title displays in the messaging thread or anywhere else it displays in the system
* Court user can delete a correspondence or draft document that's attached to a message thread without disrupting the business workflow. 
* Remove deleted PDFs from messages

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add archivedDocuments array to case (Mrinalini, Rae, Matt ustaxcourt/ef-cms-flexion#6196)
- [x] Ensure archivedDocuments are filtered out for external users from the case data (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6205)
- [x] Remove deleteDraftDocumentAction and associated code (Mrinalini, Rae, Matt ustaxcourt/ef-cms-flexion#6201)
- [x] Ensure all document deletions set the archived flag on the document entity
  - [x] Ability to archive documents on a case back-end (Mrinalini, Rae, Matt ustaxcourt/ef-cms-flexion#6201)
  - [x] All documents (including SDEC) should be archived on 'delete', not truly deleted (Mrinalini, Rae, Matt ustaxcourt/ef-cms-flexion#6201)
  - [x] call Case.archiveDocument() wherever a document is being archived (Mrinalini, Rae, Matt ustaxcourt/ef-cms-flexion#6201)
- [x] Fetching case documents should filter archived documents (which belong in the  archivedDocuments array) (Matt, Rae, Mrinalini ustaxcourt/ef-cms-flexion#6196)
- [x] Refactor attachment association (pull from documents / archived documents) by reference (Matt ustaxcourt/ef-cms-flexion#6208)
- [x] Fix reference to document titles on Case Messages attachments column (Matt ustaxcourt/ef-cms-flexion#6215)
- [x] Deleted document attached to message (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6214)
  - [x] Retain document title in Attachments list (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6214)
  - [x] Update text color to bg-base-dark (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6214)
  - [x] Display “Deleted” in row of document (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6214)
  - [x] on select of deleted document, display message “This document was deleted.” (Mrinalini & Rae ustaxcourt/ef-cms-flexion#6214)
- [x] Modified document attached to message (Matt ustaxcourt/ef-cms-flexion#6208)
  - [x] Clerk edits draft/correspondence title (Matt ustaxcourt/ef-cms-flexion#6208)
  - [x] On save of document title / description updates, the Message Detail attachments list should display the updated title (Matt ustaxcourt/ef-cms-flexion#6208)
- [x] Clerk adds/edits docket entry for draft document attached to message, on save entry (Matt ustaxcourt/ef-cms-flexion#6208)
  - [x] Updated document title (aka. documentType) selected on Add Docket Entry screen should display on Message Detail (Matt ustaxcourt/ef-cms-flexion#6208)
  - [x] Original draft document title should not display (Matt ustaxcourt/ef-cms-flexion#6208)
- [x] Decide what to do with attachments not found in the aggregated documents array (previously deleted, for instance)  (Matt ustaxcourt/ef-cms-flexion#6208)
- [x] Add archivedCorrespondence to case (Mrinalini, Cody, Rae ustaxcourt/ef-cms-flexion#6228)
- [x] Archive correspondence documents instead of delete (Mrinalini, Cody, Rae ustaxcourt/ef-cms-flexion#6228)
- [x] Remove Attachments column from Case Messages view (Matt ustaxcourt/ef-cms-flexion#6218)
- [x] Bug reloading messages on case detail after delete document with message association (Matt ustaxcourt/ef-cms-flexion#6236)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
## Message Detail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/56b7bc70-a94f-4665-b5cb-6987ec50d4e4)


#### Attachments List 
**Deleted document attached to message**
*  Retain document title in Attachments list 
* Update text color to  bg-base-dark 
* Display “Deleted” in row of document 

#### PDF Preview
*on select of deleted document, display message “This document was deleted."

#### Document title is changed after draft/correspondence document is attached to message 

**Clerk edits draft/correspondence title**
* On save of document title / description updates, the Message Detail attachments list should display the updated title 

**Clerk adds docket entry for draft document attached to message**
* On Save Entry 
- updated document title (aka. documentType) selected on Add Docket Entry screen should display on Message Detail 
-  original draft document title should not display

**Comment by klohman** [comment]
### 5893 Deleting document that is attached to message

#### 1) Internal user deletes draft document that is attached to message and views message
* Login as docket clerk 
* Go to case xx1-20
* Create Order, save, sign 
* Send message with order attached to adc 
* Delete draft Order 
* Login as adc 
* View message from docket clerk 
Expected results 
- [x] Message displays in Inbox for adc 
- [x] Message displays Order as attachment 
- [x] Order displays as “Deleted” in Attachments list 
- [x] PDF Preview for Order displays message “This document was deleted”


#### 2) Internal user deletes correspondence document that is attached to message and views message
* Login as docket clerk 
* Go to case xx1-20
* Add Correspondence File = “Letter”
* Send message with “Letter” attached to adc 
* Delete “Letter” from Correspondence File 
* Login as adc 
* View message from docket clerk 
Expected results 
- [x] Message displays in Inbox for adc 
- [x] Message displays “Letter” as attachment 
- [x] “Letter” displays as “Deleted” in Attachments list 
- [x] PDF Preview for “Letter” displays message “This document was deleted”

#### 3) Internal user edits draft document title and views in Message Detail 
* Login as docket clerk 
* Go to case xx1-20
* Create Notice  
* Enter description = “Notice of things to come” 
* Save 
* Create message to Judge Buch with “Notice of things to come”  attached 
* Go to Drafts
* Edit “Notice of things to come” 
* Click Edit Title 
* Update document title to “Notice of Trial” 
* Save 
* Login as judge Buch 
* View message from docket clerk  
Expected results 
- [x] Message detail displays updated draft title “Notice of Trial” 
- [x] Drafts screen displays updated draft title “Notice of Trial”

#### 4) Internal user edits correspondence document title and views in Message Detail 
* Login as docket clerk 
* Go to case xx1-20
* Upload Correspondence File 
* Enter description = “Notes from Petitioner” 
* Save 
* Create message to Judge Buch with “Notes from Petitioner” attached 
* Go to Drafts
* Edit “Notes from Petitioner” 
* Update description to “Letter from Petitioner”
* Save 
* Login as judge Buch 
* View message from docket clerk  
Expected results 
- [x] Message detail displays updated draft title “Letter from Petitioner” 
- [x] Drafts screen displays updated draft title “Letter from Petitioner” 

#### 5) Docket clerk adds draft document, attaches to message, adds docket entry for draft message with new document title, and views updated document title on Message Detail 

* Login as docket clerk 
* Go to case xx1-20
* Upload PDF 
* Enter description = test exhibits 
* Save 
* Send message with draft document “test exhibits” attached 
* Navigate to Message Detail 
* Click Add Docket Entry on “test exhibits” documents 
* Select document type = Hearing Exhibits 
* Save entry 
* View Message Detail - Attachments list 
Expected results 
- [x] attachment title now displays as “Hearing Exhibits” instead of “exhibits”

#### 6) Docket clerk adds edits document title for docket entry document attached to message

* Login as docket clerk 
* Go to case 
* Add Paper Filing for doc type = "Motion"
* Save and Serve "Motion"
* Send message with "Motion" attached
* Click Edit on "Motion" from docket record
* Update Doc type to "Motion for Continuance"
* Save 
* View Message Detail - Attachments list 
Expected results 
- [x] attachment title now displays as "Motion for Continuance"
