### ISSUE TITLE
Revise search options for date

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7210]
As a court user, so that I can refine my report search, I need the ability to search for future dates or a specific date. 

## Acceptance Criteria
* For Deadline Report, user can search for and find deadlines falling within any date range, past, present and future
* For Deadline Report, user can search for and find deadlines on a specific date (past, present or future) and not just a range
* Apply new date finder object on all date entry fields in the CMS

## Mobile Design/Considerations
Consider mobile design - external users also have these entry fields.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* USWDS has updated their date range selector. Use theirs

## Tasks
- [x] replace date input component w/ new USWDS date picker component (Cody ustaxcourt/ef-cms-flexion#6105)
- [x] replace calendar w/ USWDS date picker on deadline report (Jojo ustaxcourt/ef-cms-flexion#6103, ustaxcourt/ef-cms-flexion#6110)
- [x] validation update for deadline report (Jojo / Cody)
- [x] (potential) date parsing (Jojo ustaxcourt/ef-cms-flexion#6110)
- [x] bug: end date getting reset in query after changing start date for range in deadlines report (Jojo / Cody)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f279c2a8-6f80-47ce-9a75-1873cc70fb60)### Updated Deadlines Report screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/926d3507-3367-4900-be5c-17565dcb66b2)

* Replace date picker with [USWDS date range picker](https://designsystem.digital.gov/components/form-controls/#date-range-picker) 

**Start Date**
* is required 
* Can be past or future 

**End Date**
* Is required 
* if blank, error message "Enter an End date."
* Cannot be < Start Date  
   * Error message displays “End date cannot be prior to Start Date. Enter valid End date.”

* can be past or future date 

**Show Deadlines button**
* on click, display cases meeting search criteria in table 

### Updated Advanced Search > Order 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7cce80d4-988e-434e-826d-d77592634607)

* Replace date picker with [USWDS date range picker](https://designsystem.digital.gov/components/form-controls/#date-range-picker) 

**Start Date**
* is required 
* Current validation  

**End Date**
* Is optional 
* if blank, date range is assume to be [Start Date] to [today] 
* Cannot be < Start Date  
* current validation  

### Updated Advanced Search > Opinion 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/34c0a05a-8aa6-472d-99bf-ce02d6e1cc28)

* Replace date picker with [USWDS date range picker](https://designsystem.digital.gov/components/form-controls/#date-range-picker) 

**Start Date**
* is required 
* Current validation  

**End Date**
* Is optional 
* if blank, date range is assume to be [Start Date] to [today] 
* Cannot be < Start Date  
* current validation

**Comment by adunkman** [comment]
Here’s a link to [the USWDS date range selector docs](https://designsystem.digital.gov/form-controls/06-date-range-picker/).

**Comment by klohman** [comment]
### 5993 Test Scenarios 

Test Data 
Deadlines
- (322-20) Case xx1-20 - deadline 02/20/20
- (106-20) Case xx2-20 - [today’s date]
- (325-20x) Case xx3-20 - 10/11/20 
- (327-20s) Case xx4-20 - 06/01/20
- (1247-20) Case xx5-20 - 06/15/20
- (1191-20) Case xx6-20 - 06/30/20
- (174-20) Case xx7-20 - 12/01/20
- (243-20) Case xx8-20- 12/19/20
- (1115-20) Case xx9-20 - 12/31/20 

Orders 
- Case xx1-20 
    - Order to Show Cause. 
        - Keyword -HHS
        - Served 07/28/20
    - Summary Opinion 
        - Keyword -judicial
        - Served 07/28/20
- Case xx2-20 
    - TC Opinion
        - Keyword -judicial
        - Served 07/29/20
- Case xx3-20 
    - Memorandum Opinion 
        - Keyword -judicial
        - Served [today]


#### 1) Internal user searches for deadline by single date (past) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 02/20/20
* Enter end date = 02/20/20
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines from 02/20/20 

#### 2) Internal user searches for deadline by single date (present) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = [today’s date]
* Enter End date = [today’s date]
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines from [today]

#### 3) Internal user searches for deadline by single date (future) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 10/11/20
* Enter end date 10/11/20
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines from 10/10/20

#### 4) Internal user search for deadlines by date range (past) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 06/01/20
* Enter End date = 06/30/20
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines between (and including) 06/01/20 and 06/30/20

#### 5) Internal user search for deadlines by date range (future) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 12/01/20
* Enter End date = 12/31/20
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines between (and including) 12/01/20 and 12/31/20

####6) Internal user search for deadlines by date range (past and future) 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 06/01/20
* Enter End date = 12/31/20
* Click View Deadlines 
Expected results 
- [x] Deadlines report table displays 
- [x] Report contains all deadlines between (and including) 06/01/20 and 12/31/20

#### 7) Internal user cannot search for deadline with end date prior to start date 
* Login as internal user 
* Navigate to Deadlines Report 
* Enter Start date = 12/01/20
* Enter End date = 11/30/20
* Click View Deadlines 
Expected results 
- [x] Error message displays “End date cannot be prior to Start Date. Enter valid End date.”

#### 7) Internal user searches for orders by single date
* Login as internal user
* Navigate to Advanced Search 
* Click Orders
* Enter keyword “HHS” 
* Enter Start Date = 07/30/20
* Enter end date = 07/30/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include orders with keyword “HHS” from 07/30/20 

#### 8a) Internal user searches for orders by date range (explicit)
* Login as internal user
* Navigate to Advanced Search 
* Click Orders
* Enter keyword “HHS” 
* Enter Start Date = 07/28/20
* Enter End Date = 07/30/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include orders with keyword “HHS” from 07/28/20 to 07/30/20

#### 8b) Internal user searches for orders by date range (implicit)
* Login as internal user
* Navigate to Advanced Search 
* Click Orders
* Enter keyword “HHS” 
* Enter Start Date = 07/30/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include orders with keyword “HHS” from 07/30/20 to [today]


#### 9) Internal user searches for opinions by single date
* Login as internal user
* Navigate to Advanced Search 
* Click Opinions
* Enter keyword “judicial” 
* Enter Start Date = 07/30/20
* End date = 07/30/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include opinions with keyword “judicial” from 07/30/20 

#### 10) Internal user searches for opinions by date range (explicit)
* Login as internal user
* Navigate to Advanced Search 
* Click Orders
* Enter keyword “judicial” 
* Enter Start Date = 07/28/20
* Enter End Date = 07/30/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include opinions with keyword “judicial” from 07/28/20 to 07/30/20

#### 11) Internal user searches for opinions by date range (implicit)
* Login as internal user
* Navigate to Advanced Search 
* Click Orders
* Enter keyword “judicial” 
* Enter Start Date = 07/28/20
* Click Search 
Expected results 
- [x] Search results table displays
- [x] Search results include opinions with keyword “judicial” from 07/28/20 to [today]

#### 12) Internal users see date picker component for all date entry fields 
* View all date entry fields (work with Rachael to identify all instances) 
Expected results 
- [x] new USWDS date picker component is used  

#### 13) External users see date picker component for all date entry fields 
* View all date entry fields (work with Rachael to identify all instances) 
Expected results 
- [x] new USWDS date picker component is used  

#### 14) Public users see date picker component for all date entry fields 
* View all date entry fields (work with Rachael to identify all instances) 
Expected results 
- [x] new USWDS date picker component is used

**Comment by klohman** [comment]
Internal user:
- [x] Add Paper Filing -> Certificate of Service date
- [x] Add/Edit Paper Filing -> Date received
- [x] Create/Edit Case Deadline Modal -> Due date
- [x] Add Deficiency Statistics -> Late date of period
- [x] Start Case from Paper -> IRS notice date
- [x] Start Case from Paper -> Petition payment date, Petition waived date
- [x] Start Case from Paper -> Date received
- [x] Start Case from Paper -> Add Statistic -> Late date of period
- [x] Edit Petition Details -> IRS notice date
- [x] Add Court-Issued Docket Entry -> Date (on some nonstandard types)
- [x] Edit Docket Entry Meta (edit link on docket record) -> Filed date (different forms for court-issued, paper filing with a document, and paper filing without a document)
- [x] Add a Practitioner -> Admissions date
- [x] Add Trial Session -> Start date
External user:
- [x] File a Document -> Certificate of Service date
- [x] File a Document -> Service date (on Certificate of Service document type)
- [x] File a Document -> Supporting Document -> Certificate of Service date
- [x] Request Access to Case -> Certificate of Service date

**Comment by klohman** [comment]
@codyseibert @sutt0n 

Correct logic for Start Date on Order and Opinion search 

(from https://github.com/flexion/ef-cms/issues/4829)
* Date range
* Field group is optional
* Limits scope of keyword search to orders with matching Filed date within entered date range
* Scope includes start and ending date
* Date format must be complete: MM/DD/YYYY
* If start date is entered, but end date is left blank - end date equals today
