### ISSUE TITLE
Data Migration: Migrate legacy cases that are calendared for trial

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7211]
As the Court, in order to make sure that all open trial sessions are able to be worked in the new system, we need to migrate legacy cases that are calendared for trial and make sure they're associated to the correct trial session in the CMS.

## Acceptance Criteria:
* Migrate legacy cases that are calendared for trial and make sure they're associated to the correct trial session. 
* A new Notice of Setting Case for Trial and SPTO/SPTN should not be generated
* After migration, legacy cases and trial sessions should work exactly the same as if the session was completely generated in the new CMS
   * Display trial session info on Case Info tab
   * Working copies (Judge and Trial Clerk)
   * Reciprocal note feature
   * (Others)
* Update data migration documentation/API as needed

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Possible solution -- manually add legacy trial sessions to CMS (will need to determine how to manually add a session without cases, w/o it being closed) and pass legacy cases with "Calendared" as case status with a trial date and trial city which match one of the manually added sessions.

## Questions for Mark
- what data do we have coming in with a case to match a trial session? what criteria to use to match?
  - A: trial session id will be migrated as well, per @mark-meyer

## Answers
- create trial sessions if they're new (not matched)
  - better choice from engineering standpoint
  - ~~_iff_ trial session created via migration(s), no notices should be generated when info modified (bool flag: `Case.resumeNoticesAt`)~~
    - ~~update: going to pause notifications after a case is migrated for X amount of time~~
  - migrated cases will have trialSessionId coming in

## Tasks
- [x] new endpoint, `/migrate/trial-session` (Kris / Jojo ustaxcourt/ef-cms-flexion#6222)
- [x] associate trial session data w/ cases (incoming field via @mark-meyer) (Kris / Jojo ustaxcourt/ef-cms-flexion#6231 )
~~- [ ] resume notices after certain period of time (via `Case.resumeNoticesAt`) (Kris / Jojo)~~
- [x] `Case.trialSessionId` is required _iff_ `Case.status` = calendared (Kris / Jojo ustaxcourt/ef-cms-flexion#6231 )
- [x] add migration integration test (Jojo ustaxcourt/ef-cms-flexion#6238)
- [x] update migration docs (Jojo ustaxcourt/ef-cms-flexion#6238)
- [x] instead of adding `caseOrder` right off the bat to Trial Sessions, update the Trial Session with the docketNumber for each case as they're migrated (modify case migration interactor) (Jojo ustaxcourt/ef-cms-flexion#6246)
  - as a case is migrated, if a case has a trial session, add that case to the trial session's calendar (e.g. addCaseToCalendar)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Tested with Mark 8/20/2020.

Small bug found relating to migrating same case multiple times -- backlogged by Eric as bug.
