### ISSUE TITLE
Apply Read/Unread to New Messaging Flow, and total counts to QC boxes

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7213]
As the Court, in order to make sure our employees know what is new work, we need to apply read/unread to the new messaging flow.

## Acceptance Criteria:
* Apply read/unread to Message Inbox for all court users [NOTE: No read/unread needed in QC box]
* Message Inbox count is the number of Unread messages {Note: Follow up w/court on user needs}
* Message inbox counts are displayed on tabs instead of global header. 
* Confirm envelope icon for new message is working correctly in global header
* QC counts are number of total items in QC (for new and in progress)
* QC counts are displayed on tabs instead of global header. (new and in progress) 
## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x] 1 Individual Message row unread indicator
   - [x] 1.a Add `isRead` to Message entity (Matt ustaxcourt/ef-cms-flexion#6389)
   - [x] 1.b Route, sequence, action for setting message as read (Matt ustaxcourt/ef-cms-flexion#6389)
   - [x] 1.c Endpoint and persistence method for setting message as read (Matt ustaxcourt/ef-cms-flexion#6389)
   - [x] 2.d Display closed envelope icon and bold message subject on unread individual message rows (Matt ustaxcourt/ef-cms-flexion#6394)
 - [x] 2 Display message count on individual Inbox tab label (Jojo ustaxcourt/ef-cms-flexion#6399)
 - [x] 3 Display total message count on section Inbox tab label (Jojo ustaxcourt/ef-cms-flexion#6399)
 - [x] 4 Display closed envelope icon and bold message subject on unread judge / chambers dashboard recent message rows  (Matt ustaxcourt/ef-cms-flexion#6394)
 - [x] 5 Docket - My / Section Document QC - remove count in page title header (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 6 Docket - My / Section Document QC - Add total inbox count to Inbox label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 7  Docket - My / Section Document QC - Add total in progress count to In Progress label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 8 Internal User - remove count in page title header (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 9 Internal User - Add total inbox count to Document QC Inbox label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 10 Internal User -  Add total in progress count to In Progress label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)`
 - [x] 11 Petitions - My / Section Document QC - remove count in page title header (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 12 Petitions - My / Section Document QC - Add total inbox count to Inbox label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 13  Petitions - My / Section Document QC - Add total in progress count to In Progress label (Mrinalini & Matt ustaxcourt/ef-cms-flexion#6393, ustaxcourt/ef-cms-flexion#6406)
 - [x] 14 Endpoint or computed for fetching box count for given user / box (Mrin, Matt, ustaxcourt/ef-cms-flexion#6406) <---------> (Jojo ustaxcourt/ef-cms-flexion#6399)
- [x] 15 Global Header 
  - [x] 15.a New message icon displays when unread items are present in the My Messages Inbox (Jojo ustaxcourt/ef-cms-flexion#6422)
  - [x] 15.b New message icon Displays number of unread items in My Messages Inbox (Jojo ustaxcourt/ef-cms-flexion#6422)
  - [x] 15.c. New message icon Is hidden when no unread items are present in My Messages Inbox (Jojo ustaxcourt/ef-cms-flexion#6422)
- [x] Bug: My Document QC "In Progress" count incorrect after saving (not serving) a new Paper Filing entry (Matt, Jojo ustaxcourt/ef-cms-flexion#6406)
  - Test Scenario: `Docket clerk sees total number of in progress QC items in My Document QC In Progress`

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written 
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Global Header 

**New message icon**
* Displays when unread items are present in the My Messages Inbox 
* Displays number of unread items in My Messages Inbox
* Is hidden when no unread items are present in My Messages Inbox 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/245b41c0-9cf4-4d98-a41e-f505d0a0cc25)

### My Messages > Inbox  

**Unread message**
* Displays closed envelope icon on unread message
* Message subject line text is displayed in bold 


**Total message count**
* Total message count is displayed in Inbox tab label 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/51628bd8-5345-40e5-bc9e-796f2c34eb71)

### Section Messages > Inbox  

* No concept of unread messages for the Section Inbox 

**Total message count**  * Total messages in Inbox is displayed in Inbox tab label = Inbox(#)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4044d04c-c7e0-4729-88a6-e61711dea6ab)

### Judges/ Chambers Dashboard - Recent Messages 

**Unread message**
* Displays closed envelope icon on unread message
* Message subject line text is displayed in bold 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/611f8e54-5b73-4764-8131-a7de5850a33f)

### Docket My Document QC

* remove count in page title header 
* No concept of unread document qc items

**Total Inbox count**  * Total messages in Inbox is displayed in inbox tab label: “Inbox (#)” 

**Total In Progress count**  * Total messages in Inbox is displayed in inbox tab label: “In Progress (#)” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c937966f-babe-44a3-9df7-a518879f9de4)

### Docket Section Document QC

* remove count in page title header 
* No concept of unread document qc items

**Total Inbox count**  * Total messages in Inbox is displayed in inbox tab label: “Inbox (#)” 

**Total In Progress count**  * Total messages in Inbox is displayed in inbox tab label: “In Progress (#)” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/609da721-220b-41ed-9dae-201bd11dd086)


### Internal User Document QC

* remove count in page title header 
* No concept of unread document qc items

**Total Inbox count**  * Total messages in Inbox is displayed in inbox tab label: “Inbox (#)” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/acfd6c8a-dddd-4145-94ca-c1f6fdf5c71c)


### Petitions My Document QC

* remove count in page title header 
* No concept of unread document qc items

**Total Inbox count**  * Total messages in Inbox is displayed in inbox tab label: “Inbox (#)” 

**Total In Progress  count**  * Total messages in In Progress is displayed in inbox tab label: “In Progress  (#)” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cdb4bd90-9a5b-4a66-b6b4-a73c53592a4a)

### Petitions Section Document QC

* remove count in page title header 
* No concept of unread document qc items

**Total Inbox count**  * Total messages in Inbox is displayed in inbox tab label: “Inbox (#)” 

**Total In Progress  count**  * Total messages in In Progress is displayed in inbox tab label: “In Progress  (#)” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/67680f0d-71f2-45b4-9c3a-ffb9abb08265)

**Comment by klohman** [comment]
### 6069 Test Scenarios 


Test data
* Send new message to adc1 - subject line “needs signature”

#### 1) Internal user sees message icon in global header when there are unread messages in Inbox 
* Login as adc1 
* View global header 
Expected results 
- [x] Yellow message icon displays in global header  with "1" number displays 

#### 2) Internal user does not see message icon in global header when there are unread messages in Inbox
* Scenario 1 
* Click on Messages from global nav 
* Click into message “needs signature” 
Expected results 
- [x] Yellow message icon no longer displays in global header 

#### 3) Internal user sees unread messages in My Messages Inbox 
* Login as docket clerk  
* Send message on case xx1-20 to adc1
* Login as adc1
* View My Messages Inbox 
Expected results 
- [x] Message on case xx1-20 from docket clerk displays as unread (envelope icon, bold subject) 


#### 4) Internal user sees total number of messages in My Messages Inbox 
* Scenario 3 
* View My Messages Inbox 
Expected results 
- [x] Inbox displays number of messages in tab label 
- [x] Total messages displays in table matches the total messages count 

#### 5) Internal user sees total number of messages in Section Messages Inbox 
* Login as adc2 
* Navigate to Section Messages Inbox 
Expected results 
- [x] Inbox displays number of messages in tab label 
- [x] Total messages displays in table matches the total messages count 

#### 6) Docket clerk sees total number of QC items in My Document QC Inbox
* Login as docket clerk 1
* Navigate to Section Document QC
* Assign 3 QC items to docket clerk 1 
* Click on My Document QC Inbox 
Expected results 
- [x] My Document QC Inbox displays number of items in tab label = Inbox (3)
- [x] Total QC items in table matches the total items count in the tab label 

#### 7) Docket clerk sees total number of QC items in Section Document QC Inbox 
* Login as docket clerk 1
* Navigate to Section Document Q
Expected results 
- [x] Section Document QC Inbox displays number of items in tab label 
- [x] Total QC items in table matches the total items count in the tab label 

#### 8) Internal user (not docket or petitions) sees total number of QC items in Section Document QC Inbox 
* Login as admissions clerk 1 
* Navigate to Document QC 
Expected results 
- [x] Document QC Inbox displays number of items in tab label 
- [x] Total QC items in table matches the total items count in the tab label 

#### 6) Docket clerk sees total number of in progress QC items in My Document QC In Progress 
* Login as docket clerk 1 
* Navigate case xx2-20
* Add Paper Filing
* Save Entry 
* Navigate to My Document QC > In Progress 
Expected results 
- [x] My Document QC In Progress displays number of items in tab label 
- [x] Total In Progress QC items in table matches the total items count in the tab label 

#### 7) Docket clerk sees total number of in progress QC items in Section Document QC In Progress 
* Login as docket clerk 1 
* Navigate to Section Document QC > In Progress 
Expected results 
- [x] Section Document QC In Progress displays number of items in tab label 
- [x] Total In Progress QC items in table matches the total items count in the tab label 

#### 8) Petitions clerk sees total number of QC items in My Document QC Inbox
* Login as petitions clerk 1
* Navigate to Section Document QC
* Assign 3 QC items to petitions clerk 1 
* Click on My Document QC Inbox 
Expected results 
- [x] My Document QC Inbox displays number of items in tab label = Inbox (3)
- [x] Total QC items in table matches the total items count in the tab label 

#### 9) Petitions clerk sees total number of QC items in Section Document QC Inbox 
* Login as petitions clerk 1
* Navigate to Section Document QC
Expected results 
- [x] Section Document QC Inbox displays number of items in tab label 
- [x] Total QC items in table matches the total items count in the tab label 

#### 10) Petitions clerk sees total number of in progress QC items in My Document QC In Progress 
* Scenario 8 
* Navigate to My Document QC > Inbox 
* Click into a Petition 
* Review petition 
* Click Save for Later 
* Navigate to My Document QC > In Progress 
Expected results 
- [x] My Document QC In Progress displays number of items in tab label 
- [x] Total In Progress QC items in table matches the total items count in the tab label 

#### 11) Petitions clerk sees total number of in progress QC items in Section Document QC In Progress 
* Login as petitions clerk 1 
* Navigate to Section Document QC > In Progress 
Expected results 
- [x] Section Document QC In Progress displays number of items in tab label 
- [x] Total In Progress QC items in table matches the total items count in the tab label 

#### 12) Judge / chambers user sees unread messages in Recent Messages on dashboard 
* Login as docket 
* Send message to Judge Buch on case xx3-20 
* Login as Judge Buch 
* View Recent Messages 
Expected results
- [x] Message on case xx3-20 from docket clerk displays as unread (envelope icon, bold subject)
