### ISSUE TITLE
Docket Clerks: Sealed Addresses (design + data migration)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7214]
As the Court, in order to protect some of our petitioners, we need to allow addresses to be sealed.

From time to time the Court has a situation (maybe domestic violence, heightened privacy concern, etc.) that will require us to SEAL a party's address.  This means that the address is not viewable to anyone *except* Docket.  The Court needs the ability to do this prospectively, as well as with legacy cases. There are several cases in the legacy case management system where the address of a party is sealed.  We need a way to pass their real address and mark it as sealed so that it doesn't show to anyone other than Docket.

## Acceptance Criteria:
* As part of the data migration, CMS needs a way to ingest sealed addresses
* The docket section has a way to seal an address. 
* After it's sealed, the sealed address should only be viewable to the Docket section.
* Update data migration documentation, as appropriate.

***NEW*** see additional AC in [comments](https://github.com/flexion/ef-cms/issues/6070#issuecomment-680225649)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Update Case entity to have `isAddressSealed` flag (Mrinalini & Kris ustaxcourt/ef-cms-flexion#6252)
- [x] Case Information - only viewable to Docket Clerk 
   - [x] Update `getCaseInteractor` to remove address/email/telephone from endpoint response (Kris ustaxcourt/ef-cms-flexion#6260 )
   - [x] Add “Seal Address” link to each Petitioner card (Mrinalini ustaxcourt/ef-cms-flexion#6253)
   - [x] On click of "Seal Address", open Seal Address modal (Mrinalini ustaxcourt/ef-cms-flexion#6257)
- [x] Create Seal Address modal (Mrinalini ustaxcourt/ef-cms-flexion#6257)
   - [x] Display petitioner name (Mrinalini ustaxcourt/ef-cms-flexion#6257)
- [x] Create sequence to seal address on submit
   - [x] Display confirmation message “Address sealed for [Petitioner Name].”  (Mrinalini ustaxcourt/ef-cms-flexion#6257)
   - [x] Add proxy, interactor,  lambda for sealing an address (Kris ustaxcourt/ef-cms-flexion#6255)
- [x] Case Information viewing a sealed address - Docket Clerk view  (Mrinalini)
   - [x] Add lock icon by petitioner name (Mrinalini + Kris ustaxcourt/ef-cms-flexion#6261)
   - [x] Address/phone number are visible (Mrinalini ustaxcourt/ef-cms-flexion#6261)
   - [x] Address/ phone number text is updated to secondary-dark (Mrinalini ustaxcourt/ef-cms-flexion#6261)
- [x] Case Information viewing a sealed address - Internal User view (Mrinalini & Kris  ustaxcourt/ef-cms-flexion#6263)
   - [x] Add lock icon by petitioner name 
   - [x] “Address Sealed” test color is secondary dark
   - [x] Message Displays “Address Sealed”
   - [x] Address/telephone/email information is hidden
- [x] Case Information viewing a sealed address- External User view (Mrinalini & Kris  ustaxcourt/ef-cms-flexion#6263)
   - [x] Add lock icon by petitioner name
   - [x] “Address Sealed” test color is secondary dark
   - [x] Message Displays “Address Sealed”
   - [x] Address/telephone/email information is hidden
- [x] Printable Docket Record PDF (all users) (Rachael ustaxcourt/ef-cms-flexion#6265)
   - [x] Add lock icon by petitioner name
   - [x] Message Displays “Address Sealed”
   - [x] Address/telephone/email information is hidden
- [x] Data Migration  (Mrinalini & Kris ustaxcourt/ef-cms-flexion#6252)
   - [x] Update migration documentation  (Mrinalini & Kris ustaxcourt/ef-cms-flexion#6252)
- [x] Ensure all get-case and search endpoints filter sealed addresses (Kris ustaxcourt/ef-cms-flexion#6272) 
- [x] Hide edit button (on petitioner and spouse contact info) for petitioner user when address is sealed (Mrinalini ustaxcourt/ef-cms-flexion#6283)

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written (Mrinalini ustaxcourt/ef-cms-flexion#6270)
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts (Rachael ustaxcourt/ef-cms-flexion#6269)
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects (Rachael ustaxcourt/ef-cms-flexion#6269)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt (Mrinalini ustaxcourt/ef-cms-flexion#6270)
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by klohman** [comment]
### Case Detail  > Case Information > Petitioner 

#### Docket Clerk view
**Address is not Sealed**
* Add “Seal Address” link to each Petitioner card 
* On click of "Seal Address", open Seal Address modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/06c52086-d7bf-468f-93eb-919bce063515)


### Seal Address Modal 

* Display petitioner name 

**On click of Yes, Seal Address**
* Modal closes and screen displays success message “Address sealed for [Petitioner Name].”

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/910ebdc4-54e0-4455-ab4d-9a016e4b06ef)


### Case Detail  > Case Information > Petitioner 

#### Docket Clerk view
**Address is Sealed**
* Add lock icon by petitioner name 
* Address/phone number are visible 
* Address/ phone number text is updated to secondary-dark 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3abdf9e3-3a08-4344-ad23-b5db803e7d26)

### Case Detail  > Case Information > Petitioner 

#### Internal user  view
**Address is Sealed**
* Add lock icon by petitioner name 
* Address / telephone informaiton is hidden 
* Message displays “Address sealed”
* “Address sealed” text color is secondary-dark  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a94b31e3-6e4e-4f8e-aec0-f802bf416a67)

### Case Detail  > Case Information > Petitioner 

#### External user  view
**Address is Sealed**
* Add lock icon by petitioner name 
* Address / telephone informaiton is hidden 
* Message displays “Address sealed”
* “Address sealed” text color is secondary-dark  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/69dbfcc5-0f9f-4bd6-888d-7e15a6491bfb)

### Printable Docket Record PDF ( For all users) 

* Add lock icon by petitioner name 
* Address / telephone information is hidden 
* Message displays “Address sealed”

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c10f91e8-0a5e-4b7a-8cbd-819b7f38e0c8)


### Data Migration 

* Migrated cases with petitioner(s) with sealed address should display the same as above 

#### Other petitioners
* Petitioners that appear in the "Petitioner" tab  with sealed addresses should display same as above. 

**Other petitioners - not sealed**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e8cec22a-1ed0-44da-b9a6-d3aa78b72449)

**Other petitioners - sealed address**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/df279efb-85bf-4095-8f9a-9df2c43e2471)


#### Other filer 

**Not sealed**
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/01fd1067-7bca-4547-87e6-d45bedcece79)

**Other filers - sealed address** 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/01780ee6-64f9-4191-86ae-f6b78b653d94)

**Comment by klohman** [comment]
### 6070 Sealed Addresses Tests Scenarios 

**Case xx1-20**
* Petitioner and Spouse

**Case xx2-20**
* E-filed case as petitioner1
* Petitioner 
* Seal address for petitioner

**Case (migrated)**
- With Other Petitioner 

**Case (migrated)**
- With Other Filer

#### 1) Docket clerk sees Seal Address option for petitioners 
* Login as docket clerk 1
* Navigate to case xx1-20 
* Click Case Information tab > Petitioners tab
Expected results 
- [x] “Seal Address” link is visible for primary contact 
- [x] “Seal Address” link is visible for secondary contact 

#### 2) Internal users (not docket) do not see Seal Address option for petitioners 
* Login as petitions clerk 
* Navigate to case xx1-20 
* Click Case Information tab > Petitioners tab
Expected results 
- [x] “Seal Address” link is not visible for primary contact 
- [x] “Seal Address” link is not visible for secondary contact 

#### 3) Docket clerk seals address for a petitioner (primary contact)
* Scenario 1 
* Click “Seal Address” for primary contact 
* Click “Yes, Seal Address” on modal 
Expected results 
On click of “Seal Address” 
- [x] Seal Address modal displays 
- [x] Primary contact name displays on modal 
On click of Yes, Seal Address 
- [x] Modal closes 
- [x] Screen displays success message ““Address sealed for [Primary contact].”
- [x] “Seal Address” link is hidden for primary contact 
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are displayed in red text
- [x] “Seal address” link is visible for secondary contact 
- [x] Secondary contact has no lock icon 
- [x] Secondary contact address /phone number are displayed in normal body copy text color

#### 4) Docket clerk seals address for a petitioner (secondary contact)
* Scenario 3
* Click “Seal Address” for secondary contact 
* Click “Yes, Seal Address” on modal 
Expected results 
On click of “Seal Address” 
- [x] Seal Address modal displays 
- [x] Secondary contact name displays on modal 
On click of Yes, Seal Address 
- [x] Modal closes 
- [x] Screen displays success message ““Address sealed for [Secondary contact].”
- [x] “Seal Address” link is hidden for primary contact 
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are displayed in red text
- [x] “Seal address” link is hidden for secondary contact 
- [x] Secondary contact has lock icon 
- [x] Secondary contact address /phone number are displayed in red text color


#### 5a) Docket clerk seals address for other petitioner (migrated data)
* Login as docket clerk 
* Navigate to migrated case with additional petitioner
* Click “Seal Address” for other petitioner  
* Click “Yes, Seal Address” on modal 
Expected results 
On click of “Seal Address” 
- [x] Seal Address modal displays 
- [x] Other petitioner name displays on modal 
On click of Yes, Seal Address 
- [x] Modal closes 
- [x] Screen displays success message ““Address sealed for [Other petitioner].”
- [x] “Seal Address” link is hidden for Other petitioner
- [x]  Other petitioner has lock icon 
- [x] Other petitioner address /phone number are displayed in red text


#### 5b) Docket clerk seals address for other filer (migrated data)
* Login as docket clerk 
* Navigate to migrated case with other filer (intervener or participant)
* Click “Seal Address” for other filer  
* Click “Yes, Seal Address” on modal 
Expected results 
On click of “Seal Address” 
- [x] Seal Address modal displays 
- [x] Other filer name displays on modal 
On click of Yes, Seal Address 
- [x] Modal closes 
- [x] Screen displays success message ““Address sealed for [Other filer].”
- [x] “Seal Address” link is hidden for Other filer
- [x] Other filer has lock icon 
- [x] Other filer address /phone number are displayed in red text


#### 6) Docket clerk views case with sealed address 
* Login as docket clerk 2 
* Navigate to case xx2-20
* Click Case Information > Petitioner 
Expected results 
- [x] “Seal Address” link is hidden for primary contact 
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are displayed in red text

#### 7) Internal user (not docket) views case with sealed address 
* Login as judge 
* Navigate to case xx1-20 
* Click Case Information > Petitioner 
Expected results 
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are hidden 
- [x] “Address sealed” for primary contact displays in red text
- [x] Secondary contact has lock icon 
- [x] Secondary contact address /phone number are hidden 
- [x] “Address sealed” for secondary contact displays in red text

#### 8) External party views case with sealed address 
* Login as petitioner 1
* Navigate to case 1721-20
* Click on Case Information > Petitioner 
Expected results 
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are hidden 
- [x] “Address sealed” for primary contact displays in red text
- [x] Secondary contact has lock icon 
- [x] Secondary contact address /phone number are hidden 
- [x] “Address sealed” for secondary contact displays in red text

#### 9) User views Printable Docket Record for case with sealed address 
* Scenario 8 
* Click Docket record tab 
* Click Printable Docket Record 
Expected results 
Printable Docket record displays
- [x] Primary contact has lock icon 
- [x] Primary contact address /phone number are hidden 
- [x] “Address sealed” for primary contact displays 
- [x] Secondary contact has lock icon 
- [x] Secondary contact address /phone number are hidden 
- [x] “Address sealed” for secondary contact displays

**Comment by uxforgood** [comment]
# New requirement around Petitioner's editing contact info for a sealed address
@JessicaMarine @mrinsin @kkoskelin 

## Acceptance Criteria

- Petitioner isn't able to edit the contact information (for themselves or secondary contact) if that address is sealed 
- Petitioner sees message of how to contact the Court in order to change contact information if the address is sealed 

## Design

- If an address is sealed, the Petitioner no longer sees the "Edit" button/link on the Contact info box when looking at Case information 
- Instead, Petitioner sees text "Call the Tax Court at (202) 521-0700 if you need to update your contact information." in _**italics**_ under the "Sealed address" text 
- This would appear on any sealed address, whether it's the primary or secondary contact

![image](https://user-images.githubusercontent.com/43787395/91217979-f9b87e00-e6dd-11ea-86be-a0ba4d068439.png)

## Test scenario

10) External party views case with sealed address (replaces # 8 in original scenarios) 
- Login as petitioner 1
- Navigate to case xx-20
- Click on Case Information > Petitioner

**Expected results**

- [x] Primary contact has lock icon
- [x] Primary contact address /phone number are hidden
- [x] “Address sealed” for primary contact displays in red text
- [x] Edit link is no longer visible for contact information 
- [x] "Call the Tax Court at (202) 521-0700 if you need to update your contact information." appears under red "Address sealed" text
- [x] The same applies to the Secondary contact, if the address is sealed for them as well
