### ISSUE TITLE
Data Migration: Legacy documents already served by the parties

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7216]
As the Court, so that legacy documents that have already been served by the parties show up on the docket record correctly, no service information is required.

Currently, a legacy document that was already served by the parties and, therefore, not served by the Court is showing "Not Served" in red on the docket record.  These documents need to be treated as served or not required to be served so that they show up on the docket record correctly.

## Prerequisite
* There's a post-MVP story in Flexion's backlog for selecting served parties. Do we need to do this or is there a workaround?

## Acceptance Criteria:
* Legacy document that has already been served by a party should not display "Not Served" on the docket record. [Note: Discuss with Mark Meyer; he may be able to pass an `Already Served` flag on these entries]
* Documents already served can be identified because they have a (C/S date) as part of the entry

Note:
* Legacy documents won't have a service date or other service information because in the legacy system that data is recorded in the certificate of service. 
* After discussing with Mark, it has been decided that the flag being used is named `isLegacyServed`, not `alreadyServed`.

Questions for Mark:
* Could we get an example case that would exhibit this behavior?
* Do the cases being migrated already have `servedAt` and `servedParties` defined on their documents?
* Should we be populating `servedAt` and `servedParties` if empty when C/S is present?

## Tasks
- [x]  Do not display 'Not Served'  on the Docket Record for documents that are legacy documents and have been served - Rachael ustaxcourt/ef-cms-flexion#6241 
  - [x] `servedAt` and `servedParties` must be blank - Rachael ustaxcourt/ef-cms-flexion#6241
- [x] When `alreadyServed` is true then treat document as unservable document - Rachael ustaxcourt/ef-cms-flexion#6241

## Definition of Done (Updated 7-2-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by JessicaMarine** [comment]
Reviewed w/ Mark 8/20/2020
