### ISSUE TITLE
Court: Display Bench Opinions on Today's Opinions (Tom)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7227]
As the Court, in order to have all of our opinions appear in the same place, Bench Opinions should be displayed on Today's Opinions.

## Preconditions
* Bench opinion is served.

## Acceptance Criteria:
* Bench Opinions (Doc Code OST) should appear in Today's Opinions
   * Type should be listed as the document type
* The bench opinion should be publicly viewable on the docket record
* A bench opinion in a sealed case should return in the today's opinions and the document should be viewable

## Notes
* OST =  Order of Service of Transcript (Bench Opinion)
* Should OST still display in Today's Orders? No.
* Should OST be searchable under Order Search? No.

## Tasks
- [x] Display served OST documents in today’s opinions - Team mob ustaxcourt/ef-cms-flexion#7721
- [x] Don’t display served OST documents in today’s orders - Team mob ustaxcourt/ef-cms-flexion#7723
- [x] Display Judge in today's opinions table - Team mob ustaxcourt/ef-cms-flexion#7723
- [x] Bench opinions in sealed cases should be publicly viewable in Today's opinions - Team mob ustaxcourt/ef-cms-flexion#7723

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Code toggle has been implemented (“On” for items that are QA’d)
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a532f283-5675-4ef0-98ff-97ed301491ea)

**Comment by klohman** [comment]
#### 6239 Test Scenarios 

#### 1) Public user sees served OST in Today’s Opinions 
* Login as docket clerk 
* Go to case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-opinions
Expected results 
- [x] OST is listed in Today’s Opinions 
- [x] OST Opinion Type displays as Order of Service of Transcript (Bench Opinion)

#### 2) Public user does not see served OST in Today’s Orders 
* Login as docket clerk 
* Go to case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-orders
Expected results 
- [x] OST is not listed in Today’s Orders 

#### 3) Public user views PDF for OST 
* Scenario 1 
* Click document link for OST 
Expected results 
- [x] OST PDF opens 

#### 4) Public user views PDF for OST in a sealed case 
* Login as docket clerk 
* Go to a sealed case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-opinions
* Click document link for OST 
Expected results 
- [x] OST PDF opens 


#### 5) Public user sees served OST in Today’s Opinions (MOBILE)
* Login as docket clerk 
* Go to case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-opinions
Expected results 
- [x] OST is listed in Today’s Opinions 
- [x] OST Opinion Type displays as Order of Service of Transcript (Bench Opinion)

#### 6) Public user does not see served OST in Today’s Orders  (MOBILE)
* Login as docket clerk 
* Go to case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-orders
Expected results 
- [x] OST is not listed in Today’s Orders 

#### 7) Public user views PDF for OST  (MOBILE) 
* Scenario 1 
* Click document link for OST 
Expected results 
- [x] OST PDF opens

#### 8) Public user views PDF for OST in a sealed case  (MOBILE)
* Login as docket clerk 
* Go to a sealed case 
* Upload PDF and sign
* Add docket entry and serve OST 
* Go to public site - /todays-opinions
* Click document link for OST 
Expected results 
- [x] OST PDF opens 

#### 8) Public user views PDF for OST from public docket record 
* Go to public site 
* Search for case with OST
* Click document link for OST from docket record 
Expected results 
- [x] OST PDF opens
