### ISSUE TITLE
Prod: Run deployments without umzug issues

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7232]
As a system administrator, so that I can deploy a new version of the code, I need to be able to update all records in persistence to meet the requirements of the latest version of the code base without running into umzug issues. 

## Preconditions:
* Migrate the fake golden data set to Flexion's prod environment

## Acceptance Criteria:
* Deploys should take fewer than 6 hours (In case we need to roll back)
* ~16 million items in data table 
* Migrate both DynamoDB and ElasticSearch
- Migration processes need to run inside of AWS, not CircleCI
- Manual checks are expected instead of a fully automated deployment
- The system should continue to function while the data is being migrated
- rolling back must be an option if there's a migration failure

## Notes:
* Estimate of 750k items are on open cases only (which is 3-5% of total legacy data); We'll likely create another story to deal with the entire data set. 
* Court has specified a 12-hour downtime window for deploys
* Possibly need to create another database (e.g. what another Flexion team did to deal w/deployment times)
* Also consider using a fall-back location for data (Mike)
* an interesting article with someone trying to ingest 10million records into dynamo and the optimization he had to do to make it happen in 3 hours https://www.codementor.io/@mohdbelal/writing-millions-of-records-in-dynamodb-14zgyszj41
  * use batchWrite (25 inserts at a time)
  * run umzug in AWS (maybe lambda) on same region of dynamo (reduce latency)
  * parallel process records (multi-threaded scan / writes)
  * turn auto-scaling off on dynamo table and set a high provisioned WCU / RCU
- ~migration would be initiated by a CircleCI job~
- Get segments for the table, run processes simultaneously on segments
- use SQS to queue up the jobs for the segments, which would be handled by lambdas (assuming each can run under 15 minutes)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

#### Migrate items as they requested by a user
- no downtime
- rollbacks are no longer an option
- elasticsearch queries may be more complicated

#### Query for items needing a migration with ElasticSearch and only access the items needing a change (no scan required)
- won't help with migrations that require a change to every item

#### Migrate data to a second table before the new code is deployed ✅
- easy to roll back
- may be expensive

#### Run multiple migration jobs to parallelize the work ✅
- may be expensive

## Mobile Design/Considerations

- none

## Tasks (Cody version - To Discuss with team)

Migration Infrastructure
- [x] create a new global table in our web-api terraform code
- [x] setup separate terraform scripts for migration resources
  - [x] segments (SQS) (Cody & Rae)
  - [x] record modifier (Lambda)
  - [x] segments -> record modifier (event source mapping)
  - [x] migration (Lambda)
  - [x] dynamo stream -> migration
- [x] the kickoff script (Cody & Rae)
  - [x] grab the total item counts from the dynamodb table
  - [x] divide the count by a constant to get the total segments we will need (TOTAL_SEGMENTS = count / CONSTANT)
  - [x] publish a separate SQS event for each segment { segment: 0,1,2,.....(TOTAL_SEGMENTS-1), totalSegments: TOTAL_SEGMENTS}
- [x] the record modifier lambda
  - [x] a lambda which takes in SQS events
  - [x] scan the table using the segment + totalSegments
  - [x] modify each record by adding "migrate": true
  - [x] batchWrite the items back to the original table
- [x] the migration lambda
  - [x] a lambda which reads in the dynamodb stream events
  - [x] for each record, run it through the migration code (make sure it is idempotent code)
  - [x] batchWrite / write the record to the new table
  - [x] Conditional writes so it doesn't update records that have already been migrated
- [x] validation script / steps (iteration 0) 
  - [x] verify the new table has the same item count as the old table
- [x] Cleanup common bash scripts in migration-terraform / terraform (ex - deploy-app.sh)
- [x] Blue/green deploys
  - [x] deploy 2 separate APIs 
  - [x] 2 separate UI deploys
  - [x] script to do the switchover
  - [x] fix scripts that are hardcoded to find a specific api to include color
- [x] separate elasticsearch per color
- [x] Delete old Umzug migrations and set up migrated seed data locally
  

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the stage environment
