### ISSUE TITLE
Tech Lead: Health and Configuration Endpoints

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7233]
As the Court’s Tech Lead, so that I can be sure EF-CMS is in a functional state, I need to be able to check each component is configured together correctly and operational, both during regular operations and after deployments.

## Acceptance Criteria: 
* Tech Lead can ensure that each component is configured together correctly and operational
* Current status only, historical data is not needed
* API and UI should be publicly available
* Responses must be returned within X milliseconds
* DynamoDB tables are reachable from lambda
* ElasticSearch is reachable from lambda
* Dynamsoft library is reachable from lambda
* ClamAV service is reachable from lambda
* Email service is reachable from lambda (AWS CLI command)
* All S3 buckets on all regions are reachable from lambda
* Cognito is reachable from lambda

## Notes:
* Access and security are not included in this user story. if we have security requirements, create another story. 
* Potential tasks:
   * A JSON endpoint is added to each application component. (UI, public UI, API, public API.)
   * The endpoint returns the URLs it is using to access the other components it needs to use.
   * May include other API endpoints, login pages, Elasticsearch endpoints, etc.
   * For APIs which access a data store, the endpoint contacts that data store and ensures a connection can be made.
   * A smoke test which hits these endpoints post-deploy.
* Specifically out of scope: 
   * Monitoring or alerting on this endpoint.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

```
const url = '/health';

// example results
const results = {
  dynamoDB: {
    efcms: true,
    efcmsDeploy: true,
  },
  elasticSearch: true,
  s3: {
    east: {
      client: true,
      clientFailover: true,
      documents: true,
      tempDocuments: true,
    },
    west: {
      client: true,
      clientFailover: true,
      documents: true,
      tempDocuments: true,
    },
  },
};
```

## Tasks

- [x] DynamoDB tables are reachable from lambda (#6341)
- [x] ElasticSearch is reachable from lambda (#6341)
- [x] Dynamsoft library is reachable from lambda (#6341)
- [x] ClamAV service is reachable from lambda (#6341, not fully implemented until fargate story has been completed)
- [x] Email service is reachable from lambda (AWS CLI command) (#6341, ustaxcourt/ef-cms-flexion#6352)
- [x] All S3 buckets on all regions are reachable from lambda (#6341)
- [x] Cognito is reachable from lambda (#6341)
- [x] UI (#6343, ustaxcourt/ef-cms-flexion#6346)
- [x] Smoke test (#6347)

## Definition of Done (Updated 8-3-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by adunkman** [comment]
Not sure where this issue is at, but wanted to chime in that we’re currently diagnosing an issue in the cognito authorizer which is preventing logins for the IRS — so it would be great to get the authorizer covered somehow.
