### ISSUE TITLE
Implement ClamAV

### ISSUE THREAD

**Issue by sutt0n** [ustaxcourt/ef-cms#7234]
As a development team, to ensure that all files can be scanned with ClamAV, we need an AWS ECS configured in Fargate to properly and effectively scan documents for viruses. (See Spike ustaxcourt/ef-cms#7212)

## Acceptance Criteria:
* Implement ClamAV.
* If Fargate:
  * On document upload to the quarantine S3 bucket, an S3 PutObject event is fired off to an SQS queue
  * An ECS instance configured via Fargate (with ClamAV running) continuously polls the SQS queue
  * After a message is consumed, its metadata is parsed and the file associated with the metadata is scanned
  * If a file is clean, it's moved to the documents bucket
  * If a file is *NOT* clean, keep it in the quarantine bucket (max lifetime 7 days)
    * Send CloudWatch alert, tag S3 Object as `infected`
* Confirm all concerns in Pen Testing Report have been remediated (see note)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Penetration Test: [https://app.zenhub.com/files/152320868/b94ffc44-672b-433f-8ca0-9dd34f893a8b/download](https://app.zenhub.com/files/152320868/b94ffc44-672b-433f-8ca0-9dd34f893a8b/download)

## Tasks
- [x] Create quarantine S3 bucket - Rachael ustaxcourt/ef-cms-flexion#8560
- [ ] Update all upload paths to upload to quarantine bucket ustaxcourt/ef-cms-flexion#8608
- [x] Create SQS queue with s3 upload trigger - Rachael ustaxcourt/ef-cms-flexion#8562 
- [x] Create ECS instance configure via Fargate with ClamAV running (Rachael, Eric, Jojo) ustaxcourt/ef-cms-flexion#8591
- [x] Create ~function~ Dockerfile with worker to process messages in SQS queue, scan the documents, and process the result - (Rachael, Jojo) ustaxcourt/ef-cms-flexion#8591
- [x] Update `virus-scan` endpoint to return true for now - RP, KK ustaxcourt/ef-cms-flexion#8606 
- [x] Update logging messages to be more descriptive - RP, KK ustaxcourt/ef-cms-flexion#8605
- [ ] Discuss CI/CD for Docker image (or should it be manually like CI docker image?) (REFACTORING)
- [x] create virus scanning use case interactor for the fargate handler - Rachael, Jojo, ES, KK ustaxcourt/ef-cms-flexion#8603
- [ ] webpack task for bundling fargate handler with use case and applicationContext - RP, ES, KK ustaxcourt/ef-cms-flexion#8608
- [ ] verify that resources that should be in 2 regions have been created in both
- [ ]  If a file is *NOT* clean, keep it in the quarantine bucket 

Refactoring:
- [ ] Break up web-api/terraform/main/clamav.tf into smaller files

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by sutt0n** [comment]
Flow:

![image](https://user-images.githubusercontent.com/1116426/91218900-6718de80-e6df-11ea-914b-9f5d47224a62.png)

**Comment by cnelsonflexion** [comment]
"Your file is being scanned for potential issues."
- (if virus found) **We've detected a problem with your file.** (new line) Please create a new file and try to upload again. Ref: #####
- (if file is clean) Your file has been uploaded successfully.

**Comment by mariahkannenberg** [comment]
This story is being put back in the backlog due to a shift in prioritization. We also broke it out into multiple stories. ustaxcourt/ef-cms#7976 ustaxcourt/ef-cms#7977 ustaxcourt/ef-cms#7978
