### ISSUE TITLE
Notes on Practitioners (Rosie)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7237]
As the Court, in order to record notes specific to an individual practitioner, we need the ability to add notes on an individual practitioner.

## Acceptance Criteria:
* Admissions Clerk can add/edit notes (free text box OK) on each practitioner
* All other Court users (other than Admissions Clerks) can view notes only

## Notes 
* where does this note need to display? Only practitioner detail screen? (Doesn't need to display anywhere else)
* Similar to case notes, w/no formatting options

## Security Considerations
 - [ ] This work make you nervous about privacy or security?
 - [ ] This work make major changes to the system?
 - [ ] This work implement new authentication or security controls?
 - [ ] This work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add practitioner notes card (view only except for practitioner)
- [x] Add form field for practitioner notes - ustaxcourt/ef-cms-flexion#7801
- [x] Add notes field to Practitioner entity - ustaxcourt/ef-cms-flexion#7801
- [x] Add validation (character limit = 500, “Limit is 500 characters. Enter 500 or fewer characters.”, optional) -#7801
- [x] Error message (above 500 chars) -#7801 
- [x] Fix email validation when adding a new email when creating the cognito account
![image](https://user-images.githubusercontent.com/16403861/108563445-5031fe00-72b6-11eb-9bff-5f363347deb0.png)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Code toggle has been implemented (“On” for items that are QA’d)
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Add Practitioner screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/662e702f-6244-4a9d-9c2b-d45cb6e126c0)

#### Practitioner Notes section 
* Add practitioner notes section to form 

**Practitioner Notes field**
* Is optional 
* Character limit = 500 
* Error message if over character limit = “Limit is 500 characters. Enter 500 or fewer characters.”


## Practitioner Detail screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/42d6d3a6-343b-4829-90ea-efe7cb2f13d2)

* Update Admissions Information card per design 

#### Practitioner Notes card 
* Add Practitioner notes card 
* Display note text read-only 


## Edit Practitioner screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/42d425d8-d91a-4558-a259-4d35962127fd)


#### Practitioner Notes section 
* Add practitioner notes section to form 

**Practitioner Notes field**
* Is optional 
* Populates with note text 
* Character limit = 500 
* Error message if over character limit = “Limit is 500 characters. Enter 500 or fewer characters.”

**Comment by klohman** [comment]
## 6335 test scenarios 

#### 1) Admissions clerk enters practitioner note when adding a new practitioner 
* Login as admissions clerk 
* Go to Advanced Search > Practitioner 
* Click Add Practitioner 
* Enter practitioner note : “This is a new practitioner note” 
* Complete form 
* Save 
Expected results 
- [x] Practitioner note field displays on Add Practitioner form
- [x] On save, Note is displayed on Practitioner Detail screen 

#### 2) Admissions clerks adds practitioner note when editing a practitioner 
* Login as admissions clerk 
* Go to Advanced Search > Practitioner 
* Search for existing practitioner 
* Click bar number link 
* Click Edit link on Practitioner Detail screen
* Enter practitioner note : “This is another practitioner note” 
* Save 
Expected results 
- [x] Practitioner note field displays on Edit Practitioner form
- [x] On save, Note is displayed on Practitioner Detail screen 

#### 3) Admissions clerk adds practitioner note with 501 characters and sees error message 
* Login as admissions clerk 
* Go to Advanced Search > Practitioner 
* Click Add Practitioner 
* Enter practitioner note with 501 characters  
* Save 
Expected results 
- [x] Error message displays on note field = “Limit is 500 characters. Enter 500 or fewer characters.”

#### 4) Admissions clerk edits practitioner note with 501 characters and sees error message 
* Login as admissions clerk 
* Go to Advanced Search > Practitioner 
* Search for existing practitioner 
* Click Edit link on Practitioner Detail screen
* Enter practitioner note with 201 characters  
* Save 
Expected results 
- [x] Error message displays on note field = “Limit is 500 characters. Enter 500 or fewer characters.”

#### 5) Internal users views practitioner detail and sees note 
* Scenario 1 
* Login as internal user (other than admissions) 
* Search for practitioner (from scenario 1) 
Expected results 
- [x] Practitioner note displays on Practitioner Detail as read-only

**Comment by JessicaMarine** [comment]
PO Review:
* I'm still getting the same spinning wheel when I try to add practitioner notes to MJ2286
* Also, I'm still seeing the progress bar sometimes -- Sometimes it flashes really quick, others it lasts several seconds.
* Found another practitioner that it won't let me add notes to -- UT0011

**Comment by rachelschneiderman** [comment]
Note: When data is brought into the court's migration environment from production, emails associated with users in the system are changed to `<MD5_HASH>@mig.ef-cms.ustaxcourt.gov` to prevent real people from receiving emails generated in this environment. Currently, the data import process does not create cognito accounts for migrated email addresess so attempting to update a user with a migrated email will display the progress spinner indefinitely. Make sure to test with a user that either does not have an email or has an email with a cognito account.

Here is an example of what an email without a cognito account looks like:
![image.png](https://images.zenhubusercontent.com/5e331dde16551cf7ef3a8f50/99faa85c-1962-4f40-ab94-87cb33319cf6)
