### ISSUE TITLE
Spike: Test load of QC, Docket Record, etc for returning 100s of items in a list

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7241]
As a court user, I need the system to return all items in a query regardless of the number of items. 

Background
Due to load limits, the QC inbox is not displaying all items in the list. Instead, a partial list is returned when the load limit is reached. In order to know if this is problematic, we need to perform testing with data that replicates actual case quantity and size. If testing reveals that current functionality doesn't meet the business need, may need to consider pagination or other solution. 

**For MVP:** Need to make sure high-priority items aren't being affected by this.  If we agree to save most of the work for post-MVP, need to make sure that high-priority items filter to top.

## AC
* Create a list of places where we have the 1M limit in place and items aren't displaying (all the places we get a collection of items)

## Notes
 - Doesn't affect Elastic Search
- check the order that work items are being retrieved - they should be coming in oldest to newest
 - Immediate workaround is to manually clear it out. But there could be thousands in there. 

## Tasks
- [x] 1 Create a list of places where we do a dynamo or elasticsearch query and could return an unlimited amount of results
- [x] 2 Research elasticsearch return limits - are there any? what happens if many many results are returned? does it handle that well? - limit is set to 10,000 results by default, but we override that to 5000 
- [x] 3 Verify that the work items aren't coming back with highest priority first - they aren't

**Comment by rachaelparris** [comment]
### High Risk
* getAllCatalogCases
	* related to setting cases ready for trial
	* records are small but there are many of them
* getDocketNumbersByUser 
	* called when generating change of address
	* these records are fairly small but could be a lot of them for some practitioners
	* also includes closed cases in this response so this will get worse over time
* getDocumentQc\*For*
	* gets work items for user/section
	* not sorted by priority, so higher priority work items could not be returned
* retrieves values for a single case:
	* getCaseByDocketNumber 
		* docket entries, practitioners, correspondences - could reach the 1M limit
	* updateCase, setPriorityOnAllWorkItems, getMessagesByDocketNumber
		* retrieve work items/messages for a single case
		* we don’t ever delete these things, so they could build up over time and we do not filter out “inactive” work items or messages when retrieving

### Medium Risk
* getMessageThreadByParentId - what is a realistic count for total messages in a thread?
* getTrialSessions - what is a realistic count for total number of trial sessions?
* getAllCaseDeadlines 
	* the catalog records are small; we shouldn’t hit a limit
	* load tested locally with realistic data and the limit seems to be a little over 5000 records

### Low Risk
* getElasticsearchReindexRecords 
	* retrieves records that failed initial indexing via elasticsearch 
	* these are deleted after they are eventually indexed, so even if we hit a limit here, the count will eventually go down
* getEligibleCasesForTrialSession 
	* gets eligible case list for a trial session
	* has a limit in place (max cases on a trial session), and sorts by priority in returned results
* getEligibleCasesForTrialCity 
	* gets counts for trial session planning report
	* the records are very small, so we should not hit a limit
* elasticsearch queries (all have a size limit of 5000 set)
	* getCaseInventoryReport (uses paging already on the API side)
	* getIndexedCasesForUser  - paging is only on front end
	* getBlockedCases 
	* fetchPendingItems
	* casePublicSearch - paging is only on front end
	* caseAdvancedSearch - paging is only on front end
	* advancedDocumentSearch - paging is only on front end
