### ISSUE TITLE
Court: Ability to Scan/Edit Correspondence

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7325]
As an Admissions, Petitions, or Docket Clerk, I need the ability to scan in and edit documents in the correspondence file so that I can easily add correspondence to the case.

## Acceptance Criteria
* The Add Correspondence File screen allows a user to either upload OR scan in a document
* Scanning functionality should be identical to current scanning functionality used for paper petitions/filings
* Scanned documents are treated as Correspondence by the system in the same way that uploaded documents are treated as Correspondence
*  The Edit Correspondence File screen allows a user to either upload OR scan in a document

## Tasks
- [x] Update AddCorrespondenceDocument.jsx to use `scanBatchPreviewer` - Rosie & Mrin  ustaxcourt/ef-cms-flexion#9305
- [x] Update EditCorrespondenceDocument.jsx to use `scanBatchPreviewer` - Rosie & Mrin  ustaxcourt/ef-cms-flexion#9305

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## 6641 Test scenarios 

#### Set-Up Flow
* Petition/docket clerk logs in
* Navigates to case
* Selects “Correspondence”
* Sees “Add Correspondence” page
* Scan radio button is selected by default

#### First Use - Install Flow
* User is prompted to download and install scan utility software
* Click download
* Software downloads
* User installs software to computer
* User returns to Case Information page and refreshes

#### First Use - Cancel Install Flow
* Sees prompt to download and install scan utility software
* Clicks "X" to cancel download
* Returns to Case Information page after install
* Can upload documents but not scan

#### Select Scanner Flow
* Clicks “Select Scanner” link
* Sees modal window with list of available scanners
* Selects a scanner
* Sees "How would you like to scan your documents"?
* Selects an option
* Clicks "Select"
* Sees selected scanner name and Option for scanning
* “Select Scanner” link is hidden; “Change” link displays
---------------
* Clicks "Cancel" / "Close"
* Modal closes without action

#### Correspondence Upload Flow
* Selects “Upload” radio button
* User selects file from computer
* Uploaded PDF displays in full pdf preview window 

#### Add First Batch Flow
* Selects “Scan” radio button
* Loads scanner hopper
* Clicks “Start Scan” button
* [Hopper scans documents]
* Scan utility software may display a progress bar
* [Hopper completes scan]
* Sees “Batch 1” under Scanned Batches, no link
* Sees batch page count in batch table (1 duplexed page counts as 2 scanned pages)
* Sees “Rescan” button in batch table
* Sees “Delete” button in batch table
* Sees preview of Batch 1 pages, one page at a time
* Uses batch preview navigation to verify scan is clean and clear

#### Hopper is Empty Flow 
* Clicks “Start Scan” while hopper or flat-bed is empty 
* Sees Modal communicating the hopper / flat-bed is empty
* Loads hopper
* Clicks “Scan”
* [Scan]
---------------
* Clicks "Cancel" / "Close"
* Modal closes without action

#### Preview Multiple Batches Flow
* [scan Batch 1]
* Batch 1 appears under Scanned Batches and displays in batch preview
* Click “Start Scan”
* [scan Batch 2]
* Batch 2 appears under Scanned Batches and displays in batch preview 
* Batch 1 text becomes a link 
* Clicks “Batch 1”
* Sees Batch 1 in batch preview
* Batch 1 text link removed (shown as selected) 
* Batch 2 text becomes a link 
* Uses navigation to view batch page-by-page
* Clicks “Batch 2”
* Sees Batch 2 in batch preview
* Uses navigation to view batch page-by-page

#### Rescan a Batch Flow
* Clicks “Rescan”
* Sees Modal window requesting confirmation of desire to rescan batch
* Clicks “Yes, rescan”
* [Scan]
* New scanned batch page count updates under Scanned Batches
* New scanned batch images appear in batch preview 
---------------
* Clicks "No, cancel" / "Close"
* Modal closes without action

#### Delete a Batch Flow (multiple batches) 
* Clicks “Delete”
* Sees Modal requesting confirmation of desire to remove batch
* Clicks “Yes, delete”
* Modal closes
* Selected batch is removed from Scanned Batches list 
* Batch order and naming remains persistent 
* Batch preview displays previous batch (if batch 2 was deleted, preview displays batch 1)  
* Previous batch displays as selected
---------------
* Clicks "No, cancel" / "Close"
* Modal closes without action

#### Delete a Batch Flow (single batches) 
* Clicks “Delete”
* Sees Modal requesting confirmation of batch removal
* Clicks “Yes, delete”
* Modal closes
* Selected batch is deleted 
* Batch preview is hidden
---------------
* Clicks "No, cancel" / "Close"
* Modal closes without action

#### Create PDF Flow 
* [scan flow] 
* Click Create PDF 
* PDF is generated from scanned batches in numeric order of batches
* Sees full PDF preview displays in preview panel 
* PDF is associated with document field and green check displays next to document name in H3 tabs
* Sees “Remove PDF” button


#### Delete PDF Flow
* [scan or upload flow]
* [if scan flow then create PDF flow]
* Click “Remove PDF“ 
* Sees modal requesting confirmation of desire to delete PDF
* Click "Yes, delete"
* PDF is deleted and document returns to default state [no file attached]
---------------
* Clicks "No, cancel" / "Close"
* Modal closes without action

#### Scanning Error Flow
* Sees Modal communicating scanning error
* Clicks “OK”
* Modal closes without action
---------------
* Use Dynamsoft's own error modals where possible

#### Unfinished Scans Flow - Document Not Finished
* [scan flow]
* Scanned batches exist for a document but PDF has not been generated
* Clicks on “Finish” 
* Sees Modal communicating that scanning has not been completed yet
* Clicks “OK, discard scans” 
* Modal closes, unfinished scans are deleted
* Form is submitted
* [no change to rest of current flow]
---------------
* Clicks "No, cancel" / "Close"
* Modal closes without action

**Comment by klohman** [comment]
## Add Correspondence (default) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9921dbee-bceb-4285-975c-68d23ead282e)
* Add “How do you want to add this document” field 
* Scan - updated functionality to match other scanning options
* Upload - current functionality for uploading PDF

**Comment by cholly75** [comment]
Tested on MIG. Two issues observed:

1) When you choose to Scan in Correspondence, if something had previously been scanned in (for example, a Paper Filing) then the prior scan already shows up as the scanned batch when moving to the Correspondence tab. Expected behavior is that no prior scan is already displayed as the Correspondence batch.

2) Clicking "Finish" before saving the Scan as a PDF elicits an incorrect validation message telling the user they must select a file for upload (screenshot below). Expected behavior is that the user receives the same sort of modal seen when clicking "Save for Later" on a Paper Filing that hasn't had a PDF created.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/d3a546c5-c874-467a-845f-781f729d5f5a)

**Comment by cholly75** [comment]
Testing today w/ Court employee to confirm final test case.
