### ISSUE TITLE
Performance Tuning - based on test legacy case migrations (Mike to QA Test)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7327]
As the tech lead for the USTC, so that I can ensure that changes to dynamoDB will be indexed and not swallowed by an exception, I need to conduct performance tuning - including adding specific descriptions to logging messages. 

## Acceptance Criteria
* Add more specific descriptions to logging messages in processStreamRecordsInteractor (#6701)
* Ensure Production Environment is ready for migration
* Demo the migration in the Production Environment
* Verify the **full** data set and quantity:
 	• Cases -  973,665
	• Individual docket records -  approx 7,890,000 
	• On average, around 8 docket entries on case; but there are a lot of outliers, some scaling up to 800.
	• Anything with entity name of user:
		○ Practitioners - approx 147,000
		○ Users (includes duplicates) - 1.2 M
	• Messages - not migrating
	• Case deadlines - approx 5k
        * UserCase - one user per case; some w/two; edge case w/ 80 people on case
* Guarantee that changes to dynamoDB will eventually be indexed (never swallowed by an exception)
* Migration of entire data set into Dynamo DB and indexing should be completed in ~12 hours. (If this time is not realistic, let's adjust. Shoot for this for now. We want to trim time off where we can, but aren't locked into an exact time.)
* List out all EF-CMS features that use elastic search access points:

#### Features Using ES
**Advanced Document Search**
**Advanced Case Search**
**Public Case Search**
**Blocked Cases**
**Case Inventory Report**
**Health Checks**
**User Open / Closed Cases**
**User Consolidated Cases**
**Practitioner Search**
**Case Deadline Search**
**User / Section Messages (inbox, outbox, completed)**

#### Persistence Methods Invoking the Search Client (ES)
advancedDocumentSearch
caseAdvancedSearch
casePublicSearch
fetchPendingItems
getBlockedCases
getCaseInventoryReport
getFirstSingleCaseRecord
getIndexedCasesForUser
getPractitionersByName
getCaseDeadlinesByDateRange
getCompletedSectionInboxMessages
getCompletedUserInboxMessages
getSectionInboxMessages
getSectionOutboxMessages
getUserInboxMessages
getUserOutboxMessages

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add more specific descriptions to logging messages in processStreamRecordsInteractor (Kris, Cody, Mrin ustaxcourt/ef-cms-flexion#6701)
- [x] JS file to post example case to the case migration endpoint with different docketNumbers
- [x] Document remaining areas that use elastic search in AC (list started above)
- [x] Stop emails from being sent from the production environment. 

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment
 - [x] Deployed to the **prod** environment

**Comment by codyseibert** [comment]
**Leaving this for documentation, but we think this issue was resolved due to a bug in the bulkIndex code:**

The current issue we are running into is that we scaled up our exp3 elasticsearch to 3 nodes using m5.large.elasticsearch instance types.  We have 2 people (myself and Kris), migrate 10,000 cases using the `migrationPerfTest.js` script which hits the /migrate/case endpoint 20,000 in total.  After all the cases have been migrated, we do an index count of the `efcms-case` index on elasticsearch, and we find that 2 cases -- one run we found 10 cases -- are missing.  The things that might be going wrong include:

- elasticsearch is dropping data
- dynamodb is throttling and the data never makes it into dynamo
- the migrate case endpoint is failing somehow and never adding the case record
- the dynamodb stream never gets the case event
- due to parallel processing, the processing streams lambda is deleting a case record AFTER it has been added

**Comment by ericsorenson** [comment]
Problems:

- If a case title changes, we have to re-index every value of metadata and every PDF document's contents from S3. (we do this so that we have an index that contains both metadata and document contents as the results of the search, document contents need to be in sync with the case title) All of this data is gathered by a lambda with a limited lifespan.
- Messaging is coupled with Case indices. When case or document indexing is blocked or slow, messages are as well.

Questions:
- Can we make the streams lambda async to avoid the 30 second timeout? No, the lambda is running out of memory.
- How much hardware have we made available to ES? This isn't an ES issue, it's a lambda issue. (Cody - I'm not seeing this as being the issue)
- Is the out of memory error from a bug or too much data? Even with many items, it's probably not too much data. (potentially fixed in ustaxcourt/ef-cms-flexion#6808)
- Try testing locally with one of the biggest cases. (Cody - I found some reasons for the poor performance in ustaxcourt/ef-cms-flexion#6808)
- Turn on AWS X-Ray.
- Investigate the applicationContext, maybe it has something causing issues? (I don't think this is the issue)
- Migrate our test data from staging to exp1. (Cody - done)

Next steps for optimizing docketEntry / parent-child indexing:
- [x] https://blog.mimacom.com/parent-child-elasticsearch/
- [x] Not indexing a combined case/docketEntry record for every docketEntry
- [x] Not re-indexing every docketEntry on a case when there are changes on a case
- [x] Create a record in the ef-cms docketEntry index with case data (this record gets updated only when the case changes)
- [x] Define parent/child relationships between the case/docketEntry mapping and the docketEntry records
- [x] Perform queries against the case/docketEntry mapping combined with the docketEntry records
- Each stream lambda run would do a subset of the work that was previously done
