### ISSUE TITLE
CMS User: Lambda timeout (Pick this story up first in the sprint)

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7340]
As any user of the system attempting to access a page, I should not be logged out if the Lambda request times out at 29s; instead I should receive an error so that I can try again or continue to use the system.

## Acceptance Criteria
* If the lambda is timing out, the user should receive an error message
* The user should not be logged out of the system
* The error should be logged and include context about the request, so that it can be replicated

## Notes
* Something to consider - This would be an excellent use for a 504 Gateway Timeout
* This is just for Lambda timeouts; for other timeouts, we'll perform a spike and document

## Tasks
- [x] implement APIGateway response for 504 timeouts on API (Jojo ustaxcourt/ef-cms-flexion#6914)
- [x] add UI from design (Jojo ustaxcourt/ef-cms-flexion#6914)
- [x] add APIGateway response for 504 timeouts on public API (Jojo ustaxcourt/ef-cms-flexion#6920)
- [x] add UI from design to public (Jojo ustaxcourt/ef-cms-flexion#6920)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by klohman** [comment]
Error messaging: 

**Page title**
* display error code 

**Button**
* On click, app routes to previous page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ec9caaa2-10de-47db-8d75-28fbada4b776)

**Comment by mariahkannenberg** [comment]
@sutt0n 

dawson.support@ustaxcourt.gov
