### ISSUE TITLE
Performance Tuning: getDocketNumbersByUser

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7395]
As the Court, in order to make sure that all cases needing a Notice of Change of Address/Phone/Both get one, we need to make sure that the system properly returns the user’s cases.

## Acceptance Criteria:
* All cases needing a Notice of Change of Address/Phone/Both get one
   * All open cases and any case closed for less than 6 months

## Notes:
* getDocketNumbersByUser is called when generating change of address
* these records are fairly small but could be a lot of them for some practitioners
* also includes closed cases in this response so this will get worse over time

## Tasks
- [x] create ES persistence method (Jojo / Eric ustaxcourt/ef-cms-flexion#6976)
- [x] substitute new method for old (Jojo / Eric ustaxcourt/ef-cms-flexion#6976)
- [x] seed script (Jojo / Eric)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the **prod** environment

**Comment by ericsorenson** [comment]
We'll need to replace 

```
  const docketNumbers = await applicationContext
    .getPersistenceGateway()
    .getDocketNumbersByUser({
      applicationContext,
      userId: user.userId,
    });
```

with an ES query to get only all open cases and any case closed for less than 6 months.

We'll need to demo with a realiztic number of cases. Jessica says _"Realistically, I wouldn't think an attorney would have more than 200 cases that fall into open and closed for less than 6 months, but this would mostly apply to IRS and I'm worried about  supervisor having more than that."_ She's going to get back to us with a specific number.
