### ISSUE TITLE
Additional Court users

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7448]
The Court has additional users that need to access the CMS. https://docs.google.com/spreadsheets/d/1Wo851jyGCYWGqooGyPrC0ogKMKl5s6IjesRSIC3A8i4/edit?usp=sharing

## Acceptance Criteria
**_Floater and Reporter's Office Roles_**
* "Floater" and "Reporter's Office" need to be listed as sections in the messaging drop-down
* Court-users need the ability to send messages to individuals with "Floater" and "Reporter's Office" roles
* Users with "Floater" role need to see their individual messages and those messages for others in the "Floater" section
* Users with "Reporter's Office" role need to see their individual messages and those messages for others in the "Reporter's Office" section
* These users can see the QC box of Docket
* Users with the Floater role have allInternalUserPermissions
* Users with the Reporter's Office role have allInternalUserPermissions

**_General Role_**
* A "general" role is needed for all remaining Court users
* The "general" role does not need to receive messages
* The "general" role can see the QC box of Docket
* The "general" role should have the allInternalUserPermissions, except those related to sending/receiving messages

## Notes
* Floaters, Reporters, and General should have the allInternalUserPermissions: 
  ROLE_PERMISSIONS.ADD_CASE_TO_TRIAL_SESSION,
  ROLE_PERMISSIONS.ADVANCED_SEARCH,
  ROLE_PERMISSIONS.ARCHIVE_DOCUMENT,
  ROLE_PERMISSIONS.ASSOCIATE_USER_WITH_CASE,
  ROLE_PERMISSIONS.BLOCK_CASE,
  ROLE_PERMISSIONS.CASE_DEADLINE,
  ROLE_PERMISSIONS.CASE_INVENTORY_REPORT,
  ROLE_PERMISSIONS.CASE_NOTES,
  ROLE_PERMISSIONS.CONSOLIDATE_CASES,
  ROLE_PERMISSIONS.COURT_ISSUED_DOCUMENT,
  ROLE_PERMISSIONS.GET_CASE,
  ROLE_PERMISSIONS.GET_JUDGES,
  ROLE_PERMISSIONS.GET_READ_MESSAGES,
  ROLE_PERMISSIONS.GET_USERS_IN_SECTION,
  ROLE_PERMISSIONS.MANAGE_PRACTITIONER_USERS,
  ROLE_PERMISSIONS.MESSAGES,
  ROLE_PERMISSIONS.PENDING_ITEMS,
  ROLE_PERMISSIONS.PRIORITIZE_CASE,
  ROLE_PERMISSIONS.TRIAL_SESSIONS,
  ROLE_PERMISSIONS.UPDATE_CASE,
  ROLE_PERMISSIONS.UPLOAD_DOCUMENT,
  ROLE_PERMISSIONS.VIEW_DOCUMENTS,
  ROLE_PERMISSIONS.VIEW_SEALED_CASE,
  ROLE_PERMISSIONS.WORKITEM,

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Add reportersOffice and general roles throughout the system - Rachael, Rae, Mrin ustaxcourt/ef-cms-flexion#7057
- [x] 2 Add seed data users for reportersOffice and general roles - Rachael, Rae, Mrin ustaxcourt/ef-cms-flexion#7057
- [x] 3 Add “Reporters Office” and “Floater” to sections and display them in the messaging drop-downs - Rachael, Rae, Mrin ustaxcourt/ef-cms-flexion#7058
- [x] 4 Hide messaging tab in header for General users - what should their homepage be? we need to also not call the endpoint that retrieves messages for users Rachael, Rae, Mrin ustaxcourt/ef-cms-flexion#7060

## Definition of Done (Updated 8-3-20)

**Product Owner**
 - [x]  Acceptance criteria have been met

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the stage environment

**Comment by mariahkannenberg** [comment]
ORIGINAL CONTENT FROM BUG

**Describe the Bug**
Court employees loaded into the system with role=floater are not showing as potential recipients on the messaging dropdown

**Business Impact/Reason for Severity**
Unable to send messages to a lot of court employees

**In which environment did you see this bug?**
Court's `test`

**Who were you logged in as?**
jessica.marine@ustaxcourt.gov

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
testing the application

**To Reproduce**
Steps to reproduce the behavior:
1. Log-in as a court user
2. Navigate to a case
3. Select Message from the Create dropdown
4. Click on "Section" -- Floater not listed

**Expected Behavior**
Court employees in Floater role should be on the messaging dropdown.

**Actual Behavior**
Floaters are not listed on the messaging dropdown.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7c8f3d34-8133-4da6-97e1-f8df464a99e1)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Cause of Bug, If Known**


**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by klohman** [comment]
### 6943 Test Scenarios 

#### 1) Internal users have option to send message to user in “Floater” section 
* Login as internal user 
* Go to Case 
* Click Create and Message 
* Select section 
* Select recipient 
Expected results 
- [x] “Floater” option displays in Section dropdown 
- [x] All users in Floater section display in Recipient dropdown when Floater section is selected 

#### 2) Floater user sees received messages for them in My Messages 
* Login as docket clerk 1 
* Send message to Angela Means (floater user)
* Login as Angela Means (ameans@example.com)
* View My Messages Inbox 
Expected results 
- [x] Message from docket clerk displays in My Messages Inbox for Angela Means 

#### 3) Floater user sees messages for all Floater users in Section Messages 
* Scenario 2
* Login as Karen Davis (Floater user) 
* View Section Messages Inbox 
Expected results 
- [x] Message from docket clerk to Angela Means displays in Section Messages Inbox for Floater section

#### 4) Floater users see the Docket Document QC Inbox 
* Login as Floater user 
* Click Document QC from global nav 
Expected results 
- [x] Docket Section Document QC Inbox items display 

#### 5) Floater users have general user permissions (allInternalUserPermissions)
* Login as Floater user 
* Go to a case 
* Check permissions (various) 
Expected results 
- [x] User has access to all permissions for allInternalUserPermissions

#### 6) Internal users can send message to user in “Reporters” section 
* Login as internal user 
* Go to Case 
* Click Create and Message 
* Select section 
* Select recipient 
Expected results 
- [x] “Reporters” option displays in Section dropdown 
- [x] All users in Reporters section display in Recipient dropdown when Floater section is selected 

#### 7) Users with Reporters section role can login to system
* Login as Matthew Madara 
Expected results 
- [x] User is able to successfully login to system 

#### 8) Reporter user sees messages for them in My Messages 
* Login as docket clerk 1 
* Send message to Matthew Madara
* Login as Matthew Madara 
* View My Messages Inbox 
Expected results 
- [x] Message from docket clerk displays in My Messages Inbox for Matthew Madara 

#### 9) Reporter user sees messages for all Floater users in Section Messages 
* Scenario 8
* Login as Thomas Silva 
* View Section Messages Inbox 
Expected results 
- [x] Message from docket clerk to Matthew Madara displays in Section Messages Inbox for Reporters section

#### 10) Reporter users see the Docket Document QC Inbox 
* Login as Reporter user 
* Click Document QC from global nav 
Expected results 
- [x] Docket Section Document QC Inbox items display 

#### 10) Reporter users have general user permissions (allInternalUserPermissions)
* Login as Reporter user 
* Go to a case 
* Check permissions (various) 
Expected results 
- [x] User has access to all permissions for allInternalUserPermissions

#### 11) Users with General role can login to system 
* Login as Greg Auth
Expected results 
- [x] User is able to successfully login to system 

#### 12) General users do not see a message inbox 
* Login as General user 
Expected results 
- [x] Messages option is hidden from global navigation 

#### 13) Internal users cannot send messages to user in General section 
* Login as docket clerk 
* Go to case 
* Click Create and Message 
* View Section dropdown options 
Expected results 
- [x] General is not an option in the Section dropdown

#### 14) General users see the Docket Document QC Inbox 
* Login as General user 
* Click Document QC from global nav 
Expected results 
- [x] Docket Section Document QC Inbox items display 

#### 15) General users have general user permissions (allInternalUserPermissions)
* Login as General user 
* Go to a case 
* Check permissions (various) 
Expected results 
- [x] User has access to all permissions for allInternalUserPermissions

**Comment by JessicaMarine** [comment]
The floater is working as expected. Unable to fully test "Reporter's Office" and "General" role because no users loaded into Flexion's prod w/ those roles.  I will move to done and when I test in Court's environment after next migration (early next week) we can address any issues I find
