### ISSUE TITLE
Guarantee that the court’s users don’t execute code that has not passed QA

### ISSUE THREAD

**Issue by ericsorenson** [ustaxcourt/ef-cms#7487]
## Pre-Conditions

None

## Acceptance Criteria

New code will be locked behind a conditional based on story-specific boolean values. When the value is false the code is not reachable, when the value is true the issue code can be executed by users.

## Mobile Design/Considerations

None

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

### Open Questions
- Do we make copies of every test impacted by the code changes? 
  - Does it make sense to create a mock data factory for tests?
- What if a data migration is required to complete the story?
- What if the story modifies dozens and dozens of files?

## Tasks

- [x] Entities need to come from a factory instead of an import to allow for toggles (refactoring task)
- [x] View templates need to come from a factory instead of an import to allow for toggles (refactoring task)
- [x] Reduce functional complexity for sane toggling (refactoring task)
- [x] Example of a toggle in a lambda
- [x] When does the toggle copy get deleted, after QA?
- [x] Consider adding any process-related toggle items to DOD

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by mariahkannenberg** [comment]
Gather a group of bug fixes to send in next PR
If any fixes, make patches to master branch
Make sure all issues solid before making a PR to court, as we work on feature toggle workflow.
