### ISSUE TITLE
Tech Lead: Allow switching the application into a maintenance mode without a deployment.

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#7493]
As the Court, in order properly maintain DAWSON, we need the ability to switch the application into a maintenance mode which prevents any changes to data.

If the application requires downtime, we need a way to prevent usage of the application during the downtime window. Because we may be performing edits to the underlaying data (for example, when restoring from a database backup), to ensure data integrity all edits to the site using the UI or API must be blocked. 

Entering maintenance mode cannot require a deployment, as it may be needed to be used before a deployment. 

## Pre-Conditions
 - ustaxcourt/ef-cms#7930, ustaxcourt/ef-cms#7931, ustaxcourt/ef-cms#7932, ustaxcourt/ef-cms-flexion#8507

## Acceptance Criteria
- The application can be set into (and out of) maintenance mode without a deployment. 
- Maintenance mode feature is not affected by deployments
- Users are not able to use the system when the system is in maintenance mode
- Users are notified that the system is in maintenance mode
- The maintenance message should point users to https://status.ustaxcourt.gov/ to see the latest updates.
- Users who have websockets blocked are able to access the system and file documents normally when maintenance mode is disengaged (NOTE: they cannot change their contact information as per https://github.com/flexion/ef-cms/issues/7959)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- No requirement that users don't lose data. Don't want partial data in the system. (per Chris)

## Tasks
- [x] UI for maintenance warning modal - mob ustaxcourt/ef-cms-flexion#8843 
- [x] UI for maintenance page - Rosie, Mrinalini ustaxcourt/ef-cms-flexion#8846
- [x] Implement cancel sequence of warning modal to redirect to maintenance page - Rosie, Rachel ustaxcourt/ef-cms-flexion#8849
- [x] Script for turning on maintenance mode flag - Rachael ustaxcourt/ef-cms-flexion#8844
- [x] Display App Maintenance Modal when maintenance mode is on and user is already logged in - Rachael/mob ustaxcourt/ef-cms-flexion#8848, ustaxcourt/ef-cms-flexion#8874
- [x] When maintenance mode is turned off navigate to home screen when a user is logged in - Mrinalini ustaxcourt/ef-cms-flexion#8851
- [x] Start a websocket connection for all users when logging in (and fix all the integration tests it breaks) ustaxcourt/ef-cms-flexion#8884
- [x] User is routed to maintenance page if they login and maintenance mode is engaged ustaxcourt/ef-cms-flexion#8890
- [x] User is routed to maintenance page if they try to visit a different route when maintenance mode is engaged ustaxcourt/ef-cms-flexion#8895
- [x] User is routed to maintenance page in public view ustaxcourt/ef-cms-flexion#8893
- [x] Route to maintenance page when maintenance mode is turned on ustaxcourt/ef-cms-flexion#8867
  - [x] When user goes to public pages (search, today's orders, today's opinions) - Mrinal ustaxcourt/ef-cms-flexion#8864
- [x] Try out the timed logout and see what happens - same as before, the warning modal pops up then logs out the user
- [x] Header and footer are hidden when we route back to the dashboard when maintenance mode is disengaged - mob ustaxcourt/ef-cms-flexion#8903
- [x] Check if deployed env has an issue with not reconnecting the websocket connection on reload of the page (not dashboard)
- [x] Add a decorator around routes to start a websocket connection on reload if !socket ustaxcourt/ef-cms-flexion#8905
- [x] Routing fixes so we route to maintenance page on reload ustaxcourt/ef-cms-flexion#8910
- [x] Integration test turning on maintenance mode and routing properly (possibly use `cy.exec` local engage script) ustaxcourt/ef-cms-flexion#8914
- [x] Disable API when maintenance mode is turned on ustaxcourt/ef-cms-flexion#8911
- [x] refresh to dashboard when mm disengaged while user is logged in

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
![Frame 9.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3b38a442-f336-4cb2-9598-8797152c4d1a)

## Tech leads sets system to maintenance mode 

#### User is logged in to DAWSON when maintenance mode begins 
* On next user action, display modal 
* On click of Log Out, user is logged out of app
* On click of Cancel, route to Maintenance Page 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7523d98e-f91c-499a-92cb-e8437f26be6f)

#### User logs in through Cognito during maintenance mode 
* User is routed to maintenance page 

#### User goes to public pages (search, today's orders, today's opinions) 
* User is routed to maintenance page 

#### User attempts to go to DAWSON page through direct URL 
* User is routed to maintenance page 

## Maintenance Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b8cfb46e-3ee6-46d5-8363-33fb88c5aac2)
* On click of View System Status button, route to https://status.ustaxcourt.gov/

## Tech lead ends maintenance mode 
#### User is currently logged in to DAWSON 
* App refreshes to user's home screen 

#### User logs in through Cognito during maintenance mode 
* User is routed to home screen

#### User goes to public pages (search, today's orders, today's opinions) 
* User is routed to public page

**Comment by klohman** [comment]
### 7095

#### 1) User is logged in to system and maintenance mode begins 
* Login as user 
* Set to maintenance mode 
Expected results 
On next user action 
- [x] Maintenance model displays 
On Click of Log out button 
- [x] User is logged out of system 
On click of Cancel button, 
- [x] User is routed to Maintenance page 

#### 2) User logs in to system during maintenance mode 
* Set to maintenance mode 
* Log in to DAWSON 
Expected results 
- [x] user is routed to maintenance page 

#### 3) User goes to public page during maintenance mode 
* Set to maintenance mode 
* Go to public page 
    * Case Search 
    * Today’s Opinions
    * Today’s Orders 
Expected results 
- [x] user is routed to maintenance page 

#### 4) User goes to DAWSON direct URL during maintenance mode 
* Set to maintenance mode 
* Go to direct URL 
Expected results 
If authenticated:
- [x] user is routed to maintenance page 
If not authenticated 
- [x] user is routed to log in screen 

#### 5) User is logged in to system when maintenance mode ends 
* Login as user 
* Set to maintenance mode 
* End maintenance mode 
Expected results 
- [x] App refreshes and home screen displays 

#### 6) User logs in to system after maintenance mode ends 
* Set to maintenance mode 
* End maintenance mode 
* Login as user 
Expected results 
- [x] Home screen displays 

#### 7) User goes to public page during maintenance mode 
* Set to maintenance mode  End maintenance mode
* Go to public page 
    * Case Search 
    * Today’s Opinions
    * Today’s Orders 
Expected results 
- [x] public page displays 

#### 8) User goes to DAWSON directly URL during maintenance mode 
* Set to maintenance mode 
* End maintenance mode
* Go to direct URL 
Expected results 
If authenticated:
- [x] user is routed to page 
If not authenticated 
- [x] user is routed to log in screen

**Comment by mariahkannenberg** [comment]
Pulling out this AC and moving it to it's own story. Will ref the new story.

- _Court tech lead can permit certain users to access the system while in maintenance mode_

**Comment by ttlenard** [comment]
@mmarcotte will be reaching out to the IRS today (9/13/21) to schedule some testing in the IRS Test environment to ensure that the IRS environment isn't affected.

**Comment by mmarcotte** [comment]
We need to discuss the next steps we need to take here. As feared, the IRS cannot log into DAWSON. They are presented with an error, the same error as https://github.com/flexion/ef-cms/issues/7959

**Comment by cholly75** [comment]
Moved back to In Progress to address defect (IRS issue).

**Comment by mmarcotte** [comment]
This breaks for all IRS Practitioners. When the system is not in maintenance mode, IRS Practitioners cannot log into DAWSON and perform any function. Effectively, this disables DAWSON for IRS Practitioners. Their browsers are configured to block WebSockets requests. 

It would seem that we might be able to catch the Network Error that is currently occurring upon logging in that establishes the WebSocket connection, and then allow the application to continue functioning without it. We can just ignore the error if it's being made to the websocket endpoint.

Important note -- this is not getting maintenance mode to work for users without websockets; this is ensuring the application continues to work for all users when the the application is not in maintenance mode.

@ericsorenson [identified a helpful tool with Firefox](https://ustaxcourt.slack.com/archives/CD4PNKEPK/p1631628722085100) that I used to mimic the behavior that the IRS is observing. We should use this method to construct a fix before we test again with the IRS.
