### ISSUE TITLE
Docket Clerk: Select party/parties to be served

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7500]
As a Docket Clerk, in order to make sure that I serve the correct parties, I need to select the parties to be served eFiled, Paper Filed, and Court-issued documents.

## Acceptance Criteria
* Docket Clerk can select none, one or more parties to be served when adding a **paper filed document** to the docket record
   * If the party receives electronic service, a service email should be initiated
   * If the party receives paper service, the paper service should generate for the Docket Clerk
* ~~Docket Clerk can select none, one or more parties to be served when adding a **Court-issued document** to the docket record.~~
   * ~~If the party receives electronic service, a service email should be initiated~~
   * ~~If the party receives paper service, the paper service should generate for the Docket Clerk~~
* The served party (R, P, or B) and date of service should display on the docket entry based on the Docket Clerk's selection.
* For "unserveable" Court-issued documents, no selection for service is needed
* For all Court-issued documents, all parties are always served

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Show message when isUnservable (Joshua ustaxcourt/ef-cms-flexion#8947)
- [ ] Ensure correct served parties code is set for a paper filed document (Matt + Joshua)
- [ ] Do not serve filing party

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
UX Research Questions 
* Tell us about how your process (current and legacy) to serve individual parties. 
* How often do you need to serve this happen? 
* What determines who should be served?
* Is there added risk in only serving individual parties? 
* What happens if you make a mistake? Do you ever need to go back and serve another party?

**Comment by cholly75** [comment]
@klohman - Use cases for choosing "none": return mail and trial minutes are both docket additions that should not be served when filed.

**Comment by klohman** [comment]
@cholly75 Returned Mail (RM) and Trial minutes (I believe those codes are TRL, PTRL, etc.) are flagged as isUnservable, so no one is served already. Do you want to chat and (if needed) update the AC for this story together? cc. @mariahkannenberg

**Comment by klohman** [comment]
## Add Paper Filing - No UI Change

**On Save and Serve**
All parties other than the filing party are served
Filing party or parties are not served  
Docket entry reflects served date and the parties served 
P - if only petitioner, intervenor, participant, or counsel was served 
R - if respondent only was served 
B -if both any petitioner, ntervenor, participant, or counsel AND respondent were served 

**Jointly filed documents**
if all parties file a document, no service is initiated 
no served stamp is applied to the document 
docket record does not display a served date or served party and does not display “Not served” message

## Add Docket Entry (Court-Issued Document) - No Change

**Service Parties**
* no change 
* all parties are served for all court-issued documents

## Add Docket Entry (Court-Issued Document - isUnservable)

For any court-issued event code with isUnservable 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2b6fca78-3a8f-4371-ab79-aca86ef0a8f7)

**Service Parties**
Display message “This document type does not require service”

**On Save**
No change to current functionality

**Comment by klohman** [comment]
## Tests

#### 1) Docket clerk adds paper-filing and non-filing parties have all electronic service 
* Login as docket clerk 
* Go to case 
    * Case has at least 2 petitioners 
        * petitioner1
        * petitioner2
* All parties on case have electronic service 
* Click Add Paper Filing 
* Select filing party = petitioner1, petitioner2
* Save and Serve
Expected results 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = R
- [ ] Respondent receives service email 
- [ ] petitioner1 does not receive service email 
- [ ] petitioner2 does not receive service email 

#### 2) Docket clerk adds paper-filing and non-filing parties have all paper service  
* Login as docket clerk 
* Go to case 
    * Case has at least 2 petitioners 
        * petitioner1 - paper service
        * petitioner2 - paper service 
    * Case has at least 1 respondent counsel - electronic service
* Click Add Paper Filing 
* Select filing party = respondent
* Save and Serve
Expected results 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = P
- [ ] Respondent does not receive service email 
- [ ] App routes to Print Paper Service screen with document PDF 
- [ ] PDF contains address sheets for petitioner1 and petitioner2 

#### 3) Docket clerk adds paper-filing and non-filing parties have both electronic and paper service   
* Login as docket clerk 
* Go to case 
    * Case has at least 2 petitioners 
        * petitioner1 - paper service
        * petitioner2 - electronic service 
    * Case has at least 1 respondent counsel - electronic service
* Click Add Paper Filing 
* Select filing party = respondent
* Save and Serve
Expected results 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = P
- [ ] Respondent does not receive service email 
- [ ] Petitioner2 receives service email 
- [ ] App routes to Print Paper Service screen with document PDF 
- [ ] PDF contains address sheets for petitioner1

#### 4) Docket clerk adds paper-filing and non-filing parties include intervenor/participants 
* Login as docket clerk 
* Go to case 
    * Case has petitioner1 - electronic service
    * Case has intervenor - electronic service 
    * Case has participant - paper service 
* Click Add Paper Filing 
* Select filing party = petitioner1, respondent 
* Save and Serve 
Expected results 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = P
- [ ] Respondent does not receive service email 
- [ ] Petitioner1 does not receive service email 
- [ ] Intervenor receives service email   
- [ ] App routes to Print Paper Service screen with document PDF 
- [ ] PDF contains address sheets for participant

#### 5) Docket clerk adds paper-filing and non-filing party is respondent with multiple respondent counsel
* Login as docket clerk 
* Go to case 
    * Case has multiple respondent counsel
        * respondent1- electronic service 
        * respondent2 - electronic service 
* Click Add Paper Filing 
* Select Filing party = petitioner 
* Save and Serve 
Expected results 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = R
- [ ] Petitioner does not receive service 
- [ ] respondent1 receives service email 
- [ ] respondent2 receives service email 

#### 6) Docket clerk adds paper-filing jointly  filed by all parties 
* Go to case 
    * Case has petitioner1 - electronic service
    * Case has intervenor - electronic service 
    * Case has participant - paper service 
    * Case has respondent counsel
* Click Add Paper Filing 
* Select filing party = all parties 
* Save and Serve 
Expected results 
- [ ] Document is added to the docket record with Served date = [blank] and Parties = [blank] 
- [ ] Docket entry does not display “Not Served” message
- [ ] Coversheet does not display a Served stamp
- [ ] Respondent does not receive service email 
- [ ] Petitioner1 does not receive service email 
- [ ] Intervenor does not receive service email   
- [ ] App does not routes to Print Paper Service screen with document PDF 

#### 7) Docket clerk adds and serves court-issued document 
* Login as docket clerk 
* Go to case 
    * Case has multiple petitioners
    * Case has multiple respondent counsel
        * respondent1- electronic service 
        * respondent2 - electronic service 
* Create, sign and add docket entry for Order 
* Save and Serve 
Expected results 
- [ ] All parties receive service 
- [ ] Document is added to the docket record with Served date = [current date] and Parties = B

#### 8) Docket clerk adds court-issued document that is unservable 
* Login as docket clerk 
* Go to case 
* Upload PDF, Add Docket Entry 
* Select document type = U.S.C.A.
* Save Entry 
Expected results 
On select of document type USCA
- [ ] Service parties field displays message “This document does not require service.”
On Save 
- [ ] Document is added to the docket record with Served date and Parties columns blank

**Comment by matthopson** [comment]
@klohman I think I know the answer to this, but just want to be clear.... In a scenario like where a Petitioner is filing a document, they would not be served - but I _assume_ the intent is to show a P (even though they weren't served, they were the only party that _would_ be served if they weren't the filing party). 🥴

**Comment by JessicaMarine** [comment]
@matthopson No.  If P files a document, then they wouldn't be served.  So, the served party would be R (or blank if nobody is served).

**Comment by matthopson** [comment]
@JessicaMarine  Thanks!

**Comment by mariahkannenberg** [comment]
Was in progress. Diverted to a bug. Move to batch 10. Matt can revert the change. 
Anyone who picks up this story can talk to Matt about what he found. This is a "sticky" story - and has some assumptions.

**Comment by mariahkannenberg** [comment]
7119 was started by Matt and then put on ice to work on a critical bug. He reverted code chagnes out of batch 9 on staging. Whoever picks this story up, can chat w/Matt about some of the challenges he encountered.
