### ISSUE TITLE
Hearing Date for Case Set for Trial

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7501]
As the court, so we can manage hearings for a case, we need the ability to add a case to a hearing, as well as a trial session.

## Pre-Conditions
* Case is already calendared on another session

## Acceptance Criteria
* The Court needs the ability to add a case to one or more additional sessions.
* When manually adding a case to a session, the Docket Clerk can add a note about why a case is being added to a session.
   * That note should be optional for the first session and required for subsequent sessions.
   * The note should display on the trial-session-detail and working-copy of the session w/ the case.
~~* A trial session can be created (calendar cut) without any cases~~

## Notes
* All logic is the same for second session as first
* Only can be added to an open trial session, so that no automated notices get generated
* Same logic for removing a case from the second session as it would for the first

## Security Considerations
 - [ ] This work make you nervous about privacy or security?
 - [ ] This work make major changes to the system?
 - [ ] This work implement new authentication or security controls?
 - [ ] This work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Feature Branch
- `7120-feature-branch-hearings`

## Tasks
- Entities
  - [x] ~Create CaseHearing entity - TrialSession + association meta (date added, note). We can store this as our mapping record (pk: case|, sk: hearing|)~ ---- Alternatively, just store the date on the trialSession.caseOrder array (but then we have to fetch it and associate them with the hearings array) **(Matt ustaxcourt/ef-cms-flexion#7315)**
  - [x] Add hearings array to Case **(Matt ustaxcourt/ef-cms-flexion#7285)**
- Backend / Persistence
  - [x] Interactor / dynamo methods for saving hearing (trial session) **(Jojo, ustaxcourt/ef-cms-flexion#7282)**
  - [x] Fetch hearings and associate with case **(Matt ustaxcourt/ef-cms-flexion#7290)**
- UI
  - Add Trial Session (Comorae Mob, ustaxcourt/ef-cms-flexion#7276)
    - [x] Add note field
    - [x] Note is OPTIONAL for FIRST trial session being associated with the case
  - Add Hearing Modal (variant of Add Trial Session Modal) **(Jojo, ustaxcourt/ef-cms-flexion#7282)**
    - [x] Note is required (assuming this is the second session being added)
    - [x] Trial Session dropdown
      - [x] If Requested city only is selected, display sessions for preferred trial location 
      - [x] If all locations is selected, display sessions for all cities 
      - [x] Display “Open” trial sessions only (filter out any sessions that are “New”)
    - [x] Add Note
      - [x] Field is required
      - [x] Error message if blank “Add a note. ” 
      - [x] Max character count 200
    - [x] On Submit
      - [x] Modal closes and success message displays
      - [x] Success message: “Case set for hearing.”
      - [x] Case is added to selected trial session 
      - [x] Case status remains “Calendared” and associated judge remains with the trial judge for the first session
  - Case Overview
    - [x] Add “Set for Hearing” button **(Matt / JoJo, ustaxcourt/ef-cms-flexion#7282)**
      - [x] Display ONLY when case status === Calendared
      - [x] On click, display “Set for Hearing” modal
      - [x] No limit on how many sessions can be added
    - [x] Trial Info Card
      - [x] Implement table layout for trial sessions **(Matt ustaxcourt/ef-cms-flexion#7280)**
      - [x] Format hearing info for display **(Matt ustaxcourt/ef-cms-flexion#7308)**
      - [x] Display note for trial session in sessions table **(Matt ustaxcourt/ef-cms-flexion#7309)**
      - [x] Display hearing note in sessions table ~(needs note from CaseHearing entity task above)~ **(Matt ustaxcourt/ef-cms-flexion#7309)**
      - [x] Display Order: First trial session, subsequent hearings as they’re added (needs date from CaseHearing entity task above) **(Matt ustaxcourt/ef-cms-flexion#7315)**
      - [x] Determine if user is associated with hearing and display working copy link **(Matt ustaxcourt/ef-cms-flexion#7310)**
  - Trial Session Detail (Mraedychael mob) ustaxcourt/ef-cms-flexion#7279
      - [x] Add “Calendar Notes” column to case list — only open cases list
      - [x] Display Note from Add Trial Session form in Calendared Notes column
  - Trial Session Working Copy (Mraedychael mob) ustaxcourt/ef-cms-flexion#7281
      - [x] Display Calendared Note above Judges Note
      - [x] Calendar note should always be displayed (whether there is a judge's note added or not)
  - Printable Trial Detail (Mraedychael mob) ustaxcourt/ef-cms-flexion#7283
      - [x] Display note field in new column for Calendar Notes
  - Remove from Trial Session Modal **(Jojo, ustaxcourt/ef-cms-flexion#7303)**
    - [x] Disposition is required
    - [x] Case Status field is required
      - Omit statuses `New` and `Calendared` from the dropdown
      - ~If it's the last Trial Session, populate with `General Docket, Ready for Trial`~
    - [x] Associated Judge field (required, dependent on case status)
      - Required for statuses: `Assigned-Case`, `Assigned-Motion`, `CAV`, `Jurisdiction Retained`, `Rule 155`, `Submitted`
  - Hearings Card
    - [x] Create Hearings card component **(Matt ustaxcourt/ef-cms-flexion#7325)**
    - [x] Separate out current hearings from Trial Session card **(Matt ustaxcourt/ef-cms-flexion#7325)**
 - [x] BUG: Shouldn't be able to add duplicate same trial session as a hearing **(Jojo ustaxcourt/ef-cms-flexion#7330)**
 - [x] BUG: Not showing hearings after removing the first trial session **(Matt ustaxcourt/ef-cms-flexion#7325)**
 - [x] Fix: Be able to Set for Hearing regardless of Case Status **(Jojo ustaxcourt/ef-cms-flexion#7330)**
 - [x] BUG: Add case to `caseOrder` for hearing (Trial Session) **(Matt ustaxcourt/ef-cms-flexion#7333)**
 - [x] BUG: Removing hearing removes case's trial session **(Jojo ustaxcourt/ef-cms-flexion#7336)**
 - [x] BUG: Current hearings should not show in add trial session dropdown **(Matt ustaxcourt/ef-cms-flexion#7349)**
 - **Review 12/14/2020 [[see comment](https://github.com/flexion/ef-cms/issues/7120#issuecomment-744757227)]**
   - [x] When manually adding case to trial session (either New or Open) - the note is not displaying on the Trial Info card (Matt, ustaxcourt/ef-cms-flexion#7344)
   - [x] "High Priority" case remove the "Remove" link in the table (causing error) and just keep the "Remove High Priority" link (which is working as expected) (Matt ustaxcourt/ef-cms-flexion#7344)
   - [x] Set for Hearing modal - trial session dropdowns should only display Open trial sessions. I am seeing a New trial session (that has not been set) listed in the dropdown (Jojo ustaxcourt/ef-cms-flexion#7346)
   - [x] For case that is set for trial and for hearing, when removing from the trial session, the case status dropdown isn't updating with the selected option and is always updating to General Docket - At Issue. (Rachael ustaxcourt/ef-cms-flexion#7345)

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env
**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Code toggle has been implemented (“On” for items that are QA’d)
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Add to Trial Session modal 

**Add note field**
* Add “Add note” field as optional 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f1610751-efda-421e-af3e-a4ddd89a7f6e)


## Trial Information Updates - 

### Calendared 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/513775cc-aa2d-4e2e-977e-78616cdb973b)

**Set for Hearing button**
* Displayed only when case is in status = Calendared 
* On click, display Set for Hearing modal 

**Add to Trial Session - Note**
* Note entered on Add to Trial Session modal displays below place of trial 

### Scheduled 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6df0ab8d-35b3-4733-8466-774274595ba7)
* Update UI to table design 

### High Priority 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2efecffd-c572-4726-9842-da0b0196288b)
* Update UI to table design 
* Note in table = "Reason for high priority" field 


## Set for Hearing modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5e4cbe83-8f8d-43f6-a5ad-921636b45b06)

**Select trial session dropdown**
* If Requested city only is selected, display sessions for preferred trial location 
* If all locations is selected, display sessions for all cities 
* Display “Open” trial sessions only (filter out any sessions that are “New”) 

**Add note**
* Field is required 
* Error message if blank “Add a note. ” 
* Max character count 200

#### On click of Add Case button 
* Modal closes and success message displays
* Success message: “Case set for hearing.”
* Case is added to selected trial session 
* Case status remains “Calendared” and associated judge remains with the trial judge for the first session 

## Trial Information - Case is on multiple trial sessions 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d48ade65-d104-4e60-b273-ea89ac6a71e8)


* Each subsequent trial session is listed in the order they were added 
* Note added on “Add to Hearing modal”  is displayed below the place of trial in the same table row    

**Remove button** 
* On click, confirmation modal displays - once confirmed, case is removed from selected trial session 
* When case is removed from all trial sessions, case status reverts back to previous status before “Calendared” and judge is updated 

**Set for Hearing button**
* No limit on how many sessions case can be added to 

## Trial Session Detail - New 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3b9099c0-25c3-4325-989d-65ab57680a36)

* Display note field in new column for Calendar Notes

## Trial Session Detail - Open 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3ccf6734-a76c-4397-9168-3ca748e90f50)
* Display note field in new column for Calendar Notes

## Working Copy 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1046fa50-89fc-43a5-8c3b-d37757d32c82)

* Display Calendar note above judge's note
* Calendar note should always be displayed (whether there is a judge's note added or not)

## Printable Trial Detail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/93b3e4e6-b078-41ba-94d0-a0f1eff985d5)

* Display note field in new column for Calendar Notes

**Comment by klohman** [comment]
#### 7120 Test Scenarios (Updated)

#### 1) Docket clerk enters note when manually adding a case to an Open trial session 
* Login as docket clerk 
* Go to case 
    * Case status = general docket at issue 
* Click Add to Trial 
* Select trial session 
    * Trial sessions is “Open” 
* Enter note 
* Click Add Case 
Expected results 
- [x] Trial info card displays updated table design 
- [x] Trial info card displays “Note” entered in modal 

#### 2) Docket clerk enters note when manually adding a case to an New trial session 
* Login as docket clerk 
* Go to case 
    * Case status = general docket at issue 
* Click Add to Trial 
* Select trial session 
    * Session is “New” 
* Enter note 
* Click Add Case 
Expected results 
- [x] Trial info card displays updated table design 
- [x] Trial info card displays “Note” entered in modal 

#### 3) Internal user views note added when case is manually added to Open 
trial session
* Scenario 1 
* Click Place of trial link from Trial Info 
* View case on Trial Session Detail 
Expected results 
- [x] Manually added case displays in Trial Session case list with calendar-plus 
- [x] Case list displays “Calendar Note” column 
- [x] Note entered in Scenario 1 displays in Calendar Note column for manually added case  

#### 4) Internal user views note added when case is manually added (scheduled) to New trial session
* Scenario 2 
* Click Place of trial link from Trial Info 
* View case on Trial Session Detail 
Expected results 
- [x] Manually added case displays in Trial Session case list with calendar-plus 
- [x] Case list displays “Calendar Note” column 
- [x] Note entered in Scenario 2 displays in Calendar Note column for manually added case  

#### 5) Docket clerk sees option to set for hearing regardless of case and trial status 
* Login as docket clerk 
* Go to case with status = Calendared 
* Go to case with status = General Docket Not at Issue that is “Scheduled” for trial
* Go to case with status = General Docket Not at Issue that is “High Priority” for trial
* Go to case with status = General Docket Not at Issue that is “Blocked” from trial
* Click Case Information tab 
Expected results 
- [x] Set for Hearing button displays 


#### 6) Docket clerk sets Calendared case for hearing 
* Login as docket clerk 
* Go to case 
    * Status = Calendared 
    * Judge = Buch
* Click Case Information tab 
* Click Set for Hearing 
* Select trial session 
* Enter note 
* Click Add Case 
Expected results 
On click of Set for Hearing button 
- [x] Set for Hearing modal displays 
- [x] Trial location dropdown displays only Open trial sessions 
On click of Add Case button. 
- [x] Modal closes and success message displays 
- [x] Hearing info card displays second trial session information in table 
- [x] Case status does not change 
- [x] Associated judge does not change 
- [x] Set for Hearing button displays 
- [x] Case is added to trial session selected for hearing 
- [x] Case remains on trial session it was Calendared for


### 7) Docket clerk sets Scheduled case for hearing 
* Login as docket clerk 
* Go to case 
    * Status = general docket 
    * Trial - Scheduled  
* Click Case Information tab 
* Click Set for Hearing 
* Select trial session 
* Enter note 
* Click Add Case 
Expected results 
On click of Set for Hearing button 
- [x] Set for Hearing modal displays 
- [x] Trial location dropdown displays only Open trial sessions 
On click of Add Case button. 
- [x] Modal closes and success message displays 
- [x] Hearing info card displays second trial session information in table 
- [x] Case status does not change 
- [x] Associated judge does not change 
- [x] Set for Hearing button displays 
- [x] Case is added to trial session selected for hearing 
- [x] Case remains on trial session it was Scheduled for

### 8) Docket clerk sets High Priority case for hearing 
* Login as docket clerk 
* Go to case 
    * Status = general docket 
    * Trial - Marked High Priority  
* Click Case Information tab 
* Click Set for Hearing 
* Select trial session 
* Enter note 
* Click Add Case 
Expected results 
On click of Set for Hearing button 
- [x] Set for Hearing modal displays 
- [x] Trial location dropdown displays only Open trial sessions 
On click of Add Case button. 
- [x] Modal closes and success message displays 
- [x] Hearing info card displays second trial session information in table 
- [x] Case status does not change 
- [x] Associated judge does not change 
- [x] Set for Hearing button displays 
- [x] Case is added to trial session selected for hearing 
- [x] Case remains on eligible list for next trial session in preferred city (as high priority)

### 9) Docket clerk sets Blocked case for hearing 
* Login as docket clerk 
* Go to case 
    * Status = general docket 
    * Trial - Blocked  
* Click Case Information tab 
* Click Set for Hearing 
* Select trial session 
* Enter note 
* Click Add Case 
Expected results 
On click of Set for Hearing button 
- [x] Set for Hearing modal displays 
- [x] Trial location dropdown displays only Open trial sessions 
On click of Add Case button. 
- [x] Modal closes and success message displays 
- [x] Hearing info card displays second trial session information in table 
- [x] Case status does not change 
- [x] Associated judge does not change 
- [x] Set for Hearing button displays 
- [x] Case is added to trial session selected for hearing 
- [x] Case remains blocked, will not show on any eligible lists

#### 10) Internal user views case set for hearing on Trial Session Detail 
* Scenario  9
* Click on Place of trial link for hearing
Expected results 
- [x] App routes to Trial Session Detail
- [x] Manually added case displays in Trial Session case list with calendar-plus 
- [x] Note entered in Scenario 9 displays in Calendar Note column for manually added case  

#### 11) Judge/chambers/trial clerk views case added to second trial session on Working Copy 
* Login as Judge Buch 
* Go to trial session (scenario 9) 
Expected results 
- [x] App routes to Working Copy of trial session 
- [x] Manually added case displays in Trial Session case list with calendar-plus 
- [x] Note entered in Scenario 9 displays in Calendar Note column for manually added case  

#### 12) Internal user views case added to second trial session on Printable Trial Session 
* Scenario 9 
* Click Place of trial link for second session 
* Click Print 
Expected results 
- [x] Note entered in Scenario 7 displays in Calendar Note column for manually added case on PDF 

#### 13) Docket clerk removes case from hearing
* Scenario 9
* Click “Remove” link for hearing 
* Enter disposition 
* Click Remove case 
Expected results 
On click of Remove case button in modal: 
- [x] Second session row is removed from Trial info table 
- [x] Case status does not change 
- [x] Associated judge does not change 
- [x] Set for Hearing button is displayed 
- [x] Case is removed from trial session selected for hearing 
- [x] Case remains blocked, will not show on any eligible lists

#### 13) Docket clerk removes case from Calendared trial session while it is also set for hearing without updating case status
* Login as docket clerk 
* Go to case
    * Case status - General Docket at issue ready for trial
* Add to first trial session
* Add to hearing 
* Click Remove link for trial session 
* Enter disposition
* Click Remove button on modal 
Expected results: 
On click of “Remove” Link 
-  [x] Modal displays case status populated with “General Docket at Issue - Ready for Trial” 
On click of Remove button on modal 
- [x] modal closes and success message displays 
- [x] trial session row is removed 
- [x] Hearing information still displays   
- [x] Case is still on Open cases list for hearing 
- [x] Case status updates to General Docket At Issue ready for trial
- [x] Associated judge updates to Chief Judge 

#### 14) Docket clerk removes case from Calendared trial session while it is also set for hearing and updates case status
* Login as docket clerk 
* Go to case
    * Case status - General Docket not at issue
* Add to trial session
* Add to hearing
* Click Remove link for  trial session 
* Enter disposition
* Update case status to “Jurisdiction Retained”
* Enter “Judge Buch” as associated judge
* Click Remove button on modal 
Expected results: 
On click of “Remove” Link 
-  [x] Modal displays case status is initially populated with “General Docket Not at Issue” 
On click of Remove button on modal 
- [x] modal closes and success message displays 
- [x] trial session is removed 
- [x] Hearing info is still displayed  
- [x] Case is still on Open cases list for second trial session 
- [ ] Case status updates to Jurisdiction Retained 
- [ ] Associated judge updates to Judge Buch 
 
#### 15) Docket clerk cannot add a case for hearing to the same trial session it is Calendared for 
* Login as docket clerk 
* Go to case
    * Case status - General Docket not at issue
* Add to trial session 
* Click Set for Hearing 
* Select same session the case is Calendared for 
Expected results 
- [x] ~~error message displays “Case is calendared for this session. Select another session.”~~ trial session that is Calendared is filtered out of list

**Comment by klohman** [comment]
## Updated Design 

### Remove from Trial Session Modal

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/25e09da3-6c40-42fa-9cb9-1aec441fd54e)

* add Case status field (required)
* Case status field should populate with the previous status (that the case would revert to after being removed from session) 
* Add "Associated judge" field (required dependent on case status)

**Comment by klohman** [comment]
Updated design 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/df600187-e3da-42ec-877a-7f6fc54b38f4)

**Comment by klohman** [comment]
### UX Notes (local) 
- [ ] When manually adding case to trial session (either New or Open) - the note is not displaying on the Trial Info card (Rae)
![Screen Shot 2020-12-14 at 4.26.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/37ff01ad-4667-472b-b9b2-9f2f944654ef)

- [ ] "High Priority" case remove the "Remove" link in the table (causing error) and just keep the "Remove High Priority" link (which is working as expected) 

![Screen Shot 2020-12-14 at 4.30.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f439a624-6cff-48e8-b480-851a5d23325c)

- [ ] Set for Hearing modal - trial session dropdowns should only display Open trial sessions. I am seeing a New trial session (that has not been set) listed in the dropdown ![Screen Shot 2020-12-14 at 4.37.37 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dfbec7e9-b583-4f8f-a204-2442311cc786)

- [ ] For case that is set for trial and for hearing, when removing from the trial session, the case status dropdown isn't updating with the selected option and is always updating to General Docket - At Issue. - Rachael
