### ISSUE TITLE
Docket Clerk: Ability to mark something as pending after it’s been processed

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7517]
As a Docket Clerk, in order to make sure everything is being tracked that the Court wants tracked, we need the ability to mark something as pending after it's been processed.  

## Pre-Conditions
* Document has already been filed/processed and is on the docket record

## Acceptance Criteria
* Docket clerk can mark something as pending after it's been processed 
* After the item is marked as pending it has all the same logic as any other pending item:
   * It shows up on pending tab in the case
   * It shows up on the pending report of the associated judge
   * It blocks a case from being eligible for trial 
   * It can be removed as pending

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* This is especially important to have for migrated data -- not all the pending items came across as pending

## Tasks
- [x] Add UI for setting a docket entry as pending - Rachael, Rae, Mrin. ustaxcourt/ef-cms-flexion#7187
- [x] Wire up UI to associated sequence/actions/interactor - Rachael, Rae, Mrin. ustaxcourt/ef-cms-flexion#7187

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
### Edit Docket Entry screen 

* Add "Track document?" field below the last field on the Document Info tab 
* "Track document" field should be displayed for all document entry types (externally filed, court-issued, system-generated) 
* "Track document" field does not need to be displayed for minute entries

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8e77a054-183a-4911-b2e6-f3506d34e6a1)

**Comment by klohman** [comment]
#### 7178 Test Scenarios 

#### 1) Docket clerk marks externally-filed document as “pending” after QC 
* Login as docket clerk 
* Go to case 
* Click “edit” link on docket entry for externally filed document 
* Check the “Add to Pending Report” checkbox 
* Save 
Expected results 
- [x] “Track document” field is displayed on Edit Docket Entry screen 
- [x] Case displays “Blocked” label in header 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge 
- [x] Case displays as “Blocked from Trial” with “pending item listed as the reason for automatic block 

#### 2) Docket clerk marks court-issued document as “pending” after saving to docket record 
* Login as docket clerk 
* Go to case 
* Click “edit” link on docket entry for a court-issued document
* Check the “Add to Pending Report” checkbox 
* Save 
Expected results 
- [x] “Track document” field is displayed on Edit Docket Entry screen =
- [x] Case displays “Blocked” label in header 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge 
- [x] Case displays as “Blocked from Trial” with “pending item listed as the reason for automatic block 

#### 3) Docket clerk cannot mark minute entry as “pending” 
* Login as docket clerk 
* Go to case 
* Click “edit for Minute Entry 
Expected results 
- [x] “Track document” field is hidden on Edit Docket Entry screen 

#### 4) Docket clerk marks document as “pending” for case with “Calendared” status 
* Login as docket clerk 
* Go to case with status “Calendared” 
* Click “edit” link on docket entry for externally filed document 
* Check the “Add to Pending Report” checkbox 
* Save 
Expected results 
- [x] “Track document” field is displayed on Edit Docket Entry screen 
- [x] Case status remains Calendared
- [x] Case remains on trial session
- [x] Case does not display “Blocked” label 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge  

#### 5) Docket clerk marks document as “pending” for case with “Calendared” status and removes case from trial session 
* Scenario 4 
* Go to Case Detail > Case Information > Trial information 
* Remove case from trial session 
Expected results 
- [x] Case status reverts to it’s previous status (before being Calendared) 
- [x] Case displays “Blocked” label in header 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge 
- [x] Case displays as “Blocked from Trial” with “pending item” listed as the reason for automatic block 

#### 6) Docket clerk marks document as “pending” for case with “High Priority” flag 
* Login as docket clerk 
* Go to case (case status General Docket - At Issue; case is marked High Priority) 
* Click “edit” link on docket entry for externally filed document 
* Check the “Add to Pending Report” checkbox 
* Save 
Expected results 
- [x] Case status remains General Docket - At Issue 
- [x] Trial Information card displays “High Priority” 
- [x] Case remains eligible for next trial session in the preferred trial city
- [x] Case does not display “Blocked” label 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge  

#### 7) Docket clerk marks document as “pending” for case with “High Priority” status and removes “High Priority” flag 
* Scenario 6 
* Go to Case Detail > Case Information > Trial information 
* Remove high priority from case
Expected results 
- [x] Case status remains General Docket - At Issue 
- [x] Case displays “Blocked” label in header 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge 
- [x] Case displays as “Blocked from Trial” with “pending item” listed as the reason for automatic block 

#### 8) Docket clerk marks document as “pending” for case “Scheduled” for trial session 
* Login as docket clerk 
* Go to case (case status “General Docket : At Issue; Case is scheduled for trial session that has not been set) 
* Click “edit” link on docket entry for externally filed document 
* Check the “Add to Pending Report” checkbox 
* Save 
Expected results 
- [x] Case status remains General Docket: At Issue
- [x] Case remains on trial session eligible list 
- [x] Case does not display “Blocked” label 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge  

#### 9) Docket clerk marks document as “pending” for case “Scheduled” for trial session and removes case from trial session
* Scenario 8 
* Go to Case Detail > Case Information > Trial information 
* Remove case from trial session 
Expected results 
- [x] Case status remains General Docket - At Issue 
- [x] Case displays “Blocked” label in header 
- [x] Document displays in Tracked Items > Pending Report tab on Case Detail 
- [x] Case displays in Pending Report for associated judge 
- [x] Case displays as “Blocked from Trial” with “pending item” listed as the reason for automatic block

**Comment by klohman** [comment]
High Priority tests aren't working as expected: 

- i set case as high priority 
- i then marked a processed docket entry as pending  
it still shows High priority , but also shows as blocked and the case doesn't show in the eligible list anymore 

![Screen Shot 2020-12-02 at 2.45.44 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/213cf244-7820-4588-8328-7b92f863838f)
