### ISSUE TITLE
Court: Pending Items w/ Legacy Served not showing in UI

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7524]
As the Court, in order to make sure all pending items are showing correctly in the UI, pending items with "legacy served" need to display.

11108-20 is an example.

## Acceptance Criteria
* Pending items with "legacy served" need to display in the UI and have all the same logic as other pending items:
   * Show up as pending under Tracked Items in the case
   * Show up on a judge's pending report
   * Prevent (block) a case from being eligible for trial
   * Be able to be removed as pending

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Check for isLegacyServed when determining pending items - Rachael, Rae, Mrin ustaxcourt/ef-cms-flexion#7210
- [x] Migration script to block migrated cases with isLegacyServed pending items  - Rachael, Rae, Mrin - ustaxcourt/ef-cms-flexion#7211

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by mrinsin** [comment]
@klohman Case 105-20 on dev has an Order to Show Cause that has `isLegacyServed` true!

**Comment by klohman** [comment]
#### 7198 Legacy Served Pending Items Tests

#### 1) Internal user views legacy served pending item in Case Detail > Tracked Items > Pending Report 
Test data 
- Legacy served pending item(s) for case associated with Judge Ashford 

* Login as internal user 
* Go to case
    * Case has legacy served pending item 
* Click Tracked Items and Pending Report 
Expected results 
- [x] Legacy served pending item displays in Pending Report table 

#### 2) Internal user views legacy served pending item in Pending Report by judge 
Test data 
- Legacy served pending item(s) for case associated with Judge Ashford 

* Login as internal user 
* Click Pending Report from Reports menu
* Select Judge Ashford 
Expected results 
- [x] Legacy served pending item displays in Pending Report table 

#### 3) Internal user sees case is blocked from trial if there is a legacy served pending item. 
Test data 
- Migrated case w/ Legacy Served pending item 

* Login as internal user
* Go to case 
* Click Case Information 
Expected results 
- [x] Case displays “Blocked” label in header 
- [x] Trial information displays “Blocked from Trial” with reason for block as “Pending item” 
- [x] Case does not display in eligible list for any upcoming trial sessions

#### 4) Internal user removes legacy served pending item from a case. 
Test data 
- Migrated case w/ 1 Legacy Served pending item 
- No due dates or manual block 
- Case status = General Docket At Issue 

* Login as internal user 
* Go to case 
* Click Tracked Item > Pending Report 
* Delete the legacy served pending item  
Expected results 
- [x] Pending item no longer displays in Pending report table 
- [x] Case no longer displays “Blocked” label in header 
- [x] Trial information does not display “Blocked from Trial” with reason for block as “Pending item” 
- [x] Case displays in eligible list for any upcoming trial sessions in it’s preferred city

**Comment by mrinsin** [comment]
@JessicaMarine to QA this - case 1000-20 has a Letter that has been set as being legacy served!
