### ISSUE TITLE
Update links to forms

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#753]
It looks like the links to various forms on our application have become out of date as the Court's website got updated. We added a workaround of copying the form file to the locations where DAWSON was pointing so that public could access them, but now we are maintaining them in two locations. We need to consolidate so that this doesn't happen again (and if the forms change, we only need to change them in one place).

The correct and latest links are all available at [this URL](https://www.ustaxcourt.gov/case_related_forms.html). You'll note that the PDFs themselves are all in `/resources/forms/`. That's the correct location. We were simply using the old way, which was "/forms/."

**Tasks**

- [ ] Before filing Page
  - [x] Confirm Your Identity STIN (TC Form 4)
  - [x] Petition form (TC Form 2)
  - [ ] Learn more about how to merge files into one PDF (This may need updating)
  - [x] Download Ownership Disclosure Statement (TC Form 6)
- [x] E-Filing a Petition as a Petitioner
  - [x] Step 1: STIN (TC Form 4)
  - [x] Step 2: Petition form (TC Form 2)
  - [x] Step 3 (if corporation) Ownership Disclosure Statement (TC Form 6)
- [x] Welcome page for a new petitioner
  - [x] STIN Form (TC form 4)
  - [x] Petition form (TC form 2)
  - [x] Disclosure Statement (TC Form 6)
  - [x] View forms Link (should go to: https://www.ustaxcourt.gov/case_related_forms.html)
- [x] Practitioner Resources
  - [x] Download Application For Waiver of Filing Fee
- [x] Look for other ones I missed! 
- [ ] Notify Scott at the Court when these are done so we can remove the duplicate workaround files.

**Screenshots**

![filing-step-1](https://user-images.githubusercontent.com/5023502/104239081-eeb18080-5427-11eb-94cc-6c81488a3f64.png)
![Uploading filing-step-2.png…](
![filing-step-3](https://user-images.githubusercontent.com/5023502/104239084-ef4a1700-5427-11eb-8c39-174d74cfef71.png)
![petitioner-welcome-page](https://user-images.githubusercontent.com/5023502/104239085-ef4a1700-5427-11eb-847f-59c67c9c9034.png)
![practitioner-filing-fee](https://user-images.githubusercontent.com/5023502/104239086-ef4a1700-5427-11eb-9363-ed79dd352d03.png)

![before-filing-1](https://user-images.githubusercontent.com/5023502/104239079-ee18ea00-5427-11eb-9617-773bd5f9b8b6.png)
![before-filing-2](https://user-images.githubusercontent.com/5023502/104239080-eeb18080-5427-11eb-956e-7ee6707a36bc.png)
