### ISSUE TITLE
PR 55 - Key Features Manual Testing

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7532]
Manual user testing to be performed during Sprint 55. 

## Acceptance Criteria

AC 1) Team has performed manual testing on the Flexion prod environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing
* External User Flows
* Public Search
* Public Docket Record
* Mobile Flows

AC 2) Team has performed manual testing on the Flexion dev environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing
* Service Emails

## Tasks
**External User Flows**
- [x] (1) eFile a petition (as petitioner) - (Kristen)
- [x] (2) eFile a petition (as practitioner) - (Kristen)
- [x] (3) File a Document (Primary document and Supporting Document) - petitioner (Jojo)
- [x] (4) File a Document (Primary and Secondary Document with Supporting Document ) - petitioner (Jojo)
- [x] (5) File a Document (practitioner) (Jojo)
- [x] (6) Request Access to Case - automatically associated (practitioner) (Jojo)
- [x] (7) Request Access to Case - not automatically associated (practitioner) (Jojo)
- [x] (8) File First IRS Document (irs practitioner) (Jojo)
- [x] (9) Request Access to Case (second irsPractitioner on case) - (irs practitioner) (Jojo)
- [x] (10) Petitioner edits contact information (Matt)
- [x] (11) Practitioner edits contact information (private practitioner) (Matt)
- [x] (12) Practitioner edits contact information (irs practitioner) (Matt)

**Public Search**
- [x] (41) Search by docket number and petitioner name (public user) (Matt)
- [x] **(44)  Search for a sealed case (public) (Matt) -- FAILS**
- [x] (47) Search for an opinion (as a public user) (Matt)
- [x] (50) Search for an order (as a public user) (Matt)
- [x] (53) View Today's Opinions (public) (Matt)

**Public Docket Record**
- [x] (146) View e-filed documents on public docket record (Matt)
- [x] (147) View paper-filed documents on public docket record (unserved and served) (Matt)
- [x] (148) View non-public court-issued documents on public docket record (unserved and served) (Matt)
- [x] (149) View public court-issued documents on public docket record (unserved and served) (Matt)
- [x] (150) View unservable court-issued documents on public docket record (Matt)

**Mobile Flows**
- [x] (115) MOBILE: eFile a petition (as petitioner) - (Kristen)
- [x] (116) MOBILE: eFile a petition (as practitioner) - (Kristen)
- [x] (117) MOBILE: File a Document (Primary document and Supporting Document) - petitioner (Kristen)
- [x] (118) MOBILE - File a Document (practitioner) (Matt)
- [x] (119) MOBILE: Request Access to Case - automatically associated (practitioner) (Matt)
- [x] **(120) MOBILE: File First IRS Document (irs pracititoner) (Matt) -- FAILS**
- [x] **(121 MOBILE: Request Access to Case (second irsPractitioner on case) - (irs pracititoner) (Matt) -- FAILS**
- [x] (122) MOBILE: Petitioner edits contact information (Matt)
- [x] (123) MOBILE: Practitioner edits contact information (private practitioner) (Matt)
- [x] (124) MOBILE: Search by docket number (practitioner) (Matt)
- [x] (125) MOBILE: Search by petitioner name (practitioner) (Matt)
- [x] (126) MOBILE: Search by docket number and petitioner name (public user) (Matt)
- [x] (127) MOBILE: Search for a sealed case (external) (Matt)
- [x] **(128) MOBILE: Search for a sealed case (public) (Matt) -- FAILS**
- [x] (129) MOBILE: Search for an opinion (as a external user) (Matt)
- [x] (130) MOBILE: Search for an opinion (as a public user) (Matt)
- [x] (131) MOBILE: Search for an order (as a external user) (Matt)
- [x] (132) MOBILE: Search for an order (as a public user) (Matt)
- [x] (133) MOBILE: View Today's Opinions (public) (Matt)
- [x] (134) MOBILE: View stricken docket entry (Matt)

**Service Emails**
- [x] (137) eFile Documents (party) (Jojo)
- [x] (138) File first IRS document (Jojo)
- [x] (139) Request access  (Jojo)
- [x] (140) Add Court Issued Docket Entry / Save then Serve (Jojo)
- [x] (141) Add paper-filed document and serve (Jojo)
- [x] (142) Add Practitioner to DB (Jojo)
- [x] (143) Update address (generate Notice of Change of Address) (Jojo)
- [x] (144) Notice of Docket Change (Jojo)
- [x] **(145) Set calendar for e-filed case (Notice of Trial, Standing PreTrial Notice/Order) (Jojo) -- FAILS**
  - Respondent counsel not showing in eligible cases table prior to setting calendar

## Definition of Done 
- [x] All user flows have been tested 
- [x] All issues discovered have been logged as Bugs
