### ISSUE TITLE
Sealed in Blackstone docs -- Non-Viewable to Parties/Practitioners on Case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7534]
As the Court, in order to make sure a party isn't gaining access to something he/she shouldn't have, we need all "Sealed in Blackstone" legacy document to be non-viewable to everyone but the Court.

Sealed documents are not currently viewable to the public, but the Court has some concern about whether specific "Sealed in Blackstone" documents should also be sealed to the parties/practitioners/IRS attorneys in the case.  To avoid any inadvertent disclosure of sensitive information, any "Sealed in Blackstone" document should *not* be viewable to anyone outside the Court.

Example: Entry 10 in 18117-19S, which is a change of address that was sealed at one spouse’s request because she had a no-contact order against the other petitioner.

## Pre-Conditions: ##
* A document has been migrated with the "Sealed in Blackstone" tag

## Acceptance Criteria: ##
* Any document tagged as "Sealed in Blackstone" should not be viewable to the parties/practitioners/IRS counsel of the case
* Any document tagged as "Sealed in Blackstone" should only be viewable to the Court.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
PR- ustaxcourt/ef-cms-flexion#7232

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Paired w/Mark on data migration work (if applicable)
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by JessicaMarine** [comment]
@mrinsin @klohman @mmarcotte any ideas how to test ustaxcourt/ef-cms#7534 on flexion's prod.  I need to be able to log-in as a petitioner/practitioner/IRS atty on a migrated case and see whether I can access "sealed in blackstone" docs, but none of the migrated cases have PDFs
