### ISSUE TITLE
Sprint 57- Key Features Manual Testing

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7550]
Manual user testing to be performed during Sprint 56. 

## Acceptance Criteria

AC 1) Team has performed manual testing on the Flexion prod environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing
* External parties workflows 
* Mobile (except search)
* calendaring 

## Tasks 
**External parties workflows**

- [x] 1) eFile a petition (as petitioner) (Kristen)
- [x] 2) eFile a petition (as practitioner)(Kristen)
- [x] 3) File a Document (Primary document and Supporting Document) - petitioner (Kristen)
- [x] 4) File a Document (Primary and Secondary Document with Supporting Document ) - petitioner (Kristen)
- [x] 5) File a Document (practitioner)
- [x] 6) Request Access to Case - automatically associated (practitioner)
- [x] 7) Request Access to Case - not automatically associated (practitioner)
- [x] 8) File First IRS Document (irs pracititoner)
- [x] 9) Request Access to Case (second irsPractitioner on case) - (irs practitioner)
- [x] 10) Petitioner edits contact information
- [x] 11) Practitioner edits contact information (private practitioner)
- [x] 12) Practitioner edits contact information (irs practitioner)

**Mobile**
- [x] 115) MOBILE: eFile a petition (as petitioner)
- [x] 116) MOBILE: eFile a petition (as practitioner)
- [x] 117) MOBILE: File a Document (Primary document and Supporting Document) - petitioner
- [x] 118) MOBILE - File a Document (practitioner)
- [x] 119) MOBILE: Request Access to Case - automatically associated (practitioner)
- [x] 120) MOBILE: File First IRS Document (irs pracititoner) 
- [x] 121) MOBILE: Request Access to Case (second irsPractitioner on case) - (irs pracititoner)
- [x] 122) MOBILE: Petitioner edits contact information
- [x] 123) MOBILE: Practitioner edits contact information (private practitioner)

**Calendaring**
- [x] 25) Add Trial Session/ View Eligible cases
- [x] 26) Create swing session / View Eligible cases
- [x] 27) Edit / Delete "New" trial session
- [x] 28) QC Eligible cases / Set calendar
- [x] 29) Edit "Open" trial session
- [x] 30) Print Trial Session
- [x] 31) Close Trial Session
- [x] 32) Block / unblock a case from trial (manual)
- [x] 33) Block / unblock a case from trial (automated)
- [x] 34) Block / unblock a case from trial (manual + automated)
- [x] 35) Add / remove high priority (for trial)
- [x] 36) Manually add case to "New" trial session
- [x] 37) Manually remove case from New trial session
- [x] 38) Manually remove case from Open trial session

## Definition of Done 
- [x] All user flows have been tested 
- [x] All issues discovered have been logged as Bugs
