### ISSUE TITLE
Conduct usability testing on public search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7551]
As a project team, in order to provide the public with an optimal search experience, we need to conduct usability testing. 

## Acceptance Criteria
* Conduct usability testing on public search features (Case search, order search, opinion search) with internal Flexion folks to identify top 5 usability improvements we need to make before we go live

## Tasks
* Identify who is using the public search and what they're using it for
* Identify the search terms for each search 
* Identify the usability test scenarios and confirm with Jessica

## Notes
* Have PDF scraping done before we begin testing

## Security Considerations
 - [ ] This work make you nervous about privacy or security?
 - [ ] This work make major changes to the system?
 - [ ] This work implement new authentication or security controls?
 - [ ] This work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 10-26-20)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env
**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Paired w/Mark on data migration work (if applicable)
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Code toggle has been implemented (“On” for items that are QA’d)
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by mariahkannenberg** [comment]
@klohman Notes from our convo w/Jessica on 12/8/20

Case Search
	• Search by name
		○ Used universally by public, practitioners and court users
		○ Public - cases that have been in the media, searching for family and friends - snoopy folks. Usually looking for one specific case. If a user puts in "Coca Cola" and gets many results, it will be unsettling if more than one case gets returned when there's only one. 
		○ Practitioners - search for a case when they don't know the docket number. If a new client comes and they need to find the docket number in their case. Or if they know a case is related to theirs and only know the name of it. 
		○ Court users - search by name to see if a person has already filed a petition; or they don't know what the docket number is

Order Search - Academics, practitioner, probably not general public 
		• Academics - people blogging about the court or writing articles; they'd be looking for key words within a document; they might put code sections, case names. They're focused more on the body of the text
			§ They likely don't want to see partial matches. There would be too many if we mix partial in there.

**Comment by klohman** [comment]
Notes 

Goals: 
* Discover if users can locate a specific case 
* Discover if users can find documents containing specific keyword 
* Discover if users can find documents containing specific phrase 
* Discover if search matches meet user expectations 

Tasks - need to rewrite 

1.  Find a case for [petitioner name with exact match] 
2.  Find a case for [petitioner name with no exact match but partial match] 
3.  Find document(s) that contain [keyword] 
4.  Find document(s) that contain [phrase]
5.  Find document(s) that contain [phrase] that were served within the [timeframe]


Evaluation 
* Task completion 
    * User is able to locate the case / document
* Satisfaction  
    * How well did the search matches meet your expectations?  
		1 - Met my expectations 
		2 - Did not meet my expectations

**Comment by klohman** [comment]
@JessicaMarine 

### Top Usability Findings / Priority Recommendations 

* 1) Exact matches need to be sorted to top of results -- Added to ustaxcourt/ef-cms#7574
      - Exact matches = matches the entered string 
      - Case search = petitioner name match should be higher relevance than case title match 

* 2) Update messaging around search matches, especially partial matches  -- Added to ustaxcourt/ef-cms#7574
        - Continue to display partial matches 
        - Messaging need to be clear when there are no exact matches, and that the matches displayed are partial matches only 
        - Provide tips on how to refine

* 3) Highlight matching search terms in results; user should be able to clearly identify why a result is matching their search terms -- will backlog for post-launch ustaxcourt/ef-cms#7155

* 4) Load more button should display additional results without scrolling to top  -- Added to ustaxcourt/ef-cms#7574

* 5) App should retain search results after navigating away -- Added to ustaxcourt/ef-cms#7574
       - Should be retained until user clears search or logs out of application
