### ISSUE TITLE
Court: Phone Number Formatting

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7553]
As the Court, in order to make phone numbers easier to read, they should be formatted when possible.

## Pre-Conditions
* User has entered a phone number into the system

## Acceptance Criteria ##
* If a phone number entered has 10-digits, it should be displayed as xxx-xxx-xxxx after the case is saved
* Number does not need to auto-format when being entered
* Anything that's other than 10 digits should not be impacted

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Create helper function to add hyphens to 10-digit number strings and call it anywhere a phone number is stored (Rachael ustaxcourt/ef-cms-flexion#8515)
- [x] 2 Write migration to update phone numbers in any entities that currently store phone numbers (case contacts and practitioners, user records, others?) (Rachael ustaxcourt/ef-cms-flexion#8517)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## UX Review - Meets Acceptance Criteria as written

#### Notes: 
* When external user (petitioner / private practitioner) creates a case, the phone number is not being formatted on the Review Your Case Screen - the case has not been saved at this point so it meets AC

* Phone number is only being formatted when 10 consecutive digits are entered. If there are spaces or special characters, it is not being formatted. So phone numbers entered as 302 888 4444, (302)7874444, etc will not be formatted.
