### ISSUE TITLE
Practitioner w/o Email Address: Default to Paper Service

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7554]
As the Court, in order to make sure we are properly serving all practitioners, we need to default Service to "Paper" for any practitioner for whom we don't have an email address.

## Pre-Conditions
* Practitioner is entered into system without an email address

## Acceptance Criteria
* All practitioners in the system who do not have an email address need to default to paper service
* Clerks cannot select electronic service for a practitioner without an email address 
* When an email address is added to a practitioner's profile, his/her service preference is updated to electronic in each case they are currently associated with.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* This only applies for migrated practitioners for now.  Emails are still required for new practitioners -- we will be changing that ASAP.

## Tasks
- [x] 1 Migration script to update USER objects in dynamo for practitioners without an email to paper service  - mob
- [x] 2 Migration script to update USER/CASE association objects in dynamo for practitioners without an email to paper service
- [x] 3 Update Practitioner entities to compute default service indicator (Matt ustaxcourt/ef-cms-flexion#7575)
- [x] 4 Validate selected practitioner/service method in add*PractitionerModal and show error when a selected method is unavailable (Matt ustaxcourt/ef-cms-flexion#7575)
- [x] 5 Set default service preference based on selected practitioner (Matt ustaxcourt/ef-cms-flexion#7575)
- [x] 6 Update aggregatePartiesForService (Matt ustaxcourt/ef-cms-flexion#7589)

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## 7287 Tests

#### 1) Docket clerk adds private practitioner without email to case and sees practitioner has paper service 
* Login as docket clerk 
* Go to Case > Case Information > Petitioner 
* Add petitioner counsel -counsel w/o email address
Expected results 
- [x] Private practitioner displays under Petitioner Counsel 
- [x] Petitioner service indicator updates to “none” 
- [x] private practitioner service indicator displays as “Paper” 

#### 2) Docket clerk serves document on private practitioner without email service 
* Scenario 1 
* Create, sign and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] App routes to Print Paper Service screen 
- [x] private Practitioner address displays on address page 


#### 3 Docket clerk adds IRS practitioner without email to case and sees practitioner has paper service 
* Login as docket clerk 
* Go to Case > Case Information > Petitioner 
* Add respondent counsel 
    * Counsel has no email 
Expected results 
- [x] IRS practitioner displays under Petitioner Counsel 
- [x] IRS practitioner service indicator displays as “Paper” 

#### 4) Docket clerk serves document on its practitioner without email service 
* Scenario 3 
* Create, sign and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] App routes to Print Paper Service screen 
- [x] IRS practitioner address displays on address page 

#### 4) Docket clerk cannot select Electronic service for a practitioner without an email 
* * Login as docket clerk 
* Go to Case > Case Information > Petitioner 
* Add petitioner counsel 
* Select "Electronic" as service preference 
Expected results 
- [x] Field level error displays on service indicator radio set: "No email found for electronic service. Select a valid service preference."

#### 5) Admissions clerk adds email to a private practitioner without email address and service preference is automatically updated to electronic in existing cases. 
* Login as docket clerk 
* Go to Case > Case Information > Petitioner 
* Add petitioner counsel -counsel w/o email address
* Login as admissions clerk 
* Search for private practitioner w/o email 
* Add email address and Save 
* Go to case associated with private Practitioner 
Expected results 
- [x] Private practitioner service indicator displays as electronic after email is added to profile 

#### 6) Admissions clerk adds email to a irs practitioner without email address and service preference is automatically updated to electronic in existing cases. 
* Login as docket clerk 
* Go to Case > Case Information > Respondent 
* Add counsel w/o email address
* Login as admissions clerk 
* Search for irs practitioner w/o email 
* Add email address and Save 
* Go to case associated with irs Practitioner 
Expected results 
- [x] Irs practitioner service indicator displays as electronic after email is added to profile

**Comment by rachaelparris** [comment]
For whoever picks this up, we have started work for task 1 on the branch `7287-user-migration`

**Comment by klohman** [comment]
@matthopson 

### 7287 UX Review 

![Screen Shot 2021-01-15 at 1.57.55 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/04f0d526-9494-4ca1-bd89-cdc26ac80cd0)

* Paper service address page is not displaying the Practitioner address (private or IRS practitioner)

**Comment by rachaelparris** [comment]
dev and prod - migrated practitioner with bar number `KS2111` with electronic service indicator. After migration, should be set to paper. Also added that practitioner to case 105-20 with electronic service indicator. After migration, should be set to paper.

**Comment by klohman** [comment]
@JessicaMarine UX Notes: 

* When adding an email to a practitioner who previously had no email on record, the practitioner service indicator does not update on the practitioner's current cases. It remains as paper. When you add this practitioner to another case, the service indicator will default to electronic.

**Comment by JessicaMarine** [comment]
@klohman I think that functionality was missed in ustaxcourt/ef-cms#7739 (https://github.com/flexion/ef-cms/issues/7377) then.  There was an AC: Practitioner's service preference is changed to electronic. I guess that could've been more explicit and said "in each case"
