### ISSUE TITLE
Admissions Clerk and General User: Add/edit/delete correspondence

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7556]
As an Admissions Clerk and Records Clerk ("General User"), I need the ability to add/edit/delete correspondence on a case, so that I can properly associate non-docket record documents with a case.

## Acceptance Criteria
* Admissions Clerk can add/edit/delete correspondence on a case
* General users can add/edit/delete correspondence on a case

Admissions Clerks and general users currently have a read-only view of correspondence: ![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/7d4bcecc-2889-428a-96d1-d9654bd71eee)

They should have the ability to add/edit/delete:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/d1817ed2-b7a9-4060-99e0-1e1ee755bb9c)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
PR- ustaxcourt/ef-cms-flexion#7314

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment
