### ISSUE TITLE
PR 56: Manual Testing w/External Legacy Logins

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7568]
As a development team, so that we can ensure external functionality is working for legacy users, we need to test external interactions with legacy user logins. 

## Acceptance Criteria
* AC 1) Mock-PDF

* AC 2) Team has performed manual testing on the Flexion prod environment for the following user flows using **legacy logins**, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=215623579

* AC3) Team has tested service emails for legacy users 

**Logins**
Legacy petitioner 
* xroberts@example.com 

Legacy private practitioner 
* 5C0BE83E10A6506ED0E1277791DDB0DC@dawson.ustaxcourt.gov 

Legacy irs practitioner 
* 7D6CB548D9C51CE49F9C57E31A325278@dawson.ustaxcourt.gov 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
**External User Flows**
- [x] (1) eFile a petition (as petitioner) (Rae)
- [x] (2) eFile a petition (as practitioner) (Mrinalini)
- [x] (3) File a Document (Primary document and Supporting Document) - petitioner (Mrinalini)
- [x] (4) File a Document (Primary and Secondary Document with Supporting Document ) - petitioner (Mrinalini)
- [x] (5) File a Document (practitioner) (Mrinalini)
- [x] (6) Request Access to Case - automatically associated (practitioner)  (Mrinalini)
- [x] (7) Request Access to Case - not automatically associated (practitioner)  (Mrinalini)
- [x] (8) File First IRS Document (irs practitioner) (Rae)
- [x] (9) Request Access to Case (second irsPractitioner on case) - (irs practitioner) (Rae)
- [x] (10) Petitioner edits contact information (Kristen)
- [x] (11) Practitioner edits contact information (private practitioner) (Mrinalini)
- [x] (12) Practitioner edits contact information (irs practitioner)

**Service Emails**
- [x] (137) eFile Documents (party) - (Kristen + Rachel)
- [x] (138) File first IRS document (Kristen + Rachel)
- [x] (139) Request access  (Kristen + Rachel)
- [x] (140) Add Court Issued Docket Entry / Save then Serve (Kristen + Rachel)
- [x] (141) Add paper-filed document and serve(Kristen + Rachel)
- [x] (143) Update address (generate Notice of Change of Address) (Kristen + Rachel)
- [x] (144) Notice of Docket Change (Kristen + Rachel)
- [x] (145) Set calendar for e-filed case (Notice of Trial, Standing PreTrial Notice/Order) (Kristen + Rachel)

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment
