### ISSUE TITLE
BUG: Opinion search by Judge showing results for non-matching judges

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7572]
**Describe the Bug**
When searching for an opinion and filtering by judge, the results display opinions for the selected judge but also display results for another judge not matching search criteria. 

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
flexion prod / court env

**Who were you logged in as?**
public

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to opinion search 
2. search keyword "opinion"
3. Select judge ashford 

**Expected Behavior**
Results should only include opinions with exact match of Judge Ashford. 

**Actual Behavior**
Opinions for Judge Ashford are displayed first, but if you continue to load results, opinions for Judge Nega are displayed as well. 

This also happens with these judge: 
 
Buch - Marvel also shows 
Copeland - Paris and Guy are mixed in results 
Greaves - Guy shows
Guy - Copeland, Greaves also show
Nega - Ashford, Goeke, and Gale show
Paris - Copeland also shows
Urda - Panuthos also shows 
Goeke - Gale, Nega, and Ruwe show

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [x] Determine why the bug wasn't caught by a test. 
 - [x] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [x] If needed, automated test is created.
 - [x] If needed, manual test is created.
 - [x] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the stage environment.
 - [ ] Bug has been tested in staging (UX or Engineering).

**Comment by kkoskelin** [comment]
FYI: the search predicate for judge name sometimes includes middle initials, like "M".  The current syntax allows for any number of matches, so if we search for "Susan B Anthony" we would get "Johnny B Goode" as a potential match.

**Comment by mmarcotte** [comment]
Notes from https://github.com/ustaxcourt/ef-cms/issues/871

Judge fields in the `efcms-docket-entry` elasticsearch index are currently mapped as text fields. This causes the judges names to be tokenized such that a name like `Maurice B. Foley` becomes individual tokens in the index `['maurice', 'b',  'foley']`. This causes search results to include other judges with shared name components like `Michael B. Thornton`.  There is no advantage to tokenizing names like this since we never need to look up all judges with middle initial `B` for first name `Maurice`. It is also less efficient to match phrases when a single keyword will do. Changing these to keyword fields will insure that each judge name will have a single exact representation in the index.  This will require, however, that all searches for judges use this exact (case-sensitive) judge name.

**Tasks:**

- [ ] Change mapping type of judges such as `judges.S` and `signedJudgeName.S` to keyword fields.
- [ ] Determine canonical naming scheme for judges.  Currently both full name and last name only appear in this field, i.e. sometimes "Maurice B. Foley" is used and sometimes only "Foley".
- [ ] Normalize judge names to canonical naming in dynamoDB
- [ ] Insure that queries from the front-end use the normalized form of the judge name.
- [ ] Insure that operation that write to dynamoDB use the normalized judge names.
- [ ] Reindex Elasticsearch index

🙌  Mark Meyer

**Comment by mariahkannenberg** [comment]
Blocked - this is for opinion search, but opinion search is off. Recommend adding this feedback to to opinion stories and archiving. OR, just leave blocked until we're working on opinion search again.

**Comment by mariahkannenberg** [comment]
Turn opinion search on in MIG or test and see if it's still a problem.

**Comment by cholly75** [comment]
@mariahkannenberg Confirmed in MIG, this is still an issue. Unblocking.

**Comment by matthopson** [comment]
PR with temp fix to only search on last name: https://github.com/ustaxcourt/ef-cms/pull/1638

@cholly75 to work on creating stories to address uniquely identifying / associating judges in the system.

**Comment by mariahkannenberg** [comment]
Opinion not turned on in Court's test environment.

**Comment by cholly75** [comment]
@rachelschneiderman I just looked at this again based on your feedback - it is indeed happening again in MIG. Did something get reverted with the deploy yesterday perhaps? I specifically looked for this yesterday and didn't see it, hence me closing the bug.

**Comment by kkoskelin** [comment]
solution resides in shared/src/business/utilities/getFormattedJudgeName.js
The drop-downs that get populated with the above utility should be using only the last name for both the visible label as well as the value sent to the API for purposes of filtering. Should be incredibly quick to fix, if I'm right...
