### ISSUE TITLE
Search Usability: Load more, and retain results

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7576]
As the Court, in order to make sure our users are having a good user experience, we need to make some usability tweaks to the search features.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

## Acceptance Criteria
*  Load more button should display additional results without scrolling to top
*  App should retain search results after navigating away  (Ask engineers re: LOE)
   * Should be retained until user clears search or logs out of application

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
 - [x]  Retain search results when navigating away from the search page (MriRachaRae ustaxcourt/ef-cms-flexion#7360)
 - [x] Retain search results when switching tabs within the search page (MriRachaRae ustaxcourt/ef-cms-flexion#7362)
 - [x] Don't scroll to top of page after clicking 'Load More' results button (MriRachaRae ustaxcourt/ef-cms-flexion#7364)
  

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment
