### ISSUE TITLE
Timeout: Order and Opinion Search

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7579]
As a user, so that I'm able to perform order and opinion searches in DAWSON, I don't want to get timed out (504 Gateway Timeout).

## Acceptance Criteria
* User doesn't get timed out (504 Gateway Timeout) when performing an order or opinion search
* If search go beyond the performance threshold, user receives a message
* Re-enable all related skipped tests such as those found https://github.com/ustaxcourt/ef-cms/pull/692#discussion_r548021875

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Create error class for 504
- [x] Create sequence for handling 504 errors
- [x] UI / messaging for timeout error

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by TomElliottFlexion** [comment]
Error message based on conversation with @cnelsonflexion:![Screen Shot 2021-07-01 at 11.45.13 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/1bb22d03-a8d0-43f5-ab9c-1eb96d9bcaba)

**Comment by cnelsonflexion** [comment]
@TomElliottFlexion Sorry Tom, super minor: Can you adjust the body to read:

Please wait a few moments, then click the Search button to retry.

**Comment by TomElliottFlexion** [comment]
Certainly

**Comment by TomElliottFlexion** [comment]
@cnelsonflexion The default timeout is set at 30 seconds

**Comment by matthopson** [comment]
@JessicaMarine We may have a difficult time testing this now after deploying to `mig` since some rate limiting stuff (#7756) came with it. I can't use the same token to run the load tests and also test the UI and hope for a timeout error because my user is rate limited. It may be something we can just try to deploy to an exp environment without the rate limiting and run the load tests against that.
