### ISSUE TITLE
Order Search: Exact matches (REPLACE with 8546)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7580]
As a user (internal or external), so that I find the order I'm looking for, I need exact matches to display at the top of the search results.

These AC are based on Kristen's usability testing with 5 participants on 12/14/2020.

## Acceptance Criteria
* User (internal or external) should see an indication that my search request is “processing” after starting a search
* Ensure that links on search results don't expire
* Exact keyword matches need to be sorted to top of results 
* We define exact matches as exact words in the exact order
    * For example, if innocent spouse is entered --First priority - matches innocent spouse

* If search keyword and petitioner name, matches need to be sorted as:
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
    * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
    * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]

* If search keyword and petitioner name, show no results
    * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
    * Keyword exact match (exact words in any order) + petitioner name [no exact match]

* If search keyword and docket number / judge / start-end date combo, matches sorted as: 
    * Keyword exact match (exact words in exact order) + docket number/judge/start-end date [exact match]
    * Keyword exact match (exact words in any order) + docket number/judge/start-end date [exact match]

* If there are no matches, inform the user

* Inform users that no advanced syntax is supported in search 
* Strip all special characters in the keyword field and replace with space 
* No fuzzy search
    * For example: if "Rob Jones" is entered
        * "Robert Jones" does not match

* Consider whether to reject searches that have special characters. Perhaps we can use Joi to validate what is a valid search query.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
Consider:  https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html

## Tasks
 - [ ] Write integration tests for test scenarios (Jojo, Matt, Mrin, Rae, Rachael)
 - [ ] Adjust search query as needed

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Design 

### Order Search Updates 
* add helper instructions for keyword field 
- "Advanced syntax search (*, “”, - , etc. ) is not supported at this time."

### Exact Match Query w/ matches
* execute only exact match (AND) queries
* Display results (sorted as defined in tests) 
* Display number of matches 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b09fed06-b11a-4873-ab48-2a5b7be4bee0)


### Exact query w/ no matches
If there are no matches:  
* Display "No Matches Found" 
* Display search tips alert 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dc8f244d-6000-4763-86be-3871c5c7787b)

### Exact query w/ max number of search results 
If there are over the max number of search results: 
* Display 100 results 
* Display max results alert 
* Display "100 matches shown" 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/65aa83a5-a8ef-483f-af5e-a073cc037912)

**Comment by mrinsin** [comment]
# Test Scenarios

## 7369 - Display matches for order search
 

> * Exact keyword matches need to be sorted to top of results 
> * We define exact matches as exact words in the exact order
>     * For example, if innocent spouse is entered --First priority - matches innocent spouse

- exact keyword match on document title - eg with keyword "Sunglasses"
  - Create an order whose title contains the word "Sunglasses" and document contents "pigeon"
  - Create an order whose title contains the word "Sunglassesy"
  - searching for keyword "sun" returns no results
  - searching for keyword "pigeon" returns no results **// TODO**
  - searching for keyword "Sunglasses" returns the first order but not the second
  - searching for keyword  "Sunglassesy" returns the second order but not the first
  - searching for keyword "Sunglasses!^&*" returns the first order but not the second
    - **Engineering note:** Replaced with `"Sunglasses{space x4}"`, w/o quotations

---

> * [1] If search keyword and petitioner name, matches need to be sorted as:
>     * Keyword exact match (exact words in exact order) + petitioner name [exact words in exact order]
>     * Keyword exact match (exact words in any order) + petitioner name [exact words in exact order]
>     * Keyword exact match (exact words in exact order) + petitioner name [exact words in any order]
>     * Keyword exact match (exact words in any order) + petitioner name [exact words in any order]
> * [2] If search keyword and petitioner name, show no results
>     * Keyword exact match (exact words in exact order) + petitioner name [no exact match]
>     * Keyword exact match (exact words in any order) + petitioner name [no exact match]

- exact keyword match on document title with petitioner name
  - add a case with the contactPrimary.name of "Bob Jones"
  - add a case with the contactPrimary.name of "Jones Bob"
  - Create an order A on case 1 with title containing the word "Sunglasses Funny" and document contents "pigeon"
  - Create another order B on case 2 whose title contains the word "Funny Sunglasses"
  - [1] searching for keyword "Funny Sunglasses" and petitioner name "Bob Jones" shows order B at the top of the results and the order A below that.
  - [1] searching for keyword "Funny Sunglasses" and petitioner name "Jones Bob" shows order B at the top of the results and the order A below that.
   - [1] searching for keyword "Sunglasses Funny" and petitioner name "Bob Jones" shows order A at the top of the results and the order B below that.
  - [1] searching for keyword "Sunglasses Funny" and petitioner name "Jones Bob" shows order A at the top of the results and the order B below that.
  - [2] searching for keyword "Sunglasses Funny" and petitioner name "Bobby Jones" does not show order A or order B
  - [2] searching for keyword "Funny Sunglasses" and petitioner name "Bobby Jones" does not show order A or order B


> * If there are no matches, inform the user
> * Inform users that no advanced syntax is supported in search 
> * Strip all special characters in the keyword field and replace with space 
> * No fuzzy search
>   * For example: if "Rob Jones" is entered
>   * "Robert Jones" does not match

**Comment by rachaelparris** [comment]
Work has been started for this story on branch `7369-order-search-with-petitioner-name`

**Comment by kkoskelin** [comment]
For exact matches:  https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-match-query-phrase.html

**Comment by JessicaMarine** [comment]
Replaced by ustaxcourt/ef-cms#7950
