### ISSUE TITLE
Today's Orders

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7591]
As the Court, in order to present all of the Orders of the Court to the public, we need a "Today's Orders" feature very similar to "Today's Opinions"

## Acceptance Criteria
* User is able to access a "Today's Order" page from the Court's website (at dawson.ustaxcourt.gov/todays-orders) that includes a list of all orders served that day chronologically, most recent on top (by time of service).
   * List should include: 
      * Docket No.
      * Case Title
      * Order Description
      * Pages
      * Judge
* If no orders have been served that day, the page should display the following message: "No orders have been issued today."
* The page should clear/reset at midnight (or 12:01am) ET.
* Display the first 100, then load more
* Confirm that no orders from sealed cases are being displayed
* Notify users that sealed cases will not be displayed

## Notes
* This work is now a higher priority to get done given that the full Order search feature is being delayed.
 - Consider adding caching, so the page doesn't need to re-load everything
## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Make UI and Back End for todays Orders PR - ustaxcourt/ef-cms-flexion#7411 (Rachael, Rae, Cody, Mrin)
- [x] Mobile view for todays orders -#7413 (Rachael, Rae, Cody, Mrinalini)
- [x] Show first 100 results and Load More button - ustaxcourt/ef-cms-flexion#7419 (Rachael, Rae, Cody, Mrinalini)
- [x] Sort results based on most recent servedAt first - ustaxcourt/ef-cms-flexion#7421 (Rachael, Rae, Cody, Mrinalini)

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Todays Orders w/ results 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/26fffe36-8289-4f33-8731-f3af8dd74bf9)

## Todays order - no orders 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/98d4c92a-0476-4b50-972b-0d0163b46369)


## Mobile 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2e9c2cfa-92e0-4339-8581-2c156298ca89)

**Comment by klohman** [comment]
## Test Scenarios 

7404 Todays Orders 

#### 1) Public user sees message when no orders have been served for today’s date
* Go to public url for Today’s Orders 
* No orders have been served today
Expected results 
- [ ] “No orders issued today” message displays

#### 2) Public user sees orders served for today’s date 
Test data
- Case xx1-20 
    - Order (not served) 
- Case xx2-20
    - Order (served today) 

* Go to public url for Today’s Orders 
Expected results 
- [ ] Order for case xx1-20 does not display 
- [ ] Order for case xx2-20 does not display 


#### 3) Public user does not see order served today in a sealed case 
Test data 
- Case xx1-20 
    - Order (not served) 
- Case xx2-20
    - Order (served today) 
- Case xx3-20 (Sealed case)
    - Order (served today) 

* Go to public url for Today’s Orders 
Expected results 
- [ ] Order for case xx1-20 does not display 
- [ ] Order for case xx2-20 displays 
- [ ] Order for case xx3-20 does not display 


#### 4) Public user sees Todays Orders displays orders issued on the current date (after daily refresh) 
* TBD

**Comment by JessicaMarine** [comment]
Jessica reviewed 12/24/2020 -- functionality is working as expected.

Need to wait until 12/25/2020 to test null state.

Also, need to increase the # showing before load more.

**Comment by mrinsin** [comment]
@JessicaMarine updated max order page size is on prod!
