### ISSUE TITLE
Practitioner: Ability to Edit Email Address

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7592]
As a Practitioner, in order to keep all my information current with the Court and ensure I am getting service emails, I need the ability to edit my email address.

Related to ustaxcourt/ef-cms#6890: Edit Petitioner's Email

## Pre-Conditions
* Practitioner exists in DAWSON with an email address

## Acceptance Criteria
* Practitioner has the ability to **edit** his/her email address
* Practitioner is provided new credentials to access DAWSON [See note below].
* When the email has changed, the practitioner is required to verify their new email address.
* Practitioner is able to log-in and access their cases
   * Ensure that the practitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
   * Practitioner can eFile documents in cases
* Practitioner's service preference remains as electronic
* Practitioner receives service emails at the new service email address
* ~~Editing email generates a Notice of Change of Email Address (create as own story w/petitioner??)~~New Story ustaxcourt/ef-cms#7674
* Email updates in every case the practitioner is associated with 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider whether we have to create and link a new Cognito account or whether Cognito may allow an admin to just change email address
* Look at current rules around which cases are updated (open, closed for x days - was this just for notice?)
https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/signing-up-users-in-your-app.html

## Tasks

- [x] 1 Add My Account item - Team mob ustaxcourt/ef-cms-flexion#7669
- [x] 2 on select of My Account, route to My Account screen  - Team mob ustaxcourt/ef-cms-flexion#7670
- [x] 3 Move ‘My Contact Information’ to ‘My Account’ - Team mob ustaxcourt/ef-cms-flexion#7670
- [x] 4 Add ‘Login & Service Email Address’ to ‘My Account’ - Team mob ustaxcourt/ef-cms-flexion#7671
  - [x] Display current email - Team mob ustaxcourt/ef-cms-flexion#7671
  - [x] On click of Change Email, route to Change Email screen - Team mob ustaxcourt/ef-cms-flexion#7671
- [x] 5 Create Change Login & Contact Email Address page - Team mob ustaxcourt/ef-cms-flexion#7671
  - [x] Validation - Team mob ustaxcourt/ef-cms-flexion#7674
  - [x] If email exists in cognito, display error - Team mob ustaxcourt/ef-cms-flexion#7676
- [x] 6 Create Verify Email modal - Team mob ustaxcourt/ef-cms-flexion#7680
- [x] 7 On submit of change email
  - [x] Add global pending email banner - Team mob ustaxcourt/ef-cms-flexion#7682
  - [x] old email still displays under Login & Service email & on cases
  - [x] Persistence of email update (interactor etc.) - Team mob ustaxcourt/ef-cms-flexion#7684
  - [x] Add ‘emailPending’ to User entity - Team mob ustaxcourt/ef-cms-flexion#7682
- [x] 8 Send verification email to UPDATED email address - Team mob ustaxcourt/ef-cms-flexion#7689
- [x] 9 Create an endpoint to handle verification and email update - Team mob ustaxcourt/ef-cms-flexion#7694
  - [x] If user is logged in, display verification success page - Team mob ustaxcourt/ef-cms-flexion#7691
  - [x] If user is NOT logged in, redirect to instruction page. - Team mob ustaxcourt/ef-cms-flexion#7691
- [x] 10 Update persistence of email update to be async - Team mob ustaxcourt/ef-cms-flexion#7699
  - [x] Potentially display progress bar - Team mob ustaxcourt/ef-cms-flexion#7706
- [x] Remove `My Contact Information` from Irs/Private practitioner dashboard - Team mob ustaxcourt/ef-cms-flexion#7729

Refactoring: 
- [x] Update getCognitoUserByEmail to use adminGetUser instead of listUsers - Team mob ustaxcourt/ef-cms-flexion#7699

Questions:
What happens in the UI after ‘please check your new email modal’?

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Practitioner Dashboard 

* Remove My Contact Information card 


## user Menu 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/444f17a5-5f0e-409f-a04a-bb9d963ddc30)
 
* Add My Account item 
* on select of My Account, route to My Account screen 

## My Account screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9a232ba1-8455-4a09-9bb7-b950b48a5192)

#### My Contact Information 
* edit routes to Edit My Contact Information screen (no changes) 

#### Login & Service Email Address 
* display current email 
* On click of Change Email, route to Change Email screen 

## Change Login & Contact Email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6cc73b98-fb93-4c33-8286-d7535873272a)
## Change Login & Contact Email Address 

**Current email address**
* display current email in read-only format 

#### Change Login & Contact Email 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display verify email modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* Old email is still valid
* New email is not yet valid 

## Verify New Email modal

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea335369-257e-4f6a-8ca7-38b7b76e0ff1)

* Display modal after save 
* Modal displays new email address in <placeholder> 
* on click of OK , navigate back to My Account screen  

## My Account screen with pending email

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f98aaff-2a8f-47b9-a46f-3820831a8df7)

* display warning message under page header globally 
* old email still displays under Login & Service email & on cases 

## Change Email screen (with pending email) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d0cd838a-aeec-4590-b23b-701b954517c8)

**Current email **
* displays current (old) email in read-only format

**Pending email**
* Displays new email in read-only format 

#### Change Login & Contact Email 
* same functionality as before 

## Verified Email Success Page 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e9cc76a5-4f00-416e-b4f7-344a5deffcb1)

**User clicks on verification link**
* if user is logged in, user is routed to a email verified success page

## User is not logged in when they click the Verify link 
* if user is not logged in, redirect to "You Must be Logged in" screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f30c014a-a78a-4ee1-b123-bf57bb4e499e)

**Comment by klohman** [comment]
## Updated Email Flow 

* Edit Contact Information 
* Update email 
* App/cognito sends verification email to NEW email with a verification link

* Old email is still valid; user can log in with old email; service emails go to old email 
* new email is pending verification and user cannot log in with new email; service emails do not go to new email
* App displays warning message to verify new email 
* Old email is displayed as email in UI under Contact Information on dashboard and in all cases

**User clicks Verify Email**
* user clicks “Verify Email” link 
* if user is logged in, user is routed to a email verified success page (In DAWSON with link to log back in) 
* if user is not logged in, redirect to "You Must be Logged In" screen 
 
* old email is now invalid; user cannot log in with old email; service emails do not go to old email 
* new email is valid and user can log in with new email; service emails now go to new email 
* New email displays in UI on dashboard and in all cases

**Comment by klohman** [comment]
## 7406 

#### A) Practitioner accesses My Account information 
* Login as practitioner 
* Click user menu and select My Account 
Expected results 
- [x] My Account is option in user menu
- [x] My Account screen displays My Contact Information Card 
- [x] My Account screen displays Login & Service email card 

#### B) Practitioner accesses Change email screen  
* Login as practitioner 
* Click user menu and select My Account 
* Click Change Email link
Expected results 
- [x] App routes to Change Email screen 
- [x] current email displays 

#### 1) Practitioner updates email and saves form with valid email address 
* Login as practitioner 
    * privatePractitioner10@example.com
    * irsPractitioner10@example.com
* Update email address 
    * privatePractitionertest@example.com
    * irsPractitionertest@example.com
* Click Save 
Expected results 
On click of Save 
- [x] Verify email modal displays 
- [x] On click of OK on modal, App routes to My Account screen with success message displayed 
- [x] Verification email is sent to new email 
- [x] Old email is still valid 
- [x] Practitioner old email still displays under Login & Service email
- [x] Practitioner old email still displays under all cases
- [x] Global warning message displays 

#### 2) Practitioner updates email and saves form with invalid email address 
* Login as private practitioner / irs practitioner 
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 3) Practitioner updates email and saves form with duplicate email address 
* Login as private practitioner / irs practitioner 
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Savel 
Expected results 
- [x] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Practitioner updates email files a document before verifying new email 
* Login as practitioner 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
* Update email address
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
* Go to case 
* File a Motion for New Trial 
Expected results 
- [x] Motion for New Trial is added to Docket Record 
- [x] New email address does not receives service email 
- [x] Old email does receives service email 

#### 5) Practitioner updates email and cannot login with new email address before verifying email
* Scenario 4 
* Login as practitioner with new email 
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
Expected results 
- [x] User sees error on login for invalid credentials 

#### 6) Practitioner updates email and can login with old email address before verifying new email
* Scenario 4 
* Login as practitioner with old email 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
Expected results 
- [x] User is able to login 
- [x] Global warning to verify email is displayed 
- [x] Old email displays in My Account>Login & Service email and in all cases

#### 7) Practitioner updates email and receives service for court-issued document at old email before verifying new email 
* Scenario 4 
* Login as docket clerk 
* Go to case 
    * Case has private practitioner flexionustc+emersongreen@gmail.com 
    * Case has irs practitioner flexionustc+IRS@gmail.com
* Create, sign and serve Order to Show Cause 
Expected results 
- [x] order to show cause is added to Docket Record 
- [x] New email address does not receive service email 
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
- [x] Old email receives service email 
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com 


#### 8) Practitioner updates email and enters non-matching email on confirmation 
* Login as private practitioner / irs practitioner 
* Update email address = firstemail@email.com
* Click Save 
* Re-enter non-matching email = secondemail@email.com
* Click Continue on modal 
Expected results 
- [x] Error displays on email field -  “Email addresses do not match.”

#### 9) Practitioner verifies new email and logs in with new email 
* Scenario 4 
* Go to gmail 
* Click Verify Email link 
* Click login on success page
* Login as practitioner
    * flexionustc+emersongreen2@gmail.com 
    * flexionustc+IRS2@gmail.com
Expected results 
On click of verification link:
- [x] User is routed to Email Verified success page 
On login: 
- [x] Login is successful 
- [x] App displays new email on My Account> Login & Service email and in all associated cases 
- [x] Global warning message is not displayed

#### 10) Practitioner verifies new email and files a document 
* Scenario 9 
* Go to case
* File a Document 
    * Administrative Record 
* Submit document
Expected results 
- [x] Administrative Record is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 11) Practitioner verifies new email and receives service email for court-issued document 
* Scenario 9 
* Login as docket clerk 
* Go to case 
    * Case has private practitioner flexionustc+emersongreen2@gmail.com 
    * Case has irs practitioner flexionustc+IRS2@gmail.com
* Create, sign and serve Decision 
Expected results 
- [x] Decision is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 12) Practitioner verifies new email and cannot log in with old email 
* Scenario 9 
* Login to system with old email
    * flexionustc+emersongreen@gmail.com 
    * flexionustc+IRS@gmail.com
Expected results 
- [x] Login is unsuccessful and error message is displayed

#### 13) Practitioner verifies email when not logged in to system 
* Scenario 1 
*  Log out of system 
* Go to email 
* Click verify email link
* Login 
Expected results 
On click of verify 
- [x] user is routed to "You Must be Logged In" screen with instructions
- [x] user can log in with old email 
- [x] user cannot log in with new email

**Comment by klohman** [comment]
## Update to Global Warning 

* OK to move warning above page title bar so that it will appear on all screens

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/84c0688b-4b46-4cd0-86c3-c3a7dc536f5a)

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8e4701c0-c7eb-47cf-8f32-302b2d99fecc)

**Comment by JessicaMarine** [comment]
PO Review: 
* My Contact Info still showing on practitioner's dashboard:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a4e3f4ec-80e3-498e-8284-4fea51ab329e)
