### ISSUE TITLE
Docket and Petitions Clerk: Received Date NEEDED for certain Court-issued docs

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7601]
As a Docket and Petitions Clerk, in order to record the date we received certain documents, I need the ability to select a date received for certain Court-issued documents.

There are some documents  (e.g., returned mail, trial transcripts) that are considered Court-issued but are "received" by the Court.  These documents needs to be added to the docket record as of the date of receipt, not date of processing.

## Acceptance Criteria
* Docket Clerk and Petitions Clerk has the ability to enter a date received for certain Court-issued documents (isUnservable: true):

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/f4eab66f-c54d-4fba-ba04-e53b72b1f372)

* The date received is treated as the date filed on the docket record and cover sheet (*if* a cover sheet is applicable)

* When editing the Filed date on a docket entry for one of these event codes, the Filed date on the docket record should update with the updated date and a new coversheet with the updated date should replace the original coversheet. 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
ustaxcourt/ef-cms-flexion#7468

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
Event codes with isUnservable: true: 

CTRA
FTRL
HEAR
PTRL
TRL
ROA
RTRA
TRAN
HE
TE
USCA
ES
RM

**Comment by klohman** [comment]
### Add Court-Issued Docket Entry 

* Add "Filed date" field for these event codes:    
    * CTRA
    * FTRL
    * HEAR
    * PTRL
    * TRL
    * ROA
    * RTRA
    * TRAN
    * HE
    * TE
    * USCA
    * ES
    * RM
* Filed date should display when the document type has been selected and should appear below Service Parties 
* Filed date is required for these codes 

#### Example: Corrected Transcript 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea3adff9-68fd-4b5d-9d84-8ec8f349fc24)

#### Example: Returned Mail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/18e8f73d-2567-40f0-b30b-135d61c00819)

### On Save of Docket Entry 
* Docket entry is added to docket record 
* Filed date displays with date entered for Filed dAte 
* Docket entry is sorted on record by filed date 

**Coversheet**
These event code have a cover sheet generated on save:     
    * HE
    * TE
    * USCA
    * ES
    * RM

* Filed date entered on form displays as Filed Date on cover sheet; Received date is not displayed on coversheet

**Comment by klohman** [comment]
## 7440 Test Scenarios 

#### 1) Petitions / docket clerk enters Filed Date for [event code] when adding to the docket record 
* Login as petitions / docket clerk 
* Go to case 
* Upload PDF 
* Add Docket entry 
* Select document type: 
    * CTRA
    * FTRL
    * HEAR
    * PTRL
    * TRL
    * ROA
    * RTRA
    * TRAN
    * HE
    * TE
    * USCA
    * ES
    * RM
Expected results 
- [x] Filed date field displays when document type is selected
- [x] Filed date is required field 


#### 2) Petitions / docket clerk saves docket entry for [event code] with Filed date 
* Login as petitions / docket clerk 
* Go to case 
* Upload PDF 
* Add Docket entry 
* Select document type:
    * CTRA
    * FTRL
    * HEAR
    * PTRL
    * TRL
    * ROA
    * RTRA
    * TRAN
    * HE
    * TE
    * USCA
    * ES
    * RM
* Enter Filed date = 12/29/2020
* Save Entry 
Expected results 
- [x] Docket entry is added to the docket record 
- [x] Document title in Filings and Proceedings is concatenated properly (no changes) 
- [x] Filed date displays as = 12/29/20
- [x] Docket entry is sorted on docket record by filed date

#### 3) Petitions / docket clerk saves docket entry for [event code] with Filed date and views cover sheet
* Login as petitions / docket clerk 
* Go to case 
* Upload PDF 
* Add Docket entry 
* Select document type:
    * HE
    * TE
    * USCA
    * ES
    * RM
* Enter Filed date = 12/25/2020
* Save entry
* Click document link 
Expected results 
- [x] Cover sheet is added to document 
- [x]  Filed displays on cover sheet = 12/25/20
- [x] "Received" does not display on cover sheet

#### 4) Docket clerk edits Filed date for a docket entry 
* Scenario 3
* Login as docket clerk 
* Go to case from scenario 3 
* Click "edit" link for docket entry for USCA 
* Update Filed date to 12/31/2020
* Click Save 
Expected results 
- [x] A new Cover sheet is added to document with filed date 12/31/20 and replaces the original cover sheet- UPdate per Jessica - add second cover sheet for now
- [x] Docket entry filed date is updated 12/31/20 on Docket Record
