### ISSUE TITLE
IRS: Needs Ability to See Service Preference before being associated w/ case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7602]
As the IRS, in order to properly serve documents on petitioner(s), I need to know their service preference *before* being associated with the case.

## Pre-Conditions
* Case exists in the system.
* IRS practitioner is not associated

## Acceptance Criteria
~~* IRS can see the service preference of petitioner(s) and any Other party *before* being associated with the case, including sealed cases, but not sealed addresses.~~

**Updated AC**
* IRS practitioners who are not associated with a case can see all information under the Case Information tab 
* IRS practitioners who are not associated with a case see the public Docket Record and public Printable Docket 
* IRS practitioners who are not associated with a sealed case do not see any information on the sealed case (current functionality) 
* IRS practitioners who are not associated with a case do not see a sealed address 
* IRS practitioners who are associated with a case do not see a sealed address (current functionality - no change) 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* May want to review anything coming back in the API with these changes to make sure nothing is visible that should not be 

## Tasks
- [ ] Display all tabs under Case Information and all included data (Jojo, Matt, Kris)
  - [ ] Overview
  - [ ] Petitioner
  - [ ] Respondent
  - [ ] Other

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Updated Permission 

#### Unassociated IRS Attorney > Case Detail view 

**Docket Record**
* Unassociated IRS Attorney sees public docket record view (no changes) 

**Printable Docket Record**
* Unassociated IRS Attorney sees public docket record view (no changes) 

**Case Information**
* Display all tabs under Case Information and all included data
  * Overview 
  * Petitioner 
  * Respondent 
  * Other

**Comment by klohman** [comment]
## 7441 Test Scenarios 

#### IRS attorney views unassociated case (with no Respondent Counsel) 
* Login as irs attorney 
* Go to case 
    * Case has no respondent counsel 
* View Docket Record 
* View Printable Docket Record 
* View Case Information (Overview, Petitioner, Respondent, Other tabs)
Expected results 
- [x] File First IRS Document button displays
- [x] Docket record displays public docket record view (i.e. only Orders, Opinions are hyperlinked) 
- [x] Printable Docket Record displays public docket view 
- [x] Case Information > Overview displays all content 
- [x] Case Information > Petitioner displays all content 
- [x] Case Information > Respondent displays all content 
- [x] Case Information > Other displays all content 

#### IRS attorney views unassociated case (with at least one Respondent Counsel) 
* Login as irs attorney 
* Go to case 
    * Case has at least one respondent counsel 
* View Docket Record 
* View Printable Docket Record 
* View Case Information (Overview, Petitioner, Respondent, Other tabs)
Expected results 
- [x] Request Access button displays 
- [x] Docket record displays public docket record view (i.e. only Orders, Opinions are hyperlinked) 
- [x] Printable Docket Record displays public docket view 
- [x] Case Information > Overview displays all content 
- [x] Case Information > Petitioner displays all content 
- [x] Case Information > Respondent displays all content 
- [x] Case Information > Other displays all content 

#### IRS attorney views associated case 
* Login as irs attorney 
* Go to case 
    * Case is associated with IRS Attorney
* View Docket Record 
* View Printable Docket Record 
* View Case Information (Overview, Petitioner, Respondent, Other tabs)
Expected results 
- [x] File a Document button displays
- [x] Docket record displays parties view (all documents are hyperlinked)
- [x] Printable Docket Record displays party / internal view 
- [x] Case Information > Overview displays all content 
- [x] Case Information > Petitioner displays all content 
- [x] Case Information > Respondent displays all content 
- [x] Case Information > Other displays all content 

#### IRS attorney views unassociated sealed case 
* Login as irs attorney
* Search for sealed case 
Expected results 
- [x] No case information (except for docket number) is displayed 

#### IRS attorney views unassociated case with sealed address 
- [x] Docket record displays public docket record view (i.e. only Orders, Opinions are hyperlinked) 
- [x] Printable Docket Record displays public docket view 
- [x] Case Information > Overview displays all content 
- [x] Case Information > Petitioner displays all content except for the sealed address 
- [x] Case Information > Respondent displays all content 
- [x] Case Information > Other displays all content
