### ISSUE TITLE
Calendar: Set/Cut a Remote Trial Session (Must be done by early January 2021)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7603]
As a Petitions Clerk, I need to the ability to cut/set a remote trial session so that cases that have been QC'd are automatically set for trial.

## Pre-Conditions
* Remote trial session is on "New" tab

## Acceptance Criteria
* Petitions Clerk can check off cases that have been QC'd [Note: same functionality as in-person sessions]
* Petitions Clerk can "set" the remote trial session
* When a remote calendar is set:
   * The Notice of Trial (Zoomgov) should be generated in each case on the session
   * A Standing Pretrial Order should be generated in each *regular* case on the session [Note: new content for remote sessions]
   * A Standing Pretrial Order for Small Case should be generated in each *small* case on the session [Note: new content for remote sessions]
   * A docket entry should be created for each. 
* Certain fields are required before calendar can be cut (Highlighted in yellow in documents below)

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] **Setting Calendar for Remote Proceeding**  - mob
  - [x] Notice of Trial for Remote Proceeding ([pdf](https://app.zenhub.com/files/152320868/41b508ff-f0bf-4f21-a0f2-2b4a50a83f49/download)) - 
    - [x] PDF - mob ustaxcourt/ef-cms-flexion#7497
    - [x] Docket Entry - mob
  - [x] Standing Pre Trial Order for Regular Cases ([pdf](https://app.zenhub.com/files/152320868/f22847fb-e950-4875-961e-6266ef058e3c/download)) - mob
    - [x] PDF - mob ustaxcourt/ef-cms-flexion#7517
    - [x] Docket Entry - mob
  - [x] Standing Pre Trial Order for Small Cases ([pdf](https://app.zenhub.com/files/152320868/f0c0c652-c7fa-4207-b937-29d4927c24c8/download)) - mob
    - [x] PDF (Cody) - ustaxcourt/ef-cms-flexion#7523
    - [x] Docket Entry - mob ustaxcourt/ef-cms-flexion#7527

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
##  Trial Session Detail  

**Warning message** 
if  any of the following fields are blank when trying to set the calendar, display the alert message = "Provide remote proceeding information and judge to set this trial session."
* Meeting ID 
* Password 
* Join by telephone 
* Chambers phone number
* judge 

If judge field is blank, display warning = "Provide judge to set this trial session."

if  any of the following fields are blank when trying to set the calendar, display the alert message = "Provide remote proceeding information to set this trial session."
* Meeting ID 
* Password 
* Join by telephone 
* Chambers phone number

## Setting Calendar for Remote Proceeding 

When the calendar is set for a remote proceeding: 
* Case statuses update to “Calendared” and associated judge is updated to trial judge (same as in person session)

### Notice of Trial 

**Notice of Trial for remote proceeding PDF**
* Notice of Trial for remote proceeding is generated and added to docket record 
* Notice of Trial PDF displays content defined in PDF design - Notice Setting Case for Trial - Remote 
* This PDF should replace the current NTD (even for in person sessions)

**Notice of Trial for remote proceedings Docket Entry**
* Same as Notice of Trial for in person session
* Event code = NTD
* Filings and Proceedings = “ Notice of Trial on [mm/dd/yy] at [trial location] 

[https://app.zenhub.com/files/152320868/41b508ff-f0bf-4f21-a0f2-2b4a50a83f49/download](https://app.zenhub.com/files/152320868/41b508ff-f0bf-4f21-a0f2-2b4a50a83f49/download)

### Standing Pre Trial Order for Regular Cases 

When the calendar is set for a remote proceeding for Regular cases:

**Standing Pre Trial Order for Remote Regular PDF**
* Standing Pre Trial Order is generated and added to docket record 
*  PDF displays content defined in PDF design - Standing Pre Trial Order for Remote Regular PDF

**Standing Pre Trial Order for Remote Regular PDF Docket Entry**
* Same as Standing Pre Trial Order for in person session
* Event code = SPTO
* Filings and Proceedings = “Standing Pretrial Order”

[https://app.zenhub.com/files/152320868/f22847fb-e950-4875-961e-6266ef058e3c/download](https://app.zenhub.com/files/152320868/f22847fb-e950-4875-961e-6266ef058e3c/download)


### Standing Pre Trial Order for Small Case

When the calendar is set for a remote proceeding for Small cases:

**Standing Pre Trial Order for Remote Small PDF**
* Standing Pre Trial Order is generated and added to docket record 
*  PDF displays content defined in PDF design - Standing Pre Trial Order for Remote Small PDF

**Standing Pre Trial Order for Remote Small PDF Docket Entry**
* Same as Standing Pre Trial Order for in person session
* Event code = SPOS
* Filings and Proceedings = “Standing Pretrial Order for Small Case”

[https://app.zenhub.com/files/152320868/f0c0c652-c7fa-4207-b937-29d4927c24c8/download](https://app.zenhub.com/files/152320868/f0c0c652-c7fa-4207-b937-29d4927c24c8/download)

**Comment by klohman** [comment]
## 7443 Test Scenarios 

#### 1) Petitions clerk sets the calendar for a remote session without remote proceeding information 
* Test Data 
    * Create remote session for “New Orleans, LA
    * Session type = Regular
    * leave one or more fields blank 
        * Meeting ID
        * Password 
        * Join by telephone number 
        * Chambers Phone number 
* Login as petitioners clerk 
* Go to remote New Orleans session 
* Click Set Calendar 
Expected results 
- [x] Warning message displays “Provide remote proceeding information to set this trial session."


#### 2) Petitions clerk sets the calendar for a remote session without judge or remote proceeding information 
* Test Data 
    * Create remote session for “Denver, CO
    * Session type = Small
    * leave one or more fields blank 
        * Meeting ID
        * Password 
        * Join by telephone number 
        * Chambers Phone number 
    * Leave judge field blank
* Login as petitioners clerk 
* Go to remote Denver, CO session 
* Click Set Calendar 
Expected results 
- [x] Warning message displays “Provide remote proceeding information and judge to set this trial session."

#### 3) Petitions clerk sets the calendar for a remote session without judge 
* Test Data 
    * Create remote session for Hartford, Connecticut
    * Session type = Hybrid
    * leave one or more fields blank 
        * Meeting ID
        * Password 
        * Join by telephone number 
        * Chambers Phone number 
    * Leave judge field blank
* Login as petitioners clerk 
* Go to remote Hartford, Connecticutsession 
* Click Set Calendar 
Expected results 
- [x] Warning message displays “Provide judge to set this trial session."

#### 4) Petitions clerk sets the calendar for a remote session with Regular cases 
* Scenario 1 
* Enter remote proceedings information
* Check “QC Complete” for cases
    * One paper service 
    * One electronic service 
* Set Calendar 
Expected results 
- [x] App routes to print paper service screen 
- [x] Print paper service PDF contains address cover sheet, Notice of Trial, and Standing Pre Trial Order for paper service parties 
- [x] Parties with electronic service receive service email for Notice of Trial and Standing Pre Trial Order 
- [x] Case statuses update to Calendar with trial judge as associated judge 
- [x] Notice of Trial is added to docket record for all cases 
- [x] Standing Pretrial Order is added to docket record for all cases 
- [ ] Session is displayed in the Trial sessions > Open tab with Notice Issued date [current date]

#### 5) Petitions clerk sets the calendar for a remote session with Small cases
* Scenario 2
* Enter remote proceedings information and judge
* Check “QC Complete” for cases
    * One electronic service 
* Set Calendar 
Expected results 
- [x] App routes to Trial session list with success message displays  
- [x] Parties with electronic service receive service email for Notice of Trial and Standing Pre Trial Order for Small Case
- [x] Case statuses update to Calendar with trial judge as associated judge 
- [x] Notice of Trial is added to docket record for all cases 
- [x] Standing Pretrial Order for Small Case is added to docket record for all cases 
- [x] Session is displayed in the Trial sessions > Open tab with Notice Issued date [current date]

#### 6) Petitions clerk sets the calendar for a remote session with hybrid cases
* Scenario 3
* Enter judge
* Check “QC Complete” for cases
    * One Small case
    * One Regular  
* Set Calendar 
Expected results 
- [x] App routes to Trial session list with success message displays  
- [x] Parties with electronic service receive service email for Notice of Trial and Standing Pre Trial Order or Standing Pre Trial Order for Small Case
- [x] Case statuses update to Calendar with trial judge as associated judge 
- [x] Notice of Trial is added to docket record for all cases 
- [x] Standing Pretrial Order is added to docket record for small case 
- [x] Standing Pretrial Order for Small Case is added to docket record for small case 
- [x] Session is displayed in the Trial sessions > Open tab with Notice Issued date [current date]

#### 7) Internal user / party views docket entry for Notice of Trial for remote session 
* Scenario 4
* Login as internal user / party to case 
* Go to case set for New Orleans remote session 
* View Notice of Trial PDF 
Expected results 
- [x] Docket entry for Notice of Trial is generated on docket record 
- [x] Docket entry displays as 
    - Filed = [today’s date]
    - Event code = NTD
    - Filings and proceedings = Notice of Trial on [mm/dd/yy] at [trial location] 
    - Served [today’s date]
    - Parties = B
- [x] Notice of Trial PDF matches design content with placeholders replaced with entered metadata

#### 8) Internal user / party views docket entry for Standing Pretrial Order for remote session 
* Scenario 4
* Login as internal user / party to case 
* Go to case set for New Orleans remote session 
* View Standing Pretrial Order PDF 
Expected results 
- [x] Docket entry for Standing Pretrial Orderl is generated on docket record 
- [x] Docket entry displays as 
    - Filed = [today’s date]
    - Event code = SPTO
    - Filings and proceedings = Standing Pretrial Order
    - Served [today’s date]
    - Parties = B
- [ ] Standing Pretrial Order PDF matches design content with placeholders replaced with entered metadata

#### 9) Internal user / party views docket entry for Standing Pretrial Order for remote session 
* Scenario 5
* Login as internal user / party to case 
* Go to case set for Denver remote session 
* View Standing Pretrial Order for Small Case PDF 
Expected results 
- [x] Docket entry for Standing Pretrial Order for Small Case is generated on docket record 
- [x] Docket entry displays as 
    - Filed = [today’s date]
    - Event code = SPOS
    - Filings and proceedings = Standing Pretrial Order for Small Case
    - Served [today’s date]
    - Parties = B
- [ ] Standing Pretrial Order for Small Case PDF matches design content with placeholders replaced with entered metadata

**Comment by sutt0n** [comment]
Marked as blocked since its work is dependent on ustaxcourt/ef-cms#7087

**Comment by klohman** [comment]
## UX Review 

### SPOS Feedback 

* In Technology section - there should be a comma before the www.ustaxcourt.gov link
![Screen Shot 2021-01-08 at 3.37.29 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cdfdbc8f-9a0a-47d5-aad8-eac562e12f69)

* Date should be left aligned 
* Judge's name shouldn't wrap 
![Screen Shot 2021-01-08 at 3.36.46 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4acffeca-5cca-43b3-bc5b-673840dd8565)

* Pages 4 - 7 should not have the header (docket number and page count) 
![Screen Shot 2021-01-08 at 3.36.55 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/bfc3e123-b867-496f-9718-7fd39450ae2f)


* Need more space between checkbox and text 
![Screen Shot 2021-01-08 at 3.40.14 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b3cff74a-a5e6-4026-b364-69a59a2bb7bc)

* Last checkbox - www.ustaxcourt.gov should be a link (I missed that in the design) 
![Screen Shot 2021-01-08 at 3.41.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/82d0ab66-3d46-48ef-b069-e36762a1a290)

* Respondent telephone number line shouldn't break; all the fields here for Petitioner and Respondent should align 
![Screen Shot 2021-01-08 at 3.42.22 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7ccc7aa0-3eb8-4f61-b9cc-2c8e5186a2a7)

* There is almost a full page of space between Issues and Witnesses - we dont need that much space. 

![Screen Shot 2021-01-08 at 3.43.48 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f9d699f2-6440-4062-ba19-255c4ccc4f22)

**Comment by klohman** [comment]
## UX review 

### SPTO feedback

* Date should be left aligned and judge name should not wrap 
![Screen Shot 2021-01-08 at 3.55.01 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/130d1b96-cd27-4ccf-8f5a-e1aae7886a65)

* Pages 4 - 5 should not have the header (docket number and page count) 
![Screen Shot 2021-01-08 at 3.58.08 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/7306a32c-cbce-44bf-b7b2-781b7b7f7cf7)

* Page 4 - need more space between Attorneys and Petitioner 
* The text lines should not break in this section 
![Screen Shot 2021-01-08 at 3.58.47 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a4cf438c-5f62-4ba2-9546-765abf71dc5e)

* Need more padding below "Amounts in Dispute" 
![Screen Shot 2021-01-08 at 4.00.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1c01a003-c747-4ffc-bf1c-336b04614261)

**Comment by JessicaMarine** [comment]
Backlogged some minor content changes in ustaxcourt/ef-cms#7650
