### ISSUE TITLE
Admissions Clerk: Edit Practitioner profile when no email

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7605]
As an Admissions Clerk, I need the ability to edit a practitioner's information even when they don't have an email address.

## Pre-Conditions
* Practitioner profile exists without email address

## Acceptance Criteria
* Admissions Clerk can edit a practitioner's information even when they don't have an email address.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Allow edit of practitioner profile when no email - mob #/7644

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
#### 1) Admission clerk edits practitioner information for practitioner without email. 
* Login as admissions clerk 
* Search for practitioner without email 
* Click Edit 
* Edit any field 
* Save  
Expected results 
- [x] No error message displays 
- [x] App routes back to Practitioner Detail with success message displayed 
- [x] Updates are saved and displayed
