### ISSUE TITLE
View Counsel Information on Printable Docket Record (Tom)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7616]
As a public user, internal user, party to the case, or petitioner, in order to know who the counsel of record is on the case, I need to see counsel information on the printable docket record.

This has also been requested by the IRS (1/5/2021): The Service’s Office of Appeals was accustomed to being able to access petitioner counsel contact information as part of the publicly facing information in eAccess.  This facilitates their ability to reach out to petitioners early in the lifecycle of a case for settlement purposes.  As I understand, the outreach sometimes occurs before a case is answered or the referral from Counsel is received by Appeals.

## Pre-Conditions
* Parties have Counsel

## Acceptance Criteria
* Petitioner's Counsel's information is available on all printable docket records (internal, party, public)
* Respondent's Counsel's information is available on all printable docket records (internal, party, public)
* If there are no Petitioner's Counsel or Respondent's Counsel, those blocks should display "None"

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks

- [x] add Petitioner Counsel card to public printable docket record template
- [x] add Respondent Counsel card  to public printable docket record template
- [x] internal printable docket record shows "pro se" if no private practitioner  (both public and internal)
  - [x] on public interactor
  - [x] on internal interactor
- [x] internal shows "none" if no IRS practitioner (both public and internal)
  - [x] on public interactor
  - [x] on internal interactor

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
## Printable Docket Record (Public) 


### With Counsel 
* Display card for Petitioner Counsel 
* Display card for Respondent Counsel 
* Hide Petitioner Contact Info card 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9091f3ca-833e-44f8-9d25-0a646da39c63)


### WIthout Counsel 
* Display card for Petitioner Counsel with "Pro Se" in body
* Display card for Respondent Counsel with "None" in body
* Hide Petitioner Contact Info card 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fc964cee-df98-47e0-bb9d-e1b3bc64b79c)

## Internal / Parties View of Printable Docket Record 

### With Counsel 
* No changes to current UI 

### Without Counsel 
* Display card for Petitioner Counsel with "Pro Se" in body
* Display card for Respondent Counsel with "None" in body
* Display Petitioner Contact Info card 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/639a39d1-3e76-4871-bb25-5b6e642bd0d3)

**Comment by klohman** [comment]
## 7470 

#### 1) Public user views Printable Docket Record for case with petitioner and respondent counsel 
* Go to public search 
* Go to case with both petitioner and respondent counsel 
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays on Printable Docket Record 
- [x] Respondent counsel contact card displays on Printable Docket Record 
- [x] Petitioner contact card does not display on Printable Docket Record 

#### 2) Public user views Printable Docket Record for case with petitioner counsel only
* Go to public search 
* Go to case with petitioner counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card does not display on Printable Docket Record 

#### 3) Public user views Printable Docket Record for case with respondent counsel only
* Go to public search 
* Go to case with  respondent counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays on Printable Docket Record 
- [x] Petitioner contact card does not display on Printable Docket Record 

#### 4) Public user views Printable Docket Record for case with no counsel 
* Go to public search 
* Go to case with no counsel 
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card does not display on Printable Docket Record 

#### 5) Internal user views Printable Docket Record for case with petitioner counsel only
* Login as internal user 
* Go to case with petitioner counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card displays on Printable Docket Record 

#### 6) Internal user views Printable Docket Record for case with respondent counsel only
* Login as internal user 
* Go to case with respondent counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays on Printable Docket Record 
- [x] Petitioner contact card displays on Printable Docket Record 

#### 7) Internal user views Printable Docket Record for case with no counsel 
* Login as internal user 
* Go to case with no counsel 
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card displays on Printable Docket Record 

#### 8) Party user views Printable Docket Record for case with petitioner counsel only
* Login as petitioner  
* Go to case (associated) with petitioner counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card displays on Printable Docket Record 

#### 6) party user views Printable Docket Record for case with respondent counsel only
* Login as petitioner
* Go to case (associated) with respondent counsel only
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays on Printable Docket Record 
- [x] Petitioner contact card displays on Printable Docket Record 

#### 7) Party user views Printable Docket Record for case with no counsel 
* Login as petitioner
* Go to case (associated) with no counsel 
* Click Printable Docket Record 
Expected results 
- [x] Petitioner counsel contact card displays “Pro Se” on Printable Docket Record 
- [x] Respondent counsel contact card displays “None” on Printable Docket Record 
- [x] Petitioner contact card display on Printable Docket Record

**Comment by TomElliottFlexion** [comment]
@klohman Do we need to update the AC to reflect replacing an empty Petitioner's Counsel block with 'Pro Se' instead of 'None'?
