### ISSUE TITLE
Docket: Ability to QC items from the docket record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7621]
As a Docket Clerk, so that I can quickly QC any item pending in a case, I need the ability to QC items from the Docket record.

Currently, the only way a Docket Clerk can QC something is from the QC box.  Due to ES limits, we only return the first 1,000 items, so there may be times when something needs to be QC'd but is not showing in that top 1,000.  Docket has no way to QC it.  Additionally, there may be times were more than 1 one item is waiting to be QC'd in a case.  It is cumbersome for a Docket Clerk to have to search through the QC box to find each item individually.

## Pre-Conditions
* Case has one or more items waiting to be QC'd

## Acceptance Criteria
* When Docket Clerk clicks on an non-QC'd item from the docket record, it takes them to the QC page.
* Docket Clerk is able to complete full QC process at this point.
* When any other user clicks on an non-QC'd item from the docket record, it takes them to the document view.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Should this apply to documents in the Document "In-Progress" box as well? For example, a paper-filing or court-issued doc that is saved to docket record but not served? (Consider doing, but not part of this story)
* Does Docket need something similar to the Document View for non-QC'd items? View PDF option? (Not for this story)

## Tasks
- [x] Display QC Pending icon - red star in Document View list for documents that have not been QC'd (Themis Mob ustaxcourt/ef-cms-flexion#7820)
- [x] Add Complete QC Button (Themis Mob ustaxcourt/ef-cms-flexion#7821)
    - [x] Only display for docketClerks (Themis Mob ustaxcourt/ef-cms-flexion#7821)
    - [x] Only display when document has not been QCd (Themis Mob ustaxcourt/ef-cms-flexion#7821)
    - [x] On click of Complete QC link, route to Document QC screen for the selected document

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Docket Record 

**On click of document link, route to Document QC screen**
* If user is Docket Clerk 
* If document has not been QC’d

**On click of document link, route to Document View with selected document in PDF preview **
 * If user is any other role except Docket Clerk
* If document has not been QC’d
* If document has been QC’d


## Document View  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5f05b5a8-70c4-4151-ad1d-1f0fd033c481)
* Display QC Pending icon - red star in Document View list for documents that have not been QC'd


**Complete QC button**
* Needs to be button and not link 
* On click of Complete QC link, route to Document QC screen for the selected document

**Display “Complete QC” link in document actions**
* If user is Docket Clerk 
* If document has not been QC’d

**Do not display “Complete QC” link **
 * If user is any other role except Docket Clerk

**Do not display “Complete QC” link **
 * If user is Docket Clerk
* If document has been QC’d

**Comment by klohman** [comment]
## 7476 Test Scenarios 

#### 1) Docket clerk accesses QC screen from docket record for an e-filed document that has not been QC’d
* Login as petitioner 
* Go to case xx1-21
* e-file document = Administrative Record
* Login as docket clerk 
* Go to case xx1-21 
* Click Administrative record link from Docket record 
Expected results 
- [x] Docket entry for Administrative record displays with red star icon and bold text on Docket Record 
- [x] On click of Administrative Record link, app displays Document View with selected document displayed in PDF preview 
- [x] “Complete QC” link displays on Document View for Administrative Record 

#### 2) Docket clerk completes QC from Docket Record for an e-filed document that has not been QC’d
* Scenario 1 
* Click Complete QC link 
* Click Complete button 
* Navigate to csae xx1-21
Expected results 
On click of “Complete QC” link 
- [x] app routes to Document QC screen for the Administrative Record 
On click of Complete button, 
- [x] App routes to My Document QC Inbox (current behavior) 
- [x] Administrative Record for case xx1-21 no longer displays in Section Document QC / My Document QC Inbox 
- [x] Administrative Record for case xx1-21  displays in Section Document QC / My Document QC Processed box
- [x] Docket entry for Administrative record no longer displays with red star icon and bold text on Docket Record 

#### 3) Docket clerk cannot access QC screen from docket record for an e-filed document that has been QC’d
* Login as petitioner 
* Go to case xx2-21
* e-file document = Motion for New Trial
* Login as docket clerk 
* Complete QC for Motion for New Trial 
* Login as docket clerk 2
* Go to case xx2-21
* Click link for Motion for New Trial from docket record
Expected results 
- [x] Docket entry for Motion for New Trial no longer displays with red star icon and bold text on Docket Record 
- [x] “Complete QC” link does not display on Document View for Motion for New Trial 

#### 4) Internal user (other than docket clerk) cannot access QC screen from docket record for an e-filed document that has not been QC’d
* Login as petitioner 
* Go to case xx2-21
* e-file document = Motion for Continuance 
* login as petitions clerk 
* Go to casee xx2-21 
* Click link for Motion for Continuance 
- [x] Docket entry for Motion for Continuance displays with red star icon and bold text on Docket Record 
- [x] “Complete QC” link does not display on Document View for Motion for Continuance

#### 4) Internal user (other than docket clerk) cannot access QC screen from docket record for an e-filed document that has been QC’d
* Scenario 2 
* Login as internal user 
* Go to case xx1-21
* Click on Administrative Record 
Expected results 
- [x] Docket entry for Administrative record no longer displays with red star icon and bold text on Docket Record 
- [x] “Complete QC” link does not display on Document View for Administrative Record
