### ISSUE TITLE
Add/edit note on trial card after case is scheduled (Dave)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7641]
As a Docket Clerk, I need the ability to add/edit a calendar note without removing and re-adding the case.

## Pre-Conditions
* Case has been set for trial

## Acceptance Criteria
Revised:
* Docket clerk has the ability to add a calendar note on a trial after adding the case to the trial
* Docket clerk has the ability to edit a calendar note on a trial 
* Docket clerk has the ability to delete a calendar note on a trial 
* When a docket clerk adds a calendar note after the case is added to trial, the calendar note displays on the Trial Session screen and the Printable Trial Session PDF 
* When a docket clerk edits a calendar note after the case is added to trial the updated calendar note displays on the Trial Session screen and the Printable Trial Session PDF 
* When a docket clerk deletes a calendar note for a trial, the calendar note no longer displays on the Trial Session screen and the Printable Trial Session PDF

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* current limit for note field 200 characters
* Assumption- any user with Add to Trial/ Hearing permission has permission to edit note 
* Assumption- only one note can exist per trial / hearing 

## Tasks
- [x] 1 on Case Detail / Case Information / Trial information card: replace the “Remove” action with the Edit Menu (on Calendared and Scheduled views) - team mob ustaxcourt/ef-cms-flexion#7825
- [x] 2 connect “Remove” menu item to original remove sequence - team mob ustaxcourt/ef-cms-flexion#7825
- [x] 3 create “Add/Edit Calendar Note” modal - team mob ustaxcourt/ef-cms-flexion#7829
- [x] 4 create add/edit calendar note sequence - team mob ustaxcourt/ef-cms-flexion#7832
- [x] 5 validate newly added or edited calendar note for trial session - team mob ustaxcourt/ef-cms-flexion#7830
- [x] 6 ability to delete a calendar note ustaxcourt/ef-cms-flexion#7835
  - [x] Modal has Delete Note ONLY when adding or editing note to trial ustaxcourt/ef-cms-flexion#7835
- [x] 7 create saveCalendarNoteSequence - team mob ustaxcourt/ef-cms-flexion#7832
- [x] 8 add calendarNote to entity and persistence - team mob ustaxcourt/ef-cms-flexion#7832
- [x] 9 New/updated calendar note displays on Trial Session Detail and Printable Trial Session Detail - team mob ustaxcourt/ef-cms-flexion#7832
- [x] 10 Deleted calendar note no longer displays on Trial Session Detail and Printable Trial Session Detail ustaxcourt/ef-cms-flexion#7835
- [x] 11 Set the calendar note in the state after adding/editing (without needing to refresh case detail) - team mob ustaxcourt/ef-cms-flexion#7834

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by cnelsonflexion** [comment]
![default.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/6011875f-7630-4de0-ada6-5786a7976ebc)

![Trial-ScheduledDefault.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/1dbfcec6-8a79-45a7-a6dc-3bff41c2d213)

Default view of Calendared and Scheduled Trial

**Comment by cnelsonflexion** [comment]
![trial-editmenu.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/a4b3747a-9f6a-4041-a0a9-33560a35bfcc)

Trial card - edit menu

**Comment by cnelsonflexion** [comment]
![trial-addeditnote.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/c35a921b-6d30-4039-b098-0cab80024c7e)

Trial card - Add/edit modal

**Comment by cnelsonflexion** [comment]
Test Scenarios 

#### 1) Docket Clerk adds a case to trial and then adds a calendar note 
* Login as docket clerk 
* Go to case 
   - Case status = Calendared 
* Click Edit link for trial card
* Click Add/Edit Calendar Note 
* Enter text in note field 
* Click Save
Expected results 
On click of Edit link: 
- [x] Edit menu options display
On click of Add/Edit Calendar Note 
- [x] Add/Edit Calendar Note modal displays 
On click of Save 
- [x] Modal closes 
- [x] Note text displays on the Trial Card 

#### 2) Docket Clerk adds a case to trial with calendar note and then edits note
* Scenario 1 
* Click Add / Edit Calendar Note 
* Update text in note field 
* Click Save 
Expected results 
On click of Add/Edit Calendar Note 
- [x] Add/Edit Calendar Note modal displays 
- [x] Note field is populated with current note text 
On click of Save 
- [x] Modal closes 
- [x] Updated note text displays on the Trial Card 

#### 3) Docket Clerk adds a trial note, if character validation fails, display error message: Limit is 200 characters. Enter 200 or fewer characters.
* Login as docket clerk 
* Go to case 
* Click Add to Trial 
* Enter text in note field = 201 characters 
* Click Add to Trial button 
Expected results 
- [x] Error message displays on note field : “Limit is 200 characters. Enter 200 or fewer characters.”

#### 4) Docket Clerk edits a trial note, if character validation fails, display error message: Limit is 200 characters. Enter 200 or fewer characters.
* Login as docket clerk 
* Go to case 
* Click Add to Trial 
* Enter text in note field = 200 characters 
* Click Add to Trial button 
* Click Add/Edit Calendar note 
* Update text in note field = 201 characters
Expected results 
- [x] Error message displays on note field : “Limit is 200 characters. Enter 200 or fewer characters.”


#### 7) Docket Clerk adds a case to trial, then adds a calendar note and views note on Trial Session screen
* Login as docket clerk 
* Go to case 
   - Case status = Calendared
* Click Edit link, and Add/Edit Calendar Note 
* Enter text in note field 
* Click Save
* Click trial location link on trial card 
Expected results 
- [x] App routes to Trial Session Detail 
- [x] Calendar Note displays on case list table 

#### 8) Docket Clerk adds a case to trial, then adds a calendar note and views note on Printable Trial Session
* Scenario 7 
* Click Print link on Trial Session Detail 
Expected results 
- [x] App routes to Printable Trial Session PDF  
- [x] Calendar Note displays on the Printable Trial Session PDF

#### 9) Docket Clerk adds a case to trial, then adds a calendar note, and then edits note and views note on Trial Session screen
* Scenario 7 
* Click Add/Edit Calendar Note 
* Update note text 
* Save 
* Go to Trial Session and view case list 
Expected results 
- [x] Updated Calendar Note displays on case list table 

#### 10) Docket Clerk adds a case to trial, then adds a calendar note, and then edits note and views note on Printable Trial Session
* Scenario 9 
* Click Print link on Trial Session Detail 
Expected results 
- [x] App routes to Printable Trial Session PDF  
- [x] Calendar Note displays on the Printable Trial Session PDF


#### 11) Docket Clerk adds a case to trial (not yet calendared) and then adds a calendar note 
* Login as docket clerk 
* Go to case 
   - Case status = Scheduled for trial 
* Click Edit link for trial card
* Click Add/Edit Calendar Note 
* Enter text in note field 
* Click Save
Expected results 
On click of Edit link: 
- [x] Edit menu options display
On click of Add/Edit Calendar Note 
- [x] Add/Edit Calendar Note modal displays 
On click of Save 
- [x] Modal closes 
- [x] Note text displays on the Trial Card

**Comment by cnelsonflexion** [comment]
![Screen Shot 2021-02-23 at 11.41.08 AM.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/00e4a622-2c89-442b-8131-f2e2234e609a)

Dropdown menu links should have text decoration "underline" on hover state.

Reference:

![Screen Shot 2021-02-23 at 11.41.17 AM.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/c4167b02-c6c0-4048-9c09-08f778d5f236)
