### ISSUE TITLE
PR 60-61 Manual Testing

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7655]
Manual user testing to be performed during Sprint . 

## Acceptance Criteria

AC 1) Team has performed manual testing on the Flexion prod environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing
* External parties workflows 
* Mobile

## Tasks 
**External parties workflows**

- [x] 1) eFile a petition (as petitioner) 
- [x] 2) eFile a petition (as practitioner)
- [x] 3) File a Document (Primary document and Supporting Document) - petitioner 
- [x] 4) File a Document (Primary and Secondary Document with Supporting Document ) - petitioner 
- [x] 5) File a Document (practitioner)
- [x] 6) Request Access to Case - automatically associated (practitioner)
- [x] 7) Request Access to Case - not automatically associated (practitioner)
- [x] 8) File First IRS Document (irs pracititoner)
- [x] 9) Request Access to Case (second irsPractitioner on case) - (irs practitioner)
- [x] 10) Petitioner edits contact information
- [x] 11) Practitioner edits contact information (private practitioner)
- [x] 12) Practitioner edits contact information (irs practitioner)

**Mobile**
- [x] 115) MOBILE: eFile a petition (as petitioner)
- [x] 116) MOBILE: eFile a petition (as practitioner)
- [x] 117) MOBILE: File a Document (Primary document and Supporting Document) - petitioner
- [x] 118) MOBILE - File a Document (practitioner)
- [x] 119) MOBILE: Request Access to Case - automatically associated (practitioner)
- [x] 120) MOBILE: File First IRS Document (irs pracititoner) 
- [x] 121) MOBILE: Request Access to Case (second irsPractitioner on case) - (irs pracititoner)
- [x] 122) MOBILE: Petitioner edits contact information
- [x] 123) MOBILE: Practitioner edits contact information (private practitioner)
