### ISSUE TITLE
Admissions Clerk: Ability to Update Practitioner Email Address

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7658]
## Pre-Conditions
* Practitioner exists in DAWSON with an email address

## Acceptance Criteria
* Admissions Clerk has the ability to edit a practitioner's email address
* Practitioner is provided new credentials to access DAWSON [See note below]
* Practitioner must verify their new email address
* Practitioner is able to log-in and access their cases with the new email after it's verified
   * Ensure that the practitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
   * Practitioner can eFile documents in cases
* Practitioner's email is updated after email verification on all of the cases the practitioner is on
* Practitioner's service preference remains as electronic
* Practitioner receives service emails at the new service email address after the email is verified
* Admission clerk must enter new email twice when adding an email for a practitioner 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
**Admissions clerk adds new email to existing practitioner without an email**
* Handling error validation on the form in this story 
* Not handling any changes to the email flow for when adding a new email to existing practitioner - that's been added to ustaxcourt/ef-cms#7695

## Tasks
- [x] 1 Practitioner detail - remove alternate email field - Team mob ustaxcourt/ef-cms-flexion#7736
- [x] 2 Edit Practitioner detail
  - [x] 2a Remove alternate email field - Team mob ustaxcourt/ef-cms-flexion#7736
  - [x] 2b Add new section labelled “Login & Service email” - Team mob ustaxcourt/ef-cms-flexion#7737
  - [x] 2c Validation for login and service email - Team mob ustaxcourt/ef-cms-flexion#7739
  - [x] 2d Add API call to make sure email does not already exist in Cognito - Team mob ustaxcourt/ef-cms-flexion#7740
- [x] 3 Verification modal - Team mob ustaxcourt/ef-cms-flexion#7742
- [x] 4 Update API to handle pending email update and sending verification email - Cody, Tom, Rae
- [x] 5 On success, display success message on practitioner detail
- [x] 6 Edit Practitioner detail with pending email address - Mrin, Rachael ustaxcourt/ef-cms-flexion#7745
- [x] 7 Edit Practitioner detail with no email address - display Not provided for current email address - Mrin, Rachael ustaxcourt/ef-cms-flexion#7745

Refactoring 
- [x] 1 Clean up - we probably do not need to persist updatedEmail or confirmEmail ustaxcourt/ef-cms-flexion#7753

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Practitioner Detail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/47e4e383-3384-408f-ba48-1ded11335f65)

* Remove alternate email field 

## Edit Practitioner Detail
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ff13cb87-98aa-4b29-b475-35d12780d992)

* Remove alternate email field 

### Login & Service Email 
* Add new section labelled “Login & Service email” 

**Current email address**
* Move the email address field to new Login & Service section 
* Update field label to “Current email address**
* display the current login/service email as read-only 

#### Change Login & Contact Email 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display verify email modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* Old email is still valid
* New email is not yet valid 

## Verification Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2daebd91-1766-4489-ac45-6279b526cf56)
* Display on Save 
* On click of OK, app routes to Practitioner Detail screen with success message displayed 

* Old email displays on Practitioner Detail and in all associated cases 

## New email is not verified - Practitioner Detail 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f2df4e00-c33f-46f6-941b-78c40727d5f6)

* Old email displays in Practitioner Detail until new email is verified 
* Old email displays in all practitioner cases until new email is verified 

## New email is not verified - Edit Practitioner screen 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a38b5442-465e-47da-bd0d-2615593f097f)
**Pending email field**
* Display pending email as read-only 


# Add Email to Existing Practitioner that has no email 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3ac84018-7940-4a34-a412-b3a7df51317f)

* Display “Not provided” in current email field

#### Add Login & Contact Email 

* Display “Add Login & Service email” fields 

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save

**Display verify email modal**

**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* email cannot already exist - Error message “An account with this email already exists. Enter a new email address.”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”

**New email is saved as pending**
* Verification email is sent to new email 
* New email is not yet valid 
* Practitioner still displays “Not provided” in Practitioner Detail and in all associated cases 

## Verification Modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b8b58e2e-b398-4237-abe9-2ff89ffacb5b)


 ## Edit Practitioner  when email is pending 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a8160f34-adfc-4a8f-ab44-0d20ea7fdd11)

**Pending email field**
* Display pending email as read-only

**Comment by klohman** [comment]
## 7574

#### 1) Admissions clerk sees Login & Service information for practitioner 
* Login as admissions clerk 
* Go to Advanced Search > Practitioner 
*  Search for practitioner 
    * flexionustc+practitioner@gmail.com
* Click Edit link on practitioner detail screen
Expected results  
- [x] Edit Practitioner screen displays Login & Service email card 
- [x] current email displays under Current email address field 


#### 2) Admissions clerk updates email and saves form with invalid email address 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner 
    * flexionustc+practitioner@gmail.com
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 3) Admissions clerk updates email and saves form with duplicate email address 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner 
    * flexionustc+practitioner@gmail.com
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Save
Expected results 
- [x] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 4) Admission clerk updates email and enters non-matching email on confirmation 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner 
    * flexionustc+practitioner@gmail.com
* Update email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save
Expected results 
- [x] Error displays on email field -  “Email addresses do not match.”


#### 5) Admissions clerk updates email and saves form with valid email address 
* Go to Advanced Search > Practitioner 
*  Search for practitioner 
* Update email address 
* Click Save 
Expected results 
On click of Save 
- [x] Verify email modal displays 
- [x] On click of OK on modal, App routes to Practitioner Detail  screen with success message displayed 
- [x] Verification email is sent to new email 
- [x] Old email is still valid 
- [x] old email still displays on Practitioner Detail
- [x] old email still displays under all cases
- [x] old email still receives service 

#### 6) Admissions clerk updates email and saves form with valid email address 
* Scenario 5 
* Login as practitioner with old email (from scenario 5)
Expected results 
- [x] Old email is still valid 
- [x] Practitioner View old email still displays under Login & Service email
- [x] Practitioner old email still displays under all cases
- [x] Global warning message displays 

#### 7) Admissions clerk updates email and practitioner files a document before verifying new email 
* Scenario 6 
* Go to case 
* File a Motion for New Trial 
Expected results 
- [x] Motion for New Trial is added to Docket Record 
- [x] New email address does not receives service email 
- [x] Old email does receives service email 

#### 8) Admissions clerk updates email and practitioner cannot login with new email address before verifying email
* Scenario 5
* Login as practitioner with new email 
   
Expected results 
- [x] User sees error on login for invalid credentials 

#### 9) Admissions clerk updates email and practitioner receives service for court-issued document at old email before verifying new email 
* Scenario 5 
* Login as docket clerk 
* Go to case 
* Create, sign and serve Order to Show Cause 
Expected results 
- [x] order to show cause is added to Docket Record 
- [x] New email address does not receive service email 
- [x] Old email receives service email 
  
#### 10) Practitioner verifies email when not logged in to system 
* Scenario 5 
*  Log out of system 
* Go to practitioner new email 
* Click verify email link
Expected results 
On click of verify 
- [x] user is routed to "You Must be Logged In" screen with instructions
- [x] user can log in with old email 
- [x] user cannot log in with new email 

#### 11) Practitioner verifies new email and logs in with new email 
* Scenario 5
* Login as practitioner (with old email) 
* Go to gmail 
* Click Verify Email link 
* Click login on success page
* Login as practitioner (with new email)
 
Expected results 
On click of verification link:
- [x] User is routed to Email Verified success page 
On login: 
- [x] Login is successful 
- [x] App displays new email on My Account> Login & Service email and in all associated cases 
- [x] Global warning message is not displayed

#### 12) Practitioner verifies new email and files a document 
* Scenario 11 
* Go to case
* File a Document 
    * Administrative Record 
* Submit document
Expected results 
- [x] Administrative Record is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 13) Practitioner verifies new email and receives service email for court-issued document 
* Scenario 11 
* Login as docket clerk 
* Go to case 
    * Case has practitioner from scenario 5 
* Create, sign and serve Decision 
Expected results 
- [x] Decision is added to the docket record 
- [x] new email receives service email 
- [x] Old email does not receive service email 

#### 14) Practitioner verifies new email and cannot log in with old email 
* Scenario 11 
* Login to system with old email

Expected results 
- [x] Login is unsuccessful and error message is displayed


## Adding new email to practitioner without email in DB

#### 15) Admissions clerk adds invalid email to existing practitioner without email
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner without email 
* Update email address = notvalid@
* Click Save 
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 16) Admissions clerk adds duplicate email to existing practitioner without email 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner without email
* Update email address = petitioner1@example.com
* Click Save 
* Re-enter matching email = petitioner1@example.com
* Click Save
Expected results 
- [x] Error displays on email field - “An account with this email already exists. Enter a new email address.”

#### 17) Admissions clerk adds email and enters non-matching email to practitioner without email 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner without email
* Update email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save
Expected results 
- [x] Error displays on email field -  “Email addresses do not match.”

#### 18) Admissions clerk adds email to existing practitioner and saves form with valid email address 
* Login as admissions clerk
* Go to Advanced Search > Practitioner 
*  Search for practitioner without email
Expected results 
- [ ] New account email is sent to email 
- [ ] Practitioner email is added to account 
- [ ] Practitioner email displays in Practitioner detail 
- [ ] Practitioner emails displays in all cases

**Comment by klohman** [comment]
UX Feedback

* To test adding a new email to a practitioner with no email - is there a practitioner on dev without an email? I think we had to set this up before?
* ![Screen Shot 2021-02-09 at 3.27.08 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9868c6a3-5a6e-45da-a140-8a27b958de99)When the verification modal displays, the success message is displaying on the Edit screen, but then when you click OK on the modal, it routes to the Practitioner Detail screen. Can we have the parent screen  remain on the Edit screen with no success message yet and then just show the success message on the Detail screen?

**Comment by JessicaMarine** [comment]
PO review: When the Admissions Clerk changes the email address of a practitioner, a progress bar popped up on the bottom of my screen.  It was unclear what was happening then.  Was it updating the email address of that practitioner on all cases?  If so, that seems inconsistent with the messaging on the modal the Admissions Clerk sees and the messaging the practitioner sees at the top of the page before verifying the new email
