### ISSUE TITLE
Petitioner with Existing Account: Gain Electronic Access to Case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7678]
As a Petitioner, in order to interact with the Court electronically, I need to gain electronic access to the case once the Court sends me my access code.

## Pre-Conditions
* Petitioner has made request for electronic access to case (manual process for now)
* Admissions Clerk has processed request (manual process for now)

## Acceptance Criteria
- Admissions clerk can add an email address for single petitioner who did not previously have one
- When Admissions Clerk adds the email address, if a cognito account already exists with that email, the case is linked to that user's account
- When a user is linked to a case, they have access to the case:
     - It shows on their dashboard
     - They have the associated view
     - They can e-file documents
     - service information is updated to "electronic"
     - they begin receiving electronic service at the email that was added

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Flow for pre-existing email/account - should their be a confirmation for the admissions clerk - "Is this the user you're looking for."
* Admissions clerks don’t have access to the Edit Petitioner Information screen - we would need to grant them access to edit all petitioner contact info, or treat email as a completely different permission?
* Scope clarification (to confirm)-  This story does not cover an Admissions clerk editing an email after they have added it. This could result in an incorrect email being added that cannot be verified and no way to change it in the UI. Do we need to create another story for this? (Jessica - This will be another story) 

## Tasks
- [x] Give Admissions clerk permission to edit Petitioner info (Matt ustaxcourt/ef-cms-flexion#7789)
- [x] Give Admissions Clerk permission to view sealed addresses (Matt ustaxcourt/ef-cms-flexion#7789)
### Case Detail > Petitioner Contact Info (Matt ustaxcourt/ef-cms-flexion#7789)
- [x] Remove Party Type from this UI
- [x] Update UI / layout to match design
### Case Detail > Edit Petitioner Info
- [x] Add “Login & Service Information” section on Edit Petitioner (Admissions Clerk ONLY) (Matt ustaxcourt/ef-cms-flexion#7794)
- [x] Display service preferences (Matt ustaxcourt/ef-cms-flexion#7794)
  - Only Paper and None if no email
- [x] Both "add email" fields required if one has a value (Matt ustaxcourt/ef-cms-flexion#7800)
- [x] Validate email on save (Matt ustaxcourt/ef-cms-flexion#7800)
- [x] Validation: “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.” (Matt ustaxcourt/ef-cms-flexion#7800)
- [x] Display Confirm Email modal
### Confirm Email Modal
- When email already exists (Cody)
  - [x] Display “Matching Service Email Found” (Cody ustaxcourt/ef-cms-flexion#7791)
  - [x] Display associated Petitioner Name
  - [x] Display email
- On click of Yes, Continue  (Cody)
  - [x] Modal closes and app routes to Case Detail > Petitioner with success message displayed (Cody ustaxcourt/ef-cms-flexion#7791)
  - [x] Email is displayed under the associated petitioner  (Cody ustaxcourt/ef-cms-flexion#7796)
  - [x] Case is added to Petitioner Dashboard (Cody ustaxcourt/ef-cms-flexion#7796)
  - [x] Service indicator is updated to electronic (Cody ustaxcourt/ef-cms-flexion#7796)
  - [x] Email receives service emails - test on dev
- [x] Display login and service email section for docket clerk without email form fields - mob ustaxcourt/ef-cms-flexion#7811

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by mariahkannenberg** [comment]
Don't need to move party type to the petitioner level. 
We're only handling primary and secondary petitioners. 
@klohman

**Comment by klohman** [comment]
## Update to Permissions 
* Admissions clerks need permissions to Edit Petitioner Information
* Admissions Clerk can view Sealed Addresses

## Case Detail > Petitioner Contact Info - No Email 
* Remove party type field 
* Update field locations per design 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6b95b791-71fa-43e2-9962-3de493e7a7e6)

## Edit Petitioner information 
* Add new section labeled Login & Service Information 

### Service Information 

**Service preference**
if there is no email for petitioner, options include: Paper, None 

* Display Add Login & Service Email form for Admission clerk users only 
* Hide Login & Service email form for all other internal users 

#### Add Login & Service Email

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save
**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”
* Display confirm email modal

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/dfb902fe-fba7-4c41-92cc-0d1a958cc32c)

## Confirm email modals 

#### Email Already Exists 
* Display “Matching Service Email Found” 
* Display associated Petitioner Name 
* Display email 

**On click of Yes, Continue**
* Modal closes and app routes to Case Detail > Petitioner with success message displayed 
* Email is displayed under the associated petitioner 
* Case is added to Petitioner Dashboard 
* Service indicator is updated to electronic 
* Email receives service emails 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9c6f800b-a9ec-49f0-bd87-2ca1559dc5f7)


## Case Detail > Petitioner - Internal users 

** Once email is verified**
* Display current email address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8412aab5-03a3-4697-8d8b-f9a5d7271690)

## Edit Petitioner Info - with email 

**Service preference**
options include: 
* Electronic 
* Paper 
* None 

* Display Current email address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ac87faf0-726d-4b1f-8a7c-ab9ef355f59d)

## External Party View: Case Detail > Petitioner with email

* Remove party type 
* Update field locations based on design 
* Hide current email field for party view 
* Email is displayed under My Account > Login & Service email for external users 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/757ed120-be64-4597-84d7-9e6d3b192eae)

**Comment by matthopson** [comment]
Feature branch: 7658-feature-petitioner-access

**Comment by klohman** [comment]
## 7658 Test Scenarios

#### 1) Admissions clerk can access Edit Practitioner screen 
* Login as Admissions clerk 
* Go to case xx1-20 
    * Case has party type = Petitioner & Spouse 
    * Both petitioner & spouse have paper service (no email)
* Click Case Information > Petitioner 
* Click Edit link on Petitioner card 
Expected results 
- [x] Edit link is displayed for Petitioner 
- [x] On click of Edit, app routes to Edit Petitioner Information form 
- [x] Admission clerk can edit all petitioner information 

#### 2) Admissions clerk views sealed address  
* Login as admissions clerk 
* Go to case xx2-20 
    * Case has Primary Contact with sealed address 
* Click Case Information > Petitioner 
* Click Edit link on Petitioner card 
Expected results 
- [x] Admissions clerk sees sealed address for primary contact on Petitioner card 
- [x] Admissions clerk sees sealed address for primary contact on Edit Petitioner Information form

#### 3) Admissions clerk has option to add service email to a petitioner on a case (primary contact)
* Login as admissions clerk 
* Go to case xx1-20 
    * Case has party type = Petitioner & Spouse 
    * Both petitioner & spouse have paper service (no email)
* Click Edit link for primary contact 
* View Login & Service Information 
Expected results 
- [x] Service preference options are Paper and None 
- [x] Service preference Electronic is hidden 
- [x] Add Login & Service Email form displays

#### 4) Admissions clerk adds invalid service email to a petitioner on a case (primary contact)
* Scenario 3
* Enter new email address = notvalid@
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 5) Admissions clerk enters non-matching emails for new service email to a petitioner on a case (primary contact)
* Scenario 3
*  Add new email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save
Expected results
- [x] Error displays on email field -  “Email addresses do not match.”

#### 6) Admissions clerk adds existing service email to petitioner on case to a petitioner on a case (primary contact)
* Scenario 3 
* Add new email = [existing email] 
    * Dev = flexionustc+petitionerupdated@gmail.com
* Re-enter email = [existing email] 
    * Dev = flexionustc+petitionerupdated@gmail.com
* Save 
* Click Yes, Continue
Expected results 
On Click of Save:
- [x] Confirm Matching Email Found modal displays 
- [x] Matching Email displays in modal 
- [ ] Matching petitioner name displays in modal 
    - Dev = Petitioner Gmail
On Click of Yes, Continue 
- [x] Modal closes and app routes to Case Information > Petitioner tab with success message displayed 
- [x] Petitioner service indicator updates to Electronic 
- [x] Email displays under Petitioner Card as current email address 

#### 7) Petitioner (primary contact) with existing account is added to case and sees new case on dashboard after service email is added 
* Scenario 6 
* Login as petitioner 
    * Dev = flexionustc+petitionerupdated@gmail.com
* Click Docket number for case xx1-20 
Expected results 
- [x] case xx1-20 displays in My Cases on dashboard 
- [x] petitioner service indicator displays as Electronic for case xx1-20

#### 8) Docket clerk views petitioner without email 
* Login as docket clerk 
* Go to case 
    * Case has petitioner without email 
* Click Edit link for Petitioner 
Expected results 
- [x] Login & Service Information section displays 
- [x] Service preference field displays with Paper and None options 
- [x] Add Login & Service Email form is hidden 


#### 9) Admissions clerk adds existing email to case and petitioner (primary contact) receives electronic service for party-filed document 
* Scenario 6 
* Login as irs practitioner 
* Search for case xx1-20 
* File Answer 
Expected results 
- [x] Petitioner primary contact service preference displays as Electronic
- [x] Petitioner primary contact receives service email at new email account 

#### 10) Admissions clerk adds email to case and petitioner (primary contact) receives electronic service for court-issued document after email is verified 
* Scenario 6
* Login as docket clerk 
* Create, sign, and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] Petitioner primary contact receives service email at new email account

**Comment by klohman** [comment]
UX review 

- - I had intended (but probably wasn't explicit about it) that the name associated with the matching email would display in the confirm modal...is that possible? Currently, it is displaying the name of the petitioner on the case that the email is being added to

example below - Petitioner Gmail was the name entered when the cognito account was created; Korey Steideman is the petitioner name of that case 

![Screen Shot 2021-02-18 at 4.10.45 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/92609bee-ef9a-40e3-8e3e-447584b78d87)

![Screen Shot 2021-02-18 at 4.09.39 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4cfd62b7-837e-4ad7-a4bb-d8b5a0abd78c)
