### ISSUE TITLE
BUG: Document went missing during blue/green deploy [Timebox research]

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7679]
Timebox research to 24 hour period. 

**Describe Bug**
While Mike was conducting a Blue/Green migration in Production, a user was filing a document. They received the service email, and the PDF made it to S3. However, upon switching colors, the record was lost to the old table. For some reason the stream was not properly subscribed to the old table. We should have copied that record over to the new table.

Document info:
```
docketNumber: 9552-19
docketEntryNo: 31
docketEntryId: b5eb1f7f-7174-4527-ab12-5a746b47e253
eventCode: SUPM
```

```
docketNumber: 9552-19
docketEntryNo: 30
docketEntryId: 21b9552a-a653-4f86-a008-c46673b6468c
eventCode: M014
```

**Business Impact/Reason for Severity**
* We can't have served documents go missing.

**In which environment did you see this bug?**
* USTC Production

**Who were you logged in as?**
N/A 

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
* User was e-filing and serving a document while a blue green migration was happening.

**To Reproduce**
1. Start a BG migration
2. File and Serve a document
3. Switch colors
4. Does the document exist in the new DB table?

**Expected Behavior**
* The document should be in the new table after switching colors.

**Actual Behavior**
* The service email completed, the PDF is in S3; however, the items were no longer in the DB, nor were they on the docket record. Nothing appeared on the docket record. 

**Screenshots**

## Tasks
- [ ] Research exact dates and times when the issue occurred - Mike
  * File was uploaded about 50 minutes BEFORE the switch colors happened 
  * Another file uploaded and successfully migrated to new deployed stack - Jan 18, 2021 @ 00:31:46.238
  * Started migration - Jan 18, 2021 @ 00:56:56.782
  * Migration finished - Jan 18, 2021 @ 01:34:56.782
  * File uploaded - January 18, 2021, 02:00:52 (UTC-05:00)
  * Switch colors - January 18, 2021, 02:54:09 (UTC-05:00)
- [ ] Attempt to exaggerate/delay the switch colors with a migration on a Flexion environment with a smaller amount of data to reproduce the issue

* User filing a document ~either~ before ~or after~ the color switch but they are on the old color? Dynamo stream is turned off and it does not make it to the new table. ~Suspect it is after the color switch but they are still on the old color~

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by mariahkannenberg** [comment]
Questions:
* What was the user's experience? How was the bug discovered?

Ticket from user - filed a document - got a service email. Document wasn't listed on the docket record. Nothing was listed on the docket record. 

Notes:
* Trying to recreate a bug that's ~1/1M will cost a lot in terms of testing. May not need to test w/ "like" dataset. 

* If people are using the system while a migration is going on, there's risk with losing documents

Options:
* People can be using the system when the cutover happens, but there's leg work needed to make sure it's fool proof. 
* Have a recovery pattern that can be followed to correct conditions through intervention.
* Do not allow users in the system during cutover.

**Comment by mariahkannenberg** [comment]
@mmarcotte To assist with this one if needed. He'll also track down some timestamps that could help us w/research and recreation.

**Comment by mariahkannenberg** [comment]
Notes:
 - Items missing were not added to system during migration
 - Doc got added after migration but before colors switched
 - Make sure nothing that was in system before migration gets excluded when everything moved from current to new
 - Do we already log everything that gets moved?

Reproduce:
 - Team



Make sure nothing that was in system before migration gets excluded when everything moved from current to new

Ability to see anything that has been loaded after the initial migration
 - Can currently see this in Kibana
Recover documents that have been loaded after the initial migration


OR


Maintenance mode

**Comment by mmarcotte** [comment]
My attempt to replicate on Friday on Court's Staging:

- e-file some documents with petitioner1@example.com.
  * 145-21
  index: 5 Motion in Limine (No Objection) a382413c-44a8-4881-bdca-2855f1a32366
  index: 6 SUPM c44c2248-ad63-4327-b658-e3dca6441df9
  * 136-21
  index: 5 M014 4e6d7071-8504-43c6-a137-69043c41ca6c
- e-file a petition with petitioner2@example.com
  * 149-21S
- switch-colors
  - 12:21pm
- without refreshing, e-file some more documents with petitioner1@example.com
  * 130-21
  - index 5: SUPM ba7c8e45-6103-4bf0-b1c0-15c1bc99b4db
- e-file another petition with petitioner3@example.com
  * 150-21S
- disable the old color’s custom domain name mapping
- attempt to e-file more documents with petitioner1@example.com
  * 130-21: error, logged me out
- attempt to e-file yet another petition with petitioner4@example.com
  * error logged me out

**Comment by matthopson** [comment]
The team stood up an instance on exp2, recreated the window where we believe the issue occurred, and filed documents as various roles - before, during, and after the window was opened and closed...

We were unable to reproduce the issue. The system performed as expected through our tests, indicating the subscription to the stream from source to destination tables was doing its job during this time.

We've also established an area where we could add an additional check before switching tables with some simple queries that we established during this process to catch this type of issue in the future should it present itself. Additionally, we may see a strengthened case for more automation during some of these steps, if possible, to increase reliability and consistency.

Thanks @mmarcotte for your patience and pairing with us!

**Comment by mmarcotte** [comment]
In two attempts we were unable to replicate the issue. And we were unable to think of a scenario where this could have happened. The stream linkage appears to be the single point of failure that could have caused this.

Created https://github.com/ustaxcourt/ef-cms/issues/836 to ensure a tool exists for the Court to ensure this doesn't happen again, or be able to handle it better in the case that it does.

Observations are to improve the automation as well as visibility of what's happening when, and provide an audit trail to troubleshoot issues should they arise in the future.
