### ISSUE TITLE
Admissions Clerk: Add new practitioner to DB with email verification

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7695]
## Acceptance Criteria

**When adding a new practitioner to the DB:** 
* Admission clerk must enter new email twice when adding an email for a practitioner
* Admission clerk cannot add an email that already exists 
* Practitioner is provided new credentials to access DAWSON 
* Practitioner must activate their new email address 
* Practitioner's service indicator is paper until email is activated
* Practitioner email displays as pending until it is activated
* Practitioner is able to log-in and access their cases with the new email after it's activated
* Practitioner's email is updated after email activation on all of the cases the practitioner is on
* Practitioner's service preference updates to electronic and receives service emails at the service email address after the email is activated

**When adding an email to an existing practitioner**
* Practitioner is provided new credentials to access DAWSON 
* Practitioner must activate their new email address 
* Practitioner's service indicator is paper until email is activated
* Practitioner email displays as pending until it is activated
* Practitioner is able to log-in and access their cases with the new email after it's activated
* Practitioner's email is updated after email activation on all of the cases the practitioner is on
* Practitioner's service preference updates to electronic and receives service emails at the service email address after the email is activated

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Adding email to existing practitioner
    - [x] Practitioner's service preference updates to electronic and receives service emails at the service email address after the email is activated - mob ustaxcourt/ef-cms-flexion#8462
    - [x] Display pending email with pending label on practitioner detail view ustaxcourt/ef-cms-flexion#8462
    - [x] Practitioner's email is updated after email activation on all of the cases the practitioner is on ustaxcourt/ef-cms-flexion#8462
- [x] When adding a new practitioner to the DB:
    - [x] Update add practitioner form to have a confirm email field ustaxcourt/ef-cms-flexion#8466
    - [x] Add Practitioner form checks for matching email in cognito on submit ustaxcourt/ef-cms-flexion#8466
    - [x] Validation error when matching email found - similar to edit practitioner form ustaxcourt/ef-cms-flexion#8466
- [x] Verify all acceptance criteria

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Updated Add Practitioner Form 

* Move email field(s) to their own section (same as on Edit Practitioner form) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ac7ab7f5-140b-4226-bebd-6576be4a09df)

**Comment by klohman** [comment]
## 7725 Test scenarios 


#### 1) Admissions clerk adds new practitioner and enters existing email 
* Login as admissions clerk 
* Add new practitioner 
* Enter existing Cognito email 
* Save 
Expected results 
- [x] error message displays on email field “An account with this email already exists. Enter a new email address.”


#### 2) Admissions clerk adds new practitioner and enters mismatching email 
* Login as admissions clerk 
* Add new practitioner 
* Enter different email in “New email address” and “Re-enter new email address” fields
* Save 
Expected results 
- [x] error message displays on email field “Email addresses do not match”

#### 3) Admissions clerk adds new practitioner and enters invalid email 
* Login as admissions clerk 
* Add new practitioner 
* Enter invalid email
* Save 
Expected results 
- [x] error message displays on email field “Enter a valid email address”

#### 4) Admissions clerk adds new practitioner with inactive email 
* Login as admissions clerk 
* Add new practitioner 
* Enter new email
* Save 
* Add practitioner to case
* Serve document on case 
Expected results 
On Save
- [x] New practitioner is added to DB
- [x] New practitioner receives activation email 
- [x] New practitioner email displays as pending
On serve 
- [x] practitioner receives paper service 
- [x] practitioner does not receive service email

#### 5) Admissions clerk adds new practitioner with valid email and practitioner activates email 
* Scenario 4 
* Go to practitioner email and activate account 
* Login as docket clerk 
* Go to practitioner’s case 
* Serve document 
Expected results 
- [x] New practitioner email displays as active on case 
- [x] Practitioner service indicator is updated to electronic
On serve 
- [x] practitioner receives service email

#### 6) Admissions clerk edits practitioner w/o email and enters existing email 
* Login as admissions clerk 
* Edit practitioner w/o email
* Enter existing Cognito email 
* Save 
Expected results 
- [x] error message displays on email field “An account with this email already exists. Enter a new email address.”

#### 7) Admissions clerk edits practitioner w/o email and enters mismatching email 
* Login as admissions clerk 
* Edit practitioner w/o email
* Enter different email in “New email address” and “Re-enter new email address” fields
* Save 
Expected results 
- [x] error message displays on email field “Email addresses do not match”

#### 8) Admissions clerk edits practitioner w/o email and enters invalid email 
* Login as admissions clerk 
* Edit practitioner w/o email
* Enter invalid email
* Save 
Expected results 
- [x] error message displays on email field “Enter a valid email address”

#### 9) Admissions clerk edits practitioner w/o email with inactive email 
* Login as admissions clerk 
* Edit practitioner w/o email
* Enter new email
* Save 
* Add practitioner to case
* Serve document on case 
Expected results 
On Save
- [x] practitioner receives activation email 
- [x] New practitioner email displays as pending
- [x] service indicator remains Paper
On serve 
- [x] practitioner receives paper service 
- [x] practitioner does not receive service email


#### 10) Admissions clerk edits practitioner w/o email with valid email and practitioner activates email 
* Scenario 9 
* Go to practitioner email and activate account 
* Login as docket clerk 
* Go to practitioner’s case 
* Serve document 
Expected results 
- [x] New practitioner email displays as active on case 
- [x] Practitioner service indicator is updated to electronic
On serve 
- [x] practitioner receives service email

**Comment by klohman** [comment]
* Weird white background on radio buttons on Add/Edit Practitioner form 
* When email is pending - we still show “Not provided” as well as pending on the Detail screen - can we hide “Not provided” in this scenario? 
* Bug??? When I went to add a practitioner to a case as a docket clerk, I could not select any petitioners? The checkbox didn’t seem to respond 

Since I can't add a practitioner to a case this way, I'm blocked from testing the rest for now
