### ISSUE TITLE
BUG: Cover sheet not being applied; page count is 0 (recurring?)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7698]
**Describe the Bug**
Same issue as previously resolved in ustaxcourt/ef-cms#7625.  Documents are being eFiled and end up without a cover sheet and a page count of 0 on the docket record.

## Tasks 
- [x] 1 Get PDFs, docket entry json, any logs from Mike
- [x] 2 Attempt to upload same PDFs locally to recreate issue
- [x] 3 Downgrade pdf-lib to 1.15.0 locally and try to recreate the issue
- [ ] ~4 Write a migration that looks at every pk/case sk/docket-entry and has a status of pending (Matt)~
  - [ ] ~pull in pdf-lib and check for encryption~
  - [ ] ~if encrypted, set processingStatus to something other than pending~
  - [ ] ~if not encrypted and page count is 0, set the page count, add a coversheet, and set processingStatus to complete~
- [x] 5 Update uploadExternalDocumentsAction to only call addCoversheetInteractor on the file(s) that were uploaded just then - not all pending docket entries
- [ ] 6 Manually fix subsequent filings (if possible) by re-running the coversheet process on filings missing page count / coversheet

* we were able to recreate the issue on the court's mig environment
* we were NOT able to recreate the issue on flexion's dev environment
* ~possible suspect - pdf-lib upgrade to 1.16.0 is the fix?~
* to reproduce locally, comment out code Jojo added for encrypted PDFs, upload an encrypted PDF on a case, then add the code back and attempt to upload ANY pdf - it will try to add a coversheet to the previously borked PDF and fail

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Court's prod.

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**

**To Reproduce**
1. Go to 14810-19
2. Note that several documents filed after January 17 (when we deployed the fix for ustaxcourt/ef-cms#7625) do not have a cover sheet and the docket record is showing a page count of 0.

**Expected Behavior**
* All eFiled documents have a cover sheet 
* All eFiled documents have a page count on the docket record

**Actual Behavior**
*eFiled documents are making it onto the docket record without a cover sheet and page count

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

**FOR ENGINEERING TEAM ONLY**
Bug Resolution Steps:
 - [ ] Determine why the bug wasn't caught by a test. 
 - [ ] Determine if an automated test needs to fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] Determine if a manual test needs to be fixed, expanded or created. If unsure, bring in others to discuss.
 - [ ] If needed, automated test is created.
 - [ ] If needed, manual test is created.
 - [ ] Reason for bug has been documented.
 - [ ] Fix has been deployed to dev environment.
 - [ ] Fix has been deployed to the Flexion prod environment.
 - [ ] Bug has been tested in Flexion prod environment (UX or Engineering).

**Comment by JessicaMarine** [comment]
@mmarcotte Are you able to add any log information about docket entries 18-21 in 14810-19.

**Comment by matthopson** [comment]
Reason for the bug:
When a document is filed electronically, the system looks at documents on the case that are in a state of `processingStatus: 'pending'` and attempts to run the coversheet generation and sets the number of pages on the docket entry. When ustaxcourt/ef-cms#7625 was addressed, validation was added to prevent encrypted PDFs from making it to the point where they are added to the case with a 'pending' status - but any document that was added BEFORE this would still exist on the case with that status... so when a new document is filed, rather than immediately add the coversheet to that document, the system is seeing the previously un-processable document on the case with the 'pending' status and attempting to add the coversheet to it BEFORE getting to the newly filed document(s).

So there are two issues that need to be addressed here:
1) Remove the 'pending' status from un-processable documents that may have been added before the ustaxcourt/ef-cms#7625 fix.
2) Rerun the coversheet process on subsequently filed documents that are NOT un-processable, but were blocked by the offending (encrypted) document filing attempt.

**Comment by JessicaMarine** [comment]
PO Review:  Able to file documents in the target case without issue.  The cover sheet was applied and the correct page count displays on the docket record.  Need to backlog the manual work needed on prod to correct the documents that are able to be corrected in the Court's backlog so that @mmarcotte can perform it after this is deployed to prod.
