### ISSUE TITLE
Court: Apply rate limiting per user for searches

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7700]
As the Court, in order to prevent degradation of services to other users, we need to apply rate limiting to order and opinion searches.

** Note: ** This is different that the auto-rate limiting that may be applied to keep ES healthy.  This is one user performing many successive searches within a period of time 

## Acceptance Criteria
* User knows how many searches they can perform without hitting a limit
* Limit = 15
   * Order --  15 searches per minute
   * Opinion -- 15 searches per minute
* When a user hits the search limit, the user is prevented from performing the search and is informed of the issue

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [ ] experiment with rateLimiter made by Cody etc
- [ ] Determine how to track usage (user, IP address: store in dynamo associated with IP address, use REDIS if needed?) - mob
- [ ] TBD UI tasks with Kristen

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by cnelsonflexion** [comment]
"You've reached your search limit. Please wait 1 minute before trying your search again."

**Comment by codyseibert** [comment]
This should be ready for UX review, but I'm setting it as blocked until ustaxcourt/ef-cms#7947 is done since there is no way for people to verify this works in the UI.

**Comment by matthopson** [comment]
@klohman This is on migration now.

![Screen Shot 2021-07-09 at 1.45.38 PM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/c87ee7bf-a18c-40ef-a312-b45878d30ded)
