### ISSUE TITLE
Quarterly Manual Testing - Tech Mob

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7701]
## Acceptance Criteria 

AC 1) Team has performed manual testing on the Court migration environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing

* Mobile - Rae + Mrin
* Stip Decision flow - Mrin
* Correspondence File - Rae
* Public Users - Rae

## Tasks (Draft)
- [x] Complete steps in Test Matrix (as assigned)
- [x] Document any test failures in Test Matrix
- [x] Validate / reproduce bug (pair with Kristen) 
- [x] Log bugs in Zenhub 

## Definition of Done 
- [x] All tests cases have been performed on the Court's migration environment 
- [x] All bugs discovered have been logged in Github
