### ISSUE TITLE
Second Petitioner: Gain Electronic Access to Case  (Refactoring pre-condition)

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7710]
As an admissions clerk, so that the secondary petitioner can gain access to the system, I need the ability to grant them access. 

## Pre-Conditions
ustaxcourt/ef-cms#7715 
* Refactor primary, secondary and other petitioners into a simple list of petitioners on the case

## Acceptance Criteria

- Admissions clerk can add an email address for second petitioner who did not previously have one
- When Admissions Clerk adds the email address, a new cognito account is created if one doesn't already exist for the email.
- When a new Cognito account is created, the petitioner receives an email to verify their account
- Petitioner is able to verify their Cognito account and gain access to the system
- When Admissions Clerk adds the email address, if a cognito account already exists with that email, the case is linked to that user's account
- When a user is linked to a case (either through the new Cognito account or linkage to existing one), they have access to the case:
      - It shows on their dashboard
      - They have the associated view
      - They can e-file documents
      - Once the petitioner has verified their email, service information is updated to "electronic"
      - Once the petitioner has verified their email, they begin receiving electronic service at the email that was added

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Related to ustaxcourt/ef-cms#7709
* Need to ensure that docket clerk / admissions can see second petitioner's service preference ( we removed the entire Login Email information card) 

## Tasks
feedback PR -#8205

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
# Add Existing Email to Second Petitioner Contact Information 
* Add new section labeled Login & Service Information 

### Service Information 

**Service preference**
if there is no email for petitioner, options include: Paper, None 

* Display Add Login & Service Email form for Admission clerk users only 
* Hide Login & Service email form for all other internal users 

#### Add Login & Service Email

**New email address** 
* field is required if text is entered in Re-enter email field 

**Re-enter email address**
* field is required if text is entered in New email field 

#### On Save
**Validate email fields** 
* email must be in valid format - Error message “Enter a valid email address”
* “New email address” and Re-enter email” fields must match - Error - “Email addresses do not match.”
* Display confirm email modal

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b8d3622c-739c-4ac0-9e79-884d9dfcd794)

## Confirm email modals 

#### Email Already Exists 
* Display “Matching Service Email Found” 
* Display associated Petitioner Name 
* Display email 

**On click of Yes, Continue**
* Modal closes and app routes to Case Detail > Petitioner with success message displayed 
* Email is displayed under the associated petitioner 
* Case is added to Petitioner Dashboard 
* Service indicator is updated to electronic 
* Email receives service emails 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9c6f800b-a9ec-49f0-bd87-2ca1559dc5f7)


## Case Detail > Petitioner - Internal users 

** Once email is verified**
* Display current email address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/131548b7-fba7-40bb-9b3a-16d0c54ceca4)

## Edit Petitioner Info - with email 

**Service preference**
options include: 
* Electronic 
* Paper 
* None 

* Display Current email address 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/03b03566-056e-4399-a6a6-ee03960e727a)

## External Party View: Case Detail > Petitioner with email

* Remove party type 
* Update Petitioner Contact Info card design
* Hide current email field for party view 
* Email is displayed under My Account > Login & Service email for external users 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/059f29de-eff2-4a1f-955b-f1890a7d9f60)

**Comment by klohman** [comment]
# Add New Email to Second Petitioner 

#### No Email Exists 

**When email is added and no matching email exists:**

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4ebd7dde-c13d-4740-9f87-0aea43711502)

* Display “No Matching Service Email" modal 
* Display associated Petitioner Name 
* Display email 

**On click of Yes, Continue**
* Modal closes and app routes to Case Detail> Petitioner with success message displayed 
* Pending email is displayed under the associated petitioner 
* Cognito account is created
* Email receives new account verification email 
* Service indicator remains paper 
* Email does not receive service emails 

## Case Detail > Petitioner - Pending email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b7f07f30-72d2-4d89-8ec6-f8adfe71f1af)

**When email is added but not verified**

* Display Service preference = Paper
* Display “Pending Email address” field 

## Edit Petitioner Information - Pending email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/28f7c6d4-c757-4da8-84dc-f87dff9371b5)
**When email is added but not verified**
* Display alert under Service Info 

**Service preference**
options include: 
* Paper 
* None 

* Display Pending email address 


## New email account 
* The email receives the new account email from Cognito

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c296ba0f-b829-4ccb-bf28-6ef3f6d90a64)

**Comment by klohman** [comment]
# Second Petitioner receives new account email and verifies (aka, logs into system for first time) email 

## External Party View: Case Detail > Petitioner 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0acad0ed-d6d7-48e4-bc74-b487a6bcdcd9)
** Once email is verified**
* Service preference changes to Electronic 

## Internal User View - Case Detail > Petitioner 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4b2c1c55-631c-406e-909f-29dbba115f0b)

** Once email is verified**
* Display email address 
Note: Seal address button should only display for docket clerks (this is current functionality)

## Edit Petitioner Info - with email 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/773cf846-0302-4a70-9262-d57a9e9ab5c5)

**Service preference**
options include: 
* Electronic (if email is saved and verified)
* Paper 
* None 

* Display Current email address

**Comment by klohman** [comment]
## 7808 Tests

### Existing email 

#### 1) Admissions clerk has option to add service email to a petitioner on a case (secondary contact)
* Login as admissions clerk 
* Go to case xx1-20 
    * Case has party type = Petitioner & Spouse 
    * Both petitioner & spouse have paper service (no email)
* Click Edit link for secondary contact 
* View Login & Service Information 
Expected results 
- [x] App routes to Edit Petitioner Contact Info for secondary contact
- [x] Service preference options are Paper and None 
- [x] Service preference Electronic is hidden 
- [x] Add Login & Service Email form displays

#### 2) Admissions clerk adds invalid service email to a petitioner on a case (secondary contact)
* Scenario 1
* Enter new email address = notvalid@
* Re-enter matching email = notvalid@
* Click Save
Expected results 
- [x] Error displays on email field - “Enter a valid email address” 

#### 3) Admissions clerk enters non-matching emails for new service email to a petitioner on a case (secondary contact)
* Scenario 1
*  Add new email address = firstemail@email.com
* Re-enter non-matching email = secondemail@email.com
* Click Save
Expected results
- [x] Error displays on email field -  “Email addresses do not match.”

#### 4) Admissions clerk adds existing service email to petitioner on case to a petitioner on a case (secondary contact)
* Scenario 1 
* Add new email = [existing email] 
    * Dev = flexionustc+petitionerupdated@gmail.com
* Re-enter email = [existing email] 
* Save 
* Click Yes, Continue
Expected results 
On Click of Save:
- [x] Confirm Matching Email Found modal displays 
- [x] Matching Email displays in modal 
On Click of Yes, Continue 
- [x] Modal closes and app routes to Case Information > Petitioner tab with success message displayed 
- [x] Petitioner service indicator updates to Electronic 
- [x] Email displays under Petitioner Card as current email address 

#### 5) Petitioner (secondary contact) with existing account is added to case and sees new case on dashboard after service email is added 
* Scenario 4 
* Login as petitioner 
* Click Docket number for case xx1-20 
Expected results 
- [x] case xx1-20 displays in My Cases on dashboard 
- [x] petitioner service indicator displays as Electronic for case xx1-20

#### 6) Admissions clerk adds existing email to case and petitioner (secondary contact) receives electronic service for party-filed document 
* Scenario 4 
* Login as irs practitioner 
* Search for case xx1-20 
* File Answer 
Expected results 
- [x] Petitioner secondary contact service preference displays as Electronic
- [x] Petitioner secondary contact receives service email at new email account 

#### 7) Admissions clerk adds email to case and petitioner (secondary contact) receives electronic service for court-issued document after email is verified 
* Scenario 4
* Login as docket clerk 
* Create, sign, and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] Petitioner secondary contact receives service email at new email account 


### New email account

#### 1) Admissions clerk adds service email that is not in the system to petitioner on case (secondary contact) 
* Login as admissions clerk 
* Go to case xx3-20 
    * Case has party type = Petitioner & Spouse 
    * Petitioner & Spouse have no email and paper service
* Click Case Information > Petitioner 
* Click edit link for secondary contact 
* Enter and re-enter new email = [new email not in system]
* Click Save
* Click Yes, Continue
Expected results 
On Save: 
- [x] Confirm No Matching Email Found modal displays 
- [x] Email displays in modal 
- [x] petitioner name displays in modal 
On Click of Yes, Continue 
- [x] Modal closes and app routes to Case Information > Petitioner tab with success message displayed 
- [x] Petitioner service indicator remains Paper 
- [x] Email displays under Petitioner Card as Pending email address 
- [x] New email receives Cognito welcome email 

#### 2) Internal user sees pending email when new service email is unverified for petitioner (secondary contact) on Petitioner info card
* Scenario 1 
* Login as petitions clerk
* Go to case xx3-20 
* Click Case Information > Petitioner 
Expected results 
- [x] Petitioner service indicator remains Paper 
- [x] Email displays under Petitioner Card as Pending email address 

#### 3) Admission clerk/Docket clerk sees pending email when new service email is unverified for petitioner (secondary contact) on Edit Petitioner Info screen 
* Scenario 1
* Login as admission clerk / docket clerk 
* Go to case xx3-20 
* Click Case Information > Petitioner
* Click Edit link for secondary contact 
Expected results 
- [x] Secondary contact service indicator displays as Paper 
- [x] electronic service option is hidden 
- [x] Pending email warning alert displays 
- [x] Pending email field displays read-only 

#### 4) Admissions clerk adds email to case and petitioner (secondary contact) receives paper service for party-filed document before the email is verified 
* Scenario 1 
* Login as docket clerk 
* Go to case xx3-20 
* Add Paper Filing 
* Complete Form 
* Save and Serve 
Expected results 
- [x] Modal displays indicating that primary contact receives paper service 
- [x] App routes to Print Paper Service screen 
- [x] Pending email does not receive service email 

#### 5) Admissions clerk adds email to case and petitioner (secondary contact) receives paper service for court-issued document before email is verified 
* Scenario 1 
* Login as docket clerk 
* Go to case xx3-20 
* Create, sign, and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] Modal displays indicating that secondary contact receives paper service 
- [x] App routes to Print Paper Service screen 
- [x] Pending email does not receive service email 

#### 6) Petitioner (secondary contact) without existing account is added to case and verifies email 
* Scenario 1 
* Go to petitioner email account 
* Click the login link 
* Update password and login 
* Click Docket number for case xx3-20 
Expected results 
- [x] case xx3-20 displays in My Cases on dashboard 
- [x] petitioner service indicator displays as Electronic for case xx3-20
- [x] email displays under My Account> Login & Service email 

#### 7) Admissions clerk adds email to case and petitioner (secondary contact) receives electronic service for party-filed document after the email is verified 
* Scenario 1 
* Login as irs practitioner 
* Search for case xx3-20 
* File Answer 
Expected results 
- [x] Petitioner secondary contact service preference displays as Electronic
- [x] Petitioner secondary contact receives service email at new email account 

#### 8) Admissions clerk adds email to case and petitioner (secondary contact) receives electronic service for court-issued document after email is verified 
* Scenario 1
* Login as docket clerk 
* Create, sign, and save Order 
* Add Docket entry for Order 
* Save and Serve 
Expected results 
- [x] Petitioner secondary contact receives service email at new email account

**Comment by ericsorenson** [comment]
Related to ustaxcourt/ef-cms#7709

**Comment by klohman** [comment]
## UX Feedback on 7808

- Pending email address - missing the yellow alert warning 

- External view (petitioner / practitioner) - is not displaying the email but should (I remember Jessica requesting this) on the Petitioner card. The email address will not be editable from here.  
- Internal and external - should display email address field on Petitioner card. If petitioner does not have email address - should display “Not provided” 

- For new emails - After email is verified, petitioner (Holmes Little on case 148-21) is still showing paper service indicator and they are not receiving service at the new email

**Comment by JessicaMarine** [comment]
Need to wait until re-deployed to `mig` to test.

**Comment by JessicaMarine** [comment]
PO Feedback:
- When you provide a petitioner (first or second) eAccess, that should **not** disassociate their counsel.  In 187-21 in `mig` I added an email to both petitioners.  It removed them from under the counsel's name as petitioners he was representing.
- With the second petitioner, if you add an email and service is electronic -- when you remove counsel, the second petitioner's service changes to paper, not electronic.  I would expect it to stay electronic since that's what it was before.

**Comment by JessicaMarine** [comment]
PO Feedback:
* Logged into mig as an Admissions Clerk.  Added an email to P2 in 206-20.  On save, none of the tabs were selected -- got a weird view.  
* This also happened when I removed P2 from being represented by counsel.  
* This might be related to the UI changes that are happening, so as long as this is fixed as part of that, I'm moving this to the holding queue for batched work.
