### ISSUE TITLE
Docket clerk edits Petitioner Contact Info at the individual level (Original Refactoring pre-condition)

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7715]
To allow petitioners to be treated equally and individually, a docket clerk needs the ability to edit contact information per each individual petitioner.

## Pre-Conditions
* Case has a petitioner & spouse / deceased spouse 
* Refactor primary, secondary, other petitioners, otherFilers into a simple list of petitioners on the case

## Acceptance Criteria
* Admission clerk and docket clerk can edit contact information for each petitioner & spouse individually
* Admission clerk and docket clerk cannot edit petitioner contact information until the petition has been served 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes & Questions
- Are we expecting to be able to atomically edit Primary, Secondary, and Other petitioners? For this story, only expecting to break apart primary and secondary. Eventually, we'll do all individually. If it makes sense to do it now, let's do it. Otherwise, keep is small. 
- What's the expected behavior for who/when can see the contact information edit button?
- After a case is served, Party type is no longer tied to the contact validation. All fields are combined into 'Additional Name' (which is optional).
- If case is created with a party type that has an 'In Care of', add 'c/o' to `additionalName` property when case is created

## Tasks
- [x] Refactor petitioners on case into a single list - Rae+Mrin
    - [x] contactPrimary - mob
      - [x] migration script - ustaxcourt/ef-cms-flexion#8043
      - [x] update seed data / tests - ustaxcourt/ef-cms-flexion#8043
      - [x] identify primary with contacttype property - ustaxcourt/ef-cms-flexion#8049
      - [x] update test data - ustaxcourt/ef-cms-flexion#8043
      - [x] validation for only a single primary contact 
    - [x] contactSecondary - mob ustaxcourt/ef-cms-flexion#8066
      - [x] migration script
      - [x] update seed data / tests
      - [x] identify secondary with contacttype property
      - [x] refactor contact factory and associated methods
      - [x] refactor contact related methods on case
      - [x] update test data
      - [x] validation for only a single secondary contact
    - [x] otherPetitioners - Rachael, Mrinalini, Rosie - ustaxcourt/ef-cms-flexion#8056
      - [x] migration script
      - [x] update seed data / tests
      - [x] identify otherPetitioners with contactType property
      - [x] refactor contact factory and associated methods
      - [x] refactor contact related methods on case
      - [x] update test data
  - [x] otherFilers - Rae, Mrinalini, Rachael - ustaxcourt/ef-cms-flexion#8054
      - [x] migration script
      - [x] update seed data / tests
      - [x] identify with contactType property
      - [x] refactor contact factory and associated methods
      - [x] refactor contact related methods on case
      - [x] update test data
  - [x] Change `getCaseContacts` usages to call `getPrimaryContact` and `getSecondaryContact` -  mob ustaxcourt/ef-cms-flexion#8066
  ~~- [ ] Fix elasticsearch query, needs to give highest boost to contactPrimary~~ Note: we think this is happening by adding the contactPrimary to to the petitioners array first, so the es query doesn't need to be done.
  ~~- [ ] Fix elasticsearch query, needs to give highest boost to contactSecondary~~

After refactoring:
- [x] 1 Petitioner Contact Info on Case Detail - mob
	- [x] 1a Display full width card for Petitioner Contact Info
	- [x] 1b Edit button is hidden until petition is served
	- [x] 1c Move “Edit” button next to contact name
	- [x] 1d On click of Edit, app routes to Edit Petitioner Contact Info screen
	- [x] 1e can contactPrimary see the edit link for contactSecondary? - Answer: No. ustaxcourt/ef-cms-flexion#8087
- [x] 2 Create route and view for Edit Petitioner Information form
- [x] 3 Validation for Edit Petitioner form ustaxcourt/ef-cms-flexion#8084
- [x] 4 Create endpoint to submit Edit Petitioner (may just want to reuse updatePetitionerInformationInteractor) ustaxcourt/ef-cms-flexion#8086
- [x] 5 Display current and pending email for secondary contact in Case Information tab ustaxcourt/ef-cms-flexion#8095
- [x] 6 Do not allow edits to petitioner information if a case has not been served (on the API side)
- [ ]  7 Add migration script to migrate already served cases that have a secondaryName, inCareOf, etc

Bugs related to refactoring: ustaxcourt/ef-cms-flexion#8079
- [x] 1 cannot QC e-filed petition as petitionsclerk - cannot visit petition QC screen if there is a contactSecondary
- [x] 2 cannot QC e-filed petition as petitionsclerk - cannot get to the review screen on ANY e-filed case
- [x] 3 Review petitions screen had missing information
- [x] 4 Document QC as petitionsClerk had no caseTitle
- [x] 5 validation error when e-filing case with second petitioner [image](https://user-images.githubusercontent.com/20514925/112874824-9f6f0980-9080-11eb-94be-7344ced7d57b.png)
- [x] 6 (as petitionsClerk) ![image](https://user-images.githubusercontent.com/20249233/113039740-031f3280-9166-11eb-8cb0-07c693b9c6ee.png)
- [x] 7 (as petitioner) when inCareOf is missing while creating a case, field level validation error is missing
- [x] 8 Create paper case w/party type petitioner, then AFTER creating but before serving, edit the party type to petr and spouse. saving it throws an error 
![image](https://user-images.githubusercontent.com/20514925/113041936-cba98980-9157-11eb-8989-bc72c4c4a73c.png)
- [x] 9 Can't print the docket record
- [x] 10 Error when serving case to IRS after adding privatePractitioners as counsel 
![image](https://user-images.githubusercontent.com/20249233/113911811-69303900-97a8-11eb-98d1-fb4088d8dc56.png)
- [x] 11 If a Petitions Clerk tries to QC a Petition. And saves it for later, it disassociates the Practitioners.
Login as Petitions Clerk ustaxcourt/ef-cms-flexion#8113 
Document QC => Switch to Section Document QC
Find one whose petition needs to be served
Hopefully there’s a practitioner already there, if not add one and associate it with the Petitioner
Then QC the Petition, but don’t serve it yet — save it for later.
Then I noticed the Practitioners were disassociated from the Petitioners.

Additional Name combination
- [x] Update validation after case is served - mob ustaxcourt/ef-cms-flexion#8098
- [x] Combine fields into additionalName when serving case, and append 'c/o' string - ustaxcourt/ef-cms-flexion#8099
- [x] Update UI to display additionalName instead of inCareOf/secondaryName/title etc & remove appending 'c/o' string from UI logic

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Refactor duplicated jsx code for 'Login & Service Email'
 - [x] Refactor/create method to getPetitioner by contactId
 - [x] Move contact logic in EditPetitionerInformationInternal.jsx into a helper
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the prod environment

**Comment by klohman** [comment]
## Case Detail > Petitioner 

### Petitioner Contact Info (All Party types except Petitioner & Spouse / Deceased Spouse)  
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2c199d8c-2690-4c3a-b8da-f4200c2f156d)
* Display full width card for Petitioner Contact Info 

#### Edit button
* Edit button is hidden until petition is served
* Move “Edit” button next to contact name 
* on click of Edit, app routes to Edit Petitioner Contact Info screen 


### Petitioner Contact Info (Petitioner & Spouse / Deceased Spouse)  
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/465be636-96d6-4316-b798-61ed183c4ef1)
* Display full width card for Petitioner Contact Info 

#### Edit button
* Edit button is hidden until petition is served
* Display individual “Edit” button for each primary contact and secondary contact 
* on click of Edit, app routes to Edit Petitioner Contact Info screen for the selected contact


# Edit Petitioner Form
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6fba601b-c883-4345-9b33-2625c523b0b0)
## Name fields mapping  
* maps to current fields from the create case form  

#### Surviving Spouse 
* Name of deceased = **Name**
* Name of surviving spouse = **Additional name**

#### Estate Information 
* Name of decedent = **Name**
* In care of = **Additional name**

#### Guardian 
* Name of taxpayer = **Name**
* Name of guardian = **Additional name**
  
#### Next Friend 
* Name of legally incompetent person = **Name**
* Name of next friend = **Additional name**

#### Conservator 
* Name of taxpayer = **Name**
* Name of conservator = **Additional name**

#### Partnership (other than tax matters partner)
* Business name = **Name**
* Name of partner (other than TMP) = **Additional name**

#### Trustee  
* Name of trust = **Name**
* Name of trustee = **Additional name**

#### Custodian
* Name of taxpayer = **Name**
* Name of custodian = **Additional name**

#### Partnership  
* Business name = **Name**
* Name of partnership representative = **Additional name**

#### Tax Matters Partner 
* Business name = **Name**
* Name of Tax Matters Partner = **Additional name**

#### Corporation
* Business name = **Name**
* In care of  = **Additional name**
 
#### Estate with executor / personal representative 
* Name of decedent = **Name**
* “Name of executor/personal representative” + “Title” fields  = **Additional name**
* The “Additional name” field should be a combination of the “Name of Executor / Personal representative” field and “Title” fields, formatted = [Name of Executor / Personal representative], [Title]

#### Donor
* Name of petitioner = **Name**

#### Transferee
* Name of petitioner = **Name**

**Comment by klohman** [comment]
## 7808 - Docket clerk edits Petitioner Contact Info at the individual level 

#### 1a) Internal user views Petitioner contact info for case with petitioner & spouse 
* Login as internal user (other than docket clerk)
* Go to case xx1-20
    * Case status = General Docket not at issue
    * Case has party type = petitioner & spouse 
* Click Case Information > Petitioner 
Expected results 
- [x] Petitioner contact info card is displayed for each petitioner per design 

#### 1b) Internal user views Petitioner contact info for case with petitioner & deceased spouse 
* Login as internal user (other than docket clerk)
* Go to case xx2-20
    * Case has party type = petitioner & deceased spouse 
* Click Case Information > Petitioner 
Expected results 
- [x] Petitioner contact info card is displayed for each petitioner per design 

#### 3)  Docket clerk has option to edit petitioner contact information each each petitioner separately 
* Login as docket clerk 
* Go to case xx1-20 
* Click Case Information > Petitioner 
Expected results 
- [x] Edit button displays for each petitioner individually 

#### 4) Docket clerk edits petitioner contact information (primary contact) 
* Scenario 3 
* Click Edit button for petitioner (primary contact) 
Expected results 
- [x] App routes to Edit Petitioner Contact information 
- [x] Form is populated with contact info for primary contact 

#### 5) Docket clerk edits petitioner contact information (secondary contact) 
* Scenario 3 
* Click Edit button for petitioner (secondary contact) 
Expected results 
- [x] App routes to Edit Petitioner Contact information 
- [x] Form is populated with contact info for secondary contact 

#### 6) Docket clerk sees mapped petitioner name fields when editing contact information (surviving spouse) 
* Login as docket clerk 
* Go to case xx3-20 
    * Case status is not New 
    * Party type - surveying spouse 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of deceased = **Name**
- [x]  Name of surviving spouse = **Additional name** 

#### 7) Docket clerk sees mapped petitioner name fields when editing contact information (estate w/o executor) 
* Login as docket clerk 
* Go to case xx4-20 
    * Case status is not New 
    * Party type - estate w/o executor  
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of decedent = **Name**
- [x] In care of = **Additional name** 

#### 8) Docket clerk sees mapped petitioner name fields when editing contact information (guardian) 
* Login as docket clerk 
* Go to case xx5-20 
    * Case status is not New 
    * Party type - guardian 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of taxpayer = **Name**
- [x] Name of guardian = **Additional name** 


#### 9) Docket clerk sees mapped petitioner name fields when editing contact information (next friend)
* Login as docket clerk 
* Go to case xx6-20 
    * Case status is not New 
    * Party type - next friend 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of legally incompetent person = **Name**
- [x] Name of next friend = **Additional name**

#### 10) Docket clerk sees mapped petitioner name fields when editing contact information (conservator)
* Login as docket clerk 
* Go to case xx7-20 
    * Case status is not New 
    * Party type - conservator 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of taxpayer = **Name**
- [x] Name of conservator = **Additional name**

#### 11) Docket clerk sees mapped petitioner name fields when editing contact information (Partnership (other than tax matters partner))
* Login as docket clerk 
* Go to case xx8-20 
    * Case status is not New 
    * Party type - Partnership (other than tax matters partner) 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Business name = **Name**
- [x] Name of partner (other than TMP) = **Additional name**

#### 12) Docket clerk sees mapped petitioner name fields when editing contact information (Trustee)
* Login as docket clerk 
* Go to case xx9-20 
    * Case status is not New 
    * Party type - Trustee 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of trust = **Name**
- [x] Name of trustee = **Additional name**

#### 13) Docket clerk sees mapped petitioner name fields when editing contact information (Custodian)
* Login as docket clerk 
* Go to case x10-20 
    * Case status is not New 
    * Party type - Custodian 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of taxpayer = **Name**
- [x] Name of custodian = **Additional name**

#### 14) Docket clerk sees mapped petitioner name fields when editing contact information (Partnership)
* Login as docket clerk 
* Go to case x11-20 
    * Case status is not New 
    * Party type - Partnership 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Business name = **Name**
- [x] Name of partnership representative = **Additional name**

#### 15) Docket clerk sees mapped petitioner name fields when editing contact information (Tax Matters Partner)
* Login as docket clerk 
* Go to case x12-20 
    * Case status is not New 
    * Party type - Tax Matters Partner 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Business name = **Name**
- [x] Name of Tax Matters Partner = **Additional name**

#### 16) Docket clerk sees mapped petitioner name fields when editing contact information (Corporation)
* Login as docket clerk 
* Go to case x13-20 
    * Case status is not New 
    * Party type - Corporation
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Business name = **Name**
- [x]  In care of  = **Additional name**

#### 17) Docket clerk sees mapped petitioner name fields when editing contact information (estate w/ executor)
* Login as docket clerk 
* Go to case x14-20 
    * Case status is not New 
    * Party type - Estate with executor / personal representative 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of decedent = **Name**
- [x] “Name of executor/personal representative” + “Title” fields  = **Additional name**

#### 18) Docket clerk sees mapped petitioner name fields when editing contact information (donor)
* Login as docket clerk 
* Go to case x20-20 
    * Case status is not New 
    * Party type - Donore 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of petitioner = **Name**

#### 19) Docket clerk sees mapped petitioner name fields when editing contact information (transferee)
* Login as docket clerk 
* Go to case x21-20 
    * Case status is not New 
    * Party type - Transferee 
* Click Edit button for petitioner 
Expected results 
- [x] App routes to Edit Petitioner Contact information
- [x] Name of petitioner = **Name**

#### 20) Admission clerk / Docket clerk cannot edit petitioner contact information before petition is served 
* Login as docket clerk / admission clerk
* Go to case x15-20 
    * Case status = New 
* Click Case Info > Petitioner 
Expected results 
- [x] Edit button for petitioner contact info does not display 

#### 21) Docket clerk views petitioner contact info on address page when serving document on paper parties 
* Login as docket clerk 
* Go to case x16-20
    * Party type - petitioner & spouse
    * Service = paper 
* Add Paper Filing and Serve 
* Go to case x14-20 
    * Party type - estate w/ executor 
    * Service = paper 
* Add Paper filing and serve 
Expected results 
- [x] Address sheet on PDF on the Print Paper Service screen displays correct petitioner name, additional name and title 

#### 22) Docket clerk / external party views Printable Docket record
* Go to case x16-20 
* Click Printable Docket Record 
* Go to case x14-20 
* Click Printable Docket Record 
Expected results 
- [x] Contact Information on Printable Docket Record displays correct petitioner name, additional name and title

**Comment by klohman** [comment]
UX Research Questions 
- How would you describe the relationships between different petitioners on a case? (Probe: are they linked in any way? Do they need to be treated separately or as a group?) 
- What initiates changes to petitioner contact information? (address, phone, email)? 
- How do you handle changing contact information when there is more than one petitioner on the case?

**Comment by ericsorenson** [comment]
Questions for Jessica

- Are we expecting to be able to atomically edit Primary, Secondary, and Other petitioners?

**Comment by klohman** [comment]
@JessicaMarine Added otherFilers to the refactoring precondition- this will not change any functionality and we'll still be able to identify these other Filers. This will just include them in the list of petitioners.

**Comment by klohman** [comment]
@mrinsin 

## Notes from UX Review 

- C/o is not displaying in address label - Receipt of Petitioner or on Print Paper Service address sheet
- Surviving spouse case 127-21-/ guardian case 119-21 / next friend case 120-21 / conservator 113-21 / partnership non-TMP 125-21 / trust 129-21 / custodian 115-21/ partnership bba 123-21/ estate w/ executor 117-21/ 
    - additional name does not display the “c/o” (it did on the review Petition screen)
- Printable docket record contact info is also missing the “c/o” 

- Case title is not displaying correctly in some queues (In Progress is where I saw this “undefined” - case title is ok in some other places - Case Inventory for example

![Screen Shot 2021-04-13 at 10.07.26 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6099dd2d-5396-4c4f-a382-2ea72106f850)

**Comment by JessicaMarine** [comment]
Need to wait until re-deployed to `mig` to test.
