### ISSUE TITLE
Quarterly Manual Testing - Themis Mob

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7716]
## Acceptance Criteria 

AC 1) Team has performed manual testing on the Court migration environment for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing

* Messaging [Kris & Tom]
* External Parties Workflows [Kris & Tom]
* Petition Workflow - Internal [Kris & Tom]
* Add Paper Filing- Internal [Cody]
* Service emails [Kris & Tom]
* QC eFiling - Internal [Cody]

## Tasks (Draft)
- [x] Complete steps in Test Matrix (as assigned)
- [x] Document any test failures in Test Matrix
- [x] Validate / reproduce bug (pair with Kristen) 
- [x] Log bugs in Zenhub 

## Definition of Done 
- [x] All tests cases have been performed on the Court's migration environment 
- [x] All bugs discovered have been logged in Github
