### ISSUE TITLE
Docket Clerk: Edit the c/o in a migrated address

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7722]
As a Docket Clerk, in order to keep accurate contact information in the system, I need the ability to edit all migrated addresses.

Party contact information was not stored exactly how we have it in DAWSON.  As a result, there are some additional fields (e.g., c/o on a petitioner) in legacy data that are not currently editable in DAWSON.

3 cases where this is a known issue:
21126-19
11377-20
1675-21

## Pre-Condition:
* Legacy contact information has additional fields from what DAWSON requires/expects

## Acceptance Criteria:
* Docket Clerk can edit **all** fields of a legacy address
* Changes are captures on a Notice of Change of Address/Phone/both
* New address is saved in the system
* Party gets service at new address (if paper service)

## Tasks
- [ ] Add input field for `inCareOf` and hook into state
- [ ] Add logic for `inCareOf` into generating new Notice of Address/Phone/both

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

# Notes:
* Contact Mark to help with uncovering any other address data that may not displaying in the form
* In care of should be mapped to additional name field, and if edited should not generate a notice of change of address
* Look at 14617-17: when you try to edit petitioner's contact information, the c/o information does not display on the form so that it can be edited.  As a result, there is no way to remove it, and it's causing the address to be incorrect.  
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/21436a7f-a397-4d3d-8752-73fa0121b3e9)

c/o doesn't display on form:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/a00493d8-bb5b-4f6d-bc11-5313cef2a020)

* Similar issue exists in 12669-18

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/33125122-9154-42fe-80d0-040ae6abc8ae)

InCareOf field is coming back as part of the contact, but is not a field in the UI required for this party type (could it have just been migrated field? )

**Comment by klohman** [comment]
## 7865 Tests Scenarios

#### 1) Docket clerk sees “c/o” for migrated petitioner in Additional Name field 
* Migrate case xx1-21
    * Party type = Petitioner 
    * Migrated data includes rogue “c/o” 
    * Paper service
* Login as docket clerk 
* Go to case xx1-21 
* Click Case Information > Petitioner
* Click Edit link for petitioner 
Expected results 
On Petitioner card:
- [ ] petitioner displays with “c/o” as second line 
On click of Edit link: 
- [ ] Additional name field is populated with “c/o” name
- [ ] Additional name field is editable 

#### 2) Docket clerk sees “c/o” for migrated petitioner & spouse in Additional Name field 
* Migrate case xx2-21
    * Party type = Petitioner & Spouse
    * Migrated data includes rogue “c/o” for petitioner 1
    * Migrated data includes rogue “c/o” for petitioner 2
    * Paper service
* Login as docket clerk 
* Go to case xx2-21 
* Click Case Information > Petitioner
* Click Edit link for petitioner 1 
*  Click Edit link for petitioner 2 
Expected results 
On Petitioner card:
- [ ] petitioner displays with “c/o” as second line 
On click of Edit link for petitioner 1: 
- [ ] Additional name field is populated with “c/o” name
- [ ] Additional name field is editable 
On click of Edit link for petitioner 2: 
- [ ] Additional name field is populated with “c/o” name
- [ ] Additional name field is editable 

#### 3) Docket clerk edits “c/o” for migrated petitioner
* Migrate case xx1-21
    * Party type = Petitioner 
    * Migrated data includes rogue “c/o” 
    * Paper service
* Login as docket clerk 
* Go to case xx1-21 
* Click Case Information > Petitioner
* Click Edit link for petitioner 
* Update Additional name field 
* Save 
Expected results 
- [ ] App routes to Petitioner tab and success message displays 
- [ ] Updated “c/o” displays in petitioner card 
- [ ] Notice of Change of Address is not added to the docket record 

#### 4) Docket clerk edits “c/o” for migrated petitioner & spouse 
* Migrate case xx2-21
    * Party type = Petitioner & Spouse
    * Migrated data includes rogue “c/o” for petitioner 1
    * Migrated data includes rogue “c/o” for petitioner 2
    * Paper service
* Login as docket clerk 
* Go to case xx2-21 
* Click Case Information > Petitioner
* Click Edit link for petitioner 2 
* Updated Additional name field 
* Save 
* View Printable Docket Record 
Expected results 
- [ ] App routes to Petitioner tab and success message displays 
- [ ] Updated “c/o” displays in petitioner 2 
- [ ] Notice of Change of Address is not added to the docket record 
- [ ] Updated “c/o” displays in Printable Docket Record

#### 5) Docket clerk edits “c/o” for migrated petitioner and sees update on Print Paper Service address page 
* Scenario 3 
* Add Paper Filing 
* Serve
Expected results 
- [ ] Paper Service PDF displays updated “c/o” on address page 

#### 6) Docket clerk removes “c/o” for migrated petitioner 
* Migrate case xx1-21
    * Party type = Petitioner 
    * Migrated data includes rogue “c/o” 
* Login as docket clerk 
* Go to case xx1-21 
* Click Case Information > Petitioner
* Click Edit link for petitioner 
* Delete Additional name field 
* Save 
* View Printable Docket Record 
Expected results 
- [ ] App routes to Petitioner tab and success message displays 
- [ ] “c/o” no longer displays in petitioner card 
- [ ] “c.o” no longer displays in Printable Docket Record 

#### 7) Docket clerk removes “c/o” for migrated petitioner and sees update on Print Paper Service address page 
* Scenario 6 
* Add Paper Filing 
* Serve
Expected results 
- [ ] Paper Service PDF does not display “c/o” on address page

**Comment by klohman** [comment]
For whoever picks this up, I don't think there is any code needed for this. We'll just need to set up some test data and run through the test scenarios.

**Comment by sutt0n** [comment]
Marking this as blocked until we touch base with Mark from 18F to get a visualization on legacy data.

**Comment by TomElliottFlexion** [comment]
Will require a migration

**Comment by JessicaMarine** [comment]
@sutt0n @TomElliottFlexion  Please add `c/o` in front of the secondary name for any of these.  Apologies for the miscommunication.
