### ISSUE TITLE
Internal Court User: Case Navigation Buttons on Message Screen

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7725]
As an internal Court user, in order to directly navigate to other parts of the case, I need the case navigation buttons on the message screen.

## Pre-Conditions
* User is on message screen within a case

## Acceptance Criteria
* User is able to see and use the case navigation buttons from the message screen

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Don't need ability to go back into message if they click out of it. 

## Tasks
- [x] 1 Display case header on message detail screen with Case Messages tab selected (Rachael) ustaxcourt/ef-cms-flexion#8461 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![message screen with sub-UI.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/a99f1e29-f00d-4cdb-909a-98ae3e1137a4)

- Logged in as docket clerk
- Browse to an in-progress or completed case message
- [ ] Case navigation tabs should appear above the message viewer in their default location
