### ISSUE TITLE
Admissions Clerk: Add email address to existing practitioner with no email address

### ISSUE THREAD

**Issue by mark-meyer** [ustaxcourt/ef-cms#7739]
As an Admissions Clerk, in order to properly update practitioner's account, I need the ability to add an email address to an existing practitioner who previously did not have one.

## Pre-Conditions
* A practitioner exists in DAWSON without an email address.

## Acceptance Criteria
* Admissions Clerk has the ability to **add** an email address to a practitioner's profile if they don't have an email on their account
* Once the email is added, the admissions clerk cannot edit the email address and doesn't have the ability to add another email address
* Practitioner's service preference is changed to electronic.
* Practitioner receives a welcome email when a new email has been added to their account.
* When a new email address is added by the Admissions Clerk, it creates a Cognito account for this practitioner.
* Ensure that the practitioner is still connected to any cases that they were attached to before and that it's reflected in the UI
* Email is the ONLY thing that change (not bar #, address, etc)
* Practitioner receives service emails at the new email address
* Technical Lead can add email addresses to practitioner's profile in bulk
* Log any errors in a way that will allow us to identify and correct problems created from failed API calls.

Technical Solution:
   * Alter (or recreate) the existing practitioner records such that their uuid matches the new Cognito account and has the new email address added to appropriate dynamoDB records.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

Here are some Bar Numbers you can use in your Prod environment that should not have Email addresses associated with them.

- TN0030
- WG0110
- SL0206
- CR0904

## Tasks
- [x] Practitioner Detail - Default UI for blank email address field - Team mob ustaxcourt/ef-cms-flexion#7438
- [x] Edit Practitioner Detail - Team mob ustaxcourt/ef-cms-flexion#7438
    - [x] Default UI for blank email address field - Team mob ustaxcourt/ef-cms-flexion#7438
    - [x] Show ‘Add email address’ button when email address is blank - Team mob ustaxcourt/ef-cms-flexion#7438
- [x] Edit Practitioner Detail on click of Add email button - Team mob ustaxcourt/ef-cms-flexion#7439
    - [x] Display text field for email address - Team mob ustaxcourt/ef-cms-flexion#7439
    - [x] hide “Add Email address’ button - Team mob ustaxcourt/ef-cms-flexion#7439
    - [x] Email address field is required - Team mob ustaxcourt/ef-cms-flexion#7439
    - [x] Error message if blank = “Enter email address - Team mob ustaxcourt/ef-cms-flexion#7439
- [x]  Edit Practitioner Detail on save - Team Mob ustaxcourt/ef-cms-flexion#7449
    - [x] app routes to Practitioner Detail screen with success message
    - [x] new email address displays as read-only ustaxcourt/ef-cms-flexion#7449
    - [x] Cognito account is created for this practitioner and practitioner receives welcome email  ustaxcourt/ef-cms-flexion#7449
- [x] Practitioner's service preference is changed to electronic on all cases when email is added - Team mob ustaxcourt/ef-cms-flexion#7451
- [x] Figure out if we should make any changes so that this can be run by tech lead in bulk (mob ustaxcourt/ef-cms-flexion#7454)
  - [x] Add a README with example use for the update endpoint 
- [x] Verify user can not modify their cognito `custom:userId` (security concern)
- [x] UI is not correctly updating the practitioners email - Team mob ustaxcourt/ef-cms-flexion#7453

## Definition of Done (Updated 10-26-20)

**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the prod environment

**Comment by klohman** [comment]
## Practitioner Detail 
* Add blank state to empty email address field = “None”
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/95652c12-bc61-4fdf-bfc5-52e478a868d7)

## Edit Practitioner Detail - No email
* Add blank state to empty email address field = “None”
* If email address field is empty = display “Add email address” button

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2b38feea-373b-41a0-b528-98bb08489b1a)

## Edit Practitioner Detail - Add email 
**On click of Add email address button**
* Display text field for email address 
* hide “Add Email address’ button 
* Email address field is optional

**On Save**
* app routes to Practitioner Detail screen with success message 
* new email address displays as read-only 
* Cognito account is created for this practitioner and practitioner receives welcome email

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1bd82a9b-0053-4f9b-8aaf-c6cd1d9387a2)

**Comment by klohman** [comment]
## 7377 Test Scenarios 

#### 1) Admission clerk sees blank state for migrated practitioner with no email address 
* Login as admissions clerk 
* Search for practitioner without email address (example: TN0030)
Expected results 
- [x] Email field displays with blank state =  “Not provided” 

#### 2) Admissions clerk sees option to add email address to practitioner with no email address on profile
* Login as admissions clerk 
* Search for practitioner without email address (example: TN0030)
* Click Edit link 
Expected results 
- [x] Email field displays with blank state =  “Not provided” 
- [x] “Add email address” button displays 

#### 3) Admissions clerk adds email address to practitioner with no email address on profile
* Login as admissions clerk 
* Search for practitioner without email address (example: TN0030)
* Click Edit link 
* Click Add email address button 
* Enter email (must have access to email to validate) 
* Click Save 
Expected results 
- [x] App routes to Practitioner Detail with success message 
- [x] Added email displays in “Email address” field 
- [x] Added email receives cognito welcome email 

#### 4) Admissions clerk cannot add/edit email to practitioner with email address on profile 
* Login as admissions clerk 
* Search for practitioner with email address (example: HO20006)
* Click Edit 
Expected results 
- [x] Email field displays read-only with practitioner email 
- [x] “Add email address” button is hidden  

#### 5) Practitioner can log into the system with added email address 
* Scenario 3 
* Login to practitioner email and verify that welcome email was received 
* Login to system with new email 
* Click on an open case and view Petitioner Counsel information
Expected results 
- [x] Added email receives welcome email from USTC 
- [x] Practitioner is able to login to system with new email 
- [x] All cases associated with practitioner display on dashboard 
- [x] Practitioner service indicator is “Email” 

#### 6) Practitioner receives service email at added email address 
* Scenario 3
* Login as docket clerk
* Go to case associated with TN0030 
* Add docket entry and serve 
* Login to practitioner email 
Expected results 
- [x] Practitioner receives service email at newly added email addresss

**Comment by klohman** [comment]
UX Review - no issues. 

These AC will need to be tested by Tech Lead:

* Technical Lead can add email addresses to practitioner's profile in bulk
* Log any errors in a way that will allow us to identify and correct problems created from failed API calls.
