### ISSUE TITLE
Docket Clerk: Manually add blocked case to trial session or for hearing

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7741]
As a Docket Clerk, I need the ability to manually add a case to a trial session or hearing even if it's blocked.

The blocked feature is really intended for a case not to be scheduled for trial as part of the automated scheduling process.  Right now, it's preventing a case from being *manually* added to a session as well.  The Court needs more flexibility.

## Pre-Conditions
* Case is blocked from trial.

## Acceptance Criteria
* Allow Docket Clerk to *manually* add case to trial session or set for hearing even if the case is blocked by due date or pending item.
* Docket clerk can mark a case as "high priority" that is blocked (automatic only).
* User should be allowed to add to a session that's been "cut" and also one that has not yet been "cut"

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Just add to session or also for setting high priority, adding to a non-calendared session? High priority 
* Doesn't matter if block was added manually or automatically
* Case still shows up on blocked report (user would see that it's calendared)

## Tasks
- [x] 1 Add notification icon to Tracked Items ustaxcourt/ef-cms-flexion#7896
  - [x] 1a Computed logic for displaying tracked items notification icon ustaxcourt/ef-cms-flexion#7896
- [x] 2 Allow internal user to add to trial or mark as high priority a case that is system blocked ustaxcourt/ef-cms-flexion#7898

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion Prod env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [x] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by cnelsonflexion** [comment]
![TrackedItems.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/1a1fa619-609e-4c1f-a097-dc044fe881bc)

![ManualBlock.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/5156eed1-933e-4af8-b3fe-0598920003ff)

**Header**
Blocked tag is added next to judge tag when there are tracked items automatically preventing the case from being added to the eligibility list.

Blocked tag is added next to judge tag when a manual block has been added to the case.

**Main Navigation**
Notification icon is added next to Tracked Items link when there are tracked items automatically preventing the case from being added to the eligibility list.

**When a user views the Case Detail screen, if there are tracked items automatically preventing the case from being added to the eligibility list:**

- display indicator next to Tracked Items in navigation
- display BLOCKED tag next to JUDGE tag

When a user views the Case Detail screen, if a manual block has been added to the case:
- display BLOCKED tag next to JUDGE tag

**Comment by cnelsonflexion** [comment]
### Test cases

**Docket clerk adds case with tracked items to Open trial session**
* Go to case  (case is not blocked, and is not set or scheduled for trial)
* Add deadline 
* Go to Trial Information 
* Add to Trial session (trial session is Open)

Expected results 
- [x] Deadline remains on case 
- [x] Tracked item indicator displays 
- [x] Case is added to the trial session and displays on trial session list
- [x] Case status updates to Calendared 
- [x] Blocked label no longer displays in header (status is Calendared)
- [x] Trial Information card now displays as Calendared 

**Scenario 2: Docket clerk adds case with tracked items to New trial session** 
* Go to case  (case is not blocked, and is not set or scheduled for trial)
* Add deadline 
* Go to Trial Information 
* Add to Trial session (trial session is New)

Expected results 
- [x] Deadline remains on case 
- [x] Tracked item indicator displays 
- [x] Case is added to the trial session and displays on trial session list
- [x] Case status does not change
- [x] Blocked label continues to display in header 
- [x] Trial Information card now displays as Scheduled

**Starting from Scenario 2**
* Mark the case as QC complete on the session
* Hit "Set Calendar" on the session

Expected results
- [x] Deadline remains on case 
- [x] Tracked item indicator displays 
- [x] Case is added to the trial session and displays on trial session list
- [x] Case status changes to Calendared
- [x] Blocked label does not display in header 
- [x] Trial Information card now displays as Calendared
 
**Docket clerk marks case with tracked items as High Priority** 
* Go to case  (case is not blocked, and is not set or scheduled for trial)
* Add deadline 
* Go to Trial Information 
* Mark as High Priority

Expected results 
- [x] Deadline remains on case 
- [x] Tracked item indicator displays 
- [x] Case is added to the eligible list for the next available trial session 
- [x] Case status does not change
- [x] Blocked label continues to display in header 
- [x] Trial Information card now displays as High Priority

**Docket clerk adds manual block to case with tracked items** 
* Go to case  (case is not blocked, and is not set or scheduled for trial)
* Add deadline
* Add a manual block 
* Go to Trial Information

Expected results
- [x] Trial card shows Blocked from Trial
- [x] System block information does not display
- [x] Blocked label remains in header
- [x] Tracked item indicator remains in navigation
