### ISSUE TITLE
Court: Access list of practitioner's cases

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7777]
As the Court user, for a variety of reasons, I need to be able to see all of the cases that a specific practitioner is counsel of record.

## Pre-Conditions
* Practitioner exists in the system

## Acceptance Criteria
* Court user is able to see a list of all cases that a practitioner is counsel of record
* List should include open cases and closed cases separately
* Court user can generate a PDF document showing the list for the practitioner's cases

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
@mmarcotte has some helpful DynamoDB queries to help generate this information.
* For all practitioners (private, IRS, etc.)? Regardless of admission status (would an inactive practitioner still be counsel of record for an old closed case? Yes.
* How far back do we need to display? To the beginning of time. All of them.
* What information for each case needs to display? Docket number and case title. 
* No need to consider practitioners that have been removed. Don't panic. 

## Tasks
 - [x] Add button “Print Case List” on practitioner detail page 
that calls sequence/action/proxy (Matt ustaxcourt/ef-cms-flexion#8405)
 - [x] action, sequence, proxy to invoke pdf endpoint (#8407)
 - [x] Lambda calls the interactor  (#8407)
 - [x] Interactor that calls persistence and generates a PDF  (#8407)
 - [x] create react template for this practitioner case report (Mob ustaxcourt/ef-cms-flexion#8415)
 - [x] Persistence method that returns list of cases associated 
with a given practitioner (kris ustaxcourt/ef-cms-flexion#8410)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by cnelsonflexion** [comment]
![print case list.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/21c5b291-8ebb-4cf4-b94c-d614e183397f)

Logged in Court employee -> Practitioner detail screen

- [x] link labled "Print case list" appears above detail cards

![case list slimmed 2.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/89bc57d9-421d-4748-aad5-aa00b69fee4e)

- [x] PDF print of all of the Practitioner's open and closed cases.
- [x] numeric count of open cases appears next to heading "Open Cases" as (#)
- [x] numeric count of closed cases appears next to heading "Closed Cases" (#)

![case list slimmed empty.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/5d2b1ccf-4e02-433e-b0f3-d1797de05776)

Practitioner has no open or closed cases

**Comment by matthopson** [comment]
Ready for UX Review on exp3
