### ISSUE TITLE
Court: Ensure proper electronic service

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7780]
As the Court, in order to ensure that we are making proper electronic service, we need to tweak some current processes.

## Acceptance Criteria:
* Court needs a fail safe to ensure that all outgoing emails for electronic service are sent when service volume is high [Potential solution: API requests that initiate service to offload heavy lifting to other Lambdas dedicated to building PDFs or serving email]
* Order of operations for electronic service must be well-defined and followed: (1) documents are prepared first, (2) Email service is attempted, and (3) finally the docket entry's state reflects the result of attempt -- Not Served vs. service information.
* If the service email is not successfully generated/sent, the user needs to be informed.
* If served email is not successful, the served stamp should not display on the document; the served information should not be on the docket record.

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [ ] Show error banner when service fails (Matt)
- [ ] Email service endpoint (Matt)
- [ ] Prevent served state on documents and docket record when service fails
  - [ ] Prevent served stamp from displaying on document
  - [ ] No service information on docket record

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [ ] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [ ] Lambdas include CloudWatch logging of users, inputs and outputs
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Rebuild entity documentation
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
## Add Paper Filing screen 
* If electronic service is not properly generated, remain on screen and display error message

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ba743977-49f4-4408-b09e-a34547deee71)

## Add Docket Entry screen 
* If electronic service is not properly generated, remain on screen and display error message

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/388a27ad-9b67-4ac6-8328-f1d9db767510)

## Review and Serve Petition screen 
* If electronic service is not properly generated, remain on screen and display error message

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8ce31ece-341c-4a9a-8755-58266b05613e)

## Message Detail screen 
* If electronic service is not properly generated, remain on screen and display error message

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8fb0bf97-6b1a-4f14-b274-077894a2a559)

**Comment by klohman** [comment]
## 8039 Test Case

#### 1) Service fails when docket clerk adds and serves paper filing
* Login as docket clerk 
* Go to case 
* Add Paper Filing
* Click Save and Serve 
* On confirmation modal, click Yes, Serve 
* [Service fails]
Expected results 
* App remains on Add Paper Filing screen 
* Error message displays 
* Service email is not received by parties
* Docket entry is added to Docket Record
* Docket entry displays “Not Served” in Served column
* Docket entry is blank in Parties column 

#### 2) Service fails when docket clerk adds and serves docket entry 
* Login as docket clerk 
* Go to case 
* Upload PDF 
* Add Docket Entry for PDF 
* Click Save and Serve 
* On confirmation modal, click Yes, Serve 
* [Service fails]
Expected results 
* App remains on Add Docket Entry screen 
* Error message displays 
* Service email is not received by parties
* Docket entry is added to Docket Record
* Docket entry displays “Not Served” in Served column
* Docket entry is blank in Parties column 

#### 3) Service fails when petitions clerk serves Petition 
* Login as petitions clerk 
* Go to Petition QC 
* Click on a Petition 
* Click Review Petition 
* Click Serve to IRS 
* On confirmation modal, click Yes, Serve 
* [Service fails]
Expected results 
* App remains on Review and Serve Petition screen 
* Error message displays 
* Service email is not received by parties
* Docket entry is added to Docket Record
* Docket entry displays “Not Served” in Served column
* Docket entry is blank in Parties column 

#### 4) Service fails when docket clerk serves document from message 
* Login as docket clerk 
* Go to message with unserved document attached 
* Click Serve 
* On confirmation modal, click Yes, Serve 
* [Service fails]
Expected results 
* App remains on Message Detail screen 
* Error message displays 
* Service email is not received by parties
* Docket entry is added to Docket Record
* Docket entry displays “Not Served” in Served column
* Docket entry is blank in Parties column
