### ISSUE TITLE
Error messages and logging for app failures

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7798]
## Pre-Conditions
[Spike ustaxcourt/ef-cms#7719](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7855)
## Acceptance Criteria
Provide more verbose/specific/user-friendly error handlers in the UI and in logging

- Delete Other Statistics deleteOtherStatisticsSequence
  - Red alert box with verbiage on Edit Other Statistic: "Statistic could not be deleted. Please try again."
- Deleting Trial Session deleteTrialSessionSequence
  - Red alert box with verbiage on New Trial Session page: "Trial session could not be deleted. Please try again."
- Sealing a Case sealCaseSequence
  - Red alert box with verbiage on Case Detail page: "Case could not be sealed. Please try again."
- Submitting Deficiency Statistics submitAddDeficiencyStatisticsSequence
  - Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be deleted. Please try again."
- Editing Deficiency Statistics submitEditDeficiencyStatisticsSequence
  - Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be edited. Please try again."
- Submitting Other Statistics submitAddOtherStatisticsSequence
  - Red alert box with verbiage on Submitting Other Statistic page: "Statistic could not be added. Please try again."
- Editing Other Statistics submitEditOtherStatisticsSequence
  - Red alert box with verbiage on Editing Other Statistic page: "Statistic could not be edited. Please try again."
- Submit Trial Session submitTrialSessionSequence
  - Red alert box with verbiage on Add Trial Session page: "Trial session could not be added. Please try again."
- Update Practitioner User submitUpdatePractitionerUserSequence
  - Red alert box with verbiage on Edit Practitioners Details page: "Practitioner could not be edited. Please try again."
- QC Complete for Trial updateQcCompleteForTrialSequence
  - Red alert box with verbiage on Trial Session Details page: "Could not complete QC eligible case. Please try again."
- Update Trial Session updateTrialSessionSequence
  - Red alert box with verbiage on Edit Trial Session page: "Trial session could not be edited. Please try again."

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes

- What detail can/should appear in logs to aid in diagnosis? Add this question to the user story when we create.
- When should errors be thrown all the way up to the lambda handler? Add this question to the user story when we create.
- If some unforeseen error occurs, what's the least obtrusive way to communicate it to the user? Add this question to the user story when we create.

## Tasks
- [x] Red alert box with verbiage on Edit Other Statistic: "Statistic could not be deleted. Please try again." (Jojo)
- [x] Red alert box with verbiage on New Trial Session page: "Trial session could not be deleted. Please try again."(Tom)
- [x] Red alert box with verbiage on Case Detail page: "Case could not be sealed. Please try again."(Tom)
- [x] Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be deleted. Please try again." (Jojo)
- [x] Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be edited. Please try again." (Jojo)
- [x] Red alert box with verbiage on Submitting Other Statistic page: "Statistic could not be added. Please try again." (Jojo)
- [x] Red alert box with verbiage on Editing Other Statistic page: "Statistic could not be edited. Please try again." (Jojo)
- [x] Red alert box with verbiage on Add Trial Session page: "Trial session could not be added. Please try again."(Tom)
- [x] Red alert box with verbiage on Edit Practitioners Details page: "Practitioner could not be edited. Please try again." (Jojo)
- [x] Red alert box with verbiage on Trial Session Details page: "Could not complete QC eligible case. Please try again."(Tom)
- [x] Red alert box with verbiage on Edit Trial Session page: "Trial session could not be edited. Please try again."(Tom)

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by cnelsonflexion** [comment]
![add other statistics.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/38a51f73-c08c-48c3-8813-7de6ab8239a5)

Logged in as docket
Browse to case -> Case Information -> Statistics
- [ ] Display above screen if app catches an error when adding a statistic

![delete other statistics.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/81335b14-c630-42d0-92a3-bc5e255e649c)
Browse to case -> Case Information -> Statistics -> Edit other statistic
- [ ] Display above screen if app catches an error when deleting a statistic

![edit other statistics.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/315f9a4c-992d-4776-981b-1a2d88c888e7)
Browse to case -> Case Information -> Statistics -> Edit other statistic
- [ ] Display above screen if app catches an error when editing a statistic

![case qc.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/01ceaff4-684e-4343-bfc5-a7f987c13769)
Browse to trial session with eligible case
- [ ] Display above screen if app catches an error when user checks "QC Complete?" box

![create trial session.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/abe80d25-6513-4c06-89ff-83170dbf5655)
Create a new trial session
- [ ] Display above screen if app catches an error that isn't basic form validation when user clicks "Add Session" button

![delete trial session.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/ce11661d-34d0-4274-9262-e9e9f04aad74)
Logged in as Petitions Clerk
Browse to a NEW trial session detail screen -> Edit
- [ ] Display above screen if app catches an error that isn't basic form validation when user clicks ""Delete session" link

![edit trial session.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/4e75efa7-d8c1-4dca-8374-b3bb52304eca)
Browse to trial session detail screen -> Edit
- [ ] Display above screen if app catches an error that isn't basic form validation when user clicks "Save" button

![edit practitioner.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/e65d0515-359a-401c-9da8-71d3f3135bac)
Logged in as Admissions Clerk
Browse to Advanced search and find a Practitioner
Click Edit link
- [ ] Display above screen if app catches an error that isn't basic form validation when user clicks "Save Updates" button

**Comment by klohman** [comment]
- [x] Delete Other Statistics deleteOtherStatisticsSequence
Red alert box with verbiage on Edit Other Statistic: "Statistic could not be deleted. Please try again."
- [x] Deleting Trial Session deleteTrialSessionSequence
Red alert box with verbiage on New Trial Session page: "Trial session could not be deleted. Please try again."
- [x] Sealing a Case sealCaseSequence
Red alert box with verbiage on Case Detail page: "Case could not be sealed. Please try again."
- [x] Submitting Deficiency Statistics submitAddDeficiencyStatisticsSequence
Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be deleted. Please try again."
- [x] Editing Deficiency Statistics submitEditDeficiencyStatisticsSequence
Red alert box with verbiage on Edit Deficiency Statistic page: "Statistic could not be edited. Please try again."
- [x] Submitting Other Statistics submitAddOtherStatisticsSequence
Red alert box with verbiage on Submitting Other Statistic page: "Statistic could not be added. Please try again."
- [x] Editing Other Statistics submitEditOtherStatisticsSequence
Red alert box with verbiage on Editing Other Statistic page: "Statistic could not be edited. Please try again."
- [x] Submit Trial Session submitTrialSessionSequence
Red alert box with verbiage on Add Trial Session page: "Trial session could not be added. Please try again."
- [x] Update Practitioner User submitUpdatePractitionerUserSequence
Red alert box with verbiage on Edit Practitioners Details page: "Practitioner could not be edited. Please try again."
- [x] QC Complete for Trial updateQcCompleteForTrialSequence
Red alert box with verbiage on Trial Session Details page: "Could not complete QC eligible case. Please try again."
- [x] Update Trial Session updateTrialSessionSequence
Red alert box with verbiage on Edit Trial Session page: "Trial session could not be edited. Please try again."
