### ISSUE TITLE
Party Redesign - Parties Tab - Docket / Petitions / Admissions View

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7822]
As DAWSON user, I need party information to be organized more intuitively so that I can locate information more easily.

## Pre-Conditions
* Case has multiple petitioners, an intervenor or participant, and petitioner counsel

## Acceptance Criteria
* Counsel (petitioner and intervenor/participant) should be visually tied to the representing petitioner. 
* Other filers (intervenor/participants) should be easily identifiable. 
* Existing functionality still exists and has been tested (List flows to test)

## Mobile Design/Considerations
* All information needs to be accessible on mobile 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- Consider potentially refactoring `OtherContactType` entity to use `Petitioner` and add 'participant' and 'intervenor to 'CONTACT_TYPES'
- Confirm that new view eliminates this bug https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7241

## Tasks
Internal only so far
- [x] Replace Petitioner, Respondent, and Other horizontal tabs with one Parties tab - Mob (#8242)
  - [x] Create Petitioner(s) & Counsel, Intervenor/Participants & Counsel, Respondent Counsel vertical tabs under new Parties horizontal tab
  - [x] Default to Petitioner(s) & Counsel tab
- [x] Petitioner(s) & Counsel - Mob (#8240, ustaxcourt/ef-cms-flexion#8241)
  - [x] Move petitioner information to cards, move (abbreviated) petitioner counsel info to same cards
  - [x] Move add counsel search bar to top of page
  - [x] Move Add Petitioner button next to search bar, rename to Add Party
- [x] Intervenor/Participants & Counsel - Mob (#8246)
  - [x] Hide when there are no intervenors/participants on case
  - [x] Move intervenors/participants information (from Other) to cards, move (abbreviated) intervenors/participants counsel info to same cards 
  - [x] Move add counsel search bar to top of page
  - [x] Add Add Party button next to search bar
- [x] Respondent Counsel:
  - [x] Move respondent counsel info to cards (from Respondent tab)

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
## Parties Tab  (Docket  Petitions / Admissions view) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/80fe3121-c02b-463d-be91-d0f2e266409d)

**Parties & Counsel tabs**
Display vertical tabs:
 Petitioner(s) & Counsel 
Intervenor/Participants & Counsel
Respondent Counsel 
Petitioner(s) tab is selected by default 
On click of a tab, display tab content 


### Petitioners & Counsel tab 
Display Add Counsel search bar at top 
Display “Add Party” button

**Add Party**
on click, route to Add Party form

#### Petitioner card 
Separate card for each petitioner 
Display Additional Name field (if applicable) above Mailing Address Line 1

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “Edit” link for each counsel 
On click of Edit link, app routes to Edit Counsel form

## Intervenor / Participants & Counsel tab
* Tab option is hidden if there are no intervenors or participants on a case  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a502e683-c4bd-4644-ab6b-45c1d84de485)

Display Add Counsel search bar at top (inactive until ustaxcourt/ef-cms#7836)
Display “Add Party” button

**Add Party**
on click, route to Add Party form

#### Intervenor/Participant card 
Separate card for each party 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “Edit” link for each counsel (inactive until ustaxcourt/ef-cms#7836)
On click of Edit link, app routes to Edit Counsel form

## Respondent Counsel tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2c6aaa70-60c7-4347-aa7e-a3ffadfe6859)

Display Add Counsel search bar at top 


#### Respondent Counsel card 
Separate card for each counsel 
Display info for counsel: 
Counsel name (Bar Number) 
Address 
Counsel phone number 
Counsel email 


**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 


Display “Edit” link for each counsel 
On click of Edit link, app routes to Edit Counsel form

**Comment by klohman** [comment]
## 8112 Test Cases 

#### 1) Docket / admissions / petitions clerk views petitioner information 
* Login as docket clerk 
* Go to case 
    * Pro se 
    * With Counsel 
    * With c/o
    * With no email/ pending email / current email 
* Click Case Information > Parties 
Expected results 
- [x] Petitioner & Counsel tab is selected by default
- [x] UI displays updated design 
    * Pro se - Petitioner card displays “None” for counsel
    * With Counsel - Petitioner card displays counsel 
    * With c/o - Petitioner card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links display for each petitioner (for Docket and Admissions only) 
* [x] Add Party link displays (for Docket only)
* [x] Add Counsel search box displays 
* [x] Edit link displays for each counsel 

#### 2) Docket / admissions / petitions clerk views intervenor/participant information 
* Login as docket clerk 
* Go to case 
    * No intervenor/participant on case 
    * With intervenor/participant 
* Click Case Information > Parties 
* Click Intervenor / Participant tab 
Expected results 
No intervenor/participant on case 
- [x] Intervenor/Participant tab is hidden 

With intervenor/participant on case 
- [x] UI displays updated design 
    * Pro se - card displays “None” for counsel
    * With Counsel - card displays counsel name, email, phone
    * With c/o - card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links display for each petitioner (for Docket and Admissions only)
* [x] Add Party link displays (for Docket only)
* [x] Add Counsel search box displays 
* [x] Edit link displays for each counsel 

#### 3) Docket / admissions / petitions clerk views respondent counsel information 
* Login as docket clerk 
* Go to case 
    * No respondent counsel 
    * With respondent counsel 
* Click Case Information > Parties > Respondent Counsel 
Expected results 
No respondent counsel 
-  [x] Tab displays “There is no respondent counsel associated with this case.”

With respondent counsel 
- [x] UI displays updated design 
    * card displays counsel name, address, phone, email, service
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links display for each counsel

**Comment by JessicaMarine** [comment]
PO Review:
1. The placement of the edit button seems to be off in 12738-18 in `mig`:
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/4ab0008a-1342-457a-a1ff-217a4473fa4d)
2. Were the test scenarios confirmed.  I don't see any of the boxes checked off?
3. This isn't exactly related to any one story, but I encountered an issue when testing the 5 stories ready for PO Review -- in mig in 14382-19, when I clicked on "Advanced" to go search for another case, the URL changed to: https://app.mig.ef-cms.ustaxcourt.gov/search but I wasn't routed there.  I had to refresh and click "Advanced" several times before it worked.  There seems to be something off with routing after all this re-work

**Comment by klohman** [comment]
Additional UX Review 

- When petitioner has a Pending email,  it displays in UI, but it also displays "No email provided". If email is pending, the pending email should display and the other state should be hidden
![Screen Shot 2021-05-12 at 11.57.42 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c0dc1c0a-0290-4c43-a7ee-8dadf9438435)
