### ISSUE TITLE
Docket Clerk: Add Petitioners to case (orig 2nd refactoring)

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7826]
[Is this functionality already covered by ustaxcourt/ef-cms#7166 and the UI changes that will be implemented by ustaxcourt/ef-cms-flexion#8112?]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to add additional petitioners to an existing case.

 ## Acceptance Criteria:
- Docket Clerk needs the ability to add more than two petitioners to a case. Petitioners will be added one at a time.
- Once added to a case, the petitioner should be treated as a full party to the case.
   - Show in the UI
      - Under the "Parties" tab
      - Listed in the filing party list for eFiled documents and paper filings
      - Listed as a party to be represented in the "Request Case Access" screen
      - Shows under Parties to be Served on the "Add Docket Entry" screen
      - Paper service modal
~~- Printable docket record~~ (moved to separate story ustaxcourt/ef-cms#7882)
     - Get paper service
 ~~- Have the party view of a case~~
   
   - Others?
- Once the petitioner is added to the case, they are "searchable" in the case, order and opinion searches

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] added petitioner displays everywhere that lists the parties on the case (mob)
  - [x] Add Docket Entry - Service Parties (mob)
  - [x] File a Document - Who is filing this document? (Mob)
  - [x] Listed as a party to be represented in the "Request Case Access" screen (Mob)
  - [x] Add Paper Filing - Who is filing this document? (Mob)
- [x] Add migration for docket entry changes (mob)
- [x] Update seed data (mob)
- [x] Show all petitioners when adding/editing counsel
- [x] Review your filing screen (after Request Access button and File a Document button) - Don't hardcode 'Petitioner', display petitioner or otherFilerType (Mob)
![image](https://user-images.githubusercontent.com/20514925/118286878-27be3800-b490-11eb-9ea7-c52747f43fd1.png)

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [x] Deployed to the Court's migration environment

 **Review Steps**
 1. Finish all other DOD
 2. Deploy to the dev environment
 3. Engineers add `Needs UX Review` label
 4. UX Review on dev environment (if feedback, implement and go back to step 2)
 5. UX add `Needs Migration Deploy` label
 6. Deploy to the Court's migration environment
 7. Engineers go through test scenarios on Court's migration environment
 8. Engineers add `Needs PO Review` label and move to Review/QA column
 9. PO review (if feedback, implement and go back to step 2)

**Comment by klohman** [comment]
Tests from 5386 

#### 6) Docket clerk adds petitioner and sees new petitioner when serving court-issued document 
* Login as docket clerk 
* Go to case
* Add new petitioner 
* Save 
* Upload PDF 
* Add Docket Entry for draft PDF 
Expected results 
- [x] New petitioner displays in the Service Parties list on the Add Docket Entry form

#### 7) Docket clerk adds petitioner and sees new petitioner when serving paper-filed document 
* Login as docket clerk 
* Go to case
* Add new petitioner 
* Save 
* Add Paper Filing 
Expected results 
- [x] New petitioner displays in the “Who is filing this document” field 

#### 8) Docket clerk adds petitioner, and new petitioner displays in filing party options when e-filing a document 
* Login as docket clerk 
* Go to case
    * Case has petitioner 1 with eAccess
* Add new petitioner 
* Save 
* Login as petitioner 1 
* Go to case 
* File a document 
Expected results 
- [x] New petitioner displays in the “Who is filing this document” field 

#### 11) Docket clerk adds petitioner counsel for new petitioner - MOVED TO 8131
* Go to case - not “New” status
* Add new petitioner 
    * Service = paper 
* Save 
* Search for private practitioner in Petitioner Counsel card 
    * Private practitioner is active in database
* Select new petitioner 
* Save 
Expected results 
- [x] new petitioner displays in list for “Representing” in Add Counsel modal 
- [x] On save, counsel displays in Petitioner Counsel card as representing new petitioner 
- [x] New petitioner service changes to None 

## From 5385
#### 3) Docket clerk removes petitioner with counsel representing only one petitioner - MOVED TO 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
    * Private practitioner represents petitioner 1 
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Click Yes, Remove 
Expected results 
On Edit Petitioner form 
- [x] Remove this Petitioner button display on form 
On click of Remove this Petitioner button 
- [x] modal displays 
- [x] petitioner name displays is warning message 
- [x] Current case caption is displayed in Case Caption field and is editable 
On Click of Yes, Remove 
- [x] modal closes and app routes to Petitioner tab with success message displayed 
- [x] Petitioner 1 no longer displays in Petitioner card 
- [x] Private practitioner no longer displays in Petitioner Counsel card 
- [x] Private practitioner no longer has eAccess to case and case does not display on dashboard

#### 4) Docket clerk removes petitioner with counsel representing multiple petitioners - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
    * Private practitioner represents petitioner 1 and petitioner 2
* Click Edit on petitioner 1 
* Click Remove This Petitioner 
* Click Yes, Remove 
Expected results 
On Edit Petitioner form 
- [x] Remove this Petitioner button display on form 
On click of Remove this Petitioner button 
- [x] modal displays 
- [x] petitioner name displays is warning message 
- [x] Current case caption is displayed in Case Caption field and is editable 
On Click of Yes, Remove 
- [x] modal closes and app routes to Petitioner tab with success message displayed 
- [x] Petitioner 1 no longer displays in Petitioner card 
- [x] Private practitioner displays in Petitioner Counsel card as representing petitioner 2 only 

#### 6) Docket clerk removes petitioner and adds paper filing - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Remove petitioner 2
* Add Paper Filing 
* Save and Serve 
Expected results 
- [x] petitioner 2 does not display under “Who is filing this document” in Add Paper Filing form
- [x] petitioner 2 does not receive service 

#### 7) Docket clerk removes petitioner and serves court issued document - MOVED to 8131
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
* Remove petitioner 2
* Upload PDF + Add Docket Entry 
* Save and Serve 
Expected results 
- [x] petitioner 2 does not display under Service Parties on Add Docket Entry form
- [x] petitioner 2 does not receive service 

#### 8) Docket clerk removes petitioner and party e-files a document 
* Login as docket clerk 
* Go to case 
    * Case has two petitioners 
        * Petitioner 1 has eAccess 
* Remove petitioner 2
* Login as petitioner 1 
* Go to case 
* efIle a Document
Expected results 
Expected results 
- [x] petitioner 2 does not display under “Who is filing this document” in Add Paper Filing form
- [x] petitioner 2 does not receive service

**Comment by klohman** [comment]
On Printable Docket record- need to increase spacing or adjust wrapping between petitioners 

![Screen Shot 2021-04-30 at 12.18.21 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f919a1df-83c9-40ae-a737-273188afe5ba)

**Comment by klohman** [comment]
Issues with petitioner counsel 
- when adding counsel and only selecting one petitioner and save - both petitioners are displaying as represented in the UI
- When removing a petitioner represented by counsel, got 400 error

**Comment by codyseibert** [comment]
one bug found:

1. create a case
2. add another party
3. attach a private practitioner to the new petitioner added
4. verify that case now shows up on the private practitioner dashboard
5. delete the newly added petitioner
6. BUG: the case still shows up on the practitioner dashboard even though he is not attached to any petitioners on that case

**Comment by klohman** [comment]
UX feedback for 8131 

- I'm getting a 404 error when trying to edit an added petitioner as their counsel. Steps to recreate: add petitioner, add counsel to new petitioner, login as counsel and click the "Edit" link for the represented petitioner 

- When adding a new email to any petitioner (original to case or added later), I received the "An account has been created for you" email.  I'm able to log in with the email but am seeing the "Need to verify email" warning, which shouldn't be displaying in this scenario, and I don't have full access to the case. See original story adding new email to petitioner https://github.com/flexion/ef-cms/issues/7807
![Screen Shot 2021-05-19 at 10.59.37 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/01bb2b98-17bf-4382-a20b-1b84eeff83e6)

**Comment by rosiehsmith** [comment]
@klohman
Since it seems like the 2nd bullet of feedback above is unrelated to this story, could you log this as a bug instead? Thank you!

**Comment by JessicaMarine** [comment]
Going to review routing issue as part of another story.

PO Review:
- On mig when I tried to add a second petitioner to 181-20, the success message displayed on a screen that looked like it was for "Intervenor(s)" even though there is no Intervenor in this case.  Also, "Intervenor(s)" shouldn't be plural
![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/cb771159-e7b8-41ca-a48a-a82206f4ad15)
