### ISSUE TITLE
Docket Clerk: Add Intervenor to case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7827]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to add an intervenor to an existing case.
 
## Acceptance Criteria:
- Docket Clerk needs the ability to add an intervenor to a case. [Note: only 1 intervenor allowed per case]
- Once added to a case, the intervenor should be treated as a full party to the case.
  - Show in the UI
      - Under the "Parties" tab
      - Listed in the filing party list for eFiled documents and paper filings
      - Listed as a party to be represented in the "Request Case Access" screen
      - Shows under Parties to be Served on the "Add Docket Entry" screen
      - Paper service modal
~~- Printable docket record~~ (moved to separate story ustaxcourt/ef-cms#7882)
     - Get paper service
 ~~- Have the party view of a case~~
   - Others?
- Once the intervenor is added to the case, they are "searchable" in the case, order and opinion searches

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Add `Intervenor` party type to select on Add Party view
- [x] Add validation for `contactType.onChange`, if an Intervenor already exists on the case
- [x] After save, persist party tab (e.g. Petitioners/Counsel, Intervenor/Participants, etc.)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![Parties - Docket View.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/93f35983-0b0b-4e9c-9653-63a11a3f681e)

## Add Party button 

On click of “Add Party” button from their Petitioneer or Intervenor .Particpant tabs, route to Add Party form

![dropdown.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/95fad211-091a-4b5d-a3cc-72b80e79e718)

![Add Petitioner Form - role.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/8975e0bb-5703-4f92-a5ed-c3dd56660f31)

![Add Petitioner form - role error.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/cee854b1-8b44-4209-b897-d9a373453c55)

## Add Party form 


**Petitioner type**
Dropdown options include: 
- [x] Petitioner 
- [x] Intervenor
- [x] Participant (TBD 8133)

- [ ] If Intervenor is selected in the dropdown and there is one already added to the case, display error modal onChange

**Form content** * identical to current “Add Petitioner” 
 
#### On Save 
- [x] app routes to Parties screen with success message (note: Should return to whichever tab they initiated the action from) 

- [x] Party is added to case and displays in UI (no changes)

![Add Paper Filing.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/8704e300-f33d-436e-b6b0-ea7ccf1ff135)

Test case

- Logged in as docket clerk. Browse to a case
Create -> New Paper Filing

Expected results 
- [x] Intervenor should appear under “Who is filing this document?” as (firstname lastname, Intervenor)

Additional UI Note
- [x] To have the party(s) name treatment consistent, other parties should appear as (firstname lastname, partytype)

![External party - File a Document.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/1369f610-e440-4c71-bd6e-f9c9a0d1f72e)

Test case

- Logged in as external user. Browse to a case
Click File a Document and select a document type
Click Continue

Expected results
- [x] Intervenor should appear under “Tell Us About the Parties Filing The Document(s)”

![Add counsel.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/f9eb819c-0935-44b1-8797-aa8cf7b56e43)

Test case

- Logged in as docket clerk. Browse to a case
Case Information -> Parties tab -> Add Petitioner Counsel

Expected results 
- [x] Intervenor should appear under “Who is this counsel representing?” as (firstname lastname, Intervenor)

Additional UI change
- [x] To have the party(s) name treatment consistent, other parties should appear as (firstname lastname, partytype)

![Edit Petitioner Counsel.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/7d0e92fa-de71-4405-b399-6b056110bd17)

Test case

- Logged in as docket clerk. Browse to a case
Case Information -> Parties tab
Edit link next to counsel name

Expected results 
- [x] Intervenor should appear under “Representing” as (firstname lastname, Intervenor)

Additional UI change
- [x] To have the party(s) name treatment consistent, other parties should appear as (firstname lastname, partytype)

![Docket-111-20-Add-docket-entry-U-S-Tax-Court 2.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/0058ca18-3f0d-4e7f-9105-c834b8787395)

![Docket-111-20-Add-docket-entry-U-S-Tax-Court1 1.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/f7cc9ac3-8974-48ab-bd46-268d02f6a357)

Test cases

- Logged in as docket clerk. Browse to a case
Create -> Order

Expected results 
- [x] Intervenor should appear under “Service parties” as (firstname lastname, Intervenor) Service type
- [x] Intervenor should appear in Save and Serve modal in alert treatment as (firstname lastname, Intervenor) Service type if service type = paper
