### ISSUE TITLE
Docket Clerk: Add Participant to case

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7828]
As a Docket Clerk, in order to properly manage the parties to a case, I need the ability to add a participant to an existing case.
 
## Acceptance Criteria:
- Docket Clerk needs the ability to add more than one participant to a case. Participants will be added one at a time.
- Once added to a case, the participant should be treated as a full party to the case.
   - Show in the UI
      - Under the "Parties" tab
      - Listed in the filing party list for eFiled documents and paper filings
      - Listed as a party to be represented in the "Request Case Access" screen
      - Shows under Parties to be Served on the "Add Docket Entry" screen
      - Paper service modal
~~- Printable docket record~~ (moved to separate story ustaxcourt/ef-cms#7882)
     - Get paper service
 ~~- Have the party view of a case~~
   - Others?
- Once the participant is added to the case, they are "searchable" in the case, order and opinion searches

## Notes
* 

## Security Considerations
 - [x] Does this work make you nervous about privacy or security?
 - [x] Does this work make major changes to the system?
 - [x] Does this work implement new authentication or security controls?
 - [x] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Move Add Party button below sidebar tabs - mob ustaxcourt/ef-cms-flexion#8313
- [x] 2 Add Party form 
- [x] 2a Change “Petitioner type” to “Role type”
- [x] 2b Add Participant to Role type options
- [x] 3 On save of Add Party form, if adding a participant, route to Parties screen > Intervenor/Participant tab
- [x] 3a Success message displays “Participant [name] has been added to case.”
- [x] 4 Add (court-issued) Docket Entry screen - participant should appear under “Service parties” as (name, Participant) with service type displayed; also petitioners should display as (name, Petitioner) (Mob)
- [x] 5 If participant has paper service, the paper service modal should display on Save and Serve of Add (court-issued) Docket Entry (name, Participant); also petitioners should display as (name, Petitioner)
- [x] 6 Add Paper Filing screen - participant should appear under “Who is filing this document” as (name, Participant) ; also petitioners should display as (name, Petitioner)
- [x] 7 File a Document screen (external parties) - participant should appear under “Who is filing this document” as (name, Participant); also petitioners should display as (name, Petitioner)
- [x] 8 Once participant is added to case, they should be searchable in case petitioner search
- [x] 9 Write migration script for contactType refactor

## Refactoring
- [x] 1 Move `petitionerTitle` generated in `fileDocumentHelper` into a more reusable place - it's also used in `partiesInformationHelper`
- [x] 2 Change otherFilerType to contactType.participant / contactType

## Bugs
- [x] 1 Parties not shown under `Are You Ready to Initiate Service?` modal when Save & Serving new paper docket entry

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
participant - can only be added after the case is started, not listed in the case caption, but once in the case can do most of the same things as a petitioner;
 they don't get the same status as a petitioner. For example, in partnership cases, there are rules around who can file a petition w/in a partnership. Tax matters partner has first option to file a petition in the court. If they don't do that, then others can.

**Comment by klohman** [comment]
## Parties > Intervenor/Participant tab 

* Add Party displays below sidebar tabs 
* On click of Add Party, route to Add Party form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0dc86470-048b-43af-affa-8780aa805f7a)

## Add Party form 

**Role type** - This is currently labelled as "Petitioner Type- please update to "Role type"
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aa2a3c0b-7706-40e8-832d-c125a0f361b9)
Dropdown options include: 
Petitioner 
Intervenor
Participant

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3daa4f9a-bda7-4b26-802e-9f530ce70b6a)
**Form content** * identical to current “Add Petitioner” 
 
* No limit on how many participants can be added to a case

#### On Save 
* app routes to Parties screen > Intervenor/Participant tab selected 
* Success message displays “Participant [name] has been added to case.”
* Party is added to case and displays in UI under Intervenor / Participant tab 


## Add Docket Entry screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/76415db5-bd1b-4039-ba09-3a9f32da7e58)

* Participant should appear under “Service parties” as (name, Participant) with service type displayed

## Paper Service modal 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d1260d45-6ae6-4324-b333-aed6a1a9f63b)

* If Participant has paper service, the paper service modal should display on Save and Serve  (name, Participant)


## Add Paper Filing screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0952ce8d-8c59-4dfb-853e-1e4e0605376d)

* Participant should appear under “Who is filing this document” as (name, Participant) with service type displayed


## File a Document screen (external parties)

* Participant should appear under “Who is filing this document” as (name, Participant) with service type displayed

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/380ebaf3-bba9-4e90-8259-464c13525d54)

**Comment by klohman** [comment]
## 8133 Tests 

#### 1) Docket clerk adds participant to case and views participant contact information 
* Login as docket clerk 
* Go to case 
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Complete form 
* Save 
Expected results 
- [x] App routes to Case Info > Parties with Intervenor/Participant tab selected 
- [x] success message displays “Participant [name] has been added to case.” 
- [x] Participant info displays correctly under Participant tab 

#### 2) Docket clerk adds participant with paper service to case and adds docket entry 
* Login as docket clerk 
* Go to case 
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Select “Paper” as service preference
* Complete form 
* Save 
* Upload PDF 
* Click Add Docket Entry 
* Complete form 
* Click Save and Serve 
* Click Yes, Serve
Expected results 
On Add Docket Entry form 
- [x] Participant displays under Service Parties as “[name], Participant”
On Save and Serve 
- [x] print paper service modal displays with participant info as “[name], Participant”
On Yes, Serve 
- [x] App routes to Print paper service screen 
- [x] Participant address is printed on address page for PDF 

#### 3) Docket clerk adds participant without paper service to case and adds docket entry 
* Login as docket clerk 
* Go to case 
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Select “None” as service preference
* Complete form 
* Save 
* Upload PDF 
* Click Add Docket Entry 
* Complete form 
* Click Save and Serve 
* Click Yes, Serve
Expected results 
On Add Docket Entry form 
- [x] Participant displays under Service Parties as “[name], Participant”
On Yes, Serve 
- [x] App routes to Docket Record with success message  
- [x] Participant does not receive service 

#### 4) Docket clerk adds participant with paper service to case and adds paper filing 
* Login as docket clerk 
* Go to case 
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Select “Paper” as service preference
* Complete form 
* Save 
* Click Add paper filing 
* Complete form 
* Click Save and Serve 
* Click Yes, Serve
Expected results 
On Add Paper Filing form 
- [x] Participant displays under Who is Filing this Document as “[name], Participant”
On Save and Serve 
- [x] print paper service modal displays with participant info as “[name], Participant”
On Yes, Serve 
- [x] App routes to Print paper service screen 
- [x] Participant address is printed on address page for PDF 

#### 5) Docket clerk adds participant without paper service to case and adds paper filing 
* Login as docket clerk 
* Go to case 
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Select “None” as service preference
* Complete form 
* Save 
* Upload PDF 
* Click Add Paper Filing
* Complete form 
* Click Save and Serve 
* Click Yes, Serve
Expected results 
On Add Docket Entry form 
- [x] Participant displays under Service Parties as “[name], Participant”
On Yes, Serve 
- [x] App routes to Docket Record with success message  
- [x] Participant does not receive service 

#### 6) Docket clerk adds participant and party files a document 
* Login as docket clerk 
* Go to case xx1-21
    * Case has petitioner with eAccess
* Click Case Information > Parties 
* Click Add Party button 
* Select “Participant” as petitioner type 
* Select “None” as service preference
* Complete form 
* Save 
* Login as petitioner 
* Go to case xx1-21
* File a Document 
* Complete Form 
* Submit 
Expected results 
On File a Document form 
- [x] Participant displays under Service Parties as “[name], Participant”

**Comment by klohman** [comment]
UX feedback 

- Participant with service indicator “None” is receiving paper service - an address sheet is being generated for the participant with None as service
