### ISSUE TITLE
Manual Testing Post 7839 Refactor

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#7838]
## Acceptance Criteria 

AC 1) Team has performed manual testing on the Court migration environment **in Edge** for the following user flows, defined in https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing
2) all bugs are logged

- [x] Calendaring (Rachael)
- [x] Edit Case Metadata (Rachael)
- [x] Search and Reporting (Themis mob)
- [x] Court-Issued Document Workflow (Cody)    
- [x] Trial Session Working Copy (Matt)
- [x] Practitioner Database (Rachael)
- [x] Messaging (Jojo)
- [x] External Parties Workflows (Matt)
- [x] Petition Workflow - Internal (Mrinalini)
- [x] Add Paper Filing- Internal (Cody)
- [x] Service emails (Themis mob)
- [x] QC eFiling - Internal (Rosie/Tom)
- [x] Mobile (Rachael/Rae)
- [x] Stip Decision flow (Kristen)
- [x] Correspondence File (Matt)
- [x] Public Users (Rosie)
- [x] User Management (Jojo)
 

## Tasks (Draft)
- [x] Complete steps in Test Matrix (as assigned)
- [x] Document any test failures in Test Matrix
- [x] Validate / reproduce bug (pair with Kristen) 
- [x] Log bugs in Zenhub 

## Definition of Done 
- [x] All tests cases have been performed on the Court's migration environment 
- [x] All bugs discovered have been logged in Github

**Comment by codyseibert** [comment]
When testing the court issued document workflow scenario ustaxcourt/ef-cms#6493, when clicking the "Edit Title" link after creating a notice, the drop-down did not default to "Notice".  I would have expected the "Select Order Type" to have defaulted to the order I was editing?  I think if the page refreshes, the the dropdown is cleared and doesn't default to the order type.

**Comment by codyseibert** [comment]
Court issued document workflow number 5 makes no mention of filing a "filed date" when doing a transcript, but I have both a Date of Trial input, and a Filed Date.  I just wanted to verify this is expected.

Also, I type 09/09/20 in the input, and the document title became this: Transcript of test on 09-09-0020.  That seems like a bug?  I would think type 09/09/20 would default to 09/09/2020

**Comment by klohman** [comment]
> When testing the court issued document workflow scenario ustaxcourt/ef-cms#6493, when clicking the "Edit Title" link after creating a notice, the drop-down did not default to "Notice". I would have expected the "Select Order Type" to have defaulted to the order I was editing? I think if the page refreshes, the the dropdown is cleared and doesn't default to the order type.

@codyseibert Yes, the dropdown is expected to be populated with the current selection.

**Comment by klohman** [comment]
> Court issued document workflow number 5 makes no mention of filing a "filed date" when doing a transcript, but I have both a Date of Trial input, and a Filed Date. I just wanted to verify this is expected.
> 
> Also, I type 09/09/20 in the input, and the document title became this: Transcript of test on 09-09-0020. That seems like a bug? I would think type 09/09/20 would default to 09/09/2020

The date that is important for the TRAN is the Date of Trial. Filed date can be the current date for this test.  For the date input, I'm not sure that is a bug -- USWDS component may just required a 4 digit input.
