### ISSUE TITLE
Party Redesign: Edit and Delete Counsel form

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7871]
As a docket clerk, in order to update counsel for a party, I need the ability to edit and delete the counsel in a more user friendly way. 

## Acceptance Criteria
* Docket clerk can edit counsel for all party types
* Docket Clerk can delete counsel for all party types
* Existing functionality still exists (Service updates, who they're representing, etc)

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Edit Petitioner Counsel Form
  - [x] Remove existing modal code
  - [x] Fields & Validation
  - [x] Delete button

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Edit Petitioner Counsel form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/afc1563f-cd18-4eda-ae53-d1a523949aec)

**Replaces the current Edit Practitioner modal!**

Display Counsel information (read-only) 
Name (Bar number)
Address 
Phone number 
email 

**Representing**
Field is hidden for Respondent Counsel

For private practitioners:
Display all parties on the case (except Respondent) 
Represented parties are checked 

**Service preference** * Display current service preference 

#### On Save 
Changes are saved, and app routes back to Paarties tab with success message displayed 

#### Remove Counsel button 
On click, display Remove Counsel modal 

## Remove Counsel confirmation modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/aad42fc2-7d46-4eb5-bbfd-4fc763afb1ea)

Display selected counsel Name (Bar number) in message

**On cancel**
 return to Edit Counsel screen

**On Yes, Remove**
Modal closes, app routes to Parties tab with success message 
Counsel is removed from case and no longer displays in UI 
Counsel no longer has party access to case and case does not display on counsel’s dashboard

**Comment by klohman** [comment]
#### 1) Docket clerk edits counsel 
* Login as docket clerk 
* Go to case 
    * With petitioner counsel 
    * With respondent counsel 
* Click Case Info > Parties > Petitioner 
* Click edit on petitioner counsel 
* Update representing parties 
* Save 
* Click Case Info > Parties > Respondent 
* Click Edit for respondent counsel
* Update service 
* Save 
Expected results 
- [ ] Updated information displays in UI 

#### 2) Docket clerk removes counsel 
* Login as docket clerk 
* Go to case 
    * With petitioner counsel 
    * With respondent counsel 
* Click Case Info > Parties > Petitioner 
* Click edit on petitioner counsel 
* Click Remove Counsel
* Click Yes, Remove on modal  
* Click Case Info > Parties > Respondent 
* Click Remove Counsel
* Click Yes, Remove on modal  
Expected results 
- [ ] Removed counsel no longer displays in UI 
- [ ] Counsel no longer has access to case in DAWSON
- [ ] Case no longer displays on counsel’s dashboard
