### ISSUE TITLE
Party Redesign: Parties Tab - Non-docket view

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7875]
As DAWSON user, I need party information to be organized more intuitively so that I can locate information more easily.

## Pre-Conditions
* Case has multiple petitioners, an intervenor or participant, and petitioner counsel

## Acceptance Criteria
* Counsel (petitioner and intervenor/participant) should be visually tied to the representing petitioner. 
* Other filers (intervenor/participants) should be easily identifiable. 
* Existing functionality still exists and has been tested (List flows to test)

## Mobile Design/Considerations
* All information needs to be accessible on mobile 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- confirm that new view eliminates this bug https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7241

## Tasks
Internal only

- [x] Petitioner(s) & Counsel:
  - [x] Add View button to open new Petitioner Counsel Modal
  - [x] Add modal on View with Counsel Info - Done by 8219 mob # ustaxcourt/ef-cms-flexion#8275
  - [x] Add sequences associated with populating Counsel Info modal  - Done by 8219 mob # ustaxcourt/ef-cms-flexion#8275

- [x] Intervenor/Participants & Counsel:
  - [x] Add View button to open new Petitioner Counsel Modal
  - [x] Add modal on View with Counsel Info - Done by 8219 mob # ustaxcourt/ef-cms-flexion#8275

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Parties Tab  (Non-Docket view) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e4c7faf0-9c05-4fcc-9201-030710e9a1f6)

**Parties & Counsel tabs**
Display vertical tabs:
 Petitioner(s) & Counsel 
Intervenor/Participants & Counsel
Respondent Counsel 
Petitioner(s) tab is selected by default 
On click of a tab, display tab content 


### Petitioners & Counsel tab 

#### Petitioner card 
Separate card for each petitioner 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/87a245b0-af68-4ffc-842c-80a5fe207845)


## Intervenor/Participants & Counsel tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9582bc59-9648-4a3d-a530-ac8b4a5745cf)#### Party card 
Separate card for each party 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays

## Respondent Counsel tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/50993694-a41a-4aa8-a54a-6eacf6c36d96)

#### Respondent Counsel card 
Separate card for each counsel 
Display info for counsel: 
Counsel name (Bar Number) 
Address 
Counsel phone number 
Counsel email 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]”

**Comment by klohman** [comment]
## Test Cases 

#### 1) Court user (non-docket) clerk views petitioner information 
* Login as ADC / judge 
* Go to case 
    * Pro se 
    * With Counsel 
    * With c/o
    * With no email/ pending email / current email 
* Click Case Information > Parties 
Expected results 
- [x] Petitioner & Counsel tab is selected by default
- [x] UI displays updated design 
    * Pro se - Petitioner card displays “None” for counsel
    * With Counsel - Petitioner card displays counsel 
    * With c/o - Petitioner card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links are hidden for petitioners
* [x] Add Party link is hidden 
* [x] Add Counsel search box is hidden 
* [x] “View” link displays for each counsel 

#### 2) Court user views petitioner counsel information 
* Login as ADC / judge 
* Go to case 
    * Petitioner has counsel 
* Click Case Information > Parties 
* Click View link for petitioner counsel 
Expected results 
- [x] Petitioner counsel modal displays with correct counsel information

#### 3) Court user (non-docket) views intervenor/participant information 
* Login as ADC / judge 
* Go to case 
    * Case w/o intervenor or participant 
    * Case with Intervenor + Participant 
        * At least one intervenor / participant has counsel
* Click Case Information > Parties > Intervenor / Participant 
Expected results 
No intervenor/participant on case 
- [x] Intervenor/Participant tab is hidden 

Case with intervenor/ participant 
- [x] UI displays updated design 
    * Pro se -  card displays “None” for counsel
    * With Counsel - card displays counsel 
    * With c/o - card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links are hidden for intervenor/participant
* [x] Add Party link is hidden 
* [x] Add Counsel search box is hidden 
* [x] “View” link displays for each counsel 

#### 4) Court user (non-docket) views respondent counsel information 
* Login as ADC / petitions clerk / judge 
* Go to case 
    * No respondent counsel 
    * With respondent counsel 
* Click Case Information > Parties > Respondent Counsel 
Expected results 
No respondent counsel 
-  [x] Tab displays “There is no respondent counsel associated with this case.”

With respondent counsel 
- [x] UI displays updated design 
    * card displays counsel name, address, phone, email, service
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links is hidden for counsel

**Comment by klohman** [comment]
UX Feedback 
- The "Edit" link for petitioners should not be displaying for court users other than Docket, Petitions, Admissions, and Clerk of the Court. I logged in as ADC and Trial Clerk and am seeing the link. 

- The "Edit" link for respondent counsel should not be displaying for court users other than Docket, Petitions, Admissions, and Clerk of the Court. I logged in as ADC and Trial Clerk and am seeing the link. 

- "Add Counsel" field should not should not be displaying for court users other than Docket, Petitions, Admissions, and Clerk of the Court. I logged in as ADC and Trial Clerk and am seeing the field.
