### ISSUE TITLE
Party Redesign: Parties Tab - External Parties View + mobile view

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7876]
As DAWSON user, I need party information to be organized more intuitively so that I can locate information more easily.

## Pre-Conditions
* Case has multiple petitioners, an intervenor or participant, and petitioner counsel

## Acceptance Criteria
* Counsel (petitioner and intervenor/participant) should be visually tied to the representing petitioner. 
* Other filers (intervenor/participants) should be easily identifiable. 
* Existing functionality still exists and has been tested (List flows to test)

## Mobile Design/Considerations
* All information needs to be accessible on mobile 

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- confirm that new view eliminates this bug - https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/7241

## Tasks - 
- [x] Replace Petitioner, Respondent, and Other horizontal tabs with one Parties tab
  - [x] Create Petitioner(s) & Counsel, Intervenor/Participants & Counsel, Respondent Counsel vertical tabs under new Parties horizontal tab
  - [x] Default to Petitioner(s) & Counsel tab

## Definition of Done (Updated 2-23-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Flexion mig env

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Module dependencies are up-to-date and are at the latest resolvable version (npm update)
 - [x] Errors in Sonarcloud are fixed https://sonarcloud.io/organizations/flexion-github/projects
 - [x] Lambdas include CloudWatch logging of users, inputs and outputs
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Rebuild entity documentation
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to the dev environment
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Parties Tab  (External Parties view) 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4e277b7a-7ca4-47c8-b442-c6e0c5547de6)

**Parties & Counsel tabs**
Display vertical tabs:
 Petitioner(s) & Counsel 
Intervenor/Participants & Counsel
Respondent Counsel 
Petitioner(s) tab is selected by default 
On click of a tab, display tab content 

### Petitioners & Counsel tab 

#### Petitioner card 
Separate card for each petitioner 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Edit link**
For Petitioner user 
* Display only for the petitioner associated with the user account (current behavior) 

For private practitioner user: 
* Display only for the petitioner who is represented with the user account (current behavior) 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays


## Mobile View - Parties tabs 

* On mobile, tabs collapse into dropdown 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8ab8400f-698a-4fdb-ab38-a540dcd91e9f)

### Petitioner tab
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/2b0cfd6a-5264-416e-a47f-e4ffa221e964)

### Petitioner Counsel modal
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8aa61232-fd40-4934-9f49-01196aa91422)


## Intervenor/Participants & Counsel tab 
* tab display as option only if there is an intervenor or participant on the case 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f5129f96-b7a0-4345-b3f2-43a24c97e691)


#### Party card 
Separate card for each party 

**Email field**
Display email beneath phone number without label 
If no email - display “No email provided” 
If pending email - display “[email address] (Pending)”
If current email - display “[email address]” 

**Counsel** 
Display info for each counsel representing this petitioner 
Counsel name (Bar Number) 
Counsel email 
Counsel phone number 

Display “View” link for each counsel 
On click of View link, Counsel Info modal displays

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8cb0628c-e9c6-49de-b7e3-227ff00d3120)

## Respondent tab - Desktop 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f3f216ec-231d-4627-be08-d9dae7f82896)

### Mobile - Respondent tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6a3cc8ac-91a1-421e-813e-8db4f84e1c7c)

**Comment by klohman** [comment]
## Test Cases

#### 1) Party to case views petitioner information 
* Login as external user (petitioner, private practitioner, irs practitioner) 
* Go to case 
    * Party is associated with case 
* Click Case Information > Parties 
Expected results 
- [x] Petitioner & Counsel tab is selected by default
- [x] UI displays updated design 
    * Pro se - Petitioner card displays “None” for counsel
    * With Counsel - Petitioner card displays counsel 
    * With c/o - Petitioner card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links display for logged in petitioner only
* [x] Add Party link is hidden 
* [x] Add Counsel search box is hidden 
* [x] View link displays for each counsel 

#### 2) Party to case edits their own petitioner information (address/phone) 
* Login as external user (petitioner)
* Go to case 
    * Party is associated with case 
    * There is more than one petitioner on the case
* Click Case Information > Parties 
* Click Edit link for logged in petitioner 
* Update form 
* Save 
Expected results 
- [x] Edit link only displays for the petitioner logged in 
- [ ]Updated information displays in UI 
- [x] Current functionality is unchanged 
    - If address / phone is updated, Notice of Change of Address / Phone is generated 

#### 3)  Party to case views intervenor/participant information 
* Login as external user (petitioner)
* Go to case 
    * Logged in user is associated with case
    * Case w/o intervenor or participant 
    * Case with Intervenor + Participant 
        * At least one intervenor / participant has counsel
* Click Case Information > Parties > Intervenor / Participant 
Expected results 
No intervenor/participant on case 
- [x] Intervenor/Participant tab is hidden 

Case with intervenor/ participant 
- [x] UI displays updated design 
    * Pro se -  card displays “None” for counsel
    * With Counsel - card displays counsel 
    * With c/o - card displays “c/o” above address 
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links are hidden for intervenor/participant
* [x] Add Party link is hidden 
* [x] Add Counsel search box is hidden 
* [x] “View” link displays for each counsel 

#### 4)  Party to case views respondent counsel information 
* Login as external user (petitioner)
* Go to case 
    * No respondent counsel 
    * With respondent counsel 
* Click Case Information > Parties > Respondent Counsel 
Expected results 
No respondent counsel 
-  [x] Tab displays “There is no respondent counsel associated with this case.”

With respondent counsel 
- [x] UI displays updated design 
    * card displays counsel name, address, phone, email, service
    * With no email/ pending email / current email - Email displays correctly per design notes 
* [x] “Edit” links is hidden for counsel  

#### 5) Party to case views petitioner information (Mobile)
* Login as external user (petitioner) on mobile device 
* Go to case 
    * Logged in user is associated with case
* Select Petitioner(s) & Counsel from navigation dropdown 
Expected results 
- [x] Navigation dropdown contains: 
    - Docket Record 
    - Case Information
    - Overview 
    - Petitioner(s) & Counsel 
    - Intervenor/Participant(s) & Counsel (if intervenor or participant is on the case) 
    - Respondent Counsel  
- [x] Updated UI displays per design 

#### 6)  Party to case views intervenor/participant information (Mobile)
* Login as external user (petitioner) on mobile device 
* Go to case 
    * Logged in user is associated with case
* Select Intervenor/Participant(s) & Counsel from navigation dropdown 
Expected results 
- [x] Navigation dropdown contains: 
    - Docket Record 
    - Case Information
    - Overview 
    - Petitioner(s) & Counsel 
    - Intervenor/Participant(s) & Counsel (if intervenor or participant is on the case) 
    - Respondent Counsel  
- [x] Updated UI displays per design 

#### 7)  Party to case views respondent counsel information (Mobile)
* Login as external user (petitioner) on mobile device 
* Go to case 
    * Logged in user is associated with case
* Select Respondent Counsel from navigation dropdown 
Expected results 
- [x] Navigation dropdown contains: 
    - Docket Record 
    - Case Information
    - Overview 
    - Petitioner(s) & Counsel 
    - Intervenor/Participant(s) & Counsel (if intervenor or participant is on the case) 
    - Respondent Counsel  
- [x] Updated UI displays per design 

#### 8) Party to case views petitioner counsel information (Mobile) 
* Login as external user (petitioner) on mobile device 
* Go to case 
    * Logged in user is associated with case
* Select Petitioner(s) & Counsel from navigation dropdown 
* Click View link by petitioner counsel 
Expected results
- [x] Petitioner counsel modal displays mobile view in UI

**Comment by klohman** [comment]
## UX Review feedback 

- 1)  When petitioner email is pending, it is still showing "No email provided" for external users (example on 598-21, Gary has a pending email if you log in as docket clerk)

![Screen Shot 2021-05-13 at 11.24.17 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/016522c7-67ac-4741-81ab-962460088dd1)


- 2) When petitioner clicks Edit link for their contact information, they should be routed to the external Edit Contact Information screen (this was current functionality and we didn’t intend to change this, although I understand why there would be confusion). On dev, it looks like the Edit link is going to the internal view for Edit Party info. 
    - The current and accurate Edit Contact Information form for external users is working on migration as of now (for reference). 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/befcd093-0ae6-44cc-a892-0997e23185df)
