### ISSUE TITLE
FiledBy Value for Private Practitioners Efiling 'Access to Case' Documents Reflects Filer Instead of Party

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7880]
As the Court, we need the Filed By value for e-filed case entry documents to reflect the name of the filer, not the party they represent.

With case entry documents, it is important to document the name of the person e-filing the document requesting access to the case so that parties and the Court can easily tell who the request is being made by.

We want to display the name of the private practitioner on the docket record in the case of e-filing the following documents:

Entry of Appearance
Limited Entry of Appearance
Notice of Election to Intervene
Notice of Election to Participate
Notice of Intervention
Substitution of Counsel

## Acceptance Criteria
* The filedBy value shown on the docket record for `Access to Case` documents should be the Name of the Private Practitioner logged in and filing the document
* This applies to Private Practitioners only; IRS Practitioner behavior is unchanged (IRS will continue to show RESP)
* This applies to electronically filed documents only; paper filings continue to work as normal (e.g., Docket selects the filing party when they enter the document)

## Notes
- How does this apply to paper-filed documents from the Request Access list? **It doesn't. Applies to e-filed docs only**
- Does this apply to both private and irs practitioners? **No.**
- Companion/duplicate of ustaxcourt/ef-cms#7188

## Test Cases
* Private Practitioner efiles a case entry document; document appears on docket record in DAWSON needing QC; Filed By value shows as the Name associated with the user of the logged in account that submitted the document to the court
* IRS Practitioner efiles a case entry document; document appears on docket record in DAWSON needing QC; Filed By value shows as the party filed on behalf of as selected in the submission (regression)
* Private Practitioner efiles a non-case entry document; document appears on docket record in DAWSON needing QC; Filed By value shows as the party filed on behalf of as selected in the submission (regression)

## Tasks
- [x] Create entity constant for documents filed by private practitioners - Rosie, Mrinalini, Rachel (https://github.com/ustaxcourt/ef-cms/pull/2114)
- [x] Update e-filing endpoints to use constant to determine filing party - Rosie, Mrinalini, Rachel (https://github.com/ustaxcourt/ef-cms/pull/2114)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Updated Docket Entry 
* for event codes e-filed by private practitioner: 
   * Entry of Appearance 
   * Limited Entry of Appearance 
   * Motion to Substitute Parties and Change Caption 
   * Notice of Election to Intervene
   * Notice of Election to Participate
   * Notice of Intervention 
   * Substitution of Counsel 

* Filed By columns displays [Private Practitioner Name]
   * Example: Sally Attorney is the authenticated private practitioner 



![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c69fa26-8023-4aee-bac5-b8f0f76a9527)

**Comment by klohman** [comment]
## 8255 Test Scenarios 

#### 1) Private Practitioner e-files Entry of Appearance in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Entry of Appearance 
* View docket record 
Expected results 
- [ ] Docket entry for Entry of Appearance displays filed by Test Practitioner 

#### 2) Private Practitioner e-files Limited Entry of Appearance in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Limited Entry of Appearance 
* View docket record 
Expected results 
- [ ] Docket entry for Limited Entry of Appearance displays filed by Test Practitioner 

#### 3) NO LONGER APPLICABLE PER COMMENT FROM CHRIS BELOW - Private Practitioner e-files Motion to Substitute Parties and Change Caption in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Motion to Substitute Parties and Change Caption
* View docket record 
Expected results 
- [ ] Docket entry for Motion to Substitute Parties and Change Caption displays filed by Test Practitioner 

#### 4) Private Practitioner e-files Notice of Election to Intervene in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Notice of Election to Intervene
* View docket record 
Expected results 
- [ ] Docket entry for Notice of Election to Intervene  displays filed by Test Practitioner 

#### 5) Private Practitioner e-files Notice of Election to Participate in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Notice of Election to Participate
* View docket record 
Expected results 
- [ ] Docket entry for Notice of Election to Participate  displays filed by Test Practitioner 

#### 6) Private Practitioner e-files Notice of Intervention in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Notice of Intervention
* View docket record 
Expected results 
- [ ] Docket entry for Notice of Intervention  displays filed by Test Practitioner 

#### 7) Private Practitioner e-files Substitution of Counsel in new case and is listed as Filed By in docket entry 
* Log in as private practitioner [Test Practitioner]
* Search for case (not associated with) 
* File Substitution of Counsel
* View docket record 
Expected results 
- [ ] Docket entry for Substitution of Counsel displays filed by Test Practitioner 

#### 8) IRS Practitioner e-files First IRS Document in new case and RESP is listed as Filed By in docket entry 
* Log in as IRS practitioner [Test irsPractitioner]
* Search for case (not associated with) 
* File First IRS Document 
* View docket record 
Expected results 
- [ ] Docket entry for document displays filed by RESP

#### 9) IRS Practitioner e-files Entry of Appearance in new case and RESP is listed as Filed By in docket entry 
* Log in as IRS practitioner [Test irsPractitioner]
* Search for case (not associated with) 
    * Case has at least 1 irs counsel associated already
* File Entry of Appearance
* View docket record 
Expected results 
- [ ] Docket entry for document displays filed by RESP

#### 10) Private Practitioner e-files a document in an existing case and Party name is listed as Filed By in docket entry
* Log in as Private Practitioner
* Click on one of your cases
* File a document 
* View Docket record
Expected Results
- [ ] Docket entry for document displays filed by party name (not the practitioner name)

**Comment by rachelschneiderman** [comment]
After talking with @cholly75, we determined DAWSON does not allow the following combinations to file a document:
1) a private practitioner and petitioner name
2) a private practitioner and irs respondent

**Comment by cholly75** [comment]
After conferring w/ Docket section, removed "Motion to Substitute Parties and Change Caption" as an affected document in this story.

**Comment by ttlenard** [comment]
All tests pass!  Thank you!
