### ISSUE TITLE
UI Updates to Printable Docket Record

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7882]
## Acceptance Criteria
* All parties (petitioners, intervenors, and participants) should display on the printable docket record
* When a new party is added to a case, they should display on the printable docket record
* When a party is removed from a case, they should no longer display on the printable docket record
* If a party is represented by counsel, the counsel's information should display on the printable docket record and it should be clear who the counsel is representing
* Respondent's counsel should display on the printable docket record
* ~~Issue from E2E UM testing: Confirm that parties are showing correct label (petitioner, intervenor, participant)~~ (Not applicable since we have removed the label per PO)
*  Before Petition is served, the Printable Docket Record link should be hidden 

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
- changes implemented [7470](https://github.com/flexion/ef-cms/issues/7470) should still apply 

## Tasks
- [x] Display all petitioners on printable docket record - completed as a part of previous story work ustaxcourt/ef-cms-flexion#8403
    - [x] Ensure the party is displayed when newly added to petrs array ustaxcourt/ef-cms-flexion#8403
    - [x] Ensure the party is no longer displayed when removed from petrs array ustaxcourt/ef-cms-flexion#8403
- [x] If a party is represented by counsel, the counsel's information should display on the printable docket record and it should be clear who the counsel is representing - ustaxcourt/ef-cms-flexion#8403
- [x] Respondent's counsel should display on the printable docket record ustaxcourt/ef-cms-flexion#8403

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by cnelsonflexion** [comment]
![Revised printable docket record - party table view.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/d688439e-c67e-4ed3-af20-29e025203afb)

Login as a docket clerk

Browse to open case -> Docket Record
- Click printable docket record

Login as a Petitioner/Practitioner

Open a case the user is associated with -> Docket Record
- Click printable docket record

PDF layout should match the above view


![Revised printable docket record - party table public view.png](https://images.zenhubusercontent.com/5db1fb429d25900001eabf17/a8a96c19-0a68-45d5-b78a-a66492226cbd)

As a public user
Browse to open case -> Docket Record
- Click printable docket record

PDF layout should match the above view

**Comment by mariahkannenberg** [comment]
Blocked - Don't pick up until Batch 1 is complete and in Court's staging.

**Comment by JessicaMarine** [comment]
@rosiehsmith 
6-9-2021 Design Decisions:
- Drop the `Role` column
- Combine `Counsel` and `Counsel contact` into one column w/3 lines:
    - Name (Bar No.)
    - Email
    - Phone
