### ISSUE TITLE
E2E Testing of UM Batch 1

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7890]
As a product team, so that we can ensure UM functionality works well once all pieces are completed, we need to test all functionality in batch 1. 

## Acceptance Criteria
* Document any bugs found
* Document any missing functionality in the comments of this story

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
### User Management - Batch 1 Stories + Tests 

Full tests - https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit#gid=1827916438

- 1) 8112) Docket/admission/petitions - updated Party Info views
    - Petitioner & Counsel tab views 
        - [x] Petitioner & Counsel tab is selected by default
        - UI displays updated design
            - [x] Pro se - Petitioner card displays “None” for counsel
            - [x] With Counsel - Petitioner card displays counsel
            - [x] With c/o - Petitioner card displays “c/o” above address
            - [x] With no email/ pending email / current email - Email displays correctly per design notes
        - [x] “Edit” links display for each petitioner (for Docket and Admissions only)
        - [x] Add Party link displays (for Docket only)
        - [x] Add Counsel search box displays
        - [x] Edit link displays for each counsel

    - Intervenor / Participant tab view 
    - Respondent Counsel view 

- 2) 8218) Non-docket - updated Party info views 
    - Petitioner & Counsel tab views 
    - Intervenor / Participant tab view 
    - Respondent Counsel view 

- 3) 8219) External users - updated Party info views 
    - Petitioner & Counsel tab views 
    - Intervenor / Participant tab view 
    - Respondent Counsel view 

- 4) 5386 + 8216 + 8133 + 8132)  Add a petitioner/intervenor/participant to an existing case /Add a party with any role type in new Add Party form 
    - Add a petitioner to a case 
    - Add intervenor to a case 
        - try to add a second intervenor 
    - Add multiple participants to case 
    - Serve court issues document for case with added petitioner/intervenor/participant
    - Serve paper-filed document for case with added petitioner/intervenor/participant
    - eFile a document for case with added petitioner/intervenor/participant
    - View Printable Docket Record with added petitioner/intervenor/participant - ustaxcourt/ef-cms#7835, 8141, 8142, 8280 


    5. Add counsel to any added petitioner - ustaxcourt/ef-cms#7835, 8141, 8142 
        - Request Access (as private Practitioner) representing added petitioner - -  - ustaxcourt/ef-cms#7835, 8141, 8142 


- 6) 5385, 8134, 8136, 8135) Remove a petitioner/intervenor/participant from a case 
    - Remove a petitioner from case
        - Try to remove single petitioner (button should be hidden) 
    - Remove intervenor from case 
    - Remove participant from case 
    - Serve court issues document for case with removed petitioner/intervenor/participant
    - Serve paper-filed document for case with removed petitioner/intervenor/participant
    - eFile a document for case with removed petitioner/intervenor/participant
    - View Printable Docket Record with removed petitioner/intervenor/participant- ustaxcourt/ef-cms#7835, 8141, 8142, 8280 

    7. Remove petitioner/intervenor/participant represented by counsel (counsel only represents this party) -  - ustaxcourt/ef-cms#7835, 8141, 8142 should address 
        - Remove petitioner/intervenor/participant represented by counsel (counsel represents another party still on case) - ustaxcourt/ef-cms#7835, 8141, 8142 should address



- 8) 7808 + previous stories) Any Petitioner gains e-access to a case (not applicable to intervenor or participants) 
    - Existing email is added to petitioner added to case after Petition 
    - New email is added to petitioner added to case after Petition 
    - Serve court issues document for case with petitioner with eAccess
    - Serve paper-filed document for case with petitioner with eAccess
    - eFile a document for case with petitioner with eAccess
    - Email is added to intervenor/participant added to case after Petition -  - 8138, 8139 

- 9) 7839 + 8215) Any party contact info can be edited individually / Any party can be edited in updated Edit Party form 
    - Edit any petitioner/intervenor/participant contact info (docket) -  7458, 8151, 8152 
    - Petitioner/intervenor/participant edits their own info - 7458, 8151, 8152 should address 
    - Practitioner edits info for petitioner they represent -  ustaxcourt/ef-cms#7835, 8141, 8142 should address 

- 10) 8214) Edit and delete counsel from a case (for petitioner only, not intervenor or participant) 
    - Edit counsel (change who they represent) for any petitioner - ustaxcourt/ef-cms#7835 to address other petitioners
    - Remove counsel for any petitioner - ustaxcourt/ef-cms#7835 to address other petitioners

- 11) 8217) Indicator displays when petitioner is represented by counsel 
    - Any petitioner, intervenor, participant is represented by counsel and indicator displays 
    - Only respondent has counsel and no indicator displays 

12. ) As petitioner/intervenor/participant w/ eAccess, update email

**Comment by JessicaMarine** [comment]
PO Comments:
- If case already has an intervenor, we should hide that option in the dropdown or provide immediate validation if that option is selected
- Consider if intervenors and participants should be identified as such in the filedBy column
- Need to extend "has ~~Petition~~ anything been served" logic change to other places in the app

**Comment by klohman** [comment]
## E2E Testing 
@TomElliottFlexion @rosiehsmith  @JessicaMarine 


I**Internal + External views** 
 * pending email not displaying on petitioner card despite showing correctly in the edit petitioner form
 * counsel with pending email - email displays but does not include "(pending)" 
* Intervenor with no email does not show "No email provided" at all
* intervenor with pending email is not displaying the email on card at all 
* participant with no email does not show "No email provided" at all
* participant with pending email is not displaying the email on card at all 
* counsel for intervenor with no email is not displaying "No email provided" (displays as expected for counsel on petitioner card)
* counsel with pending email - email displays but does not include "(pending)" 

* respondent counsel with pending email - email displays but does not include "(pending)" and cases are being updated with new counsel email before it is verified 
* consider updating design for respondent counsel to match petitioner cards (with edit link in blue bar); the edit link gets pushed with a longer respondent counsel name 


**View Counsel**
* view link for counsel for intervenor Hu Lowery on 5911-19- View link for counsel goes to internal Edit Petitioner Counsel screen 

**Edit Party Contact Info - External parties**
* when logged in as intervenor / participant, Edit link routes to internal Edit Party form - it should route to Edit Contact Info form for external users 
* No pending email is shown on Petitioner Card (expected functionality). Pending email IS shown on edit form.


**Counsel**
* counsel with paper service displays as undefined in paper service modal

**File a Document**
* On Review your filing screen, consider increasing space before party names wrap 

**Printable Docket Record**
* all parties are displaying as Petitioners (should be addressed in 8280)
* logged in as unassociated private Practitioner- Printable Docket is displaying all petitioner contact information 


**Verify Updated email**
* when updating email as external user, cannot verify new email- redirects to `http://localhost:5678/email-verification-instructions`

**Granting eAccess**
* granting eAccess to petitioner on closed case, user can log in but service indicator is not updated to electronic (this may be expected behavior) 


**Editing Counsel representation**
* when counsel is edited (change who the counsel represents), Unrepresented petitioner service preference remains as `none` and does not revert back to original

**Comment by JessicaMarine** [comment]
**Internal + External views** 
 ~~Pending email not displaying on petitioner card despite showing correctly in the edit petitioner form~~ -- Add to ustaxcourt/ef-cms#7832
- [ ] Counsel with pending email - email displays but does not include "(pending)" 
~~Intervenor with no email does not show "No email provided" at all~~ -- Add to ustaxcourt/ef-cms#7833
~~Intervenor with pending email is not displaying the email on card at all~~ -- Add to ustaxcourt/ef-cms#7833
~~Participant with no email does not show "No email provided" at all~~ -- Add to ustaxcourt/ef-cms#7834
~~Participant with pending email is not displaying the email on card at all~~ -- Add to ustaxcourt/ef-cms#7834 
~~Counsel for intervenor with no email is not displaying "No email provided" (displays as expected for counsel on petitioner card)~~ -- Add to ustaxcourt/ef-cms#7836
~~Counsel with pending email - email displays but does not include "(pending)"~~ DUPLICATE
- [ ] Respondent counsel with pending email - email displays but does not include "(pending)" and cases are being updated with new counsel email before it is verified 
~~Consider updating design for respondent counsel to match petitioner cards (with edit link in blue bar); the edit link gets pushed with a longer respondent counsel name~~ BACKLOG as new story 


**View Counsel**
- [ ] View link for counsel for intervenor Hu Lowery on 5911-19- View link for counsel goes to internal Edit Petitioner Counsel screen 


**Edit Party Contact Info - External parties**
~~When logged in as intervenor / participant, Edit link routes to internal Edit Party form - it should route to Edit Contact Info form for external users~~ -- Add to ustaxcourt/ef-cms#7833 or ustaxcourt/ef-cms#7834 
~~No pending email is shown on Petitioner Card (expected functionality). Pending email IS shown on edit form.~~ DUPLICATE


**Counsel**
- [ ] Counsel with paper service displays as undefined in paper service modal

**File a Document**
- [ ] On Review your filing screen, consider increasing space before party names wrap 

**Printable Docket Record**
~~All parties are displaying as Petitioners~~ --Confirm in ustaxcourt/ef-cms#7882
- [ ] Logged in as unassociated private Practitioner- Printable Docket is displaying all petitioner contact information 

**Verify Updated email**
- [ ] When updating email as external user, cannot verify new email- redirects to `http://localhost:5678/email-verification-instructions`

**Granting eAccess**
~~Granting eAccess to petitioner on closed case, user can log in but service indicator is not updated to electronic~~ -- Add to ustaxcourt/ef-cms#7832


**Editing Counsel representation**
- [ ] When counsel is edited (change who the counsel represents), Unrepresented petitioner service preference remains as `none` and does not revert back to original 

**PO Feedback**
- [ ] If case already has an intervenor, we should hide that option in the dropdown or provide immediate validation if that option is selected
~~Consider if intervenors and participants should be identified as such in the filedBy column~~ BACKLOG as new story
~~Need to extend "has Petition been served" logic change to other places in the app~~ BACKLOG as new story

**Comment by JessicaMarine** [comment]
@klohman @rosiehsmith @TomElliottFlexion 

Things to fix now:

**Internal + External views** 
- [x] Counsel with pending email - email displays but does not include "(pending)"  ustaxcourt/ef-cms-flexion#8395
- [x] Respondent counsel with pending email - email displays but does not include "(pending)" and cases are being updated with new counsel email before it is verified ustaxcourt/ef-cms-flexion#8395

**View Counsel**
- [x] View link for counsel for intervenor Hu Lowery on 5911-19- View link for counsel goes to internal Edit Petitioner Counsel screen 

**Counsel**
- [x] Counsel with paper service displays as undefined in paper service modal

**File a Document**
- [x] On Review your filing screen, consider increasing space before party names wrap ustaxcourt/ef-cms-flexion#8395

**Printable Docket Record**
- [x] Logged in as unassociated private Practitioner- Printable Docket is displaying all petitioner contact information 

**Verify Updated email**
- [x] When updating email as external user, cannot verify new email- redirects to `http://localhost:5678/email-verification-instructions`

**Editing Counsel representation**
- [x] When counsel is edited (change who the counsel represents), Unrepresented petitioner service preference remains as `none` and does not revert back to original 

**PO Feedback**
- [x] If case already has an intervenor, we should hide that option in the dropdown or provide immediate validation if that option is selected

**Comment by klohman** [comment]
@JessicaMarine @rosiehsmith @mrinsin 

- When adding and verifying an email for a petitioner, intervenor, or participant, I'm able to log in as petitioner but the service indicator isn't changing and the email is not displaying. This seems to be inconsistent because yesterday in testing I did see the current email displaying for petitioners. 

Update- I think this is happening with only legacy cases. I created a new case and added emails to both original petitioners and an added petitioner and this worked as expected.

**Comment by rosiehsmith** [comment]
@klohman We were unable to recreate this on a legacy case with 2 flows: editing your own email as a petitioner & adding an email to a petitioner as admissionsClerk on docketNumber 10105-13S.

Is there a case you could send us where we could recreate it? Thanks!

**Comment by klohman** [comment]
UX Re-review: 

**Internal + External views**
*  Counsel with pending email - email displays but does not include "(pending)" #8395 - now displaying duplicate emails now - one without pending, one with (pending)
![Screen Shot 2021-06-09 at 11.35.08 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/082ca6af-ef29-4423-9de2-16e666feb5d2)


**Verify Updated email**
*  When updating email as external user, cannot verify new email- redirects to http://localhost:5678/email-verification-instructions - Still happening on dev

**Comment by mrinsin** [comment]
@JessicaMarine after @klohman reviewed the feedback on dev, she found that 2 of the items still did not seem to work as expected. We are also still trying to figure out what is up with the petitioner email not being updated on legacy cases (last feedback item). Would you like us to address these three things as a part of batch 2 in order to still get batch 1 to the court today?

**Comment by JessicaMarine** [comment]
@mrinsin No, let's get them fixed.

**Comment by mrinsin** [comment]
@JessicaMarine Sounds good, thank you! @klohman (just letting you know!)

**Comment by ericsorenson** [comment]
2 remaining issues for 6/11/21:
- Properly display the email (pending) when a practitioner had no email address defined previously
- Per Kristen: when adding and verifying an email for a petitioner, intervenor, or participant on a legacy case (6712-10), I'm able to log in as petitioner but the service indicator isn't changing and the email is not displaying. This seems to be inconsistent because yesterday in testing I did see the current email displaying for petitioners.

**Comment by mmarcotte** [comment]
After the deploy over the weekend, that second bullet point appears to be working for me. Just performed the operation on **500-18**. I have not attempted for an intervenor or participant.
