### ISSUE TITLE
filedBy -- Removed Parties

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7894]
As the Court, we need to preserve the filedBy when we remove parties from a case and have the ability to edit that field after a party has been removed.

## Acceptance Criteria
* filedBy listed on an entry does not change if a party contained in the field is removed from the case
* Docket Clerk and Clerk of Court can edit the filedBy of an entry that has a removed party

Possible Solution:  When a document is served (and the filedBy) determined, convert the filedBy field to a string that can be edited as a string moving forward.

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Update FilingPartiesForm to display textbox when docketEntry isServed, otherwise show checkboxes.
- [x] Validation on FilingPartiesForm
- [x] Don't call generateFiledBy() after docketEntry has been served
- [x] Update editDocketEntry endpoint to allow update of filedBy

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
### Externally/Paper Filed Documents 

**After document is filed & served**

* Filed by field is concatenated and becomes a string 

#### Document QC form 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/95ae1118-de8f-4ed4-a673-15551fe8903c)

**Filed by**
* Use text area component 
* Field is populated with current filed by concatenation and can be edited 

**On Complete**
* If Filed by field is updated, a Notice of Docket Change is generated (current functionality) 
* Updated Filed by displays in Docket Record and in all lists where filed by appears (document QC queues, pending report, etc.) 

#### Edit Docket Entry form 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/616c3579-3346-4b5b-a903-443785e724ca)

**Filed by**
* Use text area component 
* Field is populated with current filed by concatenation and can be edited

**Comment by klohman** [comment]
#### 1) Docket clerk sees updated filing parties field on QC screen 
* Login as docket clerk 
* Go to Document QC Inbox & select a document 
Expected results 
- [x] Filed by field is text area box populated with filing parties selected when document was submitted 
- [x] Filed by field is editable  

#### 2) Docket clerk updates filing parties during QC 
* Login as docket clerk 
* Go to Document QC Inbox & select a document 
* Update filing parties 
* Complete QC 
- [x] Notice of Docket Change is added to docket record and served
- [x] Updated Filed by displays in docket entry 
- [x] Updated Filed by displays in all queues 

#### 3) Docket clerk sees updated filing parties field on Edit Docket entry screen 
* Login as docket clerk
* Go to Case 
* Click “Edit” link for externally or paper filed docket entry 
Expected results 
- [x] Filed by field is text area box populated with filing parties selected when document was submitted 
- [x] Filed by field is editable  

#### 3) Docket clerk updates filing parties when editing a docket entry 
* Login as docket clerk
* Go to Case 
* Click “Edit” link for externally or paper filed docket entry 
* Update filing parties 
* Save 
- [x] Updated Filed by displays in docket entry 
- [x] Notice of Docket Change is not added to docket record
