### ISSUE TITLE
Petitions Clerks/Docket Clerks: IRS Notice (Yes/No) question updates

### ISSUE THREAD

**Issue by JessicaMarine** [ustaxcourt/ef-cms#7902]
As a Docket Clerk, I find the question about "Is the notice attached to the petition?" to be too narrow.  Also, this question should be required throughout the application.

![image.png](https://images.zenhubusercontent.com/5bbfb4d092b88e6ddb8b0e3d/ebac4d40-f94b-4f84-94d4-75753819155e)

## Acceptance Criteria
* Question about notice being attached to petition needs to be more generic once case is created
* During the Create Case flow for paper petitions, the IRS Notice (Yes/No) question should be a required field
* During the Petition QC flow for eFiled petitions, the IRS Notice (Yes/No) question should be a required field
* IRS Notice (Yes/No) question when editing case metadata should be a required field

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] 1 Update field label from “Notice attached to petition?” to “IRS Notice provided?” throughout the app (Rachael ustaxcourt/ef-cms-flexion#8464)
- [x] 2 Make hasVerifiedIrsNotice required when QCing a petition (Rachael ustaxcourt/ef-cms-flexion#8467)
- [x] 3 Case Information > Overview tab - Update card title from “Petition Details” to “Case Details” (Rachael ustaxcourt/ef-cms-flexion#8469)
- [x] 4 Case Information > Edit Case Details (Rachael ustaxcourt/ef-cms-flexion#8469)
  - [x] 4a update page title to "Edit Case Details" (Rachael ustaxcourt/ef-cms-flexion#8469)
  - [x] 4b Make hasVerifiedIrsNotice required (Rachael ustaxcourt/ef-cms-flexion#8467)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Petition QC - IRS Notice Tab 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b31c4e58-7320-41d7-b11f-0a4dff871d36)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/91d9a577-8b3e-4e28-a6c5-ed9e35a15a1f)

**IRS Notice provided?** 
* Update field label from “Notice attached to petition?” to “IRS Notice provided?”
* Field is required 
* If field is empty, display error message on click of Review Petition - “Select an option”

**If Yes**
* display IRS Notice date field (no changes to current functionality)
* if Yes and Deficiency case, statistics are displayed and required  (no changes to current functionality)

**If No**
* no changes to current functionality

## Review and Serve Petition screen 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0a2eaff7-0730-49e3-9241-2256649a1d24)

* Update field label from “Notice attached to petition?” to “IRS Notice provided?”


## Case Information > Overview tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5a23fa7f-5de7-48ce-a6ec-8a7fa5aea12d)

* Update card title from “Petition Details” to “Case Details” 

## Case Information > Edit Case Details 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/42403322-bd36-43ce-a961-dc1a384b3e8c)

* update page title to "Edit Case Details"

**IRS Notice provided?** 
* Update field label from “Notice attached to petition?” to “IRS Notice provided?”
* Field is required 
* If field is empty, display error message on click of Review Petition - “Select an option”

**If Yes**
* display IRS Notice date field (no changes to current functionality)
* if Yes and Deficiency case, statistics are displayed and required  (no changes to current functionality)

**If No**
* no changes to current functionality

**Comment by klohman** [comment]
## test cases 

#### 1) Petitions clerk sees updated field label on Petition QC screen 
Login as petitions clerk 
Go to Petition QC screen > IRS Notice tab 
Expected results 
- [x] Update field label “IRS Notice provided?” displays 
- [x] IRS Notice provided field is blank by default 

#### 2) Petitions clerk sees error if IRS Notice provided field is blank 
Login as petitions clerk 
Go to Petition QC screen - do not select option for IRS Notice provided
Click Review Petition  
Expected results 
- [x]  error displays on IRS Notice provided = “Select an option” 

#### 3) Petitions clerk selects Yes/No for IRS Notice field 
Scenario 1 
Select Yes 
Select Deficiency case
Select No 
Expected results 
On select of “Yes” 
- [x] IRS Notice date displays and is optional 
On select of Yes and Deficiency case 
- [x] IRS Notice date displays and is optional 
- [x] Statistics fields display and are required 
On select of “No” 
- [x] IRS Notice date is hidden

#### 4) Petitions clerk sees updated field label on Review and Serve Petition screen 
Go to Petition Details 
Complete form
Click Review Petition 
Expected results 
- [x] Updated field label displays for IRS Notice provided 


#### 5) Docket clerk sees updated field label on Case Information > Overview 
Login as docket clerk 
Go to Case Information > Overview 
Expected results 
- [x] Update card label displays “Case Details” 

#### 6) Docket clerk sees updated field label on Edit Case Details screen 
Login as docket clerk 
Go to Case Information > Overview 
Click Edit link on Case Details card
Expected results 
- [x] Form title displays as Edit Case Details 
- [x] Update field label “IRS Notice provided?” displays 
- [x] IRS Notice provided field is populated

#### 7) Docket clerk selects Yes/No for IRS Notice field 
Login as docket clerk 
Go to Case Information > Overview 
Click Edit link on Case Details card
Select Yes 
Select Deficiency case
Select No 
Expected results 
On select of “Yes” 
- [x] IRS Notice date displays and is optional 
On select of Yes and Deficiency case 
- [x] IRS Notice date displays and is optional 
- [x] Statistics fields display and are required 
On select of “No” 
- [x] IRS Notice date is hidden
