### ISSUE TITLE
After a B/G Deployment is considered healthy, delete the old DDB and ES Cluster after a successful deploy

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7929]
As a tech lead, so that I can reduce costs and avoid human error after accepting a deployment, I want to automate the process of deleting the old DDB and ES Cluster after a successful deployment.

Why: Save costs. There's an ES cluster sitting w/data on it and doing nothing. This costs a lot. 

## Pre-Conditions

* Review spike: https://github.com/flexion/ef-cms/issues/8073
* ustaxcourt/ef-cms#7930, ustaxcourt/ef-cms#7931, ustaxcourt/ef-cms#7932

## Acceptance Criteria

(Note: AC should include non-standard testing, deployment, documentation or security requirements)

- Process of deleting (and backing up if Prod) the DDB table that had been the source table has been automated.
- The process of destroying the ES Cluster connected that had been the source table has been automated
- Developers can reference `blue-green-migration.md` to see up-to-date changes made by this new automation process
- The automation for this is initiated when the read-only smoketests have been completed successfully and the switch color step has been completed
- Give a demo of this running in Flexion prod
- Destroy the Migration infrastructure
- After the color switch, delete the API Gateway mappings (`api-[color]` and `public-api-[color]`) to ensure no data is collected from users that were authenticated in the old color.

## Notes
- Backing up of prod has not been completed in another story
- This readies the system for the next deployment requiring a blue/green migration.

## Tasks
- [ ] upon successful deploy, after switch colors, destroy migration infrastructure - Rachel, Rosie (https://github.com/ustaxcourt/ef-cms/pull/19466)
- [ ] upon successful deploy, after switch colors, destroy migration-cron infrastructure - Rosie (https://github.com/ustaxcourt/ef-cms/pull/1946)
- [ ] upon successful deploy, after switch colors, delete source ES cluster - Rosie, Rachel (https://github.com/ustaxcourt/ef-cms/pull/1946)
- [ ] upon successful deploy, after switch colors, delete source db - Rosie, Rachel (https://github.com/ustaxcourt/ef-cms/pull/1946)
- [ ] upon successful deploy, after switch colors, IF env = prod, backup source DB - Rosie, Rachel (https://github.com/ustaxcourt/ef-cms/pull/1946)
- [ ] upon successful deploy, after switch colors, delete API gateway mappings - Rosie (https://github.com/ustaxcourt/ef-cms/pull/1946)
- [ ] update blue-green-migration doc - Rosie (https://github.com/ustaxcourt/ef-cms/pull/1946)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by jimlerza** [comment]
### Test case

After a deployment is complete, check the active table like so:
```
aws dynamodb get-item --table-name "efcms-deploy-$ENV" --key '{"pk": {"S": "destination-table-version"}, "sk": {"S": "destination-table-version"}}' | awk 'f{print;f=0} /current/{f=1}' | awk -F'"' '$0=$4'
```

Then check the list of dynamodb tables and ensure the old table isn't listed:
```
aws dynamodb list-tables | grep $ENV
```

Also check the list of Elasticsearch domains and ensure the old domain isn't listed:
```
aws es list-domain-names | grep $ENV
```

**Outcome:**

- [ ] New active table/cluster determined
- [ ] Old DynamoDB table deleted as expected
- [ ] Old ElasticSearch cluster deleted as expected
