### ISSUE TITLE
Seamless public user experience during a deployment

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#7936]
As a DAWSON public (non-logged in) user, so that I can use the application any time that I require, I need to be able to continue to use the application during deployment activities.

DAWSON deployments currently interrupt user activity at the end of deployment activities. By implementing a process that allows users to receive the latest code deployments seamlessly, we can provide both a better user experience and more frequent deployment opportunities.

This initial story should provide continuous service to a public-facing non-logged in user during and post-deployment activities.

## Pre-Conditions

- Review spike: https://github.com/flexion/ef-cms/issues/8073

## Acceptance Criteria
* User is transitioned to the new application code after deployment without action required on the part of the user
* User can continue to work in DAWSON performing searches, viewing dockets/documents without interruption
* Kibana logs or on-screen information displayed (deployment date?) confirm user is transitioned to new application code

## Test Cases
* Public user executes case search/document viewing during deployment activities; user is able to continue doing so without interruption; post-deployment activities complete; user is transitioned to new code

None

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Will require deployments to test adequately
* How do we ensure the user client knows what version to be using?
* Need to consider cases where blue/green migration is required
* Possible approach: include versions in API requests?
* Original story w/ notes + details on possible approach: [https://app.zenhub.com/files/152320868/c149b4cf-120e-4915-9099-bc12f1a37c4d/download](https://app.zenhub.com/files/152320868/c149b4cf-120e-4915-9099-bc12f1a37c4d/download)

## Tasks
- [x] Store state in local storage
- [x] Retrieve checksum.txt from CDN to determine whether to refresh or not
- [x] On refresh use state from local storage to route and populate form

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment
