### ISSUE TITLE
Order Search: Turn on Order Search internally in the production environment

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7948]
As a Tech Lead for the Court, in order to have control over order search availability for internal users, I need the ability  to turn it on and off in the production environment without doing a deploy. 

## Pre-Conditions
* ustaxcourt/ef-cms-flexion#8543, ustaxcourt/ef-cms#7579, ustaxcourt/ef-cms#7700, ustaxcourt/ef-cms#7911, ustaxcourt/ef-cms#7949, ustaxcourt/ef-cms#7953, ustaxcourt/ef-cms#7952, ustaxcourt/ef-cms#7951, ustaxcourt/ef-cms#7950, ustaxcourt/ef-cms-flexion#8550, ustaxcourt/ef-cms#7955, ustaxcourt/ef-cms#7956 

## Acceptance Criteria
* Tech lead can turn order search on or off in the production environment for internal users only without a deployment and within 30-60 min
* All users shouldn't be able to access search endpoints after it's turned off in production
* Users who try to access search after the search page has loaded AND the search feature has been turned off, are notified in a way that doesn't disrupt their work or log them out

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Should we turn it on for all users, a subset, etc? Can use toggles to do this
* Do we have a way to turn it off if searches overload the system?

## Tasks
- [x] 1 Create toggle flag for order search - store in dynamo (deploy table?) - mob - ustaxcourt/ef-cms-flexion#8796 
- [x] 2 Endpoint to check the toggle in the deploy table (might need new permissions, db setup in app context?) - mob - ustaxcourt/ef-cms-flexion#8798
- [x] 3 Create an action, proxy, and lambda to call the interactor to check the toggle - mob - ustaxcourt/ef-cms-flexion#8799
- [x] 4 Figure out how to do this locally - mob - ustaxcourt/ef-cms-flexion#8798
- [x] 5 When user navigates to advanced search, call endpoint to check if order search is enabled and use result to determine whether warning is displayed - ustaxcourt/ef-cms-flexion#8801
- [x] 6 When user submits an order search, call endpoint to check if order search is enabled and use result to either call search endpoint or navigate back to case search tab - mob

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
@cholly75 

### Proposed flow


#### When Search Feature is turned off
**User is currently on Order search tab** 
on next action: 
* user is navigated to Case tab 
* warning message displays 
* Order tab is disabled 

**User is not on Order search tab** 
if user navigates to Advanced Search 
* user is navigated to Case tab 
* warning message displays 
* Order tab is disabled 


![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/d75aff28-a926-4035-bbc2-c5ea1ac6c600)

**Comment by cholly75** [comment]
@klohman looks good!

**Comment by ttlenard** [comment]
Got a demo of this today. All looked good to me!

**Comment by codyseibert** [comment]
leaving here to document a small bug fix related to the spinner fixed on batch8: https://github.com/flexion/ef-cms/pull/8847
