### ISSUE TITLE
Order Search: Locate document by exact keyword/phrase

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7950]
As a court employee, in order to locate documents with specific keywords or phrases, I need to be able to retrieve documents with only those exact keyword/phrases

## Acceptance Criteria
* User is aware that they can search for exact matches
* User is able to indicate if they want an exact match
* User is able to search for an exact match on a single keyword
* User is able to search for an exact match on a phrase
* When exact match is indicated by user, the result set includes only matches that include the exact keyword/phrase
* User (internal or external) should see an indication that my search request is “processing” after starting a search 
* We define exact matches as exact words in the exact order
  * For example, if innocent spouse is entered --First priority - matches innocent spouse
* Ensure that search is not case sensitive
* If there are no matches, inform the user
* Review test cases as a team and ensure our test scenarios are good and finalize

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* For example: If I search for an exact match for "motion for summary judgment", I expect the results only to return documents with that exact phrase in that exact order.
How does ES handle fuzzy searches?
  * For example: if "Rob Jones" is entered
   "Robert Jones" does not match
* Search doesn't need to be case senstive
* Testing this is going to be complex. We need to have explicit data for our scenarios and test it with the full data set on mig. 

## Tasks
- [x] 1 Rearrange Order search box UI - mob (#8622)
- [x] 2 Mobile order search UI - Rachael (#8633)
- [x] 3 Add test orders to local seed data from test scenarios - mob (#8623)
- [x] 4 Create tests for each test scenario against seed data - mob (#8624)
- [x] 5 Create seed data in integration tests instead of efcms-local -mob (#8631)
- [x] 6 Make changes to make the integration tests pass (#8631)
- [x] 7 Pad document contents in integration tests with additional lipsum / text (Matt ustaxcourt/ef-cms-flexion#8635))

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by kkoskelin** [comment]
For discussion between engineers & design: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by kkoskelin** [comment]
I don't know if it's captured in any search-related stories, but we have heard users ask whether or not their existing search results were getting further narrowed, e.g. applying more filters to a special set of search results already produced for them.  

This is most definitely not the case, and I think we should do what we can to *not* give this impression.  In a few places the words "Narrow your search" is used.  Perhaps what we should do is replace them with suggestions to search again with additional criteria.

**Comment by kkoskelin** [comment]
Preliminary work to support searching for exact phrases can be found in the branch `8546-exact-phrase-search`.  Searching for exact phrases can be accomplished simply by enclosing them in double-quotes within the search field.

**Comment by klohman** [comment]
## Order search tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1ffdc936-e6ad-46ec-8cdc-50100a2b68c8)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fe936b52-f76b-48ac-8476-09c2dfed1214)

keywords contained in quotes “[keyword keyword]” indicates exact match search

Considerations:
Stopwords 
how do we handle stopwords? Is it possible to keep them when part of a phrase? 
https://www.elastic.co/guide/en/elasticsearch/guide/master/stopwords-phrases.html#_stopwords
Special characters  - results 
Case sensitive - matches should not be case sensitive 


## Mobile 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3b2ca08c-038b-42b6-b4ad-87d1c47d33e7)

**Comment by klohman** [comment]
## Test cases 

expected results 
results include all keywords in exact order 
results do not include documents with keywords not in exact order 
exact match found in document title and contents
exact match found in document title but not document contents 
exact match found in document contents but not document title 
exact matches with stopwords 
exact matches with special characters * moving this to a separate story
exact matches with lowercase/uppercase characters (should not be case sensitive) 


Data 
Order 1 
“welcome to flavortown” in document contents + title 

Order 2
“welcome to flavortown” in document contents 

Order 3 
“welcome to flavortown” in document title  

Order 4 
“welcome to something” and “flavortown” in document title  

Order 5 
“welcome from flavortown” in document contents + title 

Order 6 
“welcome to flavor-town” in document contents + title

Order 7
“welcome to flavortown.” in document contents 

1. Search for “welcome to flavortown” 
expected results 
- [x]  Order 1 returns in results 
- [x]  Order 2 returns in results 
- [x]  Order 3 returns in results 
- [x]  Order 7 returns in results 
- [x]  Order 4, 5, 6 do not return in results

2. Search for “welcome from flavortown” 
expected results 
- [x]  Order 5 returns in results 
- [x] Order 1, 2, 3, 4, 6 do not return in results 

3. Search for “welcome to flavor-town” 
expected results
- [x]  Order 6 returns in results 
- [x] Order 1, 2, 3, 4, 5 do not return in results 

4. Search for “Welcome to Flavortown” 
expected results
- [x]  Order 1 returns in results 
- [x]  Order 2 returns in results 
- [x]  Order 3 returns in results 
- [x]  Order 7 returns in results 
- [x]  Order 4, 5, 6 do not return in results

5. Search for “welcomes to flavortown”
No orders return in results 


**Realistic data examples for larger testing** 
- some of these may end up moving to the special characters story
* confidential informant
* TC memo 2020-1
* t.c. memo. 2020-1
* 156 T.C. No. 11
* 156 TC No. 11.
* innocent spouse 
* innocent spouses
* estate of jackson
* Estate of Michael Jackson 
* motion to dismiss 
* parties’ joint motion for continuance
* parties’ joint motion for

**Comment by klohman** [comment]
UX review: 
Searches with special characters are not working 100%

example: 
- I created two orders, one with TC Memo 2020-1 in title, the other with T.C. Memo. 2020-1 in the title.
- When i search "TC Memo 2020-1", I get the correct order back. When i search "T.C. Memo 2020-1" i get no results. I believe this is due to the way the period is being handled. 

This should be addressed in the story handling special characters.

**Comment by cholly75** [comment]
Search checkout returned good results when checking exact match vs. non-exact, including filters!

Two things:

1) UI for the search fields display incorrectly on my browser UI:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/cecc58f6-d3a5-4d8b-a0c0-9e0414ec1af0)

2) It appears that the Caption+Docket# on the order is indexed as content when the document is a legacy PDF or has been scanned/uploaded to DAWSON, but it is not indexed if the document is DAWSON-generated content? Ex. docket ustaxcourt/ef-cms#8149-17; search term 'consolidated'. Is this expected behavior, and is there a way to make this consistent across all orders in either direction?

**Comment by matthopson** [comment]
This is on mig, but is awaiting a re-index to test.
