### ISSUE TITLE
Order Search: Display total results count

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#7955]
As a Court user, so that I may understand the breadth of my search results, I need the total results count to display.

## Acceptance Criteria
* User can see total results count

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Consider how to handle over 100 results
* Question from Chris: Does the system retrieve all results and then filter down to present top 100 in UI or does it return the first 100?
* Do we need the number column in the results? 

## Tasks
 - [ ] Add the total results display tag
 - [ ] Display a yellow warning

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Less than max results

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f9541722-ed86-4067-bcb5-7695eba895e4)


## Max results 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/fe0102a2-c4df-4585-8e77-ff759ca40602)

* update max results warning language (for order search and case search)

**Comment by klohman** [comment]
## Test cases 

#### 1) User sees total results count for result set fewer than 100
* Enter search term 
    * Search term should trigger fewer than 100 results 
* Click search 
Expected results 
- [ ] UI displays total result as “[xx] match(es) shown”

#### 2) User sees total result count for result set larger than 100
* Enter search term 
    * Search term should trigger more than 100 results 
* Click search 
Expected results 
- [ ] UI displays total result as “100 match(es) shown”
- [ ] UI displays max results warning message
