### ISSUE TITLE
Case Deadlines not working

### ISSUE THREAD

**Issue by adunkman** [ustaxcourt/ef-cms#796]
Unexpectedly Case Deadlines stopped working (again). It appears ONE of the cases getting returned from `getCasesByDocketNumbers(...)` fails validation, and so the whole request fails. The error message is not helpful. 

It appears that the information stored on the case is not valid, and it should not be used. However, the case passes if pulled individually by `getCaseByDocketNumber(...)` because this aggregates the related records.

**Tasks**

- [x] adjust `getCasesByDocketNumbers(...)` to make use of `getCaseByDocketNumber(...)` for consistency
- [x] try to improve validation error to be more helpful
- [x] handle the validation better (report the error, but let the cases that pass validation succeed).
- [x] Share info about the issue
- [x] Make sure everyone understands what happened
- [x] Figure out how to not do it again the same way
