### ISSUE TITLE
Order Search: Case Caption and Docket# section of DAWSON-generated/created content should be searchable content

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7986]
As a user, in order to get consistent expected search results I would like the content in the Case Caption and Docket # portion of the Order document to be factored in when determining search results.

## Acceptance Criteria

- Text in the Case Caption portion of the Order document is searchable content
- Text in the Docket # portion of the Order document is searchable content
- Search remains performant
- Searching against this content does not require special operators or UI outside of standard Order search

Additional AC (per meeting with Chris 7/29/21)
* Locate an Order by an old case caption 
* Locate an Order by an old docket number 

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
When testing exact match search in the MIG environment, we noticed that legacy PDFs and uploaded/scanned Orders had their Caption and Docket # section indexed, and that content returned matches on keyword/phrase search. However, this is not the case for DAWSON-native or generated content. The Court would like Caption and Docket # content searchable as to make this uniform across all documentation.

Example: Docket 9261-17, search for the word "consolidated"; despite being in the Caption of all Orders on the docket, a search for that word only returns the documents NOT generated via DAWSON.

## Tasks
- [x] 1 Parse document contents from older system-generated orders - mob ustaxcourt/ef-cms-flexion#8719
- [x] 2 Write test scenario setup - mob ustaxcourt/ef-cms-flexion#8719

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Do users expect to search for newest caption or old captions?
Do users care about caption or are they wanting to search by party?

As a user, so that I can search for and find documents with old case captions, I need the ability to search by old case captions. 

old  = not current case title

**Comment by mariahkannenberg** [comment]
Blocked - need to create test cases

**Comment by klohman** [comment]
## Draft Test Scenarios 

**test data**
Order 1
- Welcome to flavortown - old case caption 
- Guy Fieri - new case caption 
- Order content does not contain Welcome to flavortown 
- Order title does not contain Welcome to flavortown 
- Order contents contains word - “magic”


Order 2
- Guy Fieri - old case caption 
- Welcome to flavortown - new case caption 
- Order content does not contain Welcome to flavortown 
- Order title does not contain Welcome to flavortown 
- Order contents contains word - “magic”


Order 3
- Guy Fieri - old case caption 
- Johnny Boy  - new case caption 
- Order content contains Welcome to flavortown
- Order contents contains word - “magic” 


Order 4
- flavortown - old case caption 
- Guy Fieri - new case caption 
- Order content does not contain Welcome to flavortown 
- Order title does not contain Welcome to flavortown 
- Order contents contains word - “magic”
- Docket number on order - 123-20W
- Docket number on case - 123-20

Order 5
- flavortown - old case caption 
- Sam Fieri - new case caption 
- Order content does not contain Welcome to flavortown 
- Order title does not contain Welcome to flavortown 
- Order contents contains word - “magic”


Order 6 
- Old docket number on order - 106-21
- New docket number on case - 106-21W

Order 7 
- Old docket number on order - 106-21W
- New docket number on case - 106-21

Order 8 
- Order contents contains word - “magic”
- Docket number on order - 107-21W
- Docket number on case - 107-21


**test cases**

1)  User searches for Order using exact match old case caption - “welcome to flavortown” - as keyword 
Results 
- [x] Orders 1, 3 return 
- [x] Order 2 does not return 

2) User searches for Order using exact match current case caption - “Guy Fieri” -  as keyword
Results 
- [ ] Order 2, 3 return
- [x] Order 1 does not return 

3) User searches for Order using a keyword - “magic” and using exact match old case caption - “Welcome to flavortown” in Case title/Petitioner name field 
Results 
- [x] Order 1, 3 do not return
- [x] Order 2 returns


~~4) User searches for Order using a keyword and using exact match new case caption in “Welcome to flavortown”Case title/Petitioner name field~~(Duplicate results from test 3 - removed)

~~Results~~
- [ ] ~~Order 2 returns~~
- [ ] ~~Order 1, 3 do not return~~

5) User searches for Order using non-exact match - welcome to flavortown -  old case caption as keyword
Results 
- [x] Order 1, 3 return 
- [x] Order 2, 4 does not return

6) User searches for Order using non-exact match - Guy Fieri - current case caption as keyword 
Results 
- [ ] Orders 2, 3 return 
- [ ] Order 1, 4, 5 do not return 

7) User searches for Order using a keyword (order) and using non-exact match old case caption - Welcome to flavortown - in Case title/Petitioner name field 
Results 
- [x] Order 1, 3 , 4, 5 do not return
- [x] Order 2 returns 

8) User searches for Order using a keyword (order) and using non-exact match - Guy Fieri -  new case caption in Case title/Petitioner name field 
Results 
- [x] Orders 1, 4, return
- [x] Order 2, 3, 5 do not return 

9) User searches for Order using exact match old docket number - “106-21” as keyword 
Results 
- [ ] Order 6 returns 
- [x] Order 7 does not return  

10) User searches for Order using exact match current docket number  “106-21W” as keyword
Results 
- [x] Order 7 returns 
- [x] Order 6 does not return

11) User searches for Order using a keyword “magic” and using old docket number “107-21W”in Docket Number
Results
- [ ] Order 8 does not return  

12) User searches for Order using a keyword “magic” and using new docket number “107-21” in Docket Number field 
Results 
- [x] Order 8 returns  

13) User searches for Order using keyword old case caption “welcome to flavortown” and entering new case caption “guy fieri” in the Case title/Petitioner name field 
Results 
- [x] Order 1 returns 
- [x] Order 2, 3, 4, 5 do not return

**Comment by klohman** [comment]
![Screen Shot 2021-08-05 at 4.19.56 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/069373e3-13d9-4482-b0c2-8689cd9e9b76)

**Test 2 & 6**
* "Guy Fieri" as keyword 
* returns Order 4 PDF Upload - PDF does not contain Guy Fieri. Guy Fieri is only in case title. 
* Does not return Order 3 PDF Upload - which does contain Guy Fieri 


![Screen Shot 2021-08-06 at 9.44.14 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a1f5bb40-5e81-4ee0-89d0-54c7706db9bb)

**Test 3**
* Order on 1789-21 should not be returning. (Was this Order created before the last update? That may be the issue.)


![Screen Shot 2021-08-06 at 10.44.41 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9940e75a-3dfb-4a9f-8d23-f7f2f2aac909)

**Test 9** 
* Order 6 PDF Upload should also be returning 

![Screen Shot 2021-08-06 at 10.46.06 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b4e3afbd-2bc6-4a9d-a99f-fd1b5380f09c)

**Test 10**
* Order 4 PDF Upload should not be returning 
![Screen Shot 2021-08-06 at 9.46.50 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/78042cc6-8aa1-4149-bf9a-81a249fc64eb)



#### Hold on these items until we hear back from @cholly75 
**Test 11** 
* Order 8 should not be returning - 123-20W is on the PDF but the current docket number does not contain the W - is this how you want it to behave? 

![Screen Shot 2021-08-06 at 9.50.33 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/b3b56867-0769-4e8c-afee-d7ca8523c850)

**Additional testing**
* using quotes in the Docket number field produces no matches. It's like that this field does not support those characters, but this presents a usability issue since it is inconsistent with our other fields.

**Comment by klohman** [comment]
@cholly75 

Some info on the docket number field for searching: 

**Case Search - Docket number search**
- Strip offs all letters
- Strips out leading zeros 
- example: 123-20 will back 123-20W and vice versa

**Order Search - Docket number search**
- Does not strip off letters 
- Does not strip off leading zeros 
- Exact match only (123-20 will not bring back 123-20W orders)

**Comment by codyseibert** [comment]
While doing this work we found that some PDFs are scraped with additional spaces between the characters in words.  This is because the scrape code currently used is written to work well with a certain set of documents.  We saw that when Kristen created an order with Microsoft Word and upload it via the `upload pdf` feature in dawson, the contents was scraped like so:

{"documentContents":"\n\n Guy Fieri  \n      \n     , Petitioner               \n  \n V                                 10 3 - 21  \n  \n Commisioner of  inter nal re venue ,  \n  \n Respondent  \n  \n  \n  \n  \n  \n  \n  \n  \n ORDER   \n  \n T ha t magic  something  then  I   saw it. Welcome to flavortown, in bright lights.   103-21 Guy Fieri, Petitioner"}

attached are example orders created in word by Kristen which cause this strange parsing behavior.

[ORDER- 6 - 106-21 .pdf](https://github.com/flexion/ef-cms/files/6947767/ORDER-.6.-.106-21.pdf)
[ORDER- 7 - 106-21W .pdf](https://github.com/flexion/ef-cms/files/6947768/ORDER-.7.-.106-21W.pdf)


We find that changing this code in scrapePdfContents.js from this:

```
for (let item of pageTextContent.items) {
        if (lastY === item.transform[5] || !lastY) {
          pageText += ' ' + item.str;
        } else {
          pageText += '\n' + item.str;
        }
        lastY = item.transform[5];
      }
```

to

```
for (let item of pageTextContent.items) {
        if (lastY === item.transform[5] || !lastY) {
          pageText += '' + item.str; // <-- this line changed from ' ' to ''
        } else {
          pageText += '\n' + item.str;
        }
        lastY = item.transform[5];
      }
```

will fix the scraping of these orders, but might cause other orders we originally wrote this code to start failing when scraping.

^ all of the above is part of the reason why test case 9 tends to return 3 documents when searching `106-21`.
