### ISSUE TITLE
Order Search: Non-Keyword/Phrase Searches

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#7994]
As a user, I would like to be able to search for orders or opinions without having to enter a keyword or phrase.

## Acceptance Criteria

- Search results filtered by Judge can be delivered without the user entering any other criteria
- Search results filtered by Date Range can be delivered without the user entering any other criteria
- Search results filtered by Case Title/Petitioner Name can be delivered without the user entering any other criteria 
- Search by Docket # without entering any other criteria
- At least ONE of these are required - [judge, date range, case title/petitioner, docket number, or keyword]

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
This story is _required_ to be completed before turning on Order or Opinion search for _external_ users.

## Tasks
- [x] 1 API change - do not require a specific judge or date range or keyword to perform a search - mob ustaxcourt/ef-cms-flexion#8774
- [x] 2 Update design for search form - the mob ustaxcourt/ef-cms-flexion#8773
- [x] 3 “All judges” selected as default in judge field - the mob ustaxcourt/ef-cms-flexion#8773
- [x] 4 Update date range selector - options are “All dates” or “Custom dates” - “All dates” selected as default - the mob ustaxcourt/ef-cms-flexion#8773
- [x] 5 Selecting “Custom” for date range displays Start date and End date - the mob ustaxcourt/ef-cms-flexion#8773

Notes
- Select custom dates but don’t enter any dates in - validation (same as what already exists)
- Validation around docket number OR case title stays the same

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by klohman** [comment]
### Design concept for updated search form

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a9e4238d-2c0b-4c60-a2ff-bfa146488032)

**Judge field** 
All judges selected as default 

**Date range**
* "All dates" selected as default 
* Other options to include 
     * "Custom dates"
* On select of “Custom” - display Start date and End date fields (no change to functionality)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f72820ef-5984-4479-a4f6-484ee4be7337)

**Comment by klohman** [comment]
## 8682 Tests 

#### 1) Court user searches for Order by keyword or phrase only 
Enter keyword 
Click search 
Expected results 
[ ] Order results matching keyword return in UI 

#### 2) Court user searches for Order by Docket Number only 
Enter Docket Number 
Click search 
Expected results 
[ ] Order results matching docket number return in UI 
[ ] No error message is displayed 

#### 3) Court user searches for Order by Case title/Petitioner name only 
Enter Case Title/petitioner name  
Click search 
Expected results 
[ ] Order results matching Case title/Petitioner name return in UI 
[ ] No error message is displayed 

#### 4) Court user searches for Order by Judge only 
Select Judge 
Click search 
Expected results 
[ ] Order results matching judge return in UI 
[ ] No error message is displayed 

##### 5) Court user searches for Order by Date range only 
Select “Custom dates” for date range
Enter date range  
Click search 
Expected results 
[ ] Order results matching date range return in UI 
[ ] No error message is displayed 


#### 6) Court user searches with defaults 
Go to Order search 
Click Search 
Expected results 
[ ] Judge field displays “All judges” as default selection 
[ ] Date range displays “All dates” as default selection 
[ ] Order results return for all judges and all dates 
[ ] No error message is displayed

**Comment by klohman** [comment]
## mobile design 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/255158af-cec4-48d6-93a3-3313444e05ca)


## responsive 
* would like to keep docket # and case title fields as a group when wrapping until it gets to the mobile design 
* would also like to keep date fields as group until mobile size 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/22ec66da-dd9d-4288-a6da-a606b01d690f)

**Comment by klohman** [comment]
* When "Custom dates" is selected for date range, we'll need to add validation to require (at least) a Start date 

![Screen Shot 2021-08-13 at 9.22.27 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/cf36f5c7-c600-449a-b835-bb4e8bc63fad)

* Can we ensure that the responsive design wraps docket and case title fields as a group? 

![Screen Shot 2021-08-13 at 9.24.58 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8a0ce4ad-32b4-4684-9214-7f179a547cea)
