### ISSUE TITLE
Court: Content Changes for SPTO/Pretrial Memo - Chambers Phone # - Release with 8662 and 8663

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8000]
As the court, I need to provide accurate information on the Standing Pretrial Order and attached Pretrial Memorandum for in-person trials, so that recipients can reach the presiding judge's chambers by telephone.

## Acceptance Criteria
- User is able to enter their phone number for in-person hearings

- On the last page of the SPTO for in-person trials, the telephone number under the judge's signature should reflect the phone number of the chambers of the listed judge. Screenshot below.

- On the last page of the attached Pretrial Memorandum for in-person trials, the telephone number at the bottom of the signature block should reflect the phone number of the chambers of the listed Trial Judge. Screenshot below.

## Tasks 
 - [x] AddTrialSession form
 - [x] EditTrialSession form
 - [x] Add phone number to TrialSessionDetails
 - [x] Make phone number required for in-person sessions on Set Calendar
 - [x] Update validation on Set Calendar

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/4036cda0-ef2d-4164-b995-e9996b57f20e)

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/58450410-632e-4794-aee2-deec1ec8f9bb)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [x] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## Add Trial Session form 

**Chambers phone number**
* Add “Chambers phone number” field 
* Field is optional when creating trial session 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8f056232-648f-40e3-94b4-1a37e4357d12)


## Edit Trial Session form 

**Chambers phone number**
* Add “Chambers phone number” field 
* Field is optional when editing trial session 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ca74e1a1-6ce9-463e-9813-7eaf4bb549c8)

## Trial Session Detail screen 

**Chambers phone number**
* Add “Chambers phone number” under Judge’s name 
* Field is read-only 
* If field is empty, display “No phone number” 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/de025cbb-05e0-4c8d-990a-9bcb2ca0d13e)


#### On Set Calendar 
“Chambers phone number” is required field when setting the calendar 

**If no address, judge, or chambers phone number is entered**
display message “Provide an address, judge, and chambers phone number to set this trial session.” 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4d6e11f8-c763-4c92-bd1f-5c3fffa3285e)

**If no judge or chambers phone number is entered**
display message “Provide a judge and chambers phone number to set this trial session.” 

**If no address or chambers phone number is entered**
display message “Provide an address and chambers phone number to set this trial session.” 

**If no chambers phone number is entered**
display message “Provide a chambers phone number to set this trial session.”

**Comment by klohman** [comment]
### 8707 Test cases 

#### 1) Petitions clerk adds in-person trial session with chambers phone number. 
Expected results 
- [x] Chambers phone number field displays as optional on Add Trial Session form 

#### 2) Petitions clerk edits  in-person trial session and adds chambers phone number. 
Expected results 
- [x] Chambers phone number field displays as optional on Edit Trial Session form 

#### 3) Court user views in-person trial session with chambers phone number. 
Expected results 
- [x] Chambers phone number displays on Trial Session Detail screen under Judge’s name

#### 4) Court user views  in-person trial session without chambers phone number. 
Expected results 
- [x] “No phone number” displays on Trial Session Detail screen under Judge’s name

#### 5) Petitions clerk sets calendar for in-person trial session without chambers phone number. 
Expected results 
- [x] Calendar is not set and app remains on screen 
- [x] Warning message displays “Provide a chambers phone number to set this trial session.”

#### 6) Petitions clerk sets calendar for in-person trial session without address, judge and chambers phone number. 
Expected results 
- [x] Calendar is not set and app remains on screen 
- [x] Warning message displays “Provide an address, judge, and chambers phone number to set this trial session.”

#### 7) Petitions clerk sets calendar for in-person trial session without address and chambers phone number. 
Expected results 
- [x] Calendar is not set and app remains on screen 
- [x] Warning message displays “Provide an address and chambers phone number to set this trial session.”

#### 8) Petitions clerk sets calendar for in-person trial session without judge and chambers phone number. 
Expected results 
- [x] Calendar is not set and app remains on screen 
- [x] Warning message displays “Provide a judge and chambers phone number to set this trial session.”

#### 9) Court user views chambers phone number on SPTO/Pre-trial Memo for regular cases/in-person session. 
Expected results 
- [x] Chambers phone number entered on trial session form displays under Judge’s signature on SPTO 
- [x] Chambers phone number entered on trial session form displays under Court address on Pretrial Memo

#### 10) Court user views chambers phone number on SPOS/Pre-trial Memo for small cases/ in person session. 
- [x] Chambers phone number entered on trial session form displays under Judge’s signature on SPOS 
- [x] Chambers phone number entered on trial session form displays under Court address on Pretrial Memo

**Comment by klohman** [comment]
Some small UI tweaks: 
* on the trial session detail, can we increase the size of the Details card to align with the Assignments card (now that we've added some additional vertical space) 

![Screen Shot 2021-08-04 at 11.02.15 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/03036b4f-a7c7-4185-a04b-9afb59793f10)


* On the SPOS/SPTO, can we increase the space between the judge signature and the phone number
![Screen Shot 2021-08-04 at 12.23.00 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/81010c23-e53b-4fba-a085-56c4e0708675)

@TomElliottFlexion I also had a bit of trouble on dev setting the calendar but want to try it again a couple times to see if the problem persists. 

- first attempt at setting calendar, got the spinner for a long time. I worked on something else for a while and when i returned the session was set - https://app.dev.ustc-case-mgmt.flexion.us/trial-session-detail/b80f14e8-f61e-4405-a309-840d52bfbdbc
- second attempt to set a calendar, got bumped to an error screen 
![Screen Shot 2021-08-04 at 12.37.20 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/10784b8a-9c0b-46b2-8217-3c8a5dbe9105)
