### ISSUE TITLE
Court: Prevent parties from being served case documents before the petition is served

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8014]
As a party in a case, so I can be served documents in logical order, I need my petition to be served before other documents in the case are served. 

We have had issues with a docket clerk adding a paper filing to the docket record before the petition was served.  We have also had issues with a practitioner changing his/her contact information before a petition is served and the system generates a notice of change of address/phone.  In both cases, the system does *NOT* send service emails but notes on the docket record that the document has been served.

## Acceptance Criteria
* Parties in a case are served the petition before all other service

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks

- [ ] Add Warning banner to “Add Docket Entry” component and hide “Save and Serve” button (Kris ustaxcourt/ef-cms-flexion#8853)
- [ ] add computed value to addCourtIssuedDocketEntryHelper (Kris Kris ustaxcourt/ef-cms-flexion#8853)
- [ ] Add warning text above unservable iframe in Document View and hide “Serve” button (Kris ustaxcourt/ef-cms-flexion#8853)
- [ ] Add warning text above unservable iframe in Message View and hide “Serve” button (Kris ustaxcourt/ef-cms-flexion#8862)
- [ ] Add Warning banner to “Edit Docket Entry” component and hide “Save and Serve” button (Kris ustaxcourt/ef-cms-flexion#8853)
- [ ] Add Warning banner to “Add Paper Filing” component and hide “Save and Serve” button (Kris ustaxcourt/ef-cms-flexion#8865)
- [ ] Add Warning banner to “Edit Paper Filing” component and hide “Save and Serve” button (Kris ustaxcourt/ef-cms-flexion#8865)
- [ ] Update interactors to prevent service of documents if petition itself is not already served. See https://github.com/flexion/ef-cms/pull/8853#issuecomment-905691956 and related PR that was never merged (Kris ustaxcourt/ef-cms-flexion#8869)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Related bug: https://github.com/flexion/ef-cms/issues/8297

**Comment by mariahkannenberg** [comment]
Groom/Needs more info - Break this into smaller stories -- one for each notice type.

**Comment by cholly75** [comment]
@mariahkannenberg If the general rule is "keep everything pending until the Petition is served", do we still need separate stories?

**Comment by klohman** [comment]
relevant stories
- https://github.com/flexion/ef-cms/issues/4661

**Service Flows** 

Petition is NOT SERVED 

- Petitioner eFiles Document - prevented in UI
- Private practitioner eFiles Document in case - prevented in UI 
- IRS practitioner eFiles Document in case - prevented in UI 
- Court user (petitions, docket) adds paper filing to case 
- Court user (petitions, docket) adds/serves Order 
- Petitioner updates contact info - prevented in UI 
- Private practitioner updates petitioner contact info - prevented in UI
- Private practitioner updates their contact info 
- IRS practitioner updates their contact info 


- Notice of Docket Change - shouldn’t be possible if all e-filings are prevented?
- Notice of Trial - “shouldn’t” be possible unless case is mistakenly added to a trial session?

**Comment by klohman** [comment]
## Case status = NEW (i.e. Petition has not been served) 

#### Practitioner address/phone number is updated 
* Notice of Change of Address / Phone number is not generated for any cases in NEW status 
* Notice of Change of Address/Phone numbers are generated for all other practitioner cases (current functionality) 
* Practitioner's updated address/phone number displays in UI 

#### Add Docket Entry (Court-issued documents) 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e9192dd-a203-4dd1-981c-d11c3a355d76)

* Hide "Save and Serve" button 
* Display warning message 

#### Document View 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1d0efea3-7a5f-4d59-8b4d-06e9d59acca5)

* Hide "Serve" button 
* Display warning message 

#### Message Detail 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/6e7436d2-b73b-4eea-8481-d41cd9e76555)

* Hide "Serve" button 
* Display warning message 

#### Edit Docket Entry (Court-Issued document) 
* this is the screen accessed when a court-issue document is saved to the Docket Record and then accessed via the In Progress tab 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/c25e682c-2917-43c8-b12e-1a97d975a78c)

* Hide "Save and Serve" button 
* Display warning message 

#### Add Paper Filing 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f14cabf1-960f-4c12-8d80-055ffbacc409)

* Hide "Save and Serve" button 
* Display warning message 

#### Edit Paper Filing 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/3d5a9697-3ddf-4910-9664-c3ccbd84c30c)
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f340b2e8-b57d-4c45-b49b-9a6e0041077d)

**Comment by klohman** [comment]
### 8763 Test

#### 1) Docket clerk adds docket entry when case status = NEW
* Login as docket clerk
* Go to case with status = NEW 
* Create, save, sign Order 
* Add Docket Entry for Order 
* Save 
Expected results 
- [x] Warning messaging displays on Add Docket Entry screen 
- [x] Save and Serve button is hidden 
On Save, 
- [x] Docket entry is added to Record but not served 

#### 2) Docket clerk adds docket entry when case status = NEW and accesses document from In Progress tab 
* Scenario 1 
* Go to Document QC > In Progress tab 
* Click on Order link
Expected results 
- [x] Warning messaging displays on Edit Docket Entry screen 
- [x] Save and Serve button is hidden 

#### 3) Docket clerk views unserved court-issued document in Document View 
* Scenario 1
* Go to Document View and select Order 
Expected results 
- [x] Warning messaging displays on Document view  
- [x] Serve button is hidden 

#### 4) Docket clerk views message with unserved court-issued document attached 
* Scenario 1 
* Send message with Order attached 
* View message 
Expected results 
- [x] Warning messaging displays on Message screen 
- [x] Serve button is hidden

#### 5) Docket clerk adds paper filing when case status = NEW 
* Login as docket clerk
* Go to case with status = NEW 
* Add Paper Filing 
* Save 
Expected results 
- [x] Warning messaging displays on Add paper filing screen 
- [x] Save and Serve button is hidden 
On Save, 
- [x] Docket entry is added to Record but not served 

#### 6) Docket clerk adds paper filing when case status = NEW and accesses document from In Progress tab 
* Scenario 5
* Go to Document QC > In Progress tab 
* Click on paper filing link
Expected results 
- [x] Warning messaging displays on Edit Paper filing screen 
- [x] Save and Serve button is hidden 

#### 7) Docket clerk views unserved paper filing document in Document View 
* Scenario 5 
* Go to Document View and select paper filing 
Expected results 
- [x] Warning messaging displays on on Document View 
- [x] Serve button is hidden 

#### 8) Docket clerk views message with unserved paper-filing document attached 
* Scenario 5 
* Send message with paper filing attached
* View message
Expected results 
- [x] Warning messaging displays on Message screen 
- [x] Serve button is hidden

#### 9) Practitioner updates their contact information and has case status = NEW 
* Login as practitioner 
    * Has at least 1 case with status = NEW
    * Has at least 1 case with status = General Docket 
* Update address/phone number 
Expected results 
- [x] Updated address/phone displays in UI 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is added to docket record for cases (Open cases and Closed cases within last 6 months) without status = NEW 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is served for cases (Open cases and Closed cases within last 6 months) without status = NEW 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not added to Docket Record on any cases with status NEW  
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not served on any cases with status NEW  

#### 10) Admissions clerk updates practitioner contact info with case status = NEW 
* Login as admissions clerk
* Go to practitioner  
    * Has at least 1 case with status = NEW
    * Has at least 1 case with status = General Docket 
* Update address/phone number 
Expected results 
- [x] Updated address/phone displays in UI 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is added to docket record for cases (Open cases and Closed cases within last 6 months) without status = NEW 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is served for cases (Open cases and Closed cases within last 6 months) without status = NEW 
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not added to Docket Record on any cases with status NEW  
- [x] Notice of Change of Address/Notice of Change of Phone Number/Notice of Change of Address and Phone Number is not served on any cases with status NEW

**Comment by klohman** [comment]
#### Test 3 
* On the Edit Docket Entry screen - we don't need to show both alerts. if case status is New, display only the yellow warning message. 
![Screen Shot 2021-08-30 at 3.55.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/eb96e7eb-b036-4aa8-9b52-11f485bd69a4)

#### Test 7
* On Document View for a paper-filing, the warning message "Document cannot be served until the Petition is served" should display in place of the Not Served above the pdf preview 
![Screen Shot 2021-08-30 at 3.59.39 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/59ce3e69-3848-4a72-8899-f57fd606787f)

#### Test 9 / 10
**On dev - 203-21**
* updating practitioner contact info generated a Notice of Change of Address/phone number and opened up the case to e-filing

**Comment by kkoskelin** [comment]
Pending changes made so that if the petition itself is unserved *AND* the petition is the selected document, it still says "Not Served":
![Screen Shot 2021-08-30 at 4 15 08 PM](https://user-images.githubusercontent.com/2445917/131406595-627dd667-691f-4083-a74b-da259012c206.png)

However, all other documents will show as below:
![Screen Shot 2021-08-30 at 4 15 14 PM](https://user-images.githubusercontent.com/2445917/131406698-7ea24236-4b6e-47b8-9178-20a697d7da97.png)

If I should instead show the same message regardless whether the selected document is a petition, please let me know.

**Comment by klohman** [comment]
@kkoskelin Your first instinct is right. Let's show "Not Served" for the Petition document, but the "Document cannot be served...." message for all other documents.

**Comment by ttlenard** [comment]
Test Case 5 - As docket Clerk, if you choose add paper Filing, the save and serve button is still visible, and if you click it, you DO get a warning message stating it is NOT electronically served, but on the docket record, it shows it was served.  I was in 20050-21.
-
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/606dbb81-5837-4ef1-9227-8bbe35d0ac7e)

**Comment by mariahkannenberg** [comment]
None of this story can go live with Batch 8. @kkoskelin @TomElliottFlexion @ericsorenson

**Comment by TomElliottFlexion** [comment]
The commits that had not yet made it from dev -> staging have been cherry-picked and [merged](https://github.com/flexion/ef-cms/pull/8906) into staging, and this story has been moved back to Batch 8. @cholly75 @mariahkannenberg @kkoskelin

**Comment by ttlenard** [comment]
Some testing feedback:  

For brand new cases, the system prevented service from happening if the petition was not yet served (yay!)  However, for the records that had docket entries that had been served already and a petition that had not yet been served, there was some different behavior.  I talked with Chris about this and we think it will be ok (I think there are only 9 cases in PROD that are in this state), but I wanted to discuss this behavior we are seeing with the team to see if there are underlying issues that we need to address?

Examples:
For the records that had served docket entries (ex. 12861-21, 14945-21)) when the petition was not yet served, I was able to:

- File and EA by Private Practitioner (bullet ustaxcourt/ef-cms#6492 above)
- File an Answer by Respondent (bullet ustaxcourt/ef-cms#6493 above)
- When Private Practitioner updates their contact info, it will not update, but WILL update in ones where the petition is served (bullet ustaxcourt/ef-cms#6497 above)
- When IRS Practitioner updates their contact info, it will not update, but WILL update in ones where the petition is served. (Bullet ustaxcourt/ef-cms-flexion#9 above)
- I was able to edit docket entries, but I can't remember what document types generate a notice of docket change.  (Bullet ustaxcourt/ef-cms-flexion#10 above)
- Was able to add the funky and new case to a calendared trial, but I didn't see a notice come through on either. Don’t' think that this would happen?  Wasn't able to get this case back to NEW Status after I tested this.  (20064-21) (Bullet ustaxcourt/ef-cms-flexion#11 above)

Also of note: I checked the logs and I couldn't find service emails for these cases, even though a service date was in DAWSON.

**Comment by mariahkannenberg** [comment]
Blocked - Waiting on decision referenced in above comment. @cholly75 @JessicaMarine

**Comment by mariahkannenberg** [comment]
Unblocked - going to backlog a story to fix the 9 issues. Tenille to backlog.

**Comment by matthopson** [comment]
@cholly75 I'm just pulling this over from Slack (thanks Mike). Are these conditions correct for this story / Bug ustaxcourt/ef-cms#8073 (https://github.com/flexion/ef-cms/issues/8952)?

>Re: 8763, I talked with @Chris Holly last night, and we thought it would be best if the ticket did what the title and AC specify:
Is there a petition document?
>
-- Yes; Is it served?
---- Yes; Allow service
---- No; Disallow service
-- No; are there other documents on the case that are served?
---- Yes; Allow service
---- No; Disallow service. Log warning
>
We’ll chat at 10am (edited)

**Comment by cholly75** [comment]
@matthopson Yes, that's correct.

**Comment by matthopson** [comment]
@cholly75 Just one question for clarity - are we defining a petition document in ANY other way than a document with event code "P"?

**Comment by cholly75** [comment]
@matthopson I'm relying on past conversations prior to my arrival at the Court for this; I believe ( @JessicaMarine can confirm) that it was determined that searching for all available petitions with all possible codes would be difficult or problematic to do with accuracy for legacy cases, hence the guidance to use the "if anything has already been served, consider the petition served" rule. 

If there are other coded events we use regularly for petitions (if there's a guide or reference, please let me know), going forward, then we would want to capture those as well, but the concern is that we have (for example) MISC or other codes that aren't necessarily petition-specific that we need to account for lurking in cases in the system and so we don't want to exclude service on their account.

**Comment by cholly75** [comment]
@matthopson It looks like based on JSON files that the codes P, RAT, and PTFR are the only ones currently designated with the category of "Petition", if that helps. Doesn't solve the legacy case problem, but presumably all three of these would be considered a "petition" for current cases.

**Comment by matthopson** [comment]
Then is it more fair to say the logic should be:

```
Is this a legacy case?
- YES: Is any document served?
---- YES: Allow service
---- NO: Disallow service
- NO: Is there a served petition [P, RAT, PTFR]?
---- YES: Allow service
---- NO: Disallow service
```

The logic in the previous comment doesn't specify what a petition actually _is_. Without being able to correctly identify a petition we can't know if it's served or not. Relying, however, on whether it's a legacy case, we can easily just look for any document that's served - which seems to be the real intent here.

**Comment by matthopson** [comment]
Which I thought sounded familiar.. haha.
![Screen Shot 2021-09-20 at 11.12.17 AM.png](https://images.zenhubusercontent.com/5cadf168c7e4b91e9a637015/b4d169c5-f20c-4313-a70f-6254cb0c9ae3)

**Comment by mmarcotte** [comment]
@matthopson -- You would never get to "Is there a served petition [P, RAT, PTFR]" if there is no document served.

```
- NO: Is there a served petition [P, RAT, PTFR]?
---- YES: Allow service
---- NO: Disallow service
```

**Comment by mmarcotte** [comment]
The initial logic proposal that I made helps catch the untenable situation, which we could probably query for right now, of 

> there are no documents served and there is no petition document to serve.

**Comment by cholly75** [comment]
@matthopson My worry is that we're building in a "gotcha" in case the Court adds a new petition event code down the line; wouldn't it be safer to check:

Is there a served petition [P, RAT, PTFR]?
-YES: Allow service
-NO: Is any document served?
  - YES: Allow service
  - NO: Disallow service

An alternative solution was discussed last week I believe that might also simplify the problem greatly: disallowing service for everyone except Petitions clerks if the case is still in NEW status; given that the logic for moving the case from NEW to General Docket - Not At Issue is based on the service of the petition, and no legacy cases are in NEW status, this would accomplish the same thing (preventing service on cases before the petition has been served) without parsing the docket. I'm not sure how radical a change this would be given the current implementation, but it would seem to solve the problem?

**Comment by matthopson** [comment]
That logic started by asking the question "is there a petition document served", not "is any document served", and I saw Chris kinda qualified the problem with legacy documents (as we've kinda discussed in past conversations).

@cholly75 
>searching for all available petitions with all possible codes would be difficult or problematic to do with accuracy for legacy cases, hence the guidance to use the "if anything has already been served, consider the petition served" rule.

**Comment by matthopson** [comment]
@cholly75 
>wouldn't it be safer to check:

```
Is there a served petition [P, RAT, PTFR]?
-YES: Allow service
-NO: Is any document served?

YES: Allow service
NO: Disallow service
```

I think this effectively simplifies to "if any document is served, allow service - otherwise disallow service" - which is what existed before this story.

**Comment by matthopson** [comment]
@cholly75 @mmarcotte 

>disallowing service for everyone except Petitions clerks if the case is still in NEW status

Can we agree that this would cover all expectations? I'm happy to explore this approach, as it seems simple enough to rely on the case status and not care about the state of the docket record as long as there aren't any weird edges to this assumption.

**Comment by cholly75** [comment]
@matthopson It should, yes; as long as we're restricting service (not entry) for non-Petitions users if the case is in NEW state, that would effectively solve the problem.
