### ISSUE TITLE
Order Search - Automate performance testing to utilize variable data for a simulated load

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8025]
As a court user, so that I can perform performance testing, I need a framework to automate performance testing to utilize variable data for a simulated load

## Acceptance Criteria
* X simultaneous users running a randomized order query every Y seconds for Z minutes. Results must return within XX seconds. Users should see YY request timeouts.
* For functionality that utilizes ES run one for each query type every X seconds. [Ref list of functionality](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8793#issuecomment-901381301) (Only for case advanced search, case public search, get case by user ID, messages, doc QC)

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* How long a search can take? We've made changes, so do we need to change our baselines?
See previous spikes and performance stories: ustaxcourt/ef-cms#7892 ustaxcourt/ef-cms#7700 ustaxcourt/ef-cms#7579 ustaxcourt/ef-cms#7736
* For this story, not defining the standard. Just creating the automation. 

- We need to determine at what point the system performance application-wide begins to degrade, whether this is a function of ES CPU usage, volume, or other factors. Ideally the tests written in this story will be the basis of a mechanism that lets us test against the codebase to ensure that whatever code we develop allows the system to remain performant.
- Ultimately, work done needs to be in service to establishing a baseline level of understanding w/r/t how the system performs under various levels of load.
- Ref. ustaxcourt/ef-cms#7577 for other information that may inform this story

## Tasks
- [x] Add `artillery` library for performance/load testing
- [x] Add artillery config for `Case Deadlines` (Jojo)
- [x] Add artillery config for Case Advanced Search
- [x] Add artillery config for Case Public Search
- [x] Add artillery config for Blocked Cases Report
- [x] Add artillery config for Case Inventory Report
- [x] Add artillery config for Get Case By User ID
- [x] Add artillery config for Get First Single Case
- [x] Add artillery config for Get Ready For Trial Cases
- [x] Add artillery config for Get Case Deadlines (report)

`efcms-docket-entry`
- [x] Add artillery config for Advanced Document Search (USES JOIN ON CASE)
- [x] Add artillery config for Pending Items (USES JOIN ON CASE)
- [x] Add artillery config for Reconciliation Report

`efcms-message`
- [x] Add artillery config for Messages (user / section, inbox / completed)

`efcms-user-case`
- [x] Add artillery config for Indexed Cases for User (open / closed cases, verify user pending email)

`efcms-user`
- [x] Add artillery config for Practitioner By Name

`efcms-work-item`
- [x] Add artillery config for Document QC (user / section)

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
Services / Features By ES Index

`efcms-case-deadline`
- Case Deadlines

`efcms-case`
- Case Advanced Search
- Case Public Search
- Blocked Cases Report
- Case Inventory Report
- Get Case By User ID
- Get First Single Case
- Get Ready For Trial Cases
- Get Case Deadlines (report)

`efcms-docket-entry`
- Advanced Document Search (USES JOIN ON CASE)
- Pending Items (USES JOIN ON CASE)
- Reconciliation Report

`efcms-message`
- Messages (user / section, inbox / completed)

`efcms-user-case`
- Indexed Cases for User (open / closed cases, verify user pending email)

`efcms-user`
- Practitioner By Name

`efcms-work-item`
- Document QC (user / section)

**Comment by mmarcotte** [comment]
@cholly75 and I came up the following while spitballing for this story:

* Document (Order/Opinion) searches need to return information within 2 seconds under no/low load 
* Document searches need to return information within 10 seconds under high load (90%+ CPU Usage)
* Baseline for each of the other systems that rely on ES is established under no/low load (how many milliseconds?)
* Baseline is established for how many concurrent users can perform document searches before system degradation is observed.
* System degradation is defined as observing the other systems that use ES consistently exhibiting increased response times from their baselines

So, if we observe the baseline of other parts of the application being 500ms, as we add concurrent document searches at what point do we observe those numbers going up consistently? What is the ES CPU when this occurs?

We use this baseline of concurrent search capacity to inform the rate limiting stories.

**Comment by sutt0n** [comment]
> @cholly75 and I came up the following while spitballing for this story:
> 
>     * Document (Order/Opinion) searches need to return information within 2 seconds under no/low load
> 
>     * Document searches need to return information within 10 seconds under high load (90%+ CPU Usage)
> 
>     * Baseline for each of the other systems that rely on ES is established under no/low load (how many milliseconds?)
> 
>     * Baseline is established for how many concurrent users can perform document searches before system degradation is observed.
> 
>     * System degradation is defined as observing the other systems that use ES consistently exhibiting increased response times from their baselines
> 
> 
> So, if we observe the baseline of other parts of the application being 500ms, as we add concurrent document searches at what point do we observe those numbers going up consistently? What is the ES CPU when this occurs?
> 
> We use this baseline of concurrent search capacity to inform the rate limiting stories.

If those criteria aren't met due to implementing automated performance test (this story), then those would have to be separate tasks of their own (pending this output of this story), if I'm not mistaken.

cc: @cholly75 @mmarcotte @mariahkannenberg

**Comment by codyseibert** [comment]
duration: 300
arrivalRate: 5

```
{
    "timestamp": "2021-08-30T16:21:27.881Z",
    "scenariosCreated": 1500,
    "scenariosCompleted": 1500,
    "requestsCompleted": 1500,
    "latency": {
      "min": 55,
      "max": 1734,
      "median": 139.5,
      "p95": 1176.5,
      "p99": 1506.5
    },
    "rps": {
      "count": 1500,
      "mean": 4.99
    },
    "scenarioDuration": {
      "min": 144.2,
      "max": 2309.7,
      "median": 236.8,
      "p95": 1517.1,
      "p99": 1971.5
    },
    "scenarioCounts": {
      "Messages: User Completed": 79,
      "Messages: User Sent": 75,
      "Case Inventory Report": 79,
      "Document QC: Section Outbox (Docket)": 83,
      "Document QC: User Inbox": 73,
      "Case Deadlines": 63,
      "Messages: User Inbox": 78,
      "Advanced Document Search": 71,
      "Blocked Cases Report": 88,
      "Messages: Completed Section (Docket)": 75,
      "Document QC: User Outbox": 139,
      "Practitioner By Name": 61,
      "Case Public Search": 75,
      "Case Advanced Search": 73,
      "Pending Items": 74,
      "Document QC: Section Inbox (Docket)": 81,
      "Reconciliation Report": 74,
      "Messages: Sent Section (Docket)": 91,
      "Case Deadline Search": 68
    },
    "errors": {},
    "codes": {
      "200": 1341,
      "403": 74,
      "404": 75,
      "429": 10
    },
    "matches": 0,
    "customStats": {
      "messages-user-completed": {
        "min": 148,
        "max": 370,
        "median": 168,
        "p95": 246.8,
        "p99": 361.3
      },
      "messages-user-sent": {
        "min": 146,
        "max": 512,
        "median": 169,
        "p95": 280.8,
        "p99": 471.8
      },
      "case-inventory-report": {
        "min": 152,
        "max": 378,
        "median": 176,
        "p95": 253.8,
        "p99": 367
      },
      "document-qc-user-inbox": {
        "min": 178,
        "max": 371,
        "median": 197,
        "p95": 274.3,
        "p99": 352.6
      },
      "messages-section-docket-inbox": {
        "min": 291,
        "max": 681,
        "median": 310,
        "p95": 411.5,
        "p99": 660.5
      },
      "case-deadlines": {
        "min": 190,
        "max": 459,
        "median": 211,
        "p95": 327.4,
        "p99": 447.7
      },
      "document-qc-section-outbox": {
        "min": 1447,
        "max": 2305,
        "median": 1710,
        "p95": 2083,
        "p99": 2263.4
      },
      "advanced-document-search": {
        "min": 181,
        "max": 1306,
        "median": 752,
        "p95": 1101,
        "p99": 1283.7
      },
      "blocked-cases-report": {
        "min": 336,
        "max": 568,
        "median": 390,
        "p95": 478,
        "p99": 547.5
      },
      "messages-user-inbox": {
        "min": 148,
        "max": 386,
        "median": 166,
        "p95": 245.8,
        "p99": 372
      },
      "document-qc-user-outbox": {
        "min": 163,
        "max": 1183,
        "median": 184,
        "p95": 274.3,
        "p99": 763.8
      },
      "practitioner-by-name": {
        "min": 215,
        "max": 435,
        "median": 243,
        "p95": 344,
        "p99": 429.7
      },
      "case-public-search": {
        "min": 139,
        "max": 459,
        "median": 160,
        "p95": 271,
        "p99": 445.5
      },
      "case-advanced-search": {
        "min": 248,
        "max": 478,
        "median": 289,
        "p95": 392.8,
        "p99": 473.6
      },
      "pending-items": {
        "min": 146,
        "max": 512,
        "median": 194.5,
        "p95": 272.2,
        "p99": 511
      },
      "document-qc-section-inbox": {
        "min": 503,
        "max": 1030,
        "median": 588,
        "p95": 751.5,
        "p99": 979.5
      },
      "messages-section-docket-sent": {
        "min": 572,
        "max": 1723,
        "median": 652,
        "p95": 1063.8,
        "p99": 1633.6
      },
      "case-deadline-search": {
        "min": 328,
        "max": 570,
        "median": 372,
        "p95": 476.3,
        "p99": 569.6
      }
    },
    "counters": {
      "code 200 on messages-user-completed": 79,
      "code 200 on messages-user-sent": 75,
      "code 200 on case-inventory-report": 79,
      "code 200 on document-qc-user-inbox": 73,
      "code 200 on messages-section-docket-inbox": 75,
      "code 200 on case-deadlines": 63,
      "code 200 on document-qc-section-outbox": 83,
      "code 200 on advanced-document-search": 61,
      "code 200 on blocked-cases-report": 88,
      "code 200 on messages-user-inbox": 78,
      "code 200 on document-qc-user-outbox": 139,
      "code 200 on practitioner-by-name": 61,
      "code 404 on case-public-search": 75,
      "code 200 on case-advanced-search": 73,
      "code 200 on pending-items": 74,
      "code 200 on document-qc-section-inbox": 81,
      "code 403 on pending-items": 74,
      "code 200 on messages-section-docket-sent": 91,
      "code 200 on case-deadline-search": 68,
      "code 429 on advanced-document-search": 10
    },
    "scenariosAvoided": 0,
    "phases": [
      {
        "duration": 300,
        "arrivalRate": 5,
        "name": "Sustained load"
      }
    ]
  }
```

![Screen Shot 2021-08-30 at 12 25 11 PM](https://user-images.githubusercontent.com/1868782/131371959-6dfff971-5f39-4cbb-ba46-882c4e25c04c.png)

**Comment by codyseibert** [comment]
- duration: 300
      arrivalRate: 100

```
{
    "timestamp": "2021-08-30T16:39:39.456Z",
    "scenariosCreated": 30000,
    "scenariosCompleted": 29780,
    "requestsCompleted": 29809,
    "latency": {
      "min": 11,
      "max": 7461,
      "median": 167,
      "p95": 1301,
      "p99": 2144.4
    },
    "rps": {
      "count": 30000,
      "mean": 96.69
    },
    "scenarioDuration": {
      "min": 154.3,
      "max": 9992.6,
      "median": 379.2,
      "p95": 3606.8,
      "p99": 6266
    },
    "scenarioCounts": {
      "Pending Items": 1755,
      "Messages: Completed Section (Docket)": 1825,
      "Case Advanced Search": 1817,
      "Case Deadline Search": 1777,
      "Messages: Sent Section (Docket)": 1731,
      "Document QC: User Inbox": 1787,
      "Document QC: Section Outbox (Docket)": 1698,
      "Document QC: User Outbox": 3500,
      "Document QC: Section Inbox (Docket)": 1767,
      "Case Deadlines": 1796,
      "Messages: User Inbox": 1775,
      "Blocked Cases Report": 1795,
      "Practitioner By Name": 1732,
      "Messages: User Completed": 1773,
      "Messages: User Sent": 1748,
      "Case Inventory Report": 1724
    },
    "errors": {
      "ETIMEDOUT": 220
    },
    "codes": {
      "200": 29809
    },
    "matches": 0,
    "customStats": {
      "pending-items": {
        "min": 185,
        "max": 6601,
        "median": 287,
        "p95": 948,
        "p99": 3532.1
      },
      "messages-section-docket-inbox": {
        "min": 285,
        "max": 8096,
        "median": 479,
        "p95": 1380.5,
        "p99": 2750.5
      },
      "document-qc-user-inbox": {
        "min": 171,
        "max": 7280,
        "median": 244,
        "p95": 964.3,
        "p99": 2918
      },
      "case-advanced-search": {
        "min": 276,
        "max": 7591,
        "median": 472,
        "p95": 1563.5,
        "p99": 4577.4
      },
      "case-deadline-search": {
        "min": 339,
        "max": 7589,
        "median": 447,
        "p95": 1119,
        "p99": 2418.7
      },
      "document-qc-user-outbox": {
        "min": 151,
        "max": 5956,
        "median": 225,
        "p95": 628,
        "p99": 1684.7
      },
      "case-deadlines": {
        "min": 177,
        "max": 4921,
        "median": 247,
        "p95": 645.3,
        "p99": 1714.2
      },
      "messages-user-inbox": {
        "min": 154,
        "max": 5827,
        "median": 216,
        "p95": 768.1,
        "p99": 3528.7
      },
      "practitioner-by-name": {
        "min": 223,
        "max": 7210,
        "median": 342,
        "p95": 1132.4,
        "p99": 3073.4
      },
      "messages-user-completed": {
        "min": 154,
        "max": 5640,
        "median": 218,
        "p95": 723.6,
        "p99": 2632.7
      },
      "messages-user-sent": {
        "min": 150,
        "max": 6986,
        "median": 214,
        "p95": 756.5,
        "p99": 2555.6
      },
      "blocked-cases-report": {
        "min": 401,
        "max": 8471,
        "median": 761,
        "p95": 2017.8,
        "p99": 4896.7
      },
      "document-qc-section-inbox": {
        "min": 558,
        "max": 8470,
        "median": 1299,
        "p95": 2996.3,
        "p99": 4809.1
      },
      "messages-section-docket-sent": {
        "min": 668,
        "max": 9948,
        "median": 1561,
        "p95": 3327.5,
        "p99": 5824
      },
      "case-inventory-report": {
        "min": 156,
        "max": 5832,
        "median": 223,
        "p95": 891,
        "p99": 2600.2
      },
      "document-qc-section-outbox": {
        "min": 1623,
        "max": 9987,
        "median": 4545,
        "p95": 7552.5,
        "p99": 8734.6
      }
    },
    "counters": {
      "code 200 on pending-items": 1748,
      "code 200 on messages-section-docket-inbox": 1811,
      "code 200 on document-qc-user-inbox": 1775,
      "code 200 on case-advanced-search": 1805,
      "code 200 on case-deadline-search": 1768,
      "code 200 on document-qc-user-outbox": 3483,
      "code 200 on case-deadlines": 1785,
      "code 200 on messages-user-inbox": 1759,
      "code 200 on practitioner-by-name": 1726,
      "code 200 on messages-user-completed": 1759,
      "code 200 on messages-user-sent": 1739,
      "code 200 on blocked-cases-report": 1776,
      "code 200 on document-qc-section-inbox": 1757,
      "code 200 on messages-section-docket-sent": 1719,
      "code 200 on case-inventory-report": 1710,
      "code 200 on document-qc-section-outbox": 1660
    },
    "scenariosAvoided": 0,
    "phases": [
      {
        "duration": 300,
        "arrivalRate": 100,
        "name": "Sustained load"
      }
    ]
  }
```


![Screen Shot 2021-08-30 at 12 43 27 PM](https://user-images.githubusercontent.com/1868782/131374300-50538f7f-94e0-4dfd-8506-751cec23dc84.png)

**Comment by codyseibert** [comment]
- duration: 300
      arrivalRate: 180


```
{
    "timestamp": "2021-08-30T16:49:31.946Z",
    "scenariosCreated": 54000,
    "scenariosCompleted": 34468,
    "requestsCompleted": 36126,
    "latency": {
      "min": 14,
      "max": 7709,
      "median": 240,
      "p95": 1657,
      "p99": 2998.2
    },
    "rps": {
      "count": 54000,
      "mean": 174.04
    },
    "scenarioDuration": {
      "min": 167.6,
      "max": 10039.9,
      "median": 558.1,
      "p95": 4923.9,
      "p99": 8594.6
    },
    "scenarioCounts": {
      "Case Advanced Search": 3188,
      "Document QC: User Outbox": 6320,
      "Messages: Sent Section (Docket)": 3201,
      "Blocked Cases Report": 3138,
      "Practitioner By Name": 3105,
      "Messages: User Inbox": 3170,
      "Case Deadline Search": 3218,
      "Messages: User Completed": 3101,
      "Document QC: Section Outbox (Docket)": 3231,
      "Pending Items": 3187,
      "Document QC: Section Inbox (Docket)": 3208,
      "Document QC: User Inbox": 3137,
      "Case Inventory Report": 3209,
      "Case Deadlines": 3234,
      "Messages: Completed Section (Docket)": 3207,
      "Messages: User Sent": 3146
    },
    "errors": {
      "ECONNREFUSED": 17526,
      "ETIMEDOUT": 2000,
      "ENOTFOUND": 5,
      "ECONNRESET": 1
    },
    "codes": {
      "200": 36126
    },
    "matches": 0,
    "customStats": {
      "messages-user-inbox": {
        "min": 177,
        "max": 6249,
        "median": 280,
        "p95": 1166.1,
        "p99": 2785.2
      },
      "document-qc-user-outbox": {
        "min": 170,
        "max": 5249,
        "median": 269,
        "p95": 807.1,
        "p99": 1705.8
      },
      "messages-user-completed": {
        "min": 164,
        "max": 6822,
        "median": 279,
        "p95": 1245,
        "p99": 2747.8
      },
      "case-advanced-search": {
        "min": 362,
        "max": 9364,
        "median": 886,
        "p95": 3287.5,
        "p99": 5558.4
      },
      "pending-items": {
        "min": 217,
        "max": 7823,
        "median": 434,
        "p95": 2335.6,
        "p99": 3898.2
      },
      "case-deadline-search": {
        "min": 377,
        "max": 9079,
        "median": 634,
        "p95": 2044,
        "p99": 3863.9
      },
      "practitioner-by-name": {
        "min": 248,
        "max": 7867,
        "median": 509.5,
        "p95": 2509,
        "p99": 4114.8
      },
      "case-deadlines": {
        "min": 201,
        "max": 6861,
        "median": 287,
        "p95": 937.9,
        "p99": 2947.1
      },
      "messages-user-sent": {
        "min": 171,
        "max": 5127,
        "median": 276,
        "p95": 1199.9,
        "p99": 3063.8
      },
      "document-qc-user-inbox": {
        "min": 187,
        "max": 7611,
        "median": 358.5,
        "p95": 2364.4,
        "p99": 3658.6
      },
      "messages-section-docket-inbox": {
        "min": 369,
        "max": 9381,
        "median": 839,
        "p95": 2675.6,
        "p99": 4960
      },
      "blocked-cases-report": {
        "min": 504,
        "max": 9535,
        "median": 1593.5,
        "p95": 4208.8,
        "p99": 6586.4
      },
      "case-inventory-report": {
        "min": 178,
        "max": 7425,
        "median": 348.5,
        "p95": 2333.8,
        "p99": 4016
      },
      "messages-section-docket-sent": {
        "min": 770,
        "max": 9970,
        "median": 4052,
        "p95": 7455.1,
        "p99": 8869.5
      },
      "document-qc-section-inbox": {
        "min": 730,
        "max": 9991,
        "median": 3330,
        "p95": 6740.2,
        "p99": 8790.7
      },
      "document-qc-section-outbox": {
        "min": 2090,
        "max": 10030,
        "median": 8629,
        "p95": 9914.6,
        "p99": 9996
      }
    },
    "counters": {
      "code 200 on messages-user-inbox": 2143,
      "code 200 on document-qc-user-outbox": 4268,
      "code 200 on messages-user-completed": 2110,
      "code 200 on case-advanced-search": 2144,
      "code 200 on pending-items": 2104,
      "code 200 on case-deadline-search": 2180,
      "code 200 on practitioner-by-name": 2070,
      "code 200 on case-deadlines": 2141,
      "code 200 on messages-user-sent": 2113,
      "code 200 on document-qc-user-inbox": 2092,
      "code 200 on messages-section-docket-inbox": 2177,
      "code 200 on blocked-cases-report": 2056,
      "code 200 on case-inventory-report": 2136,
      "code 200 on messages-section-docket-sent": 2056,
      "code 200 on document-qc-section-inbox": 2127,
      "code 200 on document-qc-section-outbox": 551
    },
    "scenariosAvoided": 0,
    "phases": [
      {
        "duration": 300,
        "arrivalRate": 180,
        "name": "Sustained load"
      }
    ]
  }
```

![Screen Shot 2021-08-30 at 12 51 26 PM](https://user-images.githubusercontent.com/1868782/131375431-e4eff754-0473-455a-99ed-c6cff670b0a3.png)

**Comment by mmarcotte** [comment]
Thanks for all the hard work on this @sutt0n and @codyseibert. This will be a sweet addition right into the codebase, and it looks much more straightforward than the gatling solution we had been using. 

Here's my feedback thus far:

- Please add `tokens.csv` to `.gitignore`. I would hate for someone to inadvertently commit and push that file to github.
- Please change `DEFAULT_PASS` to `DEFAULT_ACCOUNT_PASS` so it mirrors other patterns in the codebase.
- Please add documentation for how to change X, Y, Z, XX, and YY from the Acceptance Criteria
