### ISSUE TITLE
Opinion Search: User Research

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8035]
As a DAWSON team member, I would like to understand user expectations around Opinion search so that I can better develop a user-friendly system.

## Pre-Conditions
-Opinion search is turned on in the court's MIG environment

## Acceptance Criteria
All Court users can provide usability feedback
Targeted usability testing is performed with a small group of users in the Court's prod environment
Results of the study are documented
User stories from results are added to the backlog

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Create research plan: [Opinion Search (internal) - Research Plan](https://docs.google.com/document/d/1gBztXMhQijjKYPGM2LMPAYwL7x8JIBnjw6cx2qNj9PU/edit?usp=sharing) 
- [ ] Update Opinion search UI (for testing) 
    - [ ] Design search UI 
    - [ ] Implement UI to testable environment - [#8880](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8880)
- [ ] Recruit and schedule participants 
- [ ] Research studies 
- [ ] Analyze and present findings
## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
[https://app.zenhub.com/files/152320868/80822b85-7164-4ed5-8dc7-91c29f975180/download](https://app.zenhub.com/files/152320868/80822b85-7164-4ed5-8dc7-91c29f975180/download)
