### ISSUE TITLE
Opinion Search: UI Fix

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8048]
As a user of Opinion search, I would like the fields to display in a more organized manner so I can more easily use Opinion search.

The current UI for Opinion search has been changed over the course of making multiple fixes for browser compatibility to support Order search; we need to make some adjustments to the UI to reorganize the fields given the current display code.

## Acceptance Criteria
- Opinion search input fields and spacing are organized in a manner more similar to the current Order search fields
- Court User is aware that they can search for exact matches

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
- [x] Convert object with keys to array of selected opinion types - mob ustaxcourt/ef-cms-flexion#8931
- [x] Mobile UI - mob ustaxcourt/ef-cms-flexion#8931
- [x] Check all boxes by default when navigating to opinion search page - mob ustaxcourt/ef-cms-flexion#8932
- [x] Change ES to query using eventCode instead of documentType ustaxcourt/ef-cms-flexion#8936
- [x] Add object to entity constants that helps maintain selected opinion types for search (to avoid hardcoded strings) - mob ustaxcourt/ef-cms-flexion#8936
- [x] Update integration tests ustaxcourt/ef-cms-flexion#8936
- [x] Update to opinionTypes for public search ustaxcourt/ef-cms-flexion#8936

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
### Updated Opinion UI 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/9a959e8c-4ca8-4675-a68a-c6b071d4b224)

**Opinion Type** 
* should support multi-select of checkboxes

**Comment by mariahkannenberg** [comment]
Blocked - Failed to migrate. Possibly linked to the same issue w/PK-outbox...

To unblock, @mmarcotte to look into it.

**Comment by ttlenard** [comment]
I think the UI looks great! I checked on mobile as well.
