### ISSUE TITLE
Admissions Clerk: Prevent changing practitioner employer field if practitioner is associated with Open cases

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8050]
As an Admissions Clerk, in order to prevent a docket clerk from having issues with editing Counsel (Private and IRS) correctly, I need to be prevented from switching the employer field while editing a practitioner if the practitioner is associated with Open cases.

## Pre-Conditions
A practitioner has switched employers 
Ex: IRS Attorney switches employers and moves to Private
Ex: Private Practitioner switches employers and moves to IRS

## Acceptance Criteria

- Admissions clerk is unable to switch a practitioners employer if the practitioner is associated with one or more active cases (if the cases are closed, it does not matter)
- Admissions Clerk can switch a practitioners employer if the practitioner is **not** associated with any active cases (if the cases are closed, it does not matter)
- If Practitioner is moving employment from Private to IRS or DOJ (or vice versa), Firm name of the private practice needs to be removed

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks

- Need to confirm that if Practitioner is associated with a closed case, that it would be OK to switch employers. If not ok, do they have to withdraw from the case? This is a business question to the Court.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment
