### ISSUE TITLE
Court: Standalone Remote Trial Sessions - Creation

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8056]
**As a Court user, I would like to be able to create Standalone Remote Trial sessions so that I can accommodate calendaring of remote trials on an as-needed basis.**

As the Court moves into a new era of remote and in-person sessions, we are also going to have "standalone remote trial sessions" that will not follow the normal calendaring process.  These are sessions that are scheduled **without** any cases on them and cases can be added on an ad hoc basis when a petitioner requests to have their case converted to remote.  Please note these "standalone remote trial sessions" are different than a remote session that is scheduled under the normal procedures but will be held remotely. 

Currently, when all cases assigned to a trial session are dispositioned via settlement, trial, or any other means, that trial session will automatically close, removing the possibility of adding more cases to that session.

We would like the ability to keep a specific type of session open after all cases have received a disposition, either proactively (for example, removing or modifying the automatic closure logic for these sessions in specific) or reactively (for example, requiring user confirmation on the session closure when the last open case has received a disposition).  

Desired functionality for these sessions is covered in ustaxcourt/ef-cms#8061

## Acceptance Criteria
(Note: AC should include non-standard testing, deployment, documentation or security requirements)
* User roles that can currently create Trial Sessions can create a Standalone Remote Trial Session
* Standalone Remote Trial Sessions are created with no cases assigned
* Standalone Remote Trial Sessions have no Trial Location value or they have a location of "Remote"
* Standalone Remote Trial Sessions behave as Trial Sessions with a Proceeding Type of "Remote" in all other respects, including data needed at the time of creation
* Deploy alongside ustaxcourt/ef-cms#8061

## Tasks
- [x] Update AddTrialSession to include session type radio buttons - mob ustaxcourt/ef-cms-flexion#8950
    - [x] Location-based selected by default
- [x] Add Standalone Remote Trial session UI - mob ustaxcourt/ef-cms-flexion#8956
- [x] Update Trial Session entity- mob ustaxcourt/ef-cms-flexion#8957
- [x] Update/create submit interactor - mob
    - [x] Session is created with status ‘OPEN’ ustaxcourt/ef-cms-flexion#8959
    - [x] Session is created with proceeding type 'Remote' (and all requirements for remote proceeding) - mob ustaxcourt/ef-cms-flexion#8963
- [x] Session displays in Trial Session/Open with location of “Standalone Remote” ustaxcourt/ef-cms-flexion#8959
- [x] Update Trial Session detail for standalone sessions  ustaxcourt/ef-cms-flexion#8963
    - [x] Location is “Standalone Remote"
    - [x] Print button should display
    - [x] If start date is in the future, display “Edit”
    - [x] If start day is today or in the past, do NOT show edit button
- [x] Migration for sessionScope - ustaxcourt/ef-cms-flexion#8966
- [x] Remove maxCases from trial session detail?  ustaxcourt/ef-cms-flexion#8963
- [x] UX feedback (see comments below) - mob ustaxcourt/ef-cms-flexion#8971

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
#### Notes 

**What is the purpose of a “standalone remote trial session”?**
    - Petitioners can elect to do remote trial - would submit a motion 
    - Remote session has a date - 3 set for winter already 
    - Need to add cases at any time before the session date 
    -  Cases will come and go from this session and the session cannot automatically close when there are no cases 
    - Needs to remain open until after the date of the session has passed 
    - Not bound by any location 
    - Start at 1pm ET 
    - Regular, small session types only but other options
    - Has assigned Judge, same as current trial sessions


- How is this different from Special/ Motion/Hearing 
    - standalone remote is similar to these functionally, doesn’t need to be set, doesn’t have eligible cases, is status “Open” upon creation 
    - Special/Motion/hearing sessions do close automatically when there are no more cases 
    - Special/Motion/Hearing has a trial location 

**What is the current workaround (if there is one)?**
- They are just waiting to add the session until they have a case 
- There is still a risk that the session will automatically close if the last case is removed.

**Comment by klohman** [comment]
### Create Trial Session UI

#### Session scope 
* New datapoint to identify a session 

**Location-based** 
* selected by default 
* This is the session scope for all trial sessions other than Standalone Remote session (aka all of our current sessions) 
    * Includes all in person or remote sessions that have a trial location identified 
* If selected,  display the current Create Trial Session form 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/de88259b-0dd4-4951-8351-82475fe73606)

**Standalone Remote**
* New type of trial session
* If selected, display updated Create Trial session form 
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/f4e9e06a-567d-42b3-9846-896139d43012)

#### Add Session 
On click of add session button:

**Location-based**
* No change to current functionality 

**Standalone Remote** 
* Session is created with the status of “OPEN” 
    * Similar to how Special sessions are treated currently 
* Session does not automatically close when there are no cases 
* Session displays on Trial Sessions > Open tab with location of “Standalone Remote” 


![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/5b8bdc75-f0b7-4a5d-86b7-00167c6a79b8)


## Trial Session Detail - Standalone Remote Session 
* location displays as "Standalone Remote" 
* Print button displays
* if start date is in the future, display "Edit" button; if start date = current date or past, hide Edit button 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/0ee241ee-df70-47a5-9f9b-a7acf033bd23)

**Comment by klohman** [comment]
### 8896 Test Cases 

#### 1) Petitions clerk adds location-based trial session (Regular, Small, Hybrid) 
* Login as petitions clerk 
* Go to Trial Sessions 
* Click Add Trial Session button 
* Session scope = location-based 
* Session type = Regular / Small / Hybrid 
* Complete form
* Save 
Expected results
On Create Trial Session form 
- [ ] Location based is selected by default on form
On Save (existing functionality)
- [ ] Trial session is saved and displays in New tab 
- [ ] Trial session detail displays eligible cases 
- [ ] Trial session displays “Set Calendar” option


#### 2) Petitions clerk adds location-based trial session (Special, Motion/Hearing)
* Login as petitions clerk 
* Go to Trial Sessions 
* Click Add Trial Session button 
* Session scope = location-based 
* Session type = Special  / Motion/Hearing
* Complete form
* Save 
Expected results
On Create Trial Session form 
- [ ] Location based is selected by default on form
On Save (existing functionality)
- [ ] Trial session is saved and displays in Open tab 
- [ ] Trial session detail does not have eligible cases  
- [ ] Trial session does not display “Set Calendar” option

#### 3) Petitions clerk adds standalone remote trial sessions 
* Login as petitions clerk 
* Go to Trial Sessions 
* Click Add Trial Session button 
* Session scope = Standalone Remote 
* Complete form
* Save 
Expected results
On select of Standalone Remote sessions scope: 
- [ ] updated form options display
On Save 
- [ ] Trial session is saved and displays in Open tab 
- [ ] Trial session detail does not have eligible cases  
- [ ] Trial session does not display “Set Calendar” option

#### 4) Petitions clerk adds standalone remote trial sessions and views trial sessions detail (start date in future)
* Scenario 3 
* Go to Trial Sessions > Open
* Click Standalone Remote link 
Expected results 
- [ ] app routes to Trial Session Detail 
- [ ] Standalone Remote displays as location
- [ ] Print button displays 
- [ ] Edit button displays 

#### 5) Petitions clerk adds standalone remote trial sessions and views trial sessions detail (start date in past)
* Scenario 3 
* Go to Trial Sessions > Open
* Click Standalone Remote link 
Expected results 
- [ ] app routes to Trial Session Detail 
- [ ] Standalone Remote displays as location
- [ ] Print button displays 
- [ ] Edit button does not display

#### 6) ~~Tech Lead turns Standalone Remote functionality off~~ (AC removed - no longer needed)
* Tech lead turns Standalone Remote functionality off
* Log in as a petitions clerk
* Go to Trial Sessions 
* Click Add Trial Session button 
* Session scope area of the form is not visible to the user
* Session type = Regular / Small / Hybrid / Special / Hearing/Motion options available. 
* Select Regular
* Complete form
* Save 
Expected results
On Create Trial Session form 
- [ ] Session scope area is NOT present to the user. They will not see Location based of Standalone Remote Radio buttons
On Save (existing functionality)
- [ ] Trial session is saved and displays in New tab 
- [ ] Trial session detail displays eligible cases 
- [ ] Trial session displays “Set Calendar” option

**Comment by klohman** [comment]
## UX Review

* Standalone session time is showing as 10:00 am ET on session detail screen. All standalone remote sessions should be 1 pm ET (can probably hard card this)
![Screen Shot 2021-09-22 at 10.18.15 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/8677fdb5-5b73-49b3-aca8-e20a5584a651)


* I got an error when trying to create a Standalone session. It may be related to required fields. For this type of session, the optional fields are not required and we should be able to create the session without completing all of them (same as with Special sessions). 
![Add-a-trial-session-U-S-Tax-Court.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/ea63c51d-5ca0-4a33-b399-b2ab195f68fd)

![Screen Shot 2021-09-22 at 10.23.03 AM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/4c399f8c-88dd-42ce-b6b0-878a3e65c36c)

**Comment by rachelschneiderman** [comment]
This story is ready for PO review but it can't be deployed to `ustaxcourt:migration` until Batch 9 is wrapped up. Therefore, marking it as blocked for now.

**Comment by mariahkannenberg** [comment]
Thanks @rachelschneiderman ! I'm going to move it to the blocked column!
