### ISSUE TITLE
Opinion Search: Associate Judge to Bench Opinion

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8060]
As a user of Opinion search, I would like to be able to filter my opinion search by Judge so that I can see the most relevant results.

Currently, bench opinions are not associated with the judge that signed the Order of Service of Transcript (OST) associated with the bench opinion. We need to be able to associate the correct judge to the opinion in DAWSON .

## Acceptance Criteria
* Bench opinions are associated to the judge that signs the OST associated with the bench opinion
* The judge for a given bench opinion is displayed on the Opinion Search Results display in the "Judge" column
* Filtering an Opinion search by judge will return the appropriate bench opinions
* Filtering an Opinion search by judge and another filter will return the appropriate bench opinions

## IRS API Considerations
Do these changes impact the IRS API?

## Security Considerations
 - [ ] Does this work make you nervous about privacy or security?
 - [ ] Does this work make major changes to the system?
 - [ ] Does this work implement new authentication or security controls?
 - [ ] Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Tasks
ustaxcourt/ef-cms-flexion#9015

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
## 8918 Test Cases 

#### 1) Court user searches using Opinion search and sees OST opinions in results with associated judge displayed 
* Create, save, and serve OST 1 
    * Judge = Buch  
* Create save, and serve OST 2 
    * Judge = Ashford 
* Search for 
    * Opinion type = OST 
Expected results 
- [x] OST 1 returns in results with Judge Buch displayed in judge column 
- [x] OST 2 returns in results with Judge Ashford displayed in judge column 

#### 2) Court user searches by Bench Opinion and judge using Opinion search and sees matching bench opinions in results 
* Create, save, and serve OST 1 
    * Judge = Buch  
* Create save, and serve OST 2 
    * Judge = Ashford 
* Create save, and serve OST 3
    * Judge = Ashford 
* Go to opinion search 
* Search for 
    * Opinion type = OST 
    * Judge = Ashford
Expected results 
- [x] OST 1 does not display in results 
- [x] OST 2 displays in results 
- [x] OST 3 displays in results

**Comment by rosiehsmith** [comment]
To quote, @rachelschneiderman on story ustaxcourt/ef-cms#8056 - "This story is ready for PO review but it can't be deployed to ustaxcourt:migration until Batch 9 is wrapped up. Therefore, marking it as blocked for now."
