### ISSUE TITLE
Standalone Remote Trial Sessions - Functionality

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8061]
**As a Court user, I would like to be able to use Standalone Remote Trial sessions so that I can accommodate calendaring of remote trials on an as-needed basis.**

As the Court moves into a new era of remote and in-person sessions, we are also going to have "standalone remote trial sessions" that will not follow the normal calendaring process.  These are sessions that are scheduled **without** any cases on them and cases can be added on an ad hoc basis when a petitioner requests to have their case converted to remote.  Please note these "standalone remote trial sessions" are different than a remote session that is scheduled under the normal procedures but will be held remotely. 

Currently, when all cases assigned to a trial session are dispositioned via settlement, trial, or any other means, that trial session will automatically close, removing the possibility of adding more cases to that session.

We would like the ability to keep a specific type of session open after all cases have received a disposition, either proactively (for example, removing or modifying the automatic closure logic for these sessions in specific) or reactively (for example, requiring user confirmation on the session closure when the last open case has received a disposition).  

Creation of these sessions is covered in ustaxcourt/ef-cms#8056

## Pre-Conditions
ustaxcourt/ef-cms#8056 must be completed first.

## Acceptance Criteria
(Note: AC should include non-standard testing, deployment, documentation or security requirements)
* Standalone Remote Trial Sessions can have cases added on an ad hoc basis after creation
* Standalone Remote Trial Sessions do not automatically close when no cases remain on the session for disposition
* Standalone Remote Trial Sessions can be manually closed by docket clerks when no cases remain on the session for disposition
* Standalone Remote Trial Sessions behave as Trial Sessions with a Proceeding Type of "Remote" in all other respects
* Deploy alongside ustaxcourt/ef-cms#8056

## Tasks
- [x] Edit standalone trial session
    - [x] UI - Tom
- [x] Close Trial Session
    - [x] Modal to display close button - Tom
    - [ ] update logic on click of close (Consider using `isClosed` flag or method on TrialSession entity to get status) - Tom
    - [x] on click of cancel
- [x] Add to Trial/Hearing
    - [x] Dropdown formatting - Tom
- [x] Deleting a standalone trial session- Not necessary 
        (https://flexion.slack.com/archives/CHMLA049H/p1632240639186100)
- [x] Add unit tests - Mrinalini, Rosie
- [x] Add integration test - Mrinalini, Rosie
- [x] Setup proxy and lambda for backend functionality - Mrinalini, Rosie
- [x] Address feedback
  - [x] Edit screen should not include option to select Session scope - Rosie
  - [x] Remote sessions should display at the top of Select trial session list
  - [x] Trial date is not populating for standalon remote session on trial card or hearing card
  - [x] Some trial sessions are not displaying in the add to trial dropdown consistently. It may have to do with adding and then removing cases from these sessions.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios to meet all acceptance criteria have been written
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by klohman** [comment]
@JessicaMarine @cholly75 Question on 8919 Standalone Remote Trial Session 

- Can cases be added to this session for hearing? 
- We do not automatically generate a Notice of Trial when a case is manually added to an Open trial session. Should we auto-generate this Notice for the Standalone Remote sessions?

**Comment by JessicaMarine** [comment]
@klohman 
1. yes, they should be able to add cases for hearing to these sessions.
2. No, there should not be any notices auto-generated with respect to these sessions.

**Comment by klohman** [comment]
## Editing Standalone Remote session

* on click of Edit button from the Trial session detail screen, route to Edit Trial Session form (Standalone Remote)

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/79d758e6-da80-4f7f-8701-6acd727241a6)

## Add to Trial / Set for Hearing modals
* Session displays in Select trial session dropdown in Add to Trial modal 
* Session displays in Select trial session dropdown in Set for Hearing modal 
* Format is same as other trial sessions : Standalone Remote [start date] [(session type initial)]
![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/1ba1d1e2-ccc0-4ce6-adf3-45aa96ea888f)


#### Closing a Standalone Remote session
* Standalone remote sessions do not automatically close  

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/e8ed8f05-e170-48ad-954b-67203b95df77)

**“Close Session” button**
display button only if all of the follow is true: 
* Start date = current date or past date 
* No open cases are on the session 

**On click of Close Session**
* display confirmation modal 


#### Close session modal 

![image.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/a56160aa-6aca-4778-bbae-af4040d45d3a)

**On click of No, Cancel**
*  modal closes and session remains open 

**On click of Yes, Close session**
*modal closes 
* session state changes to Closed 
* app routes to Trial Sessions screen default with success message displayed : “Trial session closed.”

**Comment by klohman** [comment]
## 8919 Test Cases 


#### 1) Petitions/docket clerk edits Standalone Remote session 
* Login as petitions or docket clerk 
* Create Standalone Session 
* Go to Trial Session > Open
* Click Standalone Remote session link
* Update information 
* Save 
Expected results 
On click of Edit 
- [x] app routes to Edit Trial Session form 
- [x] form displays field for Standalone Remote session (per design)
On click of Save
- [x] App routes back to Trial Session Detail 
- [x] Updated information displays 

#### 2) Petitions/docket clerk adds case to standalone remote trial session 
* Login as petitions or docket clerk 
* Create Standalone Remote session 
* Go to Case (not Calendared)
* Click Case Information tab
* Click Add to Trial 
* Select “All Locations” 
* Select Standalone Remote session from trial session dropdown
* Click Add Case 
Expected results
On Add to Trial modal 
- [x] Standalone Remote session displays in trial session dropdown 
On Add Case 
- [x] case displays as open case on Standalone Remote trial session 
- [x] Case displays as Calendared on Case Information > Trial card 
- [x] Case status updates to Calendared 

#### 3) Docket clerk adds case as hearing to standalone remote trial session 
* Login as docket clerk 
* Create Standalone Remote session 
* Go to Case (not Calendared)
* Click Case Information tab
* Click Set for Hearing 
* Select “All Locations” 
* Select Standalone Remote session from trial session dropdown
* Click Add Case 
Expected results
On Set for Hearing modal 
- [x] Standalone Remote session displays in trial session dropdown 
On Add Case 
- [x] case displays as open case on Standalone Remote trial session 
- [x] Case displays as Set for Hearing on Hearings card 
- [x] Case status does not change 


#### 4) Petitions/docket clerk removes the last case from the standalone remote session and the session does not automatically close 
* Login as petitions/docket clerk 
* Go to Standalone Remote session 
    * Session has one open case 
* Click docket number link for open case 
* Remove from session 
Expected results 
- [x] case is removed from session 
- [x] Standalone Remote session status remains Open


#### 5) Petitions/docket clerk cannot close session before the start date 
* Login as petitions/docket clerk 
* Go to Standalone Remote session 
    * Session has no open cases 
    * Session start date is in the future 
* Expected results 
- [x] Close session button does not display

#### 7) Petitions/docket clerk cannot close session with open cases 
* Login as petitions/docket clerk 
* Go to Standalone Remote session 
    * Session has an open cases 
    * Start date is not in the future
* Expected results 
- [x] Close session button does not display

#### 8) Petitions/docket clerk closes session 
* Login as petitions/docket clerk 
* Go to Standalone Remote session 
    * Session has no open cases 
    * Start date is not in the future
* Click Close Session button
* Click Yes, Close Session button
Expected results 
- [x] Close Session button displays on Trial session detail screen 
On click of Close Session button
- [x] confirmation modal displays 
On click of Yes, Close Session 
- [x] app routes to Trial Session > Open tab 
- [x] Standalone Remote session status updates to Closed 
- [x] Standalone Remote session displays in Trial Sessions > Closed tab

**Comment by klohman** [comment]
@cholly75 Clarifying question on last AC: Ability for the court to turn on or off in production as desired after deployment. 

Do we expect that this functionality would be turned off only if there are no existing standalone remote sessions open? Is the "turning off" portion more related to turning off the ability to create any new standalone remote sessions, or do we need to address more than that?

**Comment by klohman** [comment]
Blocked until 8896 is complete

**Comment by cholly75** [comment]
@klohman No, this AC was only intended to put this feature behind a "feature flag" in case it was done and deployed before the court was ready to start using it.

**Comment by mariahkannenberg** [comment]
@cholly75 If there are specific deployment/release strategy requirements, please include them in the acceptance criteria.

**Comment by cholly75** [comment]
@mariahkannenberg - Kristen and I chatted about this on Friday, I've removed the requirements from this and its companion story. Are there any other blocking issues for this one, or is it just blocked because we need the companion story done first (which makes sense)?

**Comment by klohman** [comment]
> @mariahkannenberg - Kristen and I chatted about this on Friday, I've removed the requirements from this and its companion story. Are there any other blocking issues for this one, or is it just blocked because we need the companion story done first (which makes sense)?

@cholly75 @mariahkannenberg I added the blocked to this because 8896 needs to be done first. I don't believe anything else is blocking this.

**Comment by klohman** [comment]
#### Test 1) 
* Edit screen should not include option to select **Session scope** 
![Screen Shot 2021-10-11 at 2.57.03 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/247d19bb-0a6e-4618-84da-161e91f96565)

#### Test 2) 
* Remote sessions should display at top of Select trial session list 
![Screen Shot 2021-10-11 at 3.01.47 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/61c1764e-2903-463c-9340-084ae4572e03)

* Trial date is not populating for standalone remote session on Trial Card or Hearing Card 
![Screen Shot 2021-10-11 at 3.05.31 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/923e7296-e992-461a-90fc-a78dea460331)

* Some trial sessions are not displaying in the add to trial dropdown consistently. It may have to do with adding and then removing cases from these sessions. I added and removed cases from session on 10/4 and it no longer displays in the dropdown, although it displays as Open on the Trial Sessions screen. 
![Screen Shot 2021-10-11 at 3.19.02 PM.png](https://images.zenhubusercontent.com/5bd7271508843955cc24d3d0/79a73f35-8e0e-4a9a-a3fb-0903a30e69d7)

**Comment by cholly75** [comment]
@TomElliottFlexion @mrinsin - looks like the placement of the standalone sessions is off by a couple states - should be at top of the menu:

![SRTSessionMenu.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/e3bd9d07-c8ca-4d1c-bfe3-0b4e17ff1726)

Tenille and I are seeing this today, but I would swear on the grave of a loved one that I didn't see this yesterday. Me am confused.
