### ISSUE TITLE
Seal and unseal cases and documents - User Research

### ISSUE THREAD

**Issue by klohman** [ustaxcourt/ef-cms#8090]
As a DAWSON team member, so that the sealing/unsealing feature meets user needs, I need to understand user workflows and usability concerns related to sealing and unsealing cases and documents.

## Pre-Conditions
Docket clerks are available for user interviews. 

## Acceptance Criteria
* Results of the study are documented
* User stories from results are added to the backlog

**Research Questions**
* What are user expectations when sealing/unsealing cases and documents? 
* How does sealing/unsealing cases and documents integrate into a larger workflow? 
* How have users done this in the past?
* What challenges and opportunities are there with this process?  

## Notes
* Sealing cases is the only existing functionality 
  * https://github.com/flexion/ef-cms/issues/3922
  * https://github.com/flexion/ef-cms/issues/7199
  
* Unsealing cases and document sealing are upcoming features
  * https://github.com/flexion/ef-cms/issues/4251
  * https://github.com/flexion/ef-cms/issues/4252

## Tasks
 - [x] Create research plan - [Interview Research Plan (Final) ](https://docs.google.com/document/d/1Kx33vIlerGeTJr7X7RvVeiSDvcMtVa8SCaC5U3NAOXk/edit?usp=sharing)
 - [x] Recruit and schedule participants 
 - [x] Conduct Interviews
 - [x] Synthesize Data
 - [x] Create Presentation [[Draft Report](https://docs.google.com/document/d/1Z1fyXoSuw6msdSUVXTNywSYJsgbiUolnprZ8VDONnpo/edit?usp=sharing)] [[Final Report](https://drive.google.com/file/d/1MhGcaIpT7TDfEO1t9HoZrQl1iv6F8lvX/view?usp=sharing)]
 - [x] Present Findings

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be ready for grooming.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
User stories from research (in order of user priority):
* [Unseal a case](https://app.zenhub.com/workspace/o/flexion/ef-cms/issues/4251)
* [Seal/Unseal document from all non-court users](https://app.zenhub.com/workspace/o/flexion/ef-cms/issues/9147)
* [Seal/Unseal document from the public
](https://app.zenhub.com/workspace/o/flexion/ef-cms/issues/4252)
* [ Clarify to users - permanent vs temporary sealing status](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9195)
* [Ensure filing entry of appearance is accessible to parties in case when the case is permanently sealed](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9196)
* [Provide a solution for maintaining the sealing status of individual documents once sealing/unsealing becomes available for documents](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9197)

Non-sealing stories:
* [Optimize and standardize notes section - currently not meeting users' needs](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9198)
* [Make it easier for clerks to manage inboxes of absent clerks](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9199)
* [Prioritization of inbox items](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9200)
* [Consolidation of cases](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/3820)
* [Ability to redact cover pages](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9201)
* [Consider how to make redaction process easier for clerks - whistleblower](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9202)
* [Ability to track redactions](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9203)
* [Investigate what it is about the user experience of working remotely that makes people want to use paper](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9204)
* [Enhance search and browse experience of tabbing structure](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/9205)
