### ISSUE TITLE
Petitions: Auto-Generate Order for Filing Fee

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8091]
As a Petitions clerk, so that I may easily generate needed documentation , I need to have DAWSON generate a draft of an Order for Filing Fee automatically when I indicate that one is needed for a case.

Currently, when a Petitions Clerk indicates that an Order For Filing Fee is needed for a case, they check the appropriate box at the time of paper Petition entry or QC of eFiled petition. After the Petition is served, they must then create the Order via copying and pasting content from outside DAWSON into a blank Order, after which DAWSON adds the appropriate header, caption/docket information, and title to the first page.

If the clerk indicates an Order for Filing Fee is needed during petition entry, then at the time the Petition is served we would like this Order to be automatically generated as a draft order in the case, at which point the clerk can review, edit, delete, apply a signature, and add as a docket entry through normal existing process. The generated draft will need to generate some content dynamically based on information present during case creation.

## Pre-Conditions
See 8993 for UX specs: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8993

## Acceptance Criteria
* If the Order for Filing Fee box is checked when the clerk serves the Petition, an Order is generated as a Draft document at the time the Petition is served.
* The generated order is created with the standard Order format (Case caption/docket number at the top followed by title and text of the Order)
* The title of the generated order is "ORDER"
* The body content is identical to the attached document, excepting one value:
[https://app.zenhub.com/files/152320868/9b24ad5f-2d54-4cf1-90b7-368a2d6a0354/download](https://app.zenhub.com/files/152320868/9b24ad5f-2d54-4cf1-90b7-368a2d6a0354/download)
   - The value for the [TODAY_PLUS_60] token in the content is derived from the current date at the time of order generation and counting 60 consecutive calendar days hence. If the resulting date falls on a Saturday, Sunday, or federal Holiday then the resulting date should instead be changed to the next weekday that is not a Holiday.
   - Note that this value is used twice in the body content and should be the same value in both places.
* The generated draft order should not auto-apply the signature of the Chief Judge. The clerk will do this.
* The generated draft order can be interacted with in the same manner as any other Draft order from the Drafts view (edit, 
   delete, apply a signature, and add as a docket entry).

## Notes
* If the value of [TODAY_PLUS_60] cannot be parsed by the system to determine if it is an eligible weekday as per the AC, then the clerks will manually have to enter the date. We would replace this token with with [ENTER_DATE] in a red font or similar callout to let them know that they need to manually enter.
* Order for Filing fee is Event Code "OF"
* https://github.com/18F/us-federal-holidays

## Tasks
- [x] Update interactor to generate draft order for filing fee - Rosie, Rachel https://github.com/ustaxcourt/ef-cms/pull/1982
- [x] Set payment due date as TODAY_PLUS_60 - Rosie https://github.com/ustaxcourt/ef-cms/pull/1982
- [x] Update alert warning in 'Review and Serve' screen - Rosie, Rachel https://github.com/ustaxcourt/ef-cms/pull/1982
- [x] Add new integration test - Mob https://github.com/ustaxcourt/ef-cms/pull/1982
- [x] Create reusable useCaseHelper to add system generated order - Rosie https://github.com/ustaxcourt/ef-cms/pull/1982
- [x] Address feedback (that Tim noticed) to remove clerk of the court's signature from the generate pdf - Tim, Rosie https://github.com/ustaxcourt/ef-cms/pull/2000 
- [x] Address feedback to not pre-populate description field for the docket entry - Tim, Rosie https://github.com/ustaxcourt/ef-cms/pull/2004

## Test Cases
* Petitions clerk starts new petition, checks box for "Order for Filing Fee" in the Case Info tab and completes all other required info and creates Case. Order is not generated. UI reflects pending order generation. Petition is served; Order is generated and appears as a Draft document attached to case.
* Petitions clerk starts new petition, checks box for "Order for Filing Fee" in the Case Info tab; checks at least one other box for a notice/order that is not currently auto-generated; completes all other required info and creates Case. Order is not generated. UI reflects pending order generation. Petition is served; Order is generated and appears as a Draft document attached to case.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be ready for grooming.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's test environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Petitions clerk starts new Paper petition, Only checks box for "Order for Filing Fee" in the Case Info tab and completes all other required info and creates Case. Order is not yet generated, but the UI reflects a pending Order generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition, STIN, and RQT under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, and select a trial location.
- Next, Select the radio button that the fee was NOT paid. This will automatically check the box for Order for Filing Fee
- Under the Orders/Notices Needed section, leave all checkboxes unchecked.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with a new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] The "Order for Filing Fee" should be below the above section header, and will be in regular font.


**2. Petitions Clerk serves the petition. Order for Filing Fee is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**3. The draft Order for Filing Fee is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [ ] On the left hand side of the page under the Drafts, you should see a new "Order" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be ORDER, etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/9b24ad5f-2d54-4cf1-90b7-368a2d6a0354/download
- [x] The date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [x] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF.

**4. Add the Order for Filing Fee as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order for Filing Fee for Paper Service" screen

Expected Results
- [x] Order for Filing Fee is added as a docket entry and shows as served
- [x] The Order Event Code is "OF" on the Docket Record
- [x] The number icon no longer appears on the Drafts tab


**5. Petitions clerk starts new Paper petition, checks boxes for multiple Orders/Notice as well as checks the box for "Order for Filing Fee" in the Case Info tab and completes all other required info and creates Case. Order for Filing Fee is not yet generated, but the UI reflects a pending Order for Filing Fee generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, and check the box for "Order to show cause".
- Leave the Trial location blank. This will ensure that the checkbox is checked for "Order Designating Place of Trial"
- Select the radio button that the fee was NOT paid. This will automatically check the box for Order for Filing Fee
- Under the Orders/Notices Needed section, select the checkbox for one or two other Orders needed, as well as the checkbox for Notice of Attachments in the nature of Evidence.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [x] On the "Review and Serve Petition" Screen, you should see a yellow warning box with 2 Section Headers.  One that states "Orders/Notices Needed" and new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [x] Some of the Orders (that have not yet had a story to be auto-created) that you selected should be under the section Header "Orders/Notices Needed" and will be in regular font.
- [x] The "Order for Filing Fee" and all other Orders/Notices that were selected that have been coded to be auto-created should be under the section header "Orders/Notices Automatically Created in Drafts After Service", and will be in regular font.


**6. Petitions Clerk serves the petition. Order for Filing Fee and all other Orders/Notices that were selected that have been coded to be auto-created   are generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [x] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there are drafts. This number should reflect the total number of draft Orders/Notices created.

**7. The draft Order for Filing Fee is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [ ] On the left hand side of the page under the Drafts, you should see a new "Order" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [x] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be ORDER, etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/9b24ad5f-2d54-4cf1-90b7-368a2d6a0354/download
- [x] The date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [x] Petitions Clerk has the ability to Edit, Delete, Add Docket Entry, or View Full PDF.

**8. Add the Order for Filing Fee as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order for Filing Fee for Paper Service" screen

Expected Results
- [x] Order for Filing Fee is added as a docket entry and shows as served
- [x] The Order Event Code is "OF" on the Docket Record
- [x] The number icon should now reflect 1 less document on the Drafts tab

**Comment by swongCO** [comment]
Updated section title verbiage to "Orders/Notices Automatically Created in Drafts After Service". See 8993 for reference.

**Comment by cholly75** [comment]
@ttlenard - FYI, the description of the order in the Draft folder will say "Order" as it's keying off the actual title of the Order in the text.

**Comment by cholly75** [comment]
OF should not have the clerk of the court's signature applied.

**Comment by cholly75** [comment]
@rosiehsmith - same question regarding clearing the description field upon adding a docket entry here as in ustaxcourt/ef-cms#8163? To prevent clerks having to clear it manually

**Comment by cholly75** [comment]
@rosiehsmith @shumway-tm - We found an issue with these notices, in that if the notice is edited/previewed in any way (or just saved from the Edit screen) then the spacing between paragraphs is lost.
