### ISSUE TITLE
Retro Improvements: Centralize location of business rules experiment

### ISSUE THREAD

**Issue by mariahkannenberg** [ustaxcourt/ef-cms#8099]
As a scrum team, we can access a central location of business rules, so that we can be confident in the domain.

Note - this story is an experiment. If it works out well, we can move forward with centralizing in this way.

## Acceptance Criteria
* A gherkin test is created covering 1-3 scenarios around the work item business rules (one Gherkin test === one scenario according to [good Gherkin test writing practices](https://automationpanda.com/2017/01/30/bdd-101-writing-good-gherkin))

## Task
Schedule 5 hours per week for engineers to ~rotate into mobbing~ collaborate with UX and Chris Holly to write gherkin tests for expected behavior for business requirements around work items
  - [ ] Complete one gherkin scenario for work items moving to "In Processed"

## Notes
* Edge cases or items that cannot be easily tested  - need to consider how to document difficult to test cases. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios to meet all acceptance criteria have been written
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] Deployed to any Flexion environment for UX Review
 - [ ] Deployed to the Court's migration environment

**Comment by mariahkannenberg** [comment]
https://cucumber.io/docs/bdd/

**Comment by mariahkannenberg** [comment]
[https://app.zenhub.com/files/152320868/336b6b5d-60c3-47fd-8819-c01c69c43da7/download](https://app.zenhub.com/files/152320868/336b6b5d-60c3-47fd-8819-c01c69c43da7/download)

**Comment by mariahkannenberg** [comment]
[https://app.zenhub.com/files/152320868/b35c88c6-9226-43dd-9430-f8122b9fd4b1/download](https://app.zenhub.com/files/152320868/b35c88c6-9226-43dd-9430-f8122b9fd4b1/download)
