### ISSUE TITLE
External Search: Turn on/off Order Search for External Users in Production Environment

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8103]
As the Court Tech Lead, so that I can control search availability for public users of DAWSON, I need the ability to toggle external Order search off and on without requiring a deployment.

## Acceptance Criteria
* Tech lead can turn order search on or off in the production environment for external users (public users, private practitioners, IRS practitioners) only without a deployment and within 30-60 min
* Users who try to access order search after the search page has loaded AND the search feature has been turned off, are notified in a way that doesn't disrupt their work or log them out

## Notes
* Functionally, this should be the same ability implemented in ustaxcourt/ef-cms#7948 with a different context (public users, private practitioners, IRS practitioners)

## Tasks
- [x] add dynamo record for non-internal order search flag  - mob ustaxcourt/ef-cms-flexion#9128
- [x] add backend to get external order search enabled (interactor, lambda, action, persistence, etc) https://github.com/flexion/ef-cms/pull/9126
- [x] use flag to toggle enable/disable of order search tab/wording for public users - mob ustaxcourt/ef-cms-flexion#9129
- [x] use flag to toggle enable/disable of order search tab/wording for external users - mob ustaxcourt/ef-cms-flexion#9131
- [x] Unskip integration tests - mob ustaxcourt/ef-cms-flexion#9132
- [x] DOD ustaxcourt/ef-cms-flexion#9125 - mob
  - [x] Rename isOrderSearchEnabled to be specific to internal https://github.com/flexion/ef-cms/pull/9125
  - [x] Refactor/clean up order search internal flag related stuff 
  - [x] Rename getOrderSearchInteractor to include internal as opposed to getExternalOrderSearchInteractor - mob ustaxcourt/ef-cms-flexion#9133
  - [x] Consider refactoring feature flag logic - mob ustaxcourt/ef-cms-flexion#9138

## Test Cases
* External search is active; public user navigates to advanced search, clicks on Orders, is able to search and retrieve results.
* External search is active; private practitioner navigates to advanced search, clicks on Orders, is able to search and retrieve results.
* External search is active; IRS practitioner navigates to advanced search, clicks on Orders, is able to search and retrieve results.
* External search is active; public user navigates to advanced search, clicks on Orders, is able to search and retrieve results. Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Order search verbiage
* External search is active; private practitioner user navigates to advanced search, clicks on Orders, is able to search and retrieve results. Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Order search verbiage
* External search is active; IRS practitioner navigates to advanced search, clicks on Orders, is able to search and retrieve results. Tech lead toggles external search inactive; user is notified/navigated to UI with inactive Order search verbiage
* External search is inactive; public user navigates to advanced search, is unable to click on Orders
* External search is inactive; private practitioner navigates to advanced search, is unable to click on Orders
* External search is inactive; IRS practitioner navigates to advanced search, is unable to click on Orders

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by rachelschneiderman** [comment]
When deploying this story on any environment, the following script needs to be run in order to setup the `external-order-search-enabled` dynamo flag:

`./scripts/setup-external-order-search-flag.sh <ENV>`

**Comment by rosiehsmith** [comment]
This script also needs to be run as we renamed the `order-search-enabled` flag to `internal-order-search-enabled` to accurately reflect what they are used for:

`sh ./scripts/rename-order-search-flag-to-internal.sh <ENV>`

**Comment by rachelschneiderman** [comment]
Per Lia:

"Order search has been temporarily disabled. Please try again later."

**Comment by rosiehsmith** [comment]
Demoed this morning 11/8 on flexion's staging environment and got the 👍  for UX review and PO review.
