### ISSUE TITLE
Order/Opinion Search: Eliminate results returned for Dockets w/ no documents

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8105]
As a search user, so that I am not presented with errors, I need to not see documents in the search results that we cannot display.

Currently, order and opinion search can return results for which we do not have the corresponding documents in DAWSON; this can be reproduced most easily by searching for either with a custom date range beginning on 5/1/86 and ending on (for example) 1/1/87. As these dockets are in the system but the attached documents are not, clicking the order or opinion returned in the search leads to an XML error (screenshot below).

This is a poor user experience and should be addressed before going live to the public with either search. The Court preference would be to eliminate search results for which we do not have documentation in the system.

## Acceptance Criteria
* User is not given the opportunity to click a results hyperlink for which we cannot display the document due to it being missing in DAWSON

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/b30344fc-98cf-418d-abc9-9caa5a685506)

## Tasks
- [x] update advancedDocumentSearch query to check for isFileAttached: true - mob ustaxcourt/ef-cms-flexion#9114

## Test Cases
* User searches for Order that is not viewable in DAWSON but exists on a docket record; order is not presented in search results.
* User searches for Opinion that is not viewable in DAWSON but exists on a docket record; opinion is not presented in search results
* User searches for Order that is viewable in DAWSON and exists on a docket record; order is presented in search results
* User searches for Opinion that is viewable in DAWSON and exists on a docket record; opinion is presented in search results

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [x] Business test scenarios have been refined to meet all acceptance criteria 
 - [x] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [x] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by rachelschneiderman** [comment]
We added `isFileAttached` to `efcms-docket-entry` index as part of this story. This change will require a reindex on all envs to take effect.
