### ISSUE TITLE
Docket Clerk: Seal an individual document from all non-Court users

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8120]
As a Docket clerk, so that I can appropriately protect the privacy of Court business, I need to be able to seal individual documents so that only Court employees can view them.

ustaxcourt/ef-cms#7164 -- back-end work to allow the sealed flag at the document level
ustaxcourt/ef-cms#7042 -- companion story to allow sealing from the public only

## Pre-Conditions:
ustaxcourt/ef-cms#7041
ustaxcourt/ef-cms#8090

## Acceptance Criteria:
* Docket Clerk has the ability to seal an individual document within a case from all users except Court employees
* When sealing the document, the Docket clerk must explicitly indicate that the document is sealed from 'all'
* If a document is "Sealed from all," in addition to it being non-viewable to the public, the parties/practitioners/IRS counsel on the case *cannot* view it. 
* Court users can view "Sealed from all" documents.
* Sealing an individual document does *not* seal the whole case.
* Docket record indicates whether or not a particular document is sealed, and to whom
* Sealing an Order from all removes it from being returned as a result in an an Order Search for everyone except Court employees
* Opinions cannot be sealed.
* Existing docket entries with "legacy seals" should be migrated to "sealed from all"

## Notes
 -[ User research report on sealing](https://drive.google.com/file/d/1MhGcaIpT7TDfEO1t9HoZrQl1iv6F8lvX/view?usp=sharing)
* What is the desired visibility on the Docket Record for a sealed document w/r/t a public view? Do we display the entry with a sealed indicator, or omit the entry entirely? --- *The former*
* Are there other exceptions to what can be sealed other than Opinions? - *no*
* Deploy alongside ustaxcourt/ef-cms#7042
* Need to test w/ IRS + IRS Superuser

## Questions:
* What should the IRS Superuser be able to see?
  * They don't log in through the UI but should be able to download sealed from external documents 

## Tasks
- [x] Update document download url endpoint - clarion mob ustaxcourt/ef-cms-flexion#9422
- [x] Update public docket record view to not display links for sealed to all docket entries - ustaxcourt/ef-cms-flexion#9423
- [x] Update advanced document search when searching as an external user ustaxcourt/ef-cms-flexion#9425
- [x] Migration
  - [x] Set `sealedTo` as 'all' (NOT public) for `isLegacySealed` docket entries - ustaxcourt/ef-cms-flexion#9424
- [x] Advanced order search results, move lock icon next to document title ustaxcourt/ef-cms-flexion#9425

## Test Cases
* Docket clerk seals document from all for a Case which is sealed; docket record indicates document is sealed to all; court employees can access sealed document and view in DAWSON; no one else can.
* Docket clerk seals document from all for a Case which is not sealed; docket record indicates document is sealed to all; court employees can access sealed document and view in DAWSON; no one else can.
* Docket clerk seals Order from all for a Case which is sealed; docket record indicates Order is sealed to all; court employees can access sealed Order and view in DAWSON; Order is not returned in Order Search results for anyone other than court employees; Order is not viewable by anyone else
* Docket clerk seals Order from all for a Case which is unsealed; docket record indicates Order is sealed to all; court employees can access sealed Order and view in DAWSON; Order is not returned in Order Search results for anyone other than court employees; Order is not viewable by anyone else

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for UX Review
 - [x] Deployed to the Court's migration environment

**Comment by swongCO** [comment]
**See ustaxcourt/ef-cms#7042 for sealing a document**
![USTC Docket Record Seal modal.jpg](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/457a0e40-adf8-4267-83a1-7eea8cf76752)

- The second option in the modal will seal the document to all but court users

**Comment by ttlenard** [comment]
**### Test Cases**

**1. Docket Clerk seals a document on a Sealed Case**
- Log in as docket clerk
- Navigate to a Sealed Case (ex: 1432-21)
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6494.
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- Select the second bullet "Seal to the public and parties of this case"
- Select "Seal"

Expected results

- [ ] The modal will close, and a red lock icon will appear next to the document name on docket index ustaxcourt/ef-cms#6494
- [ ] The far right column will now have the text "Unseal" displayed as a Red link
- [ ] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public and parties of this case"
- [ ] The red banner at the top of the screen will still be present - indicating that the entire case is sealed.

**2. Parties associated with a case cannot view "sealed to public and all parties of this case" documents in Sealed cases.** 
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the Sealed case that you used in test case ustaxcourt/ef-cms#6491.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the sealed case from Test ustaxcourt/ef-cms#6491
- Navigate to the sealed case

Expected Results
- [ ] As Petitioner, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [ ] As Participant, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [ ] As Intervenor, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [ ] As Private Practitioner, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [ ] As IRS Respondent, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6491
- [ ] The red banner at the top of the screen will be present for all of these users, indicating that the Case is sealed


**3. Public users can NOT view "sealed to public and all parties of this case" documents in a sealed case**
- As a public non-logged in user, type in the Docket # of the Sealed case you used in Test Case ustaxcourt/ef-cms#6491

Expected Results:
- [ ] You should see the "This case is sealed and not accessible to the public" message

**4. Court users can access and view documents that have been sealed to public and all parties of this case" documents in a sealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the sealed case that you used in Test case ustaxcourt/ef-cms#6491
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results
- [ ] Docket index ustaxcourt/ef-cms#6494 (or whatever document you sealed) is available as a hyperlinked document on the docket record.
- [ ] The red lock icon will appear next to the document name on the docket record.
- [ ] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [ ] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [ ] Click on the document, and you should be able to view it.

**5. Docket Clerk seals a document on an unsealed Case**
- Log in as docket clerk
- Navigate to an unsealed case in any status other than "New"
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6491.
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- Select the second bullet "Seal to the public and parties of this case"
- Select "Seal"

Expected results

- [ ] The modal will close, and a red lock icon will appear next to the document name on docket index ustaxcourt/ef-cms#6491
- [ ] The far right column will now have the text "Unseal" displayed as a Red link
- [ ] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public and parties of this case"
- [ ] The red banner that indicates that a case is sealed will NOT be present at the top of the screen.

**6. Parties associated with a case can NOT view "sealed to public and parties of this case" documents in an unsealed case.** 
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the unsealed case that you used in test case ustaxcourt/ef-cms#6494.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above from test case ustaxcourt/ef-cms#6494
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the unsealed case from Test ustaxcourt/ef-cms#6494
- Navigate to the unsealed case

Expected Results
- [ ] As Petitioner, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [ ] As Participant, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [ ] As Intervenor, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [ ] As Private Practitioner, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [ ] As IRS Respondent, you should NOT be able to view the sealed document from test case ustaxcourt/ef-cms#6494
- [ ] The red banner at the top of the screen will NOT be present on this case for any of these users

**7. Public users can NOT view "sealed to public and all parties of this case" documents in an unsealed case**
- As a public non-logged in user, type in the Docket # of the unsealed case you used in Test Case ustaxcourt/ef-cms#6494

Expected Results:
- [ ] You should see the "normal" docket record view with no links to documents (unless it is an unsealed Order, or an Unsealed Opinion - these documents will be active links)
- [ ] Lock symbol is present next to the document name for the sealed document 

**8. Court users can access and view documents that have been "sealed to public and all parties of this case" documents in an unsealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the unsealed case that you used in Test case ustaxcourt/ef-cms#6494
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results
- [ ] Docket index ustaxcourt/ef-cms#6491 (or whatever document you sealed) is available as a hyperlinked document on the docket record.
- [ ] The red lock icon will appear next to the document name on the docket record.
- [ ] When hovering over the lock icon next to the document name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [ ] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [ ] Click on the document, and you should be able to view it.


**9. Docket Clerk seals an Order on a Sealed Case**
- Log in as docket clerk
- Navigate to a Sealed Case (ex: 16543-21)
- Click the blue "Seal" link on the far right column of docket index ustaxcourt/ef-cms#6495.  (Or, of you used a different Sealed case, be sure that the document you are sealing is an Order)
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- Select the second bullet "Seal to the public and parties of this case"
- Select "Seal"

Expected results

- [ ] The modal will close, and a red lock icon will appear next to the Order name on docket index ustaxcourt/ef-cms#6495
- [ ] The far right column will now have the text "Unseal" displayed as a Red link
- [ ] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public and parties of this case"
- [ ] The red banner at the top of the screen will still be present - indicating that the entire case is sealed.

**10. Parties associated with a case can NOT view "sealed to the public and parties of this case" Orders in Sealed cases.**
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the Sealed case that you used in test case ustaxcourt/ef-cms#6497.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the sealed case from Test ustaxcourt/ef-cms#6497
- Navigate to the sealed case

Expected Results
- [ ] As Petitioner, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6497
- [ ] As Participant, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6497
- [ ] As Intervenor, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6497
- [ ] As Private Practitioner, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6497
- [ ] As IRS Respondent, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6497
- [ ] The red banner at the top of the screen will be present for all of these users, indicating that the Case is sealed


**11. Public users can NOT view sealed Orders in a sealed case**
- As a public non-logged in user, type in the Docket # of the Sealed case you used in Test Case ustaxcourt/ef-cms-flexion#9

Expected Results:
- [ ] You should see the "This case is sealed and not accessible to the public" message


**12. Court users can access and view Orders that have been "sealed to public and all parties of this case" in a sealed case.**
- Log in as a court user (ex: ADC)
- Navigate to the sealed case that you used in Test case ustaxcourt/ef-cms-flexion#9
- Be sure that you test this with multiple court user roles! (ex: ADC, Petitioners clerk, admissions clerk, Trial Clerk, Judge, Chambers, docket clerk)

Expected Results
- [ ] Docket index ustaxcourt/ef-cms#6495 (or whatever Order you sealed) is available as a hyperlinked document on the docket record.
- [ ] The red lock icon will appear next to the Order name on the docket record.
- [ ] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ] If you are logged in as any court user besides a docket clerk, you should NOT see the Seal/Unseal links on the far right column of the docket record.
- [ ] If you ARE logged in a s a docket clerk, then you SHOULD see the Seal/Unseal links on the far right column of the docket record.
- [ ] Click on the document, and you should be able to view it.

**13. Public user should not have search results returned for sealed Orders in sealed cases when using the Order search**
- Navigate to the Search screen as a non-logged in public user.
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#9 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:

- [ ] You should see either see the "No Matches found" message or the sealed Order should never appear in the search results.

**14. Private Practitioner and IRS Respondent should NOT have search results returned for "sealed to the public and parties of this case" orders in sealed cases that are associated with when using the Order Search.**
- Log in as each of these roles to perform this test: Private Practitioner, IRS Respondent
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#9 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:
- [ ] Sealed Order from Test case ustaxcourt/ef-cms-flexion#9 should NOT be available in the search results.


**15. Court users should have search results returned for "sealed to the public and parties of this case" orders in sealed cases when using the Order Search.**
- Log in as multiple court users and go through each of these steps with each user to to perform this test: (ADC, Docket, Petitions clerk, admissions clerk, trial clerk, Judge, Chambers)
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms-flexion#9 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:
- [ ] Sealed Order from Test case ustaxcourt/ef-cms-flexion#9 should be available in the search results.
- [ ] Lock symbol should be present next tot he Order Name in the Search results list
- [ ] When clicking on the Sealed Order, it should open a new tab, and the court user should be able to view the Order


**16. Docket Clerk seals an Order on a unsealed Case**
- Log in as docket clerk
- Navigate to an unsealed Case that has at least one Order on the docket record.
- Click the blue "Seal" link on the far right column of the Order.  
- A modal will pop-up asking docket clerk to confirm who to seal the document to
- Select the second bullet "Seal to the public and parties of this case"
- Select "Seal"

Expected results

- [ ] The modal will close, and a red lock icon will appear next to the Order name on docket 
- [ ] The far right column will now have the text "Unseal" displayed as a Red link
- [ ] When hovering over the lock icon next to the Order name, hover text will appear that states "Sealed to the public and parties of this case"
- [ ]  When hovering over the red "Unseal" text in the far right column, hover text will appear that states "Unseal to the public and parties of this case"
- [ ] There will be no red banner at the top of the screen on this case - indicating that the entire case is unsealed.

**17. Parties associated with a case can NOT view "sealed to the public and parties of this case"  Orders in unsealed cases.**
Preconditions for testing this one:
- Log in as a Docket Clerk
- Navigate to the unsealed case that you used in test case ustaxcourt/ef-cms#6498.
- Click on Case Information tab, and then the Parties tab
- Add a Petitioner that you have a login for (click on add party, select Petitioner, and add in user information (there won't be a place to add in an email for this petitioner, you'll have to add that in later as an admissions clerk)
- Add a Participant that you have a login for (click on add party, select participant, and add in user information (there won't be a place to add in an email for this participant, you'll have to add that in later as an admissions clerk)
- Add an Intervenor that you have a login for (click on add party, select Intervenor, and add in user information (there won't be a place to add in an email for this Intervenor, you'll have to add that in later as an admissions clerk)
- Add a Private Practitioner that you have a login for (enter in a Private Practitioners BAR # while you are on the Petitioners tab in the add counsel area to add them as counsel for Petitioners)
- Add an IRS Practitioner that you have a login for  (enter in an IRS Practitioners BAR # while you are on the Respondent tab in the add counsel area to add them as respondent counsel).

Next, log in as an Admissions Clerk
- Navigate to the same case as above
- Click on Case information tab
- Click on the Parties tab
- Click the edit link on the Petitioners tile that you just added in the steps above
- Scroll down and add in an email address that you have access to for the Petitioner that you added above.
- Do the last 2 steps for the Intervenor and the Participant

As the Petitioner, Intervenor, and Participant:
- Navigate to your email account
- You should see an email asking you to verify the account
- Verify it.

Now that you have this all set up, you can perform the test:
- Log in as the Petitioner, Participant, Intervenor, Private Practitioner, and IRS Respondent associated with the unsealed case from Test ustaxcourt/ef-cms#6498
- Navigate to the unsealed case

Expected Results
- [ ] As Petitioner, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6498.  Red lock icon should be next to the Order name. Order should not have a clickable link.
- [ ] As Participant, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6498. Red lock icon should be next to the Order name. Order should not have a clickable link.
- [ ] As Intervenor, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6498. Red lock icon should be next to the Order name. Order should not have a clickable link.
- [ ] As Private Practitioner, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6498. Red lock icon should be next to the Order name. Order should not have a clickable link.
- [ ] As IRS Respondent, you should NOT be able to view the sealed Order from test case ustaxcourt/ef-cms#6498. Red lock icon should be next to the Order name. Order should not have a clickable link.
- [ ] There will be NO red banner at the top of the screen for all of these users, indicating that the case is unsealed.

**18. Public users that are not associated with a case can NOT view sealed Orders in an unsealed case**
- As a public non-logged in user, type in the Docket # of the unsealed case you used in Test Case ustaxcourt/ef-cms#6498

Expected Results:
- [ ] You should see the red lock icon next to the Sealed Order on the docket record, and you should not be able to open the document for viewing.


**19. Court users should have search results returned for "sealed to the public and parties of this case" orders in unsealed cases when using the Order Search.**
- Log in as multiple court users and go through each of these steps with each user to to perform this test: (ADC, Docket, Petitions clerk, admissions clerk, trial clerk, Judge, Chambers)
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms#6498 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:
- [ ] Sealed Order from Test case ustaxcourt/ef-cms#6498 should be available in the search results.
- [ ] Lock symbol should be present next to the Order Name in the Search results list
- [ ] When clicking on the Sealed Order, it should open a new tab, and the court user should be able to view the Order

**20. Public user should not have search results returned for sealed Orders in unsealed cases when using the Order search**
- Navigate to the Search screen as a non-logged in public user.
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms#6498 by using all (and a combination) of the search fields:
     - Enter the Docket Number, search
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:

- [ ] You should see either see the "No Matches found" message or the sealed Order should never appear in the search results.

**21. Private Practitioner and IRS Respondent should NOT have search results returned for "sealed to the public and parties of this case" orders in unsealed cases that are associated with when using the Order Search.**
- Log in as each of these roles to perform this test: Private Practitioner, IRS Respondent
- Click on the Advanced tab in the upper right of the screen to get to the advanced Search
- Click on the Order tab
- Search for the sealed Order from test case ustaxcourt/ef-cms#6498 by using all (and a combination) of the search fields:
     - Enter the Docket Number
     - Enter the Case title/Petitioner name
     - Enter the Date that the order was served
     - Enter the Judge that signed the Order
- Click Search

Expected Results:
- [ ] Sealed Order from Test case ustaxcourt/ef-cms#6498 should NOT be available in the search results.

**Comment by liadmccabe** [comment]
@cholly75 and @ttlenard , when completing the UX Review, Sui and I noticed that there seems to be a slight delay with the tooltips over the seal locks.  It is inconsistent when we try to replicate it.  When you hover over the lock, sometimes the tooltip appears instantly and sometimes it takes a few seconds to appear.  The amount of time it took seemed to range enough that I feel a user may think that nothing happens when they hover and they may move the mouse away before the system has a chance to populate the message.  Not sure if this can be replicated on Windows (we used macs on Chrome and Safari browsers) but may want to double check this to verify. The screenshot is simply to show you what tooltip we are talking about. 


<img width="731" alt="Screen Shot 2022-02-16 at 10 56 27 AM" src="https://user-images.githubusercontent.com/91758331/154304005-bd0aa6e1-3cec-4fbd-9e6b-ebbde413f071.png">
