### ISSUE TITLE
External: Opinion Search (Public User)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8142]
As a non-Court employee, so that I can search for specific Opinions issued by the Court, I need to be able to use Opinion search.

This story will enable the existing internal Opinion search to be used by public (non-logged in) users

Deploy with ustaxcourt/ef-cms#8143

## Acceptance Criteria
* A public, non-credentialed user can access Opinion search
* Opinion Search UI for these users does not have internal "Feedback" button displayed in UI
* Clicking the Docket link from the Opinion Search results list for an unsealed case navigates the user to the public, non-logged in user view of the Docket Record in the same tab
* Clicking the Docket link from the Opinion Search results list for a sealed case navigates the user to the same "sealed case UI" seen when attempting to search for a sealed case from the Case Search
* Clicking the Document link from the Opinion Search results list navigates the user to the Opinion in a new tab
* "Coming Soon" text is removed from Opinion link in the UI
* Appropriate boilerplate text added above search UI (similar to Case search boilerplate)
* Opinion search for the public user behaves the same way it does for internal court users w/r/t filters, operators, and controls
* Sealed Opinions are never returned in search results.

## Tasks
- [x] bug fix described in ustaxcourt/ef-cms#8150 - Peter https://github.com/ustaxcourt/ef-cms/pull/1852#pullrequestreview-834543817
- [x] cypress test bug fix described in ustaxcourt/ef-cms#8150 - Rosie  https://github.com/ustaxcourt/ef-cms/pull/1852#pullrequestreview-834543817
- [x] public user search results for Bench Opinions do not display the judge name in the results list - Rosie [9285](https://github.com/flexion/ef-cms/pull/9285)
- [x] Add an integration test around public user search for Bench Opinions [9285](https://github.com/flexion/ef-cms/pull/9285) - Rosie

- [x] sealed opinions are never returned in search results. in mig, tested with docket 20237-16 and sealed the MOP in the database; result was still returned in Opinion search. [9286](https://github.com/flexion/ef-cms/pull/9286#pullrequestreview-834524541) - Mrinalini, Rosie

## Test Cases
* Public user accesses Opinion Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab
* Public user accesses Opinion Search, searches for Opinion in sealed case, Opinion is returned in results list. 
* Public user accesses Opinion Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab.
* Public user accesses Opinion Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab.
* Public user accesses Opinion Search, searches for Opinion in unsealed case, results list is returned. User clicks on link to Docket record, Docket record is opened with public UI in same tab.
* Public user access Opinion Search, searches for Opinion in sealed case, results list is returned. User clicks on link to Docket record, user is presented with "This case is sealed" UI instead of Docket record.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
The following boilerplate text  (similar to Order search but without the second bullet) should be added for opinion search:

"Anyone can search for an opinion in our system for cases filed on or after May 1, 1986.

- If you aren’t affiliated with a case, you will only see limited information about that case."

**Comment by ttlenard** [comment]
@liadmccabe Can we switch verbiage on this one as well to refer to Opinion?  Same comment made on 9211. Thanks!

**Comment by ttlenard** [comment]
**Test Cases**

**1. Public user accesses Opinion Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab**

- Public user navigates to DAWSON dashboard
- Clicks on Opinion
- Type "Premium tax Credit" in Keyword or Phrase text box and clicks "enter" on keyboard or clicks on the Search button.

Expected Results:

- [ ] Results list displays
- [ ] Click on Opinion Link and a new tab opens
- [ ] Ctrl + F in the Opinion to find the Keyword/phrase in Opinion Document
- [ ] Click on Docket # and docket record should open on same tab.  Document links in docket record should not be active, with the exception of Orders or Opinions (assuming it is not a sealed case)

**2. Public user accesses Opinion Search, searches for Opinion in sealed case, Opinion is returned in results list.**
- Public user navigates to DAWSON dashboard
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button 

Expected Results

- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ] Click on Opinion Link and new tab opens

**3. Public user accesses Opinion Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab.**
- Public user navigates to DAWSON dashboard
- Click on Opinion
- Click Search

Expected Results

- [ ]  Results list should be the most recent opinions (with the newest on top)
- [ ]  Results list should have the load more option at the bottom
- [ ]  Results list should display 100 results
- [ ]  Click on Opinion Link and new tab opens
- [ ]  Click on Docket # and docket record should open on same tab (assuming case is not sealed)
- [ ]  When clicking on docket record of sealed case, you should receive the "This case is sealed" warning.

**4. Public user accesses Opinion Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab.**
- Public user navigates to DAWSON dashboard
- Click on Opinion
- Keyword: Type "fraud" | "sanctions", can also type: “in-kind + “distribution” + “IRA”
- Filter by specific Judge (be sure to attempt the search by both active and inactive judges),
- Filter by year (adding just a start date, leaving end date empty, and also by adding start and end date)
- Filter by docket record
- Filter by Petitioner/case name
- Filter by Opinion Type
- Clicks "Enter" on keyboard

Expected Results:

- [ ]  Results list displays
- [ ]  Be sure that keyword phrase matches
- [ ]  Be sure that specific judge that is filtered on shows in results
- [ ]  Be sure that dates match correctly
- [ ]  Be sure that Petitioner/Case title matches correctly
- [ ]  Be sure that the correct Opinion Type(s) that are checked are showing in results
- [ ]  Click on Opinion Link and a new tab opens
- [ ]  Ctrl + F in the Opinion to find the Keyword/phrase in Opinion Document
- [ ]  Click on Docket # and docket record should open in same tab

**5. Public user accesses Opinion Search, searches for Opinion in unsealed case, results list is returned. User clicks on link to Docket record, Docket record is opened with public UI in same tab.**
- Public user navigates to DAWSON dashboard
- Click on Opinion
- Search for an Opinion using any of the filters
- Click on the Docket record link from the results list.

Expected results

- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are inactive links, but the Opinion is an Active link that the Public user can click on and view.
- [ ]  Click on the Opinion, and it should open for the public user to View.

**6. Public user access Opinion Search, searches for Opinion in sealed case, results list is returned. User clicks on link to Docket record, user is presented with "This case is sealed" UI instead of Docket record.**
- Public user navigates to DAWSON dashboard
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button 

Expected Results

- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ]  Click on the docket number in the results list should open in the same tab, and you should receive the "This case is sealed" notification

**Comment by ttlenard** [comment]
Note: I would like to also test this with the Public Terminal User. I'm not sure if this should be added as a test case above?

**Comment by liadmccabe** [comment]
> @liadmccabe Can we switch verbiage on this one as well to refer to Opinion? Same comment made on 9211. Thanks!

Done

**Comment by cholly75** [comment]
A couple of issues so far - 

1- the bug described in ustaxcourt/ef-cms#8150 is present
2 - public user search results for Bench Opinions do not display the judge name in the results list

Also - in mig, tested with docket 20237-16 and sealed the MOP in the database; result was still returned in Opinion search. Am adding the new AC as discussed this morning.
