### ISSUE TITLE
External: Opinion Search (Private/IRS Practitioner)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8143]
As a private or IRS practitioner, so that I can quickly find an specific issued opinion, I need to be able to search for opinions in DAWSON.

This story will enable the existing internal Opinion search to be used by private and IRS practitioners logged into DAWSON.

Deploy with ustaxcourt/ef-cms#8142

## Acceptance Criteria
* A private/IRS practitioner can access Opinion search
* Opinion Search UI for these users does not have internal "Feedback" button displayed in UI
* Clicking the Docket link from the Opinion Search results list for an unsealed case to which the private/IRS practitioner is not associated navigates the user to the public, non-logged in user view of the Docket Record in the same tab
* Clicking the Docket link from the Opinion Search results list for a sealed case to which the private/IRS practitioner is not associated navigates the user to the "sealed case UI" seen when attempting to search for a sealed case from the Case Search
* Clicking the Docket link from the Opinion Search results list for a sealed or unsealed case to which the private/IRS practitioner is associated navigates the user to the private/IRS practitioner view of the Docket Record in the same tab
* Clicking the Document link from the Opinion Search results list navigates the user to the Opinion in a new tab
* "Coming Soon" text is removed from Opinion link in the UI
* Appropriate boilerplate text added above search UI (similar to Case search boilerplate)
* Opinion search for the private/IRS practitioner behaves the same way it does for internal court users w/r/t filters, operators, and controls
* Sealed opinions are never returned in search results

## Tasks
- [ ] Verify feedback button not displayed
- [x] Clicking on docket link for unsealed, unassociated result navigates to public docket record in the same tab
- [x] Clicking on docket link for sealed, unassociated result navigates to sealed case page
- [x] Clicking on docket link for associated result navigates to non-public docket record in the same tab
- [x] Clicking on document link opens document in a new tab
- [x] Remove "Coming Soon" from opinion link
- [x] Add boilerplate as mentioned in the comments below above search UI
- [x] Uncomment relevant opinion-related tests (cause Rachel says)
- [ ] Verify opinion search behaves the same for internal and external users

## Test Cases
* Private/IRS practitioner accesses Opinion Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab
* Private/IRS practitioner accesses Opinion Search, searches for Opinion in sealed case, Opinion is returned in results list.
* Private/IRS practitioner accesses Opinion Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab.
* Private/IRS practitioner accesses Opinion Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab.
* Private/IRS practitioner accesses Opinion Search, searches for Opinion in unsealed case to which they are associated, results list is returned. User clicks on link to Docket record, Docket record is opened with practitioner UI in same tab.
* Private/IRS practitioner accesses Opinion Search, searches for Opinion in unsealed case to which they are not associated, results list is returned. User clicks on link to Docket record, Docket record is opened with public UI in same tab.
* Private/IRS practitioner access Opinion Search, searches for Opinion in sealed case to which they are associated, results list is returned. User clicks on link to Docket record, Docket record is opened with practitioner UI in the same tab.
* Private/IRS practitioner access Opinion Search, searches for Opinion in sealed case to which they are not associated, results list is returned. User clicks on link to Docket record, user is presented with "This case is sealed" UI instead of Docket record.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by liadmccabe** [comment]
The following boilerplate text  (similar to Order search but without the second bullet) should be added for opinion search:

"Anyone can search for an Opinion in our system for cases filed on or after May 1, 1986.

- If you aren’t affiliated with a case, you will only see limited information about that case."

**Comment by ttlenard** [comment]
@liadmccabe for the verbiage above - can it say "Anyone can search for an **opinion** in our system for cases filed on or after May1, 1986."  Switch out Order for Opinion???

**Comment by liadmccabe** [comment]
> @liadmccabe for the verbiage above - can it say "Anyone can search for an **opinion** in our system for cases filed on or after May1, 1986." Switch out Order for Opinion???

Good catch, That was a typo, I've adjusted it and the engineers have been made aware. Thank you!

**Comment by ttlenard** [comment]
**Test Cases**

**1. Private/IRS practitioner accesses Opinion Search, searches for keyword/phrase, results list is returned. User clicks on result, which opens in a new tab**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type "Premium tax Credit" in Keyword or Phrase text box and clicks "enter" on keyboard

Expected Results:
- [ ] Results list displays
- [ ] Click on Opinion Link and a new tab opens
- [ ] Ctrl + F in the Opinion to find the Keyword/phrase in Opinion Document
- [ ] Click on Docket # and docket record should open on same tab


_Log in as IRS Counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type "Premium tax Credit" in Keyword or Phrase text box and clicks "enter" on keyboard

Expected Results

- [ ] Results list displays
- [ ] Click on Opinion Link and a new tab opens
- [ ] Ctrl + F in the Opinion to find the Keyword/phrase in the Opinion Document
- [ ] Click on Docket # and docket record should open on same tab

**2. Private/IRS practitioner accesses Opinion Search, searches for Opinion in sealed case, Opinion is returned in results list.**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button (be sure that the Private Practitioner is NOT associated with this case)

Expected Results
- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ] Click on Opinion Link and new tab opens

_Log in as IRS Counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button (be sure that the IRS Counsel is NOT associated with this case)

Expected Results
- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ] Click on Opinion Link and new tab opens

**3. Private/IRS practitioner accesses Opinion Search, searches using no keyword/phrase. Results list is returned. User clicks on result, which opens in a new tab.**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Click Search

Expected Results
- [ ] Results list should be the most recent opinions (with the newest on top)
- [ ] Results list should have the load more option at the bottom
- [ ] Results list should display 100 results
- [ ] Click on Opinion Link and new tab opens
- [ ] Click on Docket # and docket record should open on same tab (assuming case is not sealed)
- [ ] When clicking on docket record of sealed case, you should receive the "This case is sealed" warning.

_Log in as IRS counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Click Search

Expected Results
- [ ] Results list should be the most recent opinions (with the newest on top)
- [ ] Results list should have the load more option at the bottom
- [ ] Results list should display 100 results
- [ ] Click on Opinion Link and new tab opens
- [ ] Click on Docket # and docket record should open on same tab (assuming case is not sealed)
- [ ] When clicking on docket record of sealed case, you should receive the "This case is sealed" warning.

**4. Private/IRS practitioner accesses Opinion Search, searches using combination of keyword/phrase and filters. Results list is returned. User clicks on result, which opens in a new tab.**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Keyword: Type "fraud" | "sanctions" and also try this keyword search by typing: “in-kind + “distribution” + “IRA”
- Filter by specific Judge (be sure to attempt the search by both active and inactive judges), 
- Filter by year (adding just a start date, leaving end date empty, and also by adding start and end date)
- Filter by docket record
- Filter by Petitioner/case name
- Filter by Opinion Type 
- Clicks "Enter" on keyboard

Expected Results:
- [ ] Results list displays
- [ ] Be sure that keyword phrase matches
- [ ] Be sure that specific judge that is filtered on shows in results
- [ ] Be sure that dates match correctly
- [ ] Be sure that Petitioner/Case title matches correctly
- [ ] Be sure that the correct Opinion Type(s) that are checked are showing in results
- [ ] Click on Opinion Link and a new tab opens
- [ ] Ctrl + F in the Opinion to find the Keyword/phrase in Opinion Document
- [ ] Click on Docket # and docket record should open in same tab

_Log in as IRS Counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Keyword: Type "fraud" | "sanctions" and also try this keyword search by typing: “in-kind + “distribution” + “IRA”
- Filter by specific Judge (be sure to attempt the search by both active and inactive judges), 
- Filter by year (adding just a start date, leaving end date empty, and also by adding start and end date)
- Filter by docket record
- Filter by Petitioner/case name
- Filter by Opinion Type
- Clicks "Enter" on keyboard

Expected Results:
- [ ] Results list displays
- [ ] Be sure that keyword phrase matches
- [ ] Be sure that specific judge that is filtered on shows in results
- [ ] Be sure that dates match correctly
- [ ] Be sure that Petitioner/Case title matches correctly
- [ ] Be sure that the correct Opinion Type(s) that are checked are showing in results
- [ ] Click on Opinion Link and a new tab opens
- [ ] Ctrl + F in the Opinion to find the Keyword/phrase in Opinion Document
- [ ] Click on Docket # and docket record should open in same tab

**5. Private/IRS practitioner accesses Opinion Search, searches for Opinion in unsealed case to which they are associated, results list is returned. User clicks on link to Docket record, Docket record is opened with practitioner UI in same tab.**

_Log in as Docket Clerk_
- Add Private Practitioner of your choice to a case that has an opinion on the docket record 
- Log in as Private Practitioner that was added in the previous step.
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion using any of the filters
- Click on Docket record link

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are active links that the Private Practitioner can click to view

_Log in as Docket Clerk_
- Add IRS Counsel of your choice to a case that has an opinion on the docket record
- Log in as IRS Counsel that was added in the previous step.
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion using any of the filters
- Click on Docket record link

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are active links that the IRS Counsel can click to view

**6. Private/IRS practitioner accesses Opinion Search, searches for Opinion in unsealed case to which they are not associated, results list is returned. User clicks on link to Docket record, Docket record is opened with public UI in same tab.**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion using any of the filters
- Click on the Docket record link for a case that the Private Practitioner is NOT associated with.

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are inactive links, but the Opinion is an Active link that the Private Practitioner can click on and view.
- [ ] Click on the Opinion, and it should open for the Private Practitioner to View.

_Log in as IRS Counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion using any of the filters
- Click on the Docket record link for a case that the IRS Counsel is NOT associated with.

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are inactive links, but the Opinion is an Active link that the Private Practitioner can click on and view.
- [ ] Click on the Opinion, and it should open for the IRS Counsel to View.

**7. Private/IRS practitioner access Opinion Search, searches for Opinion in sealed case to which they are associated, results list is returned. User clicks on link to Docket record, Docket record is opened with practitioner UI in the same tab.**

_Log in as Docket Clerk_
- Add Private Practitioner of your choice to a sealed case that has an opinion on the docket record 
- Log in as Private Practitioner that was added in the previous step.
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion in the sealed case using any of the filters
- Click on Docket record link

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are active links that the Private Practitioner can click to view

_Log in as Docket Clerk_
- Add IRS Counsel of your choice to a case that has an opinion on the docket record 
- Log in as IRS Counsel that was added in the previous step.
- Click on Advanced Link in upper right corner
- Click on Opinion
- Search for the Opinion in the sealed case using any of the filters
- Click on Docket record link

Expected results
- [ ] Docket record opens in same tab
- [ ] Documents on the docket record are active links that the IRS Counsel can click to view

**8. Private/IRS practitioner access Opinion Search, searches for Opinion in sealed case to which they are not associated, results list is returned. User clicks on link to Docket record, user is presented with "This case is sealed" UI instead of Docket record.**

_Log in as Private Practitioner_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button (be sure that the Private Practitioner is NOT associated with this case)

Expected Results
- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ] Click on the docket number in the results list should open in the same tab, and you should receive the "This case is sealed" notification

_Log in as IRS Counsel_
- Click on Advanced Link in upper right corner
- Click on Opinion
- Type 28246-07 in the Docket text field and click enter on your keyboard or click the Search button (be sure that the IRS Counsel is NOT associated with this case)

Expected Results
- [ ] T.C. Opinion (T.C. OPINION, Judge Goeke 134 T.C. No. 2 (An appropriate order granting resp. mot. in part & denying it in part will be issued.)) should be in the results list
- [ ] Click on the docket number in the results list should open in same tab, and you should receive the "This case is sealed" warning.
