### ISSUE TITLE
Court: Activate Motion to Proceed Remotely in DAWSON

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8144]
As a DAWSON user, so that I can accurately file or enter a Motion to Proceed Remotely, I need the changes implemented in 8684 toggled active.

The work done is ustaxcourt/ef-cms#7995 was hidden behind a feature flag at the court's request; due to miscommunication, this feature was never enabled. We would like to make the necessary code change to enable this feature for retesting and deployment.

## Acceptance Criteria
(Originally from ustaxcourt/ef-cms#7995:)
* The Motion to Proceed Remotely should be available for all parties to eFile
* The Motion to Proceed Remotely should be available for Docket users to add as a paper filing if necessary
* The Motion to Proceed Remotely should have a document code of "MOTR"
* After filing the Motion to Proceed Remotely, the motion should be added to the Pending report as with all other motions

* These changes are active in the pre-production and production environments

## Tasks
- [x] Remove feature flag - mob ustaxcourt/ef-cms-flexion#9241

## Test Cases
* Petitioner efiles a MOTR; MOTR is selectable in the UI during the efile process; MOTR appears in DAWSON labeled appropriately; MOTR is added to the Pending report
* Practitioner efiles a MOTR; MOTR is selectable in the UI during the efile process; MOTR appears in DAWSON labeled appropriately; MOTR is added to the Pending report
* Docket clerk enters a Paper Filing; MOTR is selectable in the UI during the process; MOTR appears in DAWSON labeled appropriately; MOTR is added to the Pending report

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [x]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ujahio** [comment]
Questions:

1. Do we implement the feature flag the way we do other feature flags?

**Comment by rosiehsmith** [comment]
@cholly75 is there any reason to keep this wrapped in a feature flag?

**Comment by cholly75** [comment]
@rosiehsmith Nope!

**Comment by shumway-tm** [comment]
Tested in Dev. All Test Cases looked good!
