### ISSUE TITLE
Notice of Change to Remote Proceeding

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8157]
As a docket clerk, so that I do not have to manually generate and serve needed documentation, I need DAWSON to generate and serve a Notice of Change to Remote Proceeding when a Trial Session with calendared cases has its proceeding type changed from In Person to Remote.

With COVID continuing to be an issue, some calendared trial sessions are being changed from In Person to Remote. When this happens, docket clerks must create a docket entry and generate a Notice of Change To Remote Proceeding for all open cases that are currently assigned to that trial session, then serve said notice. We would like DAWSON to do this for them. 

## Acceptance Criteria
* When a Trial Session with one or more open cases is edited to change the Proceeding Type from In Person to Remote, upon saving the changes to a Trial Session a Notice of Change to Remote Proceeding (NORP) is generated for each open case currently attached to that Trial Session.
* The NORP generated uses the template attached to this story and derives values from the Trial Session data:
  - City, St: derived from the Location data on the Trial Session
  - Judge: derived from the Judge data on the Trial Session
  - [location]: derived from the Location data on the Trial Session
  - [date]: derived from the Date of the Trial Session
  - [time]: derived from the Time of the Trial Session
  - Meeting ID: derived from the Meeting ID data on the Trial Session
  - Passcode: derived from the Passcode data on the Trial Session
* The NORP is added as a docket entry to the docket record with the link text "Notice of Change to Remote Proceeding"
* The NORP is immediately served via email to parties on the case with electronic service
* NORPs needing to be printed and served via paper are immediately presented to the clerk 

## Notes
[https://app.zenhub.com/files/152320868/79000e4f-dabc-445f-9ce5-bdf9bf9d20ac/download](https://app.zenhub.com/files/152320868/79000e4f-dabc-445f-9ce5-bdf9bf9d20ac/download)

## Tasks
- [x] add jsx for new NORP
- [x] add document generator code
- [x] add interactor and other code for generating NORP
- [x] call new interactor from updateTrialSession interactor
- [x] update courtIssuedEventCodes with NORP record
- [x] ensure James original unit tests is passing
- [x] make paper service page stuff work
- [x] update formatting for NORP doc 
- [x] DOD refactor updateTrialSessionInteractor
- [x] DOD add unit tests for all new code
- [x] DOD add integration tests for NORP generation
- [x] abstract serveNoticesOnCase code to be resuable

## Test Cases
* Case w/ parties receiving electronic service is calendared for In Person trial session; Trial Session is changed from IP to Remote; NORP is generated and served electronically; NORP appears on docket record
* Case w/ parties receiving paper service is calendared for In Person trial session; Trial Session is changed from IP to Remote; NORP is generated and presented to clerk for printing and service; NORP appears on docket record 
* Trial Session is changed from IP to Remote but the changes are not saved; no NORP is generated for any cases
* Trial Session is changed from IP to Remote along with date/time values; NORP is generated using all new values on Trial Session
* NORPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Case w/ parties receiving both paper and electronic service are calendared for In Person trial session; Trial Session is changed from IP to Remote; NORP is generated for clerk for printing paper service, and is generated and served electronically; NORP appears on docket record**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on "Add Trial Session"
- Fill in all of the Session information (Be sure that you select "in person")
- Click "Add Session"
- A green message will appear indicating "Trial Session added".
- Click on the "New" link, and navigate to the trial session you just created.
- Click on the City, State URL
- Check the "QC Complete?" boxes for a few cases in the Eligible case list.
- Click "Set Calendar"
- A modal will appear, click "Yes, Set Calendar"
- A print paper service screen will appear. Click "Done"
- Click on the "Open" tab to find the new trial session you just created
- Click on the City, State URL
- Click on the Edit link next to "Session Information"
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "In Person" to "Remote"
- Fill in the Remote proceeding fields (meeting ID, Password, etc.)
- Click Save

Expected Results:
- [ ] The Print for Paper Service page appears for Court user to print all paper service
- [ ] The NORP presented for paper service has the following information:
     - [ ] City, St: derived from the Location data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date]: derived from the Date of the Trial Session
     - [ ] [time]: derived from the Time of the Trial Session
     - [ ] Meeting ID: derived from the Meeting ID data on the Trial Session
     - [ ] Passcode: derived from the Passcode data on the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date

- Click Done
- DAWSON will bring you back to the Session Information Screen.
- Validate that the Session information now indicates all of the Remote Proceeding fields you added.
- Open one of the docket records from the Open Cases list (I opened in a new tab)
- Verify that the Notice of Change to Remote Proceeding is present on the Docket Record

Expected Results:
- [ ] The NORP is the last docket index on the record
- [ ] Date is Today's date
- [ ] Event Code = NORP
- [ ] Filings and Proceedings = Notice of Change to Remote Proceeding, this should be a link
- [ ] Pages = the total pages of the Notice
- [ ] Filed by = Blank
- [ ] Service Date = Today's date
- [ ] Parties = B

- Open the NORP by clicking on the URL on the docket record.

Expected Results:
- [ ] The NORP opened via the document viewer has the following information:
     - [ ] City, St: derived from the Location data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date]: derived from the Date of the Trial Session
     - [ ] [time]: derived from the Time of the Trial Session
     - [ ] Meeting ID: derived from the Meeting ID data on the Trial Session
     - [ ] Passcode: derived from the Passcode data on the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date


**2. Trial Session is changed from IP to Remote but the changes are not saved; no NORP is generated for any cases**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the "Open" tab to find an in-person trial session that is in the future
- Click on the City, State URL
- Click on the Edit link next to "Session Information"
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "In Person" to "Remote"
- Fill in the Remote proceeding fields (meeting ID, Password, etc.)
- Click "Cancel"
- A modal will pop-up. Click "Yes, Cancel"

Expected Results
- [ ] DAWSON navigates back to the Trial Sessions Open tab
- [ ] When you click on the Trial session that you just cancelled out of, all of the original fields remain the same.
- [ ] When you open one of the cases in the trial session, no NORP of generated on the Docket record.


**3. Trial Session is changed from IP to Remote along with date/time values; NORP is generated using all new values on Trial Session**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the "Open" tab to find an in-person trial session that is in the future
- Click on the City, State URL
- Click on the Edit link next to "Session Information"
- Change the date of the Trial Session
- Change the time 
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "In Person" to "Remote"
- Fill in the Remote proceeding fields (meeting ID, Password, etc.)
- Click Save

Expected Results:
- [ ] The Print for Paper Service page appears for Court user to print all paper service
- [ ] The NORP presented for paper service has the following information:
     - [ ] City, St: derived from the Location data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date]: derived from the Date of the Trial Session is the NEWLY UPDATED date that you entered
     - [ ] [time]: derived from the Time of the Trial Session is the NEWLY UPDATED date that you entered
     - [ ] Meeting ID: derived from the Meeting ID data on the Trial Session
     - [ ] Passcode: derived from the Passcode data on the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date

- Click Done
- DAWSON will bring you back to the Session Information Screen.
- Validate that the Session information now indicates all of the Remote Proceeding fields you added.
- Open one of the docket records from the Open Cases list (I opened in a new tab)
- Verify that the Notice of Change to Remote Proceeding is present on the Docket Record

Expected Results:
- [ ] The NORP is the last docket index on the record
- [ ] Date is Today's date
- [ ] Event Code = NORP
- [ ] Filings and Proceedings = Notice of Change to Remote Proceeding, this should be a link
- [ ] Pages = the total pages of the Notice
- [ ] Filed by = Blank
- [ ] Service Date = Today's date
- [ ] Parties = B

- Open the NORP by clicking on the URL on the docket record.

Expected Results:
- [ ] The NORP opened via the document viewer has the following information:
     - [ ] City, St: derived from the Location data on the Trial Session
     - [ ] Judge: derived from the Judge data on the Trial Session
     - [ ] [location]: derived from the Location data on the Trial Session
     - [ ] [date]: derived from the Date of the Trial Session is the NEWLY UPDATED date that you entered
     - [ ] [time]: derived from the Time of the Trial Session is the NEWLY UPDATED date that you entered
     - [ ] Meeting ID: derived from the Meeting ID data on the Trial Session
     - [ ] Passcode: derived from the Passcode data on the Trial Session
     - [ ] Service stamp at the bottom of the Notice has today's date

**4. NORPs are generated appropriately for all open cases on trial session, none are generated for closed cases on trial session**
- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click on the "Open" tab to find an in-person trial session that is in the future
- Click on the City, State URL
- Scroll down to the Case list
- Ensure that there are multiple cases on the trial session that you selected, and that there are both Open (Active) Cases, as well as inactive (closed) cases associated with the trial session.  I selected a large Metropolitan city to test with. 
- While you are on the Inactive Cases list, find a case where the Petitioner has paper service and remember this docket number for a later test.
- Click on the Edit link next to "Session Information" 
- Scroll down on the Edit Trial Session Page until you get to the Location Information Section
- Change the Proceeding type from "In Person" to "Remote"
- Fill in the Remote proceeding fields (meeting ID, Password, etc.)
- Click Save

Expected Results:
- [ ] The Print for Paper Service page appears for Court user to print all paper service
- [ ] The NORP presented for paper service has all of the information from Test case 1 for Active Cases (If you already validated via Test Case 1, a quick review on this is fine).
- [ ] The NORP is NOT generated for paper service for the docket number of the closed case that you noted above

- Click Done
- DAWSON will bring you back to the Session Information Screen.
- Validate that the Session information now indicates all of the Remote Proceeding fields you added.
- Scroll down to the Case List section, an click on the Inactive Cases link.
- Open a few of the docket records from the Inactive Cases list (I opened each in a new tab)
- Verify that the Notice of Change to Remote Proceeding is NOT present on the Docket Record of any of these cases.

Expected Results:
- [ ] The NORP is the NOT Present as the last docket index on the record for any of the Inactive cases

**Comment by cholly75** [comment]
@mrinsin @jamesobrooks - confirmed, the Court would like to include the Chambers Phone associated with the trial session and display it in the Judge portion of the information boxes in the upper half of the document.

**Comment by ttlenard** [comment]
Some initial testing feedback:

1 - Seeing duplicate judges in the dropdown for judges (Sounds like this one isn't related to the Story): 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ef8aac30-9d81-485c-8644-2ab6ea329d14)

2 - I was on Test case 1 and received an error after changing from in-person to remote. "Trial session could not be edited. Please try again."  The interesting thing was that SOME of the notices were added to the docket record, and service emails were sent on some.  Here is the Trial session ID: 54ccc5e-d1c3-43c8-bf0e-11f75ecc7103 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/55825828-90f3-49b4-a29e-3532fa79851c)

3 - I am also noticing that the service emails that are getting sent out are including michael.marcotte@ustaxcourt.gov. (Maybe this is always like this?  Interesting...)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/6a979285-3703-4a66-b76c-5f5cc4246083)

**Comment by cholly75** [comment]
Confirmed - seeing the same thing as @ttlenard 's ustaxcourt/ef-cms#6492 above - attempting to edit trial session to remote for the 4/4 San Francisco session w/ Judge Toro in TEST

**Comment by cholly75** [comment]
Still seeing duplicate entries for judges Choi and Landy.
