### ISSUE TITLE
Auto-Generate Petitions Documentation

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8162]
As a petitions clerk, so that I can quickly process and serve additional documentation needed for petitioners, I need DAWSON to automatically generate documentation when I serve a petition.

When reviewing a petition in DAWSON, the petitions clerk may need to create additional orders and notices depending on the information that the petitioner provides. Currently they must do this manually after QC, and must manually note which documentation is needed. We would like DAWSON to generate this documentation based on selections by the petitions clerk during the QC process.

**Epic Scenario:**
(_Italicized content_  = functionality that is complete. **Bold content** = new functionality.)

When a petition is submitted to the Court, a Petitions Clerk _reviews the petition for accuracy, completeness and adherence to Court procedures and policies._ When a Petitions Clerk observes inaccuracies, incompleteness, or lack of adherence to policy, they must formally _inform the petitioner of the requirements by sending a Court Order._ After the Petitions Clerk has completed their review, they must **recall which orders to create and serve to the petitioner based on their review.** One Court Order is created and served for each action required of the petitioner. **As well, the content for each Court Order may be static, dynamic or both, depending on what action is required.** 
* If the petitioner has not selected a place of trial, the Petitions Clerk will _select the place of trial_ for the petitioner and **create and serve an Order Designating Place of Trial.** The content of the order is based upon which case type is selected (regular or small).
* If the petitioner has not paid their filing fee, the Petitions Clerk will **create and serve an Order for Filing fee**
* If the petitioner has selected a "small" case type during petition entry, but the amount disputed is over $50K, the Petitions Clerk will **create and serve an Order to Show Cause**, which requires the petitioner to state why they should be considered as a small case
* If the petitioner provides incorrect information in their petition, the Petitions Clerk will **create and serve an Order for Amended Petition, along with a court form the petitioner can use to amend the petition**
* If the petitioner provides incorrect information AND does not pay their filing fee, the Petitions Clerk will **create and serve an Order for Amended Petition and Filing Fee, along with a court form the petitioner can use to amend the petition**

At times during the petition review, the Petitions Clerk may _provide information to the petitioner that is helpful, but not required_ for petitions submission.
* If the petitioner provides evidentiary documentation during petitions submission, the petitioner will **notify the petitioner of how to submit evidence, even though it is not required for petition submission.** 

## Acceptance Criteria
 - After reviewing a petition, the Petitions Clerk can easily recall which orders or notices to serve based on their review of the petition data
 - When possible, the Petitions Clerk can avoid repetitive content creation for both static and dynamic Order content.
 - All orders created should function the same as other orders in the system, in that they can be created in draft form, sent to others at the court, edited, allow for the signature of the Chief Judge, and be added to the docket record.
 - If the Petitions Clerk selects a place of trial because the petitioner has not done so, the Petitions Clerk can create and serve a Notice Designating Place of Trial for both small and regular cases ustaxcourt/ef-cms#8088
 - If the petitioner has not paid their filing fee, the Petitions Clerk can create and serve an Order for Filing Fee ustaxcourt/ef-cms#8091
 - If the Petitioner has selected “small” for case type, but the amount they’ve entered for the dispute is over $50K, the Petitions Clerk can create and serve an Order to Show Cause, which requires the petitioner to justify why the case type should be small ustaxcourt/ef-cms#8163
 - If the Petitioner has provided incorrect petition data, the Petitions Clerk can create and serve, along with a required form, the Order for Amended Petition ustaxcourt/ef-cms#8164
 - If the Petitioner has provided incorrect petition data AND has not paid their filing fee, the Petitions Clerk can create and serve, along with a required form, the Order for Amended Petition and Filing Fee ustaxcourt/ef-cms#8165
 - If the Petitioner has submitted what appears to be evidentiary documents with their petition, the Petitions Clerk can issue a notice to ustaxcourt/ef-cms#8087

* Auto-generate Order for Ratification of Petition (TBD) - may be out of scope

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment
