### ISSUE TITLE
Petitions: Auto-Generate Order to Show Cause

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8163]
As a petitions clerk, so that I can easily generate needed documentation, I need to have DAWSON generate a draft of an Order to Show Cause automatically when I indicate that one is needed for a case.

Currently, when a Petitions Clerk indicates that an Order to Show Cause (OSC) is needed for a case, they check the appropriate box at the time of paper Petition entry or QC of eFiled Petition. After the Petition is served, the Petitions Clerk must then manually create the order via copying and pasting content from outside DAWSON into a blank order (via the order generator).

As this notice is standard text across all petitions, if the clerk indicates that the order is needed we would like this order to be automatically generated as a draft entry attached to the case upon Petition service, at which point the clerk can review, edit, delete, and add as a docket entry through normal existing process.

We anticipate additional stories to auto-generate other notices and orders in the same manner; ideally the framework for auto-generating the OSC can be extended to include other documentation.

## Pre-Conditions
See 8993 for UX specs: https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/flexion/ef-cms/8993

## Acceptance Criteria
* If the Order to Show Cause box is checked when the clerk Serves the Petition, an Order to Show Cause (OSC) is generated and saved as a Draft document at the time the Petition is served.
* After Case is created and before service of the petition, the UI indicates that OSC is pending generation
* The generated OSC is created with the standard Order format (Case caption/docket number at the top followed by title and text of the order)
* The title of the generated OSC is "Order to Show Cause"
* The **body** content of the generated OSC is identical to the attached document:
[https://app.zenhub.com/files/152320868/ea20addc-5727-4548-8839-846d830c46d3/download](https://app.zenhub.com/files/152320868/ea20addc-5727-4548-8839-846d830c46d3/download)
 - The value of the [FILED_DATE] token is derived from the served date of the petition
 - The value for the [ORDER_DATE_PLUS_60] token in the content is derived from the current date at the time of order generation and counting 60 consecutive calendar days hence. If the resulting date falls on a Saturday, Sunday, or federal Holiday then the resulting date should instead be changed to the next weekday that is not a Holiday.
* The generated draft order should not auto-apply the signature of the Chief Judge. The clerk will do this.
* The generated draft order can be interacted with in the same manner as any other Draft order from the Drafts view (edit,
delete, apply a signature, and add as a docket entry).

## Notes
Should use updated order header: see [9093](https://github.com/flexion/ef-cms/issues/9093)

## Tasks
- [x] Modify Orders/Notices banner - Tim https://github.com/ustaxcourt/ef-cms/pull/2002
- [x] Update unit tests to cover OSC - Tim/Rosie https://github.com/ustaxcourt/ef-cms/pull/2002
- [x] Update integration test to cover OSC - Tim/Rosie https://github.com/ustaxcourt/ef-cms/pull/2002
- [x] Update interactor to conditionally generate OSC draft - Rosie https://github.com/ustaxcourt/ef-cms/pull/2002
- [x] Address feedback to not pre-populate description field for the docket entry - Tim, Rosie https://github.com/ustaxcourt/ef-cms/pull/2004
- [x] Add OSC to visual testing https://github.com/ustaxcourt/ef-cms/pull/2012

## Test Cases
* Petitions clerk starts new petition, checks box for "Order to Show Cause" in the Case Info tab and completes all other required info and creates Case. OSC is not generated. UI reflects pending OSC generation. Petition is served; OSC is generated and appears as a Draft document attached to case.
* Petitions clerk QCs new e-filed petition, checks box for "Order to Show Cause" in the Case Info tab and completes all other required info and creates Case. OSC is not generated. UI reflects pending OSC generation. Petition is served; OSC is generated and appears as a Draft document attached to case.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to any Flexion environment for Engineering Review
 - [x] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Petitions clerk starts new Paper petition, Only checks box for "Order to Show Cause" in the Case Info tab and completes all other required info and creates Case. Order is not yet generated, but the UI reflects a pending Order generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition, STIN, and RQT under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button
- Check the box for Order to show cause
- Add a Trial Location and indicate that the Filing Fee was paid (add in payment date and payment method)
- Under the Orders/Notices Needed section, leave all checkboxes unchecked.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [ ] On the "Review and Serve Petition" Screen, you should see a yellow warning box with a new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [ ] The "Order to Show Cause" should be below the above section header, and will be in regular font.


**2. Petitions Clerk serves the petition. Order to Show Cause is generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [ ] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there is 1 draft.

**3. The draft Order to Show Cause is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [ ] On the left hand side of the page under the Drafts, you should see a new "Order to Show Cause" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [ ] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be Order to show Cause, etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/ea20addc-5727-4548-8839-846d830c46d3/download
- [ ] The Filed Date in the Order should be the served date of the petition
- [ ] The Order Date date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [ ] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF.

**4. Add the Order to Show Cause as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order to Show Cause for Paper Service" screen

Expected Results
- [ ] Order to Show Cause is added as a docket entry and shows as served
- [ ] The Order Event Code is "OSC" on the Docket Record
- [ ] The number icon no longer appears on the Drafts tab

**5. Petitions clerk starts new Paper petition, checks boxes for multiple Orders as well as checks the box for "Order to Show Cause" in the Case Info tab and completes all other required info and creates Case. Order to Show Cause is not yet generated, but the UI reflects a pending Order to Show Cause generation.** 
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click "Start a Petition" button
- On the Create a case screen, select "Petitioner" as the Party type from the dropdown menu.
- Fill in the petitioner information on the parties tab
- Upload or scan in document for a Petition and STIN under the Documents section of the screen
- Click on the Case Info tab
- Fill in the Date Received, Mailing Date, Case Procedure radio button, and check the box for "Order to show cause".
- Leave the Trial location blank. This will ensure that the checkbox is checked for "Order Designating Place of Trial"
- Select the radio button that the fee was NOT paid. This will automatically check the box for Order for Filing Fee
- Under the Orders/Notices Needed section, select the checkbox for one or two other Orders needed, as well as the checkbox for Notice of Attachments in the Nature of Evidence.
- Click on the IRS Notice tab.
- Select No, and then select "Deficiency" from the dropdown menu for Type of Case.
- Scroll down and click "Create Case".

Expected Results

- [ ] On the "Review and Serve Petition" Screen, you should see a yellow warning box with 2 Section Headers.  One that states "Orders/Notices Needed" and new section header in bold that states: "Orders/Notices Automatically Created in Drafts After Service"
- [ ] Some of the Orders (that have not yet had a story to be auto-created) that you selected should be under the section Header "Orders/Notices Needed" and will be in regular font.
- [ ] The "Order to Show Cause", and all other Orders/Notices that were selected that have been coded to be auto-created should be under the section header "Orders/Notices Automatically Created in Drafts After Service", and will be in regular font.


**6. Petitions Clerk serves the petition. Order to Show Cause, and all other Orders/Notices that were selected that have been coded to be auto-created are generated and a new number icon appears on the Drafts tab**
- Continuing on from the Petition from the above Test Case, click the button to "Serve to IRS"
- Click "Yes, Serve"
- The "Print Paper Petition Receipt" screen will appear, click "Done"
- You should receive a green confirmation banner that the Petition was Served to the IRS.  
- Click on the "Served" tab
- The petition that you just served should be on the top of the list. Click on the Docket Number link to navigate to the case.

Expected Results
- [ ] There is a new number icon showing to the right of the word "Drafts" on the Drafts tab, indicating that there are drafts. This number should reflect the total number of draft Orders/Notices created.

**7. The draft Order to Show Cause is formatted correctly and is available for review in the drafts tab**
- Continuing from the previous test case, click on the Drafts tab

Expected Results:
- [ ] On the left hand side of the page under the Drafts, you should see a new "Order to Show Cause" draft available, and the created date should be the date it was created.  (If you did this today, it should be today's date.)
- [ ] In the document preview, the Order should be in the standard Order format (caption, US Tax Court, tax court seal,  title should be Order to show Cause, etc.), and should include the standard body content that is here: https://app.zenhub.com/files/152320868/ea20addc-5727-4548-8839-846d830c46d3/download
- [ ] The Filed Date in the Order should be the served date of the petition.
- [ ] The Order Date date should be either be: 1) 60 consecutive calendar days hence (If the calendar date falls on a Saturday, Sunday, or Federal Holiday the then resulting date should be the following weekday that is not a holiday), or 2) there should be a red [ENTER_DATE] to let the clerk know they need to add the date
- [ ] Petitions Clerk has the ability to Edit, Delete, Apply Signature, or View Full PDF

**8. Add the Order to Show Cause as a docket entry and Serve it.**
- Continuing from the previous test case, click "Apply Signature"
- Add the signature to the document
- Click Save Signature
- DAWSON will take you back to the Drafts tab, Click "Add Docket Entry"
- On the Add Docket Entry Screen, Click Save and Serve
- Click "Yes, Serve"
- Click "Done" on the "Print Order to Show Cause for Paper Service" screen

Expected Results
- [ ] Order to Show Cause is added as a docket entry and shows as served
- [ ] The Order Event Code is "OSC" on the Docket Record
- [ ] The number icon should now reflect 1 less document on the Drafts tab

**Comment by cholly75** [comment]
2 things:

1) Final paragraph appears to be indented one space too many (screenshot attached)
2) Can we clear the populated Description field when going to add the Docket Entry? Otherwise there's text that the clerk will manually have to clear themselves to prevent duplication on the record.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/cfbcdc5a-52a2-42e9-a491-be684010f18f)

Thanks!
Chris

**Comment by rosiehsmith** [comment]
For future reference, feedback item 1 will hopefully be addressed by ustaxcourt/ef-cms#8331! https://github.com/flexion/ef-cms/issues/9473#issuecomment-1082407356

**Comment by cholly75** [comment]
@rosiehsmith @shumway-tm - We found an issue with these notices, in that if the notice is edited/previewed in any way (or just saved from the Edit screen) then the spacing between paragraphs is lost.

**Comment by cholly75** [comment]
@rosiehsmith - can we blank the description field in the same manner we did for the OFF and NANE? I know there was a branch/code overwrite that had removed it previously from those stories, so I'm wondering if that's the case here or we just haven't implemented it.

**Comment by rosiehsmith** [comment]
^^ for future reference, this was happening when you edit the order, then add the docket entry. this is a slightly different flow than the previously addressed clearing of the description field for 9001 and 9340 which was clearing the description field on the initial adding of the draft docket entry upon serving the petition.

**Comment by cholly75** [comment]
@shumway-tm - now that we've fixed the overall formatting by removing the right justification, is there anything we can do about the single extra space in the tab indent for paragraph 2?

(Actually, can we just have all the paragraphs do the default tab indent spacing now that that's working again?)

**Comment by rosiehsmith** [comment]
For the first question, last night staging, which had the indent fix from migration, was merged into test so it should be all aligned unless my eyeballs aren't working 
![image](https://user-images.githubusercontent.com/16403861/161996412-dda8298b-ae79-4629-b8a9-d2c7e9bf34b7.png)

**Comment by shumway-tm** [comment]
@cholly75 The paragraph indentations look aligned to me as well @rosiehsmith.

**Comment by cholly75** [comment]
@rosiehsmith  @shumway-tm - aha! Yes, this morning things are lining up correctly, thanks! No need to replace the indentation with the default spacing, as these are all uniform.

It does look like we're missing the underline under the word "See" in the phrase "See section 7463(a)(1)..." at the end of the first graf.

**Comment by cholly75** [comment]
Update to the AC: the Court would prefer this document be generated as the OSCP event code, so that they get the more verbose docket entry addition; this allows them to supply a due date and any free text as required (see screenshot below)

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/15305d93-ce18-4405-be23-0e5181507faa)

Discussed w/ Rosie and Tim - provisionally added to this story as feedback if the change is straightforward enough. Otherwise, we can add as a separate story.

**Comment by rosiehsmith** [comment]
You know, I think I'm changing my mind with doing this as feedback on this, sorry :) Do we know why they want the date to be available here? If it's more about having the date available and not specific to that event code OSCP, an option could be to add the date to the form for OSC. Would it be helpful to include UX in this?

**Comment by cholly75** [comment]
@rosiehsmith totally fine - they would rather have it as an OSCP event code not just because it has the date picker, but also because OSCs can be issued to make the parties show cause for any number of things in a particular case, so using OSCP as the standard for THIS particular order to show cause (arguably its intended function in the first place, based on the prefilled text in the dropdown) just helps to make the docket record clearer and standardize processes.
