### ISSUE TITLE
Auto-Generate Clinic Letters

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8169]
As a pro se petitioner, so that I have all the resources I need to pursue a case, I need to receive pre-authorized letters from tax clinics at various points in the lifecycle of my case.

For pro se petitioners who may not be able to afford or locate counsel to guide them through their case, there are tax clinics available as a resource who often advise and/or represent lower income petitioners. These clinics provide the Court with letters for petitioners indicating the details on how to use these resources, and as part of the Court's commitment to taxpayer equity prior to DAWSON we sent these letters to pro se petitioners along with official Court notices at various points in the life of the case.

These letters are not official Court or IRS documentation, but we provide them as a courtesy. There are one or more letters for each place of trial where the Court conducts business, and so the specific letter that gets sent should be location-appropriate. Additionally, there may be differences in the letters for a given location based on the type of case that is docketed (regular, small, etc). 

We would like to re-establish the process of generating and sending out these letters at two places in the current lifecycle: upon serving the Notice of Receipt of Petition, and upon serving the Notice Setting Case for Trial. Additionally, we need to be able to maintain and update these letters when new versions are issued (approx. annually, mid-February). 

The letters themselves are provided in toto by the clinics; no customization is needed to the letter text itself, and these are not docketed as entries on the official record.

## Acceptance Criteria
 - Petitions clerk can provide tax clinic information to one location for one proceeding type (#9429)
 - Petitions clerk can provide tax clinic information to one location for multiple proceeding types (#9430)
 - Petitions clerk can provide tax clinic information to multiple locations for multiple proceeding types (#9355)
 - Petitions clerk can provide tax clinic information to pro-se petitioner when case is set for trial
 - Court personnel can add the tax clinic information to DAWSON
 - Court personnel can replace the tax clinic information in DAWSON
 - Court personnel can remove tax clinic information in DAWSON

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment
