### ISSUE TITLE
Session Management for Logged In Users During Deployment (BREAK INTO SMALLER?)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8176]
As a DAWSON user, so that I can use the application any time that I require, I need to be able to continue to use the application during deployment activities.

DAWSON deployments currently interrupt user activity at the end of deployment activities. By allowing users to continue working during and after deployments, we can provide both a better user experience and more frequent deployment opportunities.

This story should provide continuous service to a user during and post-deployment activities.

## Acceptance Criteria
* User is able to continue reading data from DAWSON session during deployment activity
* User is able to continue data entry to DAWSON during deployment activity
* Data entered during deployment activity is correctly reflected in DAWSON post-deployment
* Any user activity required to update application should be integrated into current user workflow
* In-flight processes initiated during deployment should continue to run and complete correctly

## Notes
* Need to work/test with IRS
* Some user activities may warrant notification to user w/ update
* Would like to make this as invisible to the end user as possible
* Test with failed/interrupted deployment scenario
* Solution can not rely on websocket
* Mob working on this ticket, provide feedback to team on story in which way the story will go.

## Tasks
- [ ] Determine how/if we can break this story up into smaller, more manageable pieces.

## Test Cases
**Write Operations**
* Petitioner - Upload Petition
* Petitioner - Create a login
* Petitions Clerk - Set Calendar
* Petitions Clerk - Serving a Petition
* Petitions Clerk - adding paper petition by scanning
* Practitioner - Update Contact info
* Practitioner - Upload a document
* Docket - Edit docket entry
* Docket - PDF Upload
* Docket - Add Parties/edit case info
* Docket - assigning work items
* Docket - applying signature
* Docket - create deadline
* Docket - Correspondence
* Docket - Create Order or Notice
* Docket - Create a case note
* CA/ADC - Sending a message
* Judge/Trial Clerk- Adding trial session notes
* Judge/Trial Clerk - Download cases
* Admissions - Add Practitioner
* Admissions - Add an email address

**Read operations**
* Petitioner - Navigate and view cases on dashboard
* CA/ADC - Run a report
* Docket - viewing section and individual inboxes
* Practitioner - Searching
* Judge/Trial Clerk - view trial session
* IRS Super User - run reconciliation report, other stuff to test???

**Operation-Agnostic Test Cases**
* Data format change: create data prior to deployment that will be affected by a format change in the migration step of the deployment. Submit the data during the time after color-switch but before the old color is taken offline. Confirm that the data is migrated properly into the new format in the new color post-deployment.

* User token refresh: Establish a user session prior to the deployment; time this such that the token refresh period occurs during the appropriate time during the deployment/migration. Confirm that the token refresh takes place in a manner that does not interrupt the user experience.

* Test with failed/interrupted deployment scenario

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by cholly75** [comment]
More detailed test cases to be added based on solution approach; the high level test cases are essentially DAWSON workflows as they operated today.

**Comment by rachelschneiderman** [comment]
Court operating hours: 8am-5pm EST

DAWSON must be up until midnight on the weeknights to be available to folks trying to meet filing deadlines

Court does not make any guarantees that its systems are available on the weekends when the court is open.

**Comment by cholly75** [comment]
Chris to write spike story for slice of this - starting with petitioner uploading petition flow to see what changes would need to be made for eventual solution.

Chris to confirm with court what intermediate measures might be acceptable in terms of getting to the "gold standard"

Both stories to be added to the epic.
