### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8193]
As a court user, so that I can prioritize my work appropriately, I need to be able to quickly tell when a message is related to a case that is in a consolidated group.

When messages are displayed for sections or users, they are accompanied by the docket number to which that message is attached; however, there is no indication on the message display whether that docket is part of a consolidated group. Feedback from court users has indicated that being able to discern at a glance whether a message pertains to a consolidated group would be helpful in assigning work and organizing the user's work. Currently a user must click into a message to determine whether or not the case is part of a consolidated group.

We would like to indicate visually on aggregate Message views whether a particular docket number is the Lead Case in or a member of a consolidated group.

## Acceptance Criteria
* Visual cues for Lead Case and member case of group are distinctive and different from each other
* Section Message views visually indicate in the Docket No. column along with the docket number when a case is the Lead Case in a consolidated group
* Section Message views visually indicate in the Docket No. column along with the docket number when a case is a member of a consolidated group
* User Message views visually indicate in the Docket No. column along with the docket number when a case is the Lead Case in a consolidated group
* User Message views visually indicate in the Docket No. column along with the docket number when a case is a member of a consolidated group
* This applies across all sections (ADC, Admissions, Chambers, CotC, Docket, Petitions, Reporter's Office, Trial Clerks) and their users.
* This applies across all views for Messages (Inbox, Sent, Completed).

## Tasks
- [x] Use docketNumberWithSuffix/retrieve docketNumber when getting messages from persistence https://github.com/ustaxcourt/ef-cms/pull/2248
- [x] Potentially add action to retrieve leadDocketNumber for each case associated with a message https://github.com/ustaxcourt/ef-cms/pull/2248
- [x] Use leadDocketNumber to determine whether to display icon https://github.com/ustaxcourt/ef-cms/pull/2248
- [x] Add icon for message on a lead case https://github.com/ustaxcourt/ef-cms/pull/2248
- [x] Add icon for message on a case that's in a consolidated group (Mrinalini & Rachel) https://github.com/ustaxcourt/ef-cms/pull/2248
- [x] DOD https://github.com/ustaxcourt/ef-cms/pull/2255
- [x] UX Feedback https://github.com/ustaxcourt/ef-cms/pull/2265 https://github.com/ustaxcourt/ef-cms/pull/2268

## Test Cases
* Message is sent/forwarded/replied to from case that is a Lead Case in a consolidated group; message displays w/ visual cue indicating Lead Case status on user and section message views (based on recipient).
* Message is sent/forwarded/replied to from case that is a member (not Lead) case in a consolidated group; message displays w/ visual cue indicating membership in consolidated group on user and section message views (based on recipient). 
* Message is sent/forwarded/replied to from case that is neither a Lead Case nor a member case in a consolidated group; message displays w/ no additional visual cue on user and section message views (based on recipient). 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Deployed to the Court's `test` environment for PO Review

**Comment by swongCO** [comment]
![Messages - consolidation indicators.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/96e3e823-bc7d-4234-8356-681b5297afc2)
![Messages - consolidation indicators hovertips.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/44f35e47-e1e9-4544-b1a8-a273301bfc6d)

1. Use existing consolidation icon
2. Lead case indicator has “L” inside of icon (to be provided as svg)
3. Placement is at beginning of row before docket no.
4. Same size as other icons (ex. Circle !) - 22px
5. Color = #005ea2
6. Include left padding to accommodate hover bar
7. If there are no consolidated cases, space persists but will be empty
8. Hover tips: “Consolidated case” “Lead case”
9. https://www.figma.com/file/6Oik8JNbmmWDMhIC1JkUhd/USTC-%7C-Consolidation-%7C-Epic?node-id=232%3A174

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Message is sent from case that is a Lead Case in a consolidated group; message displays w/ visual cue indicating Lead Case status on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to the lead case in a consolidated group
- Click on Create, and then select message
- Send a new message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Click on Section Messages

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)


#### 2) Message is forwarded from case that is a Lead Case in a consolidated group; message displays w/ visual cue indicating Lead Case status on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to the lead case in a consolidated group
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Forward a message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Click on Section Messages

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)

#### 3) Message is replied to from case that is a Lead Case in a consolidated group; message displays w/ visual cue indicating Lead Case status on user and section message views (based on recipient).
- Log in as a court user (ex: Docket clerk 1)
- Navigate to the lead case in a consolidated group
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Reply a message to another court user (testchambers1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Log out as the docket clerk 1 user, and then log in as the test chambers 1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Click on Section Messages

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message that includes the letter "L".

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)

#### 4) Message is sent to from case that is a member (not Lead) case in a consolidated group; message displays w/ visual cue indicating membership in consolidated group on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to a member case in a consolidated group (not the lead case)
- Click on Create, and then select message
- Send a new message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Click on Section Messages, inbox tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)



#### 5) Message is forwarded to from case that is a member (not Lead) case in a consolidated group; message displays w/ visual cue indicating membership in consolidated group on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to a member case in a consolidated group (not the lead case)
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Forward a message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Click on Section Messages

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)


#### 6) Message is replied to from case that is a member (not Lead) case in a consolidated group; message displays w/ visual cue indicating membership in consolidated group on user and section message views (based on recipient).
- Log in as a court user (ex: Docket clerk 1)
- Navigate to a member case in a consolidated group (not the lead case)
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Reply a message to another court user (testchambers1)
- Click on the sent tab

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Log out as the docket clerk 1 user, and then log in as the test chambers 1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Click on Section Messages

Expected Results
- [x] There is a new icon located on the left side of the docket number of the message to indicate that the case is in a consolidated group; icon does not have the "L" in it.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)


#### 7) Message is sent to from case that is neither a Lead Case nor a member case in a consolidated group; message displays w/ no additional visual cue on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to a case that is NOT in a consolidated group.
- Click on Create, and then select message
- Send a new message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Click on Section Messages, inbox tab

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)



#### 8) Message is forwarded to from case that is neither a Lead Case nor a member case in a consolidated group; message displays w/ no additional visual cue on user and section message views (based on recipient).
- Log in as a court user (ex: Chambers1)
- Navigate to a case that is NOT in a consolidated group.
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Forward a message to another court user (docketclerk1)
- Click on the sent tab

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Log out as the Chambers user, and then log in as the Docket clerk1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Click on Section Messages

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)


#### 9) Message is replied to from case that is neither a Lead Case nor a member case in a consolidated group; message displays w/ no additional visual cue on user and section message views (based on recipient).
- Log in as a court user (ex: Docket clerk 1)
- Navigate to a case that is NOT in a consolidated group.
- Click on Case Messages (Be sure that the case you are on has existing messages)
- Reply a message to another court user (testchambers1)
- Click on the sent tab

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Log out as the docket clerk 1 user, and then log in as the test chambers 1
- Be sure that you are on the inbox tab of the messages page

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Click on Section Messages

Expected Results
- [x] There is no icon present indicating that the case is consolidated next to the message.

Next:
- Be sure to repeat this test with other sections of the court (ADC, Admissions, CotC, Petitions, Reporter's Office, Trial Clerks)

**Comment by rachelschneiderman** [comment]
This story requires re-indexing as we had to add a join relationship between efcms-case and efcms-message in order to grab the `leadDocketNumber` property off the case a message belongs to.

**Comment by codyseibert** [comment]
[load-testing-9502-on-test.pdf](https://github.com/flexion/ef-cms/files/8872309/load-testing-9502-on-test.pdf)

**Comment by liadmccabe** [comment]
When logged in as Chambers1, on the dashboard under recent messages, the Lead icon is currently missing and will need to be added. ![Screen Shot 2022-06-10 at 10.49.02 AM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/d740a390-0b56-4bd2-9413-8db61c63b6b9)

**Comment by swongCO** [comment]
![Screen Shot 2022-06-09 at 2.55.28 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/f8968813-5ba2-413e-baac-23bf97c9fefb)
screenshot 1 - when there are consolidation icons, the column aligns nicely

![Screen Shot 2022-06-09 at 2.54.18 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/2b31bfc5-891f-4e6b-9bd2-0140e885e661)
screenshot 2 - when there isn’t a consolidation icon, the docket number is not left aligned with the column header label
is there a way to make the docket nos. left align with the header label like the other columns when there is no icon?

**Comment by liadmccabe** [comment]
Lead Icon - Currently the hover is picking up the icon as text instead of the image due to the "L".  This means the hover tip is not accessible unless the user hovers precisely next to rather than over the 'L'. Can be an accessibility pain point. Recommendation to convert the entire image to the .svg file provided by Sui so that the hover text can be picked up regardless of where the user hovers over the image.
