### ISSUE TITLE
Court: Dedicated Docket View for Exhibits

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8226]
As a DAWSON user so that I can quickly identify exhibits pertaining to a case, I need a view that displays only exhibit event code docket entries.

In the course of a case at trial or in a hearing, many times there will be multiple references to specific exhibits that have been docketed. Currently the trial clerk or other DAWSON user must navigate the entirety of the docket record to locate and view the specific exhibit in question. With long docket records, this becomes unwieldy and confusing.

We would like for a user to be able to see a filtered view of the docket record that includes only those docket entries coded with exhibit-related event codes. Whether this is simply a selectable filter on the current docket record or a separate navigable view, this should be accessible by all court DAWSON users. 

## Acceptance Criteria
* User can see a view of the docket record that includes only those docket entries with event codes related to exhibits
* User can interact with the docket entries on this view in the same manner as interacting with them on the Docket Record view based on their role (i.e., docket clerks can edit and seal entries from this view)
* User can easily navigate to or implement this view and then return to the full docket record
* View is accessible to all internal Court users
* View is accessible to parties and counsel (private and IRS) attached to the case
* View includes all docketed entries for the case with the following event codes:
  - EXH
  - PTE
  - HE
  - TE
  - M123
  - STIP

* View is ordered in the same default manner as the standard docket record view
* Docket entries on this view obey all other standard rules for visibility

## Tasks
- [x] Add filter dropdown on internal Docket Record page
- [x] Add filter dropdown on external Docket Record page
- [x] Add entity constant for specific exhibits event codes
- [x] Ensure dropdown isn't visible in public view

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by cholly75** [comment]
@liadmccabe @swongCO - feedback from the Court indicated a desire to have similar views for both Orders and Motions as well;  whether that should be part of this story or not is debatable, but a unified design w/ a filter dropdown like you showed me would probably serve that well if those other stories manifest.

**Comment by swongCO** [comment]
![Docket Record - View all docs.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7b832d1d-8121-41c3-b3d1-478e4e307368)

![Docket Record - View exhibits.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/65671a46-161f-4253-a1a6-b94c611d9fd6)

1. Add a new filter after the Sort dropdown
2. The label for the new filter is "Filter by"; use styling of filter label from https://app.test.ef-cms.ustaxcourt.gov/trial-sessions
3. Dropdown options are: All documents (default selection), Exhibits

**Comment by ttlenard** [comment]
## Test Cases

**Note - I was unable to find cases with HE or M123 documents.  When testing below, you should be sure to add some of these specific exhibit documents onto a docket record to ensure that all Exhibit type documents are getting filtered appropriately.


#### 1) Court user can choose to view only docket entries related to Exhibits on the docket record of a case.

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In the new View Filter, select Exhibits

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display exhibit documents (EXH, PTE, HE, TE, M123), and does not show other document types. 

*Repeat this test with multiple docket records to ensure that all of the exhibit documents are being filtered appropriately


#### 2) Docket Clerk can view/interact with documents on the docket record from the filtered Exhibit view.

- Log in as a Docket clerk
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)


Expected Results
- [x] When clicking on the Exhibit Document title, the Document Preview opens, and you can view the document
- [x] Docket Clerk can seal the Exibit document from the filtered view on the docket record
- [x] Docket Clerk can edit the Exhibit document from the filtered view on the docket record 


#### 3) Court user can view/interact with documents on the docket record from the filtered Exhibit view.

- Log in as a Court User (be sure to test with various Court user roles)
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)


Expected Results
- [x] When clicking on the Exhibit Document title, the Document Preview opens, and you can view the document


#### 4) Court user can easily change between filtered Exhibit view, and the All Documents View

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In the new View Filter, select Exhibits
- Switch back to All Documents

Expected Results
 - [x] **NEW FUNCTIONALITY** - Docket record quickly reloads to show only Exhibits/All Documents depending on what filter the user has selected.


#### 5) Court user Filters for Exhibits only on the docket record; Sorts by other fields

-  Log in as any Court user (be sure to test with various court user roles)
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In the new View Filter, select Exhibits
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Exhibits sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Exhibits is selected in the View Filter.


#### 6) Parties on a case an choose to view only docket entries related to Exhibits on the docket record of a case.

This test has some set up:
- Log in as a docket clerk
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In one of those cases, add a test petitioner, a test IRS respondant, and a test private practitioner

- Log in as a Petitioner 
- Navigate to the case that you were just added to
- In the new View Filter, select Exhibits

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display exhibit documents (EXH, PTE, HE, TE, M123), and does not show other document types.

*Repeat this test with IRS and Private Practitioner roles

#### 7) Party on a case filters for Exhibits only on the docket record; Sorts by other fields

- Log in as as a petitioner
- Navigate to the case that has Exhibits that you got access to in the previous test
- In the new View Filter, select Exhibits
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Exhibits sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Exhibits is selected in the View Filter.

*Repeat this test with IRS and Private Practitioner roles


#### 8) Docket Clerk seals an Exhibit from the public; Parties on the case can filter and view the sealed Exhibit documents from the filtered docket record view

- Log in as a Docket Clerk
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In one of those cases, seal some of the exhibit documents to the public
- Next, log in as a party to the case
- Navigate to the case where you sealed documents
- Filter by the new Exhibit view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display exhibit documents (EXH, PTE, HE, TE, M123), and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Exhibit documents
- [x] Sealed Exhibit document is hyperlinked
- [x] When clicking on the Sealed Exhibit Document title hyperlink, the Document Preview opens, and you can view the document

#### 9) Docket clerk seals an Exhibit from the public and parties on the case; Parties on the case can filter and see that there is a sealed Exhibit document on the docket record view, but are unable to view it.

- Log in as a Docket Clerk
- Navigate to a case that has Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In one of those cases, seal some of the exhibit documents to the public and parties on the case
- Next, log in as a party on the case
- Navigate to the case where you sealed documents
- Filter by the new Exhibit view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display exhibit documents (EXH, PTE, HE, TE, M123), and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Exhibit documents
- [x] Sealed Exhibit document is NOT hyperlinked
- [x] Party is unable to click on the Sealed Exhibit Document

**Comment by swongCO** [comment]
After reviewing, this is feedback from UX:

- keep the accessible "label" element (we'll note to change it on the Trial Sessions page for another story)
- change the font style of "Filter by" to match what's on the Trial Sessions page (this styling is in the design system)
- try to match the spacing between "Filter by" and the dropdown to what's on the Trial Sessions page

**Comment by swongCO** [comment]
After discussion, a Devex card was created to address standardizing the Filter by/dropdown component across Dawson.

**Comment by rosiehsmith** [comment]
For reference: https://trello.com/c/bq1n5gZT/1089-standardize-filter-by-dropdown-component

**Comment by cholly75** [comment]
Not issues, but noting for callout during demo: Filter does not revert to all exhibits if view changes. Printable docket record is still all docket entries.
