### ISSUE TITLE
Minute Sheets

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8227]
As a trial clerk or CA, so that I can easily document the occurrences that happen at trial, I need to be able to enter minute sheet information directly into DAWSON and have it generate a document to be docketed.

During a trial session, trial clerks will enter "minute sheets" (attached) for a case that document various aspects of the case and proceedings during the session. Currently, the trial clerks are filling out PDF forms, uploading them, and then sending them to Docket for addition to the docket record.

Given that much of the information on these forms is already attached to the case and trial session in DAWSON, and to streamline the process for the Court, we would like a way for trial clerks to enter the necessary information _directly_ into DAWSON and have DAWSON generate a PDF form for eventual docketing. 

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

Possible breakdown of stories: https://docs.google.com/document/d/1jcKaUWYEyaBT3xyBEu8KoOMAscK1_w3-dPvOoGZsL3w/edit?usp=sharing

Mockups of the flow and form:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakcwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4d88ded8ed324643149597e508ba38f99ca82fd6/Session%20info%20-%20minutes%20link%20page.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakswIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8d8878a0c6ea47eb47c3c6c8b63baf344057da1b/accordions%20-%20collapsed.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBak8wIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c6ce6f301bb7cd5787304f43c23fdbc34a3d7260/Prepop%20-%20no%20selections.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbiswIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b4f66f0b6c825c87fd2d180823ecf39d14f758c4/Send%20to%20docket%20modal.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb0swIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66bdad078bf96452c61b0d8256ac94e2fa0d268f/Send%20to%20docket%20success%20banner.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb2EwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5af427e43f641d3967264a2ac2b053f3567520c6/PDF%20-%20pg1.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3EwIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ac421dbf1559a708a6d4c4dd245f5d3b8d049f5/PDF%20-%20pg2.png)
