### ISSUE TITLE
Admission Clerk: Practitioner Documentation Upload

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8244]
As an admissions clerk, so that I can associate documentation filed with the court, I need to be able to associate files with practitioner records in DAWSON.

When a practitioner is admitted to the court, several types of documentation (both practitioner and court-issued) are tracked for them. Currently this documentation is tracked in email and on shared drives, divorced from the practitioner record in DAWSON.

We would like the ability for admissions clerks to upload and categorize a file and associate it with a specific practitioner record in DAWSON.  We also need to be able to view the uploaded documents for a given practitioner.

## Acceptance Criteria

File Upload:
* Admissions clerk can select a single file to upload to a single practitioner record in DAWSON
* Admissions clerk must assign the file a category from the following list at the time of upload:
  - Application
  - Certificate of Good Standing 
     - If this option is selected, user must choose a U.S. state/territory/commonwealth/possession as well
  - Fee Receipt
  - Admission Certificate
  - Reference Inquiry
  - Response to Reference Inquiry
  - Disciplinary
  - Change of Name
  - Exam-Related
  - Miscellaneous
* Admissions clerk can add a free text description to the file at the time of upload
* Uploaded file is associated to that practitioner record in DAWSON
* File types supported for upload include PDF, MS-Word, and image files
* File and Category are required fields for uploading; if the record saved does not have both of these fields populated, the user receives a validation error
* If the Add File UI is canceled out of, the user receives the "Are you sure?" modal used elsewhere in the application. 

------------------------

* Doc UI is accessible from the Practitioner Detail page for admission clerk users
  - Doc UI is NOT part of the Practitioner Detail page itself
* Doc UI displays all files uploaded and associated with the practitioner record
* Files are displayed with the following information about each one:
  - File name
  - Category
  - Description
  - Date uploaded
* Files are displayed in date order, ascending by default
* Individual files can be downloaded from the UI
* Individual files can be uploaded from the UI (see below)
* Added to support UX design: "Details" title is present on Practitioner page for non-Admissions Clerk users

## Notes
* The actual files do not have to be editable in DAWSON; the user only needs to be able to download and open them.

## Tasks
- [x] Add tab (Details, Documentation) to practitioner detail UI (Rosie, Rachel)
- [x] Add Table to Practitioner Detail > Documentation tab
- [x] “Add File” UI 
- [x] “Add File” validation
- [x] Practitioner detail tab, right align `Print case list` button with card
- [x] Display all practitioner documents
- [x] Add a cancellation modal
- [x] Handle case related to role
- [x] rename Document to PractitionerDocument to be less confusing
- [x] add link to document name to download that document
- [x] add default sort for documnetation tab
- [x] update any applicable unit tests
- [x] add pa11y tests for documentation tab
- [x] update pa11y tests for details tab
- [x] add/update e2e tests
- [x] limit character limit in description box
- [x] enable text wrapping for desc. box
- [x] disable loading of documentation tab for non-admissions-clerk users

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX specs

![Practitioner details page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7221740e-1a58-40ff-a43e-a4a7bc81a887)
1. Add two tabs to this page - "Details" & "Documentation"
2. Use the existing styling and implementation of tabs
3. Icon links move to the tab content area below the tabs

![Practitioner documentation page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d41b06f7-961c-45f3-8ff2-01108952b575)
On the documentation page:
1. Add an icon link on the right - [plus] icon "Add file"
2. Add a table with these columns - Date Uploaded, File Name, Category, Description
3. Add a list counter above the table on the right (use trial session info active/inactive/all cases as a template for spacing above the table)

![Add file page - 1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/32545ecc-3a38-4d13-bf93-f051473bd56c)

1. When "Add file" link is clicked, display this page
2. Use existing form elements

![Add file page - 2 file uploaded.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/de32c33c-ab41-4699-bb59-3dae8a88a72d)

- Display the uploaded file name with "Change" link after

![Add file page - 3 category dropdown.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/716d1333-e7e7-44e9-8a40-bbe7fc3ba7fd)

1. When category dropdown is clicked, display the list of options<s>, with ">" at the end of Certificate of Good Standing</s>
2. When Certificate of Good Standing is selected, display another dropdown field with a list of states and territories
3. The states and territories should be spelled out in the dropdown list and in the table

![Add file page - 5 dropdown selected.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7ae89c91-a935-4f35-a061-907e622f57e4)

1. When "Add File" button is clicked, add the file to the first row of the table
2. Add a green confirmation banner at the top of the Documentation page - "The file has been added."

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Admissions Clerk searches for a practitioner; two tabs are available on Practitioner page. 

- Log in as an Admissions Clerk
- Click on the Advanced tab in the upper right of the screen
- Click on the Practitioner Tab
- Search for a Practitioner by either typing in a name or adding a BAR number
- If you searched by Practitioner name, click on the BAR number of the Practitioner you would like to view.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Practitioner page now has two tabs. The Details tab is the default view; the second tab is labeled as Documentation.
- [x] **NEW FUNCTIONALITY** - The existing page for all of the practitioner information is now all under the Details tab. (Practitioner information card, Contact information card, Admissions information card, Practitioner notes card.)


#### 2) Admissions Clerk Views the Documentation tab; Page includes ability to add new files, table headers are present, but table is empty.

- Continuing from the previous test
- Click on the Documentation tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - New table is present, but table is empty (no documents will be there yet)
- [x] **NEW FUNCTIONALITY** - Column Headers include Date Uploaded, File Name, Category, Description.
- [x] **NEW FUNCTIONALITY** - List counter is present


#### 3) Admissions Clerk can upload a new file.

Note - You will need to complete Test cases 3 and 4 multiple times to test all of the file types supported (PDF, MS Word, Image files)

- Continuing from the previous test
- Click on the Add File link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Add File page appears for the user
- [x] **NEW FUNCTIONALITY** - Admissions clerk can choose and upload a file (be sure to test with PDF, MS Word, and Image files)
- [x] **NEW FUNCTIONALITY** - Admissions clerk can click a change link, and select a different file to upload
- [x] **NEW FUNCTIONALITY** - Admissions clerk can select a category (be sure that all categories that are listed in the AC are present
- [x] **NEW FUNCTIONALITY** - If Certificate of Good Standing is selected, user can select the appropriate state or US Territory
- [x] **NEW FUNCTIONALITY** - Admissions clerk can add in a description (this field should be optional, and not required)
- [x] **NEW FUNCTIONALITY** - Add file button and Cancel button is present on this page


#### 4) Admissions clerk adds a new file to be associated with the Practitioner.

Note - You will need to complete Test cases 3 and 4 multiple times to test all of the file types supported (PDF, MS Word, Image files)

- Continuing from the previous test
- Click the Add File button

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is navigated back to the Documentation tab
- [x] **NEW FUNCTIONALITY** - Green confirmation banner at the top of the Documentation page states, "The file has been added."
- [x] **NEW FUNCTIONALITY** - The table is now populated with one row, and includes the information about the document that you just uploaded.
- [x] **NEW FUNCTIONALITY** - Date filed is today's date
- [x] **NEW FUNCTIONALITY** - File Name matches the file name 
- [x] **NEW FUNCTIONALITY** - Category matches the category that you indicated upon upload
- [x] **NEW FUNCTIONALITY** - Description matches the description that you added (if you added some in the previous test case)
- [x] **NEW FUNCTIONALITY** - Edit/Delete buttons are not yet present on the right side of the table row for the document (future story)
- [x] **NEW FUNCTIONALITY** - Count displays the total number of documents that you have uploaded



#### 5) Admissions Clerk cancels out of the Add File page; Modal asks for confirmation; If "Yes, Cancel" is selected, Clerk is returned to the Documentation tab.

- From the Practitioner Documentation tab, click the Add File link
- Upload a file, and fill in the details about the document
- Click Cancel

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal appears that asks "Are you sure you want to cancel? If you cancel, your form selections will be lost."
- [x] **NEW FUNCTIONALITY** - When clicking Yes, Cancel, Admissions clerk is navigated back to the Documentation tab



#### 6) Admissions Clerk cancels out of the Add File page; Modal asks for confirmation; If "No, take me back" is selected, Clerk is returned to the Add File Form.

- From the Practitioner Documentation tab, click the Add File link
- Upload a file, and fill in the details about the document
- Click Cancel

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal appears that asks "Are you sure you want to cancel? If you cancel, your form selections will be lost."
- [x] **NEW FUNCTIONALITY** - When clicking "No, Take me back" is selected, Admissions clerk is navigated back to the Add File form.


#### 7) Admissions Clerk uploads a file, fails to add a category; upon clicking the "Add file" button, receives validation error.

- From the Practitioner Documentation tab, click the Add File link
- Upload a File
- Do not select any information in the Category dropdown.
- Click the Add file button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Validation error appears that states, "Please correct the following errors on the page: Enter a Category"




#### 8) Admissions Clerk clicks Add file from the Practitioner Documentation page, fails to add a document; adds in the Category and description; Clicks Add file; receives validation error.

- From the Practitioner Documentation tab, click the Add File link
- Do not upload a file
- Select an option in the Category dropdown.
- Click the Add file button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Validation error appears that states, "Please correct the following errors on the page: Upload a file"




#### 9) Admissions Clerk Downloads the files for viewing from the Documentation Page.

- From the Practitioner Documentation tab, click on the link to a Filename for a document.

Expected results:
- [x] **NEW FUNCTIONALITY** - Document downloads to the users default download folder on their device.
- [x] **NEW FUNCTIONALITY** - When the download completes, User can open the document for viewing in the appropriate viewer.

*Be sure to test this with all the file types (PDF, MS Word, Image Files)


#### 10) Documents listed are in ascending order, by date uploaded.

- Navigate to the Practitioner Documentation tab
- Ensure that there are a handful of documents that have been uploaded for the practitioner

Expected Results:
- [x] **NEW FUNCTIONALITY** - The first document that was uploaded will be at the top of the list
- [x] **NEW FUNCTIONALITY** - The last document that was uploaded will be at the bottom of the list.



#### 11) Court User (Not an Admissions Clerk) accesses the Practitioner tab; Documentation tab is not available for other Court Users

- Log in as a variety of Court Users (besides an Admissions Clerk) 
- Click on the Advanced link in the upper right corner of the screen
- Click on the Practitioner tab
- Search for a Practitioner by either typing in a name or adding a BAR number
- If you searched by Practitioner name, click on the BAR number of the Practitioner you would like to view.

Expected Results
- [x] The Documentation tab is not showing for the other court user

**Comment by cholly75** [comment]
@ttlenard - let's test for compatibility with .TIFF files when testing to see about legacy support.

**Comment by swongCO** [comment]
After discussion with @rachelschneiderman and @rosiehsmith on Friday, we will move the icon links that are at the right to below the horizontal tab line so content within each tab is displayed. After a cursory exploration in Dawson, the pattern is that icon links that are tab agnostic are above the horizontal tab line. UX will update the mockups to reflect this change. cc @liadmccabe

**Comment by swongCO** [comment]
Removed from UX specs: File names are linked and when clicked, opens a new tab/page with the document and functionality to print and download
File will download onto user's default folder as specified in test case ustaxcourt/ef-cms-flexion#9.

**Comment by swongCO** [comment]
UX feedback:
1. We did not get the green confirmation banner after adding a file
2. Can the territories in the dropdown be spelled out like the states?
3. <s>When a file is selected for upload, clicking the Change link removes the file and returns to the default state where no file is selected (screenshot below):
- can the interaction change to display the system dialog where the user can select a file instead?
- if not, change the link text to "Remove"</s>
![Screen Shot 2022-10-19 at 10.54.02 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/64d7dfa9-e169-461d-bbdd-628a03da3472)

**Comment by swongCO** [comment]
During UX Review, it was discovered that the downloaded word doc (docx) did not have the same file name as the file that was uploaded. @rgoshen looked into it and informed that the behavior can be changed so that the downloaded file names match the uploaded file names.
cc @liadmccabe @cholly75 @ttlenard

**Comment by ttlenard** [comment]
@codyseibert @rgoshen @jasonfu9966 Testing Feedback 10/28/2022

It appears that there is a caching issue?

Navigate to a Practitioner (I was uploading documents for SH0424)
From the Documentation tab for this practitioner (or from the Add File screen), click on the Advanced link.
Search for a different practitioner (I used Myers Newton Massengill)
Click on the BAR number for Myers to open this practitioners record

Results - the documentation tab displays the other practitioners documents. The only way to get the other practitioners documents to not show is to click on the details tab, and then back over to the Documentation tab.

Let me know if you need more clarification on the issue. Happy to chat more about this.

**Comment by ttlenard** [comment]
Testing Feedback 11/1/2022

No longer seeing the caching issue!
