### ISSUE TITLE
Petitioner:  Visibility Across Consolidated Case Group

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8251]
As a petitioner, so that I can stay informed about the other cases in my consolidated group, I need party-level visibility into cases in my consolidated group, even if I am not formally associated to them as a party.

The USTC policy regarding consolidated cases is that since filings in any case in the group may materially affect other cases in the group then parties should have full visibility across all cases in the group in which their own case is consolidated.

Functionally, what this means is that a logged-in petitioner in a consolidated group should be able to view and access the docket entries of all other cases in the group as if they were a party to the case w/r/t visibility rules.

Note that this does not extend other functions available to formal parties to the case to the petitioner.

## Pre-Conditions
ustaxcourt/ef-cms#8253

## Acceptance Criteria
* When viewing a case in their consolidated group that the petitioner is not formally associated with:
   - The petitioner can view the case record as if they were a party to the case
   - The petitioner can view individual documents on the docket record as if they were a party to the case
   - The petitioner can view individual documents on the docket record that are 'sealed to the public'
   - The petitioner cannot view individual documents on the docket record that are 'sealed to the public and parties'
   - The petitioner cannot initiate any other filings on the case
* If the case is sealed at the case level, the petitioner is treated as if a party to the case were trying to view the case
* If a petitioner is added to a case in a consolidated group, then the above visibility rules immediately take effect
* If a case is removed from the consolidated group, then a petitioner who is not a party to that case immediately loses party visibility as above, and visibility to the case and docket record revert to the current state (i.e., general public)
* If the petitioner is removed from all cases in the consolidated group, then visibility to all cases and docket records in the group revert to the current state (i.e., general public)

## Tasks

- [x] Add links to consolidated group lead and member cases from Dashboard (https://github.com/flexion/ef-cms/pull/9652)
- [x] Add treatment as a party to the case on Case Details page
   - [x] Provide information to Case Details page about what cases the user will be able to view
      - [x] Implement (https://github.com/flexion/ef-cms/pull/9657)
      - [ ] Test
   - [x] Implement visibility rules based on sealed/unsealed state and the user's authorization
   - [x] Refactor `formattedDocketEntries`
   - [x] ? Refactor link visibility ?

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner that is a party on one case in a consolidated group can view and interact with the case record on a different case in the consolidated group even though they are not a party to the case.

Preconditions: Petitioner is a party on a case or cases in a consolidated group, but not ALL cases.

- Log in as a Petitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL to a different case in the consolidated group that you are not associated with.

Expected Results:
- [x] The documents on the docket record are active hyperlinks
- [x] After clicking on a hyperlinked document, the document opens and the Petitioner can view the document
- [x] The Case information tab is present for the petitioner user
- [x] After clicking on the Case information tab, the petitioner can view the Overview tab and the Parties tab 
- [x] The "File a Document" button in the upper right hand corner of the case is not present 


#### 2) Docket Clerk seals a document to the public on a case in the consolidated group; Petitioner not associated with the case, but that is a party on a different case in the consolidated group, can view the sealed to the public document as if they were a party to the case.

Preconditions: Docket Clerk Seals a document to the public on a case in the consolidated group. Be sure that the petitioner you are testing with is not a party on the case.

- Log in as a Petitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk had sealed a document on.

Expected Results:
- [x] Red lock icon is next to the document that the docket clerk sealed
- [x] Document that is sealed to the public has a hyperlink
- [x] Petitioner can click on the hyperlink and open/view the sealed to the public document.


#### 3) Docket Clerk seals a document to the public and parties to a case in the consolidated group; Petitioner not associated with the case, but that is a party on a different case in the consolidated group, cannot view the sealed to the public and parties to the case document.

Preconditions: Docket Clerk Seals a document to the public and parties on a case in the consolidated group. Be sure that the petitioner you are testing with is not a party on the case.

- Log in as a Petitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk had sealed a document on.

Expected Results:
- [x] Red lock icon is next to the document that the docket clerk sealed
- [x] Document that is sealed to the public and parties to the case does NOT have a hyperlink
- [x] Petitioner cannot open/view the sealed to the public and parties to the case document.


#### 4) Docket Clerk seals the entire case; Petitioner not associated with the case, but that is a party on a different case in the consolidated group, can view the case record as if they were a party to the case.

Preconditions: Docket clerk has sealed a case in the consolidated group. Be sure that the Petitioner that you are testing with is not a party on the case.

- Log in as a Petitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk sealed in the consolidated group that you are not associated with.

Expected Results:
- [x] Red banner at the top indicating that the case is sealed.
- [x] The documents on the docket record are active hyperlinks
- [x] After clicking on a hyperlinked document, the document opens and the Petitioner can view the document
- [x] The Case information tab is present for the petitioner user
- [x] After clicking on the Case information tab, the petitioner can view the Overview tab and the Parties tab 
- [x] The "File a Document" button in the upper right hand corner of the case is not present 


#### 5) Petitioner that is associated with a case in a consolidated group of cases can view and interact with their case record; can file documents.

- Log in as a Petitioner
- Navigate to the case in the Consolidated group that you are associated with

Expected Results:
- [x] The documents on the docket record are active hyperlinks
- [x] After clicking on a hyperlinked document, the document opens and the Petitioner can view the document
- [x] The Case information tab is present for the petitioner user
- [x] After clicking on the Case information tab, the petitioner can view the Overview tab and the Parties tab 
- [x] The "File a Document" button in the upper right hand corner of the case is present, and you can file documents to your case.


#### 6) Docket Clerk removes a case from the consolidated group; Petitioner that was previously able to view and interact with the case record no longer has ability to view the documents on the docket record; no longer has access to case information tab.

Preconditions: Docket Clerk removes a case from the consolidated group. Be sure that the case you remove is NOT the case that the Petitioner you have been testing with is associated with.

Part 1
- Log in as a Petitioner
- Navigate to the case in the Consolidated Group that you are associated with.
- Click on the Case information tab

Expected results:
- [x] The case that the docket clerk removed is no longer listed on the Consolidated Cases Card.

Part 2
- Manipulate the URL by entering the docket number of the case that the Docket Clerk removed from the consolidated group

Expected Results
- [x] The Case information tab is not present for viewing
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).

Part 3
- Log out as the Petitioner
- Navigate to the case that the docket clerk removed from the group by using the Search tool

Expected Results
- [x] The non-logged in user retains the "public view" of the docket record
- [x] The Case information tab is not present for viewing
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).


#### 7) Petitioner that is associated with one consolidated group does not have access to view the documents in a different set of consolidated cases.

- Log in as the Petitioner that has access to one or more cases in a consolidated group.
- Click on the docket number of the consolidated case that you have access to so that the case record opens
- Manipulate the URL by adding in a consolidated case docket number of a different consolidated group, for a case/group that you are not associated with.

Expected Results:
- [x] The Case information tab is not present for viewing
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).


#### 8) Docket Clerk removes a Petitioner from a Case that is part of a Consolidated group of cases; Petitioner is no longer able to view and interact with the case records in the Group; no longer has ability to view the documents on the docket record; no longer has access to case information tab.

Preconditions: Docket Clerk removes a Petitioner from all cases that they were previously associated with in a consolidated group.

Part 1
- Log in as the Petitioner that used to be associated with a case or cases in a consolidated group.

Expected Results:
- The Consolidated group of cases no longer appears in the "My Cases" list.

Part 2
- Manipulate the URL by adding in a consolidated case docket number for a case/group that you used to be associated with.

Expected Results:
- [x] The Case information tab is not present for viewing
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).


#### 9) Regression test this story with the Feature Flag set to OFF.

**Comment by liadmccabe** [comment]
We tested with 17018-21 and 37263-21.  Each of the cases had different parties, but when we tested Step 4 (sealing the lead case) Petitioner 2 was unable to view the documents -- therefore test fails.

**Comment by swongCO** [comment]
During UX review, we found what may be a bug. After some digging, I think I have reliable steps to reproduce.

1. Log in as a docket clerk.
2. Go to a case.
3. Go to Case Information > Parties and click Add Party.
4. Before filling out any fields, note the address fields, specifically City and State. They should look like this:
5. ![Screen Shot 2023-01-13 at 2.33.36 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d7b3d617-0505-4e9a-82cb-723c26f7e298)
6. Fill out the role type and name.
7. Click on Use existing address.
8. Note that there's a dropdown for existing addresses and the State dropdown becomes an optional text field:
![Screen Shot 2023-01-13 at 2.32.35 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3d6501d1-d262-4bb7-be46-e2bfc2f6dc4f)
9. Click on Use existing address again.
10. Note that the State text field persists instead of reverting back to the dropdown:
![Screen Shot 2023-01-13 at 2.32.54 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1375389c-5f4c-4716-a0f1-f0d54387f73a)
11. Fill out the required fields and click Save.
12. This error is displayed at the top:
13. ![Screen Shot 2023-01-13 at 12.49.28 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4a278256-f051-4782-ae94-8d59af5e0dc8) 
14. The state field is optional but if you enter anything other than the state abbreviation in all caps, it's not validated.
15. There is no country type on the page.
16. Even when all fields are correctly entered, the error with the country type persists and we were unable to proceed.

**Comment by ttlenard** [comment]
@swongCO I have seen this behavior before, so I don't think that this was introduced as part of this story.  I think all you have to do to get around it is to select United States as the Country and it allows you to save (Country type is the Country field - your ustaxcourt/ef-cms-flexion#15 above).  Once you select the US from the Country dropdown, then it formats the state appropriately. I haven't ever done your workflow, but I have seen this behavior happen when you have a Petitioner and Spouse case and you click the "use existing address" box.
