### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8252]
As a practitioner, so that I can stay informed about the other cases in my consolidated group, I need party-level visibility into cases in my consolidated group, even if I am not formally associated to them as a party.

The USTC policy regarding consolidated cases is that since filings in any case in the group may materially affect other cases in the group then parties should have full visibility across all cases in the group in which their own case is consolidated.

Functionally, what this means is that a logged-in practitioner representing a party in a consolidated group should be able to view and access the docket entries of _all_ other cases in the group and be treated as if they counsel attached to the case w/r/t visibility rules.

The story affects *both* IRS and private practitioners.

Note that this does *not* extend other functions available to formal parties to the case to the practitioner. 

## Pre-Conditions
ustaxcourt/ef-cms#8257

## Acceptance Criteria
* When viewing a case in their consolidated group that the IRS or private practitioner is not associated with:
  - The practitioner can view the case record as if they were a party to the case
  - The practitioner can view individual documents on the docket record as if they were counsel to a party to the case
  - The practitioner can view individual documents on the docket record that are 'sealed to the public'
  - The practitioner cannot view individual documents on the docket record that are 'sealed to the public and parties'
  - The practitioner can still invoke the Request Access to Case functionality
  - The practitioner cannot initiate any other filings on the case 
* If the case is sealed at the case level, the practitioner is treated as if counsel to a party to the case were trying to view the case
* If a practitioner is added to a case in a consolidated group, then the above visibility rules immediately take effect
* If a case is removed from the consolidated group, then a practitioner who is not attached as counsel to that case immediately loses visibility as above, and visibility to the case and docket record revert to the current state (i.e., general public)
* If a practitioner is removed from all cases in the consolidated group, then their visibility to all cases and docket records in the group revert to the current state (i.e., general public)

## Notes
- isAuthorizedToGetCase is a flag to check if the user has permission to do stuff with a case.
- isAssociatedWithCase is another flag to check if the user can do stuff with a case.
- If you have access to a case you general have the same permissions as everyone else.

## Tasks
- [ ] Modify getCasesForUserInteractor to return true on isRequestingUserAssociated
- [ ] For isAuthorizedToGetCase check if it is a consolidated case. If it is then go through all parties of all cases to see if the user is a party to any of the member cases.
- [ ] Verify serving an answer on a consolidated case brings up a modal where we can select individual member cases.

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

Note that each test will need to be completed twice, once with a Private Practitioner and once with an IRS Practitioner.

#### 1) Practitioner that is a party on one case in a consolidated group can view and interact with the case record on a different case in the consolidated group even though they are not a party to the case.

Preconditions: Practitioner (IRS and Private Practitioner) is a party on a case or cases in a consolidated group, but not ALL cases.

- Log in as a Private Practitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL to a different case in the consolidated group that you are not associated with.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The documents on the docket record are active hyperlinks
- [x] **NEW FUNCTIONALITY** - After clicking on a hyperlinked document, the document opens and the Practitioner can view the document
- [x] **NEW FUNCTIONALITY** - The Case information tab is present for the practitioner user
- [x] **NEW FUNCTIONALITY** - After clicking on the Case information tab, the practitioner can view the Overview tab and the Parties tab 
- [x] The "Request Access to Case" button in the upper right hand corner of the case is present 

*Repeat this test with an IRS Practitioner


#### 2) Docket Clerk seals a document to the public on a case in the consolidated group; Practitioner not associated with the case, but that is a party on a different case in the consolidated group, can view the sealed to the public document as if they were a party to the case.

Preconditions: Docket Clerk Seals a document to the public on a case in the consolidated group. Be sure that the practitioner you are testing with is not a party on the case.

- Log in as a Private Practitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk had sealed a document on.

Expected Results:
- [x] Red lock icon is next to the document that the docket clerk sealed
- [x] **NEW FUNCTIONALITY** - Document that is sealed to the public has a hyperlink
- [x] **NEW FUNCTIONALITY** - Practitioner can click on the hyperlink and open/view the sealed to the public document.

*Repeat this test with an IRS Practitioner


#### 3) Docket Clerk seals a document to the public and parties to a case in the consolidated group; Practitioner not associated with the case, but that is a party on a different case in the consolidated group, cannot view the sealed to the public and parties to the case document.

Preconditions: Docket Clerk Seals a document to the public and parties on a case in the consolidated group. Be sure that the practitioner you are testing with is not a party on the case.

- Log in as a Private Practitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk had sealed a document on.

Expected Results:
- [x] Red lock icon is next to the document that the docket clerk sealed
- [x] Document that is sealed to the public and parties to the case does NOT have a hyperlink
- [x] Practitioner cannot open/view the sealed to the public and parties to the case document.

*Repeat this test with an IRS Practitioner


#### 4) Docket Clerk seals the entire case; Practitioner not associated with the case, but that is a party on a different case in the consolidated group, can view the case record as if they were a party to the case; Cannot File documents on Sealed Case.

Preconditions: Docket clerk has sealed a case in the consolidated group. Be sure that the Practitioner that you are testing with is not a party on the case.

- Log in as a Private Practitioner
- Navigate to the case in the Consolidated group that you are associated with
- Click on the Case Information tab
- Click on the docket record URL for the case that the Docket Clerk sealed in the consolidated group that you are not associated with.

Expected Results:
- [x] Red banner at the top indicating that the case is sealed.
- [x] **NEW FUNCTIONALITY** - The documents on the docket record are active hyperlinks
- [x] **NEW FUNCTIONALITY** - After clicking on a hyperlinked document, the document opens and the Practitioner can view the document
- [x] **NEW FUNCTIONALITY** - The Case information tab is present for the practitioner user
- [x] **NEW FUNCTIONALITY** - After clicking on the Case information tab, the practitioner can view the Overview tab and the Parties tab 
- [x] The "Request Access to Case" button in the upper right hand corner of the case is NOT present. 

*Repeat this test with an IRS Practitioner


#### 5) Practitioner that is associated with a case in a consolidated group of cases can view and interact with their case record; can file documents.

- Log in as a Private Practitioner
- Navigate to the case in the Consolidated group that you are associated with

Expected Results:
- [x] The documents on the docket record are active hyperlinks
- [x] After clicking on a hyperlinked document, the document opens and the Practitioner can view the document
- [x] The Case information tab is present for the practitioner user
- [x] After clicking on the Case information tab, the practitioner can view the Overview tab and the Parties tab 
- [x] The "File a Document" button in the upper right hand corner of the case is present, and you can file documents to your case.

*Repeat this test with an IRS Practitioner


#### 6) Docket Clerk removes a case from the consolidated group; Practitioner that was previously able to view and interact with the case record no longer has ability to view the documents on the docket record; no longer has access to case information tab.

Preconditions: Docket Clerk removes a case from the consolidated group. Be sure that the case you remove is NOT the case that the Practitioner you have been testing with is associated with.

Part 1
- Log in as a Private Practitioner
- Navigate to the case in the Consolidated Group that you are associated with.
- Click on the Case information tab

Expected results:
- [x] The case that the docket clerk removed is no longer listed on the Consolidated Cases Card.


Part 2
- Manipulate the URL by entering the docket number of the case that the Docket Clerk removed from the consolidated group

Expected Results
- [x] The Case information tab is not present for viewing for the private practitioner but is available to IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.

Part 3
- Navigate to your My Cases Dashboard
- Enter the docket number of the case that the Docket Clerk removed from the consolidated group.

Expected Results
- [x] The Case information tab is not present for viewing for the private practitioner but is available to IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.

*Repeat this test with an IRS Practitioner


#### 7) Practitioner that is associated with one consolidated group does not have access to view the documents in a different set of consolidated cases.

Part 1
- Log in as the Private Practitioner that has access to one or more cases in a consolidated group.
- Click on the docket number of the consolidated case that you have access to so that the case record opens
- Manipulate the URL by adding in a consolidated case docket number of a different consolidated group, for a case/group that you are not associated with.

Expected Results:
- [x] The Case information tab is not present for viewing for the private practitioner but is present for the IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.


Part 2
- Navigate to your My Cases Dashboard
- Enter the docket number of the case that is part of a different consolidated group of cases

Expected Results:
- [x] The Case information tab is not present for viewing for the private practitioner but is present for the IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.

*Repeat this test with an IRS Practitioner


#### 8) Docket Clerk removes a Practitioner from a Case that is part of a Consolidated group of cases; Practitioner is no longer able to view and interact with the case records in the Group; no longer has ability to view the documents on the docket record; no longer has access to case information tab.

Preconditions: Docket Clerk removes a Practitioner from all cases that they were previously associated with in a consolidated group.

Part 1
- Log in as the Private Practitioner that used to be associated with a case or cases in a consolidated group.

Expected Results:
- The Consolidated group of cases no longer appears in the "My Cases" list.


Part 2
- Manipulate the URL by adding in a consolidated case docket number for a case/group that you used to be associated with.

Expected Results:
The Case information tab is not present for viewing for the private practitioner but is present for the IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.


Part 3
- Navigate to your My Cases Dashboard
- Enter the docket number of the case that you used to be associated with.

Expected Results:
The Case information tab is not present for viewing for the private practitioner but is present for the IRS Practitioner.
- [x] The only documents on the docket record that are active links are Orders (and opinion, if present).
- [x] The "Request Access to Case" button is available in the upper right-hand corner.

*Repeat this test with an IRS Practitioner


#### 9) Regression test this story with the Feature Flag set to OFF.

**Comment by ttlenard** [comment]
Testing feedback. @rgoshen, @zRogersFlexion, @TomElliottFlexion 

On test case 1, the last expected result is not quite right for IRS practitioners.  The button in the top right is stating "File First IRS Document" rather than "Request Access to Case".  I did double check and for non-consolidated cases, when an IRS practitioner is requesting access to a case that already has IRS filings on it, the button still says "Request Access to Case".  I think this is only related to Consolidated cases and the new visibility, and it seems to only be related to the IRS. 

Here is a screen grab of an IRS practitioner looking at a case in the group that they are not a party to.  It says File First  IRS document, but you can see that there is an Answer already filed on this consolidated case.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cc85fb63-2e0e-49a2-bd0f-fede76fb4655)

**Comment by ttlenard** [comment]
Testing Feedback - Found another issue while testing today.  Just talked with Tom and Rick and they see where the issue is in the code! Thanks guys!

Here is the breakdown:
Test Case 8: Docket Clerk removes a Practitioner from a case. When the Practitioner attempts to search for any case in the Consolidated group, they get a 400 error.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/6886e4b2-fcbe-4749-8fc9-1fe0da0d029f)

**Comment by ttlenard** [comment]
@rgoshen @TomElliottFlexion @zRogersFlexion 

Testing feedback 2/22/23.  All test cases are now passing! Thank you!
