### ISSUE TITLE
Petitioner: Add Consolidated Card to Case Information Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8253]
As a petitioner, so that I can easily see which cases are in the consolidated group my current case is in, I need to see the Consolidated Cases card when viewing the Case Information - Overview for my case.

As part of making filing in consolidated cases more user-friendly to external parties, we would like the Consolidated Cases card that currently appears to Court users in the Case Information - Overview screen for a case in a consolidated group (see screenshot below) to also appear for petitioners when viewing the Case Information - Overview screen for a case in a consolidated group. There are some minor UI adjustments for the petitioner view of this card, as listed in the AC.

## Acceptance Criteria
* Consolidated Case card is displayed on the Case Information - Overview screen when the case is the Lead or Member case of a consolidated group
* Card lists the docket numbers and Petitioners of cases in the consolidated group
* Docket numbers are ordered/displayed in the usual fashion (ascending by docket number)
* Docket numbers on the card are hyperlinked to docket record view of those cases
  - Docket records of linked cases display exactly as if they had been navigated to via search by the petitioner w/r/t visibility
* Card does NOT grant the ability to add or remove cases from the consolidated group

## Notes
Consolidated Cases card as it displays for Court users:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/dedcc936-1107-4ef6-8c2d-e81e97e60e16)

Note: The Add/Remove Cases links should NOT display for petitioners.

## Tasks

- [x] Display Consolidated Cases Card in Case Info tab for petitioners
    - [x] ONLY show when case is in a consolidated group
- [x] Verify add and remove buttons do not show up
- [x] Verify Case Detail view shows up as expected
  - [x] Ask Holly/Tenille to clarify AC 4
- [x] Fix mobile view styling
https://github.com/ustaxcourt/ef-cms/pull/2652

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner is associated with the a Case in a Consolidated group of cases; Consolidated Cases Card is available on the Case information tab.

Preconditions: Petitioner is associated with a case in a Consolidated Group.

- Log in as a Petitioner
- Click on the Docket Number of the case you have access to in the consolidated group from the My Cases list
- Click on the Case Information Tab

Expected Results:
- [x] Consolidated Cases card is now available on this page
- [x] Card lists the docket numbers and Petitioners of cases in the consolidated group (If a case is sealed and they are not a party to that case, then the Petitioners name will not appear on this list)
- [x] Docket numbers are listed in ascending order
- [x] Docket numbers are hyperlinked to docket record view of those cases
- [x] The Card does not have any links at the top to add/remove cases 


#### 2) Petitioner clicks the hyperlink to a docket number from the Consolidated Case card for a case that they are not associated with; Docket Record view displays as if Petitioner had navigated there from the Search tool.

- Continuing from the previous test
- Click on the hyperlink of one of the other cases (be sure that the petitioner is NOT associated with this case)

Expected Results
- [x] The Docket record opens, but only Orders (or opinions) are hyperlinked on the docket record
- [x] All other documents are listed, but not hyperlinked (per the user fashion if the petitioner had navigated to the case via search)




#### 3) New Consolidated Case Card can be viewed when accessing the case from a mobile device

Preconditions: Petitioner is associated with a case in a Consolidated Group.

- Log in as a Petitioner
- Click on the Docket Number of the case you have access to in the consolidated group from the My Cases list
- Click on the dropdown that states Docket Record, and then Select Case Information/Overview 

Expected Results:
- [x] Consolidated Case card is now available on this mobile page, and is formatted in such a way as to be easy to read on a mobile device
- [x] Card lists the docket numbers and Petitioners of cases in the consolidated group (If a case is sealed and they are not a party to that case, then the Petitioners name will not appear on this list)
- [x] Docket numbers are listed in ascending order
- [x] Docket numbers are hyperlinked to docket record view of those cases
- [x] The Card does not have any links at the top to add/remove cases 



#### 4) From the mobile device, Petitioner clicks the hyperlink to a docket number from the Consolidated Case card for a case that they are not associated with; Docket Record view displays as if Petitioner had navigated there from the Search tool.

- Continuing from the previous test
- Click on the hyperlink of one of the other cases (be sure that the petitioner is NOT associated with this case)

Expected Results
- [x] The Docket record opens, but only Orders (or opinions) are hyperlinked on the docket record
- [x] All other documents are listed, but not hyperlinked (per the user fashion if the petitioner had navigated to the case via search)




#### 5) Petitioner is associated with a consolidated group of cases, attempts to view a sealed case that is in a consolidated group that they are not associated with; receives standard messaging.

Preconditions: Docket clerk has sealed one of the cases in the Consolidated Group that the Petitioner is not associated with.

- Log in as a Petitioner
- Click on the Docket Number of the case you have access to in the consolidated group from the My Cases list
- Click on the Case Information Tab
- Click on the docket number hyperlink to the case that has been sealed

Expected Results:
- [x] Page indicates that the case is sealed and not accessible to the public.
- [x] **(NEWLY ADDED TEST 10/17/2022)** - Check the Case JSON from the Case information page - ensure sealed case info does not appear
- [x] **(NEWLY ADDED TEST 10/17/2022)** - Check the Case JSON after you click on the sealed case - ensure sealed case info does not appear


#### 6) (NEWLY ADDED TEST 10/22/22 Per request from Mrin via a comment) Petitioner attempts to view a sealed case that they are not associated with; receives standard messaging.

- Log in as any petitioner
- In the address bar, manipulate the URL so that you can navigate directly to a sealed case

Expected Results:
- [x] Petitioner receives the Red banner and label indicating that the case is sealed to the public.
- [x] If the console is open, the case JSON does not show Sealed case info.

**Comment by cholly75** [comment]
@ttlenard - w/r/t sealed cases on the card - let's keep them hyperlinked and pop the "This case is sealed" screen when clicked by a petitioner who is not a party to the case. This is in line with usual visibility rules (i.e., the result the general public would see if searching for the case by docket number).

**Comment by mrinsin** [comment]
After @shumway-tm and I discussed with @cholly75, we decided to also show the Sealed Case view (red banner and label saying case is sealed to the public) when an unassociated petitioner types in the url to view a sealed case (whether the case is in a consolidated group w/petitioner or not). This previously would show the following screen: ![image.png](https://images.zenhubusercontent.com/618021eb47ddde1a5ec9cbe6/7344ac43-2355-4e3a-8ec5-40366e9cc45a)

@ttlenard would you mind adding a test case for this scenario pls?

**Comment by swongCO** [comment]
UX feedback:
Mobile view is still showing the case title overlapping the docket numbers. I used a mobile simulator chrome extension. The same is happening on an iPad simulation.
![Screen Shot 2022-10-12 at 9.54.13 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cd30b3b4-2fa5-44e9-a13c-69587abc6721)

**Comment by swongCO** [comment]
UX feedback:
It looks like the columns are being centered vertically to each other. The docket number should line up with the first line of the case title. The centering is more pronounced on mobile devices.
![Screen Shot 2022-10-13 at 3.15.34 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7d95a312-eeaf-4b13-b72e-aa101f9e8bd9)
![Screen Shot 2022-10-13 at 3.15.03 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/257a8c9e-0ac7-4225-8bc8-2fff81b0307e)

**Comment by mrinsin** [comment]
@swongCO @liadmccabe could y'all please provide us with the figma slide/mockup for this view for desktop/tablet/mobile so we can make sure we get the design exactly right? I don't have an eye for UX design and so it would be easier for me to implement with a visual aid.

**Comment by swongCO** [comment]
To clarify, the design wasn't changed. If you look at the screenshot in the Notes section, the docket number aligns with the first line of the case title. The feedback is to get the alignment back to the original. Here's what it should look like when the case titles wrap:
![Cons cases card.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/324052f7-9683-499c-8b48-6265d214cbee)

**Comment by shumway-tm** [comment]
@swongCO Thank you for the screenshot. +1 @mrinsin I agree! The visual aids help significantly. Especially with the different behavior reactive design imposes on different sized views.

**Comment by ttlenard** [comment]
@mrinsin @shumway-tm Some testing feedback:

Test case 5.
- As a docket clerk, I had sealed one of the cases in the consolidated group that the petitioner was not associated with.
- Log in as a petitioner
- Open up the Console/Network/Preview tab
- Click on the hyperlink of the case that you are associated with in the Consolidated Group
- Click on the Case information tab
- Click on the Consolidated Cases in the Console
- You can see ALL the sealed case info! This needs to be more like what it shows if you were to navigate to the sealed case. (See screen shots)

Here is where you can see all the sealed case info:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9c363ece-1b0e-4b9b-bb02-0ab1a498ddaa)


This is what this SHOULD look like when viewing the case JSON. We display very little for sealed cases:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1c2d87a0-45e4-4916-a1fc-cfd21e986365)

**Comment by ttlenard** [comment]
The issue referenced above is part of the back-end code, and will be fixed with bug ustaxcourt/ef-cms#8284.  The bug will need to be fixed before we release this story to production.
