### ISSUE TITLE
IRS Practitioner: E-filing a document in a consolidated case

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8255]
As an IRS practitioner in a case, to streamline the filing process in a consolidated case group, I need to be able to file a single document across the consolidated case group as a single operation.

With the recent enhancements to DAWSON to better handle consolidated groups of cases, we would like to now make available to practitioners the ability to e-file a document across multiple cases in their consolidated group. This feature will be available to both private and IRS practitioners in the future.

## Pre-Conditions
ustaxcourt/ef-cms#8254

## Acceptance Criteria
* When e-filing an eligible document (see Notes section below re: eligible document types) in a case to which they are a party, if that case is a part of a consolidated group (Lead or Member) a practitioner is presented with the option to file in all cases across the consolidated group to which that case belongs
* When filing in multiple cases:
  - Document entries on case docket records are created for each case selected by Practitioner
  - Cover sheets are applied to the document on each docket entry in the following manner for consolidated cases:
      - Petitioner name(s) of the *Lead case in the group* appended with "et al"
      - Docket number and document number of each case selected are listed in ascending order by docket number
  - Service is performed on all parties in all cases being filed in
  - QC work items are spawned for each docket entry created by the filing
  - The FiledBy value on the docket record for each entry indicates the party filing the document, even if they are not a party to a case in which the document is being docketed
  - Any attachments or supporting documentation for the document being filed are also filed with that document in all cases where docketed
  - Messaging throughout Practitioner flow is updated to reflect multiple cases are being filed in
  - At the final step in filing document on the Review Page, Practitioner is presented with a reminder of all cases the document will be filed in
  - At the final step in filing document, Practitioner can cancel out of the workflow
  - The document created by clicking the Print Receipt link displayed after completing filing reflects all docket numbers in which the document was filed and appends "et al.," to the Lead Case Petitioner names in the caption.
* The following document types should not be multi-docketed with this functionality (i.e., do not invoke this if the document being filed is one of the following event codes:
ACED
COED
M007
M083
PSDE

## Security Considerations
* Does this work make you nervous about privacy or security?
* Does this work make major changes to the system?
* Does this work implement new authentication or security controls?
* Does this work create new methods of authentication, modify existing security controls, or explicitly implement any security or privacy features?

## Notes
* Should tie to the same feature flag used by ustaxcourt/ef-cms#8252
* Need to test w/ IRS service agent
* Eligible document types include all documents currently available to be e-filed by Practitioners EXCEPT those noted in the AC
* Should work on mobile
* The IRS have blocked web sockets. If the solution uses async lambdas, special handling will be required to inform the user the operation has completed or failed.
* Can we show progress in filing/serving each docket entry to the user as opposed to a spinning wheel?
* Solution will need to be re-used/consistent w/ private practitioner solution
* Should consider what would happen if during document QC, the docket clerk has to edit the metadata associated with the document. This currently generates a new coversheet on the document.  Potential for multiple coversheets getting generated on the single document if edits are made in all cases that are part of the group.

## Notes
* Should tie to the same feature flag used by ustaxcourt/ef-cms#8186/#9595

## Tasks

- [X] Add the multi-docket filing card to the "File Your Document" details page.
  - [X] Mobile Styling
- [x] Add the multi-docket filing card to the "Request Access" details page. 
  - [x] Mobile Styling
  - NOTE: Slightly different styling than the "File Your Document" page. MIGHT NOT be able to reuse other card?
  - QUESTION: Design needed? Does the title need to also change due to requesting access across consolidated group vs previously being limited to one case?
- [x] Setup Feature Flag
- [x] Add "Cases your document will be filed in" card to the "Review Your Filing" page.
  - [x] Mobile Styling
- [x] Show all petitioners in the "Service Parties" card to the "Review Your Filing" page.
  - [x] Mobile Styling
- [x] MultiDocket to currently active/selected case only in Consolidated Group
  - [X] "File Your Document" Flow
  - [x] "Request Access" Flow. Different Sequence than above. 
    - [x] Associate IRS to each case when Filing a Document available in "Request Access" Flow
  - NOTE Needs refactoring. The two flows use different sequences. Can we consolidate sequences into one flow?
- [x] MultiDocket to single all cases across Consolidated Group
  - [X] "File Your Document" Flow
  - [x] "Request Access" Flow. Different Sequence than above. 
  - NOTE Needs refactoring. The two flows use different sequences. Can we consolidate sequences into one flow?
- [x] Print receipt includes all docket numbers in which the document was filed
  - [x] "et al." is appended to the Petitioner name in the caption.
- [x] Coversheets
  - [x] Coversheet includes the Petitioner name of the Lead case in the group, and is appended with the "et al."
  - [x] Coversheet includes the docket number and document number of each case in the group in ascending order.
- [x] BUG: intermittently consolidated group card shows up on a non-consolidated case

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**
Mockups for the File Document and Review Filing pages:

![File page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/fb0959d0-41ca-4697-9568-cb16bfa8409c)

- Add section below "Tell Us About the Parties..." titled "Which Cases Do You Want to File In?
- Add two lines of text "This case is part of a consolidated group." and "Select the group or this case to file in."
- Add a radio btn with all of the cases, preceded by "All in the consolidated group"
- Add a radio btn with only the case that the document was initiated in

Mobile view:

![File page - mobile.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/f08c8111-ef76-4840-ac9f-2c712c53c0dd)
___

![Review page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/f2c8dab2-c40b-40ff-9a15-aca0ebc51398)

- Add a card below Your Documents titled "Case(s) The Document(s) Will Be Filed In"
- Add a line of text "Docket numbers and petitioners"
- List the docket numbers and petitioners that were selected in the previous page
- Add a card below Parties Filing titled "Service Parties"
- List all the parties in all cases that are receiving service
- Parties in each case are separated by a grey line (same as the one below the title)
- The width of both cards should be equal
- Wrap text if needed

Mobile view:

![Review page - mobile 1.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7d9f8606-c9a5-4006-bd42-2cfb588ba0c4)

![Review page - mobile 2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/7663d183-ac72-40fb-b17f-5954fccf588e)

Figma file, page "v2": https://www.figma.com/file/qSOo3Et69sUDay2mq0BhNn/USTC-%7C-Consolidated-Case-%7C-IRS-practitioner-efile-doc-9598?node-id=22%3A2&t=0Z2ml9Dv5ftih6hK-1

**Question for Chris:** 
For the list of service parties, if an IRS practitioner represents multiple cases, are they listed more than once in the service parties or does current behavior prevent duplicating names?
Answer: After discussing with Chris, we will show all parties from all served cases, even if they are duplicated.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) IRS Practitioner files an entry of appearance in a case or cases in a Consolidated Group; New section for selecting additional cases is present on the Request Access to this Case page.

- Log in as an IRS Practitioner
- Type in the docket number of a consolidated case in the Search box on the My Cases page
- Click the Request Access to Case button

Expected Results:
- [x] **NEW FUNCTIONALITY** - New section near the bottom of the page that is titled, "Which Cases Do You Want to File In?" that matches what is in the mockup.
- [x] **NEW FUNCTIONALITY** - Section includes radio buttons for "All in the consolidated group" and The docket number/Petitioner name(s) for the case that you are filing the EA in.
- [x] **NEW FUNCTIONALITY** - Under "All in the consolidated group", it lists all of the docket number and Petitioner names for the cases in the consolidated group.
- [x] **NEW FUNCTIONALITY** - User can click either radio button, and can only have one selected.


#### 2) IRS Practitioner selects "All in the consolidated group" radio button; Cases and service parties are listed on the Review your Filing page.

- Continuing from the previous test
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Select "All in the consolidated group"
- Click Review filing button

Expected Results:
- [x] **NEW FUNCTIONALITY** - New card titled "Case(s) The Document(s) Will Be Filed In" is below the "Your Document(s)" card. Card formatting matches the mockup.
- [x] **NEW FUNCTIONALITY** - New card titled "Service Parties" is underneath the "Parties Filing the Document" card.  Card matches the formatting in the mockup.


#### 3) IRS Practitioner submits the filing; Document is added to each case in the consolidated group

- Continuing from the previous test
- Click Submit your Filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Green confirmation banner indicates successful filing in cases across the group.


#### 4) IRS Practitioner clicks the Print receipt link from the Green confirmation banner; Print receipt includes all docket numbers in which the document was filed; "et al." is appended to the Petitioner name in the caption.

- Continuing from the previous test
- Click on the Print Receipt link

Expected Results:
- [x] New tab opens with the Receipt of filing document
- [x] **NEW FUNCTIONALITY** - Petitioners name in the case caption is the case caption of the LEAD case, and it is appended with "et al."
- [x] **NEW FUNCTIONALITY** - All of the docket numbers that the document was filed in are listed.


#### 5) IRS practitioner views the document on the docket record; coversheet includes updated caption for the Lead case, and includes all the docket numbers/document numbers for each case in the consolidated group.

- Continuing from the previous test
- Click on the document title on the docket record

Expected Results:
- [x] Document opens in a new tab
- [x] Document includes a coversheet
- [x] **NEW FUNCTIONALITY** - Coversheet includes the Petitioner name of the Lead case in the group, and is appended with the "et al."
- [x] **NEW FUNCTIONALITY** - Coversheet includes the docket number and document number of each case in the group in ascending order.


#### 6) IRS practitioner navigates to each case in the consolidated group; each case has an entry of appearance document on the docket record, each document matches what was filed in the original case.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record and the individual documents in each case

- [x] **NEW FUNCTIONALITY** - Each case has the Entry of Appearance document present on the docket record
- [x] **NEW FUNCTIONALITY** - Each document matches what was entered/added in the original case you were in when you filed the document.
- [x] **NEW FUNCTIONALITY** - Document numbers match what is on the coversheet.
- [x] **NEW FUNCTIONALITY** - Review the docket record
	- [x] **NEW FUNCTIONALITY** - The docket index is in the correct order in all cases
        - [x] **NEW FUNCTIONALITY** - The filed date is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The page count is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The document title is Entry of Appearance for Respondent in all cases
        - [x] **NEW FUNCTIONALITY** - The filed by value indicates Resp. in all cases
        - [x] **NEW FUNCTIONALITY** - The served date and served parties is correct in all cases


#### 7) IRS Practitioner information is displayed correctly on the Case information/Parties tab

- Continuing from the previous test
- Click on case information tab for each case
- Click on the Respondent counsel tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The IRS Practitioner information is correctly displayed on the Respondent counsel tab in each case.


#### 8) Review the logs to ensure that service was sent to all parties appropriately

- Open Kibana
- Check service on all cases

- [x] **NEW FUNCTIONALITY** - Bulk email params list each party receiving electronic service
- [x] **NEW FUNCTIONALITY** -Bulk email response has a successful service message for each party receiving electronic service
- [x] **NEW FUNCTIONALITY** -Each case in the consolidated group should have both of the log entries above, and the IRS Practitioner should have received service emails for each case.


#### 9) Docket Clerk accesses Document QC page; work items are created for each case that the document was filed in.

- Log in as a docket clerk or Case Services Supervisor
- Click on Document QC
- Click on Section document QC
- Find the documents that you just filed in the consolidated cases as the IRS Practitioner in the previous test

Expected Results
- [x] **NEW FUNCTIONALITY** - There are individual work items for each document filed in each case, and they will be unassigned.
- [x] Work items display the consolidated case icons appropriately
- [x] All other information in the table is displayed/linked as it normally should be
- [x] Consolidated case work items from the previous test can filtered in view as per normal
- [x] Consolidated case work items from the previous test can be assigned to a docket clerk as per normal.



#### 10) Docket Clerk clicks on the document title of one of the Entry of Appearance documents from QC, Clerk can complete QC.

- Continuing from the previous test
- Click on the document name link to open the document for QC
- Review the information 

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is Resp.
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption, et al., docket/document numbers, etc.)

- Do not change any of the data while QCing.
- Click Complete

Expected Results:
- [x] Green confirmation banner
- [x] When viewing the processed tab, the document shows as QC'd as appropriate
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 11) Docket Clerk clicks on the document title of one of the Entry of Appearance documents from QC, Clerk can Complete and Send Message.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the IRS Practitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is Resp.
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption, et al., docket/document numbers, etc.)

- Do not change any of the data while QCing.
- Click Complete and Send Message

Expected Results:
- [x] The message modal appears and functions as normal (document is attached, recipients load appropriately, etc.)
- [x] Message sends successfully
- [x] Green confirmation banner indicating document was QC completed and message sent
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] When viewing case messages, the message is displayed as appropriate
- [ ] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 12) Docket Clerk clicks on the document title of one of the Entry of Appearance documents from QC, Clerk edits/adds some data during QC; Clerk can complete QC.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the IRS Practitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is Resp.
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption, et al., docket/document numbers, etc.)

- Update some of the data while QCing (examples: date received, document type, filed by, inclusions).
- Add in some test data into the Additional Info 1 field and check the box for Add to cover sheet.
- Click Complete 

Expected Results:
- [x] Green confirmation banner indicating document was QC completed 
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] The document has a new coversheet with the information that you changed reflected appropriately
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd



#### 13) Docket Clerk clicks on the document title of one of the Entry of Appearance documents from QC; Clerk checks Add to pending report; Clerk can complete QC; Pending item is captured appropriately.

- As a docket clerk, click on Document QC
- Click on Section Document QC
- Find the documents that you filed in the consolidated cases as the IRS Practitioner in the previous tests
- Click on the Document name link to open the document for QC
- Review the information

Expected Results:
- [x] The data is correct.
     - [x] The filed date
     - [x] The document title 
     - [x] Other data 
     - [x] Filed by is Resp.
     - [x] Document displayed in the preview (matches what was submitted, coversheet, Petitioner caption, et al., docket/document numbers, etc.)

- Be sure that you check the box for add to pending report
- Click Complete 

Expected Results:
- [x] Green confirmation banner indicating document was QC completed 
- [x] When viewing the processed tab, the document shows as QC'd as appropriate (including having the consolidated icon)
- [x] When viewing the docket record, the document is QC'd as appropriate
- [x] On the Tracked Items tab of the case, there is an new pending report item for this document
- [x] Clicking on the Document title from the Pending report opens the document view of the document as per normal.
- [x] The Pending Report item appears as it should when running a query on the Pending report (be sure to take note of the Judge assigned to the case for when you run this report)
- [x] The other documents that were filed on the other cases are still in their original format, there aren't any pending items associated with them.
- [x] All of the other remaining QC work items related to the consolidated case filing remain un-qc'd.


#### 14) Docket Clerk edits the document that was just filed and QC'd; Edits are saved correctly.

- Continuing from the previous test
- Navigate to the docket record of the case
- Click on the Edit link for the document
- Edit something (add an action, change the document type, update the filed by, strike the document...any of these things will be great to test with!)
- Click Save

Expected Results:
- [x] Green confirmation banner indicating Docket Entry changes saved
- [x] When viewing the docket record, the update you just made is saved, and is visible
- [x] The other documents that were filed on the other cases are still in their original format, without any of the changes you just made.


#### 15) Docket Clerk seals a document that was just filed and QC'd; Document seals appropriately.

- Continuing from the previous test
- Click the seal link for the document
- Select the seal level you want and click Seal


Expected Results:
- [x] When viewing the docket record, the document is sealed appropriately
- [x] The other documents that were filed on the other cases are still in their original format and are not sealed.


#### 16) IRS Practitioner files a document in a case in a Consolidated Group; New section for selecting additional cases is present on the File Your Document(s) page.

- Log in as the IRS Practitioner that you used for test case 1
- Click on the docket number for one of the cases in the consolidated group
- Click File a document

Expected Results:
- [x] **NEW FUNCTIONALITY** - New section near the bottom of the page that is titled, "Which Cases Do You Want to File In?" that matches what is in the mockup.
- [x] **NEW FUNCTIONALITY** - Section includes radio buttons for "All in the consolidated group" and the docket number/Petitioner name(s) for the case that you are filing the EA in.
- [x] **NEW FUNCTIONALITY** - Under "All in the consolidated group", it lists all of the docket number and Petitioner names for the cases in the consolidated group.
- [x] **NEW FUNCTIONALITY** - User can click either radio button and can only have one selected. 


#### 17) IRS Practitioner selects the singular case radio button; Standard Review your Filing page displays.

- Continuing from the previous test
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Select the radio button for the singular case that you are currently filing in.
- Click Review filing button

Expected results:
 - [x] The Review your filing page is the "standard" review page (only lists cards for Your Document(s), and Parties Filing The Documents) 



#### 18) IRS Practitioner submits the filing; Document is added to the singular case in the consolidated group only.

- Continuing from the previous test
- Click Submit your Filing

Expected Results:
- [x] Green confirmation banner indicates successful addition to the docket record.



#### 19) IRS Practitioner clicks the Print Receipt link from the Green confirmation banner; Print receipt includes only the singular docket number in which the document was filed; "et al." is NOT appended to the Petitioner name in the caption.

- Continuing from the previous test
- Click on the Print Receipt link

Expected Results:
- [x] New tab opens with the Receipt of filing document
- [x] Petitioners name in the case caption is the case caption of the case you are filing in (Might NOT be the Lead case, and it is NOT appended with "et al.")
- [x] Print receipt only shows the case docket number for the case that you filed the document in, shouldn't list any other docket numbers. 



#### 20) IRS practitioner views the document on the docket record; coversheet only refers to the singular case.

- Continuing from the previous test
- Click on the document title on the docket record

Expected Results:
- [x] Document opens in a new tab
- [x] Document includes a coversheet
- [x] Coversheet includes the Petitioner name of the singular case only in the group, and is NOT appended with the "et al."
- [x] Coversheet includes the docket number of each singular case in the group only.



#### 21) IRS practitioner navigates to each case in the consolidated group; none of the other cases in the group have the just filed document on the docket record.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record in each case

Expected Results:
- [x] None of the other cases in the Consolidated group have the most recently filed document
- [x] The only case that has the document on the docket record is the singular case that you filed the document in.


#### 22) Review the logs to ensure that service was sent to all parties appropriately.

- Open Kibana
- Check service on all cases

- [x] Bulk email params list each party receiving electronic service
- [x] Bulk email response has a successful service message for each party receiving electronic service
- [x] Only the singular case in the consolidated group should have both of the log entries above, and the IRS Practitioner should have received service emails.


#### 23) Docket Clerk accesses Document QC page; work item is created for the singular case that the document was filed in; can be QC'd as normal.

- Log in as a docket clerk or Case Services Supervisor
- Click on Document QC
- Click on Section document QC
- Find the document that you just filed in the consolidated case as the IRS Practitioner in the previous test

Expected Results
- [x] There is an individual work item for the singular document filed in the case, and it is unassigned.
- [x] Work item displays the consolidated case icon appropriately
- [x] All other information in the table is displayed/linked as it normally should be
- [x] Consolidated case work item from the previous test can filtered in view as per normal
- [x] Consolidated case work item from the previous test can be assigned to a docket clerk as per normal.
- [x] Clerk can complete QC as normal.


#### 24) IRS Practitioner files a document in all of the cases in a Consolidated Group; Practitioner includes supporting documents

- Log in as the IRS Practitioner that you used for test case 1
- Click on the docket number for one of the cases in the consolidated group
- Click File a document
- Select a document from the dropdown (doesn't matter which one)
- Upload a document
- Check the box for attachments and Certificate of Service
- Add Supporting Documents (for some of them, check attachments and certificate of service, some of them leave the checkboxes blank)
- Indicate that respondent is filing the documents
- Select "All in the consolidated group"
- Click Review filing button
- Ensure that the additional cases that you checked in Test case above are present and are displaying the correct information.
- Ensure that the supporting documents are displayed with the document
- Ensure that the Document Includes column includes the attachment and certificate of service info
- Click on Submit Your filing

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Green confirmation banner indicates successful filing in cases across the group.
- [x] After clicking on Print receipt:
     - [x] New tab opens with the Receipt of filing document
     - [x] **NEW FUNCTIONALITY** - Petitioners name in the case caption is the case caption of the LEAD case, and it is appended with "et al."
     - [x] **NEW FUNCTIONALITY** - All of the docket numbers that the documents were filed in are listed.
     - [x] The supporting documents are listed in the Documents filed column
     - [x] The Document Includes column lists the attachments and the certificate of service and date


#### 25) IRS practitioner navigates to each case in the consolidated group; each case has the document and the supporting document(s) on the docket record, each document matches what was filed in the original case.

- Continuing from the previous test
- Navigate to the case information tab
- Open each docket number that is in the consolidated group in a new tab
- Review the docket record and the individual documents in each case

- [x] **NEW FUNCTIONALITY** - Each case has the document that you uploaded for the one case present on the docket record.
- [x] **NEW FUNCTIONALITY** - Each case also has the Supporting documents that you uploaded for the one case present on the docket record.
- [x] **NEW FUNCTIONALITY** - Each document matches what was entered/added in the original case you were in when you filed the document.
- [x] **NEW FUNCTIONALITY** - Document numbers match what is listed on the coversheet.
- [x] **NEW FUNCTIONALITY** - Review the docket record
	- [x] **NEW FUNCTIONALITY** - The docket index is in the correct order in all cases
        - [x] **NEW FUNCTIONALITY** - The filed date is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The page count is correct in all cases
        - [x] **NEW FUNCTIONALITY** - The document title is the same in all cases
        - [x] **NEW FUNCTIONALITY** - The filed by value indicates Resp. in all cases
        - [x] **NEW FUNCTIONALITY** - The served date and served parties is correct in all cases


#### 26) IRS Practitioner files a motion document in all cases in a consolidated group; Judge is able to stamp each motion individually; granting some, and denying others.

- Log in as an IRS Practitioner that is associated with a consolidated group
- Click on the docket number link on the my cases page
- Click File a document
- Be sure to select a Motion document to file and upload a file
- Select Respondent for the filer
- Select all cases in the consolidated group
- Click Review filing
- Click Submit your filing
- Next, as a docket clerk, QC each entry and send a message to the Judge/ADC
- Log in as a Judge/ADC for the consolidated cases
- Navigate to the cases
- Stamp grant and Stamp deny the motions, and send a message back to docket
- As docket, Add the Stamp Order to the docket record

Expected Results:
- [x] The entire workflow works as normal for each of the individual motions that were filed across the consolidated group
- [x] Each stamp orders that you just added to the docket record are available in the Order Search

 
#### 27) IRS Practitioner starts to file a document in all cases in a consolidated group; Cancels workflow; Practitioner is returned to either My Cases or the Case Docket Record.

- Log in as an IRS Practitioner
- Click on a consolidated case docket number from the My Cases page
- Click File a Document
- Click Cancel at all of the screens during the workflow

Expected Results:
- [x] User is either returned to the docket record of the case, or back to the My Cases Screen as per usual behavior.
- [x] No documents are filed, no service


#### 28) IRS Practitioner starts to file a document in all cases in a consolidated group; Clicks the back button during the workflow; Practitioner is returned to the previous screen.

- Log in as an IRS Practitioner
- Click on a consolidated case docket number from the My Cases page
- Click File a Document
- Click the Back button on all of the screens where it is present during the workflow

Expected Results:
- [x] User is returned to the previous screen; data that was entered previously is still present.


#### 29) IRS Practitioner files a Decision type of document to a case in a consolidated group; Practitioner does not have the option to multi-docket the decision document.

- Log in as an IRS Practitioner
- Navigate to a case in a consolidated group
- Click on the File a document button
- Be sure to select a decision type document (see list of documents in the A/C), and upload a file
- Select Respondent as the filer

Expected Results:
- [x] The new section for the option to file in all cases in the consolidated group is not present
- [x] After submitting the filing, the Decision type document is only filed in the one case
- [x] The coversheet does not have the "et al.,", it only lists the caption of the case that you filed in (not necessarily the lead case), it only lists the docket number and document number of the individual case that you filed in.


*Repeat this test with all of these decision type of documents:
- [x] ACED
- [x] COED
- [x] M007
- [x] M083
- [x] PSDE


#### 30) IRS Practitioner accesses DAWSON on a Mobile device; Practitioner can go through the workflows above and multi-docket on a mobile device.

- Log in as an IRS Practitioner on a mobile device
- Click on the docket number link for one of the consolidated cases
- Click File a document

Expected Results:
- [x] All workflows outlined above work on a mobile device
- [x] Content on mobile screens are readable and usable.


#### 31) Regression test Story 9595 - Practitioner visibility across consolidated case group

- [x] Test cases for 9595 still pass



#### 32) Regression test with the FF set to off

- [x] IRS practitioner cannot file across the consolidated group
- [x] When the FF is off, Practitioner does not have visibility across the consolidated group (see story 9595)


#### 33) IRS has validated that the solution works in the IRS test environment

- [ ] Yes


#### 34) Other things to think about while testing

- What if the filing is really large, do we need to be concerned with a timeout?
- If a timeout occurs, or if the user attempts to file a document other than a PDF, what kind of error messaging would appear for the user to let them know what went wrong?

**Comment by cholly75** [comment]
@shumway-tm @rgoshen @codyseibert - please note there has been an update to the Notes section and eligible document types - we are excluding Proposed Stip Decisions from multidocketing. Lemme know if you wanna chat through it.

**Comment by cholly75** [comment]
Added AC re: ineligible document types for multidocketing

**Comment by ttlenard** [comment]
Added Test Case 29 for decision type documents.

**Comment by rgoshen** [comment]
After a some discussion with @ttlenard, probably need to add consolidatedCases array to PublicCase for irsPractitioners only since they already have some additional information included that any other external user does not receive via the Public Case Entity.  This would allow the irsPractitioner when requesting access to any case in a consolidated group they would be given access to all cases within the consolidated group and entry of appearance would be filed across all cases.

Also, when an irsPractitioner files a motion, it should act in the same way when a docketClerk or petitionsClerk files a paper filing as a motion.  It needs to spawn individual work items for all cases (when filed across all cases in the group) and then allow the judge to individual stamp each without generating the granting/denial across all cases (see TC#26). cc: @shumway-tm

**Comment by ttlenard** [comment]
Testing Feedback @codyseibert @rgoshen @shumway-tm 

- Test Case 3 and Test Case 24 - Green confirmation banner does not have the updated text to confirm filing across multiple cases.  It should match what is currently displayed for internal filings across the group.

Here is what it says now:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2d91d972-d159-4ebf-b709-b8d9f0ed351b)

Here is what is displayed for internal filings:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/923d4054-37a8-4490-a6f3-a676d30fc9ef)

**Comment by ttlenard** [comment]
@codyseibert  @rgoshen @shumway-tm 

Some additional testing feedback. No further action needs to be taken on this yet. This is just to note this edge case behavior. We will probably take action on this at a later time to adjust this behavior.

- IRS practitioner is assocaited with multiple cases in a consolidated group
- There is one case in the group that they are not associated with; this case happens to be sealed
- Current functionality allows the IRS Practitioner to be able to view the docket record of this sealed case, and they can also click on the document links to view documents.
- If the IRS Practitioner clicks on the "Printable Docket Record" Link for the sealed case that they are not associated with, they will see a brief error message on the screen and it will log the user out.
- Here is the error message in kibana:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/04daf7c7-025f-44b1-bee2-81c9da0951d7)

Some other notes:
- I did double check and IRS Practitioner does not get this message if they are associated with the sealed case and they click on printable docket record.

**Comment by ttlenard** [comment]
More testing feedback @codyseibert @rgoshen @shumway-tm 

If a case(s) in the group are sealed, and a practitioner (happens with IRS AND Private Practitioner) is attempting to request access to a different case in the group that is NOT sealed, the user experiences a blank white screen right after they click "request access to case".  When looking at the console, it is the result of a type error.  As soon as I unsealed the case in the group, the practitioner can request access to the case just fine.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/35bfe6c5-4417-448a-9aa8-d82a9e9c0682)

**Comment by shumway-tm** [comment]
@cholly75 @ttlenard 

Questions to be answered:
 - Should IRS Practitioners should be able to Request Access to sealed cases (when part of a consolidated group)?
  - IF NO -> Should the sealed case show up in the list of consolidated cases on the multi-docketing card in the Request Access Flow?
   - IF YES (@swongCO @katiecissell)-> What do we display next to the docket number where names would appear? 

CC: @TomElliottFlexion @rgoshen

**Comment by TomElliottFlexion** [comment]
Note: : The above also applies to filing the first document as an IRS practitioner
