### ISSUE TITLE
Dedicated Docket View - Orders

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8259]
As a DAWSON user so that I can quickly identify orders pertaining to a case, I need a view that displays only order-type docket entries.

In the course of a case, many times there will be multiple references to specific orders that have been issued. Currently the user must navigate the entirety of the docket record to locate and view a specific order in question. With long docket records, this becomes unwieldy and confusing.

We would like for a user to be able to see a filtered view of the docket record that includes only those docket entries coded with order-related event codes. This functionality should manifest as an option in the menu recently introduced in story ustaxcourt/ef-cms#8226.

## Pre-Conditions
ustaxcourt/ef-cms#8226

## Acceptance Criteria
* User can see a view of the docket record that includes only docketed entries for the case for which the type `isOrder:` is `true`
* User can interact with the docket entries on this view in the same manner as interacting with them on the Docket Record view based on their role (i.e., docket clerks can edit and seal entries from this view)
* User can easily navigate to or implement this view and then return to the full docket record
* View is accessible to all users
* View is ordered in the same default manner as the standard docket record view
* Docket entries on this view obey all other standard rules for visibility
* "Order" filter option should be sorted alphabetically on the "Filter By" menu

## Tasks
https://github.com/ustaxcourt/ef-cms/pull/2605
https://github.com/ustaxcourt/ef-cms/pull/2611

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Court user can choose to view only docket entries related to Orders on the docket record of a case.

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Orders 
- In the View Filter, select Orders

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Order documents and does not show other document types. 
- [x] **NEW FUNCTIONALITY** - The Filter dropdown menu is sorted alphabetically, with Exhibits as the first option, and Orders second in the dropdown menu.

*Repeat this test with multiple docket records to ensure that all of the Order documents are being filtered appropriately



#### 2) Docket Clerk can view/interact with documents on the docket record from the filtered Order view.

- Log in as a Docket clerk
- Navigate to a case that has Orders 

Expected Results
- [x] When clicking on the Order Document title, the Document Preview opens, and you can view the document
- [x] Docket Clerk can seal the Order document from the filtered view on the docket record
- [x] Docket Clerk can edit the Order document from the filtered view on the docket record 



#### 3) Court user can view/interact with documents on the docket record from the filtered Order view.

- Log in as a Court User (be sure to test with various Court user roles)
- Navigate to a case that has Orders 

Expected Results
- [x] When clicking on the Order Document title, the Document Preview opens, and you can view the document



#### 4) Court user can easily change between filtered Order view, Exhibit view, and the All Documents View

- Log in as any court user (be sure to test with various court user roles)
- Navigate to a case that has Orders and Exhibits (I was testing with 21959-16, 2670-19, 15066-18, 9171-19, 20763-17, 1781-14, 22643-18)
- In the View Filter, select Orders
- Next, select Exhibits
- Switch back to All Documents

Expected Results
 - [x] **NEW FUNCTIONALITY** - Docket record quickly reloads to show only Orders, only Exhibits, or All Documents depending on what filter the user has selected.



#### 5) Court user Filters for Orders only on the docket record; Sorts by other fields

- Log in as any Court user (be sure to test with various court user roles)
- Navigate to a case that has Orders 
- In the View Filter, select Orders
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Orders sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Orders is selected in the View Filter.



#### 6) Parties on a case an choose to view only docket entries related to Orders on the docket record of a case.

This test has some set up:
- Log in as a docket clerk
- Navigate to a case that has Orders 
- In one of those cases, add a test petitioner, a test IRS respondent, and a test private practitioner

- Log in as a Petitioner 
- Navigate to the case that you were just added to
- In the View Filter, select Orders

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Order documents, and does not show other document types.

*Repeat this test with IRS and Private Practitioner roles



#### 7) Party on a case filters for Orders only on the docket record; Sorts by other fields

- Log in as as a petitioner
- Navigate to the case that has Orders that you got access to in the previous test
- In the View Filter, select Orders
- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))

Expected Results
- [x] **NEW FUNCTIONALITY** - The Orders sort appropriately
- [x] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Orders is selected in the View Filter.

*Repeat this test with IRS and Private Practitioner roles



#### 8) Public non-logged in users can choose to view only docket entries related to Orders on the docket record of a case.

- Navigate to the DAWSON homepage search dashboard
- From the Case Search Screen, input a Petitioner name or a docket number for a case that has Orders. 
- Click Search
- In the View Filter on the docket record of the case that you searched for, select Orders

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Order documents, and does not show other document types.
- [x] **NEW FUNCTIONALITY** - The option for Exhibits is NOT available to Public non-logged in users or the public terminal user, only Orders should be available in the dropdown menu options.

*Repeat this test with the public terminal user



~~#### 9) Public non logged in user filters for Orders only on the docket record; Sorts by other fields~~

~~- Continuing from the previous test~~
~~- Change the default Sort view (Sort by newest, sort by Document no. (ascending), Sort by Document no. (descending))~~

~~Expected Results~~
~~- [ ] **NEW FUNCTIONALITY** - The Orders sort appropriately~~
~~- [ ] **NEW FUNCTIONALITY** - No other document types are appear on the docket record or are sorted when Orders is selected in the View Filter.~~

*Repeat this test with the public terminal user



#### 10) Docket Clerk seals an Order from the public; Parties on the case can filter and view the sealed Order documents from the filtered docket record view

- Log in as a Docket Clerk
- Navigate to a case that has Orders 
- In one of those cases, seal some of the Order documents to the public
- Next, log in as a party to the case
- Navigate to the case where you sealed documents
- Filter by the Order view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Order documents, and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Order documents
- [x] Sealed Order document is hyperlinked
- [x] When clicking on the Sealed Order Document title hyperlink, the Document Preview opens, and you can view the document



#### 11) Docket clerk seals an Order from the public and parties on the case; Parties on the case can filter and see that there is a sealed Order document on the docket record view, but are unable to view it.

- Log in as a Docket Clerk
- Navigate to a case that has Orders 
- In one of those cases, seal some of the Order documents to the public and parties on the case
- Next, log in as a party on the case
- Navigate to the case where you sealed documents
- Filter by the new Order view

Expected Results
- [x] **NEW FUNCTIONALITY** - The docket record view will only display Order documents, and does not show other document types.
- [x] Red lock icon appears next to the title of the sealed Order documents
- [x] Sealed Order document is NOT hyperlinked
- [x] Party/public user/terminal user is unable to click on the Sealed Order Document
- [x] **NEW FUNCTIONALITY** - The option for Exhibits is NOT available to Public non-logged in users or the Public terminal User, only Orders should be available in the dropdown menu options.

*Repeat this test with a non-logged in public user and the Public Terminal User by navigating to the case from the Case Search screen.

**Comment by cholly75** [comment]
@ttlenard - all tests pass, can you look at docket 3517-21 just to confirm with the terminal user? It should have a mix of unsealed, sealed, and "super sealed" orders on there.

**Comment by ttlenard** [comment]
@cholly75 Terminal user test passes.  I see the mixture of sealed, super sealed, and unsealed Orders on this case.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1a8d489e-388d-42fd-afbe-b9508d19f8fa)
