### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8267]
**Describe the Bug**
When a docket clerk clicks on the Complete button after QCing a document from their QC inbox, It doesn't immediately get removed from the users QC inbox.  It will disappear from the inbox if you navigate off of the inbox tab.  When you click on the Processed tab, the document is there. It is like the QC'd document "lingers" in the inbox. If they click Complete and Send Message, then the document that they QC'd goes straight into the users Processed tab, and does not "linger" in the inbox view for the user.

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Test, Staging

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other stories

**To Reproduce**
1. Docket clerk QC's something from their inbox, clicks "Complete"
2. DAWSON navigates user back to their QC inbox.
3. Green confirmation banner that says doc has been completed
4. The QC item that you just completed remains in the Inbox list of items.
5. If you navigate off of the tab, then the QC item is removed from the inbox, and shows up in the Processed tab.  If you refresh your browser, it is the same behavior.

**Expected Behavior**
When you click Complete and are redirected to the user's inbox, the QC item should not appear in the table.

**Actual Behavior**
When you click Complete, you get a green confirmation that the item has been completed, but it still shows up in the inbox until you navigate off the page.

**Screenshots**
Inbox says 0 items, green banner saying QC is complete, but you still see the document in the Inbox.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/3ad4c913-b32e-4cdb-af86-088fec77f1c4)

I clicked on the document that I just QC'd since it was still in my inbox and QC'd it a second time. This resulted in two QC'd items for the same document in my processed tab.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/81f0f662-31f7-45da-97d2-0b60cb138327)

**Tasks**
- [x] Move TDynamoRecord into its own file
- [x] Remove Migration scripts that have been deployed to prod

**Cause of Bug, If Known**
Inbox was being populated from an elasticsearch query which takes time to update after updating record in dynamo. 

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
Testing looks good. Thank you!
