### ISSUE TITLE
Docket: Filing a paper document across a consolidated group from the Edit Paper Filing screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8269]
As a docket clerk, in order to use the multi-docketing feature in a group of consolidated cases from all potential workflows, I need to be able to invoke the consolidated case feature in story ustaxcourt/ef-cms#8185 from the Edit Docket Entry screen.

ustaxcourt/ef-cms#8185 extends the ability to file documents across a group of consolidated cases to paper filings. This story addresses the functionality in the context of the Edit Paper Filing screen/workflow, accessed when a docket clerk navigates to a saved docket entry from the QC display. 

We would like the Court to have the ability when clicking Save and Serve from the Edit Paper Filing screen to docket the filing across multiple cases in the consolidated group, in the same manner in which multi-docketing currently operates (i.e., this is only invoked when serving the filing from the lead case in a consolidated group, etc) for ustaxcourt/ef-cms#8185.

## Pre-Conditions
ustaxcourt/ef-cms#8304 

## Acceptance Criteria
* When clicking the Save and Serve button on the Edit Paper Filing screen, if the case to which the filing has been saved is the Lead Case in a consolidated group, the multi-docketing modal window appears
* The docket clerk can interact with the multi-docketing UI in the same manner as when invoked from the Serve link on the document or the Add Paper Filing screen, with the same behavior and effects.
* If the case to which the filing has been saved is _not_ the Lead Case in a consolidated group, the document is saved and served to that case only, as per usual behavior
-------------------- Additional AC from ustaxcourt/ef-cms#8185 -----------------
* In the Lead case for a consolidated group, when a docket clerk chooses Save and Serve for a Paper Filing, the clerk has the ability to choose one or more _other_ cases in that group in which to also add a docket entry
* The docket entry for each additional case in the CG:
  - is entered with the same data values as the Lead Case entry
  - should be docketed just as if the document for the entry had been added to the case manually
  - should link to the same PDF file in S3
  - are viewable on the docket record as per normal visibility rules 
  - is created and served when the Lead case docket entry is served.
  - should have the petitioner's name(s) filing the document in the "Filed By" column of the docket record (even if the petitioner filing the document is not a party to all the member cases)
* The cover sheet is generated with the following information on the caption:
    - ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
    - The docket numbers of the selected cases in the consolidated group are listed sequentially in ascending order on the 
       right side of the caption, followed by the docket entry position of the document in each case as "Document No."
    - Docket numbers that were not selected are not listed
* When the filing is created and served for the Lead case in a consolidated group of cases, the user is presented with a visual reminder of all parties in the consolidated group who will receive service
* Decision documents are not in scope for this functionality (Chris to confirm w/r/t PSDE)
* Parties receive service as normal for each docket entry (including the Lead docket entry)
  - Paper service documents are presented for printing as normal for each party receiving paper service
* The following document types should _not_ be multi-docketed with this functionality (i.e., do not invoke this if the document being filed is one of the following event codes:
  - ACED
  - COED
  - M007
  - M083
  - PSDE
* Hide this functionality behind feature flag

## Notes
* Should tie to the same feature flag present in ustaxcourt/ef-cms#8185
* Feature flag to hide behind is MULTI_DOCKETABLE_PAPER_FILINGS

## Tasks
- [x] Refactor edit paper filing endpoint - Rachel (https://github.com/flexion/ef-cms/pull/9778)
- [x] Display multi-docketing service modal when serving edited paper filing - Rachel (https://github.com/flexion/ef-cms/pull/9779)
- [x] Update editPaperFiling Interactor to be able to accept multi-docket filing. - Zach/Rachel (https://github.com/flexion/ef-cms/pull/9780)
- [X] Update client to pass consolidated member docket number to edit paper filing endpoint - Zach/Rachel (https://github.com/flexion/ef-cms/pull/9789)
- [x] Standardize endpoint arguments. Make all multidocketable flows not include lead case in consolidated cases array - Zach/Rachel (https://github.com/flexion/ef-cms/pull/9790)
- [X] Make editPaperFiling async - Similar to shared/src/business/useCases/docketEntry/addPaperFilingInteractor.ts (https://github.com/flexion/ef-cms/pull/9798)
- [x] Bugfixes (https://github.com/flexion/ef-cms/pull/9804)
- [x] Contain new functionality behind feature flag (https://github.com/flexion/ef-cms/pull/9805)

DOD Tasks
 - [ ] Create new websocket route for editing a docket entry and communicating the completion of the edit and save process. (https://github.com/flexion/ef-cms/pull/9807)
## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk is in the lead case of a consolidated group and adds a Paper Filing; Saves entry, does not serve.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Paper Filing
- Upload a PDF and Fill in the required fields for the paper filing (make sure that this is NOT a decision type of document)
- Click Save for later

Expected Results
- [x] Document is added to the docket record of the lead case only



#### 2) Docket Clerk serves paper filing from the Document QC In Progress Tab.
- Continuing from previous test case 
- Click on the Document QC Tab.
- Click on the In Progress Tab
- Click on the Document that you just saved in the previous test case
- Click Save and Serve from the Edit Paper Filing screen.

Expected Results
- [x] **NEW FUNCTIONALITY** - Updated modal has the checkbox checked for "All of the consolidated Group"
- [x] **NEW FUNCTIONALITY** - The list of parties receiving paper service shows parties from all the cases that receive paper service in the CG



#### 3) Upon service, print paper service is available for clerk, and an address cover sheet has been added to the document.
- Continuing from the previous test case
- Leave the default selection "All cases in the consolidated group"
- Take note of the petitioner's names in the list of parties receiving paper service
- Click Yes, Serve 

Expected Results:
- [x] The Print for paper service screen opens
- [x] **NEW FUNCTIONALITY** - Each party that receives paper service in the CG of cases that were selected in the previous test and that were listed on the modal have the address cover sheet, and the document to be printed for service.


#### 4) Updated confirmation message appears after service.
- Continuing from the previous test case
- Click Done

Expected Results:
- [x] You will be routed back to the docket record of the lead case
- [x] **NEW FUNCTIONALITY** - Green banner is present on the top of the page that states, "Document served to selected cases in group"


#### 5) Document is reflected appropriately on the docket record for both the lead case and the selected cases.
- Continuing from the previous test case
- Review the document details on the docket record

Expected Results
- [x] On the lead case, the document is attributed with index #, date, title, pages, action, served date, served parties, and has the edit/seal links
- [x] **NEW FUNCTIONALITY** - On the one other cases in the CG that were selected, the document is attributed the exact same way on the docket record as in the lead case.


#### 6) Document on the docket record has a coversheet.
- Click on the document link to open the document viewer

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document has the updated coversheet that includes:
     - [x] ", et al.," is appended to the Petitioner's name(s) on the left side of the caption
     - [x] The docket numbers of each the selected cases in the consolidated group are listed sequentially in ascending order on the right side of the caption. 
     - [x] For the cases that were selected in the modal, the docket entry position of the document in each case has the "Document No." listed after the Docket number.
     - [x] For cases that were not selected in the modal, there will NOT be a Docket Number of Document No. listed.
- [x] **NEW FUNCTIONALITY** Ensure that the document number that is represented on the cover sheet matches the document number on the docket record of each case.


#### 7) Document in the non-lead cases are the same as the document in the lead case.
- Continuing from the previous test case
- Click on the URL of the document from the lead case
- Click on the URL to View Full PDF
- This will open the document in a new tab
- Next, navigate to the other cases that you filed the document in
- Click on the URL of the documents
- Click on the URL to View Full PDF
- This will open the documents in a new tab

Expected Results
- [x] **NEW FUNCTIONALITY** - All of the documents should be exactly the same
- [x] **NEW FUNCTIONALITY** - All of the documents should share the same document ID


#### 8) Repeat tests 1-7 by selecting the Lead case only, the lead case plus 1 other case in the group, and by selecting some but not all of the cases in the group.

#### 9) Docket Clerk saves (does not serve) a Paper Filing that is a decision type of document in the lead case that is in a consolidated group.  Docket clerk opens the document from the document QC In Progress tab and serves it from the document viewer. Add Paper Filing workflow does not include the new modal, and docket clerk does not have the ability to file the document in other cases in the group.
- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group (I used case 22447-16)
- Click Create and select Paper Filing 
- Upload a PDF and Fill in the required fields for the paper filing. Be sure to select the document type as one of the decision type of documents above. 
- Click Save Entry
- Click on Document QC
- Click on the In Progress tab
- Click on the document to open it in the document view.
- Click Save and Serve from the Edit Paper Filing Screen.

Expected Results
- [x] The pop-up modal that states "Are you ready to Initiate Service?" appears (This is NOT the new modal, this should be the original modal that appears for non-consolidated cases).
- [x] After confirming service, The coversheet on the decision document does NOT have:
     - [x] ", et al.," appended to the Petitioner's name(s) on the left side of the caption
     - [x] Any other docket numbers of all cases in the consolidated group on the right side of the caption. 
- [x] The coversheet on the decision document does have the docket entry position of the document with the "Document No." listed after the Docket number.

*Repeat this test with all the Decision types of documents


#### 10) Docket Clerk is in a member case of a consolidated group and adds a Paper Filing; Saves entry, does not serve.
- Log in as a Docket Clerk
- Navigate to a member case in a consolidated group 
- Click Create and select Paper Filing
- Upload a PDF and Fill in the required fields for the paper filing (make sure that this is NOT a decision type of document)
- Click Save for later

Expected Results
- [x] Document is added to the docket record of the member case only


#### 11) Docket Clerk serves paper filing from the Document QC In Progress Tab.
- Continuing from previous test case 
- Click on the Document QC Tab.
- Click on the In Progress Tab
- Click on the Document that you just saved in the previous test case
- Click Save and Serve from the Edit Paper Filing Screen.

Expected Results:
- [x] The pop-up modal that states "Are you ready to Initiate Service?" appears (This is NOT the new modal, this should be the original modal that appears for non-consolidated cases).
- [x] After confirming service:
     - [x] Print for paper service appears (if parties are receiving paper service)
     - [x] Document is filed on the docket record of only this case, not filed in any other cases in the consolidated group.
     - [x] After clicking on the document title from the docket record, the coversheet on the document does NOT have:
     - [x] ", et al.," appended to the Petitioner's name(s) on the left side of the caption
     - [x] Any other docket numbers of all cases in the consolidated group on the right side of the caption. 


#### 12) Regression test the other Multi-docketing workflows

#### 13) Regression test this story with the Feature Flag set to Off

**Comment by rachelschneiderman** [comment]
This story is blocked until the [multi-docketing refactoring story](https://github.com/flexion/ef-cms/issues/9681) has been completed so as not to conflict.

**Comment by ttlenard** [comment]
Testing Results 1/30/2023

I stopped testing at test case 2. Noticed a few things here.

1.  For the second "Expected Results" checkbox : The modal no longer has the "This group has parties receiving paper service" where it then lists the individuals in the group with paper service.  I did some additional testing with this and actually noticed that this section of the modal is no longer appearing in the modal when serving a court issued document across a consolidated group either.  (I checked staging and it is still appearing over there.)

This is the section I am talking about. Here it is, taken from Staging:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/143c631e-750c-43c7-87d3-8905ea31c299)

This screen grab is taken from Test, notice that it is missing the paper service section.  I  have parties that receive paper service in this group, but it is not appearing on this modal anymore:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/86dea72b-a6c5-4234-8b65-b263c83896b6)

2. The second issue that I found is that I went ahead and clicked on save and serve.  Ran into the issue that we have seen before while testing ustaxcourt/ef-cms#6969.  If a user has multiple tabs open while multi-docketing, and a party has paper service, the subsequent tabs get "taken over" with the print for paper service screen.  See the comment that I wrote in ustaxcourt/ef-cms#6969 on 6-28-22.  This behavior is explained in detail there.

3. I also found that if you have Mutiple tabs open, and you save first, and then serve a decision type of document (PSDE) on the lead case, all of your additional tabs that you have open will switch over the 400 error screen:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/096fd8b3-963a-49aa-9ce5-6d8c2df1512c)
