### ISSUE TITLE
Sealing E-mail Address (formerly flexion#9619)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8271]
As a docket clerk, so that I can keep petitioner identity confidential when required, I need to be able to seal a petitioner's email address.

In some instances (whistleblower cases, innocent spouse cases, etc.) it is advisable for the petitioner's email address to be hidden from the public and other parties associated with the case. To facilitate this, docket clerks need the ability to apply a seal to the email address of a petitioner.

This is strictly a change w/r/t visibility - sealing the email address has no impact to electronic or paper service.

## Acceptance Criteria
SEALING:
* If a petitioner has an email address on record, sealing the address also seals the email address and petition email address from view
  - Confirmation modal text is updated to inform the user that email address will be sealed
* When sealed, the email address is visible only to Court users on the Case Information screen
* When sealed, the email address displays to Court users in red text with a lock icon (similar to how sealed addresses are displayed - see screenshot below)
* When sealed, the email address does NOT display in any element of the JSON to parties or the public
  - Check Docket Entry JSON's "served to" node in particular
* A sealed email address can be edited by the logged in owner as usual
* If a petitioner has electronic service and their email address is sealed, electronic service is not impacted/interrupted
* When an admissions clerk enters a new email address for a petitioner: 
    - if the physical address is sealed, automatically seal the email address upon saving the record
    - if the physical address is not sealed, do not automatically seal the email address upon saving the record
----------
Notice of Change of Email changes:
* When a new email address is added and automatically sealed (see above AC), the NOCE text reflects "SEALED BY COURT ORDER" as the new email address (screenshot below: NOCE_2)
* When a sealed email address is edited, the NOCE text reflects "SEALED BY COURT ORDER" as both the old and the new email address (screenshot below: NOCE_3)
----------
* As part of this story, we need to identify any petitioners on non-Closed/Closed-Dismissed cases with a sealed physical address and seal their e-mail address as well. We also need to do this for any cases closed within the last 6 months of the go-live date.

## Notes

*Mock up of sealed emal address as displayed internally to the Court:

![Image](https://github.com/user-attachments/assets/1e1fe4fa-6197-4da4-beef-8808c10789ea)

* Check JSON for service to IRS to ensure appropriate visibility

* NOCE_2: 

[NOCE_2.pdf](https://github.com/user-attachments/files/19095232/NOCE_2.pdf)

* NOCE_3:

[NOCE_3.pdf](https://github.com/user-attachments/files/19095239/NOCE_3.pdf)

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Does sealing address seal both petitioner email address and petition email address? - Y
- Sealing only seals that case and not all cases for that petitioner, correct? They would manually go into each case to seal if necessary? - Correct
- There is a modal that appears when you click seal, should we update this to indicate it seals both address and email address? - Y
- You cannot unseal a sealed address. - Correct

**Comment by katiecissell** [comment]
UX Notes:

[Figma File
](https://www.figma.com/design/7eZ3PAFGZHYiEs4TpzVQGw/USTC-%7C-9619-Seal-Email-Address?node-id=27-104&t=EyFQDnj6bXg5jecL-1)

These patterns will apply to petitioner and intervenor/participant parties.

Update the seal checkbox text to:

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/477ceacf-2fe1-4c4f-8ca8-33f166f47688" />

The modal that appears when you check the box to seal should be updated to:

<img width="806" alt="Image" src="https://github.com/user-attachments/assets/cd203023-e780-48f8-bbf8-f3280ed8aaa9" />

The new information that is now sealed should display in red text like the current pattern.

<img width="410" alt="Image" src="https://github.com/user-attachments/assets/826ebecf-b3e7-437a-827c-2f22680b22a4" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk updates the contact information for a petitioner with electronic service whose contact information has no current seal; The text for the checkbox to seal address has been updated.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Case Information tab
- Click on the Parties Tab
- Click on the edit link for a Petitioner (be sure that the address for this petitioner has not been sealed prior to this story)
- Review the page:

Expected Results:
- [x] **NEW FUNCTIONALITY** - The checkbox that used to say "Seal address" now displays "Seal contact information"



#### 2) Docket Clerk checks the box for Seal contact information; new modal displays.

- Continuing from the previous test
- Check the box for Seal contact information

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new modal displays that is titled, "Seal the following information for [Petitioner Name]?
- [x] **NEW FUNCTIONALITY** - Modal displays the current Address, Phone number, Email address and Petition Email for the user.



#### 3) Docket Clerk clicks on the Close link in the top right of the modal; Modal closes; contact information is not sealed.

- Continuing from the previous test
- Click on the Close link at the top right of the modal

Expected Results:
- [x] The modal closes and the user is navigated back to the Edit Contact info screen.
- [x] The Edit contact information checkbox is not checked
- [x] The address/email address of the petitioner is not sealed.



#### 4) Docket Clerk checks the box to Seal contact information; Clicks on the "No, Cancel" button; Modal Closes; Contact information is not sealed.

- Continuing from the previous test
- Check the box for Seal Contact information
- From the modal, click on the "No, Cancel" button 

Expected Results:
- [x] The modal closes and the user is navigated back to the Edit Contact info screen.
- [x] The Edit contact information checkbox is not checked
- [x] The address/email address of the petitioner is not sealed.



#### 5) Docket Clerk checks the box to Seal contact information; Clicks on the "Yes, Seal" button; Modal Closes; Checkbox for the Seal contact information is checked.

- Continuing from the previous test
- Check the box for Seal Contact information
- From the modal, click on the "Yes, Seal" button 

Expected Results:
- [x] The modal closes and the user is navigated back to the Edit Contact info screen.
- [x] **NEW FUNCTIONALITY** - The Edit contact information checkbox is checked, cannot be unchecked per current functionality.



#### 6) Docket clerk clicks save on the Edit contact info page; user is routed to the Parties tab; Updated display for sealed contact information.

- Continuing from the previous test
- Click on the Save button

Expected Results:
- [x] User is routed to the Parties tab of the Case
- [x] **NEW FUNCTIONALITY** - The Petitioner card now has the email address of the user displayed in red text and it is indented with the sealed address info (see mock)
- [x] **NEW FUNCTIONALITY** - If there was a Petition email, it is displayed in red text next to the red lock icon
- [x] **NEW FUNCTIONALITY** - If there wasn't a Petition email, it displays "Not Provided" under the Petition email address header.
- [x] Case JSON indicates that the email is sealed. Docket Clerk can still see the email in the JSON per usual visibility rules.



#### 7) Docket Clerk views a case in the system that already has a sealed address and the Petitioner has eAccess; email is now also sealed.

- Log in to DAWSON as a docket clerk
- Navigate to a case in the system that already had a sealed address, and the Petitioner also has eAccess (See Tenille - she has a list of cases)
- Click on the Case information tab, and then select the Parties tab
- Review the Petitioner card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petitioner card now has the email address of the user displayed in red text and it is indented with the sealed address info (see mock)
- [x] **NEW FUNCTIONALITY** - If there was a Petition email, it is displayed in red text next to the red lock icon
- [x] **NEW FUNCTIONALITY** - If there wasn't a Petition email, it displays "Not Provided" under the Petition email address header.
- [x] Case JSON indicates that the email is sealed. Docket Clerk can still see the email in the JSON per usual visibility rules.


#### 8) Petitioner with one case that has a sealed address (and email) changes their email; NOCE is generated on the docket record and has "Sealed by Court Order" in the text of the NOCE.

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that you have only a single case associated with your account, and the case has a sealed email
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a NOCE on the docket record
- [x] **NEW FUNCTIONALITY** - The text of the NOCE matches the "NOCE 3" example that is attached to this story
- [x] Case JSON indicates that the email is sealed. Petitioner cannot see the email or the address in the JSON per usual visibility rules.



#### 9) Petitioner has 2 cases; One case has a sealed address (and email), and the other case does not have a sealed address (or email); Petitioner changes their email; 2 different NOCE's are generated.

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that you have only at least two cases associated with your account, and one case has a sealed email, the other does not have a sealed address
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record of both cases (the one with the sealed address and the one without the sealed address)

Expected Results:
- [x] **NEW FUNCTIONALITY** - Both cases have a NOCE on the docket record
- [x] **NEW FUNCTIONALITY** - On the sealed address/email case, the text of the NOCE matches the "NOCE 3" example that is attached to this story
- [x] On the sealed address/email case, Case JSON indicates that the email is sealed. Petitioner cannot see the email or the address in the JSON per usual visibility rules.
- [x] **NEW FUNCTIONALITY** - On the case that does not have the sealed address/email, the NOCE is the standard NOCE that shows the old email + the new email
- [x] On the non-sealed address/email case, Case JSON indicates that the email is not sealed. Petitioner can see the email and the address in the JSON per usual visibility rules.



#### 10) Regression test - Petitioner with no sealed address/email changes their email; Standard NOCE is generated

- Log in as a Petitioner (be sure that you have access to their email)
- Be sure that none of the cases you are associated with have a sealed address/email
- Click on the person icon in the upper left corner
- Click on My Account
- Change your email
- Verify the email
- Review the docket record

- [x] Standard NOCE is generated as per normal



#### 11) Admissions clerk adds in a new email for a Petitioner whose address is currently sealed; Email is automatically sealed and new NOCE is generated.

**Part 1**
- Log in as an Admissions clerk
- Navigate to a case where a Petitioner is currently receiving paper service, and their address is sealed (see Tenille for an example case)
- Click the Edit link on the Petitioner card
- Add in a new email for the Petitioner (be sure that you have access to this email address)
- Save the page
- Review the Petitioner card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The pending email is displayed as sealed

UPDATED TEST (added 9/23/25)
- Log out as admissions clerk
- Log in as a Court user (not admissions or docket)
- Navigate to the case from above
- Click on Case information tab
- Click on the parties tab

Expected Results:
- [ ] Red lock icon with red text "Address, phone, and email sealed"
- [ ] Pending email address does not display

** Part 2**
- Next, log out as the court user
- Go to your Petitioners email and log in to DAWSON and change the temp pw
- Navigate to the case

Expected Results
- [x] **NEW FUNCTIONALITY** - There is a NOCE on the docket record
- [x] **NEW FUNCTIONALITY** - The text of the NOCE matches the "NOCE 2" example that is attached to this story

**Part 3**
- Click on Case information tab and then select the Parties tab
- Review the Petitioner Card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The address and email are not displayed, and the text states, "Address, Phone and email sealed" (the text "no email provided" is no longer displayed.
- [x] Petition email address header and data are never displayed to external users

*Repeat the test above, but have the admissions clerk add the same email to a case where the address of the Petitioner is NOT sealed.
- [x] Normal process occurs, standard NOCE is generated on the case



#### 12) Complete the tests above, but with the following roles instead of a Docket Clerk

- [x] Clerk of the Court
- [x] Case Services Supervisor



#### 13) Regression Tests:

- [x] Petitioner without a sealed address changes their address/phone - Standard Notice of change is generated as per normal
- [x] Petitioner with a sealed address/phone changes their address/phone - No Notice of Change is generated as per normal
- [x] Admissions clerk adds in an email to a case without a sealed address - Standard processes occur and normal NOCE is generated and added to the docket record
- [x] Check the case JSON to ensure that if a email/address is sealed, that we NEVER display the email/address to any party, the public, or anyone at the court that is not a Admisisons clerk, Docket Clerk, CotC, or CSS.

**Comment by ttlenard** [comment]
@alexdziarn @paulo-filho-ctr 

Testing Feedback:
- [x] Emails in pending status are currently displayed for all internal court users (the pending email address is not displayed for external users - yay! this is good). The pending email address should only be visible to Admissions clerks or Docket Clerks.  I've added an additional test case above in test case 11 to check for this. 

Here is a screen grab with a sealed Pending email address that is currently getting displayed for internal court users that are not admissions clerks or Docket clerks.  We need to remove the sealed pending email address from view for these Court users.

<img width="1656" height="931" alt="Image" src="https://github.com/user-attachments/assets/f0b4c000-4183-4d22-9de6-11a43d859a10" />

- [x] If possible, can you also please remove the capitalization from "Phone" in the screen grab above? Thanks!

**Comment by ttlenard** [comment]
@alexdziarn @paulo-filho-ctr 

Testing Feedback:
- [x]  Sealed email addresses are still displaying on the case JSON for the following users and they shouldn't be. The users that should not see the emails are 1) Parties on the case, 2) Internal Court users that are not docket or Admissions.  Email addresses should not be displayed anywhere on the Case JSON if they are sealed. (Email addresses are not being displayed for Public users or External users not associated with the case - good!)

Here is the Preview tab on the case json. Note that the email address for the party with a sealed email is displayed for every document on the docket record.

<img width="2038" height="1032" alt="Image" src="https://github.com/user-attachments/assets/dbf9bb8e-9a5f-44ac-8b08-02c6db287a34" />

Here is the Response tab.  Email address for the party with the sealed email is displayed in the Served Parties section for every document on the docket record.

<img width="1990" height="1160" alt="Image" src="https://github.com/user-attachments/assets/bab9d35b-7808-4b45-a8fb-8181a82ea9fd" />

**Comment by alexdziarn** [comment]
- updated some capitalization
- updated conditional render for pending email
- removed email from docketentry.servedParties if they are not a dockerclerk or admissionsclerk
