### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8276]
**Describe the Bug**
We received a helpdesk ticket that indicated that a closed case (closed by stipulated decision) had a blocked label showing, even though there were no pending items or deadlines on the case.  After doing some investigation, we found the following information in the case JSON:
automaticBlocked = true
automaticBlockedDate: "2022-6-17T14:09:02:6502"
automaticBlockedREason: "Due Date" 

There were no due dates remaining on the case. We checked the logs, and the due date and pending items had been deleted prior to the case being closed.

I met with Rachel and we think that after a case is calendared, the system doesn't check to remove the blocked label if the case is closed via the stipulated decision workflow.  

Also - Jim did put together a query to find out how many cases were in this state currently in production, and we had ~100.   With this bug fix, we would need to fix all of the cases that fit the scenarios below. (Note - we did manually fix the case that was reported to us)

Case status = closed
automaticBlocked = true
IsPendingItems = false

**Business Impact/Reason for Severity**
low

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
docket, other court users

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. As a docket clerk, Go to the blocked cases report (it will have a deadline or a pending item)
2. Open one of the cases in the list and manually add it to an open trial session
3. Open the case, also open the case JSON in the console.
4. You should see that there is an automaticBlocked = true
5. Click on the tracked items tab, delete the pending item or deadline
6. Upload a pdf in the case and ensure that the document type is stipulated decision. 
7. Sign the stip decision and add it to the docket 
8. Blocked label appears in the Case Header.

*Note: If you remove the case from the trial session, the block label will not appear.  Seem to have to do with a case being associated with a trial session. 

**Expected Behavior**
Blocked label doesn't appear when all pending items or deadlines have been deleted.

**Actual Behavior**
A clear and concise description of what actually happened.
Blocked label appears even through pending items and deadlines have been deleted.

**Screenshots**
Here is the case that was reported to us originally in Production. Notice the case JSON with the automaticblocked fields:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/8c2a94ac-223d-42e7-bc0a-0c1065941585)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Tasks
- [x] Reproduce bug locally
- [x] Find source of bug
- [x] Resolve bug, wrap with tests
- [x] Write migration to resolve existing cases with bug
- [ ] Run migration locally to verify bug fix
- [ ] Deploy migration against an experimental environment

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rosiehsmith** [comment]
Some relevant history I found: a [bug fix ](https://github.com/flexion/ef-cms/pull/4417/files)from 3 years ago is related. It seems as though it was intentional that if a case has a trial session, it wasn't desired to system/automatic block that case. So in this bug, this is impacting the inverse, where we want the automatic block to be removed on a case that has a trial session.
