### ISSUE TITLE
BUG: When a Lead case is removed from a trial, member cases no longer display on the Session Copy Page

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8279]
**Describe the Bug**
If a Lead case in a consolidated group is removed from the trial session, the member cases that are still a part of the trial session are not displaying on the Session copy page.  These cases do still appear on the Trial Session info page.

**Business Impact/Reason for Severity**

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Judge, Chambers, Trial Clerk, Docket

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing

**To Reproduce**
1. Log in as a Judge, Chambers, or Trial Clerk for this 
2. Navigate to a Trial Session that has a Consolidated group of cases that are calendared 
     - On the Trial Session Information Page, the Cases are displayed/grouped appropriately
     - On the Session Copy page, Cases are displayed/grouped appropriately
3. Click on the docket number of the lead case and Navigate to the Case information tab of the Lead case in the Consolidated Group
4. Remove the lead case in the group from the trial session.
5. Navigate to the trial Session Info Page of the session that you were looking at before. 
6. Cases in the consolidated group are displayed appropriately on the Trial Session information page (Open Cases list + Inactive Cases list + All Cases List)
7. Next, open up the Session Copy page.
8. The Case list does not display correctly.
     - Member cases that are still calendared are not appearing on the Session Copy Page
     - Total Shown is still counting the member cases, even though they do not appear on the list.

*Note - It appears that the Session copy page does not display the member cases in a consolidated group if the lead case is removed from the trial session.  Once I added the lead case back to the trial session, it was displaying appropriately (and the counter was correct) on the Session Copy page.

**Expected Behavior**
Member cases should still appear on the Session Copy Page, even if the lead case is removed

**Actual Behavior**
A clear and concise description of what actually happened.
When a lead case is removed from a trial session, the member cases no longer appear on the Session Copy list, even though the total count still counts them.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Tasks**
bug fix PR
https://github.com/ustaxcourt/ef-cms/pull/2703
