### ISSUE TITLE
BUG: Completing QC w/o edits changes docket entry on some filed documents

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8282]
**Describe the Bug**
When QCing an e-filed/lodged document, for some document types when QC is completed without any edits the docket entry is re-titled and a Notice of Change of Docket Entry is generated.

This appears to happen for all document types having the following scenarios as listed in https://github.com/ustaxcourt/ef-cms/blob/staging/shared/src/tools/externalFilingEvents.json when the target document required to be associated with the filing was docketed with Additional Info added to its cover sheet.

Nonstandard A
Nonstandard C
Nonstandard D
Nonstandard F
Nonstandard H if the target document is one of the above scenario types and meets the criteria below

All of these document types require the user to associate the document being filed with a target docket entry that currently exists. If that target document has "Additional Info" associated with it that is added to the cover sheet, then when QC is completed on the filed document with no edits having been made in the QC process, the resulting docket entry will be modified to remove the "Additional Info" that should be a part of the title of the target document being referred to. In addition, a Notice of Docket Entry Change is generated and served.

Note that this problem does not occur if:
A) On the QC screen the target document is toggled between its initial value, another value, and then back to its initial value
B) The target document does not have any Additional Info added to its cover sheet at the time of docketing

**Business Impact/Reason for Severity**
The docket entry should not be modified unless explicitly done so by the docket clerk.

## Tasks

- [x] Remove duplicative additional info in generated coversheet after qc (PR)[https://github.com/ustaxcourt/ef-cms/pull/2752/files]
- [x] Create Devex Task for updating the docket entry's document title after modification
- [x] (Based on feedback from Tenille) Remove duplication of additional info in case detail page after qc

**In which environment did you see this bug?**
TEST, PROD

**Who were you logged in as?**
Docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Investigating report

**To Reproduce**

(Note: Feel free to have me walk through this with you when picking up this bug, it might be clearer if I demonstrate. - CH)

1. Buckle up. You'll need a docket with whom you can log in as either the petitioner or a practitioner associated with the case.
2. As a docket clerk, create a Paper Filing for a petitioner, Motion for Summary Judgment.
3. Add "Plus Superfluous Text" in the Additional Info box on the Add Docket Entry screen.
4. Check the "Add to cover sheet" box.
5. Save the docket entry.
6. Note the text of the entry on the docket record: "Motion for Summary Judgment Plus Superfluous Text". This is Docket Entry A.
7. Log in as a party to the case.
8. File a document, and choose the document type "Response".
9. On the "Which document are you responding to?" menu, choose "Motion for Summary Judgment Plus Superfluous Text". Click Continue.
10. Complete the flow to file the document.
11. Log in as a docket clerk and navigate to the docket record.
12. Note the most recent entry on the record: "Response to Motion for Summary Judgment Plus Superfluous Text" - this is Docket Entry B.
13. Click into the docket entry. Note the correct cover sheet on the document that says "Response to Motion for Summary Judgment Plus Superfluous Text"
14. Click the Complete QC link.
15. On the QC screen, note the screen title, document cover page, and target document menu all correctly display "Response to Motion for Summary Judgment Plus Superfluous Text"
16. Make no changes on this screen. Click Complete.
17. Note that the green validation box now says "Response to Motion for Summary Judgment has been completed".
18. Navigate back to the docket record.
19. Note that Docket Entry B now displays as "Response to Motion for Summary Judgment".
20. Note that a Notice of Docket Change for Docket Entry B has been issued.

**Expected Behavior**
Docket Entry B continues to retain its original title as displayed on the initial docket entry, incorporating all info from Docket Entry A and its Additional Info into its title as reference. No change is made to Docket Entry B in the QC process, so no Notice of Docket Change is issued.

**Actual Behavior**
Docket Entry B is updated to remove the Additional Info part of Docket Entry A's title. A new cover sheet is generated with the incorrect title. A Notice of Docket Change has been issued despite the docket clerk not having edited anything in the QC process.

Note that you can see a "preview" of the soon-to-be-mistitled-docket-entry in the UI if you click "Complete and Send Message" on the QC screen instead of "Complete" - the attachments portion of the message UI displays the incorrect docket entry title as well.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by TomElliottFlexion** [comment]
Note: quick fix is on `temporary-bug-branch-10/14/22`

**Comment by ttlenard** [comment]
Testing Feedback 11/14/2022.

At step 16, if the docket clerk clicks "Complete" all appears to be working as desired, but if a docket clerk clicks "Complete and Send Message", we are still seeing the same behavior as we did before. We need to be sure that it is fixed for both workflows.

Here are some screen grabs if you click "Complete and Send Message"

I see on the message that it is displaying the document type w/o the superfluous text.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/10cdbd7a-645a-4869-a3b9-8dfdc0a62365)

Green confirmation banner does not display the superfluous text either:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/c57f5a8e-bbd8-4404-b1a3-344093a7584f)

And now I have that pesky notice of docket change. Notice the original document with the superfluous text, then the renamed document, and then the notice of docket change:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/55d4b233-f8ed-44de-94cf-2b314e70c230)

**Comment by ttlenard** [comment]
Testing feedback 11/29/2022

@Absolutestunna 

1. Docket clerk files a doc + superfluous text
2. Practitioner files a response to the doc
3. Docket QC's the filing and clicks "complete and send message"
4. On the message pop-up, none of that superfluous text shows up, and it would appear that the attachment is incorrect, b/c it doesn't have all the superfluous text displayed.
5. After the message is sent, all looks fine on the green confirmation banner, and on the docket record (the superfluous text is included appropriately - Yay!)
6. Issue appears to ONLY be what is displayed in the message pop-up.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2dd3501b-a2a7-4445-a778-9489bc7dc680)

**Comment by ttlenard** [comment]
Testing Feedback 12/13/2022

Everything looks great. Thanks for fixing.
