### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8288]
As the Clerk of the Court, so that I can accurately track IRS and Court-determined penalties assessed on a case, I need to be able to see individual penalties used to calculate a total amount.

Currently when multiple penalties for a year or period are entered to calculate an aggregate total, the individual penalties are entered in the UI, after which the calculation is performed and a total amount is entered for that value. However, these individual penalty values do not appear to persist, and cannot be viewed again once entered, either from the entry UI or from the case record itself on the Statistics tab.

We would like to make individual penalties that sum up to a calculated total penalty accessible and editable in DAWSON. This will allow the Court to report out on totals assessed and determined in a more granular manner when we evaluate YTD totals for IRS and Congress. Those numbers can inform policy decisions and provide transparency into USTC proceedings.

Note that this is part of a broader effort that will see us enhancing the penalty statistics in DAWSON to enable more detail and accuracy.

## Acceptance Criteria
* If multiple penalties on an IRS notice are calculated to a total penalty for a year or period, the user can view the individual penalties used to arrive at that calculated total
* If multiple penalties determined by the Court are calculated to a total penalty for a year or period, the user can view the individual penalties used to arrive at that calculated total
* When editing or entering the penalties from either the Case statistics or the Petition entry screen, any previously entered individual penalties for that year or period appear in the edit UI and are available for editing as usual
* No changes to the calculation function itself
* No changes/restrictions to user permissions w/r/t which roles can view or edit penalty information

## Notes
Screenshot of calculation UI:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/c623cc0f-7e62-4738-b1b6-15268ca695a5)

Case Information - Statistics view:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/895cd3cc-6bf7-447e-9ae4-98582661474f)

Petition Entry - Penalties view:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/dec898ac-4e46-4c9d-88bd-cf14d940b8c1)

* We will not be able to migrate in penalties entered prior to this feature completion.
* We do not necessarily need to indicate which cases contain viewable multiple penalties and which do not

## Tasks
- [X] Create Penalty Entity https://github.com/flexion/ef-cms/pull/9774
  - [X] Joi Validation
  - [X] Testing
- [X] Add penalties array to Statistic Entity https://github.com/flexion/ef-cms/pull/9774
  - [X] Add test coverage around array addition.
  - [X] Joi Validation
  - [X] Add methods for updating and adding a penalty into the penalty array.
- [x] Calculate Penalties Modal - IRS Penalties https://github.com/flexion/ef-cms/pull/9786
  - [x] Persist Itemized penalties
  - [x] Only show 1 penalty input field when first creating a statistic
  - [x] Persist $0.00 value penalties, only when manually typing in value
  - [x] Fix Cancel button
    - [x] Do not persist added fields that were not entered with a value
- [x] Calculate Penalties Modal - Court Determination 
  - [x] TODO
- [x] Case Information Statistics Tab Edit Year/Period page
  - [x] Populate Calculate Penalties IRS Notice Modal with IRS Totals if not itemized
- [x] Case Information Statistics Tab Add Year/Period page
- [x] Case Information Statistics Tab
  - [x] New Modal for Viewing Itemized Penalties 
- [x] UI changes in Case Creation Wizard
  - [x] UI Changes 
- [x] separate courtDeterminationPenalties into its own array on Penalty Entity
  - [x] fix flows to use new separate array

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
![Screen Shot 2022-12-21 at 2.16.05 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/309b4bde-ea98-466f-b6e3-f1e78652e937)
1. When a user clicks on "Calculate penalties on IRS Notice" and enters values, they will now have a button that says "Calculate and Save". This will replace the previous "calculate" button and function the same way, except... (see step 2).
2. When a user now returns to the "Edit Year/Period" calculator, it will trigger the "Calculate penalties on IRS Notice" modal, however the values will now persist as they were last entered. The new button label of "Calculate and Save" will reflect this new behavior.
3. The same behavior applies to "Calculate penalties as determined by court".

![Screen Shot 2022-12-21 at 2.06.11 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/aaed097f-f3a5-4769-970d-4cea2794ef88)
1. In the "Penalties" box, there will now be an additional link labeled "View Itemized Penalties" to the right of the Edit Year/Period for users who have edit access, or to the right of the determination value field when logged in as a court user without edit permissions.
2. This link is disabled when there are no itemized penalties 
3. When enabled, clicking on the link will trigger a modal with a running list of all itemized penalties, as well as the total (as illustrated in mockup above)
4. These values will match the values last entered in the Edit Year/Period calculation.
5. If there are no values in one of the columns, the column header still persists and those particular fields will be left blank.
6. There will be a "close" option on the top right of the modal.

**Comment by ttlenard** [comment]
##Test Cases

#### 1) Petitions Clerk enters multiple IRS Penalties for a given Year/Period when inputting a Paper Petition, Penalty data is saved.

- Log in as a Petitions Clerk
- Click on Document QC
- Click Start a new Petition
- Fill out the required fields and upload/scan in the Petition document
- On the IRS Notice tab, click the yes radio button indicating that the IRS notice was provided.
- Input the date of the notice, and then under the statistics Proposed by IRS section, input a year or period, followed by the total Deficiency.
- Click on the Calculate Penalties on IRS Notice link.
- In the Calculate Penalties on IRS Notice modal, add in multiple Penalties
- Click the Calculate and Save button.
- The Total Penalties box should display the total of the inputs that you put in the modal.
- Click on the Calculate Penalties on the IRS Notice link again.

Expected Results:
- [x] The individual penalties that you input are retained



#### 2) Petitions Clerk edits saved Penalties, updated Penalty data is saved and can be viewed.

- Continuing from the previous test, Click Calculate Penalties on IRS Notice.
- Edit the values of the Penalties that are in the pop-up
- Click Calculate and Save

Expected Results:
 - [x] The Total Penalties box displays the updated total.


#### 3) Petitions Clerk adds additional Penalties, newly added penalties are saved.

- Continuing from the previous test, Click Calculate Penalties on IRS Notice
- Click Add another penalty so that there are no more penalties that you can add
- Input additional Penalty data in each box
- Click Calculate and Save

- [x] The additional penalties are calculated in the Total Penalties box
- [x] When clicking on the Calculate Penalties on IRS Notice link again, the additional Penalty information is retained.



#### 4) Petitions Clerk adds multiple Years/Periods for the Statistics; Individual Penalty information is saved for all Years/Penalties.

- Continuing from the previous test
- Click Add Another Year/Period
- Fill out the Year/Period Info and the Deficiency
- Click on the Calculate Penalties on IRS Notice link.
- In the Calculate Penalties on IRS Notice modal, add in multiple Penalties
- Click the Calculate and Save button.
- The Total Penalties box should display the total of the inputs that you put in the modal.
- Click on the Calculate Penalties on the IRS Notice link again.

Expected Results:
- [x] The individual penalties that you input are retained
- [x] When editing the Penalties, the data is saved and the total is updated.


#### 5) Petitions Clerk Creates Case, Edits the Penalty information before serving Petition to the IRS.

- Continuing from the previous test
- Click on Create Case
- On the Review and Serve Petition Screen, Click the Edit button on the Penalty box
- Click on the Calculate Penalties on IRS notice link

Expected Results:
- [x] The individual penalties that you input previously are retained.
- [x] When editing the Penalties, the data is saved and the total is updated.


#### 6) Petitions Clerk Serves a Petition to the IRS; Penalty data is saved and can be viewed.

- Continuing from the previous test, click Review Petition (total penalty info should match what was on the edit screen)
- Click Serve to IRS
- Click Yes, Serve
- Click Done on the Print Paper Petition Receipt page
- Click on the Served tab
- Click on the Docket Record of the Petition that you just served
- Click on Case Information
- Click on the Statistics tab

Expected Results:
- [x] There is a new link to "View Itemized Penalties" next to the Edit Year/Period Link.
- [x] After clicking the link, a pop-up modal displays the itemized penalties that you entered in the previous tests, and displays the total penalties appropriately.
- [x] The Penalties in the Determination column will be blank at this point in the test.
- [x] Clicking the close button in the top right will close the modal.



#### 7) Petitions Clerk enters multiple IRS Penalties for a given Year/Period when QCing an electronically submitted Petition, Penalty data is saved.

- Log in as a Petitions Clerk
- Click on Document QC
- Click on Section Document QC
- Click on the url for an electronic petition from the Section QC list
- On the IRS Notice tab, click the yes radio button indicating that the IRS notice was provided.
- Input the date of the notice, and then under the statistics Proposed by IRS section, input a year or period, followed by the total Deficiency.
- Click on the Calculate Penalties on IRS Notice link.
- In the Calculate Penalties on IRS Notice modal, add in multiple Penalties
- Click the Calculate and Save button.
- The Total Penalties box should display the total of the inputs that you put in the modal.
- Click on the Calculate Penalties on the IRS Notice link again.

Expected Results:
- [x] The individual penalties that you input are retained


#### 8) Repeat test cases 2-6 with the electronically submitted Petition.

Expected Results:
- [x] All tests pass for the electronically submitted Petition.

#### 9) Petitions Clerk Edits Penalty data after the Petition is served to the IRS; Data is saved.

- Continuing from the previous test, Click Edit Year/Period.
- Click on the Calculate Penalties on IRS Notice link.
- Edit the values of the Penalties that are in the pop-up
- Click Calculate and Save

Expected Results:
 - [x] The Total Penalties box displays the updated total.

- Click Save on the Edit Year/Period page
- Click on the View Itemized Penalties link next to the Edit Year/Period link on the Statistics page.

Expected Results:
- [x] The updated itemized penalties appear in the pop-up modal.


#### 10) Clerk adds Deficiency (Determination) and Penalties (Determination) to a case; Individual Penalties (Determination) are saved.

- Log in as a Petitions Clerk, Docket Clerk, or the Clerk of the Court. (Be sure to test with all these roles.)
- Navigate to a case
- Click on the Case Information tab, and then click on the Statistics tab.
- Click on Edit Year/Period Link
- Add in a Deficiency (Determination) amount.
- Click on the Calculate penalties as determined by Court link.
- Enter in multiple penalties
- Click Calculate and Save
- The Total Penalties (Determination) box should display the total of the inputs that you put in the modal.
- Click on the Calculate Penalties as determined by Court link again.

Expected Results:
- [x] The individual penalties that you input are retained.

*If there are multiple years/periods be sure that you add Determination data to each year.


#### 11) Clerk Saves the Deficiency (Determination) and the Penalties (Determination); Itemized Penalty data is saved and can be viewed.

- Continuing from the previous test
- Click the Save button on the Edit Year/Period page

Expected Results:
- [x] Green confirmation banner indicating the statistics have been updated
- [x] The Determination fields are now populated on the Statistics Screen
- [x] After clicking the "View Itemized Penalties" link, the determination column data is populated and matches the data that you entered in the previous test.

*If there are multiple years/periods be sure that you repeat this test for each year/period


#### 12) Clerk edits Determination data; Itemized Penalty data is saved.

- Continuing from the previous test, Click Edit Year/Period.
- Click on the Calculate Penalties as determined by Court link.
- Edit the values of the Penalties that are in the pop-up (They should still be populated).
- Click Calculate and Save

Expected Results:
 - [x] The Total Penalties (Determination) box displays the updated total.

- Click Save on the Edit Year/Period page
- Click on the View Itemized Penalties link next to the Edit Year/Period link on the Statistics page.

Expected Results:
- [x] The updated itemized Penalties (Determination) column appear in the pop-up modal.


*If there are multiple years/periods be sure that you repeat this test for each year/period


#### 13) Court users can view itemized penalty data.

- Log in as a Court user (not a Petitions Clerk, Docket Clerk, or the Clerk of the Court).
- Navigate to the case from the previous tests that has itemized Penalty data saved. 
- Click on the Case information tab
- Click on the Statistics tab

Expected Results:
- [x] Penalties section now has a "View Itemized Penalties" Link to the right of the Determination.
- [x] After clicking on the link, a pop-up modal appears and displays the itemized penalties for both the IRS notice and the Determination.

*If there are multiple years/periods, be sure that the "View Itemized Penalties" link is available for each year.


#### 14) Court user navigates to a case that does not have itemized penalty data; no link to view itemized Penalties is displayed for the user.

- Log in as any court user.
- Navigate to a case that does not have any itemized Penalty data
- Click on the Case information tab
- Click on the Statistics tab

Expected Results:
- [x] There is no link displayed, or the link will be disabled (to be determined by devs) to "view itemized Penalties".

**Comment by shumway-tm** [comment]
@cholly75 @ttlenard Placing blocked label on story until we hear back from court regarding conversation with Holly about whether writing a value in the irsTotalPenalty field should override itemized penalties when the totals do not match.

**Comment by codyseibert** [comment]
@cholly75 @swongCO we had a discussion and decided to make the total penalties read only and force users to edit via the modal.

**Comment by shumway-tm** [comment]
@TomElliottFlexion @rgoshen After discussing with @cholly75, we have determined that individual IRS Penalties and the Court determined Penalties will remain unlinked and independent of each other. 

We also discussed potentially wrapping this feature with a feature flag. This isn't a story a story requirement but is a nice-to-have per @cholly75.

Additionally, one other small change is in the itemized penalties modal. It no longer must by default show 5 penalty fields. The user can add additional ones as needed.

@liadmccabe @swongCO

**Comment by shumway-tm** [comment]
Per another discussion with @cholly75 , a feature flag will not be required. Placing on a hosted environment to demo to court users before deploying is sufficient in place of the feature flag. @jasonfu9966 @rgoshen @TomElliottFlexion @jhansen-flexion @ttlenard

**Comment by swongCO** [comment]
Feedback from UX review:
• the Edit page - "Select Year or period" - Year should be lowercase
• the penalty determination modal - capitalize "determined" in the modal title; replace "USTC" with "Court"

**Comment by TomElliottFlexion** [comment]
Update: Replacing 'USTC' with 'Court'!

**Comment by ttlenard** [comment]
All tests pass! Thanks all!
