### ISSUE TITLE
Additional Case Status Category - Closed (Dismissed)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8293]
As the Clerk of the Court, so that I can accurately assess data related to cases that were dismissed, I need a new case status of "Closed - Dismissed" added to DAWSON.

There is demand for more data specifically around cases that have been explicitly dismissed by the Court, but currently this is hard to obtain due to the fact that all cases share a status of Closed whether they were settled, adjudicated, withdrawn, or dismissed. To be able to better segment these cases, we would like to add "Closed - Dismissed" as a selectable Case status.

## Acceptance Criteria
* On the Case Status dropdown menu, the status "Closed - Dismissed" is available to select
* Selecting this status assigns the label and status of "Closed - Dismissed" to the case
* "Closed - Dismissed" cases behave in all respects like Closed cases in DAWSON with the attendant business rules
* "Closed - Dismissed" status can be manually assigned by a user to a case
* "Closed - Dismissed" value should be in alphabetical order in line with the rest of the list values for Case Status.
* When an Order of Dismissal, Order of Decision and Dismissal, or Order of Dismissal for Lack of Jurisdiction are added to the docket record for a case, change the status of the case to "Closed - Dismissed" instead of "Closed".

## Notes
Case Status menu:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/7de0ac3d-3f60-4316-bd5a-06df2bb8f6db)

## Tasks
- [x] Add new case status value - Rachel (https://github.com/flexion/ef-cms/pull/9760)
  - [x] Ensure it displays in edit case status modal drop-down and is sorted properly
- [x] Create constant that represents all close status types - Rachel (https://github.com/flexion/ef-cms/pull/9761)
- [x] Create case entity method to determine if case is closed (status closed OR closed - dismissed) - Rachel (https://github.com/flexion/ef-cms/pull/9762)
  - [x] Replace checks for closed status with new method - Rachel
- [x] Update interactor to set case status to closed (dismissed) when qualifying order is filed on case - Mrinalini (https://github.com/flexion/ef-cms/pull/9765)
- [x] Determine if migration script is needed - Rosie, Rachel (https://github.com/flexion/ef-cms/pull/9771, https://github.com/ustaxcourt/ef-cms/pull/2969)
  - [x] Clear `closedDate` on cases that are NOT closed
- [x] Add method to clear `closedDate` on cases where the status is NOT one of the closed statuses (`reopenCase()`) - Rachel, Rosie (https://github.com/flexion/ef-cms/pull/9770)
- [x] Question: Do we need to migrate instances where `ODJ`, `OD`, `ODD` were filed and closed case with `Closed` status so they are now `Closed - Dismissed` status? 
  - [x] Answer: No 

DOD
https://github.com/flexion/ef-cms/pull/9773

Feedback
https://github.com/ustaxcourt/ef-cms/pull/2991

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
@cholly75 Should we add in the A/C that when an Order of Dismissal, Order of Dismissal and Decision, or an Order of Dismissal for Lack of Jurisdiction are added to the Docket record, the Case status will update to "Closed - Dismissed" instead of just "Closed" as it currently does?

See this story: https://github.com/flexion/ef-cms/issues/2380
See this spreadsheet that shows which Orders change the Case Status automatically: https://docs.google.com/spreadsheets/d/1B5vfS_pDswQOKN1rY0wa7rY5rbGJ8z83mTeT6Qt-7_0/edit#gid=0

Thinking these two Orders should probably update the case status to "Closed - Dismissed" automatically?

If we do update the A/C to reflect this, I would also suggest updating this spreadsheet?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Clerk manually updates the Case Status for a case; "Closed - Dismissed" is available to select

- Log in as a docket clerk or Clerk of the Court
- Navigate to a case
- Click on the Case Information tab
- Click on the link to "Edit Case Status/Caption"
- Click on the Case Status dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - The new Case status for "Closed - Dismissed" is available to select. 
- [x] **NEW FUNCTIONALITY** - The Closed - Dismissed status is displayed below Closed in the dropdown



#### 2) Case Status Label for "Closed - Dismissed" is displayed on the Case Header and in the JSON

- Continuing from the previous test
- Select "Closed - Dismissed" from the dropdown
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case Status header now displays "Closed - Dismissed"
- [x] **NEW FUNCTIONALITY** - When viewing the Case JSON, the Case status displays "Closed - Dismissed"



#### 3) Court User runs a case inventory report, selects Case Status dropdown filter; new "Closed - Dismissed" status is not in dropdown picklist.

- Court User clicks on the Reports Header
- Click Case Inventory Report
- The Run Case Inventory Report modal will display
- Click on the dropdown for Select Case Status

Expected Results:
- [x] The "Closed - Dismissed" case status will not be present in the picklist.



#### 4) Parties to a case that has the status of Closed - Dismissed see this case in their Closed Cases list on the My Cases Page.

Preconditions
- Ensure that Parties (Petitioner, Intervenor, Participant, Private Practitioner, IRS Practitioner) are associated with a case
- Ensure that the Case Status has been set to Closed - Dismissed.

- Log in as a Party to a Case 
- Click on the Closed Cases tab on your My Cases Page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The case that was set to "Closed - Dismissed" will be in the Closed Cases List

*Repeat this test with all of the parties listed above



#### 5) Case has been in the Closed - Dismissed Status for more than 6 months, party updates their mailing address/phone; No Notice of Change service emails or docket entries get added to the case.

Preconditions
- Need to have the Closed - Dismissed status on a case for more than 6 months (can we manually manipulate the data to do this?)

- Log in as a Party to a case
- Click on the Closed Cases Tab
- Select the case that is Closed - Dismissed status (for more than 6 months)
- Click on the Case information tab
- Click on the Parties tab
- Click the Edit link on your contact card
- Update some of your contact information
- Click Save

Expected Results:
- [x] No Notice of Change documents are added to the docket record of the Closed - Dismissed case.
- [x] No service emails are sent.

*repeat this test with different parties



#### 6) Case has been in the Closed - Dismissed Status for more than 6 months, party updates their email address; No Notice of Change service emails or docket entries get added to the case.

Preconditions
- Need to have the Closed - Dismissed status on a case for more than 6 months (can we manually manipulate the data to do this?)

- Log in as a Party to a case
- Click the down arrow next to the person icon in the upper right side of the screen
- Click on My Account
- Click on the Change email link
- Enter a new email address and click save

Expected Results:
- [x] No Notice of Change documents are added to the docket record of the Closed - Dismissed case.
- [x] No service emails are sent.

*repeat this test with different parties


#### 7) Case has been in the Closed - Dismissed Status for less than 6 months, party updates their mailing address/phone; The Notice of Change service emails and docket entries get added to the case.

Preconditions
- Need to have the Closed - Dismissed status on a case for less than 6 months

- Log in as a Party to a case
- Click on the Closed Cases Tab
- Select the case that is Closed - Dismissed status for less than 6 months
- Click on the Case information tab
- Click on the Parties tab
- Click the Edit link on your contact card
- Update some of your contact information
- Click Save

Expected Results:
- [x] The Notice of Change documents are added to the docket record of the Closed - Dismissed case.
- [x] Service emails are sent.

*repeat this test with different parties



#### 8) Case has been in the Closed - Dismissed Status for less than 6 months, party updates their email address; The Notice of Change service emails and docket entries get added to the case.

Preconditions
- Need to have the Closed - Dismissed status on a case for less than 6 months

- Log in as a Party to a case
- Click the down arrow next to the person icon in the upper right side of the screen
- Click on My Account
- Click on the Change email link
- Enter a new email address and click save

Expected Results:
- [x] The Notice of Change documents are added to the docket record of the Closed - Dismissed case.
- [x] Service emails are sent.

*repeat this test with different parties



#### 9) Practitioner is associated with a case that has the Closed - Dismissed Status; This case is listed on the Print Case List report.

- Log in as a court User
- Click on the Advanced tab
- Search for a practitioner that is associated with a Closed - Dismissed case
- Click on the Print case list link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Closed - Dismissed Case will be in the Closed Cases Section of the printable report

*Be sure that you repeat this test and search for both Private Practitioners and IRS Practitioners



#### 10) Regression test some things:
- [x] Cases in the Closed - Dismissed Status do not appear on the Eligible case list when calendaring
- [x] If a case is in the Closed - Dismissed Status, show this status in the Case status column on the Pending and Blocked reports
- [x] If a case is in the Closed - Dismissed Status, show this status in the Case status column on the Messages pages (check My messages/all boxes, and Section Messages/all boxes)
- [x] If a case is in the Closed - Dismissed Status, show this status in the Case status column on the Document QC pages (check My Document QC/all boxes, and Section Document QC/all boxes)


#### 11) Order of Dismissal is added to a docket record; Case Status is automatically set to "Closed - Dismissed".

- Log in as a docket clerk
- Go to a case that is currently in one of the open status'
- Click Create, and select Order or Notice
- Select Order of Dismissal
- Click Continue
- Draft the Order and click Save
- Add in a Judges signature, and save it
- Click Add Docket Entry
- Add a Judges name and a description
- Click Save and Serve
- Click Yes, Serve
- Click Done on the Print paper service page if necessary 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case Status header now displays "Closed - Dismissed"
- [x] **NEW FUNCTIONALITY** - When viewing the Case JSON, the Case status displays "Closed - Dismissed"


#### 12) Order of Dismissal and Decision is added to the docket record; Case Status is automatically set to "Closed - Dismissed".

- Log in as a docket clerk
- Go to a case that is currently in one of the open status'
- Click Create, and select Order or Notice
- Select Order of Dismissal and Decision
- Click Continue
- Draft the Order and click Save
- Add in a Judges signature, and save it
- Click Add Docket Entry
- Add a Judges name and a description
- Click Save and Serve
- Click Yes, Serve
- Click Done on the Print paper service page if necessary 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case Status header now displays "Closed - Dismissed"
- [x] **NEW FUNCTIONALITY** - When viewing the Case JSON, the Case status displays "Closed - Dismissed"


#### 13) Order of Dismissal for Lack of Jurisdiction is added to the docket record; Case Status is automatically set to "Closed - Dismissed".

- Log in as a docket clerk
- Go to a case that is currently in one of the open status'
- Click Create, and select Order or Notice
- Select Order of Dismissal for Lack of Jurisdiction
- Click Continue
- Draft the Order and click Save
- Add in a Judges signature, and save it
- Click Add Docket Entry
- Add a Judges name and a description
- Click Save and Serve
- Click Yes, Serve
- Click Done on the Print paper service page if necessary 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case Status header now displays "Closed - Dismissed"
- [x] **NEW FUNCTIONALITY** - When viewing the Case JSON, the Case status displays "Closed - Dismissed"

**Comment by cholly75** [comment]
@ttlenard - 9/10/11 are confirmed, adding to AC

**Comment by rachelschneiderman** [comment]
This story requires a migration (`0004-remove-closedDate-for-open-cases.js`).

**Comment by swongCO** [comment]
During UX review, it was discovered that for petitioners/practitioners, there is no indication that a case is closed, other than it is displayed in the Closed Cases tab. There is no case status in the case info tab nor next to the docket number (as a tag). A scenario that can happen is if a petitioner bookmarks their case, they won't know by looking that the case is closed unless they go to My Cases>Closed Cases. Would this be a consideration for a future story to add some sort of case status indication for external users?

@cholly75 @ttlenard 
cc @liadmccabe

**Comment by cholly75** [comment]
@rosiehsmith @rachelschneiderman - Looks like both "Closed" and "Closed - Dismissed" are now appearing in the Case Status dropdown list on the Case Inventory Report screen:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/e62e4421-d78e-4d90-8f83-902c3d7a0350)

Interestingly, the "Closed - Dismissed" selection works when running the report, but "Closed" does not. Neither are currently selectable options in PROD.
