### ISSUE TITLE
Session Copy Update: Add Trial Session Assignment Info to Session Copy

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8298]
As a trial clerk, judge, or CA, so that I have personnel information at hand when reviewing a Session Copy, I need to display Assignment information on the screen and printable Session Copy views.

Currently to see the Assignments information for a Trial Session, a Session Copy viewer must navigate off the Session Copy page to the Trial Session view. Feedback indicates that this information would be useful when viewing the Session Copy, particularly in the case of the printable version. Therefore, we would like to add this information to the Session Copy page.

## Acceptance Criteria
* Session Copy screen and printable view includes the following Assignment information (currently seen only on the Trial Session page):
  - Judge w/ Chambers phone
  - Trial Clerk
  - Court Reporter
  - IRS Calendar Administrator
* Assignment info on Session Copy should be derived from the values present on the Trial Session
* If no value for a field is present on the trial session, display "Not Assigned" as the value for the field on the Session Copy

## Notes
* Assignment information (as displayed on Trial Session screen):![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/20e78f81-863e-40d6-a783-9f4ca65e0f9b)

## Tasks

- [x] Add Assignments Card to the Session Copy Page - Tim & Mrin (https://github.com/flexion/ef-cms/pull/9716)
  - [x] Extract Assignments Card to own component
  - [x] Use extracted Assignments Card Component in both jsx 
  - [x] Ensure "If no value for a field is present on the trial session, display "Not Assigned" as the value for the field on the Session Copy " 
- [x] Add Assignments Card to the Printable Session Copy Page (https://github.com/flexion/ef-cms/pull/9720)
  - [x] Update printable copy generator/interactors with new data - Tim & Mrin 
  - [x] Use extracted Assignments Card Component  - Tim & Mrin
  - [x] Ensure styling matches UX specs
  - [x] Update Printable Trial Session Working Copy pdf for image compare test.
## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [x]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX specs

1. Copy "Assignments" card content and behavior from Session Info page and place on Session Copy page
2. Move Session Notes card to the right of Assignments card

![Session Copy page.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/298e2529-8468-4fc2-b2a2-a6acb4110468)
——————————
With Session Notes:

![Session Copy page w notes.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/b89a1516-b5bb-4e78-9753-6d96633f6224)
——————————
Printable PDF:

1. Position the Assignments card first, below the title
2. Use same font styling and sizes of current pdf
3. Use same card styling and padding
4. Divide the card into two equal columns
5. Allow text to wrap when it exceeds the content area but contain it within the card
6. The height of the card will flex based on the content

![PDF.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/a7f3ece8-0e3f-4511-aae8-c8028152a300)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge opens the Session copy page for an upcoming trial session; Assignments information is displayed, and matches the information on the Session information page.

- Log in as a Judge
- Click on the link for an upcoming trial session from your dashboard
- Click on the link to view all session info
- Take note of the information on the assignments card
- Click on the view Session Copy link
- Review the Session Copy page

Expected Results:
- [ ] Assignments information that was on the Session information page is now displayed on the Session Copy page and includes:
     - [ ] Assigned Judge
     - [ ] Chambers Phone Number
     - [ ] Trial Clerk
     - [ ] Court Reporter
     - [ ] IRS Calendar Administrator 
- [ ] If no value for a field is present, display "not assigned" as it currently does on the session info page.
- [ ] Session notes card is displayed to the right of assignments card

* Repeat this test with a Trial Clerk and a CA


#### 2) Judge prints the session copy page; Assignments section is added to the printable session copy page.

- Continuing from the previous test
- Click on the print link to print the session copy page
- Review the printed copy

Expected Results:
- [ ] The Assignments information is not displayed and includes
     - [ ] Assigned Judge
     - [ ] Chambers Phone Number
     - [ ] Trial Clerk
     - [ ] Court Reporter
     - [ ] IRS Calendar Administrator 
- [ ] If no value for a field is present, display "not assigned" as it currently does on the session info page.
- [ ] Session notes are displayed below the assignments

*Repeat this test with a Trial Clerk and a CA.

**Comment by cholly75** [comment]
Tested out great on EXP4 - @ttlenard please take a quick look on TEST next week
