### ISSUE TITLE
BUG: Duplicate work items found in the Document QC Inbox/Processed tabs

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8302]
**Describe the Bug**
**Part 1** 
We have had 5 reports since August 10th from Docket Clerks indicating that there are duplicate work items found in their Document QC inbox.  They had QC'd a document, and then saw that the item was still present in their inbox. When they clicked on the QC item, that remained in their inbox, they are brought to a white screen.  Since it had already been QC'd, nothing was happening for them.  When investigating this, we could not determine the cause, so we ended up doing a manual deletion of the duplicative work item in Dynamo.

**Part 2**
While testing ustaxcourt/ef-cms#8263, we found that when filtering on the Processed tab, there were duplicative work items here as well. This caused a react bug, and the duplicative work items were not filtering. This is how we noticed this!
(Tom can explain this part much better)

Somehow - there are duplicative work items getting generated - not sure if this is happening when they come in, or after they are processed?  Not sure if the reports of the duplicative work items in the inbox is related to the duplicative work items found in the processed???

If needed, we can go take a look at the Zendesk tickets reported by the docket clerks. For reference, the tickets are: 16543, 16724, 17769, 17979, 18393.  Interesting tidbit about these: All of these documents that were duplicative in the inbox were Notice of Change of Email address. This seems to be different than the duplicative work items in the Processed tab.  

This bug blocks the deployment of ustaxcourt/ef-cms#8263.

**Business Impact/Reason for Severity**
Medium

**In which environment did you see this bug?**
Production, Test

**Who were you logged in as?**
Docket Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)** 
Using the Application, Testing other functionality

**To Reproduce**
1. Log in as a Docket clerk
2. Click on the Document QC tab
3. Click on the Section Document QC link
4. Click on the Processed tab
5. Filter by different docket clerks a number of times, and then the bug will become apparent
6. You will see different docket clerks appear in your filtered list (see screen capture below)

**Expected Behavior**
There should not be any duplicative work items

**Actual Behavior**
A clear and concise description of what actually happened.
Somehow - there are duplicative work items getting generated - not sure if this is happening when they come in, or after they are processed?  Not sure if the reports of the duplicative work items in the inbox is related to the duplicative work items in the processed???

**Screenshots**
I am filtering by testdocketclerk6 here, but notice all the other QC items that appear for the other docket clerks. These are the duplicative work items.
![image](https://user-images.githubusercontent.com/87717140/197794346-d0a7cab0-377e-431c-b236-b211878c72ee.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by TomElliottFlexion** [comment]
Duplicative `OutboxItems` seem to have been caused by duplicate POSTs completing the same `WorkItem`- whether or not this `WorkItem` was duplicated to begin with is unclear. The `WorkItem` is sometimes completed by twice by different clerks, up to half an hour apart.
![Screen Shot 2022-10-25 at 9.54.24 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/bd4be38a-930e-44b7-9c9c-b9233f3c1c40)![Screen Shot 2022-10-25 at 9.54.53 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/0c873032-9b3e-4c79-8cde-88122095d642)![Screen Shot 2022-10-25 at 9.55.42 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/e21f8d1d-d77e-4530-8254-f390d4f92fbe)![Screen Shot 2022-10-25 at 9.57.01 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/f9ca7d48-9ec6-4d66-807d-506aa5c8cfc2)![Screen Shot 2022-10-25 at 9.57.26 AM.png](https://images.zenhubusercontent.com/601ac936c7e347e64fed075e/854e9ecb-5c67-4d0f-b9a2-71f7031fbf0c)

**Comment by jimlerza** [comment]
There are a couple of different ways to replicate the data issue we're seeing:

**Method 1: 2 docket clerks**

Begin state: Docket clerks 1 & 2 both load the Section Document QC Inbox
1. Docket clerk 1 clicks an unassigned document and completes it, populating Additional info 1 and selecting Add to cover sheet
2. Docket clerk 2 clicks the same document and also completes it, populating different data in Additional info 1 and selecting Add to cover sheet

End state: The document has 2 cover sheets and there are 2 records with `pk: section-outbox|docket` for that `workItemId`

**Method 2: 1 docket clerk**

Begin state: Docket clerk 1 loads the Section Document QC Inbox
1. Docket clerk 1 opens a document in a new tab
2. Docket clerk 1 opens the same document in their first tab and completes it, populating Additional info 1 and selecting Add to cover sheet, then closes the tab
3. Docket clerk 1 completes the same document again, populating the same data in Additional info 1 and selecting Add to cover sheet

End state: The document has 2 cover sheets and there are 2 records with `pk: section-outbox|docket` for that `workItemId`

**Comment by jimlerza** [comment]
Case **17850-21** is an example of method 1:

pk: `case|17850-21` sk: `work-item|2d67c6e7-90fa-4805-a3a1-9f7571e6ada6`
pk: `section-outbox|docket` sk: `2022-10-20T20:06:37.278Z`
pk: `section-outbox|docket` sk: `2022-10-20T20:06:17.598Z`

Case **9467-22** is an example of method 2:

pk: `case|9467-22` sk: `work-item|644218c0-c35a-4224-940d-895ea78eca2f`
pk: `section-outbox|docket` sk: `2022-10-19T12:05:31.500Z`
pk: `section-outbox|docket` sk: `2022-10-19T12:04:41.946Z`

**Comment by codyseibert** [comment]
discussed with UX and decided the best approach forward is to display a non-dismissible modal to allow the user to refresh their data and warn them that the work item was already completed. We need this modal to display on the following pages

- QC Inbox when clicking the document link
- Case Detail - Document View - Complete QC button
- show modal on Qc complete page on load if the work item has already been completed (on confirm navigate back to the docket record view of the case)
- Edit / QC Complete docket entry page (show modal when they try to complete or complete & send message) (navigate the user back to previous page on closing the modal)  (on confirm navigate back to the docket record view of the case)

**Comment by swongCO** [comment]
Got feedback about the messaging in the modal:
title - Document Has Already Been Handled
body - Click the button to refresh the data and navigate to your previous page or workflow.
btn - Close and Refresh

**Comment by swongCO** [comment]
### UX feedback
When the user clicks on a duplicate document in the QC inbox and the modal is displayed on the add document page, the user should be returned to the QC inbox and not the Docket Record after closing the modal. For the other instances where the user starts from the Document View, it's fine to return them to the Docket Record.

**Comment by ttlenard** [comment]
Testing feedback 11/7/2022

The new pop-up modal looks great.  I think that in most scenarios, this will work out great.  I'm going to call this bug good to go for now, with some caveats explained below.

While testing this bug, I did find two scenarios that could potentially occur, and I decided to split them into a separate bug.  1) duplicate work items can still be created, and 2) a clerk will get a 400 error during QC.  

See bug ustaxcourt/ef-cms#8355.

I did chat briefly with @jasonfu9966 and @codyseibert about ustaxcourt/ef-cms#8355, and they thought that it could be difficult to handle these scenarios, and would need to investigate further.

CC: @cholly75 @mmarcotte @jimlerza
