### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8316]
As a petitions clerk, so that I can provide pro se petitioners whose requested place of trial is Los Angeles, CA with tax clinic documentation, I need to be able to send out clinic letters with the Notice of Receipt of Petition.

For pro se petitioners who may not be able to afford or locate counsel to guide them through their case, there are tax clinics available as a resource who often advise and/or represent lower income petitioners. These clinics provide the Court with letters for petitioners indicating the details on how to use these resources, and as part of the Court's commitment to taxpayer equity prior to DAWSON we sent these letters to pro se petitioners along with official Court notices at various points in the life of the case.

These letters are not official Court or IRS documentation, but we provide them as a courtesy. There are one or more letters for each place of trial where the Court conducts business. It is possible for a location to have no clinic letter associated with it.

We would like to re-establish the process of generating and sending out these letters at the same time we send the Notice of Receipt of Petition by appending them to said Notices at the time the Notices are generated.

The letters themselves are provided in toto by the clinics to the Court; no customization is needed to the letter text itself, and these are not docketed separately as entries on the official record.

This story is specifically to address this for petitioners whose requested place of trial is Los Angeles. The clinic letter itself is attached to this story.

## Acceptance Criteria
* When a Notice of Receipt of Petition is generated for any case where the Petitioner is unrepresented by counsel and the requested place of trial is Los Angeles, CA, the clinic letter is appended to the Notice after the final page of the Notice.
* The appended clinic letter displays along with the Notice in its entirety when viewed in DAWSON via the Print Confirmation link on the Case Information/Overview panel.
* When the clinic letter for Los Angeles, CA is replaced with a new version, all Notices of Receipt of Petition generated after that use the new version of that letter.
* When the clinic letter for Los Angeles, CA is replaced with a new version, no previously generated Notices of Receipt of Petition are updated with the new version
* When the clinic letter for Los Angeles, CA is removed but not replaced, Notices of Receipt of Petition do not append anything
* Court personnel can upload a new version of the clinic letter
* Court personnel can replace existing clinic letter with new version
* Court personnel can remove existing clinic letter in its entirety
* Court personnel can view clinic letter content without having to view a Notice of Receipt of Petition
* Clinic letters are accessible to DAWSON to incorporate/append to documentation

## Notes

[https://app.zenhub.com/files/152320868/64f7fbc1-27c6-4e50-ae35-21f622e5d43a/download](https://app.zenhub.com/files/152320868/64f7fbc1-27c6-4e50-ae35-21f622e5d43a/download)
Can the documents be in a public repository? - Not at this time.

## Tasks
- [x] uploads this letter to documents bucket
- [x] modify receipt of petition code to fetch document using trial location from bucket and append to file
- 

## Test Cases
* Court uploads new clinic letter, categorizes letter based on location.
* Court replaces existing clinic letter, categorizes letter based on location; views letter, updated content is displayed.
* Court removes existing clinic letter; letter is no longer available in the system. 
* Pro se petition is served with a requested place of trial for Los Angeles, CA; notice of receipt of petition is generated; notice document has appropriate clinic letter appended as final pages of document
* Pro se petition is served with a requested place of trial for Los Angeles, CA but no clinic letter exists for that location; notice of receipt of petition is generated; notice document has no clinic letter appended
* Represented petition is served with requested place of trial for Los Angeles, CA; notice of receipt of petition is generated; notice document has no clinic letter appended
* Clinic letter for location is updated in repository; new pro se petition is served with requested place of trial for Los Angeles, CA; notice of receipt of petition is generated with updated clinic letter appended as final pages of document; previously generated notices of receipt of petition remain unchanged
* Notice of Receipt of Petition is generated w/ clinic letter appended; Notice is viewed via Print Confirmation link on Case Information/Overview panel; Notice displays in its entirety along with clinic letter

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
### **Test Cases**

**1. Court uploads new clinic letter, categorizes letter (Los Angeles, CA) based on location.**

* Sign in to your AWS account
* Select the appropriate account (Staging for this test)
* Click on Management Console
* Open S3
* In the Buckets search area, type in "Documents"
* Click on the link for **mig.ef-cms.ustaxcourt.gov-documents-mig-us-east-1** or **test.ef-cms.ustaxcourt.gov-documents-test-us-east-1** depending on what environment you are testing this with.
* Click on the upload button
* Drag and Drop or click add files to add the clinic letter
     * The clinic letter title should be in the following format "clinic-letter-los-angeles-california-regular"
* Select the document you would like to upload from your files
* Click Open
* Click Upload

Expected Results

- [x] You should have received the "Upload Succeeded" message


**2. Court replaces existing clinic letter, categorizes letter based on location (Los Angeles, CA); views letter, updated content is displayed.**

* Sign in to your AWS account
* Select the appropriate account (Staging for this test)
* Click on Management Console
* Open S3
* In the Buckets search area, type in "Documents"
* Click on the link for **mig.ef-cms.ustaxcourt.gov-documents-mig-us-east-1** or **test.ef-cms.ustaxcourt.gov-documents-test-us-east-1** depending on what environment you are testing this with.
* Click on the upload button
* Drag and Drop or click add files to add the clinic letter
     * The **Updated** clinic letter title should be in the following format "clinic-letter-los-angeles-california-regular"
* Select the document you would like to upload from your files
* Click Open
* Click Upload

Expected Results

- [x] You should have received the "Upload Succeeded" message
- [x] When you click on the document link, and then click on Open, you should see the updated letter


**3. Court removes existing clinic letter; letter is no longer available in the system.**

* Sign in to your AWS account
* Select the appropriate account (Staging for this test)
* Click on Management Console
* Open S3
* In the Buckets search area, type in "Documents"
* Click on the link for **mig.ef-cms.ustaxcourt.gov-documents-mig-us-east-1** or or **test.ef-cms.ustaxcourt.gov-documents-test-us-east-1** depending on what environment you are testing this with.
* Type in the name (or you can just type "clinic-letter") of the document you wish to remove
     * The clinic letter title you are searching for should be "clinic-letter-los-angeles-california-regular"
* Check the box on the left hand side next to the document title
* Click on Delete
* Type in Delete to confirm deletion
* Click on "Delete Objects"

Expected Results

- [x] You should have received the "Successfully deleted objects" message

**4. Electronic Pro se petition is served with a requested place of trial for Los Angeles, CA; notice of receipt of petition is generated; notice document has appropriate clinic letter appended as final pages of document**

* Ensure that a Clinic Letter is available for Los Angeles, CA in the repository
* Log in as Petitioner
* Click on Create Case
* Fill out the necessary fields and upload documents for the petition
* Ensure that you select Los Angeles, CA as the requested place of Trial
* Submit the Petition
* On the confirmation screen, take note of the docket number of the Petition. You will need to remember this docket number!
* Log out as Petitioner

* Log in as Petitions Clerk
* Click on Document QC
* Click on "Switch to Section Document QC"
* Find the electronic Petition that you just submitted in the steps above (it is probably at the end of the list!)
* Click on the Petition link
* Click on Case Info and ensure that Los Angeles, CA is showing in the Trial Location area 
* Click on the IRS Notice tab, and then click "No" for the question "IRS Notice Provided"
* Click on the "Review Petition" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"
* You should receive the green confirmation banner.
* Click on the Served tab
* Find the Petition that you just served from the list
* Click on the Docket No. Link
* Click on the Case information tab
* Click on the "Print Confirmation" link in the Case Details card

Expected Results
- [x] The PDF viewer will appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, the Los Angeles, CA Clinic letter will be appended to the end of the Notice of Receipt of Petition


**5. Paper Pro se petition is served with a requested place of trial for Los Angeles, CA; notice of receipt of petition is generated and is available for the petitions clerk for printing; notice document has appropriate clinic letter appended as final pages of document**

* Ensure that a Clinic Letter is available for Los Angeles, CA in the repository
* Log in as Petitions Clerk
* Click on "Start a Petition"
* Fill in all required information and upload/scan documents for a paper filed petition
* Click on Case Info and ensure that you select Los Angeles, CA as the Trial Location
* Click on the "Create Case" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"

Expected Results
- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, the Los Angeles, CA Clinic letter will be appended to the end of the Notice of Receipt of Petition

**6. Electronic Pro se petition is served with a requested place of trial for Los Angeles, CA but no clinic letter exists for that location; notice of receipt of petition is generated; notice document has no clinic letter appended**

* Ensure that there is NOT a Clinic Letter available for Los Angeles, CA in the repository
* Log in as Petitioner
* Click on Create Case
* Fill out the necessary fields and upload documents for the petition
* Ensue that you select Los Angeles, CA as the requested place of Trial
* Submit the Petition
* On the confirmation screen, take note of the docket number of the Petition. You will need to remember this docket number!
* Log out as Petitioner

* Log in as Petitions Clerk
* Click on Document QC
* Click on "Switch to Section Document QC"
* Find the electronic Petition that you just submitted in the steps above (it is probably at the end of the list!)
* Click on the Petition link
* Click on Case Info and ensure that Los Angeles, CA is showing in the Trial Location area 
* Click on the IRS Notice tab, and then click "No" for the question "IRS Notice Provided"
* Click on the "Review Petition" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"
* You should receive the green confirmation banner.
* Click on the Served tab
* Find the Petition that you just served from the list
* Click on the Docket No. Link
* Click on the Case information tab
* Click on the "Print Confirmation" link in the Case Details card

Expected Results
- [x] The PDF viewer will appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, there should NOT be a Los Angeles, CA Clinic letter appended to the end of the Notice of Receipt of Petition


**7. Paper Pro se petition is served with a requested place of trial for Los Angeles, CA but no clinic letter exists for that location; notice of receipt of petition is generated and is available for the petitions clerk for printing; notice document has no clinic letter appended**

* Ensure that there is NOT a Clinic Letter available for Los Angeles, CA in the repository
* Log in as Petitions Clerk
* Click on "Start a Petition"
* Fill in all required information and upload/scan documents for a paper filed petition
* Click on Case Info and ensure that you select Los Angeles, CA as the Trial Location
* Click on the "Create Case" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"

Expected Results
- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, there should NOT be a Los Angeles, CA Clinic letter appended to the end of the Notice of Receipt of Petition



**8. Represented petition is served with requested place of trial for Los Angeles, CA; notice of receipt of petition is generated; notice document has no clinic letter appended**

* Ensure that there is a Clinic Letter available for Los Angeles, CA in the repository
* Log in as Practitioner
* Click on Create Case
* Fill out the necessary fields and upload documents for the petition
* Ensue that you select Los Angeles, CA as the requested place of Trial
* Submit the Petition
* On the confirmation screen, take note of the docket number of the Petition. You will need to remember this docket number!
* Log out as Practitioner

* Log in as Petitions Clerk
* Click on Document QC
* Click on "Switch to Section Document QC"
* Find the electronic Petition that you just submitted in the steps above (it is probably at the end of the list!)
* Click on the Petition link
* Click on Case Info and ensure that Los Angeles, CA is showing in the Trial Location area 
* Click on the IRS Notice tab, and then click "No" for the question "IRS Notice Provided"
* Click on the "Review Petition" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"
* You should receive the green confirmation banner.
* Click on the Served tab
* Find the Petition that you just served from the list
* Click on the Docket No. Link
* Click on the Case information tab
* Click on the "Print Confirmation" link in the Case Details card

Expected Results
- [x] The PDF viewer will appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, there should NOT be a Los Angeles, CA Clinic letter appended to the end of the Notice of Receipt of Petition



**9. Clinic letter for location is updated in repository; new electronic pro se petition is served with requested place of trial for Los Angeles, CA; notice of receipt of petition is generated with updated clinic letter appended as final pages of document; previously generated notices of receipt of petition remain unchanged**

* As a court user, perform test case 2 above to replace the existing Los Angeles, CA clinic letter with a new one.
* Log in as Petitioner
* Click on Create Case
* Fill out the necessary fields and upload documents for the petition
* Ensue that you select Los Angeles, CA as the requested place of Trial
* Submit the Petition
* On the confirmation screen, take note of the docket number of the Petition. You will need to remember this docket number!
* Log out as Petitioner

* Log in as Petitions Clerk
* Click on Document QC
* Click on "Switch to Section Document QC"
* Find the electronic Petition that you just submitted in the steps above (it is probably at the end of the list!)
* Click on the Petition link
* Click on Case Info and ensure that Los Angeles, CA is showing in the Trial Location area 
* Click on the IRS Notice tab, and then click "No" for the question "IRS Notice Provided"
* Click on the "Review Petition" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"
* You should receive the green confirmation banner.
* Click on the Served tab
* Find the Petition that you just served from the list
* Click on the Docket No. Link
* Click on the Case information tab
* Click on the "Print Confirmation" link in the Case Details card

Expected Results
- [x] The PDF viewer will appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, the updated Los Angeles, CA Clinic letter will be appended to the end of the Notice of Receipt of Petition
- [x] The old version of the Los Angeles, CA Clinic letter is NOT appended to the end of the Notice of Receipt of Petition


**10. Clinic letter for location is updated in repository; new paper pro se petition is served with requested place of trial for Los Angeles, CA; notice of receipt of petition is generated with updated clinic letter appended as final pages of document; previously generated notices of receipt of petition remain unchanged**

* As a court user, perform test case 2 above to replace the existing Los Angeles, CA clinic letter with a new one.
* Log in as Petitions Clerk
* Click on "Start a Petition"
* Fill in all required information and upload/scan documents for a paper filed petition
* Click on Case Info and ensure that you select Los Angeles, CA as the Trial Location
* Click on the "Create Case" button on the bottom of the screen
* Click "Serve to IRS"
* Click "Yes Serve"

Expected Results
- [x] The Print Paper Petition Receipt screen should appear with the Notice of Receipt of Petition document. 
- [x] If you scroll down, the updated Los Angeles, CA Clinic letter will be appended to the end of the Notice of Receipt of Petition
- [x] The old version of the Los Angeles, CA Clinic letter is NOT appended to the end of the Notice of Receipt of Petition

**Comment by cholly75** [comment]
Updated story and file to change location to Los Angeles instead of San Francisco.

**Comment by TomElliottFlexion** [comment]
Format for s3 keys of clinic letters: `clinic-letter-los-angeles-california-regular` (`clinic-letter-<city>-<state>-<procedureType>`)
