### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8337]
As a court user, so that information does not get incorrectly assigned, I need DAWSON to reflect that Judge Guy has retired.

Judge Guy has retired from the USTC effective 3/31/22. There are several places in the application that need to be updated to reflect this, so that new case information does not get incorrectly assigned or potentially ignored. We need to remove the ability to assign data to Judge Guy or his Chambers, while preserving data already associated with same.

## Acceptance Criteria
* Remove Judge Guy from the Judge dropdown menu on the Session Assignments section of the Create Trial Session screen
* Remove Judge Guy from the Judge dropdown menu on the Session Assignments section of the Edit Trial Session screen
* Remove "Guy's Chambers" from the Select Chambers dropdown menu on the Create Message screen (appears after selecting "Chambers" on the Select a Section dropdown)
* Remove "Guy" from the Select Judge dropdown menu on the Run Case Inventory Report screen
* Remove "Guy" from the Filter By menu on the Deadlines report screen
* Remove "Guy" from the Show Items For dropdown menu on the Pending Report screen
* Remove "Guy" from the Judge's Name dropdown menu that appears when adding a Decision, Stipulated Decision, Order and Decision, and Order of Dismissal and Decision as a docket entry
* Judge Guy SHOULD still be selectable on all advanced search screen dropdowns for filtering by Judge
* Do not remove Judge Guy's name from any data currently associated with him

## Tasks
- [x] Update judge_users.csv so Guy's roles and section are legacy - Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Remove Guy from persistence method `getJudgesChambers` - Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Add integration test - Mrinalini, Rachel, Rosie https://github.com/ustaxcourt/ef-cms/pull/2083
- [x] Add script to be run for `test`, `mig`, and `prod` to update Guy's role and section - Rosie, Mrinalini https://github.com/ustaxcourt/ef-cms/pull/2097
- [x] Run script vs. `exp2` then `test` to ensure it works as intended - Rosie, Mrinalini
- [x] Update smoketest - Rosie https://github.com/ustaxcourt/ef-cms/pull/2097

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 10-6-21)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Deployed to any Flexion environment for Engineering Review
 - [ ] Deployed to the Court's migration environment

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Offboarded Judge should not appear in any of the dropdown menus related to Trial Sessions

**Add New Trial Session**
- Log in as a petitions Clerk
- Click on Trial Sessions
- Click on Add trial session
- Scroll down to the Judge area and click on the Judge Dropdown
Expected Results
- [ ] Judge Guy is not on the list of Judges to select from

**Edit Trial Session**
- Next, cancel out of the Add Trial Session screen and click on the Open tab
- Click on the City, State URL of a trial session that is in the future
- Click on the Edit button next to the session information area
- Scroll down to the Judge area and click on the Judge dropdown

Expected Results
- [ ] Judge Guy is not on the list of Judges to select from

#### 2) Offboarded Judge and Chambers should not appear in any of the dropdowns on the create message screen.
- Log in as any court user
- Go to a case
- Click on the Create menu and then select Message
- Click the dropdown for "Select a Section" and select Chambers

Expected Results
- [ ] Guy's Chambers is no longer in the list of Chambers

#### 3) Offboarded Judge should not appear in dropdown menu's for the Reports

**Case Inventory Report**
- Log in as any court user
- Click on the Reports menu and select Case Inventory
- Click on the "Select Judge" Menu

Expected Results
- [ ] Judge Guy is not on the list of Judges to select from

**Deadlines Report**
- Click on the Reports menu and select Deadlines
- Click on the Judge Dropdown next to Filter By

Expected Results
- [ ] Judge Guy is not on the list of Judges to select from

**Pending Report**
- Click on the reports menu and select Pending Report
- Click on the Judge Dropdown

Expected Results
- [ ] Judge Guy is not on the list of Judges to select from


#### 4) Offboarded Judge should not appear in any of the Judge dropdown menus that appear when adding a Decision, Stipulated Decision and Order of Dismissal and Decision as a docket entry.

**Decision**
- Log in as a Docket Clerk 1
- Navigate to a case that is not closed
- Click on Create Menu
- Click on PDF Upload
- Upload a document, add in a description, and click save
- Apply a signature to the document
- Add Docket Entry
- Select Decision as the document type
- Click on the Judge's Name Dropdown

Expected Results:
- [ ] Judge Guy is not on the list of Judges to select from

**These other Document types**
- Continuing on from the previous test, click on Document type and select the following Document Types. Each of these document types will have a Judge's Name appear for selection:
     - Stipulated Decision
     - Order of Dismissal
     - Order of Dismissal and Decision
     - Order of Dismissal for Lack of Jurisdiction
  
Expected Results:
- [ ] Judge Guy is not on the list of Judges to select from


#### 5) Offboarded Judge should still be selectable on all advanced search screen dropdowns for filtering by Judge
**Order Search**
- As a public non logged in user, go to the DAWSON home page (the search page)
- Click on Order Search
- Click on the Judge Dropdown
Expected Results
- [ ] Judge Guy remains on the list of Judges to select from

**Opinion Search**
- As a public non logged in user, go to the DAWSON home page (the search page)
- Click on Opinion Search
- Click on the Judge Dropdown
Expected Results
- [ ] Judge Guy remains on the list of Judges to select from

#### 6) Regression Test - Judge Guy's name and Chambers info remains on data associated with him
Expected Results
- [ ] Messages remain associated with Judge Guy and his chambers (I checked case 22612-21 to be sure that Guy and his chambers had messages)
- [ ] Signed Orders retain signature of Judge Guy
- [ ] Opinions retain association with Judge Guy

**Comment by rosiehsmith** [comment]
Since `test`, `migration`, and `prod` environments do not get the script `bulk-import-judge-users.sh` run on deploy, we created a script to be run to update the offboarded judge users's role and section.

This script to be manually run on these environments is called `scripts/dynamo/offboard-judge-user.sh` and requires passing in the userId of the judge to offboard. Happy to assist in grabbing this if needed!

**Comment by ttlenard** [comment]
Tests all pass! Thanks all!
