### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8350]
As a DAWSON user, so that I can manage my messages in a timely manner, I need to be able to see the place of trial and date of trial for messages related to a case whose status is Calendared.

Currently, when we display messages related to a case that is calendared for a trial session we reflect that in the Case Status column of the message views (Inbox, Sent) with the status of Calendared. User feedback is that it would be valuable to know both the place and date of the trial session itself so the user can address these messages appropriately.

## Acceptance Criteria
* When displaying a message in the Inbox view for Section messages, if the case status displayed is Calendared, display the place of trial and date of trial for the session for which the case related to the message is assigned.
* When displaying a message in the Inbox view for My messages, if the case status displayed is Calendared, display the place of trial and date of trial for the session for which the case related to the message is assigned.
* When displaying a message in the Sent view for Section messages, if the case status displayed is Calendared, display the place of trial and date of trial for the session for which the case related to the message is assigned.
* When displaying a message in the Sent view for My messages, if the case status displayed is Calendared, display the place of trial and date of trial for the session for which the case related to the message is assigned.

## Tasks

- [x] Retrieve Place and Date of Trial Session - https://github.com/ustaxcourt/ef-cms/pull/2894
- [x] Display Place and Date of Trial Session - https://github.com/ustaxcourt/ef-cms/pull/2894
  - [x] Display in Inbox for Section and My messages
  - [x] Display in Sent for Section and My messages
- [x] Message Result VALIDATION_RULES - https://github.com/ustaxcourt/ef-cms/pull/2894

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX Specs
Display date and place of trial in the Case Status column:
1. add " - " after Calendared
2. use date format mm/dd/yy
3. abbreviate state
4. allow the column width to expand to fit city (state can wrap to next line)
![Screen Shot 2022-11-16 at 1.33.54 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/6fc5006d-92ff-4fd5-a62f-f95085cd6813)

**Comment by ttlenard** [comment]
## Test Cases

**Preconditions**
- These tests will require some set up, since you will need to ensure that your logged in user that you are testing with has messages in their inbox view and their sent view.
- To set this up, be sure that you send your test user(s) some messages, and also have multiple messages sent
- Be sure that the cases that you are sending messages from are in various case status', including Calendared.


#### 1) Court User navigates to My Messages Inbox view; Messages related to cases that have a case status as Calendared also display the date and place of trial.

- Log in as a court user 
- The My messages Inbox view should be your homepage upon login (If you logged in as a Judge or CA, click on Messages tab)
- Review the My Messages Inbox view

Expected Results:
- [x] **NEW FUNCTIONALITY** - Messages related to cases that have a status of Calendared will now also include the date and place of trial as per the design provided above.
- [x] Messages related to cases that are in a different status than Calendared, only display the case status.

Be sure to repeat this test with all Court user roles!


#### 2) Court user navigates to My Messages Sent view; Messages related to cases that have a case status as Calendared also display the date and place of trial.

- Continuing from the previous test
- Click on the My Messages Sent view
- Review the My Messages Sent View

Expected Results:
- [x] **NEW FUNCTIONALITY** - Messages related to cases that have a status of Calendared will now also include the date and place of trial as per the design provided above.
- [x] Messages related to cases that are in a different status than Calendared, only display the case status.

Be sure to repeat this test with all Court user roles!


#### 3) Court User navigates to the Section Messages Inbox view; Messages related to cases that have a case status as Calendared also display the date and place of trial.

- Log in as a Court User
- The My messages Inbox view should be your homepage upon login (If you logged in as a Judge or CA, click on Messages tab)
- Click on the Switch to Section Messages link
- Review the Section Messages Inbox View

Expected Results:
- [x] **NEW FUNCTIONALITY** - Messages related to cases that have a status of Calendared will now also include the date and place of trial as per the design provided above.
- [x] Messages related to cases that are in a different status than Calendared, only display the case status.

Be sure to repeat this test with all Court user roles!

#### 4) Court User navigates to the Section Messages Sent view; Messages related to cases that have a case status as Calendared also display the date and place of trial.

- Continuing from the previous test
- Click on the Section Messages Sent View
- Review the Section Messages Sent View

Expected Results:
- [x] **NEW FUNCTIONALITY** - Messages related to cases that have a status of Calendared will now also include the date and place of trial as per the design provided above.
- [x] Messages related to cases that are in a different status than Calendared, only display the case status.

Be sure to repeat this test with all Court user roles!

**Comment by swongCO** [comment]
@cholly75 I discovered that there is another instance of Messages that includes Case Status columns. If logged in as a judge/CA, there is a Recent Messages section under Dashboard that displays items from Messages. Would this story include this section, since it's pulling from Messages?

@shumway-tm @rachelschneiderman Can you confirm if Recent Messages displays the same data from Messages?

cc @liadmccabe 

UPDATE: A decision was made per this slack thread: https://ustaxcourt.slack.com/archives/C03AJPN0TLZ/p1668796873774859
However, if in development, the change made in Messages is applied to Recent Messages automatically, Chris will reassess. Otherwise, 9742 in the backlog will address it.

**Comment by mrinsin** [comment]
@swongCO the changes made in this story wont show up in the Recent Messages view as it is a separate JSX file and we have not added the new code to it. 9742 it is! cc @cholly75

**Comment by ttlenard** [comment]
@mrinsin @shumway-tm @rachelschneiderman 

Testing Feedback 12/12/2022

If a user completes a message in a calendared case, and then attempts to view their outbox or the section outbox, they experience a white screen. This appears to be happening only with messages associated with Calendared cases. If the case isn't calendared, and a message is completed, viewing the outbox works fine.  I pulled up the console and found that it is because of an Uncaught TypeError.  Can you please take a look at this? Thanks!

Here is a screen grab of that TypeError:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/28e26893-3fb0-418d-9bd3-811ed70bf1c7)

**Comment by ttlenard** [comment]
Testing Feedback 12/13/2022 - no longer getting that TypeScript Error. Thanks for fixing!
