### ISSUE TITLE
Recent Messages: Update w/ Trial Session Info

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8371]
As a judge or chambers user, so that I can prioritize my recent messages, I need to be able to see the place of trial and date of trial for messages related to a case whose status is Calendared.

To make the Dashboard's Recent Messages section in line with changes to the main Messages display, we want to extend the functionality introduced in 9684 to the Recent Messages display on the Dashboard for judge and chambers users.

## Pre-Conditions
ustaxcourt/ef-cms#8350 

## Acceptance Criteria
* When displaying a message in the Recent Messages view on the Dashboard, if the case status displayed is Calendared, display the place of trial and date of trial for the session for which the case related to the message is assigned.

## Tasks
- [x] display trial info on recent messages view - https://github.com/ustaxcourt/ef-cms/pull/2917

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

**Preconditions**
- These tests will require some set up, since you will need to ensure that your logged in user that you are testing with has messages in their inbox view.
- To set this up, do the following:
     - Log in as a Court user (not a Judge or Chambers user)
     - Navigate to a case that is in a status besides calendared
     - Send a message to a Judge and Chambers user
     - Next, click on the Trial sessions tab
     - Navigate to a trial session that is assigned to the Judge user that you have a log in for
     - Select a case on the trial and then from within that case, send a message to the Judge/Chambers user
     - Repeat these steps a few times, so that you have at least 5 messages sent.
     

#### 1) Judge or Chambers user navigates to their Dashboard view; Cases with a status of Calendared also display the date and place of trial on the Recent Messages view.

- Log in as a Judge or Chambers user 
- Review the Recent Messages view

Expected Results:
- [x] **NEW FUNCTIONALITY** - Messages related to cases that have a status of Calendared will now also include the date and place of trial as per the design provided above.
- [x] Messages related to cases that are in a different status than Calendared, only display the case status.

Be sure to repeat this test with both a Judge and a Chambers user!

#### 2) Regression test to ensure the following:
- [x] Judge/Chambers user can interact with the messages as they normally could (reply, complete, forward messages)
- [x] If the case is removed from the calendared session, the case status updates appropriately on the Recent Messages view
- [x] If a case that was not previously calendared, but then get's added to a session, the status updates appropriately on the Recent Messages view
- [x] Click on the My messages views (Inbox, sent, complete) and ensure that the Case status appears as it should via this message view
- [x] Click on the Section messages views (Inbox, sent, complete) and ensure that the Case status appears as it should via this message view

**Comment by ttlenard** [comment]
@mrinsin Testing on this one looks great! Thanks!
