### ISSUE TITLE
New Role: Case Services Supervisor

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8377]
As a supervisor in Case Services, so that I can switch between departmental functions as needed, I need my role in DAWSON to encompass permissions for both Petitions and Docket clerks.

Case Services is reorganizing its staff to better meet the needs of the Court's volume of work and workflow processes. They have identified a need to make supervisor-level positions more fungible across departments, and to that end they would like to have a Case Services Supervisor role that will allow them to shift between petitions, calendar, and docket work as required. This will role will encompass all the permissions currently granted to petitions and docket clerks.

## Acceptance Criteria
* Users with the Case Services Supervisor role can perform any function that a docket clerk can
* Users with the Case Services Supervisor role can perform any function that a petitions clerk can
* Users with the Case Services Supervisor role can access the Section Messages views for either Docket or Petitions 
* Users with the Case Services Supervisor role can access the Section QC views for either Docket or Petitions

## Notes
* User does not need to access combined section displays across departments
* Permissions for both roles [here](https://docs.google.com/spreadsheets/d/1FVcFy5Mka9qEPYsIFjp1NvrRi-B8TZZRukLuXySO7tQ/edit?usp=sharing) in the Docket/Petitions sheet

## Tasks
- [x] Add new role to `authorizationClientService` that combines DocketClerk and PetitionsClerk permissions - Mrinalini & Rosie https://github.com/flexion/ef-cms/pull/9792
- [x] Add some new test users with this role - Mrinalini & Rosie https://github.com/flexion/ef-cms/pull/9792
- [x] Update `headerHelper` which is used in `Header.jsx` to use permissions to determine how to display the Messages dropdown within the header - Mrinalini & Rosie https://github.com/flexion/ef-cms/pull/9793
- [x] Update `headerHelper` which is used in `Header.jsx` to use permissions to determine how to display the Document QC dropdown within the header - Mrinalini & Rosie https://github.com/flexion/ef-cms/pull/9793
- [x] Add path for new role in all sequences that call `runPathForUserRoleAction` - Mrinalini & Rosie https://github.com/flexion/ef-cms/pull/9795
- [x] Add new section in messages To Section dropdown - Mrinalini & Rosie
- [x] Populate the Messages page with selected information - Mrinalini & Rosie
  - [x] Display My Messages for CSS user  https://github.com/flexion/ef-cms/pull/9795
  - [x] Display Messages Count Icon (total of user inbox messages aka MY messages - so just use pre-existing flag/logic) https://github.com/flexion/ef-cms/pull/9795
  - [x] Display docket section inbox messages when clicking on Docket Messages link https://github.com/flexion/ef-cms/pull/9799
  - [x] Display docket section sent messages when clicking on Docket Messages link - Pair https://github.com/flexion/ef-cms/pull/9802
  - [x] Display docket section completed messages when clicking on Docket Messages link - pair https://github.com/flexion/ef-cms/pull/9802
  - [x]  Display petitions section inbox messages when clicking on Petitions Messages link https://github.com/flexion/ef-cms/pull/9799
  - [x] Display petitions section sent messages when clicking on Docket Messages link - pair https://github.com/flexion/ef-cms/pull/9802
  - [x] Display petitions section completed messages when clicking on Docket Messages link - pair https://github.com/flexion/ef-cms/pull/9802
  - [x] Remove "Switch to Section Messages" when on My Messages https://github.com/flexion/ef-cms/pull/9795
  - [x] Update `messagesTitle` for new role when viewing either section's Messages https://github.com/flexion/ef-cms/pull/9799
  - [x] When clicking a menu item on Messages, menu should no longer be expanded - pair https://github.com/flexion/ef-cms/pull/9802
  - [x] When clicking a menu item on Document QC, menu should no longer be expanded - pair https://github.com/flexion/ef-cms/pull/9802
- [x] Set primary section for CSS and create mapping records for docket and petitions section - mob https://github.com/flexion/ef-cms/pull/9808 
  - [x] Display formatted fromSection string in UI - mob https://github.com/flexion/ef-cms/pull/9808 
- [x] Populate the Document QC page with the selected section 
  - [x] Display My Document QC for CSS user - pair https://github.com/flexion/ef-cms/pull/9813
  - [x] Display docket section QC when clicking on Docket QC link - pair https://github.com/flexion/ef-cms/pull/9813
  - [x]  Display petitions section QC when clicking on Petitions QC link - pair https://github.com/flexion/ef-cms/pull/9813
  - [x] Remove "Switch to Section QC" when on Document QC  https://github.com/flexion/ef-cms/pull/9813
  - [x] Fix the count when selecting petitions or docket section for document QC  https://github.com/flexion/ef-cms/pull/9813
- [x] Fix the count when selecting petitions or docket section for messages - pair https://github.com/flexion/ef-cms/pull/9802
- [x] Update `workQueueTitle` for new role when viewing either section's Document QC https://github.com/flexion/ef-cms/pull/9813
- [x] Cleanup and refactoring - https://github.com/flexion/ef-cms/pull/9817
- [x] Address how existing users will get this role - Mike will post to `/users` endpoint
- [x] ~Possible refactoring: Combine jsx components for MessagesMenu and DocumentQCMenu and pass the titles, hrefs, sequence~ This ended up not being that readable because there had to be like 10 args passed in and names not too clear when genericized
- [x] ~DOD: in mobile view, the "my messages" part of the menu is aligned left, not right, like the rest of the menu items~ Since this is not for external users, not a priority.
- [x] Q: when you are on a docket/petitions section messages and click Inbox, should it just go back to that section's inbox? should be similar behavior to sent/completed tabs. right now, it's just going to the CCS's section rather than the selected section. Will need to update this.
- [x] DOD update docs https://github.com/flexion/ef-cms/pull/9825
- [x] DOD integration test https://github.com/flexion/ef-cms/pull/9826
- [x] Feedback: When the CSS assigns a work item in the Petitions or Docket QC section display, that item disappears completely from the display regardless of view or filtering. This behavior does not occur when the same operation is done by Petitions or Docket clerk roles.  https://github.com/ustaxcourt/ef-cms/pull/3085
- [x] Feedback: items processed by CSS (through section QC) are not showing on the Processed view for Section Document QC. https://github.com/ustaxcourt/ef-cms/pull/3085
- [x] Feedback cleanup & tests- https://github.com/flexion/ef-cms/pull/9830

## Story Definition of Ready (Created on 9/26/21)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Be immediately actionable for the development team
- [ ]  Be focused on users
- [ ]  Include a narrative. “As a ____, so that I can ______, I need _____.”
- [ ]  Include user-centric acceptance criteria that expresses the users' needs
- [ ]  Include user-centric testing scenarios
- [ ]  Include preconditions (story dependencies)
- [ ]  Not include design or technical solutions
- [ ]  Include non-standard testing, deployment, documentation, browser, mobile or security requirements, as well as any requirements for 3rd-party integrations

Process: Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
### UX Notes

- [ ] Add down arrows next to Messages and Document QC
- [ ] Add dropdown list to Messages and Document QC
- [ ] Use the same style for arrows and dropdown lists as in Reports
- [ ] Dropdown list for Messages - My Messages, Docket Section Messages, Petitions Section Messages
- [ ] Dropdown list for Document QC - My Document QC, Docket Section QC, Petitions Section QC
- [ ] Change page titles for each new view accordingly, to match the dropdown lists

Mockups for message and QC views:

![Docket messages - dropdown.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4b7790d1-9b8a-405c-b398-5c0a1f9daf08)

![Docket messages.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5c1195ec-f9cc-4faf-bdcb-0c2f6aca1b57)

![Petitions messages.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/5001143f-4eaf-4b46-b927-3be02e9e8075)

![Docket QC - dropdown.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d64507e2-e4af-42ba-b17d-582f0a13649b)

![Docket QC.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/96eff7a3-3590-45ae-a3be-897e6d3f40cf)

![Petitions QC.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/91abfacb-d0bc-4669-b24d-af746b7977ee)

**Comment by swongCO** [comment]
One thing I wanted to confirm - is it ok to omit "Document" in the page title from both section QC pages? I omitted because I believe that these court users understand that QC = Document QC so shortening the title makes it a bit easier to digest. It's also omitted in the dropdown menu. 
@cholly75 Thoughts?

**Comment by cholly75** [comment]
@swongCO - yep, that's fine.

**Comment by ttlenard** [comment]
## Test Cases

Preconditions: We will need to have some new test users set up for the Case Services Supervisor Role.

**Test Cases 1-8 are new functionality built in DAWSON for this story**

#### 1) Case Services Supervisor logs in; My Messages tab has a new dropdown menu available.

- Log in as a Case Services Supervisor
- Click on the new dropdown menu next to the messages menu option at the top of the screen.

Expected Results:
- [x] New dropdown has options for the user to navigate to My Messages, Petition Section Messages, or Docket Section Messages.


#### 2) Case Services Supervisor can change the view from My Messages to Petitions Section Messages; Petitions Section Messages views (Inbox, Sent, Completed) displays and functions appropriately.

- Continuing from the previous test
- Click on the Petitions Section Messages option

Expected Results
- [x] User can click on the message title of any of the messages in the inbox, sent, and completed tabs and it will navigate to the case message
- [x] User can interact with the message as they normally would (View the message(s), complete, forward, reply, create order - from the inbox/sent tab)
- [x] After clicking on a message from the complete tab, user can expand the messages to see the threads, and view any attachments.
- [x] Messages sent to the Case Services Supervisor, also appear in the appropriate Section Message (if they were selected in a message from the Petitions section, it would appear here)


#### 3) Case Services Supervisor can change the view from My Messages to Docket Section Messages; Docket Section Message views (Inbox, Sent, Completed) displays and functions appropriately.

- Continuing from the previous test
- Click on the Docket Section Messages option

Expected Results
- [x] User can click on the message title of any of the messages in the inbox, sent, and Completed tabs and it will navigate to the case message
- [x] User can interact with the message as they normally would (View the message(s), complete, forward, reply, create order)
- [x] After clicking on a message from the complete tab, user can expand the messages to see the threads, and view any attachments.
- [x] Messages sent to the Case Services Supervisor, also appear in the appropriate Section Message (if they were selected in a message from the Docket section, it would appear here)

#### 4) Case Services Supervisor can change the view from the Section Messages View (Petitions or Docket) to My Messages; My Messages view (inbox, sent, Completed) displays and functions appropriately.

Preconditions: For this test, you will need to be sure that you have some messages that have been sent to one of the new case services supervisors from both the Petitions section AND the Docket Section.  This will be part 1 of this test:

**Part 1** 

- Log in as a different Court User (not a Case Services Supervisor)
- Navigate to a case
- Click on the Create menu
- Select Message
- Click on the Select a Section dropdown
- Select Docket Section
- The new Case Services Supervisor(s) should be an available option in this recipient dropdown menu
- Select the Case Services Supervisor and send them a message.
- Be sure that in the message body, you indicate that this was sent from the Docket Section (you'll need this info later)

- Repeat the steps above, but instead of choosing Docket as the Section, choose Petitions.
- The new Case Services Supervisor(s) should be an available option in the Petitions recipient dropdown menu as well.
- Send them a message and be sure that in the message body, you indicate that this was sent from the Petitions Section (you'll need this info later)

- Send the Case Services Supervisor a few messages and be sure that you send a few from each Section following the steps above

**Part 2**

- Log in as the Case Services Supervisor
- Be sure that you are on the My Messages screen

Expected Results:
- [x] Messages sent to the case services supervisor appear correctly in the my messages page
- [x] User can interact with the message as they normally would (View the message(s), complete, forward, reply, create order). Be sure that you reply and complete a few messages.
- [x] After clicking on a message from the complete tab, user can expand the messages to see the threads, and view any attachments.

**Part 3**

- Click on the Petitions Section Messages

Expected Results
- [x] The messages that you sent to the Case Services Supervisor from the Petitions Section appear in this section inbox
- [ ] The messages that you replied to appear appropriately in the Sent
- [ ] The messages that you completed appear appropriately in the Completed box.

**Part 4**

- Click on the Docket Section Messages

Expected Results
- [x] The messages that you sent to the Case Services Supervisor from the Docket Section appear in this section inbox
- [ ] The messages that you replied to appear appropriately in the Sent
- [ ] The messages that you completed appear appropriately in the Completed box.



#### 5) Case Services Supervisor has a new dropdown menu available next to the Document QC Tab.

- Log in as a Case Services Supervisor
- Click on the new dropdown menu next to the Document QC menu option at the top of the screen.

Expected Results:
- [x] New dropdown has options for the user to navigate to My Document QC, Petition Section QC, or Docket Section QC.



#### 6) Case Services Supervisor can change the view for their My Document QC to Petitions Section Document QC; Petitions Section Document QC views (Inbox, In Progress, Processed) displays and functions appropriately.

- Continuing from the previous test
- Click on the Petitions Section QC option from the dropdown menu.

Expected Results:
- [x] Start a Petition button is available in the upper right-hand corner of the screen
- [x] User is able to check the box on left of each item in the table and assign it (Inbox and in Progress tabs)
- [x] The Case Services Supervisor's name is available in the dropdown picklist for the assign to box (assign a few items to them)
- [x] If the Petition work item is assigned to the Case Services Supervisor, it is then available in the Case Services Supervisors My Document QC inbox.
- [x] Clicking on the Petition link from the Petition Section Document QC inbox navigates user to the petition QC screen, where they can complete the QC and serve to the IRS.
     - [x] Orders/Notices that can be autogenerated are
     - [x] Deadlines should be auto-generated for certain Orders



#### 7) Case Services Supervisor can change the view for their My Document QC to Docket Section Document QC; Docket Section Document QC views (Inbox, In Progress, Processed) displays and functions appropriately.

- Continuing from the previous test
- Click on the Docket Section QC option from the dropdown menu.

Expected Results:
- [x] User can filter the list by assignment (all tabs)
- [x] User can Check individual boxes and once they do the Assign to box becomes active and the "pill" icon displays the number of selected items. (Inbox and In Progress tabs)
- [x] User can also check the top box in the header to select all (Inbox and In Progress tabs)
- [x] If an Assign to is selected, the item is assigned appropriately.
- [x] The Case Services Supervisor(s) are available in the dropdown menu in the Assign to box (assign a few items to them)
- [x] If work item is assigned to the case services supervisor, the work item appears correctly in their My Document QC page.
- [x] From the Section Document QC page, if the user clicks on the document title link, they are routed to the QC page appropriately, and they are able to QC as per usual (Complete, Complete and Send Message, Cancel).



#### 8) Case Services Supervisor can change the view from the Section Document QC (Petitions or Docket) to My Document QC, My Document QC displays and functions appropriately.

**Part 1**

- Continuing from the previous test
- Click on the My Document QC option from the dropdown menu.

Expected Results:
- [x] All work items assigned to the Case Services Supervisor appear in the My Document QC Inbox.
- [x] If it was a Petition assigned from the Petitions Section, clicking on the Petition link directs the user to QC a Petition. (Serve a few Petitions, save a few for later)
- [x] If it was a document assigned from the Docket Section, clicking on the document link directs the user to QC the document. (Complete a few, Complete and Send Message on a few)

**Part 2**

- Navigate to a case and Click Create
- Select PDF upload or Order or Notice
- Don't Serve it, Save the document instead


**Part 3**

- Click on the In Progress tab

Expected Results:
- [x] The petitions that you saved for later are in the In Progress tab
- [x] The Court Issued documents that you saved for later are in the In Progress Tab.


**Part 4**

- Click on the Completed tab

Expected Results:
- [x] The Petitions that you served are in the Completed tab
- [x] The Documents that you completed QC on are in the Completed tab.

**Part 5**

-  Click on the Petitions Section QC

Expected Results:
- [ ] The Petitions that you saved are in the in Progress
- [x] The Petitions that you served are in the Served box

**Part 6**

- Click on the Docket Section QC

Expected Results:
- [ ] The documents that you saved are in the In Progress box
- [ ] The documents that you completed QC are in the Processed box


**The following tests are more regression types of tests to ensure that the new role can do all the existing tasks that already exist in DAWSON**

#### 9) Case Services Supervisor can:

General
- [x] See the yellow message indicator next to the main Messages tab at the top of the page that displays the total number of new messages
     - [x] Yellow message indicator displays total number of new messages regardless of which section the messages were sent from (Docket or Petitions)

Petitions
- [x] See the File a new petition button on the Petitions Section Document QC 
- [x] Enter a paper petition, Serve a Paper Petition to the IRS.
- [x] QC an electronically submitted Petition; serve electronic petition to IRS
- [x] Assign a work item(s) from the Petitions Document QC

Permissions within a Case
- [x] Edit Statistics
- [x] Add/Edit/Delete Correspondence - includes scanning ability
- [x] Create/Edit/Delete Deadline
- [x] Remove Pending Items
- [x] Edit Case Caption/Case Status
- [x] Edit Case Details
- [x] Add/Edit/Delete Counsel on a case (private and respondent)
- [x] Add a Party to a case
- [x] Remove a Party on a case (there must be at least one party on a case, so to test this, there will need to be at least 2 parties on a case)
- [x] Edit Petitioner Information
- [x] Seal a Petitioners Address/View Petitioners Sealed Address
- [x] Edit a docket entry
- [x] Seal/Unseal Docket Entry
- [x] Seal/Unseal a Case
- [x] Add case to trial session
- [x] Add case to Hearing
- [x] Create, sign, and serve Orders/Notices
- [x] Add Docket Entry (Serve a doc)
     - [x] Serve documents in multiple cases at once (Consolidated cases)

Trial Sessions
- [x] Create/Edit/Delete new trial session
- [x] Edit an Open trial session (as long as trial has not yet started)
- [x] QC eligible cases on New tab
     - [x] For Hybrid cases, should be able to filter by type and see the count of each type QC'd
- [x] Set Calendar

**Comment by cholly75** [comment]
Added - post discussion w/ @mrinsin - preference is to not create a new Section for CSS, but to have them available as members of both Docket and Petition sections. @mmarcotte also suggested that we could accomplish this via insertion of record in Dynamo rather than building out via code.

**Comment by cholly75** [comment]
@mrinsin @rosiehsmith @ttlenard - discussed/demo'ed on EXP  - preference is to replace the FromSection display string with "Case Services" , no concerns otherwise!

**Comment by rosiehsmith** [comment]
For manual deploy steps: @mmarcotte graciously agreed to manually update existing users to this new role by posting to the `/users` endpoint which will ensure they have the 3 associated section mappings - `section|docket`, `section|petitions`, and `section|caseServicesSupervisor`. Thanks! 🥇

**Comment by swongCO** [comment]
UX review - When assigning QC items to CSS, they are being removed from section QCs and displaying only in My Document QC, which is different behavior than for other users. 

Discussed with Chris, Mrin and Rosie and it was decided to leave it be for now since CSS most likely would not be assigned QC items.

Chris will follow up with Deborah at a later date to figure out how to resolve this.

**Comment by cholly75** [comment]
Noted: message behavior w/r/t section displays (Sent/Completed views) appears to mimic behavior for QC items noted by Sui.

**Comment by cholly75** [comment]
Issue: When the CSS assigns a work item in the Petitions or Docket QC section display, that item disappears completely from the display regardless of view or filtering. This behavior does not occur when the same operation is done by Petitions or Docket clerk roles. CC: @mrinsin @rosiehsmith

**Comment by cholly75** [comment]
Issue: items processed by CSS are not showing on the Processed view for Section Document QC. Interestingly, petitions processed by CSS do appear in the Completed view for Section Petitions QC. Neither Section QC display shows In Progress work by the CSS. CC: @mrinsin @rosiehsmith

**Comment by cholly75** [comment]
Plan to ship, will hold off on role assignment pending further conversation/follow-up stories to remedy behavior found in testing

**Comment by mrinsin** [comment]
@cholly75 Updates to 9755 through [this](https://github.com/ustaxcourt/ef-cms/pull/3085) PR to test

1.  When any user (including CSS) assigns a workitem from a section qc box to the CSS user, the item disappears from the section box and only shows up their My Doc QC boxes
2. When a CSS user assigns a workitem from a section qc box to any section user, the item STAYS in the section box and also shows up in the My Doc QC box of that section user
3. When CSS user completes QCing a work item from section doc qc, that item correctly shows up in the section Processed tab

**Comment by cholly75** [comment]
@mrinsin @rosiehsmith - 1 and 2 confirmed, 3 seems to not be happening (you can check CSS1's "Processed" QC view vs. the section "Processed" QC view to see them in the former but not the latter. Thank you!

**Comment by mrinsin** [comment]
Thanks @cholly75. This is likely happening because the section of the work item from CSS's My Inbox/In Progress has no knowledge about what *human facing* section it technically belongs to (docket/petitions) so it only shows up in CSS section related stuff (aka CSS's MY boxes). Thanks for testing our changes!
