### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8385]
As a Court DAWSON user, so that I can get more detailed in my report criteria, I need additional options on the Custom Case report.

There are many situations in which the Court requests data around the case inventory in DAWSON that are ad hoc, one-time requests that cannot be satisfied using the current reports available in DAWSON. To begin facilitating self-service for these users and enable better visibility into Court data, we want to provide users with a way to query DAWSON's case inventory using a variety of criteria associated with the case.

This story adds additional criteria for generating the Custom Case report.

## Pre-Conditions
ustaxcourt/ef-cms#8365 

## Acceptance Criteria
* User can enter one or more of the following criteria to search DAWSON and return a list of cases that match the criteria selected
  - Assigned Judge (multi-select, optional)
    - Selectable values: derived from list of active judges in DAWSON
  - Requested Place of Trial (multi-select, optional)
    - Selectable values: derived from location list in DAWSON, organized by State
  - High Priority (check box, optional)
  - Case Procedure (single-select, optional)
    - Selectable values: Regular/Small
* These values can be used in conjunction with all current options on the CC report
* Results list should display the Consolidation Icon (if any), as this functionality was initially skipped with story ustaxcourt/ef-cms#8365 (See Jason's comment in the story)

## Tasks
- [x] create filters
- [x] populate filters with "real" data
- [x] index high priority on case mapping
- [x] add consolidated case icons
- [x] wire up "clear filters" button

Bugs to fix:
- [x] choosing an item in dropdowns does not reset dropdown options
- [x] clicking out of the box while typing does not reset dropdown options

DOD:
- [x] make filters not wrap on smaller screens
- [x] refactor SelectSearch to use newer method of local state management

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Questions from pre-refinement: 
- High priority - It was mentioned people aren't using this, confirm we do want this added? YES
- Do we need to be able to sort? If so, add sorting in this story or a different one? Sort will be added in another story

**Comment by swongCO** [comment]
**UX Notes**

![9769 Mockup.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e32fa74c-b0fc-4293-839d-5c9abafb0a35)

- Use existing components for new selection criteria
- Ensure that all dropdown default text is "- Select one or more -"

Figma file: https://www.figma.com/file/PjUT05kkwWDqHhIAuej7jl/USTC-%7C-Reports-%7C-Custom-Case-Inventory-9769?type=design&node-id=121%3A2462&t=kA3SkBYM8PHCpExl-1

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user has options for filtering the Custom Case Report by Assigned Judge, Requested place of trial, Priority, and Case Procedure.

- Log in as any Court User
- Click on the Reports menu
- Select Custom Case Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - Case Procedure radio buttons (All, Regular, Small) are now available (default is All)
- [x] **NEW FUNCTIONALITY** - An Assigned Judge Dropdown menu is available, no judge selected by default (optional field)
- [x] **NEW FUNCTIONALITY** - A Requested place of trial Dropdown menu is available, no city/state selected by default (optional field)
- [x] **NEW FUNCTIONALITY** - A checkbox for Calendaring high priority is available, unchecked by default.


#### 2) Court user runs the Custom Case Report and leaves the default for All on the Case Procedure; results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Leave the case procedure default to All
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are both regular and small
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723



#### 3) Court user runs the Custom Case Report and selects Regular for the Case Procedure; results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Select Regular case procedure radio button
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are regular only (no small cases)
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723


#### 4) Court user runs the Custom Case Report and selects Small for the Case Procedure; results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Select Small case procedure radio button
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are small only (no regular cases)
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723



#### 5) Court user runs the Custom Case Report and selects a Judge; results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Leave the case procedure default to All
- Select a Judge from the dropdown menu
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are both regular and small
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are assigned to the Judge you selected only (no other judges are in the results list)
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723

*Repeat this test by selecting other/multiple judges and ensure that the results list populates with those selected judges appropriately.


#### 6) Court user runs the Custom Case Report and selects a City in the requested place of trial, results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Leave the case procedure default to All
- Select a requested place of trial city/state
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are both regular and small
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are have the requested place of trial that you selected only (no other cities are in the results list)
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723

*Repeat this test by selecting other/multiple cities and ensure that the results list populates with those selected cities appropriately.



#### 7) Court user runs the Custom Case Report and checks the box for Calendaring High Priority; results list populates correctly.

- Select a date range
- Leave the filing method default to All
- Leave the case procedure default to All
- Check the box for Calendaring High Priority
- Do not fill out any of the other optional filters
- Click Run Report

Expected Results:
- [x] The results list populates with Cases in the appropriate date range, and displays cases that were filed both by paper and electronically (you may need to do some spot checking by clicking on the docket number).
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that are both regular and small
- [x] **NEW FUNCTIONALITY** - The results list populates with Cases that have been marked as high priority and each case has a green check mark in the column
- [x] The criteria used to generate the report is displayed for the user
- [ ] The default sort order should show the earliest creation date of filing first.
- [x] The total count of results should display on the right side of the screen above the table
- [ ] Data in the table for the cases are populated correctly based on the criteria in Story 9723



#### 8) Court User runs the Custom Case Report and selects multiple filters (the new ones introduced in this story + the existing filters); results list populates correctly.

- Select a date range
- Select any combination of filter options

Expected Results:
- [x] The data in the results list displays the correct data
- [x] The pagination works correctly
- [ ] The total count is correct



#### 9) Court user runs the Custom case report and selects filters so that consolidated cases will appear in the results list; consolidated icon is displayed appropriately in the results list.

- Take note of a few consolidated cases and their metadata (filed date, case procedure, assigned judge, etc.)
- Click on the Reports Menu
- Select Custom Case Report
- Input a date range that will capture the consolidated cases
- Select appropriate filters
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Consolidated cases in the results list display the appropriate consolidated icon (Lead case and member case icons)

**Comment by ttlenard** [comment]
#### Testing Feedback @jasonfu9966 @TomElliottFlexion @cholly75 

Let's plan on discussing these comments on Monday.

- The docket numbers in the results list do not display the suffix (S, L, R, W, etc.). Every other report (with the exception of the Pending report - might need to add this?), Messages, and QC has the suffix displayed.
- The docket numbers in the results list are displayed by case creation date (as indicated in the A/C for 9723), but they are not listed in order by the timestamp of when it was created on that specific date, so the docket numbers are not in ascending order by date.  
     - For example, I searched for a singular day (11/12/21), and I see the top of the results list has a case in the 32000's, and then the bottom of the list has cases in the 30,000's.
     - Case 30320-21 is at the bottom of the list: createdAt": "2021-11-12T05:37:37.280Z"
     - Case 32116-21 is at the top of the list: createdAt": "2021-11-30T13:24:36.555Z"
- When you click on the paginator at the bottom of the screen, it will go to the next page, but the user has to scroll back to the top of the results list to see the next cases in the list. 
     - Can we make it so that the page will jump to the top if you click the paginator at the bottom of the screen?
- Would it make sense to open up the docket number of the case in a new tab by default from the report?  
     - I clicked on the docket number of a case from the results list, and it opened in the same tab, but when I clicked the back button to go back to the report, all of my filters were gone, and I had to remember exactly what I had entered in the filters.
     - Wondering if we just opened in new tab by default rather than having to right click on each docket number to indicate to open in new tab every time.
     - Note, I did this same test with the case inventory report, (clicking back button), and it doesn't retain the data either. Not sure if we have ever received any complaints about this?
- The tooltip for the Calendaring High Priority is quite long, would we ever want to consider shortening that text? Right now it runs over the right side scroll bar.

**Comment by jasonfu9966** [comment]
points ustaxcourt/ef-cms-flexion#4 and ustaxcourt/ef-cms#6494 in PO feedback are included in this story. the rest will be addressed in later stories.

**Comment by ttlenard** [comment]
@jasonfu9966 bullets 4 and 5 looks good. Thank you!

**Comment by ttlenard** [comment]
@jasonfu9966 bullets 4 and 5 looks good. Thank you!
