### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8387]
As a practitioner or petitioner, so that I do not create more work for myself, I need the option to file a Motion to Substitute Trial Exhibit(s) removed as a selection from the e-filing list of documents.

Trial exhibits cannot be substituted in DAWSON - the original proposed trial exhibit remains on the record and any new exhibits are docketed separately at trial via request or oral motion; at the request of Case Services, we would like to remove this particular document as an option for e-filing by petitioners and practitioners so as to not cause undue confusion.

The event code for this document is M123.

## Acceptance Criteria
* Motion to Substitute Trial Exhibit(s) is no longer present in the list of documents available for selection when e-filing by practitioner
* Motion to Substitute Trial Exhibit(s) is no longer present in the list of documents available for selection when e-filing by petitioner

## Notes
- Need to remove the reference to this document from this page on the USTC website when this story is deployed to Prod: https://ustaxcourt.gov/documents_eligible_for_efiling.html
- Retain ability for docket clerks to select this document type when adding a paper filing.

## Tasks
PR - https://github.com/ustaxcourt/ef-cms/pull/3011

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Practitioner files a document on a case; Motion to Substitute Trial Exhibit(s) is not an option in the dropdown picklist.

- Log in as a Practitioner that has access to a case
- Click on the docket number link from the My Cases list
- Click on the File a Document button.
- Click on the Document type dropdown and start typing "Motion to Sub"

Expected Results:
- [x] The Motion to Substitute Trial Exhibit(s) option is no longer in the dropdown picklist.



#### 2) Petitioner files a document on a case; Motion to Substitute Trial Exhibit(s) is not an option in the dropdown picklist.

- Log in as a Petitioner that has an open case
- Click on the docket number link from the My Cases list
- Click on the File a Document button.
- Click on the Document type dropdown and start typing "Motion to Sub"

Expected Results:
- [x] The Motion to Substitute Trial Exhibit(s) option is no longer in the dropdown picklist.



#### 3) Docket Clerk files a paper document on a case; Motion to Substitute Trial Exhibit(s) is still an option in the document type picklist.

- Log in as a Docket Clerk
- Navigate to a Case
- Click on the Create Button
- Click on Paper Filing
- Upload a Document, Click on the Document type dropdown and start typing "Motion to Sub"

Expected Results:
- [x] The Motion to Substitute Trial Exhibit(s) option is still available in the dropdown picklist and can be Served/added to the Docket record appropriately.



#### 4) Docket Clerk edits an existing docket entry; Document Type dropdown picklist is still an option in the document type picklist.

- Log in as a Docket Clerk
- Navigate to a Case
- Click on the edit button for a docket entry that was submitted by a party
- Click on the Document Type dropdown and start typing "Motion to Sub"

Expected Results:
- [x] The Motion to Substitute Trial Exhibit(s) option is still available in the dropdown picklist the Docket record updates appropriately (Code is M123, title of doc is correct).

**Comment by ttlenard** [comment]
Testing results 1/13/2023 - Everything looks great! Thanks crew!
