### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8391]
As a Court User, so that I know which trial session to associate a swing session to, I need the dates of trial sessions and the Session Type to display on the dropdown menu for association.

Swing sessions are linked to existing trial sessions and must be associated with another trial session when created. Currently, the UI for associating these sessions lists other trial sessions by location, however when multiple sessions exist for a location, there is no indication as to the difference in each session - the location simply exists multiple times on the menu.

To help Court Users select the appropriate session, we would like the selections on this menu to reflect the start date and the Session Type of each session in the value presented on the menu.

Screenshot of current dropdown menu:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/2ed32fca-a3ae-4e1e-a76c-25757bec1fe3)

## Acceptance Criteria
* Start dates and Session type for trial sessions listed on association dropdown menu are displayed next to the session location
* No changes to functionality

## Tasks
https://github.com/ustaxcourt/ef-cms/pull/3213

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
![Screen Shot 2023-01-31 at 1.12.00 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/a589d5ae-eeb4-4f81-bb12-ac9196c78a4e)

We designed a couple versions of this dropdown and received feedback from the users, their preference is to go with the above design -- 1.) Add dates to the right of the city/state in ascending order. 2) Add abbreviation for the associated Session Type to the right of the date.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Clerk creates a new trial session and indicates that it is part of a swing session; Location start date, and Session Type of existing trial session displays in dropdown menu.

- Log in as a Court User 
- Click on the Trial Sessions Tab
- Click on Add Trial Session
- Fill out the Session information on this page
- Once you fill in the Start date, the Checkbox indicator will appear for indicating that "this session is part of a swing session".
- Check the box
- Click on the dropdown menu for the "Which Trial Session is This Associated With?"

Expected Results:
- [x] **NEW FUNCTIONALITY** - The City, State, **Date**, and **Session Type** (abbreviated) of the upcoming trial sessions now display
- [x] The list is in alphabetical (ascending) order by City
- [x] **NEW FUNCTIONALITY** - After a City is selected, the City, State, **Date**, and **Session Type** of the session appear in the selection box



#### 2) Clerk edits a New trial session, indicates that it is part of a swing session; Location, start date, and Session Type of existing trial sessions display in the dropdown menu.

- Log in as a Court User 
- Click on the Trial Sessions Tab
- Click on the New tab
- Click on the City, State link of one of the new trial sessions
- Click on the Edit link next to the Session information section
- Mark the Checkbox for the "This is part of a swing session" 
- Click on the dropdown menu for the "Which Trial Session is This Associated With?"

Expected Results:
- [x] **NEW FUNCTIONALITY** - The City, State, **Date**, and **Session Type** (abbreviated) of the upcoming trial sessions now display
- [x] The list is in alphabetical (ascending) order by City
- [x] **NEW FUNCTIONALITY** - After a City is selected, the City, State, **Date** and *Session Type** of the session appear in the selection box



#### 3) Clerk edits an Open trial session that is on a future date, indicates that it is part of a swing session; Location, start date, and Session Type of existing trial sessions display in dropdown menu.

- Log in as a Court User 
- Click on the Trial Sessions Tab
- Click on the Open tab
- Click on the City, State link of one of the Open trial sessions that is in the future
- Click on the Edit link next to the Session information section
- Mark the Checkbox for the "This is part of a swing session" 
- Click on the dropdown menu for the "Which Trial Session is This Associated With?"

Expected Results:
- [x] **NEW FUNCTIONALITY** - The City, State, **Date**, and the **Session Type** (abbreviated) of the upcoming trial sessions now display
- [x] The list is in alphabetical (ascending) order by City
- [x] **NEW FUNCTIONALITY** - After a City is selected, the City, State, **Date**, and **Session Type** of the session appear in the selection box



#### 4) Regression test a few things

- [x] After selecting the swing session when creating or editing an existing trial session (new/open), the page saves appropriately
- [x] The swing session indicator (chain link icon) still displays on all of the Trial Session Pages (New, Open, Closed)
- [x] When clicking on the city, state link of the Swing Session listed on the Trial Session information page, the swing session opens appropriately
- [x] Ensure that the validation error displays appropriately if you select the checkbox for swing session, but then do not select a Trial Session, and then click Save

**Comment by liadmccabe** [comment]
Per discussion with Tenille, Session Types has been added to the mockup.

**Comment by cholly75** [comment]
All tests pass excepting known bug ustaxcourt/ef-cms#8400
