### ISSUE TITLE
Document QC: Reorder Inbox Work Items

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8392]
As a docket clerk, so that I can address cases in priority order, I need work items for cases organized in the QC inbox prioritized by case status.

Currently the Document QC inbox (both Section and user) prioritize items for cases with Calendared status at the top of the list for action. After reviewing work processes, the docket section has asked that we implement additional organization for the inboxes.

## Acceptance Criteria
* Work items in the Docket Section and user QC inboxes are prioritized in the following manner *after* the existing prioritization (i.e., Calendared case items remain at the top, followed by):
  - Work items attached to a case whose status is Submitted, followed by:
  - Work items attached to a case whose status is Assigned - Case, followed by:
  - Work items attached to a case whose status is Assigned - Motion, followed by:
  - Work items attached to a case whose status is Jurisdiction Retained, followed by:
  - All other work items, in ascending order of oldest -> newest
* Within each status group, order items in ascending order of oldest -> newest
* This ordering is present in both Section Document QC Inbox and user (My) Document QC Inbox

## Notes
* Document current behavior sort order

## Tasks
https://github.com/ustaxcourt/ef-cms/pull/3269

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk views Section inbox; QC work items have updated prioritization.

- Log in as a Docket Clerk
- Click on Document QC
- Click on Section Document QC

Expected Results:
- [x] Cases that have a case status of Calendared appear at the top of the list
     - [x] Calendared cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Submitted appear after cases that have a Case Status of Calendared
     - [x] **NEW FUNCTIONALITY** - Submitted cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Assigned - Case are after cases that have a Case Status of Submitted
     - [x] **NEW FUNCTIONALITY** - Assigned- Case cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Assigned - Motion are after cases that have a Case Status of Assigned - Case
     - [x] **NEW FUNCTIONALITY** - Assigned - Motion cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Jurisdiction Retained are after cases that have a Case Status of Assigned - Motion.
     - [x] **NEW FUNCTIONALITY** - Jurisdiction Retained cases within this grouping are listed in ascending order - Oldest to Newest
- [x] If any of the case statuses above are not present in the inbox, the next grouping of case statuses would be the next group.
- [x] Cases that have a case status of anything other than the statuses above, then the priority order is the default (oldest to newest) towards the bottom of the QC Section inbox.



#### 2) Docket Clerk views My QC inbox; QC work items have updated prioritization.

- Log in as a Docket Clerk
- Click on Document QC

Expected Results:
- [x] Cases that have a case status of Calendared appear at the top of the list
     - [x] Calendared cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Submitted appear after cases that have a Case Status of Calendared
     - [x] **NEW FUNCTIONALITY** - Submitted cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Assigned - Case are after cases that have a Case Status of Submitted
     - [x] **NEW FUNCTIONALITY** - Assigned- Case cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Assigned - Motion are after cases that have a Case Status of Assigned - Case
     - [x] **NEW FUNCTIONALITY** - Assigned - Motion cases within this grouping are listed in ascending order - Oldest to Newest
- [x] **NEW FUNCTIONALITY** - Cases that have a case status of Jurisdiction Retained are after cases that have a Case Status of Assigned - Motion.
     - [x] **NEW FUNCTIONALITY** - Jurisdiction Retained cases within this grouping are listed in ascending order - Oldest to Newest
- [x] If any of the case statuses above are not present in the inbox, the next grouping of case statuses would be the next group.
- [x] Cases that have a case status of anything other than the statuses above, then the priority order is the default (oldest to newest) towards the bottom of the QC inbox.


#### 3) Docket Clerk updates the Case status of a case from Calendared to a different case status; Existing QC work item priority order in the QC inbox list is updated appropriately. 

- Log in as a Docket Clerk
- Click on Document QC
- Take note of a cases docket number for a case in a Calendared Status, and remember where it was located in your My Document QC list order. 
- Click on the Section Document QC inbox and take note of where it is located in the Section Document QC list order.
- Navigate to the case 
- Click on the Case information tab
- Click on the edit link next to the Trial information
- Click on the Remove from Trial Link
- Add a disposition and click Remove Case.
- The case will now have the General Docket - At Issue - Ready for Trial status.
- Navigate back to your Document QC inbox you were viewing earlier

Expected Results
- [x] On your My Document QC inbox list, The case is no longer grouped with the Calendared cases near the top of the list
- [x] The case is now located down near the bottom of the "calendared" grouping in your My Document QC inbox list 
- [x] On the Section Document QC inbox list, The case is no longer grouped with the Calendared cases near the top of the list.
- [x] The case is now located down near the bottom of the "calendared" grouping in the Section Document QC inbox list 

*Repeat this test by changing multiple Case Statuses to ensure that after the case status is updated, it is reflected in the appropriate priority order in the QC inbox (Section and My Document QC inbox). 
*Be sure to calendar a case with a QC work item and also ensure that the case is prioritized in the list appropriately

**Comment by mrinsin** [comment]
@cholly75 - when you say work items belonging to `Calendared` cases should be at the top of the table, does that mean cases whose status is `Calendared,` or a case with ANY status as long it has any association with a trial session? The latter is how its currently behaving (therefore cases that were associated with a trial session and then were set to the `Closed` status are sorted higher than non calendared ones). cc @rosiehsmith @liadmccabe

**Comment by cholly75** [comment]
@mrinsin @rosiehsmith @liadmccabe - Court would like the current state to remain so; we do not need to make any changes for that part of the re-ordering.

**Comment by ttlenard** [comment]
@mrinsin @rosiehsmith All tests pass. Thank you!
