### ISSUE TITLE
BUG: Checking/Unchecking the "Use Existing Address" checkboxes causes issues

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8398]
**Describe the Bug**
We found two issues with the check box that copies the existing address information from another petitioner on a case.

1. If a Petitions Clerk checks the box "Use same address & phone number as above" in a Petitioner and Spouse Case, and then unchecks the box, the address information from petitioner 1 does not clear from Petitioner 2's address fields.

2. If a Docket Clerk checks the box "Use Existing Address" when adding a party to a case, and then unchecks the "Use Existing Address" box, the address fields for the new party convert to the fields displayed when entering an international address.  The user types in the address fields, but then gets a validation error stating that they need to enter in the Country and State.

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Test

**Who were you logged in as?**
Docket Clerk, Petitions Clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Testing other functionality

**To Reproduce**

Here are the steps for the Petitions Clerk User:

1. Log in as a Petitions Clerk
2. Click on Document QC
3. Click Start a Petition
4. Select Petitioner and Spouse as the Party type
5. Fill in the required fields for Petitioner 1
6. Add in Spouses Name, and then check the box for Use same address & phone number as above.
7. Uncheck the Checkbox
8. Notice that all of the previous fields do not get removed, and you have to manually delete the address fields that got populated.

Here are the steps that Sui documented with the Docket Clerk User:

1. Log in as a docket clerk.
2. Go to a case.
3. Go to Case Information > Parties and click Add Party.
4. Before filling out any fields, note the address fields, specifically City and State. They should look like this:
5. ![Screen Shot 2023-01-13 at 2.33.36 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d7b3d617-0505-4e9a-82cb-723c26f7e298)
6. Fill out the role type and name.
7. Click on Use existing address.
8. Note that there's a dropdown for existing addresses and the State dropdown becomes an optional text field:
![Screen Shot 2023-01-13 at 2.32.35 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3d6501d1-d262-4bb7-be46-e2bfc2f6dc4f)
9. Click on Use existing address again.
10. Note that the State text field persists instead of reverting back to the dropdown:
![Screen Shot 2023-01-13 at 2.32.54 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1375389c-5f4c-4716-a0f1-f0d54387f73a)
11. Fill out the required fields and click Save.
12. This error is displayed at the top:
13. ![Screen Shot 2023-01-13 at 12.49.28 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4a278256-f051-4782-ae94-8d59af5e0dc8) 
14. The state field is optional but if you enter anything other than the state abbreviation in all caps, it's not validated.
15. There is no country type on the page.
16. Even when all fields are correctly entered, the error with the country type persists and we were unable to proceed.

**Expected Behavior**

Check box behavior should be consistent

**Actual Behavior**
A clear and concise description of what actually happened.

Check box behavior doesn't seem to work correctly after unchecking the box in both scenarios.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**
https://github.com/ustaxcourt/ef-cms/pull/3178 -unchecking the box resulted in an action that was unsetting all contact fields including CountryType. The default country type is domestic, which shows the states dropdown. Not unsetting the country type fixed the issue

## Tasks
- [ ] Fix Docket clerk unchecking issue - Mrinalini https://github.com/ustaxcourt/ef-cms/pull/3178
- [ ] Fix Petitions clerk unchecking issue - Rosie https://github.com/ustaxcourt/ef-cms/pull/3178
- [ ] Add or update testing

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by ttlenard** [comment]
@rosiehsmith The bug appears to be fixed, but I notice that when you click on the "Use Existing Address" check box as a Petitions clerk, the screen jumps down, and the clerk has to scroll up on the page to view the petition again.  Can we ensure that the screen doesn't jump like that when the box is checked?

**Comment by ttlenard** [comment]
@rosiehsmith I did some further testing and found that the screen is currently jumping like that in Staging, so I guess it has always done that.  I'll just move this along and we can fix the jumpiness later. Thanks!
