### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8401]
As a judge, so that I can provide data and context on my work, I need to be able to generate an activity report.

Each quarter the judges are required to produce a report detailing several key pieces of data related to their caseload and activity. Prior to DAWSON, this report was generated automatically for them in Blackstone and then marked up/edited prior to submission to the Chief Judge (see attachment for sample).

Since DAWSON launched, they have had to generate these reports by hand, often taking the form of a spreadsheet or other document. We would like the ability to generate and edit this Activity Report (AR) in DAWSON itself. 

This story will address the statistics portion of the desired report.

## Acceptance Criteria
* The AR can be generated by a judge or CA assigned to the judge's chambers
* When generating an AR, the judge or CA must supply a Start Date and End Date
* The AR displays the name of the Judge, the date the report is generated, and the Start/End dates the report is run for 
* The AR displays the following statistical data, labeled appropriately:
  - ORDERS:
    - Total Number of Orders issued during the reporting period by the judge broken out by event code
    - Aggregate Total Number of Orders issued by the judge
    - The following orders/event codes should be **excluded** entirely from these counts:
      -  OAJ (Order that case is assigned)
      - SPOS (Standing Pretrial Order for Small Case)
      - SPTO (Standing Pretrial Order)
      - OST (Order of Service of Transcript (Bench Opinion))
  - OPINIONS:
    - Total Number of Opinions issued during the reporting period by the judge broken out by event code
    - Aggregate Total Number of Opinions issued by the judge
    - **Include** the following Opinions/event codes in these numbers:
      - TCOP (Tax Court Opinion)
      - MOP (Memorandum Opinion)
      - SOP (Summary Opinion)
      - OST (Bench Opinion)
  - CASES:
    - Total Number of Cases associated with the judge that were Closed/Closed-Dismissed during the reporting period
* The AR contains the following statistical data, as measured over the period for which the report is run
  - TRIAL SESSIONS:
    - Total Number of Special trial sessions the judge has been assigned to that have Start Dates that fall within this time frame 
    - Total Number of Sessions for all non-Special sessions the judge has been assigned to that have Start Dates that fall within this time frame and are not in New status
      - Assume value for each session based on type (NOTE: values subject to change):
        - Regular/Small/Hybrid sessions: 1 session each
           - R/S/H session marked as part of a SWING session: .5 session each
        - Motion/Hearing: .5 session each

## Notes
[https://app.zenhub.com/files/152320868/271734f3-440a-4bb7-b63e-1a8b715b3e23/download](https://app.zenhub.com/files/152320868/271734f3-440a-4bb7-b63e-1a8b715b3e23/download)

* Issued = signed and docketed for purposes of this report

## Tasks
- [x] Add Activity Report item to dropdown (https://github.com/ustaxcourt/ef-cms/pull/3360)
  - [x] Make dropdown item only visible for judges and their chambers 
- [x] Add Activity Report search UI (https://github.com/ustaxcourt/ef-cms/pull/3390)
- [x] Add submit sequence (https://github.com/ustaxcourt/ef-cms/pull/3397)
- [x] Add interaction that fetches activity report results (https://github.com/ustaxcourt/ef-cms/pull/3414)
- [x] Add Activity Report results UI (https://github.com/ustaxcourt/ef-cms/pull/3414)
- [x] Retrieve closed cases in date range for the judge (https://github.com/ustaxcourt/ef-cms/pull/3452)
- [x] Retrieve sessions held by judge in date range (https://github.com/ustaxcourt/ef-cms/pull/3457)
- [x] Retrieve opinions sorted by event code for judge in date range (https://github.com/flexion/ef-cms/pull/10009)
- [x] Retrieve orders sorted by event code for judge in date range (https://github.com/flexion/ef-cms/pull/10013)
- [x] Styling fixes (https://github.com/flexion/ef-cms/pull/10014)
- [x] UX Feedback (https://github.com/flexion/ef-cms/pull/10017)
- [x] DOD - fix on blur validation for datepicker - https://github.com/flexion/ef-cms/pull/10020
- [x] Refactoring
  - [x] https://github.com/flexion/ef-cms/pull/10015
- [x] Include Hybrid-S in judge's trial sessions - https://github.com/ustaxcourt/ef-cms/pull/3493
- [x] https://github.com/ustaxcourt/ef-cms/pull/3498 PO feedback

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

Mockups

Link to Activity page in Reports tab in top navigation:

![Screen Shot 2023-02-16 at 3.07.19 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/d3eb0654-ab9b-4408-971c-f8d8ab8ff37c)

- Link only displays for judges and their chambers for their own activity
___
Default/view when user has not entered start and end dates:

![Activity report - no data.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1ff4014b-61ad-47b4-817c-ab1546b65f09)

- Use date functionality and validation from [Deadlines](https://app.test.ef-cms.ustaxcourt.gov/reports/case-deadlines) report
- User should not be able to enter dates in the future
___
Views when date range is entered:

![Activity report - empty state.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1d4e7273-97f9-45af-80f3-665c51604c3a)

![Activity report - data.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/1c6aa560-ee4d-41ab-a86f-762720ae71f2)

- Incorporated Judge Buch's feedback into mockups
- Use existing styles for all components
- Sessions Held list order should match <s>the design</s> what is in Dawson
- Orders/Opinions tables are sorted alphabetically by event code in ascending order
- Rows for Orders Issued are variable; all others are static
- If there is no data for Orders Issued, show table header with message below "There are no orders issued for the selected dates"; see My Messages for example:
![Screenshot 2023-04-18 at 1.53.04 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/025ba2b5-217f-4812-be93-9463a3bd59d4)
- Consideration of future additions (like case table and pdf version)

Figma file, page "v5": https://www.figma.com/file/nEux3pFI6g2VOZwSDDkS4c/USTC-%7C-Reports-%7C-Judges-activity-report-9809?node-id=322%3A334&t=eU0OhxZsJZgYuEX8-1

**Comment by cholly75** [comment]
@ttlenard - please note I've added A/C to specify exclusions/inclusions for specific event codes

**Comment by ttlenard** [comment]
## Test Cases


#### 1) Judge user selects the activity report to run; new Activity report page loads

- Log in as a Judge
- Click on the Reports menu
- Select the Activity report

Expected Results:
- [x] **NEW FUNCTIONALITY** - New Activity report page loads
- [x] **NEW FUNCTIONALITY** - Header Displays the Report title as "Activity - Judges Name"
- [x] **NEW FUNCTIONALITY** - Start date and End date fields are present, but no data displays
- [x] **NEW FUNCTIONALITY** - Run Report button is present, but is greyed out
- [x] **NEW FUNCTIONALITY** - Empty report text at the bottom of the page that states, "Enter a date range to view activity"


#### 2) Judge user inputs a valid Start and End date and runs the report, data is loaded.

- Continuing from the previous test
- Input valid date fields (start date that is in the past, and an end date that is after the start date)
- Click Run report

Expected results:
- [x] **NEW FUNCTIONALITY** - The Judges Name is displayed on the report
- [x] **NEW FUNCTIONALITY** - The Start/End dates that the report is run for is displayed
- [x] **NEW FUNCTIONALITY** - The date that the report was created is displayed
- [x] **NEW FUNCTIONALITY** - There is a Cases Closed Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Cases closed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Cases Closed-Dismissed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Grand Total Number is displayed and is bolded
- [x] **NEW FUNCTIONALITY** - There is a Sessions Held Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions display the total number (each session is considered 1 session each)
     - [x] **NEW FUNCTIONALITY** - Hybrid-S sessions are included in the Hybrid category when counting session values
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions associated with a swing sessoin display the total number (each session is considered .5 session each)
     - [x] **NEW FUNCTIONALITY** - Motion Hearing display the total number of weeks in session (each session is considered .5 session each)
     - [x] **NEW FUNCTIONALITY** - Special sessions display the total number of sessions (each session is considered 1 session each)
- [x] **NEW FUNCTIONALITY** - Orders Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Order Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Order types that have been issued by the Judge
     - [x] **NEW FUNCTIONALITY** - The following Order types are NOT in the table:
          - [x] **NEW FUNCTIONALITY** - OAJ, SPOS, SPTO, OST
- [x] **NEW FUNCTIONALITY** - Opinions Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Opinion Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Opinion types that have been issued by the Judge
     - [x] **NEW FUNCTIONALITY** - The following Opinion types should be in the table (Judge may not have issued all these types, but they all need to be checked!):
          - [x] **NEW FUNCTIONALITY** - TCOP, MOP, SOP, OST   



#### 3) Judge user inputs invalid Start and End dates; receive validation error

- Continuing from the previous test
- Input a different set of date values (making sure that you input in invalid date i.e. start date is after end date, End date is before start date, incorrect date format, etc.)
- Run the report

Expected results:
- [x] **NEW FUNCTIONALITY** - Validation error appears letting the user know that they need to adjust the invalid date field.



#### 4) Repeat tests 1, 2, and 3 with a Chambers Administrator


#### 5) Docket closes a case, closes a case by issuing a dismissal order, and dockets an opinion for a Judge; Activity report reflects the updated numbers.

- Log in as a Judge or CA
- Click on Reports and select Activity
- Include today's date, and click Run Report
- Take note of the values in the tables. (take a screen grab)

- Log in as a docket clerk
- Navigate to an open case assigned to the Judge user you are testing with
- Click on the Case information tab
- Update the case status to Closed
- Next, navigate to another open case assigned to the Judge
- Add an Order and Dismissal type of Order to the case's docket record so that the case status is Closed - Dismissed. (Be sure to select the Judge user you will be testing with as the Judge issuing the Order.)
- Next, Navigate to another case
- Add an Opinion type of document to the case (be sure to select the judge user you will be testing with as the Judge issuing the Opinion)

- Log in as a Judge or CA
- Click on Reports and select Activity
- Include today's date, and click Run Report
- Compare the values in this report to the values in the report that you took a screen grab of previously

Expected Results:
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated Values in the Cases Closed tab to reflect the Closed case and the Closed - Dismissed Case
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated values in the Orders Issued table to reflect the Order of Dismissal Order you added to the docket record
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated values in the Opinions Issued table to reflect the Opinion that you added to the Docket record.



#### 5) Court users besides Judge and CA do not have access to run the Activity report.

- Log in as any other court user (Law Clerk, Docket Clerk, CotC, Petitions Clerk, etc.)

Expected Results:
- [ ] The Activity report is not available for any other court user to run.

**Comment by ttlenard** [comment]
@swongCO I'm moving this one back to the UX Design column for now.  I've got some questions about the current design.  

1 - Per the mockup, there is a new "Activity" report option available in the report dropdown menu.  Is this only shown/available for Judges/CA users since these are the only users that can pull the report?  Does the Activity report option NOT show for any other user?  Would it make more sense for Judges to get to this report from their dashboard view since the judges dashboard is specific to the Judge?

2 -  Per this A/C "The AR displays the name of the Judge, the date the report is generated, and the Start/End dates the report is run for", can we add in the date that the report was generated somewhere in the mockup?


3 - I'm having a hard time understanding the Sessions held tile...In the A/C, it states that we are measuring Special sessions as the total number, but for non-special sessions, it is the total number of weeks. It looks like we are just displaying the total number of sessions in the tile.  Shouldn't these be two different calculations?  Maybe we should indicate which ones are measured in weeks vs which ones are measured as a total?


4 - When a user inputs in the dates, does the report dynamically generate on the fly or does the user need to click a "Run report" type of button. What would happen if a user changed the start/end date after the initial data has loaded?  Would a new timestamp for when the report was run be added? 


5 - What kind of validation error messaging would we have if the user inputs a start date in the future?  Or the end date is before the start date?

**Comment by rachelschneiderman** [comment]
@cholly75 During the WIP demo today we received some feedback for this story:
-  There is a desire to be able to generate this report for any judge in the system, even if you are not that judge or in their chambers
- Add the ability to generate this report without selecting a judge and get data for all judges in the system

Just wanted to document this feedback that was received, we can discuss at a later point if/how/when to implement that feedback.

**Comment by cholly75** [comment]
@rachelschneiderman - had follow up discussion today w/ the Court - let's chat tomorrow post-standup.

**Comment by cholly75** [comment]
@rachelschneiderman - while this is under development, if we can build the hooks in to capture the incoming "Hybrid S"-type trial sessions ahead of time great, if not no worries - it'll be part of a follow up story.

**Comment by rachelschneiderman** [comment]
[Follow up design discussions](https://flexion.slack.com/archives/CD6DEU37Z/p1681334457218889). Order/opinion tables should be sorted alphabetically by event code.

**Comment by rachelschneiderman** [comment]
From UX review with Sui:

- Empty state messages (No activity for date range/Enter a date range) should move closer to search form - not a dealbreaker but should try to get it closer
- “Enter a valid end/start date” - should be the error message when you enter letters/invalid date into date input (match at case deadlines report)
- When no orders filed in date range, show custom message below the table headers for orders issued
- Update trial session types sorting on trial sessions table to match what it looks like on create/edit trial session forms

**Comment by swongCO** [comment]
UX review feedback
- btn should be disabled by default on initial load
- <s>center align the total columns for all tables (see design)</s>
- <s>ensure that the total columns have enough width so that the column header does not wrap to two lines; this is happening when there is a wide Order Type column (our guess as to the reason):</s>
![Screenshot 2023-04-19 at 3.20.26 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/da306978-c9b8-4245-a749-f5d50e0d57a6)

Discussed further and resolved the two bullets above (with strikethroughs):
- make columns left aligned to be consistent with tables in Dawson
- table column widths are automatically calculated based on the content (USWDS behavior)

**Comment by cholly75** [comment]
@rachelschneiderman @mrinsin @rosiehsmith - I seem unable to advance the date in the Start Date field past the currently populated End Date using the calendar picker? I was attempting to run reports sequentially for different date ranges.

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/af06b766-c844-44fc-a2ce-0028aefb9f6d)

**Comment by cholly75** [comment]
We have the converse problem with the End Date picker:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/f61634fe-18a5-4565-8150-8c005e013b3e)

**Comment by cholly75** [comment]
One more "picker issue" - looks like the year doesn't show for Sept/Nov/Dec?

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/87fb0746-d944-4513-8dc1-38be8899c824)
