### ISSUE TITLE
E-Access: Add E-Mail Fields to Petitions Entry/Edit UI

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8404]
As a Petitions Clerk, so that I can capture e-mail information included on a petition, I need to be able to record a petitioner's email address and consent to e-service when entering or editing a petition.

The court has approved a change to the Petition form used to submit, er, petitions. The form now includes an opportunity for petitioners to indicate that they wish to receive e-service. We need to capture this information, along with the petitioner e-mail address(es) during the entry of the petition into DAWSON. Clerks should also be able to edit this information when reviewing the petition during QC.

Capture of this data will enable workflow for follow-on stories.

We anticipate these changes will need to be live in mid-March 2023.

## Acceptance Criteria
* On the Parties tab of the Petition entry/edit screen, below each ZIP code field there is a field labeled "Petition E-Mail Address"
  - This is an optional field 
  - This is a free text field 
  - Upon saving the record, validate that the text in the field is a valid e-mail address format
  - The value entered in this field is associated with the Petitioner for whom it was entered 
* On the Parties tab of the Petition entry/edit screen, below each E-Mail Address field there is a check box labeled "E-Service Consent"
  - This is an optional field
  - This field can be checked or unchecked by the petitions clerk
  - The value entered in this field is associated with the Petitioner for whom it was entered
* These fields are only displayed when entering/editing a paper petition
* These fields exist and can be entered for each petitioner on the Petition.
* If address is sealed by a docket clerk, seal the Petition email address info from internal court users as it does currently today for email/address info
* Petition email address should be available to view on the Petitioner card to internal users only, 
* Do not display petition email address information on the JSON for public users.

## Tasks
- [x] Update create paper petition entry form to include petition email address and e-consent checkbox (https://github.com/flexion/ef-cms/pull/9835)
  - [x] Update edit paper petition entry form to include petition email address and e-consent checkbox
- [x] Update review and serve page to include petition email address and e-consent information (https://github.com/flexion/ef-cms/pull/9837)
- [x] Update parties information to display petition email address and e-consent checkbox selection (https://github.com/flexion/ef-cms/pull/9840)
- [x] Do not display petition email address and e-consent checkbox fields on create case form when logged in as an external user (petitioner, respondent, practitioner (https://github.com/flexion/ef-cms/pull/9841)
- [x] Persist petition email address and e-consent checkbox information on Petitioner entity (https://github.com/flexion/ef-cms/pull/9834)
  - [x] Add validation for petition email address
  - [x] Add validation for e-consent checkbox
- [x] Styling for sealed address/contact info - PR (https://github.com/flexion/ef-cms/pull/9846)
- [x] Add feature flag logic to hide/show e consent related form and readonly fields (https://github.com/flexion/ef-cms/pull/9846) 
- [x] Hide paper petition email and e-consent fields from PetitionQc form when editing/QCing an e-filed petition - (https://github.com/flexion/ef-cms/pull/9848)
- [x] DOD refactoring/dry up code, parallelize actions in sequence - (https://github.com/flexion/ef-cms/pull/9847)
- [ ] DOD - componentize e-consent display in ReviewSavedPetition.tsx

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

Mockups:

![Create:Edit petitions - email field.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/e71c78a1-f390-4170-b91e-273480a2e514)

- Note that email field label and checkbox text are in Sentence case as per style guide
- Email is not hyphenated - this follows existing format on Dawson
_____________________________
Review petition screen with email/eservice:

![Review and Serve - consent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/03eb24d9-b265-4cc0-b6c8-09559570942e)

![Review and Serve - no consent.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/39da0c88-817f-4751-80b1-7141a8b42075)

- If e-service checkbox is not checked, display "No e-service consent"
_____________________________
Review petition screen with no email/eservice:

![Screen Shot 2023-02-14 at 9.47.08 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/140916cd-651d-4538-b7ae-168b560aa6e5)
_____________________________

Petitioner card on Case Info page:

![Screen Shot 2023-02-14 at 9.22.17 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/a0b70f1c-51e5-427f-87de-10f100b2153d)

- If there is no email address, display "Not provided"
_____________________________

Petitioner card on Case Info page - sealed address and email:

![Petitioner card - sealed address.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/f0a006bb-0cee-4d64-9c28-bee0465c0d82)

- This view is only available to users who can currently see sealed addresses
- Keep current behavior for all other users

**Comment by ttlenard** [comment]
Hey @cholly75, while writing up the test cases for this story, I came up with some ideas on how we might want to display this new data on the Review screen and on the Petitioner card.  Let me know what you think.

Review Petition Screen when the E-Service Checkbox is checked:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/dadf1c22-eb99-478d-91a8-3ee103c02868)

Review Petition Screen when the E-Service Checkbox is NOT checked:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/c0c3f2c1-6977-4cda-afb1-820790eff7cb)

Petitioner card - add in the Petition Email Address if entered by Petitions Clerk:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0d4d1265-ce58-4ad2-82ca-a4f378df0e3c)

Petitioner card after Admissions Clerk adds in the email, awaiting verification from Petitioner:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/55f3daa3-06e9-418a-85d5-2d706ae8e812)

Petitioner Card after Petitioner verifies email and gains eAccess:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/771bc6fd-7387-4d08-9f5b-b69a7b614391)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk/Case Services Supervisor enters a Paper Petition; New field to enter the Petitioners email address is available, and is optional.  There is also a new checkbox for E-Service Consent.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Select any party type (be sure to test with all of the party types to ensure that the email address field is available to all party types)
- Fill in the Party info
- Underneath the Zip Code field:


Expected Results
- [x] **NEW FUNCTIONALITY** - There is a new free text field available titled "Petition e-mail address"
- [x] **NEW FUNCTIONALITY** - The field indicates that it is an optional field and is not required
- [x] **NEW FUNCTIONALITY** - There is a new checkbox available titled "E-service consent" that can be checked/unchecked
- [x] **NEW FUNCTIONALITY** - The checkbox is optional


*Repeat this test with all of the different party types
*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 2) Petitions Clerk/Case Services Supervisor creates a case without adding in an email address, and without checking the E-Service consent box; Case can be created and served as per usual.

- Continuing from the previous test
- Fill out the required fields for the Petition 
- Make sure that you didn't fill out anything in the new Petition Email address field or the check the box.
- Click Create Case

Expected Results:
- [x] On the review and Serve the Petition screen, there is no email address shown, and there is no E-service consent indicator.
- [x] Case can be served to the IRS as per usual
- [x] When reviewing the Petitioner card on the case, information is displayed as per usual (address, phone number, Service Preference, Counsel)

*Repeat this test with all of the different party types
*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor


#### 3) Petitions Clerk/Case Services Supervisor adds an invalid email address; does not check the E-Service consent checkbox; Creates case; receives validation error for inaccurate email address.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Fill in the Party info
- Add in an email that is invalid (missing the "@" symbol, not having the proper ending ".com, .org", etc.)
- Do not check the E-service consent box
- Fill in the rest of the required fields for the case
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - Receive validation error indicating that a correct email address needs to be entered

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 4) Petitions Clerk/Case Services Supervisor adds a valid email address; does not check the E-Service consent checkbox; Creates case; Petition email address displays appropriately on the review screen.

- Continuing from the previous test
- Enter in a valid email address
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address is displayed on the Party tab
- [x] No E-service consent is displayed

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor


#### 5) Petitions Clerk/Case Services Supervisor clicks on the Docket number of the case that was created, but has not yet been served; Petition email address is displayed on the Petitioner card.

- Continuing from the previous test
- Click on the docket number of the case that you just created (but have not yet served)
- Click on the Case information tab
- Review the Petitioner Card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address that you entered for the Petitioner is now displayed on the Petitioner Card, no information about E-Service consent is displayed.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 6) Petitions Clerk/Case Services Supervisor Serves the Petition to the IRS; Petition email address is displayed on the Petitioner Card. 

- Continuing from the previous test
- Click on the Docket Record tab to view the docket record
- Click on the Petition link
- Click Review and Serve Petition
- Click Serve to IRS
- Click Done on the Print for paper service
- Click on the Served tab
- Click on the Petition link for the Petition you just served
- Click on the Case information tab
- Review the Petitioner card


Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address that you entered for the Petitioner is now displayed on the Petitioner Card, no information about E-Service consent is displayed.


*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor


#### 7) Petitions Clerk/Case Services Supervisor enters a Paper Petition; adds an invalid email address; checks the E-Service consent checkbox; Creates case; receives validation error for inaccurate email address.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Fill in the Party info
- Add in an email that is invalid (missing the "@" symbol, not having the proper ending ".com, .org", etc.)
- Check the E-service consent box
- Fill in the rest of the required fields for the case
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - Receive validation error indicating that a correct email address needs to be entered

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 8) Petitions Clerk/Case Services Supervisor enters a Paper Petition; adds a valid email address; checks the E-Service consent checkbox; Creates case; Petition email address and E-Service Consent info displays appropriately on the review screen.

- Continuing from the previous test
- Enter in a valid email address
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address is displayed on the Party tab
- [x] **NEW FUNCTIONALITY** - E-service consent information is displayed


*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor


#### 9) Petitions Clerk/Case Services Supervisor clicks on the Docket number of the case that was created, but has not yet been served; Petition email address is displayed on the Petitioner card.

- Continuing from the previous test
- Click on the docket number of the case that you just created (but have not yet served)
- Click on the Case information tab
- Review the Petitioner Card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address that you entered for the Petitioner is now displayed on the Petitioner Card, no information about E-Service consent is displayed.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 10) Petitions Clerk/Case Services Supervisor Serves the Petition to the IRS; Petition email address is displayed on the Petitioner Card.

- Continuing from the previous test
- Click on the Docket Record tab to view the docket record
- Click on the Petition link
- Click Review and Serve Petition
- Click Serve to IRS
- Click Done on the Print for paper service
- Click on the Served tab
- Click on the Petition link for the Petition you just served
- Click on the Case information tab
- Review the Petitioner card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address that you entered for the Petitioner is now displayed on the Petitioner Card, no information about E-Service consent is displayed.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor


#### 11) Petitions Clerk/Case Services Supervisor enters a Paper Petition for a Petitioner and Spouse case; adds email addresses for both Petitioners; one email is an invalid email address; checks the E-Service consent checkbox for both; Creates case; receives validation error for the one inaccurate email address.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Select Petitioner and Spouse as the Party type 
- Fill in the Party info for Petitioner 1
- Add in a valid email address and check the box for E-Service consent
- For Petitioner 2, add in an email that is invalid (missing the "@" symbol, not having the proper ending ".com, .org", etc.)
- Check the E-service consent box for Petitioner 2
- Fill in the rest of the required fields for the case
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - Receive validation error indicating that a correct email address needs to be entered.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 12) Petitions Clerk/Case Services Supervisor enters a Paper Petition for a Petitioner and Spouse case; adds email addresses for both Petitioners; checks the E-Service consent checkbox for both; Creates case; Petition email address and E-Service Consent info for both parties displays appropriately on the review screen.

- Continuing from the previous test
- Enter in a valid email address for Petitioner 2
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address is displayed for both parties on the Party tab
- [x] **NEW FUNCTIONALITY** - E-service consent information is displayed for both parties

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 13) Petitions Clerk/Case Services Supervisor Serves the Petitioner and Spouse Petition to the IRS; Petition email addresses are displayed on the Petitioner Cards.

- Continuing from the previous test
- Click Serve to IRS
- Click Done on the Print for paper service
- Click on the Served tab
- Click on the Petition link for the Petition you just served
- Click on the Case information tab
- Review the Petitioner cards

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email addresses that you entered for the Petitioners are now displayed on the Petitioner Cards appropriately, no information about E-Service consent is displayed.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 14) Petitions Clerk/Case Services Supervisor enters a Paper Petition for a Petitioner and Spouse case; adds email addresses for both Petitioners; checks the E-Service consent checkbox for only one Petitioner; Creates case; Petition email address is reflected appropriately for each Petitioner; E-Service consent info displays appropriately for the one petitioner on the Review Screen.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Select Petitioner and Spouse as the Party type 
- Fill in the Party info for Petitioner 1
- Add in a valid email address and check the box for E-Service consent
- For Petitioner 2, add in an email address
- DO NOT Check the E-service consent box for Petitioner 2
- Fill in the rest of the required fields for the case
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address is displayed for both parties on the Party tab
- [x] **NEW FUNCTIONALITY** - E-service consent information is displayed for only Petitioner 1
- [x] **NEW FUNCTIONALITY** - No E-service consent is displayed for Petitioner 2

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 15) Petitions Clerk/Case Services Supervisor enters a Paper Petition for a Petitioner and Spouse case; Fills out email address and checks the box for Petitioner 1; Checks the use same address and phone number box; email address and checkbox for Petitioner 2 are not populated/checked.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Select Petitioner and Spouse as the Party type 
- Fill in the Party info for Petitioner 1
- Add in a valid email address and check the box for E-Service consent
- For Petitioner 2, check the box for "Use same address and phone number"

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address and the E-Service Consent checkbox are not filled in from the Petitioner 1 selections.

*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



#### 16) Petitions Clerk/Case Services Supervisor enters a Paper Petition and adds a valid email address, Clicks one of the Edit buttons on the review screen; Updates the Petition email address; information is saved appropriately.

- Log in as a Petitions Clerk or a Case Services Supervisor
- Click on the Document QC tab
- Click on the Start a Petition button
- Scan/Upload a Petition document
- Fill in all of the required Petition information, and be sure to add in a valid email address and check the box for E-Service Consent
- Click Create Case
- On the Review and Serve Petition Screen, Click the Edit button on the Parties card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Petition email address can be edited
- [x] **NEW FUNCTIONALITY** - The E-service consent check box can be unchecked.
- [x] **NEW FUNCTIONALITY** - Upon save, the updated information is presented on the Review and Serve Petition Screen

*Repeat this test by clicking on the Edit links for the other cards on the Review and Serve Petition screen and ensure that you can edit the Petition email address field and can check/uncheck the box.
*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor



~#### 17) Petitions Clerk/Case Services Supervisor QC's an electronic Petition; New field to enter the Petitioners email address is available and is optional.  There is also a new checkbox for E-Service Consent.~

~- Log in as a Petitions Clerk or a Case Services Supervisor~
~- Click on the Document QC tab~
~- Click on the Section Document QC Tab~
~- Click on the Petition Link for an electronically submitted Petition~
~- On the Parties tab, Underneath the Zip Code field:~


~Expected Results~
~- [ ] **NEW FUNCTIONALITY** - There is a new free text field available titled "Petition e-mail address"~
~- [ ] **NEW FUNCTIONALITY** - The field indicates that it is an optional field and is not required~
~- [ ] **NEW FUNCTIONALITY** - There is a new checkbox available titled "E-service consent" that can be checked/unchecked~
~- [ ] **NEW FUNCTIONALITY** - The checkbox is optional~


~*Repeat this test with all of the different party types~
~*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor~


~#### 18) Petitions Clerk/Case Services Supervisor adds in an invalid email address to an electronically submitted Petition; Review's Petition; receives validation error.~

~- Continuing from the previous test~
~- Add in an email that is invalid (missing the "@" symbol, not having the proper ending ".com, .org", etc.)~
~- Check the E-service consent box~
~- Fill in the rest of the required fields for the case~
~- Click Review Petition~

~Expected Results:~
~- [ ] **NEW FUNCTIONALITY** - Receive validation error indicating that a correct email address needs to be entered.~

~*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor~



~#### 19) Petitions Clerk/Case Services Supervisor adds in a valid email address to an electronically submitted Petition; Reviews Petition; Information saves appropriately.~

~- Continuing from the previous test~
~- Enter in a valid email address~
~- Click Review Case~

~Expected Results:~
~- [ ] **NEW FUNCTIONALITY** - The Petition email address is displayed on the Review and Serve Petition Page~
~- [ ] **NEW FUNCTIONALITY** - E-service consent information is displayed~

~*Be sure that you do this test with the Petitions Clerk and the Case Services Supervisor~


~#### 20) Docket clerk/Admissions clerk/Case Services Supervisor/Cotc users can edit the Petition email address field and can check/uncheck the E-Service Consent box.~

~- Log in as a Docket Clerk~
~- Navigate to one of the Docket numbers from the test cases above where you added in an email for the Petition email address~
~- Click on the Case information tab~
~- Click on the edit link on the Petitioner card~

~Expected Results:~
~- [ ] **NEW FUNCTIONALITY** - The Petition email address can be edited~
~- [ ] **NEW FUNCTIONALITY** - The E-service consent check box can be checked/unchecked.~
~- [ ] **NEW FUNCTIONALITY** - Upon save, the updated information is presented on the Petitioner Card~

~*Repeat this test as an Admissions Clerk, Case Services Supervisor and CotC user.~



#### 21) All Court users can view the Petition email address on the Petitioner card if one was entered for the Petitioner.

- Log in as a Court user that does not have the edit permission for editing Petitioner info (Judge, ADC, CA, Trial Clerk, Floater, Reporters office, Petitions Clerk, General user)
- Navigate to one of the Docket numbers from the test cases above where you added in an email for the Petition email address
- Click on the Case information tab

Expected Results:
- [x] The Petition email address field is displayed on the Petitioner card
- [x] No edit link is available for the Petitioner card for these users

*Be sure that you test with all of the Court users listed above.



##### 22) Docket Clerk/Case Services Supervisor seals a Petitioners address; Petition email address is also sealed from view from specific Court users

- Log in as a Docket clerk
- Navigate to one of the Docket numbers from the test cases above where you added in an email for the Petition email address
- Click on the Case information tab
- Click on the Edit link for the Petitioner
- Check the box to Seal the Petitioners Address, confirm that you want to seal the address.
- Click Save

Expected Results:
- [x] The Petition email address is now in red text, but is still viewable to Docket Clerks, Admissions clerks, CotC, and Case Services Supervisors
- [x] When viewing the Petitioner card on the case as any other Court user, it states the usual "Address is sealed" information, and no Petition email address info is displayed for the user.

*Be sure that you do this test with the Case Services Supervisor


#### 23) Petitioner gains eAccess to their case; Views their Petitioner card on their case; The Petition email address information does not display on the card, but IS available in the case JSON.

- This test has some set up steps
- Log in as a Petitions Clerk
- Click on Document QC tab
- Click on the Start a Petition button
- Complete the Petition. Be sure that you add in a valid email address and check the box for E-Service Consent. 
- Serve the Petition to the IRS and make sure that you remember the docket number.
- Log out
- Log in as an Admissions Clerk
- Navigate to the case you just served to the IRS in the previous steps
- Click on Case information
- Click the Edit button for the Petitioner
- Add in an email that you have access to, and save it.
- Now the set up for this test is ready!

- As a Petitioner, navigate to your email that you used in the set up steps above.
- Verify your new account
- Log in to DAWSON and click on the docket number of your case from the My cases page, from the above steps
- Click on the Case information tab
- On your Petitioner Card:

Expected Results:
- [x] No Petition email address information is displayed on the Card for the Petitioner.
- [x] When viewing the case JSON, the Petition email address information displays


#### 24) IRS Practitioner views a case; Petition email address information does not display on the Petitioner card, but IS available in the case JSON.

- Continuing from the test above
- Log in as an IRS Practitioner
- Type in the Docket number of the case from the previous test case
- Click on the Case information tab
- On the Petitioner Card

Expected Results:
- [x] No Petition email address information is displayed on the Card for the Petitioner.
- [x] When viewing the case JSON, the Petition email address information displays


#### 25) Private Practitioner views a case that they do not have access to; Case information card with Petition email address information is not available, and no petition email address info is available in the case JSON.

- Log in as a Private Practitioner
- Type in the Docket number of the case from the previous test case (you shouldn't have access to the case)
- Open up the console and view the case JSON and view the case in the UI

Expected Results:
- [x] No case information tab is available
- [x] When viewing the case JSON, Petition email address information is not displayed.


#### 26) Private Practitioner views a case that they have access to; Petition email address information does not display on the Petitioner Card, but IS available in the case JSON.

- Continuing from the test above
- Request access to case by filing an entry of appearance
- After you file the document, you will have access to the case
- Click on the Case information tab
- On the Petitioner Card

Expected Results:
- [x] No Petition email address information is displayed on the Card for the Petitioner.
- [x] When viewing the case JSON, Petition email address information displays


#### 27) Public user views a case that they do not have access to; Case information tab/Petitioner info is not displayed; Petition email address is NOT available in the case JSON.

- As a public user, search for the case from the above test cases
- Open up the console and view the case JSON and view the case in the UI

Expected Results:
- [x] No case information tab is available
- [x] When viewing the case JSON, Petition email address information is not displayed.

**Comment by ttlenard** [comment]
@cholly75 After completing the test cases, I believe we need to add a few things to the A/C, I've added them above:
- If address is sealed by a docket clerk, seal the Petition email address info from internal court users as it does currently today for email/address info
- Petition email address should be available to view on the Petitioner card to internal users only, not displayed on the JSON for public users either

**Comment by rachelschneiderman** [comment]
Moving this back to UX because we have some questions we need to answer before we understand the domain enough to complete this work.

Questions:
1. How is the petition email address used now?
2. How will it be used in the future? How is it different from the petitioner email address?
3. Do we need to store the "petition email address" after the petition has been served? If so, why?
4. What security concerns do we have in regards to the petition email address? Who can view that information? What sealing rules apply to it?

**Comment by cholly75** [comment]
@rachelschneiderman - see below, happy to meet to discuss!

1. It isn't.
2. It will be used in ustaxcourt/ef-cms#8405 to generate part of the NOTR text. It is different in that A) it isn't tied to any e-access workflow or verification mechanics, and is intended to record the email address on the petition itself.
3. Yes. We intend to leverage this is a future iteration on our e-access workflow.
4. Not many, TBH. Anyone in the court should be able to view this info on the party, and if a docket clerk seals the address then this info should be sealed as well, much like how if we seal an address today the e-mail address is sealed.

Thanks,
Chris

**Comment by cholly75** [comment]
@rachelschneiderman - court conference is 2/17, we should have a go-live date after that meeting.

**Comment by swongCO** [comment]
Updated UX notes based on Tenille's comment and convo with Rachel.

**Comment by mrinsin** [comment]
Additional UI specs based on discussion with @swongCO regarding the parties information card on the Petition review screen -
1. When `paperPetitionEmail` exists and `eServiceConsent` is checked, display email and 'E-service consent' label.
2. When `paperPetitionEmail` exists and `eServiceConsent` is NOT checked, display email and 'No e-service consent' label.
3. When `paperPetitionEmail` does NOT exist and `eServiceConsent` is checked, display only 'E-service consent' label.
4. When `paperPetitionEmail` does NOT exist and `eServiceConsent` is NOT checked, display nothing.

cc @rachelschneiderman @shumway-tm

**Comment by liadmccabe** [comment]
UX Notes on Email Validation:
![Screen Shot 2023-02-20 at 1.25.25 PM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/f4fbef0f-391e-4197-8812-81aa3df46961)
1. When an improperly formatted email address is entered, user should get the following inline validation message "Please enter email address in format: yourname@example.com."
2. The same text should be used in the list of error messages for the page [red content box]

**Comment by ttlenard** [comment]
@rachelschneiderman @mrinsin @shumway-tm I've updated the test cases above per our conversation from earlier today.

4, 14 - updated
20 - removed entirely
23, 24 - updated
25 - new
26 - used to be 25, updated
27 - new

**Comment by ttlenard** [comment]
@rachelschneiderman @mrinsin @shumway-tm - I've removed the test cases above (17, 18, 19) that have to do with electronically submitted Petitions, per conversation with @cholly75 yesterday.

**Comment by rachelschneiderman** [comment]
This story requires a manual deploy step. Run the following script to add the feature flag to each environment's deploy table:

`scripts/dynamo/setup-e-consent-fields-enabled-feature-flag.sh`

**Comment by swongCO** [comment]
UX review feedback

![Screenshot 2023-02-24 at 1.27.25 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3d4445da-8e23-4c25-9cf1-06dc481cb42e)
On the Review and Serve screen, make the spacing between the phone number and e-service consent line the same as spacing between the other lines. In the screenshot above, under the spouse's info, the space between "n/a" and "E-service consent" should be the same as in the petitioner's info.

___
![Screenshot 2023-02-24 at 1.40.38 PM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/3351affa-39d4-465a-aa21-f396338c20c6)
While testing the email validation, it was observed that the message is inconsistent with the others. Remove 'Please" from the beginning and start with "Enter" to match the other messages.

![Screenshot 2023-02-27 at 9.07.40 AM.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/c1b65343-b875-4c0f-9c97-2479d719b631)

**Comment by rachelschneiderman** [comment]
@swongCO For the error message feedback, I see what you mean. This is something we noticed and brought up with @liadmccabe. After some discussion, @liadmccabe recommended we start a new pattern with error messages, starting with this story. Happy to implement either way, let us know when you two have had time to discuss and move forward with one of those options.

**Comment by cholly75** [comment]
Story go-live date confirmed 3/20

**Comment by rachelschneiderman** [comment]
@ttlenard Feature flag name: `e-consent-fields-enabled-feature-flag`

**Comment by ttlenard** [comment]
Testing Feedback 3/1/23:
@rachelschneiderman @mrinsin @shumway-tm 

I found 2 things while testing.

1. Whenever I check/uncheck the E-Service consent checkbox, the screen jumps down. This happens for any Petitioner or Petitioner/Spouse.  
2. After clicking create case, when DAWSON would normally load the Review and Serve Petition Screen, it gets stuck on a white screen.   The console is reporting a TypeError.  This isn't happening ALL of the time, but has happened to me a few times while testing.  If I click on the address bar and hit enter on my keyboard, it will reload and get me to the Review and Serve Petition screen and I can continue my work.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/cb4c35fd-d236-46bc-a780-bd5f3029021e)
