### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8406]
As a amicus curiae, so that submissions can be properly identified on the docket, I need a new event code for amicus briefs.

On occasion a judge will call for amicus curiae (outside individuals/organizations who are not parties to a case) to weigh in on the issues in a case with a brief, known as an amicus brief. Typically, the amicus curiae will file a motion requesting leave to file an amicus brief, lodge said brief, and when the motion is granted the brief subsequently ends up docketed as a MISC-type document.

Currently we do not have a specific event code for identifying these types of documents; we would like a new event code to help us better identify these on the docket record.

We anticipate these changes will need to be live in mid-March 2023.  This feature *can* go live ahead of time, as we are already accepting amicus briefs today.

## Acceptance Criteria
* New event code established for amicus brief (AMBR)
* AMBR documents can be received as paper filings
* AMBR documents cannot be e-filed
* AMBR documents are served on both petitioner and respondent
* When docketing an AMBR, the docket clerk must enter the **Who is filing this document?** value as free text
  - This value is what displays on the docket record in the Filed By column
* For all other fields when docketing an AMBR, the docket clerk has the same fields available to them as if they were docketing a paper-filed MISC event code document
* AMBR documents receive cover sheets
* AMBR documents can be selected as targets when docketing a paper-filed M115 (Motion for Leave to File)
* AMBR documents are "Brief"-type documents
* AMBR documents can be multidocketed
* AMBR documents obey all usual visibility rules

## Tasks
- [x] Add new event code https://github.com/flexion/ef-cms/pull/9856 - Mrinalini, Rosie 
- [x] Based on the event code, change the "Who is filing this document" input to be free text https://github.com/flexion/ef-cms/pull/9856 - Mrinalini, Rosie 
- [x] Add unit tests https://github.com/flexion/ef-cms/pull/9856 - Mrinalini, Rosie, Zach
- [x] Add error messages on form based on UX https://github.com/flexion/ef-cms/pull/9856 - Mrinalini, Rosie, Zach
- [x] DOD - Remove amicusCuriae and use otherFilingParty instead - https://github.com/flexion/ef-cms/pull/9867
- [x] DOD - Reuse DocketEntry.EntityValidationRules in DocketEntryFactory - https://github.com/flexion/ef-cms/pull/9867
- [x] DOD - Integration test  - https://github.com/flexion/ef-cms/pull/9871
- [x] DOD - Add AMBR entity constant - https://github.com/flexion/ef-cms/pull/9867
- [x] DOD - change DocketEntry.generateFiledBy to TS - https://github.com/flexion/ef-cms/pull/9871
- [x] DOD - paper filed motions should NOT require objections

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk adds a Paper Filing to a case; Amicus Brief is available in the Document Type dropdown.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Create button
- Select Paper Filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Click on the document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - New document type titled Amicus Brief is available in the dropdown list.


#### 2) Docket Clerk selects Amicus Brief as the document type for a paper filing; Clerk is able to type the filer's name in a free text field; cannot select Petitioner(s) or Respondent as filer.

- Continuing from the previous test
- Select Amicus Brief from the document dropdown
- Add in a Description
- Skip or fill in the additional info fields, can check or leave the checkboxes blank.
- Review the "Who is filing this document" section.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Clerk can type in the filers name in a free text field
- [x] **NEW FUNCTIONALITY** - Clerk cannot select Petitioner or Respondent

#### 3) Docket Clerk Serves the Amicus Brief; Document Title is reflected appropriately on the pop-up confirmation modal.

- Continuing from the previous test
- Click on the Save and Serve button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The pop-up service confirmation modal displays the document title as whatever text you entered into the Description field. 


#### 4) Amicus Brief is displayed appropriately on the Docket Record.

- Continuing from the previous test
- Click Done on the Print for paper service screen
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Event Code on the docket record is AMBR
- [x] **NEW FUNCTIONALITY** - The Document Title on the docket record is whatever text you added in the Description field
- [x] **NEW FUNCTIONALITY** - The filed by value is the name that you typed in the free text field in the previous test case
- [x] Served parties code is B
- [x] The rest of the information on the docket record is displayed as per usual (date filed, page number, service date, edit/seal links, etc.)


#### 5) Court User views the Amicus brief on the docket record; Document has a coversheet with the appropriate information.

- Continuing from the previous test
- Click on the Document title to open up the Document View page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document has a coversheet with the title (the text that you entered in the description field)
- [x] The document coversheet includes all of the usual coversheet information (case caption, service date, docket number, index number, date filed, etc.)
- [x] The Amicus Brief is available after the coversheet.


#### 6) Docket Clerk files a Motion for Leave to File; Amicus Brief is available in the "Which Document is this Motion for leave to file for?" dropdown.

- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Paper Filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Click on the document type dropdown and select Motion for leave to file or Motion for leave to file out of time.
- The "Which document is this motion for leave to file for?" dropdown appears.

Expected Results:
- [x] **NEW FUNCTIONALITY** - New document type titled Amicus Brief is available in the dropdown list.
- [x] **NEW FUNCTIONALITY** - Upon selection of the Amicus Brief, the Description field becomes available
- [x] Clerk can select Other in the "Who is filing this document?" and type in the filers name in a free text field
- [x] Upon clicking on Save and Serve, the pop-up modal confirming service indicates the appropriate title of the document to include whatever text you entered in the Description field for the Amicus Brief.
- [x] After clicking Yes, Serve, and after the Print for paper service, the document title on the Docket Record displays the title as what you added in the description field for the amicas brief appropriately.

*Repeat this test with the Motion for Leave to File out of Time document.



#### 7) Docket Clerk adds an Amicus Brief document on the Lead case in a Consolidated Group; Serves the document to all cases in the consolidated group.

- Log in as a Docket Clerk
- Navigate to the Lead case in a consolidated group
- Click on the Create Button
- Select Paper filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Select Amicus Brief as the document type
-  Add in a description
- Fill in the Filers name
- Click Save and Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Amicus Brief document title (what you added in the description) appears on the "Are you ready to Initiate Service?" pop-up modal for multi-docketing.
- [x] **NEW FUNCTIONALITY** - After confirmation of service, the Amicus Brief is now available on the docket record for all the selected cases
- [x] **NEW FUNCTIONALITY** - The Event Code on all of the docket records is AMBR
- [x] **NEW FUNCTIONALITY** - The Document Title on all of the docket records is whatever you typed in the description field
- [x] **NEW FUNCTIONALITY** - The filed by value is the name that you typed in the free text field in the previous test case
- [x] Served parties code is B
- [x] The rest of the information on the docket record is displayed as per usual (date filed, page number, service date, edit/seal links, etc.)
- [x] **NEW FUNCTIONALITY** - The document has a coversheet with the title Amicus Brief, and lists all cases and index numbers that the document was served to.
- [x] **NEW FUNCTIONALITY** - The coversheet has all of the usual requirements for consolidated cases 

*Repeat this test by selecting only a few cases to serve the document to.
*Repeat this test by saving first, and then serving from the docket record
*Repeat this test by saving first, and then serving from the Document QC/In Progress tab

#### 8) Parties on the case can view the Amicus Brief Document

- Log in as a Petitioner that has access to the case that you used above

Expected Results:
- [x] **NEW FUNCTIONALITY** - Party can click on the document title and can view the document

*Repeat this test with an IRS Practitioner, and a Private Practitioner that is a party to the case


#### 9) Terminal User can view the Amicus Brief Documents filed on cases.

- Access DAWSON as the Terminal User
- Search for a case that has an Amicus Brief Document Filed.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Terminal user can click on the document title and can view the document.



#### 10) Petitioner e-files a document on their case; Amicus Brief is not available in the dropdown options for e-filing

**Part 1**
- Log in as a Petitioner
- Navigate to your case
- Click on the File a Document button
- Click on the Document Type dropdown

Expected Results:
- [x] There is no option for Amicus Brief in the Dropdown options

**Part 2**
- Continuing from the steps above
- Select Motion for leave to File

Expected Results
- [x] There is no option for Amicus Brief in the Dropdown options for the "Which document are you Requesting Leave to file for?" dropdown.

*repeat Part 2 test with the Motion for Leave to File out of Time
*repeat this entire test with a Private Practitioner and an IRS Practitioner to ensure that they cannot select Amicus Brief either.

**Comment by ttlenard** [comment]
@rosiehsmith @mrinsin @zRogersFlexion. I just updated the test cases above so that the document title is whatever the user entered in the description field.

cc: @cholly75

**Comment by swongCO** [comment]
Per dev request, adding an error message when the “Who is filing this document?” field is blank - "Enter the name of the amicus curiae"

![Amicus brief error message.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/4ca9de8f-8650-426e-aced-f60947dded63)

**Comment by zachrog** [comment]
Conversation with UX:

What should the "Who is filing this document" field for an Amicus Brief turn into after the docket entry has been served?
 - It should turn into the same "Filed By" free response text as other documents
