### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8411]
As a Court, so that I can accurately record the content of a NOD or SNOD on a case, I need to remove the validation requiring positive values in these fields.

Analysis by the Court indicates that although extremely rare we do have cases in which the Notice of Deficiency or Second Notice of Deficiency indicates a negative value for a deficiency or penalty. We recently introduced a validation for these fields requiring the clerk to enter a positive number, however in light of this we would like to remove that validation for these fields.

To safeguard against errors by the user, we would like to introduce a pop-up modal asking them to confirm that they meant to enter a negative value when appropriate.

## Acceptance Criteria
* Negative values can be entered in any of the deficiency or penalty fields for a case
* Negative values are calculated correctly along with the value of other penalty fields to arrive at the total
* When saving a record containing a negative value, the user is presented with a modal window asking them to confirm their intention to enter a negative value

## Tasks

- [X] Remove Validation prohibiting negative numbers (PR: https://github.com/flexion/ef-cms/pull/9971)
  - [X] Penalty Entity
  - [X] Statistic Entity
  - [X] Field level validation
- [x] Add confirmation alert under fields containing negative numbers
- [x] Update tests

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by liadmccabe** [comment]
![Screen Shot 2023-02-16 at 10.37.11 AM.png](https://images.zenhubusercontent.com/615db9dfea10871c30cb1170/b7a23e34-e8ab-4c3a-bdef-402a59a3f3b9)

1. When a user enters "-" and a number into the text field, validation will appear with the text "You are entering a negative value, please confirm before saving".
2. The validation text will disappear when the "-" is removed 
3. If there are multiple negative values, each text field will have it's own associated info message/alert 
4. There should be a blue bar on the left hand side indicating which field is highlighted (much like the error messages currently function). 
5. The validation text should also be blue

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk enters IRS penalty information for a given year/period when inputting a paper petition, When negative values are entered a validation message is presented for the user.

- Log in as a Petitions Clerk
- Click on Document QC
- Click Start a new Petition
- Fill out the required fields and upload/scan in the Petition document
- On the IRS Notice tab, click the yes radio button indicating that the IRS notice was provided (must be a deficiency case).
- Input the date of the notice, and then under the statistics Proposed by IRS section, input a year or period, followed by the total Deficiency.
- Click on the Calculate Penalties on IRS Notice link.
- In the Calculate Penalties on IRS Notice modal, add in multiple Penalties, being sure that some of the penalties that you enter are negative numbers.

Expected Results:
- [x] For negative numbers, a blue bar on the left hand side of the Penalty info appears
- [x] For negative numbers, The validation message in blue text in the UX notes above appears below the box with the negative amount.
- [x] No validation appears for positive values.



#### 2) Petitions Clerk removes the "-" from the Penalty amount; Validation indicators no longer appear

- Continuing from the previous test
- Delete the "-" from one/all of the negative amounts that you entered in the previous test

Expected Results:
- [x] The blue validation indicators (blue bar and blue text) no longer appear



#### 3) Petitions Clerk adds in negative numbers; validation indicators re-appear; Petitions clerk can calculate and Save the Penalty information per usual manner.

- Continuing from the previous test
- Be sure that you add at least one negative amount in the penalty information
- The Blue validation indicators should re-appear
- Click Calculate and Save

Expected Results:
- [x] The calculated total penalties displays the correct calculation (taking into account the negative numbers)



#### 4) Petitions clerk adds in another year/Period; Adds additional penalty data and includes negative numbers; Can calculate and Save the penalty information per usual manner.

- Continuing from the previous test
- Click the Add Another Year/Period button
- Add in the date, the total deficiency amount, and then click Calculate Penalties on IRS Notice link
- Be sure that you add at least one negative amount in the penalty information
- The Blue validation indicators should appear
- Click Calculate and Save

Expected Results:
- [x] The calculated total penalties displays the correct calculation (taking into account the negative numbers)



#### 5) Petitions Clerk Creates Case, Edits the Penalty information before serving Petition to the IRS.

- Continuing from the previous test
- Click on Create Case  
- On the Review and Serve Petition Screen, Click the Edit button on the Penalty box
- Click on the Calculate Penalties on IRS notice link

Expected Results:
- [x] The individual penalties that you input previously are retained.
- [x] When editing the Penalties, if you add a negative penalty, the data is saved appropriately and the total is updated.



#### 6) Petitions Clerk Serves a Petition to the IRS; Penalty data is saved and can be viewed.

- Continuing from the previous test, click Review Petition (total penalty info should match what was on the edit screen)
- Click Serve to IRS
- Click Yes, Serve
- Click done on the print for paper service page
- Click on the Served tab
- Click on the Docket Record of the Petition that you just served
- Click on Case Information
- Click on the Statistics tab

Expected Results:
- [x] There is a link to "View Itemized Penalties" next to the Edit Year/Period Link.
- [x] After clicking the link, a pop-up modal displays the itemized penalties that you entered in the previous tests, and displays the total penalties (negative and positive values) appropriately.
- [x] The Penalties in the Determination column will be blank at this point in the test.
- [x] Clicking the close button in the top right will close the modal.



#### 7) Petitions Clerk enters multiple IRS Penalties (positive and negative numbers) for a given Year/Period when QCing an electronically submitted Petition; When negative values are entered a validation message is presented for the user.

- Log in as a Petitions Clerk
- Click on Document QC
- Click on Section Document QC
- Click on a Petition link 
- On the IRS Notice tab, click the yes radio button indicating that the IRS notice was provided.
- Click on Deficiency as the Type of case
- Input the date of the notice, and then under the statistics Proposed by IRS section, input a year or period, followed by the total Deficiency.
- Click on the Calculate Penalties on IRS Notice link.
- In the Calculate Penalties on IRS Notice modal, add in multiple Penalties, including both positive and negative values

Expected Results:
- [x] For negative numbers, a blue bar on the left hand side of the Penalty info appears
- [x] For negative numbers, The validation message in blue text in the UX notes above appears below the box with the negative amount.
- [x] No validation appears for positive values.
- [x] When a negative value is removed, the validation message disappears.



#### 8) Petitions Clerk Saves the Penalty data; can open the modal again to edit the saved values.

- Continuing from the previous test.
- Click the Calculate and Save button.
- The Total Penalties box should display the total of the inputs that you put in the modal, taking into consideration the positive and negative values.
- Click on the Calculate Penalties on the IRS Notice link again.

Expected Results:
- [x] The individual penalties (both positive and negative values) that you input are retained



#### 9) Petitions Clerk edits the Penalty information before serving Petition to the IRS.

- Continuing from the previous test
- Click on Review Petition  
- On the Review and Serve Petition Screen, Click the Edit button on the Penalty box
- Click on the Calculate Penalties on IRS notice link

Expected Results:
- [x] The individual penalties that you input previously are retained.
- [x] When editing the Penalties, if you add a negative penalty, the data is saved appropriately and the total is updated.



#### 10) Petitions Clerk Serves a Petition to the IRS; Penalty data is saved and can be viewed.

- Continuing from the previous test, click Review Petition (total penalty info should match what was on the edit screen)
- Click Serve to IRS
- Click Yes, Serve
- Click on the Served tab
- Click on the Docket Record of the Petition that you just served
- Click on Case Information
- Click on the Statistics tab

Expected Results:
- [x] There is a link to "View Itemized Penalties" next to the Edit Year/Period Link.
- [x] After clicking the link, a pop-up modal displays the itemized penalties that you entered in the previous tests, and displays the total penalties (negative and positive values) appropriately.
- [x] The Penalties in the Determination column will be blank at this point in the test.
- [x] Clicking the close button in the top right will close the modal.



#### 11) Petitions Clerk Edits Penalty data after the Petition is served to the IRS; Data is saved.

- Continuing from the previous test 
- Click Edit Year/Period.
- Click on the Calculate Penalties on IRS Notice link.
- Edit the values of the Penalties that are in the pop-up, ensuring that you add or edit the negative values

Expected Results:
- [x] For negative numbers, a blue bar on the left hand side of the Penalty info appears
- [x] For negative numbers, The validation message in blue text in the UX notes above appears below the box with the negative amount.
- [x] No validation appears for positive values.
- [x] When a negative value is removed, the validation message disappears.

- Click Calculate and Save

Expected Results:
- [x] The Total Penalties box displays the updated total.
- [x] After clicking the Save button on the Edit Year/Period screen, the total Penalties data on the Statistics tab reflects the correct total  (taking into consideration the positive and negative values entered)


- Click on the View Itemized Penalties link from the Statistics tab

Expected Results:
- [x] The itemized penalties pop-up modal displays both the positive and negative values as you entered them in previous steps
- [x] The total matches what is on the statistics screen.



#### 12) Clerk adds a negative Deficiency (Determination) and Penalties (Determination) to a case; Individual Penalties (Determination) are saved.

- Log in as a Petitions Clerk, Docket Clerk, Case Services Supervisor, or the Clerk of the Court. (Be sure to test with all these roles.)
- Navigate to a case
- Click on the Case Information tab, and then click on the Statistics tab.
- Click on Edit Year/Period Link
- Add in a Deficiency (Determination) amount.
- Click on the Calculate penalties as determined by Court link.
- Enter in multiple penalties, being sure that some of the penalties that you enter are negative numbers.

Expected Results:
- [x] For negative numbers, a blue bar on the left hand side of the Penalty info appears
- [x] For negative numbers, The validation message in blue text in the UX notes above appears below the box with the negative amount.
- [x] No validation appears for positive values.



#### 13) Clerk removes the "-" from the Penalty amount; Validation indicators no longer appear

- Continuing from the previous test
- Delete the "-" from one/all of the negative amounts that you entered in the previous test

Expected Results:
- [ ] The blue validation indicators (blue bar and blue text) no longer appear



#### 14) Clerk adds in negative numbers; validation indicators re-appear; Clerk can calculate and Save the Penalty information per usual manner.

- Continuing from the previous test
- Be sure that you add at least one negative amount in the penalty information, and also be sure to test this with only a negative value (no positives)
- The Blue validation indicators should re-appear
- Click Calculate and Save

Expected Results:
- [x] The calculated total penalties displays the correct calculation (taking into account the negative numbers)



#### 15) Clerk Saves the Deficiency (Determination) and the Penalties (Determination); Itemized Penalty data is saved and can be viewed.

- Continuing from the previous test
- Click the Save button on the Edit Year/Period page

Expected Results:
- [x] Green confirmation banner indicating the statistics have been updated
- [x] The Determination fields are now populated on the Statistics Screen (negative values included in the calculation)
- [x] After clicking the "View Itemized Penalties" link, the determination column data is populated and matches the data that you entered in the previous test (negative values included).

*If there are multiple years/periods be sure that you repeat this test for each year/period

**Comment by shumway-tm** [comment]
After talking with @liadmccabe it was determined that instead of confirming a negative number through a modal, we will proceed with the validation design in the mockup above for any fields that accept a negative number in the Statistic form.

CC: @rgoshen @cholly75 @ttlenard

**Comment by cholly75** [comment]
Some wonkiness editing a negative value - you can't place the cursor between the negative sign and the dollar sign, the cursor flips to the front of the first digit. Backspacing does remove the negative sign correctly though. Same behavior for trying to insert after removal.

**Comment by shumway-tm** [comment]
After research and speaking with @cholly75, the wonkiness mentioned above is due to the minus sign being moved in front of the dollar sign prefix, which is not a selectable character in the input field. Behavior existed prior to this story without the minus sign and is intentional behavior for the input.

CC: @rgoshen
