### ISSUE TITLE
Retain Filed Date on E-Filed Simultaneous Documents When Served

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8417]
As a party to a case, so that the docket record correctly reflects the date of filing, I need e-filed Simultaneous documents to maintain the original filing date when serving.

Currently, documents with the word "Simultaneous" in the title are not immediately served upon e-filing. These documents are correctly held until both sides have filed their respective versions of the document, and then served at a later date.

Upon serving these documents, the Filed Date on the docket record is being updated to the Served Date, and the new coversheet being applied also indicates a filed date of the date of service.

We would like these documents to retain the original filing date on the docket record when being served, and for the new generated coversheet to reflect this as well.

## Acceptance Criteria
* When an e-filed Simultaneous document is served, the Filed Date on the docket record remains unchanged from the date the document was originally filed
* When an e-filed Simultaneous document is served, the cover sheet generated has the filing date that the document was originally filed
* When an e-filed Simultaneous document is served, the Served Date on the docket record and the cover sheet is correctly reflected 

## Tasks
https://github.com/ustaxcourt/ef-cms/pull/3486

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk serves two Simultaneous Answering brief documents on a case, original filed date is retained on the docket record.

Preconditions: 
- IRS Practitioner has filed a simultaneous answering brief document on a case
- Private Practitioner or Petitioner has also filed a simultaneous answering brief document on the same case as the IRS.

- Log in as a docket Clerk
- Click on Document QC
- Click on Section Document QC
- QC both of the Simultaneous Documents, taking note of the filed date (To test this, it may be easier if the filed date is not the same as the served date)
- Navigate to the docket number of the case that the IRS Practitioner and other party filed the simultaneous documents in.
- Ensure that both of the documents have not yet been served
- Click on the document link of one of the Simultaneous documents
- Click on the Serve button from the document preview page
- Confirm Service

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Date field on the docket record reflects the original filing date, and not necessarily the served date for both documents.
- [x] The served date on the docket record reflects the correct service date for both documents
- [x] **NEW FUNCTIONALITY** - The coversheet displays the filing date that the document was originally filed for both documents
- [x] The coversheet displays the correct service date stamp at the bottom on both documents.


#### 2) Repeat test 1 with all of the simultaneous types of documents.  

- [x] Simultaneous Answering Memoranda of Law
- [x] Simultaneous Memoranda of Law
- [x] Simultaneous Opening Brief
- [x] Simultaneous Opening Memorandum Brief
- [x] Simultaneous Reply Brief
- [x] Simultaneous Supplemental Brief
- [x] Simultaneous Sur-Reply Brief
- [x] Simultaneous Sur-Reply Memorandum Brief
