### ISSUE TITLE
Pamphlet Host Page

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8421]
As a member of the public, so that I can view the opinion pamphlets published by the Court, I need a page listing electronic versions of published pamphlets.

In story ustaxcourt/ef-cms#8369 we implemented an event code for Tax Court Report Pamphlets to allow docketing of the opinion pamphlets the Court publishes several times per year. To make these pamphlets more accessible, we would like to present a chronological list of published pamphlets along with the corresponding docket numbers to the general public, and link to this list from the USTC website (similar to the Today's Opinions/Orders pages).

The expected Court process will be that each time a pamphlet is published, Docket section will enter a TCRP entry on the docket numbers associated with the opinions published in the pamphlet. These entries will be docketed with the same filed date, title, and file. The pamphlet host page should automatically read in and display the pamphlet with its associated information as laid out in the AC.

## Acceptance Criteria
* Page with links to published TCRP documents exists and can be linked to from Court website
* Page is titled "United States Tax Court Reports"
* No authentication/login needed to view page
* One pamphlet on this page for each unique filed date on TCRP docket entries
* Information displayed for each pamphlet:
  - FilingDate of TCRP docket entry
  - Docket number/Case Titles the pamphlet has been docketed for
  - Page number associated with TCRP docket entry on the case
  - Cases ordered alphabetically by LAST NAME of Petitioner
* Pamphlets are hyperlinked to the pamphlet document that opens in a new tab
* Pamphlets are arranged chronologically in date descending order using the filed date

## Notes
* Sample pamphlet:[https://app.zenhub.com/files/152320868/c5517737-dc71-4c27-a52b-50dcb560373d/download](https://app.zenhub.com/files/152320868/c5517737-dc71-4c27-a52b-50dcb560373d/download) 

## Tasks
- [x] create endpoint for new pamphlets page https://github.com/flexion/ef-cms/pull/9974/
- [x] create new landing page for pamphlets https://github.com/flexion/ef-cms/pull/9974/
- [x] retrieve all pamphlets for new endpoint - https://github.com/flexion/ef-cms/pull/9977
- [x] display pamphlets - https://github.com/flexion/ef-cms/pull/9988
  - [x] transform data in helper
  - [x] styling
  - [x] sorting
  - [x] verify hyperlinks
- [x] Mobile styling https://github.com/flexion/ef-cms/pull/9990
- [x] Feedback - https://github.com/ustaxcourt/ef-cms/pull/3410
- [x] DOD - https://github.com/flexion/ef-cms/pull/9991

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by cholly75** [comment]
Page Number data associated w/ TCRP docket entry to be addressed in follow-up story

**Comment by katiecissell** [comment]
Mockups attached.
Page title of “United States Tax Court Reports”, styling is H1
Below page title there should be another header that is the year 2023, styling is H2
A link should be displayed of the most recent pamphlet (Docket will send us the link name via the description field). Use current link styling.
A table should be below the pamphlet. (Use current table spacing and styling)
Page number info will not be covered in this ticket but the column should still be made. The page numbers will start appearing with 9967.

Note for Mobile: Title should wrap as needed. Table should be displayed in mobile following current styling.

![updated Table per pamphlet.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/e08bdb42-4585-482b-ae78-ab7bf035668f)
![13 Pro - 14.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/f878f2d5-b295-498c-851d-9cb6ab4b076d)   
![New year pamphlets.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/ca9744ad-9e7f-455a-b94c-01119ca51e7a)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Public Non-logged in user accesses Pamphlet hosting page, new Reports page displays; user can access Pamphlets via hyperlink that have been added to the docket record.

Precondition for tests:
- Docket clerk has added a TCRP document to the Docket Record on one case.  
     - Take note of the description that the docket clerk added when docketing the TCRP
     - Take note of the filed date that the docket clerk added when docketing the TCRP

- As a non-logged in user, navigate to the pamphlet hosting page link
- Review the Page:

Expected Results:
- [x] **NEW FUNCTIONALITY** - Page is titled "United States Tax Court Reports"
- [x] **NEW FUNCTIONALITY** - Year Header displays above the table, and displays the appropriate year of filed date
- [x] **NEW FUNCTIONALITY** - Under the header, display a hyperlink to the pamphlet description that was added when the pamphlet was added to the docket record.
- [x] **NEW FUNCTIONALITY** - To the right side of the page, the Filed date that you input when docketing the TCRP is displayed.
- [x] **NEW FUNCTIONALITY** - Table will have the following headers: Docket No., Case, Page.
- [x] **NEW FUNCTIONALITY** - The table will be populated with the entry that matches the case that the docket clerk uploaded a TCRP into
     - [x] **NEW FUNCTIONALITY** - The docket number for the case is displayed
     - [x] **NEW FUNCTIONALITY** - The Case title is displayed
     - [x] **NEW FUNCTIONALITY** - The page column is blank for now (page number data will be populated here once 9967 is implemented).


#### 2) Public non-logged in user clicks on the hyperlink for a pamphlet; new tab opens and displays the document that was added to the docket entry.

- Continuing from the previous test
- Click on the hyperlink of the pamphlet

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document opens appropriately in a new tab


#### 3) Public non-logged in user accesses the Pamphlet hosting page; multiple cases that are associated with a single TCRP are included in the table.

Preconditions: Docket Clerk has added the same TCRP document to multiple cases
     - Be sure that you add the SAME filed date and the EXACT same document description for each docket entry that you add to a case.

- As a non-logged in user, navigate to the pamphlet hosting page link

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is one pamphlet link, with a table below it. The table includes all of the cases that you uploaded the pamphlet to.
     - [x] **NEW FUNCTIONALITY** - The docket number for each case is displayed
     - [x] **NEW FUNCTIONALITY** - The Case title is displayed
     - [x] **NEW FUNCTIONALITY** - The page column is blank for now (page number data will be populated here once 9967 is implemented).
- [x] **NEW FUNCTIONALITY** - Cases are sorted in alphabetical order by the case caption.
- [x] **NEW FUNCTIONALITY** - After clicking on the hyperlink, the Document opens appropriately in a new tab.



#### 4) Docket Clerk adds a different TCRP document to the docket record of multiple cases; Filed date is different than in the previous tests; New table is displayed.

- Log in as a docket clerk
- Take note of what you titled the TCRP documents and the specific filed date that you input from the previous tests
- Navigate to a docket record of a different case
- Upload a TCRP
- Include the DIFFERENT filed date that you input in the previous test
- Be sure that the description for this TCRP is DIFFERENT than the previous tests
- Repeat the steps above in multiple cases, making sure that the filed date and the Description that you add for this TCRP is the SAME for each case.
- Access the Pamphlet Hosting page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The TCRP hosting page displays a NEW table with the TCRP that you just uploaded.
- [x] **NEW FUNCTIONALITY** - The description of what you typed for the TCRP is displayed in the hyperlink
- [x] **NEW FUNCTIONALITY** - The Filed date matches what you input while uploading the TCRP
- [x] **NEW FUNCTIONALITY** - The table will be populated with the cases that the docket clerk uploaded a TCRP into
     - [x] **NEW FUNCTIONALITY** - The docket number for each case is displayed
     - [x] **NEW FUNCTIONALITY** - The Case title for each case is displayed
     - [x] **NEW FUNCTIONALITY** - The page column is blank for now (page number data will be populated here once 9967 is implemented).


#### 5) Docket Clerk adds a TCRP document to a case, inputs the same date as in the test case above, but names the TCRP differently; The TCRP is added to the existing table.

- Log in as a docket clerk
- Take note of what you titled the TCRP documents and the specific filed date that you input from the previous test
- Navigate to a docket record of a different case
- Upload a TCRP
- Include the SAME filed date that you input in the previous test
- Be sure that the description for this TCRP is DIFFERENT than the previous test
- Access the Pamphlet Hosting page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The TCRP hosting page displays the TCRP that you just uploaded, and it is added to an existing table with the same filed date.
- [x] **NEW FUNCTIONALITY** - The description of what you typed for the TCRP is displayed in the hyperlink if the Petitioners name is the alphabetically first. If it is not alphabetically first in the list, then the TCRP link will remain the same as it was previously.
- [x] **NEW FUNCTIONALITY** - The Filed date matches what you input while uploading the TCRP
- [x] **NEW FUNCTIONALITY** - The table will be populated with the entry that matches the case that the docket clerk uploaded a TCRP into
     - [x] **NEW FUNCTIONALITY** - The docket number for the case is displayed
     - [x] **NEW FUNCTIONALITY** - The Case title is displayed
     - [x] **NEW FUNCTIONALITY** - The page column is blank for now (page number data will be populated here once 9967 is implemented).



#### 6) Docket Clerk adds a TCRP document to a case, inputs a DIFFERENT filed date as in the test case above, but names the TCRP the SAME; New table for the TCRP is generated on the TCRP Hosting page.

- Log in as a docket clerk
- Take note of what you titled the TCRP documents and the specific filed date that you input from the previous test
- Navigate to a docket record of a different case
- Upload a TCRP
- Input a DIFFERENT filed date than you added in the previous test
- Be sure that the description for this TCRP is the SAME as the previous test
- Access the Pamphlet Hosting page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The TCRP hosting page displays a NEW table with the TCRP that you just uploaded.
- [x] **NEW FUNCTIONALITY** - The description of what you typed for the TCRP is displayed in the hyperlink
- [x] **NEW FUNCTIONALITY** - The Filed date matches what you input while uploading the TCRP
- [x] **NEW FUNCTIONALITY** - The table will be populated with the entry that matches the case that the docket clerk uploaded a TCRP into
     - [x] **NEW FUNCTIONALITY** - The docket number for the case is displayed
     - [x] **NEW FUNCTIONALITY** - The Case title is displayed
     - [x] **NEW FUNCTIONALITY** - The page column is blank for now (page number data will be populated here once 9967 is implemented).


#### 7) Docket Clerk adds a TCRP document to a case; Filed date is backdated to 2022; Appropriate Header is displayed on the Pamphlet hosting page.

- Log in as a Docket clerk
- Navigate to a case
- Click Upload PDF
- Add a Document and Description and then save
- Click add docket entry
- Select TCRP, and be sure that the filed date is from 2022 '
- Save the entry
- Navigate to the Pamphlet Hosting page

Expected Results:
- [x] **NEW FUNCTIONALITY** - Year Header displays above the table, and displays the appropriate year of filed date

*Repeat this test by back-dating a few TCRP document filed dates.  Year Header on the page should display the appropriate year.


#### 8) Docket Clerk strikes a TCRP document from the docket record of a case; Striken document no longer displays on the Pamphlet Hosting page.

- Log in as a docket clerk
- Navigate to one of the cases from above that you added a TCRP to
- Click Edit on the docket record for the TCRP document that you uploaded
- Click on Actions
- Click on the link to Strike the Entry
- Confirm the action, and ensure that the document is striken from the record.
- Access the Pamphlet hosting page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Case that you had striken the TCRP document no longer appears on this page.



#### 9) Public non-logged in users can view the pamphlet hosting page on a Mobile device; user can easily view and open pamphlet links to view documents.

- As a non-logged in user, navigate to the pamphlet hosting page link using a mobile device

Expected Results:
- [x] **NEW FUNCTIONALITY** - Data is displayed as per the mockup above (docket No., case, page (page number may not be present until story 9967 is deployed)
- [x] **NEW FUNCTIONALITY** - Pamphlet title wraps and displays in a manner that can be read by the user.
- [x] **NEW FUNCTIONALITY** - User can click on the link of the pamphlet document and document opens in a new tab for viewing.

*Be sure to test this on various Mobile devices with different screen sizes!

**Comment by mrinsin** [comment]
Some additional notes based on discussion with @cholly75 and @katiecissell 
- TCRPs are grouped based on a matching Filing Date. (The clerk uploading TCRP docket entries to cases will make sure to enter the same Filing Date and Description for TCRP docket entries referring to the same pamphlet)
- TCRP pdf link will open up the s3 document associated with the TCRP docket entry of the 1st case in the grouping after sorting has been applied
- Within each TCRP grouping, cases will follow an alphabetical sort order on the case caption for each result

**Comment by rosiehsmith** [comment]
After speaking to Holly on 4/3, we will be sorting by the first letter of the case caption in descending order (A-Z) rather than on primary petitioners last name/business name (update to third bullet above).

**Comment by cholly75** [comment]
Additional pamphlet for an example:[Uploading... Mar-June Pam Interactive Version.pdf]

**Comment by katiecissell** [comment]
A couple things noticed during UX Review:
Sealed cases are not letting you click their pamphlet link
Mobile- the highlight on hover does not stretch across certain tables.
The comma and petitioners language can be removed from the case descriptions.
Please align the header and the pamphlet link to the left to match the table and also align the filed date to the right

**Comment by mrinsin** [comment]
> Additional pamphlet for an example:[Uploading... Mar-June Pam Interactive Version.pdf]

It looks like this pamphlet did not get uploaded!

**Comment by ttlenard** [comment]
For testing, use this link for the pamphlet host page:

https://test.ef-cms.ustaxcourt.gov/opinion-pamphlets

**Comment by cholly75** [comment]
Closing - will revisit at a later time
