### ISSUE TITLE
Reporting: Judge Activity Report - Judge Selection

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8427]
As a member of the Court, so that I can compare and contrast judge activity on an as needed basis, I need to be able to run the report for any judge I choose.

Feedback on the judge activity report indicates a desire to be able to select any particular judge for which to run the report data. This will be useful when evaluating judge case inventory and scheduling judges for particular trial sessions and cases; this also provides the Chief Judge operational reporting on Court inventory and assignment.

Note: there is also desire to be able to run the report for ALL active judges; we will address in a separate story unless it makes sense to address this at the same time as this functionality.

## Acceptance Criteria
* A user running the judge activity report must specify the judge for which to run the report
* The judge activity report is run using the selected judge in combination with the date criteria to run the report
* The judge for whom the report was run is clearly displayed on the report
* The user can select a different judge and re-run the report

## Tasks
- [x] Add combo box selection for judges + functionality to select judge (https://github.com/flexion/ef-cms/pull/10053)
- [x]  Refactor capturing of request information for judges activitiy report to its own state (https://github.com/flexion/ef-cms/pull/10055)
- [x]  Update integration tests (https://github.com/flexion/ef-cms/pull/10059)
- [x] Aggregate opinions for all judges selection (https://github.com/flexion/ef-cms/pull/10067)
- [x] Aggregate cases closed for all judges selection (https://github.com/flexion/ef-cms/pull/10067)
- [x] Aggregate sessions held for all judges selection (https://github.com/flexion/ef-cms/pull/10067)
- [x] Aggregate orders for all judges selection (https://github.com/flexion/ef-cms/pull/10067)
- [x] Aggregate CAV/Submitted cases for all judges selection (https://github.com/flexion/ef-cms/pull/10067)
- [x]  UX - what should the header be for 'All' selection? (https://github.com/flexion/ef-cms/pull/10067)
- [x] Refactor state for judge selections to be an array  (https://github.com/flexion/ef-cms/pull/10067)
- [x]  Refactor JudgeActivityReportSearch entity to validate agains an array of judges selection; make it required!! (https://github.com/flexion/ef-cms/pull/10067)
- [x] Paginate the CAV/Submitted table (https://github.com/ustaxcourt/ef-cms/pull/3691)
- [x]  UX Feedback (Alignment issue after validation) (https://github.com/ustaxcourt/ef-cms/pull/3764)
- [x]  Convert endpoint to fetch orders and opinions to an async lambda

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**
- Add judge selector dropdown next to date range fields (use existing dropdown component)
- Spacing between end date component and judge selector is 40px or equivalent in relative measurement
- Judge should be pre-selected when user lands on the page
- Pre-selected judge should default to the logged in user's chambers (ex. Buch, Chief Judge, etc.)
- <s>Remove "Wells" from list of judges</s>
- Only include judges in the dropdown list (no option for "Select")
- End date picker: disable dates after current date (as implemented in [9723](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/9723))
- Figma file: https://www.figma.com/file/11G36whofPP6wYIqlDrpAD/USTC-%7C-Reports-%7C-Judges-activity-report-9980%2F9998?node-id=443%3A227&t=hNTDWRtOly3ZgEni-1

![Activity report - judge selector.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/488c0652-6d5b-4074-883a-a8643afd24ee)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user selects the activity report to run; Activity report page loads; A new Judge Selection box is present, default Judge displayed is the logged in user's chambers.

- Log in as a Judge
- Click on the Reports menu
- Select the Activity report

Expected Results:
- [x] Activity Report page loads
- [x] Header Displays the Report title as "Activity - Judges Name"
- [x] Start date and End date fields are present, but no data displays
- [x] **NEW FUNCTIONALITY** - The Default Judge in the Judge dropdown is the logged in users Judges Name
- [x] The Run Report button is present, but is greyed out
- [x] Empty report text at the bottom of the page that states, "Enter a date range to view activity"


#### 2) Judge user selects valid dates, keeps the default Judge and runs the report; Data is displayed appropriately.

- This is a Regression test
- Continuing from the previous test
- Input valid date fields (start date that is in the past, and an end date that is after the start date)
- Keep the default judge in the judge field.
- Click Run report

Expected results:
- [x] The Judges Name is displayed on the report
- [x] The Start/End dates that the report is run for is displayed
- [x] The date that the report was created is displayed
- [x] There is a Cases Closed Tile Displayed
     - [x] Cases closed is displayed with the total number
     - [x] Cases Closed-Dismissed is displayed with the total number
     - [x] Grand Total Number is displayed and is bolded
- [x] There is a Sessions Held Tile Displayed
     - [x] Small, Regular, and Hybrid sessions display the total number (each session is considered 1 session each)
     - [x] Small, Regular, and Hybrid sessions associated with a swing session display the total number (each session is considered .5 session each)
     - [x] Motion Hearing display total number - each session is considered .5 session each
     - [x] Special sessions display total number - each session is considered 1 session each
- [x] Orders Issued section is displayed with a grand total
     - [x] Table available that lists the Event Code, Order Type, and an Event Total
     - [x] Table is populated with the correct number of Orders by Order types that have been issued by the Judge
     - [x] The following Order types are NOT in the table:
          - [x]  OAJ, SPOS, SPTO, OST
- [x] Opinions Issued section is displayed with a grand total
     - [x] Table available that lists the Event Code, Opinion Type, and an Event Total
     - [x] Table is populated with the correct number of Orders by Opinion types that have been issued by the Judge
     - [x] The following Opinion types should be in the table (Judge may not have issued all these types, but they all need to be checked!):
          - [x] TCOP, MOP, SOP, OST 
- [x] The Submitted/CAV section is displayed and displays the cases appropriately.


#### 3) Judge user updates the Judge selection to a different judge; runs the report; data is displayed appropriately.

- Continuing from the previous test
- Input valid date fields (start date that is in the past, and an end date that is after the start date)
- Select a DIFFERENT Judge User
- Click Run report

Expected results:
- [x] **NEW FUNCTIONALITY** - The Judges Name that you selected from the dropdown list is displayed on the report
- [x] **NEW FUNCTIONALITY** - The Start/End dates that the report is run for is displayed
- [x] **NEW FUNCTIONALITY** - The date that the report was created is displayed
- [x] **NEW FUNCTIONALITY** - There is a Cases Closed Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Cases closed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Cases Closed-Dismissed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Grand Total Number is displayed and is bolded
- [x] **NEW FUNCTIONALITY** - There is a Sessions Held Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions display the total number (each session is considered 1 session each)
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions associated with a swing session display the total number (each session is considered .5 session each)
     - [x] **NEW FUNCTIONALITY** - Motion Hearing display the total number - each session is considered .5 session each
     - [x] **NEW FUNCTIONALITY** - Special sessions display the total number of sessions (each session is considered 1 session each)
- [x] **NEW FUNCTIONALITY** - Orders Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Order Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Order types that have been issued by the Judge
     - [x] **NEW FUNCTIONALITY** - The following Order types are NOT in the table:
          - [x] **NEW FUNCTIONALITY** - OAJ, SPOS, SPTO, OST
- [x] **NEW FUNCTIONALITY** - Opinions Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Opinion Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Opinion types that have been issued by the Judge
     - [x] **NEW FUNCTIONALITY** - The following Opinion types should be in the table (Judge may not have issued all these types, but they all need to be checked!):
          - [x] **NEW FUNCTIONALITY** - TCOP, MOP, SOP, OST   
- [x] **NEW FUNCTIONALITY** The Submitted/CAV section is displayed and displays the cases for the selected Judge appropriately.



#### 4) Judge user selects the option to run the report for all judges; data is displayed appropriately.

- This test case is dependent on dev discretion and whether or not the option to run this report for all judges was implemented with this story.
- Continuing from the previous test
- Input valid date fields (start date that is in the past, and an end date that is after the start date)
- Select the option for selecting all Judges
- Click Run report

Expected results:
- [x] **NEW FUNCTIONALITY** - Report header indicates that the report is for all judges
- [x] **NEW FUNCTIONALITY** - The Start/End dates that the report is run for is displayed
- [x] **NEW FUNCTIONALITY** - The date that the report was created is displayed
- [x} **NEW FUNCTIONALITY** - There is a Cases Closed Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Cases closed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Cases Closed-Dismissed is displayed with the total number
     - [x] **NEW FUNCTIONALITY** - Grand Total Number is displayed and is bolded
- [x] **NEW FUNCTIONALITY** - There is a Sessions Held Tile Displayed
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions display the total number (each session is considered 1 session each)
     - [x] **NEW FUNCTIONALITY** - Small, Regular, and Hybrid sessions associated with a swing session display the total number (each session is considered .5 session each)
     - [x] **NEW FUNCTIONALITY** - Motion Hearing display the total number - each session is considered .5 session each
     - [x] **NEW FUNCTIONALITY** - Special sessions display the total number of sessions (each session is considered 1 session each)
- [x] **NEW FUNCTIONALITY** - Orders Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Order Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Order types that have been issued by all Judges
     - [x] **NEW FUNCTIONALITY** - The following Order types are NOT in the table:
          - [x] **NEW FUNCTIONALITY** - OAJ, SPOS, SPTO, OST
- [x] **NEW FUNCTIONALITY** - Opinions Issued section is displayed with a grand total
     - [x] **NEW FUNCTIONALITY** - table available that lists the Event Code, Opinion Type, and an Event Total
     - [x] **NEW FUNCTIONALITY** - table is populated with the correct number of Orders by Opinion types that have been issued by all Judges
     - [x] **NEW FUNCTIONALITY** - The following Opinion types should be in the table (Judges may not have issued all these types, but they all need to be checked!):
          - [x] **NEW FUNCTIONALITY** - TCOP, MOP, SOP, OST   
- [x] **NEW FUNCTIONALITY** The Submitted/CAV section is displayed and displays the cases for all Judges appropriately.


#### 5) Regression tests

- [x] Attempt to run report with Invalid dates
- [x] Court Users besides Judge/CA do not have access to run the Activity report.


#### 6) Repeat test 1 - 5 with a Chambers user

- [ ] All tests pass with a Chambers user


#### 7) Docket closes a case, closes a case by issuing a dismissal order, and dockets an opinion for a Judge; Activity report reflects the updated numbers.

- Log in as a Judge or CA
- Click on Reports and select Activity
- Include today's date, select a Judge, and then click Run Report
- Take note of the values in the tables. (take a screen grab)

- Log in as a docket clerk
- Navigate to an open case assigned to the Judge user you selected
- Click on the Case information tab
- Update the case status to Closed
- Next, navigate to another open case assigned to the Judge
- Add an Order and Dismissal type of Order to the case's docket record so that the case status is Closed - Dismissed. (Be sure to select the Judge user you selected as the Judge issuing the Order.)
- Next, Navigate to another case
- Add an Opinion type of document to the case (be sure to select the judge user you selected as the Judge issuing the Opinion)

- Log in as a Judge or CA
- Click on Reports, and select Activity
- Include today's date, select the same Judge as earlier in the test, and click Run Report
- Compare the values in this report to the values in the report that you took a screen grab of previously

Expected Results:
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated Values in the Cases Closed tab to reflect the Closed case and the Closed - Dismissed Case
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated values in the Orders Issued table to reflect the Order of Dismissal Order you added to the docket record
- [x] **NEW FUNCTIONALITY** - The newly run report includes updated values in the Opinions Issued table to reflect the Opinion that you added to the Docket record.

**Comment by cholly75** [comment]
@Absolutestunna - received feedback on changing the title of the lower portion of the report from "Progress Information" to "Submitted/CAV Cases". Please advise on feasibility. Thank you!

**Comment by ttlenard** [comment]
@Absolutestunna @cruzjone-flexion 

Testing Feedback:

I notice that when I pull a report for All Judges, the Submitted/CAV Cases section isn't displaying all of the cases in that status.  In Test, I am seeing 53 total displayed.  If you calculate the total number of cases (including the cases that are in consolidated groups, I get a total of 104.  If you do a comparison with the Case inventory report, the Case inventory report totals 276 cases.

I did some spot checking, and when you run the report for All Judges, I see that only one CAV case is displayed in the results list.  If you pull a case inventory report for CAV cases, there are 23 total.  

For example, run a case inventory report for Cases in CAV for Judge Carluzzo. It will display a total of 5 CAV cases. 
Next, run an activity report for Judge Carluzzo, It will display a total of 5 CAV cases
Next, run an activity report for All Judges, It will only display one total CAV case, and this one is assigned to Judge Ashford (23887-13)

Need to be sure that when a user pulls the data for All Judges, all of CAV/Submitted cases are displayed appropriately. Not sure what is causing some of the Submitted/CAV cases to NOT display when All Judges is selected, but they do display when the individual judge is selected?

**Comment by ttlenard** [comment]
@Absolutestunna 

Testing Feedback:

Test case 3 - When I change the Judge user to run the report for a different Judge, the title of the report is updating to the new judge, making it appear that the new judge's data has already been run before I click run report.

Run an activity report, input in dates and select all judges, click run report. You get all the data...
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/7ac45ae9-a65d-49e8-bf34-1d74484fc122)

Next, change the judge in the Judge dropdown to someone else, forget to click run report.  The title of the report has changed to the other judge's name, but all the data remains in the "all Judges" state, making you think that Judge Ashford has closed 8000+ cases and held 198 sessions :slightly_smiling_face:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/00a32346-618e-4d32-9825-aed9132e6155)

**Comment by ttlenard** [comment]
@Absolutestunna @cruzjone-flexion 

Some more testing feedback. Let's plan on talking through this feedback when you are back in the office. Thanks!

I ran the Activity report for all judges, and then to compare numbers of Submitted/CAV cases, I also ran the Case inventory report.  The total number of cases on the Activity report for all Judges in Test was 270 cases, and the total number of Submitted/CAV cases from the Case inventory report was 276. There was a difference of 6 cases.

After diving in to the data a bit more, we've identified those 6 cases that are in the case inventory report, but not on the activity report. 
After doing this comparison, we've identified a few issues:

**Issue 1**
- Run a case inventory report for Judge Holmes.  You should see that there are 19 cases in Submitted status, 0 in CAV.
- Next, run an activity report for Judge Homes.  There will be 17 cases in total in submitted status. 
- We are missing two cases.
     - Docket number 21575-11 has a decision document (index 81) on the docket record (but it was vacated).  
          - Because of the rules we have attached to the activity report, this should be fine that we are not displaying this case at the moment.
     - Docket number 21903-19 has a Computation for Entry of Decision (index 22) on the docket record
          - This decision type document is not on the list of decision type documents to be excluded from story ustaxcourt/ef-cms#8547.
          - Why isn't case 21903-19 displayed in the Submitted/CAV section?
- The count on the Submitted/CAV cases section appears to be incorrect
     - The total count displays 11, but when you count the rows, there are only 10 rows.
     - Need to understand what the total count is counting.

**Issue 2**
- Run a case inventory report for Judge Kerrigan. You should see that there are 4 cases in Submitted status, 1 in CAV.
- Next, run an activity report for Judge Kerrigan. There will be 3 cases in Submitted, 1 in CAV, yet the total count displays 5.
- We are missing 1 case
     - Docket number 18336-19 has a decision document in the Drafts folder, not on the docket record.
     - Decision documents in drafts do not mean that there is a decision document on the docket record, and this case should still be counted.
     - Or, is the issue on this one with the OD document (index 17) that was filed?  OD is a decision document...
- The count on the Submitted/CAV cases section appears to be incorrect
     - Is it counting the case in submitted status that has the document in drafts?
     - Need to understand what the total count is counting

**Issue 3 - this one is actually ok - don't think we need to do anything with this, but we need to understand the count**
- Run a case inventory report for Judge Landy. You should see that there are 3 cases in Submitted, 1 in CAV
- Next, run an activity report form Judge Landy. There will be 3 cases in Submitted, but none in CAV.
- We are missing the CAV case
     - Docket number 6788-22 has a decision document (index 12) on the docket record (but it was vacated).
          - Because of the rules we have attached to the activity report, this should be fine that we are not displaying this case at the moment.
- Count
     - The count is correct on this one, so maybe it is counting the CAV status correctly, but not cases in submitted like above?
     - Need to understand what the total count is counting

**Issue 4 - this one is actually ok - don't think we need to do anything with this, but we need to understand the count**
- Run a case inventory report for Judge Pugh. You should see that there are 7 cases in Submitted, 0 in CAV
- Next, run an activity report for Judge Pugh. There will be 5 cases showing, total count appears to be correct.
- We are missing 2 cases
     - Docket number 1031-17 is the lead case in a consolidated group, has a decision document (index 31) on the docket record (but it was vacated).
          - Because of the rules we have attached to the activity report, this should be fine that we are not displaying this case at the moment.
     - Docket number 12485-17 is a member case, but it does NOT have a decision.  
          - Because of the grouping rules for consolidated cases, we are not displaying this one. I think this is OK.
- Count
     - The count on this one is correct, making this scenario strange because we thought it was counting cases in submitted status (see issues 1 and 2).
     - Need to understand what the total count is counting.

**Comment by ttlenard** [comment]
@Absolutestunna @jasonfu9966 All of the tests now pass + testing feedback comments appear to be resolved! Thank you!

**Comment by ttlenard** [comment]
@Absolutestunna @jasonfu9966 Test results for this round look good.

**Comment by mmarcotte** [comment]
- Opinions Issued are missing ones with 0
- Motion/Hearing calculation? 

  > Motion Hearing display the total number of weeks in session (each session is considered .5 session each)
  
  we are currently calculating the number of sessions divided by 2. we are not taking into account the number of weeks in session they are.

- Submitted/CAV cases is not filtering by judge

**Comment by ttlenard** [comment]
@Absolutestunna @jasonfu9966 Some testing feedback:

1 - Orders Issued Table - It would appear that only 10 rows of Order types are being displayed.  When there are more than 10 order types, some are not being displayed.  See screen grab, I ran a report for All Judges, and I do notice that the list is missing Order of Dismissal (and probably other types).  Note how the Total calculation does not match the total in the columns. Probably because we are missing some Order types?

2 - Orders Issued Table - Orders that are in Draft are currently being displayed and counted in the Orders issued.  I can confirm this is happening when viewing the report with a singular judge (see judge Ashford - There are draft orders in case 3702-20 that are appearing on the Activity report). We shouldn't be counting draft Orders. I did double check and this is NOT happening on Staging.

3 - Opinions Issued - Opinions that have been saved to the docket record, but not served are showing up in the Opinions Issued count. I did double check and this is NOT happening on Staging.

4 - Submitted/CAV Cases - These need to be listed with the cases with the Most days in status first and the cases with the least days in status last.  Right now, if you run the report for all judges, the first page looks good, but when you go to page 2, the cases aren't in this order. Page 1 ends at 7 days, but then page 2 starts with a case in 800+ days.

Screen grabs:
This one shows Mis-count with Orders Issued + a note about draft Opinions
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVU5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3218c630832a49649d247ef2897944d25798c11d/image.png)


This one shows how drafts are being displayed in the table
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVk5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3d3ed3616c218597eb0dfb07fabe476aa165a30e/image.png)


This one shows page 1 of the Submitted/CAV cases - pay attention to the days in status (ends at 7 days)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWM5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d3368029f9d323e70cab842e869c8a32662a36d9/image.png)


This one shows page 2. Pay attention to the days in status (starts at 870 days):
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWs5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bbcd84ec10eb19a24688bea5b88755d852f10b13/image.png)
