### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8444]
As a private practitioner, so that I am not associated with parties I am not representing, I need to be unable to multi-docket entry of appearance documents across a consolidated group.

Reviewing testing for consolidated multi-docketing by private practitioners, it has been decided that allowing PPs to multi-docket entry of appearance-type documents presents too much opportunity for unintended case/party association without implementing a high degree of complexity to solve the issue. Therefore, the Court would like to eliminate this functionality for the initial iteration of this feature.

## Acceptance Criteria
* Private Practitioners are not offered the ability to multi-docket EA docs (see list below in Notes) when e-filing in a consolidated case.
* Private Practitioners can still e-file and multi-docket all other types of documents not specifically prohibited from multi-docketing across consolidated cases

## Notes
* EA documents in scope for this story (these should *not* be multi-docketed):
  - ![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/40ad2564-6adf-441b-8f7a-7deb11dcb783)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner files an EA Type document on a case that is part of a consolidated group; The option to multi-docket the EA document is not available.

**Part 1**
- Log in as a Private Practitioner that is not associated with any cases that are part of a consolidated group
- In the case search box, enter a docket number of a case that is part of a consolidated group
- Click on the Request Access to Case button
- Select the Entry of Appearance document from the list
- Upload a document
- Select the Party that you are representing

Expected Results:
- [x] **NEW FUNCTIONALITY** There is no section for the Practitioner to select that they would like to file the EA document in all cases in the group.

**Part 2**
- Click review filing

Expected Results:
- [x] The Review Your Filing page does not display the Card for Cases the document will be filed in, and does not display the Card for Service Parties.

**Part 3**
- Click on the Submit Your Filing Button

Expected Results:
- [x] Green confirmation banner indicating that the document was filed and is accessible from the docket record.
- [x] The Print Receipt document only displays the Case Caption of the singular case that you filed the document to
- [x] The Print Receipt document only displays the docket number of the case you filed in and displays the appropriate document that you just filed.
- [x] The EA document that you just filed is only docketed on the case that you requested access to.
- [x] The EA document is not on the docket record for any other case in the consolidated group.

**Part 4**
- Repeat Parts 1-3 with all of the Entry of Appearance type of documents in the AC

- [x] Limited Entry of Appearance
- [x] Motion to Substitute Parties and Change Caption
- [x] Notice of Election to Intervene
- [x] Notice of Election to Participate
- [x] Notice of Intervention
- [x] Substitution of Counsel


#### 2) Private Practitioner that is associated with one case in a consolidated Group files and entry of appearance document on another case in the Group; The option to multi-docket the EA document is not available.

**Part 1**
- Continuing from the previous test
- From the case in the group that you now have access to, Click on the Case information tab
- Click on the docket number for a different case in the consolidated group that you are not associated with
- Click on the Request Access to Case Button.
- Select the Entry of Appearance document from the list
- Upload a document
- Select the Party that you are representing

Expected Results:
- [x] **NEW FUNCTIONALITY** There is **NOT** a section for the Practitioner to select that they would like to file the EA document in all cases in the group.

**Part 2**
- Click review filing

Expected Results:
- [x] The Review Your Filing page does **NOT** display the Card for Cases the document will be filed in, and does **NOT** display the Card for Service Parties.

**Part 3**
- Click on the Submit Your Filing Button

Expected Results:
- [x] Green confirmation banner indicating that the document was filed and is accessible from the docket record.
- [x] The Print Receipt document only displays the Case Caption of the singular case that you filed the document to
- [x] The Print Receipt document only displays the docket number of the case you filed in and displays the appropriate document that you just filed.
- [x] The EA document that you just filed is only docketed on the case that you requested access to.
- [x] After Clicking on the Case information tab, the Private practitioner is now listed as Counsel for the Petitioner(s) that were selected from Part 1 of this test.
- [x] The EA document is not on the docket record for any other case in the consolidated group.
- [x] The Practitioner is not listed as Counsel for any of the other petitioners in the Consolidated group

**Part 4**
- Repeat Parts 1-3 with all of the Entry of Appearance type of documents in the AC

- [x] Limited Entry of Appearance
- [x] Motion to Substitute Parties and Change Caption
- [x] Notice of Election to Intervene
- [x] Notice of Election to Participate
- [x] Notice of Intervention
- [x] Substitution of Counsel


#### 3) Private Practitioner attempts to efile an EA type document in a Sealed case that is part of a consolidated group that the Practitioner is already associated with; No Request Access to Case button is available.

- This is a regression test.  
- This test has some set up.
- As a Docket Clerk, navigate to the consolidated case group that you used for Test Cases 1 and 2.
- Seal one of the cases that the Private practitioner is not yet associated with (has not filed an EA type document on.)
- Log in as the Private Practitioner you used from test case 1 and 2
- Click on one of the docket numbers in the consolidated group of cases on your My cases page that you have access to
- Click on the Case information tab
- Click on the docket number of the case you just sealed as the docket clerk

Expected Results
- [x] The Case is sealed, but you still have access to view the docket record and case information tab
- [x] There is **NOT** a Request Access to Case button available on the Sealed case.



#### 4) Regression tests

- [x] 9598 - IRS Practitioners can still file EA type documents and be associated with cases across the consolidated group. 
- [x] 9874 - Private Practitioner efiling a document in a consolidated case
- [x] 9595 - Practitioner Visibility across Consolidated Group
- [x] Test with the FF off
