### ISSUE TITLE
Visibility Change for Amicus Briefs (AMBR)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8446]
As a friend of the court, so that the general public can read my contributions to a case, I need amicus briefs filed on or after 8/1/2023 to be viewable from the docket record to all users.

In an effort to increase transparency into the cases heard by the USTC, the Court is adopting a policy that all post-trial briefs filed by practitioners should be publicly available. This will be done on a prospective basis as of August 1, 2023 following a public notice in advance of this policy change.

Briefs filed prior to 8/1/23 will not be in scope, and cannot be retroactively made visible.

This will apply solely to select brief event codes filed by users with the Practitioner role in DAWSON at the time of filing **and** AMBR briefs (currently filed via paper only). Should the user transition to another role after filing, this will not affect the visibility of the brief.

As all practitioners are required to e-file unless exempted by the Court (an extremely rare occurrence) we are comfortable applying this policy to e-filed briefs and AMBR briefs only for now.

This story will address amicus briefs in specific.

## Pre-Conditions
Blocked until https://github.com/flexion/ef-cms/issues/9866 is completed

## Acceptance Criteria
* Amicus briefs (event code AMBR) filed on or after 8/1/2023 are visible to all users when viewing the docket record. This applies **only** to briefs filed on or after 8/1/2023; briefs filed prior to this date are not affected
* Sealed documents still obey sealing visibility rules, even when meeting the above criteria
* Lodged briefs are *never* available to the public 
* Stricken briefs are *never* available to the public

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Questions from pre-refinement:
- why does the public user want to read an amicus brief? A: they want to read everything so the court wants to be more transparent
- do these AMBR need to be searchable? A: No
- why the date of 8/1/2023? A: Clerk of the Court decision

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk files a paper Amicus Brief to a case and sets the filing date prior to 8/1/2023; document is not viewable for the public or other logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Add Paper Filing
- Upload a document, select a date prior to 8/1/2023 for the Date Received
- For Document Type, Select Amicus Brief
- Add in a description
- Add in a name for the "Who is filing this document?" field
- Click Save and Serve
- Click Yes Serve
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Ensure that there are parties associated with the case that you have a log in for (IRS, Private Practitioner, Petitioner)
- Take note of the docket number that you just filed the document in
- Log out of DAWSON as a docket clerk
- Next, Log in as one of the parties associated with the case
- Navigate to the case
- Review the docket record

Expected Results:
- [x] The Amicus document has a active hyperlink, and you can view the document.
 
*Repeat Part 1 with each party that is associated with the case

**Part 2**
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results:
- [x] The brief type document that was filed is not an active hyperlink, and can not be viewed by the public non-logged in user.


**Part 3**
- Log in as user that is **NOT** associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The brief type document that was filed does not have an active hyperlink, and can not be viewed by the logged in user that is not associated with the case.



#### 2) Docket Clerk files a paper Amicus Brief to a case and sets the date received for 8/1/2023; document is viewable for the public and other logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Add Paper Filing
- Upload a document, select 8/1/2023 for the Date Received
- For Document Type, Select Amicus Brief
- Add in a description
- Add in a name for the "Who is filing this document?" field
- Click Save and Serve
- Click Yes Serve
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Ensure that there are parties associated with the case that you have a log in for (IRS, Private Practitioner, Petitioner)
- Take note of the docket number that you just filed the document in
- Log out of DAWSON as a docket clerk
- Next, Log in as one of the parties associated with the case
- Navigate to the case
- Review the docket record

Expected Results:
- [x] The Amicus document has a active hyperlink, and you can view the document.
 
*Repeat Part 1 with each party that is associated with the case

**Part 2**
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results:
- [x] The brief type document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.


**Part 3**
- Log in as user that is **NOT** associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The brief type document that was filed does has an active hyperlink, and can be viewed by the logged in user that is not associated with the case.




#### 3) Docket Clerk files a paper Amicus Brief to a case and sets the date received for 8/2/2023; document is viewable for the public and other logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Add Paper Filing
- Upload a document, select 8/2/2023 for the Date Received
- For Document Type, Select Amicus Brief
- Add in a description
- Add in a name for the "Who is filing this document?" field
- Click Save and Serve
- Click Yes Serve
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Ensure that there are parties associated with the case that you have a log in for (IRS, Private Practitioner, Petitioner)
- Take note of the docket number that you just filed the document in
- Log out of DAWSON as a docket clerk
- Next, Log in as one of the parties associated with the case
- Navigate to the case
- Review the docket record

Expected Results:
- [x] The Amicus document has a active hyperlink, and you can view the document.
 
*Repeat Part 1 with each party that is associated with the case

**Part 2**
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results:
- [x] The brief type document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.


**Part 3**
- Log in as user that is **NOT** associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The brief type document that was filed does has an active hyperlink, and can be viewed by the logged in user that is not associated with the case.


#### 4) Legacy Amicus Brief documents filed prior to 8/1/2023 continue to NOT be available for viewing by the public or other logged in users not associated with the case.

- This is a regression test to ensure visibility of documents prior to 8/1 were not changed.

**Part 1**
- Navigate to DAWSON as a non-logged in user
- Search for a cases that have amicus brief documents filed on the case prior to this story

Expected Results:
- [x] Amicus Briefs on the docket record do not have an active hyperlink, and are not available to be viewed by the public user.

**Part 2**
- Log into DAWSON as a user (be sure to test with private practitioner, IRS practitioner, and petitioner)
- Navigate to cases that have amicus brief documents filed on the case prior to this story

Expected Results:
- [x] Amicus Briefs on the docket record do not have an active hyperlink, and are not available to be viewed by the logged in user.


#### 5) Docket clerk Seals (to the public) an Amicus brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or logged in users that are not associated with the case; Parties can still view the document.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the Amicus brief document that was filed on or after 8/1/23
- Select Seal to the Public
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The Amicus brief document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed amicus brief documents

Expected Results:
- [x] The amicus brief document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed amicus brief document(s)

Expected Results:
- [x] The amicus brief document(s) that was filed has a red lock icon next to the document title, it has an active hyperlink, and the document can still be viewed by the party that is associated with the case.


#### 6) Docket clerk Seals (to the public and parties to the case) a brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or parties to the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the amicus brief type documents that were filed on or after 8/1/23
- Select Seal to the Public and parties to the case
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The amicus brief document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed amicus brief documents

Expected Results:
- [x] The amicus brief document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed amicus brief document(s)

Expected Results:
- [x] The amicus brief document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the party that is associated with the case.


#### 7) Docket Clerk lodges a paper Amicus Brief to a case and sets the date received for on or after 8/1/2023; document is NOT viewable for the public or other logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Add Paper Filing
- Select the "Lodge" radio button
- Upload a document, select 8/1/2023 for the Date Received
- For Document Type, Select Amicus Brief
- Add in a description
- Add in a name for the "Who is filing this document?" field
- Click Save and Serve
- Click Yes Serve
- Ensure that the document is available on the docket record with "(LODGED)" in the document title, there is an active hyperlink, and you can view the document.
- Ensure that there are parties associated with the case that you have a log in for (IRS, Private Practitioner, Petitioner)
- Take note of the docket number that you just lodged the document in
- Log out of DAWSON as a docket clerk
- Next, Log in as one of the parties associated with the case
- Navigate to the case
- Review the docket record

Expected Results:
- [x] The lodged Amicus document has a active hyperlink, and you can view the document.
 
*Repeat Part 1 with each party that is associated with the case

**Part 2**
- As a public, non-logged in user, search for the case docket number you just lodged the document on.
- Review the docket record

Expected Results:
- [x] The lodged amicus brief document that was filed does NOT have an active hyperlink, and can NOT be viewed by the public non-logged in user.


**Part 3**
- Log in as user that is **NOT** associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just lodged the document on.
- Review the docket record.

Expected Results:
- [x] The amicus brief document that was filed does NOT have an active hyperlink, and can NOT be viewed by the logged in user that is not associated with the case.


**Part 4**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The lodged Amicus brief document that was filed is available as a hyperlink, and can be viewed by the logged in user.



#### 8) Docket Clerk edits the document metadata and removes the lodged status from the amicus brief; Brief has an active hyperlink and is available for viewing on the docket record to public users and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case that has the lodged brief document
- Click the edit link on the docket record for the lodged document
- Change the radio button to File, and then save.
- Ensure that the document has an active hyperlink and can be viewed
- Ensure that there are parties associated with the case that you have a log in for (IRS, Private Practitioner, Petitioner)
- Take note of the docket number that you just "de-lodged" the document in
- Log out of DAWSON as a docket clerk
- Next, Log in as one of the parties associated with the case
- Navigate to the case
- Review the docket record

Expected Results:
- [x] The Amicus document has a active hyperlink, and you can view the document.
 
*Repeat Part 1 with each party that is associated with the case

**Part 2**
- As a public, non-logged in user, search for the case docket number you just "de-lodged" the document on.
- Review the docket record

Expected Results:
- [x] The amicus brief document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.


**Part 3**
- Log in as user that is **NOT** associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just "de-lodged" the document on.
- Review the docket record.

Expected Results:
- [x] The amicus brief document that was filed has an active hyperlink, and can be viewed by the logged in user that is not associated with the case.


**Part 4**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The lodged Amicus brief document that was filed is available as a hyperlink, and can be viewed by the logged in user.


#### 9) Docket Clerk Strikes an Amicus Brief document that is on the docket record that was filed on or after 8/1/23, brief document is no longer available for viewing by the public or logged in users that are and are not associated with the case.

**Part 1**
- Log in as a docket clerk.
- Navigate to a case that has an amicus brief document that was filed on or after 8/1/23.
- Strike the document.
- Next, log in as a party associated with the case 
- Navigate to the case

Expected Results:
- [x] The stricken amicus brief document does not have a hyperlink, and cannot be viewed by the party.

*Repeat Part 1 with each party that is associated with the case

**Part 2**
- Next, as a public non-logged in user, search for the case with the stricken amicus brief document on the docket record

Expected Results:
- [x] The stricken amicus brief document does not have a hyperlink, and cannot be viewed by the non-logged in user.

**Part 3**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number with the stricken the brief document.
- Review the docket record.

Expected Results:
- [x] The stricken brief document does not have a hyperlink, and cannot be viewed by the logged in user.


#### 10) If a FF is implemented with this story, be sure to test with FF off.
