### ISSUE TITLE
Judge Activity Report: Roll-Up

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8447]
As the Chief Judge, so that I can easily understand the activities of the judges, I need to be able to query for a specific cohort of judges, and see their individual data in addition to an aggregate display.

When reviewing judge activity on a quarterly basis, the Chief Judge would like to see the stats and Submitted/CAV Cases for a particular group of judges (senior, STJ, regular). Ideally these judges' data are clearly labeled on the report in their own section, with an aggregate display of the statistics also available.

## Pre-Conditions
ustaxcourt/ef-cms#8427
ustaxcourt/ef-cms#8426

## Acceptance Criteria
* User can run the report for "All Special Trial Judges" and see the appropriate data for each individual judge in that group as well as an aggregate display for the statistics
* User can run the report for "All Regular Judges" and see the appropriate data for each individual judge in that group as well as an aggregate display for the statistics
* User can run the report for "All Senior Judges" and see the appropriate data for each individual judge in that group as well as an aggregate display for the statistics
* Report is optimized for best performance
* "Judge" is added as column to the Submitted/CAV data
* Columns sortable as per UX mock up
* No other changes to functionality for the report

## Notes
* Do we need to make "judge title" (e.g., STJ, senior) part of our judge data to facilitate this?
* Judge titles: https://ustaxcourt.gov/judges.html

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/fc5abffa-03fa-4f89-9a1a-b55c25494863)

## Tasks
- Add information on running "Senior Judge" script

## Questions
- Is the title of "Senior Judge" mutually exclusive with "Special Trial Judge"? Yes
- Who is considered a "regular judge", is the "chief judge" a regular judge? Everyone that is not a "senior" or "special trial judge" is a regular judge.
- What is the upper limit of Submitted/CAV cases that can exist in the system at any one time? 500 would be considered an extreme amount of Submitted/CAV cases
- Should 'Primary Issue' span more columns than in mockup?

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [x] experimental1
   - [x] experimental2
   - [x] experimental3
   - [x] experimental4
   - [x] experimental5

**Comment by swongCO** [comment]
Questions from pre-refinement:
Does the current judge title property already provide the grouping info?

**Comment by swongCO** [comment]
**UX Notes**

1. List the groups of judges from AC first in alphabetical order in the dropdown list
2. Add a Judge column to the CAV table after No. of Cases
3. Judge column is sortable
4. Days in Status column is sortable
5. Default sort is by Days in Status in descending order if no judge group is selected
6. If a judge group is selected, sort by judge in alphabetical order and for each judge, sort by days in status in descending order

![Activity report - judge grouping.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/21f421d4-b742-4847-8349-f2628f4f08ac)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge runs an Activity Report; New Judge selections are available in the Judge dropdown picklist.

- Log in as a Judge
- Click on the Reports Menu, and Select Activity
- Click on the Judge dropdown menu

Expected Results:
- [x]  **NEW FUNCTIONALITY** - Dropdown menu now has selections for "All Regular Judges"
- [x]  **NEW FUNCTIONALITY** - Dropdown menu now has selections for "All Senior Judges"
- [x]  **NEW FUNCTIONALITY** - Dropdown menu now has selections for "All Special Trial Judges"
- [x] Judges names are listed in alphabetical order



#### 2) Judge selects All Regular Judges from the dropdown picklist and runs the report; Results are correctly displayed for all regular judges.

- Continuing from the previous test
- Input valid dates and then select All Regular Judges from the Judge dropdown
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Cases Closed card displays all cases closed for regular judges only, in the date range selected.
- [x] **NEW FUNCTIONALITY** - The Sessions Held card displays all sessions held for regular judges only, in the date range selected.
- [x] **NEW FUNCTIONALITY** - The Orders Issued card displays all Orders Issued for regular judges only, in the date range selected.
- [ ] **NEW FUNCTIONALITY** - The Opinions Issued card displays all Opinions Issued for regular judges only, in the date range selected.
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV Cases section has a new Column header titled "Judge", and it has the Sort arrows.
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV Cases section now has sort arrows on the "Days in Status" column header.
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV Cases section displays all regular Judges that have cases in the CAV/Submitted Status.
- [x] **NEW FUNCTIONALITY** - The default Sort Order of the results in the Submitted/CAV cases section is by Days in Status in descending order.



#### 3) Judge sorts the Submitted/CAV section by the Judge Column; results sort appropriately

- Continuing from the previous test
- In the Submitted/CAV Cases section, click on the Judge Header in the column to sort

Expected Results:
- [x] **NEW FUNCTIONALITY** - The results in the Submitted/CAV Cases section are now sorted by Judge in alphabetical order.
- [x] **NEW FUNCTIONALITY** - Clicking on the Judge Header again re-sorts it so that the Judges in reverse alphabetical order.



#### 4) Judge sorts the Submitted/CAV section by the Days in Status Column; results sort appropriately

- Continuing from the previous test
- In the Submitted/CAV Cases section, click on the Days in Status Header in the column to sort

Expected Results:
- [x] **NEW FUNCTIONALITY** - The results in the Submitted/CAV Cases section are now sorted by Days in Status in Ascending Order
- [x] **NEW FUNCTIONALITY** - Clicking on the Days in Status Header again re-sorts it so that the Days in Status are in Descending Order


#### 5) Repeat Tests 1-4, but for Judge, be sure to select All Senior Judges and All Special Trial Judges.

Expected Results:
- [x] Tests 1-4 pass with the selection for All Senior Judges
- [x] Tests 1-4 pass with the selection for All Special Trial Judges



#### 6) Repeat tests 1 - 5 with a CA user

Expected Results:
- [x] Tests 1-5 pass when logged in as a CA user



#### 7) Regression test this report by picking other dates, All Judges, Individual Judges and reviewing results

Expected Results:
- [ ] All regression tests pass.

**Comment by swongCO** [comment]
**UX test feedback**

- No. of cases column show "0" for single cases - this should display as "1"
- <s>There are judges who have two versions of their names (one with title and one without):</s> The court is ok with the legacy data (judge with titles) displaying in the table as is

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fa5b69f61d7174860b44143e8204323d30ddd53/Screenshot%202023-10-04%20at%201.53.05%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU1HQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bf9ccd51b8ef6fa9f3810e3da5f81aca9d7c57a/Screenshot%202023-10-04%20at%201.53.19%20PM.png)

- <s>The "Judge" title is included when sorting by judge:</s>

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ccffe7841fc5a445afbf5eabb1a7fa9280ac18c/Screenshot%202023-10-04%20at%202.21.37%20PM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c11533e0830042f37fb6b3410bab22d6f4916b3/Screenshot%202023-10-04%20at%202.22.35%20PM.png)

- <s>When sorting by a single judge, the sorting is off due to the title in front of their name:</s>
 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHdHQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5824ff14aaedc20e9bc6e8cc7d91b6f5cb8d89f9/Screenshot%202023-10-04%20at%202.20.03%20PM.png)
