### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8448]
As a system administrator, so that I can remedy service emails that did not get sent to appropriate parties, I need to be alerted when messages are sent to the dead letter queue (DLQ).

With the implementation of multidocketing for external parties, we are increasing the potential number of service emails sent in any one particular filing. To make sure that service is completed, we need to address any service emails that fail to get sent and wind up in the DLQ. We would like for the system administrators to be proactively notified when this situation occurs so they can respond as quickly as possible.

## Acceptance Criteria
* Each time the DLQ receives one or more transactions, a notification is sent immediately to system administrator/devops engineers.
* System administrator/devops engineers can curate and modify the list of people receiving notifications

## Tasks
- [x] Set up a notification (system_health_alarms SNS topic) on an experimental env to go off when send_emails DLQ has item in it. Alarm is `send_emails_exp3_dl_queue_alarm`
  - [x] Add a Cloudwatch alarm for the `NumberOfMessagesSent` metric on the dl queue with a threshold of 0
  - [x] Notify SNS topic, `system_health_alarms`, when Cloudwatch alarm goes off by adding a subscription to the topic via email.
- [x] Set up throttling on that experimental via limiting max # messages on DLQ and verify that the notification gets triggered
- [x] The hard part: automate the setup of this notification on an env https://github.com/ustaxcourt/ef-cms/pull/3684

## Test Cases

1. Trigger an event that would cause a AWS to throttle our attempts to send Email via SES. We have done this in the past by filing and serving multiple documents across a large consolidated group. If we manually configure the maximum number of receives for messages in the queue to 1, then if a message fails to send during its initial attempt it should end up in the DLQ. 

    * At this point we should be able to confirm that the number of alerts sent matches the number of messages in the DLQ. 
    * Alerts should be sent to the `system_health_alarms` SNS Topic

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by mmarcotte** [comment]
NOTE: We already have an SNS Topic named `system_health_alarms` controlled in Terraform that is being to report on Cluster health. It would be preferable to use this as the target destination for the alerts.

**Comment by katiecissell** [comment]
Is there a better way to help this rather than relying on the dead letter queue?
Mike:What is our current retry strategy for things going into the dead letter queue for multi-docketing?

**Comment by mmarcotte** [comment]
@katiecissell -- sorry I missed your comment. 

**Is there a better way?** There often is a better way, but I would be scratching my head as to what that may be in this case. the DLQ is where messages go if they've exhausted their retries in the regular queue. It's just the way that the technology that we're using works. The most likely reason for this to happen is that AWS is having an outage, and all of our attempts to send Email are failing, and the DLQ would fill up with messages. Then we could wait for the outage to recover, and move all of those items back into the regular queue to be retried. Personally, I think the DLQ approach is really useful. What do you think?

Each item that goes into the queue is an individual attempt to send an Email. The strategy is to:

1. get notified
2. try to understand what went wrong

    * is it because the destination address is invalid somehow?
    * is there a service outage for SES (the service that sends Email at AWS)?
    * what the heck is going on?
    
* if we think the message should be retried, it would be straightforward, yet manual, to move the messages back into the regular queue for processing.
