### ISSUE TITLE
Visibility Change for Stipulated Decisions (SDEC)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8450]
As a member of the general public, so that I can read and understand how USTC interprets the law, I need decisions filed on or after 8/1/2023 to be viewable from the docket record to all users.

In an effort to increase transparency into the cases heard by the USTC, the Court is adopting a policy that all post-trial briefs filed by practitioners should be publicly available. This will be done on a prospective basis as of August 1, 2023 following a public notice in advance of this policy change.

Recently the decision was made to include most decision-type documents in this policy as well. As three of the decision documents (OAD/ODD/DEC) are already publicly available due to being Orders, this will affect one event code: Stipulated Decision (SDEC).

Proposed Stipulated Decisions (PSDE) are NOT in scope.

Stipulated Decisions filed prior to 8/1/23 will not be in scope, and cannot be retroactively made visible.

## Pre-Conditions
Blocked until https://github.com/flexion/ef-cms/issues/9866 is completed

## Acceptance Criteria
* Stipulated Decisions (event code SDEC) filed on or after 8/1/2023 are visible to all users when viewing the docket record. This applies **only** to Stipulated Decisions filed on or after 8/1/2023; stipulated decisions filed prior to this date are not affected
* Sealed documents still obey sealing visibility rules, even when meeting the above criteria 
* Stricken decisions are *never* available to the public

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Questions from pre-refinement: Should these be searchable?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk Saves and Serves a Stipulated Decision document to a case prior to 8/1/2023; document is not viewable for the public or other logged in users that are not associated with the case.

This test has some set up:

**Part 1**
- Log in as an IRS practitioner that has a case assigned to a judge user that you can log in with
- File a proposed stipulated decision on the case 
- Log in as a Docket Clerk
- Navigate to the case and QC the PSDE
- Log in as the Judge assigned to the case where the PSDE was filed
- Navigate to the Case with the PSDE
- Click on the document's hyperlink
- From the document view, click on Sign stipulated decision
- Sign the document
- Next, log in as a docket clerk
- Navigate to the Case with the draft Stipulated decision
- Click on the drafts folder
- Click on the Add Docket Entry link from the draft view
- Add the appropriate information on the add docket entry screen
- Save and serve the document. (This document needs to be added to the docket record on a date before 8/1/23)

Now the test is ready.
- Navigate to the case as a public non-logged in user

Expected Results:
- [x] The Stipulated Decision document that was filed is not an active hyperlink and cannot be viewed by the public non-logged in user.


**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Stipulated Decision document that was filed does not have an active hyperlink and cannot be viewed by the logged in user that is not associated with the case.

**Part 3**
- Log in as a Party on the Case (petitioner, private practitioner, IRS Practitioner)
- Click on the Docket record link for the case that the Stipulated Decision was filed in

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the party to the case as per normal.



#### 2) Docket Clerk Saves and Serves a Stipulated Decision document to a case on 8/1/2023; Stipulated Decision is available as an active hyperlink on the docket record and can be viewed by the public or other logged in users.

This test has some set up:

**Part 1**
- Log in as an IRS practitioner that has a case assigned to a judge user that you can log in with
- File a proposed stipulated decision on the case.
- Log in as a Docket Clerk
- Navigate to the case and QC the PSDE
- Log in as the Judge assigned to the case where the PSDE was filed
- Navigate to the Case with the PSDE
- Click on the document's hyperlink
- From the document view, click on Sign stipulated decision
- Sign the document
- Next, log in as a docket clerk
- Navigate to the Case with the draft Stipulated decision
- Click on the drafts folder
- Click on the Add Docket Entry link from the draft view
- Add the appropriate information on the add docket entry screen
- Save and serve the document. (Be sure that the filed date is 8/1/23). (Need Dev determination on how we will test this date)

Now the test is ready:
- Navigate to the case as a public non-logged in user

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the public non-logged in user.


**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the logged in user that is not associated with the case.

**Part 3**
- Log in as a Party on the Case (petitioner, private practitioner, IRS Practitioner)
- Click on the Docket record link for the case that the Stipulated Decision was filed in

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the party to the case as per normal.




#### 3) Docket Clerk Saves and Serves a Stipulated Decision document to a case on 8/2/2023; Stipulated Decision is available as an active hyperlink on the docket record and can be viewed by the public or other logged in users.

This test has some set up:

**Part 1**
- Log in as an IRS practitioner that has a case assigned to a judge user that you can log in with
- File a proposed stipulated decision on the case.
- Log in as a Docket Clerk
- Navigate to the case and QC the PSDE
- Log in as the Judge assigned to the case where the PSDE was filed
- Navigate to the Case with the PSDE
- Click on the document's hyperlink
- From the document view, click on Sign stipulated decision
- Sign the document
- Next, log in as a docket clerk
- Navigate to the Case with the draft Stipulated decision
- Click on the drafts folder
- Click on the Add Docket Entry link from the draft view
- Add the appropriate information on the add docket entry screen
- Save and serve the document. (Be sure that the filed date is 8/2/23). (Need Dev determination on how we will test this date)

Now the test is ready:
- Navigate to the case as a public non-logged in user

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the public non-logged in user.


**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the logged in user that is not associated with the case.

**Part 3**
- Log in as a Party on the Case (petitioner, private practitioner, IRS Practitioner)
- Click on the Docket record link for the case that the Stipulated Decision was filed in

Expected Results:
- [x] The Stipulated Decision document that was filed has an active hyperlink and can be viewed by the party to the case as per normal.


#### 4) Legacy Stipulated Decision-type documents filed prior to 8/1/2023 continue to NOT be available for viewing by the public or other logged in users not associated with the case.

- This is a regression test to ensure visibility of documents prior to 8/1 were not changed.

**Part 1**
- Navigate to DAWSON as a non-logged in user
- Search for a case that has stipulated decision documents filed on the case prior to this story.

Expected Results:
- [x] Stipulated Decisions on the docket record do not have an active hyperlink and are not available to be viewed by the public user.

**Part 2**
- Log into DAWSON as a user (be sure to test with private practitioner, IRS practitioner, and petitioner) that is not associated with the cases you will be searching for.
- Navigate to cases that have Stipulated Decision documents filed on the case prior to this story

Expected Results:
- [x] Stipulated Decisions on the docket record do not have an active hyperlink and are not available to be viewed by the logged in user.



#### 5) Docket clerk Seals (to the public) a Stipulated Decision document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or logged in users that are not associated with the case; Parties can still view the document.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the Stipulated Decision documents that were filed on or after 8/1/23
- Select Seal to the Public
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The Stipulated Decision document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed Stipulated Decision documents

Expected Results:
- [x] The Stipulated Decision document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed Stipulated Decision document(s)

Expected Results:
- [x] The Stipulated Decision document(s) that was filed has a red lock icon next to the document title, it has an active hyperlink, and the document can still be viewed by the party that is associated with the case.



#### 6) Docket clerk Seals (to the public and parties to the case) a Stipulated Decision type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or parties to the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the Stipulated Decision documents that were filed on or after 8/1/23
- Select Seal to the Public and parties to the case
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The Stipulated Decision document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed Stipulated Decision documents

Expected Results:
- [x] The Stipulated Decision document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed Stipulated decision document(s)

Expected Results:
- [x] The Stipulated Decision type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the party that is associated with the case.



#### 7) Docket Clerk Strikes a Stipulated Decision document that is on the docket record that was filed on or after 8/1/23, document is no longer available for viewing by public or logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk.
- Navigate to a case that has a Stipulated Decision type document that was filed on or after 8/1/23.
- Strike the document.
- Next, log in as a party on the case (petitioner, private practitioner, or IRS Practitioner)
- Navigate to the case

Expected Results:
- [x] The stricken Stipulated decision document does not have a hyperlink and cannot be viewed by the party.

**Part 2**
- Next, as a non-logged in user (public user), search for the case docket number for the case with the stricken Stipulated decision document on the docket record

Expected Results:
- [x] The stricken document does not have a hyperlink and cannot be viewed by the public user.

**Part 3**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number with the stricken the Stipulated decision document.
- Review the docket record.

Expected Results:
- [x] The stricken Stipulated decision document does not have a hyperlink and cannot be viewed by the logged in user.
