### ISSUE TITLE
Judge Activity Report: Display WIP Information for Submitted/CAV Cases

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8452]
As a judge, so that I can have visibility into the context of Submitted/CAV cases on the Activity Report, I need data entered in the Case Worksheet to appear on the Activity Report.

On the Case Worksheet, we provide a way for judges and CAs to add context around cases otherwise waiting for judicial action. As these cases are already reflected in the Activity Report, we would like to include this contextual information on the Activity Report as well.

## Pre-Conditions
ustaxcourt/ef-cms#8426

## Acceptance Criteria
* Information entered on the "Case Worksheet" for a given case (Primary Matter, Date Transitioned, Final Date for Briefs, Status of Matter) is also displayed for that case on the Activity Report in the Submitted/CAV Cases portion

## Sub-Tasks
- [x]  Combine `Opinions` and `Orders` aggregation endpoints into one endpoint (+ swagger docs update)
- [x] Pull in Mikes `consolidatedCasesGroupCountMap` refactor and clean up work
- [x] Pull in ustaxcourt/ef-cms#8426 story (and understand new refactor)
- [x] Display `statusOfMatter` and `final brief due date` on the CAV/Submitted Cases Table

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

Paginator component (not shown in mockup) - address functionality:
- Current functionality
  - scroll to the bottom of the table
  - click to the next page with the bottom paginator component
  - new page position remains at the bottom of the table
  - user has to manually scroll back up to the top of the table
- Desired functionality
  - scroll to the bottom of the table
  - click to the next page
  - new page position moves to the top paginator component
  - each page change will reposition to the top paginator component
  
Mockup - table column widths may not reflect actual  widths due to dynamic sizing of table components

![Activity report - import worksheet data.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/bfb1b3aa-3619-4d5f-947f-d57ac53fcc89)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge User adds data to their Submitted/CAV Cases Section from their Dashboard; Data entered displays on the Judges Activity Report.

- Log in as a Judge 
- From your dashboard, ensure that you have some cases listed in the Submitted/CAV section
- Be sure to add in some data in the Final Brief Due Date, Status of Matter, and the Primary Issue.
- Do this for at least one of the cases, but if you have more listed, add additional data for multiple cases.
- Next, click on reports and select Activity
- Select some dates, be sure that the Judge selection is the Judge you are logged in as
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV Cases section of the Activity report has the same columns as what is displayed on the Judges Dashboard
- [x] **NEW FUNCTIONALITY** - The data that you entered for each case on the Judges Dashboard is now displayed (read only) on the report.
- [x] **NEW FUNCTIONALITY** - There are no edit buttons or any abiltity to update the text from the report.


#### 2) Judge User makes an edit to the data on the Submitted/CAV Cases Section from their Dashboard; Changes made on the Judges dashboard are reflected on the Judges Activity Report.

- Continuing from the previous test
- Click on the Dashboard tab
- Update some of the data in the Submitted/CAV Cases Section
- Next, click on reports, and select Activity
- Select some dates, be sure that the Judge selection is the Judge you are logged in as
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The edits you just made are reflected on the Submitted/CAV Cases section.


#### 3) Judge user runs a report for a different judge, the data in the Submitted/CAV Cases section is displayed for that judge appropriately.

**Part 1**
- Log in as a differnet Judge than the one you were using from test cases 1-2.
- From your dashboard, ensure that you have some cases listed in the Submitted/CAV section
- Be sure to add in some data in the Final Brief Due Date, Status of Matter, and the Primary Issue.
- Do this for at least one of the cases, but if you have more listed, add additional data for multiple cases.
- Next, click on reports and select Activity
- Select some dates, be sure that the Judge selection is the Judge you are logged in as
- Click Run Report

Expected Results:
- [x] Data should be reflected in the Submitted/CAV Cases Section as described in test case 1

**Part 2**
- Next, On the top of the report, select the Judge user that you used for test case 1 and 2.
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - Judge users can see the data that other Judges input in their Submitted/CAV Cases section.

**Comment by ujahio** [comment]
Areas of Refactor to consider:
1. Combine endpoints.
2. Change the verb the a `get`. 

BEFORE:
```  
  app.post(
    '/judge-activity-report/opinions',
    lambdaWrapper(getCountOfOpinionsFiledByJudgeLambda),
  );
  app.post(
    '/judge-activity-report/orders',
    lambdaWrapper(getCountOfOrdersFiledByJudgeLambda),
  );
  ```
AFTER:
  ```
  app.get(
    '/case-documents/counts',
    lambdaWrapper(getCountOfCaseDocumentsFiledByJudgeLambda),
  );
  ```
  with the front end passing in the type of event codes to fetch (with a default to fetching all event codes).

**Comment by jhansen-flexion** [comment]
Reason this is blocked per Tom: This is dependent on 9995, which is still undergoing changes and needs the remaining 9998 work merged into it.
