### ISSUE TITLE
Calendar: Retrieve Paper Service

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8457]
As a calendar or petitions clerk, so that I can easily process paper service when I need to, I need to be able to retrieve generated paper service documents associated with the trial session.

When generating a large amount of paper service documents in service to a trial session, often there are times when a clerk would want to navigate to other areas of DAWSON rather than wait for the UI to return. Sometimes an error condition occurs that forces the clerk to refresh or close their page prior to being presented with paper service documentation. Sometimes there's an error in the printing itself, or we want to assign a different user the task of printing and mailing the paper service documentation.

In all these cases, it would be helpful to be able to retrieve the PDF documents presented to the user immediately after generation after the fact.

## Acceptance Criteria
* Petitions/calendar clerk can retrieve paper service PDF documents generated when setting a calendar on a trial session up to 3 days after initial PDF generation
* Petitions/calendar clerk can retrieve paper service PDF documents generated when editing a trial session up to 3 days after initial PDF generation
* Petitions/calendar clerk can retrieve paper service PDF documents generated when issuing the NOTT for a trial session up to 3 days after initial PDF generation

## Notes
* ~~The 3-day limitation is intended to be a minimum, not a maximum - if we can persist the retrieval mechanism indefinitely, that would be ideal.~~ After discussion with Chris, the decision was made to delete these documents after 3 days. Paper service documents aren't meant to live on forever in the same way that docket entry pdfs are so it makes sense they are eventually cleaned up. The TTL is relatively simple to change if we find users need access to those documents a little bit longer.

## Tasks
- [x] Persist paper service pdfs for 3 days, not 1 
- [x] UI bug where paper service pdfs is not updated after a change to the trial session
- [x] Unify trial session print paper to a single page instead of two. Do not need one for editing a trial session and for printing paper service after calendaring.
- [x] See if state.trialSessionId can be replaced with state.trialSession.trialSessionId
- [x] Add correct title for trial session paper service pdfs
- [x] Default browser behavior is to block more than 1 tab from opening at a time. Should we redesign how we open multiple documents?
- [x] everywhere getTrialSessionById be sure to add NotFound error checking
- [ ] write an integration test so that we can compare speed of cypress vs integration tests
- [x] check in a few days that https://app.test.ef-cms.ustaxcourt.gov/edit-trial-session/e6d4ac2f-d1ce-4234-9abc-8eb9798e8e25 no longer has the paper pdf links

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by katiecissell** [comment]
Pre-refinement questions:
- 30 day NOTT needs this too right?
- Is problem "They need to get back to PDF after generated" Or/and "I want to do other things while its processing things and sometimes things break and I can't get back"

**Comment by swongCO** [comment]
**UX Notes**

![Trial session - retrieve paper service.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/cfdb0e58-3e43-4d54-9ac2-cdc82e2e1920)
- on the Session Info page, add an icon link "Print Paper Service PDF" next to the print link
- the link will persist for 3 days after the initial pdf is generated
- update the Print link to "Print Session Information"
___
![Trial session - retrieve paper service modal.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/42128347-e485-427c-a672-a84588bb7ed9)
- when the link is clicked, a modal displays
- the document name will be displayed per naming conventions in Dawson (NOTE: .pdf extension can be removed in file name as that's not how it's stored in the system)
- for trial session edits, the document name will include the event that was changed (i.e. Notice of Change to Remote Proceeding)
- <s>when the primary btn is clicked, the user will be taken to a new tab with the pdf and the modal will disappear</s> each document is a link that will open in a new tab
- the pdf will display in accordance with existing paper service design
- if the pdf is unable to be displayed, show the generic error modal or the system error page
- **NEW** text in the primary btn says "Done", which will close the modal; there is no Cancel btn
___
![Trial session - retrieve paper service modal 2.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/598db003-bcf4-45e5-8ecb-18ccf74a204f)
- when there is more than one document, list each one <s>in a checkbox list</s> as a link
- each pdf will open in its own tab

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions/Calendar Clerk sets a calendar; Print Paper Service PDF link is available on the Session information screen for 3 days after setting the calendar. 

- Log in as a Petitions/Calendar Clerk
- Click on Trial Sessions
- Ensure that you have a Trial session ready for calendaring on the New tab
- Click Set Calendar
- Click Done on the Print for paper service page
- Navigate back to the Trial Session that you just calendared.

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a Print Paper Service PDF link now available in the upper right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - The Print link for printing the Session information page is now renamed to Print Session Information.
 


#### 2) Petitions/Calendar Clerk clicks on the Print Paper Service PDF link; Modal opens and displays the Document Name.

- Continuing from the previous test
- Click on the Print Paper Service PDF link

Expected Results:
- [x] **NEW FUNCTIONALITY** - A modal opens with text that matches what is in the mockup in the story.
- [x] **NEW FUNCTIONALITY** - Document name is reflected appropriately.



#### 3) Petitions/Calendar Clerk can Cancel out of the Modal; Clerk is returned to the Session information page.

- Continuing from the previous test
- Click on the Done button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The modal closes and the clerk is navigated back to the Session Information page



#### 4) Petitions/Calendar Clerk clicks on the Print Paper Service PDF link; Modal opens; Clerk can Close out of modal; Clerk is returned to the session information page.

- Continuing from the previous test
- Click on the Print Paper Service PDF again
- From the modal, Click on the Close link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The modal closes, and the clerk is navigated back to the Session Information page



#### 5) Petitions/Calendar Clerk clicks on the Print Paper Service PDF link; Modal opens; Clerk can Open the PDF.

- Continuing from the previous test
- Click on the Print Paper Service PDF link again
- From the modal, click on the PDF link

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new tab opens, and the Print paper service document is available for printing on a separate tab as it currently does with existing paper service design.
- [x] **NEW FUNCTIONALITY** - If the clerk navigates back to the Session information page, they can repeat this test again and another print paper service PDF can be available for printing.



#### 6) Petitions/Calendar Clerk updates an open trial session (In Person to remote), The Print paper service PDF link is available on the Session Information screen for 3 days after updating the Session.

- Log in as a Petitions/Calendar clerk
- Click on Trial Sessions
- Navigate to a trial session that is open, and is an In Person session.  
- Click on the Edit link
- Update the session from an In Person session, to a Remote session.
- Save the session
- Click done on the print paper service PDF
- Navigate back to the Trial Session that you just edited.

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a Print Paper Service PDF link now available in the upper right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - You can Click on the link and the modal displays the name of the document appropriately
- [x] **NEW FUNCTIONALITY** - Clicking the document link opens a new tab and the Print paper service document is available for printing on a separate tab as it currently does with existing paper service design.
- [x] **NEW FUNCTIONALITY** - Clicking Done will cancel out of the pop-up modal
- [x] **NEW FUNCTIONALITY** - Clicking close will close the pop-up modal



#### 7) Petitions/Calendar Clerk updates an open trial session (Remote to In Person), The Print paper service PDF link is available on the Session Information screen for 3 days after updating the Session.

- Log in as a Petitions/Calendar clerk
- Click on Trial Sessions
- Navigate to a trial session that is open, and is a Remote session.  
- Click on the Edit link
- Update the session from a Remote session, to an In Person session.
- Save the session
- Click done on the print paper service PDF
- Navigate back to the Trial Session that you just edited.

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a Print Paper Service PDF link now available in the upper right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - You can Click on the link and the modal displays the name of the document appropriately
- [x] **NEW FUNCTIONALITY** - Clicking the document link opens a new tab and the Print paper service document is available for printing on a separate tab as it currently does with existing paper service design.
- [x] **NEW FUNCTIONALITY** - Clicking Done will cancel out of the pop-up modal
- [x] **NEW FUNCTIONALITY** - Clicking close will close the pop-up modal



#### 8) Petitions/Calendar Clerk updates an open trial session (Change Trial Judge), The Print paper service PDF link is available on the Session Information screen for 3 days after updating the Session.

- Log in as a Petitions/Calendar clerk
- Click on Trial Sessions
- Navigate to a trial session that is open.  
- Click on the Edit link
- Update the session and change the Trial Judge
- Save the session
- Click done on the print paper service PDF
- Navigate back to the Trial Session that you just edited.

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a Print Paper Service PDF link now available in the upper right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - You can Click on the link and the modal displays the name of the document appropriately
- [x] **NEW FUNCTIONALITY** - Clicking the document link opens a new tab and the Print paper service document is available for printing on a separate tab as it currently does with existing paper service design.
- [x] **NEW FUNCTIONALITY** - Clicking Done will cancel out of the pop-up modal
- [x] **NEW FUNCTIONALITY** - Clicking close will close the pop-up modal



#### 9) Petitions/Calendar Clerk generates a 30 Day Notice of Trial on an open trial session, The Print paper service PDF link is available on the Session Information screen for 3 days after updating the Session.

- Log in as a Petitions/Calendar clerk
- Click on Trial Sessions
- Navigate to a trial session that is open and that has the clock icon indicating that the session is 30-35 days away
- From the Session information page, click on the Serve/Dismiss link, and Serve the 30 Day Notice
- Click Done on the Paper service screen
- Navigate back to the session

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a Print Paper Service PDF link now available in the upper right hand side of the screen.
- [x] **NEW FUNCTIONALITY** - You can Click on the link and the modal displays the name of the document appropriately
- [x] **NEW FUNCTIONALITY** - Clicking the document link opens a new tab and the Print paper service document is available for printing on a separate tab as it currently does with existing paper service design.
- [x] **NEW FUNCTIONALITY** - Clicking Done will cancel out of the pop-up modal
- [x] **NEW FUNCTIONALITY** - Clicking close will close the pop-up modal



#### 10) Petitions/Calendar Clerk clicks on the Print Paper Service PDF link for a Trial Session that has multiple print paper service PDF's (NOTT, NOT, Notice of Change, etc.); Modal displays the name of each Notice that is available for printing with a checkbox next to the document name.

- Log in as a Petitions/Calendar clerk
- Click on Trial Sessions
- Navigate to a trial session that is open and that has the clock icon indicating that the session is 30-35 days away
- Be sure that this trial session has also had an edit (change of trial judge, change from remote to in person, or change from in person to remote)
- Click on the Print Paper Service PDF link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The modal displays multiple documents that are available for printing
- [x] **NEW FUNCTIONALITY** - Each document that is displayed in the modal has a link as the document name.




#### 11) Petitions/Calendar Clerk selects all Print Paper Service PDF's from the modal; Each paper service PDF opens in separate tabs.

- Continuing from the previous test
- Click on each document link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Clicking the document link opens separate tabs for each of the documents and each tab has it displayed as it currently does with existing paper service design.



#### 12) Petitions/Calendar clerk accesses a Calendar Session that was set 4 days prior, Print Paper Service PDF link no longer displays.

- This test case has some set up
- Be sure that you have set a new calendar session and that it has been 3 days
- You should see the Print Paper Service PDF link.
- On the 4th day after you have calendared, navigate to the Trial Session

Expected Results:
- [ ] The Print Paper Service PDF link is no longer available.


#### 13) Petitions/Calendar clerk accesses a Calendar Session that was updated (In Person to Remote) 4 days prior, Print Paper Service PDF link no longer displays.

- This test case has some set up
- Be sure that you have edited the calendar session from In Person to Remote and that it has been 3 days
- You should see the Print Paper Service PDF link.
- On the 4th day after you have edited the trial session, navigate to the Trial Session

Expected Results:
- [ ] The Print Paper Service PDF link is no longer available.


#### 14) Petitions/Calendar clerk accesses a Calendar Session that was updated (Remote to In Person) 4 days prior, Print Paper Service PDF link no longer displays.

- This test case has some set up
- Be sure that you have edited the calendar session from Remote to In Person and that it has been 3 days
- You should see the Print Paper Service PDF link.
- On the 4th day after you have edited the trial session, navigate to the Trial Session

Expected Results:
- [ ] The Print Paper Service PDF link is no longer available.


#### 15) Petitions/Calendar clerk accesses a Calendar Session that was updated (Change of Trial Judge) 4 days prior, Print Paper Service PDF link no longer displays.

- This test case has some set up
- Be sure that you have edited the calendar session's Judge and that it has been 3 days
- You should see the Print Paper Service PDF link.
- On the 4th day after you have edited the trial session, navigate to the Trial Session

Expected Results:
- [ ] The Print Paper Service PDF link is no longer available.


#### 16) Print Paper Service PDF link is only available for Petitions/Calendar clerk, Case Services Supervisor, and Clerk of the Court

- Log in as various Court Users
- Click on a trial Session that would have the Print Paper Service PDF link.

Expected Results:
- [x] Print Paper Service PDF link is available for Petitions/Calendar Clerk
- [x] Print Paper Service PDF Link is available for Case Services Supervisor
- [x] Print Paper Service PDF link is available for Clerk of the Court
- [x] Print Paper Service PDF Link is NOT available for any other Court user (ADC, Docket, Judges, CA's, etc.)

**Comment by rachelschneiderman** [comment]
From @cholly75: paper service document created when trial session is calendared can be referred to as `Initial Calendaring`

**Comment by swongCO** [comment]
Feedback from Case Services meeting: trial session changes are singular so to prevent confusion and future proof this, the title of the document should include the event that was changed. UX notes updated to reflect this.

There are 4 types of changes that will generate a notice. Two of them (change of trial judge, change of proceeding type (remote or in person)) will automatically generate a notice. The other two (change of trial location, change of trial date) will have notices created manually.

The auto generated notices are titled:
- Notice of Change of Trial Judge
- Notice of Change to In Person Proceeding
- Notice of Change to Remote Proceeding

The manually created notices will take on whatever name is entered when it's created.

**Comment by swongCO** [comment]
UX review feedback
Found a bug in the modal - if the primary btn is clicked without selecting a document, a 404 error occurs. To address this, we made each document a link that will open a pdf in a separate tab. UX notes updated accordingly.

**Comment by swongCO** [comment]
UX review feedback
Minor spacing adjustment - reduce spacing between the body text and pdf list; use the consolidation modal as a reference for spacing between elements:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGl2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--780d6af602839f37a5ef78a59e9ae7f1d0fddef0/Screenshot%202023-11-07%20at%209.11.06%20AM.png)
___
Currently in test:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF2QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c708ac1c3b72a8ce6b288e4a22c09650ccc536b/Screenshot%202023-11-07%20at%209.06.44%20AM.png)

**Comment by ttlenard** [comment]
Testing Feedback:

Looks like if you have multiple tabs open it will generate an individual paper service PDF link for each tab open.

Per Cody: The websocket event gets sent to all tabs and the socket router generates the paper pdf on each event. We should only send the event to the tab who started the process I'd think.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhBQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f88af7b46bc9005c5feecfd7155b307ad6766b6/image.png)

**Comment by ttlenard** [comment]
Testing feedback:

1. Test Case 16 - Trial Clerks currently have access to the link (not a showstopper. Chris did mention that we could fix this later).
2. Noticed an issue when you have multiple tabs open and you serve a 30 day notice of trial, and it has a print for paper service PDF, any additional tab that you have open will get an error 404 on it.  I talked with Cody about this and he said that it is an issue with the Websockets (probably exists in prod today).  Talked with Chris as well and we will address this in a separate bug.

**Comment by ttlenard** [comment]
Updated Testing feedback

Issue 1 from above has now been fixed. Thanks @codyseibert.
