### ISSUE TITLE
BUG: "Coming Soon" text next to Order and Opinion Search tabs flashes briefly upon initial load of DAWSON home page

### ISSUE THREAD

**Issue by ttlenard** [ustaxcourt/ef-cms#8459]
**Describe the Bug**
When you first load the DAWSON home page, the Coming soon text flashes next to the Order and Opinion tabs.  It is extremely fast, but the text does show.  

**Business Impact/Reason for Severity**
Low

**In which environment did you see this bug?**
Prod, Test

**Who were you logged in as?**
Not logged in, public user

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application

**To Reproduce**
1. Navigate to the DAWSON url (https://dawson.ustaxcourt.gov/ or https://test.ef-cms.ustaxcourt.gov/)
2. Keep a close eye on the homepage.
3. Notice that the "Coming Soon" text flashes for Order and Opinion Search tabs
4. If you missed it the first time, just refresh your screen and pay attention.  It will flash very quickly.

**Expected Behavior**
Coming soon text should not display

**Actual Behavior**
A clear and concise description of what actually happened.
Coming Soon text flashes briefly

**Screenshots**

I was able to print the screen during the flash to capture what the text says on initial load of the page:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/2bfee2de-df64-41f8-95e4-9ac24b9c9012)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Tasks
- [x] Remove order & opinion search checks in featureFlagHelper
- [x] Remove order & opinion search 'Coming Soon' labels in .tsx
- [x] Remove feature flags: INTERNAL_ORDER_SEARCH, EXTERNAL_ORDER_SEARCH, INTERNAL_OPINION_SEARCH, EXTERNAL_OPINION_SEARCH
- [x] Add a script to set those feature flags to true if they aren't - verified with Holly that removing these feature flags was okay since advanced search has been released for a while
- [x] Verify the rate limiter is still working as expected with the removed flags above
- [x] Remove get/set of feature flag in sequences

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by rosiehsmith** [comment]
For cleanup, remove the 4 previous feature flags that enabled order/opinion search with the script:
`ENV=exp1 ./delete-order-and-opinion-search-feature-flags.sh` 

With this fix we're just removing those feature flags and by default that these features are turned on.
