### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8462]
As a Court user, so that I can easily access case documentation outside of DAWSON, I want to be able to download multiple docket entry documents at a time.

We have had requests from Court users who for one reason or another need or want to download some or all of the docket entries on a particular case. Reference during a meeting/trial, law clerks doing research, or to forward to other Courts (ex. appellate courts) are all potential situations where it would be useful to be able to do so.

Currently, the user can drill into each individual docket entry and save it, but if many files are needed this can be cumbersome. 

We would like to give Court users the ability to view the docket record, select the entries they wish to download the files for, and then execute said download.

## Acceptance Criteria
* Court user can indicate which docket entries they would like to download
* Court user can easily indicate that they want to download all docket record entries
* Court user can choose to include the printable version of the docket record with their document download
* Court user can download selected docket entries together into a compressed file
  - Compressed filename is [DocketNumber], [Petitioner]
  - Docket filenames are created according to the same syntax/process currently used in the Download All Case Files mechanism used by judges
  - Stricken documents have "STRICKEN_" prepended to the beginning of the filename
  - Sealed documents are stored in a separate folder inside the compressed file
* Minute entries/entries without a document association cannot be downloaded or selected for download

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- are the files to be downloaded as one big file or individual files? preference to keep it as it in one compressed file
- please clarify third AC (user can print from the downloaded pdf) include printable docket record with downloaded file
- what is the difference between the printable version and the downloaded version? it's the same; printable version is the docket record - see trial session download

**Comment by katiecissell** [comment]
UX Notes:

[Figma file](https://www.figma.com/file/veLMwnemIJDcH1VUbxFoWU/Download-Docket-Entries-%7C-10068?type=design&node-id=46%3A6169&mode=design&t=vvUnacetBTntXl2U-1)

For court users, add a new column of checkboxes to the left of the docket index. Also add a checkbox to the top of the column that will select/deselect all checkboxes. There should be three states for the header checkbox: checked, unchecked, indeterminate (where one or more box is checked but not all). A new Download link with the <i class="fas fa-cloud-download-alt"></i> icon should be added to the right of the "Printable docket record' link. When a checkbox is selected, enable the download option as a link.

<img width="1163" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDg4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fa4aa8720acdb0cfad9fea467473c157d06b6b0c/image.png" alt="image.png" />

<img width="1137" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXc3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51b26d454496145965e8ba9a97f6834584890397/image.png" alt="image.png" />

When the download button is clicked, display a modal. It should say how many entries were selected. The user should also have the option to include the printable docket record. Default is unchecked.
<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkU3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a1381864c20a9ea756e4a8d74a48ad50ba2d8614/image.png" alt="image.png" />

After the user selects to download, use the progress bar that we use for downloading all cases. The wording for downloading docket entries and downloading all cases should be same. (Will have to update the downloading all cases wording). Engineers should please verify that we will need this banner and that it won't be a fast enough process we do not.
<img width="746" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlE3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7a0afb0303a742e15a316207b194bfc5069bb13/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user views the docket record for a case; New checkboxes are displayed on the docket record, and an inactive "Download" link is displayed.

- Log in an a Court User
- Navigate to a docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a checkbox displayed in the header row of the docket record on the far left side
- [x] **NEW FUNCTIONALITY** - There are now checkboxes on the far left of the docket reocrd for any document 
- [x] **NEW FUNCTIONALITY** - There is no checkbox available on the far left for minute entries.
- [x] **NEW FUNCTIONALITY** - There is a greyed out Download link that is displayed above the docket record to the right of the Printable docket record link.



#### 2) Court user checks the box in the header row of the docket record; All checkboxes are checked.

- Continuing from the previous test
- Check the box in the header row of the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - Every document on the docket record is selected.
- [x] **NEW FUNCTIONALITY** - The download link in the upper right is now an active link.



#### 3) Court User checks the box in the header row of the docket record after it has already been checked; All checkboxes are de-selected.

- Continuing from the previous test
- Check the box in the header row of the docket record

Expected Results
- [x] **NEW FUNCTIONALITY** - Every document on the docket record is de-selected.
- [x] **NEW FUNCTIONALITY** - The download link in the upper right is now an inactive link.



#### 4) Court user checks an individual checkbox on the docket record, User can check/uncheck the boxes; as soon as one checkbox is selected, the Download link is activated.

**Part 1**
- Continuing from the previous test
- Check the box for a single document on the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The singular document on the docket record has the Checkbox selected; no other checkboxes are selected.
- [x] **NEW FUNCTIONALITY** - The download link in the upper right is now an active link.

**Part 2**
- Uncheck the singular checkbox that you checked in part 1.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The singular document on the docket record has the checkbox de-selected.
- [x] **NEW FUNCTIONALITY** - The download link in the upper right is now an inactive link.


#### 5) Court User selects one checkbox, Clicks the Download link; Modal displays.

- Continuing from the previous test
- Check a singular checkbox on the docket record
- Click on the Download Link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal Displays (see mockup)
- [x] **NEW FUNCTIONALITY** - The Modal displays the correct number of docket entries selected (1).
- [x] **NEW FUNCTIONALITY** - The Modal includes a checkbox for the user to indicate if they would like to also include the printable docket record.
- [x] **NEW FUNCTIONALITY** - Clicking the close link in the upper right closes the modal
- [x] **NEW FUNCTIONALITY** - Clicking the Cancel link at the bottom of the modal closes the modal


#### 6) Court user clicks the Download button on the modal; the document selected is downloaded to a file on their computer.

**Part 1**
- Continuing from the previous test
- Be sure that there is one document selected
- Click on the Download Link
- Do not select the checkbox for the printable docket record.
- Click on the Download button on the modal

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Compressing Files" progress bar appears at the bottom of the page
- [x] **NEW FUNCTIONALITY** - The user is given the opportunity to indicate where they would like to download the file on their computer
- [x] **NEW FUNCTIONALITY** - Once the download completes, the user can navigate to the folder on their computer.
- [x] **NEW FUNCTIONALITY** - The compressed folder name is [DocketNumber], [Petitioner]
- [x] **NEW FUNCTIONALITY** - User can unzip the folder per usual steps
- [x] **NEW FUNCTIONALITY** - There is no printable docket record file in the folder
- [x] **NEW FUNCTIONALITY** - The Document filename is [date]_[index #]_[Document file name]
- [x] **NEW FUNCTIONALITY** - User can open the PDF and view the file.

**Part 2**
- Repeat the steps above, but this time check the box indicating that you would like to include the printable docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The folder that was downloaded includes everything above, but this time also includes the printable docket record as one of the documents that was downloaded.
- [x] **NEW FUNCTIONALITY** - The Document filename for the printable docket record is "0_Docket_Record"


#### 7) Court user selects multiple files to download; The documents selected are downloaded to a compressed file successfully.

**Part 1**
- Log in as a Court user
- Navigate to a case
- Check multiple checkboxes on the docket record
- Click on the Download Link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal Displays (see mockup)
- [x] **NEW FUNCTIONALITY** - The Modal displays the correct number of docket entries that you selected.
- [x] **NEW FUNCTIONALITY** - The Modal includes a checkbox for the user to indicate if they would like to also include the printable docket record.

**Part 2**
- Check the box to include the printable docket record
- Click Download

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Compressing Files" progress bar appears at the bottom of the page
- [x] **NEW FUNCTIONALITY** - The user is given the opportunity to indicate where they would like to download the file on their computer
- [x] **NEW FUNCTIONALITY** - Once the download completes, the user can navigate to the folder on their computer.
- [x] **NEW FUNCTIONALITY** - The compressed folder name is [DocketNumber], [Petitioner]
- [x] **NEW FUNCTIONALITY** - User can unzip the folder per usual steps
- [x] **NEW FUNCTIONALITY** - There is a printable docket record document
- [x] **NEW FUNCTIONALITY** - All documents that were selected on the docket record are in the folder
- [x] **NEW FUNCTIONALITY** - The Document filenames are [date]_[index #]_[Document file name]
- [x] **NEW FUNCTIONALITY** - User can open the PDFs and view the files.



#### 8) Court user checks the box to select all documents to download, All of the documents on the docket record are downloaded to a compressed file successfully.

**Part 1**
- Log in as a Court user
- Navigate to a case
- Check the checkbox on the header row on the docket record to select all documents
- Click on the Download Link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Modal Displays (see mockup)
- [x] **NEW FUNCTIONALITY** - The Modal displays the correct number of docket entries that were selected.
- [x] **NEW FUNCTIONALITY** - The Modal includes a checkbox for the user to indicate if they would like to also include the printable docket record.

**Part 2**
- Check the box to include the printable docket record
- Click Download

Expected Results:
- [x] **NEW FUNCTIONALITY** - The "Compressing Files" progress bar appears at the bottom of the page
- [x] **NEW FUNCTIONALITY** - The user is given the opportunity to indicate where they would like to download the file on their computer
- [x] **NEW FUNCTIONALITY** - Once the download completes, the user can navigate to the folder on their computer.
- [x] **NEW FUNCTIONALITY** - The compressed folder name is [DocketNumber], [Petitioner]
- [x] **NEW FUNCTIONALITY** - User can unzip the folder per usual steps
- [x] **NEW FUNCTIONALITY** - There is a printable docket record document
- [x] **NEW FUNCTIONALITY** - All documents that were selected on the docket record are in the folder
- [x] **NEW FUNCTIONALITY** - The Document filenames are [date]_[index #]_[Document file name]
- [x] **NEW FUNCTIONALITY** - User can open the PDFs and view the files.

**Part 3**
- Repeat the steps above with a case docket record that has ALOT of files and ALOT of BIG files (ex: Facebook case) to ensure that it downloads successfully.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Large docket records with large documents download successfully



#### 9) Court user downloads documents in a case that has sealed documents; Sealed documents display in a separate folder.

- Log in as a Court user
- Navigate to a case that has a few sealed documents
- Check the boxes on the docket record to download both sealed and unsealed documents
- Click the download link
- Select the printable docket record (or not)
- Click Download
- Select the location that you would like to download the documents to on your computer
- Review the contents of the folder

Expected Results:
- [x] **NEW FUNCTIONALITY** - Within the compressed folder, there is a subfolder for sealed documents.
- [x] **NEW FUNCTIONALITY** - The sealed documents that you selected are located in the subfolder.



#### 10) Court user downloads documents in a sealed case; All documents in the sealed case are displayed in a subfolder for sealed documents.

- Log in as a Court user
- Navigate to a sealed case
- Check the box to download all documents on the sealed case
- Click the download link
- Select the printable docket record (or not)
- Click Download
- Select the location that you would like to download the documents to on your computer
- Review the contents of the folder

Expected Results:
- [x] **NEW FUNCTIONALITY** - Within the compressed folder, there is a subfolder for sealed documents.
- [x] **NEW FUNCTIONALITY** - All documents on the sealed case that you selected are located in the subfolder.



#### 11) Court user downloads documents in a case where there are stricken documents; The Stricken documents that are downloaded are labeled appropriately.

**Part 1**
- Log in as a Court user
- Navigate to a case that has some documents on the docket record that are Stricken
- Check some of the boxes to download documents, making sure that you check the box for stricken and non-stricken documents.
- Click the download link
- Select the printable docket record (or not)
- Click Download
- Select the location that you would like to download the documents to on your computer
- Review the contents of the folder

Expected Results:
- [x] **NEW FUNCTIONALITY** - Within the compressed folder, the Stricken documents have "STRICKEN_" prepended to the document filename.

**Part 2**
- Repeat this steps above, but ensure that the Stricken document(s) that you select are also sealed.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Within the Sealed subfolder, the Stricken documents have "STRICKEN_" prepended to the document filename.


#### 12) Repeat each test above to ensure that all Court Users have the ability to download documents.

- [x] All court users can download documents appropriately



#### 12) Regression tests to ensure that External users do not have the ability to download docket entries

- [x] Petitioner
- [x] Intervenor
- [x] Participant
- [x] Private Practitioner
- [x] IRS Practitioner
- [x] Terminal User
- [x] Public User




#### 13) Dev Question - Per UX feedback, are we also changing the wording on the Judge's Session Copy Download all cases progress bar on this story?

- If yes:

Expected Results: 
- [x] **NEW FUNCTIONALITY** - When a Judge clicks on Download all Cases, the Compressing Files window that appears at the bottom of the screen displays "Compressing Files" instead of "Compressing Case Files"

**Comment by jasonfu9966** [comment]
test cases to add:
when multiple checkboxes are selected a filter is applied, the checkboxes should not clear, and the download button should show the correct number of documents selected *after* the filter was applied.
i.e. all documents are selected with one order (6), filter by order, then download should show 1 docket entry, and zip should have one file

**Comment by jasonfu9966** [comment]
Pre-existing bug found: the "printable docket record" button disappears right after sealing or unsealing a case. Refreshing the page makes the button reappear.

**Comment by ttlenard** [comment]
A Court user recommended testing with the following cases:

7671-17
9011-13

**Comment by jasonfu9966** [comment]
an important previously-unaccounted-for test case:
cases that are unserved don't allow printing the docket record. our batch downloader should not allow it to be included in the zip in that case. (or should it?)
edit: talked with Chris. we are okay leaving the option to print the docket record through the batch downloader, even if the "printable docket record" button does not show
