### ISSUE TITLE
BUG: Multi-docketing UI appears when serving Simultaneous e-filings in Lead case

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8469]
**Describe the Bug**
When a clerk goes to serve e-filed Simultaneous-type documents in the Lead case of a consolidated group, they are presented with the option to multi-docket it across the consolidated group. We do not currently otherwise allow docket to multi-docket for e-filed party documents, and so this UI should not be activated in this situation.

Note that all other e-filed documents that are *not* "Simultaneous" are immediately served when e-filed, and so this does not present as an issue with non-Simultaneous e-filed documents.

**Business Impact/Reason for Severity**
Docket clerks may think they can/should multidocket Simultaneous filings, leading to confusion and misnumbering of docket entries in the group. Note that parties will soon have the ability to correctly multidocket their own filings on 7/5, which may cause this behavior to be even more likely.

**In which environment did you see this bug?**
TEST, STG, PROD

**Who were you logged in as?**
Docket clerk

**What were you doing when you discovered this bug? (Using the application, demoing, smoke tests, testing other functionality, etc.)**
Using the application 

**To Reproduce**
1. Set up - Be sure that  multi-docketable-paper-filings FF is set to true.
2. Log in as a party that has access to the lead case that is part of a consolidated group
2. Click File a Document
3. File any "Simultaneous" type document (you can multi-docket or just file in lead case - doesn't matter)
4. Log in as a docket clerk
5. Click on Document QC/Section document QC
5. QC the filing (this doesn't serve it)
6. Next, click on the document title on the docket record
7. Click Serve from the Document Preview screen
8. Notice that you get the "Are you ready to initiate Service" pop up modal for serving paper filings
9. If you do end up mulit-docketing the document, you will notice some other strange behavior occurs. The coversheet shows the index number of only the lead case for ALL of the cases it get's filed on which ends up duplicating the index number on the member cases on the docket record. (see screen grabs)
10. If a docket clerk attempts to strike the entry, the document type reverts back to the ORIGINAL index number, and they cannot properly strike the entry. (see screen grabs)

**Expected Behavior**
The electronically filed simultaneous document was not a paper filing, so it should not get the multi-docketable paper filing pop-up modal when the docket clerk clicks the link to serve the document.  

**Actual Behavior**
A clear and concise description of what actually happened.
When a docket clerk is serving an electronically filed simultaneous type document, they are getting the multi-dockeable paper filing pop-up modal asking them if they want to serve it across the group. This modal shouldn't be showing up for these electronic filings.

**Screenshots**

This is a screen grab of when the docket clerk clicks serve on an electronically filed simultaneous type document.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/f2362cdc-af7c-4ca8-b9bf-b0aae8a4e2fc)

This a screen grab of the duplicated index numbers:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9e979440-a4d1-41eb-b12f-7abea78f89dc)

This is a screen grab of what the coversheet looks like:
Notice how the index number shows all of them at 213, which is not the case: 
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/39032995-665d-4cc2-9c49-bbe436e87c9c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Cause of Bug, If Known**

**Process for Logging a Bug:**
* Complete the above information
* Add a severity tag (Critical, High Severity, Medium Severity or Low Severity). See below for priority definition. 

**Severity Definition:**
* Critical Defect
Blocks entire system's or module’s functionality
No workarounds available
Testing cannot proceed further without bug being fixed.

* High-severity Defect
Affects key functionality of an application
There's a workaround, but not obvious or easy
App behaves in a way that is strongly different from the one stated in the requirements

* Medium-severity Defect
A minor function does not behave in a way stated in the requirements.
Workaround is available and easy

* Low-severity Defect
Mostly related to an application’s UI
Doesn't need a workaround, because it doesn't impact functionality

## Definition of Ready for Bugs(Created 10-4-21)
Definition used: A failure or flaw in the system which produces an incorrect or undesired result that deviates from the expected result or behavior. (Note: Expected results are use cases that have been documented in past user stories as acceptance criteria and test cases, and do not include strange behavior unrelated to use cases.)

The following criteria must be met in order for the development team to begin work on the bug.

The bug must:
 - Be focused on solving a user problem
 - Contain data for all fields in the bug template, so the team can pick it up and begin working immediately

Process: If the unexpected results are new use cases that have been identified, but not yet built, new acceptance criteria and test cases should be captured in a new user story and prioritized by the product owner. 

If the Court is not able to reproduce the bug, add the “Unable to reproduce” tag. This will provide visibility into the type of support that may be needed by the Court. In the event that the Court cannot reproduce the bug, the Court will work with Flexion to communicate what type of troubleshooting help may be needed.

## Tasks
- [x] Don't show the multi-docketing modal for Simultaneous documents on a lead case
- [x] Fix index on the simultaneous doc on the docket record
- [x] Fix how the coversheet prints the filed doc index
- [x] Fix docket numbers impacted by this? Docket entry index duplicated on coversheet, index on docket record is incorrect
- [ ] Look at changes made in https://github.com/ustaxcourt/ef-cms/pull/3745/files and update places that include checks for SIMULTANEOUS_DOCUMENT_EVENT_CODES to also check the documentTitle for the inclusion of `simultaneous` which covers the modified briefs and supplementary simultaneous docket entries mentioned in the feedback https://github.com/flexion/ef-cms/issues/10075#issuecomment-1638878600
- [ ] Find out why logs showing all docket numbers for simultaneous. Fix it possibly?

## Definition of Done (Updated 4-14-21)
**Product Owner**
 - [ ]  Bug fix has been validated in the Court's test environment

**Engineering**
 - [ ] Automated test scripts have been written
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Deployed to the Court's `test` environment if prod-like data is required. Otherwise, deployed to any `experimental` environment for review.

**Comment by cholly75** [comment]
Looks like we're now immediately serving e-filed documents with Simultaneous in the title if they are the "Target" documents of the initially selected document type (amended, supplement, reply, motion for leave to file, etc) - we should keep the same behavior today (do not automatically serve any document with the word "simultaneous" in the title).

Thanks,
Chris

**Comment by ttlenard** [comment]
Testing Feedback: @rosiehsmith 

- Still getting multi-docketing UI on non-standard docs (anything that points to something else) ex: Amended, Amendment to, Reply, Supplement to, Supplemental, redacted
- Still getting Multi-docketing UI when filing a motion for leave to file/motion for leave to file out of time and then on the simultaneous type doc that the motion was pointing to.
- When serving a regular simultaneous doc, when looking at the logs, I see a list of all the docket numbers in the group, but it was only served in one case. This seems inconsistent with how the logs report it when a singular case is selected on the multi-docketing UI (in this scenario it doesn't list any docket numbers)

**Comment by ttlenard** [comment]
@rosiehsmith @jasonfu9966 Here are some screen grabs of the log entries:

Here is a screen grab of what it looks like when I serve a generic simultaneous doc (not one of those Non-standard ones) in the Lead case. Notice how it lists all of the docket numbers here, even though I didn't serve it to all of those cases.  There is also the subjectCaseDocketNumber that shows what I assume is the case that it originated from???

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/1172e95a-e37a-45a8-8bf9-f6ff10f2dea6)


Here is a screen grab of what it looks like when I DO get the multi-docketing UI and select a singular case to serve a document to, rather than multi-docket.  The Docket Numbers portion is now empty, which I was interpreting that it was like this because it didn't get served across the group:

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/744de3fe-85d9-4473-910c-7d8662fd8e1a)

I was thinking that in the first scenario, when I served the "generic" simultaneous brief (not one with the non-standard stuff), that it would NOT be listing all those other docket numbers in the log entry.  

Am I incorrect in my assumptions?  Let me know, thanks!

-Tenille
