### ISSUE TITLE
Extend Visibility Changes to Amended/Supplemental/Redacted Briefs

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8470]
As a practitioner, so that changes to e-filed briefs are in line with our new policy around docket transparency, I need modified briefs e-filed on or after 8/1/2023 to be visible to everyone on the docket record.

In ustaxcourt/ef-cms#8530/#10037/#10045 we implemented new visibility rules for practitioner e-filed briefs on the docket record, making the documents visible to every external user. The Court has decided that we need to extend this functionality to follow-on versions of these documents, such as amended, supplemental, or redacted versions of these documents.

This story will address extending these visibility changes to a subset of "Non-Standard Scenario" e-filed document event codes that require the practitioner to link to an existing item on the docket record. If that _linked item_ is a brief e-filed by a practitioner _regardless of the original filing date_, then the  amended/redacted/supplemental document should be made visible to all users, sealed documents/cases excepted as usual.

Plainly: even if the linked brief would not normally be visible due to not meeting the criteria, the amended/redacted/supplemented version of that brief can be.

This should apply to the following event codes, provided the e-filer is a practitioner user at the time of filing on or after 8/1/23:

* AMAT
* ADMT
* REDC
* SPML
* SUPM

Please see notes on which particular event codes constitute "brief-type" documents in scope for this change.

## Pre-Conditions
ustaxcourt/ef-cms#8530/#10037/#10045

## Acceptance Criteria
* AMAT documents e-filed by practitioners on or after 8/1/23 that are linked to a document in scope is itself openly visible to all users
* ADMT documents e-filed by practitioners on or after 8/1/23 that are linked to a document in scope is itself openly visible to all users
* REDC documents e-filed by practitioners on or after 8/1/23 that are linked to a document in scope is itself openly visible to all users
* SPML documents e-filed by practitioners on or after 8/1/23 that are linked to a document in scope is itself openly visible to all users
* SUPM documents e-filed by practitioners on or after 8/1/23 that are linked to a document in scope is itself openly visible to all users 
*  Sealed documents or documents in sealed cases continue to obey standard visibility rules

## Notes
*Documents in scope as linked targets of the above event codes: AMBR and everything on this list:

![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/30da9575-ecc4-4f72-a00e-7a6a0c275ff8)

* Do not limit visibility of these documents for the Terminal User if they do not meet the AC - Terminal User behavior should remain the same
* Documents still must be served prior to being visible on the docket record to public
* Lodged documents are never available to the public
* Stricken documents are never available to the public
## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Practitioner e-files an Amended brief type document to a case prior to 8/1/2023; Amended Brief is not viewable for the public or other logged in users that are not associated with the case.

*Preconditions: There is already a Brief type of document filed on the docket record of a case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one the case from the my Cases Page where you have previously filed a brief type document.
- Click on the File a Document button.
- Select Amended and then select one of the existing brief documents that is already on the docket record (not a simultaneous type brief for this test) (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is 7/31/2023 or prior
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results:
- [x] The Amended brief type document that was filed is not an active hyperlink, and can not be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Amended brief type document that was filed does not have an active hyperlink, and can not be viewed by the logged in user that is not associated with the case.


**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document has an active hyperlink and can be viewed by the public terminal user.


#### 2) Practitioner e-files an Amended brief type document to a case on 8/1/2023; Amended brief is available as an active hyperlink on the docket record, and can be viewed by the public or other logged in users.

*Preconditions: There is already a Brief type of document filed on the docket record of a case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one the case from the my Cases Page where you have previously filed a brief type document.
- Click on the File a Document button.
- Select Amended and then select one of the existing brief documents that is already on the docket record (not a simultaneous type brief for this test) (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on 8/1/2023 
- Ensure that the amended document is available on the docket record, there is an active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] The Amended brief type document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Amended brief type document that was filed has an active hyperlink, and can be viewed by the logged in user that is not associated with the case.


**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document has an active hyperlink and can be viewed by the public terminal user.


#### 3) Practitioner e-files an amended brief type document to a case at a date after 8/1/2023; Amended brief is available as an active hyperlink on the docket record, and can be viewed by the public or other logged in users.

- Repeat test 2, but be sure that the filing date is after 8/1/23.

Expected Results
- [x] The amended brief type document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Amended brief type document that was filed has an active hyperlink, and can be viewed by the logged in user that is not associated with the case.


**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document has an active hyperlink and can be viewed by the public terminal user.


#### 4) Legacy Amended Brief-type documents filed prior to 8/1/2023 continue to NOT be available for viewing by the public or other logged in users not associated with the case.

- This is a regression test to ensure visibility of documents prior to 8/1 were not changed.

**Part 1**
- Navigate to DAWSON as a non-logged in user
- Search for a cases that have Amended brief type documents filed on the case prior to this story. (The Facebook case has quite a few)

Expected Results:
- [x] Amended Briefs on the docket record (simultaneous, seriatim, and amicus) do not have an active hyperlink, and are not available to be viewed by the public user.

**Part 2**
- Log into DAWSON as a user (be sure to test with private practitioner, IRS practitioner, and petitioner)
- Navigate to cases that have Amended brief type documents filed on the case prior to this story

Expected Results:
- [x] Amended Briefs on the docket record (simultaneous, seriatim, and amicus) do not have an active hyperlink, and are not available to be viewed by the logged in user.

**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document has an active hyperlink and can be viewed by the public terminal user.


#### 5) Docket clerk Seals (to the public) an Amended brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or logged in users that are not associated with the case; Parties can still view the document.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the Amended brief type documents that were filed on or after 8/1/23
- Select Seal to the Public
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed Amended brief documents

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed Amended brief document(s)

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it has an active hyperlink, and the document can still be viewed by the party that is associated with the case.


**Part 4**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document does NOT have an active hyperlink and cannot be viewed by the public terminal user.


#### 6) Docket clerk Seals (to the public and parties to the case) an Amended brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or parties to the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the Amended brief type documents that were filed on or after 8/1/23
- Select Seal to the Public and parties to the case
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed Amended brief documents

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed Amended brief document(s)

Expected Results:
- [x] The Amended brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the party that is associated with the case.

**Part 4**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Brief document does NOT have an active hyperlink and cannot be viewed by the public terminal user.



#### 7) Practitioner files an Amended Simultaneous type brief on or after 8/1/23, document does not have an active hyperlink, and is not available to be viewed by the public or logged in users that are not associated with the case.

*Preconditions: There is already a Simultaneous Brief type of document filed on the docket record of a case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one the case from the my Cases Page where you have previously filed a brief type document.
- Click on the File a Document button.
- Select Amended and then select a simultaneous brief type of document (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on or after 8/1/2023 
- Ensure that the document is available on the docket record, but there is not an active hyperlink, and you cannot view the document since it is not yet served.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON.
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] The Amended Simultaneous brief type document that was filed should not yet be available as a hyperlink, and cannot be viewed by the public non-logged in user, as it must manually be QC'd first by a docket clerk. 

**Part 2**
- Log in as a Practitioner or Petitioner that is not associated with the case
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Amended Simultaneous brief type document that was filed should not yet be available as a hyperlink, and cannot be viewed by the logged in user, as it must manually be QC'd first by a docket clerk. 

**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Simultaneous Brief document does NOT have an active hyperlink and cannot be viewed by the public terminal user.



#### 8) Docket Clerk Serves the Amended Simultaneous type brief; document now has an active hyperlink, and is available to be viewed by the public and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case from the previous test that you filed an Amended simultaneous brief.
- Click on the Amended Simultaneous brief document link and serve the document.
- Next, Navigate to the case as a non-logged in public user.

Expected Results:
- [x] The Amended Simultaneous brief type document that was filed has a hyperlink, and can now be viewed by the non-logged in public user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the Amended simultaneous document on.
- Review the docket record.

Expected Results:
- [x] The Amended Simultaneous brief type document that was filed has as a hyperlink, and can be viewed by the logged in user.

**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Simultaneous Brief document has an active hyperlink and can be viewed by the public terminal user.



#### 9) Docket Clerk adds a paper filed Amended Amicus Brief on or after 8/1/23 to the docket record; Amended Amicus brief has an active hyperlink, and is viewable to the public and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on Create, and select paper filing
- Upload a document
- Select Amended Amicus Brief as the document type and add it to the docket record
- Next, navigate to this case as a public non-logged in user

Expected Results:
- [x] The Amended Amicus brief document that was filed has an active hyperlink, and can be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The Amended Amicus brief type document that was filed has an active hyperlink, and can be viewed by the private practitioner that is not associated with the case.


**Part 3**
- Navigate to the docket record as the Public Terminal user

Expected Results:
- [x] The Amended Amicus Brief document has an active hyperlink and can be viewed by the public terminal user.



#### 10) Practitioner files a motion for leave to file or a motion for leave to file out of time, and selects an Amended brief document for the file they are requesting leave for on or after 8/1/23; lodged Amended brief document is not viewable to the public or logged in users that are not associated with the case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one the case from the my Cases Page where you have previously filed a brief type document.
- Click on the File a Document button.
- Select a motion for leave or Motion for leave to file out of time type of document.
- Select Amended and then select a brief type of document (Not a simultaneous doc).
- Upload the motion for leave PDF and the Amended brief document
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on or after 8/1/2023 
- Ensure that the document is available on the docket record, there is active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON.
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] The lodged Amended brief type document that was filed should not yet be available as a hyperlink, and cannot be viewed by the public non-logged in user. 

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the Amended document on.
- Review the docket record.

Expected Results:
- [x] The lodged Amended brief type document that was filed should not yet be available as a hyperlink, and cannot be viewed by the logged in user.

**Part 3**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The lodged Amended brief type document that was filed is available as a hyperlink, and can be viewed by the terminal user.



#### 11) Docket clerk QC's the motion and Amended brief from the previous test case; edits the document metadata and removes the lodged status from the Amended brief; Amended brief document has an active hyperlink and is available for viewing on the docket record to public users and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case that has the lodged Amended brief document
- QC the lodged document
- Click the edit link on the docket record for the lodged Amended document
- Change the radio button to File, and then save.
- Next, navigate to the case as public, non-logged in user

Expected Results:
- [x] The now un-lodged Amended brief type document that was filed is available as a hyperlink, and can be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The now un-lodged Amended brief type document that was filed has a hyperlink, and can be viewed by the logged in user.

**Part 3**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The now un-lodged Amended brief type document that was filed is available as a hyperlink, and can be viewed by the terminal user.



#### 12) Docket Clerk Strikes an Amended Brief document that is on the docket record that was filed on or after 8/1/23, brief document is no longer available for viewing by public or logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk.
- Navigate to a case that has an Amended brief type document that was filed on or after 8/1/23.
- Strike the document.
- Next, log in as the practitioner that filed the document
- Navigate to the case

Expected Results:
- [x] The stricken Amended brief document does not have a hyperlink, and cannot be viewed by the party.

**Part 2**
- Next, As a public non-logged in user, navigate to the case with the stricken Amended brief document on the docket record

Expected Results:
- [x] The stricken Amended brief document does not have a hyperlink, and cannot be viewed by the non-logged in user.

**Part 3**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number with the striken the brief document.
- Review the docket record.

Expected Results:
- [x] The striken brief document does not have a hyperlink, and cannot be viewed by the logged in user.


**Part 4**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The stricken Amended brief type document that was filed is NOT available as a hyperlink, and cannot be viewed by the Terminal in user.


#### 13) Repeat test cases 1 - 11 with a the IRS Practitioner role.

- [x] Test Case 1 passes with the IRS Practitioner
- [x] Test Case 2 passes with the IRS Practitioner
- [x] Test Case 3 passes with the IRS Practitioner
- [x] Test Case 4 passes with the IRS Practitioner
- [x] Test Case 5 passes with the IRS Practitioner
- [x] Test Case 6 passes with the IRS Practitioner
- [x] Test Case 7 passes with the IRS Practitioner
- [x] Test Case 8 passes with the IRS Practitioner
- [x] Test Case 9 passes with the IRS Practitioner
- [x] Test Case 10 passes with the IRS Practitioner
- [x] Test Case 11 passes with the IRS Practitioner
- [x] Test Case 12 passes with the IRS Practitioner



#### 14) Repeat Test cases 1 - 12, but instead of selecting Amended, choose the following document types. Also, be sure that you have been testing with different types of briefs, and not selecting the same document type each time.

- [x] Test Cases 1-12 pass with Amendment (ADMT) types of briefs
- [x] Test Cases 1-12 pass with Redacted (REDC) types of briefs
- [x] Test Cases 1-12 pass with Supplemental (SPML) types of briefs
- [x] Test Cases 1-12 pass with Supplement (SUPM) types of briefs


#### 15) Regression test to ensure that Amended, Amendment, Redacted, Supplement, Supplemental Briefs filed by Petitioners are NEVER visible to the public.

- [x] Petitioner filed Briefs (Refer to Notes in the Story), as well as Amended Briefs, Amendment Briefs, Redacted Briefs, Supplement Briefs, and Supplemental Briefs continue to not be available for viewing to the public, regardless of date.

**Comment by ttlenard** [comment]
Testing Feedback @jasonfu9966 @cruzjone-flexion 

Test case 1, part 2 is failing.  I set the date to 7/19 in dynamo, and looks like logged in users that are not associated with the case are able to view the brief documents prior to the "visibility date" that is set in dynamo.

**Comment by ttlenard** [comment]
@jasonfu9966 @cruzjone-flexion 

I just met with Jason and we did some additional testing, it appears that after changing the policy date, sometimes there is a delay in the new date becoming "activated".  Looks to be anywhere from 10-15 min, or sometimes it is immediate. This made it appear that the policy date changes weren't in effect, but I believe we just needed to wait for a bit for the dates to become activated.

Moving back to Review column

**Comment by ttlenard** [comment]
@jasonfu9966 @cruzjone-flexion

Testing Feedback
Test Case 9 is not passing.  I filed an amended and supplemental amicus brief document to case 3100-23 in Test after the visibility policy date, and these documents are not showing with an active hyperlink.

**Comment by ttlenard** [comment]
Just catching up on more testing feedback from the other day that we talked about after standup on 7/26.

I'm still not seeing documents linked appropriately for public users. Policy date is 7/19/23.  In this screen grab, the redacted brief at Index 24 was filed by respondent, and then Index 28 and 29 are amended/supplemental paper filed amicus briefs that should be visible. 

Also noticed that there are differences in what public logged in users that are not associated with the case see vs. public non-logged in users. These folks visibility should be the same.

![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/0cb65938-22a7-414f-995c-4dc5cc5000cb)

**Comment by ttlenard** [comment]
@Rachel Schneiderman @Cody Seibert @Zachary Rogers

**Testing Feedback**
 Chris and I tested this and we are comfortable with pushing it to Production. Note that paper filed amended/redacted/supplement amicus briefs were visible to the public (yay). Not sure if this was what you guys were expecting after all?  Also, we did find some regression issues with the visibility of ALL practitioner eFiled briefs (regular + the amended/redacted, etc) when they are multi-docketed.  Chris determined that we can get this addressed in a bug next week. I'll be working on getting that submitted on the board in the AM.
