### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8476]
As a judge, ADC or chambers administrator, so that I can quickly issue orders in response to status reports, I need a mechanism to quickly generate these orders based on a few selections.

One of the most common orders issued by the Court is an order in response to a status report from the parties. Generally, these are orders that set a time frame for parties to submit either a stipulated decision or another status report on where their case is at in terms of progress/discussion of the issues or any directives issued by the Court. As these orders often share a few common elements in the text used, we would like a mechanism to facilitate generation of these types of orders in a fashion similar to that used with stamp disposition to ensure uniformity and provide a quick way to create these.

## Acceptance Criteria
* When viewing a Status Report (RPT) in DAWSON from the Document View or Message, the SR Order workflow can be invoked
* This workflow displays options (see below) and a preview of the SR Order to be generated and saved as a Draft (a la Stamp Disposition)
* If the workflow is invoked from a Status Report that is the Lead case in a consolidated group, the user can indicate that all cases in the group should be added to the caption of the SR Order
* When invoked, the SR Order workflow presents the following options for the user. Selecting an option updates the SR Preview with the appropriate text (noted in the sample PDF attached to the story). At least ONE of these four options must be chosen before the SR Order can be generated and saved as a Draft
  - Formatting Rule: if a clause in the order is followed by another (i.e., more than one selection has been made in the UI) then the preceding clause should have "It is further" appended to the end of it prior to the paragraph break
* User can choose to save the document as previewed and generate a Draft for the case. Generated Draft behaves like a Draft in all respects (can be edited, deleted, signed, docketed, etc. based on the user viewing the document).
----------

 - **ORDER TYPE** (optional selection, can choose one of the below selections):
   - Status Report
   - Status Report/Stip Decision
 - Selection of one of the above options requires an additional selection for:
   - **DUE DATE** (required selection if ORDER TYPE has been selected, date picker)
 
-----------

  - **STRICKEN FROM TRIAL** (optional selection, check box)
  - If this option is chosen, then an option under **JURISDICTION** must also be chosen prior to generating/saving the order
----------

  - **JURISDICTION** (optional selection, can choose one of the below selections):
    - Restored
    - Retained

-----------
 
  - **ADDITIONAL TEXT** (optional, free text box, 140-160 char limit [in line with Stamp Disposition free text limit)

## Notes
[SR_Template.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2lSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1d34010863634cca16ce3bd38fbdc164c8154ff/SR_Template.pdf)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [x]  Is framed in business/user need, the value has been addressed.
- [x] Includes acceptance criteria
- [x] Has been refined
- [x] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- why does this one need a live preview if it's consistent every time? 
- to confirm, this is an order with the same event code as an order?

**Comment by katiecissell** [comment]
UX Notes

[Figma file](https://www.figma.com/file/CZSfLKgWwni0ROFrPUyJ1D/USTC-%7C-Generate-response-to-status-report-10102?type=design&node-id=68%3A419&mode=design&t=XN25Kc1VaomE0c2h-1)

When a judge, ADC or chambers administrator views a status report they can see an option to "Order Response". Icon is "edit"
<img width="1363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNExhQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0a06aeed439c0f4fcda0ea7e869853609097020b/image.png" alt="image.png" />

A Status Report Order Response page will appear. Options selected on the left should appear in the PDF preview on the right.
<img width="897" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFloQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2f8761e4ab35bd5a87538fb141533a0d477b81e1/image.png" alt="image.png" />

If it is the lead case in a consolidated group, additional options should appear at the top of the form and the docket numbers in the PDF preview respond according to which option is chosen (if needed). The default is all cases in this group.
<img width="1283" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOThnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--63729862dd105c777101f2a7b327118b9c315dbb/image.png" alt="image.png" />


Save draft does not enable until at least one option is chosen.
Clear all will clear all selections. (and disable save draft until at least one option is chosen.) 
Example of options chosen:
<img width="748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d84717d314bb3b8ed924685c540afdcc16558e97/image.png" alt="image.png" />



If an order type is chosen and no due date selected, a validation alert should appear.
<img width="928" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9oQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--147eff728bdb70c365c31beac110098acb750654/image.png" alt="image.png" />

If an order type is chosen and the due date is improperly formatted, a validation alert should appear.
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzRXQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c7f248cc86c401fa84f96891353b737522055570/image.png" alt="image.png" />


If case is stricken from trial session and no jurisdiction chosen then a validation alert should appear.
<img width="707" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNoQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77177ebb564b47028ff76ae284ed241443e074ae/image.png" alt="image.png" />



After the order is saved as a draft, it should behave like a typical order:
- the user can edit, delete, add a signature and view the full pdf
- red text above the preview pane should remain when the signature is required
- if the user clicks Edit, they'll be taken to the edit flow where they can edit.
- the default docket entry description of the order is 'Order'
<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0loQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--54ccc88a8b1a9e6408ed7475457c9ed18a74d0d9/image.png" alt="image.png" />


If the draft is saved, a green alert should appear (just like orders being saved).
<img width="1552" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhnQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cc3bb59d6ae6de9cd8a4f49d32ced587ba48359/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user previews a Status report from the docket record; New link is available at the top of the document preview pane that displays "Order Report"

- Log in as a Judge user
- Navigate to a case that has a Status Report on the docket record.
- Click on the Status report document link so that the document preview pane displays

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a new link at the top of the document preview pane that displays Order Report and there is an edit icon to the left of the text.



#### 2) Judge user clicks on the Order report link from the Document Preview panel; a new page displays and is titled Status Order Report.

- Continuing from the previous test
- Click on the Order Report link from the document preview panel
- Click on the Preview Draft button

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new page titled Status Order Report displays.
- [x] **NEW FUNCTIONALITY** - There is a document preview on the right - titled Order.
- [x] **NEW FUNCTIONALITY** - Document preview includes the correct case caption and Docket number of the case; Order is underlined, and has the beginning sentence of the Order already populated.
- [x] **NEW FUNCTIONALITY** - The date in the first sentence is the date that the Status report was filed by the party, the index number correctly displays the document index number on the docket record.
- [x] **NEW FUNCTIONALITY** - The left side of the screen has the options for selection, nothing is selected by default.
- [x] **NEW FUNCTIONALITY** - The Additional order text field is blank
~~- [x] **NEW FUNCTIONALITY** - The Docket entry description is defaulted to display "Order". User can delete the text or add additional text in this field. No text limit.~~
- [x] **NEW FUNCTIONALITY** - The Save as Draft button is active


#### 3) Judge user clicks the Cancel link at the bottom of the left side; User is navigated back to the document preview panel, and they are back to viewing the Status Report document.

- Continuing from the previous test
- Click the cancel link

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is navigated back to the previous screen - the document preview of the Status Report document. (Note: this only passes is the user is viewing the status report from a message, not from the docket record.  Per Chris Holly - this is ok.)



#### 4) Judge user clicks on Order Report link, selects Status Report radio button for Order type; Document preview displays Order text appropriately.

- Continuing from the previous test
- Click on the Order Report link
- Select Status Report radio button under Order Type
- Click on the Preview PDF button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document preview displays, "ORDERED that the parties shall file a further status report by" (there will not be any date displayed yet - since you did not add in a date)



#### 5) Judge user clicks the Save as Draft button; Receives validation error.

- Continuing from the previous test
- Be sure that you did not input a date in the Due date field
- Click Save as Draft

Expected Results:
- [x] **NEW FUNCTIONALITY** - User receives validation error that states "Due date is required for status reports and stipulated decisions", and the Due date field is highlighted red with "select due date" text in red below the field.



#### 6) Judge user adds an invalid date in the Due date field, Clicks Save as draft; User receives validation error.

- Continuing from the previous test
- Add in an invalid date - be sure to add in letters or an incorrect date format, as well as type in a date in the past

Expected Results:
- [x] **NEW FUNCTIONALITY** - "Invalid DateTime" is displayed on the document preview.
- [x] **NEW FUNCTIONALITY** - User receives appropriate validation error upon clicking Save as Draft - see mocks
- [x] **NEW FUNCTIONALITY** - User cannot select a date in the past with the calendar date picker (dates prior to today's date are greyed out).


#### 7) Judge user adds in a valid date in the Due Date field; Clicks Save as Draft; Draft Order is added to the drafts folder.

- Continuing from the previous test
- Input a valid date by either using the calendar picker, or typing in the date in the correct format
- Leave the rest of the fields as the default 
- Click Save as Draft button.

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed to the Apply Signature page
- [x] **NEW FUNCTIONALITY** - After clicking Skip Signature; User is routed to the drafts folder of the case
- [x] **NEW FUNCTIONALITY** - Green confirmation banner indicating that the Order was updated
- [x] **NEW FUNCTIONALITY** - Created date is today's date
- [x] **NEW FUNCTIONALITY** - Document title is "Order"
- [x] **NEW FUNCTIONALITY** - User has options to Edit, Delete, Apply Signature and View Full PDF
- [x] **NEW FUNCTIONALITY** - Red text in the top right that indicates Signature required for this document



#### 8) Judge user clicks the Edit link; User is navigated back to the Status Order Report page; data entered previously remains; User can make necessary edits.

**Part 1**
- Continuing from the previous test
- Click on the Edit link

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed back to the Status Order Report page
- [x] **NEW FUNCTIONALITY** - Data entered from the previous tests remains

**Part 2**
- Change the Order type from Status Report to Status Report or Stipulated Decision
- Update the date to a different date in the future
- Click on the Preview PDF button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document preview displays, "ORDERED that the parties shall file a status report or proposed stipulated decision by [updated date entered]"

~~**Part 3**~~
~~- Add in additional text in the Docket entry description text box~~

~~Expected Results:~~
~~- [x] The text at the top of the Document preview next to "Docket entry preview" displays the description text that you just added.~~

**Part 4**
- Click Save as Draft button

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed to the Apply Signature page
- [x] **NEW FUNCTIONALITY** - After clicking on the skip signature button; User is routed to the drafts folder of the case.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner indicating that the Order was updated.
- [x] **NEW FUNCTIONALITY** - Created date is today's date.
- [x] **NEW FUNCTIONALITY** - Document title is "Order".
- [x] **NEW FUNCTIONALITY** - User has options to Edit, Delete, Apply Signature and View Full PDF.
- [x] **NEW FUNCTIONALITY** - Red text in the top right that indicates Signature required for this document.
- [x] **NEW FUNCTIONALITY** - The draft document in the preview matches the document from the preview in the Status Order Report.



#### 9) Judge user adds a signature and saves the Order, Draft is saved appropriately

- Continuing from the previous test
- Click on the Add Signature link

Expected Results:
- [x] User can add in the Judge Signature as per normal/Delete signature/Go back to draft/Save Signature.
- [x] After signature is saved, the draft order is available in the Drafts folder
- [x] Green confirmation banner indicating Order updated.



#### 10) Judge user creates an Order Report as in the previous test cases, Does not select Order type, selects Jurisdiction and also add additional Order Text to the order based off of options in the left panel.

**Part 1**
- Log in as a Judge
- Navigate to a case that has a status report on the docket record
- Click on the document link for the status report
- Click on Order Report
- Do not select Status Report or Status Report or Stipulated Decision radio button or add a date in the future.
- Check the box next to Case is stricken from the trial session

Expected Results:
- [x] **NEW FUNCTIONALITY** - Text on the right side is added to the draft order, and states, "ORDERED that this case is stricken from the trail session."

**Part 2**
- Click the save as draft button without selecting any additional fields

Expected Results:
- [x] **NEW FUNCTIONALITY** - User receives validation error indicating that Jurisdiction is required since case is stricken from the trial session

**Part 3**
- Select Retained
- Click Preview PDF button

Expected Results
- [x] **NEW FUNCTIONALITY** - Text on the right side is added to the draft order, and states, "ORDERED that jurisdiction is retained by the undersigned." There is no "It is Further" at the end of this sentence if there isn't any text in the additional text field.

~~**Part 4**~~
~~- Add in the "Order title in the Docket entry description" text box~~

~~Expected Results:~~
~~- [x] The text at the top of the Document preview next to "Docket entry preview" displays the description text that you just added.~~

**Part 5**
- Click Save as Draft button

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed to the Apply Signature Page
- [x] **NEW FUNCTIONALITY** - After Clicking Skip Signature; User is routed to the drafts folder of the case.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner indicating that the Order was updated.
- [x] **NEW FUNCTIONALITY** - Created date is today's date.
- [x] **NEW FUNCTIONALITY** - Document title is "Order".
- [x] **NEW FUNCTIONALITY** - User has options to Edit, Delete, Apply Signature and View Full PDF.
- [x] **NEW FUNCTIONALITY** - Red text in the top right that indicates Signature required for this document.
- [x] **NEW FUNCTIONALITY** - The draft document in the preview matches the document from the preview in the Status Report Order Response.

**Part 6**
- Click on the edit link from the Draft folder
- From the Status Order Report page, you should see all of the previous data entered.
- Change the Jurisdiction by selecting the radio button to "Restored to the general docket"
- Click the Preview PDF button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Text on the right side is added to the draft order, and states, "ORDERED that this case is restored to the general docket." There is no "It is Further" at the end of this sentence if there isn't any text in the additional text field.

**Part 7**
- User types in some text in the Additional order text field.

Expected Results:
- [x] **NEW FUNCTIONALITY** - As the user types, the characters remaining counts down
- [x] **NEW FUNCTIONALITY** - After Clicking on the Preview PDF, the right-side document preview adds in "It is further" to the last line of text, and then "ORDERED that [whatever the user types in the additional order text].

**Part7**
- Click Save as Draft and take note of the document preview.

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed to the Apply Signature PAge
- [x] **NEW FUNCTIONALITY** - After clicking on the Skip Signature button; User is routed to the drafts folder of the case.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner indicating that the Order was updated.
- [x] **NEW FUNCTIONALITY** - Created date is today's date.
- [x] **NEW FUNCTIONALITY** - Document title is whatever you typed in the "Docket entry description" text box.
- [x] **NEW FUNCTIONALITY** - User has options to Edit, Delete, Apply Signature and View Full PDF.
- [x] **NEW FUNCTIONALITY** - Red text in the top right that indicates Signature required for this document.
- [x] **NEW FUNCTIONALITY** - The draft document in the preview matches the document from the preview in the Status Order Report (includes the jurisdiction and additional order text that was added in the previous tests.)



#### 11) Judge user creates an Order Report and selects an Order type; User cannot select a Jurisdiction if the checkbox for Case is stricken from the trial session isn't selected.

- Log in as a Judge user
- Navigate to a case that has a status report on the docket record.
- Click on the document link for the status report
- Click on Order Report link at the top of the document preview
- Select an Order type and add in a valid due date in the future.
- Attempt to select a radio button in the jurisdiction section

Expected Results:
- [x] **NEW FUNCTIONALITY** - User cannot select a Jurisdiction if the Checkbox above is not selected.



#### 12) Judge user creates an Order Report and selects only additional order text; User is not required to select any radio button in the order type, check the checkbox or add in a jurisdiction.

**Part 1**
- Log in as a Judge user
- Navigate to a case that has a status report on the docket record.
- Click on the document link for the status report
- Click on Order Report link at the top of the document preview
- Add in some additional order text
- Do not add in any text in the Docket entry description text box
- Click on the Preview PDF button

Expected Results
- [x] **NEW FUNCTIONALITY** - As soon as there is text added in the additional order text box, the right side document preview adds in whatever the user types in the additional order text.
- [x] **NEW FUNCTIONALITY** - Only 80 characters are allowed. Once the character limit is reached, no additional text is added when typing.		

**Part 2**
- Finish typing in the Additional Order Text
- User clicks Save as Draft

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is routed to the Apply Signature Page
- [x] **NEW FUNCTIONALITY** - After clicking on the Skip Signature button, User is routed to the drafts folder of the case.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner indicating that the Order was updated.
- [x] **NEW FUNCTIONALITY** - Created date is today's date.
- [x] **NEW FUNCTIONALITY** - Document title is "Order" 
- [x] **NEW FUNCTIONALITY** - User has options to Edit, Delete, Apply Signature and View Full PDF.
- [x] **NEW FUNCTIONALITY** - Red text in the top right that indicates Signature required for this document.
- [x] **NEW FUNCTIONALITY** - The draft document in the preview matches the document from the preview in the Status Order Report (does not include Order type, jurisdiction, but does include the additional order text that was added).



#### 13) Judge user creates an Order Report as in the previous test cases, user can clear all selected/added data.

- Log in as a Judge user
- Navigate to a case that has a status report on the docket record.
- Click on the document link for the status report
- Click on Order Report link at the top of the document preview
- Add in some data to all or some of the options
- Click the Clear All link

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the data that was input in the fields is cleared, no data is retained.
- [x] **NEW FUNCTIONALITY** - After clicking on the Preview PDF button, All of the data that was input on the document preview is cleared, with only the caption, Order title, and first sentence remaining.
~~- [x] **NEW FUNCTIONALITY** - The Save as Draft button is also disabled again.~~



#### 14) Judge user creates an Order Report in a lead case in a consolidated group; Additional option is present at the top of the page to select a single case or all cases in the group.

- Log in as a Judge user
- Navigate to a lead case in a consolidated group that has a status report on the docket record.
- Click on the document link for the status report
- Click on Order Report link at the top of the document preview

Expected Results:
- [x] **NEW FUNCTIONALITY** - A new page titled Status Order Report displays.
- [x] **NEW FUNCTIONALITY** - There is a document preview on the right - titled Order.
- [x] **NEW FUNCTIONALITY** - There is a section on the top of the Status Order Report page that indicates that the case is part of a consolidated group, with radio button selections. "All cases in this group" is selected by default.
- [x] **NEW FUNCTIONALITY** - After clicking on the Preview PDF button, the Document preview includes the correct case caption for all cases in the group (Lead case + ET AL.,) and Docket numbers of all cases in the group; Order is underlined, and has the beginning sentence of the Order already populated.
- [ ] **NEW FUNCTIONALITY** - The beginning sentence states, "On [date], a status report was filed in the lead case of the consolidated group (Index no. [index number of document]). For cause, it is"
- [x] **NEW FUNCTIONALITY** - The date in the first sentence is the date that the Status report was filed by the party, the index number correctly displays the document index number on the docket record of the lead case.
~~- [x] **NEW FUNCTIONALITY** - The Save as Draft button is not activated.~~
- [x] **NEW FUNCTIONALITY** - If the user changes the radio button to "Just this case", ET AL., is removed from the caption, and the Lead cases docket number is the only docket number displayed.
~~- [ ] **NEW FUNCTIONALITY** - The first sentence is the same regardless of if filing in the single case or in all cases in the group.~~



#### 15) Judge user keeps the default option to issue the order in all cases in the group; Order Report works as per test cases above

- Continuing from the previous test
- Keep the default radio button selected to issue the order in "All cases in this group"
- Repeat the tests from above to ensure:

Expected Results:
- [x] **NEW FUNCTIONALITY** - Validation error messages work the same (must have at least one selection (besides the consolidated radio button), valid date, Jurisdiction)
- [x] **NEW FUNCTIONALITY** - Document preview adjusts appropriately based off of what selections are made, what text is added in the Additional order text, and Docket entry description text box
- [x] **NEW FUNCTIONALITY** - Order can be saved, edited, deleted, or signed appropriately



#### 16) Judge user creates an Order Report in a member case in a consolidated group; There is NOT an option present at the top of the page to select a single case or all cases in the group.

- Log in as a Judge user
- Navigate to a member case in a consolidated group that has a status report on the docket record.
- Click on the document link for the status report
- Click on Order Report link at the top of the document preview

Expected Results:
- [x] **NEW FUNCTIONALITY** - The left side of the screen does NOT have an additional option at the top for selecting if the user wants to file the order in just this case or in all cases in the group, since this is not the lead case in the group.
- [x] **NEW FUNCTIONALITY** - The rest of the functionality of the Order response works per the tests above for non-lead cases in a group)



#### 17) Judge user previews a Status report from a message; New link is available at the top of the document preview pane that displays "Order Report"

- Log in as a Judge user
- Navigate to a message that has a Status Report attached.
- Click on the Status report document link in the message so that the message, attachments and document preview pane displays

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a new link at the top of the document preview pane that displays Order Report and there is an edit icon to the left of the text.



#### 18) Judge user can complete the Status Order Report from a message just as in test cases 1-16, but the draft order is also associated with the message attachment.

- [ ] Tests 1-16 pass when initiating this workflow from a message.



#### 19) Repeat all of the test cases above as a Chambers user and an ADC user

Expected results:
- [x] All tests pass as a Chambers user
- [x] All tests pass as an ADC user



#### 20) Docket clerk adds an Order Report to the docket record, document is added and served as per normal Order.

- Log in as a docket clerk
- Navigate to the docket record of a case/access your messages for the Status Order Report.
- Click on the add docket entry link at the top of the document preview

Expected Results:

- The Order Report acts as any regular order getting added to the docket record:
     - [x] Docket clerk can edit the "What is this Order for?" text if necessary
     - [x] Docket clerk can change the Document type
     - [x] Docket clerk can select the service stamp
     - [x] Docket clerk can Save and Serve or Save Entry
     - [x] Once served, the document is available in their Processed folder (or in progress folder if saved)
     - [x] Document is served appropriately (can check logs)
     - [x] Document is titled correctly on the docket record. Date filed is today's date, Event code = O, Served parties is B
     - [x] If the Order is getting added to the lead case in a consolidated group, Docket sees the modal to select all cases in the group
     - [x] If paper service, docket receives the print for paper service screen


#### 21) Other Regression tests

- [x] Once the Order Report documents have been served, they appear on the Today's Order page
- [x] Once the Order Report documents have been served, they can be searched for on the Order Search page
- [x] The Order Report documents obey all existing visibility rules
- [x] Docket clerks can seal an Order Report as per usual
- [x] Docket clerks can strike an Order Report as per usual
- [x] Order Report documents display in a Judge's Activity report as per normal

**Comment by katiecissell** [comment]
UX Update for preview:
- Add a secondary outline button between the save draft button and cancel. When it is clicked, display the preview of the PDF the preview pane where it normally is. Can use a regular loading spinner if we need when generating the PDF.
- <img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6c3758dacf2bd4ae5e3e78ec9b0a7f17761f9f6/image.png" alt="image.png" />

**Comment by cholly75** [comment]
Feedback from judges:

1) Formatting of separate clauses should be: indent first line beginning with "ORDERED", following lines should return to left margin as in the example PDF you sent (so, normal paragraph formatting).

2) Dates should have the following format in all cases where they've been generated/selected: "Month DD, YYYY" (essentially, spell out the month).

**Comment by akuny** [comment]
Notes after having worked through DoD checklist and test cases:

- The AC state that the "additional text" field in the Status Report Order Response form should be an "(optional, free text box, 140-160 char limit [in line with Stamp Disposition free text limit)".
  - The character limit of the "additional text" field and the "docket entry description" field is currently 80.
  - The Stamp Disposition free text limit stamp is 60 characters, not 140-160 as specified.
  - The preexisting order title limit is 100 characters.
  - The 80 character limit for these two fields on the Status Report Order Response form can be brought in line with those analogous fields, or tweaked as needed.
- Per discussion with Chris Holly during development:
  - A user should be able to submit a blank Status Report Order Response without any options: therefore, the save button should be activated even if no form fields are filled out. This contradicts the fourth AC.
  - The document preview should be empty before anything is selected. This contradicts test case 2, checkbox 3.
- Per discussion with UX, radio buttons are stacked vertically as opposed to inline horizontally in the mock-ups.
- When an invalid due date is entered and a PDF preview is generated, the phrase "Invalid DateTime" appears in place of the invalid date in the PDF preview.
- Requirements concerning the use of "et al." for lead case orders will be addressed by [10421](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10421)

**Comment by akuny** [comment]
Regarding test case ustaxcourt/ef-cms#6493

Desired behavior: a user is navigated back to the previous screen - the document preview of the Status Report document - after hitting the "Cancel" button on the Status Report Order Response form.

Current behavior: Upon Editing an Order, when clicking cancel, it will return you to the previous page, but not the previous tab. I'd recommend making this a separate ask on another ticket if this is still desired.

**Comment by cholly75** [comment]
UI typo: <img width="456" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG9YQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--07979bc69fd7ba20a3c7671b1dda829142c26600/image.png" alt="image.png" />

Please edit to "stricken" and "session" should be singular. Thanks!

**Comment by cholly75** [comment]
Addl. typo to fix:

<img width="553" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzhYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a43df91dfed0927268b6a36ff4c7eb756d43e0dd/image.png" alt="image.png" />

**Comment by Mwindo** [comment]
> lease edit to "stricken" and "session" should be singular. Thanks!

> Addl. typo to fix:

Just pushed these changes to our PR--thanks for catching these!

**Comment by cholly75** [comment]
Feedback from Judge Review:

@pixywn @akuny @Mwindo - overall LOVED it. Especially impressed with the generated PDF! Items for change are listed below - hit me up if you want to talk through any/all.

1. Change text here to "Order Report" ("Response" is a term of art here that implies different context): <img width="187" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMllaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--512f8d244e1698d7b3e686891999d541cef0a202/image.png" alt="image.png" />

2. Change page title to "Status Report Order" (same reason as above): <img width="502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmNaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cb58654dedd9b1d2551d0b98f267def3cdcfba2/image.png" alt="image.png" />

3. Remove this section entirely to simplify/streamline process: <img width="590" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnNaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4c5983b1141266c68a1ebc9bc37682c781e3dd6e/image.png" alt="image.png" />
Default title is simply "Order" for all orders generated via this workflow. Docket can customize docket entry description separately at the time of docketing.

4. A la stamp dispositions - remove Edit link/capability for Docket clerks **entirely for these orders**, they will not be allowed to edit these orders. Note that the current edit behavior for judge/CA/ADC is exactly as desired (i.e., returning to the original UI).

5. Request to investigate being able to grey out/make unselectable weekends/federal holidays in the calendar picker. Not a requirement, but a "nice to have" if possible.

**Comment by Mwindo** [comment]
@cholly75 Just to double-check: is the preferred nomenclature for this report in general then "Status Report Order?" Asking because if so, it would probably be good for us to rename some classes/files/etc. to avoid future developer confusion (e.g., "The title on the page says Status Report Order, but the entity is called statusReportOrderResponse").

**Comment by cholly75** [comment]
@Mwindo Yes sir!

**Comment by ttlenard** [comment]
@akuny @pixiwyn @mwindo

Some preliminary testing feedback.

1 - If you draft up a Status Report Order, and then go back and edit it, the Clear Fields link does not work.

2 - When a Status Report is attached to a message, and the Judge clicks on the link to create the Order Report, after they save it/sign it, the Order report is not attached to the message thread. When they reply to the message, they have to then manually attach it to the message thread. See test case 18.   The Order report draft should be attached to the message thread, so the user doesn't have to go find it to attach it (We automatically attach Stamp orders to message threads, this workflow would be a good comparison.)

**Comment by ttlenard** [comment]
@akuny @pixiwyn @ttlenard 

Just spoke with the Judges, and they have a text update if possible:

1 - Remove "in this case" for any Order Report that is not filing in all cases in the group.  This would be for the generic Order report, and when "Just this case" is selected from the lead case in a group.

![Image](https://github.com/user-attachments/assets/380fee41-ec1f-42e9-84b1-95717cc14de8)

2 - Re-word the text in the Order when the "all cases in this group" is selected: 

![Image](https://github.com/user-attachments/assets/34b861c1-97dd-47da-b8b4-c16f9aa65082)
