### ISSUE TITLE
Court User: Ability to Remove Message Attachments

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8482]
As a Court user, in order to make sure the correct documents are attached to my message, I need to the ability to remove one or more of the documents attached when drafting a message.

A common complaint heard about the DAWSON messaging system is that if a particular docket entry is attached by mistake the user is forced to delete the message they were working on in its entirety and start over, selecting the correct ones. 

We would like the ability to remove any documents manually added to a message when drafting.

## Acceptance Criteria
* A Court user has the ability to remove one or more of the documents attached by the user when drafting a message
   * Drafting includes: Replying to a message, forwarding a message, and drafting a new message
* Removing an attached document removes it from the message being drafted 
* Documents added to a message by the system (e.g., docket QC's "Complete & Send Message" functionality) cannot be removed from the message
* Documents added to a message by another user cannot be removed from the message
* Documents added to the thread by the user in a previous operation cannot be removed when drafting a new message (see above for what constitutes 'drafting').

## Tasks
- [ ] Tighten up spacing between inputs on message modal
- [ ] Add a "remove" link only for newly-added documents on the modal
- [ ] Test

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre-refinement questions:
- Creating a new message, subject line populates with title of first attached document: how does deletion affect the subject line? **in favor of leaving the subj line alone but UX will think on this**

**Comment by katiecissell** [comment]
For attachments in the create message, forward message and reply to message modals:
- Add a Close icon with the word “Remove” to the right of the row, inline with the attachment name.
- Clicking the X Remove will remove the attachment from the message, No confirmation needed
- Don’t change subject line when attachments are removed
- If all attachments are removed, and a new one attached don’t change subject line
- Tighten up this modal with spacing with token 2.5/20px between everything (instead of token 5/40px)

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/e69d3864-b821-4d7a-8069-8e8286d66bbf)

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/65883f4e-c5ef-42b1-b1b6-a5f2b2ae14d7)

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/420ca1c0-0400-46b8-813e-0444e273fb3b)

If the attachment is a 'system generated' one, like when you complete and send message, users should not be able to remove that attachment so the remove option will not appear.
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/7823ec2d-1acb-4111-8695-eac21fe9b6fb)

[Figma File Link
](https://www.figma.com/file/SSme9qSS1mMH7xV4mfvfwp/Messaging-%7C-Ability-to-remove-attachments-10110?type=design&node-id=16%3A868&mode=design&t=qeLTMBm5moxaRErc-1)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court User creates a new message; attaches a document to the message; user sees a new option to remove the attachment from the Create Message modal.

- Log in to DAWSON as any Court User
- Navigate to a case
- Click on the Create dropdown and select Message
- On the Create Message Screen, select a section, recipient, add a document, and add in message text (the subject should have defaulted to the document title that you added).

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document that you just added as an attachment has a remove link.



#### 2) Court user clicks the remove link for the attachment, document is removed from the message

- Continuing from the previous test
- Click on the remove link next to the document name that you attached in the previous test

Expected Results:
- [x] **NEW FUNCITONALITY** - The attachment is removed from the Create Message modal
- [x] **NEW FUNCTIONALITY** - The subject line text remains as the title of the document that you had previously attached.



#### 3) Court User adds additional documents as attachments to the message, each document has the remove link available.

- Continuing from the previous test
- Click on the Add More Documents link
- Select a document from the docket record to add to the message
- Repeat the last two steps to add additional documents (up to 5)

Expected Results:
- [x] **NEW FUNCTIONALITY** - Each document that you added has the remove link available, and when clicked, the document is removed.
- [x] **NEW FUNCTIONALITY** - The subject line of the message modal has not changed but can be updated by the court user.



#### 4) Court user replies to a message; There are no remove links next to any of the previously attached documents on the reply to message modal

- Continuing from the previous test
- Be sure that there are a few documents attached to the Create Message modal
- Be sure that the recipient is a user that you have a login for
- Click Send.
- Next log in as that user and navigate to the message
- Click on the reply button from the message thread

Expected Results
- [x] Reply to Message Modal appears
- [x] None of the documents that are attached to the message have a remove link next to the document title



#### 5) Court user adds some additional attachments to the reply message; Newly added attachments can be removed

- Continuing from the previous test
- Click the Add documents link
- Add a document

Expected Results:
- [x] **NEW FUNCTIONALITY** - The newly added document has a remove icon next to the document title and can be removed from the reply draft.



#### 6) Court user forwards a message; There are no remove links next to any of the previously attached documents on the Forward message modal

- Log in to DAWSON as any Court User
- Navigate to a case
- Click on the Create dropdown and select Message
- On the Create Message Screen, select a section, recipient, add a few documents as attachments (these will all have remove links), and add in message text (the subject should have defaulted to the document title that you added).
- Be sure that the recipient is a user that you have a login for
- Click Send.
- Next log in as a that user and navigate to the message
- Click on the Forward button from the message thread

Expected Results
- [x] Forward Message Modal appears
- [x] None of the documents that are attached to the message have a remove link next to the document title



#### 7) Court user adds some additional attachments to the Forward message; Newly added attachments can be removed

- Continuing from the previous test
- Click the Add documents link
- Add a document

Expected Results:
- [x] **NEW FUNCTIONALITY** - The newly added document has a remove icon next to the document title and can be removed from the Forward draft.



#### 8) Docket Clerk QC's a document, clicks complete and send message; cannot remove the document that was automatically attached.

- Log in as a Docket Clerk 
- Click on Document QC
- Click on the document title of the document that you wish to QC
- Click Complete and Send Message

Expected Results
- [x] The document that was automatically attached to the message thread does not have the remove link available.


*Repeat this test as a Case Services Supervisor



#### 9) Docket clerk adds an additional attachment to the message modal; clerk can remove the newly added document but cannot remove the document that was automatically added.

- Continuing from the previous test
- Click on the Add Document link
- Add a document

Expected Results:
- [x] **NEW FUNCTIONALITY** - The newly added document has a remove icon next to the document title and can be removed from the Complete and Send Message modal.
- [x] The document that was automatically added during QC does not have the remove link available.



#### 10) Docket Clerk sends a message that has an automatically attached document and an additional document from the QC workflow; Recipient cannot remove the either of the attachments in their reply.

- Continuing from the previous test
- Be sure that you have a section, recipient, title, and message text
- Add in an additional document so that you have the automatically generated document and an additional document added to the message
- Click Send
- Next, log in to DAWSON as the user that you just sent the message to
- Click on the message title
- Click reply

Expected Results:
- [x] Neither of the documents that were added in the previous test have the remove links available.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft reply and can remove the documents.



#### 11) Docket Clerk sends a message that has an automatically attached document from the QC workflow; Recipient cannot remove the attachment in their forwarded message.

- Continuing from the previous test
- Cancel out of the reply, and instead click Forward

Expected Results:
- [x] Neither of the documents that were added in the previous tests have the remove links available.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft Forward and can remove the documents.



#### 12) Recipient of a message creates an Order from the message thread; Replies to the message, neither the original document nor the Order that is attached can be removed in their reply.

- Log in as a docket clerk
- Click on Document QC
- Click on the document title of the document that you wish to QC
- Click Complete and Send Message
- Send the message to a user that you have a login for that can create/sign orders
- Next, log in as that user
- Click on the message title
- From the messages page, click on the Create Order link
- Select the order type and click continue
- Draft an order on the create order page
- Click Save
- Sign the order and then click save signature
- The Draft order should now be in the attachment list for the message and there is a new draft order in the drafts tab
- Click Reply

Expected Results:
- [x] Neither the original document nor the newly created Order can be removed from the Reply to message Modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft Reply and can remove the documents.



#### 13) Recipient of a message creates an Order from the message thread; Forwards the message, neither the original document nor the Order that is attached can be removed in their forwarded message.

- Continuing from the previous test
- Click Cancel from the message pop-up modal
- Click Forward from the Message screen

Expected Results:
- [x] Neither the original document nor the newly created Order can be removed from the Forward message modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft Forward and can remove the documents.



#### 14) Docket Clerk QC's a proposed stip decision document; clicks Complete and Send Message; cannot remove the Proposed Stip document that was automatically attached.

- Log in as a Party that is associated with a case
- Click on the docket number of the case from the my cases screen
- Click on the File a document button
- Be sure to select Proposed Stipulated Decision and then file the document
- Next Log in as a docket clerk
- Click on Document QC
- Navigate to the Proposed Stipulated Decision that you just filed, and click on the document title to QC the document
- Click Complete and Send Message

Expected Results:
- [x] The proposed stipulated decision that was automatically attached cannot be removed.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft and can remove the newly added documents.



#### 15) Recipient that receives a proposed stip doc via a message signs the stip decision; neither the proposed stip nor the stip decision can be removed from the message modal in their reply.

- Continuing from the previous test
- Click Send
- Next, log in as the user you just sent the message to
- Click on the message title from your messages screen
- Click on the Sign stipulated Decision link
- Sign the stip decision and then click save signature
- Click on the Reply link

Expected Results:
- [x] Neither the proposed stip document nor the newly created stipulated decision can be removed from the Reply to Message modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft Reply and can remove the documents.



#### 16) Recipient that receives a proposed stip doc via a message signs the stip decision; neither the proposed stip nor the stip decision can be removed from the message modal in their Forwarded message.

- Continuing from the previous test
- Click Cancel on the Reply to Message modal
- Click on Forward from the Message Screen

Expected Results:
- [x] Neither the proposed stip document nor the newly created stipulated decision can be removed from the Forward Message modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft forward and can remove the documents.



#### 17) Docket Clerk QC's a motion document; clicks Complete and Send Message; cannot remove the Motion document that was automatically attached.

- Log in as a Party that is associated with a case
- Click on the docket number of the case from the my cases screen
- Click on the File a motion document and then file the document
- Next Log in as a docket clerk
- Click on Document QC
- Navigate to the Motion document that you just filed, and click on the document title to QC the document
- Click Complete and Send Message

Expected Results:
- [x] The motion that was automatically attached cannot be removed.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft and can remove the newly added documents.



#### 18) Recipient that receives the motion applies a stamp; neither the motion nor the stamp order can be removed from the message modal in their reply.

- Continuing from the previous test
- Be sure that you select a recipient that can Stamp Motions (ADC, Judge, Chambers)
- Click Send
- Next, log in as the user you just sent the message to
- Click on the message title from your messages screen
- Click on the Apply Stamp link
- Create the Stamp Order and then click Save Stamp Order
- The Message attachments will now include the Stamp Order and there will be a draft Order in the Drafts tab
- Click on the Reply link

Expected Results:
- [x] Neither the Motion nor the newly created Stamp Order can be removed from the Reply to Message modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft Reply and can remove the documents.


#### 19) Recipient that receives the motion applies a stamp; neither the motion nor the stamp order can be removed from the message modal in their Forwarded message.

- Continuing from the previous test
- Click Cancel on the Reply to Message modal
- Click on Forward from the Message Screen

Expected Results:
- [x] Neither the Motion nor the newly created Stamp Order can be removed from the Forward Message modal.
- [x] **NEW FUNCTIONALITY** - User is able to add additional documents to the draft forward and can remove the documents.

**Comment by jasonfu9966** [comment]
Chatted with UX about changes that are not listed above:
- Instead of tightening up spaces between inputs on the modal, we are going to reduce the size of the message box in half, and tighten up the space between the list of attachments and the "Add another document" button.
- We will be preventing users from adding duplicate attachments to messages by disabling them in the dropdown if they are already in the list of attachments.

**Comment by ttlenard** [comment]
All tests pass. Thanks all!
