### ISSUE TITLE
My Cases - Filing Fee Status Display

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8488]
As a petitioner or private practitioner, so that I can easily see the status of my filing fee payment, I need the My Cases display to show the filing fee payment status of each of my cases.

As we move towards integrating DAWSON workflows with pay.gov, we want to begin signifying payment status for petitioners and private practitioners in various places in their DAWSON UI. 

We would like to indicate the filing fee payment status for each case on the My Cases dashboard. This value should be displayed correctly for each case listed on the dashboard for both petitioners and private practitioners regardless of access to the case. This should be the same value seen by internal Court users when viewing the Case Details (see screenshot below). 

Additionally, there should be some sort of explanatory text indicating that this value may take 24-48 hours to update from the date of payment or approval of waiver, as this is currently a manual process.

## Acceptance Criteria
* My Cases display for petitioners indicate the Filing Fee status of the case and is updated when the Filing Fee status is updated by a Court user
* My Cases display for private practitioners indicates the Filing Fee status of the case and is updated when the Filing Fee status is updated by a Court user
* Tooltip/text display informs user of waiting period before the Filing Fee value is updated
  - Tooltip/text display should also appear on the Case Detail screen where the Filing Fee value is displayed
* My Cases display remains unchanged for IRS practitioners

## Notes
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/6695b6b4-c3ee-4e2d-879f-d1f0e30e447f)

* Open to UX recommendations for visual display methods other than text value in table

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by swongCO** [comment]
Pre-refinement questions:
- what is the context for payment status to be displayed on My Cases page? (feedback source) **users who paid the fee but haven't gotten the update, users who forget if they paid the fee or not, users who pay multiple times and the court has to issue refunds (long process)**
- will pay.gov be the only method for payments in the future, aside from checks? **for the foreseeable future; court processes checks and issues receipts**

**Comment by swongCO** [comment]
**UX Notes**
In My Cases for external parties for both Open and Closed cases:
- Add a 4th column named "Filing fee*"
- Add a line of text above the table, right aligned, that says "*Filing fee status may take 2-3 business days from payment received date or approval of waiver to update"
- The 3 statuses are Paid, Not paid, Waived

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHJVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3347d8ddf9aa962c70648f9863f5e9dcb7be406/My%20Cases.png)

___
In the Case Details card under Case Information:
- Add an asterisk (*) after Filing fee
- Add a line of text at the bottom of the card, <s>right</s> left aligned, that says "*Filing fee status may take 2-3 business days from payment received date or approval of waiver to update"

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e22b83c2550ff45ec0e470d5fd242fcfdde8691/Case%20Info.png)

___
**Mobile**
- Add a third column in the table that displays filing fee status
- Display the line of text above the table

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDNVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--48a7db43e84e77d419b1776e2b46b096dd79e00e/My%20Cases%20-%20mobile.png)
___
- Display the line of text at the bottom of Case details
- (If possible) add spacing above Requested place of trial to match spacing between other elements in Case details

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUhVQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d0d81b65c2df900757e850e7a26bfedd362a5e9/Case%20Info%20-%20mobile.png)


Figma file: https://www.figma.com/file/lMGWBOXXaakviNrQswESfc/USTC-%7C-My-Cases-%7C-Filing-fee-status-10117?type=design&node-id=0%3A1&mode=design&t=g0LI4iBvT5CHexQx-1

**Comment by ttlenard** [comment]
## Test Cases

#### 1) New column titled Filing Fee displays on the My Cases Open Cases and Closed Cases pages for a Petitioner.

- Log in to DAWSON as a Petitioner that has at least one case
- Review the My Cases Page

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is now a 4th column titled Filing Fee* on both the Open Cases List and the Closed Cases List
- [ ] **NEW FUNCTIONALITY** - There is text above the tables that states, "May take 2-3 business days from payment received date or approval of waiver to update."
- [x] **NEW FUNCTIONALITY** - On the right hand side of the row for the cases, the Filing Fee payment status is displayed (Paid, Not Paid, Waived).

*Repeat this test with Private Practitioner 
*Could also test this with an intervenor and Participant



#### 2) Petitioner views the Overview tab for their case, Filing fee has an asterisk and additional text displayed in the Case Detail card.

- Continuing from the previous test
- Take note of the Filing fee status for a case on the My Cases Page
- Click on the docket number of the case 
- Click on the Case information tab
- Review the information on the Overview tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Filing Fee section on the Case details card now has an asterisk next to it
- [ ] **NEW FUNCTIONALITY** - There is text near the bottom of the card that states, "May take 2-3 business days from payment received date or approval of waiver to update."
- [x] **NEW FUNCTIONALITY** - The Filing Fee status on the Case details card matches the status on the My Cases Page

*Repeat this test with Private Practitioner 
*Could also test this with an intervenor and Participant


#### 3) Petitions Clerk edits the Filing Fee Status on a case; Petitioner can see the edit on the My Cases page and on the Case Details Card.

**Part 1**
- Log in as a Petitions Clerk (or any court user that can edit the Case Details)
- Navigate to a case that you also have access to as a Petitioner.
- Click on the Case information tab
- Click on the Edit button next to Case Details
- Update the value in the Petition Fee section to a different value
- Click Save
- Next, log in as the Petitioner
- Review the My Cases Page

Expected Results
- [x] **NEW FUNCTIONALITY** - There is now a 4th column titled Filing Fee*
- [ ] **NEW FUNCTIONALITY** - There is text above the table that states, "May take 2-3 business days from payment received date or approval of waiver to update."
- [x] **NEW FUNCTIONALITY** - On the right hand side of the row for the case, the Filing Fee payment status matches what was just edited by the court user

**Part 2**
- Click on the case docket number
- Click on the Case information tab
- Review the Case Details card

Expected Results
- [x] **NEW FUNCTIONALITY** - The Filing Fee section on the Case details card now has an asterisk next to it
- [ ] **NEW FUNCTIONALITY** - There is text near the bottom of the card that states, "May take 2-3 business days from payment received date or approval of waiver to update."
- [x] **NEW FUNCTIONALITY** - The Filing Fee status on the Case details card matches the status on the My Cases Page

*Repeat this test by updating the Filing Fee status a few times to different values ensure that the value is reflected appropriately
*Repeat this test with Private Practitioner 
*Could also test this with an intervenor and Participant


#### 4) My Cases page for an IRS practitioner does not have the new Filing Fee Column

- Log in to DAWSON as a IRS Practitioner that is associated with at least 1 case
- Review the My Cases Page

Expected Results
- [x] There is no 4th column on the My Cases page for neither the Open Cases List nor the Closed Cases list, and there is no information about the Filing Fee Status.


#### 5) Case Details card for an IRS Practitioner does not have the Asterisk next to the Filing Fee and does not have the additional text displayed.

- Continuing from the previous test
- Click on the docket number for one of your cases
- Click on the Case information tab
- Review the case details

Expected Results:
- [x] There is no asterisk next to the Filing Fee, and there is no additional text displayed near the bottom of the card.


#### 6) Internal Court User reviews the Case Detail Card, No asterisk and no additional text is dislayed for Court Users

- Log into DAWSON as any court user
- Navigate to a case
- Click on the Case information tab
- Review the case details

Expected Results:
- [x] There is no asterisk next to the Filing Fee, and there is no additional text displayed near the bottom of the card.

**Comment by swongCO** [comment]
Added mobile mockups in addition to text change and one alignment change. UX notes updated.

**Comment by rachelschneiderman** [comment]
@ttlenard Heads up for testing: The wording was changed slightly for one of the messages such that it does not match the expectation in the test cases. Additionally, we implemented a more accessible and responsive case table for phones only. 

Thank you!
