### ISSUE TITLE
E-Filing: Text/Design Update

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8493]
As an e-filer, so that I can address issues that might prevent me from successfully filing my document, I need better guidance in the e-filing flow.

We see a number of help desk tickets that indicate petitioners and practitioners are unable to successfully e-file their documents with the Court. We would like to provide guidance as to some commonly seen issues with files uploaded so that they may be able to address these prior to receiving an error in DAWSON.

Tenille and UX to provide text/design changes to petition and non-petition e-filing screen(s).

## Acceptance Criteria
* Text/design changes implemented at appropriate places in e-filing flows to message potential issues regarding file uploads.
* Update instructional text on the following sections to remind users that documents must be in PDF format and the uploaded documents cannot be encrypted or password protected.
     * Upload Statement of Taxpayer Number 
     * Upload Your Petition 
     * Upload Your Document (including when party files motion for leave to file and motion for leave to file out of time)
     * Upload Your Supporting Document 
     * Upload your Secondary Supporting Document
* If the document that the user uploaded results in an error, update the "Uh-oh" popup modal to be more consistent with other pop-up modals in DAWSON and include similar instructional text to remind users that documents must be in PDF format and the uploaded documents cannot be encrypted or password protected.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by katiecissell** [comment]
UX Notes:

There are four areas where the user can upload files that need updated text. This will change the text of the header, the text beneath the header, <s>the file upload button and the empty state text</s>.
- use the standard USWDS alert banner style (black icon instead of blue in the mockup)
- button in mobile modal follows the content and not positioned at the bottom

Filing a document and supporting documents.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazRiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a77124aa8f2550cc8e37d36f957cefb8dc16f88a/image.png)

filing a petitioner STIN
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--331cfc62cfc7020d65e160e1c8e002e8d13d89d3/image.png)

Filing petition
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEViIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b24f771d03b83aac2e7e11d813220a90df2292e0/image.png)
___
Error modal after clicking Submit
- Replace existing modal
- Use current modal component
- Title: Your Request Was Not Completed
- Body: There was a problem with your submission. Ensure that your uploaded files:
           • Are in PDF format (.pdf)
           • Have a file size of 250MB or less
           • Are not encrypted or password protected
           If you still have a problem after troubleshooting your files, email dawson.support@ustaxcourt.gov.
- Close btns will exit the modal and keep the user on the page
- Clicking the support link will open the user's email client

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVliIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef3e40dd3f584d746daa70dcef2a5612e74ac3e1/Error%20modal.png)

Mobile error modal
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm9iIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ea2bbffbcd33903db4fb6bdaad797bfcb41f932f/Mobile%20error%20modal.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner creates a new case in DAWSON; The instructions on the Upload your Statement of Taxpayer Identification Number screen now include more helpful infomration.

- Log in as a Petitioner
- Start a case
- Review the Upload your Statement of Taxpayer Identification Number Screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - This section now has the additional instructional text in the header to specify a PDF document (see mockup).
- [x] **NEW FUNCTIONALITY** - Under the Upload your STIN PDF header, there is additional instructional text that matches the mockup.
- [ ] **NEW FUNCTIONALITY** - The button to upload a file now says "Choose PDF", and "No PDF file chosen" if there isn't a file selected.


#### 2) Petitioner creates a new case in DAWSON; The instructions on the Upload your Petition screen now include more helpful information.

- Continuing from the previous test
- Upload a PDF file for the STIN and then click Continue to Step 2 of 5
- Review the Upload your Petition screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - This section now has the additional instructional text in the header to specify a PDF document (see mockup).
- [x] **NEW FUNCTIONALITY** - Under the Upload your Petition PDF header, there is additional instructional text that matches the mockup.
- [ ] **NEW FUNCTIONALITY** - The button to upload a file now says "Choose PDF", and "No PDF file chosen" if there isn't a file selected.


#### 3) Petitioner uploads a document that is not in a pdf format, upon submittal to the US Tax Court, Receives updated error message.

- Continuing from the previous test
- For the Petition document, be sure to upload a document that is not in PDF format (word, excel, jpeg, etc.)
- Complete the required fields for the Create a Case process until you get to the Review your case screen.
- Click on the Submit to US Tax Court Button

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your case screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your case screen.

*Repeat this test, but be sure that the STIN document is the document that is not in PDF format
*Repeat this test, and be sure that both the STIN and the Petition are not in PDF format

#### 4) Petitioner closes out of the error message; navigates back to the Upload your Petition screen, uploads a document in the correct format, and can then submit appropriately.

- Continuing from the previous test
- After clicking one of the close options on the modal, click the back button until you get to the upload screen with the incorrect document
- Remove the file and then upload a file in the correct file format
- Continue forward in the workflow until you get to the Review your case screen
- Click Submit to US Tax Court button

Expected Results:
- [x] Case is created successfully


#### 5) Petitioner uploads a document that is encrypted or password protected, upon submittal to the US Tax Court, Receives updated error message.

**PART 1**
- Continuing from the previous test
- For the Petition document, be sure to upload a document that is encrypted or password protected
- Complete the required fields for the Create a Case process until you get to the Review your case screen.
- Click on the Submit to US Tax Court Button

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your case screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your case screen.

*Repeat this test, but be sure that the STIN document is the document that is encrypted or password protected
*Repeat this test, and be sure that both the STIN and the Petition are encrypted or password protected

**PART 2**
- After clicking one of the close options on the modal, click the back button until you get to the upload screen with the incorrect document
- Remove the file and then upload a file in the correct file format
- Continue forward in the workflow until you get to the Review your case screen
- Click Submit to US Tax Court button

Expected Results:
- [x] Case is created successfully



#### 6) Petitioner uploads a document that is corrupted or in a pdf format that is not supported, upon submittal to the US Tax Court, Receives updated error message.

**Part 1**
- Log in as a Petitioner
- Start a case
- Go through the create a case workflow and be sure to upload a corrupted Petition (not sure how to find an example of one of these documents??? Maybe look in S3 for a file that was attempted to be uploaded and received the "PDF Pages cannot be read" error?)
- Complete the required fields for the Create a Case process until you get to the Review your case screen.
- Click on the Submit to US Tax Court Button

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your case screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your case screen.

*Repeat this test, but be sure that the STIN document is the document that is corrupted
*Repeat this test, and be sure that both the STIN and the Petition are both corrupted files

**PART 2**
- After clicking one of the close options on the modal, click the back button until you get to the upload screen with the corrupted document
- Remove the file and then upload a file that is not corrupted
- Continue forward in the workflow until you get to the Review your case screen
- Click Submit to US Tax Court button

Expected Results:
- [x] Case is created successfully



#### 7) Repeat tests 1-7 as a Private Practitioner

Expected Results:
- [x] Tests 1-6 pass



#### 8) Petitioner efiles a document on one of their cases; the instructions on the Upload PDF document section now includes more helpful information.

- Log in as a petitioner that is associated with a case
- Click on the docket number link on the my cases page
- Click the file a document button
- Select a document type from the dropdown menu and click continue
- Review the File your Documents screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - This section now has the additional instructional text in the header to specify a PDF document (see mockup).
- [x] **NEW FUNCTIONALITY** - Under the Upload your PDF Document, there is additional instructional text that matches the mockup.
- [ ] **NEW FUNCTIONALITY** - The button to upload a file now says "Choose PDF", and "No PDF file chosen" if there isn't a file selected.



#### 9) Petitioner adds supporting documents to their filing, the instructions on the Upload your Supporting document PDF section now includes more helpful information.

- Continuing from the previous test
- Click the button to add supporting document
- Select a Supporting document type


Expected Results:
- [x] **NEW FUNCTIONALITY** - This section now has the additional instructional text in the header to specify a PDF document (see mockup).
- [x] **NEW FUNCTIONALITY** - Under the Upload your Supporting PDF Document, there is additional instructional text that matches the mockup.
- [ ] **NEW FUNCTIONALITY** - The button to upload a file now says "Choose PDF", and "No PDF file chosen" if there isn't a file selected.

*Repeat this test by adding 5 supporting documents to the filing. All 5 Upload supporting document sections should have the updated text.



#### 10) Petitioner files a Motion for Leave to File, both the Motion and the document they are filing leave for have the instructions on the Upload PDF document section that now includes more helpful information. 

- Log in as a petitioner that is associated with a case
- Click on the docket number link on the my cases page
- Click the file a document button
- Select a Motion for Leave to File document type from the dropdown menu 
- Then select the document you are filing leave for, and then click continue
- Review the File your Documents screen

Expected Results:
- [x] **NEW FUNCTIONALITY** - Both sections (Motion and the document you selected) now have the additional instructional text in the header to specify a PDF document (see mockup).
- [x] **NEW FUNCTIONALITY** - Under both sections for the Upload your PDF Document, there is additional instructional text that matches the mockup.
- [ ] **NEW FUNCTIONALITY** - The button to upload a file on both sections now says "Choose PDF", and "No PDF file chosen" if there isn't a file selected.

*Repeat this test with a motion for leave to file out of time document as well
*Repeat this test by adding in supporting documents for the motion as well as Secondary Supporting documents for the file you are filing leave for, all upload sections should display the updated text.



#### 11) Petitioner uploads a document that is not in a pdf format, upon submittal to the US Tax Court, Receives updated error message.

- Log in as a petitioner that is associated with a case
- Click on the docket number link on the my cases page
- Click the file a document button
- Select a document type from the dropdown menu and click continue
- Upload a document that is not in PDF Format
- Click Review Filing
- Check the box to indicate your files are redacted
- Click Submit your Filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your Filing screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your Filing screen.



#### 12) Petitioner closes out of the error message; navigates back to the File Your Documents screen, uploads a document in the correct format, and can then submit appropriately.

- Continuing from the previous test
- After clicking one of the close options on the modal, click the back button until you get to the File Your Documents screen
- Remove the file and then upload a file in the correct file format
- Continue forward in the workflow until you get to the Review your Filing screen
- Click Submit Your Filing button

Expected Results:
- [x] Document is filed successfully

*Repeat tests 11 and 12 by adding non-PDF files as supporting documents with the filing 
*Repeat tests 11 and 12 by adding non-PDF files to motion for leave/motion for leave to file out of time/secondary supporting documents with the filings



#### 13) Petitioner uploads a document that is encrypted or password protected, upon submittal to the US Tax Court, Receives updated error message.

**Part 1**
- Log in as a petitioner that is associated with a case
- Click on the docket number link on the my cases page
- Click the file a document button
- Select a document type from the dropdown menu and click continue
- Upload a document that is encrypted or Password protected
- Click Review Filing
- Check the box to indicate your files are redacted
- Click Submit your Filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your Filing screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your Filing screen.

**Part 2**
- After clicking one of the close options on the modal, click the back button until you get to the File Your Documents screen
- Remove the file and then upload a file that is not encrypted or password protected
- Continue forward in the workflow until you get to the Review your Filing screen
- Click Submit Your Filing button

Expected Results:
- [x] Document is filed successfully

*Repeat test by adding encrypted/password protected files as supporting documents with the filing 
*Repeat test by adding encrypted/password protected files to motion for leave/motion for leave to file out of time/secondary supporting documents with the filings



#### 14) Petitioner uploads a document that is corrupted or in a pdf format that is not supported, upon submittal to the US Tax Court, Receives updated error message.

**Part 1**
- Log in as a petitioner that is associated with a case
- Click on the docket number link on the my cases page
- Click the file a document button
- Select a document type from the dropdown menu and click continue
- Upload a document that is corrupted or in a pdf format that is not supported
- Click Review Filing
- Check the box to indicate your files are redacted
- Click Submit your Filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - An updated error message appears that indicates "Your Request Was Not Completed" (see mockup for all of the text displayed)
- [x] **NEW FUNCTIONALITY** - Clicking the Close link in the upper right hand corner returns the user to the Review your Filing screen
- [x] **NEW FUNCTIONALITY** - Clicking the Close button in the modal will return the user to the Review your Filing screen.

**Part 2**
- After clicking one of the close options on the modal, click the back button until you get to the File Your Documents screen
- Remove the file and then upload a file that is not corrupted
- Continue forward in the workflow until you get to the Review your Filing screen
- Click Submit Your Filing button

Expected Results:
- [x] Document is filed successfully

*Repeat test by adding corrupted files as supporting documents with the filing 
*Repeat test by adding corrupted files to motion for leave/motion for leave to file out of time/secondary supporting documents with the filings



#### 15) Repeat tests 9-14 as a Private Practitioner

Expected Results:
- [x] Tests 9-14 pass



#### 16) Repeat tests 9-14 as an IRS Respondent

Expected Results: 
- [x] Tests 9-14 Pass 



#### 17) Repeat all tests above on a mobile device

Expected Results:
- [x] All tests pass on a mobile device
- [x] Screens are readable and are displayed in a way that looks good on a mobile device

**Comment by swongCO** [comment]
**UX test feedback**

Container width for petition upload is not consistent with STIN upload:
- text is wrapping before it needs
- No file chosen text is truncated
- Inspector shows that there's a grid element wrapping the form-group element

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkg5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b96e02eabc1c8b79430fd8662365adaa6c4e636d/Screenshot%202023-10-03%20at%2010.00.28%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkw5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--496d512f856f0969212874361754577afbef59a1/Screenshot%202023-10-03%20at%2010.31.46%20AM.png)
