### ISSUE TITLE
Petitioner: Remove Default 'Surviving Spouse' Designation From Caption

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8514]
As a petitioner, so that the caption of my case accurately represents me, I need DAWSON to stop automatically adding my name as 'Surviving Spouse' to the caption.

When a petition is filed and the petitioner indicates that a deceased spouse is also part of the petitioning party, DAWSON creates the case caption in the following format:

[Petitioner] & [Petitioner Spouse], Deceased, [Petitioner], Surviving Spouse, Petitioners v. Commissioner of Internal Revenue, Respondent

The third clause - "[Petitioner], Surviving Spouse" - is both unnecessary and misleading. "Surviving Spouse" is a legal term in this context and recognized in only two states as having any standing. Alternate selections are used to indicate this status and party type. Case Services currently must amend these captions to remove this designation for the majority of these cases.

The court would like to stop automatically adding this designation to these case captions when certain flows are invoked.  There are currently 4 possible ways to trigger this behavior, 2 for e-filers and 2 for docket; we need to change1 flow for e-filers and 1 flow for docket.

## Acceptance Criteria
These scenarios require change to their behavior:
* When an e-filing petitioner indicates that they are filing a petition on behalf of "Myself and my spouse" AND that their spouse is deceased (see screenshot 1) the resulting case is created with the caption as follows: "[Petitioner] & [Petitioner Spouse], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
* When a Private Practitioner indicates that they are filing a petition on behalf of "Petitioner and spouse" AND that the spouse is deceased, the resulting case is created with the caption as follows: "[Petitioner] & [Petitioner Spouse], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
* When a petitions clerk indicates that a petition they are filing is on behalf of "Petitioner and deceased spouse" (see screenshot 3) the resulting case is created with the caption as follows: "[Petitioner] & [Petitioner Spouse], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
 
These scenarios should *not* change:
* When a petitions clerk indicates that a petition they are filing is on behalf of "Surviving spouse" - NO CHANGE
* When an e-filing petitioner indicates that they are filing a petition on behalf of "Other" and "Deceased Spouse" (see screenshot 2) - NO CHANGE
* When an e-filing private practitioner indicates that they are filing a petition on behalf of "Other" and "Deceased Spouse" (see screenshot 2) - NO CHANGE

* No action needed on any cases created prior to this change

## Notes
Screenshot 1:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTI5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ba147bef6d2596c9e585f447fd95c8b7f6a8dc98/image.png)

Screenshot 2:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTY5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fcdf97f9651862580365e11b71ef4262a26b1aeb/image.png)

Screenshot 3:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdSs5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c7cb416d6730f85243c68f0e1f85fd8c1648892/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [x] experimental1
   - [x] experimental2
   - [x] experimental3
   - [x] experimental4
   - [x] experimental5
   - [x] experimental6
   - [x] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Why are only some flows changing and not others?

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner eFiles a Petition; Indicates they are filing on behalf of "Myself and my Spouse" AND that their Spouse is Deceased; Case caption does not display "Surviving Spouse"

- Log in as a Petitioner
- Click on the Create a Case button
- Click Got it, let's start a case button
- Upload a STIN and click Continue to Step 2 of 5
- Upload a Petition, select any radio button/selection for IRS notice, and then click Continue to Step 3 of 5
- Select "Myself and my spouse" radio button
- Select Yes, that your Spouse is deceased.
- Fill out the required fields Petitioner and the deceased spouse
- Click Continue to Step 4 of 5 button
- Indicate any case procedure
- Select a trial location
- Click Continue to Step 5 of 5
- Click Submit to U.S. Tax Court button.

Expected Results:
- [x] App is routed to the Confirmation screen that shows the case docket number
- [x] **NEW FUNCTIONALITY** - Case Caption is "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After clicking on the View Dashboard button, the Case title on the Petitioners dashboard is the same as the case caption.
- [x] **NEW FUNCTIONALITY** - Printable docket record and Petition document have the case caption displayed as: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"



#### 2) Private Practitioner eFiles a Petition; Indicates they are filing on behalf of "Petitioner and Spouse" AND that their Spouse is Deceased; Case caption does not display "Surviving Spouse"

- Log in as a Petitioner
- Click on the Create a Case button
- Click Got it, let's start a case button
- Upload a STIN and click Continue to Step 2 of 5
- Upload a Petition, select any radio button/selection for IRS notice, and then click Continue to Step 3 of 5
- Select "Petitioner and spouse" radio button
- Select Yes, that the Spouse is deceased.
- Fill out the required fields Petitioner and the deceased spouse
- Click Continue to Step 4 of 5 button
- Indicate any case procedure
- Select a trial location
- Click Continue to Step 5 of 5
- Click Submit to U.S. Tax Court button.

Expected Results:
- [x] App is routed to the Confirmation screen that shows the case docket number
- [x] **NEW FUNCTIONALITY** - Case Caption is "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After clicking on the View Dashboard button, the Case title on the Practitioners dashboard is the same as the caption
- [x] **NEW FUNCTIONALITY** - Printable docket record and Petition document have the case caption displayed as: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"



#### 3) Petitions Clerk QC's the eFiled petitions that were submitted in the previous test cases; Case caption and Case Title is appropriately displayed.

**Part 1**
- Log in as a Petitions Clerk
- Click on Document QC
- Click on Section Document QC
- Scroll down the list to and find the petition that you filed from test case 1

Expected Results:
- [x] **NEW FUNCTIONALITY** - Case Title on the Document QC page is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased

**Part 2**
- Click on the Petition link
- Review the Case Caption

Expected Results:
- [x] **NEW FUNCTIONALITY** - Case Caption in the header is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - Case Caption on the Case info tab is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners"
- [x] **NEW FUNCTIONALITY** - Case Caption on the coversheet of the Petition is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After clicking Review Petition the Case Caption in the Case information box is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After Clicking Serve to IRS, the Case Title on the Served Tab of My Document QC is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased"
- [x] **NEW FUNCTIONALITY** - After Clicking on the Petition link, Case caption on the Petition coversheet and the NOTR is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"


*Repeat this test with the petition that you submitted in test case 2
*Repeat this test with a Case Services Supervisor



#### 4) Service emails sent to the eFilers in Test case 1 and 2 reflect the Case Title appropriately

- Access the email account for the Petitioner that you used for Test case 1  
- Find the eService Notification email from Serving the Petition

Expected Results: 
- [x] **NEW FUNCTIONALITY** - The Case title in the email is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased"

*Repeat this test with the Private Practitioner from test case 2



#### 5) Petitions Clerk starts a paper petition, indicates that the petition that they are filing was filed on behalf of Petitioner and Deceased Spouse"; Case caption does not display "Surviving Spouse".

**Part 1**
- Log in as a Petitions Clerk
- Click on the Document QC menu
- Click on Start a Petition button
- Upload or Scan a Petition and STIN
- Select "Petitioner and deceased spouse as the Party type
- Fill out the required contact fields
- Click on the Case Info Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - Case Caption on the Case info tab is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners"

**Part 2**
- Fill out the Required fields on the case info tab and the IRS notice tab
- Click Create Case

Expected Results:
- [x] App is routed to the Review and Serve Petition Screen
- [x] **NEW FUNCTIONALITY** - Case Caption in the Header is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - Case Caption in Case information card is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After Clicking Serve to IRS, the Case caption on the Print Paper Service NOTR is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"
- [x] **NEW FUNCTIONALITY** - After Clicking Done on the Print Paper Service Screen, the Case Title on the Served Tab of My Document QC is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased"
- [x] **NEW FUNCTIONALITY** - After Clicking on the Petition link from the Served tab, the Case caption on the Petition on the docket record is: "[Petitioner Name] & [Deceased Petitioner Name], Deceased, Petitioners v. Commissioner of Internal Revenue, Respondent"

*Repeat this test with the Case Services Supervisor role.



### **Regression testing - These tests are to ensure that there was no change to the existing functionality:**


#### 6) Petitioner eFiles a Petition; Indicates they are filing on behalf of "Other" and they select "Deceased Spouse", Case Caption includes the term "Surviving Spouse".

- Log in as a Petitioner
- Click on the Create a Case button
- Click Got it, let's start a case button
- Upload a STIN and click Continue to Step 2 of 5
- Upload a Petition, select any radio button/selection for IRS notice, and then click Continue to Step 3 of 5
- Select Other and then select Deceased Spouse
- Fill in the required contact fields for the deceased and surviving spouse and then click Continue to Step 4 of 5
- Select a case procedure, a preferred trial location, and then click on Continue to step 5 of 5.
- Click Submit to US Tax Court

Expected Results:
- [x] App is routed to the Confirmation screen that shows the case docket number
- [x] Surviving Spouse is in the Case Caption as per normal: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"
- [x] After clicking on View Dashboard, Case title is "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse"
- [x] After clicking on the docket number link, the coversheet of the petition has the case caption: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"



#### 7) Private Practitioner eFiles a Petition; Indicates they are filing on behalf of "Other" and they select "Deceased Spouse", Case Caption includes the term "Surviving Spouse".

- Log in as a Petitioner
- Click on the Create a Case button
- Click Got it, let's start a case button
- Upload a STIN and click Continue to Step 2 of 5
- Upload a Petition, select any radio button/selection for IRS notice, and then click Continue to Step 3 of 5
- Select Other and then select Deceased Spouse
- Fill in the required contact fields for the deceased and surviving spouse and then click Continue to Step 4 of 5
- Select a case procedure, a preferred trial location, and then click on Continue to step 5 of 5.
- Click Submit to US Tax Court

Expected Results:
- [x] App is routed to the Confirmation screen that shows the case docket number
- [x] Surviving Spouse is in the Case Caption as per normal: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"
- [x] After clicking on View Dashboard, Case title is "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse"
- [x] After clicking on the docket number link, the coversheet of the petition has the case caption: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"



#### 8) Service emails sent to the eFilers in Test case 6 and 7 reflect the Case Title appropriately

- Access the email account for the Petitioner that you used for Test case 6  
- Find the eService Notification email from Serving the Petition

Expected Results: 
- [x] The Case title in the email is:"[Surviving Petitioner Name] & [Deceased Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse"

*Repeat this test with the Private Practitioner from test case 7



#### 9) Petitioner clerk starts a paper petition; indicates that the petition they are filing was filed on behalf of "Surviving Spouse"; Case Caption includes the term "Surviving Spouse"

**Part 1**
- Log in as a Petitions Clerk
- Click on the Document QC menu
- Click on Start a Petition button
- Upload or Scan a Petition and STIN
- Select Surviving Spouse as the Party Type
- Fill in the contact information about the deceased and surviving spouse
- Click on the Case Info tab

Expected Results:
- [x] Case Caption on the Case info tab is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner"

**Part 2**
- Fill out the Required fields on the case info tab and the IRS notice tab
- Click Create Case

Expected Results:
- [x] App is routed to the Review and Serve Petition Screen
- [x] Case Caption in the Header is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"
- [x] Case Caption in Case information card is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"
- [x] After Clicking Serve to IRS, the Case caption on the Print Paper Service NOTR is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"
- [x] After Clicking Done on the Print Paper Service Screen, the Case Title on the Served Tab of My Document QC is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse
- [x] After Clicking on the Petition link from the Served tab, the Case caption on the Petition on the docket record is: "[Petitioner Name], Deceased, [Surviving Spouse Name], Surviving Spouse, Petitioner v. Commissioner of Internal Revenue, Respondent"

*Repeat this test with the Case Services Supervisor role.
