### ISSUE TITLE
Activity Report/Judge Dashboard: Remove Decision Doc Criteria

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8518]
As a judge, so that vacated and remanded cases continue to appear on the Activty report and my dashboard, I need cases with a decision-type document to be included in the data captured in these two places.

As designed, both the Activity report and the judge/CA "Submitted/CAV Cases" portion of the dashboard currently exclude any cases that have a decision-type document on their docket record (see below for list of event codes). After review and discussion, the Court has determined that this presents irregularity in the data in certain instances (for example, cases where a decision has been vacated or the case remanded).

The Court has determined we need not exclude cases with a decision document on the docket record from the report or dashboard going forward, so we would like to remove that criteria from both when determining which cases are visible.

## Acceptance Criteria
* Cases that have a Decision-type document on the docket record (ODD, DEC, OAD, SDEC) are no longer excluded from the Activity report provided they meet the other criteria for inclusion
* Cases have a Decision-type document on the docket record (ODD, DEC, OAD, SDEC) are no longer excluded from the "Submitted/CAV Cases" portion of the judge/CA dashboard provided they meet the other criteria for inclusion

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ] Acceptance criteria have been met and validated on the Court's test environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Case in Submitted Status has a Decision document filed on the docket record; case is listed in the Submitted/CAV Cases section on the Judges Activity Report.

**Part 1**
- Log in as a Judge User
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section
- Click on the docket number link for one of the cases in Submitted Status (remember this docket number!)
- Click Create and then select Order or Notice
- Select Order and then select "Order of Dismissal and Decision"
- Draft an Order, sign it, and then send a message with the draft order a test docket clerk user
- Go back to the Activity report and run the report again

Expected Results:
- [x] The docket number that has the Order of Dismissal and Decision in the draft folder remains in the results in the Submitted/CAV Cases section.

**Part 2**
- Log in as the test docket clerk user from above
- Click on the message from the Judge
- Click on the Add Docket Entry
- Save and Serve the Order of Dismissal and Decision
- Click on the Case information tab in the case
- Click on Edit Case Status/Caption
- Change the Case Status back to Submitted and select the judge that was previously associated with the case
- Click Save

Expected Results:
- [x] Case Status is back to Submitted

**Part 3**
- Log in as the Judge from above
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket number that has the Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this entire test by drafting/docketing the following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision

*Be sure that you also run an Activity Report by selecting All Judges, Special Trial Judges, Senior Judges to ensure that the case remains in the Submitted/CAV cases list.



#### 2) Case in Submitted Status has a Decision document filed on the docket record; case is listed in the Submitted/CAV Cases section on the Judges Dashboard.

- Continuing from the previous test
- As the Judge User, Click on the Dashboard tab
- Review the Submitted/CAV cases section on the Judges Dashboard

Expected Results:

- [x] **NEW FUNCTIONALITY** - The docket number that has the Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by testing with the following cases with Decision type documents - Cases should still remain in the results on the Judges Dashboard
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision



#### 3) Case in CAV Status has a Decision document filed on the docket record; case is listed in the Submitted/CAV Cases section on the Judges Activity Report

**Part 1**
- Log in as a Judge User
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section
- Click on the docket number link for one of the cases in CAV Status (remember this docket number!)
- Click Create and then select Order or Notice
- Select Order and then select "Order of Dismissal and Decision"
- Draft an Order, sign it, and then send a message with the draft order a test docket clerk user
- Go back to the Activity report and run the report again

Expected Results:
- [x] The docket number that has the Order of Dismissal and Decision in the draft folder remains in the results in the Submitted/CAV Cases section.


**Part 2**
- Log in as the test docket clerk user from above
- Click on the message from the Judge
- Click on the Add Docket Entry
- Save and Serve the Order of Dismissal and Decision
- Click on the Case information tab in the case
- Click on Edit Case Status/Caption
- Change the Case Status back to CAV and select the judge that was previously associated with the case
- Click Save

Expected Results:
- [x] Case Status is back to CAV

**Part 3**
- Log in as the Judge from above
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket number that has the Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by drafting/docketing the following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision

*Be sure that you also run an Activity Report by selecting All Judges, Special Trial Judges, Senior Judges to ensure that the case remains in the Submitted/CAV cases list.



#### 4) Case in CAV Status has a Decision document filed on the docket record; case is listed in the Submitted/CAV Cases section on the Judges Dashboard

- Continuing from the previous test
- As the Judge User, Click on the Dashboard tab
- Review the Submitted/CAV cases section on the Judges Dashboard

Expected Results:

- [x] **NEW FUNCTIONALITY** - The docket number that has the Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by testing with cases that have the following Decision type documents - Cases should still remain in the results on the Judges Dashboard.
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision



#### 5) Docket Clerk Strikes a decision document that is filed on a case in a Submitted case status; case is listed in the Submitted/CAV Cases section on the Judges Activity Report

**Part 1**
- Log in as a docket clerk
- Navigate to one of the cases in Submitted Status that you filed an Order and Decision document on from the tests above
- Strike the Order and Decision document on the docket record

**Part 2**
- Log in as the Judge from above
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket number that has the stricken Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by striking the following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision



#### 6) Case in Submitted Status with the Stricken Decision document is listed on the Submitted/CAV cases section on the Judges Dashboard.

- Continuing from the previous test
- As the Judge User, Click on the Dashboard tab
- Review the Submitted/CAV cases section on the Judges Dashboard

Expected Results:

- [x] **NEW FUNCTIONALITY** - The docket number that has the Stricken Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by testing with cases that have following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision


#### 7) Docket Clerk Strikes a decision document that is filed on a case in a CAV case status; case is listed in the Submitted/CAV Cases section on the Judges Activity Report

**Part 1**
- Log in as a docket clerk
- Navigate to one of the cases in CAV Status that you filed the Order and Decision document on from the tests above
- Strike the Order and Decision document on the docket record

**Part 2**
- Log in as the Judge from above
- Click on Reports and select Activity
- Input some dates, leave the Judge user you logged in as the default
- Click Run Report
- Review the cases in the submitted/CAV cases section

Expected Results:
- [x] **NEW FUNCTIONALITY** - The docket number in CAV status that has the stricken Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by striking the following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision



#### 8) Case in CAV Status with the Stricken Decision document is listed on the Submitted/CAV cases section on the Judges Dashboard.

- Continuing from the previous test
- As the Judge User, Click on the Dashboard tab
- Review the Submitted/CAV cases section on the Judges Dashboard

Expected Results:

- [x] **NEW FUNCTIONALITY** - The docket number in CAV Status that has the Stricken Order of Dismissal and Decision remains in the results in the Submitted/CAV Cases section.

*Repeat this test by testing with cases that have following Decision type documents - Cases should still remain in the results on the Judges Activity report
- [x] Decision
- [x] Order and Decision
- [x] Stipulated Decision



#### 9) Be sure to test filing decisions, striking, and having a draft decision in consolidated cases

- [x] The Consolidated group remains in the Submitted/CAV cases section on the Activity report and on the Dashboard if decisions, drafts, or stricken documents are filed in Lead or Member cases.



#### 10) Repeat all tests above with a Chambers Administrator User instead of a Judge User

- [x] All tests pass



#### 11) Regression test the Activity report and Submitted/CAV case worksheet to ensure all functions work as designed.

- [x] Regression tests pass

**Comment by ttlenard** [comment]
@Absolutestunna @rachelschneiderman @zRogersFlexion Testing looks good. Thanks!
