### ISSUE TITLE
New Event Code: Motion to Lift Stay of Proceedings

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8519]
As a petitioner or practitioner, so that I can be sure I'm filing the correct document type, I need to be able to file a Motion to Lift Stay of Proceedings.

The Court has asked us to implement a new Motion type available for e-filing and paper docketing: Motion to Lift Stay of Proceedings. This behaves like a normal motion in all respects (can be stamped, can be the target of another filed document, requires objection value when filing, receive cover sheets, etc.

No prescription as to event code - we can use whichever "M###" is next in line or "MLSP".

## Acceptance Criteria
* E-filers can choose "Motion to Lift Stay of Proceedings" as a document type when e-filing
* Docket clerks can choose "Motion to Lift Stay of Proceedings" as a document type when adding a paper filing or editing a document in QC
* "Motion to Lift Stay of Proceedings" documents are docketed/served/behave in the same manner as any other non-simultaneous motion

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement
 - What does this motion actually do for the filer/court?
 - Is there some giant list of all possible motions the court will accept that some day we should support? No
 - Can it be multi docketed with both efiling and paper filing? Yes

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner files a document on a case, Document type option of "Motion to Lift Stay of Proceedings" is available in the picklist.

- Log into DAWSON as a Petitioner that has access to a case
- Click on the docket number of the case on the My Cases Screen
- Click on the File a Document Button
- Click on the Ok, I'm ready to file button
- Click on the dropdown for Document Type

Expected Results:
- [x] **NEW FUNCTIONALITY** - Motion to Lift Stay of Proceedings is an available option.
- [x] **NEW FUNCTIONALITY** - User can type the selected event code (MLSP?) and the document title appears in the dropdown



#### 2) Petitioner Selects Motion to Lift Stay of Proceedings as the document type, Submits to the Court, Document appears correctly on the Docket Record

**Part 1**
- Continuing from the previous test
- Select Motion to Lift Stay of Proceedings from the document Type Dropdown menu
- Click Continue

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title is displayed appropriately on the File your Document(s) page

**Part 2**
- Upload a document, indicate if there are any objections, and then click Review filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title is displayed appropriately on the Review Your Filing page

**Part 3**
- Check the redaction acknowledgement checkbox and then click Submit your Filing

Expected Results:
- [x] Green confirmation banner with print receipt link
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the Receipt of Filing document
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions



#### 3) Petitioner Files a Motion to Lift Stay of Proceedings across all cases in a consolidated group, document is filed appropriately in all cases in the group.

- Log in as a petitioner that has access to at least one case in a consolidated group
- File a document in one of the cases
- Be sure to select Motion to Lift Stay of Proceedings as the document type and be sure that the document name is reflected appropriately in the workflow
- Submit the filing

Expected Results
- [x] Green confirmation banner with print receipt link
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the Receipt of Filing document; all case docket numbers in the group are listed
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs for each case in the group
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions for each case in the group



#### 4) Petitioner files Motion for Leave to file and then selects the Motion to lift Stay of Proceedings.

- Log in as a petitioner that has access to a case
- File a document in the case
- Be sure to select Motion for Leave to File and then select Motion to Lift Stay of Proceedings
- Fill out the required fields and be sure that the document if titled correctly on each of the pages
- Submit the Filing

Expected Results:
- [x] Green confirmation banner with print receipt link
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the Receipt of Filing document, and the motion to lift stay is lodged
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions

*Repeat this test with a Motion for Leave to File



#### 5) Petitioner files a document where the Motion to Lift Stay of Proceedings is the secondary document, Motion appears in the document dropdown appropriately.

- Log in as a petitioner 
- navigate to one of the cases that you have already filed the motion to lift stay of proceedings on
- File a document in the case
- Be sure to select one of the documents from below (amended, response, etc.) as the document type, and then pick the Motion to lift stay from the secondary dropdown

Here is a list with some document types that result in the document picklist
- [x] Amended
- [x] Amendment
- [x] Certificate of Service
- [x] Response
- [x] Reply
- [x] Redacted
- [x] Sur-Reply
- [x] Others?

- Go through the filing process, checking the document title on each page and then submitting the document.

Expected Results:
- [x] Green confirmation banner with print receipt link
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the Receipt of Filing document
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions



#### 6) Test Cases 1-5 pass with a Private Practitioner and IRS Practitioner

Expected Results:
- [x] Passes



#### 7) Docket Clerk starts a paper filing, Motion to Lift Stay of Proceedings is available in the document Type dropdown picklist.

- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Paper Filing
- Upload or Scan a document, add in a date received.
- Click on the document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - Motion to Lift Stay of Proceedings is an available option.
- [x] **NEW FUNCTIONALITY** - User can type the selected event code (MLSP?) and the document title appears in the dropdown



#### 8) Docket clerk files a Motion to Lift Stay of Proceedings; Document appears correctly on the Docket Record.

- Continuing from the previous test
- Fill in the required fields on the add paper filing screen
- Click save and Serve
- Click Yes, Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent (if eService) and in Kibana logs
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions

*Repeat this test, but instead of saving and serving, save it first. Then go to the in progress tab of your QC and file the document from there.  Results should be the same.



#### 9) Docket Clerk files a Motion to Lift Stay of Proceedings across all cases in a consolidated group, document is filed appropriately in all cases in the group.

- Log in as a Docket Clerk
- Navigate to the lead case in a consolidated group
- Click Create
- Select Paper filing
- Upload or Scan a document, add in a date received
- Select Motion to Lift Stay of Proceedings as the document type
- Select who is filing the document and if there are objections
- Click Save and Serve
- Select All in the Consolidated group, and then select Yes, Serve

Expected Results:
- [x] Green confirmation banner 
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet for each case in the group
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs for each case in the group
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions for each case in the group



#### 10) Docket Clerk files a paper filing document where the Motion to Lift Stay of Proceedings is the secondary document, Motion appears in the document dropdown appropriately.

- Log in as a Docket Clerk
- Navigate to one of the cases that you have already filed the motion to lift stay of proceedings on
- Click on create
- Select Paper Filing
- Upload or Scan a document, add in a date received
- Be sure to select one of the documents from below (amended, response, etc.) as the document type, and then pick the Motion to lift stay from the secondary dropdown

Here is a list with some document types that result in the document picklist
- [x] Amended
- [x] Amendment
- [x] Certificate of Service
- [x] Response
- [x] Reply
- [x] Redacted
- [x] Sur-Reply
- [x] Others?

- Fill in the rest of the required fields
- Click Save and Serve

Expected Results:
- [x] Green confirmation banner 
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the service email that is sent and in Kibana logs
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions



#### 11) Docket clerk edits an existing document on the docket record; Document type picklist has Motion to Lift Stay of Proceedings as an option.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on the Edit button for a document on the docket record (not a Motion to Lift Stay of Proceedings - something else!)
- Click on the document type dropdown to change the document type

Expected Results:
- [x] **NEW FUNCTIONALITY** - Motion to Lift Stay of Proceedings is an available option.
- [x] **NEW FUNCTIONALITY** - User can type the selected event code (MLSP?) and the document title appears in the dropdown

**Part 2**
- Select Motion to Lift Stay of proceedings and click save

Expected Results
- [x] Green confirmation banner
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document Event Code is displayed correctly on the docket record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the printable docket Record
- [x] **NEW FUNCTIONALITY** - The document title is displayed correctly on the document coversheet
- [x] **NEW FUNCTIONALITY** - The Motion displays appropriately when the user Filters the docket record by motions



#### 12) Regression test

- [x] Judges can stamp a Motion to Lift Stay of Proceedings per normal
- [x] Document name is reflected appropriately in the case JSON
- [x] Document name can be attached as per normal in messages
- [x] Document name is reflected appropriately on QC pages/Message titles
