### ISSUE TITLE
Custom Case Report: Add "All Cases" Option

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8524]
As a Court user, to make it simpler to ensure I'm searching all cases in the system, I want an option to indicate that I need to search all cases.

The CCR has proven to be invaluable to Court users in datamining our case inventory in DAWSON. Currently, if one wishes to search the set of all cases in the system they must enter a date range that ensures the Start Date predates the earliest case filing date in DAWSON.

To make this search simpler to execute, we would like a way for the user to indicate that they want to search the entire collection rather than have to input a date range.
 
## Acceptance Criteria
* Instead of inputting a date range prior to running the Custom Case Report, a user can indicate that they wish to search all cases in DAWSON
* User can de-select indicator and enter a date range as usual prior to running the report
* When a user indicates they wish to search all cases in DAWSON they cannot input a Start/End date - either the indicator is set OR a date range is entered
* User can select additional report criteria after indicating they wish to search all cases prior to clicking Run Report
* When running a report after indicating they wish to search all cases, report captures result set using all cases in the system combined with any additional selected or defaulted criteria

## Tasks
- [x] Add radio button for all dates (UI adjustments)
- [x] Adjust API to work without date ranges
- [x] Verify validation works for when entering dates
- [x] Add/Update appropriate tests
- [x] Question(s) for UX: Do we need to add a "All Dates" radio button because we can search for all cases without the date ranges prescribed

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement 
- All cases is default? Not necessarily; should there be a default?
- Why are they searching all cases? versus a subset?  Is the problem more a 'they're usually searching for all so having to click into the date range selector is a lot of extra clicks' or 'we don't understand how to use the date range selector'? For Clerk of the Court and Chris, they're datamining
-

**Comment by swongCO** [comment]
**UX Notes**

- Change to the date picker functionality to allow input of date range, start or end date or no input for all dates
- Re-order inputs: Petition filing method and Case procedure first, then date fields, then filters and the rest
- Add "(optional)" to date field labels
- Keep Clear filters link functioning as is
- Primary btn is not disabled

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2pUQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39c4be87838784d1f29fdd405e9aa91164761bd8/Custom%20Case%20Report%20-%20default%20to%20all.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Custom Case Report; Case Created Start Date and Case Created End Date fields are below the Radio buttons for case procedure and Filing method.

- Log in as any Court User
- Click on the Reports menu
- Select Custom Case Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The radio buttons for Case Procedure and for Filing Method are now at the top of the page
 - [ ] **NEW FUNCTIONALITY** - The  Case Created Start Date and Case Created End date are now below the radio buttons and are optional


#### 2) Court user leaves the Date fields blank; Runs report; results include all cases.

- Continuing from the previous test
- Click on the "Run Report" button

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - All cases return in the search results



#### 3) Court user adds filters; Runs Report; results list displays filtered list appropriately.

- Continuing from the previous test
- Select a filter (or not) and click run report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays all cases appropriately (depending on the filters (or no filters) selected



#### 4) Court user inputs specific dates in the Date fields; Runs Report; results list displays cases within the date range appropriately.

- Continuing from the previous test
- Add valid dates into the date fields
- Select a filter (or not)
- Click Run Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays all cases appropriately (depending on the filters (or no filters) selected).


#### 5) Court user inputs only a start date; Leaves the end date empty; Results list displays cases from the start date to today's date

- Continuing from the previous test
- Delete the End date so that there is no data in this field
- Be sure that there is a start date
- Click Run Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays cases from the start date entered all the way up to today's date


#### 6) Court user inputs only an end date; leaves the start date empty; Results list displays cases from the beginning of cases in DAWSON to the date in the end date field.

- Continuing from the previous test
- Delete the start date so that there is no data in this field
- Be sure that there is an end date input in the field
- Click Run Report

Expected Results:
 - [ ] **NEW FUNCTIONALITY** - The results list displays cases from the first case entered into DAWSON up to the end date that was input.
 

#### 7) Regression test to ensure that the date picker validation still functions as per normal.

- [ ] Regression testing passes

**Comment by swongCO** [comment]
Updated UX notes based on convo with devs re complexity of previous design.

**Comment by cholly75** [comment]
@swongCO @katiecissell @ttlenard - court users liked the functionality but agreed that the instructions/design felt a little "off". If we're going to go with this solution in place of the original AC to reduce complexity then we want to either position the date fields as optional or filters in line with the rest of the UI or rationalize the UI/mechanism with the other date field selection options in the app.

**Comment by ttlenard** [comment]
Test cases in this story were written for the original design, so I was unable to complete the test cases above. I did test functionality as deployed, and it appears that the search is functioning appropriately.

I was able to search all dates (by not inputting anything), with only a start date, with only an end date, or with a date range.  I was also able to trigger validation errors on the date fields as appropriate.
