### ISSUE TITLE
Visibility Change for Practitioner-Filed Briefs

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8530]
As a practitioner, so that my brief documents are available for viewing to everyone, I need practitioner-filed briefs filed on or after 8/1/2023 to be viewable from the docket record to all users.

In an effort to increase transparency into the cases heard by the USTC, the Court is adopting a policy that all post-trial briefs filed by practitioners should be publicly available. This will be done on a prospective basis as of August 1, 2023 following a public notice in advance of this policy change. 

Briefs filed prior to 8/1/23 will not be in scope, and **cannot** be retroactively made visible.

This will apply solely to select brief event codes (see AC) filed by users with the Practitioner role in DAWSON at the time of filing and AMBR briefs (currently filed via paper only). Should the user transition to another role after filing, this will not affect the visibility of the brief. 

As all practitioners are required to e-file unless exempted by the Court (an extremely rare occurrence) we are comfortable applying this policy to e-filed briefs and AMBR briefs only for now.

This story will address e-filed briefs in specific; another story will address amicus briefs.

## Pre-Conditions
ustaxcourt/ef-cms#8420

## Acceptance Criteria
* Event codes designating briefs (see Notes below for listing of approved codes) e-filed by users with a role of Practitioner in DAWSON are visible to *all* users when viewing the docket record
* Visibility is determined by the role of the e-filing user at the time of filing
* This applies only to briefs filed on or after 8/1/2023; briefs filed prior to this date are not affected
* Sealed documents still obey sealing visibility rules, even when meeting the above criteria

## Notes
* The following briefs/event codes are in scope for this:
![image.png](https://images.zenhubusercontent.com/60e7a3b441280d0c68e72525/2c2940ce-15c8-4ce3-a981-8bee6a90ca80)
* Briefs still must be served prior to being visible on the docket record to public
* Lodged briefs are *never* available to the public 
* Stricken briefs are *never* available to the public
* Feature flag is optional if we can satisfy date criteria w/o it

## Tasks
- [x] Add constant for SERIATIM briefs in `EntityConstants`
- [x] Add business logic to docket entry entity to determine if document link should be shown based on if the user that filed the docket entry is a private practitioner
- [x] Add business logic to docket entry entity to determine if document link should be shown based on if the user that filed the docket entry is an irs practitioner
- [x] Add business logic to docket entry entity to determine if filing date >= 8/1/23
- [x] Use newly added docket entry property in `PublicCaseDetailHelper` 
- [x] Use newly added docket entry property in `formattedDocketEntries`
- [x] Check that this works for terminal user as well as the public, and non-associated external users  
- [x] Change POLICY_CHANGE_DATE to a database flag so it can be updated for testing
  - [x] get and set feature flag during public and reg gotoCaseDetailSequence
  - [x] use feature flags in computeds to determine visibilty instead of in entity
  - [x] removed outdated property and method from entities + tests (filedAfterPolicyChange date)
  - [x] Add script to change policy change date
  - [x] Add script to insert policy change date into dynamo deploy table
  - [x] update helper tests
  - [x] verify that scripts work as expected
- [x] DOD: integration test that filed before policy change doesn't show link

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Practitioner e-files a brief type document to a case prior to 8/1/2023; document is not viewable for the public or other logged in users that are not associated with the case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one of the cases from the my Cases Page (this assumes you already have an active case).
- Click on the File a Document button.
- Select a brief type of document (not a simultaneous type brief for this test) (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is 7/31/2023 (Need Dev determination on how we will test this date).
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results:
- [x] The brief type document that was filed is not an active hyperlink and cannot be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The brief type document that was filed does not have an active hyperlink and cannot be viewed by the logged in user that is not associated with the case.



#### 2) Practitioner e-files a brief type document to a case on 8/1/2023; brief is available as an active hyperlink on the docket record and can be viewed by the public or other logged in users.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one of the cases from the my Cases Page (this assumes you already have an active case).
- Click on the File a Document button.
- Select a brief type of document (not a simultaneous type brief for this test) (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on 8/1/2023 (Need Dev determination on how we will test this date).
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] **NEW FUNCTIONALITY** - The brief type document that was filed has an active hyperlink and can be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The brief type document that was filed has an active hyperlink and can be viewed by the logged in user that is not associated with the case.



#### 3) Practitioner e-files a brief type document to a case on 8/2/2023; brief is available as an active hyperlink on the docket record and can be viewed by the public or other logged in users.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one of the cases from the my Cases Page (this assumes you already have an active case).
- Click on the File a Document button.
- Select a brief type of document (not a simultaneous type brief for this test) (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on 8/2/2023 (Need Dev determination on how we will test this date).
- Ensure that the document is available on the docket record, there is an active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] **NEW FUNCTIONALITY** - The brief type document that was filed has an active hyperlink and can be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The brief type document that was filed has an active hyperlink and can be viewed by the logged in user that is not associated with the case.


#### 4) Legacy Brief-type documents filed prior to 8/1/2023 continue to NOT be available for viewing by the public or other logged in users not associated with the case.

- This is a regression test to ensure visibility of documents prior to 8/1 were not changed.

**Part 1**
- Navigate to DAWSON as a non-logged in user
- Search for a cases that have brief type documents filed on the case prior to this story

Expected Results:
- [x] Briefs on the docket record (simultaneous, seriatim, and amicus) do not have an active hyperlink, and are not available to be viewed by the public user.

**Part 2**
- Log into DAWSON as a user (be sure to test with private practitioner, IRS practitioner, and petitioner)
- Navigate to cases that have brief type documents filed on the case prior to this story

Expected Results:
- [x] Briefs on the docket record (simultaneous, seriatim, and amicus) do not have an active hyperlink, and are not available to be viewed by the logged in user.



#### 5) Docket clerk Seals (to the public) a brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or logged in users that are not associated with the case; Parties can still view the document.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the brief type documents that were filed on or after 8/1/23
- Select Seal to the Public
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed brief documents

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed brief document(s)

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it has an active hyperlink, and the document can still be viewed by the party that is associated with the case.



#### 6) Docket clerk Seals (to the public and parties to the case) a brief type document that was filed on a case on or after 8/1/23, document is not able to be viewed by the public or parties to the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case(s) that you used for the previous test cases
- Click the Seal link next to the brief type documents that were filed on or after 8/1/23
- Select Seal to the Public and parties to the case
- Next, search for the case(s) as the public non-logged in user.

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Navigate to the case(s) with the sealed brief documents

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the logged in user.

**Part 3**
- Log in as a party that is associated with the case
- Navigate to the case docket record for the case(s) with the sealed brief document(s)

Expected Results:
- [x] The brief type document(s) that was filed has a red lock icon next to the document title, it does not have an active hyperlink, and the document cannot be viewed by the party that is associated with the case.



#### 7) Practitioner files a Simultaneous type brief on or after 8/1/23, document does not have an active hyperlink, and is not available to be viewed by the public or logged in users that are not associated with the case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one of the cases from the my Cases Page (this assumes you already have an active case).
- Click on the File a Document button.
- Select a simultaneous brief type of document (refer to the A/C).
- Upload a PDF
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on or after 8/1/2023 (Need Dev determination on how we will test this date).
- Ensure that the document is available on the docket record, but there is not an active hyperlink, and you cannot view the document since it is not yet served.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON.
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] The simultaneous brief type document that was filed should not yet be available as a hyperlink and cannot be viewed by the public non-logged in user, as it must manually be QC'd first by a docket clerk. 

**Part 2**
- Log in as a Practitioner or Petitioner that is not associated with the case
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The simultaneous brief type document that was filed should not yet be available as a hyperlink, and cannot be viewed by the logged in user, as it must manually be QC'd first by a docket clerk. 



#### 8) Docket Clerk Serves the Simultaneous type brief; document now has an active hyperlink and is available to be viewed by the public and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case from the previous test that you filed a simultaneous brief.
- Click on the simultaneous brief document link and serve the document.
- Next, Navigate to the case as a non-logged in public user.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The simultaneous brief type document that was filed has a hyperlink and can now be viewed by the non-logged in public user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the simultaneous document on.
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The simultaneous brief type document that was filed has as a hyperlink and can be viewed by the logged in user.



#### 9) Docket Clerk adds a paper filed amicus brief on or after 8/1/23 to the docket record; Amicus brief does not have an active hyperlink and is not viewable to the public or logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to a case
- Click on Create, and select paper filing
- Upload a document
- Select Amicus Brief as the document type and add it to the docket record
- Next, navigate to this case as a public non-logged in user

Expected Results:
- [ ] The brief type document that was filed does not have an active hyperlink and cannot be viewed by the public non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [ ] The brief type document that was filed does not have an active hyperlink and cannot be viewed by the private practitioner that is not associated with the case.



#### 10) Practitioner files a motion for leave to file or a motion for leave to file out of time and selects a brief document for the file they are requesting leave for on or after 8/1/23; lodged brief document is not viewable to the public or logged in users that are not associated with the case.

**Part 1**
- Log in as a Private Practitioner
- Click on the docket number of one of the cases from the my Cases Page (this assumes you already have an active case).
- Click on the File a Document button.
- Select a motion for leave or Motion for leave to file out of time type of document.
- Select a brief type of document (not a simultaneous type brief for this test) (refer to the A/C).
- Upload the motion for leave PDF and the brief document
- Fill out the required fields 
- Submit the filing (be sure that the date that you are filing this document is on or after 8/1/2023 (Need Dev determination on how we will test this date).
- Ensure that the document is available on the docket record, there is active hyperlink, and you can view the document.
- Take note of the docket number that you just filed the document on.
- Next, log out of DAWSON.
- As a public, non-logged in user, search for the case docket number you just filed the document on.
- Review the docket record

Expected Results
- [x] The lodged brief type document that was filed should not yet be available as a hyperlink and cannot be viewed by the public non-logged in user. 

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] The lodged brief type document that was filed should not yet be available as a hyperlink and cannot be viewed by the logged in user.

**Part 3**
- Navigate to the case as the public terminal user

Expected Results:
- [x] The lodged brief type document that was filed is available as a hyperlink and can be viewed by the terminal user.



#### 11) Docket clerk QC's the motion and brief from the previous test case; edits the document metadata and removes the lodged status from the brief; brief document has an active hyperlink and is available for viewing on the docket record to public users and logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk
- Navigate to the case that has the lodged brief document
- QC the lodged document
- Click the edit link on the docket record for the lodged document
- Change the radio button to File, and then save.
- Next, navigate to the case as public, non-logged in user

Expected Results:
- [x] **NEW FUNCTIONALITY** - The previously lodged brief type document that was filed is available as a hyperlink and can be viewed by the non-logged in user.

**Part 2**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number you just filed the document on.
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The previously lodged brief type document that was filed has a hyperlink and can be viewed by the logged in user.



#### 12) Docket Clerk Strikes a Brief document that is on the docket record that was filed on or after 8/1/23, brief document is no longer available for viewing by public or logged in users that are not associated with the case.

**Part 1**
- Log in as a docket clerk.
- Navigate to a case that has a brief type document that was filed on or after 8/1/23.
- Strike the document.
- Next, log in as the practitioner that filed the document
- Navigate to the case

Expected Results:
- [x] The stricken brief document does not have a hyperlink and cannot be viewed by the party.

**Part 2**
- Next, as a public non-logged in user, search for the case with the stricken brief document on the docket record

Expected Results:
- [x] The stricken brief document does not have a hyperlink and cannot be viewed by the non-logged in user.

**Part 3**
- Log in as user that is not associated with the case (petitioner, private practitioner, IRS Practitioner)
- Search for the case docket number with the stricken the brief document.
- Review the docket record.

Expected Results:
- [x] The stricken brief document does not have a hyperlink and cannot be viewed by the logged in user.



#### 13) Repeat test cases 1 - 11 with the IRS Practitioner role.

- [x] Test Case 1 passes with the IRS Practitioner
- [x] Test Case 2 passes with the IRS Practitioner
- [x] Test Case 3 passes with the IRS Practitioner
- [x] Test Case 4 passes with the IRS Practitioner
- [x] Test Case 5 passes with the IRS Practitioner
- [x] Test Case 6 passes with the IRS Practitioner
- [x] Test Case 7 passes with the IRS Practitioner
- [x] Test Case 8 passes with the IRS Practitioner
- [ ] Test Case 9 passes with the IRS Practitioner
- [x] Test Case 10 passes with the IRS Practitioner
- [x] Test Case 11 passes with the IRS Practitioner
- [x] Test Case 12 passes with the IRS Practitioner



#### 14) If a FF is implemented with this story, be sure to test with FF off.

**Comment by rosiehsmith** [comment]
In order to test this feature, the policy change date is 5/1/2023 on the `test` environment.

**Comment by mrinsin** [comment]
To add/change the policy change date to the deploy table of an env, run the script as follows : `./set-document-policy-change-date.sh 2023-08-01 exp2`. The first argument is the date to use as the effective policy change date (in exactly the same format specified). When a policy change date arg is not passed in, the value defaults to 2023-08-01 (date chosen by court).

cc @mmarcotte @jimlerza

**Comment by ttlenard** [comment]
@rosiehsmith I went to exp3 to do a quick test, but looks like things still aren't quite right?  I've got this case (331-23) set up and I'm not seeing the hyperlinks. Index 5 was filed by IRS practitioner 6, and index 6 was by Private Practitioner 6.  Neither of the entries has a hyperlink when viewing the case as a public non-logged in user.
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/bf3a42bb-1924-492d-9f05-6f5d847eabc3)

**Comment by ttlenard** [comment]
@rosiehsmith Looks like the visibility change date made it so that the public terminal user can no longer view brief type documents prior to the policy date.  This policy change shouldn't affect the visibility of brief documents for the public terminal user.

Note that this probably also affects the two other visibility stories (#10037 and ustaxcourt/ef-cms#8450).

**Comment by ttlenard** [comment]
Visibility by terminal user fixed. Thank you!
