### ISSUE TITLE
New Docket Entry: NOTT - 30 Day Notice of Trial

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8541]
As a docket clerk, so that I can enter a 30-day Notice of Trial to pro se petitioners, I need a new docket entry event code.

The Court will begin generating and issuing a new Notice of Trial 30 days prior to a pro se petitioner's scheduled trial session. To accommodate this, we would like these notices to have a unique event code on the docket record and the capability to enter as such on the record.

Further stories will address the capability to generate these documents in DAWSON. 

## Acceptance Criteria
* Docket clerks can upload a PDF and docket as a "30-Day Notice of Trial"
* Event code for these docket entries should be "NOTT"
* At the time of docketing the NOTT, the clerk MUST specify:
  - Date
  - Place of Trial (using the standard location dropdown selections)
* Once docketed, the description of the entry in the "Filings and Proceedings" column reads: "30 Day Notice of Trial on [DATE] at [CITY, STATE]
  - The [DATE] token is replaced with the date entered at the time of docketing the entry
  - The [CITY, STATE] token is replaced with the location information entered at the time of docketing the entry
* NOTT entries are served on all parties

## Tasks
- [x] Add NOTT to CourtIssuedEventCodes
- [x] Persist Trial Location on editing docket entry (also unpopulated on NTD?)
- [x] Question: test case 6 mentions editing the document title, however is that a field that's required for this event code? a somewhat similar event code, NTD (notice of trial), doesn't have a description field. A: make it like NTD, so no free text field

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
- Document type, date and trial location are required fields.
- Signature is not required for NOTT.
- Document type list: 30 day notice of trial should appear after notice of trial in list
- When filtering document type, numbered items should be top of the filtered list.
- Current validation rules/errors should be fine for trial date, trial location and document type.
- When editing, filed date should be on top![Add NTT entry.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/1477821c-7f66-4cee-915f-1852996c2399)![Edit NTT Entry.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/3b83ed44-023c-45f4-97f1-91e1fffafd04)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk adds a document to the docket record; New 30-Day Notice of Trial document is available in the Document type dropdown.

- Log in as a docket clerk
- Navigate to a case
- Case should have a document in drafts that was uploaded by another clerk, or you can upload a PDF as the docket clerk
- Click on the Add docket entry link from the document view
- Click on the Document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a new document type labeled 30-Day Notice of Trial.
- [x] **NEW FUNCTIONALITY** - When not filtering, the 30-Day Notice of Trial is below the Notice of Trial document in the list order.
- [x] **NEW FUNCTIONALITY** - Clerk can type in NOTT in the dropdown and the 30-Day Notice of Trial will display

*Repeat this test with the CotC and CSS roles.



#### 2) Docket Clerk selects 30-Day Notice of Trial document from the Document Type dropdown; Trial Date and Trial Location fields are required.

- Continuing from the previous test
- Select the 30-Day Notice of Trial from the document type dropdown
- Click the Save and Serve button

Expected Results:
- [x] Validation error message for Trial Date and Trial Location field
- [x] No signature validation error message for 30 Day Notice of Trial (this document shouldn't require a signature)

*Repeat this test with the CotC and CSS roles.


#### 3) Docket Clerk inputs required fields for 30-Day Notice of Trial document; Saves and Serves Document.

- Continuing from the previous test
- Input values for the Trial date and place of trial
- Click Save and Serve
- Click Yes, Serve (ensure that the document title is correct on this pop-up confirmation modal)

Expected Results
- [x] Print for paper service if Petitioner has paper service.
- [x] Green confirmation banner indicating that the document was served.
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is NOTT
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "30 Day Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input in the previous test
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] **NEW FUNCTIONALITY** - NOTT is served successfully on all Parties.
- [x] All other fields on the docket record are as per normal.

*Repeat this test with the CotC and CSS roles.


#### 4) Docket clerk adds a 30-Day Notice of trial to the docket record; Saves entry, does not Serve; Document is saved appropriately to the docket record.

- Log in as a Docket Clerk
- Navigate to a case
- Upload a PDF and add the docket entry
- Select 30-Day Notice of Trial
- Input a trial date and trial location
- Click Save Entry

Expected Results:
- [x] Green confirmation banner indicating that the document was saved
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is NOTT
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "30 Day Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input for trial date 
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] Entry indicates "Not Served", and is highlighted in yellow.
- [x] No index number, no filed date, no value in the service column.

*Repeat this test with the CotC and CSS roles.


#### 5) Docket Clerk serves the previously saved NOTT, Docket record reflects information correctly.

- Continuing from the previous test
- Click on the document link for the 30-Day Notice of Trial on the docket record
- From the document view, click the Serve link
- Click Yes, Serve (ensure that the document title is correct on this pop-up confirmation modal)

Expected Results
- [x] Print for paper service if Petitioner has paper service.
- [x] Green confirmation banner indicating that the document was served.
- [x] **NEW FUNCTIONALITY** - Event Code on the docket record is NOTT
- [x] **NEW FUNCTIONALITY** - Filings and Proceedings column displays "30-Day Notice of Trial on [DATE] at [CITY, STATE]".
- [x] **NEW FUNCTIONALITY** - The [DATE] is the value that you input in the previous test
- [x] **NEW FUNCTIONALITY** - The [CITY, STATE] is the value that you entered in the previous test.
- [x] **NEW FUNCTIONALITY** - NOTT is served successfully on all Parties.
- [x] All other fields on the docket record are as per normal.

*Repeat this test with the CotC and CSS roles.


#### 6) Docket Clerk edits the document metadata for a 30-Day Notice of Trial; Document saves appropriately on the docket record

- Continuing from the previous test
- Click on the edit link on one of the 30-Day Notice of Trial documents that you just served.
- Update the Document Type
- Click Save

Expected Results:
- [ ] Green confirmation banner indicating Docket entry changes saved. 
- [ ] Document title and Event code are updated on the docket record

*Repeat this test by editing other metadata

- [x] Filed date
- [x] Date of trial
- [x] Trial Location
- [x] Adding an action
- [x] Striking the document
- [x] Adding the document to the pending report
     - [x] Pending report item is reflected on the tracked items tab in the case
     - [x] Case appears on the Pending Report

*Repeat this test with the CotC and CSS roles.


#### 7) Docket Clerk seals the 30-Day Notice of Trial; Document seals appropriately.

- Continuing from the previous test
- Click on the Seal link on the docket record
- Indicate the seal level that you would like
- Click Seal

Expected Results:
- [x] Document has the red lock icon
- [x] Document is no longer accessible for the parties that you indicated

*Be sure that you test this with both seal levels
*Repeat this test with the CotC and the CSS roles.



#### 8) Terminal user accesses case with a 30-Day Notice of Trial that has been docketed; User can view the document.

- Access DAWSON as the Terminal user
- Navigate to a case that has a 30-Day Notice of Trial

Expected Results:
- [x] Terminal user can click on the link and view the document.



#### 9) Docket clerk multi-dockets the 30-Day Notice of Trial; Document is filed and served appropriately.

- Log in as a docket clerk
- Navigate to the lead case in a consolidated group
- Upload a PDF and add the docket entry
- Select 30-Day Notice of Trial
- Input a date and trial location
- Click Save and Serve

Expected Results
- [x] Consolidated case modal appears
- [x] Docket clerk can select all or some cases in the group
- [x] After service, print for paper service appears (if P has paper service)
- [x] The 30-Day Notice of Trial is served appropriately across all cases that you selected in the Consolidated Group.


*Repeat this test with the CotC and the CSS roles.

**Comment by rosiehsmith** [comment]
Noticed a pre-existing issue on editing docket entries of event code NTD which matches the scenario type of this new docket entry, NOTT. The generated document title does not populate with the trial date or trial location. Going to roll that fix into this story.
See example: https://app.stg.ef-cms.ustaxcourt.gov/case-detail/103-20/docket-entry/5/edit-meta
![image](https://user-images.githubusercontent.com/16403861/230996305-80b8f943-8c7c-41fe-863c-5679e0548aec.png)

**Comment by swongCO** [comment]
**UX Review feedback**
On both the add and edit docket entry pages, the date field label should be "Trial date". They currently say "Date". <s>There will be a design debt story to change this for Notice of Trial as well.</s> Change was also made to Notice of Trial document type.

**Comment by ttlenard** [comment]
All tests pass.  Thanks!
