### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8542]
As a petitions clerk, so that I can easily see when NOTT notices should be issued, I need an indicator on the trial session view that tells me when the date to issue a NOTT is imminent.

The Court will begin generating and issuing a new Notice of Trial 30 days prior to a pro se petitioner's scheduled trial session. To accommodate this, we would like these notices to have a unique event code on the docket record and the capability to enter as such on the record.

In order to accommodate the time required for paper service and those NOTTs that will be manually docketed, we would like a signifier 5 days prior to the date when the NOTT should be issued. The signifier should be visible on the trial session view and the session detail screen, and should be able to be manually dismissed/cleared by a clerk.

## Acceptance Criteria
* When the scheduled date for a trial is 35 calendar days from the current date, a signifier is present for that trial session on the Trial Sessions views and Trial Detail screen.
* The clerk can permanently dismiss the signifier so that it no longer appears for that trial session to anyone 
  - ONLY a petitions clerk, CotC, or CSS role can clear the signifier permanently
* Once the trial session start date is 29 days from the current date, the signifier disappears from the Trial Session in the Trial Session views

## Tasks
- [x] Add logic to trial session helper for displaying notice - https://github.com/flexion/ef-cms/pull/10023
- [x] Add UI for signifier on trial sessions table - https://github.com/flexion/ef-cms/pull/10023
- [x] UI for signifier on trial sessions detail - https://github.com/flexion/ef-cms/pull/10023
- [x] show modal on dismiss of signifier - https://github.com/flexion/ef-cms/pull/10032
- [x] persist alert dismissal -  https://github.com/flexion/ef-cms/pull/10032
- [x] roles allowed to dismiss modal - https://github.com/flexion/ef-cms/pull/10032
- [x] DOD: Integration test - Rosie and Mrinalini https://github.com/flexion/ef-cms/pull/10038

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [x] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
[Figma file with clean and annotated mockups](https://www.figma.com/file/wD49rBEMg76LorVeUf4YxX/USTC-%7C-9969-%7C-Trial-Session-View%3A-NOTT-Reminder?node-id=58%3A2595&t=5Q0yZKCbQIOUBlA6-1)

**Comment by katiecissell** [comment]
Mockups:![Hover tooltip for clock icon.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/09077275-b09e-43a9-bb8e-e857bbe37ab3)![Warning banner.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/fa978631-39fd-4726-b142-dea90bb0917c)![Confirmation modal.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/fecec4a9-06ab-4975-91b1-ea6b072ed34a)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk accesses the Open Trial Sessions page; Calendared trial sessions that are between 30-35 calendar days from the scheduled session have a new clock icon next to the date.

- Log in as a  Petitions Clerk.
- Click on the Trial Sessions tab.
- Be sure that you are on the Open Tab.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Sessions that are between 30 - 35 calendar days now have a clock icon next to the session date.
- [x] **NEW FUNCTIONALITY** - If you hover your cursor over the clock icon, a tooltip states "The 30-day notice is due before xx/xx/xx (where the date = the 30 day mark).

*Repeat this test with a CSS and CotC user



#### 2) Petitions Clerk opens one of the trial sessions that has a new clock icon; new yellow warning banner is present underneath the Session Information header.

- Continuing from the previous test.
- Click on the City, State link for a trial session that has the new clock icon.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Yellow warning banner is present under the Session Information header; text in the banner matches what is in the mockups above.
- [x] **NEW FUNCTIONALITY** - Link is present in the banner that displays "Yes, served".

*Repeat this test with a CSS and CotC user



#### 3) Clerk clicks the "Yes, served" link in the yellow warning banner; pop-up modal displays asking for confirmation.

- Continuing from the previous test.
- Click on the "Yes, served" link in the yellow banner.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Pop-up modal displays; text in the modal displays what is in the mockup up above.

*Repeat this test with a CSS and CotC user



#### 4) Clerk cancels out of the pop-up modal; clerk is navigated back to the Session information page for the trial session.

- Continuing from the previous test.
- Click the cancel button.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Clerk is navigated back to the Session information page.
- [x] **NEW FUNCTIONALITY** - Yellow warning banner remains on the session information page.
- [x] **NEW FUNCTIONALITY** - On the Trial Sessions page, the clock icon and tooltip is still displayed.

*Repeat this test with a CSS and CotC user



#### 5) Clerk selects "Yes" in the pop-up modal; Yellow warning banner disappears, clock icon is no longer displayed on the Trial Sessions page.

- Continuing from the previous test.
- Click on the City, State link for the session with the clock icon.
- Click on the Yes, Served link in the yellow warning banner.
- Click on the Yes button in the pop-up modal.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Clerk is navigated back to the Session information page.
- [x] **NEW FUNCTIONALITY** - Yellow warning banner is no longer present on the page.
- [x] **NEW FUNCTIONALITY** - On the Trial Sessions page, the clock icon and tooltip is no longer displayed for the session.

*Repeat this test with a CSS and CotC user



#### 6) Other Court Staff are able to see the 30 day notice warning banner and clock icon, but are unable to clear the yellow warning banner from view.

- Log in as any Court user besides Petitions Clerk, CSS, or CotC.
- Click on the Trial Sessions tab.
- Click on the City, State of a session that has the new clock icon.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Yellow warning banner is present under the Session Information header; text in the banner matches what is in the mockups above.
- [x] **NEW FUNCTIONALITY** - Clerk is unable to dismiss the warning banner.

*Be sure to repeat this with all of the other court roles (besides Petitions clerk, CSS, or CotC) to ensure that the warning banner is not dismissible  


#### 7) Petitions Clerk sets a calendar, schedules the start date to 36 days from today; The following day, as the Petitions clerk, check the Trial Sessions page; New clock icon and warning banner are present.

This test case has some set up:

- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 36 days from today
- Select eligible cases
- Set the calendar

The next day...
- Log in as the Petitions Clerk again
- Click on the Trial Sessions Page
- Find the trial session that you created yesterday on the Open tab

Expected Results:
- [x] Test cases 1-6 pass


*Repeat this test with a CSS and CotC User

#### 8) Petitions Clerk sets a calendar, schedules the start date to 30 days from today; The clock icon and yellow warning banner are present.

- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 30 days from today
- Select eligible cases
- Set the calendar

Expected Results:
- [x] Test cases 1-6 pass

*Repeat this test with a CSS and CotC User


#### 9) Petitions Clerk sees the clock icon and yellow warning banner for a session that is 30 days from today; The following day the clerk views the same session; Clock icon and yellow warning banner are no longer present.

This test case has some set up:
- Log in as a Petitions Clerk
- Create a new Trial Session that has a start date of 30 days from today
- Select eligible cases
- Set the calendar
- The clock icon and the yellow warning banner should be present

The next day...
- Log in as a Petitions Clerk
- Click on the Trial Sessions Page
- Find the Trial Session from above

Expected Results:
- [x] **NEW FUNCTIONALITY** - The clock icon is no longer present on the trial session page
- [x] **NEW FUNCTIONALITY** - The yellow warning banner is no longer present on the Session information page.

*Repeat this test with a CSS and CotC User

**Comment by katiecissell** [comment]
Chatted with Mrinalini, we decided alert will use current default width so text will be a single line. (Mocks show double and a custom width so ignore that part.)

**Comment by rosiehsmith** [comment]
Adding myself to this in case anything else is needed to push it over the line while Mrinalini will be out of office in the next few days.

**Comment by ttlenard** [comment]
@rosiehsmith @mrinsin all tests pass. Thank you!

**Comment by rosiehsmith** [comment]
Documenting a couple clarifications based on review:
- The NOTT reminder will display during the 5 day buffer 31-35 days before the trial, as well as the 30th day before the trial. e.g. using [this calculator](https://www.timeanddate.com/date/durationresult.html?m1=5&d1=17&y1=2023&m2=6&d2=15&y2=2023&ti=on), the 30th day before a trial starting 6/15/23 would be 5/17/23. The 5 days preceding that include 5/12-5/16/23 (inclusive).
- Considering the 30th day before the trial is included in this range, the language of the banner was changed to "30 day trial notices are due **by** {30 days before trial start date}" - swapping "before" with "by"
