### ISSUE TITLE
Issue 30 Day Notice of Trial

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8543]
As a clerk, so that I don't have to manually docket NOTTs, I need to be able to easily generate and serve all NOTTs for a given trial session.

The recently added NOTT document is intended to be generated and served to pro se petitioners ~30 days prior to their trial date. To facilitate this, we would like to be able to generate and serve these documents automatically without needing to create, upload, and docket these individually for each eligible petitioner with a case attached to the trial session.

We will have 3 versions of this notice with different text depending on the Proceeding Type/Location values of the trial session. 

## Acceptance Criteria
* A clerk can generate NOTTs for all eligible pro se petitioners associated with cases on a trial session for which the "NOTT due" icon appears (see ustaxcourt/ef-cms#8542).
* Clerk can generate NOTTs for all eligible pro se petitioners in a single operation
* NOTT is generated with attached text and tokens (see details below)
* Appropriate clinic letters are attached to NOTT
* NOTTs are immediately docketed and served with the description "30 Day Notice of Trial on [DATE] at [LOCATION]"
  - Electronic service where applicable
  - Paper notices generated for printing where applicable
* If the Trial Session type proceeding type is "**In Person**", generate the NOTT text using the In Person Notice linked in the Notes below
  - NOTT caption populates the correct information based on the case/petitioner information
  - NOTT Trial At and Judge boxes populate the correct information based on the Trial Session information
  -  NOTT token [DAY, DATE] populates with the day of the week and the date the trial session is scheduled to start.
* If the Trial Session type proceeding type is "**Remote**", and the Location is NOT "**Standalone Remote**" generate the NOTT text using the Remote person Notice linked in the Notes below
  - NOTT caption populates the correct information based on the case/petitioner information
  - NOTT Trial At and Judge boxes populate the correct information based on the Trial Session information
* If the Trial Session proceeding type is "**Remote**", and the Location IS "**Standalone Remote**", generate the NOTT text using the Standalone Remote Notice linked in the Notes below
  - NOTT caption populates the correct information based on the case/petitioner information
  - NOTT Trial At and Judge boxes populate the correct information based on the Trial Session information

## Notes
[https://app.zenhub.com/files/152320868/51a0f4a3-92b2-4d4f-b609-09c1ca112bcf/download]
(In Person Notice)

[https://app.zenhub.com/files/152320868/83113f8c-5812-449b-9073-b5ce995f9c47/download](https://app.zenhub.com/files/152320868/83113f8c-5812-449b-9073-b5ce995f9c47/download)
(Remote proceedings)

[https://app.zenhub.com/files/152320868/976cabc0-834b-4b27-b992-47c1475b0bd3/download]
(Standalone Remote)

## Tasks
- [ ] DOD: trial session can ONLY be calendared when it has at least one case on the docket, except for standalone remote trial sessions

## Questions
- What should the "title" be on these generated pdfs? In the examples the title is "Notice". - Chris will get back to us after checking with the court
- Should the clerk of the court signature text be center or left justified? - Left justified
- Should the judge information box include the chambers phone number? A few other notices (NoticeOfChangeToInPersonProceeding, NoticeOfChangeToRemoteProceeding) do so, should we standardize that?

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [ ] Verify that language for docket record for internal users and external users is identical
 - [ ] New screens have been added to pa11y scripts
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [ ] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [ ] Interactors should validate entities before calling persistence methods
 - [ ] Code refactored for clarity and to remove any known technical debt
 - [ ] Acceptance criteria for the story has been met
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Expectation for the NOTT reminder, automatically go away? Ask users.

Why not just do it automatically? What are the negatives of automatically doing it? Case services want eyes on them; also have to consider paper service flow

Of the three types of notice/trial sets, which is most common or most rare? Standalone remote is rarer, one or two per term

User type - does this include both docket and petitions/calendar clerks? any other type? petitions, cotc, cs supervisor

Paper service - do we want to allow clerks to print them at a later time (printer issues, internet dies)? yes but not with this story; currently Tenille or Mike/Jim would need to pull them out and provide them if the user exits the screen

**Comment by katiecissell** [comment]
- People without the power to dismiss the notice/generate notices will have no UI changes.
- No changes to the clock icon or tooltip
- People who CAN dismiss notice and generate notices will see a 'serve/dismiss' option (this replaces the 'Yes, Served' button.
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/4ae30868-ab34-4a66-b51c-e5384a0c00e6)
- When the "Serve/Dismiss' button is clicked a modal will display. The document title should display the correct location and date.
  ![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/8012996d-cad3-4bac-8730-437380bb6c90)
- Clicking Serve should display a progress spinner/banner (essentially what Cody just did with[10022](https://app.zenhub.com/workspaces/flexionef-cms-5bbe4bed4b5806bc2bec65d3/issues/gh/flexion/ef-cms/10022)) as it generates the PDF, sends them electronically, adds the notices to each of the dockets (Event code NOTT and identical to the notice of trial docket entry except with the words 30 Day at the beginning of it) and finally presents a PDF for printing the paper notices (with the correct information and clinic letters, mockup just shows lorem ipsum placeholder text)
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/0ac446c2-d37b-4cfe-8c81-9a54877feeff)
- After printing, the user will click the 'Printing Complete' button and be taken back to the session info page with the reminder banner still visible.
- If the user clicks to 'Dismiss Reminder" the banner and clock icons will disappear for that specific trial. 
- Clicking cancel will close the modal with no other action taken

[Figma File](https://www.figma.com/file/wD49rBEMg76LorVeUf4YxX/USTC-%7C-9969-%7C-Trial-Session-View%3A-NOTT-Reminder?type=design&node-id=150%3A1677&t=ZeFO1NacMqKf2SJ5-1)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Clerk navigates to an In Person trial session with a 30 day NOTT Reminder; Clicks the Serve/Dismiss link; Serves the Notices; Print for paper Service displays the Notices + Clinic Letters for Paper Pro Se Parties only.

- This test requires some set up
- Log in as a Petitions Clerk
- Click on Trial Sessions 
- Click on the City, State link for an In Person trial session that has a clock icon for the 30 Day Notice reminder.
- Ensure that the City has a Clinic Letter in S3 for the Session type (small/regular)
     - If it is a regular session, you will ensure that the appropriate regular clinic letter is attached to the notice
     - If it is a small session, you will ensure that the appropriate small clinic letter is attached to the notice
     - If it is a hybrid session, you will ensure that for regular cases, a regular clinic letter is attached, and for small cases a small clinic letter is attached.
- You will need to review a handful of the cases on the trial session that has the 30 day reminder to understand who should/shouldn't be receiving service of the NOTT, and which cases the NOTT should NOT docketed on.
- Here are the things to Ensure. 
     - [ ] Scenario 1 - Take note of a case docket number where there is a Paper Pro Se Petitioner
     - [ ] Scenario 2 - Take note of a case docket number where there is a Electronic Pro Se Petitioner
     - [ ] Scenario 3 - Take note of a case docket number where there is a Represented Petitioner
     - [ ] Scenario 4 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 5 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 6 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 7 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 8 - Take note of a case docket number where there is a Represented Petitioner and Spouse 
     - [ ] Scenario 9 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Same Address)
     - [ ] Scenario 10 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Different Address)
     - [ ] Scenario 11 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Same Address)
     - [ ] Scenario 12 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Different Address)
- Once you have noted the Case docket numbers for each of the scenarios above, the test is ready
- Click on Serve/Dismiss link
- Ensure that the title of the document in the modal is displaying the correct Location and date of the trial
- Click on the Yes, Serve button

Expected Results:
- [ ] The Generating Notices Message appears with a progress bar
- [x] The Generating Paper PDF message appears with a progress bar
- [x] The Print for Paper Service screen displays (You may want to save it for checking)
- [x] Take note of the docket numbers and the contents of what gets mailed in the Print for paper service doc
     - [x] Scenario 1 - There is an address coversheet, the In Person 30 day Notice of Trial document, and the appropriate Clinic Letter 
     - [x] Scenario 2 - There is no print for paper service doc for this
     - [x] Scenario 3 - There is no print for paper service doc for this 
     - [x] Scenario 4 - There is an address coversheet, the In Person 30 day Notice of Trial document, and the appropriate Clinic Letter for BOTH Petitioners
     - [x] Scenario 5 - There is an address coversheet, the In Person 30 day Notice of Trial document, and the appropriate Clinic Letter for BOTH Petitioners 
     - [x] Scenario 6 - There is no print for paper service doc for this
     - [x] Scenario 7 - There is no print for paper service doc for this
     - [x] Scenario 8 - There is no print for paper service doc for this
     - [x] Scenario 9 - There is an address coversheet, the In Person 30 day Notice of Trial document and the appropriate Clinic Letter for the Unrepresented Spouse only
     - [x] Scenario 10 - There is an address coversheet, the In Person 30 day Notice of Trial document and the appropriate Clinic Letter for the Unrepresented Spouse only
     - [x] Scenario 11 - There is no print for paper service doc for this
     - [x] Scenario 12 - There is no print for paper service doc for this
- [x] The In Person 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption is populated with the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes are populated with the correct information based on the Trial Session information
     - [x] NOTT token [DAY, DATE] is populated with the day of the week and the date the trial session is scheduled to start.



#### 2) 30 Day Notice of Trial is added to the Docket Record for Cases with Pro Se Petitioners, Not on docket record for Cases with Represented Petitioners

- Continuing from the previous test
- Click the Printing Complete button on the print for paper service
- Ensure that you remain on the Trial Session page, and that the reminder banner is still present on the screen. Do not dismiss the banner at this time (we will do this in a later test).
- Open a new tab to view the case Docket numbers of the Cases that you took note of for the scenarios above

Expected Results
- [x] There is a document on the docket record for Scenarios 1, 2, 4, 5, 6, 7, 9, 10, 11, 12 
     - [x] Filed date is today's date
     - [x] Event Code is NOTT
     - [x] Document Title is 30 Day Notice of Trial on [DATE] at [LOCATION]
     - [x] Page number is correctly displayed
     - [x] Filed by and Action column is blank
     - [x] Served date is today's date
     - [x] Parties code is P
     - [x] Edit/Seal links are available (for docket clerks, CoTC, and CSS only)
- [x] There is no NOTT document on the docket record for scenario 3, 8 (Represented Petitioner(s).
- [x] When viewing the document, the In Person 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption is populated with the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes are populated with the correct information based on the Trial Session information
     - [x] NOTT token [DAY, DATE] is populated with the day of the week and the date the trial session is scheduled to start.



#### 3) Electronic Service was sent to Electronic Pro Se Petitioners; Electronic Service was not sent to represented Petitioner(s).

- Continuing from the previous test
- Navigate to Kibana
- Ensure that you adjust the time to narrow it down to the timeline that you sent the notices
- Add "Bulk" in the search bar and click Refresh

Expected Results:
- [x] There are log entries showing electronic service for the petitioners email addresses for scenarios 2, 6, 7, 11, 12
- [x] For Scenario 6, 7 both Petitioner and Spouse received a service email
- [x] There are not any service emails sent to Counsel (Private or IRS) on any of these cases, only the Electronic Pro Se Petitioners 



#### 4) Clerk navigates to a Remote (NOT STANALONE REMOTE) trial session with a 30 day NOTT Reminder; Clicks the Serve/Dismiss link; Serves the Notices; Print for paper Service displays the Notices + Clinic Letters for Paper Pro Se Parties only.

- This test requires some set up
- Log in as a Petitions Clerk
- Click on Trial Sessions 
- Click on the City, State link for a Remote trial session that has a clock icon for the 30 Day Notice reminder.
- Ensure that the City has a Clinic Letter in S3 for the Session type (small/regular)
     - If it is a regular session, you will ensure that the appropriate regular clinic letter is attached to the notice
     - If it is a small session, you will ensure that the appropriate small clinic letter is attached to the notice
     - If it is a hybrid session, you will ensure that for regular cases, a regular clinic letter is attached, and for small cases a small clinic letter is attached.
- You will need to review a handful of the cases on the trial session that has the 30 day reminder to understand who should/shouldn't be receiving service of the NOTT, and which cases the NOTT should NOT docketed on.
- Here are the things to Ensure. 
     - [ ] Scenario 1 - Take note of a case docket number where there is a Paper Pro Se Petitioner
     - [ ] Scenario 2 - Take note of a case docket number where there is a Electronic Pro Se Petitioner
     - [ ] Scenario 3 - Take note of a case docket number where there is a Represented Petitioner
     - [ ] Scenario 4 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 5 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 6 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 7 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 8 - Take note of a case docket number where there is a Represented Petitioner and Spouse 
     - [ ] Scenario 9 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Same Address)
     - [ ] Scenario 10 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Different Address)
     - [ ] Scenario 11 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Same Address)
     - [ ] Scenario 12 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Different Address)
- Once you have noted the Case docket numbers for each of the scenarios above, the test is ready
- Click on Serve/Dismiss link
- Ensure that the title of the document in the modal is displaying the correct Location and date of the trial
- Click on the Yes, Serve button

Expected Results:
- [ ] The Generating Notices Message appears with a progress bar
- [x] The Generating Paper PDF message appears with a progress bar
- [x] The Print for Paper Service screen displays (You may want to save it for checking)
- [x] Take note of the docket numbers and the contents of what gets mailed in the Print for paper service doc
     - [x] Scenario 1 - There is an address coversheet, the Remote 30 day Notice of Trial document, and the appropriate Clinic Letter 
     - [x] Scenario 2 - There is no print for paper service doc for this
     - [x] Scenario 3 - There is no print for paper service doc for this 
     - [x] Scenario 4 - There is an address coversheet, the Remote 30 day Notice of Trial document, and the appropriate Clinic Letter for BOTH Petitioners
     - [x] Scenario 5 - There is an address coversheet, the Remote 30 day Notice of Trial document, and the appropriate Clinic Letter for BOTH Petitioners 
     - [x] Scenario 6 - There is no print for paper service doc for this
     - [x] Scenario 7 - There is no print for paper service doc for this
     - [x] Scenario 8 - There is no print for paper service doc for this
     - [x] Scenario 9 - There is an address coversheet, the Remote 30 day Notice of Trial document and the appropriate Clinic Letter for the Unrepresented Spouse only
     - [x] Scenario 10 - There is an address coversheet, the Remote 30 day Notice of Trial document and the appropriate Clinic Letter for the Unrepresented Spouse only
     - [x] Scenario 11 - There is no print for paper service doc for this
     - [x] Scenario 12 - There is no print for paper service doc for this
- [x] The Remote 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption is populated with the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes are populated with the correct information based on the Trial Session information



#### 5) 30 Day Notice of Trial is added to the Docket Record for Cases with Pro Se Petitioners, Not on docket record for Cases with Represented Petitioners

- Continuing from the previous test
- Click the Printing Complete button on the print for paper service
- Ensure that you remain on the Trial Session page, and that the reminder banner is still present on the screen. Do not dismiss the banner at this time (we will do this in a later test).
- Open a new tab to view the case Docket numbers of the Cases that you took note of for the scenarios above

Expected Results
- [x] There is a document on the docket record for Scenarios 1, 2, 4, 5, 6, 7, 9, 10, 11, 12 
     - [x] Filed date is today's date
     - [x] Event Code is NOTT
     - [x] Document Title is 30 Day Notice of Trial on [DATE] at [LOCATION]
     - [x] Page number is correctly displayed
     - [x] Filed by and Action column is blank
     - [x] Served date is today's date
     - [x] Parties code is P
     - [x] Edit/Seal links are available (for docket clerks, CoTC, and CSS only)
- [x] There is no NOTT document on the docket record for scenario 3, 8 (Represented Petitioner(s).
- [x] When viewing the document, the Remote 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption populates the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes populate the correct information based on the Trial Session information



#### 6) Electronic Service was sent to Electronic Pro Se Petitioners; Electronic Service was not sent to represented Petitioner(s).

- Continuing from the previous test
- Navigate to Kibana
- Ensure that you adjust the time to narrow it down to the timeline that you sent the notices
- Add "Bulk" in the search bar and click Refresh

Expected Results:
- [x] There are log entries showing electronic service for the petitioners email addresses for scenarios 2, 6, 7, 11, 12
- [x] For Scenario 6, 7 both Petitioner and Spouse received a service email
- [x] There are not any service emails sent to Counsel (Private or IRS) on any of these cases, only the Electronic Pro Se Petitioners 



#### 7) Clerk navigates to a Standalone Remote trial session with a 30 day NOTT Reminder; Clicks the Serve/Dismiss link; Serves the Notices; Print for paper Service displays the Notices for Paper Pro Se Parties only.

- This test requires some set up
- Log in as a Petitions Clerk
- Click on Trial Sessions 
- Click on the City, State link for a Standalone Remote trial session that has a clock icon for the 30 Day Notice reminder.
- You will need to review a handful of the cases on the trial session that has the 30 day reminder to understand who should/shouldn't be receiving service of the NOTT, and which cases the NOTT should NOT docketed on.
- There will not be any Clinic letters since Standalone Remote does not have a location associated with it.
- Here are the things to Ensure. 
     - [ ] Scenario 1 - Take note of a case docket number where there is a Paper Pro Se Petitioner
     - [ ] Scenario 2 - Take note of a case docket number where there is a Electronic Pro Se Petitioner
     - [ ] Scenario 3 - Take note of a case docket number where there is a Represented Petitioner
     - [ ] Scenario 4 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 5 - Take note of a case docket number where there is a Paper Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 6 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Same Address)
     - [ ] Scenario 7 - Take note of a case docket number where there is a Electronic Pro Se Petitioner and Spouse (Different Address)
     - [ ] Scenario 8 - Take note of a case docket number where there is a Represented Petitioner and Spouse 
     - [ ] Scenario 9 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Same Address)
     - [ ] Scenario 10 - Take note of a case docket number where there is a Represented Petitioner and Paper Pro Se Spouse (Different Address)
     - [ ] Scenario 11 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Same Address)
     - [ ] Scenario 12 - Take note of a case docket number where there is a Represented Petitioner and Electronic Pro Se Spouse (Different Address)
- Once you have noted the Case docket numbers for each of the scenarios above, the test is ready
- Click on Serve/Dismiss link
- Ensure that the title of the document in the modal is displaying the correct Location and date of the trial
- Click on the Yes, Serve button

Expected Results:
- [ ] The Generating Notices Message appears with a progress bar
- [x] The Generating Paper PDF message appears with a progress bar
- [x] The Print for Paper Service screen displays (You may want to save it for checking)
- [ ] Take note of the docket numbers and the contents of what gets mailed in the Print for paper service doc
     - [x] Scenario 1 - There is an address coversheet and the Standalone Remote 30 day Notice of Trial document
     - [x] Scenario 2 - There is no print for paper service doc for this
     - [x] Scenario 3 - There is no print for paper service doc for this 
     - [x] Scenario 4 - There is an address coversheet and the Standalone Remote 30 day Notice of Trial document for BOTH Petitioners
     - [x] Scenario 5 - There is an address coversheet and the Standalone Remote 30 day Notice of Trial document for BOTH Petitioners 
     - [x] Scenario 6 - There is no print for paper service doc for this
     - [x] Scenario 7 - There is no print for paper service doc for this
     - [x] Scenario 8 - There is no print for paper service doc for this
     - [x] Scenario 9 - There is an address coversheet and the Standalone Remote 30 day Notice of Trial document for the Unrepresented Spouse only
     - [x] Scenario 10 - There is an address coversheet and the Standalone Remote 30 day Notice of Trial document for the Unrepresented Spouse only
     - [x] Scenario 11 - There is no print for paper service doc for this
     - [x] Scenario 12 - There is no print for paper service doc for this
- [x] The Standalone Remote 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption is populated with the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes are populated with the correct information based on the Trial Session information



#### 8) 30 Day Notice of Trial is added to the Docket Record for Cases with Pro Se Petitioners, Not on docket record for Cases with Represented Petitioners

- Continuing from the previous test
- Click the Printing Complete button on the print for paper service
- Ensure that you remain on the Trial Session page, and that the reminder banner is still present on the screen. Do not dismiss the banner at this time (we will do this in a later test).
- Open a new tab to view the case Docket numbers of the Cases that you took note of for the scenarios above

Expected Results
- [x] There is a document on the docket record for Scenarios 1, 2, 4, 5, 6, 7, 9, 10, 11, 12 
     - [x] Filed date is today's date
     - [x] Event Code is NOTT
     - [x] Document Title is 30 Day Notice of Trial on [DATE] at [LOCATION]
     - [x] Page number is correctly displayed
     - [x] Filed by and Action column is blank
     - [x] Served date is today's date
     - [x] Parties code is P
     - [x] Edit/Seal links are available (for docket clerks, CoTC, and CSS only)
- [x] There is no NOTT document on the docket record for scenario 3, 8 (Represented Petitioner(s).
- [x] When viewing the document, the Standalone Remote 30 Day Notice of Trial document displays the correct information within the document:
     - [x] NOTT caption populates the correct information based on the case/petitioner information
     - [x] NOTT Trial At and Judge boxes populate the correct information based on the Trial Session information



#### 9) Electronic Service was sent to Electronic Pro Se Petitioners; Electronic Service was not sent to represented Petitioner(s).

- Continuing from the previous test
- Navigate to Kibana
- Ensure that you adjust the time to narrow it down to the timeline that you sent the notices
- Add "Bulk" in the search bar and click Refresh

Expected Results:
- [x] There are log entries showing electronic service for the petitioners email addresses for scenarios 2, 6, 7, 11, 12
- [x] For Scenario 6, 7 both Petitioner and Spouse received a service email
- [x] There are not any service emails sent to Counsel (Private or IRS) on any of these cases, only the Electronic Pro Se Petitioners 



#### 10) Clerk clicks the Yes, Dismiss link on the reminder; Clicks the Close link; Modal closes appropriately

- Continuing from the previous tests
- Navigate to the Trial Sessions page
- Click on the City, State link for an In Person trial session that has a clock icon for the 30 Day Notice reminder.
- Click on the  Yes, Dismiss link
- Click on the Close link in the top right of the modal

Expected Results:
- [x] The modal closes
- [x] The user is navigated back to the Session information page
- [x] The reminder remains on the Session information screen.


 
#### 11) Clerk clicks the Yes, Dismiss link on the reminder; Clicks the Cancel link; Modal closes appropriately

- Continuing from the previous test
- Click on the Yes, Dismiss link
- Click on the Cancel link 

Expected Results:
- [x] The modal closes
- [x] The user is navigated back to the Session information page
- [x] The reminder remains on the Session information screen.



#### 12) Clerk clicks the Yes, Dismiss link on the reminder; Clicks the Dismiss Reminder button; reminder and clock icon are no longer present.

- Continuing from the previous test
- Click on the Yes, Dismiss link
- Click on the Dismiss Reminder button 

Expected Results:
- [x] The modal closes
- [x] The user is navigated back to the Session information page
- [x] The reminder is no longer displayed on the Session information screen.
- [x] The clock icon is no longer present on the Trial Sessions screen
 


~~#### 13) Clerk can Serve the 30 Day Notice of Trial again if necessary.~~

~~- Continuing from the previous tests (as a Petitions Clerk)~~
~~- Navigate to the Trial Sessions page~~
~~- Click on the City, State link for a trial session that has a clock icon for the 30 Day Notice reminder, and ensure that you have already served a 30 Day Notice of Trial document on the cases for this trial session.~~
~~- Click on the Serve/Dismiss link~~
~~- Click on the Yes, Serve button~~

~~Expected Results~~
~~- [ ] The workflow completes again, and all of the expected results from the tests above complete a second time as expected.~~



#### 14) Other Court Staff are able to see the 30 day notice warning banner and clock icon, but are unable to clear the yellow warning banner from view.

- Log in as any Court user besides Petitions Clerk, CSS, or CotC.
- Click on the Trial Sessions tab.
- Click on the City, State of a session that has the new clock icon.

Expected Results:
- [x] Yellow warning banner is present under the Session Information header; text in the banner matches what is in the mockups above.
- [x] Clerk is unable to dismiss the warning banner, and they do not have the option to Serve/Dismiss.

*Be sure to repeat this with all of the other court roles (besides Petitions clerk, CSS, or CotC) to ensure that the warning banner is not dismissible 



#### 15) Regression test to ensure that the reminder appears at the 35 day mark and disappears at the 29 day mark if the clerk doesn't dismiss it.

- [x] Reminder functions appropriately as per story 9969


#### 16) Be sure to test 1-13 with the CotC and the Case Services Supervisor roles. These users should be able to serve the NOTT.

- [x] CotC and CSS roles can also successfully serve NOTT and the workflow works as expected as in Tests 1-13.

**Comment by rachelschneiderman** [comment]
@ttlenard As part of this story, we will be locking down some Trial Session functionality. After this story has been deployed, only standalone remote trial sessions can be calendared without cases on the docket. All other trial sessions will have to have at least one case on their docket to be calendared.

**Comment by rachelschneiderman** [comment]
- single NOTT on docket record per case (if applicable)
- NOTT on docket record WILL have clinic letter appended (if clinic letter exists for trial location)
- printable paper pdf has a set of pages (coversheet + NOTT + clinic letter) for each paper petitioner on the case

**Comment by zachrog** [comment]
After talking with UX we will be making the modal have three options. Serve, Dismiss Notice, and Cancel.

**Comment by ttlenard** [comment]
@rachelschneiderman @codyseibert @zRogersFlexion 

Testing Feedback. I stopped testing after test case 3

- Test Case 1 - After you click Serve/Dismiss link, it doesn't have the progress bar for Generating Notices, it goes straight to the Generating Paper PDF message. The session that I tested with has 72 cases on it, and it took quite a while for the progress bar for the print paper PDF to do anything.  It just sat there.  Was it supposed to also have the "Generating Notices" popup first per the design comments above?
- Test Case 1 - The generated NOTT is missing the served stamp at the bottom of the document.  
- Test Case 2 - On the docket record, the served Parties Code is B, should be P - we are only serving to Petitioners that would receive this document, right?  (I remember we had this discussion, and I thought we were only serving to Pro se petitioners and not to IRS counsel or represented petitioners?
- Test Case 2 - CSS, CotC, and Docket have the Edit/Seal link on the docket record, but if the clerk edits the 30 day notice, Trial Date and Trial Location are blank and must be added manually in if they edit the record. Trial Date and Trial location data is also missing from the Docket Entry Preview text at the top.  (See Screen grab below)
- Test Case 3 - Checking the logs, Respondent and Counsel did get a service email. See other comment above about service.


Screen grab of the Edit Docket Entry screen for the NOTT.  
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/ab54352a-0f84-4c82-8ec7-854f09030c03)

**Comment by ttlenard** [comment]
@codyseibert @zRogersFlexion @rachelschneiderman 

~~More testing Feedback~~
~~Test Case 7 - Standalone Remote Trial Sessions - The appropriate Clinic Letter isn't getting appended to any of the Notices.~~

Updated comment: Nevermind!  Standalone Remote wouldn't have clinic letters since there isn't a location tied to it! My bad!
