### ISSUE TITLE
Docket Clerk: Connect Order to Motion - One to One

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8546]
As a party to a case, so that I can quickly tell the disposition of a particular motion, I need motions to indicate their disposition and connection to the dispositive Order.

Currently when an order granting or denying a motion is docketed, there is no indication on the motion docket entry or in the motion data of how it has been disposed. This means that to find out whether a particular motion has been granted or denied the docket record and orders must be scanned and parsed individually for the order doing so. This makes it difficult to see at a glance the disposition of the motion for parties to the case and Court personnel.

Additionally, this makes it difficult to report out on operational Court data regarding types and behaviors w/r/t motions. For example, the Court is interested in monitoring how many Motions for Summary Judgment are granted vs. denied, but because there's no explicit connection between the motion itself and the order disposing of it, these statistics are difficult to collect with any degree of accuracy.

This story will address an order disposing of a single motion.

We would like to keep this behind a feature flag pending the full rollout of use cases. A future story will extend this functionality to orders disposing of multiple motions.

## Acceptance Criteria
* When adding an order to the docket record, if an order is disposing of a motion, the clerk can indicate which motion on the docket record the order is disposing of
* When adding an order disposing of a motion to the docket record, the clerk must indicate whether the motion is Granted, Granted in Part, or Denied
* The motion disposition is indicated on the docket record entry for the **motion** by appending " - [DISPOSITION] #[ENTRY]" to the current description in the "Filings and Proceedings" column of the appropriate motion
  - [DISPOSITION] is either "GRANTED", "GRANTED IN PART" or "DENIED" based on the selection by the docket clerk
  - [ENTRY] is a hyperlink to the **docket entry for the order** disposing of the motion (this means that for Court users and parties to the case with visibility into the Motion docket entry there will be two different hyperlinks present on the entry - one for the original motion and one linking to the order disposing of the motion. Both links should obey all visibility rules.)
  - This does **not** trigger a Notice of Docket Change entry on the record
* If the order disposing of the motion is sealed, the [ENTRY] hyperlink displays the red lock icon as well
* If the docket entry for an order is edited, the motion disposition association can be edited as well
* If the order is in a consolidated group, all appropriate motion records in each case in the group are edited in the manner above upon multi-docketing of the order

## Notes
* We would like the motion disposition to be stored as data in some way on the motion itself to enable reporting

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] Swagger docs have been updated if API endpoints have been added or updated.
 - [ ] UI should be touch optimized and responsive for external users.
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [ ] Types have been added to all added and updated functions.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`.
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5

**Comment by katiecissell** [comment]
Pre-refinement questions:
- If you edit disposition on motion, after the order was associated, does it need to flow through?
- Should we create a work item for somethings like if they strike it? If the disposition was granted, is there more we can automate for the user? 
- As a regular person/petitioner, is there more we can do to notify them of the results of their motion? (Email something?)

**Comment by katiecissell** [comment]
In the add/edit docket entry field for all orders a new checkbox should be added above the inclusion/attachments checkbox. 
- The checkbox should say "This order acts on a motion"
- If checkbox is selected two new fields should appear below the checkbox.
- The first is a dropdown box with the label: "What motion is being acted on?". The dropdown should show the line number with the name of any motions on the docket. 
- The second is a dropdown with the label "What action is being taken?"  The dropdown options should be Denied, Granted, Granted in Part.

![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/97a2e36f-460f-4762-bc2b-69bb50af1e6c)
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/30af112a-ddcb-4d1b-b19b-ddb217558741)
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/4e448c4e-c3bd-4ad0-b2d2-a835a4fc5c7d)
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/805ff9e4-8eab-43d0-88e5-f6dc8757e973)

If there are no motions on the docket record, the dropdown should say "There are no motions on the docket record".
![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/4bd1e3c5-fae1-4f00-b448-6e48962f02d2)

If the user clicks a motion is being disposed but does not select a motion and/or its status, display validation messages. ![image.png](https://images.zenhubusercontent.com/63ecf8daa45ad187539a9d61/f70d5dd1-bbc5-4feb-9825-a6b273706cc7)

[Figma File](https://www.figma.com/file/jYVB3xmtTWEB11S5dR5ZN3/USTC-%7C-Docket-Record-%7C-Connect-order-disposing-of-motion-%7C-9976?type=design&node-id=0%3A1&mode=design&t=y0cRyStJ9DyigcdR-1)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk navigates to a draft Order; Adds Docket Entry; New checkbox is present to indicate if the Order disposes of a motion.

*Pre-Conditions - Be sure that the case you are on has a few motions on the docket record.

- Log in as a Docket clerk
- Navigate to a case that has a signed Order in Drafts
- Click Add Docket Entry

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new checkbox that states, "This order disposes of a motion" that is below the "What is this order for?" field and the Inclusions header.



#### 2) Docket Clerk checks the box indicating that the Order disposes of a motion, two additional fields appear.

- Continuing from the previous test
- Check the box for "This order disposes of a motion"

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Two new fields appear: "What motion is being disposed of?" and "What is the disposition of the motion?"


#### 3) Docket Clerk Clicks Save and Serve; receives validation error.

- Continuing from the previous test
- Be sure that you leave the two additional fields blank
- Click the Save and Serve button

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User receives validation errors indicating that they need to select a motion to displose of, and the disposition.



#### 4) Docket Clerk selects a motion and the disposition for the Order; Saves and Serves Order.

**Part 1**
- Continuing from the previous test
- Click on the dropdown menu to select a motion that is being disposed of

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu displays the index number and Motion Name for each motion on the docket record.

**Part 2**
- Click on the dropdown for the disposition of the motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Selections include Granted, Granted in Part, and Denied.

**Part 3**
- Docket Clerk clicks save and serve.

Expected Results:
- [ ] Order is served appropriately



#### 5) The text in the Filings and Proceedings column for the original Motion on the docket record is updated

- Continuing from the previous test
- You should have a green confirmation banner
- Scroll down on the docket record and review the entry for the original motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing
- [ ] **NEW FUNCTIONALITY** - There is no Notice of Docket Change for the updated text on the Original motion.



#### 6) Docket Clerk edits an existing Order that is on the docket record of a case; Checkbox for This Order disposes of a motion

*Pre-Conditions - Be sure that the case you are on has a few motions and Orders on the docket record.

- Log in as a docket clerk
- Navigate to a case with the pre-conditions above
- Click on the edit link to edit an order

Expected Results:
- [ ] **NEW FUNCTIONALITY** - There is a new checkbox that states, "This order disposes of a motion" that is below the "What is this order for?" field and the Inclusions header.
- [ ] **NEW FUNCTIONALITY** - If the checkbox is checked, two new fields appear: "What motion is being disposed of?" and "What is the disposition of the motion?"



#### 7) Docket Clerk Clicks Save; receives validation error.

- Continuing from the previous test
- Be sure that you leave the two additional fields blank
- Click the Save button

Expected Results:
- [ ] **NEW FUNCTIONALITY** - User receives validation errors indicating that they need to select a motion to displose of, and the disposition.


#### 8) Docket Clerk selects a motion and the disposition for the Order; Saves edited Order.

**Part 1**
- Continuing from the previous test
- Click on the dropdown menu to select a motion that is being disposed of

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu displays the index number and Motion Name for each motion on the docket record.

**Part 2**
- Click on the dropdown for the disposition of the motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - Selections include Granted, Granted in Part, and Denied.

**Part 3**
- Docket Clerk clicks save entry.

Expected Results:
- [ ] Order record is saved appropriately



#### 9) The text in the Filings and Proceedings column for the original Motion on the docket record is updated

- Continuing from the previous test
- You should have a green confirmation banner
- Scroll down on the docket record and review the entry for the original motion

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing
- [ ] **NEW FUNCTIONALITY** - There is no Notice of Docket Change for the updated text on the Original motion.



#### 10) Docket Clerk checks the box indicating that the Order disposes of a motion; No motions are present on the docket record; What motion is being disposed dropdown menu indicates that there are no motions.

- Log in as a docket clerk
- Navigate to a case that does not have any motions on the docket record, but has a draft order
- Click on the add docket entry button
- Check the box for "This order disposes of a motion"
- Click on the What motion is being disposed dropdown

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The dropdown menu states, "There are no motions on the docket record" 



#### 11) Repeat tests 1-10 with the Clerk of the Court and with the Case Services Supervisor

- [ ] Tests 1-10 pass with the CotC user
- [ ] Tests 1-10 pass with the Case Services Supervisor 



#### 12) When External parties view the case docket record, they can also see the appended text on the original motion.

- As an external user, navigate to the cases that you were testing with in the previous steps.
- Review the docket record

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The original motion has text appended to the original title that includes the disposition that the clerk entered for the Order in the previous test (Granted, Granted in Part, or Denied)
- [ ] **NEW FUNCTIONALITY** - The original motion has a link to the index number of the Order that disposed of the motion.
- [ ] **NEW FUNCTIONALITY** - Clicking on the link opens the document for viewing

*Repeat this test with other external users (Petitioner, IRS, Practitioner, Terminal user)

**Comment by zacharybrown204** [comment]
Notes: (This list will be updated as work is done)

- If orders are one to many with motions (so that each motion can only be affected by one order, but one order can affect many motions) then we will need to filter out any motions that have already been dispositioned from the dropdown.
- Should we account for stricken orders and their resulting disposition on respective motions

**Comment by cholly75** [comment]
@zacharybrown204 @JayFlexy @ttlenard - additional ask to the story: we would like the Order disposing of the motion to _also_ have its docket entry edited when serving, indicating which motions were disposed of in the same manner that we are editing the docket entries of the motions.

The catch here is that since Orders are publicly viewable, the hyperlink to the Motions should _only_ be active to internal Court users and parties to the case. If it's viewed by the public, the "GRANTED/DENIED/GRANTED IN PART # Whatever" should just be plain text. Will codify as AC.

**Comment by zacharybrown204** [comment]
Ready for UX review. 
New UI elements are visible by:

- Creating a motion
- Creating an order
  - When docketing the order there is a new checkbox to relate a motion to the order, revealing the new UI elements
- New links will be visible on the order and motion referencing eachother
- Editing the order will also show these new elements.

**Comment by katiecissell** [comment]
UX Feedback:
- ~~The what motion is being acted on select helper text and the entries is bolded. Needs to be not bold.~~
-  ~~The "Remove" shouldn't appear on the first entry (you can remove it and get into a weird state. If they want to remove the first entry then they should uncheck the box.~~
- ~~Space between remove and the select field  should be 16px~~
- ~~Space between remove and the divider line should 16px~~
- ~~Space between add and divider line should be 16px.~~
- ~~When you remove a set that has validation messages, remove those messages otherwise they could appear on a set that is fine.~~
- ~~Just to confirm, are we seeing two alerts here because of 8477?~~ Yes, or at the very least those alerts are not related to 8546
- 

<img width="516" height="541" alt="Image" src="https://github.com/user-attachments/assets/123335de-82c1-4f6f-b6b0-e14ec1bbae0e" />

**Comment by JayFlexy** [comment]
@katiecissell Yes, when testing on a branch that only contains staging + 8546 code, we do not see these two alerts.

**Comment by Evelyn-Durbin** [comment]
I am ready to move this along, but I need to chat with Zack and Javis about the last two bulletpoints provided. I think they're both out today so I would like to check in with them on Monday

**Comment by JayFlexy** [comment]
> I am ready to move this along, but I need to chat with Zack and Javis about the last two bulletpoints provided. I think they're both out today so I would like to check in with them on Monday

New code is up on exp1 and confirms that those paper service alerts are not present. Everything looks g2g. I consolidated 101-25 and 105-25 in this environment for testing.

**Comment by cholly75** [comment]
Document hyperlink visibility rules:

External (non-logged in) users: should have visibility into non-"sealed to public" Orders/Court-issued documents on the docket record
Logged in parties (petitioner and practitioner) to a case should have visibility into Orders/Court-issued documents and all non-"sealed to parties" documents on the docket record.
Court users should have access to all documents on the docket record.

**Comment by niusha1365** [comment]
**Testing feedback**

- The links should be available to Public and Parties to the case. 
- Public should nsee the links to Orders only
- Parties should see links to Motions and Orders

We will work with UX to get updated mocks
@zacharybrown204  @JayFlexy

**Comment by Evelyn-Durbin** [comment]
https://www.figma.com/design/Q1Jz3GUGzMXeF4JTHh0d0f/USTC-%7C-Docket-Record-%7C-Connect-order-disposing-of-motion-%7C-8546?node-id=2773-870&t=tuuE9t7nJtXBd0OO-1

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

I found an instance that results in a generic error, rather than a descriptive error.

Preconditions: Be sure that you have an order on a docket record and that order already has data in it to identify that it acted on a motion.

1. As a docket clerk, navigate to a case with an order that has acted on a motion
2. Click on the edit link for the order
3. Be sure that there is already data in the docket entry metadata indicating that it has acted on a motion
4. Click on the Add new motion link to add an additional motion, but don't add any data to the two fields
5. Click Save
6. Receive generic error message at the top of the page that states, "Ensure that you are using a supported browser: Chrome, Firefox, Safari, MS Edge, or IE11 (or later)

Somewhat related...if someone were to get this generic error, shouldn't we remove the reference to IE 11 all together??? This can be a separate ticket, but that just caught my attention.

Generic error:

<img width="1292" height="1221" alt="Image" src="https://github.com/user-attachments/assets/42252d3b-296a-4c2b-a9c3-7f76e3efb76e" />


I tested this when adding a docket entry, and if you attempt to add in a second motion on the add docket entry screen, the validation error displays correctly:

<img width="1363" height="1210" alt="Image" src="https://github.com/user-attachments/assets/defb925b-a71a-464f-8b7f-9d8fc701d346" />

I also attempted to get this generic error to display if you were to edit a docket entry and then attempt to save with no data if the user clicks on Add new motion only one time.  For this scenario, I am seeing the correct validation error. 

<img width="1222" height="1066" alt="Image" src="https://github.com/user-attachments/assets/4f520a12-5af9-418d-a86f-6b2f420249a1" />

The issue appears to only happen when you edit a docket entry and there is a second (or third) motion that is blank.

**Comment by cholly75** [comment]
@zacharybrown204 @ttlenard 

Changes requested from feedback:

- [ ] A) Change phrasing on checkbox to "This order is dispositive for at least one motion"
- [ ] B) On the motion dropdown, order the menu items from newest -> oldest
- [ ] C) Change association verbiage for both motion and order:

  - Motion: "GRANTED BY" / "GRANTED IN PART BY" / "DENIED BY"
  - Order: "GRANTING" / "GRANTING IN PART" / "DENYING"

- [ ] D) Include association verbiage in index listing on Document View (@zacharybrown204 to assess feasibility/effort required)
- [ ] E) Current behavior is that associations can be added to a single motion with successive orders - this is **desired** behavior, but unexpected.  @zacharybrown204 to look into why it's doing that

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

- [x] Can we please make sure that the verbiage matches this for Order? Thanks!

Order: "GRANTING" / "GRANTING IN PART" / "DENYING"

Here is what it is saying currently on TEST:

<img width="270" height="192" alt="Image" src="https://github.com/user-attachments/assets/0793b815-de89-4017-91c6-5589cf5083b6" />

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

- [x] Can we get these x's to function? Right now, they don't do anything. Thanks!

<img width="599" height="725" alt="Image" src="https://github.com/user-attachments/assets/716827b1-f103-422e-933a-054792044a95" />

**Comment by ttlenard** [comment]
Testing Feedback

@zacharybrown204 

- [x] Can we please get the Order/Motion disposition information added to the Printable docket record?

<img width="1475" height="288" alt="Image" src="https://github.com/user-attachments/assets/bd6aca8c-0ada-4b9f-9650-3d6ae41eedff" />

Here is an example of how an order looks like on the docket record (see the link to the motion)

<img width="1497" height="391" alt="Image" src="https://github.com/user-attachments/assets/7caea611-0f48-4d18-9829-4603cfe538e0" />

<img width="1409" height="141" alt="Image" src="https://github.com/user-attachments/assets/34ef5b13-a5e2-4a64-8aab-6e567cfb6f9f" />

Here is how the current printable docket record looks (no information about the motion).  We would like to be able to have both the motion and order information that got added to the docket record in this story also available on the printable docket record.

<img width="728" height="337" alt="Image" src="https://github.com/user-attachments/assets/5db70038-cee0-4f53-b196-50f6644439dc" />

<img width="699" height="116" alt="Image" src="https://github.com/user-attachments/assets/b81152cb-54cc-40ba-b720-48551c5900ab" />

**Comment by ttlenard** [comment]
Testing Feedback

@zacharybrown204 

- [x]  When a docket clerk or CSS seals an Order that has a motion disposition or seals the motion that has an associated Order(s), the reference links disappear. If you refresh the screen, the references will display again. It's just on initial load of the docket record after a document is sealed that the reference disappears.  We need the reference to the Motion to remain, and not appear to be removed. Thanks!

- [ ] DISREGARD THIS! ~~Also, can we adjust the seal icon to be in line with the document that is sealed? Right now it appears to just be aligned in the middle of the row? @Evelyn-Durbin~~

~~1. This is when there are no Motions associated:~~

<img width="1438" height="144" alt="Image" src="https://github.com/user-attachments/assets/2855b597-d64d-4c46-8878-8f885e0c8386" />

~~2. This is when there is one. Note how the lock icon is slightly off:~~

<img width="1403" height="149" alt="Image" src="https://github.com/user-attachments/assets/74b62064-c4dd-4940-a7c7-b803a9e1801c" />

~~3. This is when a sealed order disposes of multiple motions. The lock icon is now aligned somewhere with the motions, when it needs to be in line with the Order.~~

<img width="1381" height="190" alt="Image" src="https://github.com/user-attachments/assets/2a8f62d7-4381-4872-a554-6553fa0c4e6e" />

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

- [ ]  DISREGARD THIS! ~~When an Order is stricken, the information on the docket record looks good, but we need some updates on the document view.  Right now when looking at the entry on the document view, it appears that all of the motions are also stricken. Can you ensure that it matches how it looks on the docket record? Thank you.~~

~~Document view~~
<img width="531" height="229" alt="Image" src="https://github.com/user-attachments/assets/a11eaf0a-2576-400f-8013-963150bea9a4" />

~~This is how it should look. Here is the docket record view. only the Order is stricken, not the associated motions.~~

<img width="1419" height="171" alt="Image" src="https://github.com/user-attachments/assets/f0e150dd-1cee-4ec5-8b4c-71efd4f5f621" />

**Comment by ttlenard** [comment]
Testing Feedback:

- [ ] A Few weeks ago, there was terminology change requested for how we display the dispositions on the docket record.  For public non-logged in users and for the public terminal user, it looks like the verbiage didn't get updated on the docket record for these users. The docket record is still displaying the old verbiage "GRANTED, DENIED, GRANTED IN PART".  When viewing the printable docket record as these user types, the verbiage IS updated. It seems the issue is only with what is displayed on the docket record for non-logged in users

<img width="1454" height="467" alt="Image" src="https://github.com/user-attachments/assets/4da8fd1b-ff1e-4c94-8509-6ca27f4eaf5c" />

For reference, here is the original verbiage request.

C) Change association verbiage for both motion and order:

Motion: "GRANTED BY" / "GRANTED IN PART BY" / "DENIED BY"
Order: "GRANTING" / "GRANTING IN PART" / "DENYING"

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

- [x] When viewing the Case docket record as the Public Terminal user, the visibility rules are not quite correct.  The Terminal user should see a link to the motion that the Order is granting. The only time that the Public terminal user shouldn't be able to see a link to a document, is if the document is sealed or stricken.

See below. The terminal user should have a link to this motion.

<img width="1421" height="597" alt="Image" src="https://github.com/user-attachments/assets/5f77cd4d-dc69-4953-8b68-d7475b02703d" />

**Comment by ttlenard** [comment]
Testing Feedback:

@zacharybrown204 

- [x] I'm getting a type error in the console when a public user or Public Terminal user attempts to sort or filter the docket record.  Here are the steps to recreate the issue. Note: This does not happen on Production.

1. As a public user, go to the DAWSON landing page
2. Open the Console on your computer
3. From the case search, navigate to a case that has an Order with a motion disposition on the docket record (coca cola)
4. Click on any of the docket record headers to sort the docket record columns, or filter the docket record by any document type
5. Receive a spinning wheel next to the column header, or if you filtered, the document type you selected doesn't get selected.
6. Notice that there is a type error in your console that has something to do with "Order". See screen grabs below:

<img width="1901" height="730" alt="Image" src="https://github.com/user-attachments/assets/ff372fb2-2c7c-4060-902d-c4da34d61af8" />

<img width="1918" height="748" alt="Image" src="https://github.com/user-attachments/assets/d5b6a0cc-2c05-46f0-bf3b-8c67161d5795" />

<img width="1898" height="792" alt="Image" src="https://github.com/user-attachments/assets/570bd5d3-6185-4831-83a1-ed682451062e" />
