### ISSUE TITLE
New item

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8547]
As a judge, so that I can communicate the disposition of cases assigned to me in progress, I need to show details around cases in progress on the judge activity report.

In ustaxcourt/ef-cms#8401 the judge activity report was created so that judges can communicate statistics around cases and trial sessions within a particular date range with ease.

To provide additional details around cases awaiting activity, we would like to enhance this report with additional cases meeting specific criteria. Future stories will allow judge/CA users to provide additional information around those cases via interactive elements.

## Pre-Conditions
ustaxcourt/ef-cms#8401

## Acceptance Criteria
* The judge activity report includes a section labelled "Progress Description" that displays individual cases that meet all of the following criteria:
  - Are assigned to the judge being reported on
  - Have a status of either "Submitted" or "CAV"
  - Does not have a Decision-type document on the docket record (ODD, DEC, OAD, SDEC)
  - Is not a Member case of a Consolidated group (Lead cases can and should be shown providing they meet the criteria)
* For each case meeting the criteria, we display:
  - the docket number
  - the case status
  - if the case is the Lead case in a Consolidated group, the number (count) of member cases in the group
  - the Petitioner(s) on the case
  - the number of elapsed calendar days
     -  FROM the date the case was assigned its current status
     - TO the date of the report being run (i.e., current date)
  - ordered most -> least in terms of elapsed calendar days as above
* Ensure that the permanent underline on the Reports Menu is removed (This appears to have been introduced when we rolled out 9809.)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/5a27a309-b110-4893-818b-0c377961b54a)
## Notes
* Expect volume to be relatively low for any given judge - 75 cases would be *enormous* relatively speaking.
* Intent is that this is a snapshot of data as of the report run date as to outstanding cases awaiting decision

## Tasks
- [x] Update existing unit tests
- [x] Add new unit tests
- [x] Fix judgeActivityReportJourney integration tests
## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ]  Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 
**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning
 - [x] Verify that language for docket record for internal users and external users is identical
 - [x] New screens have been added to pa11y scripts
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html 
 - [x] READMEs, other appropriate docs, JSDocs and swagger/APIs fully updated
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required)
 - [x] Interactors should validate entities before calling persistence methods
 - [x] Code refactored for clarity and to remove any known technical debt
 - [x] Acceptance criteria for the story has been met
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story
 - [x] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**

Figma file link: https://www.figma.com/file/11G36whofPP6wYIqlDrpAD/USTC-%7C-Reports-%7C-Judges-activity-report-9980?node-id=417%3A186&t=xv6kFhIa3zoVacOd-1

![Activity report - progress descr.png](https://images.zenhubusercontent.com/61a7bbb7fda36d7b28c1ab23/dc3b1784-2f72-4f18-a477-cf85f4f26296)

- Add table titled "Progress Description" below the other tables
- Table component should follow the style of existing tables
- Column order: consolidation icon, Docket No., No. of Cases, Petitioner(s), Case Status, Days in Status
- No. of Cases to include total number of cases for a docket (lead case is included in the total for consolidated groups)
- Left align all columns
- Prevent end date picker from allowing future dates to be selected (see comment in 9723 from Zach re the date range component)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user selects the activity report to run; Enters dates and runs the report; New section called Progress Description is below the statistics portion.

- Log in as a Judge or CA user
- Click on Reports
- Select Activity 
- Input valid dates and click Run report

Expected Results:
- [x] The statistics portion populates correctly (As per story 9809)
- [x] **NEW FUNCTIONALITY** - There is a new section titled "Progress Description" below the statistics portion of the report.
- [x] **NEW FUNCTIONALITY** - Table includes the following header Columns: Docket No., No. of Cases, Petitioner(s), Case Status, Days in Status
- [x] **NEW FUNCTIONALITY** - The only two case statuses in the Progress Description are CAV and Submitted
- [x] **NEW FUNCTIONALITY** - The cases that have the most calendar days from when it changed to the current status will be on the top of the list (displaying total number of days) and then it is displays cases in descending order from the next highest calendar days since status change.
- [x] **NEW FUNCTIONALITY** - Docket numbers listed in the Progress Description will have a hyperlink. When clicked, the appropriate Docket number will open.
- [x] **NEW FUNCTIONALITY** - Lead cases in a consolidated group appear in the list with the lead case icon, no member cases appear.
- [x] **NEW FUNCTIONALITY** - Lead cases display the total number of cases within the group, for non-consolidated cases, it displays 1.
- [x] **NEW FUNCTIONALITY** - There is a total count displayed on the top right of the table.


*Be sure to test this with both a Judge User and a CA user.


#### 2) Docket Clerk files a decision on a case that was in a submitted status; Case no longer appears in the Progress Description area of the Activity Report.

*This test case has some set up

Part 1
- Take note of one of the docket numbers for a submitted case that is assigned to the Judge user from the report you ran for test case 1
- Navigate to the case
- Click on Create, and select Upload PDF or Order or Notice
- Upload a PDF or create an order
- Sign the document. It should save to drafts
- Log out 

Part 2
- Log in as a docket clerk
- Navigate to the case docket number of the submitted case that you just noted
- Click on the drafts tab
- Click on Add Docket Entry
- For the document type, select any document that is a decision type of document
- Serve the document
- Log out as the docket clerk

Part 3
- Log in as the Judge User/CA that you were for test case 1
- Click on Reports
- Click Activity 
- Enter in the same dates as you did for test case 1
- Click Run Report

Expected Results
- [x] **NEW FUNCTIONALITY** - The case that you filed the decision in is no longer present in the Progress Description section.

*Be sure that you do this test with both Judge and CA users.
*Be sure to repeat this test with a case that is in a CAV status.


#### 3) Lead case in a consolidated group has a Submitted status; Lead case is removed from the group; New lead case (which was previously a member case) now has the lead case indicator in the Progress Description table, Previous lead case is displayed in the table as a "normal" case.

*This test case has some set up

Part 1
- Take note of one of the docket numbers for a Lead case that is in a submitted status. Take note of how many cases are in the group in the No. of Cases column.
- Log in as a docket clerk
- Navigate to the Lead case and click on Case information
- Take note of the next lowest docket number member case in the consolidated group
- Click on the unconsolidate link
- Unconsolidate the current lead case from the group
- The next lowest docket number member case should now be the new Lead case in the group.

Part 2
- Log in as the Judge or CA user that you were previously
- Click on Reports
- Click Activity
- Enter in the same dates as you did for test case 1
- Click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The previous lead case is now represented in the Progress description table as an individual case
- [x] **NEW FUNCTIONALITY** - The new lead case in the group is displayed and the No. of Cases column displays one less case than it did previously (since the previous lead case was removed from the group)

*Be sure that you do this test with both Judge and CA users.



#### 4) Number of cases in Submitted/CAV status for a particular Judge that come up in the Case inventory report match the total number of cases displayed in the Progress Description of the Activity Report.

- Log in as a Judge or CA User
- Click on Reports
- Click on Case Inventory Report
- Filter by the Judge you are logged in as (or the Judge you are CA for)
- Select Submitted as the case status
- Take note of how many cases and which docket numbers are in the report results for submitted cases
- Do the steps above, but filter by CAV case status
- Take note of how many cases and which docket numbers are in the report results for CAV cases.
- Next, Click on the Activity report
- Enter in some dates and click run report

Expected Results:
- [x] The number of cases displayed in the Progress Description section matches the total number of cases and docket numbers that you took note of from the Case inventory report.

*Repeat this test with other Judge/CA users.

**Comment by jhansen-flexion** [comment]
Blocked needs to waititil 9809 goes through testing.

**Comment by shumway-tm** [comment]
Met with @swongCO to discuss what to display beneath the Progress Description table.

We did some cross functional mobbing and arrived at the following:
![4820F986-EC71-41FE-84EB-B6233F6A3991_4_5005_c.jpeg](https://images.zenhubusercontent.com/618021eb47ddde1a5ec9cbe6/87f0020b-350d-4daa-965e-7e185c5f24e2)

**Comment by rgoshen** [comment]
Per a conversation today with @cholly75 and @swongCO, this story will only show cases with the status of "Submitted" or "CAV" with a non-empty caseStatusHistory.  i.e. if the case is "Submitted" or "CAV" and this status was changed prior to caseStatusHistory feature being implemented, then do not show it in the Progress Description table.

**Comment by ttlenard** [comment]
Testing Feedback @shumway-tm @rgoshen 

Test Case 2: Looks like Decision type documents that are in the drafts folder, or decision documents that have not yet been served are removing the CAV/Submitted status cases from the Progress Description section of the report.  These documents need to be on the docket record (and served) before they are removed from the Progress description area of the report.

Here are some tests I did:
- As a judge, run an activity report
- Take note of the cases in the CAV/Submitted status
- Navigate to one of those cases and create a decision type of Order 
- Sign the order
- The draft decision type of Order is now in the drafts folder, and it has not been served, and it is not yet on the docket record
- Run the Activity report again
- Notice that the Case no longer shows up in the Progress Description area.

This image shows the Order and Decision document in Drafts
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/b2b5d120-c1c1-4cbb-9a55-d3b18a5be5d3)

This image shows that the case no longer appears in the Progress Description area:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/8f3da8f9-4286-47be-8d8a-2d044809c853)

Another Example:
- As a judge, run an activity report
- Take note of the cases in the CAV/Submitted status
- Navigate to one of those cases and create a PDF upload
- Add any description that you would like
- Sign the document
- Run the Activity report again 
- The Progress Description area will still have the case listed (good!)
- Next, as a docket clerk, navigate to the case that you just did the PDF upload in
- Click Add docket entry
- Select a document type that is a decision type document
- Save the document, do not click Save and Serve
- The document will now be on the docket record, but has not yet been served
- Next, log in as the Judge user
- Run the Activity Report
- Notice that the Case that the Decision type document was saved to is no longer in the list of cases in the progress description area, even though the decision document has not yet been served.

This image shows the saved decision document (not yet served)
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/e6603e87-e4ad-4f4a-9964-35a25a140d26)

This image shows that the case with the saved decision document is no longer showing in the progress description area of the report:
![image.png](https://images.zenhubusercontent.com/60f99b8ac0d8d04c8aed1aa3/9f1b170f-427f-4471-8d71-f88320b685fa)

**Comment by ttlenard** [comment]
@rgoshen I found one more thing. If a Decision type document that is filed on a CAV or Submitted case happens to be stricken, the case isn't displayed in the Progress description section.

Here is the test I did:
- As a judge, create a decision type document on a CAV or Submitted case that appears in the Progress description section.
- Apply your signature
- As a docket clerk, Serve it to the Case
- The case status will change to closed or closed - dismissed depending on the type of decision document you served
- Log in as a judge
- click on Reports and select Activity report
- The progress description section will no longer display the case
- Next, log in as a docket clerk
- navigate back to the case
- strike the Decision document that you just served in the previous step
- Click on case information and update the case status so that it is back in CAV or Submitted
- Log in as the Judge
- Click on Reports and select activity
- run the report
- Notice that the Case that is back in CAV or Submitted status is not appearing in the Progress description section

Expected results - on the last step, since the decision document was stricken, the case should re-appear in the Progress description section.

**Comment by ttlenard** [comment]
@rgoshen All tests pass now. Thank you!
