### ISSUE TITLE
Trial Session: IRS Calendar Administrator Lookup

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8562]
As a trial/petitions clerk, so that I can easily populate the IRS Calendar Administrator information on a trial session, I want to be able to search for and select an IRS practitioner to populate this information on the trial session.

Currently, our trial clerk supervisor populates the IRS Calendar Administrator information on each trial session manually. This includes the name, email address, and phone number of the IRS practitioner. 

Since all IRS Calendar Administrators are in DAWSON as IRS practitioners, it would be much easier and faster if to populate this field the trial clerk could search by practitioner name and select the relevant IRS practitioner, then have DAWSON autopopulate the relevant details into the IRS Calendar Administrator field for them. The clerk would then simply have to save the change to the trial session.

## Acceptance Criteria
* ✅ When editing the IRS Calendar Administrator field on a Trial Session, the user can search active IRS practitioners by name without having to navigate to Practitioner Search screen
* ✅ User is presented with results of search
* ✅ User chooses a result, and the following information is populated into the IRS Calendar Administrator field:
  - Practitioner name
  - Practitioner email
  - Practitioner phone number
* ✅ IRS Calendar Administrator field can still be edited manually
* ✅ User can save the trial session with the information populated

## Notes

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEtFQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4a4c88493676cec2fe6c3f30445b8bb60c1163be/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

 * 
  -

**Comment by swongCO** [comment]
Pre refinement
- is there ever a case where the IRS practitioner would not be in the search results? No

**Comment by swongCO** [comment]
**UX Notes**

Changes to the IRS calendar administrator field:
- Add combo-box component labeled "Search for IRS calendar administrator name (optional)"
- Combo-box placeholder text: "- Enter name -"
- See docket entry combo-box component for reference
- Add name, email and phone number fields with labels as displayed in mockup
- Search results will include name and address (match styling in Dawson)
- When the user selects a result, the name, email and phone number will populate in the respective fields
- Name, email and phone number are editable by the user
- On the Session Info/Copy pages, display as 3 separate lines in the Assignments card
- This story does not affect legacy trial sessions unless the admin is changed
- FOR DEVS: find out how many active IRS practitioners are in the database to determine what the drop down should display
- Figma file: https://www.figma.com/file/TIDBmJ73hfcM8d6ygYvSG6/USTC-%7C-10185-%7C-Trial-Session-%7C-IRS-admin-lookup?type=design&node-id=90%3A89&mode=design&t=Q4e2BMcvoGQdNjp6-1

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0lVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--557cba5850720fd23c737140c6c32b07f7af48ba/Trial%20session%20-%20IRS%20calendar%20admin%20search.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeElVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--db8b3059b40ca3200f03dcfe6f5ee1ab6ee68d4e/Trial%20session%20-%20IRS%20calendar%20admin%20search%20results.png)

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Trial Clerk edits an upcoming trial session; New fields are present for IRS calendar administrator name, email and phone number.

- Log in as a trial clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming session
- Click on the Edit link on the Session information page
- Scroll down to the Session Assignments section

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now 4 fields for the IRS Calendar Adminstrator - Search for IRS calendar administrator name, IRS calendar administrator name, Email, and Phone number.



#### 2) Trial Clerk starts typing a name in the Search for IRS calendar administrator field, results list dropdown updates as the name is typed to further refine results.

- Continuing from the previous test
- Start typing the name of an IRS Practitioner in the Search for IRS calendar administrator name field.

Expected Results:
- [x] **NEW FUNCTIONALITY** - As you type, the results list displays names consistent with what is being typed. The more text that is entered for the name, the more the results list is refined.
- [x] **NEW FUNCTIONALITY** - The Names in the results list also include the IRS Practitioner's address information (as it is stored in DAWSON)



#### 3) Trial Clerk selects a practitioner from the results list; The DAWSON stored email and phone number automatically populate in the Email and Phone number fields.

- Continuing from the previous test
- Select a practitioner from the results list

Expected Results:
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners name populates in the IRS calendar administrator name field
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners email populates in the Email field
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners Phone number populates in the Phone number field.



#### 4) Trial Clerk types a name in the search for IRS calendar admin field, selects a different name, Name, email, and phone number are replaced with new values.

- Continuing from the previous test
- Start typing the name of a different person in the search IRS calendar admin name field
- Select a different IRS practitioner

Expected Results:
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners name that you just selected populates in the IRS calendar administrator name field
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners email populates in the Email field
- [x] **NEW FUNCTIONALITY** - The IRS Practitioners Phone number populates in the Phone number field.



#### 5) Trial Clerk saves the session assignments; IRS Calendar administrator information is displayed appropriately on in DAWSON and in Printed materials.

**Part 1**
- Continuing from the previous test
- Make sure that the trial clerk that you are logged in as is listed as the trial clerk assigned to the session
- Click Save
- App will route to the Session information page
- Review the page

Expected Results:
- [x] The IRS calendar administrator name, email, and phone number that were auto populated are displayed on 3 lines on the assignments card.

**Part 2**
- Click on the Print Session information link

Expected Results
- [x] The IRS calendar administrator name, email, and phone number that were auto populated are displayed on 3 lines on the assignments card.


**Part 3**
- Go back to the Session information page
- Click on the View Session Copy link

Expected Results:
- [x] The IRS calendar administrator name, email, and phone number that were auto populated are displayed on 3 lines on the assignments card.


**Part 4**
- Click on the Print Session info link
- Print with or without notes (doesn't matter)

Expected Results
- [x] The IRS calendar administrator name, email, and phone number that were auto populated are displayed on 3 lines on the assignments card.



#### 6) Trial Clerk deletes some or all of the auto populated data; page saves without error and displays data appropriately. 

- Log in as a Trial Clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming trial session
- Click on the Edit link on the session info page
- Start typing a name in the Search for IRS calendar administrator name field and select a person
- The name, email and phone number should be auto populated
- Delete one of the values (name, email, or phone number)
- Click Save

Expected Results:
- [x] The page saves appropriately without error
- [x] The information on the Session info page is displayed correctly (the info that you deleted it not displayed)
- [x] The information on the Session copy page is displayed correctly
- [x] The information on the Printed Session info is displayed correctly
- [x] The information on the Printed Session copy is displayed correctly

*Repeat this test by deleting various info and saving - it should save appropriately each time.
- [x] Delete name only
- [x] Delete email only
- [x] Delete phone number only
- [x] Delete name and email
- [x] Delete name and phone number
- [x] Delete email and phone
- [x] Delete name, email, and phone



#### 7) Trial Clerk edits some or all of the auto populated data; page saves without error and displays data appropriately.

- Log in as a Trial Clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming trial session
- Click on the Edit link on the session info page
- Start typing a name in the Search for IRS calendar administrator name field and select a person
- The name, email and phone number should be auto populated
- Edit one of the values (name, email, or phone number)
- Click Save

Expected Results:
- [x] The page saves appropriately without error
- [x] The information on the Session info page is displayed correctly (the info that you edited is displayed appropriately)
- [x] The information on the Session copy page is displayed correctly
- [x] The information on the Printed Session info is displayed correctly
- [x] The information on the Printed Session copy is displayed correctly

*Repeat this test by deleting various info and saving - it should save appropriately each time.
- [x] Edit name only
- [x] Edit email only
- [x] Edit phone number only
- [x] Edit name and email
- [x] Edit name and phone number
- [x] Edit email and phone
- [x] Edit name, email, and phone



#### 8) Inactive IRS Practitioners are not available in the Search for IRS Calendar administrator results

This test has some set up
- Log in as a Trial Clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming trial session
- Click on the Edit link on the session info page
- Start typing a name in the Search for IRS calendar administrator name field and select a person
- The name, email and phone number should be auto populated
- Take note of this IRS Practitioner

- Log in as an Admissions Clerk
- Click on the Advanced tab
- Click on the Practitioner tab
- Search for the IRS Practitioner that you noted above
- Edit the practitioner details
- Change the practitioner from Active to inactive and save

- Log in as a Trial Clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming trial session
- Click on the Edit link on the session info page
- Start typing the Practitioners name in the Search for IRS calendar administrator name field 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The inactive IRS Practitioner does not display in the dropdown list of results


#### 9) Private Practitioners are not available in the Search for IRS calendar administrator results

- Log in as an Admissions Clerk
- Click on the Advanced tab
- Click on the Practitioner tab
- Search for an active Private Practitioner
- Take note of this persons name and contact info

- Log in as a Trial Clerk
- Click on Trial Sessions
- Click on the City, State link for an upcoming trial session
- Click on the Edit link on the session info page
- Start typing the Private Practitioners name in the Search for IRS calendar administrator name field 

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Private Practitioner does not display in the dropdown list of results



#### 10) Trial Clerk edits an upcoming session that already had an IRS Calendar administrator's contact information added; Data previously entered is displayed only in the IRS Calendar administrator name field.

- Log in as a Trial Clerk
- Click on Trial Sessions
- Navigate to a Trial Session that is upcoming and that already has an IRS calendar administrator populated
- Click on the edit link

Expected Results:
- [x] **NEW FUNCTIONALITY** - The data that was previously input for the IRS Calendar administrator is populated in the IRS Calendar administrator name field. No data is populated in the Email or phone number field.



#### 11) Trial Clerk edits a session that already had an IRS Calendar administrator's contact information added; Data saves appropriately

- Continuing from the previous test
- Start typing a name in the Search for IRS calendar administrator name field
- Select a person's name

Expected Results:
- [x] **NEW FUNCTIONALITY** - The previously entered calendar administrator name and info is replaced with the data from the selected IRS user
- [x] **NEW FUNCTIONALITY** - The email and phone number fields are also populated
- [x] **NEW FUNCTIONALITY** - After save, the new information is populated and displayed appropriately on the session info page, session copy page, and printed versions of these pages appropriately.


#### 12) Repeat tests 1-12 with a Petitions clerk

- [x] All tests pass while logged in as a petitions clerk role

**Comment by swongCO** [comment]
**UX feedback**
1. Printable pdf is not wrapping the phone number to its own line
2. <s>Add "." to the types of delineators (in addition to space, dash, etc.)</s>

<img width="837" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1ZOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d2644a3851f6e57892d3de076f12268b2c2f9fe/Screenshot%202023-12-11%20at%202.21.17%E2%80%AFPM.png" alt="Screenshot 2023-12-11 at 2.21.17 PM.png" />

3. Shorten the phone number field to align with other fields above it (see UX mockup)
4. This is failing test case 10, where the legacy info should be displayed in the name field. It's currently blank.

<img width="699" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1pOQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cdd58039d182227266caed22b42f23cb57ee039f/Screenshot%202023-12-11%20at%202.39.59%E2%80%AFPM.png" alt="Screenshot 2023-12-11 at 2.39.59 PM.png" />

<img width="1420" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3ROQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e75f088824da34e92eeabb92336a77b266185a34/Screenshot%202023-12-11%20at%202.39.25%E2%80%AFPM.png" alt="Screenshot 2023-12-11 at 2.39.25 PM.png" />

**Comment by ttlenard** [comment]
@cruzjone-flexion @nechama-krigsman

Testing Feedback 

Test Case 5 part 4 is failing.  The printed Session Copy page is not displaying the IRS calendar administrator contact info. See screen grab:
<img width="1000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejFzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--457c6de74b89773121222e3457bbb54572c51a57/image.png" alt="image.png" />

For reference, here is the calendar admin that I added to this session:
<img width="1317" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--505fede17cb96b7dab7da3322faec0b91e106598/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
@nechama-krigsman @cruzjone-flexion Testing looks great!
