### ISSUE TITLE
Trial Session: Chambers Phone# Lookup

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8564]
As a clerk editing a trial session, so that I don't have to manually enter the Chambers phone number for a judge, I need the Chambers phone field to autopopulate when a judge is selected.

When a judge is selected to preside over a trial session, the clerk must manually enter the judge phone number in the Chambers Phone Number field.

Since judge chambers phone numbers do not change, we want the phone number to autopopulate in this field when a judge is selected in the Judge field.

## Acceptance Criteria
* Each judge in DAWSON can have a Chambers phone number associated with them
* When the Judge field is populated on a Trial Session, the Chambers phone number field is automatically populated with the Chambers phone associated with the judge
* When the Judge field is edited on a Trial Session, any existing value in the Chambers phone number field is automatically replaced with the Chambers phone number associated with the new Judge value
* Chambers phone number field can still be edited manually
* Number format: (XXX) XXX-XXXX

## Notes
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGFGQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ef1b08e59e5197066bd873eaa8c0af6d5fd8216/image.png)

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- why do they need to be able to edit it?
-

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions Clerk creates a new small trial session, adds a Judge, Chambers phone number field is automatically populated with the correct chambers phone number.

- Log in as a petitions clerk
- Click on Trial Sessions
- Click Add Trial session
- Fill in the required fields for a small session in the upper section of the page
- Select any Judge

Expected Results:
- [x] **NEW FUNCTIONALITY** - The chambers phone number for said Judge populates correctly in the Chambers phone number field.



#### 2) Petitions Clerk saves the newly created small trial session; Chambers phone number that was automatically populated displays on the Trial Session information page.

- Continuing from the previous test
- Be sure that all of the required fields are filled in
- Click Add Session
- Click on the New tab
- Click on the City, State link of the session that you just created.
- Review the Trial Session info page.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Chambers phone number that was auto-populated is displayed appropriately on the Assignments card on the Trial Session Info page.



#### 3) Petitions Clerk checks eligible cases and sets the calendar; On the print for paper service screen, the Chambers phone number that was automatically populated displays on correctly in the Standing Pretrial Order for small cases and the Pretrial Memorandum document.

- Continuing from the previous test
- Check the box for some of the cases on the eligible case list
- Click Set Calendar
- Click Yes, Set Calendar
- After the Generating Notices and Creating Print Paper Service PDF modals, review the Print Paper Service screen.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Standing Pretrial Order for each case that has paper service has the correct auto-populated Judge's Chambers phone number.
- [x] **NEW FUNCTIONALITY** - The Pretrial Memorandum for each case that has paper service has the correct auto-populated Judge's Chambers phone number.



#### 4) Petitions Clerk prints the Trial Session information page, Chambers phone number that was automatically populated displays on the printed version of the Trial Session Information page.

- Continuing from the previous test
- Click Done
- On the Trial Session info page, click on the print session information link.

Expected results:
- [ ] **NEW FUNCTIONALITY** - The Chambers phone number that was auto-populated is displayed appropriately on the Assignments card on the Trial Session Info page.




#### 5) Judge User assigned to the session accesses the Session information page; Chambers phone number that was automatically populated displays on the Assignments card.

- Continuing from the previous test
- Log in as the Judge User that was assigned to the trial session from the previous test cases
- Click on the City, State of the Trial Session from the upcoming trial session card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Chambers phone number that was auto-populated is displayed appropriately on the Assignments card.



#### 6) Judge User assigned to the session prints the Session Copy page; Chambers phone number that was automatically populated displays on the printed version of the Session Copy Page.

- Continuing from the previous test
- Click on the Print link
- Indicate if you want to print notes

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Chambers phone number that was auto-populated is displayed appropriately on the Assignments card.



#### 7) Repeat tests 1-6 with a Regular and Hybrid session. 

Expected Results:
- [x] Tests 1-6 pass with a regular session
- [x] Tests 1-6 pass with a hybrid session (Be sure that you calendar both small and regular types of cases)(You should have both standing pretrial order for small cases + standing pretrial order for reg cases that display the chambers phone number appropriately)



#### 8) Petitions Clerk creates a new small trial session, adds a Judge, Chambers phone number field is automatically populated; Clerk can delete the chambers number and Add the new session as per normal.

- Log in as a Petitions Clerk
- Click on Trial Sessions
- Click Add Trial session
- Fill in the required fields for a small session in the upper section of the page
- Select any Judge
- Delete the auto-populated Chambers phone number
- Click Add Session

Expected Results:
- [x] The trial session saves appropriately with no errors.



#### 9) Petitions clerk edits the session from the test case above, adds in a different chambers phone number, saves the session.

- Continuing from the previous test
- From the Trial Sessions/New tab, click on the City, State link for the session you just created in the previous test case
- Click on the Edit link on the Session information page
- Add in a different phone number in the Chambers phone number field
- Click Save

Expected Results:
- [x] The trial session saves appropriately
- [x] The phone number that you manually input displays on the Session info page and printed version so the Session information page




#### 10) Petitions Clerk edits the session from the test case above, selects a different Judge; Chambers phone number field is automatically populated with the updated Judges chambers phone number.

- Continuing from the previous test case
- Click on the Edit link on the Session information page
- Select a different Judge

Expected Results:
- [x] **NEW FUNCTIONALITY** - The chambers phone number for said Judge populates correctly in the Chambers phone number field.



#### 11) Petitions clerk deletes the autogenerated phone number and inputs a different phone number.  Saves the session.

- Continuing from the previous test
- Delete the auto-generated number and input a different phone number
- Click Save

Expected Results:
- [x] The trial session saves appropriately
- [x] The phone number that you manually input displays on the Session info page.



#### 12) Petitions clerk checks eligible cases and sets the calendar; On the print for paper service screen, the Chambers phone number that was manually populated displays on correctly in the Standing Pretrial Order for small cases and the Pretrial Memorandum document.

- Continuing from the previous test
- Check some of the cases on the eligible case list, ensuring that some of the cases have petitioners that receive paper service.
- Set the Calendar

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Standing Pretrial Order for each case that has paper service has the correct manually entered Judge's Chambers phone number.
- [x] **NEW FUNCTIONALITY** - The Pretrial Memorandum for each case that has paper service has the correct manually entered Judge's Chambers phone number.



#### 13) Petitions Clerk prints the Trial Session information page, Chambers phone number that was manually populated displays on the printed version of the Trial Session Information page.

- Continuing from the previous test
- Click the print session information link on the session info page for the trial session from the previous test case

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Chambers phone number that was manually updated is displayed appropriately on the Assignments card.



#### 14) Judge User assigned to the trial accesses the Session information page; Chambers phone number that was manually populated displays on the Assignments card.

- Log in as the Judge User assigned to the trial session from the previous test case
- Click on the City, State link for the session from the upcoming trial sessions card

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Chambers phone number that was manually updated is displayed appropriately on the Assignments card.



#### 15) Judge User assigned to the trial prints the Session Copy page; Chambers phone number that was manually populated displays on the printed version of the Session Copy Page.

- Continuing from the previous test
- Click on the Print link

Expected Results:
- [ ] **NEW FUNCTIONALITY** - The Chambers phone number that was manually updated is displayed appropriately on the Assignments card.



#### 16) Repeat tests 8-15 with a Regular and Hybrid session. 

Expected Results:
- [x] Tests 1-6 pass with a regular session
- [x] Tests 1-6 pass with a hybrid session (Be sure that you calendar both small and regular types of cases) (You should have both standing pretrial order for small cases + standing pretrial order for reg cases that display the chambers phone number appropriately)



#### 17) Petitions clerk changes the trial judge on an upcoming in-person trial session; the chambers phone number is automatically updated when changing the trial judge; the autogenerated phone number is displayed on the Notice of Change of Trial Judge Document, and on the session pages in DAWSON.

**Part 1**
- Log in as a Petitions clerk
- Click on the Trial Sessions tab
- Click on the City, State link for an in-person trial session that is in the future
- Click on the Edit link
- Change the assigned Judge

Expected results:
- [x] **NEW FUNCTIONALITY** - The chambers phone number for said Judge populates correctly in the Chambers phone number field.

**Part 2**
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Notice of Change of Trial Judge for each case that has paper service has the correct auto-populated Judge's Chambers phone number on the print for paper service screen.
- [x] **NEW FUNCTIONALITY** - The Notice of Change of Trial Judge for each case has the correct auto-populated Judge's Chambers phone number on the docket record.
- [ ] **NEW FUNCTIONALITY** - The auto-populated Chambers Phone number displays appropriately on the following pages:
     - [x] Trial Session info page 
     - [ ] The printed trial session info page 
     - [x] The Judges Session Copy page
     - [ ] The printed Session Copy page



#### 18) Petitions clerk changes a trial session from the test case above from an in-person to a remote proceeding; the chambers phone number is displayed appropriately on the Notice of change to remote proceeding.

- Continuing from the previous test
- Navigate to the in-person Trial Session that you used in the test case above
- Click on the Edit link on the trial session information page
- Change the location from in person to remote, and being sure to add in the required fields for a remote session
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Notice of Change to remote proceeding for each case that has paper service has the correct auto-populated Judge's Chambers phone number on the print for paper service screen.
- [x] **NEW FUNCTIONALITY** - The Notice of Change to remote proceeding for each case has the correct auto-populated Judge's Chambers phone number on the docket record.
- [ ] **NEW FUNCTIONALITY** - The auto-populated Chambers Phone number displays appropriately on the following pages:
     - [x] Trial Session info page 
     - [ ] The printed trial session info page 
     - [x] The Judges Session Copy page
     - [ ] The printed Session Copy page



#### 19) Petitions clerk changes the trial session from the test case above from a remote to in-person proceeding; the chambers phone number is displayed appropriately on the Notice of Change to in person proceeding.

- Continuing from the previous test
- Navigate to the remote Trial Session that you used in the test case above
- Click on the Edit link on the trial session information page
- Change the location from remote to in person, and be sure to add in the required fields for an in person
- Click Save

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Notice of Change to in person proceeding for each case that has paper service has the correct auto-populated Judge's Chambers phone number on the print for paper service screen.
- [x] **NEW FUNCTIONALITY** - The Notice of Change to in person proceeding for each case has the correct auto-populated Judge's Chambers phone number on the docket record.
- [ ] **NEW FUNCTIONALITY** - The auto-populated Chambers Phone number displays appropriately on the following pages:
     - [x] Trial Session info page 
     - [ ] The printed trial session info page 
     - [x] The Judges Session Copy page
     - [ ] The printed Session Copy page



#### 20) Some additional regression tests:

- [x] Petitions clerk edits an upcoming trial session that was created before the release of this story; chambers phone number that was originally input remains in the field as per normal.
- [x] Petitions clerk edits an upcoming trial session that was created before the release of this story; Changes the trial judge, chambers phone number get's auto-generated. Session can be saved; notices generated appropriately; printed versions of session data print/display the phone # appropriately.
- [x] Petitions clerk edits a trial session from the New tab that was created before the release of this story; adds in a Judge, chambers phone number gets auto-generated.  Session can be saved, calendared, and displays appropriately on printed versions and in DAWSON session pages.
- [x] Test the above test cases with different users (Case Services Supervisor, Clerk of the Court, Chambers, Trial Clerk) to ensure that the test cases pass with different users.

**Comment by codyseibert** [comment]
we talked to @cholly75 and decided to move any new functionality related to changing any PDFs to a new story

**Comment by ttlenard** [comment]
@codyseibert @Absolutestunna @rachelschneiderman Testing looks good!  Thank you.
