### ISSUE TITLE
Export Pending Report to Excel-friendly Format

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8570]
As a Court user, so that I can easily repurpose and manipulate report data , I need to be able to export the Pending Report to a format that can be read/imported by Microsoft Excel.

We have gotten many requests from Court users who would like to use the data in DAWSON as the basis for more advanced tracking/calculations for a variety of purposes; as this often relies on functionality available in spreadsheet software (pivot tables; formulas; charting, for example), they would like an easy and reliable way to run a report and then export that data into a format that can be read by a spreadsheet program such as Excel.

In order to facilitate this, we would like to start with a single report (the Pending report) and provide the user a way to quickly generate a file for further use outside of DAWSON. As Excel is the enterprise spreadsheet solution for the Court, the file should be in a format that can be easily opened/imported into Excel.

We expect to extend this functionality to a variety of reports/views in the future.

## Acceptance Criteria
* User can export the Pending report results into a file suitable for opening as a spreadsheet in Excel
* Column headings are included in the exported file 

## Notes
* Consolidation icons do not need to be represented in the data

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- which features of excel are important to support? make sure info is in excel as data - csv file would fine but can discuss xls if it makes sense
- what are users trying to do with the exported data? should dawson be doing this? depends on who - CAs wants to print out a list of pending reports; pivot tables for court locations for CFO; not worth it to be in dawson
- do we need to show the header (logo and USTC title)? no
- do we need the table count? no

**Comment by katiecissell** [comment]
UX Notes:
- Add an unstyled button with an icon to the left of the Printable Report button on the Pending Report.
- Icon should be from Font Awesome, called File export. https://fontawesome.com/v5/icons/file-export?f=classic&s=solid . Should be our primary blue color (#005EA2) and 14.5 x 12.89.
- The spacing between export and printable report should be 20px, this should be the same spacing as when we have two buttons next to each other.
- When the button (text and/or icon) is clicked the file should be exported to a CSV (or excel if engineering determines that is better).  This should just utilize the browser download feature. (Like if you open the printable report and then download it, the download process is what I'd ideally like to imitate through the browser)
- Note: If this export process ends up not being fast, then we will need some kind of loading/spinner so if that is what happens Engineers should reach out to UX to chat about options.

Mockup:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVVVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edd7f0ebb6030f22f6f98d26dae5a817cf62cd81/image.png)

CSV
- Name of export should be "Pending Report - judgename 00/00/0000". Example: "Pending Report - Buch 11/26/2023"
- Using whatever styling is default is fine as long as its organized in the table. Note: If possible, please bold headers. If not possible, thats ok.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Pending Report; new option to export is displayed next to the Printable report link.

- Log in as any Court user
- Click on Reports
- Select Pending Report
- Select a Judge from the dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a new Export link (with an icon per the mockup) to the left of the Printable Report link.



#### 2) Court user clicks on the export link, computers Save/Save As folder displays (i.e. windows explorer), allowing the user to indicate where they would like to save the document.

- Continuing from the previous test
- Click on the export link

Expected Results:
- [x] **NEW FUNTIONALITY** - Windows explorer (or similar) opens.
- [x] **NEW FUNTIONALITY** - Default file name is "Pending Report - [Judge name] [Date XX/XX/XXXX]" 
- [x] **NEW FUNTIONALITY** - File type is csv or xls (dev discretion)



#### 3) Court user saves the exported Pending report to their computer; Opens the file; data is represented in the spreadsheet appropriately

**Part 1**
- Continuing from the previous test
- Click on the Save button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document is saved to the users computer at the location that they indicated.

**Part 2**
- User navigates to the location that they saved it on their computer
- Open the document

Expected Results:
- [x] **NEW FUNCTIONALITY** - A spreadsheet opens (dev determination on what file format it is)
- [x] **NEW FUNCTIONALITY** - Column headings from the Pending report page are represented in the spreadsheet
- [x] **NEW FUNCTIONALITY** - Formatting is such that users can sort, filter, etc. (data is represented in singular cells, cells aren't merged, etc.)
- [x] **NEW FUNCTIONALITY** - All data that was in the UI on the report is also represented in the spreadsheet (48 pending items in the UI = 48 pending items in the spreadsheet)


*Be sure to test with a variety of Court users

**Comment by TomElliottFlexion** [comment]
Updating file naming to use `_` characters instead of `/` for dates

**Comment by ttlenard** [comment]
@jasonfu9966 @TomElliottFlexion Testing looks good. Thank you!

**Comment by TomElliottFlexion** [comment]
Uses csv-stringify, see PR: https://github.com/ustaxcourt/ef-cms/pull/4390
