### ISSUE TITLE
New Event Code - Attachment to Petition (ATP)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8578]
As a petitioner, so that my supporting documentation can be easily located on the docket record, I need a specific event code for attachments to my petition submission.

As part of the Court's move to greater transparency, we will be making changes to the petition docketing flow in which the petition proper will be docketed separately from any attachments to said petition. Up until now we have requested that (particularly for e-filers) petitioners attach additional documentation (IRS Notices, other supporting documents) to the petition file itself. Going forward we will be modifying the petition submission flow to request and receive these documents separately, and as such will docket them separately.

To this end, we need a new event code to classify these attachments to the petition (ATP). 

**We do not expect this to be used until future stories are completed, and we expect to make changes to ATP functionality prior to it being used.**

A future story will integrate the upload of ATP into the case creation process for petitions clerks.

Until we modify the online petition flow to accommodate this separately from the petition upload, ATP will only be available to Docket when docketing paper filings or QCing a filing (but will remain unused near term while we build out the functionality incorporating it).

## Acceptance Criteria
* Attachments to Petition can be selected as a document type when Docket is entering a Paper Filing or QCing a filing
* Attachments to Petition receive a cover sheet when docketing
* When docketing an ATP, the docket clerk UI asks for the following information:
  - Date Received
  - Mailing Date (optional)
  - Additional Info 1 (optional)
    - Check box to add to cover sheet
  - Additional Info 2 (optional)
* Attachments to Petition are only ever filed by petitioner(s)
* Attachments to Petition cannot be selected as document types when e-filing a document in an existing case
* Attachments to Petition are served on respondent
* Attachments to Petition when docketed are visible only to parties to the case, court employees and the terminal user

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:
Docket clerks will have a new document type when adding a paper filing or editing a docket entry.

If certain document type scenarios are similar, consider using them as the basis for the ATP.

Add Paper filing mock:
<img width="712" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGRhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--103a91674e791b17882533c2a790d42581ed4788/image.png" alt="image.png" />



Edit ATP (service and Action tabs have no changes for ATP) mock:
<img width="734" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejliQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71c441230eb84a396d86bab68fecbda17ab91c51/image.png" alt="image.png" />


What it should look like on docket mock:
<img width="1810" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDVhQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7988dcba1fa9b71ef33d20062d27c077449f650b/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Docket Clerk adds a Paper Filing to a case; Attachment to Petition is available in the Document Type dropdown.

- Log in as a Docket Clerk
- Navigate to a case
- Click on the Create button
- Select Paper Filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Click on the document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - New document type titled Attachment to Petition is available in the dropdown list.
- [x] **NEW FUNCTIONALITY** - Clerk can type ATP in the document type dropdown and Attachment to Petition displays in the list.



#### 2) Docket Clerk selects Attachment to Petition as the document type for a paper filing; Clerk is able to select Petitioner(s) as filer.

- Continuing from the previous test
- Select Attachment to Petition from the document dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - Fields available on the add paper filing screen include the date filed, Mailing Date (optional), Additional info 1, checkbox to add to coversheet, and Additional info 2.
- [x] **NEW FUNCTIONALITY** - Clerk can select Petitioner(s) as the filing party

 

#### 3) Docket Clerk Serves the Attachment to Petition; Document Title is reflected appropriately on the pop-up confirmation modal.

- Continuing from the previous test
- Click on the Save and Serve button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The pop-up service confirmation modal displays the document title correctly.


#### 4) Attachment to Petition is displayed appropriately on the Docket Record.

- Continuing from the previous test
- Click Done on the Print for paper service screen
- Review the docket record.

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Event Code on the docket record is ATP
- [x] **NEW FUNCTIONALITY** - The Document Title is Attachment to Petition
- [x] **NEW FUNCTIONALITY** - The filed by value is the filer that you selected in the previous test case
- [x] **NEW FUNCTIONALITY** - Served parties code is R 
- [x] **NEW FUNCTIONALITY** - Kibana logs confirm that only R was served
- [x] The rest of the information on the docket record is displayed as per usual (date filed, page number, service date, edit/seal links, etc.)


#### 5) Court User views the Attachment to Petition on the docket record; Document has a coversheet with the appropriate information.

- Continuing from the previous test
- Click on the Document title to open up the Document View page

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document has a coversheet with the title (Attachment to Petition)
- [x] The document coversheet includes all of the usual coversheet information (case caption, service date, docket number, index number, date filed, etc.)
- [x] The Attachment to Petition is available after the coversheet.


#### 6) Docket Clerk files a Motion for Leave to File; Attachment to Petition is available in the "Which Document is this Motion for leave to file for?" dropdown.

- Log in as a docket clerk
- Navigate to a case
- Click on the Create button
- Select Paper Filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Click on the document type dropdown and select Motion for leave to file or Motion for leave to file out of time.
- The "Which document is this motion for leave to file for?" dropdown appears.

Expected Results:
- [x] **NEW FUNCTIONALITY** - New document type titled Attachment to Petition is available in the dropdown list.
- [x] **NEW FUNCTIONALITY** - Upon selection of the Attachment to Petition, the Additional info 1, checkbox, and additional info 2 boxes display 
- [x] Clerk can select Petitioners as the filing party
- [x] Upon clicking on Save and Serve, the pop-up modal confirming service indicates the appropriate title of the document.
- [x] After clicking Yes, Serve, and after the Print for paper service, the document title on the Docket Record displays the title correctly (Attachment to Petition).

*Repeat this test with the Motion for Leave to File out of Time document.



#### 7) Docket Clerk adds an Attachment to Petition document on the Lead case in a Consolidated Group; Serves the document to all cases in the consolidated group.

- Log in as a Docket Clerk
- Navigate to the Lead case in a consolidated group
- Click on the Create Button
- Select Paper filing
- Upload a document
- Add in a Date Received and a Mailing Date
- Select Attachment to Petition as the document type
- Click Save and Serve

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Attachment to Petition document title appears on the "Are you ready to Initiate Service?" pop-up modal for multi-docketing.
- [x] **NEW FUNCTIONALITY** - After confirmation of service, the Attachment to Petitoin is now available on the docket record for all the selected cases
- [x] **NEW FUNCTIONALITY** - The Event Code on all of the docket records is ATP
- [x] **NEW FUNCTIONALITY** - The Document Title on all of the docket records is Attachment to Petition
- [x] **NEW FUNCTIONALITY** - The filed by value is the Petitioner(s) you selected
- [x] **NEW FUNCTIONALITY** - Served parties code is R
- [x] - [ ] **NEW FUNCTIONALITY** - Kibana logs confirm that only R was served
- [x] The rest of the information on the docket record is displayed as per usual (date filed, page number, service date, edit/seal links, etc.)
- [x] **NEW FUNCTIONALITY** - The document has a coversheet with the title Attachment to Petition, and lists all cases and index numbers that the document was served to.
- [x] **NEW FUNCTIONALITY** - The coversheet has all of the usual requirements for consolidated cases 

*Repeat this test by selecting only a few cases to serve the document to.
*Repeat this test by saving first, and then serving from the docket record
*Repeat this test by saving first, and then serving from the Document QC/In Progress tab



#### 8) Parties on the case can view the Attachment to Petition Document

- Log in as a Petitioner that has access to the case that you used above

Expected Results:
- [x] **NEW FUNCTIONALITY** - Party can click on the document title and can view the document

*Repeat this test with an IRS Practitioner, and a Private Practitioner that is a party to the case



#### 9) Terminal User can view the Attachment to Petition Document filed on cases.

- Access DAWSON as the Terminal User
- Search for a case that has an Attachment to Petition Document Filed.

Expected Results:
- [x] **NEW FUNCTIONALITY** - Terminal user can click on the document title and can view the document.



#### 10) Petitioner e-files a document on their case; Attachment to Petition is not available in the dropdown options for e-filing

**Part 1**
- Log in as a Petitioner
- Navigate to your case
- Click on the File a Document button
- Click on the Document Type dropdown

Expected Results:
- [x] There is no option for Attachment to Petition in the Dropdown options

**Part 2**
- Continuing from the steps above
- Select Motion for leave to File

Expected Results
- [x] There is no option for Attachment to Petition in the Dropdown options for the "Which document are you Requesting Leave to file for?" dropdown.

*repeat Part 2 test with the Motion for Leave to File out of Time
*repeat this entire test with a Private Practitioner and an IRS Practitioner to ensure that they cannot select Attachment to Petition either.


#### 11) Docket clerk edits a filing made by a petitioner; Clerk can select and change the document type to Attachemnt to Petition.

- Log in as a docket clerk
- Navigate to a case that has a document filed by a Petitioner (select a document that is NOT one of the Attachments to Petition that you used in previous test cases).
- Click on the Edit link.
- Click on the Document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - New document type titled Attachment to Petition is available in the dropdown list. 
- [x] **NEW FUNCTIONALITY** - Clerk can save the entry and the docket record displays the document title appropriately.
