### ISSUE TITLE
Practitioner: Remove Option to Generate EA for Cases w/ Paper Service

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8580]
As a practitioner, so that I do not create more work for the Court or myself, I need the generated Entry of Appearance option to only be available if all petitioner parties on a case have counsel or electronic service.

Despite admonition and requests to refrain from using the generated Entry of Appearance option if the EA requires a certificate of service, we continue to see high volumes of practitioners (mostly IRS) submitting generated EAs that should be served via paper to petitioner(s).

To stop this behavior, we would like to remove the option to generate the Entry of Appearance document if one or more petitioner parties are receiving paper service.

## Acceptance Criteria
* A practitioner filing an Entry of Appearance document is not shown the option to generate the Entry of Appearance document if the case in question has one or more parties receiving paper service.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement questions:
- Are Practitioners responsible for serving paper filings for ANYTHING they file? Or just specific documents like entry of appearance?

**Comment by katiecissell** [comment]
UX Notes:
- If one or more of the parties have paper service, then do not display the radio button options and instead simply default to uploading.

<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHRBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2d47b5b626ee95a93ca5e728c0f513215803792e/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner files an Entry of Appearance on a case where at least one Petitioner on the case receives paper service, No option is available to auto generate the EA document.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where there is more than one petitioner on the case, and the petitioner receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is only an option to upload the PDF form.
- [x] **NEW FUNCTIONALITY** - There is no option to auto-generate the Entry of Appearance.

**Part 2**
- Continue the File a document flow
- Be sure that you upload a PDF document and select who you are filing the EA document for
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] EA document is filed on the case as per normal. Practitioner is associated with the case.


#### 2) Private Practitioner files an Entry of Appearance on a case where there is an Intervenor on the case that receives paper service, No option is available to auto generate the EA document.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where there is an intervenor on the case, and the intervenor receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is only an option to upload the PDF form.
- [x] **NEW FUNCTIONALITY** - There is no option to auto-generate the Entry of Appearance.

**Part 2**
- Continue the File a document flow
- Be sure that you upload a PDF document and select who you are filing the EA document for
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] EA document is filed on the case as per normal. Practitioner is associated with the case.

*Repeat this test with a Participant that receives Paper service.


#### 3) Private Practitioner files an Entry of Appearance on a case where all Petitioners on the case receive electronic service, Option to auto generate the EA document is available.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where the petitioner(s) has electronic service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are two options for filing the EA
- [x] **NEW FUNCTIONALITY** - The options are Upload PDF and auto-generate the Entry of Appearance (as per usual).

**Part 2**
- Continue the File a document flow
- Be sure that you select auto-generate, and select who you are filing the EA document for
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] Auto-generated EA document is filed on the case as per normal. Practitioner is associated with the case.

*Repeat this test and instead select Upload PDF.



#### 4) Repeat tests 1 - 3 with an IRS Practitioner.

- [x] Test 1 Passes with an IRS Practitioner
- [x] Test 2 Passes with an IRS Practitioner
- [x] Test 3 Passes with an IRS Practitioner

**Comment by ttlenard** [comment]
Testing Feedback: @codyseibert @Absolutestunna 

This story passes all the test cases, but I did notice that if you preview the Entry of Appearance document that you uploaded, the File name of the PDF that you uploaded changes when you submit the Entry of Appearance.  Is this ok?

Preview the document that you uploaded:
<img width="1157" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fa25320baee82255e7284ad3ec1dae0d61da74c/image.png" alt="image.png" />


When you submit it, the file name changes. 
<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0p0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--edd6ec9ccb7727b7192388953b807c1e05f57862/image.png" alt="image.png" />

Is this a problem? Or is this ok?

**Comment by ttlenard** [comment]
After meeting with Josh and Cody, I've entered a bug ustaxcourt/ef-cms#8591 for the issue I found that is detailed in the comment above.
