### ISSUE TITLE
Ignore Username Case Sensitivity On Login

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8581]
As a DAWSON user, so that I can easily access DAWSON, I need the username field to ignore case sensitivity when logging in.

In ustaxcourt/ef-cms#8436 we established a new hosting page for logins to DAWSON. To complete this functionality we would like to make logging into the system smart enough to recognize and authenticate a user when the only difference between the input name and the stored name is the character case.

To this end, we would like to parse usernames logging into the system in a manner that allows us to retrieve and log in a user who types in a valid username and password even if there are differences in the capitalization between the input name and the stored name.

## Pre-Conditions
ustaxcourt/ef-cms#8436

## Acceptance Criteria
* User can log into DAWSON with valid username/password combination even when there are differences in capitalized characters between the input username and the stored username
* Users entering an exact match between input username and stored username with the correct password are logged in as normal
* Ensure data is normalized as per notes section below

## Notes
* Do we need to figure out how to resolve the following scenario?
TESTUSER@example.com/12345 exists
testuser@example.com/12345 exists

User enters TestUser@example.com/12345

* Feedback from @mmarcotte :

1. We need to perform cleanup outside of the scope of this story. I know I've run a full report on every user that has a duplicate account.
2. From that report, I'm optimistic that we can remove all but a very small handful of duplicate accounts that were created in error. These would be accounts where there is a Practitioner record and a Petitioner record, and there really should be no practitioner record.
3. If there happens to be two of the same type of record that both have cases, we should consolidate those.

User gets logged into whichever one of those it attempts to authenticate first.
Attempt to login TestUser@example.com/12345
Fail
Get users matching TestUser@example.com
Found 2, TESTUSER@example.com, testuser@example.com
Attempt to login TESTUSER@example.com/12345
Success!

## Tasks
- [ ] Refactor cognito so every account has and can be looked up by custom:userId. 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] Swagger docs have been updated if API endpoints have been added or updated.
 - [x] UI should be touch optimized and responsive for external users.
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Features have been optimized where possible to reduce response times. For example, reducing api response times, parallelizing client network calls, optimizing database reads, etc.
 - [x] Types have been added to all added and updated functions.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] Code that resides in the shared folder that only runs on the API or browser has been moved to either /web-client or /web-api.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) User creates and verifies a new petitioner account; On login, user types in different capitalization for the email, User can log in successfully.

**PART 1**
- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all lower-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all capital letters (this is different than when you signed up - you should have used all lowercase.)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [x] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**PART 2**
- Repeat the above steps, but instead of all capital letters, use a combination of lower case/upper case.

Expected Results:
- [x] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.



#### 2) Regression test - User creates and verifies a new petitioner account; On login, user types in the same capitalization for the email, User can log in successfully.

- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all lower-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all lowercase (matching how you input it on account creation)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [x] User can log in to DAWSON successfully


#### 2) Regression test - Ensure that Passwords are still case sensitive.

- Repeat test 1 but at the Password step, input a password that is in a different case
- Click Log in

Expected Results:
- [x] User cannot log in.



#### 3) Regression test - User creates a new account, Inputs their username with all capital letters; On log in, user can log in to DAWSON capitalization.

**PART 1**
- From the Create Petitioner Account page, input all valid fields
- Be sure that the email address that you enter is input in all upper-case letters, is one that you have access to, and NOT an email that is already in use in DAWSON.
- Be sure that you remember your password.
- Click on the Continue button once all of the fields have been filled out.
- Navigate to your email and verify it.
- Navigate to the log in page
- Input your email address in all lower-case letters (this is different than when you signed up - you should have used all uppercase.)
- Input your password in the same case that you used when signing up.
- Click Log in

Expected Results:
- [x] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**PART 2**
- Repeat the above steps, but instead of all capital letters during account creation, use a combination of lower case/upper case.

Expected Results:
- [x] **NEW FUNCTIONALITY** - User can log in to DAWSON successfully even though their email was entered in a different case.

**Some additional test cases - Added 4/19**
- [x] Petitioner creates and verifies an account.  Goes to create account page and attempts to create another account with the same email, but with different capitalization.  Receives an alert that the account already exists and that they can go to the log in page or go through the forgot PW flow.
- [x] Admissions clerk creates a Practitioner account with all lowercase, when Practitioner signs in, they use different capitalization, user can log in successfully. (repeat this test but have admissions clerk use all caps/mixed case).
- [x] Admissions clerk creates a Petitioner account with all lowercase, when Petitioner signs in, they use different capitalization, user can log in successfully. (repeat this test but have admissions clerk use all caps/mixed case).
- [ ] Admissions clerk runs the "add court user" automation in Zendesk - inputs user in mixed case, user can log in with any capitalization
- [ ] Admissions clerk runs the "delete court users" automation in Zendesk - inputs a different case than the email, user is deleted successfully
- [x] User goes through the forgot password workflow, inputs an email that is in a different capitalization - user still receives an email with a password reset code.
- [ ] Test automations in Zendesk with different capitalizations in the email - automations work per normal
     - [x] update email no access
     - [x] overwrite email
     - [ ] resend
     - [ ] add-to-closed
     - [ ] deactivate-court-user
     - [ ] create-court-user
     - [x] reg-status 
- [ ] Need to update Macros in Zendesk
- [x] Case sensitivity on Mobile

**Comment by jtdevos** [comment]
I've researched the cognito documentation and had a couple conversations w/ Tom & Jim about the issue.  Capturing my notes here so I don't forget.

- Regarding migrating to new cognito user pool 
	- Our cognito user pools are case-sensitive, which was the default when we created them.  
	- There is no way to enable/disable case sensitivity on existing pool.  The only option is to create a new pool with the desired configuration and then to migrate accounts from the old pool to the new pool.
	- To my knowledge, these are the only ways to perform a migration:
		- using a "Migrate user lambda trigger". (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-import-using-lambda.html). AWS invokes this lambda when a user atttempts to log in but cognito does not find the requested user in the user pool. Upside: AWS retains credentials and user does not need to reset password.   Downside: There is no way to perform this type of migration in bulk. So we would presumably double the number of cognito user pools: one set of new case insensitive pools, and a legacy set that only serves as a reference for the migrate lambda.
		- Bulk import CSV into cognito. Upside: can be done as one-time operation.  Downside: effectively resets all user account passwords.
		- Bulk import using Cognito API/SDK. Here we would just be using API calls to get the list of users from the old pool and then using API calls to add them to the new pool.  Same downside: effectively resets user account passwords.
	- Given the above, in my opinion the best bet is to simply implement case-insensitivity in-app (as described by the ticket).  But I don't have strong feelings about it yet as I have more to learn about this ticket.
	- Per a chat w/ Jim L., I beleive that some work has already been done in terms of identifying "dupe" accounts (i.e. accounts that resolve to the same down-cased value).  But I'm less clear if we have performed any de-duping yet.

**Comment by jhansen-flexion** [comment]
Per Chris on 4/7:  proceed with implementing the lower-case solution on the front end and keeping our existing Cognito user pool.

**Comment by zachrog** [comment]
## Deployment Steps:
- Use the environment switcher to point to the deploying environment.
- Run an account specific deploy:
`npm run deploy:account-specific`
- Run the migration script:
`npx ts-node --transpile-only scripts/run-once-scripts/cognitoUserIdAndEmailMigration.ts`
- Kick off Circle deploy

**Comment by rachelschneiderman** [comment]
@cholly75 @ttlenard @mmarcotte Reminder that ZenDesk automations need to be updated to remove "usernames are case sensitive" language before this story is deployed

**Comment by mmarcotte** [comment]
Hey just a quick note that we have a mixed case caseServicesSupervisor1 in `users.json` that you will likely need to lowercase

**Comment by ttlenard** [comment]
@zRogersFlexion @rachelschneiderman @codyseibert Some testing feedback:

Seems there is a problem when Admissions clerks create an account for a user, the user MUST input the same exact capitalization as when the Admissions clerk created the account, or else the user's account is only "half" saved correctly.  See steps below on how to reproduce

1. Log in as an Admissions clerk
2. Go to a case where a petitioner on the case has paper service
3. Click edit on their contact card
4. Add in an email that you have access to with any combination of capitalization (doesn't matter for this test), but REMEMBER how you input the email.
5. Create the new account for this user
6. Log out
7. Navigate to your email and find the email for the account you just created
8. Click the link to navigate to the dawson login page from your email
9. For the email address, input the email in the EXACT same case.
10. You should get the update password page
11. Update the PW and log in
12. Everything should work PERFECTLY.
13. Next, repeat steps 1-8
14. Instead of inputting the email EXACTLY the same, input the email with different capitalization
15. You will get the update PW step, and you will log in, but you will see the following:
     - On the My cases page, you will still see the banner indicating that you have a pending email
     - If you click on the My account page, there will not be any Service email listed for the user
     - If you click on the case docket number and then go to the Case information screen, your email is not associated with the user, and they still have paper service
     - If you log in as a Court user and navigate to the case, click on Case information tab, you will see that their email is still in a pending status.

When I log in, I see this yellow alert, even though I just confirmed my email and updated my PW:
<img width="1411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUdJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c582df6b2c3da37ab5a1b150434b2a76782b734/image.png" alt="image.png" />

If I click on the my account link, I don't have any email associated with my account:
<img width="1647" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUtJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--665fd97c46472656a46c495a2d28838cb5ee2e36/image.png" alt="image.png" />

When I go into my case, my email is not associated with my contact card, and I still have paper service:
<img width="1406" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVdJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--58be86ca192fa6d260f9a8ecd1fc84e451393a4a/image.png" alt="image.png" />
