### ISSUE TITLE
Add Pending Motions to Activity Report

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8584]
As a judge or chambers user, so that the Activity report is a comprehensive reflection of outstanding action items, I need Pending Motions tracked on my dashboard reflected on the Activity report.

With the addition of Pending Motions (motions outstanding for greater than 180 days) to the Judge/CA dashboard, the next step is to reflect these as part of the overall judge activity on the Activity report.

## Acceptance Criteria
* When the Activity report is run for a single judge, it reflects the same Pending Motions data included on the judge's dashboard, including the assigned judge and contextual data entered by the user 
* When the Activity report is run for multiple judges, it reflects the aggregate Pending Motions data from the selected judges' dashboard, including the assigned judges and contextual data entered by the users
* Pending Motions are displayed in order from oldest -> newest
* Pending Motions data is captured in its entirety regardless of the date range selected when running the report

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- are we showing only pending motions 180 days and older? YES
-

**Comment by katiecissell** [comment]
UX Notes:
The activity report should be organized into three tabs. Statistics is the default. The judge selector will apply to all tabs. The date selector will be moved to the statistics tab as it only effects that tab.

There should be an empty state for statistics tab if no date is selected:
<img width="753" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmxoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9048b19540319a69ad71defeb35e5223a6c619a3/image.png" alt="image.png" />
___
Statistics tab with date selected:
- if the judge is changed, clear out statistics date fields/data. They will have to reenter date and view to see the updated info.
<img width="715" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea33654508991495d341d642ce817ec382cab277/image.png" alt="image.png" />
___
Submitted/CAV tab:
Note: change the "Total" counter to "Count".
<img width="876" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnhoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71838d25f521b938eaccb18c6a9de1aef2c80e24/image.png" alt="image.png" />
___
Pending Motions:
- use the message from the dashboard for the empty state
- add judge as the third column (Judge column was not necessary on dashboard because you can't change judge there, but you can here)
<img width="831" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0ZoQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--956c272c0e57edcffcb09cfbbc511d2b9afa7fbe/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Judge user accesses the activity report; Logged in Judge is the default Judge in the picklist; There are now 3 tabs, with Statistics being the default "Active" tab displayed with the date fields below.

- Log in as a Judge
- Click on Reports, and then select Activity

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Judge dropdown has been renamed to "Show items for"
- [x] The logged in Judge is the Judge listed in the "Show items for" dropdown menu
- [x] **NEW FUNCTIONALITY** - The Activity report has a new look and feel, with 3 tabs (Statistics, Submitted/CAV, and Pending Motions) as three tabs
- [x] **NEW FUNCTIONALITY** - The Statistics tab is the default, with blank date fields
- [x] **NEW FUNCTIONALITY** - The Run report button has now been renamed to "View Statistics" and it is greyed out 
- [x] **NEW FUNCTIONALITY** - Text underneath the date fields reads "Enter a date range to view statistics"

*Repeat this test with a Chambers user



#### 2) Judge user can click on the Submitted/CAV tab or the Pending Motions tab to view data without inputting in a date.

- Continuing from the previous test
- Click on the Submitted/CAV tab and the Pending Motions Tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV tab has the data loaded and doesn't need to have the date picker fields in order to display the data.
- [x] **NEW FUNCTIONALITY** - The Pending Motions tab has the data loaded and doesn't need to have the date picker fields in order to display the data.

*Repeat this test with a Chambers user



#### 3) Judge user adds a date range on the statistics tab; Clicks view statistics; statistic data displays appropriately.

- This is partly a regression test to ensure that the data displays appropriately.
- Continuing from the previous test
- Click on the Statistics tab
- Input a date range with valid dates
- The View Statistics button should activate
- Click on the View Statistics button

Expected Results
- [x] The statistics portion of the activity report should work as designed in previous stories.

*Repeat this test with a Chambers user



#### 4) Judge user views the Submitted/CAV tab; data displayed in this table matches the data that is on the Dashboard for the signed in Judge.

- This is partly a regression test to ensure that the data displays appropriately
- Continuing from the previous test
- Click on the Submitted/CAV tab
- Data should already be populated based off of the logged in Judge user (defaulted in the "Show items for" dropdown)

Expected Results:
- [x] The data present in the Submitted/CAV matches the data that is displayed in the Case Inventory report (cases in submitted, submitted Rule 122, and CAV status)
- [x] Ensure that the data that had been entered for these cases in the primary issue, Final Brief Due date and status of matter fields prior to the release of this story remains intact and associated to the correct case.
- [x] **NEW FUNCTIONALITY** - The top right of the table now displays "Count" instead of "Total".
- [x] **NEW FUNCTIONALITY** - The Submitted/CAV tab header also displays the Count, and it matches what displayed at the top right of the table.

*Repeat this test with a Chambers user



#### 5) Judge user views the Pending Motions tab; data displayed in this table matches the data that is on the Dashboard for signed in Judge

- Continuing from the previous test
- Click on the Pending Motions tab
- Data should already be populated based off of the logged in Judge user (defaulted in the "Show items for" dropdown)

Expected Results:
- [x] **NEW FUNCTIONALITY** - The data present in the Pending Motions tab matches the data that is displayed on the Judge's Dashboard view
- [x] **NEW FUNCTIONALITY** - The primary issue, Final Brief Due date and status of matter fields display the same data that was entered from the Judge's Dashboard, data on the activity report is not editable.
- [x] **NEW FUNCTIONALITY** - The top right of the table displays "Count".
- [x] **NEW FUNCTIONALITY** - The Pending Motions tab header also displays the Count, and it matches what displayed at the top right of the table.
- [x] **NEW FUNCTIONALITY** - There is a Judge Column that displays the same judge that is in the "show items for" dropdown above.
- [x] **NEW FUNCTIONALITY** - Pending motions are displayed in order from oldest to newest
- [x] **NEW FUNCTIONALITY** - The pending motions do not rely on the date range selected (if any) and show all pending motions for said judge that are 180 days or more.

*Repeat this test with a Chambers user



#### 6) Judge user selects a different judge in the Judge dropdown; Pending motions data is updated to reflect that Judge user's pending motions.

- Continuing from the previous test
- While on the pending motions tab, change the Judge user in the Showing items for dropdown.

Expected Results
- [x] **NEW FUNCTIONALITY** - The name of the report at the top of the page is updated to the selected Judge User and today's date.
- [x] **NEW FUNCTIONALITY** - The count that is displayed in the Tab headers for Submitted/CAV and Pending motions are updated with the new values for the selected Judge.
- [x] **NEW FUNCTIONALITY** - The data present in the Pending Motions tab matches the data that is displayed on the selected Judge's Dashboard view
- [x] **NEW FUNCTIONALITY** - The primary issue, Final Brief Due date and status of matter fields display the same data that was entered from the Judge's Dashboard, data on the activity report is not editable.
- [x] **NEW FUNCTIONALITY** - The top right of the table displays "Count".
- [x] **NEW FUNCTIONALITY** - The Pending Motions tab header also displays the Count, and it matches what displayed at the top right of the table.
- [x] **NEW FUNCTIONALITY** - There is a Judge Column that displays the same judge that is in the "show items for" dropdown above.
- [x] **NEW FUNCTIONALITY** - Pending motions are displayed in order from oldest to newest
- [x] **NEW FUNCTIONALITY** - The pending motions do not rely on the date range selected (if any) and show all pending motions for said judge that are 180 days or more.

*Repeat this test with a Chambers user



#### 7) Judge user selects All Judges in the Judge Dropdown; Pending motions data is updated to reflect the selected Judges pending motions.

- Continuing from the previous test
- While on the pending motions tab, change the Judge user in the Showing items for dropdown to All Judges.

Expected Results
- [x] **NEW FUNCTIONALITY** - The name of the report at the top of the page is updated to display "All Judges" and today's date is displayed.
- [x] **NEW FUNCTIONALITY** - The count that is displayed in the Tab headers for Submitted/CAV and Pending motions are updated with the new values for the selected Judge group.
- [x] **NEW FUNCTIONALITY** - The data present in the Pending Motions tab matches the total number of pending motions for all judges that are 180 days or more. (can double check this against the pending report - be aware that if a motion was multi-docketed, then the pending motion will only be displayed for the lead case on the Pending motions tab, but on the pending report it will display all of motions in all of the cases)
- [x] **NEW FUNCTIONALITY** - The primary issue, Final Brief Due date and status of matter fields display the same data that was entered from the Judge's Dashboard, data on the activity report is not editable.
- [x] **NEW FUNCTIONALITY** - The top right of the table displays "Count".
- [x] **NEW FUNCTIONALITY** - The Pending Motions tab header also displays the Count, and it matches what displayed at the top right of the table.
- [x] **NEW FUNCTIONALITY** - There is a Judge Column that displays the correct name of the Judge for each pending item.
- [x] **NEW FUNCTIONALITY** - Pending motions are displayed in order from oldest to newest
- [x] **NEW FUNCTIONALITY** - The pending motions do not rely on the date range selected (if any) and show all pending motions for said judge group that are 180 days or more.

*Repeat this test by selecting other Judge Groups

- [x] All Regular Judges
- [x] All Senior Judges
- [x] All Special Trial Judges

*Repeat this test with a Chambers user



#### 8) Judge user selects a Judge that doesn't have any Pending Motions on the Activity report; Text on the report states, "There are no pending motions for 180 days or more".

- Continuing from the previous test
- Be sure you are on the Pending motions tab
- Select a Judge from the dropdown that does not have any Pending motions

Expected Results:
- [x] **NEW FUNCTIONALITY** - Text on the report states, "There are no pending motions for 180 days or more".

*Repeat this test with a Chambers user

*Repeat this test but on the Submitted/CAV tab
Expected Results:
- [x] Report states, "There are no cases with a status of "Submitted" or "CAV".

*Repeat this test but on the Statistics tab
Expected Results:
- [x] Report states, "There is no activity for the selected dates"



#### 9) Judge user views data on the Statistics tab, changes the judge; the previous statistics data that was generated no longer displays, original dates input are cleared.

- Log in as a Judge user
- Click on Reports, and then select Activity
- Leave the default judge in the dropdown
- Input valid dates and click view statistics
- Next, change the Judge in the dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - The title of the report has updated to display the newly selected Judge and today's date
- [x] **NEW FUNCTIONALITY** - The original dates that you input in the date fields are cleared and the report data has been cleared.
- [x] **NEW FUNCTIONALITY** - The tab headers for Submitted/CAV and Pending motions have updated to reflect the new Judges values for how many cases/motions apply to the selected judge(s)
- [x] **NEW FUNCTIONALITY** - After clicking View statistics, the appropriate data for the selected Judge is displayed on the statistics tab.

*Repeat this test with a Chambers user



#### 10) Judge user views data on the Statistics tab, then goes to other tabs and changes the judge; When returning to the Statistics tab, the previous statistics data that was generated no longer displays, original dates input are cleared.

- Log in as a Judge user
- Click on Reports, and then select Activity
- Leave the default judge in the dropdown
- Input valid dates and click view statistics
- Next, click on Submitted/CAV or Pending Motions tab
- Change the Judge user to see different results on the Submitted/CAV or Pending tabs
- Next, Click on Statistics tab again

Expected Results:
- [x] **NEW FUNCTIONALITY** - The original dates that you input in the date fields are cleared and the report data has been cleared.
- [x] **NEW FUNCTIONALITY** - When you add in dates and then click view statistics, it will display for whatever Judge User is in the dropdown above.
- [x] **NEW FUNCTIONALITY** - If you navigate off of the Activity report and come back, the dates that you originally input do NOT persist.

*Repeat this test by viewing statistics, viewing other tabs on the activity report, and then changing the selected Judge, whenever you return to the statistics tab, the report data and the dates should be cleared.
*Repeat this test with a Chambers user



#### 11) Regression test updating the Judge user/sorting the data on the Submitted/CAV tab

- Continuing from the previous test
- Click on the Submitted/CAV tab
- Be sure that there is a group of Judge's selected 
- Sort the table by Judge or Days in Status

Expected Results:
- [x] The sorting of the data works as per normal.

*Repeat this test with a Chambers user



#### 12) Regression test updating the dates/Judges with the data on the Statistics Tab

**Part 1**
- Continuing from the previous test
- Click on the statistics tab
- Input valid and invalid dates

Expected Results:
- [x] Invalid dates return validation errors

**Part 2**
- Change the Judges/dates and view statistics data

Expected Results
- [x] Results tables displays the correct values per the dates/Judge(s) selected.

*Repeat this test with a Chambers user

**Comment by ttlenard** [comment]
Testing feedback

@cruzjone-flexion @nechama-krigsman @codyseibert 

I'm getting a 504 error when attempting to run the Pending Motions Activity report for All Judges. See Screen Grabs:

<img width="1902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59e2936dab720e8af2301f2968e64cbe7a738408/image.png" alt="image.png" />

<img width="1630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFvQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5204c5dc7fb89ad0aba2732acfa2bcbd18dd889/image.png" alt="image.png" />
