### ISSUE TITLE
Petitions Clerk: Attachments to Petitions (Paper Petitions Flow)

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8588]
As a petitions clerk, so that I can accurately represent attachments to a petition on the docket record, I need to be able to upload and scan in attachments to a petition.

We are beginning the process of treating attachments to a petition as their own entry on the docket record, in an effort to provide better clarity and transparency around the petition itself. 

## Pre-Conditions
ustaxcourt/ef-cms#8578

## Acceptance Criteria
* When entering a paper petition, the petitions clerk can upload/scan in a PDF as part of the overall petitions package UI labelled "ATP" in the same manner as the CDS/STIN
* Documents uploaded/scanned into the ATP view of the petitions package are docketed as ATP event codes when the petition is saved
* ATPs are served on Respondent concurrently with the service of the petition
* ATPs receive cover sheets when docketed
* Preview link to ATP is listed in the Attachments card of the Review and Serve screen for Petition

## Tasks
- [x] Add ATP button and upload pdfs via scanning or upload (save for later) 
    -- confirm it appears on docket record (unserved)
- [x] Serve ATP 

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [x] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [x] Reviewed by UX on a deployed environment.
 - [x] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX notes: 
There should be a new tab in the petitions QC process called ATP which allows the upload of a PDF. No changes are needed to be made to the IRS entry fields. 

<img width="965" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--589cc39bbf9632f967a9badb20d186cfd31f213c/image.png" alt="image.png" />


<img width="745" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHFHQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--864cb5bb91c4cec21deda8c345e8b697888bd742/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitions clerk starts to QC a paper petition; New tab is available labeled ATP in the Add Document(s) section.

- Log in as a Petitions Clerk
- Click on Document QC tab
- Click on the Start a new Petition button

Expected Results:
- [x] **NEW FUNCTIONALITY**


#### 2) Petitions Clerk inputs data for a paper petition; Indicates that an IRS Notice was provided, but does not scan/upload an ATP; No Validation errors after clicking Create Case button.

- Continuing from the previous test
- Fill in the required information for the Petitioner on the Parties tab and Case Info tab
- On the IRS Notice tab, be sure that you select the radio button for Yes, the IRS Notice was provided
- Fill out the rest of the required info on the IRS Notice tab, upload a Petition and STIN, but do not upload/scan a document for the ATP tab.
- Click on the Create Case

Expected Results:
- [x] Review and Serve Petition screen displays


#### 3) Petitions Clerk has option to scan or upload an ATP document(s)

- Continuing from the previous test
- Click on the Edit link on the IRS Notice tab
- Click on the ATP tab

Expected Results
- [x] **NEW FUNCTIONALITY** - The option to Upload or Scan is available for the Clerk


#### 4) Petitions Clerk selects Scan; Clerk can scan one or multiple documents as per usual.

- Continuing from the previous test
- Click on the Scan radio button
- Ensure that the correct Scanner is selected
- Click on the Start Scan button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document that was scanned displays in the document preview
- [x] **NEW FUNCTIONALITY** - User can scan other documents and they display as batches
- [x] **NEW FUNCTIONALITY** - User can remove a batch if needed
- [x] **NEW FUNCTIONALITY** - User can click Create PDF button to combine all uploaded documents into one single ATP.


#### 5) Petitions Clerk clicks on the Create Case button/Review Petition button after scanning in an ATP; ATP is displayed as a link on the Review and Serve Petition Screen.

- Continuing from the previous test
- Click on the Create Case button (or Review Petition button)

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a link for the Attachment to Petition document on the Attachments Card
- [x] **NEW FUNCTIONALITY** - Clicking on the link for the Attachment to Petition displays the document preview modal, and the scanned document displays


#### 6) Petitions Clerk Saves the Petition for later; ATP document displays on the docket record of the case but has not been served.

- Continuing from the previous test
- Click on the Save for later button
- Click on the In Progress tab
- Click on the docket number link for the case you just saved

Expected Results:
- [x] **NEW FUNCTIONALITY** - Docket record opens and the Petition, RQT, and ATP are on the docket record, but they have not yet been served.
- [x] **NEW FUNCTIONALITY** - Clerk can open the ATP and view the document
- [x] **NEW FUNCTIONALITY** - There is no coversheet on the ATP (or any of the documents on the docket record) yet, since they have not been served.


#### 7) Petitions clerk clicks on the Review and Serve Petition Link, Serves the petition to the IRS; ATP is served on Respondent, ATP is displayed appropriately on the docket record.

- Continuing from the previous test
- Click on the Attachment to Petition link from the docket record (no link to serve should be available on the document preview section)
- Click on the Review petition link from the docket record
- Click on the Review and Serve Petition link
- Click on the Review Petition button
- Click on the Serve to IRS button
- Click Yes, Serve
- Click Done on the Print paper Petition page
- Click on the Docket Record tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Attachment to Petition is on the Docket Record 
     - [x] **NEW FUNCTIONALITY** - Event Code is ATP
     - [x] **NEW FUNCTIONALITY** - Title is Attachment to Petition
     - [x] **NEW FUNCTIONALITY** - Pages are reflected appropriately
     - [x] **NEW FUNCTIONALITY** - Filed by is the Petitioner
     - [x] **NEW FUNCTIONALITY** - Served date is today's date
     - [x] **NEW FUNCTIONALITY** - Served Parties Code is R.


##### 8) Petitions Clerk opens the Attachment to Petition document, Document has a coversheet.

- Continuing from the previous test
- Click on the document title on the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The ATP has a document coversheet that includes the typical information on the coversheet (case caption, filed date, served date, docket number, etc.



#### 9) Logs indicate successful service to the IRS Service agent

- Continuing from the previous test
- Review the logs to ensure that the IRS Service agent received the Attachment to Petition document

Expected Results:
- [x] **NEW FUNCTIONALITY** - Logs show that the ATP was served appropriately.


#### 10) Petitions Clerk inputs a Petition, Uploads an ATP, Document uploads appropriately.

- Log in as a Petitions Clerk
- Click on Document QC
- Click Start a new petition
- Fill out the required fields for on the party, Case info, and IRS notice tabs
- Upload a petition, a STIN, and then upload an ATP document on the ATP tab
- Click Create Case

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a link for the Attachment to Petition document on the Attachments Card
- [x] **NEW FUNCTIONALITY** - Clicking on the link for the Attachment to Petition displays the document preview modal, and the uploaded document displays.


#### 11) Petitions Clerk Serves the Petition to the IRS; ATP is served on Respondent; ATP is displayed appropriately on the docket record.

- Continuing from the previous test
- Close out of the preview
- Click on the Serve to IRS button
- Click Yes, Serve
- Click Done on the Print paper Petition page
- Click on the Docket Record tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Attachment to Petition is on the Docket Record 
     - [x] **NEW FUNCTIONALITY** - Event Code is ATP
     - [x] **NEW FUNCTIONALITY** - Title is Attachment to Petition
     - [x] **NEW FUNCTIONALITY** - Pages are reflected appropriately
     - [x] **NEW FUNCTIONALITY** - Filed by is the Petitioner
     - [x] **NEW FUNCTIONALITY** - Served date is today's date
     - [x] **NEW FUNCTIONALITY** - Served Parties Code is R.


##### 12) Petitions Clerk opens the Attachment to Petition document, Document has a coversheet.

- Continuing from the previous test
- Click on the document title on the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The ATP has a document coversheet that includes the typical information on the coversheet (case caption, filed date, served date, docket number, etc.



#### 14) Logs indicate successful service to the IRS Service agent

- Continuing from the previous test
- Review the logs to ensure that the IRS Service agent received the Attachment to Petition document

Expected Results:
- [x] **NEW FUNCTIONALITY** - Logs show that the ATP was served appropriately.



#### 13) Repeat this test with the Cotc and CSS role.

- [x] Tests 1-12 pass with Cotc and CSS user roles.
