### ISSUE TITLE
Get some statistics for Clerks of the Court

### ISSUE THREAD

**Issue by mmarcotte** [ustaxcourt/ef-cms#859]
## Tasks:

- [x]  Get a sheet of ZIp Codes for petitioners with open cases
- [x] How many documents with code LEA​ were filed between June 1, 2020 - November 21, 2020?
- [x] List of cases (docket numbers) w/ suffix with document code TCOP​MOP​ or SOP​filed October 1, 2019 - September 30, 2020.
- [x] Number of open cases with petitioner's counsel
- [x] Number of total open cases
- [x]  For cases with a filed date of October 1, 2019 - September 30, 2020, how many are:
  * Regular
  * Small
  * Lien/Levy -- L suffix on Docket Number 
  * Whistleblower -- W suffix on Docket Number 
  * Passport -- P suffix on Docket Number 
  * Declaratory judgments for Exempt Orgs -- X suffix on Docket Number
  * Declaratory Judgment for retirement plan revocation -- R suffix on Docket Number 
  * Disclosure case -- D suffix on Docket Number

**Comment by mmarcotte** [comment]
```
{
  eventCode: 'LEA',
  num: 18,
  startWindow: '2020-06-01T00:00:00Z',
  endWindow: '2020-11-21T00:00:00Z'
}
```

**Comment by mmarcotte** [comment]
```
13905-16
8711-16
8721-18
25268-18
19356-15L
23676-16
3880-16W
8649-17
12519-16
13022-17L
27693-14
3435-19
17435-17
11061-17L
3300-11
4118-18
26829-08
27313-13
588-18
20266-18
2108-16
32168-15
13836-19L
7859-19L
19031-13
15274-17L
5742-18
9623-16
8999-17L
6871-19L
11728-17
23155-14
17291-14L
20552-17
23359-15
14514-18
4817-19W
11239-19W
3411-19
22182-10
19871-15
22285-16
31162-14
4346-18L
12017-16
2458-19L
28426-15W
29815-13
12309-17
6829-18
12037-17
26557-17
24704-15
23623-17L
4491-19
21684-18W
26975-17
12498-16
20941-16
16250-17
14898-17L
30224-12
427-17
30283-15
2426-18
10104-18
13059-16L
29743-14
13189-13
9539-15
10783-18L
9650-14
6936-17
2154-18
19146-18L
26865-08
18817-12
8457-16
21590-17
14765-15L
5092-17
22400-13
14914-19W
12315-17L
15855-15
9649-14
5783-18L
20940-16
10988-18
15853-16
27474-16
26921-16L
8249-18
21829-17X
22082-09
11838-16
26828-08
13226-17
6560-18
11642-18
23797-14
17039-18L
26867-08
23621-15
17041-18L
1099-18
5444-13
307-18L
24344-17
20245-18L
10198-17
11847-15
1117-18L
16947-18W
3272-18
23983-14
6663-18
1996-18
11905-14
17954-18L
10134-18L
6504-18
4803-15
10588-16
18571-16
9169-17
20306-15
23283-18L
1870-16R
5089-17
1031-17
21591-17
14368-15
22852-17
9526-19
29356-14
9768-15
6345-14
27538-08
25395-16
14076-17
15791-17L
27344-16
14294-13L
29484-14
23713-17
4825-18
7013-17
21922-15
25306-14
15303-16
7579-18
26210-16
26210-16
23647-15
10531-17
27321-13
6602-17L
4980-17
2928-17L
15742-19
5016-18
22528-14
8947-15
15440-18W
14432-14
4619-18L
8296-19L
9261-17
3354-11
6662-18
15112-16
23859-17
13659-17
13948-16L
1560-18
21209-09
11352-18
27735-13
20735-16L
191-18
5911-18
13550-15
3855-18
192-18
12151-17W
23809-17
26519-16
7441-19L
10266-19L
15941-12
27759-15
16301-16L
16605-18W
23105-18W
398-18L
20240-18
2564-18
427-16
8667-16
9033-19
15349-17
19493-17
10374-18L
5576-12
25751-15L
21277-13W
5444-13
27778-16
30309-12
11859-17
5760-19L
13986-17
27571-10
30020-15
28140-14
12231-12
19787-18W
3372-16
26889-16
17049-18L
20050-12
12810-18
9761-16W
14911-17W
6613-13
3634-18
14616-14L
21276-13W
14796-14
6188-19P
13987-17
4816-15
23479-14
19493-17
3842-18S
24302-15S
22664-18S
12809-18S
24303-15S
12911-15SL
14862-18S
16116-17S
20248-18S
17836-18S
18779-17S
30414-15S
18423-17SL
19359-18SL
9320-18S
6879-17S
19351-18S
23782-18S
12788-18S
5722-18SL
16317-15S
2104-18S
20640-17S
20188-18SL
4671-18S
1860-18S
12958-17S
5811-17S
22530-17S
23698-18S
8755-18S
21517-17SL
18257-18S
---
268 total cases found
```

**Comment by JessicaMarine** [comment]
@mmarcotte I think there is some confusion about:
- Number of open cases with petitioner's counsel
- Number of total open cases

This isn't a sub-request of the opinion question, it's a completely independent one.  We're looking for total # of open cases in the system and, of those, how many have counsel.

**Comment by mmarcotte** [comment]
17215 total open cases
6760 have a practitioner

**Comment by mmarcotte** [comment]
NOTE: I had to used the receivedAt... createdAt isn't indexed. 🤔 
```
{
  Regular: 6259,
  Small: 3741,
  L: 643,
  W: 123,
  P: 10,
  X: 14,
  R: 0,
  D: 0
}
```

**Comment by mmarcotte** [comment]
NOTE: I had to use `receivedAt` because we don't index `createdAt` for cases:

```
16988 total cases
----
{ 
  Regular: 10061, 
  Small: 6927, 
  L: 770, 
  W: 80, 
  P: 12, 
  X: 6, 
  R: 1, 
  D: 0 
}
```
