### ISSUE TITLE
Re-Enable EA Generation on Cases w/ Paper Service for Private Practitioners

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8604]
As a private practitioner, so that I can easily enter same-day appearances for clients at their Calendar Call, I need to be able to automatically generate Entries of Appearance for petitioners even if parties on the case receive paper service.

Recently to prevent abuse of the EA generation feature we disabled that functionality on cases with parties receiving paper service. 

Although the Court typically approaches functionality with an eye towards keeping the IRS and private practitioners on a level playing field, the Pro Se committee has determined that the interests of LITC attorneys and their ability to quickly enter representation at Calendar Calls presents a situation where the Court is comfortable having the functionality diverge.

To this end, we would like to re-enable the ability to generate EAs for cases with parties receiving paper service for private practitioners only.

## Acceptance Criteria
* Private Practitioners are given the option to have DAWSON generate the Entry of Appearance form even when there are parties receiving paper service associated with the case as per ustaxcourt/ef-cms#8455
* IRS Practitioners may only generate the Entry of Appearance form if there are no parties receiving paper service on the case

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Private Practitioner files an Entry of Appearance on a case where at least one Petitioner on the case receives paper service; Options to auto-generate or upload the PDF are available.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where there is more than one petitioner on the case, and at least one of the petitioners receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There is an option to upload the PDF form.
- [x] ** NEW FUNCTIONALITY** - There is also an option to auto-generate the Entry of Appearance.

**Part 2**
- Indicate the party or parties that you are representing
- Select the Auto-generate option 
- Click Review Filing

Expected Results
- [x] **NEW FUNCTIONALITY** - There is a document preview on the right side of the screen where the user can review the auto-generated document
- [x] **NEW FUNCTIONALITY** - Auto-generated document matches the format from Story 10054
- [x] **NEW FUNCTIONALITY** - the party/parties that the Practitioner selected in the previous step are populated in the form correctly
- [x] **NEW FUNCTIONALITY** - The Name, Address (1-3 address lines depending on what is stored for the practitioner), City, State, Phone, Bar #, and email address are all populated correctly based off of the information that is stored for the Practitioner in the Database (You will need to review the information about the practitioner in the DB to ensure that the data matches.)
- [x] **NEW FUNCTIONALITY** - The format of the auto-generated EA matches the mockups in 10054
- [x] Clicking on the Document link displays the same auto-generated EA in a pop-up window.
- [x] There is no section for "Document Includes" displayed for auto-generated EA's.
- [x] There is no checkbox present for the user to certify that they have redacted information from their filing

**Part 3**
- Click the Submit Your Filing button

Expected Results
- [x] **NEW FUNCTIONALITY** - Generating PDF progress window is displayed
- [x] **NEW FUNCTIONALITY** - After PDF is generated, user is navigated back to the case docket record.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner with a Print Receipt link
- [x] **NEW FUNCTIONALITY** - After clicking on the print receipt, Receipt of Filing opens.  Information is displayed appropriately ex: Filed by lists the practitioner name, Date filed info is appropriate, and the EA is titled appropriately 
- [x] **NEW FUNCTIONALITY** - The Entry of Appearance document is displayed on the docket record
     - [x] Filed date is correct
     - [x] Event code is EA
     - [x] Document title reflects the petitioners that you selected appropriately
     - [x] Page number is correct (Should be 2 pages, 1 page is the EA, one page is the coversheet)
     - [x] Filed by is the practitioner name
     - [x] Served date is today's date
     - [x] Served party code is B
- [x] **NEW FUNCTIONALITY** - After clicking on the link to view the document, the document opens in a new tab
     - [x] Coversheet is appended to the auto-generated document
     - [x] Coversheet has the correct case caption, electronically filed, correct docket number, and document number, correct title, and correct served date.
     - [x] Auto-generated EA matches the format in the mockup in 10054
- [x] Service logs in Kibana reflect service was sent appropriately



#### 2) Private Practitioner files an Entry of Appearance on a case where there is an Intervenor on the case that receives paper service; Options to auto-generate or upload the PDF are available.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where there is an intervenor on the case, and the intervenor receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There is an option to upload the PDF form.
- [x] ** NEW FUNCTIONALITY** - There is also an option to auto-generate the Entry of Appearance.

**Part 2**
- Indicate the intervenor as the party that you are representing
- Select the Auto-generate option 
- Click Review Filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a document preview on the right side of the screen where the user can review the auto-generated document
- [x] **NEW FUNCTIONALITY** - Auto-generated document matches the format from Story 10054
- [x] **NEW FUNCTIONALITY** - the intervenor that they selected in the previous step is populated in the form correctly
- [x] **NEW FUNCTIONALITY** - The Name, Address (1-3 address lines depending on what is stored for the practitioner), City, State, Phone, Bar #, and email address are all populated correctly based off of the information that is stored for the Practitioner in the Database (You will need to review the information about the practitioner in the DB to ensure that the data matches.)
- [x] **NEW FUNCTIONALITY** - The format of the auto-generated EA matches the mockups
- [x] Clicking on the Document link displays the same auto-generated EA in a pop-up window.
- [x] There is no section for "Document Includes" displayed for auto-generated EA's.
- [x] There is no checkbox present for the user to certify that they have redacted information from their filing

**Part 3**
- Click the Submit Your Filing button

Expected Results
- [x] **NEW FUNCTIONALITY** - Generating PDF progress window is displayed
- [x] **NEW FUNCTIONALITY** - After PDF is generated, user is navigated back to the case docket record.
- [x] **NEW FUNCTIONALITY** - Green confirmation banner with a Print Receipt link
- [x] **NEW FUNCTIONALITY** - After clicking on the print receipt, Receipt of Filing opens.  Information is displayed appropriately ex: Filed by lists the practitioner name, Date filed info is appropriate, and the EA is titled appropriately (it's going to say Petr. instead of intervenor - this is ok for now)
- [x] **NEW FUNCTIONALITY** - The Entry of Appearance document is displayed on the docket record
     - [x] Filed date is correct
     - [x] Event code is EA
     - [x] Document title will indicate Petr (not intervenor) this is ok for now 
     - [x] Page number is correct (Should be 2 pages, 1 page is the EA, one page is the coversheet)
     - [x] Filed by is the practitioner name
     - [x] Served date is today's date
     - [x] Served party code is B
- [x] **NEW FUNCTIONALITY** - After clicking on the link to view the document, the document opens in a new tab
     - [x] Coversheet is appended to the auto-generated document
     - [x] Coversheet has the correct case caption, electronically filed, correct docket number, and document number, correct title, and correct served date.
     - [x] Auto-generated EA matches the format in the mockup
- [x] Service logs in Kibana reflect service was sent appropriately

*Repeat this test with a Participant that receives Paper service.



#### 3) Private Practitioner files an Entry of Appearance on a case where all Petitioners on the case receive electronic service, Option to auto generate the EA document is still available.

**Part 1**
- Log in as a Private Practitioner
- Type in the case docket number of a case where the petitioner(s) has electronic service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There are two options for filing the EA
- [x] The options are Upload PDF and auto-generate the Entry of Appearance (as per usual).

**Part 2**
- Indicate the party you are representing
- Select Auto-Generate EA radio button
- Click Review Your filing button
- Submit the document to the US Tax Court

Expected Results:
- [x] Auto-generated EA document is filed on the case as per normal (same as in the test cases above). Practitioner is associated with the case.

*Repeat this test and instead select Upload PDF.



#### 4) Regression test to ensure that Docket can QC the auto-generated doc as per normal.

- [x] This test passes



#### 5) Regression test that a Private Practitioner that files an EA cannot file and EA across a consolidated group.

- [x] This test passes - Private practitioner cannot eFile an EA across a consolidated group



**The following are regression tests for an IRS Practitioner, ensuring that they still do not have the ability to auto-generate the EA**

#### 6) IRS Practitioner files an Entry of Appearance on a case where at least one Petitioner on the case receives paper service, No option is available to auto generate the EA document.

**Part 1**
- Log in as an IRS Practitioner
- Type in the case docket number of a case where there is more than one petitioner on the case, and the petitioner receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There is only an option to upload the PDF form.
- [x] There is no option to auto-generate the Entry of Appearance.

**Part 2**
- Continue the File a document flow
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] EA document is filed on the case as per normal. IRS Practitioner is associated with the case.



#### 7) IRS Practitioner files an Entry of Appearance on a case where there is an Intervenor on the case that receives paper service, No option is available to auto generate the EA document.

**Part 1**
- Log in as an IRS Practitioner
- Type in the case docket number of a case where there is an intervenor on the case, and the intervenor receives paper service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There is only an option to upload the PDF form.
- [x] There is no option to auto-generate the Entry of Appearance.

**Part 2**
- Continue the File a document flow
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] EA document is filed on the case as per normal. IRS Practitioner is associated with the case.

*Repeat this test with a Participant that receives Paper service.



#### 8) IRS Practitioner files an Entry of Appearance on a case where all Petitioners on the case receive electronic service, Option to auto generate the EA document is available.

**Part 1**
- Log in as an IRS Practitioner
- Type in the case docket number of a case where the petitioner(s) has electronic service
- Click the file a document button
- Select Entry of Appearance as the document type

Expected Results:
- [x] There are two options for filing the EA
- [x] The options are Upload PDF and auto-generate the Entry of Appearance (as per usual).

**Part 2**
- Continue the File a document flow
- Review the filing
- Submit the document to the US Tax Court

Expected Results:
- [x] Auto-generated EA document is filed on the case as per normal. Practitioner is associated with the case.

*Repeat this test and instead select Upload PDF.

**Comment by ttlenard** [comment]
Looks good. Thanks all!

@codyseibert @nechama-krigsman @cruzjone-flexion

**Comment by ttlenard** [comment]
Looks good. Thanks all!

@codyseibert @nechama-krigsman @cruzjone-flexion
