### ISSUE TITLE
Set PDF Metadata On Court Upload

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8605]
As a Court user, so that I do not unintentionally expose document metadata to the public, I need DAWSON to blank out PDF metadata fields upon uploading a PDF.

Many Court users still use an outside product such as Microsoft Word or WordPerfect to create orders and opinions, then convert these to PDF format and upload them to DAWSON. Depending on the individual and their application, these resulting PDFs may contain information such as the author, title, or keywords supplied by the originating program or original copy of the file.

To ensure that no unintentional metadata is associated with document files issued by the court, we would like DAWSON to clear out specific fields in the metadata of the PDF file when a Court user uploads it: Document Title, Author, Author Title, Description, Description Writer, Keywords

## Acceptance Criteria
* When a Court user uploads a PDF document, the document metadata on the following fields is emptied or set to blank:
  - Document Title
  - Author
  - Author Title
  - Description
  - Description Writer
  - Keywords
* When a Court user uploads a PDF document, the document metadata on the following fields is set to the current date/time:
  - Created Date
  - Modified Date
 * Bookmarks/other data remains as is
  
## Notes
* The fields mentioned can be seen in the Description metadata properties of the PDF:
<img width="672" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW5wQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7e3710aee101bb616ae8437cb9c98f2a3a622311/image.png" alt="image.png" />

* These appear to be derived from/related to the metadata seen on the initial properties screen:
<img width="822" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2Z0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad511c9f1771f37adb123ee93e6a09c88e3a2e84/image.png" alt="image.png" />

* Properties visible in browser view by public:
<img width="396" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzd0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--27b4316fdb33e31a6485201b59707ba82d8c8d86/image.png" alt="image.png" />

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user uploads a PDF document that has metadata associated with it into DAWSON; Upon upload, metadata is blank, Document title is the document ID, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as a Court user
- Navigate to a case
- Click on the Create button
- Select PDF Upload
- Click on Choose File button and select a PDF that has metadata associated with it (document title, author, author title, Description, Description writer, Keywords)
- Input a Description and then click save
- The PDF that you uploaded will be added to the Drafts folder
- Click on View Full PDF
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)


#### 2) Docket Clerk adds the docket entry and serves the PDF document that was uploaded; metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Continuing from the previous test
- Take note of the docket number of the case that you uploaded the document in
- If you aren't already, log in as a docket clerk (CSS or CotC) and navigate to the case
- Click on the drafts tab
- Click on the document that you uploaded in the previous test
- Click on add docket entry
- Select a document type and then click save and serve
- Click Yes, Serve
- Click Done if the Petitioner received Paper service
- Click on the document title from the docket record
- Click on View Full PDF
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (or the time that you initially uploaded it)


#### 3) Court user uploads a PDF document that has bookmarks; Bookmarks remain after document upload and service.

**Part 1**
- Log in as a Docket clerk
- Navigate to a case
- Click on Create and select PDF upload
- Upload a document that has bookmarks
- Add a description and click save
- The PDF that you uploaded will be added to the Drafts folder
- Click on View Full PDF
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe

Expected Results:
- [x] The bookmarks that were in the original document remain the same

**Part 2**
- Click Add Docket Entry
- Select a document type and then click save and serve
- Click Yes, Serve
- Click Done if the Petitioner received Paper service
- Click on the document title from the docket record
- Click on View Full PDF
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe

Expected Results:
- [x] The bookmarks that were in the original document remain the same



#### 4) Court user uploads a document in the Correspondence tab; Upon upload, metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as a Court user that has access to upload correspondence
- Navigate to a case
- Click on the Correspondence tab
- Click the Add Correspondence File link
- Upload a document that has metadata in it (document title, author, author title, Description, Description writer, Keywords)
- Add in a document description
- Click Finish
- Click on the View Full PDF link for the document that you just uploaded
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 5) Docket Clerk adds a paper filing; Upon upload, metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as a Docket Clerk
- Navigate to a case
- Click on Create and then select Add Paper Filing
- Upload a document that has metadata in it (document title, author, author title, Description, Description writer, Keywords)
- From the document preview, save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [ ] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [ ] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 6) Docket Clerk Saves the Paper filing for later; The saved document's metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Continuing from the previous test
- Fill in the required fields from the Add Paper Filing screen
- Click Save for Later
- Navigate to the saved document that is now saved to the docket record (but not yet served)
- Click on the document title to view the document
- Click on View Full PDF link
- Save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 7) Docket Clerk serves the paper filing; The served document's metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as a Docket Clerk
- Navigate to a case
- Click on Create and then select Add Paper Filing
- Upload a document that has metadata in it (document title, author, author title, Description, Description writer, Keywords)
- Fill in the required fields
- Click Save and Serve
- Click Yes, Serve
- Click on the Document title from the docket record
- Click on the View Full PDF link for the document that you just uploaded
- From your browser, click on the download/save link and save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 8) Petitions Clerk starts a Petition, Uploads all documents in the petition flow; Upon upload, metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as a petitions clerk
- Click on Document QC tab
- Click on Start a Petition
- Select Upload for each document type in the Add Documents section
- Upload a document that has metadata in it (document title, author, author title, Description, Description writer, Keywords) for each document type
- Fill in the required data on the Parties, Case Info, and IRS Notice tabs
- Click Review Petition button
- Open each of the documents in the attachments card so that the document preview appears
- Click the save button on each of the documents to save to your computer
- Open each PDF in adobe
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [ ] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [ ] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 9) Petitions clerk Serves the Petition and associated documents, All of the served document's metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Continuing from the previous test
- Click on Serve to IRS
- Click Yes, Serve
- Click Done on the Print for paper service screen
- Navigate to the Case
- Open each of the PDF's that you uploaded to the case
- Click on the View Full PDF link
- Save each PDF document to your computer
- Open each PDF in adobe
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [x] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [x] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)



#### 10) Admissions clerk uploads documents for a Practitioner, Upon upload, metadata is blank, and the Created/Modified date is updated to the date that the document was initially uploaded.

- Log in as an Admissions Clerk
- Click on the Advanced link
- Click on Practitioner
- Type in the Name or a BAR number of an attorney
- Click on the Bar number to open the practitioner record
- Click on the Documentation tab
- Click on Add File link
- Upload a document that has metadata in it (document title, author, author title, Description, Description writer, Keywords) for each document type 
- Select a category for the document
- Click Add File
- Click on the File name link of the document you just uploaded
- Save the document to your computer
- Open the document in Adobe
- Click on File, and then select Properties
- Click on the Description tab and review the document metadata

Expected Results:
- [ ] **NEW FUNCTIONALITY** - All of the document metadata in the description fields (author, author title, Description, Description writer, Keywords) are blank; document title is the document ID.
- [ ] **NEW FUNCTIONALITY** - The Created/Modified date is set to today's date (the time that you uploaded it)


#### 11) Regression test uploading PDF documents that are not compliant; User should receive an error.
- [x] Encrypted
- [x] PW protected
- [x] Corrupt
- [x] Non-PDF file
- [x] Document over 250MB

**Comment by cholly75** [comment]
Hi John - uploading a PDF (sample attached) w/ metadata results in a 400 error. The console reports:

<img width="557" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c2f9b0a78ac49b41d5fcddff08d95470c747b55/image.png" alt="image.png" />

[dummy.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--33b4528389e4b65e8763c5e0e633432c531233bb/dummy.pdf)

**Comment by ttlenard** [comment]
@cruzjone-flexion @nechama-krigsman Some testing feedback:

Still seeing keywords metadata display after uploading a PDF. When viewing the document properties in the browser, there are no keywords displayed, but if you view the document properties in adobe, then the keywords DO display.

Browser - keywords do not display
<img width="815" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVZuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4009039f83b27f62f024d6f04e009205efcf1c3/image.png" alt="image.png" />


In Adobe: Keywords are still there in the metadata:
<img width="1036" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVpuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b40ccd969b3253532e9b4c5c3d7f130f4de7985e/image.png" alt="image.png" />

Here is a PDF file that has all the metadata fields that I have been testing with. It also has bookmarks:
[Doc4Jon.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWRuQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b5965387da967575e43976707dac433074b1ac84/Doc4Jon.pdf)

**Comment by ttlenard** [comment]
Some more feedback

Looks like we are able to upload corrupt PDF's without an error.  I did do some testing in the IRS environment as a comparison, and if a user attempts to upload a corrupt PDF, the user experiences a 400 error.  Right now in Test, if a user uploads a corrupt PDF, it will still load, but the file is messed up and not displaying the data appropriately.  

Here is the corrupt PDF file I was testing with.[Lubbock_corrupt.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5uQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ae72528dfd87209e56a9459867e8a8d0df1785e6/Lubbock_corrupt.pdf)

**Comment by cholly75** [comment]
Noticed that the Title field value (which is the GUID of the document when uploaded/created as a draft) is changing to a different GUID once the Signature has been applied (which will always happen for an order/opinion).
