### ISSUE TITLE
Export Custom Case Report to Excel-Friendly Format

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8606]
As a Court user, so that I can extend and repurpose DAWSON data for needs outside of DAWSON, I need to be able to export the Custom Case Report results.

Following the model used on the Pending Report, we would like to extend the Export functionality to the Custom Case Report.

## Acceptance Criteria
* User can export the Custom Case Report results into a file suitable for opening as a spreadsheet in Excel
* Column headings are included in the exported file

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
Pre refinement
- need to consider the potential large amounts of data for the case report
- backend upper limit is ~1m rows

**Comment by katiecissell** [comment]
UX Notes:
Depending on the route engineering decides to take, we may need to adjust our progress bar/messaging so we expect we will need some conversation when this is picked up and a direction is determined. 

Place the export link next to the counter of the table.
<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNm83QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--81435eb78c975953377be91dd5baa2febbae9db5/image.png" alt="image.png" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the Custom Case Report; new option to export is displayed next to the total Count.

- Log in as any Court user
- Click on Reports
- Select Custom Case Report
- Input some filters and then click Run Report

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is a new Export link (with an icon per the mockup) on the right side of the page, to the left of the results counter above the table.



#### 2) Court user clicks on the export link, computers Save/Save As folder displays (i.e. windows explorer), allowing the user to indicate where they would like to save the document.

- Continuing from the previous test
- Click on the export link

Expected Results:
- [x] **NEW FUNTIONALITY** - Windows explorer (or similar) opens.
- [x] **NEW FUNTIONALITY** - Default file name is "Custom Case Report - [Date XX_XX_XXXX]" 
- [x] **NEW FUNTIONALITY** - File type is csv or xls (dev discretion)



#### 3) Court user saves the exported Custom Case report to their computer; Opens the file; data is represented in the spreadsheet appropriately

**Part 1**
- Continuing from the previous test
- Click on the Save button

Expected Results:
- [x] **NEW FUNCTIONALITY** - Document is saved to the users computer at the location that they indicated.

**Part 2**
- User navigates to the location that they saved it on their computer
- Open the document

Expected Results:
- [x] **NEW FUNCTIONALITY** - A spreadsheet opens (dev determination on what file format it is)
- [x] **NEW FUNCTIONALITY** - Column headings from the Custom Case report page are represented in the spreadsheet
- [x] **NEW FUNCTIONALITY** - If the Calendaring High Priority column had a checkmark for a case, then the data in the spreadsheet is represented with "yes" for that row.
- [x] **NEW FUNCTIONALITY** - Formatting is such that users can sort, filter, etc. (data is represented in singular cells, cells aren't merged, etc.)
- [x] **NEW FUNCTIONALITY** - All data that was in the UI on the report is also represented in the spreadsheet (4000 Custom Case Report items in the UI = 4000 Custom Case Report items in the spreadsheet)


*Be sure to test all of the above stories with a variety of Court users, and a variety of filters to ensure that the data exports correctly


#### 4) Test the behavior if you attempt to run the custom case report w/o adding any filters (it's a lot of data), what is the user experience?

Questions for the Devs:

- If the process fails, can we have an acceptable user experience that lets them know that not all of the data was exported?
- How will the user know that not all the data made it over to the spreadsheet?

**Comment by cruzjone-flexion** [comment]
For Mac OS (have not tested other OS yet) the date in the file name seem to be changed by the browser from "/" to "_"

i.e 
expected -> "Custom Case Report - 03/13/2024.csv"
got -> "Custom Case Report - 03_13_2024.csv"

From a quick google search it seems like this is happening because "/" are used for directories/folders.
This is an Operating System issue and not code.

**Comment by ttlenard** [comment]
Some initial Testing Feedback:

1. I've noticed some differences between the UI and the CSV:
     - UI just lists the petitioner name, CSV says petitioner name followed by ",Petitioner" or ",Petitioners". (Chris said that this is NOT a priority, and it doesn't matter if this is updated or not. Ok to leave as is for now.)
     - UI has the Column Date Created, CSV says "Date Filed" (Chris would like this issue fixed)

**Comment by ttlenard** [comment]
This message was from @cruzjone-flexion. Wanted to put this in the comments of the story.

When running the Custom Case report with no filters and export the CSV file there were some records missing. We looked into it and it seems like this is a data issue. It is consistently short by 3 records in the csv file. After a lot of testing we discovered that the cases that were missing are pre 1970.

As you can see in the image below, we ran the report where the end date is January 1st, 1970 and the report says there is 3 records but the table is empty.  This explains the mismatch between the UI and our exported CSV. We will be discussing this missing data with Mike and Jim later.

Other  than that this feature is working as expected. Please let us know if there are any other issues.

We are 99% sure it is because it converts the date to Unix Time and that only goes back to January 1st 1970. So that can explain why those records are not being returned when using receivedAt as its sorting.

We might want to create a separate card/task to handle fetching records before the beginning of time (unix time)

Here are the 3 cases:
6098-69
1574-65
23947-95

**Comment by ttlenard** [comment]
@nechama-krigsman @cruzjone-flexion Issues reported earlier appear to be fixed. Thank you!  Testing passes.
