### ISSUE TITLE
Refactor all Terraform to Blue/Green + applyables folder

### ISSUE THREAD

**Issue by zachrog** [ustaxcourt/ef-cms#8678]
## Pre-Conditions
  - None

## Acceptance Criteria
 - All terraform is moved into web-api/terraform
 - We run terraform apply exclusively from within the web-api/terraform/applyables folder
 - All infrastructure is described in web-api/terraform/modules
 - UI terraform is unified into the blue green deployment system of the api
 - Remove environment specific and put it in allColors deployment
 - Move account-specific over to applyables folder
 - Create an applyable for creating terraform backend. (S3 and Dynamo)

## Pain Avoided/Frustration Saved
- UI infrastructure is can be deployed without affecting active color.
- Unified approach within the project to how infrastructure is organized and deployed.

## Complexity of Problem (Low, Medium, High) and Why it's Complex
  - High complexity for migrating UI -> blue/green as a full teardown is not acceptable because cloudfront would require a 24hr outage. Need to use a tool to migrate like: https://github.com/minamijoyo/tfmigrate

## Tasks
- [x] Account-specific deploy (https://github.com/ustaxcourt/ef-cms/pull/4906)
- [x] Environment-specific deploys (https://github.com/ustaxcourt/ef-cms/pull/4906https://github.com/ustaxcourt/ef-cms/pull/4906)
- [x] UI deploys (https://github.com/ustaxcourt/ef-cms/pull/4962)
- [x] DOD (https://github.com/ustaxcourt/ef-cms/pull/4964)
