### ISSUE TITLE
Convert Elasticsearch Judge Fields to Keywords

### ISSUE THREAD

**Issue by mark-meyer** [ustaxcourt/ef-cms#871]
Judge fields in the `efcms-docket-entry` elasticsearch index are currently mapped as text fields. This causes the judges names to be tokenized such that a name like `Maurice B. Foley` becomes individual tokens in the index `['maurice', 'b',  'foley']`. This causes search results to include other judges with shared name components like `Michael B. Thornton`.  There is no advantage to tokenizing names like this since we never need to look up all judges with middle initial `B` for first name `Maurice`. It is also less efficient to match phrases when a single keyword will do. Changing these to keyword fields will insure that each judge name will have a single exact representation in the index.  This will require, however, that all searches for judges use this exact (case-sensitive) judge name.

**Tasks:**

- [ ] Change mapping type of judges such as `judges.S` and `signedJudgeName.S` to keyword fields.
- [ ] Determine canonical naming scheme for judges.  Currently both full name and last name only appear in this field, i.e. sometimes "Maurice B. Foley" is used and sometimes only "Foley".
- [ ] Normalize judge names to canonical naming in dynamoDB
- [ ] Insure that queries from the front-end use the normalized form of the judge name.
- [ ] Insure that operation that write to dynamoDB use the normalized judge names.
- [ ] Reindex Elasticsearch index

**Comment by mmarcotte** [comment]
Related to if not the direct cause of https://github.com/flexion/ef-cms/issues/7341

**Comment by mmarcotte** [comment]
Helpful notes passed along to Flexion 7341 🥑
