### ISSUE TITLE
Remove parent/child join in Elasticsearch

### ISSUE THREAD

**Issue by mark-meyer** [ustaxcourt/ef-cms#872]
The `efcms-docket-entry` Elasticsearch index contains a parent/child relationship between cases and docket entries. This is used to allow a single representation of case-level fields (docket number, sealed state,  case caption, etc). The search query however to join this case data with advanced docket record searches creates a bottleneck and is very resource intensive. [Elasticsearch documentation warns](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/tune-for-search-speed.html#_document_modeling): 

>  "parent-child relations can make queries hundreds of times slower."

With current queries and data model, load tests showed 100% cpu use with 8.5 requests/second (approximating 40 concurrent users). Removing the join from query allowed 80 requests/second with only 60% CPU use. 

**TODO:**

- [ ] Remove the join field from the `efcms-docket-entry` index.
- [ ] Denormalize data by adjusting stream scripts to copy case level data into each docket entry so all fields required by code using this index exists directly in the docket entry documents.
- [ ] Remove custom routing (this has currently has no effect since this index only has one primary shard)
- [ ] Make necessary changes to queries to anticipate the above changes.
- [ ] Reindex the `efcms-docket-entry` index.

**Comment by mmarcotte** [comment]
related:

- https://github.com/flexion/ef-cms/pull/6866
- https://github.com/flexion/ef-cms/issues/6654

**Comment by mmarcotte** [comment]
Possibly try adjusting `refresh_interval` to `-1` during blue/green migration.

Identify the bottleneck for reindexing during a Blue/Green migration.

**Comment by mark-meyer** [comment]
Thinking a bit more about this and it seems like the fundamental issue is that we want to query over relationships in the data that have not been denormalized. For example, we want to be able to search for docket entries using the case caption as a search field. But the case caption is not on the docket entry rows.

The current solution is to create this relationship in Elasticsearch using the Parent/Child join. This works well when writing to the Elasticsearch index, but creates performance problems when searching. 

Past attempts have tried to denormalize the data in Elasticsearch as the index is written by the stream processor. This create performance problems when indexing because of the need to retrieve case data for every docket entry. 

A solution that may not have been tried is to _truly_ denormalize the data in the source of truth: DynamoDB. This would be a fairly large refactor because changes to case level fields would need to propagate to the docket entries which would store denormalized copies of the fields we need to search. It would, however, make indexing, migrating, and searching more performant. Docket entry rows could be copied directly to Elasticsearch and queried directly.

**Comment by mmarcotte** [comment]
Need to identify a path forward.
