### ISSUE TITLE
Event Code Title/Type Change: Expert Report

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8764]
As a petitioner, so that I can classify my filing as the correct kind of document, I need the RTP event code title and document type changed from "Report" to "Expert Report".

Currently we have the RTP event code labeled as "Report" available for use in DAWSON as well as the event code RPT (labeled as "Status Report"). To prevent confusion/misclassification when filing one type of report vs. another, we would like to change "Report" to "Expert Report", as the RTP event code is intended for use in filing expert reports in an evidentiary context.

## Acceptance Criteria
* RTP documents are labelled as "Expert Report" as default document type and title
* E-filing dropdown menu has "Expert Report" available for selection instead of "Report"

## Notes
* We do not need to retroactively change any filed documents already in the system
  - But if it's that OR a new event code altogether, let's retroactively change all RTPs.

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
Pre-refinement question:
- We can either retroactively change all the RTPs to 'expert report' OR create a new Expert Report document type which wouldn't effect existing report doc types.

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Petitioner files a document on a case; Document type dropdown no longer has an option for "Report".

- Log in as a petitioner that has a case
- Click on the case docket number
- Click on the File a Document button
- Click on the Ok, I'm ready to file button
- Click on the Document type dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no longer an option in the dropdown for "Report"
- [x] **NEW FUNCTIONALITY** - The Report option now displays Expert Report.
- [x] **NEW FUNCTIONALITY** - The other report option in the dropdown is "Status Report"



#### 2) Petitioner types in "RTP" and "RPT" in the Document type dropdown, appropriate document names display.

- Continuing from the previous test
- Type "RPT" and "RTP"

Expected Results:
- [x] **NEW FUNCTIONALITY** - When typing "RTP" the Document type displayed is Expert Report
- [x] **NEW FUNCTIONALITY** - When typing "RPT" the Document type displayed is Status Report



#### 3) Petitioner selects Expert Report from the Document Type dropdown; Document is titled appropriately on the workflow screens.

**Part 1**
- Continuing from the previous test
- Select Expert Report from the Document type dropdown
- Click Continue button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Document title is titled "Report" on the File your Document(s) screen.

**Part 2**
- Upload a document and click the Review filing button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title in the Your Document's card is titled "Report"



#### 4) Petitioner files a document on a case; Selects "Expert Report" and submits the document; Document on the docket record has the event code "RTP".

- Continuing from the previous test
- Check the redaction acknowledgement checkbox
- Click Submit your Filing button.

Expected Results:
- [x] User is navigated to the docket record
- [x] Green confirmation banner
- [x] **NEW FUNCTIONALITY** - After clicking on the print receipt link, the print receipt document opens in a new tab and displays the document title as "Report"
- [x] **NEW FUNCTIONALITY** - The docket record displays the document title as "Report"
- [x] Event code is RTP
- [x] The rest of the information for the filing of the document on the docket record is correct (service date, page numbers, served parties code, etc.)


#### 5) Petitioner views the Report document on the docket record, Coversheet information displays the document title correctly.

- Continuing from the previous test
- Click on the Report document link from the docket record

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document coversheet displays the document title as Report.


#### 6) Petitioner files a Motion for Leave to File, Expert Report document type is available in the dropdown picklist.

- Log in as a Petitioner that has a case
- Click on the docket number of the case
- Click on the File a Document button
- For Document type, select Motion for Leave
- Click on the document type dropdown for the "Which Document Are you Requesting Leave to File for?"

Expected Results:
- [x] **NEW FUNCTIONALITY** - There is no longer an option in the dropdown for "Report"
- [x] **NEW FUNCTIONALITY** - The Report option now displays Expert Report.
- [x] **NEW FUNCTIONALITY** - The other report option in the dropdown is "Status Report"
- [x] **NEW FUNCTIONALITY** - When typing "RTP" the Document type displayed is Expert Report
- [x] **NEW FUNCTIONALITY** - When typing "RPT" the Document type displayed is Status Report

*Repeat this test with a Motion for Leave to File out of time.



#### 7) Petitioner selects Expert Report from the secondary Document Type Dropdown, Document title is reflected appropriately on the workflow screens.

**Part 1**
- Continuing from the previous test
- Select Expert Report as the document that you are requesting leave to file for
- Click continue

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Document title is correctly titled "Motion for Leave to File Report" on the File your Document(s) screen.
- [x] **NEW FUNCTIONALITY** - The Secondary Document title is correctly titled "Report" on the File your Document(s) Screen.

**Part 2**
- Upload the two documents and indicate if there are any objections to the filing
- Click the Review filing button

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title in the Your Document(s) card is titled "Motion for Leave to File Report" and then the "Report" is the second document.

*Repeat this test with a Motion for Leave to File out of time.



#### 8) Petitioner files the Motion and the Expert report to the docket record; Document on the docket record has the event code "MISCL", with a document title of Report.

- Continuing from the previous test
- Check the redaction acknowledgement checkbox
- Click Submit your Filing button.

Expected Results:
- [x] User is navigated to the docket record
- [x] Green confirmation banner
- [x] **NEW FUNCTIONALITY** - After clicking on the print receipt link, the print receipt document opens in a new tab and displays the document titles filed as "Motion for Leave to File Report" and the secondary document is "Report".
- [x] **NEW FUNCTIONALITY** - The docket record displays the document title as "Motion for Leave to File Report" and " Report (Lodged)".
- [x] Event code for the Report is "MISCL" 
- [x] The rest of the information for the filing of the document on the docket record is correct (service date, page numbers, served parties code, etc.)

*Repeat this test with a Motion for Leave to File out of time.



#### 9) Petitioner files an Amended document and selects the Expert Report that was just filed in the previous tests; Document in the picklist is titled appropriately and can be filed to the docket record.

- Continuing from the previous test
- Click on the File a document button
- From the document type dropdown, select Amended
- Click on the dropdown arrow in the "Which document are you amending?" field

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Expert Report document that was filed on the docket record is titled as "Report" in the dropdown.

*Repeat this test with Amendment To, Redacted, Supplement, Supplemental Document types.



#### 10) Petitioner files an Amended document and selects a legacy filed Report document; Document in the picklist is titled appropriately and can be filed to the docket record.

- Continuing from the previous test
- Select report as the document you are amending 
- Select an iteration
- Click Continue

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document title on the File Your Document Screen is displayed appropriately "First Amended Report"
- [x] **NEW FUNCTIONALITY** - After uploading the document, clicking review document, the Document is titled appropriately on the Review your Filing page.
- [x] **NEW FUNCTIONALITY** - After submitting the document, the document is titled appropriately on the print receipt
- [x] **NEW FUNCTIONALITY** - After submitting the document, the document is titled appropriately on the Docket Record

*Repeat this test with Amendment To, Redacted, Supplement, Supplemental Document types.




#### 11) Repeat tests above with other external parties.

Expected Results:
- Tests above also pass with these roles:
     - [x] Private Practitioner
     - [x] IRS Practitioner
     - [x] Intervenor
     - [x] Participant



#### 12) Docket Clerk QC's the efiled Expert Reports, document title is reflected as "Report" appropriately.

- Log in as a Docket Clerk
- Click on the Document QC link
- Click on the Section Document QC link
- Find the Expert Report documents that were submitted in the previous tests

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document titles are reflected appropriately on the Document QC page
- [x] **NEW FUNCTIONALITY** - After clicking on the document link, the document title is reflected appropriately on the QC page
- [x] **NEW FUNCTIONALITY** - The Document type dropdown indicates Expert Report
- [x] **NEW FUNCTIONALITY** - Coversheet of the document displays "Report" as the title 
- [x] **NEW FUNCTIONALITY** - After completing the QC, the Green confirmation banner indicates that the report was completed
- [x] **NEW FUNCTIONALITY** - After clicking on the Processed tab, the document title is reflected correctly.

*Repeat this test and be sure that you QC the amended/amendment/etc. type documents.
*Be sure that you test with complete and complete and send message.



#### 13) Docket clerk QC's a document, edits the document type to Expert report, Document data updates appropriately.

- Continuing from the previous test
- Click on Document QC tab
- Click on the Section document QC tab
- Select any document that is NOT an expert report
- On the QC page, change the document type to Expert report

Expected Results:
- [x] **NEW FUNCTIONALITY** - The document type has the document Expert report in the dropdown 
- [x] **NEW FUNCTIONALITY** - After completing the QC, the Green confirmation banner indicates that the report was completed
- [x] **NEW FUNCTIONALITY** - After clicking on the Processed tab, the document title is reflected correctly.



#### 14) Docket Clerk edits an existing document on the docket record; Expert Report is an option in the document type picklist

- Continuing from the previous test
- Navigate to a docket record
- Click on a Edit link for a document (not an Expert report)

Expected Results:
- [x] **NEW FUNCTIONALITY** - Expert Report is available in the document type dropdown
- [x] **NEW FUNCTIONALITY** - After saving the newly categorized Expert Report document, the docket record displays the document as "Report". 



#### 15) Docket Clerk adds a paper filing to a case; Document type dropdown no longer has an option for "Report".

- Continuing from the previous test
- Navigate to a docket record
- Click on the Create button
- Select Paper filing

Expected Results:
- [x] **NEW FUNCTIONALITY** - Expert Report is available as an option in the document type dropdown
- [x] **NEW FUNCTIONALITY** - There is no longer any option available for Report.



#### 16) Docket Clerk adds a paper filing to a case; Selects "Expert Report" and adds the document to the docket record; Document on the docket record has event code "RTP".

- Continuing from the previous test
- Upload a document
- Fill in the required fields
- Click save and serve

- [x] **NEW FUNCTIONALITY** - The Report document title is reflected appropriately on the are you ready to initiate service pop up modal.
- [x] **NEW FUNCTIONALITY** - If paper service, the document includes the correct document title on the coversheet.
- [x] **NEW FUNCTIONALITY** - The document on the docket record displays the report document title correctly with an event code of RTP.

**Comment by zachrog** [comment]
In order to update "Report" to "Expert Report" we need to update the documentType on our docketEntry json. When we do this without a migration it causes old docket entries to become invalid. Chris H. says that this story is not worth a full dynamo migration at this time, however this story becomes much easier once in Postgres.

**Comment by ttlenard** [comment]
@jdr81394 

Testing Feedback:

- [x] I was testing the Postgres Trial Sessions story by editing an existing trial session and attempting to create a new trial session. I kept getting errors.  It says the "Case entity was invalid". When I tracked down the error, it points to a case and a specific docket entry. The docket entry is a RPT document. Seems like this story has potentially caused issues with cases that have existing Report documents?  Can you please look into this? I'm currently not able to create or Edit trial sessions that have cases with this document type now. Thanks!

Here are some screen grabs of the error I received:

<img width="1906" height="959" alt="Image" src="https://github.com/user-attachments/assets/8b5bdcd9-a771-434f-89a0-7803f057de82" />

<img width="1760" height="822" alt="Image" src="https://github.com/user-attachments/assets/e3897031-1695-4409-a311-3b88e05ae4cf" />

<img width="1668" height="1788" alt="Image" src="https://github.com/user-attachments/assets/30262aba-1bdf-4710-abc3-cc22b6b6872e" />
