### ISSUE TITLE
Trial Location Screen

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8773]
As a court, so that I can monitor the case load for a particular location, I need to be able to see a list of all eligible and blocked cases for a particular location. 

Currently to prepare for scheduling a trial session the necessary information must be collated from several different places in DAWSON: the eligible case list (only available after a trial session has been created for the location), the blocked cases report, the trial session planning report, and sometimes the custom case report.

We would like the Court to be able to easily navigate to a screen that provides an overview of the eligible and blocked cases report for a given location.

Future stories will include the ability to store a default address for each trial location and see that default address on this same screen, the ability to QC cases from this screen, and additional information on this screen.

## Pre-Conditions
ustaxcourt/ef-cms#8771 (maybe?)
ustaxcourt/ef-cms#8836 

## Acceptance Criteria
* Page displays cases eligible for trial and blocked for a specific trial location (see UX notes below)
* Tabs are paginated
* Eligible cases displayed for a given location displays using the same logic/ordering as currently seen on the Trial Session eligible case list today
* Blocked cases displayed for a given location displays all blocked cases for the location with a Case Status value of:
  - General Docket - Not At Issue
  - General Docket (Ready For Trial)
  - Assigned - Case
  - Assigned - Motion
* User can export case lists to downloadable CSV file

## Notes
* Intended navigation to this screen initially will be hyperlinks from the location column in ustaxcourt/ef-cms#8771 - will queue up separate story for that, not opposed to implementing these in the context of this story though
* Additional criteria may be necessary for the blocked cases displayed on this screen - Chris to follow up

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [x] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [x] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [x] Verify that language for docket record for internal users and external users is identical.
 - [x] New screens have been added to pa11y scripts.
 - [x] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [x] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [x] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [x] Interactors should validate entities before calling persistence methods.
 - [x] Code refactored for clarity and to remove any known technical debt.
 - [x] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [x] Acceptance criteria for the story has been met.
 - [x] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**
See [Figma file](https://www.figma.com/design/7bMaSunIwunaE1bO57vTYz/Trial-Session-Planning?node-id=373-15572) for mockups and comments.

- [ ] Locations have links that open a new tab

![Image](https://github.com/user-attachments/assets/dee17367-4898-4cc0-b0f4-d2cec141c69d)

___

- [ ] NEW PAGE (does not open in a new tab): Two tabs (Eligible Cases, Blocked Cases); page title is the location (City, State)
- [ ] Ability to export each table as a .csv file: Blocked Cases Report - City_State Term_yyyy.csv
Eligible Cases - City_State Term_yyyy.csv
- [ ] Eligible cases lists all cases that are eligible for trial for the location
- [ ] Blocked cases lists the blocked cases for the location
- [ ] Display empty state message

![Image](https://github.com/user-attachments/assets/6896c6b2-998f-4762-bde2-df7dbb1a6b7f)

![Image](https://github.com/user-attachments/assets/49713151-e809-4c67-b71a-13aae30c5ad9)

![Image](https://github.com/user-attachments/assets/caa6e6cf-37c6-4497-ae6d-8b4743e58e55)

**Comment by swongCO** [comment]
Pre refinement
- should we include case status for eligible cases list? <s>yes</s>
- do we need filters for blocked cases list and potentially eligible cases list if we include case status? not initially

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Case Services Supervisor user runs a trial session planning report; Trial cities on the report screen are now displayed as active hyperlinks.

- Log in as a Case Services Supervisor
- Click on Trial Sessions
- Click on the Trial Sessions Planning report link
- Select a term and year, then click Run Report

Expected Results
- **NEW FUNCTIONALITY** - Each City, State link on the page is now displayed as an active hyperlink

*Repeat this test, but access the Trial Session Planning Report via the Reports menu
- [x] This test passes



#### 2) Case Services Supervisor clicks on the City, State link; An Eligible Cases page displays for the City, State.

- Continuing from the previous test
- Take note of the total number of Eligible cases and blocked cases that display in the report for a specific City, State
- Click on the City, State link 

Expected Results:
- [x] **NEW FUNCTIONALITY** - New page displays (in the same tab)
- [x] **NEW FUNCTIONALITY** - Page has the City, State that was clicked on displayed in the Blue Header 
- [x] **NEW FUNCTIONALITY** - There is a breadcrumb link to navigate back to the Trial Session Planning report at the top of the page
- [x] **NEW FUNCTIONALITY** - There are two header tabs. Eligible Cases and Blocked Cases, each displaying the total number of cases in parenthesis after the header title.
- [x] **NEW FUNCTIONALITY** - The total number of cases in the Eligible Cases tab (in parenthesis on the header and on the table counter) matches the numbers displayed on the report.
- [x] **NEW FUNCTIONALITY** - The default tab is Eligible cases.
- [ ] **NEW FUNCTIONALITY** - If there are more than 100 cases, a paginator is displayed and works correctly.
- [x] **NEW FUNCTIONALITY** - There is an export link in the top right corner for the Eligible cases
- [x] **NEW FUNCTIONALITY** - Case docket numbers display the suffix
- [x] **NEW FUNCTIONALITY** - If a case is part of a consolidated group, the lead case/member case icons are displayed, each case is counted individually in the counters.
- [x] **NEW FUNCTIONALITY** - The cases displayed on the eligible case list are listed in the same order in priority as when a new session is calendared (marked high priority, CDP, Passport, oldest to newest, etc.)
- [ ] **NEW FUNCTIONALITY** - Clicking on the docket number link on the Eligible Cases List opens the case in a new tab.



#### 3) Case Services Supervisor clicks on the Blocked Cases Tab; Blocked cases with certain case statuses for the selected Trial location are displayed.

- Continuing from the previous test case
- Click on the Blocked Cases tab

Expected Results:
- [x] **NEW FUNCTIONALITY** - Page has the City, State that was clicked on displayed in the Blue Header 
- [x] **NEW FUNCTIONALITY** - There is a breadcrumb link to navigate back to the Trial Session Planning report at the top of the page
- [x] **NEW FUNCTIONALITY** - The total number of cases in the Blocked Cases tab (in parenthesis on the header and on the table counter) matches the numbers displayed on the report.
- [x] **NEW FUNCTIONALITY** - The Blocked Cases list only displays cases with a case status of General Docket - Not at Issue, General Docket - at issue - ready for trial, Assigned Case, and Assigned Motion.
- [ ] **NEW FUNCTIONALITY** - If there are more than 100 cases, a paginator is displayed and works correctly.
- [x] **NEW FUNCTIONALITY** - There is an export link in the top right corner for the Blocked cases
- [x] **NEW FUNCTIONALITY** - Case docket numbers display the suffix
- [x] **NEW FUNCTIONALITY** - If a case is part of a consolidated group, the lead case/member case icons are displayed, each case is counted individually in the counters.
- [x] **NEW FUNCTIONALITY** - Blocked cases display as per requirements in story ustaxcourt/ef-cms#8777 (display all cases in a group as blocked if only one/some cases have a block).
- [ ] **NEW FUNCTIONALITY** - Clicking on the docket number link on the Blocked Cases List opens the case in a new tab.



#### 4) Case Services Supervisor clicks on Export link; data is exported to a csv file.

**Part 1**
- Continuing from the previous test
- Click on the Eligible Cases header
- Click Export

Expected Results:
- [x] **NEW FUNCTIONALITY** - A pop up window displays for the user to indicate where on their device that they would like to download the csv file to
- [x] **NEW FUNCTIONALITY** - File is titled in a way that is clear what the user downloaded
- [x] **NEW FUNCTIONALITY** - After clicking save, the file is downloaded to the user's device
- [x] **NEW FUNCTIONALITY** - File can be opened successfully
- [x] **NEW FUNCTIONALITY** - Column headers match what is on the screen
- [x] **NEW FUNCTIONALITY** - Cases that are displayed in the list match the order that was displayed on the screen (if there are over 100 cases, ALL cases that are in the list are included, not just what is displayed on the screen.)
- [x] **NEW FUNCTIONALITY** - Consolidated case icons are not displayed in the csv file

**Part 2**
- Repeat this test by clicking export on the Blocked cases list

Expected Results:
- [x] Same results as in Part 1



#### 5) Case Services Supervisor clicks on the link "Back to Trial Session Planning Report"; User is navigated back appropriately.

- Continuing from the previous test
- Click on the link "Back to Trial Session Planning Report"

Expected Results:
- [x] **NEW FUNCTIONALITY** - User is navigated back to the Trial Session Planning Report that was created in test case 1.



#### 6) Case Services Supervisor Clicks on a City, State link that has 0 Eligible Cases, Messaging on the page indicates this.

- Continuing from the previous test
- Review the Eligible cases listed for the cities displayed on the Trial Session planning report screen
- Find a city that has 0 eligible cases
- Click on the City, State link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Eligible Cases header displays 0
- [x] **NEW FUNCTIONALITY** - Underneath the header, the screen displays the following text, "There are no eligible cases."
- [x] **NEW FUNCTIONALITY** - The export link is disabled.

*Repeat this test, but with a city/state that has 0 Blocked cases

- [x] Same results as above, but the text displays, "There are no blocked cases."



#### 7) Repeat tests 1-6; Opening multiple City, State links from the Screen version of the Trial Session Planning Report.

- [ ] These tests pass with different cities



#### 8) Tests 1-6 pass on Mobile

- [x] Page opens, doesn't have to be pretty, but must at least open.



#### 9) Repeat all tests with other Court users

- [ ] These tests pass

**Comment by katiecissell** [comment]
UX Feedback:

- [x] Exported reports should have the same sort as the page
- [x] The print icon on the breadcrumb should be a left arrow

**Comment by TomElliottFlexion** [comment]
As part of `eligible-for-trial-catalog` refactoring, prioritized cases will no longer ignore standard trial eligibility rules

**Comment by TomElliottFlexion** [comment]
The totality of work on this story will directly affect the following

- (New) Trial location screen loading
- Trial session planning report loading
- Eligible cases on trial session details loading
- Setting calendar on trial session using eligible cases

**Comment by cholly75** [comment]
Note: Cannot be deployed prior to Case postgres migration.

**Comment by ttlenard** [comment]
Testing Feedback @TomElliottFlexion 

- [x] Found an issue with the paginator

- Click on the city, state link for a city that has more than 100 eligible cases, it will display a paginator.  
- Click on page 2 of the paginator, for example
- Next, click on the "Go back to Trial Session Planning Report" link
- Click on the city, state link for a different city that has more than 100 eligible cases.  It will automatically display page 2 of the paginator, rather than page 1. This should always default to the first page.
- Next, click on the "Go back to Trial Session Planning Report" link
- Click on the city, state link for a city that has more than 200 eligible cases (ex: Atlanta), and click on page 3, 4, or 5.
- Next, click on the "Go back to Trial Session Planning Report" link
- Click on the City, state link for a city that has more than 100 eligible cases, but less than 200.
- Notice that the page says "There are not eligible cases" (See screen grab). This should default to first page.

![Image](https://github.com/user-attachments/assets/0746a68e-226b-4c0d-b617-78442152a167)

**Comment by ttlenard** [comment]
Testing Feedback @TomElliottFlexion 

- [x]  Test Case 2 and 3 indicate that if you click on the docket number of a case in either the blocked cases list or Eligible cases list, then it will open in a new tab, but currently if you click on the docket number link it opens in the same tab.
