### ISSUE TITLE
Blocked Cases Report - Improvements

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8774]
As a case services user, so that I can focus the results of the Blocked Cases report to address blocking issues, I need additional filter options and a way to export the report.

UX in conversation with the Case Services group has identified some improvements to be made that will improve the usability of the Blocked Cases report.

The addition of two filters (Case Status and Reason) along with the ability to export the results of the report to a CSV file will help the person viewing the report to focus their results and work offline to track progress over time for a particular location.

## Acceptance Criteria
* New filter added to Blocked Cases report: Case Status
  - Selecting the Case Status filter will only display cases with the selected Case Status
  - Values in Case Status filter derived from existing values displayed on report
  - Filter can be cleared/set to All
* New filter added to Blocked Cases report: Reason
  - Selecting the Reason filter will only display cases with the selected Reason
  - Values in Reason filter derived from existing values displayed on report
  - Filter can be cleared/set to All
* Case Status and Reason filters are only active after a Location has been selected
* Case Status and Reason filters default to All/unselected
  - Case Status and Reason filters are reset/cleared to All/unselected if the Trial Location or Case Type selection is changed
* Export Link added to report - downloads report results as a CSV file to the user
  - CSV is titled "Blocked Cases Report - [City_State] [MM_DD_YYYY].csv"

## Notes
* Crazy number of items to show up on this report for any given location: 1000

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by swongCO** [comment]
**UX Notes**
See [Figma file](https://www.figma.com/design/7bMaSunIwunaE1bO57vTYz/Trial-Session-Planning?node-id=358-11864) for mockup and comments.

- [ ] Add two filters "Case status" and "Reason" under existing filters
- [ ] <s>Dropdown values for each filter will be determined by the trial location selected</s>
- [ ] <s>Dropdown values for "Case status" and "Reason" are contextual based on the selection for "Case type"</s>
- [ ] <s>Dropdown values for "Reason" is contextual based on the selection for "Case status" and vice versa</s>
- [ ] Dropdown values will be listed in alphabetical order
- [ ] Add "Export" link - export table as a .csv file

<img width="994" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNThvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcf0807121753459b7dccff418d1e2aa4d5d8fac/v.3%20Blocked%20Cases%20Enhancements.jpg" alt="v.3 Blocked Cases Enhancements.jpg" />

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Court user accesses the blocked cases report; Two additional filters and an export link are now available.

- Log in to DAWSON as any Court user
- Click on Reports
- Select Blocked Cases Report
- Review the page

Expected Results:
- [x] **NEW FUNCTIONALITY** - There are now two additional filters: Case status and Reason
- [x] **NEW FUNCTIONALITY** - Case Status and Reason are greyed out, and the user is unable to make a selection until a Trial Location is selected. 
- [x] **NEW FUNCTIONALITY** - There is now a link to export the data at the top of the table, but it is greyed out



#### 2) Court user selects a place of trial; Case Status and Reason Filters activate; Export link activates; data in the dropdowns is based on the data available for that city and is alphabetized.

**Part 1**
- Continuing from the previous test
- Select a trial location from the filter

Expected Results:
- [x] **NEW FUNCTIONALITY** - Case Status and Reason filters activate and data can be selected from the dropdowns
- [x] **NEW FUNCTIONALITY** - The Export link activates 

**Part 2**
- Click on the Case Status Dropdown and then the Reason Dropdown and review the picklist 

Expected Results: 
- [x] **NEW FUNCTIONALITY** - Case Status and Reason filters are defaulted to All
- [x] **NEW FUNCTIONALITY** - Data in the Case status dropdown is populated based off of values that are present in the table for that location.  For example, if there are no cases in Submitted status that are blocked for that trial location, Submitted will not be available in the Case status dropdown.
- [x] **NEW FUNCTIONALITY** - Data in the Reason dropdown is populated based off of values that are present in the table for that location.  For example, if there are no cases with a reason of Due date that are blocked for that trial location, Due Date will not be available in the Reason dropdown.
- [x] **NEW FUNCTIONALITY** - Picklist options in both the Case Status and Reason dropdowns have All as the first item, and the list is alphabetized after "All".



#### 3) Court User makes some filter selections; Data in the table filters appropriately based off of the selections made.

**Part 1**
- Continuing from the previous test
- Select a Case status from the filter

Expected Results:
- [x] **NEW FUNCTIONALITY** - The blocked cases that are displayed in the table filter appropriately

**Part 2**
- Select a Reason from the filter

Expected Results:
- [x] **NEW FUNCTIONALITY** - The blocked cases that are displayed in the table filter appropriately

*Note - If in the above test, there is only one reason (ex: all cases filtered are blocked due to a pending item), the picklist will only show 1 value of Pending item in the reason filter.



#### 4) Repeat Test cases 1-3 with different cities/different filters to ensure data populates in the table and filters appropriately.

- [x] This test passes



#### 5) Court use exports the filtered Deadlines Report; Data in the csv file reflects what was displayed on the screen.

**Part 1**
- Continuing from the previous tests
- Be sure that you selected a City, State that has data, and be sure to filter it by making selections in the filters
- Click on the Export link

Expected Results:
- [x] **NEW FUNCTIONALITY** - Windows Explorer (or similar depending on your device) will display for the user to select the location on their device to save the report
- [x] **NEW FUNCTIONALITY** - Report is titled "Blocked Cases Report - [City_State] [MM_DD_YYYY].csv"

**Part 2**
- Save the file to a location on your computer
- Open the file 
- Review the spreadsheet

Expected Results:
- [x] **NEW FUNCTIONALITY** - Data in the table is the same as what was displayed in the UI (data is filtered appropriately)
- [x] **NEW FUNCTIONALITY** - Column headers match what is in the UI

*Repeat the tests above, making sure to filter/Not filter and then export the data. 

- [x] **NEW FUNCTIONALITY** - Data in the CSV always matches what is displayed in the UI.


#### 6) Repeat all of the tests above with all Court user roles

- [x] ADC
- [x] Admissions Clerks
- [x] Chambers Administrator
- [x] Floater
- [x] Docket Clerk
- [x] General User
- [x] Petitions Clerk
- [x] Reporters Office
- [x] Trial Clerk
- [x] Judge
- [x] Clerk of the Court
- [x] Case Services Supervisor

**Comment by mwestereng1** [comment]
For cases that are manually blocked, the reason in the dropdown should be "Manual Block" and confirmed with court staff 8/22/24
- "Manual Block" simplifies the dropdown. Large variety of reasons could make for a busy dropdown. 
- The reason is manually entered by a user. If the reason is the same between two cases, but there is a text or character discrepancy, that reason will appear twice in the dropdown

<img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0I4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4c1f2a57ee6441f69df40162d0f48a9fbeac1dd/image.png" alt="image.png" />

**Comment by katiecissell** [comment]
To confirm with Chris when he returns:
1.  Options show up in dropdown list even if there is no instance of that occurring. Is there a strong reason for us to hide options that do not have anything in them? Currently we do not hide.
2. Case type, status and reason should reset when location is changed. Is there actually a need for type to reset status and reason?

**Comment by cholly75** [comment]
1. The feedback has been positive around the same kind of methodology used in filtering messages (only providing values that actually exists to be filtered by). Why would we want to filter for values that aren't present? Plus, the status menu has a _lot_ of options, let's not make them wade through a menu any longer than it has to be.
2. We shouldn't assume that the next location being worked will have any cases of the selected type/status/reason; we don't want to risk someone thinking that a location has no blocked cases simply because they forgot to reset the filters.

**Comment by swongCO** [comment]
- UX notes updated to include additional contextual filtering
- Awaiting feedback on whether a Case type filter selection change should clear the two filters below it (Chris will reach out to Deborah)

**Comment by cholly75** [comment]
Confirmed w/ case services - they do want the Status and Reason filters reset when change is made to the Type filter as well.

**Comment by swongCO** [comment]
Test feedback

<s>Reason dropdown is displaying options that do not exist. </s> Clarified with Chris - options should persist from initial location selection.

Example 1 - Honolulu is showing multiple options when there is only one for calendared cases
<img width="1835" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEtRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8e6018986cbafe0d00433c6c703e3d9c982a9bb/Screenshot%202024-08-27%20at%202.22.10%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 2.22.10 PM.png" />

Example 2 - Atlanta is showing Manual Block when there is none
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE9RQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d950bd61f7340e88fe881dfe5556fabd9b1801cd/Screenshot%202024-08-27%20at%202.13.53%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 2.13.53 PM.png" />

**Comment by cholly75** [comment]
One last change to this story:

Replace all empty table messaging with: "There are no blocked cases for this set of critieria." This message can be displayed in all cases where there are no results displayed on this report.

**Comment by ttlenard** [comment]
@cruzjone-flexion @zachrog 

Testing Feedback: While testing the functionality with different Court users, I noticed something. Not sure if this matters or not.  Please advise.

1. Log in as any Court user
2. Navigate to the Blocked cases report 
3. Select a trial location and run the report, taking note of which city and selections you have filtered
4. log out
5. Log back in as a different Court user
6. Navigate to the Blocked cases report
7. Notice that the same criteria that you used for the previous user is still present

Note: I tested a few other things to check if the behavior above happens in other scenarios.

1. If you log in as user 1, run the report, log out, shift + refresh, and then log in as user 2, the criteria no longer "sticks" for user 2.
2. If you log in as user 1 on computer 1, log out, and then log in as user 2 on computer 2, the criteria doesn't "stick" for user 2 on computer 2.

**Comment by ttlenard** [comment]
@cruzjone-flexion @zachrog

Some additional testing feedback. Not sure if it is related to this story or not? Please advise: 

I noticed today that the Reports menu has extra spacing between the picklist items on TEST

TEST:
<img width="1211" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13c73c48c66fe3450cc92a4972e8f3b371d2a9b2/image.png" alt="image.png" />

Staging:
<img width="1130" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3VzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83443e1497c956f406ce067052ef84ba304eaf10/image.png" alt="image.png" />

**Comment by mwestereng1** [comment]
On added comment, can you right align the "Export" button with the line beneath and the edge of the table?

<img width="766" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN210Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d67f35bd7952188d91384ea19b809c8072510792/image.png" alt="image.png" />
