### ISSUE TITLE
Trial Sessions Page: Public View

### ISSUE THREAD

**Issue by cholly75** [ustaxcourt/ef-cms#8797]
As a member of the public, so that I can easily see what trial sessions are upcoming, I need a public view of the calendared Trial Sessions.

Currently, the Court maintains a web page populated with PDF files to inform the public of scheduled trial sessions. Since this information can become outdated over time and require re-publishing new files when a change is made and since the Trial Sessions in DAWSON are always up to date, we would like a public-facing version of the Trial Sessions page to be made available in place of the current web page.

Note that this story and ustaxcourt/ef-cms#8798 should be released together; a feature flag may be necessary to facilitate separate deployments for each.

## Acceptance Criteria
* Page is accessible to public facing (i.e., non-logged in user) w/ a unique URL
* Page title is "Scheduled Trial Sessions"
* Page displays all currently Open trial sessions **only**
* Page retains current format of internal view of Trial Sessions page with the following exceptions:
  - Tabs/Views removed: all (not needed since we only display Open sessions here)
  - Columns removed: Est. End Date, Notice Issued
  - Icons removed: 30-day NOTT reminder clock
  - Links removed: Trial Session Planning Report
* Page retains Location, Proceeding Type, Session Type, Judge filters
* Location links direct user to public view of Session Info Page (see ustaxcourt/ef-cms#8797)
* List of Open Trial Sessions on page matches list of Open Trial Sessions on internal view at all times
* Text addition to page: "Information on this page is current as of [current mm/dd/yy 12:00 AM Eastern]"

## Story Definition of Ready (updated on 12/23/22)
The following criteria must be met in order for the user story to be picked up by the Flexion development team.
The user story must: 
- [ ] Is framed in business/user need, the value has been addressed.
- [ ] Includes acceptance criteria
- [ ] Has been refined
- [ ] Pre conditions have been satisfied. 

**Process:** 
Flexion developers and designers will test if the story meets acceptance criteria and test cases in Flexion dev and staging environments (“standard testing”). If additional acceptance criteria or testing scenarios are discovered while the story is in progress, a new story should be created, added to the backlog and prioritized by the product owner. 

## Definition of Done (Updated 5-19-22)
**Product Owner**
 - [ ]  Acceptance criteria have been met and validated on the Court's migration environment
 - [ ] Add scenario to testing document, if applicable (https://docs.google.com/spreadsheets/d/1FUHKC_YrT-PosaWD5gRVmsDzI1HS_U-8CyMIb-qX9EA/edit?usp=sharing)

**UX**
 - [ ] Business test scenarios have been refined to meet all acceptance criteria 
 - [ ] Usability has been validated
 - [ ] Wiki has been updated (if applicable) 
 - [ ] Story has been tested on a mobile device (for external users only)

**Engineering**
 - [ ] Automated test scripts have been written, including visual tests for newly added PDFs.
 - [ ] Field level and page level validation errors (front-end and server-side) integrated and functioning.
 - [ ] Verify that language for docket record for internal users and external users is identical.
 - [ ] New screens have been added to pa11y scripts.
 - [ ] All new functionality verified to work with keyboard and macOS voiceover https://www.apple.com/voiceover/info/guide/_1124.html.
 - [ ] READMEs, other appropriate docs, and swagger/APIs fully updated.
 - [ ] UI should be touch optimized and responsive for external only (functions on supported mobile devices and optimized for screen sizes as required).
 - [ ] Interactors should validate entities before calling persistence methods.
 - [ ] Code refactored for clarity and to remove any known technical debt.
 - [ ] If new docket entries have been added as seed data to `efcms-local.json`, 3 local s3 files corresponding to that docketEntryId have been added to `web-api/storage/fixtures/s3/noop-documents-local-us-east-1`
 - [ ] Acceptance criteria for the story has been met.
 - [ ] If there are special instructions in order to deploy into the next environment, add them as a comment in the story.
 - [ ] If the work completed for the story requires a reindex without a migration, or any other special deploy steps, apply these changes to the following flexion branches:
   - [ ] experimental1
   - [ ] experimental2
   - [ ] experimental3
   - [ ] experimental4
   - [ ] experimental5
   - [ ] experimental6
   - [ ] develop
 - [ ] Reviewed by UX on a deployed environment.
 - [ ] Reviewed by PO on a deployed environment. Can be deployed to the Court's `test` environment if prod-like data is required. Otherwise deployed to any `experimental` environment.
 - [ ] Deployed to the Court's `staging` environment.

**Comment by katiecissell** [comment]
UX Notes:

[Figma file](https://www.figma.com/design/VD71xuva6ACC1OSF7kXVRx/USTC-%7C-10460%2C10461-%7C-Public-Trial-Sessions?node-id=133-334&t=KrycPoFqGgtZjf50-1)

![Image](https://github.com/user-attachments/assets/734e3100-519c-4c62-9c91-eb575fb1a006)

<img src="https://github.com/user-attachments/assets/8ca4896c-c96c-485c-9332-449e233f9ed3" width="300">

<img src="https://github.com/user-attachments/assets/1b6035d8-bf7e-4b62-bf03-eb6163b8407a" width="300" align=top>

___
<img src="https://github.com/user-attachments/assets/d19ec1d2-1198-4766-ad38-5b7f242da726" width="300">

<img src="https://github.com/user-attachments/assets/a3373417-1bf6-44eb-91a8-e6dc1d242377" width="300" align=top>

___
Known issues:

- Accessibility issue with the combo-box component: in mobile devices when VoiceOver or Talkback is on, the dropdown options are not selectable
- <s>Date field format hint text: add spoken text when screen reader is on and the field is onfocus</s>
- Blue selection pills have added padding on iOS (confirmed on iPhone 15 and iPad Air 4th gen); on android, they're fine
<img src="https://github.com/user-attachments/assets/4649272c-f989-43b0-a621-43b4dc817615" width="300">

**Comment by ttlenard** [comment]
## Test Cases

#### 1) Public user can now accesses the new Scheduled Trial Sessions Page; page loads and matches the mockup.

- As a public non-logged in user, access the URL for the new Scheduled Trial Sessions Page (URL to be determined by devs.)
- Review the page

Expected Results:
- [x] **NEW FUNCTIONALITY** - Welcome to DAWSON/Log in, and Create Account links in normal location
- [x] **NEW FUNCTIONALITY** - Page title is Scheduled Trial Sessions
- [x] **NEW FUNCTIONALITY** - Text below the page title matches the mockup, but is today's date and time (in eastern time zone)
- [x] **NEW FUNCTIONALITY** - Proceeding type radio button has All selected by default
- [x] **NEW FUNCTIONALITY** - There is a card for Remote Proceedings, links open appropriately (in the same tab)
- [x] **NEW FUNCTIONALITY** - Session type, Location, and Judge are all optional filters, nothing selected by default
- [x] **NEW FUNCTIONALITY** - Reset filters link is disabled
- [x] **NEW FUNCTIONALITY** - Table data below the filters displays all open trial sessions (see mock for column names)
- [x] **NEW FUNCTIONALITY** - The city/state displays as a link (dev discretion on if the links are active or not for this story (see associated story ustaxcourt/ef-cms#8798)
- [x] **NEW FUNCTIONALITY** - If a session is a swing session, hover over tip displays "Swing session: will be held in two cities."



#### 2) Public user applies filters; results list displays the correct data based on the filters selected.

**Part 1**
- Continuing from the previous test
- Change the proceeding type to In Person

Expected Results:
- [x] **NEW Functionality** - Results list of scheduled trial sessions filters appropriately to display only sessions that are in Person
- [x] **NEW Functionality** - No Remote sessions are displayed in the results
- [x] **NEW FUNCTIONALITY** - The Reset Filters link activates
- [x] **NEW Functionality** - Clicking Reset filters link clears the filters, refreshes the results, and sets the proceeding type radio button back to the default of All

*Repeat this test but instead choose Remote

**Part 2**
- Continuing from the above
- Select the In Person radio button
- Select one or more session types from the dropdown

Expected Results:
- [x] **NEW FUNCTIONALITY** - The Session type selections that you selected will display underneath the dropdown in a blue pill container.
- [x] **NEW FUNCTIONALITY** - Accessibility - These blue pill containers can be selected using a keyboard, and can be removed by using the keyboard only
- [x] **NEW Functionality** - Results list of scheduled trial sessions filters appropriately to display only sessions that are in Person and with the Session type filters that you applied.
- [x] **NEW Functionality** - No Remote sessions are displayed in the results, and neither are any of the session types that you did not select.
- [x] **NEW FUNCTIONALITY** - The Reset Filters link activates
- [x] **NEW Functionality** - Clicking Reset filters link clears the filters, refreshes the results, and sets the proceeding type radio button back to the default of All

*Repeat this test, but add in additional filters for Location and Judge



#### 3) Public user applies multiple filters; results list displays correct data; User manually removes some of the filters by clicking on the "x" in the pill; results list refreshes with the updated filters

- Public user accesses the Scheduled Trial Sessions Page
- Select multiple filters for Session type/Location/Judge
- Click Apply Filters
- Results list should update
- Manually click on the "x" in one of the pill containers 

Expected Results:
- [x] Results list refreshes with the updated list based off of the filter that you just removed

*Repeat this test by removing multiple filters by clicking on the x in the pill container. Results list will update each time a filter is removed.
*If you add a new filter to the list, you must click apply filters for the new filter added to "take"



#### 4) Repeat the tests above on a mobile device

- [x] Tests pass on iOS
- [ ] Tests pass on Android
- [ ] Clicking on the swing session icon displays the hover text appropriately on mobile.
- [x] Mobile design matches mockups

**Comment by swongCO** [comment]
### UX test feedback (desktop)

- [x] Add a period to the end of the sentence
- [x] Increase spacing between radios to 32px
- [x] Add spinning loader when Reset Filters is clicked
- [x] Reduce spacing between Reset Filters and table counter
- [x] Reduce spacing above and below paginator (can match spacing in feedback above)
- [x] Table counter should display total results, not per page
- [x] Table counter font weight: label = semibold; number = regular
- [x] Dropdowns should stack at smaller breakpoints - see Custom Case Report
- [x] Swing session icon hover tip: "Swing session: will be held in two cities"
- [x] Adjust spacing of swing session icon in its column - match internal trial session view

![Image](https://github.com/user-attachments/assets/ca1fa4cb-8df6-4af3-8baf-c9f26e25e70b)
![Image](https://github.com/user-attachments/assets/9a701f60-e931-4b2f-919c-e28bf171274c)
![Image](https://github.com/user-attachments/assets/07a0ef54-869b-4723-be0b-ab2ad595c6c3)
![Image](https://github.com/user-attachments/assets/ac5421f7-9bfe-4e48-901c-2c6e4acfd347)

Internal view icon:
![Image](https://github.com/user-attachments/assets/486861d2-9b87-4567-bbe4-23428f8bcd1c)

Public view icon:
![Image](https://github.com/user-attachments/assets/a6936c86-f566-4fd0-8bc1-deb861c4ce10)

**Comment by swongCO** [comment]
### Test feedback for Remote Proceedings card

- [x] Reduce width of horizontal divider
- [x] Reduce height of card

![Image](https://github.com/user-attachments/assets/26974ff9-5d22-4f60-846d-d8028c206c3c)

**Comment by swongCO** [comment]
### Test feedback (mobile)

- [x] Swing session icon is missing next to location
- [x] Add empty state message
- [x] Increase the width of the dropdown filters to match the card and table
- [x] Adjust spacing as indicated in screenshots (if fixing the desktop view addresses this, disregard)

<img src="https://github.com/user-attachments/assets/7d5a7c1f-dadb-46ec-972a-2cd321b28674" width="300">

<img src="https://github.com/user-attachments/assets/22a10c3b-f3fd-4cdc-a6ce-3d22065ed945" width="300">

- [x] <img src="https://github.com/user-attachments/assets/601e1d0f-cac0-4469-bdaa-041b67b31040" width="300" align=top>

- [x] <img src="https://github.com/user-attachments/assets/ac67b0c1-852f-4964-b09b-06a7f2305fc1" width="300" align=top>

- [x] <img src="https://github.com/user-attachments/assets/f5a7d6c3-2dc4-477b-8c1e-4a5a0748c6e3" width="300" align=top>

**Comment by swongCO** [comment]
### Accessibility feedback
Items flagged by WAVE Evaluation Tool and manual testing:
- there are two H1s (Welcome to Dawson and Scheduled Trial Sessions)
- H3 is not on desktop (goes from H2 Remote Proceedings to H4 Week of…) but there is H3 on mobile (filters accordion)
- no label for hidden icon column
- swing session icon is not keyboard navigable and hover tip is not read by VoiceOver
- combo box picklist is not selectable in mobile with VO/Talkback on

___
- [x] Hidden icon column - add text for screen readers "Swing session icon"
- [x] Enable swing session icon and hover tip to be keyboard navigable
- [x] Enable label and hover tip for swing session icon to be read by screen readers
- [x] Timebox: enable combo box picklist to be selectable in mobile with VoiceOver/Talkback on (discuss options at the end of timebox)

**Comment by swongCO** [comment]
### UX feedback

- [x] There is more spacing than previous between the pill and the filter, which impacts the spacing when the browser window width is reduced
![Image](https://github.com/user-attachments/assets/fce12e57-cb42-4c5c-9838-200255a839e4)
![Image](https://github.com/user-attachments/assets/e6380961-1bcf-4d7a-a1bb-21ef342f15d9)

- [x] Remote proceedings links should open in the same tab
- [x] Remote proceedings card should be positioned above the filters (instead of below) when the browser window width is reduced, like it is in mobile view
- [x] Mobile - add "Week of" in header row before the date

**Comment by swongCO** [comment]
### UX feedback

- [x] Remove H1 from welcome text and make it a div
- [x] Reduce font size of welcome text to 26px to match font size on log in page

**Comment by ttlenard** [comment]
Some initial Testing feedback: @cruzjone-flexion @nechama-krigsman 

- [x] Looks like standalone remote is not present as a filter in the Location dropdown.  Please add Standalone remote as the first option in the Location dropdown to match the internal view. Thanks! 

![Image](https://github.com/user-attachments/assets/2a15eac0-ebb1-448a-810d-c6767019f1d3)

**Comment by ttlenard** [comment]
Testing Feedback @cruzjone-flexion @nechama-krigsman 

Everything looks good, with the exception of the swing session icon not being able to be clicked/hovered on mobile. @swongCO mentioned that there is a design debt card to address this. Once I have the story number for that Design Debt item, I will add it to this comment

UPDATE: Design Debt ticket is ustaxcourt/ef-cms#8874
